# Classic ML Baselines

This notebook runs the classic baseline grid and creates two analysis tables:

- `total_results`: all evaluated combinations.
- `report_results`: the best validation result per representation family.

The task predicts sentiment labels `0..4` for mixed English/German product reviews. The validation score is `1 - MAE / 4`.

The grid contains a majority baseline; sparse BoW/TF-IDF word/character features with Logistic Regression, Linear SVM, Ridge Classifier, and Complement NB; and optional static embedding features with Logistic Regression, Linear SVM, and Ridge Classifier.

In [1]:
from datetime import datetime
from pathlib import Path
import subprocess
import sys

import pandas as pd

EXPERIMENT_KIND = "DENSE_EMBEDDING_EXPERIMENTS"
RUN_ID = datetime.now().strftime("%Y%m%d_%H%M%S")
EXPERIMENT_DIR = Path("experiments/classic_ml") / f"{RUN_ID}_{EXPERIMENT_KIND}"
EMBEDDING_DIR = Path("experiments/embeddings")
EXPERIMENT_DIR.mkdir(parents=True, exist_ok=True)
EMBEDDING_DIR.mkdir(parents=True, exist_ok=True)

TRAIN_PATH = Path("data/train.csv")
VALIDATION_SIZE = 0.1
RANDOM_STATE = 42
MAX_FEATURES = 250_000
MAX_ITER = 100

embedding_paths = {
    "glove": EMBEDDING_DIR / "glove.6B.300d.txt",
    "fasttext": EMBEDDING_DIR / "fasttext.vec",
}

available_embeddings = {
    name: path for name, path in embedding_paths.items() if path.exists()
}
available_embeddings

{'glove': PosixPath('experiments/embeddings/glove.6B.300d.txt'),
 'fasttext': PosixPath('experiments/embeddings/fasttext.vec')}

This notebook is configured to run only dense static-embedding experiments. Place optional pretrained static embeddings in `experiments/embeddings/` with the filenames configured above.

In [2]:
if not available_embeddings:
    raise FileNotFoundError("No embedding files found in experiments/embeddings/. Run load_embeddings.ipynb first.")

mode = "embeddings"

cmd = [
    sys.executable,
    "-m",
    "baselines.classic_ml_baselines",
    "--mode",
    mode,
    "--train-path",
    str(TRAIN_PATH),
    "--output-dir",
    str(EXPERIMENT_DIR),
    "--validation-size",
    str(VALIDATION_SIZE),
    "--random-state",
    str(RANDOM_STATE),
    "--max-features",
    str(MAX_FEATURES),
    "--max-iter",
    str(MAX_ITER),
]

for name, path in available_embeddings.items():
    cmd.extend([f"--{name}-path", str(path)])

print(" ".join(cmd))
subprocess.run(cmd, check=True)

/cluster/courses/cil/envs/envs/text-5060/bin/python -m baselines.classic_ml_baselines --mode embeddings --train-path data/train.csv --output-dir experiments/classic_ml/20260517_183650_DENSE_EMBEDDING_EXPERIMENTS --validation-size 0.1 --random-state 42 --max-features 250000 --max-iter 100 --glove-path experiments/embeddings/glove.6B.300d.txt --fasttext-path experiments/embeddings/fasttext.vec

Train examples: 226800
Validation examples: 25200
Class counts: {0: 45360, 1: 45360, 2: 45360, 3: 45360, 4: 45360}
[job] majority__most_frequent | jobs_run: 1/33
[ok] majority__most_frequent: score=0.50000 mae=2.00000 acc=0.20000 macro_f1=0.06667
[job] glove__average__features | jobs_run: 2/33

[job] glove__average__logreg | jobs_run: 3/33

/cluster/courses/cil/envs/envs/text-5060/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] glove__average__logreg: score=0.79871 mae=0.80516 acc=0.45615 macro_f1=0.44942
[job] glove__average__linear_svm | jobs_run: 4/33

[ok] glove__average__linear_svm: score=0.79437 mae=0.82254 acc=0.46464 macro_f1=0.44435
[job] glove__average__ridge_classifier | jobs_run: 5/33

[ok] glove__average__ridge_classifier: score=0.79064 mae=0.83742 acc=0.46052 macro_f1=0.44009
[job] glove__tfidf_weighted__features | jobs_run: 6/33

[job] glove__tfidf_weighted__logreg | jobs_run: 7/33

/cluster/courses/cil/envs/envs/text-5060/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] glove__tfidf_weighted__logreg: score=0.78523 mae=0.85909 acc=0.43758 macro_f1=0.43078
[job] glove__tfidf_weighted__linear_svm | jobs_run: 8/33

[ok] glove__tfidf_weighted__linear_svm: score=0.77630 mae=0.89480 acc=0.44024 macro_f1=0.41888
[job] glove__tfidf_weighted__ridge_classifier | jobs_run: 9/33

[ok] glove__tfidf_weighted__ridge_classifier: score=0.77320 mae=0.90718 acc=0.43567 macro_f1=0.41405
[job] glove__mean_max__features | jobs_run: 10/33

[job] glove__mean_max__logreg | jobs_run: 11/33

/cluster/courses/cil/envs/envs/text-5060/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] glove__mean_max__logreg: score=0.78936 mae=0.84258 acc=0.44556 macro_f1=0.44010
[job] glove__mean_max__linear_svm | jobs_run: 12/33

[ok] glove__mean_max__linear_svm: score=0.79588 mae=0.81647 acc=0.46722 macro_f1=0.44972
[job] glove__mean_max__ridge_classifier | jobs_run: 13/33

[ok] glove__mean_max__ridge_classifier: score=0.78935 mae=0.84262 acc=0.45937 macro_f1=0.44241
[job] glove__sif__features | jobs_run: 14/33

[job] glove__sif__logreg | jobs_run: 15/33

/cluster/courses/cil/envs/envs/text-5060/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] glove__sif__logreg: score=0.77383 mae=0.90468 acc=0.42770 macro_f1=0.41954
[job] glove__sif__linear_svm | jobs_run: 16/33

[ok] glove__sif__linear_svm: score=0.76384 mae=0.94464 acc=0.42603 macro_f1=0.40486
[job] glove__sif__ridge_classifier | jobs_run: 17/33

[ok] glove__sif__ridge_classifier: score=0.76270 mae=0.94921 acc=0.42603 macro_f1=0.40449
[job] fasttext__average__features | jobs_run: 18/33

[job] fasttext__average__logreg | jobs_run: 19/33

/cluster/courses/cil/envs/envs/text-5060/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] fasttext__average__logreg: score=0.81801 mae=0.72798 acc=0.48933 macro_f1=0.48443
[job] fasttext__average__linear_svm | jobs_run: 20/33

[ok] fasttext__average__linear_svm: score=0.81158 mae=0.75369 acc=0.49397 macro_f1=0.47723
[job] fasttext__average__ridge_classifier | jobs_run: 21/33

[ok] fasttext__average__ridge_classifier: score=0.80833 mae=0.76667 acc=0.48821 macro_f1=0.47089
[job] fasttext__tfidf_weighted__features | jobs_run: 22/33

[job] fasttext__tfidf_weighted__logreg | jobs_run: 23/33

/cluster/courses/cil/envs/envs/text-5060/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] fasttext__tfidf_weighted__logreg: score=0.80083 mae=0.79667 acc=0.46528 macro_f1=0.45929
[job] fasttext__tfidf_weighted__linear_svm | jobs_run: 24/33

[ok] fasttext__tfidf_weighted__linear_svm: score=0.79105 mae=0.83579 acc=0.46583 macro_f1=0.44765
[job] fasttext__tfidf_weighted__ridge_classifier | jobs_run: 25/33

[ok] fasttext__tfidf_weighted__ridge_classifier: score=0.78900 mae=0.84401 acc=0.46369 macro_f1=0.44479
[job] fasttext__mean_max__features | jobs_run: 26/33

[job] fasttext__mean_max__logreg | jobs_run: 27/33

/cluster/courses/cil/envs/envs/text-5060/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] fasttext__mean_max__logreg: score=0.80633 mae=0.77468 acc=0.47738 macro_f1=0.47129
[job] fasttext__mean_max__linear_svm | jobs_run: 28/33

[ok] fasttext__mean_max__linear_svm: score=0.81748 mae=0.73008 acc=0.50464 macro_f1=0.48954
[job] fasttext__mean_max__ridge_classifier | jobs_run: 29/33

[ok] fasttext__mean_max__ridge_classifier: score=0.81104 mae=0.75583 acc=0.49591 macro_f1=0.48098
[job] fasttext__sif__features | jobs_run: 30/33

[job] fasttext__sif__logreg | jobs_run: 31/33

/cluster/courses/cil/envs/envs/text-5060/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] fasttext__sif__logreg: score=0.79493 mae=0.82028 acc=0.46040 macro_f1=0.45505
[job] fasttext__sif__linear_svm | jobs_run: 32/33

[ok] fasttext__sif__linear_svm: score=0.78495 mae=0.86020 acc=0.46036 macro_f1=0.44283
[job] fasttext__sif__ridge_classifier | jobs_run: 33/33

[ok] fasttext__sif__ridge_classifier: score=0.78267 mae=0.86933 acc=0.45722 macro_f1=0.43908
Wrote experiments/classic_ml/20260517_183650_DENSE_EMBEDDING_EXPERIMENTS/classic_ml_results.csv
Wrote experiments/classic_ml/20260517_183650_DENSE_EMBEDDING_EXPERIMENTS/classic_ml_best_by_family.csv

CompletedProcess(args=['/cluster/courses/cil/envs/envs/text-5060/bin/python', '-m', 'baselines.classic_ml_baselines', '--mode', 'embeddings', '--train-path', 'data/train.csv', '--output-dir', 'experiments/classic_ml/20260517_183650_DENSE_EMBEDDING_EXPERIMENTS', '--validation-size', '0.1', '--random-state', '42', '--max-features', '250000', '--max-iter', '100', '--glove-path', 'experiments/embeddings/glove.6B.300d.txt', '--fasttext-path', 'experiments/embeddings/fasttext.vec'], returncode=0)

## Total Analysis

In [3]:
results = pd.read_csv(EXPERIMENT_DIR / "classic_ml_results.csv")

total_results = results.sort_values(
    ["status", "cil_score"], ascending=[False, False]
).reset_index(drop=True)
total_results.to_csv(EXPERIMENT_DIR / "total_analysis.csv", index=False)
total_results

,experiment,family,representation,variant,classifier,status,train_seconds,predict_seconds,accuracy,macro_f1,mae,cil_score,quadratic_weighted_kappa,notes
0,fasttext__average__logreg,fasttext,fasttext average,average,logreg,ok,32.013341,0.051845,0.489325,0.484434,0.727976,0.818006,0.681885,feature_seconds=98.08; vocab_cov=0.8222; token...
1,fasttext__mean_max__linear_svm,fasttext,fasttext mean_max,mean_max,linear_svm,ok,214.385197,0.072041,0.504643,0.489537,0.730079,0.817480,0.686796,feature_seconds=102.63; vocab_cov=0.8222; toke...
2,fasttext__average__linear_svm,fasttext,fasttext average,average,linear_svm,ok,121.492976,0.055609,0.493968,0.477233,0.753690,0.811577,0.675158,feature_seconds=98.08; vocab_cov=0.8222; token...
3,fasttext__mean_max__ridge_classifier,fasttext,fasttext mean_max,mean_max,ridge_classifier,ok,1.982565,0.029813,0.495913,0.480976,0.755833,0.811042,0.667846,feature_seconds=102.63; vocab_cov=0.8222; toke...
4,fasttext__average__ridge_classifier,fasttext,fasttext average,average,ridge_classifier,ok,0.838506,0.015227,0.488214,0.470886,0.766667,0.808333,0.666875,feature_seconds=98.08; vocab_cov=0.8222; token...
5,fasttext__mean_max__logreg,fasttext,fasttext mean_max,mean_max,logreg,ok,53.054653,0.070347,0.477381,0.471295,0.774683,0.806329,0.649109,feature_seconds=102.63; vocab_cov=0.8222; toke...
6,fasttext__tfidf_weighted__logreg,fasttext,fasttext tfidf_weighted,tfidf_weighted,logreg,ok,32.017375,0.048267,0.465278,0.459293,0.796667,0.800833,0.637394,feature_seconds=102.53; vocab_cov=0.8222; toke...
7,glove__average__logreg,glove,glove average,average,logreg,ok,30.471465,0.049681,0.456151,0.449424,0.805159,0.798710,0.636024,feature_seconds=44.69; vocab_cov=0.3329; token...
8,glove__mean_max__linear_svm,glove,glove mean_max,mean_max,linear_svm,ok,338.907535,0.115289,0.467222,0.449720,0.816468,0.795883,0.638414,feature_seconds=44.60; vocab_cov=0.3329; token...
9,fasttext__sif__logreg,fasttext,fasttext sif,sif,logreg,ok,30.660883,0.038150,0.460397,0.455054,0.820278,0.794931,0.616699,feature_seconds=103.28; vocab_cov=0.8222; toke...
10,glove__average__linear_svm,glove,glove average,average,linear_svm,ok,204.489259,0.045964,0.464643,0.444353,0.822540,0.794365,0.638241,feature_seconds=44.69; vocab_cov=0.3329; token...
11,fasttext__tfidf_weighted__linear_svm,fasttext,fasttext tfidf_weighted,tfidf_weighted,linear_svm,ok,91.763823,0.048679,0.465833,0.447652,0.835794,0.791052,0.622626,feature_seconds=102.53; vocab_cov=0.8222; toke...
12,glove__average__ridge_classifier,glove,glove average,average,ridge_classifier,ok,0.902734,0.020388,0.460516,0.440090,0.837421,0.790645,0.627818,feature_seconds=44.69; vocab_cov=0.3329; token...
13,glove__mean_max__logreg,glove,glove mean_max,mean_max,logreg,ok,52.442593,0.092788,0.445556,0.440099,0.842579,0.789355,0.606164,feature_seconds=44.60; vocab_cov=0.3329; token...
14,glove__mean_max__ridge_classifier,glove,glove mean_max,mean_max,ridge_classifier,ok,1.903293,0.030662,0.459365,0.442412,0.842619,0.789345,0.619158,feature_seconds=44.60; vocab_cov=0.3329; token...
15,fasttext__tfidf_weighted__ridge_classifier,fasttext,fasttext tfidf_weighted,tfidf_weighted,ridge_classifier,ok,0.876357,0.015375,0.463690,0.444793,0.844008,0.788998,0.617430,feature_seconds=102.53; vocab_cov=0.8222; toke...
16,glove__tfidf_weighted__logreg,glove,glove tfidf_weighted,tfidf_weighted,logreg,ok,32.740038,0.046205,0.437579,0.430777,0.859087,0.785228,0.599644,feature_seconds=45.12; vocab_cov=0.3329; token...
17,fasttext__sif__linear_svm,fasttext,fasttext sif,sif,linear_svm,ok,81.370726,0.040485,0.460357,0.442829,0.860198,0.784950,0.603633,feature_seconds=103.28; vocab_cov=0.8222; toke...
18,fasttext__sif__ridge_classifier,fasttext,fasttext sif,sif,ridge_classifier,ok,0.828436,0.015339,0.457222,0.439080,0.869325,0.782669,0.598148,feature_seconds=103.28; vocab_cov=0.8222; toke...
19,glove__tfidf_weighted__linear_svm,glove,glove tfidf_weighted,tfidf_weighted,linear_svm,ok,186.116883,0.082147,0.440238,0.418882,0.894802,0.776300,0.593176,feature_seconds=45.12; vocab_cov=0.3329; token...
20,glove__sif__logreg,glove,glove sif,sif,logreg,ok,30.873860,0.049436,0.427698,0.419542,0.904683,0.773829,0.566080,feature_seconds=51.42; vocab_cov=0.3329; token...
21,glove__tfidf_weighted__ridge_classifier,glove,glove tfidf_weighted,tfidf_weighted,ridge_classifier,ok,0.940615,0.019011,0.435675,0.414048,0.907183,0.773204,0.586081,feature_seconds=45.12; vocab_cov=0.3329; token...
22,glove__sif__linear_svm,glove,glove sif,sif,linear_svm,ok,155.795403,0.053494,0.426032,0.404865,0.944643,0.763839,0.559340,feature_seconds=51.42; vocab_cov=0.3329; token...
23,glove__sif__ridge_classifier,glove,glove sif,sif,ridge_classifier,ok,0.911074,0.022605,0.426032,0.404488,0.949206,0.762698,0.555671,feature_seconds=51.42; vocab_cov=0.3329; token...
24,majority__most_frequent,majority,constant,most_frequent,dummy_most_frequent,ok,0.008669,0.000209,0.200000,0.066667,2.000000,0.500000,0.000000,Always predicts the most frequent training label.

## Report Analysis

In [4]:
ok_results = results[results["status"] == "ok"].copy()
report_results = (
    ok_results.sort_values("cil_score", ascending=False)
    .groupby("family", as_index=False)
    .first()
    .sort_values("cil_score", ascending=False)
    .reset_index(drop=True)
)
report_results.to_csv(EXPERIMENT_DIR / "report_analysis.csv", index=False)
report_results

,family,experiment,representation,variant,classifier,status,train_seconds,predict_seconds,accuracy,macro_f1,mae,cil_score,quadratic_weighted_kappa,notes
0,fasttext,fasttext__average__logreg,fasttext average,average,logreg,ok,32.013341,0.051845,0.489325,0.484434,0.727976,0.818006,0.681885,feature_seconds=98.08; vocab_cov=0.8222; token...
1,glove,glove__average__logreg,glove average,average,logreg,ok,30.471465,0.049681,0.456151,0.449424,0.805159,0.798710,0.636024,feature_seconds=44.69; vocab_cov=0.3329; token...
2,majority,majority__most_frequent,constant,most_frequent,dummy_most_frequent,ok,0.008669,0.000209,0.200000,0.066667,2.000000,0.500000,0.000000,Always predicts the most frequent training label.