# Classic ML Baselines

This notebook runs the classic baseline grid and creates two analysis tables:

- `total_results`: all evaluated combinations.
- `report_results`: the best validation result per representation family.

In [1]:
from pathlib import Path
import subprocess
import sys

import pandas as pd

EXPERIMENT_DIR = Path("experiments/classic_ml")
EMBEDDING_DIR = Path("experiments/embeddings")
EXPERIMENT_DIR.mkdir(parents=True, exist_ok=True)
EMBEDDING_DIR.mkdir(parents=True, exist_ok=True)

TRAIN_PATH = Path("data/train.csv")
VALIDATION_SIZE = 0.1
RANDOM_STATE = 42
MAX_FEATURES = 100_000
MAX_ITER = 100
#Todo: Change MAX_ITER to at least 100 - maybe 1000 and run again

embedding_paths = {
    "glove": EMBEDDING_DIR / "glove.6B.300d.txt",
    "fasttext": EMBEDDING_DIR / "fasttext.vec",
}

available_embeddings = {
    name: path for name, path in embedding_paths.items() if path.exists()
}
available_embeddings

{'glove': PosixPath('experiments/embeddings/glove.6B.300d.txt'),
 'fasttext': PosixPath('experiments/embeddings/fasttext.vec')}

Place optional pretrained static embeddings in `experiments/embeddings/` with the filenames configured above. If no embedding files are present, the notebook runs the sparse baselines only.

In [2]:
mode = "all" if available_embeddings else "sparse"

cmd = [
    sys.executable,
    "-m",
    "baselines.classic_ml_baselines",
    "--mode",
    mode,
    "--train-path",
    str(TRAIN_PATH),
    "--output-dir",
    str(EXPERIMENT_DIR),
    "--validation-size",
    str(VALIDATION_SIZE),
    "--random-state",
    str(RANDOM_STATE),
    "--max-features",
    str(MAX_FEATURES),
    "--max-iter",
    str(MAX_ITER),
]

for name, path in available_embeddings.items():
    cmd.extend([f"--{name}-path", str(path)])

print(" ".join(cmd))
subprocess.run(cmd, check=True)

/cluster/courses/cil/envs/envs/text-classification/bin/python -m baselines.classic_ml_baselines --mode all --train-path data/train.csv --output-dir experiments/classic_ml --validation-size 0.1 --random-state 42 --max-features 100000 --max-iter 100 --glove-path experiments/embeddings/glove.6B.300d.txt --fasttext-path experiments/embeddings/fasttext.vec
Train examples: 226800
Validation examples: 25200
Class counts: {0: 45360, 1: 45360, 2: 45360, 3: 45360, 4: 45360}
[job] majority__most_frequent | jobs_run: 1/33
[ok] majority__most_frequent: score=0.50000 mae=2.00000 acc=0.20000 macro_f1=0.06667
[job] bow__word_1_1__logreg | jobs_run: 2/33

/cluster/courses/cil/envs/envs/text-classification/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] bow__word_1_1__logreg: score=0.86338 mae=0.54647 acc=0.56905 macro_f1=0.56475
[job] bow__word_1_1__complement_nb | jobs_run: 3/33
[ok] bow__word_1_1__complement_nb: score=0.83695 mae=0.65218 acc=0.53603 macro_f1=0.51529
[job] bow__word_1_2__logreg | jobs_run: 4/33

/cluster/courses/cil/envs/envs/text-classification/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] bow__word_1_2__logreg: score=0.86810 mae=0.52762 acc=0.57063 macro_f1=0.56954
[job] bow__word_1_2__complement_nb | jobs_run: 5/33
[ok] bow__word_1_2__complement_nb: score=0.85435 mae=0.58262 acc=0.56964 macro_f1=0.55068
[job] bow__word_1_3__logreg | jobs_run: 6/33

/cluster/courses/cil/envs/envs/text-classification/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] bow__word_1_3__logreg: score=0.86611 mae=0.53556 acc=0.56829 macro_f1=0.56623
[job] bow__word_1_3__complement_nb | jobs_run: 7/33
[ok] bow__word_1_3__complement_nb: score=0.85398 mae=0.58409 acc=0.56933 macro_f1=0.55105
[job] tfidf_word__word_1_1__logreg | jobs_run: 8/33

/cluster/courses/cil/envs/envs/text-classification/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] tfidf_word__word_1_1__logreg: score=0.86777 mae=0.52893 acc=0.58056 macro_f1=0.57780
[job] tfidf_word__word_1_1__complement_nb | jobs_run: 9/33
[ok] tfidf_word__word_1_1__complement_nb: score=0.83597 mae=0.65611 acc=0.53313 macro_f1=0.51292
[job] tfidf_word__word_1_2__logreg | jobs_run: 10/33

/cluster/courses/cil/envs/envs/text-classification/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] tfidf_word__word_1_2__logreg: score=0.87277 mae=0.50893 acc=0.59060 macro_f1=0.58806
[job] tfidf_word__word_1_2__complement_nb | jobs_run: 11/33
[ok] tfidf_word__word_1_2__complement_nb: score=0.85624 mae=0.57504 acc=0.57139 macro_f1=0.55276
[job] tfidf_word__word_1_3__logreg | jobs_run: 12/33

/cluster/courses/cil/envs/envs/text-classification/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] tfidf_word__word_1_3__logreg: score=0.87447 mae=0.50210 acc=0.59210 macro_f1=0.58985
[job] tfidf_word__word_1_3__complement_nb | jobs_run: 13/33
[ok] tfidf_word__word_1_3__complement_nb: score=0.85530 mae=0.57881 acc=0.56861 macro_f1=0.55046
[job] tfidf_char__char_wb_3_5__logreg | jobs_run: 14/33

/cluster/courses/cil/envs/envs/text-classification/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] tfidf_char__char_wb_3_5__logreg: score=0.86789 mae=0.52845 acc=0.58107 macro_f1=0.57678
[job] tfidf_char__char_wb_3_5__complement_nb | jobs_run: 15/33
[ok] tfidf_char__char_wb_3_5__complement_nb: score=0.83343 mae=0.66627 acc=0.53679 macro_f1=0.51510
[job] tfidf_char__char_wb_3_6__logreg | jobs_run: 16/33

/cluster/courses/cil/envs/envs/text-classification/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] tfidf_char__char_wb_3_6__logreg: score=0.86977 mae=0.52091 acc=0.58464 macro_f1=0.58184
[job] tfidf_char__char_wb_3_6__complement_nb | jobs_run: 17/33
[ok] tfidf_char__char_wb_3_6__complement_nb: score=0.83294 mae=0.66825 acc=0.53516 macro_f1=0.51272
[job] glove__average__features | jobs_run: 18/33
[job] glove__average__logreg | jobs_run: 19/33

/cluster/courses/cil/envs/envs/text-classification/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] glove__average__logreg: score=0.79869 mae=0.80524 acc=0.45611 macro_f1=0.44938
[job] glove__tfidf_weighted__features | jobs_run: 20/33
[job] glove__tfidf_weighted__logreg | jobs_run: 21/33

/cluster/courses/cil/envs/envs/text-classification/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] glove__tfidf_weighted__logreg: score=0.78523 mae=0.85909 acc=0.43758 macro_f1=0.43078
[job] glove__mean_max__features | jobs_run: 22/33
[job] glove__mean_max__logreg | jobs_run: 23/33

/cluster/courses/cil/envs/envs/text-classification/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] glove__mean_max__logreg: score=0.78936 mae=0.84258 acc=0.44556 macro_f1=0.44010
[job] glove__sif__features | jobs_run: 24/33
[job] glove__sif__logreg | jobs_run: 25/33

/cluster/courses/cil/envs/envs/text-classification/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] glove__sif__logreg: score=0.77382 mae=0.90472 acc=0.42766 macro_f1=0.41951
[job] fasttext__average__features | jobs_run: 26/33
[job] fasttext__average__logreg | jobs_run: 27/33

/cluster/courses/cil/envs/envs/text-classification/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] fasttext__average__logreg: score=0.81801 mae=0.72798 acc=0.48933 macro_f1=0.48444
[job] fasttext__tfidf_weighted__features | jobs_run: 28/33
[job] fasttext__tfidf_weighted__logreg | jobs_run: 29/33

/cluster/courses/cil/envs/envs/text-classification/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] fasttext__tfidf_weighted__logreg: score=0.80083 mae=0.79667 acc=0.46528 macro_f1=0.45929
[job] fasttext__mean_max__features | jobs_run: 30/33
[job] fasttext__mean_max__logreg | jobs_run: 31/33

/cluster/courses/cil/envs/envs/text-classification/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] fasttext__mean_max__logreg: score=0.80633 mae=0.77468 acc=0.47738 macro_f1=0.47129
[job] fasttext__sif__features | jobs_run: 32/33
[job] fasttext__sif__logreg | jobs_run: 33/33

/cluster/courses/cil/envs/envs/text-classification/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] fasttext__sif__logreg: score=0.79493 mae=0.82028 acc=0.46040 macro_f1=0.45505
Wrote experiments/classic_ml/classic_ml_results.csv
Wrote experiments/classic_ml/classic_ml_best_by_family.csv

CompletedProcess(args=['/cluster/courses/cil/envs/envs/text-classification/bin/python', '-m', 'baselines.classic_ml_baselines', '--mode', 'all', '--train-path', 'data/train.csv', '--output-dir', 'experiments/classic_ml', '--validation-size', '0.1', '--random-state', '42', '--max-features', '100000', '--max-iter', '100', '--glove-path', 'experiments/embeddings/glove.6B.300d.txt', '--fasttext-path', 'experiments/embeddings/fasttext.vec'], returncode=0)

## Total Analysis

In [3]:
results = pd.read_csv(EXPERIMENT_DIR / "classic_ml_results.csv")
metric_columns = [
    "cil_score",
    "mae",
    "accuracy",
    "macro_f1",
    "quadratic_weighted_kappa",
]

total_results = results.sort_values(
    ["status", "cil_score"], ascending=[False, False]
).reset_index(drop=True)
total_results.to_csv(EXPERIMENT_DIR / "total_analysis.csv", index=False)
total_results

,experiment,family,representation,variant,classifier,status,train_seconds,predict_seconds,accuracy,macro_f1,mae,cil_score,quadratic_weighted_kappa,notes
0,tfidf_word__word_1_3__logreg,tfidf_word,"word n-grams=(1, 3)",word_1_3,logreg,ok,104.110521,3.111074,0.592103,0.589850,0.502103,0.874474,0.818131,NaN
1,tfidf_word__word_1_2__logreg,tfidf_word,"word n-grams=(1, 2)",word_1_2,logreg,ok,60.459653,2.156135,0.590595,0.588056,0.508929,0.872768,0.812681,NaN
2,tfidf_char__char_wb_3_6__logreg,tfidf_char,"char_wb n-grams=(3, 6)",char_wb_3_6,logreg,ok,237.339754,9.298223,0.584643,0.581842,0.520913,0.869772,0.806598,NaN
3,bow__word_1_2__logreg,bow,"word n-grams=(1, 2)",word_1_2,logreg,ok,60.479222,2.352276,0.570635,0.569541,0.527619,0.868095,0.808753,NaN
4,tfidf_char__char_wb_3_5__logreg,tfidf_char,"char_wb n-grams=(3, 5)",char_wb_3_5,logreg,ok,212.482959,7.896952,0.581071,0.576779,0.528452,0.867887,0.803520,NaN
5,tfidf_word__word_1_1__logreg,tfidf_word,"word n-grams=(1, 1)",word_1_1,logreg,ok,32.698813,1.302801,0.580556,0.577797,0.528929,0.867768,0.801860,NaN
6,bow__word_1_3__logreg,bow,"word n-grams=(1, 3)",word_1_3,logreg,ok,100.579952,2.944685,0.568294,0.566229,0.535556,0.866111,0.804957,NaN
7,bow__word_1_1__logreg,bow,"word n-grams=(1, 1)",word_1_1,logreg,ok,31.777767,1.260918,0.569048,0.564749,0.546468,0.863383,0.795801,NaN
8,tfidf_word__word_1_2__complement_nb,tfidf_word,"word n-grams=(1, 2)",word_1_2,complement_nb,ok,32.600356,2.108132,0.571389,0.552762,0.575040,0.856240,0.787303,NaN
9,tfidf_word__word_1_3__complement_nb,tfidf_word,"word n-grams=(1, 3)",word_1_3,complement_nb,ok,66.288002,2.722399,0.568611,0.550458,0.578810,0.855298,0.784619,NaN
10,bow__word_1_2__complement_nb,bow,"word n-grams=(1, 2)",word_1_2,complement_nb,ok,30.924107,2.085439,0.569643,0.550679,0.582619,0.854345,0.782520,NaN
11,bow__word_1_3__complement_nb,bow,"word n-grams=(1, 3)",word_1_3,complement_nb,ok,67.852611,2.702104,0.569325,0.551048,0.584087,0.853978,0.779825,NaN
12,bow__word_1_1__complement_nb,bow,"word n-grams=(1, 1)",word_1_1,complement_nb,ok,11.752771,1.270232,0.536032,0.515292,0.652183,0.836954,0.745023,NaN
13,tfidf_word__word_1_1__complement_nb,tfidf_word,"word n-grams=(1, 1)",word_1_1,complement_nb,ok,11.461023,1.245757,0.533135,0.512916,0.656111,0.835972,0.742501,NaN
14,tfidf_char__char_wb_3_5__complement_nb,tfidf_char,"char_wb n-grams=(3, 5)",char_wb_3_5,complement_nb,ok,77.223748,7.995738,0.536786,0.515100,0.666270,0.833433,0.733119,NaN
15,tfidf_char__char_wb_3_6__complement_nb,tfidf_char,"char_wb n-grams=(3, 6)",char_wb_3_6,complement_nb,ok,90.467984,9.406812,0.535159,0.512725,0.668254,0.832937,0.732697,NaN
16,fasttext__average__logreg,fasttext,fasttext average,average,logreg,ok,28.789498,0.078383,0.489325,0.484444,0.727976,0.818006,0.681866,feature_seconds=111.21; vocab_cov=0.8222; toke...
17,fasttext__mean_max__logreg,fasttext,fasttext mean_max,mean_max,logreg,ok,48.499025,0.073476,0.477381,0.471295,0.774683,0.806329,0.649109,feature_seconds=104.37; vocab_cov=0.8222; toke...
18,fasttext__tfidf_weighted__logreg,fasttext,fasttext tfidf_weighted,tfidf_weighted,logreg,ok,26.629335,0.047492,0.465278,0.459293,0.796667,0.800833,0.637394,feature_seconds=108.62; vocab_cov=0.8222; toke...
19,glove__average__logreg,glove,glove average,average,logreg,ok,25.865019,0.047466,0.456111,0.449377,0.805238,0.798690,0.636000,feature_seconds=56.28; vocab_cov=0.3329; token...
20,fasttext__sif__logreg,fasttext,fasttext sif,sif,logreg,ok,26.661123,0.030664,0.460397,0.455054,0.820278,0.794931,0.616699,feature_seconds=116.11; vocab_cov=0.8222; toke...
21,glove__mean_max__logreg,glove,glove mean_max,mean_max,logreg,ok,51.085435,0.096424,0.445556,0.440099,0.842579,0.789355,0.606164,feature_seconds=51.42; vocab_cov=0.3329; token...
22,glove__tfidf_weighted__logreg,glove,glove tfidf_weighted,tfidf_weighted,logreg,ok,26.524405,0.058372,0.437579,0.430777,0.859087,0.785228,0.599644,feature_seconds=53.04; vocab_cov=0.3329; token...
23,glove__sif__logreg,glove,glove sif,sif,logreg,ok,28.244787,0.060379,0.427659,0.419509,0.904722,0.773819,0.566059,feature_seconds=64.99; vocab_cov=0.3329; token...
24,majority__most_frequent,majority,constant,most_frequent,dummy_most_frequent,ok,0.009505,0.000238,0.200000,0.066667,2.000000,0.500000,0.000000,Always predicts the most frequent training label.

## Report Analysis

In [4]:
ok_results = results[results["status"] == "ok"].copy()
report_results = (
    ok_results.sort_values("cil_score", ascending=False)
    .groupby("family", as_index=False)
    .first()
)

report_columns = [
    "family",
    "representation",
    "variant",
    "classifier",
    "cil_score",
    "mae",
    "accuracy",
    "macro_f1",
    "quadratic_weighted_kappa",
    "train_seconds",
]
report_results = report_results[report_columns].sort_values(
    "cil_score", ascending=False
).reset_index(drop=True)
report_results.to_csv(EXPERIMENT_DIR / "report_analysis.csv", index=False)
report_results

,family,representation,variant,classifier,cil_score,mae,accuracy,macro_f1,quadratic_weighted_kappa,train_seconds
0,tfidf_word,"word n-grams=(1, 3)",word_1_3,logreg,0.874474,0.502103,0.592103,0.589850,0.818131,104.110521
1,tfidf_char,"char_wb n-grams=(3, 6)",char_wb_3_6,logreg,0.869772,0.520913,0.584643,0.581842,0.806598,237.339754
2,bow,"word n-grams=(1, 2)",word_1_2,logreg,0.868095,0.527619,0.570635,0.569541,0.808753,60.479222
3,fasttext,fasttext average,average,logreg,0.818006,0.727976,0.489325,0.484444,0.681866,28.789498
4,glove,glove average,average,logreg,0.798690,0.805238,0.456111,0.449377,0.636000,25.865019
5,majority,constant,most_frequent,dummy_most_frequent,0.500000,2.000000,0.200000,0.066667,0.000000,0.009505