# Classic ML Baselines

This notebook runs the final classic baseline grid across multiple random seeds and creates analysis tables:

- `total_results`: all evaluated combinations across all seeds.
- `per_seed_report_results`: the best validation result per seed and representation family.
- `report_results`: mean/std validation metrics across seeds.

The task predicts sentiment labels `0..4` for mixed English/German product reviews. The validation score is `1 - MAE / 4`.

The final grid contains a majority baseline; sparse BoW/TF-IDF word/character features with Logistic Regression, Linear SVM, Ridge Classifier, and Complement NB; and static embedding features with average, TF-IDF weighted, and mean+max pooling trained with Logistic Regression, Linear SVM, and Ridge Classifier.

In [1]:
from datetime import datetime
from pathlib import Path
import subprocess
import sys

import pandas as pd

EXPERIMENT_KIND = "CLASSIC_ML_BASELINES"
RUN_ID = datetime.now().strftime("%Y%m%d_%H%M%S")
EXPERIMENT_DIR = Path("experiments/classic_ml") / f"{RUN_ID}_{EXPERIMENT_KIND}"
EMBEDDING_DIR = Path("experiments/embeddings")
EXPERIMENT_DIR.mkdir(parents=True, exist_ok=True)
EMBEDDING_DIR.mkdir(parents=True, exist_ok=True)

TRAIN_PATH = Path("data/train.csv")
VALIDATION_SIZE = 0.1
SEEDS = [42, 43, 44]
MAX_FEATURES = 250_000
MAX_ITER = 100

embedding_paths = {
    "glove": EMBEDDING_DIR / "glove.6B.300d.txt",
    "fasttext": EMBEDDING_DIR / "fasttext.vec",
}

available_embeddings = {
    name: path for name, path in embedding_paths.items() if path.exists()
}
EXPERIMENT_DIR, SEEDS, available_embeddings

(PosixPath('experiments/classic_ml/20260524_100658_CLASSIC_ML_BASELINES'),
 [42, 43, 44],
 {'glove': PosixPath('experiments/embeddings/glove.6B.300d.txt'),
  'fasttext': PosixPath('experiments/embeddings/fasttext.vec')})

This notebook is configured for the final classic run: sparse lexical baselines plus dense static-embedding baselines for every seed. Place pretrained static embeddings in `experiments/embeddings/` with the filenames configured above.

In [2]:
if not available_embeddings:
    raise FileNotFoundError("No embedding files found in experiments/embeddings/. Run load_embeddings.ipynb first.")

completed_runs = []
mode = "all"

for seed in SEEDS:
    seed_dir = EXPERIMENT_DIR / f"seed_{seed}"
    seed_dir.mkdir(parents=True, exist_ok=True)
    cmd = [
        sys.executable,
        "-m",
        "baselines.classic_ml_baselines",
        "--mode",
        mode,
        "--train-path",
        str(TRAIN_PATH),
        "--output-dir",
        str(seed_dir),
        "--validation-size",
        str(VALIDATION_SIZE),
        "--random-state",
        str(seed),
        "--max-features",
        str(MAX_FEATURES),
        "--max-iter",
        str(MAX_ITER),
    ]
    for name, path in available_embeddings.items():
        cmd.extend([f"--{name}-path", str(path)])

    print(" ".join(cmd))
    subprocess.run(cmd, check=True)
    completed_runs.append({"seed": seed, "run_dir": seed_dir})

completed_runs

/cluster/courses/cil/envs/envs/text-5060/bin/python -m baselines.classic_ml_baselines --mode all --train-path data/train.csv --output-dir experiments/classic_ml/20260524_100658_CLASSIC_ML_BASELINES/seed_42 --validation-size 0.1 --random-state 42 --max-features 250000 --max-iter 100 --glove-path experiments/embeddings/glove.6B.300d.txt --fasttext-path experiments/embeddings/fasttext.vec

Train examples: 226800
Validation examples: 25200
Class counts: {0: 45360, 1: 45360, 2: 45360, 3: 45360, 4: 45360}
[job] majority__most_frequent | jobs_run: 1/40
[ok] majority__most_frequent: score=0.50000 mae=2.00000 acc=0.20000 macro_f1=0.06667
[job] bow__word_1_3__features | jobs_run: 2/40

[job] bow__word_1_3__logreg | jobs_run: 3/40

/cluster/courses/cil/envs/envs/text-5060/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] bow__word_1_3__logreg: score=0.86758 mae=0.52968 acc=0.56897 macro_f1=0.56825
[job] bow__word_1_3__linear_svm | jobs_run: 4/40

/cluster/courses/cil/envs/envs/text-5060/lib/python3.14/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[ok] bow__word_1_3__linear_svm: score=0.83943 mae=0.64226 acc=0.51544 macro_f1=0.51428
[job] bow__word_1_3__ridge_classifier | jobs_run: 5/40

[ok] bow__word_1_3__ridge_classifier: score=0.80551 mae=0.77798 acc=0.46774 macro_f1=0.46544
[job] bow__word_1_3__complement_nb | jobs_run: 6/40

[ok] bow__word_1_3__complement_nb: score=0.85586 mae=0.57655 acc=0.56845 macro_f1=0.55095
[job] tfidf_word__word_1_3__features | jobs_run: 7/40

[job] tfidf_word__word_1_3__logreg | jobs_run: 8/40

/cluster/courses/cil/envs/envs/text-5060/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] tfidf_word__word_1_3__logreg: score=0.87465 mae=0.50139 acc=0.59560 macro_f1=0.59284
[job] tfidf_word__word_1_3__linear_svm | jobs_run: 9/40

[ok] tfidf_word__word_1_3__linear_svm: score=0.86125 mae=0.55500 acc=0.56171 macro_f1=0.55798
[job] tfidf_word__word_1_3__ridge_classifier | jobs_run: 10/40

[ok] tfidf_word__word_1_3__ridge_classifier: score=0.86332 mae=0.54671 acc=0.56877 macro_f1=0.56306
[job] tfidf_word__word_1_3__complement_nb | jobs_run: 11/40

[ok] tfidf_word__word_1_3__complement_nb: score=0.85838 mae=0.56647 acc=0.57103 macro_f1=0.55378
[job] tfidf_char__char_wb_3_6__features | jobs_run: 12/40

[job] tfidf_char__char_wb_3_6__logreg | jobs_run: 13/40

/cluster/courses/cil/envs/envs/text-5060/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] tfidf_char__char_wb_3_6__logreg: score=0.86928 mae=0.52290 acc=0.58385 macro_f1=0.58040
[job] tfidf_char__char_wb_3_6__linear_svm | jobs_run: 14/40

[ok] tfidf_char__char_wb_3_6__linear_svm: score=0.85653 mae=0.57389 acc=0.55536 macro_f1=0.54935
[job] tfidf_char__char_wb_3_6__ridge_classifier | jobs_run: 15/40

[ok] tfidf_char__char_wb_3_6__ridge_classifier: score=0.85778 mae=0.56889 acc=0.56083 macro_f1=0.55255
[job] tfidf_char__char_wb_3_6__complement_nb | jobs_run: 16/40

[ok] tfidf_char__char_wb_3_6__complement_nb: score=0.83369 mae=0.66524 acc=0.53504 macro_f1=0.51359
[job] glove__average__features | jobs_run: 17/40

[job] glove__average__logreg | jobs_run: 18/40

/cluster/courses/cil/envs/envs/text-5060/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] glove__average__logreg: score=0.79871 mae=0.80516 acc=0.45615 macro_f1=0.44942
[job] glove__average__linear_svm | jobs_run: 19/40

[ok] glove__average__linear_svm: score=0.79437 mae=0.82254 acc=0.46464 macro_f1=0.44435
[job] glove__average__ridge_classifier | jobs_run: 20/40

[ok] glove__average__ridge_classifier: score=0.79064 mae=0.83742 acc=0.46052 macro_f1=0.44009
[job] glove__tfidf_weighted__features | jobs_run: 21/40

[job] glove__tfidf_weighted__logreg | jobs_run: 22/40

/cluster/courses/cil/envs/envs/text-5060/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] glove__tfidf_weighted__logreg: score=0.78523 mae=0.85909 acc=0.43758 macro_f1=0.43078
[job] glove__tfidf_weighted__linear_svm | jobs_run: 23/40

[ok] glove__tfidf_weighted__linear_svm: score=0.77630 mae=0.89480 acc=0.44024 macro_f1=0.41888
[job] glove__tfidf_weighted__ridge_classifier | jobs_run: 24/40

[ok] glove__tfidf_weighted__ridge_classifier: score=0.77320 mae=0.90718 acc=0.43567 macro_f1=0.41405
[job] glove__mean_max__features | jobs_run: 25/40

[job] glove__mean_max__logreg | jobs_run: 26/40

/cluster/courses/cil/envs/envs/text-5060/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] glove__mean_max__logreg: score=0.78936 mae=0.84258 acc=0.44556 macro_f1=0.44010
[job] glove__mean_max__linear_svm | jobs_run: 27/40

[ok] glove__mean_max__linear_svm: score=0.79588 mae=0.81647 acc=0.46722 macro_f1=0.44972
[job] glove__mean_max__ridge_classifier | jobs_run: 28/40

[ok] glove__mean_max__ridge_classifier: score=0.78935 mae=0.84262 acc=0.45937 macro_f1=0.44241
[job] fasttext__average__features | jobs_run: 29/40

[job] fasttext__average__logreg | jobs_run: 30/40

/cluster/courses/cil/envs/envs/text-5060/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] fasttext__average__logreg: score=0.81801 mae=0.72798 acc=0.48933 macro_f1=0.48443
[job] fasttext__average__linear_svm | jobs_run: 31/40

[ok] fasttext__average__linear_svm: score=0.81158 mae=0.75369 acc=0.49397 macro_f1=0.47723
[job] fasttext__average__ridge_classifier | jobs_run: 32/40

[ok] fasttext__average__ridge_classifier: score=0.80833 mae=0.76667 acc=0.48821 macro_f1=0.47089
[job] fasttext__tfidf_weighted__features | jobs_run: 33/40

[job] fasttext__tfidf_weighted__logreg | jobs_run: 34/40

/cluster/courses/cil/envs/envs/text-5060/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] fasttext__tfidf_weighted__logreg: score=0.80083 mae=0.79667 acc=0.46528 macro_f1=0.45929
[job] fasttext__tfidf_weighted__linear_svm | jobs_run: 35/40

[ok] fasttext__tfidf_weighted__linear_svm: score=0.79105 mae=0.83579 acc=0.46583 macro_f1=0.44765
[job] fasttext__tfidf_weighted__ridge_classifier | jobs_run: 36/40

[ok] fasttext__tfidf_weighted__ridge_classifier: score=0.78900 mae=0.84401 acc=0.46369 macro_f1=0.44479
[job] fasttext__mean_max__features | jobs_run: 37/40

[job] fasttext__mean_max__logreg | jobs_run: 38/40

/cluster/courses/cil/envs/envs/text-5060/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] fasttext__mean_max__logreg: score=0.80633 mae=0.77468 acc=0.47738 macro_f1=0.47129
[job] fasttext__mean_max__linear_svm | jobs_run: 39/40

[ok] fasttext__mean_max__linear_svm: score=0.81748 mae=0.73008 acc=0.50464 macro_f1=0.48954
[job] fasttext__mean_max__ridge_classifier | jobs_run: 40/40

[ok] fasttext__mean_max__ridge_classifier: score=0.81104 mae=0.75583 acc=0.49591 macro_f1=0.48098
Wrote experiments/classic_ml/20260524_100658_CLASSIC_ML_BASELINES/seed_42/classic_ml_results.csv
Wrote experiments/classic_ml/20260524_100658_CLASSIC_ML_BASELINES/seed_42/classic_ml_best_by_family.csv

/cluster/courses/cil/envs/envs/text-5060/bin/python -m baselines.classic_ml_baselines --mode all --train-path data/train.csv --output-dir experiments/classic_ml/20260524_100658_CLASSIC_ML_BASELINES/seed_43 --validation-size 0.1 --random-state 43 --max-features 250000 --max-iter 100 --glove-path experiments/embeddings/glove.6B.300d.txt --fasttext-path experiments/embeddings/fasttext.vec

Train examples: 226800
Validation examples: 25200
Class counts: {0: 45360, 1: 45360, 2: 45360, 3: 45360, 4: 45360}
[job] majority__most_frequent | jobs_run: 1/40
[ok] majority__most_frequent: score=0.50000 mae=2.00000 acc=0.20000 macro_f1=0.06667
[job] bow__word_1_3__features | jobs_run: 2/40

[job] bow__word_1_3__logreg | jobs_run: 3/40

/cluster/courses/cil/envs/envs/text-5060/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] bow__word_1_3__logreg: score=0.86528 mae=0.53889 acc=0.56778 macro_f1=0.56409
[job] bow__word_1_3__linear_svm | jobs_run: 4/40

/cluster/courses/cil/envs/envs/text-5060/lib/python3.14/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[ok] bow__word_1_3__linear_svm: score=0.83707 mae=0.65171 acc=0.51218 macro_f1=0.51045
[job] bow__word_1_3__ridge_classifier | jobs_run: 5/40

[ok] bow__word_1_3__ridge_classifier: score=0.80382 mae=0.78472 acc=0.46567 macro_f1=0.46371
[job] bow__word_1_3__complement_nb | jobs_run: 6/40

[ok] bow__word_1_3__complement_nb: score=0.85296 mae=0.58817 acc=0.56214 macro_f1=0.54382
[job] tfidf_word__word_1_3__features | jobs_run: 7/40

[job] tfidf_word__word_1_3__logreg | jobs_run: 8/40

/cluster/courses/cil/envs/envs/text-5060/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] tfidf_word__word_1_3__logreg: score=0.87134 mae=0.51464 acc=0.59036 macro_f1=0.58599
[job] tfidf_word__word_1_3__linear_svm | jobs_run: 9/40

[ok] tfidf_word__word_1_3__linear_svm: score=0.85970 mae=0.56119 acc=0.55802 macro_f1=0.55371
[job] tfidf_word__word_1_3__ridge_classifier | jobs_run: 10/40

[ok] tfidf_word__word_1_3__ridge_classifier: score=0.86222 mae=0.55111 acc=0.56528 macro_f1=0.55898
[job] tfidf_word__word_1_3__complement_nb | jobs_run: 11/40

[ok] tfidf_word__word_1_3__complement_nb: score=0.85463 mae=0.58147 acc=0.56480 macro_f1=0.54701
[job] tfidf_char__char_wb_3_6__features | jobs_run: 12/40

[job] tfidf_char__char_wb_3_6__logreg | jobs_run: 13/40

/cluster/courses/cil/envs/envs/text-5060/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] tfidf_char__char_wb_3_6__logreg: score=0.86772 mae=0.52913 acc=0.58194 macro_f1=0.57754
[job] tfidf_char__char_wb_3_6__linear_svm | jobs_run: 14/40

[ok] tfidf_char__char_wb_3_6__linear_svm: score=0.85652 mae=0.57393 acc=0.55694 macro_f1=0.55087
[job] tfidf_char__char_wb_3_6__ridge_classifier | jobs_run: 15/40

[ok] tfidf_char__char_wb_3_6__ridge_classifier: score=0.85733 mae=0.57067 acc=0.56111 macro_f1=0.55273
[job] tfidf_char__char_wb_3_6__complement_nb | jobs_run: 16/40

[ok] tfidf_char__char_wb_3_6__complement_nb: score=0.83304 mae=0.66786 acc=0.53357 macro_f1=0.51173
[job] glove__average__features | jobs_run: 17/40

[job] glove__average__logreg | jobs_run: 18/40

/cluster/courses/cil/envs/envs/text-5060/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] glove__average__logreg: score=0.80053 mae=0.79790 acc=0.46032 macro_f1=0.45488
[job] glove__average__linear_svm | jobs_run: 19/40

[ok] glove__average__linear_svm: score=0.79511 mae=0.81956 acc=0.46655 macro_f1=0.44657
[job] glove__average__ridge_classifier | jobs_run: 20/40

[ok] glove__average__ridge_classifier: score=0.79214 mae=0.83143 acc=0.46286 macro_f1=0.44247
[job] glove__tfidf_weighted__features | jobs_run: 21/40

[job] glove__tfidf_weighted__logreg | jobs_run: 22/40

/cluster/courses/cil/envs/envs/text-5060/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] glove__tfidf_weighted__logreg: score=0.78377 mae=0.86492 acc=0.43714 macro_f1=0.43006
[job] glove__tfidf_weighted__linear_svm | jobs_run: 23/40

[ok] glove__tfidf_weighted__linear_svm: score=0.77653 mae=0.89389 acc=0.44083 macro_f1=0.41966
[job] glove__tfidf_weighted__ridge_classifier | jobs_run: 24/40

[ok] glove__tfidf_weighted__ridge_classifier: score=0.77362 mae=0.90552 acc=0.43698 macro_f1=0.41560
[job] glove__mean_max__features | jobs_run: 25/40

[job] glove__mean_max__logreg | jobs_run: 26/40

/cluster/courses/cil/envs/envs/text-5060/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] glove__mean_max__logreg: score=0.78875 mae=0.84500 acc=0.44667 macro_f1=0.43854
[job] glove__mean_max__linear_svm | jobs_run: 27/40

[ok] glove__mean_max__linear_svm: score=0.79954 mae=0.80183 acc=0.47246 macro_f1=0.45453
[job] glove__mean_max__ridge_classifier | jobs_run: 28/40

[ok] glove__mean_max__ridge_classifier: score=0.79313 mae=0.82746 acc=0.46520 macro_f1=0.44841
[job] fasttext__average__features | jobs_run: 29/40

[job] fasttext__average__logreg | jobs_run: 30/40

/cluster/courses/cil/envs/envs/text-5060/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] fasttext__average__logreg: score=0.81745 mae=0.73020 acc=0.49472 macro_f1=0.48784
[job] fasttext__average__linear_svm | jobs_run: 31/40

[ok] fasttext__average__linear_svm: score=0.81179 mae=0.75286 acc=0.49405 macro_f1=0.47789
[job] fasttext__average__ridge_classifier | jobs_run: 32/40

[ok] fasttext__average__ridge_classifier: score=0.80813 mae=0.76746 acc=0.48873 macro_f1=0.47177
[job] fasttext__tfidf_weighted__features | jobs_run: 33/40

[job] fasttext__tfidf_weighted__logreg | jobs_run: 34/40

/cluster/courses/cil/envs/envs/text-5060/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] fasttext__tfidf_weighted__logreg: score=0.80080 mae=0.79679 acc=0.46524 macro_f1=0.45914
[job] fasttext__tfidf_weighted__linear_svm | jobs_run: 35/40

[ok] fasttext__tfidf_weighted__linear_svm: score=0.79125 mae=0.83500 acc=0.46556 macro_f1=0.44740
[job] fasttext__tfidf_weighted__ridge_classifier | jobs_run: 36/40

[ok] fasttext__tfidf_weighted__ridge_classifier: score=0.78865 mae=0.84540 acc=0.46353 macro_f1=0.44498
[job] fasttext__mean_max__features | jobs_run: 37/40

[job] fasttext__mean_max__logreg | jobs_run: 38/40

/cluster/courses/cil/envs/envs/text-5060/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] fasttext__mean_max__logreg: score=0.80596 mae=0.77615 acc=0.47452 macro_f1=0.46882
[job] fasttext__mean_max__linear_svm | jobs_run: 39/40

[ok] fasttext__mean_max__linear_svm: score=0.81716 mae=0.73135 acc=0.50401 macro_f1=0.48873
[job] fasttext__mean_max__ridge_classifier | jobs_run: 40/40

[ok] fasttext__mean_max__ridge_classifier: score=0.81125 mae=0.75500 acc=0.49579 macro_f1=0.48060
Wrote experiments/classic_ml/20260524_100658_CLASSIC_ML_BASELINES/seed_43/classic_ml_results.csv
Wrote experiments/classic_ml/20260524_100658_CLASSIC_ML_BASELINES/seed_43/classic_ml_best_by_family.csv

/cluster/courses/cil/envs/envs/text-5060/bin/python -m baselines.classic_ml_baselines --mode all --train-path data/train.csv --output-dir experiments/classic_ml/20260524_100658_CLASSIC_ML_BASELINES/seed_44 --validation-size 0.1 --random-state 44 --max-features 250000 --max-iter 100 --glove-path experiments/embeddings/glove.6B.300d.txt --fasttext-path experiments/embeddings/fasttext.vec

Train examples: 226800
Validation examples: 25200
Class counts: {0: 45360, 1: 45360, 2: 45360, 3: 45360, 4: 45360}
[job] majority__most_frequent | jobs_run: 1/40
[ok] majority__most_frequent: score=0.50000 mae=2.00000 acc=0.20000 macro_f1=0.06667
[job] bow__word_1_3__features | jobs_run: 2/40

[job] bow__word_1_3__logreg | jobs_run: 3/40

/cluster/courses/cil/envs/envs/text-5060/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] bow__word_1_3__logreg: score=0.86610 mae=0.53560 acc=0.57075 macro_f1=0.56809
[job] bow__word_1_3__linear_svm | jobs_run: 4/40

/cluster/courses/cil/envs/envs/text-5060/lib/python3.14/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[ok] bow__word_1_3__linear_svm: score=0.83871 mae=0.64516 acc=0.51440 macro_f1=0.51343
[job] bow__word_1_3__ridge_classifier | jobs_run: 5/40

[ok] bow__word_1_3__ridge_classifier: score=0.80438 mae=0.78250 acc=0.46333 macro_f1=0.46154
[job] bow__word_1_3__complement_nb | jobs_run: 6/40

[ok] bow__word_1_3__complement_nb: score=0.85610 mae=0.57560 acc=0.56960 macro_f1=0.55189
[job] tfidf_word__word_1_3__features | jobs_run: 7/40

[job] tfidf_word__word_1_3__logreg | jobs_run: 8/40

/cluster/courses/cil/envs/envs/text-5060/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] tfidf_word__word_1_3__logreg: score=0.87524 mae=0.49905 acc=0.59833 macro_f1=0.59569
[job] tfidf_word__word_1_3__linear_svm | jobs_run: 9/40

[ok] tfidf_word__word_1_3__linear_svm: score=0.86090 mae=0.55639 acc=0.55948 macro_f1=0.55579
[job] tfidf_word__word_1_3__ridge_classifier | jobs_run: 10/40

[ok] tfidf_word__word_1_3__ridge_classifier: score=0.86321 mae=0.54714 acc=0.56774 macro_f1=0.56208
[job] tfidf_word__word_1_3__complement_nb | jobs_run: 11/40

[ok] tfidf_word__word_1_3__complement_nb: score=0.85809 mae=0.56766 acc=0.57214 macro_f1=0.55488
[job] tfidf_char__char_wb_3_6__features | jobs_run: 12/40

[job] tfidf_char__char_wb_3_6__logreg | jobs_run: 13/40

/cluster/courses/cil/envs/envs/text-5060/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] tfidf_char__char_wb_3_6__logreg: score=0.86810 mae=0.52762 acc=0.58048 macro_f1=0.57800
[job] tfidf_char__char_wb_3_6__linear_svm | jobs_run: 14/40

[ok] tfidf_char__char_wb_3_6__linear_svm: score=0.85718 mae=0.57127 acc=0.55897 macro_f1=0.55325
[job] tfidf_char__char_wb_3_6__ridge_classifier | jobs_run: 15/40

[ok] tfidf_char__char_wb_3_6__ridge_classifier: score=0.85761 mae=0.56956 acc=0.56381 macro_f1=0.55574
[job] tfidf_char__char_wb_3_6__complement_nb | jobs_run: 16/40

[ok] tfidf_char__char_wb_3_6__complement_nb: score=0.83328 mae=0.66687 acc=0.53607 macro_f1=0.51401
[job] glove__average__features | jobs_run: 17/40

[job] glove__average__logreg | jobs_run: 18/40

/cluster/courses/cil/envs/envs/text-5060/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] glove__average__logreg: score=0.80081 mae=0.79675 acc=0.46286 macro_f1=0.45649
[job] glove__average__linear_svm | jobs_run: 19/40

[ok] glove__average__linear_svm: score=0.79688 mae=0.81250 acc=0.46980 macro_f1=0.44990
[job] glove__average__ridge_classifier | jobs_run: 20/40

[ok] glove__average__ridge_classifier: score=0.79367 mae=0.82532 acc=0.46679 macro_f1=0.44674
[job] glove__tfidf_weighted__features | jobs_run: 21/40

[job] glove__tfidf_weighted__logreg | jobs_run: 22/40

/cluster/courses/cil/envs/envs/text-5060/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] glove__tfidf_weighted__logreg: score=0.78446 mae=0.86214 acc=0.43817 macro_f1=0.43187
[job] glove__tfidf_weighted__linear_svm | jobs_run: 23/40

[ok] glove__tfidf_weighted__linear_svm: score=0.77883 mae=0.88468 acc=0.44734 macro_f1=0.42675
[job] glove__tfidf_weighted__ridge_classifier | jobs_run: 24/40

[ok] glove__tfidf_weighted__ridge_classifier: score=0.77630 mae=0.89480 acc=0.44536 macro_f1=0.42444
[job] glove__mean_max__features | jobs_run: 25/40

[job] glove__mean_max__logreg | jobs_run: 26/40

/cluster/courses/cil/envs/envs/text-5060/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] glove__mean_max__logreg: score=0.79136 mae=0.83456 acc=0.45063 macro_f1=0.44298
[job] glove__mean_max__linear_svm | jobs_run: 27/40

[ok] glove__mean_max__linear_svm: score=0.79940 mae=0.80238 acc=0.47345 macro_f1=0.45561
[job] glove__mean_max__ridge_classifier | jobs_run: 28/40

[ok] glove__mean_max__ridge_classifier: score=0.79344 mae=0.82623 acc=0.46476 macro_f1=0.44731
[job] fasttext__average__features | jobs_run: 29/40

[job] fasttext__average__logreg | jobs_run: 30/40

/cluster/courses/cil/envs/envs/text-5060/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] fasttext__average__logreg: score=0.81606 mae=0.73575 acc=0.49270 macro_f1=0.48573
[job] fasttext__average__linear_svm | jobs_run: 31/40

[ok] fasttext__average__linear_svm: score=0.80946 mae=0.76214 acc=0.49071 macro_f1=0.47479
[job] fasttext__average__ridge_classifier | jobs_run: 32/40

[ok] fasttext__average__ridge_classifier: score=0.80566 mae=0.77734 acc=0.48690 macro_f1=0.47020
[job] fasttext__tfidf_weighted__features | jobs_run: 33/40

[job] fasttext__tfidf_weighted__logreg | jobs_run: 34/40

/cluster/courses/cil/envs/envs/text-5060/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] fasttext__tfidf_weighted__logreg: score=0.79943 mae=0.80226 acc=0.46611 macro_f1=0.46045
[job] fasttext__tfidf_weighted__linear_svm | jobs_run: 35/40

[ok] fasttext__tfidf_weighted__linear_svm: score=0.78888 mae=0.84448 acc=0.46155 macro_f1=0.44377
[job] fasttext__tfidf_weighted__ridge_classifier | jobs_run: 36/40

[ok] fasttext__tfidf_weighted__ridge_classifier: score=0.78668 mae=0.85329 acc=0.45960 macro_f1=0.44135
[job] fasttext__mean_max__features | jobs_run: 37/40

[job] fasttext__mean_max__logreg | jobs_run: 38/40

/cluster/courses/cil/envs/envs/text-5060/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[ok] fasttext__mean_max__logreg: score=0.80535 mae=0.77861 acc=0.47849 macro_f1=0.47098
[job] fasttext__mean_max__linear_svm | jobs_run: 39/40

[ok] fasttext__mean_max__linear_svm: score=0.81723 mae=0.73107 acc=0.50349 macro_f1=0.48845
[job] fasttext__mean_max__ridge_classifier | jobs_run: 40/40

[ok] fasttext__mean_max__ridge_classifier: score=0.81210 mae=0.75159 acc=0.49651 macro_f1=0.48162
Wrote experiments/classic_ml/20260524_100658_CLASSIC_ML_BASELINES/seed_44/classic_ml_results.csv
Wrote experiments/classic_ml/20260524_100658_CLASSIC_ML_BASELINES/seed_44/classic_ml_best_by_family.csv

[{'seed': 42,
  'run_dir': PosixPath('experiments/classic_ml/20260524_100658_CLASSIC_ML_BASELINES/seed_42')},
 {'seed': 43,
  'run_dir': PosixPath('experiments/classic_ml/20260524_100658_CLASSIC_ML_BASELINES/seed_43')},
 {'seed': 44,
  'run_dir': PosixPath('experiments/classic_ml/20260524_100658_CLASSIC_ML_BASELINES/seed_44')}]

## Total Analysis

In [3]:
result_frames = []
for run in completed_runs:
    frame = pd.read_csv(run["run_dir"] / "classic_ml_results.csv")
    frame.insert(0, "seed", run["seed"])
    result_frames.append(frame)

results = pd.concat(result_frames, ignore_index=True)
results.to_csv(EXPERIMENT_DIR / "classic_ml_results.csv", index=False)

total_results = results.sort_values(
    ["status", "cil_score"], ascending=[False, False]
).reset_index(drop=True)
total_results.to_csv(EXPERIMENT_DIR / "total_analysis.csv", index=False)
total_results

,seed,experiment,family,representation,variant,classifier,status,train_seconds,predict_seconds,accuracy,macro_f1,mae,cil_score,quadratic_weighted_kappa,notes
0,44,tfidf_word__word_1_3__logreg,tfidf_word,"word n-grams=(1, 3)",word_1_3,logreg,ok,50.853062,0.031266,0.598333,0.595693,0.499048,0.875238,0.817048,"feature_seconds=69.57; train_shape=(226800, 25..."
1,42,tfidf_word__word_1_3__logreg,tfidf_word,"word n-grams=(1, 3)",word_1_3,logreg,ok,42.306954,0.023856,0.595595,0.592839,0.501389,0.874653,0.816759,"feature_seconds=60.99; train_shape=(226800, 25..."
2,43,tfidf_word__word_1_3__logreg,tfidf_word,"word n-grams=(1, 3)",word_1_3,logreg,ok,41.535271,0.021415,0.590357,0.585986,0.514643,0.871339,0.810656,"feature_seconds=58.49; train_shape=(226800, 25..."
3,42,tfidf_char__char_wb_3_6__logreg,tfidf_char,"char_wb n-grams=(3, 6)",char_wb_3_6,logreg,ok,159.854112,0.093858,0.583849,0.580399,0.522897,0.869276,0.805958,"feature_seconds=86.26; train_shape=(226800, 25..."
4,44,tfidf_char__char_wb_3_6__logreg,tfidf_char,"char_wb n-grams=(3, 6)",char_wb_3_6,logreg,ok,162.642435,0.079766,0.580476,0.577999,0.527619,0.868095,0.803204,"feature_seconds=95.39; train_shape=(226800, 25..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,43,glove__tfidf_weighted__ridge_classifier,glove,glove tfidf_weighted,tfidf_weighted,ridge_classifier,ok,1.197790,0.015891,0.436984,0.415602,0.905516,0.773621,0.584771,feature_seconds=50.95; vocab_cov=0.3326; token...
89,42,glove__tfidf_weighted__ridge_classifier,glove,glove tfidf_weighted,tfidf_weighted,ridge_classifier,ok,0.894921,0.014813,0.435675,0.414048,0.907183,0.773204,0.586081,feature_seconds=44.59; vocab_cov=0.3329; token...
90,42,majority__most_frequent,majority,constant,most_frequent,dummy_most_frequent,ok,0.009343,0.000206,0.200000,0.066667,2.000000,0.500000,0.000000,Always predicts the most frequent training label.
91,43,majority__most_frequent,majority,constant,most_frequent,dummy_most_frequent,ok,0.008632,0.000298,0.200000,0.066667,2.000000,0.500000,0.000000,Always predicts the most frequent training label.
92,44,majority__most_frequent,majority,constant,most_frequent,dummy_most_frequent,ok,0.008864,0.000252,0.200000,0.066667,2.000000,0.500000,0.000000,Always predicts the most frequent training label.

## Report Analysis

In [4]:
ok_results = results[results["status"] == "ok"].copy()
per_seed_report_results = (
    ok_results.sort_values("cil_score", ascending=False)
    .groupby(["seed", "family"], as_index=False)
    .first()
    .sort_values(["family", "seed"])
    .reset_index(drop=True)
)
per_seed_report_results.to_csv(EXPERIMENT_DIR / "per_seed_report_analysis.csv", index=False)

report_results = (
    per_seed_report_results
    .groupby("family")[["cil_score", "mae", "accuracy", "macro_f1"]]
    .agg(["mean", "std"])
    .reset_index()
)
report_results.columns = [
    column[0] if column[1] == "" else f"{column[0]}_{column[1]}"
    for column in report_results.columns.to_flat_index()
]
report_results = report_results.sort_values("cil_score_mean", ascending=False).reset_index(drop=True)
report_results.to_csv(EXPERIMENT_DIR / "report_analysis.csv", index=False)
report_results

,family,cil_score_mean,cil_score_std,mae_mean,mae_std,accuracy_mean,accuracy_std,macro_f1_mean,macro_f1_std
0,tfidf_word,0.873743,0.002102,0.505026,0.008410,0.594762,0.004053,0.591506,0.004989
1,tfidf_char,0.868363,0.000813,0.526548,0.003250,0.582090,0.001691,0.578646,0.001536
2,bow,0.866319,0.001166,0.534722,0.004665,0.569167,0.001498,0.566809,0.002357
3,fasttext,0.817563,0.000399,0.729749,0.001596,0.495847,0.007150,0.486907,0.002163
4,glove,0.800017,0.001140,0.799934,0.004561,0.459775,0.003386,0.453601,0.003706
5,majority,0.500000,0.000000,2.000000,0.000000,0.200000,0.000000,0.066667,0.000000

## Analysis Artifacts

In [5]:
analysis_dir = EXPERIMENT_DIR / "analysis"
analysis_dir.mkdir(parents=True, exist_ok=True)

classic_fastest_table = analysis_dir / "classic_fastest_families.tex"
classic_full_table = analysis_dir / "classic_full_results.tex"
classic_seed_summary_table = analysis_dir / "classic_seed_summary.tex"
subprocess.run(
    [
        sys.executable,
        "-m",
        "baselines.analysis.make_classic_latex_table",
        "--input",
        str(EXPERIMENT_DIR / "classic_ml_results.csv"),
        "--output",
        str(classic_fastest_table),
        "--full-output",
        str(classic_full_table),
    ],
    check=True,
)
subprocess.run(
    [
        sys.executable,
        "-m",
        "baselines.analysis.make_seed_summary_latex_table",
        "--input",
        str(EXPERIMENT_DIR / "per_seed_report_analysis.csv"),
        "--output",
        str(classic_seed_summary_table),
        "--group-by",
        "family",
        "--caption",
        "Classic baseline validation metrics across five seeds.",
        "--label",
        "tab:classic-seed-summary",
    ],
    check=True,
)

classic_fastest_table, classic_full_table, classic_seed_summary_table

Wrote experiments/classic_ml/20260524_100658_CLASSIC_ML_BASELINES/analysis/classic_fastest_families.tex
Wrote experiments/classic_ml/20260524_100658_CLASSIC_ML_BASELINES/analysis/classic_full_results.tex

Wrote experiments/classic_ml/20260524_100658_CLASSIC_ML_BASELINES/analysis/classic_seed_summary.tex

(PosixPath('experiments/classic_ml/20260524_100658_CLASSIC_ML_BASELINES/analysis/classic_fastest_families.tex'),
 PosixPath('experiments/classic_ml/20260524_100658_CLASSIC_ML_BASELINES/analysis/classic_full_results.tex'),
 PosixPath('experiments/classic_ml/20260524_100658_CLASSIC_ML_BASELINES/analysis/classic_seed_summary.tex'))