# Classic DNN Baselines

This notebook runs the fastText DNN baseline grid and creates analysis tables:

- `total_results`: all evaluated DNN combinations.
- `report_results`: the best validation result per model family.
- `epoch_history`: per-epoch validation metrics for training curves.

The task predicts sentiment labels `0..4`, with validation score `1 - MAE / 4`. The grid uses average fastText document vectors with an MLP plus fastText token sequences with TextCNN and BiLSTM. BERT-style modeling is handled separately.

In [1]:
from datetime import datetime
from pathlib import Path
import subprocess
import sys

import pandas as pd

EXPERIMENT_KIND = "FASTTEXT_DNN_BASELINES"
RUN_ID = datetime.now().strftime("%Y%m%d_%H%M%S")
EXPERIMENT_DIR = Path("experiments/classic_dnn") / f"{RUN_ID}_{EXPERIMENT_KIND}"
EMBEDDING_DIR = Path("experiments/embeddings")
EXPERIMENT_DIR.mkdir(parents=True, exist_ok=True)
EMBEDDING_DIR.mkdir(parents=True, exist_ok=True)

TRAIN_PATH = Path("data/train.csv")
FASTTEXT_PATH = EMBEDDING_DIR / "fasttext.vec"
VALIDATION_SIZE = 0.1
RANDOM_STATE = 42
EPOCHS = 10
BATCH_SIZE = 128


FASTTEXT_PATH.exists(), FASTTEXT_PATH

(True, PosixPath('experiments/embeddings/fasttext.vec'))

Place the merged fastText vector file at `experiments/embeddings/fasttext.vec`. You can create it with `load_embeddings.ipynb`.

In [2]:
cmd = [
    sys.executable,
    "-m",
    "baselines.classic_dnn_baselines",
    "--train-path",
    str(TRAIN_PATH),
    "--output-dir",
    str(EXPERIMENT_DIR),
    "--validation-size",
    str(VALIDATION_SIZE),
    "--random-state",
    str(RANDOM_STATE),
    "--fasttext-path",
    str(FASTTEXT_PATH),
    "--epochs",
    str(EPOCHS),
    "--batch-size",
    str(BATCH_SIZE),
]

print(" ".join(cmd))
subprocess.run(cmd, check=True)

/cluster/courses/cil/envs/envs/text-5060/bin/python -m baselines.classic_dnn_baselines --train-path data/train.csv --output-dir experiments/classic_dnn/20260518_101535_FASTTEXT_DNN_BASELINES --validation-size 0.1 --random-state 42 --fasttext-path experiments/embeddings/fasttext.vec --epochs 10 --batch-size 128

Train examples: 226800
Validation examples: 25200
Device: cuda
Loading fasttext embeddings from experiments/embeddings/fasttext.vec
fasttext coverage: token=0.9846, vocab=0.8222, dim=300
[job] D1__fasttext__average__mlp | jobs_run: 1/3

[epoch] D1__fasttext__average__mlp | epoch: 1/10 | val_score=0.81868 | val_mae=0.72528

[epoch] D1__fasttext__average__mlp | epoch: 2/10 | val_score=0.82268 | val_mae=0.70929

[epoch] D1__fasttext__average__mlp | epoch: 3/10 | val_score=0.82021 | val_mae=0.71917

[epoch] D1__fasttext__average__mlp | epoch: 4/10 | val_score=0.82406 | val_mae=0.70377

[epoch] D1__fasttext__average__mlp | epoch: 5/10 | val_score=0.83670 | val_mae=0.65321

[epoch] D1__fasttext__average__mlp | epoch: 6/10 | val_score=0.81679 | val_mae=0.73286

[epoch] D1__fasttext__average__mlp | epoch: 7/10 | val_score=0.82697 | val_mae=0.69210

[epoch] D1__fasttext__average__mlp | epoch: 8/10 | val_score=0.83301 | val_mae=0.66798

[epoch] D1__fasttext__average__mlp | epoch: 9/10 | val_score=0.83371 | val_mae=0.66516

[epoch] D1__fasttext__average__mlp | epoch: 10/10 | val_score=0.83133 | val_mae=0.67468
[ok] D1__fasttext__average__mlp: best_epoch=5 score=0.83670 mae=0.65321 acc=0.51286 macro_f1=0.50869
[job] D2__fasttext__pretrained_token_vectors__textcnn | jobs_run: 2/3

[epoch] D2__fasttext__pretrained_token_vectors__textcnn | epoch: 1/10 | val_score=0.86737 | val_mae=0.53052

[epoch] D2__fasttext__pretrained_token_vectors__textcnn | epoch: 2/10 | val_score=0.86788 | val_mae=0.52849

[epoch] D2__fasttext__pretrained_token_vectors__textcnn | epoch: 3/10 | val_score=0.87013 | val_mae=0.51948

[epoch] D2__fasttext__pretrained_token_vectors__textcnn | epoch: 4/10 | val_score=0.87062 | val_mae=0.51750

[epoch] D2__fasttext__pretrained_token_vectors__textcnn | epoch: 5/10 | val_score=0.87549 | val_mae=0.49806

[epoch] D2__fasttext__pretrained_token_vectors__textcnn | epoch: 6/10 | val_score=0.87476 | val_mae=0.50095

[epoch] D2__fasttext__pretrained_token_vectors__textcnn | epoch: 7/10 | val_score=0.87829 | val_mae=0.48683

[epoch] D2__fasttext__pretrained_token_vectors__textcnn | epoch: 8/10 | val_score=0.87636 | val_mae=0.49456

[epoch] D2__fasttext__pretrained_token_vectors__textcnn | epoch: 9/10 | val_score=0.87853 | val_mae=0.48587

[epoch] D2__fasttext__pretrained_token_vectors__textcnn | epoch: 10/10 | val_score=0.87450 | val_mae=0.50198
[ok] D2__fasttext__pretrained_token_vectors__textcnn: best_epoch=9 score=0.87853 mae=0.48587 acc=0.59690 macro_f1=0.59411
[job] D3__fasttext__pretrained_token_vectors__bilstm | jobs_run: 3/3

[epoch] D3__fasttext__pretrained_token_vectors__bilstm | epoch: 1/10 | val_score=0.83801 | val_mae=0.64798

[epoch] D3__fasttext__pretrained_token_vectors__bilstm | epoch: 2/10 | val_score=0.84734 | val_mae=0.61063

[epoch] D3__fasttext__pretrained_token_vectors__bilstm | epoch: 3/10 | val_score=0.85644 | val_mae=0.57425

[epoch] D3__fasttext__pretrained_token_vectors__bilstm | epoch: 4/10 | val_score=0.86273 | val_mae=0.54909

[epoch] D3__fasttext__pretrained_token_vectors__bilstm | epoch: 5/10 | val_score=0.85688 | val_mae=0.57250

[epoch] D3__fasttext__pretrained_token_vectors__bilstm | epoch: 6/10 | val_score=0.86381 | val_mae=0.54476

[epoch] D3__fasttext__pretrained_token_vectors__bilstm | epoch: 7/10 | val_score=0.86596 | val_mae=0.53615

[epoch] D3__fasttext__pretrained_token_vectors__bilstm | epoch: 8/10 | val_score=0.86483 | val_mae=0.54067

[epoch] D3__fasttext__pretrained_token_vectors__bilstm | epoch: 9/10 | val_score=0.86544 | val_mae=0.53825

[epoch] D3__fasttext__pretrained_token_vectors__bilstm | epoch: 10/10 | val_score=0.86543 | val_mae=0.53829
[ok] D3__fasttext__pretrained_token_vectors__bilstm: best_epoch=7 score=0.86596 mae=0.53615 acc=0.56671 macro_f1=0.56362
Wrote experiments/classic_dnn/20260518_101535_FASTTEXT_DNN_BASELINES/classic_dnn_results.csv
Wrote experiments/classic_dnn/20260518_101535_FASTTEXT_DNN_BASELINES/classic_dnn_epoch_history.csv

CompletedProcess(args=['/cluster/courses/cil/envs/envs/text-5060/bin/python', '-m', 'baselines.classic_dnn_baselines', '--train-path', 'data/train.csv', '--output-dir', 'experiments/classic_dnn/20260518_101535_FASTTEXT_DNN_BASELINES', '--validation-size', '0.1', '--random-state', '42', '--fasttext-path', 'experiments/embeddings/fasttext.vec', '--epochs', '10', '--batch-size', '128'], returncode=0)

## Total Analysis

In [3]:
results = pd.read_csv(EXPERIMENT_DIR / "classic_dnn_results.csv")
total_results = results.sort_values(
    ["status", "cil_score"], ascending=[False, False]
).reset_index(drop=True)
total_results.to_csv(EXPERIMENT_DIR / "total_analysis.csv", index=False)
total_results

,experiment,experiment_id,embedding,input_type,representation,model,status,best_epoch,best_epoch_train_loss,best_epoch_val_loss,train_seconds,accuracy,macro_f1,mae,cil_score,quadratic_weighted_kappa,notes
0,D2__fasttext__pretrained_token_vectors__textcnn,D2,fasttext,token_sequence,pretrained_token_vectors,textcnn,ok,9,0.866136,0.920343,158.762167,0.596905,0.594107,0.485873,0.878532,0.830687,NaN
1,D3__fasttext__pretrained_token_vectors__bilstm,D3,fasttext,token_sequence,pretrained_token_vectors,bilstm,ok,7,0.996050,0.989845,410.321889,0.566706,0.563621,0.536151,0.865962,0.802752,NaN
2,D1__fasttext__average__mlp,D1,fasttext,document_vector,average,mlp,ok,5,1.170457,1.132415,69.052891,0.512857,0.508695,0.653214,0.836696,0.731013,NaN

## Report Analysis

In [4]:
ok_results = results[results["status"] == "ok"].copy()
report_results = (
    ok_results.sort_values("cil_score", ascending=False)
    .groupby("model", as_index=False)
    .first()
    .sort_values("cil_score", ascending=False)
    .reset_index(drop=True)
)
report_results.to_csv(EXPERIMENT_DIR / "report_analysis.csv", index=False)
report_results

,model,experiment,experiment_id,embedding,input_type,representation,status,best_epoch,best_epoch_train_loss,best_epoch_val_loss,train_seconds,accuracy,macro_f1,mae,cil_score,quadratic_weighted_kappa,notes
0,textcnn,D2__fasttext__pretrained_token_vectors__textcnn,D2,fasttext,token_sequence,pretrained_token_vectors,ok,9,0.866136,0.920343,158.762167,0.596905,0.594107,0.485873,0.878532,0.830687,NaN
1,bilstm,D3__fasttext__pretrained_token_vectors__bilstm,D3,fasttext,token_sequence,pretrained_token_vectors,ok,7,0.996050,0.989845,410.321889,0.566706,0.563621,0.536151,0.865962,0.802752,NaN
2,mlp,D1__fasttext__average__mlp,D1,fasttext,document_vector,average,ok,5,1.170457,1.132415,69.052891,0.512857,0.508695,0.653214,0.836696,0.731013,NaN

## Epoch History

In [5]:
epoch_history = pd.read_csv(EXPERIMENT_DIR / "classic_dnn_epoch_history.csv")
epoch_history = epoch_history.sort_values(["experiment", "epoch"]).reset_index(drop=True)
epoch_history.to_csv(EXPERIMENT_DIR / "epoch_analysis.csv", index=False)
epoch_history

,experiment,epoch,train_loss,val_loss,accuracy,macro_f1,mae,cil_score,quadratic_weighted_kappa
0,D1__fasttext__average__mlp,1,1.287451,1.220750,0.462778,0.462873,0.725278,0.818681,0.681540
1,D1__fasttext__average__mlp,2,1.212858,1.172247,0.491032,0.480551,0.709286,0.822679,0.704604
2,D1__fasttext__average__mlp,3,1.192118,1.160790,0.495437,0.476920,0.719167,0.820208,0.707280
3,D1__fasttext__average__mlp,4,1.178672,1.185865,0.481349,0.480745,0.703770,0.824058,0.701040
4,D1__fasttext__average__mlp,5,1.170457,1.132415,0.512857,0.508695,0.653214,0.836696,0.731013
5,D1__fasttext__average__mlp,6,1.160141,1.145390,0.494008,0.472195,0.732857,0.816786,0.702508
6,D1__fasttext__average__mlp,7,1.154436,1.132195,0.508810,0.491463,0.692103,0.826974,0.718506
7,D1__fasttext__average__mlp,8,1.146688,1.119032,0.515675,0.505582,0.667976,0.833006,0.726509
8,D1__fasttext__average__mlp,9,1.143437,1.113286,0.517381,0.504110,0.665159,0.833710,0.731471
9,D1__fasttext__average__mlp,10,1.138916,1.114911,0.518135,0.504790,0.674683,0.831329,0.723873
10,D2__fasttext__pretrained_token_vectors__textcnn,1,1.098077,0.995228,0.569841,0.569280,0.530516,0.867371,0.800644
11,D2__fasttext__pretrained_token_vectors__textcnn,2,0.975915,0.951343,0.584683,0.573233,0.528492,0.867877,0.805940
12,D2__fasttext__pretrained_token_vectors__textcnn,3,0.945310,0.942794,0.589365,0.579331,0.519484,0.870129,0.813710
13,D2__fasttext__pretrained_token_vectors__textcnn,4,0.926117,0.939122,0.588849,0.578630,0.517500,0.870625,0.814910
14,D2__fasttext__pretrained_token_vectors__textcnn,5,0.909487,0.926890,0.595754,0.589561,0.498056,0.875486,0.825319
15,D2__fasttext__pretrained_token_vectors__textcnn,6,0.896942,0.925578,0.597460,0.587873,0.500952,0.874762,0.824794
16,D2__fasttext__pretrained_token_vectors__textcnn,7,0.883695,0.923332,0.594762,0.594252,0.486825,0.878294,0.829402
17,D2__fasttext__pretrained_token_vectors__textcnn,8,0.872814,0.927942,0.593968,0.589599,0.494563,0.876359,0.825730
18,D2__fasttext__pretrained_token_vectors__textcnn,9,0.866136,0.920343,0.596905,0.594107,0.485873,0.878532,0.830687
19,D2__fasttext__pretrained_token_vectors__textcnn,10,0.857328,0.929831,0.594087,0.583730,0.501984,0.874504,0.824210
20,D3__fasttext__pretrained_token_vectors__bilstm,1,1.201919,1.093670,0.526984,0.513876,0.647976,0.838006,0.742061
21,D3__fasttext__pretrained_token_vectors__bilstm,2,1.089458,1.055270,0.542500,0.530053,0.610635,0.847341,0.760779
22,D3__fasttext__pretrained_token_vectors__bilstm,3,1.052501,1.023687,0.550833,0.542571,0.574246,0.856438,0.786141
23,D3__fasttext__pretrained_token_vectors__bilstm,4,1.029188,1.014026,0.557778,0.557844,0.549087,0.862728,0.791741
24,D3__fasttext__pretrained_token_vectors__bilstm,5,1.014055,1.009396,0.560317,0.549209,0.572500,0.856875,0.783715
25,D3__fasttext__pretrained_token_vectors__bilstm,6,1.002719,0.990146,0.568492,0.562660,0.544762,0.863810,0.799825
26,D3__fasttext__pretrained_token_vectors__bilstm,7,0.996050,0.989845,0.566706,0.563621,0.536151,0.865962,0.802752
27,D3__fasttext__pretrained_token_vectors__bilstm,8,0.987135,0.982792,0.573214,0.567983,0.540675,0.864831,0.797344
28,D3__fasttext__pretrained_token_vectors__bilstm,9,0.980881,0.978490,0.570873,0.564941,0.538254,0.865437,0.800938
29,D3__fasttext__pretrained_token_vectors__bilstm,10,0.976140,0.971358,0.572937,0.564705,0.538294,0.865427,0.804748

In [6]:
best_epochs = (
    epoch_history.sort_values("cil_score", ascending=False)
    .groupby("experiment", as_index=False)
    .first()
    .sort_values("cil_score", ascending=False)
    .reset_index(drop=True)
)
best_epochs.to_csv(EXPERIMENT_DIR / "best_epoch_analysis.csv", index=False)
best_epochs

,experiment,epoch,train_loss,val_loss,accuracy,macro_f1,mae,cil_score,quadratic_weighted_kappa
0,D2__fasttext__pretrained_token_vectors__textcnn,9,0.866136,0.920343,0.596905,0.594107,0.485873,0.878532,0.830687
1,D3__fasttext__pretrained_token_vectors__bilstm,7,0.996050,0.989845,0.566706,0.563621,0.536151,0.865962,0.802752
2,D1__fasttext__average__mlp,5,1.170457,1.132415,0.512857,0.508695,0.653214,0.836696,0.731013