# Transformer Baselines

This notebook runs Hugging Face transformer comparisons and creates analysis tables:

- `total_results`: all evaluated transformer runs.
- `report_results`: the best validation result per model.
- `epoch_history`: per-epoch validation metrics for training curves.

The task predicts sentiment labels `0..4`, with validation score `1 - MAE / 4`.

In [1]:
from datetime import datetime
from pathlib import Path
import subprocess
import sys

import pandas as pd
import torch

EXPERIMENT_KIND = "TRANSFORMER_BASELINES"
RUN_ID = datetime.now().strftime("%Y%m%d_%H%M%S")
EXPERIMENT_DIR = Path("experiments/transformers") / f"{RUN_ID}_{EXPERIMENT_KIND}"
EXPERIMENT_DIR.mkdir(parents=True, exist_ok=True)

TRAIN_PATH = Path("data/train.csv")
VALIDATION_SIZE = 0.1
RANDOM_STATE = 42
MAX_LENGTH = 256
EPOCHS = 3
BATCH_SIZE = 16
EVAL_BATCH_SIZE = 32
LEARNING_RATE = 2e-5
WEIGHT_DECAY = 0.01
USE_FP16 = True
FP16_EXCLUDED_MODELS = {"microsoft/deberta-v3-base"}

EXPERIMENT_DIR

PosixPath('experiments/transformers/20260521_115409_TRANSFORMER_BASELINES')

In [2]:
models = [
    # {"model_name": "distilbert-base-uncased", "variant": "fine_tuned"},  # completed
    # {"model_name": "bert-base-uncased", "variant": "fine_tuned"},  # completed
    # {"model_name": "roberta-base", "variant": "fine_tuned"},  # completed
    {"model_name": "microsoft/deberta-v3-base", "variant": "fine_tuned"},
    {"model_name": "nlptown/bert-base-multilingual-uncased-sentiment", "variant": "fine_tuned"},
    {"model_name": "nlptown/bert-base-multilingual-uncased-sentiment", "variant": "eval_only"},
]

models

[{'model_name': 'microsoft/deberta-v3-base', 'variant': 'fine_tuned'},
 {'model_name': 'nlptown/bert-base-multilingual-uncased-sentiment',
  'variant': 'fine_tuned'},
 {'model_name': 'nlptown/bert-base-multilingual-uncased-sentiment',
  'variant': 'eval_only'}]

## Run Experiments

In [3]:
completed_runs = []

for spec in models:
    model_name = spec["model_name"]
    variant = spec["variant"]
    run_name = f"{model_name.replace('/', '__')}__{variant}"
    run_dir = EXPERIMENT_DIR / run_name
    run_dir.mkdir(parents=True, exist_ok=True)

    cmd = [
        sys.executable,
        "-m",
        "baselines.train_review_model",
        "--model-name",
        model_name,
        "--experiment-name",
        f"transformer__{run_name}",
        "--train-path",
        str(TRAIN_PATH),
        "--output-dir",
        str(run_dir),
        "--validation-size",
        str(VALIDATION_SIZE),
        "--random-state",
        str(RANDOM_STATE),
        "--max-length",
        str(MAX_LENGTH),
        "--epochs",
        str(EPOCHS),
        "--batch-size",
        str(BATCH_SIZE),
        "--eval-batch-size",
        str(EVAL_BATCH_SIZE),
        "--learning-rate",
        str(LEARNING_RATE),
        "--weight-decay",
        str(WEIGHT_DECAY),
    ]
    if variant == "eval_only":
        cmd.append("--eval-only")
    if USE_FP16 and model_name not in FP16_EXCLUDED_MODELS:
        cmd.append("--fp16")

    print(" ".join(cmd))
    subprocess.run(cmd, check=True)
    completed_runs.append({**spec, "run_name": run_name, "run_dir": run_dir})

completed_runs

/cluster/courses/cil/envs/envs/text-5060/bin/python -m baselines.train_review_model --model-name microsoft/deberta-v3-base --experiment-name transformer__microsoft__deberta-v3-base__fine_tuned --train-path data/train.csv --output-dir experiments/transformers/20260521_115409_TRANSFORMER_BASELINES/microsoft__deberta-v3-base__fine_tuned --validation-size 0.1 --random-state 42 --max-length 256 --epochs 3 --batch-size 16 --eval-batch-size 32 --learning-rate 2e-05 --weight-decay 0.01

Model: microsoft/deberta-v3-base
Variant: fine_tuned
Train examples: 226800
Validation examples: 25200
Class counts: {0: 45360, 1: 45360, 2: 45360, 3: 45360, 4: 45360}

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights: 100%|████████████████████| 198/198 [00:00<00:00, 11949.41it/s]
[transformers] DebertaV2ForSequenceClassification LOAD REPORT from: microsoft/deberta-v3-base
Key                                     | Status     |
----------------------------------------+------------+-
lm_predictions.lm_head.dense.bias       | UNEXPECTED |
mask_predictions.dense.weight           | UNEXPECTED |
mask_predictions.LayerNorm.bias         | UNEXPECTED |
mask_predictions.dense.bias             | UNEXPECTED |
lm_predictions.lm_head.bias             | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.weight | UNEXPECTED |
mask_predictions.classifier.bias        | UNEXPECTED |
mask_predictions.classifier.weight      | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.bias   | UNEXPECTED |
lm_predictions.lm_head.dense.weight     | UNEXPECTED |
mask_predictions.LayerNorm.weight       | UNEXPECTED |
pooler.dense.bias                       | MISSING    |
pooler.dense.weight                     | MISSING    |
classifier.weight                       | MISSING    |
classifier.bias                         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 2, 'bos_token_id': 1}.

  0%|                                                | 0/42525 [00:00<?, ?it/s]

  0%|                                     | 1/42525 [00:01<23:14:26,  1.97s/it]

  0%|                                     | 2/42525 [00:02<11:36:08,  1.02it/s]

  0%|                                      | 3/42525 [00:02<7:42:42,  1.53it/s]

  0%|                                      | 5/42525 [00:03<4:44:48,  2.49it/s]

  0%|                                      | 7/42525 [00:03<2:48:15,  4.21it/s]

  0%|                                      | 9/42525 [00:03<2:04:21,  5.70it/s]

  0%|                                     | 13/42525 [00:03<1:30:32,  7.83it/s]

  0%|                                     | 16/42525 [00:04<1:21:57,  8.64it/s]

  0%|                                     | 19/42525 [00:04<1:16:26,  9.27it/s]

  0%|                                     | 22/42525 [00:04<1:12:42,  9.74it/s]

  0%|                                     | 24/42525 [00:04<1:11:11,  9.95it/s]

  0%|                                     | 28/42525 [00:05<1:13:38,  9.62it/s]

  0%|                                     | 30/42525 [00:05<1:20:50,  8.76it/s]

  0%|                                     | 33/42525 [00:06<1:22:07,  8.62it/s]

  0%|                                     | 35/42525 [00:06<1:25:54,  8.24it/s]

  0%|                                     | 38/42525 [00:06<1:18:21,  9.04it/s]

  0%|                                     | 40/42525 [00:06<1:19:20,  8.93it/s]

  0%|                                     | 43/42525 [00:07<1:23:07,  8.52it/s]

  0%|                                     | 44/42525 [00:07<1:28:17,  8.02it/s]

  0%|                                     | 48/42525 [00:07<1:20:35,  8.79it/s]

  0%|                                     | 50/42525 [00:08<1:24:19,  8.39it/s]

  0%|                                     | 53/42525 [00:08<1:15:44,  9.35it/s]

  0%|                                     | 56/42525 [00:08<1:14:39,  9.48it/s]

  0%|                                     | 60/42525 [00:09<1:15:17,  9.40it/s]

  0%|                                     | 63/42525 [00:09<1:16:15,  9.28it/s]

  0%|                                     | 65/42525 [00:09<1:16:04,  9.30it/s]

  0%|                                     | 67/42525 [00:09<1:15:07,  9.42it/s]

  0%|                                     | 69/42525 [00:10<1:15:11,  9.41it/s]

  0%|                                     | 71/42525 [00:10<1:13:54,  9.57it/s]

  0%|                                     | 72/42525 [00:10<1:15:30,  9.37it/s]

  0%|                                     | 76/42525 [00:10<1:11:59,  9.83it/s]

  0%|                                     | 80/42525 [00:11<1:10:55,  9.97it/s]

  0%|                                     | 83/42525 [00:11<1:13:48,  9.58it/s]

  0%|                                     | 87/42525 [00:11<1:11:47,  9.85it/s]

  0%|                                     | 88/42525 [00:11<1:13:58,  9.56it/s]

  0%|                                     | 90/42525 [00:12<1:18:14,  9.04it/s]

  0%|                                     | 94/42525 [00:12<1:14:18,  9.52it/s]

  0%|                                     | 96/42525 [00:12<1:18:37,  8.99it/s]

  0%|                                     | 98/42525 [00:13<1:14:11,  9.53it/s]

  0%|                                    | 102/42525 [00:13<1:12:20,  9.77it/s]

  0%|                                    | 105/42525 [00:13<1:14:33,  9.48it/s]

  0%|                                    | 107/42525 [00:13<1:12:25,  9.76it/s]

  0%|                                    | 111/42525 [00:14<1:11:04,  9.95it/s]

  0%|                                    | 113/42525 [00:14<1:23:19,  8.48it/s]

  0%|                                    | 115/42525 [00:14<1:27:53,  8.04it/s]

  0%|                                    | 117/42525 [00:15<1:31:35,  7.72it/s]

  0%|                                    | 119/42525 [00:15<1:23:42,  8.44it/s]

  0%|                                    | 121/42525 [00:15<1:28:24,  7.99it/s]

  0%|                                    | 124/42525 [00:15<1:18:44,  8.97it/s]

  0%|                                    | 126/42525 [00:16<1:26:07,  8.20it/s]

  0%|                                    | 129/42525 [00:16<1:22:03,  8.61it/s]

  0%|                                    | 132/42525 [00:16<1:16:58,  9.18it/s]

  0%|                                    | 134/42525 [00:17<1:18:51,  8.96it/s]

  0%|                                    | 137/42525 [00:17<1:16:56,  9.18it/s]

  0%|                                    | 140/42525 [00:17<1:14:17,  9.51it/s]

  0%|                                    | 143/42525 [00:18<1:19:43,  8.86it/s]

  0%|                                    | 145/42525 [00:18<1:17:47,  9.08it/s]

  0%|                                    | 147/42525 [00:18<1:19:16,  8.91it/s]

  0%|▏                                   | 149/42525 [00:18<1:15:06,  9.40it/s]

  0%|▏                                   | 152/42525 [00:19<1:15:44,  9.32it/s]

  0%|▏                                   | 154/42525 [00:19<1:13:28,  9.61it/s]

  0%|▏                                   | 157/42525 [00:19<1:14:19,  9.50it/s]

  0%|▏                                   | 161/42525 [00:19<1:11:12,  9.92it/s]

  0%|▏                                   | 164/42525 [00:20<1:17:23,  9.12it/s]

  0%|▏                                   | 168/42525 [00:20<1:17:19,  9.13it/s]

  0%|▏                                   | 170/42525 [00:21<1:21:35,  8.65it/s]

  0%|▏                                   | 172/42525 [00:21<1:29:42,  7.87it/s]

  0%|▏                                   | 174/42525 [00:21<1:21:38,  8.65it/s]

  0%|▏                                   | 176/42525 [00:21<1:19:49,  8.84it/s]

  0%|▏                                   | 178/42525 [00:21<1:22:22,  8.57it/s]

  0%|▏                                   | 180/42525 [00:22<1:29:14,  7.91it/s]

  0%|▏                                   | 182/42525 [00:22<1:38:14,  7.18it/s]

  0%|▏                                   | 184/42525 [00:22<1:38:10,  7.19it/s]

  0%|▏                                   | 187/42525 [00:23<1:21:21,  8.67it/s]

  0%|▏                                   | 188/42525 [00:23<1:20:05,  8.81it/s]

  0%|▏                                   | 192/42525 [00:23<1:14:22,  9.49it/s]

  0%|▏                                   | 194/42525 [00:23<1:20:43,  8.74it/s]

  0%|▏                                   | 196/42525 [00:24<1:25:52,  8.21it/s]

  0%|▏                                   | 198/42525 [00:24<1:29:38,  7.87it/s]

  0%|▏                                   | 201/42525 [00:24<1:27:54,  8.02it/s]

  0%|▏                                   | 202/42525 [00:24<1:26:13,  8.18it/s]

  0%|▏                                   | 205/42525 [00:25<1:23:32,  8.44it/s]

  0%|▏                                   | 207/42525 [00:25<1:27:08,  8.09it/s]

  0%|▏                                   | 210/42525 [00:25<1:25:39,  8.23it/s]

  0%|▏                                   | 212/42525 [00:26<1:20:11,  8.79it/s]

  1%|▏                                   | 214/42525 [00:26<1:22:20,  8.56it/s]

  1%|▏                                   | 216/42525 [00:26<1:26:20,  8.17it/s]

  1%|▏                                   | 218/42525 [00:26<1:22:19,  8.56it/s]

  1%|▏                                   | 220/42525 [00:27<1:26:38,  8.14it/s]

  1%|▏                                   | 223/42525 [00:27<1:19:17,  8.89it/s]

  1%|▏                                   | 226/42525 [00:27<1:14:26,  9.47it/s]

  1%|▏                                   | 229/42525 [00:27<1:17:18,  9.12it/s]

  1%|▏                                   | 230/42525 [00:28<1:15:54,  9.29it/s]

  1%|▏                                   | 232/42525 [00:28<1:15:35,  9.32it/s]

  1%|▏                                   | 235/42525 [00:28<1:17:30,  9.09it/s]

  1%|▏                                   | 236/42525 [00:28<1:23:41,  8.42it/s]

  1%|▏                                   | 239/42525 [00:29<1:22:57,  8.50it/s]

  1%|▏                                   | 241/42525 [00:29<1:29:53,  7.84it/s]

  1%|▏                                   | 244/42525 [00:29<1:20:18,  8.77it/s]

  1%|▏                                   | 247/42525 [00:30<1:17:15,  9.12it/s]

  1%|▏                                   | 249/42525 [00:30<1:23:45,  8.41it/s]

  1%|▏                                   | 251/42525 [00:30<1:28:13,  7.99it/s]

  1%|▏                                   | 254/42525 [00:30<1:18:59,  8.92it/s]

  1%|▏                                   | 256/42525 [00:31<1:22:55,  8.50it/s]

  1%|▏                                   | 258/42525 [00:31<1:26:29,  8.14it/s]

  1%|▏                                   | 262/42525 [00:31<1:19:18,  8.88it/s]

  1%|▏                                   | 265/42525 [00:32<1:20:53,  8.71it/s]

  1%|▏                                   | 267/42525 [00:32<1:16:00,  9.27it/s]

  1%|▏                                   | 271/42525 [00:32<1:14:57,  9.39it/s]

  1%|▏                                   | 274/42525 [00:33<1:15:39,  9.31it/s]

  1%|▏                                   | 277/42525 [00:33<1:18:20,  8.99it/s]

  1%|▏                                   | 278/42525 [00:33<1:18:13,  9.00it/s]

  1%|▏                                   | 281/42525 [00:33<1:26:39,  8.12it/s]

  1%|▏                                   | 284/42525 [00:34<1:18:43,  8.94it/s]

  1%|▏                                   | 286/42525 [00:34<1:16:22,  9.22it/s]

  1%|▏                                   | 288/42525 [00:34<1:14:56,  9.39it/s]

  1%|▏                                   | 290/42525 [00:34<1:18:38,  8.95it/s]

  1%|▏                                   | 293/42525 [00:35<1:20:09,  8.78it/s]

  1%|▎                                   | 297/42525 [00:35<1:13:10,  9.62it/s]

  1%|▎                                   | 299/42525 [00:35<1:18:01,  9.02it/s]

  1%|▎                                   | 300/42525 [00:35<1:17:11,  9.12it/s]

  1%|▎                                   | 302/42525 [00:36<1:20:58,  8.69it/s]

  1%|▎                                   | 305/42525 [00:36<1:21:54,  8.59it/s]

  1%|▎                                   | 309/42525 [00:36<1:13:48,  9.53it/s]

  1%|▎                                   | 313/42525 [00:37<1:10:40,  9.95it/s]

  1%|▎                                   | 316/42525 [00:37<1:11:43,  9.81it/s]

  1%|▎                                   | 318/42525 [00:37<1:16:51,  9.15it/s]

  1%|▎                                   | 319/42525 [00:38<1:15:19,  9.34it/s]

  1%|▎                                   | 322/42525 [00:38<1:19:23,  8.86it/s]

  1%|▎                                   | 325/42525 [00:38<1:14:51,  9.40it/s]

  1%|▎                                   | 327/42525 [00:38<1:24:49,  8.29it/s]

  1%|▎                                   | 329/42525 [00:39<1:28:46,  7.92it/s]

  1%|▎                                   | 332/42525 [00:39<1:17:05,  9.12it/s]

  1%|▎                                   | 334/42525 [00:39<1:23:54,  8.38it/s]

  1%|▎                                   | 337/42525 [00:40<1:24:17,  8.34it/s]

  1%|▎                                   | 339/42525 [00:40<1:25:56,  8.18it/s]

  1%|▎                                   | 342/42525 [00:40<1:19:14,  8.87it/s]

  1%|▎                                   | 345/42525 [00:41<1:16:01,  9.25it/s]

  1%|▎                                   | 348/42525 [00:41<1:14:59,  9.37it/s]

  1%|▎                                   | 351/42525 [00:41<1:11:27,  9.84it/s]

  1%|▎                                   | 355/42525 [00:42<1:11:46,  9.79it/s]

  1%|▎                                   | 358/42525 [00:42<1:20:06,  8.77it/s]

  1%|▎                                   | 361/42525 [00:42<1:21:41,  8.60it/s]

  1%|▎                                   | 364/42525 [00:43<1:24:23,  8.33it/s]

  1%|▎                                   | 367/42525 [00:43<1:16:38,  9.17it/s]

  1%|▎                                   | 370/42525 [00:43<1:12:07,  9.74it/s]

  1%|▎                                   | 372/42525 [00:43<1:09:55, 10.05it/s]

  1%|▎                                   | 374/42525 [00:44<1:10:38,  9.95it/s]

  1%|▎                                   | 377/42525 [00:44<1:20:38,  8.71it/s]

  1%|▎                                   | 380/42525 [00:44<1:22:09,  8.55it/s]

  1%|▎                                   | 381/42525 [00:44<1:20:01,  8.78it/s]

  1%|▎                                   | 385/42525 [00:45<1:14:26,  9.44it/s]

  1%|▎                                   | 388/42525 [00:45<1:15:58,  9.24it/s]

  1%|▎                                   | 392/42525 [00:46<1:12:25,  9.70it/s]

  1%|▎                                   | 395/42525 [00:46<1:17:13,  9.09it/s]

  1%|▎                                   | 396/42525 [00:46<1:21:39,  8.60it/s]

  1%|▎                                   | 399/42525 [00:46<1:20:59,  8.67it/s]

  1%|▎                                   | 402/42525 [00:47<1:16:30,  9.18it/s]

  1%|▎                                   | 406/42525 [00:47<1:11:23,  9.83it/s]

  1%|▎                                   | 408/42525 [00:47<1:20:18,  8.74it/s]

  1%|▎                                   | 411/42525 [00:48<1:21:08,  8.65it/s]

  1%|▎                                   | 414/42525 [00:48<1:15:27,  9.30it/s]

  1%|▎                                   | 416/42525 [00:48<1:23:24,  8.41it/s]

  1%|▎                                   | 417/42525 [00:48<1:20:05,  8.76it/s]

  1%|▎                                   | 421/42525 [00:49<1:17:17,  9.08it/s]

  1%|▎                                   | 423/42525 [00:49<1:20:33,  8.71it/s]

  1%|▎                                   | 424/42525 [00:49<1:26:11,  8.14it/s]

  1%|▎                                   | 427/42525 [00:50<1:28:42,  7.91it/s]

  1%|▎                                   | 429/42525 [00:50<1:21:18,  8.63it/s]

  1%|▎                                   | 432/42525 [00:50<1:16:53,  9.12it/s]

  1%|▎                                   | 435/42525 [00:50<1:13:41,  9.52it/s]

  1%|▎                                   | 438/42525 [00:51<1:19:30,  8.82it/s]

  1%|▎                                   | 440/42525 [00:51<1:20:01,  8.76it/s]

  1%|▎                                   | 442/42525 [00:51<1:23:18,  8.42it/s]

  1%|▍                                   | 445/42525 [00:52<1:16:57,  9.11it/s]

  1%|▍                                   | 447/42525 [00:52<1:19:27,  8.83it/s]

  1%|▍                                   | 451/42525 [00:52<1:11:54,  9.75it/s]

  1%|▍                                   | 454/42525 [00:53<1:14:02,  9.47it/s]

  1%|▍                                   | 457/42525 [00:53<1:11:26,  9.81it/s]

  1%|▍                                   | 460/42525 [00:53<1:15:23,  9.30it/s]

  1%|▍                                   | 462/42525 [00:53<1:14:59,  9.35it/s]

  1%|▍                                   | 465/42525 [00:54<1:20:30,  8.71it/s]

  1%|▍                                   | 467/42525 [00:54<1:27:55,  7.97it/s]

  1%|▍                                   | 468/42525 [00:54<1:31:59,  7.62it/s]

  1%|▍                                   | 471/42525 [00:55<1:27:03,  8.05it/s]

  1%|▍                                   | 473/42525 [00:55<1:34:48,  7.39it/s]

  1%|▍                                   | 476/42525 [00:55<1:19:07,  8.86it/s]

  1%|▍                                   | 477/42525 [00:55<1:19:45,  8.79it/s]

  1%|▍                                   | 480/42525 [00:56<1:21:50,  8.56it/s]

  1%|▍                                   | 482/42525 [00:56<1:26:51,  8.07it/s]

  1%|▍                                   | 484/42525 [00:56<1:29:37,  7.82it/s]

  1%|▍                                   | 487/42525 [00:56<1:22:02,  8.54it/s]

  1%|▍                                   | 489/42525 [00:57<1:18:25,  8.93it/s]

  1%|▍                                   | 492/42525 [00:57<1:19:30,  8.81it/s]

  1%|▍                                   | 495/42525 [00:57<1:18:11,  8.96it/s]

  1%|▍                                   | 498/42525 [00:58<1:17:12,  9.07it/s]

  1%|▍                                   | 500/42525 [00:58<1:14:46,  9.37it/s]

  1%|▍                                   | 503/42525 [00:58<1:18:01,  8.98it/s]

  1%|▍                                   | 506/42525 [00:59<1:19:28,  8.81it/s]

  1%|▍                                   | 507/42525 [00:59<1:22:54,  8.45it/s]

  1%|▍                                   | 509/42525 [00:59<1:24:13,  8.31it/s]

  1%|▍                                   | 513/42525 [00:59<1:18:54,  8.87it/s]

  1%|▍                                   | 516/42525 [01:00<1:19:25,  8.82it/s]

  1%|▍                                   | 518/42525 [01:00<1:22:31,  8.48it/s]

  1%|▍                                   | 520/42525 [01:00<1:19:08,  8.85it/s]

  1%|▍                                   | 524/42525 [01:01<1:16:39,  9.13it/s]

  1%|▍                                   | 525/42525 [01:01<1:22:25,  8.49it/s]

  1%|▍                                   | 527/42525 [01:01<1:18:04,  8.96it/s]

  1%|▍                                   | 529/42525 [01:01<1:20:51,  8.66it/s]

  1%|▍                                   | 533/42525 [01:02<1:14:55,  9.34it/s]

  1%|▍                                   | 536/42525 [01:02<1:13:39,  9.50it/s]

  1%|▍                                   | 538/42525 [01:02<1:20:10,  8.73it/s]

  1%|▍                                   | 540/42525 [01:02<1:19:11,  8.84it/s]

  1%|▍                                   | 542/42525 [01:03<1:19:01,  8.85it/s]

  1%|▍                                   | 543/42525 [01:03<1:25:50,  8.15it/s]

  1%|▍                                   | 546/42525 [01:03<1:18:09,  8.95it/s]

  1%|▍                                   | 549/42525 [01:03<1:20:40,  8.67it/s]

  1%|▍                                   | 552/42525 [01:04<1:21:55,  8.54it/s]

  1%|▍                                   | 554/42525 [01:04<1:16:52,  9.10it/s]

  1%|▍                                   | 558/42525 [01:04<1:14:52,  9.34it/s]

  1%|▍                                   | 560/42525 [01:05<1:20:37,  8.67it/s]

  1%|▍                                   | 561/42525 [01:05<1:18:38,  8.89it/s]

  1%|▍                                   | 564/42525 [01:05<1:24:28,  8.28it/s]

  1%|▍                                   | 565/42525 [01:05<1:23:36,  8.36it/s]

  1%|▍                                   | 567/42525 [01:06<1:24:30,  8.28it/s]

  1%|▍                                   | 570/42525 [01:06<1:25:04,  8.22it/s]

  1%|▍                                   | 574/42525 [01:06<1:14:19,  9.41it/s]

  1%|▍                                   | 577/42525 [01:07<1:12:39,  9.62it/s]

  1%|▍                                   | 578/42525 [01:07<1:14:12,  9.42it/s]

  1%|▍                                   | 582/42525 [01:07<1:13:08,  9.56it/s]

  1%|▍                                   | 584/42525 [01:07<1:20:56,  8.64it/s]

  1%|▍                                   | 588/42525 [01:08<1:12:50,  9.60it/s]

  1%|▍                                   | 589/42525 [01:08<1:16:20,  9.16it/s]

  1%|▌                                   | 592/42525 [01:08<1:20:42,  8.66it/s]

  1%|▌                                   | 593/42525 [01:08<1:26:10,  8.11it/s]

  1%|▌                                   | 597/42525 [01:09<1:18:52,  8.86it/s]

  1%|▌                                   | 601/42525 [01:09<1:16:37,  9.12it/s]

  1%|▌                                   | 604/42525 [01:10<1:14:24,  9.39it/s]

  1%|▌                                   | 606/42525 [01:10<1:14:50,  9.34it/s]

  1%|▌                                   | 609/42525 [01:10<1:18:58,  8.85it/s]

  1%|▌                                   | 612/42525 [01:10<1:15:15,  9.28it/s]

  1%|▌                                   | 614/42525 [01:11<1:27:10,  8.01it/s]

  1%|▌                                   | 618/42525 [01:11<1:15:49,  9.21it/s]

  1%|▌                                   | 622/42525 [01:12<1:13:14,  9.54it/s]

  1%|▌                                   | 623/42525 [01:12<1:13:40,  9.48it/s]

  1%|▌                                   | 625/42525 [01:12<1:13:40,  9.48it/s]

  1%|▌                                   | 628/42525 [01:12<1:22:34,  8.46it/s]

  1%|▌                                   | 631/42525 [01:13<1:22:37,  8.45it/s]

  1%|▌                                   | 634/42525 [01:13<1:17:44,  8.98it/s]

  1%|▌                                   | 637/42525 [01:13<1:17:09,  9.05it/s]

  2%|▌                                   | 641/42525 [01:14<1:11:45,  9.73it/s]

  2%|▌                                   | 644/42525 [01:14<1:14:06,  9.42it/s]

  2%|▌                                   | 648/42525 [01:14<1:10:49,  9.85it/s]

  2%|▌                                   | 651/42525 [01:15<1:20:30,  8.67it/s]

  2%|▌                                   | 655/42525 [01:15<1:12:50,  9.58it/s]

  2%|▌                                   | 657/42525 [01:15<1:19:10,  8.81it/s]

  2%|▌                                   | 660/42525 [01:16<1:13:58,  9.43it/s]

  2%|▌                                   | 663/42525 [01:16<1:12:15,  9.65it/s]

  2%|▌                                   | 667/42525 [01:16<1:09:03, 10.10it/s]

  2%|▌                                   | 669/42525 [01:17<1:11:23,  9.77it/s]

  2%|▌                                   | 671/42525 [01:17<1:18:20,  8.90it/s]

  2%|▌                                   | 673/42525 [01:17<1:19:03,  8.82it/s]

  2%|▌                                   | 674/42525 [01:17<1:18:38,  8.87it/s]

  2%|▌                                   | 676/42525 [01:17<1:21:49,  8.52it/s]

  2%|▌                                   | 679/42525 [01:18<1:23:51,  8.32it/s]

  2%|▌                                   | 681/42525 [01:18<1:27:50,  7.94it/s]

  2%|▌                                   | 685/42525 [01:18<1:15:36,  9.22it/s]

  2%|▌                                   | 689/42525 [01:19<1:10:55,  9.83it/s]

  2%|▌                                   | 690/42525 [01:19<1:10:55,  9.83it/s]

  2%|▌                                   | 694/42525 [01:19<1:13:05,  9.54it/s]

  2%|▌                                   | 698/42525 [01:20<1:10:02,  9.95it/s]

  2%|▌                                   | 701/42525 [01:20<1:10:24,  9.90it/s]

  2%|▌                                   | 702/42525 [01:20<1:14:32,  9.35it/s]

  2%|▌                                   | 705/42525 [01:21<1:18:47,  8.85it/s]

  2%|▌                                   | 707/42525 [01:21<1:18:50,  8.84it/s]

  2%|▌                                   | 709/42525 [01:21<1:23:49,  8.31it/s]

  2%|▌                                   | 712/42525 [01:21<1:15:38,  9.21it/s]

  2%|▌                                   | 714/42525 [01:22<1:22:07,  8.49it/s]

  2%|▌                                   | 718/42525 [01:22<1:17:21,  9.01it/s]

  2%|▌                                   | 721/42525 [01:22<1:18:10,  8.91it/s]

  2%|▌                                   | 724/42525 [01:23<1:25:54,  8.11it/s]

  2%|▌                                   | 728/42525 [01:23<1:15:07,  9.27it/s]

  2%|▌                                   | 731/42525 [01:24<1:23:39,  8.33it/s]

  2%|▌                                   | 734/42525 [01:24<1:19:46,  8.73it/s]

  2%|▌                                   | 737/42525 [01:24<1:15:21,  9.24it/s]

  2%|▋                                   | 740/42525 [01:24<1:11:50,  9.69it/s]

  2%|▋                                   | 743/42525 [01:25<1:14:06,  9.40it/s]

  2%|▋                                   | 747/42525 [01:25<1:10:19,  9.90it/s]

  2%|▋                                   | 750/42525 [01:26<1:11:33,  9.73it/s]

  2%|▋                                   | 753/42525 [01:26<1:16:36,  9.09it/s]

  2%|▋                                   | 756/42525 [01:26<1:15:13,  9.25it/s]

  2%|▋                                   | 758/42525 [01:26<1:20:54,  8.60it/s]

  2%|▋                                   | 761/42525 [01:27<1:15:09,  9.26it/s]

  2%|▋                                   | 765/42525 [01:27<1:11:05,  9.79it/s]

  2%|▋                                   | 769/42525 [01:28<1:09:13, 10.05it/s]

  2%|▋                                   | 771/42525 [01:28<1:13:00,  9.53it/s]

  2%|▋                                   | 774/42525 [01:28<1:16:59,  9.04it/s]

  2%|▋                                   | 776/42525 [01:28<1:17:30,  8.98it/s]

  2%|▋                                   | 777/42525 [01:28<1:16:20,  9.11it/s]

  2%|▋                                   | 779/42525 [01:29<1:19:44,  8.73it/s]

  2%|▋                                   | 783/42525 [01:29<1:16:28,  9.10it/s]

  2%|▋                                   | 786/42525 [01:29<1:14:26,  9.34it/s]

  2%|▋                                   | 789/42525 [01:30<1:15:47,  9.18it/s]

  2%|▋                                   | 793/42525 [01:30<1:11:18,  9.75it/s]

  2%|▋                                   | 795/42525 [01:30<1:11:40,  9.70it/s]

  2%|▋                                   | 799/42525 [01:31<1:09:16, 10.04it/s]

  2%|▋                                   | 803/42525 [01:31<1:10:04,  9.92it/s]

  2%|▋                                   | 804/42525 [01:31<1:16:26,  9.10it/s]

  2%|▋                                   | 806/42525 [01:32<1:19:35,  8.74it/s]

  2%|▋                                   | 810/42525 [01:32<1:17:26,  8.98it/s]

  2%|▋                                   | 813/42525 [01:32<1:13:19,  9.48it/s]

  2%|▋                                   | 815/42525 [01:33<1:15:24,  9.22it/s]

  2%|▋                                   | 819/42525 [01:33<1:10:43,  9.83it/s]

  2%|▋                                   | 821/42525 [01:33<1:09:44,  9.97it/s]

  2%|▋                                   | 825/42525 [01:34<1:11:25,  9.73it/s]

  2%|▋                                   | 829/42525 [01:34<1:09:10, 10.05it/s]

  2%|▋                                   | 833/42525 [01:34<1:09:18, 10.02it/s]

  2%|▋                                   | 835/42525 [01:35<1:15:29,  9.20it/s]

  2%|▋                                   | 838/42525 [01:35<1:17:31,  8.96it/s]

  2%|▋                                   | 839/42525 [01:35<1:17:47,  8.93it/s]

  2%|▋                                   | 841/42525 [01:35<1:16:25,  9.09it/s]

  2%|▋                                   | 844/42525 [01:36<1:15:28,  9.20it/s]

  2%|▋                                   | 847/42525 [01:36<1:12:56,  9.52it/s]

  2%|▋                                   | 850/42525 [01:36<1:17:54,  8.92it/s]

  2%|▋                                   | 853/42525 [01:37<1:13:13,  9.49it/s]

  2%|▋                                   | 855/42525 [01:37<1:19:35,  8.73it/s]

  2%|▋                                   | 859/42525 [01:37<1:13:35,  9.44it/s]

  2%|▋                                   | 861/42525 [01:37<1:16:14,  9.11it/s]

  2%|▋                                   | 862/42525 [01:38<1:21:28,  8.52it/s]

  2%|▋                                   | 865/42525 [01:38<1:18:23,  8.86it/s]

  2%|▋                                   | 867/42525 [01:38<1:19:12,  8.77it/s]

  2%|▋                                   | 870/42525 [01:38<1:17:51,  8.92it/s]

  2%|▋                                   | 872/42525 [01:39<1:14:06,  9.37it/s]

  2%|▋                                   | 875/42525 [01:39<1:19:22,  8.74it/s]

  2%|▋                                   | 878/42525 [01:39<1:14:26,  9.32it/s]

  2%|▋                                   | 881/42525 [01:40<1:15:07,  9.24it/s]

  2%|▋                                   | 884/42525 [01:40<1:12:49,  9.53it/s]

  2%|▊                                   | 887/42525 [01:40<1:17:21,  8.97it/s]

  2%|▊                                   | 890/42525 [01:41<1:15:11,  9.23it/s]

  2%|▊                                   | 894/42525 [01:41<1:12:28,  9.57it/s]

  2%|▊                                   | 897/42525 [01:41<1:10:18,  9.87it/s]

  2%|▊                                   | 899/42525 [01:42<1:12:22,  9.59it/s]

  2%|▊                                   | 901/42525 [01:42<1:10:31,  9.84it/s]

  2%|▊                                   | 904/42525 [01:42<1:18:50,  8.80it/s]

  2%|▊                                   | 907/42525 [01:42<1:17:32,  8.95it/s]

  2%|▊                                   | 910/42525 [01:43<1:20:13,  8.65it/s]

  2%|▊                                   | 914/42525 [01:43<1:13:39,  9.41it/s]

  2%|▊                                   | 916/42525 [01:43<1:25:22,  8.12it/s]

  2%|▊                                   | 919/42525 [01:44<1:20:26,  8.62it/s]

  2%|▊                                   | 921/42525 [01:44<1:16:34,  9.05it/s]

  2%|▊                                   | 924/42525 [01:44<1:13:59,  9.37it/s]

  2%|▊                                   | 927/42525 [01:45<1:14:37,  9.29it/s]

  2%|▊                                   | 931/42525 [01:45<1:10:46,  9.80it/s]

  2%|▊                                   | 933/42525 [01:45<1:15:43,  9.15it/s]

  2%|▊                                   | 935/42525 [01:46<1:22:02,  8.45it/s]

  2%|▊                                   | 939/42525 [01:46<1:12:18,  9.59it/s]

  2%|▊                                   | 942/42525 [01:46<1:17:35,  8.93it/s]

  2%|▊                                   | 944/42525 [01:47<1:20:34,  8.60it/s]

  2%|▊                                   | 946/42525 [01:47<1:16:57,  9.00it/s]

  2%|▊                                   | 948/42525 [01:47<1:15:14,  9.21it/s]

  2%|▊                                   | 951/42525 [01:47<1:22:55,  8.36it/s]

  2%|▊                                   | 953/42525 [01:48<1:22:06,  8.44it/s]

  2%|▊                                   | 956/42525 [01:48<1:14:54,  9.25it/s]

  2%|▊                                   | 960/42525 [01:48<1:10:26,  9.84it/s]

  2%|▊                                   | 963/42525 [01:49<1:10:57,  9.76it/s]

  2%|▊                                   | 966/42525 [01:49<1:17:43,  8.91it/s]

  2%|▊                                   | 968/42525 [01:49<1:19:32,  8.71it/s]

  2%|▊                                   | 971/42525 [01:49<1:14:56,  9.24it/s]

  2%|▊                                   | 973/42525 [01:50<1:19:10,  8.75it/s]

  2%|▊                                   | 975/42525 [01:50<1:29:01,  7.78it/s]

  2%|▊                                   | 977/42525 [01:50<1:29:38,  7.72it/s]

  2%|▊                                   | 980/42525 [01:51<1:21:10,  8.53it/s]

  2%|▊                                   | 982/42525 [01:51<1:15:42,  9.15it/s]

  2%|▊                                   | 985/42525 [01:51<1:21:49,  8.46it/s]

  2%|▊                                   | 986/42525 [01:51<1:19:33,  8.70it/s]

  2%|▊                                   | 990/42525 [01:52<1:12:42,  9.52it/s]

  2%|▊                                   | 993/42525 [01:52<1:14:29,  9.29it/s]

  2%|▊                                   | 995/42525 [01:52<1:20:38,  8.58it/s]

  2%|▊                                   | 997/42525 [01:52<1:19:06,  8.75it/s]

  2%|▊                                  | 1001/42525 [01:53<1:16:22,  9.06it/s]

  2%|▊                                  | 1002/42525 [01:53<1:15:42,  9.14it/s]

  2%|▊                                  | 1005/42525 [01:53<1:15:34,  9.16it/s]

  2%|▊                                  | 1008/42525 [01:54<1:11:33,  9.67it/s]

  2%|▊                                  | 1010/42525 [01:54<1:24:43,  8.17it/s]

  2%|▊                                  | 1011/42525 [01:54<1:27:39,  7.89it/s]

  2%|▊                                  | 1014/42525 [01:54<1:30:27,  7.65it/s]

  2%|▊                                  | 1016/42525 [01:55<1:21:22,  8.50it/s]

  2%|▊                                  | 1020/42525 [01:55<1:15:12,  9.20it/s]

  2%|▊                                  | 1023/42525 [01:55<1:11:45,  9.64it/s]

  2%|▊                                  | 1026/42525 [01:56<1:10:58,  9.74it/s]

  2%|▊                                  | 1029/42525 [01:56<1:13:37,  9.39it/s]

  2%|▊                                  | 1032/42525 [01:56<1:17:35,  8.91it/s]

  2%|▊                                  | 1036/42525 [01:57<1:11:56,  9.61it/s]

  2%|▊                                  | 1039/42525 [01:57<1:21:38,  8.47it/s]

  2%|▊                                  | 1042/42525 [01:57<1:15:49,  9.12it/s]

  2%|▊                                  | 1044/42525 [01:58<1:20:07,  8.63it/s]

  2%|▊                                  | 1046/42525 [01:58<1:23:57,  8.23it/s]

  2%|▊                                  | 1050/42525 [01:58<1:12:55,  9.48it/s]

  2%|▊                                  | 1053/42525 [01:59<1:10:25,  9.81it/s]

  2%|▊                                  | 1054/42525 [01:59<1:11:19,  9.69it/s]

  2%|▊                                  | 1057/42525 [01:59<1:16:26,  9.04it/s]

  2%|▊                                  | 1060/42525 [01:59<1:19:23,  8.71it/s]

  2%|▊                                  | 1063/42525 [02:00<1:17:58,  8.86it/s]

  3%|▉                                  | 1065/42525 [02:00<1:21:04,  8.52it/s]

  3%|▉                                  | 1068/42525 [02:00<1:13:32,  9.39it/s]

  3%|▉                                  | 1071/42525 [02:01<1:11:22,  9.68it/s]

  3%|▉                                  | 1072/42525 [02:01<1:12:10,  9.57it/s]

  3%|▉                                  | 1075/42525 [02:01<1:15:48,  9.11it/s]

  3%|▉                                  | 1077/42525 [02:01<1:13:03,  9.46it/s]

  3%|▉                                  | 1081/42525 [02:02<1:11:32,  9.65it/s]

  3%|▉                                  | 1084/42525 [02:02<1:12:39,  9.51it/s]

  3%|▉                                  | 1087/42525 [02:02<1:11:45,  9.63it/s]

  3%|▉                                  | 1090/42525 [02:03<1:11:39,  9.64it/s]

  3%|▉                                  | 1092/42525 [02:03<1:18:48,  8.76it/s]

  3%|▉                                  | 1095/42525 [02:03<1:14:15,  9.30it/s]

  3%|▉                                  | 1098/42525 [02:04<1:12:10,  9.57it/s]

  3%|▉                                  | 1101/42525 [02:04<1:12:29,  9.52it/s]

  3%|▉                                  | 1104/42525 [02:04<1:15:48,  9.11it/s]

  3%|▉                                  | 1107/42525 [02:05<1:12:43,  9.49it/s]

  3%|▉                                  | 1110/42525 [02:05<1:13:20,  9.41it/s]

  3%|▉                                  | 1112/42525 [02:05<1:13:58,  9.33it/s]

  3%|▉                                  | 1114/42525 [02:05<1:11:02,  9.72it/s]

  3%|▉                                  | 1118/42525 [02:06<1:09:20,  9.95it/s]

  3%|▉                                  | 1119/42525 [02:06<1:11:48,  9.61it/s]

  3%|▉                                  | 1122/42525 [02:06<1:14:31,  9.26it/s]

  3%|▉                                  | 1126/42525 [02:06<1:10:00,  9.85it/s]

  3%|▉                                  | 1128/42525 [02:07<1:17:19,  8.92it/s]

  3%|▉                                  | 1130/42525 [02:07<1:13:31,  9.38it/s]

  3%|▉                                  | 1132/42525 [02:07<1:12:09,  9.56it/s]

  3%|▉                                  | 1135/42525 [02:07<1:15:17,  9.16it/s]

  3%|▉                                  | 1138/42525 [02:08<1:19:45,  8.65it/s]

  3%|▉                                  | 1140/42525 [02:08<1:24:09,  8.20it/s]

  3%|▉                                  | 1142/42525 [02:08<1:28:45,  7.77it/s]

  3%|▉                                  | 1143/42525 [02:08<1:25:28,  8.07it/s]

  3%|▉                                  | 1146/42525 [02:09<1:29:52,  7.67it/s]

  3%|▉                                  | 1150/42525 [02:09<1:15:20,  9.15it/s]

  3%|▉                                  | 1153/42525 [02:10<1:17:47,  8.86it/s]

  3%|▉                                  | 1157/42525 [02:10<1:11:30,  9.64it/s]

  3%|▉                                  | 1160/42525 [02:10<1:11:57,  9.58it/s]

  3%|▉                                  | 1162/42525 [02:11<1:16:12,  9.05it/s]

  3%|▉                                  | 1165/42525 [02:11<1:16:20,  9.03it/s]

  3%|▉                                  | 1166/42525 [02:11<1:16:28,  9.01it/s]

  3%|▉                                  | 1169/42525 [02:11<1:14:07,  9.30it/s]

  3%|▉                                  | 1171/42525 [02:12<1:22:40,  8.34it/s]

  3%|▉                                  | 1173/42525 [02:12<1:17:40,  8.87it/s]

  3%|▉                                  | 1177/42525 [02:12<1:11:17,  9.67it/s]

  3%|▉                                  | 1180/42525 [02:12<1:11:51,  9.59it/s]

  3%|▉                                  | 1181/42525 [02:13<1:18:43,  8.75it/s]

  3%|▉                                  | 1183/42525 [02:13<1:17:09,  8.93it/s]

  3%|▉                                  | 1186/42525 [02:13<1:17:00,  8.95it/s]

  3%|▉                                  | 1189/42525 [02:14<1:22:59,  8.30it/s]

  3%|▉                                  | 1191/42525 [02:14<1:18:27,  8.78it/s]

  3%|▉                                  | 1195/42525 [02:14<1:16:24,  9.02it/s]

  3%|▉                                  | 1199/42525 [02:15<1:11:03,  9.69it/s]

  3%|▉                                  | 1201/42525 [02:15<1:12:14,  9.53it/s]

  3%|▉                                  | 1202/42525 [02:15<1:13:47,  9.33it/s]

  3%|▉                                  | 1205/42525 [02:15<1:12:54,  9.45it/s]

  3%|▉                                  | 1207/42525 [02:16<1:17:33,  8.88it/s]

  3%|▉                                  | 1210/42525 [02:16<1:11:51,  9.58it/s]

  3%|▉                                  | 1214/42525 [02:16<1:10:38,  9.75it/s]

  3%|█                                  | 1217/42525 [02:17<1:11:23,  9.64it/s]

  3%|█                                  | 1221/42525 [02:17<1:12:58,  9.43it/s]

  3%|█                                  | 1224/42525 [02:17<1:11:06,  9.68it/s]

  3%|█                                  | 1228/42525 [02:18<1:09:00,  9.97it/s]

  3%|█                                  | 1231/42525 [02:18<1:10:06,  9.82it/s]

  3%|█                                  | 1232/42525 [02:18<1:16:30,  9.00it/s]

  3%|█                                  | 1235/42525 [02:18<1:14:10,  9.28it/s]

  3%|█                                  | 1238/42525 [02:19<1:13:57,  9.30it/s]

  3%|█                                  | 1241/42525 [02:19<1:18:15,  8.79it/s]

  3%|█                                  | 1242/42525 [02:19<1:16:22,  9.01it/s]

  3%|█                                  | 1246/42525 [02:20<1:11:59,  9.56it/s]

  3%|█                                  | 1249/42525 [02:20<1:11:51,  9.57it/s]

  3%|█                                  | 1250/42525 [02:20<1:18:26,  8.77it/s]

  3%|█                                  | 1254/42525 [02:21<1:16:11,  9.03it/s]

  3%|█                                  | 1257/42525 [02:21<1:12:06,  9.54it/s]

  3%|█                                  | 1259/42525 [02:21<1:16:19,  9.01it/s]

  3%|█                                  | 1261/42525 [02:21<1:14:43,  9.20it/s]

  3%|█                                  | 1264/42525 [02:22<1:16:57,  8.94it/s]

  3%|█                                  | 1266/42525 [02:22<1:22:22,  8.35it/s]

  3%|█                                  | 1270/42525 [02:22<1:13:14,  9.39it/s]

  3%|█                                  | 1272/42525 [02:22<1:11:14,  9.65it/s]

  3%|█                                  | 1275/42525 [02:23<1:17:01,  8.93it/s]

  3%|█                                  | 1276/42525 [02:23<1:18:10,  8.79it/s]

  3%|█                                  | 1280/42525 [02:23<1:13:04,  9.41it/s]

  3%|█                                  | 1283/42525 [02:24<1:14:32,  9.22it/s]

  3%|█                                  | 1285/42525 [02:24<1:22:18,  8.35it/s]

  3%|█                                  | 1287/42525 [02:24<1:16:21,  9.00it/s]

  3%|█                                  | 1290/42525 [02:25<1:20:52,  8.50it/s]

  3%|█                                  | 1292/42525 [02:25<1:15:32,  9.10it/s]

  3%|█                                  | 1295/42525 [02:25<1:15:47,  9.07it/s]

  3%|█                                  | 1296/42525 [02:25<1:14:14,  9.26it/s]

  3%|█                                  | 1298/42525 [02:25<1:12:37,  9.46it/s]

  3%|█                                  | 1301/42525 [02:26<1:13:58,  9.29it/s]

  3%|█                                  | 1303/42525 [02:26<1:11:03,  9.67it/s]

  3%|█                                  | 1306/42525 [02:26<1:19:42,  8.62it/s]

  3%|█                                  | 1309/42525 [02:27<1:16:06,  9.03it/s]

  3%|█                                  | 1312/42525 [02:27<1:12:10,  9.52it/s]

  3%|█                                  | 1315/42525 [02:27<1:12:26,  9.48it/s]

  3%|█                                  | 1317/42525 [02:27<1:17:03,  8.91it/s]

  3%|█                                  | 1320/42525 [02:28<1:12:55,  9.42it/s]

  3%|█                                  | 1323/42525 [02:28<1:12:20,  9.49it/s]

  3%|█                                  | 1325/42525 [02:28<1:10:13,  9.78it/s]

  3%|█                                  | 1327/42525 [02:28<1:10:03,  9.80it/s]

  3%|█                                  | 1331/42525 [02:29<1:09:51,  9.83it/s]

  3%|█                                  | 1334/42525 [02:29<1:10:30,  9.74it/s]

  3%|█                                  | 1337/42525 [02:30<1:15:55,  9.04it/s]

  3%|█                                  | 1339/42525 [02:30<1:18:52,  8.70it/s]

  3%|█                                  | 1341/42525 [02:30<1:26:15,  7.96it/s]

  3%|█                                  | 1343/42525 [02:30<1:20:14,  8.55it/s]

  3%|█                                  | 1346/42525 [02:31<1:23:47,  8.19it/s]

  3%|█                                  | 1349/42525 [02:31<1:14:50,  9.17it/s]

  3%|█                                  | 1350/42525 [02:31<1:14:48,  9.17it/s]

  3%|█                                  | 1352/42525 [02:31<1:12:26,  9.47it/s]

  3%|█                                  | 1355/42525 [02:32<1:13:21,  9.35it/s]

  3%|█                                  | 1358/42525 [02:32<1:14:13,  9.24it/s]

  3%|█                                  | 1361/42525 [02:32<1:16:43,  8.94it/s]

  3%|█                                  | 1364/42525 [02:33<1:11:37,  9.58it/s]

  3%|█                                  | 1366/42525 [02:33<1:10:22,  9.75it/s]

  3%|█▏                                 | 1368/42525 [02:33<1:11:09,  9.64it/s]

  3%|█▏                                 | 1370/42525 [02:33<1:11:15,  9.63it/s]

  3%|█▏                                 | 1373/42525 [02:34<1:16:33,  8.96it/s]

  3%|█▏                                 | 1375/42525 [02:34<1:13:02,  9.39it/s]

  3%|█▏                                 | 1378/42525 [02:34<1:15:30,  9.08it/s]

  3%|█▏                                 | 1382/42525 [02:34<1:10:17,  9.76it/s]

  3%|█▏                                 | 1384/42525 [02:35<1:11:43,  9.56it/s]

  3%|█▏                                 | 1386/42525 [02:35<1:09:39,  9.84it/s]

  3%|█▏                                 | 1389/42525 [02:35<1:18:39,  8.72it/s]

  3%|█▏                                 | 1391/42525 [02:36<1:23:49,  8.18it/s]

  3%|█▏                                 | 1393/42525 [02:36<1:23:45,  8.18it/s]

  3%|█▏                                 | 1396/42525 [02:36<1:15:12,  9.11it/s]

  3%|█▏                                 | 1400/42525 [02:36<1:09:56,  9.80it/s]

  3%|█▏                                 | 1403/42525 [02:37<1:12:47,  9.41it/s]

  3%|█▏                                 | 1404/42525 [02:37<1:12:17,  9.48it/s]

  3%|█▏                                 | 1407/42525 [02:37<1:15:36,  9.06it/s]

  3%|█▏                                 | 1409/42525 [02:38<1:26:53,  7.89it/s]

  3%|█▏                                 | 1413/42525 [02:38<1:15:02,  9.13it/s]

  3%|█▏                                 | 1415/42525 [02:38<1:12:12,  9.49it/s]

  3%|█▏                                 | 1418/42525 [02:38<1:11:52,  9.53it/s]

  3%|█▏                                 | 1422/42525 [02:39<1:13:27,  9.33it/s]

  3%|█▏                                 | 1424/42525 [02:39<1:15:29,  9.07it/s]

  3%|█▏                                 | 1426/42525 [02:39<1:18:56,  8.68it/s]

  3%|█▏                                 | 1427/42525 [02:40<1:24:47,  8.08it/s]

  3%|█▏                                 | 1430/42525 [02:40<1:21:11,  8.44it/s]

  3%|█▏                                 | 1431/42525 [02:40<1:18:03,  8.77it/s]

  3%|█▏                                 | 1435/42525 [02:40<1:11:25,  9.59it/s]

  3%|█▏                                 | 1437/42525 [02:41<1:09:39,  9.83it/s]

  3%|█▏                                 | 1441/42525 [02:41<1:12:17,  9.47it/s]

  3%|█▏                                 | 1444/42525 [02:41<1:20:20,  8.52it/s]

  3%|█▏                                 | 1446/42525 [02:42<1:18:39,  8.70it/s]

  3%|█▏                                 | 1449/42525 [02:42<1:17:24,  8.84it/s]

  3%|█▏                                 | 1452/42525 [02:42<1:19:42,  8.59it/s]

  3%|█▏                                 | 1454/42525 [02:43<1:25:15,  8.03it/s]

  3%|█▏                                 | 1458/42525 [02:43<1:16:06,  8.99it/s]

  3%|█▏                                 | 1461/42525 [02:43<1:17:28,  8.83it/s]

  3%|█▏                                 | 1463/42525 [02:44<1:19:59,  8.56it/s]

  3%|█▏                                 | 1466/42525 [02:44<1:14:31,  9.18it/s]

  3%|█▏                                 | 1469/42525 [02:44<1:14:49,  9.15it/s]

  3%|█▏                                 | 1470/42525 [02:44<1:14:34,  9.18it/s]

  3%|█▏                                 | 1472/42525 [02:45<1:18:20,  8.73it/s]

  3%|█▏                                 | 1476/42525 [02:45<1:12:10,  9.48it/s]

  3%|█▏                                 | 1477/42525 [02:45<1:14:19,  9.20it/s]

  3%|█▏                                 | 1481/42525 [02:45<1:10:17,  9.73it/s]

  3%|█▏                                 | 1484/42525 [02:46<1:08:57,  9.92it/s]

  3%|█▏                                 | 1487/42525 [02:46<1:08:50,  9.94it/s]

  4%|█▏                                 | 1489/42525 [02:46<1:18:51,  8.67it/s]

  4%|█▏                                 | 1490/42525 [02:46<1:16:14,  8.97it/s]

  4%|█▏                                 | 1493/42525 [02:47<1:14:51,  9.14it/s]

  4%|█▏                                 | 1497/42525 [02:47<1:11:59,  9.50it/s]

  4%|█▏                                 | 1499/42525 [02:47<1:09:57,  9.77it/s]

  4%|█▏                                 | 1501/42525 [02:48<1:14:36,  9.16it/s]

  4%|█▏                                 | 1504/42525 [02:48<1:14:04,  9.23it/s]

  4%|█▏                                 | 1508/42525 [02:48<1:10:35,  9.68it/s]

  4%|█▏                                 | 1511/42525 [02:49<1:09:31,  9.83it/s]

  4%|█▏                                 | 1514/42525 [02:49<1:10:37,  9.68it/s]

  4%|█▏                                 | 1516/42525 [02:49<1:16:00,  8.99it/s]

  4%|█▏                                 | 1518/42525 [02:49<1:11:47,  9.52it/s]

  4%|█▎                                 | 1521/42525 [02:50<1:17:36,  8.81it/s]

  4%|█▎                                 | 1523/42525 [02:50<1:17:42,  8.79it/s]

  4%|█▎                                 | 1526/42525 [02:50<1:16:12,  8.97it/s]

  4%|█▎                                 | 1530/42525 [02:51<1:10:29,  9.69it/s]

  4%|█▎                                 | 1532/42525 [02:51<1:09:19,  9.86it/s]

  4%|█▎                                 | 1535/42525 [02:51<1:11:11,  9.60it/s]

  4%|█▎                                 | 1537/42525 [02:51<1:12:38,  9.40it/s]

  4%|█▎                                 | 1540/42525 [02:52<1:10:08,  9.74it/s]

  4%|█▎                                 | 1542/42525 [02:52<1:14:29,  9.17it/s]

  4%|█▎                                 | 1544/42525 [02:52<1:13:43,  9.26it/s]

  4%|█▎                                 | 1547/42525 [02:53<1:15:42,  9.02it/s]

  4%|█▎                                 | 1549/42525 [02:53<1:13:43,  9.26it/s]

  4%|█▎                                 | 1552/42525 [02:53<1:13:56,  9.24it/s]

  4%|█▎                                 | 1555/42525 [02:53<1:14:47,  9.13it/s]

  4%|█▎                                 | 1556/42525 [02:54<1:19:01,  8.64it/s]

  4%|█▎                                 | 1560/42525 [02:54<1:15:42,  9.02it/s]

  4%|█▎                                 | 1562/42525 [02:54<1:15:16,  9.07it/s]

  4%|█▎                                 | 1564/42525 [02:54<1:19:01,  8.64it/s]

  4%|█▎                                 | 1568/42525 [02:55<1:16:30,  8.92it/s]

  4%|█▎                                 | 1570/42525 [02:55<1:17:34,  8.80it/s]

  4%|█▎                                 | 1573/42525 [02:55<1:11:59,  9.48it/s]

  4%|█▎                                 | 1576/42525 [02:56<1:16:22,  8.94it/s]

  4%|█▎                                 | 1579/42525 [02:56<1:13:18,  9.31it/s]

  4%|█▎                                 | 1581/42525 [02:56<1:12:43,  9.38it/s]

  4%|█▎                                 | 1582/42525 [02:56<1:11:41,  9.52it/s]

  4%|█▎                                 | 1585/42525 [02:57<1:12:51,  9.36it/s]

  4%|█▎                                 | 1587/42525 [02:57<1:14:38,  9.14it/s]

  4%|█▎                                 | 1589/42525 [02:57<1:13:10,  9.32it/s]

  4%|█▎                                 | 1590/42525 [02:57<1:12:30,  9.41it/s]

  4%|█▎                                 | 1593/42525 [02:58<1:20:08,  8.51it/s]

  4%|█▎                                 | 1597/42525 [02:58<1:11:38,  9.52it/s]

  4%|█▎                                 | 1600/42525 [02:58<1:12:56,  9.35it/s]

  4%|█▎                                 | 1603/42525 [02:59<1:14:02,  9.21it/s]

  4%|█▎                                 | 1606/42525 [02:59<1:12:07,  9.46it/s]

  4%|█▎                                 | 1609/42525 [02:59<1:14:57,  9.10it/s]

  4%|█▎                                 | 1611/42525 [03:00<1:26:13,  7.91it/s]

  4%|█▎                                 | 1613/42525 [03:00<1:21:04,  8.41it/s]

  4%|█▎                                 | 1617/42525 [03:00<1:14:38,  9.13it/s]

  4%|█▎                                 | 1619/42525 [03:01<1:22:00,  8.31it/s]

  4%|█▎                                 | 1621/42525 [03:01<1:24:39,  8.05it/s]

  4%|█▎                                 | 1623/42525 [03:01<1:25:54,  7.93it/s]

  4%|█▎                                 | 1626/42525 [03:01<1:21:34,  8.36it/s]

  4%|█▎                                 | 1630/42525 [03:02<1:11:44,  9.50it/s]

  4%|█▎                                 | 1632/42525 [03:02<1:15:36,  9.01it/s]

  4%|█▎                                 | 1633/42525 [03:02<1:14:26,  9.16it/s]

  4%|█▎                                 | 1636/42525 [03:02<1:23:49,  8.13it/s]

  4%|█▎                                 | 1639/42525 [03:03<1:15:11,  9.06it/s]

  4%|█▎                                 | 1642/42525 [03:03<1:18:02,  8.73it/s]

  4%|█▎                                 | 1644/42525 [03:03<1:22:22,  8.27it/s]

  4%|█▎                                 | 1645/42525 [03:03<1:19:08,  8.61it/s]

  4%|█▎                                 | 1648/42525 [03:04<1:26:08,  7.91it/s]

  4%|█▎                                 | 1651/42525 [03:04<1:23:13,  8.18it/s]

  4%|█▎                                 | 1653/42525 [03:05<1:27:29,  7.79it/s]

  4%|█▎                                 | 1656/42525 [03:05<1:19:27,  8.57it/s]

  4%|█▎                                 | 1658/42525 [03:05<1:14:02,  9.20it/s]

  4%|█▎                                 | 1661/42525 [03:05<1:22:50,  8.22it/s]

  4%|█▎                                 | 1662/42525 [03:06<1:26:58,  7.83it/s]

  4%|█▎                                 | 1664/42525 [03:06<1:25:55,  7.93it/s]

  4%|█▎                                 | 1667/42525 [03:06<1:23:42,  8.13it/s]

  4%|█▍                                 | 1671/42525 [03:07<1:13:13,  9.30it/s]

  4%|█▍                                 | 1673/42525 [03:07<1:10:44,  9.62it/s]

  4%|█▍                                 | 1677/42525 [03:07<1:12:19,  9.41it/s]

  4%|█▍                                 | 1679/42525 [03:07<1:16:00,  8.96it/s]

  4%|█▍                                 | 1681/42525 [03:08<1:24:49,  8.02it/s]

  4%|█▍                                 | 1685/42525 [03:08<1:12:54,  9.34it/s]

  4%|█▍                                 | 1687/42525 [03:08<1:10:38,  9.64it/s]

  4%|█▍                                 | 1690/42525 [03:09<1:19:18,  8.58it/s]

  4%|█▍                                 | 1691/42525 [03:09<1:17:06,  8.83it/s]

  4%|█▍                                 | 1695/42525 [03:09<1:14:58,  9.08it/s]

  4%|█▍                                 | 1699/42525 [03:10<1:10:05,  9.71it/s]

  4%|█▍                                 | 1702/42525 [03:10<1:11:04,  9.57it/s]

  4%|█▍                                 | 1705/42525 [03:10<1:13:05,  9.31it/s]

  4%|█▍                                 | 1708/42525 [03:11<1:16:54,  8.85it/s]

  4%|█▍                                 | 1710/42525 [03:11<1:15:15,  9.04it/s]

  4%|█▍                                 | 1713/42525 [03:11<1:11:39,  9.49it/s]

  4%|█▍                                 | 1716/42525 [03:12<1:15:48,  8.97it/s]

  4%|█▍                                 | 1718/42525 [03:12<1:21:44,  8.32it/s]

  4%|█▍                                 | 1721/42525 [03:12<1:17:34,  8.77it/s]

  4%|█▍                                 | 1724/42525 [03:12<1:16:17,  8.91it/s]

  4%|█▍                                 | 1727/42525 [03:13<1:13:37,  9.23it/s]

  4%|█▍                                 | 1729/42525 [03:13<1:13:38,  9.23it/s]

  4%|█▍                                 | 1731/42525 [03:13<1:11:39,  9.49it/s]

  4%|█▍                                 | 1733/42525 [03:13<1:16:24,  8.90it/s]

  4%|█▍                                 | 1736/42525 [03:14<1:18:38,  8.64it/s]

  4%|█▍                                 | 1739/42525 [03:14<1:13:24,  9.26it/s]

  4%|█▍                                 | 1742/42525 [03:14<1:14:22,  9.14it/s]

  4%|█▍                                 | 1746/42525 [03:15<1:13:34,  9.24it/s]

  4%|█▍                                 | 1749/42525 [03:15<1:14:23,  9.14it/s]

  4%|█▍                                 | 1752/42525 [03:16<1:15:42,  8.98it/s]

  4%|█▍                                 | 1756/42525 [03:16<1:09:19,  9.80it/s]

  4%|█▍                                 | 1758/42525 [03:16<1:08:02,  9.99it/s]

  4%|█▍                                 | 1761/42525 [03:16<1:09:58,  9.71it/s]

  4%|█▍                                 | 1763/42525 [03:17<1:12:36,  9.36it/s]

  4%|█▍                                 | 1766/42525 [03:17<1:17:40,  8.75it/s]

  4%|█▍                                 | 1768/42525 [03:17<1:17:37,  8.75it/s]

  4%|█▍                                 | 1770/42525 [03:17<1:15:39,  8.98it/s]

  4%|█▍                                 | 1772/42525 [03:18<1:21:22,  8.35it/s]

  4%|█▍                                 | 1774/42525 [03:18<1:20:00,  8.49it/s]

  4%|█▍                                 | 1776/42525 [03:18<1:15:27,  9.00it/s]

  4%|█▍                                 | 1778/42525 [03:18<1:16:52,  8.83it/s]

  4%|█▍                                 | 1780/42525 [03:19<1:15:04,  9.04it/s]

  4%|█▍                                 | 1782/42525 [03:19<1:23:50,  8.10it/s]

  4%|█▍                                 | 1784/42525 [03:19<1:19:07,  8.58it/s]

  4%|█▍                                 | 1788/42525 [03:19<1:10:02,  9.69it/s]

  4%|█▍                                 | 1792/42525 [03:20<1:07:12, 10.10it/s]

  4%|█▍                                 | 1796/42525 [03:20<1:07:21, 10.08it/s]

  4%|█▍                                 | 1799/42525 [03:21<1:10:02,  9.69it/s]

  4%|█▍                                 | 1803/42525 [03:21<1:08:02,  9.98it/s]

  4%|█▍                                 | 1805/42525 [03:21<1:10:12,  9.67it/s]

  4%|█▍                                 | 1808/42525 [03:22<1:15:28,  8.99it/s]

  4%|█▍                                 | 1811/42525 [03:22<1:11:51,  9.44it/s]

  4%|█▍                                 | 1815/42525 [03:22<1:08:15,  9.94it/s]

  4%|█▍                                 | 1817/42525 [03:22<1:07:30, 10.05it/s]

  4%|█▍                                 | 1821/42525 [03:23<1:08:57,  9.84it/s]

  4%|█▌                                 | 1825/42525 [03:23<1:10:17,  9.65it/s]

  4%|█▌                                 | 1827/42525 [03:24<1:14:31,  9.10it/s]

  4%|█▌                                 | 1830/42525 [03:24<1:17:39,  8.73it/s]

  4%|█▌                                 | 1832/42525 [03:24<1:15:26,  8.99it/s]

  4%|█▌                                 | 1835/42525 [03:24<1:11:25,  9.49it/s]

  4%|█▌                                 | 1837/42525 [03:25<1:08:57,  9.83it/s]

  4%|█▌                                 | 1840/42525 [03:25<1:14:53,  9.05it/s]

  4%|█▌                                 | 1843/42525 [03:25<1:23:12,  8.15it/s]

  4%|█▌                                 | 1846/42525 [03:26<1:15:51,  8.94it/s]

  4%|█▌                                 | 1848/42525 [03:26<1:23:24,  8.13it/s]

  4%|█▌                                 | 1850/42525 [03:26<1:19:12,  8.56it/s]

  4%|█▌                                 | 1852/42525 [03:26<1:30:10,  7.52it/s]

  4%|█▌                                 | 1854/42525 [03:27<1:36:15,  7.04it/s]

  4%|█▌                                 | 1857/42525 [03:27<1:23:25,  8.12it/s]

  4%|█▌                                 | 1859/42525 [03:27<1:19:56,  8.48it/s]

  4%|█▌                                 | 1862/42525 [03:28<1:14:22,  9.11it/s]

  4%|█▌                                 | 1864/42525 [03:28<1:19:09,  8.56it/s]

  4%|█▌                                 | 1867/42525 [03:28<1:11:33,  9.47it/s]

  4%|█▌                                 | 1871/42525 [03:29<1:10:32,  9.61it/s]

  4%|█▌                                 | 1874/42525 [03:29<1:09:06,  9.80it/s]

  4%|█▌                                 | 1876/42525 [03:29<1:09:51,  9.70it/s]

  4%|█▌                                 | 1880/42525 [03:30<1:12:13,  9.38it/s]

  4%|█▌                                 | 1883/42525 [03:30<1:16:18,  8.88it/s]

  4%|█▌                                 | 1887/42525 [03:30<1:10:05,  9.66it/s]

  4%|█▌                                 | 1891/42525 [03:31<1:08:09,  9.94it/s]

  4%|█▌                                 | 1893/42525 [03:31<1:07:22, 10.05it/s]

  4%|█▌                                 | 1897/42525 [03:31<1:08:44,  9.85it/s]

  4%|█▌                                 | 1901/42525 [03:32<1:07:17, 10.06it/s]

  4%|█▌                                 | 1905/42525 [03:32<1:10:27,  9.61it/s]

  4%|█▌                                 | 1907/42525 [03:32<1:12:38,  9.32it/s]

  4%|█▌                                 | 1909/42525 [03:33<1:18:58,  8.57it/s]

  4%|█▌                                 | 1912/42525 [03:33<1:11:50,  9.42it/s]

  4%|█▌                                 | 1913/42525 [03:33<1:11:54,  9.41it/s]

  5%|█▌                                 | 1917/42525 [03:33<1:10:23,  9.61it/s]

  5%|█▌                                 | 1921/42525 [03:34<1:07:55,  9.96it/s]

  5%|█▌                                 | 1922/42525 [03:34<1:11:53,  9.41it/s]

  5%|█▌                                 | 1925/42525 [03:34<1:11:38,  9.44it/s]

  5%|█▌                                 | 1928/42525 [03:35<1:11:15,  9.50it/s]

  5%|█▌                                 | 1929/42525 [03:35<1:11:42,  9.44it/s]

  5%|█▌                                 | 1933/42525 [03:35<1:12:56,  9.28it/s]

  5%|█▌                                 | 1936/42525 [03:35<1:12:12,  9.37it/s]

  5%|█▌                                 | 1938/42525 [03:36<1:14:26,  9.09it/s]

  5%|█▌                                 | 1940/42525 [03:36<1:17:33,  8.72it/s]

  5%|█▌                                 | 1943/42525 [03:36<1:17:07,  8.77it/s]

  5%|█▌                                 | 1945/42525 [03:36<1:17:13,  8.76it/s]

  5%|█▌                                 | 1946/42525 [03:37<1:17:31,  8.72it/s]

  5%|█▌                                 | 1949/42525 [03:37<1:19:56,  8.46it/s]

  5%|█▌                                 | 1952/42525 [03:37<1:12:18,  9.35it/s]

  5%|█▌                                 | 1954/42525 [03:37<1:11:26,  9.46it/s]

  5%|█▌                                 | 1957/42525 [03:38<1:12:25,  9.34it/s]

  5%|█▌                                 | 1960/42525 [03:38<1:11:09,  9.50it/s]

  5%|█▌                                 | 1963/42525 [03:38<1:09:26,  9.74it/s]

  5%|█▌                                 | 1966/42525 [03:39<1:11:53,  9.40it/s]

  5%|█▌                                 | 1970/42525 [03:39<1:08:44,  9.83it/s]

  5%|█▌                                 | 1972/42525 [03:39<1:09:39,  9.70it/s]

  5%|█▋                                 | 1976/42525 [03:40<1:10:51,  9.54it/s]

  5%|█▋                                 | 1977/42525 [03:40<1:10:17,  9.61it/s]

  5%|█▋                                 | 1980/42525 [03:40<1:19:49,  8.47it/s]

  5%|█▋                                 | 1983/42525 [03:41<1:12:57,  9.26it/s]

  5%|█▋                                 | 1985/42525 [03:41<1:16:16,  8.86it/s]

  5%|█▋                                 | 1988/42525 [03:41<1:13:30,  9.19it/s]

  5%|█▋                                 | 1990/42525 [03:41<1:18:45,  8.58it/s]

  5%|█▋                                 | 1991/42525 [03:41<1:16:20,  8.85it/s]

  5%|█▋                                 | 1994/42525 [03:42<1:12:54,  9.26it/s]

  5%|█▋                                 | 1997/42525 [03:42<1:15:55,  8.90it/s]

  5%|█▋                                 | 1999/42525 [03:42<1:16:03,  8.88it/s]

  5%|█▋                                 | 2002/42525 [03:43<1:13:35,  9.18it/s]

  5%|█▋                                 | 2006/42525 [03:43<1:08:31,  9.85it/s]

  5%|█▋                                 | 2009/42525 [03:43<1:08:28,  9.86it/s]

  5%|█▋                                 | 2010/42525 [03:43<1:09:24,  9.73it/s]

  5%|█▋                                 | 2012/42525 [03:44<1:13:18,  9.21it/s]

  5%|█▋                                 | 2016/42525 [03:44<1:10:43,  9.55it/s]

  5%|█▋                                 | 2020/42525 [03:44<1:08:10,  9.90it/s]

  5%|█▋                                 | 2024/42525 [03:45<1:07:00, 10.07it/s]

  5%|█▋                                 | 2028/42525 [03:45<1:07:49,  9.95it/s]

  5%|█▋                                 | 2030/42525 [03:45<1:07:18, 10.03it/s]

  5%|█▋                                 | 2034/42525 [03:46<1:09:42,  9.68it/s]

  5%|█▋                                 | 2037/42525 [03:46<1:09:34,  9.70it/s]

  5%|█▋                                 | 2041/42525 [03:47<1:07:21, 10.02it/s]

  5%|█▋                                 | 2044/42525 [03:47<1:11:38,  9.42it/s]

  5%|█▋                                 | 2048/42525 [03:47<1:08:18,  9.88it/s]

  5%|█▋                                 | 2050/42525 [03:48<1:07:24, 10.01it/s]

  5%|█▋                                 | 2053/42525 [03:48<1:12:18,  9.33it/s]

  5%|█▋                                 | 2056/42525 [03:48<1:11:17,  9.46it/s]

  5%|█▋                                 | 2059/42525 [03:49<1:08:46,  9.81it/s]

  5%|█▋                                 | 2063/42525 [03:49<1:07:01, 10.06it/s]

  5%|█▋                                 | 2065/42525 [03:49<1:06:36, 10.12it/s]

  5%|█▋                                 | 2068/42525 [03:49<1:14:21,  9.07it/s]

  5%|█▋                                 | 2070/42525 [03:50<1:19:32,  8.48it/s]

  5%|█▋                                 | 2072/42525 [03:50<1:18:13,  8.62it/s]

  5%|█▋                                 | 2076/42525 [03:50<1:14:08,  9.09it/s]

  5%|█▋                                 | 2078/42525 [03:51<1:11:02,  9.49it/s]

  5%|█▋                                 | 2081/42525 [03:51<1:12:44,  9.27it/s]

  5%|█▋                                 | 2083/42525 [03:51<1:20:12,  8.40it/s]

  5%|█▋                                 | 2084/42525 [03:51<1:18:35,  8.58it/s]

  5%|█▋                                 | 2088/42525 [03:52<1:11:31,  9.42it/s]

  5%|█▋                                 | 2092/42525 [03:52<1:12:16,  9.32it/s]

  5%|█▋                                 | 2095/42525 [03:52<1:13:14,  9.20it/s]

  5%|█▋                                 | 2099/42525 [03:53<1:08:51,  9.78it/s]

  5%|█▋                                 | 2101/42525 [03:53<1:17:10,  8.73it/s]

  5%|█▋                                 | 2103/42525 [03:53<1:15:14,  8.95it/s]

  5%|█▋                                 | 2105/42525 [03:54<1:10:46,  9.52it/s]

  5%|█▋                                 | 2108/42525 [03:54<1:10:53,  9.50it/s]

  5%|█▋                                 | 2111/42525 [03:54<1:12:45,  9.26it/s]

  5%|█▋                                 | 2112/42525 [03:54<1:18:38,  8.56it/s]

  5%|█▋                                 | 2116/42525 [03:55<1:14:49,  9.00it/s]

  5%|█▋                                 | 2119/42525 [03:55<1:10:50,  9.51it/s]

  5%|█▋                                 | 2122/42525 [03:55<1:17:37,  8.67it/s]

  5%|█▋                                 | 2125/42525 [03:56<1:16:43,  8.78it/s]

  5%|█▊                                 | 2128/42525 [03:56<1:11:55,  9.36it/s]

  5%|█▊                                 | 2132/42525 [03:56<1:08:30,  9.83it/s]

  5%|█▊                                 | 2133/42525 [03:57<1:11:09,  9.46it/s]

  5%|█▊                                 | 2137/42525 [03:57<1:11:40,  9.39it/s]

  5%|█▊                                 | 2140/42525 [03:57<1:15:29,  8.92it/s]

  5%|█▊                                 | 2142/42525 [03:58<1:12:14,  9.32it/s]

  5%|█▊                                 | 2145/42525 [03:58<1:20:09,  8.40it/s]

  5%|█▊                                 | 2147/42525 [03:58<1:15:12,  8.95it/s]

  5%|█▊                                 | 2151/42525 [03:59<1:11:26,  9.42it/s]

  5%|█▊                                 | 2153/42525 [03:59<1:15:19,  8.93it/s]

  5%|█▊                                 | 2156/42525 [03:59<1:10:59,  9.48it/s]

  5%|█▊                                 | 2157/42525 [03:59<1:16:45,  8.76it/s]

  5%|█▊                                 | 2160/42525 [04:00<1:18:10,  8.61it/s]

  5%|█▊                                 | 2162/42525 [04:00<1:15:51,  8.87it/s]

  5%|█▊                                 | 2165/42525 [04:00<1:11:50,  9.36it/s]

  5%|█▊                                 | 2167/42525 [04:00<1:09:26,  9.69it/s]

  5%|█▊                                 | 2169/42525 [04:01<1:14:23,  9.04it/s]

  5%|█▊                                 | 2172/42525 [04:01<1:13:02,  9.21it/s]

  5%|█▊                                 | 2175/42525 [04:01<1:09:49,  9.63it/s]

  5%|█▊                                 | 2177/42525 [04:01<1:14:13,  9.06it/s]

  5%|█▊                                 | 2178/42525 [04:02<1:12:44,  9.24it/s]

  5%|█▊                                 | 2181/42525 [04:02<1:14:43,  9.00it/s]

  5%|█▊                                 | 2183/42525 [04:02<1:18:13,  8.60it/s]

  5%|█▊                                 | 2185/42525 [04:02<1:12:50,  9.23it/s]

  5%|█▊                                 | 2187/42525 [04:03<1:12:24,  9.29it/s]

  5%|█▊                                 | 2190/42525 [04:03<1:10:52,  9.49it/s]

  5%|█▊                                 | 2192/42525 [04:03<1:17:58,  8.62it/s]

  5%|█▊                                 | 2194/42525 [04:03<1:13:54,  9.09it/s]

  5%|█▊                                 | 2197/42525 [04:04<1:10:16,  9.56it/s]

  5%|█▊                                 | 2199/42525 [04:04<1:12:25,  9.28it/s]

  5%|█▊                                 | 2201/42525 [04:04<1:19:14,  8.48it/s]

  5%|█▊                                 | 2204/42525 [04:04<1:11:55,  9.34it/s]

  5%|█▊                                 | 2207/42525 [04:05<1:14:41,  9.00it/s]

  5%|█▊                                 | 2209/42525 [04:05<1:21:06,  8.28it/s]

  5%|█▊                                 | 2211/42525 [04:05<1:23:40,  8.03it/s]

  5%|█▊                                 | 2213/42525 [04:05<1:25:49,  7.83it/s]

  5%|█▊                                 | 2216/42525 [04:06<1:16:31,  8.78it/s]

  5%|█▊                                 | 2219/42525 [04:06<1:14:42,  8.99it/s]

  5%|█▊                                 | 2222/42525 [04:06<1:17:12,  8.70it/s]

  5%|█▊                                 | 2225/42525 [04:07<1:18:52,  8.52it/s]

  5%|█▊                                 | 2228/42525 [04:07<1:16:20,  8.80it/s]

  5%|█▊                                 | 2231/42525 [04:07<1:10:57,  9.46it/s]

  5%|█▊                                 | 2233/42525 [04:08<1:12:50,  9.22it/s]

  5%|█▊                                 | 2235/42525 [04:08<1:16:09,  8.82it/s]

  5%|█▊                                 | 2237/42525 [04:08<1:21:22,  8.25it/s]

  5%|█▊                                 | 2240/42525 [04:09<1:19:40,  8.43it/s]

  5%|█▊                                 | 2242/42525 [04:09<1:14:16,  9.04it/s]

  5%|█▊                                 | 2245/42525 [04:09<1:09:50,  9.61it/s]

  5%|█▊                                 | 2248/42525 [04:09<1:09:44,  9.63it/s]

  5%|█▊                                 | 2251/42525 [04:10<1:08:01,  9.87it/s]

  5%|█▊                                 | 2255/42525 [04:10<1:11:05,  9.44it/s]

  5%|█▊                                 | 2257/42525 [04:10<1:08:46,  9.76it/s]

  5%|█▊                                 | 2260/42525 [04:11<1:12:29,  9.26it/s]

  5%|█▊                                 | 2262/42525 [04:11<1:17:07,  8.70it/s]

  5%|█▊                                 | 2264/42525 [04:11<1:12:14,  9.29it/s]

  5%|█▊                                 | 2267/42525 [04:11<1:16:39,  8.75it/s]

  5%|█▊                                 | 2268/42525 [04:12<1:15:37,  8.87it/s]

  5%|█▊                                 | 2272/42525 [04:12<1:13:47,  9.09it/s]

  5%|█▊                                 | 2276/42525 [04:12<1:08:46,  9.75it/s]

  5%|█▊                                 | 2278/42525 [04:13<1:10:40,  9.49it/s]

  5%|█▉                                 | 2281/42525 [04:13<1:16:07,  8.81it/s]

  5%|█▉                                 | 2285/42525 [04:13<1:09:24,  9.66it/s]

  5%|█▉                                 | 2288/42525 [04:14<1:09:28,  9.65it/s]

  5%|█▉                                 | 2290/42525 [04:14<1:13:43,  9.09it/s]

  5%|█▉                                 | 2292/42525 [04:14<1:11:14,  9.41it/s]

  5%|█▉                                 | 2295/42525 [04:14<1:12:42,  9.22it/s]

  5%|█▉                                 | 2298/42525 [04:15<1:11:56,  9.32it/s]

  5%|█▉                                 | 2300/42525 [04:15<1:17:58,  8.60it/s]

  5%|█▉                                 | 2302/42525 [04:15<1:18:56,  8.49it/s]

  5%|█▉                                 | 2304/42525 [04:15<1:18:20,  8.56it/s]

  5%|█▉                                 | 2307/42525 [04:16<1:12:03,  9.30it/s]

  5%|█▉                                 | 2309/42525 [04:16<1:22:37,  8.11it/s]

  5%|█▉                                 | 2312/42525 [04:16<1:17:43,  8.62it/s]

  5%|█▉                                 | 2316/42525 [04:17<1:10:20,  9.53it/s]

  5%|█▉                                 | 2319/42525 [04:17<1:09:45,  9.61it/s]

  5%|█▉                                 | 2322/42525 [04:17<1:09:33,  9.63it/s]

  5%|█▉                                 | 2326/42525 [04:18<1:07:02,  9.99it/s]

  5%|█▉                                 | 2330/42525 [04:18<1:09:40,  9.62it/s]

  5%|█▉                                 | 2331/42525 [04:18<1:11:32,  9.36it/s]

  5%|█▉                                 | 2334/42525 [04:19<1:16:18,  8.78it/s]

  5%|█▉                                 | 2337/42525 [04:19<1:13:27,  9.12it/s]

  6%|█▉                                 | 2339/42525 [04:19<1:12:10,  9.28it/s]

  6%|█▉                                 | 2342/42525 [04:20<1:13:05,  9.16it/s]

  6%|█▉                                 | 2345/42525 [04:20<1:15:11,  8.91it/s]

  6%|█▉                                 | 2349/42525 [04:20<1:09:13,  9.67it/s]

  6%|█▉                                 | 2350/42525 [04:20<1:09:22,  9.65it/s]

  6%|█▉                                 | 2353/42525 [04:21<1:13:55,  9.06it/s]

  6%|█▉                                 | 2355/42525 [04:21<1:11:36,  9.35it/s]

  6%|█▉                                 | 2358/42525 [04:21<1:09:53,  9.58it/s]

  6%|█▉                                 | 2361/42525 [04:22<1:11:06,  9.41it/s]

  6%|█▉                                 | 2363/42525 [04:22<1:17:11,  8.67it/s]

  6%|█▉                                 | 2366/42525 [04:22<1:12:58,  9.17it/s]

  6%|█▉                                 | 2368/42525 [04:22<1:09:47,  9.59it/s]

  6%|█▉                                 | 2372/42525 [04:23<1:11:19,  9.38it/s]

  6%|█▉                                 | 2375/42525 [04:23<1:09:59,  9.56it/s]

  6%|█▉                                 | 2377/42525 [04:23<1:07:56,  9.85it/s]

  6%|█▉                                 | 2381/42525 [04:24<1:10:27,  9.50it/s]

  6%|█▉                                 | 2383/42525 [04:24<1:11:45,  9.32it/s]

  6%|█▉                                 | 2385/42525 [04:24<1:18:13,  8.55it/s]

  6%|█▉                                 | 2388/42525 [04:24<1:11:46,  9.32it/s]

  6%|█▉                                 | 2390/42525 [04:25<1:12:31,  9.22it/s]

  6%|█▉                                 | 2392/42525 [04:25<1:19:08,  8.45it/s]

  6%|█▉                                 | 2396/42525 [04:25<1:10:14,  9.52it/s]

  6%|█▉                                 | 2399/42525 [04:26<1:12:29,  9.23it/s]

  6%|█▉                                 | 2402/42525 [04:26<1:20:54,  8.27it/s]

  6%|█▉                                 | 2403/42525 [04:26<1:18:26,  8.52it/s]

  6%|█▉                                 | 2406/42525 [04:27<1:15:01,  8.91it/s]

  6%|█▉                                 | 2409/42525 [04:27<1:18:35,  8.51it/s]

  6%|█▉                                 | 2410/42525 [04:27<1:18:21,  8.53it/s]

  6%|█▉                                 | 2413/42525 [04:27<1:18:07,  8.56it/s]

  6%|█▉                                 | 2415/42525 [04:28<1:21:28,  8.21it/s]

  6%|█▉                                 | 2418/42525 [04:28<1:15:10,  8.89it/s]

  6%|█▉                                 | 2419/42525 [04:28<1:21:02,  8.25it/s]

  6%|█▉                                 | 2422/42525 [04:28<1:23:10,  8.04it/s]

  6%|█▉                                 | 2426/42525 [04:29<1:11:43,  9.32it/s]

  6%|██                                 | 2430/42525 [04:29<1:08:19,  9.78it/s]

  6%|██                                 | 2432/42525 [04:29<1:07:15,  9.93it/s]

  6%|██                                 | 2435/42525 [04:30<1:11:28,  9.35it/s]

  6%|██                                 | 2438/42525 [04:30<1:11:52,  9.30it/s]

  6%|██                                 | 2441/42525 [04:30<1:14:17,  8.99it/s]

  6%|██                                 | 2445/42525 [04:31<1:08:53,  9.70it/s]

  6%|██                                 | 2448/42525 [04:31<1:07:21,  9.92it/s]

  6%|██                                 | 2452/42525 [04:32<1:05:31, 10.19it/s]

  6%|██                                 | 2454/42525 [04:32<1:06:46, 10.00it/s]

  6%|██                                 | 2457/42525 [04:32<1:11:00,  9.40it/s]

  6%|██                                 | 2460/42525 [04:32<1:10:12,  9.51it/s]

  6%|██                                 | 2462/42525 [04:33<1:08:13,  9.79it/s]

  6%|██                                 | 2466/42525 [04:33<1:10:27,  9.48it/s]

  6%|██                                 | 2468/42525 [04:33<1:12:03,  9.26it/s]

  6%|██                                 | 2471/42525 [04:34<1:12:37,  9.19it/s]

  6%|██                                 | 2475/42525 [04:34<1:08:01,  9.81it/s]

  6%|██                                 | 2476/42525 [04:34<1:09:11,  9.65it/s]

  6%|██                                 | 2480/42525 [04:34<1:08:12,  9.78it/s]

  6%|██                                 | 2482/42525 [04:35<1:10:12,  9.51it/s]

  6%|██                                 | 2484/42525 [04:35<1:14:00,  9.02it/s]

  6%|██                                 | 2487/42525 [04:35<1:17:33,  8.60it/s]

  6%|██                                 | 2489/42525 [04:36<1:14:14,  8.99it/s]

  6%|██                                 | 2491/42525 [04:36<1:22:06,  8.13it/s]

  6%|██                                 | 2495/42525 [04:36<1:10:45,  9.43it/s]

  6%|██                                 | 2498/42525 [04:37<1:11:38,  9.31it/s]

  6%|██                                 | 2499/42525 [04:37<1:13:17,  9.10it/s]

  6%|██                                 | 2501/42525 [04:37<1:16:42,  8.70it/s]

  6%|██                                 | 2505/42525 [04:37<1:12:52,  9.15it/s]

  6%|██                                 | 2507/42525 [04:38<1:15:52,  8.79it/s]

  6%|██                                 | 2511/42525 [04:38<1:11:51,  9.28it/s]

  6%|██                                 | 2515/42525 [04:38<1:08:04,  9.80it/s]

  6%|██                                 | 2519/42525 [04:39<1:06:49,  9.98it/s]

  6%|██                                 | 2523/42525 [04:39<1:06:35, 10.01it/s]

  6%|██                                 | 2525/42525 [04:39<1:06:38, 10.00it/s]

  6%|██                                 | 2528/42525 [04:40<1:15:46,  8.80it/s]

  6%|██                                 | 2530/42525 [04:40<1:21:16,  8.20it/s]

  6%|██                                 | 2533/42525 [04:40<1:17:15,  8.63it/s]

  6%|██                                 | 2535/42525 [04:41<1:21:38,  8.16it/s]

  6%|██                                 | 2536/42525 [04:41<1:19:07,  8.42it/s]

  6%|██                                 | 2538/42525 [04:41<1:15:14,  8.86it/s]

  6%|██                                 | 2542/42525 [04:41<1:12:07,  9.24it/s]

  6%|██                                 | 2545/42525 [04:42<1:15:40,  8.80it/s]

  6%|██                                 | 2547/42525 [04:42<1:20:36,  8.27it/s]

  6%|██                                 | 2551/42525 [04:42<1:12:12,  9.23it/s]

  6%|██                                 | 2553/42525 [04:43<1:11:13,  9.35it/s]

  6%|██                                 | 2557/42525 [04:43<1:09:31,  9.58it/s]

  6%|██                                 | 2559/42525 [04:43<1:10:19,  9.47it/s]

  6%|██                                 | 2561/42525 [04:43<1:19:09,  8.42it/s]

  6%|██                                 | 2564/42525 [04:44<1:20:14,  8.30it/s]

  6%|██                                 | 2567/42525 [04:44<1:13:45,  9.03it/s]

  6%|██                                 | 2570/42525 [04:44<1:10:26,  9.45it/s]

  6%|██                                 | 2574/42525 [04:45<1:07:44,  9.83it/s]

  6%|██                                 | 2577/42525 [04:45<1:17:47,  8.56it/s]

  6%|██                                 | 2579/42525 [04:45<1:17:29,  8.59it/s]

  6%|██                                 | 2581/42525 [04:46<1:20:49,  8.24it/s]

  6%|██▏                                | 2584/42525 [04:46<1:11:31,  9.31it/s]

  6%|██▏                                | 2586/42525 [04:46<1:11:18,  9.34it/s]

  6%|██▏                                | 2588/42525 [04:47<1:18:57,  8.43it/s]

  6%|██▏                                | 2591/42525 [04:47<1:18:07,  8.52it/s]

  6%|██▏                                | 2594/42525 [04:47<1:18:43,  8.45it/s]

  6%|██▏                                | 2597/42525 [04:48<1:16:19,  8.72it/s]

  6%|██▏                                | 2601/42525 [04:48<1:11:04,  9.36it/s]

  6%|██▏                                | 2604/42525 [04:48<1:10:32,  9.43it/s]

  6%|██▏                                | 2607/42525 [04:49<1:09:46,  9.53it/s]

  6%|██▏                                | 2608/42525 [04:49<1:15:58,  8.76it/s]

  6%|██▏                                | 2611/42525 [04:49<1:13:25,  9.06it/s]

  6%|██▏                                | 2613/42525 [04:49<1:18:33,  8.47it/s]

  6%|██▏                                | 2614/42525 [04:49<1:19:29,  8.37it/s]

  6%|██▏                                | 2617/42525 [04:50<1:18:24,  8.48it/s]

  6%|██▏                                | 2619/42525 [04:50<1:14:42,  8.90it/s]

  6%|██▏                                | 2621/42525 [04:50<1:19:48,  8.33it/s]

  6%|██▏                                | 2624/42525 [04:51<1:16:51,  8.65it/s]

  6%|██▏                                | 2625/42525 [04:51<1:22:17,  8.08it/s]

  6%|██▏                                | 2628/42525 [04:51<1:18:57,  8.42it/s]

  6%|██▏                                | 2630/42525 [04:51<1:25:18,  7.79it/s]

  6%|██▏                                | 2633/42525 [04:52<1:14:29,  8.92it/s]

  6%|██▏                                | 2636/42525 [04:52<1:10:34,  9.42it/s]

  6%|██▏                                | 2638/42525 [04:52<1:09:56,  9.51it/s]

  6%|██▏                                | 2641/42525 [04:52<1:12:02,  9.23it/s]

  6%|██▏                                | 2645/42525 [04:53<1:07:56,  9.78it/s]

  6%|██▏                                | 2648/42525 [04:53<1:10:51,  9.38it/s]

  6%|██▏                                | 2650/42525 [04:53<1:21:55,  8.11it/s]

  6%|██▏                                | 2652/42525 [04:54<1:17:27,  8.58it/s]

  6%|██▏                                | 2655/42525 [04:54<1:18:19,  8.48it/s]

  6%|██▏                                | 2656/42525 [04:54<1:23:25,  7.96it/s]

  6%|██▏                                | 2659/42525 [04:55<1:20:31,  8.25it/s]

  6%|██▏                                | 2661/42525 [04:55<1:25:15,  7.79it/s]

  6%|██▏                                | 2664/42525 [04:55<1:18:06,  8.50it/s]

  6%|██▏                                | 2668/42525 [04:56<1:10:34,  9.41it/s]

  6%|██▏                                | 2670/42525 [04:56<1:14:23,  8.93it/s]

  6%|██▏                                | 2673/42525 [04:56<1:10:55,  9.36it/s]

  6%|██▏                                | 2677/42525 [04:57<1:07:19,  9.86it/s]

  6%|██▏                                | 2681/42525 [04:57<1:07:27,  9.84it/s]

  6%|██▏                                | 2685/42525 [04:57<1:06:04, 10.05it/s]

  6%|██▏                                | 2689/42525 [04:58<1:06:06, 10.04it/s]

  6%|██▏                                | 2693/42525 [04:58<1:05:48, 10.09it/s]

  6%|██▏                                | 2695/42525 [04:58<1:05:42, 10.10it/s]

  6%|██▏                                | 2698/42525 [04:59<1:13:41,  9.01it/s]

  6%|██▏                                | 2702/42525 [04:59<1:09:53,  9.50it/s]

  6%|██▏                                | 2705/42525 [04:59<1:11:18,  9.31it/s]

  6%|██▏                                | 2707/42525 [05:00<1:11:23,  9.30it/s]

  6%|██▏                                | 2710/42525 [05:00<1:08:19,  9.71it/s]

  6%|██▏                                | 2714/42525 [05:00<1:05:59, 10.05it/s]

  6%|██▏                                | 2716/42525 [05:01<1:13:56,  8.97it/s]

  6%|██▏                                | 2718/42525 [05:01<1:10:20,  9.43it/s]

  6%|██▏                                | 2720/42525 [05:01<1:14:28,  8.91it/s]

  6%|██▏                                | 2723/42525 [05:01<1:15:17,  8.81it/s]

  6%|██▏                                | 2725/42525 [05:02<1:17:42,  8.54it/s]

  6%|██▏                                | 2728/42525 [05:02<1:16:35,  8.66it/s]

  6%|██▏                                | 2730/42525 [05:02<1:12:29,  9.15it/s]

  6%|██▏                                | 2733/42525 [05:02<1:11:22,  9.29it/s]

  6%|██▎                                | 2737/42525 [05:03<1:11:34,  9.27it/s]

  6%|██▎                                | 2740/42525 [05:03<1:12:32,  9.14it/s]

  6%|██▎                                | 2743/42525 [05:04<1:11:15,  9.31it/s]

  6%|██▎                                | 2745/42525 [05:04<1:14:16,  8.93it/s]

  6%|██▎                                | 2749/42525 [05:04<1:08:13,  9.72it/s]

  6%|██▎                                | 2752/42525 [05:05<1:06:58,  9.90it/s]

  6%|██▎                                | 2754/42525 [05:05<1:11:59,  9.21it/s]

  6%|██▎                                | 2756/42525 [05:05<1:20:51,  8.20it/s]

  6%|██▎                                | 2757/42525 [05:05<1:18:39,  8.43it/s]

  6%|██▎                                | 2760/42525 [05:05<1:18:37,  8.43it/s]

  6%|██▎                                | 2763/42525 [05:06<1:14:12,  8.93it/s]

  7%|██▎                                | 2765/42525 [05:06<1:21:44,  8.11it/s]

  7%|██▎                                | 2768/42525 [05:06<1:17:49,  8.51it/s]

  7%|██▎                                | 2769/42525 [05:07<1:15:34,  8.77it/s]

  7%|██▎                                | 2772/42525 [05:07<1:20:10,  8.26it/s]

  7%|██▎                                | 2773/42525 [05:07<1:21:29,  8.13it/s]

  7%|██▎                                | 2777/42525 [05:07<1:14:22,  8.91it/s]

  7%|██▎                                | 2779/42525 [05:08<1:10:35,  9.38it/s]

  7%|██▎                                | 2782/42525 [05:08<1:11:14,  9.30it/s]

  7%|██▎                                | 2784/42525 [05:08<1:10:15,  9.43it/s]

  7%|██▎                                | 2787/42525 [05:08<1:13:02,  9.07it/s]

  7%|██▎                                | 2791/42525 [05:09<1:10:06,  9.44it/s]

  7%|██▎                                | 2795/42525 [05:09<1:08:32,  9.66it/s]

  7%|██▎                                | 2797/42525 [05:10<1:14:00,  8.95it/s]

  7%|██▎                                | 2798/42525 [05:10<1:12:34,  9.12it/s]

  7%|██▎                                | 2802/42525 [05:10<1:09:34,  9.52it/s]

  7%|██▎                                | 2806/42525 [05:10<1:06:13,  9.99it/s]

  7%|██▎                                | 2810/42525 [05:11<1:09:09,  9.57it/s]

  7%|██▎                                | 2813/42525 [05:11<1:06:56,  9.89it/s]

  7%|██▎                                | 2815/42525 [05:11<1:06:10, 10.00it/s]

  7%|██▎                                | 2817/42525 [05:12<1:10:46,  9.35it/s]

  7%|██▎                                | 2821/42525 [05:12<1:10:46,  9.35it/s]

  7%|██▎                                | 2824/42525 [05:12<1:16:32,  8.65it/s]

  7%|██▎                                | 2826/42525 [05:13<1:17:36,  8.53it/s]

  7%|██▎                                | 2829/42525 [05:13<1:14:51,  8.84it/s]

  7%|██▎                                | 2831/42525 [05:13<1:10:45,  9.35it/s]

  7%|██▎                                | 2833/42525 [05:13<1:09:56,  9.46it/s]

  7%|██▎                                | 2836/42525 [05:14<1:08:50,  9.61it/s]

  7%|██▎                                | 2838/42525 [05:14<1:18:04,  8.47it/s]

  7%|██▎                                | 2841/42525 [05:14<1:14:16,  8.91it/s]

  7%|██▎                                | 2845/42525 [05:15<1:09:56,  9.46it/s]

  7%|██▎                                | 2847/42525 [05:15<1:12:28,  9.12it/s]

  7%|██▎                                | 2850/42525 [05:15<1:15:25,  8.77it/s]

  7%|██▎                                | 2852/42525 [05:16<1:20:58,  8.17it/s]

  7%|██▎                                | 2856/42525 [05:16<1:10:23,  9.39it/s]

  7%|██▎                                | 2859/42525 [05:16<1:13:40,  8.97it/s]

  7%|██▎                                | 2861/42525 [05:17<1:13:44,  8.97it/s]

  7%|██▎                                | 2864/42525 [05:17<1:09:49,  9.47it/s]

  7%|██▎                                | 2868/42525 [05:17<1:06:19,  9.97it/s]

  7%|██▎                                | 2870/42525 [05:17<1:11:28,  9.25it/s]

  7%|██▎                                | 2872/42525 [05:18<1:13:05,  9.04it/s]

  7%|██▎                                | 2876/42525 [05:18<1:09:06,  9.56it/s]

  7%|██▎                                | 2879/42525 [05:18<1:08:13,  9.68it/s]

  7%|██▎                                | 2882/42525 [05:19<1:10:56,  9.31it/s]

  7%|██▎                                | 2883/42525 [05:19<1:16:39,  8.62it/s]

  7%|██▎                                | 2885/42525 [05:19<1:12:49,  9.07it/s]

  7%|██▍                                | 2887/42525 [05:19<1:12:10,  9.15it/s]

  7%|██▍                                | 2890/42525 [05:20<1:15:53,  8.70it/s]

  7%|██▍                                | 2891/42525 [05:20<1:20:32,  8.20it/s]

  7%|██▍                                | 2894/42525 [05:20<1:19:29,  8.31it/s]

  7%|██▍                                | 2897/42525 [05:20<1:12:57,  9.05it/s]

  7%|██▍                                | 2901/42525 [05:21<1:09:24,  9.52it/s]

  7%|██▍                                | 2905/42525 [05:21<1:06:17,  9.96it/s]

  7%|██▍                                | 2908/42525 [05:22<1:07:51,  9.73it/s]

  7%|██▍                                | 2911/42525 [05:22<1:06:21,  9.95it/s]

  7%|██▍                                | 2912/42525 [05:22<1:12:50,  9.06it/s]

  7%|██▍                                | 2916/42525 [05:22<1:08:57,  9.57it/s]

  7%|██▍                                | 2918/42525 [05:23<1:11:20,  9.25it/s]

  7%|██▍                                | 2921/42525 [05:23<1:11:39,  9.21it/s]

  7%|██▍                                | 2924/42525 [05:23<1:07:43,  9.75it/s]

  7%|██▍                                | 2928/42525 [05:24<1:08:21,  9.66it/s]

  7%|██▍                                | 2931/42525 [05:24<1:08:39,  9.61it/s]

  7%|██▍                                | 2932/42525 [05:24<1:12:48,  9.06it/s]

  7%|██▍                                | 2936/42525 [05:25<1:09:52,  9.44it/s]

  7%|██▍                                | 2937/42525 [05:25<1:10:01,  9.42it/s]

  7%|██▍                                | 2940/42525 [05:25<1:13:43,  8.95it/s]

  7%|██▍                                | 2941/42525 [05:25<1:15:13,  8.77it/s]

  7%|██▍                                | 2945/42525 [05:26<1:12:32,  9.09it/s]

  7%|██▍                                | 2947/42525 [05:26<1:11:36,  9.21it/s]

  7%|██▍                                | 2951/42525 [05:26<1:11:13,  9.26it/s]

  7%|██▍                                | 2954/42525 [05:27<1:12:17,  9.12it/s]

  7%|██▍                                | 2956/42525 [05:27<1:13:10,  9.01it/s]

  7%|██▍                                | 2959/42525 [05:27<1:09:55,  9.43it/s]

  7%|██▍                                | 2962/42525 [05:27<1:08:27,  9.63it/s]

  7%|██▍                                | 2965/42525 [05:28<1:09:15,  9.52it/s]

  7%|██▍                                | 2969/42525 [05:28<1:07:13,  9.81it/s]

  7%|██▍                                | 2970/42525 [05:28<1:12:44,  9.06it/s]

  7%|██▍                                | 2973/42525 [05:29<1:20:18,  8.21it/s]

  7%|██▍                                | 2976/42525 [05:29<1:14:17,  8.87it/s]

  7%|██▍                                | 2980/42525 [05:29<1:07:45,  9.73it/s]

  7%|██▍                                | 2984/42525 [05:30<1:05:19, 10.09it/s]

  7%|██▍                                | 2986/42525 [05:30<1:10:17,  9.38it/s]

  7%|██▍                                | 2990/42525 [05:30<1:07:52,  9.71it/s]

  7%|██▍                                | 2992/42525 [05:31<1:14:49,  8.81it/s]

  7%|██▍                                | 2993/42525 [05:31<1:12:58,  9.03it/s]

  7%|██▍                                | 2995/42525 [05:31<1:12:53,  9.04it/s]

  7%|██▍                                | 2998/42525 [05:31<1:20:24,  8.19it/s]

  7%|██▍                                | 3002/42525 [05:32<1:10:24,  9.36it/s]

  7%|██▍                                | 3006/42525 [05:32<1:08:44,  9.58it/s]

  7%|██▍                                | 3007/42525 [05:32<1:09:07,  9.53it/s]

  7%|██▍                                | 3010/42525 [05:33<1:13:17,  8.99it/s]

  7%|██▍                                | 3013/42525 [05:33<1:12:45,  9.05it/s]

  7%|██▍                                | 3015/42525 [05:33<1:13:43,  8.93it/s]

  7%|██▍                                | 3018/42525 [05:34<1:08:43,  9.58it/s]

  7%|██▍                                | 3020/42525 [05:34<1:08:17,  9.64it/s]

  7%|██▍                                | 3024/42525 [05:34<1:05:31, 10.05it/s]

  7%|██▍                                | 3028/42525 [05:35<1:04:07, 10.26it/s]

  7%|██▍                                | 3030/42525 [05:35<1:04:12, 10.25it/s]

  7%|██▍                                | 3032/42525 [05:35<1:05:08, 10.11it/s]

  7%|██▍                                | 3035/42525 [05:35<1:08:28,  9.61it/s]

  7%|██▍                                | 3037/42525 [05:35<1:14:55,  8.78it/s]

  7%|██▌                                | 3038/42525 [05:36<1:14:49,  8.80it/s]

  7%|██▌                                | 3040/42525 [05:36<1:16:14,  8.63it/s]

  7%|██▌                                | 3043/42525 [05:36<1:17:56,  8.44it/s]

  7%|██▌                                | 3046/42525 [05:37<1:17:41,  8.47it/s]

  7%|██▌                                | 3048/42525 [05:37<1:12:03,  9.13it/s]

  7%|██▌                                | 3052/42525 [05:37<1:11:44,  9.17it/s]

  7%|██▌                                | 3056/42525 [05:38<1:06:43,  9.86it/s]

  7%|██▌                                | 3058/42525 [05:38<1:05:27, 10.05it/s]

  7%|██▌                                | 3061/42525 [05:38<1:10:53,  9.28it/s]

  7%|██▌                                | 3065/42525 [05:38<1:07:35,  9.73it/s]

  7%|██▌                                | 3068/42525 [05:39<1:07:16,  9.78it/s]

  7%|██▌                                | 3071/42525 [05:39<1:07:18,  9.77it/s]

  7%|██▌                                | 3074/42525 [05:39<1:05:56,  9.97it/s]

  7%|██▌                                | 3076/42525 [05:40<1:11:43,  9.17it/s]

  7%|██▌                                | 3079/42525 [05:40<1:14:39,  8.81it/s]

  7%|██▌                                | 3082/42525 [05:40<1:15:42,  8.68it/s]

  7%|██▌                                | 3084/42525 [05:41<1:19:33,  8.26it/s]

  7%|██▌                                | 3087/42525 [05:41<1:10:48,  9.28it/s]

  7%|██▌                                | 3091/42525 [05:41<1:06:36,  9.87it/s]

  7%|██▌                                | 3093/42525 [05:41<1:05:08, 10.09it/s]

  7%|██▌                                | 3097/42525 [05:42<1:05:38, 10.01it/s]

  7%|██▌                                | 3100/42525 [05:42<1:08:25,  9.60it/s]

  7%|██▌                                | 3102/42525 [05:42<1:12:18,  9.09it/s]

  7%|██▌                                | 3104/42525 [05:43<1:17:55,  8.43it/s]

  7%|██▌                                | 3107/42525 [05:43<1:19:45,  8.24it/s]

  7%|██▌                                | 3108/42525 [05:43<1:18:43,  8.34it/s]

  7%|██▌                                | 3111/42525 [05:44<1:19:45,  8.24it/s]

  7%|██▌                                | 3114/42525 [05:44<1:11:21,  9.21it/s]

  7%|██▌                                | 3117/42525 [05:44<1:14:53,  8.77it/s]

  7%|██▌                                | 3118/42525 [05:44<1:19:49,  8.23it/s]

  7%|██▌                                | 3121/42525 [05:45<1:19:17,  8.28it/s]

  7%|██▌                                | 3125/42525 [05:45<1:09:31,  9.45it/s]

  7%|██▌                                | 3129/42525 [05:45<1:06:22,  9.89it/s]

  7%|██▌                                | 3131/42525 [05:46<1:13:12,  8.97it/s]

  7%|██▌                                | 3133/42525 [05:46<1:12:36,  9.04it/s]

  7%|██▌                                | 3135/42525 [05:46<1:24:03,  7.81it/s]

  7%|██▌                                | 3137/42525 [05:46<1:18:40,  8.34it/s]

  7%|██▌                                | 3140/42525 [05:47<1:11:47,  9.14it/s]

  7%|██▌                                | 3143/42525 [05:47<1:11:35,  9.17it/s]

  7%|██▌                                | 3145/42525 [05:47<1:16:24,  8.59it/s]

  7%|██▌                                | 3148/42525 [05:48<1:09:53,  9.39it/s]

  7%|██▌                                | 3151/42525 [05:48<1:11:44,  9.15it/s]

  7%|██▌                                | 3154/42525 [05:48<1:13:44,  8.90it/s]

  7%|██▌                                | 3156/42525 [05:49<1:11:48,  9.14it/s]

  7%|██▌                                | 3159/42525 [05:49<1:12:57,  8.99it/s]

  7%|██▌                                | 3160/42525 [05:49<1:14:50,  8.77it/s]

  7%|██▌                                | 3163/42525 [05:49<1:10:50,  9.26it/s]

  7%|██▌                                | 3165/42525 [05:50<1:17:46,  8.43it/s]

  7%|██▌                                | 3168/42525 [05:50<1:10:24,  9.32it/s]

  7%|██▌                                | 3169/42525 [05:50<1:13:26,  8.93it/s]

  7%|██▌                                | 3172/42525 [05:50<1:10:43,  9.27it/s]

  7%|██▌                                | 3173/42525 [05:50<1:10:35,  9.29it/s]

  7%|██▌                                | 3175/42525 [05:51<1:09:05,  9.49it/s]

  7%|██▌                                | 3177/42525 [05:51<1:09:06,  9.49it/s]

  7%|██▌                                | 3179/42525 [05:51<1:08:58,  9.51it/s]

  7%|██▌                                | 3183/42525 [05:51<1:07:59,  9.64it/s]

  7%|██▌                                | 3186/42525 [05:52<1:05:49,  9.96it/s]

  7%|██▌                                | 3188/42525 [05:52<1:06:38,  9.84it/s]

  8%|██▋                                | 3190/42525 [05:52<1:08:53,  9.52it/s]

  8%|██▋                                | 3193/42525 [05:53<1:14:37,  8.79it/s]

  8%|██▋                                | 3195/42525 [05:53<1:09:46,  9.39it/s]

  8%|██▋                                | 3198/42525 [05:53<1:12:57,  8.98it/s]

  8%|██▋                                | 3201/42525 [05:53<1:08:42,  9.54it/s]

  8%|██▋                                | 3203/42525 [05:54<1:13:11,  8.95it/s]

  8%|██▋                                | 3205/42525 [05:54<1:12:27,  9.04it/s]

  8%|██▋                                | 3207/42525 [05:54<1:08:28,  9.57it/s]

  8%|██▋                                | 3210/42525 [05:54<1:16:08,  8.61it/s]

  8%|██▋                                | 3212/42525 [05:55<1:16:36,  8.55it/s]

  8%|██▋                                | 3215/42525 [05:55<1:22:40,  7.93it/s]

  8%|██▋                                | 3217/42525 [05:55<1:14:30,  8.79it/s]

  8%|██▋                                | 3220/42525 [05:56<1:14:40,  8.77it/s]

  8%|██▋                                | 3222/42525 [05:56<1:13:25,  8.92it/s]

  8%|██▋                                | 3223/42525 [05:56<1:13:51,  8.87it/s]

  8%|██▋                                | 3225/42525 [05:56<1:10:31,  9.29it/s]

  8%|██▋                                | 3227/42525 [05:56<1:14:05,  8.84it/s]

  8%|██▋                                | 3229/42525 [05:57<1:12:06,  9.08it/s]

  8%|██▋                                | 3231/42525 [05:57<1:14:34,  8.78it/s]

  8%|██▋                                | 3234/42525 [05:57<1:14:02,  8.84it/s]

  8%|██▋                                | 3238/42525 [05:58<1:10:56,  9.23it/s]

  8%|██▋                                | 3241/42525 [05:58<1:09:54,  9.37it/s]

  8%|██▋                                | 3243/42525 [05:58<1:10:54,  9.23it/s]

  8%|██▋                                | 3245/42525 [05:58<1:09:11,  9.46it/s]

  8%|██▋                                | 3248/42525 [05:59<1:11:02,  9.21it/s]

  8%|██▋                                | 3250/42525 [05:59<1:16:50,  8.52it/s]

  8%|██▋                                | 3252/42525 [05:59<1:21:40,  8.01it/s]

  8%|██▋                                | 3255/42525 [06:00<1:15:32,  8.66it/s]

  8%|██▋                                | 3259/42525 [06:00<1:07:45,  9.66it/s]

  8%|██▋                                | 3263/42525 [06:00<1:06:06,  9.90it/s]

  8%|██▋                                | 3266/42525 [06:01<1:12:53,  8.98it/s]

  8%|██▋                                | 3268/42525 [06:01<1:09:59,  9.35it/s]

  8%|██▋                                | 3272/42525 [06:01<1:07:30,  9.69it/s]

  8%|██▋                                | 3276/42525 [06:02<1:05:46,  9.94it/s]

  8%|██▋                                | 3278/42525 [06:02<1:12:10,  9.06it/s]

  8%|██▋                                | 3282/42525 [06:02<1:07:14,  9.73it/s]

  8%|██▋                                | 3285/42525 [06:03<1:07:12,  9.73it/s]

  8%|██▋                                | 3288/42525 [06:03<1:06:24,  9.85it/s]

  8%|██▋                                | 3289/42525 [06:03<1:08:24,  9.56it/s]

  8%|██▋                                | 3292/42525 [06:03<1:14:41,  8.75it/s]

  8%|██▋                                | 3295/42525 [06:04<1:10:43,  9.25it/s]

  8%|██▋                                | 3299/42525 [06:04<1:06:16,  9.86it/s]

  8%|██▋                                | 3302/42525 [06:04<1:06:35,  9.82it/s]

  8%|██▋                                | 3306/42525 [06:05<1:06:09,  9.88it/s]

  8%|██▋                                | 3307/42525 [06:05<1:06:28,  9.83it/s]

  8%|██▋                                | 3309/42525 [06:05<1:07:07,  9.74it/s]

  8%|██▋                                | 3313/42525 [06:06<1:09:30,  9.40it/s]

  8%|██▋                                | 3315/42525 [06:06<1:07:48,  9.64it/s]

  8%|██▋                                | 3318/42525 [06:06<1:07:48,  9.64it/s]

  8%|██▋                                | 3321/42525 [06:06<1:09:53,  9.35it/s]

  8%|██▋                                | 3323/42525 [06:07<1:15:11,  8.69it/s]

  8%|██▋                                | 3327/42525 [06:07<1:08:36,  9.52it/s]

  8%|██▋                                | 3328/42525 [06:07<1:14:40,  8.75it/s]

  8%|██▋                                | 3330/42525 [06:07<1:16:49,  8.50it/s]

  8%|██▋                                | 3334/42525 [06:08<1:13:34,  8.88it/s]

  8%|██▋                                | 3336/42525 [06:08<1:17:57,  8.38it/s]

  8%|██▋                                | 3339/42525 [06:08<1:12:09,  9.05it/s]

  8%|██▊                                | 3342/42525 [06:09<1:15:09,  8.69it/s]

  8%|██▊                                | 3346/42525 [06:09<1:08:07,  9.59it/s]

  8%|██▊                                | 3348/42525 [06:09<1:07:37,  9.66it/s]

  8%|██▊                                | 3351/42525 [06:10<1:09:12,  9.43it/s]

  8%|██▊                                | 3355/42525 [06:10<1:05:58,  9.89it/s]

  8%|██▊                                | 3359/42525 [06:11<1:05:07, 10.02it/s]

  8%|██▊                                | 3362/42525 [06:11<1:09:11,  9.43it/s]

  8%|██▊                                | 3364/42525 [06:11<1:10:17,  9.28it/s]

  8%|██▊                                | 3368/42525 [06:12<1:09:36,  9.37it/s]

  8%|██▊                                | 3371/42525 [06:12<1:15:47,  8.61it/s]

  8%|██▊                                | 3374/42525 [06:12<1:16:33,  8.52it/s]

  8%|██▊                                | 3375/42525 [06:12<1:15:32,  8.64it/s]

  8%|██▊                                | 3379/42525 [06:13<1:11:38,  9.11it/s]

  8%|██▊                                | 3382/42525 [06:13<1:09:08,  9.43it/s]

  8%|██▊                                | 3386/42525 [06:13<1:06:09,  9.86it/s]

  8%|██▊                                | 3388/42525 [06:14<1:04:40, 10.09it/s]

  8%|██▊                                | 3392/42525 [06:14<1:07:00,  9.73it/s]

  8%|██▊                                | 3396/42525 [06:14<1:05:02, 10.03it/s]

  8%|██▊                                | 3398/42525 [06:15<1:04:07, 10.17it/s]

  8%|██▊                                | 3400/42525 [06:15<1:05:16,  9.99it/s]

  8%|██▊                                | 3403/42525 [06:15<1:11:12,  9.16it/s]

  8%|██▊                                | 3406/42525 [06:16<1:08:05,  9.57it/s]

  8%|██▊                                | 3407/42525 [06:16<1:09:42,  9.35it/s]

  8%|██▊                                | 3410/42525 [06:16<1:10:15,  9.28it/s]

  8%|██▊                                | 3412/42525 [06:16<1:10:03,  9.31it/s]

  8%|██▊                                | 3413/42525 [06:16<1:17:18,  8.43it/s]

  8%|██▊                                | 3415/42525 [06:17<1:13:50,  8.83it/s]

  8%|██▊                                | 3417/42525 [06:17<1:15:04,  8.68it/s]

  8%|██▊                                | 3420/42525 [06:17<1:12:58,  8.93it/s]

  8%|██▊                                | 3422/42525 [06:17<1:16:57,  8.47it/s]

  8%|██▊                                | 3426/42525 [06:18<1:09:47,  9.34it/s]

  8%|██▊                                | 3428/42525 [06:18<1:15:28,  8.63it/s]

  8%|██▊                                | 3431/42525 [06:18<1:15:06,  8.67it/s]

  8%|██▊                                | 3433/42525 [06:19<1:13:35,  8.85it/s]

  8%|██▊                                | 3436/42525 [06:19<1:13:01,  8.92it/s]

  8%|██▊                                | 3437/42525 [06:19<1:11:24,  9.12it/s]

  8%|██▊                                | 3441/42525 [06:19<1:08:18,  9.54it/s]

  8%|██▊                                | 3444/42525 [06:20<1:06:15,  9.83it/s]

  8%|██▊                                | 3446/42525 [06:20<1:08:56,  9.45it/s]

  8%|██▊                                | 3449/42525 [06:20<1:10:53,  9.19it/s]

  8%|██▊                                | 3452/42525 [06:21<1:11:14,  9.14it/s]

  8%|██▊                                | 3454/42525 [06:21<1:07:42,  9.62it/s]

  8%|██▊                                | 3458/42525 [06:21<1:07:06,  9.70it/s]

  8%|██▊                                | 3462/42525 [06:22<1:05:10,  9.99it/s]

  8%|██▊                                | 3466/42525 [06:22<1:03:53, 10.19it/s]

  8%|██▊                                | 3468/42525 [06:22<1:07:15,  9.68it/s]

  8%|██▊                                | 3471/42525 [06:23<1:06:54,  9.73it/s]

  8%|██▊                                | 3474/42525 [06:23<1:10:53,  9.18it/s]

  8%|██▊                                | 3476/42525 [06:23<1:08:08,  9.55it/s]

  8%|██▊                                | 3478/42525 [06:23<1:08:30,  9.50it/s]

  8%|██▊                                | 3481/42525 [06:24<1:17:08,  8.44it/s]

  8%|██▊                                | 3482/42525 [06:24<1:15:41,  8.60it/s]

  8%|██▊                                | 3485/42525 [06:24<1:18:16,  8.31it/s]

  8%|██▊                                | 3488/42525 [06:25<1:17:32,  8.39it/s]

  8%|██▊                                | 3490/42525 [06:25<1:21:25,  7.99it/s]

  8%|██▊                                | 3493/42525 [06:25<1:21:27,  7.99it/s]

  8%|██▉                                | 3494/42525 [06:25<1:25:00,  7.65it/s]

  8%|██▉                                | 3497/42525 [06:26<1:22:42,  7.86it/s]

  8%|██▉                                | 3499/42525 [06:26<1:23:06,  7.83it/s]

  8%|██▉                                | 3502/42525 [06:26<1:10:49,  9.18it/s]

  8%|██▉                                | 3504/42525 [06:26<1:07:54,  9.58it/s]

  8%|██▉                                | 3506/42525 [06:27<1:08:19,  9.52it/s]

  8%|██▉                                | 3510/42525 [06:27<1:09:32,  9.35it/s]

  8%|██▉                                | 3513/42525 [06:27<1:09:49,  9.31it/s]

  8%|██▉                                | 3515/42525 [06:28<1:13:17,  8.87it/s]

  8%|██▉                                | 3518/42525 [06:28<1:14:12,  8.76it/s]

  8%|██▉                                | 3521/42525 [06:28<1:09:33,  9.35it/s]

  8%|██▉                                | 3524/42525 [06:29<1:12:50,  8.92it/s]

  8%|██▉                                | 3527/42525 [06:29<1:15:55,  8.56it/s]

  8%|██▉                                | 3531/42525 [06:29<1:08:49,  9.44it/s]

  8%|██▉                                | 3532/42525 [06:30<1:12:53,  8.92it/s]

  8%|██▉                                | 3536/42525 [06:30<1:08:34,  9.48it/s]

  8%|██▉                                | 3540/42525 [06:30<1:05:12,  9.97it/s]

  8%|██▉                                | 3542/42525 [06:31<1:06:39,  9.75it/s]

  8%|██▉                                | 3544/42525 [06:31<1:19:21,  8.19it/s]

  8%|██▉                                | 3546/42525 [06:31<1:20:56,  8.03it/s]

  8%|██▉                                | 3548/42525 [06:31<1:22:10,  7.90it/s]

  8%|██▉                                | 3550/42525 [06:32<1:17:29,  8.38it/s]

  8%|██▉                                | 3553/42525 [06:32<1:14:06,  8.76it/s]

  8%|██▉                                | 3555/42525 [06:32<1:19:54,  8.13it/s]

  8%|██▉                                | 3557/42525 [06:32<1:18:00,  8.33it/s]

  8%|██▉                                | 3558/42525 [06:33<1:23:14,  7.80it/s]

  8%|██▉                                | 3562/42525 [06:33<1:14:38,  8.70it/s]

  8%|██▉                                | 3566/42525 [06:33<1:07:29,  9.62it/s]

  8%|██▉                                | 3568/42525 [06:34<1:11:24,  9.09it/s]

  8%|██▉                                | 3571/42525 [06:34<1:12:01,  9.01it/s]

  8%|██▉                                | 3575/42525 [06:34<1:06:41,  9.73it/s]

  8%|██▉                                | 3579/42525 [06:35<1:04:46, 10.02it/s]

  8%|██▉                                | 3582/42525 [06:35<1:15:19,  8.62it/s]

  8%|██▉                                | 3585/42525 [06:36<1:14:02,  8.77it/s]

  8%|██▉                                | 3589/42525 [06:36<1:10:58,  9.14it/s]

  8%|██▉                                | 3591/42525 [06:36<1:14:17,  8.73it/s]

  8%|██▉                                | 3594/42525 [06:37<1:11:32,  9.07it/s]

  8%|██▉                                | 3595/42525 [06:37<1:14:46,  8.68it/s]

  8%|██▉                                | 3599/42525 [06:37<1:11:47,  9.04it/s]

  8%|██▉                                | 3601/42525 [06:37<1:11:47,  9.04it/s]

  8%|██▉                                | 3604/42525 [06:38<1:07:31,  9.61it/s]

  8%|██▉                                | 3606/42525 [06:38<1:12:17,  8.97it/s]

  8%|██▉                                | 3609/42525 [06:38<1:09:02,  9.40it/s]

  8%|██▉                                | 3612/42525 [06:38<1:07:00,  9.68it/s]

  9%|██▉                                | 3616/42525 [06:39<1:04:04, 10.12it/s]

  9%|██▉                                | 3618/42525 [06:39<1:06:18,  9.78it/s]

  9%|██▉                                | 3621/42525 [06:39<1:12:19,  8.96it/s]

  9%|██▉                                | 3623/42525 [06:40<1:21:31,  7.95it/s]

  9%|██▉                                | 3625/42525 [06:40<1:13:24,  8.83it/s]

  9%|██▉                                | 3628/42525 [06:40<1:17:06,  8.41it/s]

  9%|██▉                                | 3631/42525 [06:41<1:15:14,  8.61it/s]

  9%|██▉                                | 3634/42525 [06:41<1:09:43,  9.30it/s]

  9%|██▉                                | 3636/42525 [06:41<1:11:08,  9.11it/s]

  9%|██▉                                | 3637/42525 [06:41<1:17:16,  8.39it/s]

  9%|██▉                                | 3641/42525 [06:42<1:08:16,  9.49it/s]

  9%|██▉                                | 3644/42525 [06:42<1:06:29,  9.75it/s]

  9%|███                                | 3647/42525 [06:42<1:11:18,  9.09it/s]

  9%|███                                | 3649/42525 [06:43<1:21:20,  7.97it/s]

  9%|███                                | 3651/42525 [06:43<1:16:11,  8.50it/s]

  9%|███                                | 3653/42525 [06:43<1:18:50,  8.22it/s]

  9%|███                                | 3655/42525 [06:43<1:15:10,  8.62it/s]

  9%|███                                | 3657/42525 [06:44<1:16:56,  8.42it/s]

  9%|███                                | 3659/42525 [06:44<1:20:02,  8.09it/s]

  9%|███                                | 3663/42525 [06:44<1:09:34,  9.31it/s]

  9%|███                                | 3666/42525 [06:45<1:12:10,  8.97it/s]

  9%|███                                | 3670/42525 [06:45<1:08:51,  9.40it/s]

  9%|███                                | 3672/42525 [06:45<1:15:56,  8.53it/s]

  9%|███                                | 3675/42525 [06:46<1:11:16,  9.08it/s]

  9%|███                                | 3679/42525 [06:46<1:06:59,  9.66it/s]

  9%|███                                | 3681/42525 [06:46<1:13:55,  8.76it/s]

  9%|███                                | 3685/42525 [06:47<1:07:00,  9.66it/s]

  9%|███                                | 3687/42525 [06:47<1:10:34,  9.17it/s]

  9%|███                                | 3690/42525 [06:47<1:16:07,  8.50it/s]

  9%|███                                | 3691/42525 [06:47<1:20:54,  8.00it/s]

  9%|███                                | 3695/42525 [06:48<1:11:01,  9.11it/s]

  9%|███                                | 3699/42525 [06:48<1:08:36,  9.43it/s]

  9%|███                                | 3702/42525 [06:48<1:12:23,  8.94it/s]

  9%|███                                | 3704/42525 [06:49<1:11:17,  9.08it/s]

  9%|███                                | 3707/42525 [06:49<1:12:25,  8.93it/s]

  9%|███                                | 3709/42525 [06:49<1:09:31,  9.30it/s]

  9%|███                                | 3713/42525 [06:50<1:04:41, 10.00it/s]

  9%|███                                | 3715/42525 [06:50<1:04:46,  9.99it/s]

  9%|███                                | 3718/42525 [06:50<1:06:02,  9.79it/s]

  9%|███                                | 3720/42525 [06:50<1:04:39, 10.00it/s]

  9%|███                                | 3723/42525 [06:51<1:07:41,  9.55it/s]

  9%|███                                | 3726/42525 [06:51<1:05:21,  9.89it/s]

  9%|███                                | 3728/42525 [06:51<1:04:12, 10.07it/s]

  9%|███                                | 3731/42525 [06:52<1:12:07,  8.96it/s]

  9%|███                                | 3734/42525 [06:52<1:11:14,  9.07it/s]

  9%|███                                | 3736/42525 [06:52<1:07:52,  9.53it/s]

  9%|███                                | 3738/42525 [06:52<1:11:49,  9.00it/s]

  9%|███                                | 3742/42525 [06:53<1:08:06,  9.49it/s]

  9%|███                                | 3745/42525 [06:53<1:07:03,  9.64it/s]

  9%|███                                | 3747/42525 [06:53<1:10:53,  9.12it/s]

  9%|███                                | 3749/42525 [06:53<1:07:06,  9.63it/s]

  9%|███                                | 3753/42525 [06:54<1:04:55,  9.95it/s]

  9%|███                                | 3755/42525 [06:54<1:07:33,  9.56it/s]

  9%|███                                | 3758/42525 [06:54<1:10:27,  9.17it/s]

  9%|███                                | 3759/42525 [06:55<1:16:09,  8.48it/s]

  9%|███                                | 3762/42525 [06:55<1:12:01,  8.97it/s]

  9%|███                                | 3766/42525 [06:55<1:06:57,  9.65it/s]

  9%|███                                | 3768/42525 [06:55<1:05:04,  9.93it/s]

  9%|███                                | 3772/42525 [06:56<1:04:34, 10.00it/s]

  9%|███                                | 3774/42525 [06:56<1:12:16,  8.94it/s]

  9%|███                                | 3775/42525 [06:56<1:13:05,  8.84it/s]

  9%|███                                | 3778/42525 [06:57<1:13:09,  8.83it/s]

  9%|███                                | 3781/42525 [06:57<1:14:25,  8.68it/s]

  9%|███                                | 3783/42525 [06:57<1:11:57,  8.97it/s]

  9%|███                                | 3786/42525 [06:57<1:08:03,  9.49it/s]

  9%|███                                | 3790/42525 [06:58<1:04:10, 10.06it/s]

  9%|███                                | 3792/42525 [06:58<1:12:55,  8.85it/s]

  9%|███                                | 3796/42525 [06:58<1:06:19,  9.73it/s]

  9%|███▏                               | 3800/42525 [06:59<1:06:17,  9.74it/s]

  9%|███▏                               | 3804/42525 [06:59<1:06:27,  9.71it/s]

  9%|███▏                               | 3805/42525 [06:59<1:06:52,  9.65it/s]

  9%|███▏                               | 3808/42525 [07:00<1:15:46,  8.52it/s]

  9%|███▏                               | 3811/42525 [07:00<1:14:15,  8.69it/s]

  9%|███▏                               | 3814/42525 [07:00<1:15:05,  8.59it/s]

  9%|███▏                               | 3818/42525 [07:01<1:10:48,  9.11it/s]

  9%|███▏                               | 3821/42525 [07:01<1:17:44,  8.30it/s]

  9%|███▏                               | 3824/42525 [07:02<1:10:50,  9.11it/s]

  9%|███▏                               | 3827/42525 [07:02<1:13:20,  8.79it/s]

  9%|███▏                               | 3828/42525 [07:02<1:11:25,  9.03it/s]

  9%|███▏                               | 3831/42525 [07:02<1:12:11,  8.93it/s]

  9%|███▏                               | 3833/42525 [07:03<1:22:16,  7.84it/s]

  9%|███▏                               | 3836/42525 [07:03<1:14:33,  8.65it/s]

  9%|███▏                               | 3838/42525 [07:03<1:22:22,  7.83it/s]

  9%|███▏                               | 3840/42525 [07:04<1:19:38,  8.10it/s]

  9%|███▏                               | 3843/42525 [07:04<1:08:58,  9.35it/s]

  9%|███▏                               | 3846/42525 [07:04<1:06:26,  9.70it/s]

  9%|███▏                               | 3849/42525 [07:04<1:15:58,  8.48it/s]

  9%|███▏                               | 3853/42525 [07:05<1:08:18,  9.43it/s]

  9%|███▏                               | 3856/42525 [07:05<1:09:20,  9.29it/s]

  9%|███▏                               | 3859/42525 [07:06<1:06:08,  9.74it/s]

  9%|███▏                               | 3862/42525 [07:06<1:15:26,  8.54it/s]

  9%|███▏                               | 3864/42525 [07:06<1:14:55,  8.60it/s]

  9%|███▏                               | 3866/42525 [07:06<1:19:50,  8.07it/s]

  9%|███▏                               | 3868/42525 [07:07<1:27:07,  7.40it/s]

  9%|███▏                               | 3871/42525 [07:07<1:15:57,  8.48it/s]

  9%|███▏                               | 3873/42525 [07:07<1:19:50,  8.07it/s]

  9%|███▏                               | 3876/42525 [07:08<1:10:00,  9.20it/s]

  9%|███▏                               | 3880/42525 [07:08<1:05:27,  9.84it/s]

  9%|███▏                               | 3882/42525 [07:08<1:08:44,  9.37it/s]

  9%|███▏                               | 3886/42525 [07:09<1:06:48,  9.64it/s]

  9%|███▏                               | 3888/42525 [07:09<1:05:21,  9.85it/s]

  9%|███▏                               | 3892/42525 [07:09<1:07:53,  9.48it/s]

  9%|███▏                               | 3895/42525 [07:10<1:09:16,  9.29it/s]

  9%|███▏                               | 3897/42525 [07:10<1:11:43,  8.98it/s]

  9%|███▏                               | 3900/42525 [07:10<1:09:00,  9.33it/s]

  9%|███▏                               | 3902/42525 [07:10<1:10:52,  9.08it/s]

  9%|███▏                               | 3904/42525 [07:11<1:09:51,  9.22it/s]

  9%|███▏                               | 3906/42525 [07:11<1:20:26,  8.00it/s]

  9%|███▏                               | 3910/42525 [07:11<1:10:40,  9.11it/s]

  9%|███▏                               | 3912/42525 [07:12<1:17:42,  8.28it/s]

  9%|███▏                               | 3915/42525 [07:12<1:11:14,  9.03it/s]

  9%|███▏                               | 3918/42525 [07:12<1:06:40,  9.65it/s]

  9%|███▏                               | 3921/42525 [07:12<1:11:03,  9.05it/s]

  9%|███▏                               | 3923/42525 [07:13<1:15:00,  8.58it/s]

  9%|███▏                               | 3927/42525 [07:13<1:08:11,  9.43it/s]

  9%|███▏                               | 3928/42525 [07:13<1:07:54,  9.47it/s]

  9%|███▏                               | 3930/42525 [07:13<1:11:39,  8.98it/s]

  9%|███▏                               | 3933/42525 [07:14<1:08:35,  9.38it/s]

  9%|███▏                               | 3937/42525 [07:14<1:05:18,  9.85it/s]

  9%|███▏                               | 3939/42525 [07:14<1:05:55,  9.76it/s]

  9%|███▏                               | 3941/42525 [07:15<1:08:31,  9.38it/s]

  9%|███▏                               | 3943/42525 [07:15<1:10:01,  9.18it/s]

  9%|███▏                               | 3946/42525 [07:15<1:09:58,  9.19it/s]

  9%|███▎                               | 3950/42525 [07:16<1:05:10,  9.86it/s]

  9%|███▎                               | 3952/42525 [07:16<1:11:33,  8.99it/s]

  9%|███▎                               | 3954/42525 [07:16<1:16:53,  8.36it/s]

  9%|███▎                               | 3957/42525 [07:16<1:14:53,  8.58it/s]

  9%|███▎                               | 3961/42525 [07:17<1:09:00,  9.31it/s]

  9%|███▎                               | 3962/42525 [07:17<1:09:48,  9.21it/s]

  9%|███▎                               | 3965/42525 [07:17<1:11:54,  8.94it/s]

  9%|███▎                               | 3966/42525 [07:17<1:11:15,  9.02it/s]

  9%|███▎                               | 3969/42525 [07:18<1:14:40,  8.61it/s]

  9%|███▎                               | 3971/42525 [07:18<1:09:55,  9.19it/s]

  9%|███▎                               | 3973/42525 [07:18<1:12:31,  8.86it/s]

  9%|███▎                               | 3976/42525 [07:18<1:15:01,  8.56it/s]

  9%|███▎                               | 3979/42525 [07:19<1:17:13,  8.32it/s]

  9%|███▎                               | 3983/42525 [07:19<1:09:14,  9.28it/s]

  9%|███▎                               | 3987/42525 [07:20<1:05:15,  9.84it/s]

  9%|███▎                               | 3990/42525 [07:20<1:05:18,  9.83it/s]

  9%|███▎                               | 3993/42525 [07:20<1:08:26,  9.38it/s]

  9%|███▎                               | 3995/42525 [07:21<1:15:08,  8.55it/s]

  9%|███▎                               | 3997/42525 [07:21<1:14:01,  8.67it/s]

  9%|███▎                               | 3999/42525 [07:21<1:14:51,  8.58it/s]

  9%|███▎                               | 4000/42525 [07:21<1:11:50,  8.94it/s]

  9%|███▎                               | 4003/42525 [07:21<1:15:52,  8.46it/s]

  9%|███▎                               | 4005/42525 [07:22<1:12:38,  8.84it/s]

  9%|███▎                               | 4008/42525 [07:22<1:07:23,  9.52it/s]

  9%|███▎                               | 4011/42525 [07:22<1:10:13,  9.14it/s]

  9%|███▎                               | 4013/42525 [07:23<1:15:01,  8.56it/s]

  9%|███▎                               | 4016/42525 [07:23<1:11:32,  8.97it/s]

  9%|███▎                               | 4019/42525 [07:23<1:12:51,  8.81it/s]

  9%|███▎                               | 4021/42525 [07:24<1:14:51,  8.57it/s]

  9%|███▎                               | 4023/42525 [07:24<1:19:07,  8.11it/s]

  9%|███▎                               | 4024/42525 [07:24<1:17:12,  8.31it/s]

  9%|███▎                               | 4026/42525 [07:24<1:13:23,  8.74it/s]

  9%|███▎                               | 4030/42525 [07:24<1:07:16,  9.54it/s]

  9%|███▎                               | 4032/42525 [07:25<1:10:21,  9.12it/s]

  9%|███▎                               | 4036/42525 [07:25<1:06:38,  9.63it/s]

  9%|███▎                               | 4039/42525 [07:25<1:07:52,  9.45it/s]

 10%|███▎                               | 4041/42525 [07:26<1:07:04,  9.56it/s]

 10%|███▎                               | 4043/42525 [07:26<1:10:36,  9.08it/s]

 10%|███▎                               | 4046/42525 [07:26<1:09:17,  9.26it/s]

 10%|███▎                               | 4048/42525 [07:26<1:12:36,  8.83it/s]

 10%|███▎                               | 4052/42525 [07:27<1:05:45,  9.75it/s]

 10%|███▎                               | 4055/42525 [07:27<1:04:27,  9.95it/s]

 10%|███▎                               | 4058/42525 [07:27<1:03:40, 10.07it/s]

 10%|███▎                               | 4062/42525 [07:28<1:02:09, 10.31it/s]

 10%|███▎                               | 4066/42525 [07:28<1:05:14,  9.83it/s]

 10%|███▎                               | 4068/42525 [07:28<1:04:02, 10.01it/s]

 10%|███▎                               | 4072/42525 [07:29<1:06:45,  9.60it/s]

 10%|███▎                               | 4074/42525 [07:29<1:06:16,  9.67it/s]

 10%|███▎                               | 4076/42525 [07:29<1:06:58,  9.57it/s]

 10%|███▎                               | 4079/42525 [07:30<1:06:55,  9.58it/s]

 10%|███▎                               | 4081/42525 [07:30<1:14:04,  8.65it/s]

 10%|███▎                               | 4083/42525 [07:30<1:11:10,  9.00it/s]

 10%|███▎                               | 4085/42525 [07:30<1:07:52,  9.44it/s]

 10%|███▎                               | 4088/42525 [07:31<1:08:08,  9.40it/s]

 10%|███▎                               | 4092/42525 [07:31<1:04:50,  9.88it/s]

 10%|███▎                               | 4094/42525 [07:31<1:12:49,  8.80it/s]

 10%|███▎                               | 4097/42525 [07:32<1:08:00,  9.42it/s]

 10%|███▍                               | 4101/42525 [07:32<1:04:40,  9.90it/s]

 10%|███▍                               | 4103/42525 [07:32<1:03:41, 10.05it/s]

 10%|███▍                               | 4107/42525 [07:33<1:03:30, 10.08it/s]

 10%|███▍                               | 4110/42525 [07:33<1:05:48,  9.73it/s]

 10%|███▍                               | 4113/42525 [07:33<1:04:34,  9.92it/s]

 10%|███▍                               | 4115/42525 [07:33<1:10:27,  9.09it/s]

 10%|███▍                               | 4118/42525 [07:34<1:11:33,  8.95it/s]

 10%|███▍                               | 4122/42525 [07:34<1:06:01,  9.70it/s]

 10%|███▍                               | 4125/42525 [07:34<1:10:52,  9.03it/s]

 10%|███▍                               | 4128/42525 [07:35<1:10:26,  9.09it/s]

 10%|███▍                               | 4131/42525 [07:35<1:10:26,  9.08it/s]

 10%|███▍                               | 4133/42525 [07:35<1:09:04,  9.26it/s]

 10%|███▍                               | 4135/42525 [07:36<1:08:16,  9.37it/s]

 10%|███▍                               | 4138/42525 [07:36<1:06:29,  9.62it/s]

 10%|███▍                               | 4141/42525 [07:36<1:07:40,  9.45it/s]

 10%|███▍                               | 4144/42525 [07:36<1:05:50,  9.72it/s]

 10%|███▍                               | 4146/42525 [07:37<1:04:20,  9.94it/s]

 10%|███▍                               | 4149/42525 [07:37<1:12:28,  8.83it/s]

 10%|███▍                               | 4151/42525 [07:37<1:12:30,  8.82it/s]

 10%|███▍                               | 4153/42525 [07:38<1:17:22,  8.27it/s]

 10%|███▍                               | 4156/42525 [07:38<1:13:39,  8.68it/s]

 10%|███▍                               | 4159/42525 [07:38<1:11:04,  9.00it/s]

 10%|███▍                               | 4162/42525 [07:38<1:07:23,  9.49it/s]

 10%|███▍                               | 4165/42525 [07:39<1:08:20,  9.36it/s]

 10%|███▍                               | 4167/42525 [07:39<1:19:15,  8.07it/s]

 10%|███▍                               | 4171/42525 [07:40<1:12:16,  8.84it/s]

 10%|███▍                               | 4172/42525 [07:40<1:16:59,  8.30it/s]

 10%|███▍                               | 4175/42525 [07:40<1:14:29,  8.58it/s]

 10%|███▍                               | 4177/42525 [07:40<1:09:36,  9.18it/s]

 10%|███▍                               | 4180/42525 [07:41<1:09:09,  9.24it/s]

 10%|███▍                               | 4182/42525 [07:41<1:07:36,  9.45it/s]

 10%|███▍                               | 4184/42525 [07:41<1:13:39,  8.68it/s]

 10%|███▍                               | 4188/42525 [07:41<1:06:10,  9.65it/s]

 10%|███▍                               | 4191/42525 [07:42<1:08:04,  9.39it/s]

 10%|███▍                               | 4193/42525 [07:42<1:08:30,  9.33it/s]

 10%|███▍                               | 4196/42525 [07:42<1:09:46,  9.16it/s]

 10%|███▍                               | 4199/42525 [07:43<1:11:15,  8.97it/s]

 10%|███▍                               | 4201/42525 [07:43<1:21:40,  7.82it/s]

 10%|███▍                               | 4202/42525 [07:43<1:17:01,  8.29it/s]

 10%|███▍                               | 4205/42525 [07:43<1:10:35,  9.05it/s]

 10%|███▍                               | 4207/42525 [07:44<1:21:10,  7.87it/s]

 10%|███▍                               | 4210/42525 [07:44<1:18:29,  8.14it/s]

 10%|███▍                               | 4212/42525 [07:44<1:22:23,  7.75it/s]

 10%|███▍                               | 4213/42525 [07:44<1:23:32,  7.64it/s]

 10%|███▍                               | 4216/42525 [07:45<1:21:55,  7.79it/s]

 10%|███▍                               | 4217/42525 [07:45<1:18:19,  8.15it/s]

 10%|███▍                               | 4220/42525 [07:45<1:11:33,  8.92it/s]

 10%|███▍                               | 4223/42525 [07:46<1:13:22,  8.70it/s]

 10%|███▍                               | 4227/42525 [07:46<1:06:23,  9.61it/s]

 10%|███▍                               | 4229/42525 [07:46<1:04:51,  9.84it/s]

 10%|███▍                               | 4231/42525 [07:46<1:06:17,  9.63it/s]

 10%|███▍                               | 4233/42525 [07:47<1:06:06,  9.65it/s]

 10%|███▍                               | 4236/42525 [07:47<1:12:46,  8.77it/s]

 10%|███▍                               | 4238/42525 [07:47<1:13:00,  8.74it/s]

 10%|███▍                               | 4242/42525 [07:48<1:07:04,  9.51it/s]

 10%|███▍                               | 4245/42525 [07:48<1:12:05,  8.85it/s]

 10%|███▍                               | 4248/42525 [07:48<1:08:07,  9.36it/s]

 10%|███▍                               | 4251/42525 [07:48<1:06:17,  9.62it/s]

 10%|███▌                               | 4253/42525 [07:49<1:10:51,  9.00it/s]

 10%|███▌                               | 4256/42525 [07:49<1:08:21,  9.33it/s]

 10%|███▌                               | 4259/42525 [07:49<1:08:00,  9.38it/s]

 10%|███▌                               | 4261/42525 [07:50<1:10:06,  9.10it/s]

 10%|███▌                               | 4264/42525 [07:50<1:14:30,  8.56it/s]

 10%|███▌                               | 4268/42525 [07:50<1:08:42,  9.28it/s]

 10%|███▌                               | 4270/42525 [07:51<1:17:33,  8.22it/s]

 10%|███▌                               | 4272/42525 [07:51<1:12:21,  8.81it/s]

 10%|███▌                               | 4275/42525 [07:51<1:15:01,  8.50it/s]

 10%|███▌                               | 4278/42525 [07:52<1:14:00,  8.61it/s]

 10%|███▌                               | 4280/42525 [07:52<1:17:07,  8.27it/s]

 10%|███▌                               | 4283/42525 [07:52<1:09:34,  9.16it/s]

 10%|███▌                               | 4285/42525 [07:52<1:06:03,  9.65it/s]

 10%|███▌                               | 4287/42525 [07:53<1:06:12,  9.63it/s]

 10%|███▌                               | 4291/42525 [07:53<1:04:26,  9.89it/s]

 10%|███▌                               | 4293/42525 [07:53<1:12:13,  8.82it/s]

 10%|███▌                               | 4295/42525 [07:53<1:14:23,  8.56it/s]

 10%|███▌                               | 4298/42525 [07:54<1:10:08,  9.08it/s]

 10%|███▌                               | 4299/42525 [07:54<1:09:14,  9.20it/s]

 10%|███▌                               | 4302/42525 [07:54<1:11:17,  8.94it/s]

 10%|███▌                               | 4304/42525 [07:54<1:09:23,  9.18it/s]

 10%|███▌                               | 4306/42525 [07:55<1:21:42,  7.80it/s]

 10%|███▌                               | 4308/42525 [07:55<1:19:42,  7.99it/s]

 10%|███▌                               | 4312/42525 [07:55<1:07:17,  9.46it/s]

 10%|███▌                               | 4315/42525 [07:56<1:14:03,  8.60it/s]

 10%|███▌                               | 4317/42525 [07:56<1:13:14,  8.69it/s]

 10%|███▌                               | 4320/42525 [07:56<1:09:13,  9.20it/s]

 10%|███▌                               | 4323/42525 [07:57<1:09:41,  9.14it/s]

 10%|███▌                               | 4326/42525 [07:57<1:09:35,  9.15it/s]

 10%|███▌                               | 4328/42525 [07:57<1:06:48,  9.53it/s]

 10%|███▌                               | 4332/42525 [07:58<1:07:47,  9.39it/s]

 10%|███▌                               | 4334/42525 [07:58<1:10:38,  9.01it/s]

 10%|███▌                               | 4338/42525 [07:58<1:09:37,  9.14it/s]

 10%|███▌                               | 4340/42525 [07:58<1:15:49,  8.39it/s]

 10%|███▌                               | 4343/42525 [07:59<1:11:45,  8.87it/s]

 10%|███▌                               | 4346/42525 [07:59<1:07:16,  9.46it/s]

 10%|███▌                               | 4348/42525 [07:59<1:04:57,  9.79it/s]

 10%|███▌                               | 4352/42525 [08:00<1:03:41,  9.99it/s]

 10%|███▌                               | 4353/42525 [08:00<1:05:24,  9.73it/s]

 10%|███▌                               | 4356/42525 [08:00<1:12:23,  8.79it/s]

 10%|███▌                               | 4358/42525 [08:00<1:08:31,  9.28it/s]

 10%|███▌                               | 4361/42525 [08:01<1:09:38,  9.13it/s]

 10%|███▌                               | 4363/42525 [08:01<1:06:46,  9.53it/s]

 10%|███▌                               | 4366/42525 [08:01<1:12:19,  8.79it/s]

 10%|███▌                               | 4368/42525 [08:01<1:10:08,  9.07it/s]

 10%|███▌                               | 4371/42525 [08:02<1:12:32,  8.77it/s]

 10%|███▌                               | 4374/42525 [08:02<1:13:23,  8.66it/s]

 10%|███▌                               | 4375/42525 [08:02<1:18:11,  8.13it/s]

 10%|███▌                               | 4378/42525 [08:03<1:16:10,  8.35it/s]

 10%|███▌                               | 4379/42525 [08:03<1:15:42,  8.40it/s]

 10%|███▌                               | 4381/42525 [08:03<1:13:34,  8.64it/s]

 10%|███▌                               | 4384/42525 [08:03<1:15:55,  8.37it/s]

 10%|███▌                               | 4386/42525 [08:04<1:23:40,  7.60it/s]

 10%|███▌                               | 4389/42525 [08:04<1:12:04,  8.82it/s]

 10%|███▌                               | 4391/42525 [08:04<1:17:34,  8.19it/s]

 10%|███▌                               | 4393/42525 [08:04<1:11:20,  8.91it/s]

 10%|███▌                               | 4397/42525 [08:05<1:05:00,  9.77it/s]

 10%|███▌                               | 4400/42525 [08:05<1:05:28,  9.71it/s]

 10%|███▌                               | 4401/42525 [08:05<1:11:44,  8.86it/s]

 10%|███▌                               | 4404/42525 [08:06<1:13:28,  8.65it/s]

 10%|███▋                               | 4406/42525 [08:06<1:08:50,  9.23it/s]

 10%|███▋                               | 4408/42525 [08:06<1:11:14,  8.92it/s]

 10%|███▋                               | 4411/42525 [08:06<1:08:56,  9.22it/s]

 10%|███▋                               | 4412/42525 [08:06<1:10:54,  8.96it/s]

 10%|███▋                               | 4416/42525 [08:07<1:08:27,  9.28it/s]

 10%|███▋                               | 4419/42525 [08:07<1:07:12,  9.45it/s]

 10%|███▋                               | 4421/42525 [08:07<1:15:06,  8.46it/s]

 10%|███▋                               | 4424/42525 [08:08<1:15:27,  8.42it/s]

 10%|███▋                               | 4426/42525 [08:08<1:18:30,  8.09it/s]

 10%|███▋                               | 4428/42525 [08:08<1:23:39,  7.59it/s]

 10%|███▋                               | 4431/42525 [08:09<1:11:37,  8.86it/s]

 10%|███▋                               | 4433/42525 [08:09<1:17:36,  8.18it/s]

 10%|███▋                               | 4436/42525 [08:09<1:17:04,  8.24it/s]

 10%|███▋                               | 4439/42525 [08:10<1:12:52,  8.71it/s]

 10%|███▋                               | 4442/42525 [08:10<1:09:42,  9.11it/s]

 10%|███▋                               | 4444/42525 [08:10<1:06:53,  9.49it/s]

 10%|███▋                               | 4447/42525 [08:10<1:12:26,  8.76it/s]

 10%|███▋                               | 4449/42525 [08:11<1:08:56,  9.21it/s]

 10%|███▋                               | 4452/42525 [08:11<1:07:57,  9.34it/s]

 10%|███▋                               | 4455/42525 [08:11<1:05:48,  9.64it/s]

 10%|███▋                               | 4457/42525 [08:12<1:17:24,  8.20it/s]

 10%|███▋                               | 4459/42525 [08:12<1:24:59,  7.46it/s]

 10%|███▋                               | 4461/42525 [08:12<1:15:08,  8.44it/s]

 10%|███▋                               | 4463/42525 [08:12<1:08:42,  9.23it/s]

 10%|███▋                               | 4465/42525 [08:13<1:10:01,  9.06it/s]

 11%|███▋                               | 4468/42525 [08:13<1:14:12,  8.55it/s]

 11%|███▋                               | 4471/42525 [08:13<1:13:27,  8.63it/s]

 11%|███▋                               | 4473/42525 [08:13<1:16:40,  8.27it/s]

 11%|███▋                               | 4475/42525 [08:14<1:17:17,  8.20it/s]

 11%|███▋                               | 4478/42525 [08:14<1:09:54,  9.07it/s]

 11%|███▋                               | 4479/42525 [08:14<1:09:28,  9.13it/s]

 11%|███▋                               | 4481/42525 [08:14<1:12:23,  8.76it/s]

 11%|███▋                               | 4484/42525 [08:15<1:18:14,  8.10it/s]

 11%|███▋                               | 4487/42525 [08:15<1:13:45,  8.60it/s]

 11%|███▋                               | 4489/42525 [08:15<1:18:32,  8.07it/s]

 11%|███▋                               | 4490/42525 [08:15<1:15:21,  8.41it/s]

 11%|███▋                               | 4494/42525 [08:16<1:08:10,  9.30it/s]

 11%|███▋                               | 4497/42525 [08:16<1:11:23,  8.88it/s]

 11%|███▋                               | 4499/42525 [08:16<1:15:56,  8.34it/s]

 11%|███▋                               | 4501/42525 [08:17<1:21:54,  7.74it/s]

 11%|███▋                               | 4503/42525 [08:17<1:18:06,  8.11it/s]

 11%|███▋                               | 4505/42525 [08:17<1:12:13,  8.77it/s]

 11%|███▋                               | 4508/42525 [08:18<1:07:46,  9.35it/s]

 11%|███▋                               | 4512/42525 [08:18<1:08:10,  9.29it/s]

 11%|███▋                               | 4516/42525 [08:18<1:04:17,  9.85it/s]

 11%|███▋                               | 4518/42525 [08:19<1:03:15, 10.01it/s]

 11%|███▋                               | 4521/42525 [08:19<1:08:36,  9.23it/s]

 11%|███▋                               | 4524/42525 [08:19<1:08:10,  9.29it/s]

 11%|███▋                               | 4527/42525 [08:20<1:07:50,  9.34it/s]

 11%|███▋                               | 4530/42525 [08:20<1:05:29,  9.67it/s]

 11%|███▋                               | 4532/42525 [08:20<1:11:02,  8.91it/s]

 11%|███▋                               | 4533/42525 [08:20<1:16:54,  8.23it/s]

 11%|███▋                               | 4536/42525 [08:21<1:18:23,  8.08it/s]

 11%|███▋                               | 4538/42525 [08:21<1:17:42,  8.15it/s]

 11%|███▋                               | 4540/42525 [08:21<1:13:20,  8.63it/s]

 11%|███▋                               | 4544/42525 [08:21<1:05:56,  9.60it/s]

 11%|███▋                               | 4545/42525 [08:22<1:06:23,  9.53it/s]

 11%|███▋                               | 4549/42525 [08:22<1:05:09,  9.71it/s]

 11%|███▋                               | 4552/42525 [08:22<1:05:25,  9.67it/s]

 11%|███▋                               | 4554/42525 [08:22<1:06:11,  9.56it/s]

 11%|███▊                               | 4557/42525 [08:23<1:11:22,  8.87it/s]

 11%|███▊                               | 4560/42525 [08:23<1:10:39,  8.95it/s]

 11%|███▊                               | 4562/42525 [08:23<1:09:10,  9.15it/s]

 11%|███▊                               | 4565/42525 [08:24<1:15:41,  8.36it/s]

 11%|███▊                               | 4566/42525 [08:24<1:14:08,  8.53it/s]

 11%|███▊                               | 4570/42525 [08:24<1:06:59,  9.44it/s]

 11%|███▊                               | 4573/42525 [08:25<1:05:24,  9.67it/s]

 11%|███▊                               | 4575/42525 [08:25<1:08:10,  9.28it/s]

 11%|███▊                               | 4578/42525 [08:25<1:06:31,  9.51it/s]

 11%|███▊                               | 4581/42525 [08:25<1:06:24,  9.52it/s]

 11%|███▊                               | 4583/42525 [08:26<1:10:29,  8.97it/s]

 11%|███▊                               | 4587/42525 [08:26<1:05:55,  9.59it/s]

 11%|███▊                               | 4589/42525 [08:26<1:10:05,  9.02it/s]

 11%|███▊                               | 4591/42525 [08:27<1:12:42,  8.70it/s]

 11%|███▊                               | 4594/42525 [08:27<1:18:12,  8.08it/s]

 11%|███▊                               | 4597/42525 [08:27<1:10:30,  8.96it/s]

 11%|███▊                               | 4600/42525 [08:28<1:10:23,  8.98it/s]

 11%|███▊                               | 4604/42525 [08:28<1:05:13,  9.69it/s]

 11%|███▊                               | 4607/42525 [08:28<1:09:53,  9.04it/s]

 11%|███▊                               | 4611/42525 [08:29<1:05:03,  9.71it/s]

 11%|███▊                               | 4613/42525 [08:29<1:03:47,  9.91it/s]

 11%|███▊                               | 4616/42525 [08:29<1:07:56,  9.30it/s]

 11%|███▊                               | 4618/42525 [08:30<1:09:54,  9.04it/s]

 11%|███▊                               | 4620/42525 [08:30<1:13:12,  8.63it/s]

 11%|███▊                               | 4623/42525 [08:30<1:08:45,  9.19it/s]

 11%|███▊                               | 4625/42525 [08:30<1:14:10,  8.52it/s]

 11%|███▊                               | 4626/42525 [08:30<1:11:11,  8.87it/s]

 11%|███▊                               | 4629/42525 [08:31<1:15:24,  8.38it/s]

 11%|███▊                               | 4632/42525 [08:31<1:09:18,  9.11it/s]

 11%|███▊                               | 4634/42525 [08:31<1:08:44,  9.19it/s]

 11%|███▊                               | 4637/42525 [08:32<1:05:31,  9.64it/s]

 11%|███▊                               | 4640/42525 [08:32<1:10:55,  8.90it/s]

 11%|███▊                               | 4642/42525 [08:32<1:07:24,  9.37it/s]

 11%|███▊                               | 4645/42525 [08:33<1:15:45,  8.33it/s]

 11%|███▊                               | 4648/42525 [08:33<1:16:03,  8.30it/s]

 11%|███▊                               | 4651/42525 [08:33<1:08:31,  9.21it/s]

 11%|███▊                               | 4654/42525 [08:34<1:16:17,  8.27it/s]

 11%|███▊                               | 4658/42525 [08:34<1:07:41,  9.32it/s]

 11%|███▊                               | 4661/42525 [08:34<1:11:01,  8.89it/s]

 11%|███▊                               | 4663/42525 [08:35<1:10:09,  9.00it/s]

 11%|███▊                               | 4666/42525 [08:35<1:05:58,  9.56it/s]

 11%|███▊                               | 4668/42525 [08:35<1:04:03,  9.85it/s]

 11%|███▊                               | 4672/42525 [08:35<1:03:11,  9.98it/s]

 11%|███▊                               | 4676/42525 [08:36<1:05:58,  9.56it/s]

 11%|███▊                               | 4679/42525 [08:36<1:07:40,  9.32it/s]

 11%|███▊                               | 4682/42525 [08:37<1:11:21,  8.84it/s]

 11%|███▊                               | 4684/42525 [08:37<1:14:03,  8.52it/s]

 11%|███▊                               | 4687/42525 [08:37<1:14:35,  8.46it/s]

 11%|███▊                               | 4689/42525 [08:37<1:17:37,  8.12it/s]

 11%|███▊                               | 4690/42525 [08:38<1:15:16,  8.38it/s]

 11%|███▊                               | 4692/42525 [08:38<1:12:05,  8.75it/s]

 11%|███▊                               | 4696/42525 [08:38<1:06:17,  9.51it/s]

 11%|███▊                               | 4698/42525 [08:38<1:06:22,  9.50it/s]

 11%|███▊                               | 4702/42525 [08:39<1:02:57, 10.01it/s]

 11%|███▊                               | 4705/42525 [08:39<1:08:29,  9.20it/s]

 11%|███▊                               | 4707/42525 [08:39<1:12:19,  8.71it/s]

 11%|███▉                               | 4710/42525 [08:40<1:07:17,  9.37it/s]

 11%|███▉                               | 4712/42525 [08:40<1:18:49,  7.99it/s]

 11%|███▉                               | 4714/42525 [08:40<1:19:55,  7.88it/s]

 11%|███▉                               | 4716/42525 [08:40<1:12:37,  8.68it/s]

 11%|███▉                               | 4719/42525 [08:41<1:12:48,  8.65it/s]

 11%|███▉                               | 4720/42525 [08:41<1:17:32,  8.13it/s]

 11%|███▉                               | 4723/42525 [08:41<1:13:46,  8.54it/s]

 11%|███▉                               | 4725/42525 [08:42<1:22:08,  7.67it/s]

 11%|███▉                               | 4728/42525 [08:42<1:10:48,  8.90it/s]

 11%|███▉                               | 4731/42525 [08:42<1:07:04,  9.39it/s]

 11%|███▉                               | 4733/42525 [08:42<1:15:00,  8.40it/s]

 11%|███▉                               | 4736/42525 [08:43<1:10:24,  8.94it/s]

 11%|███▉                               | 4738/42525 [08:43<1:09:39,  9.04it/s]

 11%|███▉                               | 4742/42525 [08:43<1:04:27,  9.77it/s]

 11%|███▉                               | 4744/42525 [08:44<1:11:38,  8.79it/s]

 11%|███▉                               | 4746/42525 [08:44<1:16:58,  8.18it/s]

 11%|███▉                               | 4750/42525 [08:44<1:07:13,  9.37it/s]

 11%|███▉                               | 4751/42525 [08:44<1:12:44,  8.65it/s]

 11%|███▉                               | 4754/42525 [08:45<1:19:14,  7.94it/s]

 11%|███▉                               | 4757/42525 [08:45<1:14:25,  8.46it/s]

 11%|███▉                               | 4759/42525 [08:45<1:15:39,  8.32it/s]

 11%|███▉                               | 4761/42525 [08:46<1:18:10,  8.05it/s]

 11%|███▉                               | 4765/42525 [08:46<1:07:16,  9.35it/s]

 11%|███▉                               | 4767/42525 [08:46<1:12:32,  8.68it/s]

 11%|███▉                               | 4770/42525 [08:47<1:08:35,  9.17it/s]

 11%|███▉                               | 4773/42525 [08:47<1:13:54,  8.51it/s]

 11%|███▉                               | 4777/42525 [08:47<1:06:50,  9.41it/s]

 11%|███▉                               | 4778/42525 [08:47<1:06:40,  9.44it/s]

 11%|███▉                               | 4781/42525 [08:48<1:10:12,  8.96it/s]

 11%|███▉                               | 4783/42525 [08:48<1:12:51,  8.63it/s]

 11%|███▉                               | 4786/42525 [08:48<1:09:37,  9.03it/s]

 11%|███▉                               | 4790/42525 [08:49<1:04:59,  9.68it/s]

 11%|███▉                               | 4791/42525 [08:49<1:10:31,  8.92it/s]

 11%|███▉                               | 4793/42525 [08:49<1:08:26,  9.19it/s]

 11%|███▉                               | 4796/42525 [08:49<1:07:13,  9.35it/s]

 11%|███▉                               | 4798/42525 [08:50<1:17:46,  8.08it/s]

 11%|███▉                               | 4801/42525 [08:50<1:16:40,  8.20it/s]

 11%|███▉                               | 4805/42525 [08:50<1:08:18,  9.20it/s]

 11%|███▉                               | 4807/42525 [08:51<1:08:59,  9.11it/s]

 11%|███▉                               | 4811/42525 [08:51<1:08:00,  9.24it/s]

 11%|███▉                               | 4815/42525 [08:52<1:04:25,  9.75it/s]

 11%|███▉                               | 4818/42525 [08:52<1:03:34,  9.88it/s]

 11%|███▉                               | 4822/42525 [08:52<1:06:19,  9.47it/s]

 11%|███▉                               | 4824/42525 [08:53<1:15:55,  8.28it/s]

 11%|███▉                               | 4826/42525 [08:53<1:13:10,  8.59it/s]

 11%|███▉                               | 4829/42525 [08:53<1:16:43,  8.19it/s]

 11%|███▉                               | 4832/42525 [08:54<1:12:52,  8.62it/s]

 11%|███▉                               | 4834/42525 [08:54<1:09:05,  9.09it/s]

 11%|███▉                               | 4838/42525 [08:54<1:06:43,  9.41it/s]

 11%|███▉                               | 4842/42525 [08:55<1:05:15,  9.62it/s]

 11%|███▉                               | 4844/42525 [08:55<1:14:34,  8.42it/s]

 11%|███▉                               | 4847/42525 [08:55<1:11:46,  8.75it/s]

 11%|███▉                               | 4851/42525 [08:56<1:05:43,  9.55it/s]

 11%|███▉                               | 4853/42525 [08:56<1:06:22,  9.46it/s]

 11%|███▉                               | 4855/42525 [08:56<1:07:58,  9.24it/s]

 11%|███▉                               | 4856/42525 [08:56<1:14:23,  8.44it/s]

 11%|███▉                               | 4859/42525 [08:56<1:10:50,  8.86it/s]

 11%|████                               | 4861/42525 [08:57<1:10:09,  8.95it/s]

 11%|████                               | 4864/42525 [08:57<1:05:30,  9.58it/s]

 11%|████                               | 4866/42525 [08:57<1:03:52,  9.83it/s]

 11%|████                               | 4870/42525 [08:58<1:04:29,  9.73it/s]

 11%|████                               | 4873/42525 [08:58<1:04:00,  9.80it/s]

 11%|████                               | 4875/42525 [08:58<1:09:00,  9.09it/s]

 11%|████                               | 4877/42525 [08:58<1:13:05,  8.59it/s]

 11%|████                               | 4879/42525 [08:59<1:11:55,  8.72it/s]

 11%|████                               | 4880/42525 [08:59<1:12:08,  8.70it/s]

 11%|████                               | 4884/42525 [08:59<1:05:44,  9.54it/s]

 11%|████                               | 4887/42525 [08:59<1:06:52,  9.38it/s]

 11%|████                               | 4890/42525 [09:00<1:09:56,  8.97it/s]

 12%|████                               | 4893/42525 [09:00<1:09:32,  9.02it/s]

 12%|████                               | 4896/42525 [09:00<1:05:45,  9.54it/s]

 12%|████                               | 4898/42525 [09:01<1:13:38,  8.52it/s]

 12%|████                               | 4901/42525 [09:01<1:14:38,  8.40it/s]

 12%|████                               | 4904/42525 [09:01<1:07:42,  9.26it/s]

 12%|████                               | 4906/42525 [09:02<1:08:38,  9.13it/s]

 12%|████                               | 4909/42525 [09:02<1:12:25,  8.66it/s]

 12%|████                               | 4910/42525 [09:02<1:17:06,  8.13it/s]

 12%|████                               | 4914/42525 [09:03<1:11:10,  8.81it/s]

 12%|████                               | 4917/42525 [09:03<1:08:24,  9.16it/s]

 12%|████                               | 4920/42525 [09:03<1:11:42,  8.74it/s]

 12%|████                               | 4921/42525 [09:03<1:10:05,  8.94it/s]

 12%|████                               | 4924/42525 [09:04<1:09:34,  9.01it/s]

 12%|████                               | 4927/42525 [09:04<1:06:18,  9.45it/s]

 12%|████                               | 4930/42525 [09:04<1:03:42,  9.84it/s]

 12%|████                               | 4931/42525 [09:04<1:09:50,  8.97it/s]

 12%|████                               | 4935/42525 [09:05<1:06:35,  9.41it/s]

 12%|████                               | 4936/42525 [09:05<1:06:05,  9.48it/s]

 12%|████                               | 4939/42525 [09:05<1:12:02,  8.70it/s]

 12%|████                               | 4942/42525 [09:06<1:06:57,  9.35it/s]

 12%|████                               | 4946/42525 [09:06<1:07:43,  9.25it/s]

 12%|████                               | 4948/42525 [09:06<1:05:13,  9.60it/s]

 12%|████                               | 4952/42525 [09:07<1:06:02,  9.48it/s]

 12%|████                               | 4954/42525 [09:07<1:03:58,  9.79it/s]

 12%|████                               | 4958/42525 [09:07<1:02:54,  9.95it/s]

 12%|████                               | 4959/42525 [09:07<1:08:15,  9.17it/s]

 12%|████                               | 4961/42525 [09:08<1:07:47,  9.24it/s]

 12%|████                               | 4964/42525 [09:08<1:11:15,  8.79it/s]

 12%|████                               | 4966/42525 [09:08<1:09:37,  8.99it/s]

 12%|████                               | 4969/42525 [09:08<1:14:19,  8.42it/s]

 12%|████                               | 4971/42525 [09:09<1:17:26,  8.08it/s]

 12%|████                               | 4972/42525 [09:09<1:16:58,  8.13it/s]

 12%|████                               | 4975/42525 [09:09<1:14:45,  8.37it/s]

 12%|████                               | 4979/42525 [09:10<1:06:27,  9.42it/s]

 12%|████                               | 4982/42525 [09:10<1:11:57,  8.70it/s]

 12%|████                               | 4986/42525 [09:10<1:04:52,  9.64it/s]

 12%|████                               | 4989/42525 [09:11<1:10:31,  8.87it/s]

 12%|████                               | 4992/42525 [09:11<1:09:13,  9.04it/s]

 12%|████                               | 4994/42525 [09:11<1:06:20,  9.43it/s]

 12%|████                               | 4996/42525 [09:12<1:09:38,  8.98it/s]

 12%|████                               | 4999/42525 [09:12<1:13:09,  8.55it/s]

 12%|████                               | 5002/42525 [09:12<1:13:24,  8.52it/s]

 12%|████                               | 5005/42525 [09:13<1:08:38,  9.11it/s]

 12%|████                               | 5008/42525 [09:13<1:11:02,  8.80it/s]

 12%|████                               | 5010/42525 [09:13<1:13:12,  8.54it/s]

 12%|████▏                              | 5013/42525 [09:14<1:18:08,  8.00it/s]

 12%|████▏                              | 5016/42525 [09:14<1:17:29,  8.07it/s]

 12%|████▏                              | 5020/42525 [09:14<1:06:57,  9.34it/s]

 12%|████▏                              | 5021/42525 [09:14<1:06:24,  9.41it/s]

 12%|████▏                              | 5023/42525 [09:15<1:05:55,  9.48it/s]

 12%|████▏                              | 5025/42525 [09:15<1:09:14,  9.03it/s]

 12%|████▏                              | 5029/42525 [09:15<1:06:04,  9.46it/s]

 12%|████▏                              | 5033/42525 [09:16<1:02:49,  9.94it/s]

 12%|████▏                              | 5035/42525 [09:16<1:10:43,  8.83it/s]

 12%|████▏                              | 5037/42525 [09:16<1:12:57,  8.56it/s]

 12%|████▏                              | 5039/42525 [09:16<1:16:10,  8.20it/s]

 12%|████▏                              | 5042/42525 [09:17<1:13:28,  8.50it/s]

 12%|████▏                              | 5044/42525 [09:17<1:14:44,  8.36it/s]

 12%|████▏                              | 5047/42525 [09:17<1:11:53,  8.69it/s]

 12%|████▏                              | 5050/42525 [09:18<1:07:05,  9.31it/s]

 12%|████▏                              | 5053/42525 [09:18<1:06:04,  9.45it/s]

 12%|████▏                              | 5055/42525 [09:18<1:14:10,  8.42it/s]

 12%|████▏                              | 5057/42525 [09:18<1:08:28,  9.12it/s]

 12%|████▏                              | 5059/42525 [09:19<1:11:27,  8.74it/s]

 12%|████▏                              | 5062/42525 [09:19<1:09:01,  9.04it/s]

 12%|████▏                              | 5065/42525 [09:19<1:11:19,  8.75it/s]

 12%|████▏                              | 5068/42525 [09:20<1:08:25,  9.12it/s]

 12%|████▏                              | 5070/42525 [09:20<1:10:56,  8.80it/s]

 12%|████▏                              | 5072/42525 [09:20<1:08:01,  9.18it/s]

 12%|████▏                              | 5075/42525 [09:20<1:12:42,  8.59it/s]

 12%|████▏                              | 5076/42525 [09:21<1:12:46,  8.58it/s]

 12%|████▏                              | 5080/42525 [09:21<1:08:48,  9.07it/s]

 12%|████▏                              | 5082/42525 [09:21<1:18:01,  8.00it/s]

 12%|████▏                              | 5085/42525 [09:22<1:11:12,  8.76it/s]

 12%|████▏                              | 5087/42525 [09:22<1:13:34,  8.48it/s]

 12%|████▏                              | 5091/42525 [09:22<1:05:19,  9.55it/s]

 12%|████▏                              | 5094/42525 [09:23<1:10:26,  8.86it/s]

 12%|████▏                              | 5095/42525 [09:23<1:08:49,  9.06it/s]

 12%|████▏                              | 5098/42525 [09:23<1:06:56,  9.32it/s]

 12%|████▏                              | 5100/42525 [09:23<1:03:54,  9.76it/s]

 12%|████▏                              | 5104/42525 [09:24<1:05:21,  9.54it/s]

 12%|████▏                              | 5106/42525 [09:24<1:13:16,  8.51it/s]

 12%|████▏                              | 5109/42525 [09:24<1:10:22,  8.86it/s]

 12%|████▏                              | 5112/42525 [09:25<1:11:36,  8.71it/s]

 12%|████▏                              | 5115/42525 [09:25<1:05:53,  9.46it/s]

 12%|████▏                              | 5118/42525 [09:25<1:09:56,  8.91it/s]

 12%|████▏                              | 5120/42525 [09:25<1:12:09,  8.64it/s]

 12%|████▏                              | 5123/42525 [09:26<1:12:44,  8.57it/s]

 12%|████▏                              | 5126/42525 [09:26<1:14:27,  8.37it/s]

 12%|████▏                              | 5128/42525 [09:26<1:08:44,  9.07it/s]

 12%|████▏                              | 5132/42525 [09:27<1:05:12,  9.56it/s]

 12%|████▏                              | 5134/42525 [09:27<1:07:25,  9.24it/s]

 12%|████▏                              | 5136/42525 [09:27<1:09:14,  9.00it/s]

 12%|████▏                              | 5139/42525 [09:28<1:04:37,  9.64it/s]

 12%|████▏                              | 5142/42525 [09:28<1:06:49,  9.32it/s]

 12%|████▏                              | 5145/42525 [09:28<1:10:16,  8.86it/s]

 12%|████▏                              | 5147/42525 [09:28<1:12:44,  8.56it/s]

 12%|████▏                              | 5150/42525 [09:29<1:10:56,  8.78it/s]

 12%|████▏                              | 5152/42525 [09:29<1:08:41,  9.07it/s]

 12%|████▏                              | 5154/42525 [09:29<1:07:35,  9.21it/s]

 12%|████▏                              | 5157/42525 [09:29<1:03:45,  9.77it/s]

 12%|████▏                              | 5159/42525 [09:30<1:07:48,  9.19it/s]

 12%|████▏                              | 5161/42525 [09:30<1:11:47,  8.67it/s]

 12%|████▏                              | 5163/42525 [09:30<1:13:37,  8.46it/s]

 12%|████▎                              | 5166/42525 [09:30<1:06:56,  9.30it/s]

 12%|████▎                              | 5169/42525 [09:31<1:10:29,  8.83it/s]

 12%|████▎                              | 5171/42525 [09:31<1:12:01,  8.64it/s]

 12%|████▎                              | 5173/42525 [09:31<1:09:45,  8.92it/s]

 12%|████▎                              | 5177/42525 [09:32<1:07:55,  9.16it/s]

 12%|████▎                              | 5179/42525 [09:32<1:12:22,  8.60it/s]

 12%|████▎                              | 5181/42525 [09:32<1:14:11,  8.39it/s]

 12%|████▎                              | 5182/42525 [09:32<1:15:23,  8.26it/s]

 12%|████▎                              | 5185/42525 [09:33<1:16:17,  8.16it/s]

 12%|████▎                              | 5188/42525 [09:33<1:10:40,  8.80it/s]

 12%|████▎                              | 5191/42525 [09:33<1:07:39,  9.20it/s]

 12%|████▎                              | 5195/42525 [09:34<1:05:47,  9.46it/s]

 12%|████▎                              | 5197/42525 [09:34<1:09:05,  9.00it/s]

 12%|████▎                              | 5199/42525 [09:34<1:13:41,  8.44it/s]

 12%|████▎                              | 5202/42525 [09:35<1:10:38,  8.81it/s]

 12%|████▎                              | 5206/42525 [09:35<1:04:24,  9.66it/s]

 12%|████▎                              | 5207/42525 [09:35<1:05:44,  9.46it/s]

 12%|████▎                              | 5211/42525 [09:35<1:04:03,  9.71it/s]

 12%|████▎                              | 5215/42525 [09:36<1:05:37,  9.48it/s]

 12%|████▎                              | 5217/42525 [09:36<1:03:49,  9.74it/s]

 12%|████▎                              | 5221/42525 [09:37<1:02:58,  9.87it/s]

 12%|████▎                              | 5223/42525 [09:37<1:10:21,  8.84it/s]

 12%|████▎                              | 5226/42525 [09:37<1:07:49,  9.16it/s]

 12%|████▎                              | 5228/42525 [09:37<1:14:48,  8.31it/s]

 12%|████▎                              | 5230/42525 [09:38<1:12:54,  8.53it/s]

 12%|████▎                              | 5233/42525 [09:38<1:15:00,  8.29it/s]

 12%|████▎                              | 5235/42525 [09:38<1:18:53,  7.88it/s]

 12%|████▎                              | 5237/42525 [09:39<1:23:04,  7.48it/s]

 12%|████▎                              | 5238/42525 [09:39<1:18:40,  7.90it/s]

 12%|████▎                              | 5241/42525 [09:39<1:10:07,  8.86it/s]

 12%|████▎                              | 5244/42525 [09:39<1:05:56,  9.42it/s]

 12%|████▎                              | 5247/42525 [09:40<1:11:25,  8.70it/s]

 12%|████▎                              | 5248/42525 [09:40<1:09:39,  8.92it/s]

 12%|████▎                              | 5250/42525 [09:40<1:07:50,  9.16it/s]

 12%|████▎                              | 5253/42525 [09:40<1:15:42,  8.21it/s]

 12%|████▎                              | 5257/42525 [09:41<1:07:34,  9.19it/s]

 12%|████▎                              | 5259/42525 [09:41<1:10:04,  8.86it/s]

 12%|████▎                              | 5260/42525 [09:41<1:09:38,  8.92it/s]

 12%|████▎                              | 5263/42525 [09:41<1:09:46,  8.90it/s]

 12%|████▎                              | 5265/42525 [09:42<1:09:46,  8.90it/s]

 12%|████▎                              | 5267/42525 [09:42<1:13:12,  8.48it/s]

 12%|████▎                              | 5270/42525 [09:42<1:05:56,  9.42it/s]

 12%|████▎                              | 5273/42525 [09:43<1:08:23,  9.08it/s]

 12%|████▎                              | 5276/42525 [09:43<1:04:19,  9.65it/s]

 12%|████▎                              | 5279/42525 [09:43<1:02:59,  9.85it/s]

 12%|████▎                              | 5280/42525 [09:43<1:04:51,  9.57it/s]

 12%|████▎                              | 5283/42525 [09:44<1:07:47,  9.16it/s]

 12%|████▎                              | 5285/42525 [09:44<1:05:11,  9.52it/s]

 12%|████▎                              | 5288/42525 [09:44<1:10:40,  8.78it/s]

 12%|████▎                              | 5289/42525 [09:44<1:15:46,  8.19it/s]

 12%|████▎                              | 5292/42525 [09:45<1:13:45,  8.41it/s]

 12%|████▎                              | 5294/42525 [09:45<1:12:27,  8.56it/s]

 12%|████▎                              | 5297/42525 [09:45<1:14:25,  8.34it/s]

 12%|████▎                              | 5300/42525 [09:46<1:11:05,  8.73it/s]

 12%|████▎                              | 5303/42525 [09:46<1:07:15,  9.22it/s]

 12%|████▎                              | 5306/42525 [09:46<1:05:51,  9.42it/s]

 12%|████▎                              | 5310/42525 [09:47<1:02:36,  9.91it/s]

 12%|████▎                              | 5311/42525 [09:47<1:04:08,  9.67it/s]

 12%|████▎                              | 5314/42525 [09:47<1:04:54,  9.56it/s]

 13%|████▍                              | 5317/42525 [09:47<1:03:50,  9.71it/s]

 13%|████▍                              | 5320/42525 [09:48<1:10:40,  8.77it/s]

 13%|████▍                              | 5324/42525 [09:48<1:04:47,  9.57it/s]

 13%|████▍                              | 5327/42525 [09:48<1:02:48,  9.87it/s]

 13%|████▍                              | 5331/42525 [09:49<1:02:15,  9.96it/s]

 13%|████▍                              | 5334/42525 [09:49<1:04:47,  9.57it/s]

 13%|████▍                              | 5336/42525 [09:49<1:09:45,  8.89it/s]

 13%|████▍                              | 5338/42525 [09:50<1:11:58,  8.61it/s]

 13%|████▍                              | 5339/42525 [09:50<1:17:12,  8.03it/s]

 13%|████▍                              | 5343/42525 [09:50<1:08:29,  9.05it/s]

 13%|████▍                              | 5347/42525 [09:51<1:05:00,  9.53it/s]

 13%|████▍                              | 5350/42525 [09:51<1:03:13,  9.80it/s]

 13%|████▍                              | 5353/42525 [09:51<1:05:49,  9.41it/s]

 13%|████▍                              | 5355/42525 [09:51<1:04:17,  9.64it/s]

 13%|████▍                              | 5357/42525 [09:52<1:08:26,  9.05it/s]

 13%|████▍                              | 5360/42525 [09:52<1:11:30,  8.66it/s]

 13%|████▍                              | 5363/42525 [09:52<1:13:23,  8.44it/s]

 13%|████▍                              | 5364/42525 [09:52<1:16:05,  8.14it/s]

 13%|████▍                              | 5366/42525 [09:53<1:11:08,  8.71it/s]

 13%|████▍                              | 5369/42525 [09:53<1:09:49,  8.87it/s]

 13%|████▍                              | 5371/42525 [09:53<1:11:39,  8.64it/s]

 13%|████▍                              | 5374/42525 [09:54<1:07:31,  9.17it/s]

 13%|████▍                              | 5376/42525 [09:54<1:09:39,  8.89it/s]

 13%|████▍                              | 5378/42525 [09:54<1:10:33,  8.77it/s]

 13%|████▍                              | 5379/42525 [09:54<1:08:09,  9.08it/s]

 13%|████▍                              | 5383/42525 [09:55<1:05:25,  9.46it/s]

 13%|████▍                              | 5387/42525 [09:55<1:02:30,  9.90it/s]

 13%|████▍                              | 5389/42525 [09:55<1:13:44,  8.39it/s]

 13%|████▍                              | 5392/42525 [09:56<1:11:12,  8.69it/s]

 13%|████▍                              | 5394/42525 [09:56<1:14:26,  8.31it/s]

 13%|████▍                              | 5397/42525 [09:56<1:08:08,  9.08it/s]

 13%|████▍                              | 5398/42525 [09:56<1:08:55,  8.98it/s]

 13%|████▍                              | 5401/42525 [09:57<1:13:12,  8.45it/s]

 13%|████▍                              | 5403/42525 [09:57<1:17:05,  8.03it/s]

 13%|████▍                              | 5405/42525 [09:57<1:10:03,  8.83it/s]

 13%|████▍                              | 5409/42525 [09:57<1:08:21,  9.05it/s]

 13%|████▍                              | 5411/42525 [09:58<1:08:44,  9.00it/s]

 13%|████▍                              | 5413/42525 [09:58<1:05:37,  9.43it/s]

 13%|████▍                              | 5416/42525 [09:58<1:12:41,  8.51it/s]

 13%|████▍                              | 5418/42525 [09:59<1:13:47,  8.38it/s]

 13%|████▍                              | 5420/42525 [09:59<1:08:56,  8.97it/s]

 13%|████▍                              | 5422/42525 [09:59<1:13:32,  8.41it/s]

 13%|████▍                              | 5426/42525 [09:59<1:04:22,  9.61it/s]

 13%|████▍                              | 5429/42525 [10:00<1:04:12,  9.63it/s]

 13%|████▍                              | 5433/42525 [10:00<1:01:16, 10.09it/s]

 13%|████▍                              | 5435/42525 [10:00<1:08:11,  9.06it/s]

 13%|████▍                              | 5437/42525 [10:01<1:04:55,  9.52it/s]

 13%|████▍                              | 5439/42525 [10:01<1:07:43,  9.13it/s]

 13%|████▍                              | 5443/42525 [10:01<1:07:36,  9.14it/s]

 13%|████▍                              | 5446/42525 [10:02<1:08:05,  9.08it/s]

 13%|████▍                              | 5449/42525 [10:02<1:09:05,  8.94it/s]

 13%|████▍                              | 5450/42525 [10:02<1:09:47,  8.85it/s]

 13%|████▍                              | 5453/42525 [10:02<1:07:59,  9.09it/s]

 13%|████▍                              | 5456/42525 [10:03<1:08:14,  9.05it/s]

 13%|████▍                              | 5459/42525 [10:03<1:11:16,  8.67it/s]

 13%|████▍                              | 5461/42525 [10:03<1:16:24,  8.08it/s]

 13%|████▍                              | 5463/42525 [10:04<1:15:33,  8.17it/s]

 13%|████▍                              | 5465/42525 [10:04<1:16:37,  8.06it/s]

 13%|████▍                              | 5466/42525 [10:04<1:15:39,  8.16it/s]

 13%|████▌                              | 5469/42525 [10:04<1:13:49,  8.37it/s]

 13%|████▌                              | 5471/42525 [10:04<1:18:42,  7.85it/s]

 13%|████▌                              | 5474/42525 [10:05<1:09:04,  8.94it/s]

 13%|████▌                              | 5476/42525 [10:05<1:05:31,  9.42it/s]

 13%|████▌                              | 5478/42525 [10:05<1:09:38,  8.87it/s]

 13%|████▌                              | 5482/42525 [10:06<1:05:07,  9.48it/s]

 13%|████▌                              | 5484/42525 [10:06<1:05:12,  9.47it/s]

 13%|████▌                              | 5487/42525 [10:06<1:02:53,  9.82it/s]

 13%|████▌                              | 5490/42525 [10:06<1:02:38,  9.85it/s]

 13%|████▌                              | 5493/42525 [10:07<1:03:36,  9.70it/s]

 13%|████▌                              | 5495/42525 [10:07<1:12:10,  8.55it/s]

 13%|████▌                              | 5498/42525 [10:07<1:09:17,  8.91it/s]

 13%|████▌                              | 5500/42525 [10:08<1:19:18,  7.78it/s]

 13%|████▌                              | 5502/42525 [10:08<1:16:01,  8.12it/s]

 13%|████▌                              | 5504/42525 [10:08<1:11:41,  8.61it/s]

 13%|████▌                              | 5507/42525 [10:08<1:05:13,  9.46it/s]

 13%|████▌                              | 5509/42525 [10:09<1:04:53,  9.51it/s]

 13%|████▌                              | 5510/42525 [10:09<1:05:11,  9.46it/s]

 13%|████▌                              | 5514/42525 [10:09<1:02:52,  9.81it/s]

 13%|████▌                              | 5516/42525 [10:09<1:04:52,  9.51it/s]

 13%|████▌                              | 5518/42525 [10:10<1:02:51,  9.81it/s]

 13%|████▌                              | 5520/42525 [10:10<1:04:14,  9.60it/s]

 13%|████▌                              | 5523/42525 [10:10<1:06:40,  9.25it/s]

 13%|████▌                              | 5525/42525 [10:10<1:06:08,  9.32it/s]

 13%|████▌                              | 5528/42525 [10:11<1:11:18,  8.65it/s]

 13%|████▌                              | 5532/42525 [10:11<1:04:44,  9.52it/s]

 13%|████▌                              | 5535/42525 [10:11<1:06:13,  9.31it/s]

 13%|████▌                              | 5537/42525 [10:12<1:12:32,  8.50it/s]

 13%|████▌                              | 5538/42525 [10:12<1:13:55,  8.34it/s]

 13%|████▌                              | 5541/42525 [10:12<1:14:24,  8.28it/s]

 13%|████▌                              | 5543/42525 [10:12<1:11:38,  8.60it/s]

 13%|████▌                              | 5546/42525 [10:13<1:11:16,  8.65it/s]

 13%|████▌                              | 5548/42525 [10:13<1:16:35,  8.05it/s]

 13%|████▌                              | 5552/42525 [10:13<1:04:58,  9.48it/s]

 13%|████▌                              | 5554/42525 [10:14<1:05:05,  9.47it/s]

 13%|████▌                              | 5557/42525 [10:14<1:04:10,  9.60it/s]

 13%|████▌                              | 5559/42525 [10:14<1:08:45,  8.96it/s]

 13%|████▌                              | 5561/42525 [10:14<1:06:45,  9.23it/s]

 13%|████▌                              | 5564/42525 [10:15<1:15:27,  8.16it/s]

 13%|████▌                              | 5566/42525 [10:15<1:11:35,  8.60it/s]

 13%|████▌                              | 5568/42525 [10:15<1:06:46,  9.22it/s]

 13%|████▌                              | 5571/42525 [10:16<1:14:43,  8.24it/s]

 13%|████▌                              | 5574/42525 [10:16<1:13:22,  8.39it/s]

 13%|████▌                              | 5576/42525 [10:16<1:13:56,  8.33it/s]

 13%|████▌                              | 5578/42525 [10:16<1:16:54,  8.01it/s]

 13%|████▌                              | 5580/42525 [10:17<1:16:33,  8.04it/s]

 13%|████▌                              | 5582/42525 [10:17<1:16:33,  8.04it/s]

 13%|████▌                              | 5586/42525 [10:17<1:07:46,  9.08it/s]

 13%|████▌                              | 5588/42525 [10:18<1:11:46,  8.58it/s]

 13%|████▌                              | 5591/42525 [10:18<1:07:13,  9.16it/s]

 13%|████▌                              | 5592/42525 [10:18<1:07:45,  9.08it/s]

 13%|████▌                              | 5595/42525 [10:18<1:09:56,  8.80it/s]

 13%|████▌                              | 5597/42525 [10:18<1:07:19,  9.14it/s]

 13%|████▌                              | 5598/42525 [10:19<1:13:44,  8.35it/s]

 13%|████▌                              | 5602/42525 [10:19<1:04:59,  9.47it/s]

 13%|████▌                              | 5605/42525 [10:19<1:03:39,  9.67it/s]

 13%|████▌                              | 5607/42525 [10:20<1:08:35,  8.97it/s]

 13%|████▌                              | 5610/42525 [10:20<1:07:32,  9.11it/s]

 13%|████▌                              | 5613/42525 [10:20<1:03:40,  9.66it/s]

 13%|████▌                              | 5615/42525 [10:20<1:07:53,  9.06it/s]

 13%|████▌                              | 5619/42525 [10:21<1:03:19,  9.71it/s]

 13%|████▋                              | 5621/42525 [10:21<1:09:28,  8.85it/s]

 13%|████▋                              | 5624/42525 [10:21<1:04:59,  9.46it/s]

 13%|████▋                              | 5626/42525 [10:22<1:09:41,  8.82it/s]

 13%|████▋                              | 5629/42525 [10:22<1:13:01,  8.42it/s]

 13%|████▋                              | 5631/42525 [10:22<1:15:51,  8.11it/s]

 13%|████▋                              | 5634/42525 [10:23<1:16:50,  8.00it/s]

 13%|████▋                              | 5636/42525 [10:23<1:12:48,  8.44it/s]

 13%|████▋                              | 5638/42525 [10:23<1:18:16,  7.85it/s]

 13%|████▋                              | 5640/42525 [10:23<1:10:15,  8.75it/s]

 13%|████▋                              | 5644/42525 [10:24<1:03:27,  9.69it/s]

 13%|████▋                              | 5646/42525 [10:24<1:02:02,  9.91it/s]

 13%|████▋                              | 5649/42525 [10:24<1:05:50,  9.33it/s]

 13%|████▋                              | 5653/42525 [10:25<1:02:27,  9.84it/s]

 13%|████▋                              | 5656/42525 [10:25<1:02:17,  9.86it/s]

 13%|████▋                              | 5658/42525 [10:25<1:05:43,  9.35it/s]

 13%|████▋                              | 5660/42525 [10:25<1:16:06,  8.07it/s]

 13%|████▋                              | 5663/42525 [10:26<1:10:51,  8.67it/s]

 13%|████▋                              | 5664/42525 [10:26<1:11:04,  8.64it/s]

 13%|████▋                              | 5667/42525 [10:26<1:09:16,  8.87it/s]

 13%|████▋                              | 5670/42525 [10:27<1:05:43,  9.34it/s]

 13%|████▋                              | 5673/42525 [10:27<1:04:11,  9.57it/s]

 13%|████▋                              | 5676/42525 [10:27<1:02:26,  9.83it/s]

 13%|████▋                              | 5679/42525 [10:27<1:03:01,  9.74it/s]

 13%|████▋                              | 5682/42525 [10:28<1:03:23,  9.69it/s]

 13%|████▋                              | 5685/42525 [10:28<1:08:21,  8.98it/s]

 13%|████▋                              | 5687/42525 [10:28<1:06:30,  9.23it/s]

 13%|████▋                              | 5689/42525 [10:29<1:12:18,  8.49it/s]

 13%|████▋                              | 5692/42525 [10:29<1:05:37,  9.36it/s]

 13%|████▋                              | 5694/42525 [10:29<1:16:53,  7.98it/s]

 13%|████▋                              | 5696/42525 [10:29<1:12:51,  8.43it/s]

 13%|████▋                              | 5697/42525 [10:30<1:11:47,  8.55it/s]

 13%|████▋                              | 5700/42525 [10:30<1:14:28,  8.24it/s]

 13%|████▋                              | 5703/42525 [10:30<1:10:55,  8.65it/s]

 13%|████▋                              | 5706/42525 [10:31<1:07:56,  9.03it/s]

 13%|████▋                              | 5708/42525 [10:31<1:05:33,  9.36it/s]

 13%|████▋                              | 5710/42525 [10:31<1:09:18,  8.85it/s]

 13%|████▋                              | 5712/42525 [10:31<1:07:09,  9.14it/s]

 13%|████▋                              | 5715/42525 [10:32<1:07:28,  9.09it/s]

 13%|████▋                              | 5718/42525 [10:32<1:04:18,  9.54it/s]

 13%|████▋                              | 5721/42525 [10:32<1:02:33,  9.81it/s]

 13%|████▋                              | 5724/42525 [10:32<1:01:45,  9.93it/s]

 13%|████▋                              | 5726/42525 [10:33<1:09:15,  8.86it/s]

 13%|████▋                              | 5729/42525 [10:33<1:05:58,  9.30it/s]

 13%|████▋                              | 5732/42525 [10:33<1:03:09,  9.71it/s]

 13%|████▋                              | 5734/42525 [10:34<1:09:30,  8.82it/s]

 13%|████▋                              | 5735/42525 [10:34<1:08:05,  9.01it/s]

 13%|████▋                              | 5738/42525 [10:34<1:13:23,  8.35it/s]

 13%|████▋                              | 5739/42525 [10:34<1:10:22,  8.71it/s]

 14%|████▋                              | 5741/42525 [10:34<1:07:10,  9.13it/s]

 14%|████▋                              | 5745/42525 [10:35<1:06:49,  9.17it/s]

 14%|████▋                              | 5749/42525 [10:35<1:02:37,  9.79it/s]

 14%|████▋                              | 5751/42525 [10:35<1:09:53,  8.77it/s]

 14%|████▋                              | 5754/42525 [10:36<1:05:05,  9.41it/s]

 14%|████▋                              | 5756/42525 [10:36<1:12:10,  8.49it/s]

 14%|████▋                              | 5758/42525 [10:36<1:13:51,  8.30it/s]

 14%|████▋                              | 5762/42525 [10:37<1:06:09,  9.26it/s]

 14%|████▋                              | 5764/42525 [10:37<1:08:54,  8.89it/s]

 14%|████▋                              | 5767/42525 [10:37<1:07:50,  9.03it/s]

 14%|████▋                              | 5770/42525 [10:38<1:04:00,  9.57it/s]

 14%|████▊                              | 5772/42525 [10:38<1:10:29,  8.69it/s]

 14%|████▊                              | 5775/42525 [10:38<1:05:52,  9.30it/s]

 14%|████▊                              | 5777/42525 [10:38<1:06:30,  9.21it/s]

 14%|████▊                              | 5780/42525 [10:39<1:03:14,  9.68it/s]

 14%|████▊                              | 5783/42525 [10:39<1:01:27,  9.96it/s]

 14%|████▊                              | 5786/42525 [10:39<1:03:04,  9.71it/s]

 14%|████▊                              | 5789/42525 [10:40<1:12:28,  8.45it/s]

 14%|████▊                              | 5791/42525 [10:40<1:07:23,  9.08it/s]

 14%|████▊                              | 5794/42525 [10:40<1:11:32,  8.56it/s]

 14%|████▊                              | 5797/42525 [10:41<1:10:25,  8.69it/s]

 14%|████▊                              | 5800/42525 [10:41<1:10:50,  8.64it/s]

 14%|████▊                              | 5802/42525 [10:41<1:05:57,  9.28it/s]

 14%|████▊                              | 5804/42525 [10:41<1:08:53,  8.88it/s]

 14%|████▊                              | 5807/42525 [10:42<1:14:33,  8.21it/s]

 14%|████▊                              | 5811/42525 [10:42<1:10:15,  8.71it/s]

 14%|████▊                              | 5813/42525 [10:42<1:13:45,  8.30it/s]

 14%|████▊                              | 5815/42525 [10:43<1:16:20,  8.01it/s]

 14%|████▊                              | 5819/42525 [10:43<1:05:34,  9.33it/s]

 14%|████▊                              | 5823/42525 [10:43<1:01:47,  9.90it/s]

 14%|████▊                              | 5827/42525 [10:44<1:01:09, 10.00it/s]

 14%|████▊                              | 5830/42525 [10:44<1:00:41, 10.08it/s]

 14%|████▊                              | 5832/42525 [10:44<1:00:37, 10.09it/s]

 14%|████▊                              | 5836/42525 [10:45<1:00:54, 10.04it/s]

 14%|████▊                              | 5839/42525 [10:45<1:08:49,  8.88it/s]

 14%|████▊                              | 5841/42525 [10:45<1:07:40,  9.04it/s]

 14%|████▊                              | 5844/42525 [10:46<1:06:03,  9.26it/s]

 14%|████▊                              | 5845/42525 [10:46<1:06:17,  9.22it/s]

 14%|████▊                              | 5848/42525 [10:46<1:07:51,  9.01it/s]

 14%|████▊                              | 5851/42525 [10:46<1:05:54,  9.27it/s]

 14%|████▊                              | 5854/42525 [10:47<1:05:25,  9.34it/s]

 14%|████▊                              | 5857/42525 [10:47<1:06:26,  9.20it/s]

 14%|████▊                              | 5859/42525 [10:47<1:07:11,  9.09it/s]

 14%|████▊                              | 5861/42525 [10:48<1:10:25,  8.68it/s]

 14%|████▊                              | 5863/42525 [10:48<1:08:21,  8.94it/s]

 14%|████▊                              | 5865/42525 [10:48<1:18:49,  7.75it/s]

 14%|████▊                              | 5867/42525 [10:48<1:19:08,  7.72it/s]

 14%|████▊                              | 5869/42525 [10:49<1:24:55,  7.19it/s]

 14%|████▊                              | 5870/42525 [10:49<1:21:06,  7.53it/s]

 14%|████▊                              | 5873/42525 [10:49<1:17:29,  7.88it/s]

 14%|████▊                              | 5875/42525 [10:49<1:11:50,  8.50it/s]

 14%|████▊                              | 5876/42525 [10:49<1:09:51,  8.74it/s]

 14%|████▊                              | 5880/42525 [10:50<1:04:07,  9.53it/s]

 14%|████▊                              | 5884/42525 [10:50<1:01:03, 10.00it/s]

 14%|████▊                              | 5887/42525 [10:50<1:04:24,  9.48it/s]

 14%|████▊                              | 5889/42525 [10:51<1:06:12,  9.22it/s]

 14%|████▊                              | 5891/42525 [10:51<1:03:49,  9.57it/s]

 14%|████▊                              | 5895/42525 [10:51<1:01:49,  9.87it/s]

 14%|████▊                              | 5898/42525 [10:52<1:04:30,  9.46it/s]

 14%|████▊                              | 5900/42525 [10:52<1:04:52,  9.41it/s]

 14%|████▊                              | 5903/42525 [10:52<1:05:27,  9.32it/s]

 14%|████▊                              | 5905/42525 [10:52<1:15:45,  8.06it/s]

 14%|████▊                              | 5906/42525 [10:53<1:19:11,  7.71it/s]

 14%|████▊                              | 5909/42525 [10:53<1:10:14,  8.69it/s]

 14%|████▊                              | 5912/42525 [10:53<1:07:50,  9.00it/s]

 14%|████▊                              | 5914/42525 [10:54<1:09:50,  8.74it/s]

 14%|████▊                              | 5915/42525 [10:54<1:15:15,  8.11it/s]

 14%|████▊                              | 5918/42525 [10:54<1:09:25,  8.79it/s]

 14%|████▊                              | 5921/42525 [10:54<1:08:28,  8.91it/s]

 14%|████▉                              | 5925/42525 [10:55<1:07:01,  9.10it/s]

 14%|████▉                              | 5928/42525 [10:55<1:04:51,  9.40it/s]

 14%|████▉                              | 5930/42525 [10:55<1:07:07,  9.09it/s]

 14%|████▉                              | 5931/42525 [10:55<1:12:57,  8.36it/s]

 14%|████▉                              | 5934/42525 [10:56<1:08:21,  8.92it/s]

 14%|████▉                              | 5936/42525 [10:56<1:10:04,  8.70it/s]

 14%|████▉                              | 5939/42525 [10:56<1:11:30,  8.53it/s]

 14%|████▉                              | 5942/42525 [10:57<1:05:54,  9.25it/s]

 14%|████▉                              | 5945/42525 [10:57<1:04:07,  9.51it/s]

 14%|████▉                              | 5947/42525 [10:57<1:04:18,  9.48it/s]

 14%|████▉                              | 5949/42525 [10:57<1:11:11,  8.56it/s]

 14%|████▉                              | 5950/42525 [10:58<1:13:02,  8.35it/s]

 14%|████▉                              | 5954/42525 [10:58<1:06:18,  9.19it/s]

 14%|████▉                              | 5957/42525 [10:58<1:06:35,  9.15it/s]

 14%|████▉                              | 5958/42525 [10:58<1:07:11,  9.07it/s]

 14%|████▉                              | 5960/42525 [10:59<1:05:05,  9.36it/s]

 14%|████▉                              | 5963/42525 [10:59<1:08:01,  8.96it/s]

 14%|████▉                              | 5966/42525 [10:59<1:07:06,  9.08it/s]

 14%|████▉                              | 5970/42525 [11:00<1:02:26,  9.76it/s]

 14%|████▉                              | 5973/42525 [11:00<1:04:45,  9.41it/s]

 14%|████▉                              | 5976/42525 [11:00<1:05:34,  9.29it/s]

 14%|████▉                              | 5977/42525 [11:00<1:05:02,  9.37it/s]

 14%|████▉                              | 5980/42525 [11:01<1:05:07,  9.35it/s]

 14%|████▉                              | 5982/42525 [11:01<1:10:01,  8.70it/s]

 14%|████▉                              | 5984/42525 [11:01<1:08:49,  8.85it/s]

 14%|████▉                              | 5988/42525 [11:02<1:07:09,  9.07it/s]

 14%|████▉                              | 5989/42525 [11:02<1:12:12,  8.43it/s]

 14%|████▉                              | 5992/42525 [11:02<1:12:17,  8.42it/s]

 14%|████▉                              | 5994/42525 [11:02<1:07:38,  9.00it/s]

 14%|████▉                              | 5997/42525 [11:03<1:09:03,  8.81it/s]

 14%|████▉                              | 5999/42525 [11:03<1:13:38,  8.27it/s]

 14%|████▉                              | 6001/42525 [11:03<1:18:32,  7.75it/s]

 14%|████▉                              | 6004/42525 [11:04<1:10:31,  8.63it/s]

 14%|████▉                              | 6007/42525 [11:04<1:06:22,  9.17it/s]

 14%|████▉                              | 6010/42525 [11:04<1:02:38,  9.71it/s]

 14%|████▉                              | 6012/42525 [11:04<1:03:07,  9.64it/s]

 14%|████▉                              | 6015/42525 [11:05<1:09:46,  8.72it/s]

 14%|████▉                              | 6018/42525 [11:05<1:07:02,  9.08it/s]

 14%|████▉                              | 6021/42525 [11:05<1:05:30,  9.29it/s]

 14%|████▉                              | 6025/42525 [11:06<1:02:13,  9.78it/s]

 14%|████▉                              | 6027/42525 [11:06<1:02:52,  9.68it/s]

 14%|████▉                              | 6031/42525 [11:06<1:00:54,  9.99it/s]

 14%|████▉                              | 6034/42525 [11:07<1:04:35,  9.42it/s]

 14%|████▉                              | 6037/42525 [11:07<1:02:38,  9.71it/s]

 14%|████▉                              | 6038/42525 [11:07<1:04:50,  9.38it/s]

 14%|████▉                              | 6041/42525 [11:08<1:04:03,  9.49it/s]

 14%|████▉                              | 6043/42525 [11:08<1:06:14,  9.18it/s]

 14%|████▉                              | 6047/42525 [11:08<1:01:42,  9.85it/s]

 14%|████▉                              | 6049/42525 [11:08<1:05:11,  9.32it/s]

 14%|████▉                              | 6051/42525 [11:09<1:08:55,  8.82it/s]

 14%|████▉                              | 6053/42525 [11:09<1:04:37,  9.41it/s]

 14%|████▉                              | 6056/42525 [11:09<1:04:31,  9.42it/s]

 14%|████▉                              | 6058/42525 [11:09<1:02:39,  9.70it/s]

 14%|████▉                              | 6060/42525 [11:10<1:02:24,  9.74it/s]

 14%|████▉                              | 6063/42525 [11:10<1:06:07,  9.19it/s]

 14%|████▉                              | 6066/42525 [11:10<1:04:38,  9.40it/s]

 14%|████▉                              | 6070/42525 [11:11<1:04:57,  9.35it/s]

 14%|████▉                              | 6073/42525 [11:11<1:02:51,  9.66it/s]

 14%|█████                              | 6076/42525 [11:11<1:05:35,  9.26it/s]

 14%|█████                              | 6078/42525 [11:11<1:03:12,  9.61it/s]

 14%|█████                              | 6081/42525 [11:12<1:06:19,  9.16it/s]

 14%|█████                              | 6083/42525 [11:12<1:15:36,  8.03it/s]

 14%|█████                              | 6086/42525 [11:12<1:13:52,  8.22it/s]

 14%|█████                              | 6088/42525 [11:13<1:21:45,  7.43it/s]

 14%|█████                              | 6090/42525 [11:13<1:18:21,  7.75it/s]

 14%|█████                              | 6093/42525 [11:13<1:20:16,  7.56it/s]

 14%|█████                              | 6097/42525 [11:14<1:07:33,  8.99it/s]

 14%|█████                              | 6100/42525 [11:14<1:06:48,  9.09it/s]

 14%|█████                              | 6102/42525 [11:14<1:08:36,  8.85it/s]

 14%|█████                              | 6104/42525 [11:15<1:04:55,  9.35it/s]

 14%|█████                              | 6107/42525 [11:15<1:08:07,  8.91it/s]

 14%|█████                              | 6109/42525 [11:15<1:06:40,  9.10it/s]

 14%|█████                              | 6111/42525 [11:15<1:06:56,  9.07it/s]

 14%|█████                              | 6114/42525 [11:16<1:04:26,  9.42it/s]

 14%|█████                              | 6117/42525 [11:16<1:03:21,  9.58it/s]

 14%|█████                              | 6119/42525 [11:16<1:04:53,  9.35it/s]

 14%|█████                              | 6122/42525 [11:17<1:02:02,  9.78it/s]

 14%|█████                              | 6125/42525 [11:17<1:02:39,  9.68it/s]

 14%|█████                              | 6128/42525 [11:17<1:01:42,  9.83it/s]

 14%|█████                              | 6131/42525 [11:17<1:07:04,  9.04it/s]

 14%|█████                              | 6134/42525 [11:18<1:06:19,  9.14it/s]

 14%|█████                              | 6136/42525 [11:18<1:04:42,  9.37it/s]

 14%|█████                              | 6139/42525 [11:18<1:09:11,  8.76it/s]

 14%|█████                              | 6142/42525 [11:19<1:05:39,  9.24it/s]

 14%|█████                              | 6145/42525 [11:19<1:02:34,  9.69it/s]

 14%|█████                              | 6148/42525 [11:19<1:02:30,  9.70it/s]

 14%|█████                              | 6151/42525 [11:20<1:04:45,  9.36it/s]

 14%|█████                              | 6153/42525 [11:20<1:04:30,  9.40it/s]

 14%|█████                              | 6155/42525 [11:20<1:09:10,  8.76it/s]

 14%|█████                              | 6158/42525 [11:20<1:05:01,  9.32it/s]

 14%|█████                              | 6162/42525 [11:21<1:01:05,  9.92it/s]

 14%|█████                              | 6164/42525 [11:21<1:07:37,  8.96it/s]

 15%|█████                              | 6167/42525 [11:21<1:03:27,  9.55it/s]

 15%|█████                              | 6170/42525 [11:22<1:04:36,  9.38it/s]

 15%|█████                              | 6172/42525 [11:22<1:08:18,  8.87it/s]

 15%|█████                              | 6176/42525 [11:22<1:06:37,  9.09it/s]

 15%|█████                              | 6177/42525 [11:22<1:07:16,  9.01it/s]

 15%|█████                              | 6180/42525 [11:23<1:10:12,  8.63it/s]

 15%|█████                              | 6181/42525 [11:23<1:08:43,  8.81it/s]

 15%|█████                              | 6184/42525 [11:23<1:05:23,  9.26it/s]

 15%|█████                              | 6186/42525 [11:23<1:05:31,  9.24it/s]

 15%|█████                              | 6188/42525 [11:24<1:09:33,  8.71it/s]

 15%|█████                              | 6190/42525 [11:24<1:06:36,  9.09it/s]

 15%|█████                              | 6193/42525 [11:24<1:05:51,  9.20it/s]

 15%|█████                              | 6195/42525 [11:24<1:04:19,  9.41it/s]

 15%|█████                              | 6197/42525 [11:25<1:10:37,  8.57it/s]

 15%|█████                              | 6199/42525 [11:25<1:18:05,  7.75it/s]

 15%|█████                              | 6203/42525 [11:25<1:05:43,  9.21it/s]

 15%|█████                              | 6205/42525 [11:26<1:10:54,  8.54it/s]

 15%|█████                              | 6206/42525 [11:26<1:15:12,  8.05it/s]

 15%|█████                              | 6210/42525 [11:26<1:06:03,  9.16it/s]

 15%|█████                              | 6214/42525 [11:27<1:02:31,  9.68it/s]

 15%|█████                              | 6216/42525 [11:27<1:01:12,  9.89it/s]

 15%|█████                              | 6219/42525 [11:27<1:03:01,  9.60it/s]

 15%|█████                              | 6221/42525 [11:27<1:04:22,  9.40it/s]

 15%|█████                              | 6223/42525 [11:28<1:11:47,  8.43it/s]

 15%|█████                              | 6226/42525 [11:28<1:07:25,  8.97it/s]

 15%|█████▏                             | 6229/42525 [11:28<1:03:48,  9.48it/s]

 15%|█████▏                             | 6230/42525 [11:28<1:05:27,  9.24it/s]

 15%|█████▏                             | 6233/42525 [11:29<1:07:07,  9.01it/s]

 15%|█████▏                             | 6237/42525 [11:29<1:02:38,  9.65it/s]

 15%|█████▏                             | 6240/42525 [11:29<1:04:34,  9.37it/s]

 15%|█████▏                             | 6242/42525 [11:30<1:02:47,  9.63it/s]

 15%|█████▏                             | 6244/42525 [11:30<1:02:55,  9.61it/s]

 15%|█████▏                             | 6247/42525 [11:30<1:07:19,  8.98it/s]

 15%|█████▏                             | 6249/42525 [11:30<1:16:42,  7.88it/s]

 15%|█████▏                             | 6251/42525 [11:31<1:09:27,  8.70it/s]

 15%|█████▏                             | 6254/42525 [11:31<1:06:28,  9.09it/s]

 15%|█████▏                             | 6257/42525 [11:31<1:04:01,  9.44it/s]

 15%|█████▏                             | 6258/42525 [11:31<1:09:50,  8.66it/s]

 15%|█████▏                             | 6260/42525 [11:32<1:11:48,  8.42it/s]

 15%|█████▏                             | 6263/42525 [11:32<1:11:32,  8.45it/s]

 15%|█████▏                             | 6264/42525 [11:32<1:15:13,  8.03it/s]

 15%|█████▏                             | 6267/42525 [11:33<1:12:16,  8.36it/s]

 15%|█████▏                             | 6270/42525 [11:33<1:08:53,  8.77it/s]

 15%|█████▏                             | 6274/42525 [11:33<1:02:27,  9.67it/s]

 15%|█████▏                             | 6276/42525 [11:33<1:08:33,  8.81it/s]

 15%|█████▏                             | 6278/42525 [11:34<1:12:44,  8.31it/s]

 15%|█████▏                             | 6280/42525 [11:34<1:20:46,  7.48it/s]

 15%|█████▏                             | 6283/42525 [11:34<1:10:58,  8.51it/s]

 15%|█████▏                             | 6287/42525 [11:35<1:03:13,  9.55it/s]

 15%|█████▏                             | 6290/42525 [11:35<1:07:02,  9.01it/s]

 15%|█████▏                             | 6292/42525 [11:35<1:09:53,  8.64it/s]

 15%|█████▏                             | 6295/42525 [11:36<1:06:37,  9.06it/s]

 15%|█████▏                             | 6299/42525 [11:36<1:01:50,  9.76it/s]

 15%|█████▏                             | 6300/42525 [11:36<1:07:21,  8.96it/s]

 15%|█████▏                             | 6304/42525 [11:37<1:04:11,  9.40it/s]

 15%|█████▏                             | 6307/42525 [11:37<1:02:01,  9.73it/s]

 15%|█████▏                             | 6310/42525 [11:37<1:06:56,  9.02it/s]

 15%|█████▏                             | 6311/42525 [11:37<1:10:00,  8.62it/s]

 15%|█████▏                             | 6315/42525 [11:38<1:07:19,  8.96it/s]

 15%|█████▏                             | 6318/42525 [11:38<1:03:59,  9.43it/s]

 15%|█████▏                             | 6321/42525 [11:38<1:01:48,  9.76it/s]

 15%|█████▏                             | 6322/42525 [11:39<1:07:55,  8.88it/s]

 15%|█████▏                             | 6324/42525 [11:39<1:06:44,  9.04it/s]

 15%|█████▏                             | 6327/42525 [11:39<1:08:47,  8.77it/s]

 15%|█████▏                             | 6329/42525 [11:39<1:06:16,  9.10it/s]

 15%|█████▏                             | 6331/42525 [11:40<1:06:38,  9.05it/s]

 15%|█████▏                             | 6333/42525 [11:40<1:09:58,  8.62it/s]

 15%|█████▏                             | 6335/42525 [11:40<1:06:34,  9.06it/s]

 15%|█████▏                             | 6338/42525 [11:40<1:08:04,  8.86it/s]

 15%|█████▏                             | 6340/42525 [11:41<1:10:59,  8.49it/s]

 15%|█████▏                             | 6342/42525 [11:41<1:14:08,  8.13it/s]

 15%|█████▏                             | 6345/42525 [11:41<1:13:03,  8.25it/s]

 15%|█████▏                             | 6347/42525 [11:41<1:16:14,  7.91it/s]

 15%|█████▏                             | 6350/42525 [11:42<1:08:41,  8.78it/s]

 15%|█████▏                             | 6353/42525 [11:42<1:10:40,  8.53it/s]

 15%|█████▏                             | 6356/42525 [11:42<1:05:20,  9.23it/s]

 15%|█████▏                             | 6359/42525 [11:43<1:06:08,  9.11it/s]

 15%|█████▏                             | 6362/42525 [11:43<1:09:07,  8.72it/s]

 15%|█████▏                             | 6366/42525 [11:44<1:03:16,  9.52it/s]

 15%|█████▏                             | 6368/42525 [11:44<1:08:29,  8.80it/s]

 15%|█████▏                             | 6371/42525 [11:44<1:04:28,  9.34it/s]

 15%|█████▏                             | 6374/42525 [11:44<1:01:19,  9.83it/s]

 15%|█████▏                             | 6377/42525 [11:45<1:00:37,  9.94it/s]

 15%|█████▎                             | 6380/42525 [11:45<1:05:47,  9.16it/s]

 15%|█████▎                             | 6381/42525 [11:45<1:05:33,  9.19it/s]

 15%|█████▎                             | 6384/42525 [11:46<1:12:54,  8.26it/s]

 15%|█████▎                             | 6386/42525 [11:46<1:12:41,  8.29it/s]

 15%|█████▎                             | 6387/42525 [11:46<1:09:45,  8.63it/s]

 15%|█████▎                             | 6390/42525 [11:46<1:11:55,  8.37it/s]

 15%|█████▎                             | 6393/42525 [11:47<1:09:17,  8.69it/s]

 15%|█████▎                             | 6397/42525 [11:47<1:03:30,  9.48it/s]

 15%|█████▎                             | 6399/42525 [11:47<1:11:41,  8.40it/s]

 15%|█████▎                             | 6402/42525 [11:48<1:09:19,  8.68it/s]

 15%|█████▎                             | 6404/42525 [11:48<1:06:03,  9.11it/s]

 15%|█████▎                             | 6407/42525 [11:48<1:11:01,  8.48it/s]

 15%|█████▎                             | 6411/42525 [11:49<1:04:26,  9.34it/s]

 15%|█████▎                             | 6413/42525 [11:49<1:09:59,  8.60it/s]

 15%|█████▎                             | 6415/42525 [11:49<1:15:34,  7.96it/s]

 15%|█████▎                             | 6418/42525 [11:49<1:08:11,  8.83it/s]

 15%|█████▎                             | 6420/42525 [11:50<1:05:56,  9.13it/s]

 15%|█████▎                             | 6422/42525 [11:50<1:05:47,  9.15it/s]

 15%|█████▎                             | 6425/42525 [11:50<1:02:24,  9.64it/s]

 15%|█████▎                             | 6427/42525 [11:50<1:15:12,  8.00it/s]

 15%|█████▎                             | 6429/42525 [11:51<1:15:25,  7.98it/s]

 15%|█████▎                             | 6431/42525 [11:51<1:11:21,  8.43it/s]

 15%|█████▎                             | 6434/42525 [11:51<1:09:49,  8.61it/s]

 15%|█████▎                             | 6435/42525 [11:51<1:13:16,  8.21it/s]

 15%|█████▎                             | 6438/42525 [11:52<1:12:28,  8.30it/s]

 15%|█████▎                             | 6440/42525 [11:52<1:15:24,  7.98it/s]

 15%|█████▎                             | 6442/42525 [11:52<1:11:52,  8.37it/s]

 15%|█████▎                             | 6444/42525 [11:53<1:17:54,  7.72it/s]

 15%|█████▎                             | 6447/42525 [11:53<1:06:39,  9.02it/s]

 15%|█████▎                             | 6449/42525 [11:53<1:02:54,  9.56it/s]

 15%|█████▎                             | 6452/42525 [11:53<1:11:31,  8.41it/s]

 15%|█████▎                             | 6455/42525 [11:54<1:06:16,  9.07it/s]

 15%|█████▎                             | 6458/42525 [11:54<1:08:57,  8.72it/s]

 15%|█████▎                             | 6461/42525 [11:54<1:08:07,  8.82it/s]

 15%|█████▎                             | 6463/42525 [11:55<1:14:40,  8.05it/s]

 15%|█████▎                             | 6466/42525 [11:55<1:05:57,  9.11it/s]

 15%|█████▎                             | 6468/42525 [11:55<1:03:14,  9.50it/s]

 15%|█████▎                             | 6471/42525 [11:55<1:02:43,  9.58it/s]

 15%|█████▎                             | 6473/42525 [11:56<1:08:56,  8.72it/s]

 15%|█████▎                             | 6475/42525 [11:56<1:05:05,  9.23it/s]

 15%|█████▎                             | 6477/42525 [11:56<1:11:20,  8.42it/s]

 15%|█████▎                             | 6480/42525 [11:57<1:06:49,  8.99it/s]

 15%|█████▎                             | 6482/42525 [11:57<1:04:02,  9.38it/s]

 15%|█████▎                             | 6484/42525 [11:57<1:10:35,  8.51it/s]

 15%|█████▎                             | 6486/42525 [11:57<1:10:41,  8.50it/s]

 15%|█████▎                             | 6488/42525 [11:57<1:17:42,  7.73it/s]

 15%|█████▎                             | 6490/42525 [11:58<1:17:15,  7.77it/s]

 15%|█████▎                             | 6491/42525 [11:58<1:17:23,  7.76it/s]

 15%|█████▎                             | 6494/42525 [11:58<1:15:01,  8.00it/s]

 15%|█████▎                             | 6496/42525 [11:58<1:10:03,  8.57it/s]

 15%|█████▎                             | 6498/42525 [11:59<1:13:38,  8.15it/s]

 15%|█████▎                             | 6501/42525 [11:59<1:07:41,  8.87it/s]

 15%|█████▎                             | 6504/42525 [11:59<1:04:16,  9.34it/s]

 15%|█████▎                             | 6506/42525 [12:00<1:04:34,  9.30it/s]

 15%|█████▎                             | 6508/42525 [12:00<1:05:34,  9.16it/s]

 15%|█████▎                             | 6511/42525 [12:00<1:04:10,  9.35it/s]

 15%|█████▎                             | 6513/42525 [12:00<1:10:30,  8.51it/s]

 15%|█████▎                             | 6516/42525 [12:01<1:06:24,  9.04it/s]

 15%|█████▎                             | 6519/42525 [12:01<1:06:06,  9.08it/s]

 15%|█████▎                             | 6523/42525 [12:01<1:01:57,  9.68it/s]

 15%|█████▎                             | 6526/42525 [12:02<1:00:56,  9.84it/s]

 15%|█████▎                             | 6529/42525 [12:02<1:00:33,  9.91it/s]

 15%|█████▍                             | 6531/42525 [12:02<1:12:06,  8.32it/s]

 15%|█████▍                             | 6533/42525 [12:02<1:06:33,  9.01it/s]

 15%|█████▍                             | 6537/42525 [12:03<1:02:35,  9.58it/s]

 15%|█████▍                             | 6539/42525 [12:03<1:06:40,  9.00it/s]

 15%|█████▍                             | 6540/42525 [12:03<1:05:06,  9.21it/s]

 15%|█████▍                             | 6542/42525 [12:03<1:08:50,  8.71it/s]

 15%|█████▍                             | 6545/42525 [12:04<1:08:22,  8.77it/s]

 15%|█████▍                             | 6547/42525 [12:04<1:14:29,  8.05it/s]

 15%|█████▍                             | 6550/42525 [12:04<1:09:48,  8.59it/s]

 15%|█████▍                             | 6552/42525 [12:05<1:07:57,  8.82it/s]

 15%|█████▍                             | 6555/42525 [12:05<1:03:37,  9.42it/s]

 15%|█████▍                             | 6558/42525 [12:05<1:02:15,  9.63it/s]

 15%|█████▍                             | 6560/42525 [12:05<1:06:46,  8.98it/s]

 15%|█████▍                             | 6564/42525 [12:06<1:01:42,  9.71it/s]

 15%|█████▍                             | 6566/42525 [12:06<1:07:40,  8.85it/s]

 15%|█████▍                             | 6568/42525 [12:06<1:12:18,  8.29it/s]

 15%|█████▍                             | 6570/42525 [12:07<1:14:05,  8.09it/s]

 15%|█████▍                             | 6572/42525 [12:07<1:09:35,  8.61it/s]

 15%|█████▍                             | 6574/42525 [12:07<1:17:24,  7.74it/s]

 15%|█████▍                             | 6576/42525 [12:07<1:17:15,  7.75it/s]

 15%|█████▍                             | 6578/42525 [12:08<1:15:21,  7.95it/s]

 15%|█████▍                             | 6581/42525 [12:08<1:05:25,  9.16it/s]

 15%|█████▍                             | 6582/42525 [12:08<1:11:17,  8.40it/s]

 15%|█████▍                             | 6585/42525 [12:08<1:12:54,  8.22it/s]

 15%|█████▍                             | 6586/42525 [12:09<1:11:51,  8.34it/s]

 15%|█████▍                             | 6589/42525 [12:09<1:08:36,  8.73it/s]

 15%|█████▍                             | 6590/42525 [12:09<1:13:39,  8.13it/s]

 16%|█████▍                             | 6593/42525 [12:09<1:10:12,  8.53it/s]

 16%|█████▍                             | 6596/42525 [12:10<1:04:05,  9.34it/s]

 16%|█████▍                             | 6598/42525 [12:10<1:06:52,  8.95it/s]

 16%|█████▍                             | 6600/42525 [12:10<1:03:30,  9.43it/s]

 16%|█████▍                             | 6604/42525 [12:11<1:01:34,  9.72it/s]

 16%|█████▍                             | 6606/42525 [12:11<1:07:56,  8.81it/s]

 16%|█████▍                             | 6609/42525 [12:11<1:04:42,  9.25it/s]

 16%|█████▍                             | 6611/42525 [12:11<1:15:36,  7.92it/s]

 16%|█████▍                             | 6613/42525 [12:12<1:10:14,  8.52it/s]

 16%|█████▍                             | 6616/42525 [12:12<1:04:09,  9.33it/s]

 16%|█████▍                             | 6618/42525 [12:12<1:06:35,  8.99it/s]

 16%|█████▍                             | 6620/42525 [12:12<1:10:44,  8.46it/s]

 16%|█████▍                             | 6622/42525 [12:13<1:09:01,  8.67it/s]

 16%|█████▍                             | 6625/42525 [12:13<1:03:04,  9.49it/s]

 16%|█████▍                             | 6627/42525 [12:13<1:01:42,  9.69it/s]

 16%|█████▍                             | 6630/42525 [12:13<1:06:27,  9.00it/s]

 16%|█████▍                             | 6633/42525 [12:14<1:02:32,  9.56it/s]

 16%|█████▍                             | 6636/42525 [12:14<1:07:40,  8.84it/s]

 16%|█████▍                             | 6640/42525 [12:14<1:01:38,  9.70it/s]

 16%|█████▍                             | 6641/42525 [12:15<1:03:32,  9.41it/s]

 16%|█████▍                             | 6644/42525 [12:15<1:04:40,  9.25it/s]

 16%|█████▍                             | 6648/42525 [12:15<1:01:05,  9.79it/s]

 16%|█████▍                             | 6651/42525 [12:16<1:08:42,  8.70it/s]

 16%|█████▍                             | 6653/42525 [12:16<1:09:20,  8.62it/s]

 16%|█████▍                             | 6655/42525 [12:16<1:06:40,  8.97it/s]

 16%|█████▍                             | 6657/42525 [12:16<1:12:48,  8.21it/s]

 16%|█████▍                             | 6659/42525 [12:17<1:10:34,  8.47it/s]

 16%|█████▍                             | 6662/42525 [12:17<1:10:55,  8.43it/s]

 16%|█████▍                             | 6664/42525 [12:17<1:06:27,  8.99it/s]

 16%|█████▍                             | 6667/42525 [12:18<1:06:34,  8.98it/s]

 16%|█████▍                             | 6669/42525 [12:18<1:04:50,  9.22it/s]

 16%|█████▍                             | 6673/42525 [12:18<1:03:48,  9.36it/s]

 16%|█████▍                             | 6674/42525 [12:18<1:03:09,  9.46it/s]

 16%|█████▍                             | 6678/42525 [12:19<1:02:53,  9.50it/s]

 16%|█████▍                             | 6680/42525 [12:19<1:03:41,  9.38it/s]

 16%|█████▍                             | 6682/42525 [12:19<1:10:06,  8.52it/s]

 16%|█████▌                             | 6685/42525 [12:19<1:07:39,  8.83it/s]

 16%|█████▌                             | 6687/42525 [12:20<1:13:19,  8.15it/s]

 16%|█████▌                             | 6690/42525 [12:20<1:05:54,  9.06it/s]

 16%|█████▌                             | 6691/42525 [12:20<1:10:14,  8.50it/s]

 16%|█████▌                             | 6694/42525 [12:21<1:10:58,  8.41it/s]

 16%|█████▌                             | 6696/42525 [12:21<1:08:12,  8.75it/s]

 16%|█████▌                             | 6698/42525 [12:21<1:13:32,  8.12it/s]

 16%|█████▌                             | 6700/42525 [12:21<1:07:09,  8.89it/s]

 16%|█████▌                             | 6703/42525 [12:22<1:06:38,  8.96it/s]

 16%|█████▌                             | 6706/42525 [12:22<1:02:38,  9.53it/s]

 16%|█████▌                             | 6708/42525 [12:22<1:08:27,  8.72it/s]

 16%|█████▌                             | 6710/42525 [12:22<1:07:03,  8.90it/s]

 16%|█████▌                             | 6712/42525 [12:23<1:12:37,  8.22it/s]

 16%|█████▌                             | 6715/42525 [12:23<1:05:26,  9.12it/s]

 16%|█████▌                             | 6718/42525 [12:23<1:04:54,  9.19it/s]

 16%|█████▌                             | 6721/42525 [12:24<1:01:48,  9.65it/s]

 16%|█████▌                             | 6724/42525 [12:24<1:06:11,  9.01it/s]

 16%|█████▌                             | 6725/42525 [12:24<1:07:59,  8.78it/s]

 16%|█████▌                             | 6727/42525 [12:24<1:05:15,  9.14it/s]

 16%|█████▌                             | 6731/42525 [12:25<1:02:46,  9.50it/s]

 16%|█████▌                             | 6733/42525 [12:25<1:06:04,  9.03it/s]

 16%|█████▌                             | 6736/42525 [12:25<1:13:32,  8.11it/s]

 16%|█████▌                             | 6738/42525 [12:26<1:15:19,  7.92it/s]

 16%|█████▌                             | 6742/42525 [12:26<1:07:51,  8.79it/s]

 16%|█████▌                             | 6746/42525 [12:26<1:02:22,  9.56it/s]

 16%|█████▌                             | 6748/42525 [12:27<1:02:20,  9.56it/s]

 16%|█████▌                             | 6750/42525 [12:27<1:03:55,  9.33it/s]

 16%|█████▌                             | 6752/42525 [12:27<1:04:57,  9.18it/s]

 16%|█████▌                             | 6755/42525 [12:27<1:05:12,  9.14it/s]

 16%|█████▌                             | 6756/42525 [12:28<1:10:34,  8.45it/s]

 16%|█████▌                             | 6759/42525 [12:28<1:06:55,  8.91it/s]

 16%|█████▌                             | 6762/42525 [12:28<1:02:10,  9.59it/s]

 16%|█████▌                             | 6763/42525 [12:28<1:06:24,  8.97it/s]

 16%|█████▌                             | 6766/42525 [12:29<1:04:26,  9.25it/s]

 16%|█████▌                             | 6769/42525 [12:29<1:04:30,  9.24it/s]

 16%|█████▉                               | 6773/42525 [12:29<59:55,  9.94it/s]

 16%|█████▌                             | 6776/42525 [12:30<1:01:36,  9.67it/s]

 16%|█████▌                             | 6777/42525 [12:30<1:07:09,  8.87it/s]

 16%|█████▌                             | 6779/42525 [12:30<1:08:19,  8.72it/s]

 16%|█████▌                             | 6782/42525 [12:30<1:08:57,  8.64it/s]

 16%|█████▌                             | 6785/42525 [12:31<1:03:33,  9.37it/s]

 16%|█████▌                             | 6786/42525 [12:31<1:07:01,  8.89it/s]

 16%|█████▌                             | 6790/42525 [12:31<1:02:22,  9.55it/s]

 16%|█████▉                               | 6794/42525 [12:32<59:58,  9.93it/s]

 16%|█████▌                             | 6797/42525 [12:32<1:02:36,  9.51it/s]

 16%|█████▌                             | 6801/42525 [12:32<1:00:49,  9.79it/s]

 16%|█████▌                             | 6804/42525 [12:33<1:01:52,  9.62it/s]

 16%|█████▌                             | 6806/42525 [12:33<1:00:12,  9.89it/s]

 16%|█████▌                             | 6810/42525 [12:33<1:00:52,  9.78it/s]

 16%|█████▌                             | 6812/42525 [12:33<1:02:03,  9.59it/s]

 16%|█████▉                               | 6814/42525 [12:34<59:52,  9.94it/s]

 16%|█████▌                             | 6818/42525 [12:34<1:01:41,  9.65it/s]

 16%|█████▌                             | 6820/42525 [12:34<1:05:14,  9.12it/s]

 16%|█████▌                             | 6823/42525 [12:35<1:08:36,  8.67it/s]

 16%|█████▌                             | 6825/42525 [12:35<1:05:41,  9.06it/s]

 16%|█████▌                             | 6828/42525 [12:35<1:11:56,  8.27it/s]

 16%|█████▌                             | 6831/42525 [12:36<1:15:39,  7.86it/s]

 16%|█████▋                             | 6835/42525 [12:36<1:05:28,  9.08it/s]

 16%|█████▋                             | 6838/42525 [12:36<1:05:27,  9.09it/s]

 16%|█████▋                             | 6841/42525 [12:37<1:02:51,  9.46it/s]

 16%|█████▋                             | 6844/42525 [12:37<1:02:15,  9.55it/s]

 16%|█████▋                             | 6846/42525 [12:37<1:08:15,  8.71it/s]

 16%|█████▋                             | 6848/42525 [12:38<1:12:46,  8.17it/s]

 16%|█████▋                             | 6851/42525 [12:38<1:04:59,  9.15it/s]

 16%|█████▋                             | 6854/42525 [12:38<1:03:42,  9.33it/s]

 16%|█████▋                             | 6857/42525 [12:38<1:01:07,  9.72it/s]

 16%|█████▋                             | 6859/42525 [12:39<1:11:07,  8.36it/s]

 16%|█████▋                             | 6861/42525 [12:39<1:13:43,  8.06it/s]

 16%|█████▋                             | 6864/42525 [12:39<1:04:42,  9.19it/s]

 16%|█████▋                             | 6866/42525 [12:39<1:05:03,  9.13it/s]

 16%|█████▋                             | 6868/42525 [12:40<1:06:08,  8.98it/s]

 16%|█████▋                             | 6871/42525 [12:40<1:02:41,  9.48it/s]

 16%|█████▋                             | 6874/42525 [12:40<1:00:55,  9.75it/s]

 16%|█████▉                               | 6878/42525 [12:41<59:58,  9.91it/s]

 16%|█████▉                               | 6880/42525 [12:41<58:58, 10.07it/s]

 16%|█████▋                             | 6883/42525 [12:41<1:04:43,  9.18it/s]

 16%|█████▋                             | 6886/42525 [12:42<1:08:06,  8.72it/s]

 16%|█████▋                             | 6888/42525 [12:42<1:09:30,  8.55it/s]

 16%|█████▋                             | 6890/42525 [12:42<1:14:24,  7.98it/s]

 16%|█████▋                             | 6892/42525 [12:42<1:15:28,  7.87it/s]

 16%|█████▋                             | 6895/42525 [12:43<1:10:02,  8.48it/s]

 16%|█████▋                             | 6896/42525 [12:43<1:14:32,  7.97it/s]

 16%|█████▋                             | 6899/42525 [12:43<1:11:22,  8.32it/s]

 16%|█████▋                             | 6903/42525 [12:44<1:03:59,  9.28it/s]

 16%|█████▋                             | 6905/42525 [12:44<1:08:55,  8.61it/s]

 16%|█████▋                             | 6906/42525 [12:44<1:13:25,  8.08it/s]

 16%|█████▋                             | 6909/42525 [12:44<1:12:36,  8.18it/s]

 16%|█████▋                             | 6913/42525 [12:45<1:03:11,  9.39it/s]

 16%|█████▋                             | 6916/42525 [12:45<1:05:31,  9.06it/s]

 16%|█████▋                             | 6920/42525 [12:45<1:01:09,  9.70it/s]

 16%|█████▋                             | 6923/42525 [12:46<1:02:40,  9.47it/s]

 16%|█████▋                             | 6925/42525 [12:46<1:07:58,  8.73it/s]

 16%|█████▋                             | 6927/42525 [12:46<1:06:33,  8.91it/s]

 16%|█████▋                             | 6930/42525 [12:47<1:02:05,  9.55it/s]

 16%|█████▋                             | 6931/42525 [12:47<1:08:19,  8.68it/s]

 16%|█████▋                             | 6934/42525 [12:47<1:07:33,  8.78it/s]

 16%|█████▋                             | 6936/42525 [12:47<1:12:12,  8.21it/s]

 16%|█████▋                             | 6939/42525 [12:48<1:07:36,  8.77it/s]

 16%|█████▋                             | 6940/42525 [12:48<1:09:56,  8.48it/s]

 16%|█████▋                             | 6944/42525 [12:48<1:06:06,  8.97it/s]

 16%|█████▋                             | 6947/42525 [12:49<1:04:04,  9.25it/s]

 16%|█████▋                             | 6948/42525 [12:49<1:08:57,  8.60it/s]

 16%|█████▋                             | 6951/42525 [12:49<1:08:37,  8.64it/s]

 16%|█████▋                             | 6953/42525 [12:49<1:12:14,  8.21it/s]

 16%|█████▋                             | 6957/42525 [12:50<1:04:58,  9.12it/s]

 16%|█████▋                             | 6959/42525 [12:50<1:02:09,  9.54it/s]

 16%|█████▋                             | 6963/42525 [12:50<1:00:53,  9.73it/s]

 16%|█████▋                             | 6964/42525 [12:50<1:04:16,  9.22it/s]

 16%|█████▋                             | 6967/42525 [12:51<1:03:06,  9.39it/s]

 16%|█████▋                             | 6971/42525 [12:51<1:03:08,  9.39it/s]

 16%|█████▋                             | 6972/42525 [12:51<1:08:02,  8.71it/s]

 16%|█████▋                             | 6975/42525 [12:52<1:06:03,  8.97it/s]

 16%|█████▋                             | 6979/42525 [12:52<1:02:22,  9.50it/s]

 16%|█████▋                             | 6981/42525 [12:52<1:05:32,  9.04it/s]

 16%|█████▋                             | 6983/42525 [12:53<1:16:09,  7.78it/s]

 16%|█████▋                             | 6985/42525 [12:53<1:22:05,  7.22it/s]

 16%|█████▊                             | 6988/42525 [12:53<1:10:14,  8.43it/s]

 16%|█████▊                             | 6990/42525 [12:53<1:05:17,  9.07it/s]

 16%|█████▊                             | 6993/42525 [12:54<1:03:10,  9.37it/s]

 16%|█████▊                             | 6996/42525 [12:54<1:05:37,  9.02it/s]

 16%|█████▊                             | 6999/42525 [12:54<1:02:30,  9.47it/s]

 16%|█████▊                             | 7001/42525 [12:55<1:01:47,  9.58it/s]

 16%|█████▊                             | 7003/42525 [12:55<1:02:15,  9.51it/s]

 16%|█████▊                             | 7006/42525 [12:55<1:03:14,  9.36it/s]

 16%|█████▊                             | 7008/42525 [12:55<1:04:59,  9.11it/s]

 16%|█████▊                             | 7010/42525 [12:56<1:07:26,  8.78it/s]

 16%|█████▊                             | 7012/42525 [12:56<1:13:43,  8.03it/s]

 16%|█████▊                             | 7014/42525 [12:56<1:09:01,  8.57it/s]

 17%|█████▊                             | 7017/42525 [12:56<1:02:46,  9.43it/s]

 17%|█████▊                             | 7018/42525 [12:57<1:03:53,  9.26it/s]

 17%|█████▊                             | 7021/42525 [12:57<1:03:19,  9.35it/s]

 17%|█████▊                             | 7023/42525 [12:57<1:11:42,  8.25it/s]

 17%|█████▊                             | 7026/42525 [12:57<1:05:07,  9.08it/s]

 17%|█████▊                             | 7027/42525 [12:58<1:10:31,  8.39it/s]

 17%|█████▊                             | 7030/42525 [12:58<1:11:37,  8.26it/s]

 17%|█████▊                             | 7032/42525 [12:58<1:13:53,  8.01it/s]

 17%|█████▊                             | 7034/42525 [12:58<1:14:40,  7.92it/s]

 17%|█████▊                             | 7036/42525 [12:59<1:08:57,  8.58it/s]

 17%|█████▊                             | 7037/42525 [12:59<1:08:59,  8.57it/s]

 17%|█████▊                             | 7039/42525 [12:59<1:10:37,  8.38it/s]

 17%|█████▊                             | 7043/42525 [12:59<1:03:43,  9.28it/s]

 17%|██████▏                              | 7047/42525 [13:00<59:53,  9.87it/s]

 17%|█████▊                             | 7050/42525 [13:00<1:06:41,  8.87it/s]

 17%|█████▊                             | 7053/42525 [13:01<1:08:37,  8.62it/s]

 17%|█████▊                             | 7056/42525 [13:01<1:06:51,  8.84it/s]

 17%|█████▊                             | 7058/42525 [13:01<1:07:18,  8.78it/s]

 17%|█████▊                             | 7060/42525 [13:01<1:03:07,  9.36it/s]

 17%|█████▊                             | 7062/42525 [13:02<1:06:34,  8.88it/s]

 17%|█████▊                             | 7066/42525 [13:02<1:04:01,  9.23it/s]

 17%|█████▊                             | 7067/42525 [13:02<1:08:11,  8.67it/s]

 17%|█████▊                             | 7071/42525 [13:03<1:02:24,  9.47it/s]

 17%|██████▏                              | 7075/42525 [13:03<59:26,  9.94it/s]

 17%|██████▏                              | 7077/42525 [13:03<58:35, 10.08it/s]

 17%|██████▏                              | 7081/42525 [13:04<59:41,  9.90it/s]

 17%|██████▏                              | 7083/42525 [13:04<59:01, 10.01it/s]

 17%|█████▊                             | 7086/42525 [13:04<1:01:50,  9.55it/s]

 17%|█████▊                             | 7087/42525 [13:04<1:01:37,  9.59it/s]

 17%|█████▊                             | 7089/42525 [13:04<1:01:33,  9.59it/s]

 17%|█████▊                             | 7092/42525 [13:05<1:01:00,  9.68it/s]

 17%|█████▊                             | 7093/42525 [13:05<1:02:22,  9.47it/s]

 17%|█████▊                             | 7097/42525 [13:05<1:00:00,  9.84it/s]

 17%|█████▊                             | 7099/42525 [13:05<1:03:57,  9.23it/s]

 17%|█████▊                             | 7100/42525 [13:06<1:03:23,  9.31it/s]

 17%|█████▊                             | 7102/42525 [13:06<1:07:11,  8.79it/s]

 17%|█████▊                             | 7105/42525 [13:06<1:13:06,  8.08it/s]

 17%|█████▊                             | 7108/42525 [13:06<1:11:37,  8.24it/s]

 17%|█████▊                             | 7109/42525 [13:07<1:15:09,  7.85it/s]

 17%|█████▊                             | 7113/42525 [13:07<1:07:11,  8.78it/s]

 17%|█████▊                             | 7115/42525 [13:07<1:06:34,  8.86it/s]

 17%|█████▊                             | 7118/42525 [13:08<1:07:14,  8.78it/s]

 17%|█████▊                             | 7120/42525 [13:08<1:04:41,  9.12it/s]

 17%|█████▊                             | 7123/42525 [13:08<1:04:36,  9.13it/s]

 17%|█████▊                             | 7125/42525 [13:08<1:08:01,  8.67it/s]

 17%|█████▊                             | 7127/42525 [13:09<1:03:20,  9.31it/s]

 17%|█████▊                             | 7129/42525 [13:09<1:05:07,  9.06it/s]

 17%|█████▊                             | 7132/42525 [13:09<1:06:21,  8.89it/s]

 17%|█████▊                             | 7134/42525 [13:09<1:05:30,  9.00it/s]

 17%|█████▊                             | 7137/42525 [13:10<1:02:12,  9.48it/s]

 17%|█████▉                             | 7141/42525 [13:10<1:02:35,  9.42it/s]

 17%|█████▉                             | 7144/42525 [13:10<1:05:13,  9.04it/s]

 17%|█████▉                             | 7147/42525 [13:11<1:01:29,  9.59it/s]

 17%|█████▉                             | 7149/42525 [13:11<1:10:59,  8.31it/s]

 17%|█████▉                             | 7152/42525 [13:11<1:08:16,  8.64it/s]

 17%|█████▉                             | 7155/42525 [13:12<1:03:47,  9.24it/s]

 17%|█████▉                             | 7158/42525 [13:12<1:03:23,  9.30it/s]

 17%|█████▉                             | 7160/42525 [13:12<1:08:56,  8.55it/s]

 17%|█████▉                             | 7163/42525 [13:13<1:04:11,  9.18it/s]

 17%|█████▉                             | 7165/42525 [13:13<1:08:15,  8.63it/s]

 17%|█████▉                             | 7168/42525 [13:13<1:06:54,  8.81it/s]

 17%|█████▉                             | 7172/42525 [13:14<1:04:56,  9.07it/s]

 17%|█████▉                             | 7175/42525 [13:14<1:04:04,  9.20it/s]

 17%|█████▉                             | 7177/42525 [13:14<1:07:01,  8.79it/s]

 17%|█████▉                             | 7180/42525 [13:15<1:06:29,  8.86it/s]

 17%|█████▉                             | 7184/42525 [13:15<1:01:14,  9.62it/s]

 17%|█████▉                             | 7188/42525 [13:15<1:01:06,  9.64it/s]

 17%|█████▉                             | 7190/42525 [13:16<1:06:40,  8.83it/s]

 17%|█████▉                             | 7192/42525 [13:16<1:08:41,  8.57it/s]

 17%|█████▉                             | 7194/42525 [13:16<1:05:52,  8.94it/s]

 17%|█████▉                             | 7197/42525 [13:16<1:07:07,  8.77it/s]

 17%|█████▉                             | 7199/42525 [13:17<1:03:45,  9.24it/s]

 17%|█████▉                             | 7203/42525 [13:17<1:00:30,  9.73it/s]

 17%|█████▉                             | 7205/42525 [13:17<1:03:44,  9.23it/s]

 17%|█████▉                             | 7206/42525 [13:17<1:09:04,  8.52it/s]

 17%|█████▉                             | 7209/42525 [13:18<1:14:37,  7.89it/s]

 17%|█████▉                             | 7211/42525 [13:18<1:19:45,  7.38it/s]

 17%|█████▉                             | 7213/42525 [13:18<1:15:53,  7.75it/s]

 17%|█████▉                             | 7215/42525 [13:19<1:08:03,  8.65it/s]

 17%|█████▉                             | 7217/42525 [13:19<1:12:13,  8.15it/s]

 17%|█████▉                             | 7219/42525 [13:19<1:10:22,  8.36it/s]

 17%|█████▉                             | 7220/42525 [13:19<1:09:58,  8.41it/s]

 17%|█████▉                             | 7223/42525 [13:19<1:04:20,  9.15it/s]

 17%|█████▉                             | 7225/42525 [13:20<1:04:55,  9.06it/s]

 17%|█████▉                             | 7227/42525 [13:20<1:13:40,  7.99it/s]

 17%|█████▉                             | 7229/42525 [13:20<1:14:55,  7.85it/s]

 17%|█████▉                             | 7232/42525 [13:21<1:09:14,  8.50it/s]

 17%|█████▉                             | 7234/42525 [13:21<1:07:10,  8.76it/s]

 17%|█████▉                             | 7238/42525 [13:21<1:00:58,  9.65it/s]

 17%|█████▉                             | 7240/42525 [13:21<1:03:01,  9.33it/s]

 17%|█████▉                             | 7243/42525 [13:22<1:01:49,  9.51it/s]

 17%|█████▉                             | 7245/42525 [13:22<1:04:03,  9.18it/s]

 17%|█████▉                             | 7247/42525 [13:22<1:07:44,  8.68it/s]

 17%|█████▉                             | 7249/42525 [13:22<1:04:13,  9.15it/s]

 17%|█████▉                             | 7252/42525 [13:23<1:05:28,  8.98it/s]

 17%|█████▉                             | 7253/42525 [13:23<1:05:11,  9.02it/s]

 17%|█████▉                             | 7256/42525 [13:23<1:12:47,  8.08it/s]

 17%|█████▉                             | 7259/42525 [13:24<1:11:22,  8.23it/s]

 17%|█████▉                             | 7260/42525 [13:24<1:15:09,  7.82it/s]

 17%|█████▉                             | 7263/42525 [13:24<1:13:08,  8.03it/s]

 17%|█████▉                             | 7264/42525 [13:24<1:16:31,  7.68it/s]

 17%|█████▉                             | 7267/42525 [13:25<1:09:17,  8.48it/s]

 17%|█████▉                             | 7270/42525 [13:25<1:06:32,  8.83it/s]

 17%|█████▉                             | 7273/42525 [13:25<1:01:59,  9.48it/s]

 17%|█████▉                             | 7276/42525 [13:25<1:00:39,  9.69it/s]

 17%|██████▎                              | 7278/42525 [13:26<59:18,  9.91it/s]

 17%|█████▉                             | 7281/42525 [13:26<1:06:22,  8.85it/s]

 17%|█████▉                             | 7284/42525 [13:26<1:02:26,  9.41it/s]

 17%|█████▉                             | 7285/42525 [13:26<1:07:59,  8.64it/s]

 17%|█████▉                             | 7287/42525 [13:27<1:09:38,  8.43it/s]

 17%|██████                             | 7290/42525 [13:27<1:08:52,  8.53it/s]

 17%|██████                             | 7292/42525 [13:27<1:05:23,  8.98it/s]

 17%|██████                             | 7294/42525 [13:27<1:03:35,  9.23it/s]

 17%|██████                             | 7295/42525 [13:28<1:03:17,  9.28it/s]

 17%|██████                             | 7297/42525 [13:28<1:05:23,  8.98it/s]

 17%|██████                             | 7300/42525 [13:28<1:04:09,  9.15it/s]

 17%|██████                             | 7303/42525 [13:28<1:04:15,  9.13it/s]

 17%|██████                             | 7306/42525 [13:29<1:03:24,  9.26it/s]

 17%|██████                             | 7309/42525 [13:29<1:01:00,  9.62it/s]

 17%|██████                             | 7311/42525 [13:29<1:07:49,  8.65it/s]

 17%|██████                             | 7314/42525 [13:30<1:04:35,  9.09it/s]

 17%|██████                             | 7315/42525 [13:30<1:03:19,  9.27it/s]

 17%|██████                             | 7318/42525 [13:30<1:04:26,  9.11it/s]

 17%|██████                             | 7321/42525 [13:30<1:07:49,  8.65it/s]

 17%|██████                             | 7324/42525 [13:31<1:06:49,  8.78it/s]

 17%|██████                             | 7327/42525 [13:31<1:04:35,  9.08it/s]

 17%|██████                             | 7330/42525 [13:32<1:11:54,  8.16it/s]

 17%|██████                             | 7333/42525 [13:32<1:08:13,  8.60it/s]

 17%|██████                             | 7337/42525 [13:32<1:01:45,  9.50it/s]

 17%|██████▍                              | 7340/42525 [13:33<59:45,  9.81it/s]

 17%|██████                             | 7343/42525 [13:33<1:05:52,  8.90it/s]

 17%|██████                             | 7345/42525 [13:33<1:03:39,  9.21it/s]

 17%|██████                             | 7347/42525 [13:33<1:00:56,  9.62it/s]

 17%|██████                             | 7350/42525 [13:34<1:08:44,  8.53it/s]

 17%|██████                             | 7353/42525 [13:34<1:05:12,  8.99it/s]

 17%|██████                             | 7355/42525 [13:34<1:14:17,  7.89it/s]

 17%|██████                             | 7358/42525 [13:35<1:06:56,  8.76it/s]

 17%|██████                             | 7361/42525 [13:35<1:04:05,  9.14it/s]

 17%|██████                             | 7363/42525 [13:35<1:02:27,  9.38it/s]

 17%|██████                             | 7365/42525 [13:35<1:05:47,  8.91it/s]

 17%|██████                             | 7369/42525 [13:36<1:01:50,  9.47it/s]

 17%|██████                             | 7372/42525 [13:36<1:00:41,  9.65it/s]

 17%|██████                             | 7373/42525 [13:36<1:06:20,  8.83it/s]

 17%|██████                             | 7375/42525 [13:37<1:05:25,  8.96it/s]

 17%|██████                             | 7378/42525 [13:37<1:06:36,  8.79it/s]

 17%|██████                             | 7381/42525 [13:37<1:03:05,  9.28it/s]

 17%|██████                             | 7383/42525 [13:37<1:06:08,  8.86it/s]

 17%|██████                             | 7386/42525 [13:38<1:05:10,  8.99it/s]

 17%|██████                             | 7388/42525 [13:38<1:03:30,  9.22it/s]

 17%|██████                             | 7390/42525 [13:38<1:07:37,  8.66it/s]

 17%|██████                             | 7393/42525 [13:39<1:05:41,  8.91it/s]

 17%|██████                             | 7395/42525 [13:39<1:02:25,  9.38it/s]

 17%|██████                             | 7399/42525 [13:39<1:01:52,  9.46it/s]

 17%|██████                             | 7401/42525 [13:40<1:11:30,  8.19it/s]

 17%|██████                             | 7403/42525 [13:40<1:13:54,  7.92it/s]

 17%|██████                             | 7406/42525 [13:40<1:11:38,  8.17it/s]

 17%|██████                             | 7410/42525 [13:40<1:02:16,  9.40it/s]

 17%|██████                             | 7412/42525 [13:41<1:02:53,  9.31it/s]

 17%|██████                             | 7414/42525 [13:41<1:02:47,  9.32it/s]

 17%|██████                             | 7417/42525 [13:41<1:02:17,  9.39it/s]

 17%|██████                             | 7419/42525 [13:41<1:00:37,  9.65it/s]

 17%|██████                             | 7422/42525 [13:42<1:07:04,  8.72it/s]

 17%|██████                             | 7425/42525 [13:42<1:02:28,  9.36it/s]

 17%|██████                             | 7427/42525 [13:42<1:12:54,  8.02it/s]

 17%|██████                             | 7430/42525 [13:43<1:09:28,  8.42it/s]

 17%|██████                             | 7432/42525 [13:43<1:06:08,  8.84it/s]

 17%|██████                             | 7435/42525 [13:43<1:03:13,  9.25it/s]

 17%|██████                             | 7437/42525 [13:43<1:02:55,  9.29it/s]

 17%|██████                             | 7439/42525 [13:44<1:06:11,  8.84it/s]

 17%|██████                             | 7441/42525 [13:44<1:05:13,  8.96it/s]

 18%|██████▏                            | 7444/42525 [13:44<1:12:42,  8.04it/s]

 18%|██████▏                            | 7447/42525 [13:45<1:04:43,  9.03it/s]

 18%|██████▏                            | 7449/42525 [13:45<1:11:50,  8.14it/s]

 18%|██████▏                            | 7453/42525 [13:45<1:03:53,  9.15it/s]

 18%|██████▏                            | 7456/42525 [13:46<1:01:47,  9.46it/s]

 18%|██████▏                            | 7459/42525 [13:46<1:02:55,  9.29it/s]

 18%|██████▏                            | 7462/42525 [13:46<1:00:15,  9.70it/s]

 18%|██████▏                            | 7464/42525 [13:46<1:04:17,  9.09it/s]

 18%|██████▏                            | 7467/42525 [13:47<1:11:47,  8.14it/s]

 18%|██████▏                            | 7469/42525 [13:47<1:08:30,  8.53it/s]

 18%|██████▏                            | 7471/42525 [13:47<1:05:12,  8.96it/s]

 18%|██████▏                            | 7473/42525 [13:48<1:11:30,  8.17it/s]

 18%|██████▏                            | 7475/42525 [13:48<1:09:02,  8.46it/s]

 18%|██████▏                            | 7477/42525 [13:48<1:15:01,  7.79it/s]

 18%|██████▏                            | 7479/42525 [13:48<1:08:57,  8.47it/s]

 18%|██████▏                            | 7483/42525 [13:49<1:01:00,  9.57it/s]

 18%|██████▏                            | 7485/42525 [13:49<1:05:38,  8.90it/s]

 18%|██████▌                              | 7489/42525 [13:49<59:58,  9.74it/s]

 18%|██████▌                              | 7491/42525 [13:50<59:36,  9.80it/s]

 18%|██████▏                            | 7494/42525 [13:50<1:04:42,  9.02it/s]

 18%|██████▏                            | 7496/42525 [13:50<1:03:43,  9.16it/s]

 18%|██████▏                            | 7498/42525 [13:50<1:00:49,  9.60it/s]

 18%|██████▏                            | 7502/42525 [13:51<1:02:04,  9.40it/s]

 18%|██████▏                            | 7506/42525 [13:51<1:02:25,  9.35it/s]

 18%|██████▏                            | 7509/42525 [13:52<1:05:48,  8.87it/s]

 18%|██████▏                            | 7511/42525 [13:52<1:05:27,  8.92it/s]

 18%|██████▏                            | 7514/42525 [13:52<1:05:20,  8.93it/s]

 18%|██████▏                            | 7516/42525 [13:52<1:06:14,  8.81it/s]

 18%|██████▏                            | 7519/42525 [13:53<1:06:11,  8.81it/s]

 18%|██████▏                            | 7522/42525 [13:53<1:02:00,  9.41it/s]

 18%|██████▏                            | 7524/42525 [13:53<1:05:58,  8.84it/s]

 18%|██████▏                            | 7526/42525 [13:53<1:08:07,  8.56it/s]

 18%|██████▏                            | 7528/42525 [13:54<1:05:31,  8.90it/s]

 18%|██████▏                            | 7532/42525 [13:54<1:02:12,  9.37it/s]

 18%|██████▏                            | 7533/42525 [13:54<1:01:50,  9.43it/s]

 18%|██████▏                            | 7536/42525 [13:54<1:01:28,  9.49it/s]

 18%|██████▌                              | 7539/42525 [13:55<59:34,  9.79it/s]

 18%|██████▏                            | 7542/42525 [13:55<1:00:00,  9.72it/s]

 18%|██████▏                            | 7545/42525 [13:55<1:01:07,  9.54it/s]

 18%|██████▏                            | 7547/42525 [13:56<1:07:50,  8.59it/s]

 18%|██████▏                            | 7550/42525 [13:56<1:07:28,  8.64it/s]

 18%|██████▏                            | 7552/42525 [13:56<1:06:16,  8.80it/s]

 18%|██████▏                            | 7553/42525 [13:56<1:04:09,  9.09it/s]

 18%|██████▏                            | 7557/42525 [13:57<1:01:14,  9.52it/s]

 18%|██████▌                              | 7559/42525 [13:57<59:36,  9.78it/s]

 18%|██████▏                            | 7562/42525 [13:57<1:01:29,  9.48it/s]

 18%|██████▏                            | 7563/42525 [13:57<1:00:51,  9.58it/s]

 18%|██████▌                              | 7567/42525 [13:58<59:36,  9.77it/s]

 18%|██████▌                              | 7571/42525 [13:58<58:08, 10.02it/s]

 18%|██████▏                            | 7574/42525 [13:58<1:01:23,  9.49it/s]

 18%|██████▏                            | 7575/42525 [13:59<1:06:21,  8.78it/s]

 18%|██████▏                            | 7578/42525 [13:59<1:07:05,  8.68it/s]

 18%|██████▏                            | 7581/42525 [13:59<1:08:28,  8.51it/s]

 18%|██████▏                            | 7584/42525 [14:00<1:04:25,  9.04it/s]

 18%|██████▏                            | 7585/42525 [14:00<1:04:48,  8.98it/s]

 18%|██████▏                            | 7588/42525 [14:00<1:01:57,  9.40it/s]

 18%|██████▏                            | 7590/42525 [14:00<1:05:51,  8.84it/s]

 18%|██████▏                            | 7593/42525 [14:01<1:08:22,  8.51it/s]

 18%|██████▎                            | 7594/42525 [14:01<1:12:46,  8.00it/s]

 18%|██████▎                            | 7597/42525 [14:01<1:15:09,  7.75it/s]

 18%|██████▎                            | 7599/42525 [14:01<1:16:28,  7.61it/s]

 18%|██████▎                            | 7601/42525 [14:02<1:18:55,  7.37it/s]

 18%|██████▎                            | 7603/42525 [14:02<1:11:36,  8.13it/s]

 18%|██████▎                            | 7606/42525 [14:02<1:10:45,  8.22it/s]

 18%|██████▎                            | 7609/42525 [14:03<1:07:29,  8.62it/s]

 18%|██████▎                            | 7610/42525 [14:03<1:06:40,  8.73it/s]

 18%|██████▎                            | 7613/42525 [14:03<1:07:29,  8.62it/s]

 18%|██████▎                            | 7615/42525 [14:03<1:03:26,  9.17it/s]

 18%|██████▎                            | 7618/42525 [14:04<1:05:27,  8.89it/s]

 18%|██████▎                            | 7621/42525 [14:04<1:01:22,  9.48it/s]

 18%|██████▎                            | 7624/42525 [14:04<1:03:05,  9.22it/s]

 18%|██████▎                            | 7626/42525 [14:05<1:03:06,  9.22it/s]

 18%|██████▎                            | 7628/42525 [14:05<1:09:31,  8.37it/s]

 18%|██████▎                            | 7630/42525 [14:05<1:04:12,  9.06it/s]

 18%|██████▎                            | 7633/42525 [14:05<1:07:52,  8.57it/s]

 18%|██████▎                            | 7634/42525 [14:05<1:12:09,  8.06it/s]

 18%|██████▎                            | 7636/42525 [14:06<1:11:55,  8.08it/s]

 18%|██████▎                            | 7639/42525 [14:06<1:13:39,  7.89it/s]

 18%|██████▎                            | 7642/42525 [14:06<1:06:40,  8.72it/s]

 18%|██████▎                            | 7645/42525 [14:07<1:04:41,  8.99it/s]

 18%|██████▎                            | 7648/42525 [14:07<1:04:03,  9.07it/s]

 18%|██████▎                            | 7651/42525 [14:07<1:06:43,  8.71it/s]

 18%|██████▎                            | 7653/42525 [14:08<1:02:38,  9.28it/s]

 18%|██████▋                              | 7657/42525 [14:08<59:48,  9.72it/s]

 18%|██████▎                            | 7659/42525 [14:08<1:02:03,  9.36it/s]

 18%|██████▎                            | 7661/42525 [14:08<1:01:45,  9.41it/s]

 18%|██████▋                              | 7665/42525 [14:09<59:22,  9.79it/s]

 18%|██████▋                              | 7668/42525 [14:09<59:14,  9.81it/s]

 18%|██████▋                              | 7672/42525 [14:10<57:18, 10.14it/s]

 18%|██████▋                              | 7674/42525 [14:10<57:33, 10.09it/s]

 18%|██████▎                            | 7678/42525 [14:10<1:00:20,  9.62it/s]

 18%|██████▎                            | 7681/42525 [14:11<1:02:30,  9.29it/s]

 18%|██████▎                            | 7683/42525 [14:11<1:02:38,  9.27it/s]

 18%|██████▎                            | 7684/42525 [14:11<1:02:32,  9.28it/s]

 18%|██████▋                              | 7688/42525 [14:11<59:39,  9.73it/s]

 18%|██████▎                            | 7692/42525 [14:12<1:00:47,  9.55it/s]

 18%|██████▎                            | 7695/42525 [14:12<1:04:38,  8.98it/s]

 18%|██████▎                            | 7697/42525 [14:12<1:09:31,  8.35it/s]

 18%|██████▎                            | 7699/42525 [14:13<1:11:59,  8.06it/s]

 18%|██████▎                            | 7702/42525 [14:13<1:03:52,  9.09it/s]

 18%|██████▎                            | 7705/42525 [14:13<1:00:56,  9.52it/s]

 18%|██████▎                            | 7708/42525 [14:14<1:02:29,  9.29it/s]

 18%|██████▎                            | 7712/42525 [14:14<1:02:07,  9.34it/s]

 18%|██████▎                            | 7715/42525 [14:14<1:03:48,  9.09it/s]

 18%|██████▋                              | 7719/42525 [14:15<59:18,  9.78it/s]

 18%|██████▎                            | 7721/42525 [14:15<1:09:13,  8.38it/s]

 18%|██████▎                            | 7723/42525 [14:15<1:11:30,  8.11it/s]

 18%|██████▎                            | 7727/42525 [14:16<1:01:25,  9.44it/s]

 18%|██████▎                            | 7729/42525 [14:16<1:08:16,  8.49it/s]

 18%|██████▎                            | 7731/42525 [14:16<1:11:18,  8.13it/s]

 18%|██████▎                            | 7735/42525 [14:17<1:01:10,  9.48it/s]

 18%|██████▎                            | 7737/42525 [14:17<1:00:45,  9.54it/s]

 18%|██████▋                              | 7740/42525 [14:17<59:31,  9.74it/s]

 18%|██████▎                            | 7742/42525 [14:17<1:03:54,  9.07it/s]

 18%|██████▎                            | 7745/42525 [14:18<1:08:09,  8.50it/s]

 18%|██████▍                            | 7748/42525 [14:18<1:07:21,  8.61it/s]

 18%|██████▍                            | 7750/42525 [14:18<1:09:01,  8.40it/s]

 18%|██████▍                            | 7753/42525 [14:19<1:02:37,  9.25it/s]

 18%|██████▍                            | 7754/42525 [14:19<1:03:11,  9.17it/s]

 18%|██████▍                            | 7757/42525 [14:19<1:08:40,  8.44it/s]

 18%|██████▍                            | 7759/42525 [14:19<1:07:05,  8.64it/s]

 18%|██████▍                            | 7762/42525 [14:20<1:06:27,  8.72it/s]

 18%|██████▊                              | 7766/42525 [14:20<59:35,  9.72it/s]

 18%|██████▍                            | 7768/42525 [14:20<1:06:08,  8.76it/s]

 18%|██████▍                            | 7771/42525 [14:21<1:03:49,  9.07it/s]

 18%|██████▍                            | 7773/42525 [14:21<1:06:28,  8.71it/s]

 18%|██████▍                            | 7777/42525 [14:21<1:01:46,  9.38it/s]

 18%|██████▊                              | 7780/42525 [14:22<59:01,  9.81it/s]

 18%|██████▊                              | 7783/42525 [14:22<58:00,  9.98it/s]

 18%|██████▊                              | 7785/42525 [14:22<57:09, 10.13it/s]

 18%|██████▍                            | 7788/42525 [14:22<1:06:52,  8.66it/s]

 18%|██████▍                            | 7790/42525 [14:23<1:02:39,  9.24it/s]

 18%|██████▍                            | 7792/42525 [14:23<1:04:26,  8.98it/s]

 18%|██████▍                            | 7796/42525 [14:23<1:02:51,  9.21it/s]

 18%|██████▍                            | 7798/42525 [14:24<1:08:06,  8.50it/s]

 18%|██████▍                            | 7802/42525 [14:24<1:02:24,  9.27it/s]

 18%|██████▍                            | 7804/42525 [14:24<1:03:00,  9.18it/s]

 18%|██████▍                            | 7806/42525 [14:24<1:09:29,  8.33it/s]

 18%|██████▍                            | 7808/42525 [14:25<1:08:26,  8.45it/s]

 18%|██████▍                            | 7811/42525 [14:25<1:02:07,  9.31it/s]

 18%|██████▊                              | 7815/42525 [14:25<57:58,  9.98it/s]

 18%|██████▍                            | 7818/42525 [14:26<1:00:34,  9.55it/s]

 18%|██████▍                            | 7821/42525 [14:26<1:00:16,  9.60it/s]

 18%|██████▍                            | 7823/42525 [14:26<1:05:13,  8.87it/s]

 18%|██████▍                            | 7826/42525 [14:27<1:01:04,  9.47it/s]

 18%|██████▊                              | 7830/42525 [14:27<59:47,  9.67it/s]

 18%|██████▊                              | 7833/42525 [14:27<58:31,  9.88it/s]

 18%|██████▍                            | 7834/42525 [14:27<1:04:10,  9.01it/s]

 18%|██████▍                            | 7837/42525 [14:28<1:07:20,  8.59it/s]

 18%|██████▍                            | 7839/42525 [14:28<1:04:08,  9.01it/s]

 18%|██████▍                            | 7842/42525 [14:28<1:04:11,  9.00it/s]

 18%|██████▍                            | 7845/42525 [14:29<1:00:33,  9.54it/s]

 18%|██████▍                            | 7849/42525 [14:29<1:01:25,  9.41it/s]

 18%|██████▊                              | 7851/42525 [14:29<59:17,  9.75it/s]

 18%|██████▍                            | 7855/42525 [14:30<1:00:34,  9.54it/s]

 18%|██████▊                              | 7857/42525 [14:30<59:10,  9.76it/s]

 18%|██████▍                            | 7859/42525 [14:30<1:01:23,  9.41it/s]

 18%|██████▊                              | 7863/42525 [14:30<59:51,  9.65it/s]

 18%|██████▍                            | 7865/42525 [14:31<1:00:05,  9.61it/s]

 19%|██████▍                            | 7868/42525 [14:31<1:03:54,  9.04it/s]

 19%|██████▍                            | 7870/42525 [14:31<1:06:44,  8.65it/s]

 19%|██████▍                            | 7874/42525 [14:32<1:03:57,  9.03it/s]

 19%|██████▍                            | 7876/42525 [14:32<1:01:19,  9.42it/s]

 19%|██████▍                            | 7880/42525 [14:32<1:01:39,  9.36it/s]

 19%|██████▍                            | 7883/42525 [14:33<1:05:32,  8.81it/s]

 19%|██████▍                            | 7884/42525 [14:33<1:05:35,  8.80it/s]

 19%|██████▍                            | 7886/42525 [14:33<1:03:22,  9.11it/s]

 19%|██████▊                              | 7890/42525 [14:33<59:47,  9.65it/s]

 19%|██████▊                              | 7892/42525 [14:34<58:17,  9.90it/s]

 19%|██████▍                            | 7895/42525 [14:34<1:06:36,  8.67it/s]

 19%|██████▌                            | 7898/42525 [14:34<1:07:17,  8.58it/s]

 19%|██████▌                            | 7900/42525 [14:35<1:12:43,  7.94it/s]

 19%|██████▌                            | 7903/42525 [14:35<1:06:40,  8.66it/s]

 19%|██████▌                            | 7905/42525 [14:35<1:08:54,  8.37it/s]

 19%|██████▌                            | 7908/42525 [14:36<1:07:53,  8.50it/s]

 19%|██████▌                            | 7911/42525 [14:36<1:01:19,  9.41it/s]

 19%|██████▉                              | 7915/42525 [14:36<57:49,  9.98it/s]

 19%|██████▌                            | 7918/42525 [14:37<1:02:40,  9.20it/s]

 19%|██████▌                            | 7920/42525 [14:37<1:09:32,  8.29it/s]

 19%|██████▌                            | 7922/42525 [14:37<1:08:05,  8.47it/s]

 19%|██████▌                            | 7924/42525 [14:37<1:11:18,  8.09it/s]

 19%|██████▌                            | 7927/42525 [14:38<1:04:08,  8.99it/s]

 19%|██████▌                            | 7929/42525 [14:38<1:04:15,  8.97it/s]

 19%|██████▌                            | 7931/42525 [14:38<1:08:09,  8.46it/s]

 19%|██████▌                            | 7933/42525 [14:38<1:03:48,  9.04it/s]

 19%|██████▌                            | 7934/42525 [14:38<1:04:26,  8.95it/s]

 19%|██████▌                            | 7937/42525 [14:39<1:05:19,  8.82it/s]

 19%|██████▌                            | 7939/42525 [14:39<1:06:51,  8.62it/s]

 19%|██████▌                            | 7942/42525 [14:39<1:08:40,  8.39it/s]

 19%|██████▌                            | 7944/42525 [14:40<1:03:21,  9.10it/s]

 19%|██████▌                            | 7948/42525 [14:40<1:00:08,  9.58it/s]

 19%|██████▌                            | 7950/42525 [14:40<1:05:03,  8.86it/s]

 19%|██████▌                            | 7953/42525 [14:41<1:01:10,  9.42it/s]

 19%|██████▌                            | 7955/42525 [14:41<1:01:08,  9.42it/s]

 19%|██████▌                            | 7956/42525 [14:41<1:07:31,  8.53it/s]

 19%|██████▌                            | 7959/42525 [14:41<1:10:29,  8.17it/s]

 19%|██████▌                            | 7961/42525 [14:42<1:11:36,  8.05it/s]

 19%|██████▌                            | 7963/42525 [14:42<1:04:37,  8.91it/s]

 19%|██████▌                            | 7965/42525 [14:42<1:03:30,  9.07it/s]

 19%|██████▌                            | 7969/42525 [14:42<1:00:36,  9.50it/s]

 19%|██████▌                            | 7972/42525 [14:43<1:02:47,  9.17it/s]

 19%|██████▌                            | 7974/42525 [14:43<1:05:39,  8.77it/s]

 19%|██████▌                            | 7976/42525 [14:43<1:03:59,  9.00it/s]

 19%|██████▌                            | 7979/42525 [14:44<1:05:55,  8.73it/s]

 19%|██████▌                            | 7982/42525 [14:44<1:03:12,  9.11it/s]

 19%|██████▌                            | 7984/42525 [14:44<1:00:28,  9.52it/s]

 19%|██████▌                            | 7988/42525 [14:44<1:01:04,  9.43it/s]

 19%|██████▉                              | 7991/42525 [14:45<59:21,  9.70it/s]

 19%|██████▌                            | 7993/42525 [14:45<1:03:02,  9.13it/s]

 19%|██████▌                            | 7994/42525 [14:45<1:03:57,  9.00it/s]

 19%|██████▌                            | 7997/42525 [14:45<1:03:45,  9.03it/s]

 19%|██████▌                            | 8000/42525 [14:46<1:09:33,  8.27it/s]

 19%|██████▌                            | 8002/42525 [14:46<1:16:38,  7.51it/s]

 19%|██████▌                            | 8003/42525 [14:46<1:16:23,  7.53it/s]

 19%|██████▌                            | 8007/42525 [14:47<1:05:11,  8.83it/s]

 19%|██████▉                              | 8011/42525 [14:47<59:27,  9.68it/s]

 19%|██████▌                            | 8014/42525 [14:47<1:03:31,  9.05it/s]

 19%|██████▌                            | 8017/42525 [14:48<1:04:19,  8.94it/s]

 19%|██████▌                            | 8020/42525 [14:48<1:01:43,  9.32it/s]

 19%|██████▌                            | 8021/42525 [14:48<1:01:27,  9.36it/s]

 19%|██████▌                            | 8024/42525 [14:49<1:03:55,  8.99it/s]

 19%|██████▌                            | 8027/42525 [14:49<1:03:42,  9.02it/s]

 19%|██████▌                            | 8030/42525 [14:49<1:02:54,  9.14it/s]

 19%|██████▉                              | 8033/42525 [14:50<59:30,  9.66it/s]

 19%|██████▌                            | 8036/42525 [14:50<1:04:25,  8.92it/s]

 19%|██████▌                            | 8038/42525 [14:50<1:05:28,  8.78it/s]

 19%|██████▌                            | 8040/42525 [14:50<1:10:19,  8.17it/s]

 19%|██████▌                            | 8043/42525 [14:51<1:05:12,  8.81it/s]

 19%|██████▌                            | 8045/42525 [14:51<1:09:32,  8.26it/s]

 19%|██████▌                            | 8047/42525 [14:51<1:03:59,  8.98it/s]

 19%|██████▋                            | 8050/42525 [14:51<1:07:26,  8.52it/s]

 19%|██████▋                            | 8054/42525 [14:52<1:00:47,  9.45it/s]

 19%|██████▋                            | 8056/42525 [14:52<1:01:13,  9.38it/s]

 19%|██████▋                            | 8057/42525 [14:52<1:03:19,  9.07it/s]

 19%|██████▋                            | 8059/42525 [14:52<1:02:32,  9.18it/s]

 19%|██████▋                            | 8062/42525 [14:53<1:02:39,  9.17it/s]

 19%|██████▋                            | 8064/42525 [14:53<1:12:11,  7.96it/s]

 19%|██████▋                            | 8068/42525 [14:53<1:02:30,  9.19it/s]

 19%|██████▋                            | 8070/42525 [14:54<1:05:07,  8.82it/s]

 19%|██████▋                            | 8072/42525 [14:54<1:07:02,  8.56it/s]

 19%|██████▋                            | 8074/42525 [14:54<1:04:38,  8.88it/s]

 19%|███████                              | 8078/42525 [14:55<59:02,  9.72it/s]

 19%|██████▋                            | 8080/42525 [14:55<1:02:09,  9.24it/s]

 19%|██████▋                            | 8082/42525 [14:55<1:01:46,  9.29it/s]

 19%|██████▋                            | 8085/42525 [14:55<1:03:02,  9.10it/s]

 19%|██████▋                            | 8088/42525 [14:56<1:02:05,  9.24it/s]

 19%|██████▋                            | 8090/42525 [14:56<1:03:29,  9.04it/s]

 19%|██████▋                            | 8093/42525 [14:56<1:05:23,  8.78it/s]

 19%|██████▋                            | 8096/42525 [14:57<1:00:45,  9.45it/s]

 19%|██████▋                            | 8098/42525 [14:57<1:04:37,  8.88it/s]

 19%|██████▋                            | 8102/42525 [14:57<1:03:02,  9.10it/s]

 19%|██████▋                            | 8104/42525 [14:57<1:09:08,  8.30it/s]

 19%|██████▋                            | 8107/42525 [14:58<1:02:33,  9.17it/s]

 19%|███████                              | 8110/42525 [14:58<59:28,  9.65it/s]

 19%|██████▋                            | 8113/42525 [14:58<1:08:14,  8.41it/s]

 19%|██████▋                            | 8115/42525 [14:59<1:15:20,  7.61it/s]

 19%|██████▋                            | 8118/42525 [14:59<1:04:54,  8.83it/s]

 19%|██████▋                            | 8121/42525 [14:59<1:03:43,  9.00it/s]

 19%|██████▋                            | 8123/42525 [15:00<1:01:32,  9.32it/s]

 19%|██████▋                            | 8126/42525 [15:00<1:05:57,  8.69it/s]

 19%|██████▋                            | 8128/42525 [15:00<1:02:07,  9.23it/s]

 19%|██████▋                            | 8132/42525 [15:01<1:00:18,  9.51it/s]

 19%|███████                              | 8136/42525 [15:01<58:23,  9.81it/s]

 19%|██████▋                            | 8138/42525 [15:01<1:00:05,  9.54it/s]

 19%|██████▋                            | 8139/42525 [15:01<1:03:49,  8.98it/s]

 19%|██████▋                            | 8143/42525 [15:02<1:03:15,  9.06it/s]

 19%|██████▋                            | 8146/42525 [15:02<1:04:44,  8.85it/s]

 19%|██████▋                            | 8147/42525 [15:02<1:05:08,  8.80it/s]

 19%|██████▋                            | 8151/42525 [15:03<1:03:04,  9.08it/s]

 19%|██████▋                            | 8154/42525 [15:03<1:00:02,  9.54it/s]

 19%|██████▋                            | 8156/42525 [15:03<1:02:11,  9.21it/s]

 19%|██████▋                            | 8158/42525 [15:03<1:02:06,  9.22it/s]

 19%|██████▋                            | 8160/42525 [15:04<1:01:51,  9.26it/s]

 19%|██████▋                            | 8162/42525 [15:04<1:08:37,  8.34it/s]

 19%|██████▋                            | 8165/42525 [15:04<1:04:04,  8.94it/s]

 19%|██████▋                            | 8168/42525 [15:05<1:00:15,  9.50it/s]

 19%|██████▋                            | 8171/42525 [15:05<1:07:33,  8.47it/s]

 19%|██████▋                            | 8173/42525 [15:05<1:07:14,  8.51it/s]

 19%|██████▋                            | 8175/42525 [15:05<1:05:43,  8.71it/s]

 19%|██████▋                            | 8177/42525 [15:06<1:05:22,  8.76it/s]

 19%|██████▋                            | 8180/42525 [15:06<1:05:33,  8.73it/s]

 19%|██████▋                            | 8182/42525 [15:06<1:01:18,  9.34it/s]

 19%|██████▋                            | 8184/42525 [15:06<1:01:39,  9.28it/s]

 19%|██████▋                            | 8186/42525 [15:07<1:04:41,  8.85it/s]

 19%|██████▋                            | 8188/42525 [15:07<1:03:04,  9.07it/s]

 19%|██████▋                            | 8192/42525 [15:07<1:01:01,  9.38it/s]

 19%|██████▋                            | 8194/42525 [15:07<1:01:32,  9.30it/s]

 19%|██████▋                            | 8197/42525 [15:08<1:00:16,  9.49it/s]

 19%|███████▏                             | 8201/42525 [15:08<56:56, 10.05it/s]

 19%|██████▊                            | 8202/42525 [15:08<1:02:21,  9.17it/s]

 19%|██████▊                            | 8205/42525 [15:09<1:08:04,  8.40it/s]

 19%|██████▊                            | 8208/42525 [15:09<1:07:15,  8.50it/s]

 19%|██████▊                            | 8210/42525 [15:09<1:10:25,  8.12it/s]

 19%|██████▊                            | 8213/42525 [15:10<1:02:55,  9.09it/s]

 19%|██████▊                            | 8215/42525 [15:10<1:05:11,  8.77it/s]

 19%|██████▊                            | 8218/42525 [15:10<1:03:03,  9.07it/s]

 19%|███████▏                             | 8220/42525 [15:10<59:47,  9.56it/s]

 19%|███████▏                             | 8224/42525 [15:11<58:00,  9.85it/s]

 19%|███████▏                             | 8228/42525 [15:11<55:55, 10.22it/s]

 19%|██████▊                            | 8231/42525 [15:12<1:00:27,  9.45it/s]

 19%|██████▊                            | 8233/42525 [15:12<1:06:59,  8.53it/s]

 19%|██████▊                            | 8235/42525 [15:12<1:10:15,  8.14it/s]

 19%|██████▊                            | 8237/42525 [15:12<1:12:04,  7.93it/s]

 19%|██████▊                            | 8241/42525 [15:13<1:01:03,  9.36it/s]

 19%|███████▏                             | 8244/42525 [15:13<58:40,  9.74it/s]

 19%|███████▏                             | 8246/42525 [15:13<57:39,  9.91it/s]

 19%|██████▊                            | 8248/42525 [15:13<1:02:00,  9.21it/s]

 19%|██████▊                            | 8251/42525 [15:14<1:05:58,  8.66it/s]

 19%|██████▊                            | 8252/42525 [15:14<1:09:54,  8.17it/s]

 19%|██████▊                            | 8254/42525 [15:14<1:10:08,  8.14it/s]

 19%|██████▊                            | 8257/42525 [15:15<1:10:56,  8.05it/s]

 19%|██████▊                            | 8259/42525 [15:15<1:05:38,  8.70it/s]

 19%|██████▊                            | 8261/42525 [15:15<1:04:50,  8.81it/s]

 19%|██████▊                            | 8263/42525 [15:15<1:08:06,  8.38it/s]

 19%|██████▊                            | 8264/42525 [15:15<1:12:07,  7.92it/s]

 19%|██████▊                            | 8268/42525 [15:16<1:02:47,  9.09it/s]

 19%|██████▊                            | 8271/42525 [15:16<1:01:26,  9.29it/s]

 19%|██████▊                            | 8274/42525 [15:16<1:02:25,  9.15it/s]

 19%|██████▊                            | 8275/42525 [15:17<1:01:24,  9.30it/s]

 19%|██████▊                            | 8278/42525 [15:17<1:03:39,  8.97it/s]

 19%|██████▊                            | 8281/42525 [15:17<1:09:39,  8.19it/s]

 19%|██████▊                            | 8284/42525 [15:18<1:02:15,  9.17it/s]

 19%|██████▊                            | 8286/42525 [15:18<1:00:39,  9.41it/s]

 19%|██████▊                            | 8289/42525 [15:18<1:01:49,  9.23it/s]

 20%|███████▏                             | 8293/42525 [15:19<57:53,  9.86it/s]

 20%|██████▊                            | 8295/42525 [15:19<1:03:43,  8.95it/s]

 20%|██████▊                            | 8298/42525 [15:19<1:02:27,  9.13it/s]

 20%|██████▊                            | 8300/42525 [15:19<1:05:50,  8.66it/s]

 20%|██████▊                            | 8302/42525 [15:20<1:08:57,  8.27it/s]

 20%|██████▊                            | 8303/42525 [15:20<1:13:22,  7.77it/s]

 20%|██████▊                            | 8306/42525 [15:20<1:05:31,  8.70it/s]

 20%|██████▊                            | 8308/42525 [15:20<1:03:12,  9.02it/s]

 20%|██████▊                            | 8310/42525 [15:20<1:01:49,  9.22it/s]

 20%|██████▊                            | 8313/42525 [15:21<1:04:33,  8.83it/s]

 20%|██████▊                            | 8316/42525 [15:21<1:00:48,  9.38it/s]

 20%|██████▊                            | 8318/42525 [15:21<1:08:15,  8.35it/s]

 20%|██████▊                            | 8319/42525 [15:22<1:07:59,  8.39it/s]

 20%|██████▊                            | 8322/42525 [15:22<1:05:02,  8.76it/s]

 20%|███████▏                             | 8326/42525 [15:22<59:26,  9.59it/s]

 20%|██████▊                            | 8329/42525 [15:23<1:01:11,  9.31it/s]

 20%|██████▊                            | 8330/42525 [15:23<1:06:07,  8.62it/s]

 20%|██████▊                            | 8332/42525 [15:23<1:05:01,  8.76it/s]

 20%|██████▊                            | 8335/42525 [15:23<1:05:41,  8.67it/s]

 20%|██████▊                            | 8337/42525 [15:24<1:03:52,  8.92it/s]

 20%|██████▊                            | 8340/42525 [15:24<1:05:31,  8.70it/s]

 20%|██████▊                            | 8343/42525 [15:24<1:06:12,  8.61it/s]

 20%|██████▊                            | 8346/42525 [15:25<1:01:39,  9.24it/s]

 20%|███████▎                             | 8350/42525 [15:25<59:22,  9.59it/s]

 20%|██████▊                            | 8353/42525 [15:25<1:01:25,  9.27it/s]

 20%|██████▉                            | 8355/42525 [15:26<1:10:14,  8.11it/s]

 20%|██████▉                            | 8358/42525 [15:26<1:09:40,  8.17it/s]

 20%|██████▉                            | 8362/42525 [15:26<1:01:06,  9.32it/s]

 20%|██████▉                            | 8364/42525 [15:27<1:10:02,  8.13it/s]

 20%|██████▉                            | 8367/42525 [15:27<1:08:57,  8.26it/s]

 20%|██████▉                            | 8368/42525 [15:27<1:12:33,  7.85it/s]

 20%|██████▉                            | 8371/42525 [15:27<1:10:47,  8.04it/s]

 20%|██████▉                            | 8372/42525 [15:28<1:14:03,  7.69it/s]

 20%|██████▉                            | 8375/42525 [15:28<1:10:39,  8.05it/s]

 20%|██████▉                            | 8376/42525 [15:28<1:09:36,  8.18it/s]

 20%|██████▉                            | 8379/42525 [15:28<1:10:17,  8.10it/s]

 20%|██████▉                            | 8382/42525 [15:29<1:02:00,  9.18it/s]

 20%|██████▉                            | 8385/42525 [15:29<1:07:45,  8.40it/s]

 20%|██████▉                            | 8387/42525 [15:29<1:08:36,  8.29it/s]

 20%|██████▉                            | 8389/42525 [15:30<1:14:26,  7.64it/s]

 20%|██████▉                            | 8391/42525 [15:30<1:13:54,  7.70it/s]

 20%|██████▉                            | 8393/42525 [15:30<1:05:02,  8.75it/s]

 20%|██████▉                            | 8396/42525 [15:30<1:05:04,  8.74it/s]

 20%|██████▉                            | 8399/42525 [15:31<1:00:16,  9.44it/s]

 20%|██████▉                            | 8400/42525 [15:31<1:03:53,  8.90it/s]

 20%|██████▉                            | 8403/42525 [15:31<1:01:55,  9.18it/s]

 20%|██████▉                            | 8405/42525 [15:31<1:03:07,  9.01it/s]

 20%|██████▉                            | 8408/42525 [15:32<1:01:01,  9.32it/s]

 20%|███████▎                             | 8411/42525 [15:32<58:07,  9.78it/s]

 20%|███████▎                             | 8415/42525 [15:32<57:13,  9.93it/s]

 20%|███████▎                             | 8419/42525 [15:33<55:51, 10.18it/s]

 20%|███████▎                             | 8421/42525 [15:33<55:25, 10.25it/s]

 20%|███████▎                             | 8425/42525 [15:33<56:54,  9.99it/s]

 20%|███████▎                             | 8429/42525 [15:34<58:38,  9.69it/s]

 20%|███████▎                             | 8431/42525 [15:34<57:32,  9.87it/s]

 20%|██████▉                            | 8434/42525 [15:34<1:00:44,  9.36it/s]

 20%|██████▉                            | 8437/42525 [15:35<1:04:12,  8.85it/s]

 20%|██████▉                            | 8438/42525 [15:35<1:03:49,  8.90it/s]

 20%|██████▉                            | 8440/42525 [15:35<1:02:19,  9.11it/s]

 20%|██████▉                            | 8443/42525 [15:35<1:05:42,  8.64it/s]

 20%|██████▉                            | 8446/42525 [15:36<1:00:26,  9.40it/s]

 20%|██████▉                            | 8448/42525 [15:36<1:01:40,  9.21it/s]

 20%|██████▉                            | 8450/42525 [15:36<1:12:03,  7.88it/s]

 20%|██████▉                            | 8452/42525 [15:36<1:12:38,  7.82it/s]

 20%|██████▉                            | 8454/42525 [15:37<1:06:05,  8.59it/s]

 20%|██████▉                            | 8456/42525 [15:37<1:01:52,  9.18it/s]

 20%|███████▎                             | 8459/42525 [15:37<59:37,  9.52it/s]

 20%|██████▉                            | 8461/42525 [15:37<1:00:28,  9.39it/s]

 20%|███████▎                             | 8463/42525 [15:38<58:00,  9.79it/s]

 20%|███████▎                             | 8467/42525 [15:38<57:06,  9.94it/s]

 20%|██████▉                            | 8469/42525 [15:38<1:01:23,  9.25it/s]

 20%|██████▉                            | 8471/42525 [15:38<1:04:14,  8.84it/s]

 20%|███████▎                             | 8475/42525 [15:39<59:41,  9.51it/s]

 20%|███████▍                             | 8478/42525 [15:39<59:02,  9.61it/s]

 20%|███████▍                             | 8481/42525 [15:40<58:53,  9.63it/s]

 20%|██████▉                            | 8483/42525 [15:40<1:06:18,  8.56it/s]

 20%|██████▉                            | 8486/42525 [15:40<1:03:41,  8.91it/s]

 20%|███████▍                             | 8490/42525 [15:41<58:20,  9.72it/s]

 20%|███████▍                             | 8494/42525 [15:41<57:22,  9.89it/s]

 20%|███████▍                             | 8497/42525 [15:41<58:18,  9.73it/s]

 20%|███████▍                             | 8501/42525 [15:42<56:56,  9.96it/s]

 20%|███████▍                             | 8503/42525 [15:42<56:11, 10.09it/s]

 20%|███████                            | 8505/42525 [15:42<1:00:09,  9.42it/s]

 20%|███████                            | 8508/42525 [15:42<1:04:18,  8.82it/s]

 20%|███████                            | 8510/42525 [15:43<1:02:45,  9.03it/s]

 20%|███████                            | 8513/42525 [15:43<1:00:21,  9.39it/s]

 20%|███████▍                             | 8515/42525 [15:43<58:10,  9.74it/s]

 20%|███████                            | 8518/42525 [15:43<1:00:00,  9.44it/s]

 20%|███████                            | 8522/42525 [15:44<1:00:30,  9.36it/s]

 20%|███████▍                             | 8526/42525 [15:44<57:09,  9.91it/s]

 20%|███████                            | 8529/42525 [15:45<1:01:55,  9.15it/s]

 20%|███████                            | 8533/42525 [15:45<1:00:56,  9.30it/s]

 20%|███████                            | 8536/42525 [15:45<1:04:05,  8.84it/s]

 20%|███████                            | 8539/42525 [15:46<1:02:14,  9.10it/s]

 20%|███████                            | 8541/42525 [15:46<1:06:28,  8.52it/s]

 20%|███████                            | 8543/42525 [15:46<1:11:00,  7.98it/s]

 20%|███████                            | 8545/42525 [15:46<1:06:27,  8.52it/s]

 20%|███████▍                             | 8549/42525 [15:47<58:19,  9.71it/s]

 20%|███████▍                             | 8552/42525 [15:47<58:58,  9.60it/s]

 20%|███████▍                             | 8556/42525 [15:48<56:10, 10.08it/s]

 20%|███████▍                             | 8558/42525 [15:48<55:31, 10.20it/s]

 20%|███████                            | 8560/42525 [15:48<1:00:35,  9.34it/s]

 20%|███████                            | 8564/42525 [15:48<1:00:34,  9.34it/s]

 20%|███████                            | 8567/42525 [15:49<1:01:02,  9.27it/s]

 20%|███████                            | 8569/42525 [15:49<1:01:45,  9.16it/s]

 20%|███████                            | 8570/42525 [15:49<1:06:50,  8.47it/s]

 20%|███████                            | 8574/42525 [15:50<1:00:08,  9.41it/s]

 20%|███████▍                             | 8577/42525 [15:50<59:02,  9.58it/s]

 20%|███████▍                             | 8580/42525 [15:50<57:19,  9.87it/s]

 20%|███████▍                             | 8583/42525 [15:50<59:38,  9.49it/s]

 20%|███████                            | 8585/42525 [15:51<1:01:09,  9.25it/s]

 20%|███████                            | 8586/42525 [15:51<1:06:41,  8.48it/s]

 20%|███████                            | 8589/42525 [15:51<1:03:24,  8.92it/s]

 20%|███████▍                             | 8593/42525 [15:52<58:56,  9.59it/s]

 20%|███████                            | 8596/42525 [15:52<1:00:21,  9.37it/s]

 20%|███████                            | 8598/42525 [15:52<1:02:00,  9.12it/s]

 20%|███████                            | 8601/42525 [15:52<1:07:09,  8.42it/s]

 20%|███████                            | 8605/42525 [15:53<1:00:30,  9.34it/s]

 20%|███████▍                             | 8608/42525 [15:53<58:14,  9.71it/s]

 20%|███████                            | 8610/42525 [15:53<1:04:20,  8.79it/s]

 20%|███████▍                             | 8613/42525 [15:54<58:55,  9.59it/s]

 20%|███████▍                             | 8615/42525 [15:54<58:48,  9.61it/s]

 20%|███████                            | 8617/42525 [15:54<1:05:18,  8.65it/s]

 20%|███████                            | 8618/42525 [15:54<1:06:26,  8.51it/s]

 20%|███████                            | 8621/42525 [15:55<1:02:16,  9.07it/s]

 20%|███████                            | 8623/42525 [15:55<1:08:14,  8.28it/s]

 20%|███████                            | 8626/42525 [15:55<1:01:50,  9.14it/s]

 20%|███████                            | 8628/42525 [15:55<1:04:56,  8.70it/s]

 20%|███████                            | 8632/42525 [15:56<1:00:52,  9.28it/s]

 20%|███████                            | 8635/42525 [15:56<1:00:17,  9.37it/s]

 20%|███████                            | 8637/42525 [15:56<1:05:50,  8.58it/s]

 20%|███████                            | 8639/42525 [15:57<1:01:55,  9.12it/s]

 20%|███████▌                             | 8641/42525 [15:57<59:42,  9.46it/s]

 20%|███████▌                             | 8645/42525 [15:57<58:29,  9.65it/s]

 20%|███████▌                             | 8647/42525 [15:57<59:14,  9.53it/s]

 20%|███████▌                             | 8650/42525 [15:58<58:52,  9.59it/s]

 20%|███████                            | 8652/42525 [15:58<1:09:55,  8.07it/s]

 20%|███████                            | 8654/42525 [15:58<1:06:59,  8.43it/s]

 20%|███████                            | 8656/42525 [15:58<1:02:41,  9.00it/s]

 20%|███████▏                           | 8658/42525 [15:59<1:01:10,  9.23it/s]

 20%|███████▏                           | 8661/42525 [15:59<1:00:25,  9.34it/s]

 20%|███████▌                             | 8663/42525 [15:59<59:19,  9.51it/s]

 20%|███████▌                             | 8664/42525 [15:59<59:35,  9.47it/s]

 20%|███████▏                           | 8667/42525 [16:00<1:02:23,  9.04it/s]

 20%|███████▌                             | 8670/42525 [16:00<59:57,  9.41it/s]

 20%|███████▌                             | 8671/42525 [16:00<59:09,  9.54it/s]

 20%|███████▌                             | 8675/42525 [16:01<59:55,  9.41it/s]

 20%|███████▏                           | 8677/42525 [16:01<1:02:12,  9.07it/s]

 20%|███████▏                           | 8680/42525 [16:01<1:04:54,  8.69it/s]

 20%|███████▏                           | 8681/42525 [16:01<1:08:47,  8.20it/s]

 20%|███████▏                           | 8684/42525 [16:02<1:04:01,  8.81it/s]

 20%|███████▌                             | 8688/42525 [16:02<59:19,  9.51it/s]

 20%|███████▌                             | 8691/42525 [16:02<58:57,  9.57it/s]

 20%|███████▏                           | 8693/42525 [16:03<1:03:11,  8.92it/s]

 20%|███████▏                           | 8695/42525 [16:03<1:06:47,  8.44it/s]

 20%|███████▏                           | 8698/42525 [16:03<1:00:03,  9.39it/s]

 20%|███████▏                           | 8700/42525 [16:03<1:01:38,  9.14it/s]

 20%|███████▏                           | 8702/42525 [16:04<1:04:19,  8.76it/s]

 20%|███████▌                             | 8705/42525 [16:04<58:43,  9.60it/s]

 20%|███████▌                             | 8707/42525 [16:04<57:40,  9.77it/s]

 20%|███████▌                             | 8709/42525 [16:04<57:24,  9.82it/s]

 20%|███████▌                             | 8713/42525 [16:05<57:42,  9.77it/s]

 20%|███████▏                           | 8715/42525 [16:05<1:03:38,  8.86it/s]

 20%|███████▏                           | 8717/42525 [16:05<1:04:42,  8.71it/s]

 21%|███████▏                           | 8720/42525 [16:05<1:02:48,  8.97it/s]

 21%|███████▌                             | 8724/42525 [16:06<57:12,  9.85it/s]

 21%|███████▏                           | 8727/42525 [16:06<1:01:36,  9.14it/s]

 21%|███████▌                             | 8729/42525 [16:06<58:35,  9.61it/s]

 21%|███████▌                             | 8733/42525 [16:07<56:48,  9.92it/s]

 21%|███████▌                             | 8736/42525 [16:07<57:28,  9.80it/s]

 21%|███████▏                           | 8738/42525 [16:07<1:01:11,  9.20it/s]

 21%|███████▏                           | 8741/42525 [16:08<1:07:42,  8.32it/s]

 21%|███████▏                           | 8744/42525 [16:08<1:05:42,  8.57it/s]

 21%|███████▏                           | 8747/42525 [16:08<1:09:41,  8.08it/s]

 21%|███████▏                           | 8749/42525 [16:09<1:15:42,  7.44it/s]

 21%|███████▏                           | 8751/42525 [16:09<1:11:06,  7.92it/s]

 21%|███████▏                           | 8753/42525 [16:09<1:03:40,  8.84it/s]

 21%|███████▌                             | 8757/42525 [16:10<59:09,  9.51it/s]

 21%|███████▌                             | 8760/42525 [16:10<57:40,  9.76it/s]

 21%|███████▌                             | 8763/42525 [16:10<56:49,  9.90it/s]

 21%|███████▋                             | 8766/42525 [16:11<59:59,  9.38it/s]

 21%|███████▋                             | 8768/42525 [16:11<57:51,  9.72it/s]

 21%|███████▋                             | 8771/42525 [16:11<58:11,  9.67it/s]

 21%|███████▋                             | 8774/42525 [16:11<57:49,  9.73it/s]

 21%|███████▏                           | 8776/42525 [16:12<1:01:55,  9.08it/s]

 21%|███████▋                             | 8779/42525 [16:12<58:21,  9.64it/s]

 21%|███████▋                             | 8783/42525 [16:12<59:43,  9.42it/s]

 21%|███████▏                           | 8786/42525 [16:13<1:02:01,  9.07it/s]

 21%|███████▋                             | 8788/42525 [16:13<59:49,  9.40it/s]

 21%|███████▏                           | 8791/42525 [16:13<1:02:17,  9.03it/s]

 21%|███████▋                             | 8794/42525 [16:14<59:28,  9.45it/s]

 21%|███████▏                           | 8796/42525 [16:14<1:02:39,  8.97it/s]

 21%|███████▏                           | 8799/42525 [16:14<1:00:46,  9.25it/s]

 21%|███████▏                           | 8801/42525 [16:14<1:00:53,  9.23it/s]

 21%|███████▏                           | 8803/42525 [16:15<1:07:12,  8.36it/s]

 21%|███████▏                           | 8805/42525 [16:15<1:02:46,  8.95it/s]

 21%|███████▋                             | 8808/42525 [16:15<59:49,  9.39it/s]

 21%|███████▋                             | 8810/42525 [16:15<57:44,  9.73it/s]

 21%|███████▋                             | 8813/42525 [16:16<58:15,  9.65it/s]

 21%|███████▎                           | 8816/42525 [16:16<1:00:37,  9.27it/s]

 21%|███████▋                             | 8819/42525 [16:16<59:06,  9.50it/s]

 21%|███████▎                           | 8821/42525 [16:16<1:07:00,  8.38it/s]

 21%|███████▎                           | 8824/42525 [16:17<1:06:22,  8.46it/s]

 21%|███████▎                           | 8826/42525 [16:17<1:03:26,  8.85it/s]

 21%|███████▎                           | 8828/42525 [16:17<1:07:27,  8.33it/s]

 21%|███████▎                           | 8830/42525 [16:17<1:01:17,  9.16it/s]

 21%|███████▎                           | 8833/42525 [16:18<1:07:49,  8.28it/s]

 21%|███████▋                             | 8837/42525 [16:18<59:24,  9.45it/s]

 21%|███████▋                             | 8840/42525 [16:19<57:36,  9.74it/s]

 21%|███████▎                           | 8841/42525 [16:19<1:03:22,  8.86it/s]

 21%|███████▎                           | 8844/42525 [16:19<1:07:49,  8.28it/s]

 21%|███████▎                           | 8846/42525 [16:19<1:07:50,  8.27it/s]

 21%|███████▋                             | 8850/42525 [16:20<59:09,  9.49it/s]

 21%|███████▋                             | 8853/42525 [16:20<57:06,  9.83it/s]

 21%|███████▋                             | 8855/42525 [16:20<55:59, 10.02it/s]

 21%|███████▋                             | 8858/42525 [16:21<58:22,  9.61it/s]

 21%|███████▎                           | 8861/42525 [16:21<1:00:59,  9.20it/s]

 21%|███████▎                           | 8863/42525 [16:21<1:03:37,  8.82it/s]

 21%|███████▋                             | 8866/42525 [16:21<59:09,  9.48it/s]

 21%|███████▎                           | 8868/42525 [16:22<1:09:10,  8.11it/s]

 21%|███████▎                           | 8871/42525 [16:22<1:00:46,  9.23it/s]

 21%|███████▎                           | 8872/42525 [16:22<1:01:34,  9.11it/s]

 21%|███████▎                           | 8874/42525 [16:22<1:04:23,  8.71it/s]

 21%|███████▎                           | 8877/42525 [16:23<1:04:25,  8.70it/s]

 21%|███████▎                           | 8880/42525 [16:23<1:04:08,  8.74it/s]

 21%|███████▎                           | 8883/42525 [16:23<1:03:09,  8.88it/s]

 21%|███████▎                           | 8886/42525 [16:24<1:04:44,  8.66it/s]

 21%|███████▎                           | 8888/42525 [16:24<1:03:09,  8.88it/s]

 21%|███████▎                           | 8890/42525 [16:24<1:07:42,  8.28it/s]

 21%|███████▎                           | 8893/42525 [16:24<1:02:41,  8.94it/s]

 21%|███████▎                           | 8895/42525 [16:25<1:00:18,  9.29it/s]

 21%|███████▎                           | 8898/42525 [16:25<1:03:51,  8.78it/s]

 21%|███████▎                           | 8900/42525 [16:25<1:00:07,  9.32it/s]

 21%|███████▎                           | 8904/42525 [16:26<1:00:10,  9.31it/s]

 21%|███████▊                             | 8908/42525 [16:26<57:13,  9.79it/s]

 21%|███████▊                             | 8909/42525 [16:26<57:47,  9.70it/s]

 21%|███████▎                           | 8912/42525 [16:27<1:03:09,  8.87it/s]

 21%|███████▎                           | 8914/42525 [16:27<1:06:38,  8.40it/s]

 21%|███████▎                           | 8917/42525 [16:27<1:07:21,  8.32it/s]

 21%|███████▎                           | 8920/42525 [16:27<1:04:14,  8.72it/s]

 21%|███████▎                           | 8922/42525 [16:28<1:03:06,  8.88it/s]

 21%|███████▎                           | 8924/42525 [16:28<1:12:30,  7.72it/s]

 21%|███████▎                           | 8927/42525 [16:28<1:03:18,  8.84it/s]

 21%|███████▎                           | 8929/42525 [16:29<1:08:17,  8.20it/s]

 21%|███████▎                           | 8932/42525 [16:29<1:00:07,  9.31it/s]

 21%|███████▎                           | 8934/42525 [16:29<1:05:57,  8.49it/s]

 21%|███████▎                           | 8937/42525 [16:29<1:00:40,  9.23it/s]

 21%|███████▎                           | 8940/42525 [16:30<1:02:35,  8.94it/s]

 21%|███████▊                             | 8943/42525 [16:30<59:48,  9.36it/s]

 21%|███████▎                           | 8945/42525 [16:30<1:04:27,  8.68it/s]

 21%|███████▎                           | 8948/42525 [16:31<1:05:04,  8.60it/s]

 21%|███████▎                           | 8950/42525 [16:31<1:04:22,  8.69it/s]

 21%|███████▎                           | 8953/42525 [16:31<1:03:39,  8.79it/s]

 21%|███████▊                             | 8956/42525 [16:32<58:37,  9.54it/s]

 21%|███████▊                             | 8960/42525 [16:32<55:51, 10.01it/s]

 21%|███████▊                             | 8962/42525 [16:32<59:02,  9.47it/s]

 21%|███████▊                             | 8963/42525 [16:32<58:57,  9.49it/s]

 21%|███████▍                           | 8965/42525 [16:32<1:02:50,  8.90it/s]

 21%|███████▊                             | 8969/42525 [16:33<58:52,  9.50it/s]

 21%|███████▊                             | 8971/42525 [16:33<58:42,  9.53it/s]

 21%|███████▊                             | 8974/42525 [16:33<57:26,  9.74it/s]

 21%|███████▍                           | 8977/42525 [16:34<1:01:55,  9.03it/s]

 21%|███████▊                             | 8981/42525 [16:34<56:40,  9.86it/s]

 21%|███████▍                           | 8984/42525 [16:35<1:02:02,  9.01it/s]

 21%|███████▊                             | 8987/42525 [16:35<59:27,  9.40it/s]

 21%|███████▊                             | 8991/42525 [16:35<56:06,  9.96it/s]

 21%|███████▊                             | 8995/42525 [16:36<57:18,  9.75it/s]

 21%|███████▊                             | 8997/42525 [16:36<57:43,  9.68it/s]

 21%|███████▍                           | 9000/42525 [16:36<1:01:32,  9.08it/s]

 21%|███████▍                           | 9002/42525 [16:36<1:05:39,  8.51it/s]

 21%|███████▊                             | 9005/42525 [16:37<59:35,  9.37it/s]

 21%|███████▍                           | 9008/42525 [16:37<1:03:03,  8.86it/s]

 21%|███████▍                           | 9010/42525 [16:37<1:05:03,  8.59it/s]

 21%|███████▍                           | 9012/42525 [16:38<1:00:07,  9.29it/s]

 21%|███████▍                           | 9015/42525 [16:38<1:01:06,  9.14it/s]

 21%|███████▊                             | 9017/42525 [16:38<59:51,  9.33it/s]

 21%|███████▍                           | 9019/42525 [16:38<1:05:50,  8.48it/s]

 21%|███████▍                           | 9023/42525 [16:39<1:00:42,  9.20it/s]

 21%|███████▍                           | 9026/42525 [16:39<1:00:41,  9.20it/s]

 21%|███████▍                           | 9027/42525 [16:39<1:00:51,  9.17it/s]

 21%|███████▊                             | 9031/42525 [16:40<59:35,  9.37it/s]

 21%|███████▊                             | 9034/42525 [16:40<57:06,  9.77it/s]

 21%|███████▍                           | 9036/42525 [16:40<1:01:59,  9.00it/s]

 21%|███████▍                           | 9038/42525 [16:40<1:03:32,  8.78it/s]

 21%|███████▊                             | 9041/42525 [16:41<58:48,  9.49it/s]

 21%|███████▊                             | 9045/42525 [16:41<59:17,  9.41it/s]

 21%|███████▍                           | 9048/42525 [16:41<1:00:01,  9.30it/s]

 21%|███████▉                             | 9051/42525 [16:42<57:18,  9.73it/s]

 21%|███████▉                             | 9053/42525 [16:42<59:05,  9.44it/s]

 21%|███████▍                           | 9055/42525 [16:42<1:04:10,  8.69it/s]

 21%|███████▍                           | 9059/42525 [16:43<1:00:15,  9.26it/s]

 21%|███████▍                           | 9061/42525 [16:43<1:01:44,  9.03it/s]

 21%|███████▉                             | 9065/42525 [16:43<58:35,  9.52it/s]

 21%|███████▉                             | 9068/42525 [16:44<58:09,  9.59it/s]

 21%|███████▍                           | 9070/42525 [16:44<1:03:20,  8.80it/s]

 21%|███████▍                           | 9071/42525 [16:44<1:07:53,  8.21it/s]

 21%|███████▍                           | 9073/42525 [16:44<1:06:23,  8.40it/s]

 21%|███████▍                           | 9076/42525 [16:45<1:05:16,  8.54it/s]

 21%|███████▍                           | 9079/42525 [16:45<1:02:20,  8.94it/s]

 21%|███████▉                             | 9082/42525 [16:45<59:56,  9.30it/s]

 21%|███████▍                           | 9083/42525 [16:45<1:01:46,  9.02it/s]

 21%|███████▍                           | 9086/42525 [16:46<1:05:00,  8.57it/s]

 21%|███████▍                           | 9087/42525 [16:46<1:04:27,  8.64it/s]

 21%|███████▍                           | 9090/42525 [16:46<1:09:49,  7.98it/s]

 21%|███████▍                           | 9094/42525 [16:47<1:00:22,  9.23it/s]

 21%|███████▍                           | 9097/42525 [16:47<1:00:17,  9.24it/s]

 21%|███████▍                           | 9100/42525 [16:47<1:06:53,  8.33it/s]

 21%|███████▍                           | 9102/42525 [16:48<1:09:17,  8.04it/s]

 21%|███████▍                           | 9104/42525 [16:48<1:07:04,  8.30it/s]

 21%|███████▍                           | 9106/42525 [16:48<1:03:58,  8.71it/s]

 21%|███████▉                             | 9109/42525 [16:48<59:08,  9.42it/s]

 21%|███████▍                           | 9112/42525 [16:49<1:02:27,  8.92it/s]

 21%|███████▉                             | 9116/42525 [16:49<57:18,  9.72it/s]

 21%|███████▉                             | 9118/42525 [16:49<58:24,  9.53it/s]

 21%|███████▉                             | 9122/42525 [16:50<58:58,  9.44it/s]

 21%|███████▌                           | 9124/42525 [16:50<1:04:03,  8.69it/s]

 21%|███████▌                           | 9127/42525 [16:50<1:08:13,  8.16it/s]

 21%|███████▌                           | 9130/42525 [16:51<1:02:16,  8.94it/s]

 21%|███████▌                           | 9132/42525 [16:51<1:10:22,  7.91it/s]

 21%|███████▌                           | 9136/42525 [16:51<1:02:17,  8.93it/s]

 21%|███████▌                           | 9139/42525 [16:52<1:00:29,  9.20it/s]

 21%|███████▌                           | 9141/42525 [16:52<1:07:30,  8.24it/s]

 22%|███████▌                           | 9144/42525 [16:52<1:04:03,  8.68it/s]

 22%|███████▉                             | 9148/42525 [16:53<57:49,  9.62it/s]

 22%|███████▉                             | 9151/42525 [16:53<59:04,  9.42it/s]

 22%|███████▉                             | 9153/42525 [16:53<59:16,  9.38it/s]

 22%|███████▌                           | 9154/42525 [16:53<1:05:02,  8.55it/s]

 22%|███████▌                           | 9158/42525 [16:54<1:02:07,  8.95it/s]

 22%|███████▌                           | 9160/42525 [16:54<1:01:42,  9.01it/s]

 22%|███████▌                           | 9162/42525 [16:54<1:00:40,  9.17it/s]

 22%|███████▌                           | 9164/42525 [16:54<1:04:19,  8.64it/s]

 22%|███████▉                             | 9168/42525 [16:55<58:02,  9.58it/s]

 22%|███████▌                           | 9171/42525 [16:55<1:02:28,  8.90it/s]

 22%|███████▌                           | 9173/42525 [16:55<1:03:49,  8.71it/s]

 22%|███████▌                           | 9175/42525 [16:56<1:06:35,  8.35it/s]

 22%|███████▌                           | 9176/42525 [16:56<1:06:10,  8.40it/s]

 22%|███████▌                           | 9179/42525 [16:56<1:03:38,  8.73it/s]

 22%|███████▌                           | 9181/42525 [16:56<1:07:19,  8.25it/s]

 22%|███████▌                           | 9184/42525 [16:57<1:07:06,  8.28it/s]

 22%|███████▌                           | 9187/42525 [16:57<1:06:54,  8.30it/s]

 22%|███████▌                           | 9188/42525 [16:57<1:06:36,  8.34it/s]

 22%|███████▌                           | 9190/42525 [16:57<1:04:07,  8.67it/s]

 22%|███████▌                           | 9193/42525 [16:58<1:05:16,  8.51it/s]

 22%|███████▌                           | 9196/42525 [16:58<1:08:59,  8.05it/s]

 22%|███████▌                           | 9199/42525 [16:59<1:03:02,  8.81it/s]

 22%|███████▌                           | 9201/42525 [16:59<1:04:21,  8.63it/s]

 22%|███████▌                           | 9203/42525 [16:59<1:07:57,  8.17it/s]

 22%|███████▌                           | 9205/42525 [16:59<1:15:27,  7.36it/s]

 22%|███████▌                           | 9207/42525 [17:00<1:05:33,  8.47it/s]

 22%|███████▌                           | 9210/42525 [17:00<1:05:02,  8.54it/s]

 22%|███████▌                           | 9211/42525 [17:00<1:03:40,  8.72it/s]

 22%|███████▌                           | 9214/42525 [17:00<1:07:29,  8.23it/s]

 22%|███████▌                           | 9216/42525 [17:01<1:07:48,  8.19it/s]

 22%|███████▌                           | 9219/42525 [17:01<1:02:42,  8.85it/s]

 22%|███████▌                           | 9221/42525 [17:01<1:09:21,  8.00it/s]

 22%|███████▌                           | 9224/42525 [17:02<1:04:55,  8.55it/s]

 22%|███████▌                           | 9226/42525 [17:02<1:00:30,  9.17it/s]

 22%|███████▌                           | 9229/42525 [17:02<1:00:25,  9.18it/s]

 22%|███████▌                           | 9232/42525 [17:02<1:03:10,  8.78it/s]

 22%|████████                             | 9236/42525 [17:03<58:06,  9.55it/s]

 22%|████████                             | 9238/42525 [17:03<58:00,  9.56it/s]

 22%|███████▌                           | 9241/42525 [17:03<1:02:12,  8.92it/s]

 22%|███████▌                           | 9243/42525 [17:04<1:04:31,  8.60it/s]

 22%|███████▌                           | 9246/42525 [17:04<1:00:44,  9.13it/s]

 22%|████████                             | 9250/42525 [17:04<56:15,  9.86it/s]

 22%|████████                             | 9253/42525 [17:05<56:27,  9.82it/s]

 22%|████████                             | 9256/42525 [17:05<55:48,  9.94it/s]

 22%|████████                             | 9260/42525 [17:05<58:18,  9.51it/s]

 22%|████████                             | 9263/42525 [17:06<59:56,  9.25it/s]

 22%|███████▋                           | 9265/42525 [17:06<1:02:47,  8.83it/s]

 22%|███████▋                           | 9268/42525 [17:06<1:01:17,  9.04it/s]

 22%|███████▋                           | 9271/42525 [17:07<1:03:17,  8.76it/s]

 22%|███████▋                           | 9273/42525 [17:07<1:07:01,  8.27it/s]

 22%|███████▋                           | 9275/42525 [17:07<1:02:29,  8.87it/s]

 22%|███████▋                           | 9277/42525 [17:07<1:05:01,  8.52it/s]

 22%|███████▋                           | 9280/42525 [17:08<1:04:37,  8.57it/s]

 22%|████████                             | 9283/42525 [17:08<59:40,  9.28it/s]

 22%|███████▋                           | 9285/42525 [17:08<1:03:34,  8.71it/s]

 22%|███████▋                           | 9287/42525 [17:08<1:06:40,  8.31it/s]

 22%|███████▋                           | 9290/42525 [17:09<1:06:33,  8.32it/s]

 22%|███████▋                           | 9293/42525 [17:09<1:00:23,  9.17it/s]

 22%|████████                             | 9296/42525 [17:09<57:51,  9.57it/s]

 22%|███████▋                           | 9297/42525 [17:10<1:03:30,  8.72it/s]

 22%|███████▋                           | 9301/42525 [17:10<1:01:15,  9.04it/s]

 22%|████████                             | 9304/42525 [17:10<59:45,  9.27it/s]

 22%|███████▋                           | 9306/42525 [17:11<1:08:11,  8.12it/s]

 22%|███████▋                           | 9308/42525 [17:11<1:05:55,  8.40it/s]

 22%|███████▋                           | 9310/42525 [17:11<1:06:05,  8.38it/s]

 22%|███████▋                           | 9311/42525 [17:11<1:05:06,  8.50it/s]

 22%|████████                             | 9315/42525 [17:12<58:42,  9.43it/s]

 22%|████████                             | 9317/42525 [17:12<57:03,  9.70it/s]

 22%|████████                             | 9321/42525 [17:12<56:06,  9.86it/s]

 22%|████████                             | 9324/42525 [17:13<56:49,  9.74it/s]

 22%|████████                             | 9327/42525 [17:13<55:17, 10.01it/s]

 22%|████████                             | 9330/42525 [17:13<55:08, 10.03it/s]

 22%|████████                             | 9332/42525 [17:13<54:31, 10.15it/s]

 22%|████████                             | 9335/42525 [17:14<59:37,  9.28it/s]

 22%|███████▋                           | 9337/42525 [17:14<1:03:49,  8.67it/s]

 22%|███████▋                           | 9339/42525 [17:14<1:01:19,  9.02it/s]

 22%|████████▏                            | 9342/42525 [17:14<58:41,  9.42it/s]

 22%|████████▏                            | 9345/42525 [17:15<57:47,  9.57it/s]

 22%|████████▏                            | 9346/42525 [17:15<57:40,  9.59it/s]

 22%|████████▏                            | 9350/42525 [17:15<56:23,  9.80it/s]

 22%|████████▏                            | 9354/42525 [17:16<58:11,  9.50it/s]

 22%|████████▏                            | 9357/42525 [17:16<57:11,  9.67it/s]

 22%|███████▋                           | 9359/42525 [17:16<1:00:52,  9.08it/s]

 22%|███████▋                           | 9361/42525 [17:16<1:00:40,  9.11it/s]

 22%|███████▋                           | 9363/42525 [17:17<1:05:05,  8.49it/s]

 22%|███████▋                           | 9365/42525 [17:17<1:09:47,  7.92it/s]

 22%|███████▋                           | 9367/42525 [17:17<1:12:00,  7.67it/s]

 22%|███████▋                           | 9369/42525 [17:18<1:12:39,  7.61it/s]

 22%|███████▋                           | 9372/42525 [17:18<1:02:54,  8.78it/s]

 22%|███████▋                           | 9374/42525 [17:18<1:00:24,  9.15it/s]

 22%|███████▋                           | 9376/42525 [17:18<1:05:56,  8.38it/s]

 22%|███████▋                           | 9379/42525 [17:19<1:01:36,  8.97it/s]

 22%|███████▋                           | 9381/42525 [17:19<1:11:19,  7.74it/s]

 22%|███████▋                           | 9384/42525 [17:19<1:02:05,  8.90it/s]

 22%|███████▋                           | 9387/42525 [17:20<1:03:53,  8.65it/s]

 22%|███████▋                           | 9389/42525 [17:20<1:11:46,  7.69it/s]

 22%|███████▋                           | 9392/42525 [17:20<1:02:43,  8.80it/s]

 22%|████████▏                            | 9394/42525 [17:20<58:48,  9.39it/s]

 22%|████████▏                            | 9396/42525 [17:21<58:06,  9.50it/s]

 22%|████████▏                            | 9400/42525 [17:21<56:12,  9.82it/s]

 22%|████████▏                            | 9403/42525 [17:21<56:09,  9.83it/s]

 22%|████████▏                            | 9407/42525 [17:22<57:42,  9.57it/s]

 22%|███████▋                           | 9409/42525 [17:22<1:01:46,  8.94it/s]

 22%|████████▏                            | 9412/42525 [17:22<59:29,  9.28it/s]

 22%|████████▏                            | 9415/42525 [17:23<58:57,  9.36it/s]

 22%|███████▊                           | 9417/42525 [17:23<1:01:08,  9.03it/s]

 22%|████████▏                            | 9420/42525 [17:23<58:18,  9.46it/s]

 22%|███████▊                           | 9423/42525 [17:23<1:01:06,  9.03it/s]

 22%|███████▊                           | 9426/42525 [17:24<1:03:50,  8.64it/s]

 22%|███████▊                           | 9427/42525 [17:24<1:06:04,  8.35it/s]

 22%|███████▊                           | 9430/42525 [17:24<1:07:23,  8.18it/s]

 22%|███████▊                           | 9432/42525 [17:25<1:04:28,  8.55it/s]

 22%|███████▊                           | 9434/42525 [17:25<1:12:52,  7.57it/s]

 22%|███████▊                           | 9435/42525 [17:25<1:10:24,  7.83it/s]

 22%|███████▊                           | 9438/42525 [17:25<1:07:27,  8.18it/s]

 22%|███████▊                           | 9441/42525 [17:26<1:04:48,  8.51it/s]

 22%|███████▊                           | 9443/42525 [17:26<1:07:42,  8.14it/s]

 22%|███████▊                           | 9446/42525 [17:26<1:01:02,  9.03it/s]

 22%|███████▊                           | 9449/42525 [17:27<1:01:07,  9.02it/s]

 22%|████████▏                            | 9453/42525 [17:27<56:40,  9.73it/s]

 22%|████████▏                            | 9456/42525 [17:27<58:26,  9.43it/s]

 22%|████████▏                            | 9458/42525 [17:27<57:00,  9.67it/s]

 22%|████████▏                            | 9462/42525 [17:28<56:05,  9.82it/s]

 22%|████████▏                            | 9466/42525 [17:28<54:24, 10.13it/s]

 22%|████████▏                            | 9470/42525 [17:29<54:15, 10.15it/s]

 22%|████████▏                            | 9473/42525 [17:29<59:15,  9.30it/s]

 22%|████████▏                            | 9476/42525 [17:29<57:30,  9.58it/s]

 22%|███████▊                           | 9478/42525 [17:30<1:02:42,  8.78it/s]

 22%|███████▊                           | 9480/42525 [17:30<1:02:17,  8.84it/s]

 22%|████████▎                            | 9482/42525 [17:30<58:42,  9.38it/s]

 22%|████████▎                            | 9485/42525 [17:30<58:00,  9.49it/s]

 22%|███████▊                           | 9486/42525 [17:30<1:03:26,  8.68it/s]

 22%|████████▎                            | 9490/42525 [17:31<58:27,  9.42it/s]

 22%|███████▊                           | 9492/42525 [17:31<1:07:39,  8.14it/s]

 22%|███████▊                           | 9494/42525 [17:31<1:03:14,  8.70it/s]

 22%|███████▊                           | 9496/42525 [17:32<1:08:02,  8.09it/s]

 22%|███████▊                           | 9499/42525 [17:32<1:00:30,  9.10it/s]

 22%|████████▎                            | 9503/42525 [17:32<59:50,  9.20it/s]

 22%|████████▎                            | 9506/42525 [17:33<57:11,  9.62it/s]

 22%|████████▎                            | 9510/42525 [17:33<55:44,  9.87it/s]

 22%|████████▎                            | 9512/42525 [17:33<56:12,  9.79it/s]

 22%|████████▎                            | 9514/42525 [17:33<57:01,  9.65it/s]

 22%|███████▊                           | 9517/42525 [17:34<1:01:46,  8.91it/s]

 22%|███████▊                           | 9519/42525 [17:34<1:02:43,  8.77it/s]

 22%|███████▊                           | 9521/42525 [17:34<1:03:26,  8.67it/s]

 22%|████████▎                            | 9524/42525 [17:35<58:00,  9.48it/s]

 22%|████████▎                            | 9527/42525 [17:35<58:41,  9.37it/s]

 22%|███████▊                           | 9529/42525 [17:35<1:02:45,  8.76it/s]

 22%|███████▊                           | 9531/42525 [17:35<1:05:50,  8.35it/s]

 22%|████████▎                            | 9535/42525 [17:36<57:44,  9.52it/s]

 22%|███████▊                           | 9538/42525 [17:36<1:01:16,  8.97it/s]

 22%|███████▊                           | 9540/42525 [17:36<1:05:23,  8.41it/s]

 22%|███████▊                           | 9543/42525 [17:37<1:00:20,  9.11it/s]

 22%|████████▎                            | 9546/42525 [17:37<57:24,  9.57it/s]

 22%|███████▊                           | 9548/42525 [17:37<1:00:59,  9.01it/s]

 22%|███████▊                           | 9551/42525 [17:38<1:02:53,  8.74it/s]

 22%|███████▊                           | 9553/42525 [17:38<1:06:39,  8.24it/s]

 22%|███████▊                           | 9556/42525 [17:38<1:01:03,  9.00it/s]

 22%|████████▎                            | 9559/42525 [17:38<59:35,  9.22it/s]

 22%|███████▊                           | 9560/42525 [17:39<1:04:19,  8.54it/s]

 22%|████████▎                            | 9564/42525 [17:39<58:23,  9.41it/s]

 22%|████████▎                            | 9565/42525 [17:39<59:49,  9.18it/s]

 23%|████████▎                            | 9569/42525 [17:40<56:39,  9.69it/s]

 23%|████████▎                            | 9571/42525 [17:40<55:45,  9.85it/s]

 23%|████████▎                            | 9575/42525 [17:40<56:01,  9.80it/s]

 23%|███████▉                           | 9577/42525 [17:40<1:01:38,  8.91it/s]

 23%|███████▉                           | 9580/42525 [17:41<1:04:27,  8.52it/s]

 23%|████████▎                            | 9584/42525 [17:41<57:39,  9.52it/s]

 23%|███████▉                           | 9587/42525 [17:42<1:01:27,  8.93it/s]

 23%|████████▎                            | 9591/42525 [17:42<58:39,  9.36it/s]

 23%|████████▎                            | 9593/42525 [17:42<58:34,  9.37it/s]

 23%|████████▎                            | 9595/42525 [17:42<57:35,  9.53it/s]

 23%|███████▉                           | 9597/42525 [17:43<1:07:12,  8.17it/s]

 23%|███████▉                           | 9599/42525 [17:43<1:08:58,  7.96it/s]

 23%|███████▉                           | 9601/42525 [17:43<1:08:12,  8.04it/s]

 23%|███████▉                           | 9604/42525 [17:43<1:00:08,  9.12it/s]

 23%|███████▉                           | 9606/42525 [17:44<1:05:35,  8.36it/s]

 23%|████████▎                            | 9609/42525 [17:44<58:59,  9.30it/s]

 23%|███████▉                           | 9611/42525 [17:44<1:08:48,  7.97it/s]

 23%|███████▉                           | 9613/42525 [17:45<1:10:42,  7.76it/s]

 23%|███████▉                           | 9615/42525 [17:45<1:08:32,  8.00it/s]

 23%|████████▎                            | 9619/42525 [17:45<59:00,  9.29it/s]

 23%|███████▉                           | 9621/42525 [17:45<1:00:30,  9.06it/s]

 23%|███████▉                           | 9623/42525 [17:46<1:02:44,  8.74it/s]

 23%|███████▉                           | 9626/42525 [17:46<1:00:51,  9.01it/s]

 23%|████████▍                            | 9629/42525 [17:46<57:56,  9.46it/s]

 23%|████████▍                            | 9632/42525 [17:47<59:31,  9.21it/s]

 23%|███████▉                           | 9634/42525 [17:47<1:03:56,  8.57it/s]

 23%|████████▍                            | 9638/42525 [17:47<57:41,  9.50it/s]

 23%|███████▉                           | 9640/42525 [17:48<1:00:41,  9.03it/s]

 23%|████████▍                            | 9643/42525 [17:48<58:58,  9.29it/s]

 23%|███████▉                           | 9645/42525 [17:48<1:02:06,  8.82it/s]

 23%|████████▍                            | 9648/42525 [17:48<57:25,  9.54it/s]

 23%|████████▍                            | 9651/42525 [17:49<55:56,  9.79it/s]

 23%|████████▍                            | 9653/42525 [17:49<58:48,  9.32it/s]

 23%|███████▉                           | 9656/42525 [17:49<1:00:16,  9.09it/s]

 23%|████████▍                            | 9657/42525 [17:49<59:59,  9.13it/s]

 23%|███████▉                           | 9660/42525 [17:50<1:02:41,  8.74it/s]

 23%|███████▉                           | 9662/42525 [17:50<1:00:43,  9.02it/s]

 23%|████████▍                            | 9665/42525 [17:50<57:09,  9.58it/s]

 23%|████████▍                            | 9668/42525 [17:51<59:14,  9.24it/s]

 23%|███████▉                           | 9670/42525 [17:51<1:01:23,  8.92it/s]

 23%|███████▉                           | 9672/42525 [17:51<1:02:40,  8.74it/s]

 23%|███████▉                           | 9675/42525 [17:51<1:06:47,  8.20it/s]

 23%|███████▉                           | 9678/42525 [17:52<1:02:07,  8.81it/s]

 23%|███████▉                           | 9680/42525 [17:52<1:05:55,  8.30it/s]

 23%|███████▉                           | 9683/42525 [17:52<1:07:49,  8.07it/s]

 23%|███████▉                           | 9686/42525 [17:53<1:03:25,  8.63it/s]

 23%|███████▉                           | 9689/42525 [17:53<1:00:07,  9.10it/s]

 23%|████████▍                            | 9692/42525 [17:53<58:11,  9.40it/s]

 23%|███████▉                           | 9695/42525 [17:54<1:02:00,  8.82it/s]

 23%|████████▍                            | 9698/42525 [17:54<57:54,  9.45it/s]

 23%|████████▍                            | 9702/42525 [17:54<56:45,  9.64it/s]

 23%|███████▉                           | 9705/42525 [17:55<1:00:21,  9.06it/s]

 23%|███████▉                           | 9708/42525 [17:55<1:03:19,  8.64it/s]

 23%|███████▉                           | 9711/42525 [17:55<1:02:25,  8.76it/s]

 23%|███████▉                           | 9713/42525 [17:56<1:03:02,  8.67it/s]

 23%|███████▉                           | 9716/42525 [17:56<1:04:15,  8.51it/s]

 23%|███████▉                           | 9718/42525 [17:56<1:06:52,  8.18it/s]

 23%|████████                           | 9720/42525 [17:57<1:09:37,  7.85it/s]

 23%|████████                           | 9724/42525 [17:57<1:00:06,  9.10it/s]

 23%|████████▍                            | 9728/42525 [17:57<57:57,  9.43it/s]

 23%|████████                           | 9731/42525 [17:58<1:01:17,  8.92it/s]

 23%|████████▍                            | 9734/42525 [17:58<59:07,  9.24it/s]

 23%|████████                           | 9737/42525 [17:58<1:00:01,  9.10it/s]

 23%|████████                           | 9740/42525 [17:59<1:02:09,  8.79it/s]

 23%|████████                           | 9742/42525 [17:59<1:09:27,  7.87it/s]

 23%|████████                           | 9745/42525 [17:59<1:04:24,  8.48it/s]

 23%|████████                           | 9748/42525 [18:00<1:04:59,  8.41it/s]

 23%|████████▍                            | 9751/42525 [18:00<59:00,  9.26it/s]

 23%|████████▍                            | 9753/42525 [18:00<57:14,  9.54it/s]

 23%|████████▍                            | 9757/42525 [18:01<58:19,  9.36it/s]

 23%|████████                           | 9760/42525 [18:01<1:01:52,  8.83it/s]

 23%|████████                           | 9762/42525 [18:01<1:02:31,  8.73it/s]

 23%|████████                           | 9764/42525 [18:02<1:11:01,  7.69it/s]

 23%|████████                           | 9766/42525 [18:02<1:09:26,  7.86it/s]

 23%|████████                           | 9769/42525 [18:02<1:05:10,  8.38it/s]

 23%|████████                           | 9773/42525 [18:03<1:01:25,  8.89it/s]

 23%|████████                           | 9775/42525 [18:03<1:04:54,  8.41it/s]

 23%|████████▌                            | 9778/42525 [18:03<59:10,  9.22it/s]

 23%|████████▌                            | 9781/42525 [18:03<56:53,  9.59it/s]

 23%|████████                           | 9783/42525 [18:04<1:02:12,  8.77it/s]

 23%|████████▌                            | 9786/42525 [18:04<57:57,  9.42it/s]

 23%|████████                           | 9788/42525 [18:04<1:03:12,  8.63it/s]

 23%|████████▌                            | 9792/42525 [18:05<56:57,  9.58it/s]

 23%|████████▌                            | 9794/42525 [18:05<58:20,  9.35it/s]

 23%|████████▌                            | 9796/42525 [18:05<58:46,  9.28it/s]

 23%|████████▌                            | 9798/42525 [18:05<58:54,  9.26it/s]

 23%|████████▌                            | 9802/42525 [18:06<55:01,  9.91it/s]

 23%|████████▌                            | 9805/42525 [18:06<54:41,  9.97it/s]

 23%|████████▌                            | 9807/42525 [18:06<59:42,  9.13it/s]

 23%|████████                           | 9809/42525 [18:06<1:04:50,  8.41it/s]

 23%|████████▌                            | 9813/42525 [18:07<57:22,  9.50it/s]

 23%|████████▌                            | 9816/42525 [18:07<56:06,  9.72it/s]

 23%|████████▌                            | 9817/42525 [18:07<55:46,  9.77it/s]

 23%|████████                           | 9820/42525 [18:08<1:00:36,  8.99it/s]

 23%|████████▌                            | 9823/42525 [18:08<57:23,  9.50it/s]

 23%|████████▌                            | 9825/42525 [18:08<58:28,  9.32it/s]

 23%|████████                           | 9827/42525 [18:08<1:01:32,  8.85it/s]

 23%|████████                           | 9830/42525 [18:09<1:02:27,  8.72it/s]

 23%|████████                           | 9832/42525 [18:09<1:08:39,  7.94it/s]

 23%|████████                           | 9833/42525 [18:09<1:09:34,  7.83it/s]

 23%|████████                           | 9835/42525 [18:09<1:08:43,  7.93it/s]

 23%|████████                           | 9838/42525 [18:10<1:07:20,  8.09it/s]

 23%|████████▌                            | 9842/42525 [18:10<58:56,  9.24it/s]

 23%|████████▌                            | 9845/42525 [18:10<58:09,  9.37it/s]

 23%|████████                           | 9847/42525 [18:11<1:02:50,  8.67it/s]

 23%|████████▌                            | 9851/42525 [18:11<59:47,  9.11it/s]

 23%|████████                           | 9854/42525 [18:11<1:04:25,  8.45it/s]

 23%|████████                           | 9856/42525 [18:12<1:11:19,  7.63it/s]

 23%|████████                           | 9859/42525 [18:12<1:03:35,  8.56it/s]

 23%|████████                           | 9862/42525 [18:12<1:01:30,  8.85it/s]

 23%|████████                           | 9864/42525 [18:13<1:09:22,  7.85it/s]

 23%|████████▌                            | 9868/42525 [18:13<58:59,  9.23it/s]

 23%|████████                           | 9870/42525 [18:13<1:02:40,  8.68it/s]

 23%|████████▏                          | 9872/42525 [18:14<1:00:52,  8.94it/s]

 23%|████████▌                            | 9875/42525 [18:14<56:59,  9.55it/s]

 23%|████████▏                          | 9877/42525 [18:14<1:00:48,  8.95it/s]

 23%|████████▌                            | 9880/42525 [18:14<58:57,  9.23it/s]

 23%|████████▌                            | 9884/42525 [18:15<55:46,  9.75it/s]

 23%|████████▌                            | 9886/42525 [18:15<57:59,  9.38it/s]

 23%|████████▏                          | 9889/42525 [18:15<1:01:26,  8.85it/s]

 23%|████████▏                          | 9891/42525 [18:16<1:02:40,  8.68it/s]

 23%|████████▏                          | 9893/42525 [18:16<1:02:44,  8.67it/s]

 23%|████████▏                          | 9896/42525 [18:16<1:03:44,  8.53it/s]

 23%|████████▏                          | 9898/42525 [18:16<1:02:34,  8.69it/s]

 23%|████████▏                          | 9900/42525 [18:17<1:05:11,  8.34it/s]

 23%|████████▏                          | 9903/42525 [18:17<1:03:54,  8.51it/s]

 23%|████████▏                          | 9906/42525 [18:17<1:01:36,  8.82it/s]

 23%|████████▌                            | 9910/42525 [18:18<56:45,  9.58it/s]

 23%|████████▌                            | 9912/42525 [18:18<55:38,  9.77it/s]

 23%|████████▋                            | 9915/42525 [18:18<56:06,  9.69it/s]

 23%|████████▋                            | 9917/42525 [18:19<59:57,  9.07it/s]

 23%|████████▏                          | 9919/42525 [18:19<1:02:13,  8.73it/s]

 23%|████████▏                          | 9921/42525 [18:19<1:07:33,  8.04it/s]

 23%|████████▏                          | 9923/42525 [18:19<1:13:05,  7.43it/s]

 23%|████████▏                          | 9925/42525 [18:20<1:16:33,  7.10it/s]

 23%|████████▏                          | 9927/42525 [18:20<1:12:45,  7.47it/s]

 23%|████████▏                          | 9930/42525 [18:20<1:04:13,  8.46it/s]

 23%|████████▋                            | 9934/42525 [18:21<57:31,  9.44it/s]

 23%|████████▋                            | 9936/42525 [18:21<59:51,  9.08it/s]

 23%|████████▋                            | 9939/42525 [18:21<59:50,  9.08it/s]

 23%|████████▋                            | 9942/42525 [18:21<56:43,  9.57it/s]

 23%|████████▋                            | 9945/42525 [18:22<58:46,  9.24it/s]

 23%|████████▋                            | 9949/42525 [18:22<59:00,  9.20it/s]

 23%|████████▋                            | 9952/42525 [18:23<57:18,  9.47it/s]

 23%|████████▋                            | 9956/42525 [18:23<55:17,  9.82it/s]

 23%|████████▋                            | 9958/42525 [18:23<55:59,  9.69it/s]

 23%|████████▏                          | 9960/42525 [18:23<1:03:21,  8.57it/s]

 23%|████████▏                          | 9962/42525 [18:24<1:06:44,  8.13it/s]

 23%|████████▏                          | 9965/42525 [18:24<1:02:59,  8.62it/s]

 23%|████████▋                            | 9968/42525 [18:24<58:11,  9.32it/s]

 23%|████████▋                            | 9971/42525 [18:25<58:20,  9.30it/s]

 23%|████████▋                            | 9973/42525 [18:25<59:16,  9.15it/s]

 23%|████████▋                            | 9975/42525 [18:25<57:00,  9.52it/s]

 23%|████████▋                            | 9979/42525 [18:26<56:32,  9.59it/s]

 23%|████████▏                          | 9980/42525 [18:26<1:01:11,  8.86it/s]

 23%|████████▏                          | 9983/42525 [18:26<1:02:47,  8.64it/s]

 23%|████████▏                          | 9984/42525 [18:26<1:05:43,  8.25it/s]

 23%|████████▏                          | 9987/42525 [18:26<1:02:52,  8.62it/s]

 23%|████████▋                            | 9990/42525 [18:27<58:55,  9.20it/s]

 23%|████████▏                          | 9992/42525 [18:27<1:02:55,  8.62it/s]

 24%|████████▏                          | 9994/42525 [18:27<1:02:34,  8.67it/s]

 24%|████████▋                            | 9997/42525 [18:28<57:47,  9.38it/s]

 24%|████████▍                           | 10000/42525 [18:28<57:20,  9.45it/s]

 24%|████████▍                           | 10003/42525 [18:28<56:09,  9.65it/s]

 24%|████████▍                           | 10005/42525 [18:28<58:37,  9.25it/s]

 24%|████████▍                           | 10007/42525 [18:29<59:47,  9.06it/s]

 24%|████████                          | 10008/42525 [18:29<1:05:26,  8.28it/s]

 24%|████████                          | 10011/42525 [18:29<1:07:06,  8.08it/s]

 24%|████████                          | 10013/42525 [18:29<1:02:07,  8.72it/s]

 24%|████████▍                           | 10017/42525 [18:30<56:08,  9.65it/s]

 24%|████████▍                           | 10021/42525 [18:30<54:20,  9.97it/s]

 24%|████████▍                           | 10022/42525 [18:30<59:24,  9.12it/s]

 24%|████████▍                           | 10026/42525 [18:31<57:09,  9.48it/s]

 24%|████████▍                           | 10030/42525 [18:31<54:33,  9.93it/s]

 24%|████████▍                           | 10033/42525 [18:31<55:18,  9.79it/s]

 24%|████████▍                           | 10035/42525 [18:32<54:14,  9.98it/s]

 24%|████████▍                           | 10039/42525 [18:32<54:16,  9.98it/s]

 24%|████████                          | 10042/42525 [18:32<1:00:21,  8.97it/s]

 24%|████████▌                           | 10045/42525 [18:33<57:13,  9.46it/s]

 24%|████████                          | 10047/42525 [18:33<1:06:42,  8.12it/s]

 24%|████████                          | 10050/42525 [18:33<1:01:35,  8.79it/s]

 24%|████████                          | 10053/42525 [18:34<1:04:25,  8.40it/s]

 24%|████████▌                           | 10057/42525 [18:34<58:06,  9.31it/s]

 24%|████████                          | 10060/42525 [18:34<1:04:48,  8.35it/s]

 24%|████████                          | 10062/42525 [18:35<1:02:55,  8.60it/s]

 24%|████████                          | 10064/42525 [18:35<1:01:35,  8.78it/s]

 24%|████████                          | 10065/42525 [18:35<1:02:51,  8.61it/s]

 24%|████████                          | 10068/42525 [18:35<1:02:21,  8.68it/s]

 24%|████████                          | 10070/42525 [18:36<1:07:17,  8.04it/s]

 24%|████████                          | 10072/42525 [18:36<1:01:19,  8.82it/s]

 24%|████████                          | 10075/42525 [18:36<1:01:54,  8.74it/s]

 24%|████████                          | 10077/42525 [18:36<1:03:51,  8.47it/s]

 24%|████████                          | 10080/42525 [18:37<1:03:12,  8.55it/s]

 24%|████████▌                           | 10083/42525 [18:37<58:11,  9.29it/s]

 24%|████████▌                           | 10087/42525 [18:38<55:23,  9.76it/s]

 24%|████████▌                           | 10089/42525 [18:38<59:53,  9.03it/s]

 24%|████████▌                           | 10091/42525 [18:38<58:11,  9.29it/s]

 24%|████████▌                           | 10094/42525 [18:38<58:22,  9.26it/s]

 24%|████████                          | 10097/42525 [18:39<1:01:14,  8.83it/s]

 24%|████████▌                           | 10101/42525 [18:39<57:21,  9.42it/s]

 24%|████████                          | 10103/42525 [18:39<1:01:48,  8.74it/s]

 24%|████████▌                           | 10105/42525 [18:40<58:03,  9.31it/s]

 24%|████████                          | 10108/42525 [18:40<1:05:28,  8.25it/s]

 24%|████████                          | 10110/42525 [18:40<1:09:27,  7.78it/s]

 24%|████████                          | 10113/42525 [18:41<1:01:42,  8.75it/s]

 24%|████████                          | 10115/42525 [18:41<1:06:40,  8.10it/s]

 24%|████████                          | 10117/42525 [18:41<1:03:47,  8.47it/s]

 24%|████████                          | 10120/42525 [18:41<1:04:11,  8.41it/s]

 24%|████████▌                           | 10123/42525 [18:42<59:11,  9.12it/s]

 24%|████████▌                           | 10124/42525 [18:42<57:59,  9.31it/s]

 24%|████████                          | 10127/42525 [18:42<1:02:26,  8.65it/s]

 24%|████████                          | 10129/42525 [18:42<1:00:42,  8.89it/s]

 24%|████████▌                           | 10133/42525 [18:43<55:09,  9.79it/s]

 24%|████████▌                           | 10136/42525 [18:43<59:30,  9.07it/s]

 24%|████████▌                           | 10138/42525 [18:43<58:02,  9.30it/s]

 24%|████████                          | 10141/42525 [18:44<1:00:59,  8.85it/s]

 24%|████████▌                           | 10144/42525 [18:44<56:49,  9.50it/s]

 24%|████████                          | 10146/42525 [18:44<1:06:00,  8.17it/s]

 24%|████████                          | 10149/42525 [18:45<1:02:30,  8.63it/s]

 24%|████████                          | 10150/42525 [18:45<1:02:45,  8.60it/s]

 24%|████████                          | 10153/42525 [18:45<1:04:58,  8.30it/s]

 24%|████████                          | 10155/42525 [18:45<1:02:48,  8.59it/s]

 24%|████████                          | 10158/42525 [18:46<1:03:45,  8.46it/s]

 24%|████████                          | 10160/42525 [18:46<1:02:16,  8.66it/s]

 24%|████████                          | 10161/42525 [18:46<1:00:18,  8.94it/s]

 24%|████████▌                           | 10164/42525 [18:46<58:41,  9.19it/s]

 24%|████████▌                           | 10167/42525 [18:47<56:31,  9.54it/s]

 24%|████████▏                         | 10170/42525 [18:47<1:00:34,  8.90it/s]

 24%|████████▏                         | 10171/42525 [18:47<1:00:43,  8.88it/s]

 24%|████████▏                         | 10174/42525 [18:47<1:00:29,  8.91it/s]

 24%|████████▌                           | 10176/42525 [18:48<58:24,  9.23it/s]

 24%|████████▌                           | 10177/42525 [18:48<57:39,  9.35it/s]

 24%|████████▌                           | 10181/42525 [18:48<55:52,  9.65it/s]

 24%|████████▌                           | 10184/42525 [18:48<54:36,  9.87it/s]

 24%|████████▌                           | 10186/42525 [18:49<57:28,  9.38it/s]

 24%|████████▌                           | 10188/42525 [18:49<56:39,  9.51it/s]

 24%|████████▋                           | 10191/42525 [18:49<57:39,  9.35it/s]

 24%|████████▋                           | 10192/42525 [18:49<59:21,  9.08it/s]

 24%|████████▏                         | 10195/42525 [18:50<1:04:38,  8.34it/s]

 24%|████████▏                         | 10197/42525 [18:50<1:01:10,  8.81it/s]

 24%|████████▋                           | 10201/42525 [18:50<59:06,  9.11it/s]

 24%|████████▏                         | 10203/42525 [18:51<1:04:38,  8.33it/s]

 24%|████████▏                         | 10205/42525 [18:51<1:03:12,  8.52it/s]

 24%|████████▋                           | 10207/42525 [18:51<58:38,  9.19it/s]

 24%|████████▏                         | 10210/42525 [18:51<1:04:51,  8.30it/s]

 24%|████████▏                         | 10211/42525 [18:51<1:03:19,  8.50it/s]

 24%|████████▏                         | 10214/42525 [18:52<1:02:56,  8.56it/s]

 24%|████████▋                           | 10218/42525 [18:52<57:35,  9.35it/s]

 24%|████████▋                           | 10221/42525 [18:53<57:57,  9.29it/s]

 24%|████████▋                           | 10224/42525 [18:53<57:02,  9.44it/s]

 24%|████████▋                           | 10228/42525 [18:53<54:26,  9.89it/s]

 24%|████████▋                           | 10229/42525 [18:53<59:24,  9.06it/s]

 24%|████████▏                         | 10232/42525 [18:54<1:01:59,  8.68it/s]

 24%|████████▋                           | 10234/42525 [18:54<58:39,  9.17it/s]

 24%|████████▋                           | 10238/42525 [18:54<55:56,  9.62it/s]

 24%|████████▋                           | 10239/42525 [18:54<57:32,  9.35it/s]

 24%|████████▋                           | 10241/42525 [18:55<59:48,  9.00it/s]

 24%|████████▏                         | 10243/42525 [18:55<1:01:55,  8.69it/s]

 24%|████████▋                           | 10245/42525 [18:55<59:52,  8.99it/s]

 24%|████████▏                         | 10248/42525 [18:56<1:02:25,  8.62it/s]

 24%|████████▏                         | 10252/42525 [18:56<1:00:08,  8.94it/s]

 24%|████████▏                         | 10254/42525 [18:56<1:01:37,  8.73it/s]

 24%|████████▏                         | 10256/42525 [18:56<1:04:47,  8.30it/s]

 24%|████████▏                         | 10258/42525 [18:57<1:06:54,  8.04it/s]

 24%|████████▏                         | 10261/42525 [18:57<1:00:32,  8.88it/s]

 24%|████████▋                           | 10263/42525 [18:57<59:32,  9.03it/s]

 24%|████████▋                           | 10267/42525 [18:58<54:50,  9.80it/s]

 24%|████████▏                         | 10269/42525 [18:58<1:03:52,  8.42it/s]

 24%|████████▏                         | 10271/42525 [18:58<1:04:14,  8.37it/s]

 24%|████████▏                         | 10274/42525 [18:59<1:04:32,  8.33it/s]

 24%|████████▏                         | 10277/42525 [18:59<1:01:18,  8.77it/s]

 24%|████████▋                           | 10280/42525 [18:59<59:36,  9.01it/s]

 24%|████████▋                           | 10283/42525 [18:59<57:16,  9.38it/s]

 24%|████████▏                         | 10286/42525 [19:00<1:00:01,  8.95it/s]

 24%|████████▋                           | 10289/42525 [19:00<57:23,  9.36it/s]

 24%|████████▋                           | 10291/42525 [19:00<58:25,  9.20it/s]

 24%|████████▋                           | 10293/42525 [19:01<58:35,  9.17it/s]

 24%|████████▋                           | 10297/42525 [19:01<58:29,  9.18it/s]

 24%|████████▋                           | 10300/42525 [19:01<56:21,  9.53it/s]

 24%|████████▋                           | 10303/42525 [19:02<56:23,  9.52it/s]

 24%|████████▋                           | 10305/42525 [19:02<54:45,  9.81it/s]

 24%|████████▋                           | 10308/42525 [19:02<57:36,  9.32it/s]

 24%|████████▏                         | 10310/42525 [19:02<1:01:24,  8.74it/s]

 24%|████████▋                           | 10314/42525 [19:03<56:17,  9.54it/s]

 24%|████████▋                           | 10317/42525 [19:03<56:00,  9.58it/s]

 24%|████████▋                           | 10321/42525 [19:04<53:41, 10.00it/s]

 24%|████████▋                           | 10323/42525 [19:04<59:18,  9.05it/s]

 24%|████████▋                           | 10324/42525 [19:04<58:06,  9.24it/s]

 24%|████████▎                         | 10327/42525 [19:04<1:02:37,  8.57it/s]

 24%|████████▎                         | 10329/42525 [19:04<1:05:59,  8.13it/s]

 24%|████████▎                         | 10331/42525 [19:05<1:00:29,  8.87it/s]

 24%|████████▎                         | 10334/42525 [19:05<1:06:24,  8.08it/s]

 24%|████████▎                         | 10335/42525 [19:05<1:06:16,  8.10it/s]

 24%|████████▎                         | 10339/42525 [19:06<1:01:00,  8.79it/s]

 24%|████████▊                           | 10341/42525 [19:06<58:19,  9.20it/s]

 24%|████████▊                           | 10345/42525 [19:06<58:03,  9.24it/s]

 24%|████████▊                           | 10347/42525 [19:06<56:08,  9.55it/s]

 24%|████████▊                           | 10350/42525 [19:07<58:29,  9.17it/s]

 24%|████████▎                         | 10352/42525 [19:07<1:02:31,  8.57it/s]

 24%|████████▊                           | 10356/42525 [19:07<57:02,  9.40it/s]

 24%|████████▊                           | 10360/42525 [19:08<54:19,  9.87it/s]

 24%|████████▊                           | 10362/42525 [19:08<55:33,  9.65it/s]

 24%|████████▊                           | 10365/42525 [19:08<55:12,  9.71it/s]

 24%|████████▊                           | 10367/42525 [19:09<58:10,  9.21it/s]

 24%|████████▊                           | 10370/42525 [19:09<58:42,  9.13it/s]

 24%|████████▊                           | 10373/42525 [19:09<56:30,  9.48it/s]

 24%|████████▊                           | 10376/42525 [19:10<54:25,  9.85it/s]

 24%|████████▊                           | 10378/42525 [19:10<57:31,  9.31it/s]

 24%|████████▎                         | 10380/42525 [19:10<1:00:29,  8.86it/s]

 24%|████████▎                         | 10382/42525 [19:10<1:08:47,  7.79it/s]

 24%|████████▎                         | 10384/42525 [19:11<1:13:53,  7.25it/s]

 24%|████████▎                         | 10386/42525 [19:11<1:03:55,  8.38it/s]

 24%|████████▎                         | 10388/42525 [19:11<1:00:42,  8.82it/s]

 24%|████████▊                           | 10392/42525 [19:11<56:35,  9.46it/s]

 24%|████████▊                           | 10394/42525 [19:12<55:06,  9.72it/s]

 24%|████████▊                           | 10397/42525 [19:12<54:57,  9.74it/s]

 24%|████████▊                           | 10400/42525 [19:12<55:29,  9.65it/s]

 24%|████████▊                           | 10403/42525 [19:13<58:39,  9.13it/s]

 24%|████████▊                           | 10407/42525 [19:13<55:06,  9.71it/s]

 24%|████████▊                           | 10408/42525 [19:13<55:05,  9.72it/s]

 24%|████████▊                           | 10410/42525 [19:13<57:45,  9.27it/s]

 24%|████████▊                           | 10414/42525 [19:14<55:07,  9.71it/s]

 24%|████████▊                           | 10416/42525 [19:14<54:58,  9.73it/s]

 25%|████████▊                           | 10419/42525 [19:14<57:14,  9.35it/s]

 25%|████████▊                           | 10423/42525 [19:15<54:57,  9.74it/s]

 25%|████████▊                           | 10424/42525 [19:15<56:18,  9.50it/s]

 25%|████████▊                           | 10427/42525 [19:15<58:15,  9.18it/s]

 25%|████████▊                           | 10430/42525 [19:15<58:30,  9.14it/s]

 25%|████████▊                           | 10434/42525 [19:16<56:31,  9.46it/s]

 25%|████████▎                         | 10436/42525 [19:16<1:02:03,  8.62it/s]

 25%|████████▎                         | 10438/42525 [19:16<1:03:20,  8.44it/s]

 25%|████████▎                         | 10441/42525 [19:17<1:05:15,  8.19it/s]

 25%|████████▎                         | 10443/42525 [19:17<1:00:16,  8.87it/s]

 25%|████████▊                           | 10447/42525 [19:17<56:51,  9.40it/s]

 25%|████████▎                         | 10450/42525 [19:18<1:04:01,  8.35it/s]

 25%|████████▎                         | 10452/42525 [19:18<1:10:26,  7.59it/s]

 25%|████████▎                         | 10454/42525 [19:18<1:10:19,  7.60it/s]

 25%|████████▎                         | 10455/42525 [19:18<1:08:15,  7.83it/s]

 25%|████████▎                         | 10457/42525 [19:19<1:07:16,  7.94it/s]

 25%|████████▎                         | 10460/42525 [19:19<1:00:50,  8.78it/s]

 25%|████████▎                         | 10462/42525 [19:19<1:03:10,  8.46it/s]

 25%|████████▎                         | 10464/42525 [19:20<1:04:36,  8.27it/s]

 25%|████████▊                           | 10468/42525 [19:20<56:23,  9.47it/s]

 25%|████████▎                         | 10470/42525 [19:20<1:01:52,  8.63it/s]

 25%|████████▊                           | 10472/42525 [19:20<58:35,  9.12it/s]

 25%|████████▊                           | 10474/42525 [19:21<55:21,  9.65it/s]

 25%|████████▊                           | 10478/42525 [19:21<54:55,  9.72it/s]

 25%|████████▍                         | 10481/42525 [19:21<1:01:54,  8.63it/s]

 25%|████████▍                         | 10482/42525 [19:22<1:03:38,  8.39it/s]

 25%|████████▍                         | 10484/42525 [19:22<1:01:24,  8.70it/s]

 25%|████████▍                         | 10487/42525 [19:22<1:01:43,  8.65it/s]

 25%|████████▍                         | 10489/42525 [19:22<1:06:25,  8.04it/s]

 25%|████████▍                         | 10491/42525 [19:23<1:02:17,  8.57it/s]

 25%|████████▍                         | 10493/42525 [19:23<1:07:38,  7.89it/s]

 25%|████████▍                         | 10495/42525 [19:23<1:01:43,  8.65it/s]

 25%|████████▉                           | 10499/42525 [19:23<55:14,  9.66it/s]

 25%|████████▍                         | 10501/42525 [19:24<1:05:13,  8.18it/s]

 25%|████████▍                         | 10503/42525 [19:24<1:02:38,  8.52it/s]

 25%|████████▍                         | 10505/42525 [19:24<1:09:34,  7.67it/s]

 25%|████████▍                         | 10508/42525 [19:25<1:05:20,  8.17it/s]

 25%|████████▉                           | 10511/42525 [19:25<59:35,  8.95it/s]

 25%|████████▍                         | 10513/42525 [19:25<1:01:54,  8.62it/s]

 25%|████████▍                         | 10515/42525 [19:25<1:05:59,  8.08it/s]

 25%|████████▉                           | 10517/42525 [19:26<59:12,  9.01it/s]

 25%|████████▉                           | 10521/42525 [19:26<55:49,  9.55it/s]

 25%|████████▉                           | 10523/42525 [19:26<54:22,  9.81it/s]

 25%|████████▉                           | 10527/42525 [19:27<53:38,  9.94it/s]

 25%|████████▉                           | 10530/42525 [19:27<54:12,  9.84it/s]

 25%|████████▉                           | 10533/42525 [19:27<55:52,  9.54it/s]

 25%|████████▉                           | 10537/42525 [19:28<54:17,  9.82it/s]

 25%|████████▉                           | 10540/42525 [19:28<56:02,  9.51it/s]

 25%|████████▉                           | 10542/42525 [19:28<56:24,  9.45it/s]

 25%|████████▉                           | 10546/42525 [19:29<54:38,  9.75it/s]

 25%|████████▉                           | 10548/42525 [19:29<58:06,  9.17it/s]

 25%|████████▉                           | 10551/42525 [19:29<59:39,  8.93it/s]

 25%|████████▉                           | 10553/42525 [19:29<58:04,  9.17it/s]

 25%|████████▉                           | 10556/42525 [19:30<56:51,  9.37it/s]

 25%|████████▉                           | 10559/42525 [19:30<58:07,  9.17it/s]

 25%|████████▉                           | 10562/42525 [19:30<55:29,  9.60it/s]

 25%|████████▍                         | 10564/42525 [19:31<1:01:00,  8.73it/s]

 25%|████████▉                           | 10567/42525 [19:31<56:38,  9.40it/s]

 25%|████████▉                           | 10568/42525 [19:31<56:49,  9.37it/s]

 25%|████████▉                           | 10571/42525 [19:31<55:40,  9.57it/s]

 25%|████████▉                           | 10573/42525 [19:32<54:26,  9.78it/s]

 25%|████████▉                           | 10575/42525 [19:32<54:58,  9.69it/s]

 25%|████████▉                           | 10579/42525 [19:32<53:40,  9.92it/s]

 25%|████████▉                           | 10582/42525 [19:32<56:17,  9.46it/s]

 25%|████████▉                           | 10586/42525 [19:33<53:34,  9.94it/s]

 25%|████████▉                           | 10588/42525 [19:33<54:43,  9.73it/s]

 25%|████████▉                           | 10592/42525 [19:34<56:03,  9.49it/s]

 25%|████████▉                           | 10595/42525 [19:34<55:12,  9.64it/s]

 25%|████████▉                           | 10598/42525 [19:34<53:40,  9.91it/s]

 25%|████████▉                           | 10600/42525 [19:34<54:14,  9.81it/s]

 25%|████████▍                         | 10602/42525 [19:35<1:00:35,  8.78it/s]

 25%|████████▉                           | 10605/42525 [19:35<58:15,  9.13it/s]

 25%|████████▉                           | 10608/42525 [19:35<56:28,  9.42it/s]

 25%|████████▉                           | 10610/42525 [19:35<56:37,  9.39it/s]

 25%|████████▉                           | 10613/42525 [19:36<55:02,  9.66it/s]

 25%|████████▉                           | 10616/42525 [19:36<55:58,  9.50it/s]

 25%|████████▉                           | 10619/42525 [19:36<55:23,  9.60it/s]

 25%|████████▉                           | 10622/42525 [19:37<54:16,  9.80it/s]

 25%|████████▉                           | 10625/42525 [19:37<54:14,  9.80it/s]

 25%|████████▉                           | 10627/42525 [19:37<53:34,  9.92it/s]

 25%|████████▍                         | 10630/42525 [19:38<1:01:50,  8.59it/s]

 25%|████████▌                         | 10632/42525 [19:38<1:08:59,  7.70it/s]

 25%|████████▌                         | 10635/42525 [19:38<1:02:46,  8.47it/s]

 25%|█████████                           | 10638/42525 [19:39<58:25,  9.10it/s]

 25%|█████████                           | 10642/42525 [19:39<53:46,  9.88it/s]

 25%|█████████                           | 10645/42525 [19:39<54:50,  9.69it/s]

 25%|█████████                           | 10648/42525 [19:40<57:41,  9.21it/s]

 25%|█████████                           | 10651/42525 [19:40<55:09,  9.63it/s]

 25%|█████████                           | 10652/42525 [19:40<57:12,  9.29it/s]

 25%|████████▌                         | 10655/42525 [19:40<1:00:52,  8.73it/s]

 25%|████████▌                         | 10658/42525 [19:41<1:03:17,  8.39it/s]

 25%|█████████                           | 10661/42525 [19:41<58:37,  9.06it/s]

 25%|█████████                           | 10664/42525 [19:41<55:37,  9.55it/s]

 25%|█████████                           | 10667/42525 [19:42<53:25,  9.94it/s]

 25%|█████████                           | 10670/42525 [19:42<52:44, 10.07it/s]

 25%|████████▌                         | 10673/42525 [19:42<1:00:41,  8.75it/s]

 25%|████████▌                         | 10676/42525 [19:43<1:01:48,  8.59it/s]

 25%|█████████                           | 10679/42525 [19:43<59:59,  8.85it/s]

 25%|████████▌                         | 10682/42525 [19:43<1:05:11,  8.14it/s]

 25%|████████▌                         | 10684/42525 [19:44<1:00:11,  8.82it/s]

 25%|█████████                           | 10688/42525 [19:44<58:18,  9.10it/s]

 25%|█████████                           | 10692/42525 [19:44<55:51,  9.50it/s]

 25%|████████▌                         | 10694/42525 [19:45<1:01:04,  8.69it/s]

 25%|████████▌                         | 10697/42525 [19:45<1:02:09,  8.53it/s]

 25%|█████████                           | 10699/42525 [19:45<58:44,  9.03it/s]

 25%|████████▌                         | 10702/42525 [19:46<1:00:38,  8.75it/s]

 25%|█████████                           | 10705/42525 [19:46<58:57,  8.99it/s]

 25%|█████████                           | 10707/42525 [19:46<56:05,  9.45it/s]

 25%|█████████                           | 10711/42525 [19:46<53:59,  9.82it/s]

 25%|█████████                           | 10713/42525 [19:47<53:47,  9.86it/s]

 25%|█████████                           | 10715/42525 [19:47<55:50,  9.50it/s]

 25%|████████▌                         | 10718/42525 [19:47<1:01:46,  8.58it/s]

 25%|█████████                           | 10720/42525 [19:47<58:13,  9.10it/s]

 25%|████████▌                         | 10723/42525 [19:48<1:01:05,  8.68it/s]

 25%|█████████                           | 10724/42525 [19:48<59:29,  8.91it/s]

 25%|█████████                           | 10728/42525 [19:48<54:53,  9.65it/s]

 25%|█████████                           | 10729/42525 [19:48<55:16,  9.59it/s]

 25%|█████████                           | 10732/42525 [19:49<56:09,  9.44it/s]

 25%|█████████                           | 10734/42525 [19:49<55:01,  9.63it/s]

 25%|█████████                           | 10737/42525 [19:49<57:58,  9.14it/s]

 25%|█████████                           | 10740/42525 [19:50<57:31,  9.21it/s]

 25%|█████████                           | 10741/42525 [19:50<58:59,  8.98it/s]

 25%|████████▌                         | 10743/42525 [19:50<1:01:17,  8.64it/s]

 25%|█████████                           | 10745/42525 [19:50<59:00,  8.98it/s]

 25%|█████████                           | 10747/42525 [19:50<57:12,  9.26it/s]

 25%|█████████                           | 10749/42525 [19:51<56:22,  9.40it/s]

 25%|█████████                           | 10753/42525 [19:51<55:19,  9.57it/s]

 25%|█████████                           | 10755/42525 [19:51<54:15,  9.76it/s]

 25%|█████████                           | 10758/42525 [19:51<58:39,  9.03it/s]

 25%|█████████                           | 10760/42525 [19:52<59:52,  8.84it/s]

 25%|█████████                           | 10763/42525 [19:52<57:12,  9.25it/s]

 25%|████████▌                         | 10765/42525 [19:52<1:04:08,  8.25it/s]

 25%|████████▌                         | 10767/42525 [19:53<1:11:12,  7.43it/s]

 25%|████████▌                         | 10770/42525 [19:53<1:00:25,  8.76it/s]

 25%|█████████                           | 10773/42525 [19:53<57:22,  9.22it/s]

 25%|████████▌                         | 10776/42525 [19:54<1:00:15,  8.78it/s]

 25%|████████▌                         | 10779/42525 [19:54<1:05:23,  8.09it/s]

 25%|████████▌                         | 10782/42525 [19:54<1:03:58,  8.27it/s]

 25%|█████████▏                          | 10784/42525 [19:55<59:40,  8.87it/s]

 25%|█████████▏                          | 10788/42525 [19:55<54:41,  9.67it/s]

 25%|████████▋                         | 10790/42525 [19:55<1:00:45,  8.71it/s]

 25%|████████▋                         | 10791/42525 [19:55<1:05:10,  8.12it/s]

 25%|█████████▏                          | 10795/42525 [19:56<57:20,  9.22it/s]

 25%|████████▋                         | 10797/42525 [19:56<1:00:50,  8.69it/s]

 25%|█████████▏                          | 10800/42525 [19:56<59:43,  8.85it/s]

 25%|█████████▏                          | 10802/42525 [19:57<59:26,  8.89it/s]

 25%|████████▋                         | 10805/42525 [19:57<1:01:48,  8.55it/s]

 25%|████████▋                         | 10806/42525 [19:57<1:01:54,  8.54it/s]

 25%|█████████▏                          | 10809/42525 [19:57<58:21,  9.06it/s]

 25%|█████████▏                          | 10810/42525 [19:57<58:08,  9.09it/s]

 25%|█████████▏                          | 10813/42525 [19:58<57:20,  9.22it/s]

 25%|█████████▏                          | 10816/42525 [19:58<59:43,  8.85it/s]

 25%|████████▋                         | 10817/42525 [19:58<1:01:54,  8.54it/s]

 25%|████████▋                         | 10820/42525 [19:59<1:02:03,  8.51it/s]

 25%|█████████▏                          | 10823/42525 [19:59<57:34,  9.18it/s]

 25%|█████████▏                          | 10825/42525 [19:59<58:25,  9.04it/s]

 25%|████████▋                         | 10827/42525 [19:59<1:00:22,  8.75it/s]

 25%|████████▋                         | 10828/42525 [19:59<1:00:46,  8.69it/s]

 25%|████████▋                         | 10831/42525 [20:00<1:03:21,  8.34it/s]

 25%|████████▋                         | 10833/42525 [20:00<1:05:59,  8.00it/s]

 25%|████████▋                         | 10836/42525 [20:00<1:00:45,  8.69it/s]

 25%|█████████▏                          | 10837/42525 [20:01<58:54,  8.96it/s]

 25%|█████████▏                          | 10840/42525 [20:01<56:32,  9.34it/s]

 25%|█████████▏                          | 10842/42525 [20:01<54:00,  9.78it/s]

 26%|█████████▏                          | 10845/42525 [20:01<57:40,  9.15it/s]

 26%|█████████▏                          | 10846/42525 [20:02<58:35,  9.01it/s]

 26%|█████████▏                          | 10850/42525 [20:02<57:51,  9.12it/s]

 26%|█████████▏                          | 10852/42525 [20:02<57:04,  9.25it/s]

 26%|█████████▏                          | 10855/42525 [20:02<57:27,  9.19it/s]

 26%|█████████▏                          | 10859/42525 [20:03<57:32,  9.17it/s]

 26%|████████▋                         | 10862/42525 [20:03<1:00:43,  8.69it/s]

 26%|█████████▏                          | 10866/42525 [20:04<54:49,  9.62it/s]

 26%|█████████▏                          | 10868/42525 [20:04<55:58,  9.42it/s]

 26%|█████████▏                          | 10871/42525 [20:04<56:36,  9.32it/s]

 26%|█████████▏                          | 10873/42525 [20:04<56:24,  9.35it/s]

 26%|█████████▏                          | 10876/42525 [20:05<55:47,  9.45it/s]

 26%|█████████▏                          | 10879/42525 [20:05<53:53,  9.79it/s]

 26%|█████████▏                          | 10881/42525 [20:05<57:08,  9.23it/s]

 26%|████████▋                         | 10883/42525 [20:06<1:02:22,  8.45it/s]

 26%|█████████▏                          | 10886/42525 [20:06<57:02,  9.25it/s]

 26%|█████████▏                          | 10890/42525 [20:06<53:28,  9.86it/s]

 26%|█████████▏                          | 10892/42525 [20:06<58:52,  8.95it/s]

 26%|█████████▏                          | 10895/42525 [20:07<57:06,  9.23it/s]

 26%|█████████▏                          | 10897/42525 [20:07<58:30,  9.01it/s]

 26%|████████▋                         | 10899/42525 [20:07<1:02:51,  8.39it/s]

 26%|████████▋                         | 10901/42525 [20:08<1:02:28,  8.44it/s]

 26%|████████▋                         | 10904/42525 [20:08<1:04:56,  8.12it/s]

 26%|████████▋                         | 10907/42525 [20:08<1:01:02,  8.63it/s]

 26%|█████████▏                          | 10911/42525 [20:09<55:15,  9.54it/s]

 26%|████████▋                         | 10914/42525 [20:09<1:01:46,  8.53it/s]

 26%|████████▋                         | 10916/42525 [20:09<1:04:10,  8.21it/s]

 26%|█████████▏                          | 10919/42525 [20:10<59:31,  8.85it/s]

 26%|█████████▏                          | 10922/42525 [20:10<58:47,  8.96it/s]

 26%|████████▋                         | 10924/42525 [20:10<1:03:25,  8.30it/s]

 26%|████████▋                         | 10926/42525 [20:10<1:05:27,  8.05it/s]

 26%|████████▋                         | 10928/42525 [20:11<1:03:11,  8.33it/s]

 26%|████████▋                         | 10930/42525 [20:11<1:10:58,  7.42it/s]

 26%|████████▋                         | 10931/42525 [20:11<1:12:56,  7.22it/s]

 26%|████████▋                         | 10934/42525 [20:11<1:05:09,  8.08it/s]

 26%|████████▋                         | 10937/42525 [20:12<1:01:25,  8.57it/s]

 26%|█████████▎                          | 10940/42525 [20:12<56:49,  9.26it/s]

 26%|█████████▎                          | 10944/42525 [20:13<56:46,  9.27it/s]

 26%|████████▊                         | 10946/42525 [20:13<1:00:14,  8.74it/s]

 26%|█████████▎                          | 10949/42525 [20:13<57:32,  9.15it/s]

 26%|█████████▎                          | 10951/42525 [20:13<54:58,  9.57it/s]

 26%|█████████▎                          | 10953/42525 [20:14<55:29,  9.48it/s]

 26%|█████████▎                          | 10956/42525 [20:14<58:55,  8.93it/s]

 26%|█████████▎                          | 10959/42525 [20:14<59:42,  8.81it/s]

 26%|████████▊                         | 10961/42525 [20:14<1:01:23,  8.57it/s]

 26%|█████████▎                          | 10964/42525 [20:15<57:35,  9.13it/s]

 26%|█████████▎                          | 10967/42525 [20:15<54:33,  9.64it/s]

 26%|█████████▎                          | 10970/42525 [20:15<59:05,  8.90it/s]

 26%|█████████▎                          | 10973/42525 [20:16<59:02,  8.91it/s]

 26%|████████▊                         | 10975/42525 [20:16<1:01:30,  8.55it/s]

 26%|████████▊                         | 10977/42525 [20:16<1:06:57,  7.85it/s]

 26%|████████▊                         | 10980/42525 [20:17<1:01:58,  8.48it/s]

 26%|█████████▎                          | 10983/42525 [20:17<59:24,  8.85it/s]

 26%|█████████▎                          | 10986/42525 [20:17<55:46,  9.42it/s]

 26%|█████████▎                          | 10988/42525 [20:17<56:37,  9.28it/s]

 26%|█████████▎                          | 10991/42525 [20:18<56:25,  9.31it/s]

 26%|█████████▎                          | 10994/42525 [20:18<54:30,  9.64it/s]

 26%|█████████▎                          | 10997/42525 [20:18<54:37,  9.62it/s]

 26%|█████████▎                          | 11000/42525 [20:19<53:36,  9.80it/s]

 26%|█████████▎                          | 11001/42525 [20:19<53:49,  9.76it/s]

 26%|█████████▎                          | 11004/42525 [20:19<57:11,  9.19it/s]

 26%|█████████▎                          | 11006/42525 [20:19<56:46,  9.25it/s]

 26%|█████████▎                          | 11008/42525 [20:20<58:15,  9.02it/s]

 26%|█████████▎                          | 11009/42525 [20:20<58:57,  8.91it/s]

 26%|█████████▎                          | 11012/42525 [20:20<57:19,  9.16it/s]

 26%|████████▊                         | 11014/42525 [20:20<1:01:14,  8.57it/s]

 26%|████████▊                         | 11016/42525 [20:21<1:02:11,  8.44it/s]

 26%|████████▊                         | 11017/42525 [20:21<1:04:35,  8.13it/s]

 26%|████████▊                         | 11020/42525 [20:21<1:01:44,  8.51it/s]

 26%|████████▊                         | 11023/42525 [20:21<1:02:39,  8.38it/s]

 26%|████████▊                         | 11026/42525 [20:22<1:00:32,  8.67it/s]

 26%|████████▊                         | 11028/42525 [20:22<1:02:15,  8.43it/s]

 26%|█████████▎                          | 11031/42525 [20:22<59:46,  8.78it/s]

 26%|████████▊                         | 11033/42525 [20:23<1:04:37,  8.12it/s]

 26%|████████▊                         | 11035/42525 [20:23<1:00:14,  8.71it/s]

 26%|█████████▎                          | 11038/42525 [20:23<56:08,  9.35it/s]

 26%|█████████▎                          | 11041/42525 [20:23<59:33,  8.81it/s]

 26%|████████▊                         | 11044/42525 [20:24<1:02:01,  8.46it/s]

 26%|█████████▎                          | 11047/42525 [20:24<59:46,  8.78it/s]

 26%|████████▊                         | 11049/42525 [20:24<1:00:26,  8.68it/s]

 26%|█████████▎                          | 11052/42525 [20:25<56:54,  9.22it/s]

 26%|█████████▎                          | 11056/42525 [20:25<53:27,  9.81it/s]

 26%|█████████▎                          | 11058/42525 [20:25<53:30,  9.80it/s]

 26%|████████▊                         | 11060/42525 [20:26<1:04:36,  8.12it/s]

 26%|████████▊                         | 11063/42525 [20:26<1:00:40,  8.64it/s]

 26%|█████████▎                          | 11064/42525 [20:26<59:17,  8.84it/s]

 26%|████████▊                         | 11066/42525 [20:26<1:01:29,  8.53it/s]

 26%|████████▊                         | 11068/42525 [20:27<1:02:42,  8.36it/s]

 26%|█████████▎                          | 11072/42525 [20:27<59:25,  8.82it/s]

 26%|█████████▍                          | 11075/42525 [20:27<57:32,  9.11it/s]

 26%|█████████▍                          | 11078/42525 [20:28<55:02,  9.52it/s]

 26%|█████████▍                          | 11082/42525 [20:28<52:50,  9.92it/s]

 26%|█████████▍                          | 11083/42525 [20:28<52:53,  9.91it/s]

 26%|█████████▍                          | 11086/42525 [20:28<55:24,  9.46it/s]

 26%|█████████▍                          | 11088/42525 [20:29<56:05,  9.34it/s]

 26%|█████████▍                          | 11089/42525 [20:29<57:49,  9.06it/s]

 26%|█████████▍                          | 11091/42525 [20:29<57:39,  9.09it/s]

 26%|████████▊                         | 11094/42525 [20:29<1:01:21,  8.54it/s]

 26%|█████████▍                          | 11098/42525 [20:30<55:06,  9.51it/s]

 26%|█████████▍                          | 11099/42525 [20:30<54:45,  9.57it/s]

 26%|█████████▍                          | 11103/42525 [20:30<54:36,  9.59it/s]

 26%|█████████▍                          | 11104/42525 [20:30<58:16,  8.99it/s]

 26%|████████▉                         | 11107/42525 [20:31<1:00:59,  8.59it/s]

 26%|█████████▍                          | 11110/42525 [20:31<59:14,  8.84it/s]

 26%|█████████▍                          | 11113/42525 [20:31<59:37,  8.78it/s]

 26%|████████▉                         | 11115/42525 [20:32<1:07:08,  7.80it/s]

 26%|█████████▍                          | 11119/42525 [20:32<57:17,  9.13it/s]

 26%|█████████▍                          | 11122/42525 [20:32<59:40,  8.77it/s]

 26%|█████████▍                          | 11124/42525 [20:33<59:05,  8.86it/s]

 26%|████████▉                         | 11127/42525 [20:33<1:00:59,  8.58it/s]

 26%|████████▉                         | 11128/42525 [20:33<1:03:36,  8.23it/s]

 26%|█████████▍                          | 11132/42525 [20:34<56:35,  9.24it/s]

 26%|█████████▍                          | 11136/42525 [20:34<54:03,  9.68it/s]

 26%|█████████▍                          | 11138/42525 [20:34<56:14,  9.30it/s]

 26%|█████████▍                          | 11141/42525 [20:35<57:02,  9.17it/s]

 26%|█████████▍                          | 11144/42525 [20:35<59:48,  8.74it/s]

 26%|█████████▍                          | 11145/42525 [20:35<59:29,  8.79it/s]

 26%|████████▉                         | 11148/42525 [20:35<1:01:25,  8.51it/s]

 26%|█████████▍                          | 11151/42525 [20:36<56:18,  9.29it/s]

 26%|█████████▍                          | 11154/42525 [20:36<54:24,  9.61it/s]

 26%|█████████▍                          | 11156/42525 [20:36<53:05,  9.85it/s]

 26%|████████▉                         | 11159/42525 [20:37<1:01:10,  8.55it/s]

 26%|█████████▍                          | 11162/42525 [20:37<59:45,  8.75it/s]

 26%|█████████▍                          | 11165/42525 [20:37<59:01,  8.86it/s]

 26%|█████████▍                          | 11168/42525 [20:38<57:31,  9.09it/s]

 26%|█████████▍                          | 11172/42525 [20:38<53:41,  9.73it/s]

 26%|█████████▍                          | 11175/42525 [20:38<56:11,  9.30it/s]

 26%|████████▉                         | 11177/42525 [20:39<1:01:58,  8.43it/s]

 26%|████████▉                         | 11178/42525 [20:39<1:04:13,  8.13it/s]

 26%|████████▉                         | 11181/42525 [20:39<1:04:21,  8.12it/s]

 26%|█████████▍                          | 11184/42525 [20:39<59:52,  8.72it/s]

 26%|█████████▍                          | 11186/42525 [20:40<56:47,  9.20it/s]

 26%|█████████▍                          | 11188/42525 [20:40<54:25,  9.60it/s]

 26%|█████████▍                          | 11192/42525 [20:40<53:28,  9.77it/s]

 26%|█████████▍                          | 11195/42525 [20:40<53:15,  9.80it/s]

 26%|█████████▍                          | 11198/42525 [20:41<52:22,  9.97it/s]

 26%|█████████▍                          | 11202/42525 [20:41<51:56, 10.05it/s]

 26%|█████████▍                          | 11204/42525 [20:41<52:06, 10.02it/s]

 26%|████████▉                         | 11207/42525 [20:42<1:00:59,  8.56it/s]

 26%|█████████▍                          | 11210/42525 [20:42<56:19,  9.27it/s]

 26%|█████████▍                          | 11211/42525 [20:42<55:30,  9.40it/s]

 26%|█████████▍                          | 11215/42525 [20:43<53:12,  9.81it/s]

 26%|█████████▍                          | 11217/42525 [20:43<57:12,  9.12it/s]

 26%|████████▉                         | 11219/42525 [20:43<1:02:17,  8.38it/s]

 26%|████████▉                         | 11220/42525 [20:43<1:03:21,  8.23it/s]

 26%|█████████▌                          | 11222/42525 [20:43<59:06,  8.83it/s]

 26%|█████████▌                          | 11226/42525 [20:44<55:19,  9.43it/s]

 26%|████████▉                         | 11228/42525 [20:44<1:03:21,  8.23it/s]

 26%|████████▉                         | 11230/42525 [20:44<1:04:57,  8.03it/s]

 26%|████████▉                         | 11233/42525 [20:45<1:03:46,  8.18it/s]

 26%|████████▉                         | 11235/42525 [20:45<1:03:06,  8.26it/s]

 26%|█████████▌                          | 11239/42525 [20:45<55:33,  9.39it/s]

 26%|█████████▌                          | 11242/42525 [20:46<53:46,  9.70it/s]

 26%|█████████▌                          | 11245/42525 [20:46<52:23,  9.95it/s]

 26%|█████████▌                          | 11248/42525 [20:46<52:15,  9.98it/s]

 26%|█████████▌                          | 11251/42525 [20:47<57:08,  9.12it/s]

 26%|█████████▌                          | 11253/42525 [20:47<57:39,  9.04it/s]

 26%|█████████▌                          | 11257/42525 [20:47<53:31,  9.74it/s]

 26%|█████████▌                          | 11259/42525 [20:47<52:46,  9.87it/s]

 26%|█████████▌                          | 11262/42525 [20:48<54:48,  9.51it/s]

 26%|█████████▌                          | 11266/42525 [20:48<52:32,  9.92it/s]

 26%|█████████▌                          | 11269/42525 [20:48<52:47,  9.87it/s]

 27%|█████████▌                          | 11272/42525 [20:49<53:50,  9.68it/s]

 27%|█████████                         | 11274/42525 [20:49<1:01:44,  8.44it/s]

 27%|█████████▌                          | 11278/42525 [20:49<55:08,  9.45it/s]

 27%|█████████▌                          | 11281/42525 [20:50<59:37,  8.73it/s]

 27%|█████████▌                          | 11284/42525 [20:50<58:46,  8.86it/s]

 27%|█████████▌                          | 11287/42525 [20:50<56:37,  9.19it/s]

 27%|█████████▌                          | 11291/42525 [20:51<53:05,  9.80it/s]

 27%|█████████▌                          | 11293/42525 [20:51<52:16,  9.96it/s]

 27%|█████████▌                          | 11297/42525 [20:51<52:05,  9.99it/s]

 27%|█████████▌                          | 11301/42525 [20:52<51:20, 10.14it/s]

 27%|█████████▌                          | 11303/42525 [20:52<51:36, 10.08it/s]

 27%|█████████▌                          | 11306/42525 [20:52<57:19,  9.08it/s]

 27%|█████████                         | 11307/42525 [20:52<1:01:18,  8.49it/s]

 27%|█████████                         | 11309/42525 [20:53<1:01:42,  8.43it/s]

 27%|█████████▌                          | 11312/42525 [20:53<59:18,  8.77it/s]

 27%|█████████▌                          | 11314/42525 [20:53<56:44,  9.17it/s]

 27%|█████████▌                          | 11315/42525 [20:53<55:43,  9.33it/s]

 27%|█████████▌                          | 11318/42525 [20:54<55:03,  9.45it/s]

 27%|█████████                         | 11320/42525 [20:54<1:00:55,  8.54it/s]

 27%|█████████▌                          | 11321/42525 [20:54<58:30,  8.89it/s]

 27%|█████████▌                          | 11323/42525 [20:54<56:01,  9.28it/s]

 27%|█████████                         | 11326/42525 [20:55<1:00:53,  8.54it/s]

 27%|█████████                         | 11328/42525 [20:55<1:01:54,  8.40it/s]

 27%|█████████                         | 11330/42525 [20:55<1:00:23,  8.61it/s]

 27%|█████████▌                          | 11333/42525 [20:55<58:28,  8.89it/s]

 27%|█████████▌                          | 11337/42525 [20:56<53:42,  9.68it/s]

 27%|█████████▌                          | 11341/42525 [20:56<53:03,  9.80it/s]

 27%|█████████▌                          | 11343/42525 [20:56<54:30,  9.54it/s]

 27%|█████████▌                          | 11345/42525 [20:57<57:10,  9.09it/s]

 27%|█████████▌                          | 11349/42525 [20:57<54:21,  9.56it/s]

 27%|█████████▌                          | 11351/42525 [20:57<59:40,  8.71it/s]

 27%|█████████▌                          | 11354/42525 [20:58<58:22,  8.90it/s]

 27%|█████████                         | 11357/42525 [20:58<1:00:26,  8.59it/s]

 27%|█████████▌                          | 11360/42525 [20:58<56:29,  9.19it/s]

 27%|█████████▌                          | 11361/42525 [20:58<56:34,  9.18it/s]

 27%|█████████▌                          | 11363/42525 [20:59<59:26,  8.74it/s]

 27%|█████████                         | 11366/42525 [20:59<1:02:06,  8.36it/s]

 27%|█████████▋                          | 11370/42525 [20:59<55:45,  9.31it/s]

 27%|█████████▋                          | 11373/42525 [21:00<56:27,  9.19it/s]

 27%|█████████▋                          | 11375/42525 [21:00<55:11,  9.41it/s]

 27%|█████████▋                          | 11379/42525 [21:00<53:01,  9.79it/s]

 27%|█████████▋                          | 11381/42525 [21:01<54:03,  9.60it/s]

 27%|█████████▋                          | 11383/42525 [21:01<58:34,  8.86it/s]

 27%|█████████                         | 11385/42525 [21:01<1:03:34,  8.16it/s]

 27%|█████████▋                          | 11388/42525 [21:01<57:31,  9.02it/s]

 27%|█████████▋                          | 11392/42525 [21:02<53:23,  9.72it/s]

 27%|█████████▋                          | 11395/42525 [21:02<55:30,  9.35it/s]

 27%|█████████                         | 11397/42525 [21:02<1:02:31,  8.30it/s]

 27%|█████████                         | 11399/42525 [21:03<1:00:39,  8.55it/s]

 27%|█████████▋                          | 11402/42525 [21:03<56:04,  9.25it/s]

 27%|█████████▋                          | 11405/42525 [21:03<53:44,  9.65it/s]

 27%|█████████                         | 11407/42525 [21:04<1:00:04,  8.63it/s]

 27%|█████████▋                          | 11410/42525 [21:04<59:04,  8.78it/s]

 27%|█████████                         | 11412/42525 [21:04<1:04:49,  8.00it/s]

 27%|█████████▏                        | 11414/42525 [21:04<1:00:34,  8.56it/s]

 27%|█████████▏                        | 11417/42525 [21:05<1:04:04,  8.09it/s]

 27%|█████████▋                          | 11421/42525 [21:05<55:25,  9.35it/s]

 27%|█████████▋                          | 11424/42525 [21:05<53:41,  9.66it/s]

 27%|█████████▋                          | 11425/42525 [21:06<55:05,  9.41it/s]

 27%|█████████▋                          | 11429/42525 [21:06<54:47,  9.46it/s]

 27%|█████████▋                          | 11431/42525 [21:06<54:14,  9.55it/s]

 27%|█████████▋                          | 11433/42525 [21:06<57:36,  8.99it/s]

 27%|█████████▏                        | 11436/42525 [21:07<1:01:27,  8.43it/s]

 27%|█████████▋                          | 11439/42525 [21:07<58:13,  8.90it/s]

 27%|█████████▏                        | 11441/42525 [21:07<1:00:51,  8.51it/s]

 27%|█████████▋                          | 11443/42525 [21:08<58:38,  8.83it/s]

 27%|█████████▏                        | 11445/42525 [21:08<1:04:26,  8.04it/s]

 27%|█████████▋                          | 11448/42525 [21:08<57:01,  9.08it/s]

 27%|█████████▋                          | 11451/42525 [21:08<55:47,  9.28it/s]

 27%|█████████▋                          | 11455/42525 [21:09<52:42,  9.82it/s]

 27%|█████████▋                          | 11458/42525 [21:09<58:24,  8.87it/s]

 27%|█████████▋                          | 11460/42525 [21:09<58:03,  8.92it/s]

 27%|█████████▋                          | 11462/42525 [21:10<57:26,  9.01it/s]

 27%|█████████▏                        | 11465/42525 [21:10<1:00:25,  8.57it/s]

 27%|█████████▋                          | 11468/42525 [21:10<56:24,  9.18it/s]

 27%|█████████▋                          | 11471/42525 [21:11<55:41,  9.29it/s]

 27%|█████████▋                          | 11475/42525 [21:11<52:41,  9.82it/s]

 27%|█████████▋                          | 11477/42525 [21:11<52:42,  9.82it/s]

 27%|█████████▋                          | 11481/42525 [21:12<52:20,  9.89it/s]

 27%|█████████▋                          | 11483/42525 [21:12<54:09,  9.55it/s]

 27%|█████████▋                          | 11485/42525 [21:12<53:34,  9.66it/s]

 27%|█████████▋                          | 11489/42525 [21:13<52:49,  9.79it/s]

 27%|█████████▋                          | 11492/42525 [21:13<56:59,  9.07it/s]

 27%|█████████▏                        | 11495/42525 [21:13<1:00:15,  8.58it/s]

 27%|█████████▋                          | 11497/42525 [21:13<58:11,  8.89it/s]

 27%|█████████▋                          | 11500/42525 [21:14<55:46,  9.27it/s]

 27%|█████████▋                          | 11503/42525 [21:14<59:21,  8.71it/s]

 27%|█████████▏                        | 11505/42525 [21:14<1:03:19,  8.16it/s]

 27%|█████████▋                          | 11509/42525 [21:15<55:39,  9.29it/s]

 27%|█████████▋                          | 11512/42525 [21:15<54:08,  9.55it/s]

 27%|█████████▋                          | 11514/42525 [21:15<55:33,  9.30it/s]

 27%|█████████▋                          | 11516/42525 [21:16<56:59,  9.07it/s]

 27%|█████████▊                          | 11518/42525 [21:16<55:52,  9.25it/s]

 27%|█████████▊                          | 11521/42525 [21:16<52:37,  9.82it/s]

 27%|█████████▊                          | 11525/42525 [21:16<52:34,  9.83it/s]

 27%|█████████▊                          | 11527/42525 [21:17<53:33,  9.65it/s]

 27%|█████████▊                          | 11529/42525 [21:17<59:38,  8.66it/s]

 27%|█████████▏                        | 11531/42525 [21:17<1:06:15,  7.80it/s]

 27%|█████████▏                        | 11533/42525 [21:17<1:04:52,  7.96it/s]

 27%|█████████▏                        | 11536/42525 [21:18<1:00:26,  8.54it/s]

 27%|█████████▏                        | 11537/42525 [21:18<1:02:12,  8.30it/s]

 27%|█████████▊                          | 11540/42525 [21:18<57:33,  8.97it/s]

 27%|█████████▊                          | 11543/42525 [21:19<58:30,  8.82it/s]

 27%|█████████▏                        | 11545/42525 [21:19<1:02:17,  8.29it/s]

 27%|█████████▏                        | 11546/42525 [21:19<1:05:20,  7.90it/s]

 27%|█████████▊                          | 11550/42525 [21:19<59:09,  8.73it/s]

 27%|█████████▊                          | 11552/42525 [21:20<56:01,  9.21it/s]

 27%|█████████▊                          | 11555/42525 [21:20<57:50,  8.92it/s]

 27%|█████████▊                          | 11558/42525 [21:20<55:09,  9.36it/s]

 27%|█████████▊                          | 11562/42525 [21:21<52:27,  9.84it/s]

 27%|█████████▊                          | 11566/42525 [21:21<51:14, 10.07it/s]

 27%|█████████▊                          | 11570/42525 [21:21<52:25,  9.84it/s]

 27%|█████████▊                          | 11573/42525 [21:22<52:44,  9.78it/s]

 27%|█████████▊                          | 11575/42525 [21:22<56:46,  9.08it/s]

 27%|█████████▊                          | 11578/42525 [21:22<59:22,  8.69it/s]

 27%|█████████▊                          | 11582/42525 [21:23<54:11,  9.52it/s]

 27%|█████████▊                          | 11583/42525 [21:23<58:41,  8.79it/s]

 27%|█████████▊                          | 11587/42525 [21:23<55:46,  9.25it/s]

 27%|█████████▊                          | 11590/42525 [21:24<54:32,  9.45it/s]

 27%|█████████▊                          | 11593/42525 [21:24<56:11,  9.17it/s]

 27%|█████████▊                          | 11596/42525 [21:24<53:49,  9.58it/s]

 27%|█████████▊                          | 11599/42525 [21:25<53:19,  9.67it/s]

 27%|█████████▎                        | 11601/42525 [21:25<1:01:02,  8.44it/s]

 27%|█████████▊                          | 11605/42525 [21:25<54:37,  9.43it/s]

 27%|█████████▊                          | 11607/42525 [21:26<59:22,  8.68it/s]

 27%|█████████▊                          | 11610/42525 [21:26<58:05,  8.87it/s]

 27%|█████████▊                          | 11613/42525 [21:26<59:12,  8.70it/s]

 27%|█████████▊                          | 11616/42525 [21:27<57:23,  8.98it/s]

 27%|█████████▎                        | 11618/42525 [21:27<1:00:37,  8.50it/s]

 27%|█████████▎                        | 11620/42525 [21:27<1:08:08,  7.56it/s]

 27%|█████████▎                        | 11622/42525 [21:27<1:06:13,  7.78it/s]

 27%|█████████▎                        | 11625/42525 [21:28<1:00:09,  8.56it/s]

 27%|█████████▊                          | 11627/42525 [21:28<56:43,  9.08it/s]

 27%|█████████▎                        | 11630/42525 [21:28<1:00:03,  8.57it/s]

 27%|█████████▊                          | 11634/42525 [21:29<54:50,  9.39it/s]

 27%|█████████▊                          | 11636/42525 [21:29<55:37,  9.26it/s]

 27%|█████████▊                          | 11637/42525 [21:29<59:29,  8.65it/s]

 27%|█████████▊                          | 11640/42525 [21:29<58:55,  8.74it/s]

 27%|█████████▊                          | 11644/42525 [21:30<53:33,  9.61it/s]

 27%|█████████▊                          | 11646/42525 [21:30<57:09,  9.00it/s]

 27%|█████████▊                          | 11649/42525 [21:30<59:24,  8.66it/s]

 27%|█████████▊                          | 11653/42525 [21:31<53:38,  9.59it/s]

 27%|█████████▊                          | 11656/42525 [21:31<55:38,  9.25it/s]

 27%|█████████▊                          | 11658/42525 [21:31<53:24,  9.63it/s]

 27%|█████████▎                        | 11661/42525 [21:32<1:00:22,  8.52it/s]

 27%|█████████▉                          | 11665/42525 [21:32<54:15,  9.48it/s]

 27%|█████████▉                          | 11668/42525 [21:32<52:44,  9.75it/s]

 27%|█████████▉                          | 11672/42525 [21:33<50:57, 10.09it/s]

 27%|█████████▉                          | 11676/42525 [21:33<53:00,  9.70it/s]

 27%|█████████▉                          | 11679/42525 [21:33<56:03,  9.17it/s]

 27%|█████████▎                        | 11680/42525 [21:34<1:00:16,  8.53it/s]

 27%|█████████▉                          | 11682/42525 [21:34<58:27,  8.79it/s]

 27%|█████████▉                          | 11684/42525 [21:34<59:43,  8.61it/s]

 27%|█████████▎                        | 11687/42525 [21:34<1:01:04,  8.42it/s]

 27%|█████████▉                          | 11691/42525 [21:35<54:20,  9.46it/s]

 28%|█████████▉                          | 11695/42525 [21:35<51:51,  9.91it/s]

 28%|█████████▉                          | 11696/42525 [21:35<53:05,  9.68it/s]

 28%|█████████▎                        | 11699/42525 [21:36<1:00:28,  8.49it/s]

 28%|█████████▉                          | 11703/42525 [21:36<54:05,  9.50it/s]

 28%|█████████▉                          | 11705/42525 [21:36<52:58,  9.70it/s]

 28%|█████████▉                          | 11709/42525 [21:37<52:06,  9.86it/s]

 28%|█████████▉                          | 11711/42525 [21:37<57:02,  9.00it/s]

 28%|█████████▉                          | 11714/42525 [21:37<56:21,  9.11it/s]

 28%|█████████▉                          | 11718/42525 [21:38<53:49,  9.54it/s]

 28%|█████████▉                          | 11721/42525 [21:38<56:24,  9.10it/s]

 28%|█████████▉                          | 11724/42525 [21:38<59:34,  8.62it/s]

 28%|█████████▉                          | 11725/42525 [21:38<58:12,  8.82it/s]

 28%|█████████▉                          | 11729/42525 [21:39<56:30,  9.08it/s]

 28%|█████████▉                          | 11732/42525 [21:39<58:30,  8.77it/s]

 28%|█████████▉                          | 11734/42525 [21:39<57:26,  8.93it/s]

 28%|█████████▉                          | 11737/42525 [21:40<55:34,  9.23it/s]

 28%|█████████▉                          | 11740/42525 [21:40<55:58,  9.17it/s]

 28%|█████████▉                          | 11741/42525 [21:40<56:49,  9.03it/s]

 28%|█████████▉                          | 11745/42525 [21:41<54:45,  9.37it/s]

 28%|█████████▉                          | 11747/42525 [21:41<52:49,  9.71it/s]

 28%|█████████▍                        | 11750/42525 [21:41<1:00:10,  8.52it/s]

 28%|█████████▉                          | 11752/42525 [21:41<59:15,  8.66it/s]

 28%|█████████▉                          | 11755/42525 [21:42<57:24,  8.93it/s]

 28%|█████████▉                          | 11757/42525 [21:42<59:20,  8.64it/s]

 28%|█████████▉                          | 11760/42525 [21:42<56:50,  9.02it/s]

 28%|█████████▉                          | 11763/42525 [21:43<59:50,  8.57it/s]

 28%|█████████▍                        | 11766/42525 [21:43<1:00:21,  8.49it/s]

 28%|█████████▍                        | 11768/42525 [21:43<1:02:39,  8.18it/s]

 28%|█████████▉                          | 11771/42525 [21:44<55:53,  9.17it/s]

 28%|█████████▉                          | 11774/42525 [21:44<53:29,  9.58it/s]

 28%|█████████▍                        | 11776/42525 [21:44<1:02:16,  8.23it/s]

 28%|█████████▉                          | 11778/42525 [21:44<57:51,  8.86it/s]

 28%|█████████▉                          | 11780/42525 [21:45<56:01,  9.15it/s]

 28%|█████████▉                          | 11784/42525 [21:45<56:04,  9.14it/s]

 28%|█████████▍                        | 11786/42525 [21:45<1:02:11,  8.24it/s]

 28%|█████████▉                          | 11788/42525 [21:46<57:52,  8.85it/s]

 28%|█████████▉                          | 11790/42525 [21:46<56:20,  9.09it/s]

 28%|█████████▉                          | 11791/42525 [21:46<56:24,  9.08it/s]

 28%|█████████▉                          | 11794/42525 [21:46<59:57,  8.54it/s]

 28%|█████████▉                          | 11796/42525 [21:46<58:19,  8.78it/s]

 28%|█████████▉                          | 11799/42525 [21:47<57:22,  8.93it/s]

 28%|█████████▍                        | 11801/42525 [21:47<1:02:25,  8.20it/s]

 28%|█████████▍                        | 11804/42525 [21:47<1:01:33,  8.32it/s]

 28%|█████████▉                          | 11808/42525 [21:48<54:47,  9.34it/s]

 28%|█████████▉                          | 11811/42525 [21:48<52:50,  9.69it/s]

 28%|██████████                          | 11813/42525 [21:48<51:40,  9.90it/s]

 28%|██████████                          | 11816/42525 [21:49<56:22,  9.08it/s]

 28%|██████████                          | 11818/42525 [21:49<54:49,  9.34it/s]

 28%|██████████                          | 11820/42525 [21:49<53:36,  9.55it/s]

 28%|██████████                          | 11821/42525 [21:49<53:28,  9.57it/s]

 28%|██████████                          | 11824/42525 [21:50<56:32,  9.05it/s]

 28%|██████████                          | 11828/42525 [21:50<54:27,  9.40it/s]

 28%|██████████                          | 11830/42525 [21:50<57:28,  8.90it/s]

 28%|██████████                          | 11833/42525 [21:51<57:28,  8.90it/s]

 28%|█████████▍                        | 11835/42525 [21:51<1:02:52,  8.13it/s]

 28%|██████████                          | 11837/42525 [21:51<57:39,  8.87it/s]

 28%|██████████                          | 11840/42525 [21:51<54:51,  9.32it/s]

 28%|██████████                          | 11844/42525 [21:52<51:51,  9.86it/s]

 28%|██████████                          | 11847/42525 [21:52<56:04,  9.12it/s]

 28%|██████████                          | 11849/42525 [21:52<57:03,  8.96it/s]

 28%|██████████                          | 11850/42525 [21:52<58:27,  8.75it/s]

 28%|█████████▍                        | 11853/42525 [21:53<1:00:34,  8.44it/s]

 28%|██████████                          | 11856/42525 [21:53<57:55,  8.82it/s]

 28%|██████████                          | 11860/42525 [21:54<54:51,  9.32it/s]

 28%|██████████                          | 11862/42525 [21:54<59:19,  8.61it/s]

 28%|█████████▍                        | 11865/42525 [21:54<1:01:00,  8.38it/s]

 28%|██████████                          | 11867/42525 [21:54<57:03,  8.95it/s]

 28%|██████████                          | 11870/42525 [21:55<56:05,  9.11it/s]

 28%|██████████                          | 11874/42525 [21:55<52:17,  9.77it/s]

 28%|██████████                          | 11876/42525 [21:55<57:15,  8.92it/s]

 28%|█████████▍                        | 11878/42525 [21:56<1:00:12,  8.48it/s]

 28%|██████████                          | 11881/42525 [21:56<56:14,  9.08it/s]

 28%|██████████                          | 11883/42525 [21:56<56:10,  9.09it/s]

 28%|██████████                          | 11885/42525 [21:56<59:58,  8.51it/s]

 28%|██████████                          | 11888/42525 [21:57<58:06,  8.79it/s]

 28%|█████████▌                        | 11891/42525 [21:57<1:00:21,  8.46it/s]

 28%|█████████▌                        | 11893/42525 [21:57<1:01:39,  8.28it/s]

 28%|██████████                          | 11896/42525 [21:58<59:00,  8.65it/s]

 28%|██████████                          | 11898/42525 [21:58<55:08,  9.26it/s]

 28%|██████████                          | 11902/42525 [21:58<52:30,  9.72it/s]

 28%|██████████                          | 11905/42525 [21:59<51:45,  9.86it/s]

 28%|██████████                          | 11906/42525 [21:59<51:43,  9.87it/s]

 28%|██████████                          | 11909/42525 [21:59<54:48,  9.31it/s]

 28%|██████████                          | 11912/42525 [21:59<52:57,  9.64it/s]

 28%|██████████                          | 11914/42525 [22:00<59:19,  8.60it/s]

 28%|██████████                          | 11917/42525 [22:00<55:05,  9.26it/s]

 28%|██████████                          | 11920/42525 [22:00<58:11,  8.77it/s]

 28%|██████████                          | 11923/42525 [22:01<59:17,  8.60it/s]

 28%|██████████                          | 11925/42525 [22:01<56:22,  9.05it/s]

 28%|██████████                          | 11928/42525 [22:01<56:53,  8.96it/s]

 28%|██████████                          | 11931/42525 [22:01<53:19,  9.56it/s]

 28%|██████████                          | 11933/42525 [22:02<53:53,  9.46it/s]

 28%|██████████                          | 11934/42525 [22:02<54:51,  9.29it/s]

 28%|██████████                          | 11936/42525 [22:02<54:16,  9.39it/s]

 28%|██████████                          | 11939/42525 [22:02<58:16,  8.75it/s]

 28%|█████████▌                        | 11941/42525 [22:03<1:05:36,  7.77it/s]

 28%|█████████▌                        | 11943/42525 [22:03<1:04:00,  7.96it/s]

 28%|██████████                          | 11945/42525 [22:03<57:40,  8.84it/s]

 28%|██████████                          | 11947/42525 [22:03<59:25,  8.58it/s]

 28%|██████████                          | 11951/42525 [22:04<57:15,  8.90it/s]

 28%|██████████                          | 11954/42525 [22:04<53:23,  9.54it/s]

 28%|██████████                          | 11957/42525 [22:04<52:34,  9.69it/s]

 28%|██████████                          | 11959/42525 [22:05<53:41,  9.49it/s]

 28%|██████████▏                         | 11962/42525 [22:05<52:56,  9.62it/s]

 28%|██████████▏                         | 11965/42525 [22:05<55:36,  9.16it/s]

 28%|██████████▏                         | 11967/42525 [22:05<55:28,  9.18it/s]

 28%|██████████▏                         | 11969/42525 [22:06<52:45,  9.65it/s]

 28%|██████████▏                         | 11971/42525 [22:06<56:26,  9.02it/s]

 28%|██████████▏                         | 11973/42525 [22:06<58:28,  8.71it/s]

 28%|██████████▏                         | 11977/42525 [22:06<54:25,  9.35it/s]

 28%|██████████▏                         | 11979/42525 [22:07<58:33,  8.69it/s]

 28%|██████████▏                         | 11981/42525 [22:07<59:06,  8.61it/s]

 28%|█████████▌                        | 11983/42525 [22:07<1:08:14,  7.46it/s]

 28%|██████████▏                         | 11987/42525 [22:08<55:32,  9.16it/s]

 28%|██████████▏                         | 11991/42525 [22:08<53:24,  9.53it/s]

 28%|██████████▏                         | 11992/42525 [22:08<52:55,  9.61it/s]

 28%|██████████▏                         | 11995/42525 [22:09<56:10,  9.06it/s]

 28%|██████████▏                         | 11998/42525 [22:09<55:18,  9.20it/s]

 28%|██████████▏                         | 12000/42525 [22:09<57:52,  8.79it/s]

 28%|██████████▏                         | 12003/42525 [22:09<59:31,  8.55it/s]

 28%|██████████▏                         | 12005/42525 [22:10<55:52,  9.10it/s]

 28%|██████████▏                         | 12008/42525 [22:10<58:38,  8.67it/s]

 28%|██████████▏                         | 12010/42525 [22:10<58:05,  8.76it/s]

 28%|██████████▏                         | 12013/42525 [22:11<55:23,  9.18it/s]

 28%|██████████▏                         | 12017/42525 [22:11<51:53,  9.80it/s]

 28%|██████████▏                         | 12020/42525 [22:11<55:03,  9.23it/s]

 28%|██████████▏                         | 12022/42525 [22:11<55:25,  9.17it/s]

 28%|██████████▏                         | 12025/42525 [22:12<53:23,  9.52it/s]

 28%|█████████▌                        | 12028/42525 [22:12<1:00:55,  8.34it/s]

 28%|█████████▌                        | 12029/42525 [22:12<1:04:14,  7.91it/s]

 28%|█████████▌                        | 12032/42525 [22:13<1:06:10,  7.68it/s]

 28%|██████████▏                         | 12036/42525 [22:13<55:57,  9.08it/s]

 28%|█████████▋                        | 12039/42525 [22:14<1:01:37,  8.25it/s]

 28%|█████████▋                        | 12041/42525 [22:14<1:02:46,  8.09it/s]

 28%|██████████▏                         | 12044/42525 [22:14<59:23,  8.55it/s]

 28%|█████████▋                        | 12047/42525 [22:14<1:01:45,  8.23it/s]

 28%|██████████▏                         | 12050/42525 [22:15<56:15,  9.03it/s]

 28%|██████████▏                         | 12053/42525 [22:15<53:43,  9.45it/s]

 28%|██████████▏                         | 12055/42525 [22:15<51:45,  9.81it/s]

 28%|██████████▏                         | 12059/42525 [22:16<53:30,  9.49it/s]

 28%|██████████▏                         | 12061/42525 [22:16<54:11,  9.37it/s]

 28%|██████████▏                         | 12062/42525 [22:16<59:11,  8.58it/s]

 28%|█████████▋                        | 12064/42525 [22:16<1:00:34,  8.38it/s]

 28%|█████████▋                        | 12067/42525 [22:17<1:00:45,  8.35it/s]

 28%|█████████▋                        | 12069/42525 [22:17<1:04:13,  7.90it/s]

 28%|█████████▋                        | 12070/42525 [22:17<1:01:35,  8.24it/s]

 28%|█████████▋                        | 12073/42525 [22:17<1:02:04,  8.18it/s]

 28%|█████████▋                        | 12075/42525 [22:18<1:08:09,  7.45it/s]

 28%|█████████▋                        | 12077/42525 [22:18<1:00:56,  8.33it/s]

 28%|█████████▋                        | 12079/42525 [22:18<1:01:34,  8.24it/s]

 28%|██████████▏                         | 12081/42525 [22:18<55:48,  9.09it/s]

 28%|██████████▏                         | 12084/42525 [22:19<59:44,  8.49it/s]

 28%|█████████▋                        | 12086/42525 [22:19<1:06:44,  7.60it/s]

 28%|█████████▋                        | 12088/42525 [22:19<1:06:57,  7.58it/s]

 28%|█████████▋                        | 12090/42525 [22:20<1:05:13,  7.78it/s]

 28%|█████████▋                        | 12091/42525 [22:20<1:04:06,  7.91it/s]

 28%|█████████▋                        | 12094/42525 [22:20<1:00:24,  8.40it/s]

 28%|█████████▋                        | 12097/42525 [22:20<1:04:27,  7.87it/s]

 28%|██████████▏                         | 12100/42525 [22:21<59:52,  8.47it/s]

 28%|██████████▏                         | 12103/42525 [22:21<54:59,  9.22it/s]

 28%|██████████▏                         | 12107/42525 [22:21<55:18,  9.17it/s]

 28%|██████████▎                         | 12110/42525 [22:22<57:34,  8.80it/s]

 28%|█████████▋                        | 12112/42525 [22:22<1:00:11,  8.42it/s]

 28%|██████████▎                         | 12114/42525 [22:22<58:28,  8.67it/s]

 28%|██████████▎                         | 12118/42525 [22:23<52:45,  9.61it/s]

 29%|██████████▎                         | 12121/42525 [22:23<54:12,  9.35it/s]

 29%|██████████▎                         | 12123/42525 [22:23<58:26,  8.67it/s]

 29%|██████████▎                         | 12125/42525 [22:23<54:36,  9.28it/s]

 29%|██████████▎                         | 12127/42525 [22:24<57:29,  8.81it/s]

 29%|█████████▋                        | 12130/42525 [22:24<1:00:56,  8.31it/s]

 29%|█████████▋                        | 12132/42525 [22:24<1:06:08,  7.66it/s]

 29%|█████████▋                        | 12135/42525 [22:25<1:00:41,  8.34it/s]

 29%|█████████▋                        | 12137/42525 [22:25<1:02:51,  8.06it/s]

 29%|█████████▋                        | 12140/42525 [22:25<1:01:25,  8.25it/s]

 29%|██████████▎                         | 12143/42525 [22:26<57:05,  8.87it/s]

 29%|██████████▎                         | 12146/42525 [22:26<54:39,  9.26it/s]

 29%|██████████▎                         | 12149/42525 [22:26<53:30,  9.46it/s]

 29%|██████████▎                         | 12150/42525 [22:26<58:34,  8.64it/s]

 29%|██████████▎                         | 12154/42525 [22:27<54:38,  9.26it/s]

 29%|██████████▎                         | 12157/42525 [22:27<57:10,  8.85it/s]

 29%|██████████▎                         | 12161/42525 [22:28<53:25,  9.47it/s]

 29%|██████████▎                         | 12163/42525 [22:28<53:43,  9.42it/s]

 29%|██████████▎                         | 12165/42525 [22:28<57:01,  8.87it/s]

 29%|██████████▎                         | 12166/42525 [22:28<55:19,  9.15it/s]

 29%|██████████▎                         | 12170/42525 [22:29<54:20,  9.31it/s]

 29%|██████████▎                         | 12174/42525 [22:29<51:18,  9.86it/s]

 29%|██████████▎                         | 12177/42525 [22:29<50:54,  9.93it/s]

 29%|██████████▎                         | 12179/42525 [22:30<57:20,  8.82it/s]

 29%|██████████▎                         | 12181/42525 [22:30<54:03,  9.35it/s]

 29%|██████████▎                         | 12183/42525 [22:30<53:39,  9.43it/s]

 29%|█████████▋                        | 12186/42525 [22:30<1:00:27,  8.36it/s]

 29%|█████████▋                        | 12187/42525 [22:30<1:03:35,  7.95it/s]

 29%|██████████▎                         | 12190/42525 [22:31<58:59,  8.57it/s]

 29%|█████████▋                        | 12192/42525 [22:31<1:04:27,  7.84it/s]

 29%|██████████▎                         | 12194/42525 [22:31<57:59,  8.72it/s]

 29%|██████████▎                         | 12197/42525 [22:32<55:55,  9.04it/s]

 29%|██████████▎                         | 12200/42525 [22:32<57:00,  8.87it/s]

 29%|██████████▎                         | 12203/42525 [22:32<58:34,  8.63it/s]

 29%|█████████▊                        | 12205/42525 [22:33<1:00:14,  8.39it/s]

 29%|██████████▎                         | 12207/42525 [22:33<57:00,  8.86it/s]

 29%|█████████▊                        | 12209/42525 [22:33<1:02:59,  8.02it/s]

 29%|██████████▎                         | 12211/42525 [22:33<57:18,  8.82it/s]

 29%|█████████▊                        | 12213/42525 [22:33<1:01:24,  8.23it/s]

 29%|██████████▎                         | 12217/42525 [22:34<52:56,  9.54it/s]

 29%|██████████▎                         | 12221/42525 [22:34<50:32,  9.99it/s]

 29%|██████████▎                         | 12225/42525 [22:35<49:58, 10.11it/s]

 29%|██████████▎                         | 12229/42525 [22:35<49:24, 10.22it/s]

 29%|██████████▎                         | 12232/42525 [22:35<55:27,  9.10it/s]

 29%|██████████▎                         | 12235/42525 [22:36<54:39,  9.24it/s]

 29%|██████████▎                         | 12237/42525 [22:36<53:00,  9.52it/s]

 29%|██████████▎                         | 12240/42525 [22:36<51:00,  9.90it/s]

 29%|██████████▎                         | 12243/42525 [22:37<50:28, 10.00it/s]

 29%|██████████▎                         | 12245/42525 [22:37<56:55,  8.86it/s]

 29%|██████████▎                         | 12247/42525 [22:37<59:01,  8.55it/s]

 29%|██████████▎                         | 12249/42525 [22:37<57:13,  8.82it/s]

 29%|██████████▎                         | 12251/42525 [22:37<59:44,  8.45it/s]

 29%|██████████▎                         | 12253/42525 [22:38<59:48,  8.44it/s]

 29%|██████████▍                         | 12256/42525 [22:38<54:25,  9.27it/s]

 29%|██████████▍                         | 12260/42525 [22:38<52:06,  9.68it/s]

 29%|██████████▍                         | 12263/42525 [22:39<58:22,  8.64it/s]

 29%|██████████▍                         | 12267/42525 [22:39<53:55,  9.35it/s]

 29%|██████████▍                         | 12269/42525 [22:39<52:16,  9.65it/s]

 29%|██████████▍                         | 12273/42525 [22:40<53:03,  9.50it/s]

 29%|██████████▍                         | 12276/42525 [22:40<52:48,  9.55it/s]

 29%|██████████▍                         | 12278/42525 [22:40<54:09,  9.31it/s]

 29%|██████████▍                         | 12281/42525 [22:41<53:36,  9.40it/s]

 29%|██████████▍                         | 12283/42525 [22:41<58:49,  8.57it/s]

 29%|██████████▍                         | 12287/42525 [22:41<52:28,  9.60it/s]

 29%|██████████▍                         | 12290/42525 [22:42<52:55,  9.52it/s]

 29%|██████████▍                         | 12292/42525 [22:42<53:52,  9.35it/s]

 29%|██████████▍                         | 12295/42525 [22:42<53:54,  9.35it/s]

 29%|██████████▍                         | 12298/42525 [22:43<54:48,  9.19it/s]

 29%|██████████▍                         | 12300/42525 [22:43<52:26,  9.61it/s]

 29%|██████████▍                         | 12303/42525 [22:43<52:09,  9.66it/s]

 29%|██████████▍                         | 12306/42525 [22:43<56:05,  8.98it/s]

 29%|██████████▍                         | 12308/42525 [22:44<59:52,  8.41it/s]

 29%|█████████▊                        | 12311/42525 [22:44<1:00:16,  8.35it/s]

 29%|██████████▍                         | 12313/42525 [22:44<57:04,  8.82it/s]

 29%|█████████▊                        | 12315/42525 [22:44<1:00:58,  8.26it/s]

 29%|█████████▊                        | 12317/42525 [22:45<1:00:29,  8.32it/s]

 29%|█████████▊                        | 12320/42525 [22:45<1:01:19,  8.21it/s]

 29%|█████████▊                        | 12322/42525 [22:45<1:01:10,  8.23it/s]

 29%|██████████▍                         | 12325/42525 [22:46<59:56,  8.40it/s]

 29%|██████████▍                         | 12327/42525 [22:46<56:46,  8.87it/s]

 29%|██████████▍                         | 12328/42525 [22:46<55:08,  9.13it/s]

 29%|██████████▍                         | 12331/42525 [22:46<59:11,  8.50it/s]

 29%|█████████▊                        | 12333/42525 [22:47<1:02:11,  8.09it/s]

 29%|██████████▍                         | 12336/42525 [22:47<57:51,  8.70it/s]

 29%|██████████▍                         | 12338/42525 [22:47<54:28,  9.24it/s]

 29%|██████████▍                         | 12341/42525 [22:47<57:46,  8.71it/s]

 29%|██████████▍                         | 12343/42525 [22:48<57:02,  8.82it/s]

 29%|██████████▍                         | 12347/42525 [22:48<52:00,  9.67it/s]

 29%|██████████▍                         | 12350/42525 [22:48<54:22,  9.25it/s]

 29%|██████████▍                         | 12354/42525 [22:49<53:37,  9.38it/s]

 29%|██████████▍                         | 12358/42525 [22:49<50:47,  9.90it/s]

 29%|██████████▍                         | 12362/42525 [22:50<49:40, 10.12it/s]

 29%|██████████▍                         | 12364/42525 [22:50<54:54,  9.15it/s]

 29%|██████████▍                         | 12367/42525 [22:50<54:54,  9.16it/s]

 29%|██████████▍                         | 12370/42525 [22:51<52:18,  9.61it/s]

 29%|██████████▍                         | 12372/42525 [22:51<52:55,  9.50it/s]

 29%|██████████▍                         | 12374/42525 [22:51<57:46,  8.70it/s]

 29%|██████████▍                         | 12376/42525 [22:51<57:24,  8.75it/s]

 29%|██████████▍                         | 12379/42525 [22:52<59:14,  8.48it/s]

 29%|██████████▍                         | 12382/42525 [22:52<59:45,  8.41it/s]

 29%|██████████▍                         | 12385/42525 [22:52<54:22,  9.24it/s]

 29%|██████████▍                         | 12387/42525 [22:52<54:56,  9.14it/s]

 29%|██████████▍                         | 12389/42525 [22:53<57:07,  8.79it/s]

 29%|██████████▍                         | 12393/42525 [22:53<51:53,  9.68it/s]

 29%|██████████▍                         | 12395/42525 [22:53<52:56,  9.48it/s]

 29%|██████████▍                         | 12396/42525 [22:53<55:12,  9.10it/s]

 29%|██████████▍                         | 12399/42525 [22:54<56:35,  8.87it/s]

 29%|█████████▉                        | 12401/42525 [22:54<1:00:20,  8.32it/s]

 29%|██████████▍                         | 12402/42525 [22:54<57:40,  8.70it/s]

 29%|██████████▌                         | 12405/42525 [22:54<54:41,  9.18it/s]

 29%|██████████▌                         | 12409/42525 [22:55<53:53,  9.31it/s]

 29%|██████████▌                         | 12411/42525 [22:55<52:23,  9.58it/s]

 29%|██████████▌                         | 12415/42525 [22:56<51:40,  9.71it/s]

 29%|██████████▌                         | 12417/42525 [22:56<58:07,  8.63it/s]

 29%|█████████▉                        | 12419/42525 [22:56<1:05:12,  7.69it/s]

 29%|█████████▉                        | 12421/42525 [22:56<1:00:09,  8.34it/s]

 29%|██████████▌                         | 12423/42525 [22:57<56:32,  8.87it/s]

 29%|██████████▌                         | 12426/42525 [22:57<53:59,  9.29it/s]

 29%|██████████▌                         | 12429/42525 [22:57<56:58,  8.80it/s]

 29%|██████████▌                         | 12432/42525 [22:57<53:13,  9.42it/s]

 29%|██████████▌                         | 12435/42525 [22:58<51:23,  9.76it/s]

 29%|█████████▉                        | 12437/42525 [22:58<1:00:49,  8.24it/s]

 29%|██████████▌                         | 12441/42525 [22:58<52:59,  9.46it/s]

 29%|██████████▌                         | 12443/42525 [22:59<54:08,  9.26it/s]

 29%|██████████▌                         | 12446/42525 [22:59<53:29,  9.37it/s]

 29%|██████████▌                         | 12448/42525 [22:59<51:37,  9.71it/s]

 29%|██████████▌                         | 12450/42525 [22:59<55:03,  9.10it/s]

 29%|██████████▌                         | 12453/42525 [23:00<55:35,  9.02it/s]

 29%|██████████▌                         | 12456/42525 [23:00<52:48,  9.49it/s]

 29%|██████████▌                         | 12459/42525 [23:00<54:08,  9.25it/s]

 29%|█████████▉                        | 12461/42525 [23:01<1:02:27,  8.02it/s]

 29%|██████████▌                         | 12463/42525 [23:01<58:20,  8.59it/s]

 29%|██████████▌                         | 12467/42525 [23:01<52:16,  9.58it/s]

 29%|██████████▌                         | 12470/42525 [23:02<53:03,  9.44it/s]

 29%|██████████▌                         | 12472/42525 [23:02<55:46,  8.98it/s]

 29%|█████████▉                        | 12474/42525 [23:02<1:04:19,  7.79it/s]

 29%|██████████▌                         | 12476/42525 [23:02<59:42,  8.39it/s]

 29%|██████████▌                         | 12480/42525 [23:03<52:22,  9.56it/s]

 29%|██████████▌                         | 12483/42525 [23:03<53:48,  9.30it/s]

 29%|██████████▌                         | 12485/42525 [23:03<53:56,  9.28it/s]

 29%|██████████▌                         | 12486/42525 [23:03<58:51,  8.51it/s]

 29%|██████████▌                         | 12489/42525 [23:04<58:04,  8.62it/s]

 29%|██████████▌                         | 12491/42525 [23:04<56:07,  8.92it/s]

 29%|██████████▌                         | 12495/42525 [23:04<54:26,  9.19it/s]

 29%|██████████▌                         | 12498/42525 [23:05<58:27,  8.56it/s]

 29%|██████████▌                         | 12501/42525 [23:05<53:51,  9.29it/s]

 29%|█████████▉                        | 12503/42525 [23:05<1:02:07,  8.05it/s]

 29%|██████████▌                         | 12507/42525 [23:06<53:56,  9.28it/s]

 29%|██████████▌                         | 12510/42525 [23:06<54:33,  9.17it/s]

 29%|██████████▌                         | 12511/42525 [23:06<53:58,  9.27it/s]

 29%|██████████▌                         | 12515/42525 [23:07<53:41,  9.31it/s]

 29%|██████████▌                         | 12518/42525 [23:07<53:19,  9.38it/s]

 29%|██████████▌                         | 12521/42525 [23:07<53:36,  9.33it/s]

 29%|██████████▌                         | 12523/42525 [23:08<51:46,  9.66it/s]

 29%|██████████▌                         | 12526/42525 [23:08<51:39,  9.68it/s]

 29%|██████████▌                         | 12527/42525 [23:08<55:36,  8.99it/s]

 29%|██████████▌                         | 12529/42525 [23:08<57:53,  8.63it/s]

 29%|██████████▌                         | 12532/42525 [23:09<57:12,  8.74it/s]

 29%|██████████▌                         | 12535/42525 [23:09<55:48,  8.96it/s]

 29%|██████████▌                         | 12539/42525 [23:09<51:37,  9.68it/s]

 29%|██████████▌                         | 12541/42525 [23:09<50:23,  9.92it/s]

 29%|██████████▌                         | 12543/42525 [23:10<50:58,  9.80it/s]

 30%|██████████▌                         | 12545/42525 [23:10<53:43,  9.30it/s]

 30%|██████████▌                         | 12548/42525 [23:10<57:40,  8.66it/s]

 30%|██████████                        | 12549/42525 [23:10<1:00:58,  8.19it/s]

 30%|██████████                        | 12552/42525 [23:11<1:03:02,  7.92it/s]

 30%|██████████▋                         | 12555/42525 [23:11<57:01,  8.76it/s]

 30%|██████████▋                         | 12557/42525 [23:11<54:53,  9.10it/s]

 30%|██████████▋                         | 12559/42525 [23:12<59:24,  8.41it/s]

 30%|██████████▋                         | 12563/42525 [23:12<52:28,  9.51it/s]

 30%|██████████▋                         | 12564/42525 [23:12<52:30,  9.51it/s]

 30%|██████████▋                         | 12568/42525 [23:12<51:36,  9.67it/s]

 30%|██████████▋                         | 12571/42525 [23:13<52:17,  9.55it/s]

 30%|██████████▋                         | 12574/42525 [23:13<51:06,  9.77it/s]

 30%|██████████▋                         | 12577/42525 [23:13<52:37,  9.48it/s]

 30%|██████████▋                         | 12580/42525 [23:14<51:38,  9.66it/s]

 30%|██████████▋                         | 12583/42525 [23:14<55:21,  9.02it/s]

 30%|██████████▋                         | 12586/42525 [23:14<55:04,  9.06it/s]

 30%|██████████▋                         | 12590/42525 [23:15<51:02,  9.77it/s]

 30%|██████████▋                         | 12593/42525 [23:15<51:23,  9.71it/s]

 30%|██████████▋                         | 12597/42525 [23:16<52:00,  9.59it/s]

 30%|██████████▋                         | 12599/42525 [23:16<50:52,  9.80it/s]

 30%|██████████▋                         | 12602/42525 [23:16<52:56,  9.42it/s]

 30%|██████████▋                         | 12605/42525 [23:16<51:11,  9.74it/s]

 30%|██████████▋                         | 12607/42525 [23:17<56:57,  8.75it/s]

 30%|██████████                        | 12608/42525 [23:17<1:00:38,  8.22it/s]

 30%|██████████▋                         | 12612/42525 [23:17<56:06,  8.89it/s]

 30%|██████████▋                         | 12615/42525 [23:18<55:31,  8.98it/s]

 30%|██████████▋                         | 12618/42525 [23:18<52:38,  9.47it/s]

 30%|██████████▋                         | 12621/42525 [23:18<56:05,  8.89it/s]

 30%|██████████▋                         | 12624/42525 [23:19<53:32,  9.31it/s]

 30%|██████████▋                         | 12628/42525 [23:19<50:42,  9.83it/s]

 30%|██████████▋                         | 12631/42525 [23:19<52:51,  9.43it/s]

 30%|██████████                        | 12633/42525 [23:20<1:00:30,  8.23it/s]

 30%|██████████                        | 12635/42525 [23:20<1:06:26,  7.50it/s]

 30%|██████████▋                         | 12639/42525 [23:20<54:47,  9.09it/s]

 30%|██████████▋                         | 12641/42525 [23:20<52:17,  9.52it/s]

 30%|██████████▋                         | 12645/42525 [23:21<52:09,  9.55it/s]

 30%|██████████▋                         | 12649/42525 [23:21<49:52,  9.98it/s]

 30%|██████████▋                         | 12653/42525 [23:22<48:49, 10.20it/s]

 30%|██████████▋                         | 12655/42525 [23:22<49:31, 10.05it/s]

 30%|██████████▋                         | 12658/42525 [23:22<51:40,  9.63it/s]

 30%|██████████▋                         | 12661/42525 [23:23<58:04,  8.57it/s]

 30%|██████████                        | 12663/42525 [23:23<1:01:13,  8.13it/s]

 30%|██████████▏                       | 12666/42525 [23:23<1:01:27,  8.10it/s]

 30%|██████████▋                         | 12670/42525 [23:24<53:44,  9.26it/s]

 30%|██████████▋                         | 12673/42525 [23:24<57:32,  8.65it/s]

 30%|██████████▋                         | 12676/42525 [23:24<52:46,  9.43it/s]

 30%|██████████▋                         | 12679/42525 [23:25<55:42,  8.93it/s]

 30%|██████████▋                         | 12682/42525 [23:25<52:58,  9.39it/s]

 30%|██████████▋                         | 12684/42525 [23:25<59:38,  8.34it/s]

 30%|██████████▋                         | 12686/42525 [23:25<57:43,  8.62it/s]

 30%|██████████▋                         | 12689/42525 [23:26<59:56,  8.30it/s]

 30%|██████████▋                         | 12692/42525 [23:26<56:05,  8.87it/s]

 30%|██████████▋                         | 12695/42525 [23:26<54:25,  9.14it/s]

 30%|██████████▏                       | 12697/42525 [23:27<1:02:40,  7.93it/s]

 30%|██████████▏                       | 12699/42525 [23:27<1:03:43,  7.80it/s]

 30%|██████████▊                         | 12702/42525 [23:27<58:10,  8.54it/s]

 30%|██████████▊                         | 12704/42525 [23:27<57:52,  8.59it/s]

 30%|██████████▊                         | 12707/42525 [23:28<54:58,  9.04it/s]

 30%|██████████▊                         | 12711/42525 [23:28<50:42,  9.80it/s]

 30%|██████████▊                         | 12714/42525 [23:29<55:34,  8.94it/s]

 30%|██████████▊                         | 12717/42525 [23:29<59:01,  8.42it/s]

 30%|██████████▏                       | 12719/42525 [23:29<1:02:32,  7.94it/s]

 30%|██████████▊                         | 12723/42525 [23:30<53:31,  9.28it/s]

 30%|██████████▊                         | 12727/42525 [23:30<51:39,  9.61it/s]

 30%|██████████▊                         | 12729/42525 [23:30<52:50,  9.40it/s]

 30%|██████████▊                         | 12731/42525 [23:30<53:20,  9.31it/s]

 30%|██████████▊                         | 12732/42525 [23:31<53:47,  9.23it/s]

 30%|██████████▊                         | 12734/42525 [23:31<56:53,  8.73it/s]

 30%|██████████▏                       | 12737/42525 [23:31<1:00:21,  8.23it/s]

 30%|██████████▏                       | 12739/42525 [23:31<1:02:10,  7.98it/s]

 30%|██████████▏                       | 12741/42525 [23:32<1:01:30,  8.07it/s]

 30%|██████████▊                         | 12743/42525 [23:32<55:36,  8.93it/s]

 30%|██████████▏                       | 12746/42525 [23:32<1:01:26,  8.08it/s]

 30%|██████████▏                       | 12747/42525 [23:32<1:04:18,  7.72it/s]

 30%|██████████▏                       | 12750/42525 [23:33<1:02:45,  7.91it/s]

 30%|██████████▊                         | 12754/42525 [23:33<54:16,  9.14it/s]

 30%|██████████▊                         | 12757/42525 [23:33<55:31,  8.94it/s]

 30%|██████████▊                         | 12760/42525 [23:34<58:55,  8.42it/s]

 30%|██████████▊                         | 12762/42525 [23:34<58:41,  8.45it/s]

 30%|██████████▊                         | 12763/42525 [23:34<59:58,  8.27it/s]

 30%|██████████▏                       | 12766/42525 [23:35<1:03:30,  7.81it/s]

 30%|██████████▏                       | 12768/42525 [23:35<1:00:36,  8.18it/s]

 30%|██████████▊                         | 12771/42525 [23:35<56:54,  8.71it/s]

 30%|██████████▊                         | 12774/42525 [23:35<51:58,  9.54it/s]

 30%|██████████▊                         | 12777/42525 [23:36<50:44,  9.77it/s]

 30%|██████████▊                         | 12779/42525 [23:36<58:16,  8.51it/s]

 30%|██████████▊                         | 12781/42525 [23:36<56:33,  8.76it/s]

 30%|██████████▏                       | 12783/42525 [23:36<1:00:33,  8.19it/s]

 30%|██████████▊                         | 12787/42525 [23:37<52:51,  9.38it/s]

 30%|██████████▊                         | 12789/42525 [23:37<57:17,  8.65it/s]

 30%|██████████▊                         | 12791/42525 [23:37<53:23,  9.28it/s]

 30%|██████████▊                         | 12793/42525 [23:38<54:32,  9.08it/s]

 30%|██████████▊                         | 12797/42525 [23:38<52:25,  9.45it/s]

 30%|██████████▊                         | 12801/42525 [23:38<50:10,  9.87it/s]

 30%|██████████▊                         | 12804/42525 [23:39<49:56,  9.92it/s]

 30%|██████████▊                         | 12807/42525 [23:39<50:16,  9.85it/s]

 30%|██████████▊                         | 12810/42525 [23:39<50:15,  9.85it/s]

 30%|██████████▊                         | 12811/42525 [23:39<53:28,  9.26it/s]

 30%|██████████▊                         | 12813/42525 [23:40<52:00,  9.52it/s]

 30%|██████████▊                         | 12816/42525 [23:40<53:15,  9.30it/s]

 30%|██████████▊                         | 12819/42525 [23:40<51:33,  9.60it/s]

 30%|██████████▊                         | 12821/42525 [23:40<52:39,  9.40it/s]

 30%|██████████▊                         | 12823/42525 [23:41<59:07,  8.37it/s]

 30%|██████████▊                         | 12825/42525 [23:41<54:28,  9.09it/s]

 30%|██████████▊                         | 12828/42525 [23:41<54:13,  9.13it/s]

 30%|██████████▊                         | 12830/42525 [23:41<53:30,  9.25it/s]

 30%|██████████▊                         | 12834/42525 [23:42<49:35,  9.98it/s]

 30%|██████████▊                         | 12837/42525 [23:42<53:22,  9.27it/s]

 30%|██████████▊                         | 12841/42525 [23:43<50:00,  9.89it/s]

 30%|██████████▊                         | 12842/42525 [23:43<51:48,  9.55it/s]

 30%|██████████▊                         | 12846/42525 [23:43<50:51,  9.73it/s]

 30%|██████████▉                         | 12850/42525 [23:44<52:07,  9.49it/s]

 30%|██████████▉                         | 12852/42525 [23:44<50:40,  9.76it/s]

 30%|██████████▉                         | 12856/42525 [23:44<50:27,  9.80it/s]

 30%|██████████▉                         | 12858/42525 [23:44<55:58,  8.83it/s]

 30%|██████████▉                         | 12860/42525 [23:45<53:56,  9.17it/s]

 30%|██████████▉                         | 12864/42525 [23:45<52:30,  9.42it/s]

 30%|██████████▉                         | 12867/42525 [23:45<51:31,  9.59it/s]

 30%|██████████▉                         | 12870/42525 [23:46<52:10,  9.47it/s]

 30%|██████████▉                         | 12872/42525 [23:46<50:29,  9.79it/s]

 30%|██████████▉                         | 12875/42525 [23:46<51:43,  9.55it/s]

 30%|██████████▉                         | 12877/42525 [23:46<53:58,  9.15it/s]

 30%|██████████▉                         | 12879/42525 [23:47<58:22,  8.46it/s]

 30%|██████████▎                       | 12882/42525 [23:47<1:00:34,  8.16it/s]

 30%|██████████▉                         | 12884/42525 [23:47<57:12,  8.64it/s]

 30%|██████████▉                         | 12887/42525 [23:48<55:02,  8.97it/s]

 30%|██████████▉                         | 12889/42525 [23:48<58:52,  8.39it/s]

 30%|██████████▎                       | 12890/42525 [23:48<1:02:38,  7.89it/s]

 30%|██████████▎                       | 12892/42525 [23:48<1:01:48,  7.99it/s]

 30%|██████████▉                         | 12896/42525 [23:49<53:46,  9.18it/s]

 30%|██████████▉                         | 12900/42525 [23:49<50:38,  9.75it/s]

 30%|██████████▉                         | 12902/42525 [23:49<54:34,  9.05it/s]

 30%|██████████▉                         | 12905/42525 [23:50<54:12,  9.11it/s]

 30%|██████████▉                         | 12909/42525 [23:50<53:38,  9.20it/s]

 30%|██████████▉                         | 12912/42525 [23:50<51:57,  9.50it/s]

 30%|██████████▉                         | 12915/42525 [23:51<56:19,  8.76it/s]

 30%|██████████▉                         | 12917/42525 [23:51<55:53,  8.83it/s]

 30%|██████████▉                         | 12919/42525 [23:51<55:38,  8.87it/s]

 30%|██████████▉                         | 12922/42525 [23:51<52:16,  9.44it/s]

 30%|██████████▉                         | 12925/42525 [23:52<54:58,  8.97it/s]

 30%|██████████▉                         | 12929/42525 [23:52<53:49,  9.16it/s]

 30%|██████████▉                         | 12931/42525 [23:52<53:45,  9.18it/s]

 30%|██████████▉                         | 12933/42525 [23:53<53:17,  9.25it/s]

 30%|██████████▉                         | 12934/42525 [23:53<53:39,  9.19it/s]

 30%|██████████▉                         | 12938/42525 [23:53<51:29,  9.58it/s]

 30%|██████████▉                         | 12941/42525 [23:54<55:58,  8.81it/s]

 30%|██████████▉                         | 12942/42525 [23:54<59:21,  8.31it/s]

 30%|██████████▉                         | 12945/42525 [23:54<54:41,  9.02it/s]

 30%|██████████▉                         | 12948/42525 [23:54<52:58,  9.31it/s]

 30%|██████████▉                         | 12951/42525 [23:55<55:45,  8.84it/s]

 30%|██████████▉                         | 12953/42525 [23:55<52:54,  9.31it/s]

 30%|██████████▉                         | 12956/42525 [23:55<57:18,  8.60it/s]

 30%|██████████▉                         | 12960/42525 [23:56<52:03,  9.47it/s]

 30%|██████████▉                         | 12962/42525 [23:56<54:44,  9.00it/s]

 30%|██████████▉                         | 12966/42525 [23:56<53:35,  9.19it/s]

 30%|██████████▉                         | 12969/42525 [23:57<58:11,  8.47it/s]

 31%|██████████▉                         | 12972/42525 [23:57<54:10,  9.09it/s]

 31%|██████████▉                         | 12976/42525 [23:57<51:08,  9.63it/s]

 31%|██████████▉                         | 12980/42525 [23:58<50:03,  9.84it/s]

 31%|██████████▉                         | 12983/42525 [23:58<49:37,  9.92it/s]

 31%|██████████▉                         | 12984/42525 [23:58<49:51,  9.87it/s]

 31%|██████████▉                         | 12987/42525 [23:59<50:05,  9.83it/s]

 31%|██████████▉                         | 12989/42525 [23:59<59:35,  8.26it/s]

 31%|██████████▍                       | 12992/42525 [23:59<1:00:59,  8.07it/s]

 31%|███████████                         | 12995/42525 [24:00<59:43,  8.24it/s]

 31%|██████████▍                       | 12997/42525 [24:00<1:01:22,  8.02it/s]

 31%|███████████                         | 12999/42525 [24:00<58:40,  8.39it/s]

 31%|███████████                         | 13001/42525 [24:00<56:31,  8.71it/s]

 31%|███████████                         | 13003/42525 [24:00<55:28,  8.87it/s]

 31%|███████████                         | 13005/42525 [24:01<52:46,  9.32it/s]

 31%|███████████                         | 13008/42525 [24:01<59:46,  8.23it/s]

 31%|███████████                         | 13011/42525 [24:01<59:12,  8.31it/s]

 31%|███████████                         | 13014/42525 [24:02<56:40,  8.68it/s]

 31%|██████████▍                       | 13016/42525 [24:02<1:01:06,  8.05it/s]

 31%|███████████                         | 13018/42525 [24:02<56:00,  8.78it/s]

 31%|███████████                         | 13021/42525 [24:02<52:30,  9.36it/s]

 31%|███████████                         | 13025/42525 [24:03<48:47, 10.08it/s]

 31%|███████████                         | 13028/42525 [24:03<49:15,  9.98it/s]

 31%|███████████                         | 13030/42525 [24:03<53:58,  9.11it/s]

 31%|███████████                         | 13032/42525 [24:04<56:26,  8.71it/s]

 31%|███████████                         | 13034/42525 [24:04<57:49,  8.50it/s]

 31%|██████████▍                       | 13036/42525 [24:04<1:00:18,  8.15it/s]

 31%|███████████                         | 13040/42525 [24:05<53:33,  9.17it/s]

 31%|███████████                         | 13042/42525 [24:05<57:36,  8.53it/s]

 31%|██████████▍                       | 13044/42525 [24:05<1:02:52,  7.82it/s]

 31%|██████████▍                       | 13046/42525 [24:05<1:01:40,  7.97it/s]

 31%|██████████▍                       | 13049/42525 [24:06<1:01:14,  8.02it/s]

 31%|███████████                         | 13051/42525 [24:06<58:33,  8.39it/s]

 31%|███████████                         | 13052/42525 [24:06<57:11,  8.59it/s]

 31%|███████████                         | 13055/42525 [24:06<53:50,  9.12it/s]

 31%|██████████▍                       | 13058/42525 [24:07<1:00:05,  8.17it/s]

 31%|██████████▍                       | 13060/42525 [24:07<1:01:37,  7.97it/s]

 31%|███████████                         | 13063/42525 [24:07<57:17,  8.57it/s]

 31%|███████████                         | 13067/42525 [24:08<54:13,  9.06it/s]

 31%|███████████                         | 13070/42525 [24:08<54:08,  9.07it/s]

 31%|███████████                         | 13072/42525 [24:08<51:54,  9.46it/s]

 31%|███████████                         | 13075/42525 [24:09<52:50,  9.29it/s]

 31%|███████████                         | 13078/42525 [24:09<53:04,  9.25it/s]

 31%|███████████                         | 13082/42525 [24:09<53:04,  9.25it/s]

 31%|███████████                         | 13084/42525 [24:10<56:26,  8.69it/s]

 31%|██████████▍                       | 13086/42525 [24:10<1:02:19,  7.87it/s]

 31%|███████████                         | 13087/42525 [24:10<59:34,  8.24it/s]

 31%|███████████                         | 13091/42525 [24:10<52:33,  9.33it/s]

 31%|███████████                         | 13094/42525 [24:11<56:36,  8.67it/s]

 31%|███████████                         | 13095/42525 [24:11<59:18,  8.27it/s]

 31%|███████████                         | 13099/42525 [24:11<55:17,  8.87it/s]

 31%|███████████                         | 13101/42525 [24:12<52:23,  9.36it/s]

 31%|███████████                         | 13104/42525 [24:12<54:28,  9.00it/s]

 31%|██████████▍                       | 13106/42525 [24:12<1:01:47,  7.94it/s]

 31%|███████████                         | 13109/42525 [24:13<54:51,  8.94it/s]

 31%|███████████                         | 13113/42525 [24:13<50:13,  9.76it/s]

 31%|███████████                         | 13117/42525 [24:13<48:39, 10.07it/s]

 31%|███████████                         | 13120/42525 [24:14<55:06,  8.89it/s]

 31%|███████████                         | 13123/42525 [24:14<51:28,  9.52it/s]

 31%|███████████                         | 13126/42525 [24:14<50:31,  9.70it/s]

 31%|███████████                         | 13129/42525 [24:15<50:52,  9.63it/s]

 31%|███████████                         | 13131/42525 [24:15<52:07,  9.40it/s]

 31%|███████████                         | 13134/42525 [24:15<50:06,  9.77it/s]

 31%|███████████                         | 13136/42525 [24:15<55:27,  8.83it/s]

 31%|███████████                         | 13138/42525 [24:16<54:32,  8.98it/s]

 31%|███████████                         | 13140/42525 [24:16<59:44,  8.20it/s]

 31%|███████████▏                        | 13143/42525 [24:16<56:12,  8.71it/s]

 31%|██████████▌                       | 13146/42525 [24:17<1:01:05,  8.02it/s]

 31%|███████████▏                        | 13148/42525 [24:17<56:57,  8.60it/s]

 31%|███████████▏                        | 13152/42525 [24:17<54:10,  9.04it/s]

 31%|███████████▏                        | 13154/42525 [24:18<58:14,  8.41it/s]

 31%|███████████▏                        | 13157/42525 [24:18<54:17,  9.02it/s]

 31%|███████████▏                        | 13161/42525 [24:18<51:59,  9.41it/s]

 31%|███████████▏                        | 13164/42525 [24:19<55:53,  8.75it/s]

 31%|███████████▏                        | 13167/42525 [24:19<52:10,  9.38it/s]

 31%|███████████▏                        | 13169/42525 [24:19<56:27,  8.67it/s]

 31%|███████████▏                        | 13172/42525 [24:20<53:00,  9.23it/s]

 31%|███████████▏                        | 13176/42525 [24:20<50:31,  9.68it/s]

 31%|███████████▏                        | 13180/42525 [24:20<48:36, 10.06it/s]

 31%|███████████▏                        | 13184/42525 [24:21<47:54, 10.21it/s]

 31%|███████████▏                        | 13188/42525 [24:21<47:18, 10.34it/s]

 31%|███████████▏                        | 13190/42525 [24:21<47:37, 10.27it/s]

 31%|███████████▏                        | 13193/42525 [24:22<52:21,  9.34it/s]

 31%|███████████▏                        | 13195/42525 [24:22<50:44,  9.63it/s]

 31%|███████████▏                        | 13199/42525 [24:22<51:36,  9.47it/s]

 31%|███████████▏                        | 13202/42525 [24:23<53:15,  9.18it/s]

 31%|███████████▏                        | 13204/42525 [24:23<52:52,  9.24it/s]

 31%|███████████▏                        | 13207/42525 [24:23<53:00,  9.22it/s]

 31%|███████████▏                        | 13210/42525 [24:23<52:14,  9.35it/s]

 31%|███████████▏                        | 13212/42525 [24:24<53:38,  9.11it/s]

 31%|███████████▏                        | 13215/42525 [24:24<57:01,  8.57it/s]

 31%|███████████▏                        | 13218/42525 [24:24<54:04,  9.03it/s]

 31%|███████████▏                        | 13221/42525 [24:25<51:14,  9.53it/s]

 31%|███████████▏                        | 13224/42525 [24:25<56:20,  8.67it/s]

 31%|███████████▏                        | 13226/42525 [24:25<57:47,  8.45it/s]

 31%|███████████▏                        | 13229/42525 [24:26<57:35,  8.48it/s]

 31%|███████████▏                        | 13231/42525 [24:26<55:55,  8.73it/s]

 31%|███████████▏                        | 13233/42525 [24:26<57:37,  8.47it/s]

 31%|███████████▏                        | 13236/42525 [24:26<53:35,  9.11it/s]

 31%|███████████▏                        | 13238/42525 [24:27<52:42,  9.26it/s]

 31%|███████████▏                        | 13241/42525 [24:27<50:14,  9.71it/s]

 31%|███████████▏                        | 13243/42525 [24:27<52:22,  9.32it/s]

 31%|███████████▏                        | 13245/42525 [24:27<57:07,  8.54it/s]

 31%|██████████▌                       | 13247/42525 [24:28<1:00:04,  8.12it/s]

 31%|███████████▏                        | 13250/42525 [24:28<58:37,  8.32it/s]

 31%|███████████▏                        | 13253/42525 [24:28<53:02,  9.20it/s]

 31%|███████████▏                        | 13255/42525 [24:29<54:52,  8.89it/s]

 31%|███████████▏                        | 13258/42525 [24:29<59:38,  8.18it/s]

 31%|███████████▏                        | 13262/42525 [24:29<52:31,  9.29it/s]

 31%|███████████▏                        | 13266/42525 [24:30<49:16,  9.90it/s]

 31%|███████████▏                        | 13268/42525 [24:30<54:11,  9.00it/s]

 31%|███████████▏                        | 13271/42525 [24:30<51:31,  9.46it/s]

 31%|███████████▏                        | 13274/42525 [24:31<51:40,  9.43it/s]

 31%|███████████▏                        | 13278/42525 [24:31<49:08,  9.92it/s]

 31%|███████████▏                        | 13282/42525 [24:31<47:57, 10.16it/s]

 31%|███████████▏                        | 13285/42525 [24:32<55:21,  8.80it/s]

 31%|███████████▏                        | 13287/42525 [24:32<59:05,  8.25it/s]

 31%|███████████▎                        | 13290/42525 [24:32<56:04,  8.69it/s]

 31%|███████████▎                        | 13293/42525 [24:33<54:57,  8.87it/s]

 31%|███████████▎                        | 13295/42525 [24:33<53:23,  9.12it/s]

 31%|███████████▎                        | 13297/42525 [24:33<55:36,  8.76it/s]

 31%|███████████▎                        | 13301/42525 [24:34<51:39,  9.43it/s]

 31%|███████████▎                        | 13304/42525 [24:34<50:40,  9.61it/s]

 31%|███████████▎                        | 13306/42525 [24:34<51:29,  9.46it/s]

 31%|███████████▎                        | 13308/42525 [24:34<57:12,  8.51it/s]

 31%|██████████▋                       | 13310/42525 [24:35<1:00:08,  8.10it/s]

 31%|███████████▎                        | 13313/42525 [24:35<54:37,  8.91it/s]

 31%|███████████▎                        | 13316/42525 [24:35<57:11,  8.51it/s]

 31%|███████████▎                        | 13319/42525 [24:36<54:16,  8.97it/s]

 31%|███████████▎                        | 13320/42525 [24:36<53:38,  9.08it/s]

 31%|███████████▎                        | 13324/42525 [24:36<52:19,  9.30it/s]

 31%|███████████▎                        | 13326/42525 [24:36<54:43,  8.89it/s]

 31%|███████████▎                        | 13329/42525 [24:37<55:24,  8.78it/s]

 31%|███████████▎                        | 13331/42525 [24:37<51:29,  9.45it/s]

 31%|███████████▎                        | 13335/42525 [24:37<48:59,  9.93it/s]

 31%|███████████▎                        | 13337/42525 [24:38<52:18,  9.30it/s]

 31%|███████████▎                        | 13341/42525 [24:38<50:23,  9.65it/s]

 31%|███████████▎                        | 13343/42525 [24:38<52:20,  9.29it/s]

 31%|███████████▎                        | 13344/42525 [24:38<51:43,  9.40it/s]

 31%|███████████▎                        | 13346/42525 [24:38<52:50,  9.20it/s]

 31%|███████████▎                        | 13349/42525 [24:39<51:25,  9.45it/s]

 31%|███████████▎                        | 13350/42525 [24:39<53:14,  9.13it/s]

 31%|███████████▎                        | 13353/42525 [24:39<54:19,  8.95it/s]

 31%|███████████▎                        | 13355/42525 [24:40<58:39,  8.29it/s]

 31%|██████████▋                       | 13357/42525 [24:40<1:04:13,  7.57it/s]

 31%|██████████▋                       | 13359/42525 [24:40<1:02:22,  7.79it/s]

 31%|██████████▋                       | 13362/42525 [24:40<1:00:00,  8.10it/s]

 31%|███████████▎                        | 13365/42525 [24:41<56:03,  8.67it/s]

 31%|███████████▎                        | 13367/42525 [24:41<57:01,  8.52it/s]

 31%|██████████▋                       | 13368/42525 [24:41<1:00:41,  8.01it/s]

 31%|██████████▋                       | 13371/42525 [24:42<1:03:09,  7.69it/s]

 31%|███████████▎                        | 13375/42525 [24:42<52:57,  9.17it/s]

 31%|███████████▎                        | 13379/42525 [24:42<49:42,  9.77it/s]

 31%|███████████▎                        | 13382/42525 [24:43<51:41,  9.40it/s]

 31%|███████████▎                        | 13384/42525 [24:43<51:24,  9.45it/s]

 31%|███████████▎                        | 13385/42525 [24:43<56:16,  8.63it/s]

 31%|███████████▎                        | 13389/42525 [24:43<53:40,  9.05it/s]

 31%|███████████▎                        | 13392/42525 [24:44<53:45,  9.03it/s]

 31%|███████████▎                        | 13395/42525 [24:44<56:42,  8.56it/s]

 32%|███████████▎                        | 13398/42525 [24:44<51:40,  9.39it/s]

 32%|███████████▎                        | 13401/42525 [24:45<54:45,  8.86it/s]

 32%|███████████▎                        | 13403/42525 [24:45<58:13,  8.34it/s]

 32%|███████████▎                        | 13406/42525 [24:45<53:53,  9.01it/s]

 32%|██████████▋                       | 13408/42525 [24:46<1:01:54,  7.84it/s]

 32%|███████████▎                        | 13411/42525 [24:46<54:43,  8.87it/s]

 32%|███████████▎                        | 13414/42525 [24:46<51:08,  9.49it/s]

 32%|███████████▎                        | 13417/42525 [24:47<54:04,  8.97it/s]

 32%|███████████▎                        | 13418/42525 [24:47<57:21,  8.46it/s]

 32%|███████████▎                        | 13422/42525 [24:47<54:18,  8.93it/s]

 32%|██████████▋                       | 13424/42525 [24:47<1:01:05,  7.94it/s]

 32%|███████████▎                        | 13428/42525 [24:48<53:26,  9.07it/s]

 32%|███████████▎                        | 13430/42525 [24:48<51:40,  9.39it/s]

 32%|███████████▎                        | 13432/42525 [24:48<50:41,  9.57it/s]

 32%|███████████▎                        | 13435/42525 [24:49<55:34,  8.72it/s]

 32%|███████████▍                        | 13438/42525 [24:49<51:48,  9.36it/s]

 32%|███████████▍                        | 13440/42525 [24:49<51:04,  9.49it/s]

 32%|███████████▍                        | 13444/42525 [24:50<49:21,  9.82it/s]

 32%|███████████▍                        | 13447/42525 [24:50<49:16,  9.84it/s]

 32%|███████████▍                        | 13449/42525 [24:50<57:58,  8.36it/s]

 32%|███████████▍                        | 13452/42525 [24:50<55:13,  8.77it/s]

 32%|███████████▍                        | 13455/42525 [24:51<51:32,  9.40it/s]

 32%|███████████▍                        | 13457/42525 [24:51<55:35,  8.72it/s]

 32%|███████████▍                        | 13458/42525 [24:51<59:44,  8.11it/s]

 32%|███████████▍                        | 13462/42525 [24:52<54:32,  8.88it/s]

 32%|███████████▍                        | 13466/42525 [24:52<49:55,  9.70it/s]

 32%|███████████▍                        | 13468/42525 [24:52<49:09,  9.85it/s]

 32%|███████████▍                        | 13470/42525 [24:52<50:14,  9.64it/s]

 32%|███████████▍                        | 13473/42525 [24:53<50:22,  9.61it/s]

 32%|███████████▍                        | 13476/42525 [24:53<51:32,  9.39it/s]

 32%|███████████▍                        | 13480/42525 [24:53<48:50,  9.91it/s]

 32%|███████████▍                        | 13483/42525 [24:54<48:48,  9.92it/s]

 32%|███████████▍                        | 13484/42525 [24:54<49:12,  9.83it/s]

 32%|███████████▍                        | 13487/42525 [24:54<49:40,  9.74it/s]

 32%|███████████▍                        | 13490/42525 [24:54<48:06, 10.06it/s]

 32%|███████████▍                        | 13494/42525 [24:55<47:13, 10.25it/s]

 32%|███████████▍                        | 13498/42525 [24:55<47:26, 10.20it/s]

 32%|███████████▍                        | 13502/42525 [24:56<49:44,  9.72it/s]

 32%|███████████▍                        | 13504/42525 [24:56<53:28,  9.05it/s]

 32%|██████████▊                       | 13506/42525 [24:56<1:01:12,  7.90it/s]

 32%|███████████▍                        | 13509/42525 [24:57<59:01,  8.19it/s]

 32%|███████████▍                        | 13512/42525 [24:57<59:13,  8.17it/s]

 32%|███████████▍                        | 13513/42525 [24:57<56:58,  8.49it/s]

 32%|███████████▍                        | 13517/42525 [24:57<53:45,  8.99it/s]

 32%|███████████▍                        | 13519/42525 [24:58<51:28,  9.39it/s]

 32%|███████████▍                        | 13523/42525 [24:58<51:46,  9.33it/s]

 32%|███████████▍                        | 13525/42525 [24:58<55:31,  8.70it/s]

 32%|███████████▍                        | 13529/42525 [24:59<51:52,  9.32it/s]

 32%|███████████▍                        | 13531/42525 [24:59<51:38,  9.36it/s]

 32%|███████████▍                        | 13533/42525 [24:59<55:16,  8.74it/s]

 32%|███████████▍                        | 13536/42525 [25:00<50:28,  9.57it/s]

 32%|███████████▍                        | 13539/42525 [25:00<57:39,  8.38it/s]

 32%|███████████▍                        | 13542/42525 [25:00<55:15,  8.74it/s]

 32%|███████████▍                        | 13543/42525 [25:00<57:31,  8.40it/s]

 32%|███████████▍                        | 13546/42525 [25:01<55:35,  8.69it/s]

 32%|███████████▍                        | 13549/42525 [25:01<54:13,  8.91it/s]

 32%|███████████▍                        | 13550/42525 [25:01<55:10,  8.75it/s]

 32%|███████████▍                        | 13552/42525 [25:01<52:46,  9.15it/s]

 32%|███████████▍                        | 13555/42525 [25:02<56:22,  8.56it/s]

 32%|███████████▍                        | 13557/42525 [25:02<52:59,  9.11it/s]

 32%|███████████▍                        | 13560/42525 [25:02<56:11,  8.59it/s]

 32%|███████████▍                        | 13562/42525 [25:03<57:12,  8.44it/s]

 32%|███████████▍                        | 13565/42525 [25:03<52:44,  9.15it/s]

 32%|███████████▍                        | 13569/42525 [25:03<49:17,  9.79it/s]

 32%|███████████▍                        | 13570/42525 [25:03<52:22,  9.21it/s]

 32%|███████████▍                        | 13574/42525 [25:04<50:02,  9.64it/s]

 32%|███████████▍                        | 13577/42525 [25:04<48:56,  9.86it/s]

 32%|███████████▍                        | 13580/42525 [25:04<51:43,  9.33it/s]

 32%|███████████▍                        | 13582/42525 [25:05<54:26,  8.86it/s]

 32%|███████████▌                        | 13586/42525 [25:05<49:37,  9.72it/s]

 32%|███████████▌                        | 13588/42525 [25:05<49:14,  9.79it/s]

 32%|███████████▌                        | 13592/42525 [25:06<47:30, 10.15it/s]

 32%|███████████▌                        | 13595/42525 [25:06<49:43,  9.70it/s]

 32%|███████████▌                        | 13597/42525 [25:06<48:39,  9.91it/s]

 32%|███████████▌                        | 13600/42525 [25:06<49:07,  9.81it/s]

 32%|███████████▌                        | 13603/42525 [25:07<48:18,  9.98it/s]

 32%|███████████▌                        | 13606/42525 [25:07<52:03,  9.26it/s]

 32%|███████████▌                        | 13608/42525 [25:07<52:24,  9.20it/s]

 32%|███████████▌                        | 13610/42525 [25:08<51:33,  9.35it/s]

 32%|███████████▌                        | 13613/42525 [25:08<58:06,  8.29it/s]

 32%|███████████▌                        | 13616/42525 [25:08<54:49,  8.79it/s]

 32%|███████████▌                        | 13619/42525 [25:09<52:35,  9.16it/s]

 32%|███████████▌                        | 13622/42525 [25:09<52:59,  9.09it/s]

 32%|███████████▌                        | 13623/42525 [25:09<56:55,  8.46it/s]

 32%|███████████▌                        | 13627/42525 [25:09<52:05,  9.25it/s]

 32%|███████████▌                        | 13631/42525 [25:10<48:52,  9.85it/s]

 32%|███████████▌                        | 13633/42525 [25:10<55:59,  8.60it/s]

 32%|███████████▌                        | 13636/42525 [25:10<51:30,  9.35it/s]

 32%|███████████▌                        | 13638/42525 [25:11<53:53,  8.93it/s]

 32%|███████████▌                        | 13639/42525 [25:11<53:13,  9.05it/s]

 32%|███████████▌                        | 13643/42525 [25:11<49:27,  9.73it/s]

 32%|███████████▌                        | 13646/42525 [25:11<49:14,  9.77it/s]

 32%|███████████▌                        | 13648/42525 [25:12<56:06,  8.58it/s]

 32%|███████████▌                        | 13649/42525 [25:12<55:35,  8.66it/s]

 32%|███████████▌                        | 13653/42525 [25:12<53:10,  9.05it/s]

 32%|███████████▌                        | 13656/42525 [25:13<51:26,  9.35it/s]

 32%|███████████▌                        | 13657/42525 [25:13<53:01,  9.07it/s]

 32%|███████████▌                        | 13660/42525 [25:13<58:54,  8.17it/s]

 32%|███████████▌                        | 13661/42525 [25:13<59:34,  8.07it/s]

 32%|███████████▌                        | 13664/42525 [25:14<57:26,  8.37it/s]

 32%|███████████▌                        | 13667/42525 [25:14<55:20,  8.69it/s]

 32%|███████████▌                        | 13670/42525 [25:14<53:55,  8.92it/s]

 32%|███████████▌                        | 13673/42525 [25:15<51:42,  9.30it/s]

 32%|███████████▌                        | 13674/42525 [25:15<51:19,  9.37it/s]

 32%|███████████▌                        | 13677/42525 [25:15<53:09,  9.05it/s]

 32%|███████████▌                        | 13681/42525 [25:15<50:55,  9.44it/s]

 32%|███████████▌                        | 13683/42525 [25:16<54:27,  8.83it/s]

 32%|███████████▌                        | 13684/42525 [25:16<53:52,  8.92it/s]

 32%|███████████▌                        | 13687/42525 [25:16<54:54,  8.75it/s]

 32%|███████████▌                        | 13689/42525 [25:16<54:17,  8.85it/s]

 32%|███████████▌                        | 13693/42525 [25:17<49:57,  9.62it/s]

 32%|███████████▌                        | 13697/42525 [25:17<50:26,  9.53it/s]

 32%|███████████▌                        | 13701/42525 [25:18<48:35,  9.89it/s]

 32%|███████████▌                        | 13703/42525 [25:18<53:56,  8.90it/s]

 32%|███████████▌                        | 13706/42525 [25:18<50:53,  9.44it/s]

 32%|███████████▌                        | 13709/42525 [25:18<53:53,  8.91it/s]

 32%|███████████▌                        | 13711/42525 [25:19<58:31,  8.20it/s]

 32%|███████████▌                        | 13713/42525 [25:19<57:45,  8.31it/s]

 32%|███████████▌                        | 13716/42525 [25:19<56:46,  8.46it/s]

 32%|███████████▌                        | 13719/42525 [25:20<54:35,  8.79it/s]

 32%|███████████▌                        | 13721/42525 [25:20<54:16,  8.84it/s]

 32%|███████████▌                        | 13724/42525 [25:20<56:16,  8.53it/s]

 32%|███████████▌                        | 13727/42525 [25:21<53:46,  8.93it/s]

 32%|███████████▌                        | 13730/42525 [25:21<50:49,  9.44it/s]

 32%|███████████▋                        | 13734/42525 [25:21<47:47, 10.04it/s]

 32%|███████████▋                        | 13736/42525 [25:21<49:15,  9.74it/s]

 32%|███████████▋                        | 13738/42525 [25:22<47:54, 10.01it/s]

 32%|███████████▋                        | 13741/42525 [25:22<49:02,  9.78it/s]

 32%|███████████▋                        | 13744/42525 [25:22<48:24,  9.91it/s]

 32%|███████████▋                        | 13747/42525 [25:23<49:19,  9.72it/s]

 32%|███████████▋                        | 13750/42525 [25:23<49:44,  9.64it/s]

 32%|███████████▋                        | 13754/42525 [25:23<50:48,  9.44it/s]

 32%|███████████▋                        | 13757/42525 [25:24<50:49,  9.43it/s]

 32%|███████████▋                        | 13760/42525 [25:24<49:57,  9.60it/s]

 32%|███████████▋                        | 13764/42525 [25:24<47:40, 10.05it/s]

 32%|███████████▋                        | 13766/42525 [25:25<56:30,  8.48it/s]

 32%|███████████                       | 13768/42525 [25:25<1:00:07,  7.97it/s]

 32%|███████████                       | 13770/42525 [25:25<1:00:48,  7.88it/s]

 32%|███████████▋                        | 13773/42525 [25:25<55:20,  8.66it/s]

 32%|███████████▋                        | 13775/42525 [25:26<53:15,  9.00it/s]

 32%|███████████▋                        | 13777/42525 [25:26<51:51,  9.24it/s]

 32%|███████████▋                        | 13780/42525 [25:26<53:16,  8.99it/s]

 32%|███████████▋                        | 13783/42525 [25:27<49:48,  9.62it/s]

 32%|███████████▋                        | 13787/42525 [25:27<47:25, 10.10it/s]

 32%|███████████▋                        | 13790/42525 [25:27<51:18,  9.33it/s]

 32%|███████████▋                        | 13791/42525 [25:27<50:47,  9.43it/s]

 32%|███████████▋                        | 13793/42525 [25:28<53:39,  8.93it/s]

 32%|███████████▋                        | 13797/42525 [25:28<52:09,  9.18it/s]

 32%|███████████▋                        | 13800/42525 [25:28<54:15,  8.82it/s]

 32%|███████████▋                        | 13803/42525 [25:29<52:16,  9.16it/s]

 32%|███████████▋                        | 13804/42525 [25:29<56:07,  8.53it/s]

 32%|███████████▋                        | 13807/42525 [25:29<57:25,  8.34it/s]

 32%|███████████▋                        | 13809/42525 [25:29<56:52,  8.41it/s]

 32%|███████████▋                        | 13811/42525 [25:30<53:27,  8.95it/s]

 32%|███████████▋                        | 13815/42525 [25:30<49:36,  9.65it/s]

 32%|███████████▋                        | 13817/42525 [25:30<54:28,  8.78it/s]

 32%|███████████▋                        | 13820/42525 [25:31<55:32,  8.61it/s]

 33%|███████████▋                        | 13822/42525 [25:31<58:37,  8.16it/s]

 33%|███████████▋                        | 13826/42525 [25:31<50:43,  9.43it/s]

 33%|███████████▋                        | 13829/42525 [25:32<48:53,  9.78it/s]

 33%|███████████▋                        | 13832/42525 [25:32<50:30,  9.47it/s]

 33%|███████████▋                        | 13834/42525 [25:32<48:59,  9.76it/s]

 33%|███████████▋                        | 13838/42525 [25:32<48:25,  9.87it/s]

 33%|███████████▋                        | 13840/42525 [25:33<49:51,  9.59it/s]

 33%|███████████▋                        | 13842/42525 [25:33<48:28,  9.86it/s]

 33%|███████████▋                        | 13845/42525 [25:33<55:00,  8.69it/s]

 33%|███████████▋                        | 13848/42525 [25:34<52:48,  9.05it/s]

 33%|███████████▋                        | 13850/42525 [25:34<53:54,  8.87it/s]

 33%|███████████▋                        | 13853/42525 [25:34<52:40,  9.07it/s]

 33%|███████████▋                        | 13854/42525 [25:34<53:24,  8.95it/s]

 33%|███████████▋                        | 13857/42525 [25:35<54:48,  8.72it/s]

 33%|███████████▋                        | 13859/42525 [25:35<56:30,  8.46it/s]

 33%|███████████▋                        | 13861/42525 [25:35<54:59,  8.69it/s]

 33%|███████████▋                        | 13865/42525 [25:36<51:03,  9.36it/s]

 33%|███████████▋                        | 13869/42525 [25:36<48:07,  9.93it/s]

 33%|███████████▋                        | 13871/42525 [25:36<49:48,  9.59it/s]

 33%|███████████▋                        | 13874/42525 [25:36<53:27,  8.93it/s]

 33%|███████████▋                        | 13875/42525 [25:37<57:20,  8.33it/s]

 33%|███████████▋                        | 13878/42525 [25:37<53:13,  8.97it/s]

 33%|███████████▊                        | 13882/42525 [25:37<49:09,  9.71it/s]

 33%|███████████▊                        | 13885/42525 [25:38<55:00,  8.68it/s]

 33%|███████████▊                        | 13886/42525 [25:38<54:12,  8.81it/s]

 33%|███████████▊                        | 13889/42525 [25:38<57:22,  8.32it/s]

 33%|███████████▊                        | 13890/42525 [25:38<58:41,  8.13it/s]

 33%|███████████                       | 13893/42525 [25:39<1:00:31,  7.88it/s]

 33%|███████████▊                        | 13896/42525 [25:39<52:56,  9.01it/s]

 33%|███████████▊                        | 13898/42525 [25:39<53:07,  8.98it/s]

 33%|███████████▊                        | 13901/42525 [25:40<52:51,  9.03it/s]

 33%|███████████▊                        | 13903/42525 [25:40<58:18,  8.18it/s]

 33%|███████████▊                        | 13907/42525 [25:40<50:20,  9.48it/s]

 33%|███████████▊                        | 13910/42525 [25:41<49:25,  9.65it/s]

 33%|███████████▊                        | 13914/42525 [25:41<47:31, 10.04it/s]

 33%|███████████▊                        | 13918/42525 [25:41<47:05, 10.13it/s]

 33%|███████████▊                        | 13920/42525 [25:41<46:43, 10.20it/s]

 33%|███████████▊                        | 13924/42525 [25:42<46:33, 10.24it/s]

 33%|███████████▊                        | 13927/42525 [25:42<50:06,  9.51it/s]

 33%|███████████▊                        | 13931/42525 [25:43<47:43,  9.99it/s]

 33%|███████████▊                        | 13935/42525 [25:43<46:57, 10.15it/s]

 33%|███████████▊                        | 13938/42525 [25:43<50:44,  9.39it/s]

 33%|███████████▊                        | 13940/42525 [25:44<55:02,  8.66it/s]

 33%|███████████▊                        | 13944/42525 [25:44<49:37,  9.60it/s]

 33%|███████████▊                        | 13947/42525 [25:44<48:17,  9.86it/s]

 33%|███████████▊                        | 13951/42525 [25:45<47:25, 10.04it/s]

 33%|███████████▊                        | 13952/42525 [25:45<49:16,  9.67it/s]

 33%|███████████▊                        | 13954/42525 [25:45<52:24,  9.09it/s]

 33%|███████████▊                        | 13957/42525 [25:45<50:57,  9.34it/s]

 33%|███████████▊                        | 13960/42525 [25:46<52:24,  9.08it/s]

 33%|███████████▊                        | 13963/42525 [25:46<52:32,  9.06it/s]

 33%|███████████▊                        | 13964/42525 [25:46<56:24,  8.44it/s]

 33%|███████████▊                        | 13967/42525 [25:47<53:58,  8.82it/s]

 33%|███████████▊                        | 13970/42525 [25:47<51:25,  9.25it/s]

 33%|███████████▊                        | 13973/42525 [25:47<50:06,  9.50it/s]

 33%|███████████▊                        | 13975/42525 [25:47<50:12,  9.48it/s]

 33%|███████████▊                        | 13976/42525 [25:47<51:50,  9.18it/s]

 33%|███████████▊                        | 13980/42525 [25:48<49:47,  9.55it/s]

 33%|███████████▊                        | 13982/42525 [25:48<53:29,  8.89it/s]

 33%|███████████▊                        | 13985/42525 [25:48<50:02,  9.51it/s]

 33%|███████████▊                        | 13989/42525 [25:49<50:29,  9.42it/s]

 33%|███████████▊                        | 13991/42525 [25:49<48:51,  9.73it/s]

 33%|███████████▊                        | 13994/42525 [25:49<53:41,  8.86it/s]

 33%|███████████▊                        | 13997/42525 [25:50<55:08,  8.62it/s]

 33%|███████████▊                        | 13999/42525 [25:50<55:37,  8.55it/s]

 33%|███████████▊                        | 14003/42525 [25:50<49:29,  9.61it/s]

 33%|███████████▊                        | 14007/42525 [25:51<48:36,  9.78it/s]

 33%|███████████▊                        | 14010/42525 [25:51<50:45,  9.36it/s]

 33%|███████████▊                        | 14012/42525 [25:51<54:43,  8.68it/s]

 33%|███████████▊                        | 14016/42525 [25:52<49:46,  9.55it/s]

 33%|███████████▊                        | 14018/42525 [25:52<53:57,  8.81it/s]

 33%|███████████▊                        | 14022/42525 [25:52<49:10,  9.66it/s]

 33%|███████████▊                        | 14025/42525 [25:53<49:16,  9.64it/s]

 33%|███████████▉                        | 14028/42525 [25:53<48:53,  9.72it/s]

 33%|███████████▉                        | 14029/42525 [25:53<49:41,  9.56it/s]

 33%|███████████▉                        | 14032/42525 [25:54<50:29,  9.41it/s]

 33%|███████████▉                        | 14034/42525 [25:54<52:00,  9.13it/s]

 33%|███████████▉                        | 14036/42525 [25:54<56:14,  8.44it/s]

 33%|███████████▉                        | 14037/42525 [25:54<55:30,  8.55it/s]

 33%|███████████▉                        | 14041/42525 [25:55<49:53,  9.51it/s]

 33%|███████████▉                        | 14044/42525 [25:55<51:34,  9.20it/s]

 33%|███████████▉                        | 14046/42525 [25:55<56:21,  8.42it/s]

 33%|███████████▉                        | 14050/42525 [25:55<49:43,  9.54it/s]

 33%|███████████▉                        | 14053/42525 [25:56<53:00,  8.95it/s]

 33%|███████████▉                        | 14056/42525 [25:56<49:48,  9.52it/s]

 33%|███████████▉                        | 14059/42525 [25:56<48:45,  9.73it/s]

 33%|███████████▉                        | 14061/42525 [25:57<53:58,  8.79it/s]

 33%|███████████▉                        | 14063/42525 [25:57<57:39,  8.23it/s]

 33%|███████████▉                        | 14065/42525 [25:57<53:45,  8.82it/s]

 33%|███████████▉                        | 14068/42525 [25:57<53:43,  8.83it/s]

 33%|███████████▉                        | 14071/42525 [25:58<53:11,  8.91it/s]

 33%|███████████▎                      | 14073/42525 [25:58<1:00:50,  7.79it/s]

 33%|███████████▉                        | 14076/42525 [25:58<58:16,  8.14it/s]

 33%|███████████▉                        | 14079/42525 [25:59<56:05,  8.45it/s]

 33%|███████████▉                        | 14082/42525 [25:59<52:49,  8.97it/s]

 33%|███████████▉                        | 14085/42525 [25:59<50:07,  9.46it/s]

 33%|███████████▉                        | 14086/42525 [26:00<51:22,  9.22it/s]

 33%|███████████▉                        | 14089/42525 [26:00<53:38,  8.84it/s]

 33%|███████████▉                        | 14092/42525 [26:00<50:40,  9.35it/s]

 33%|███████████▉                        | 14094/42525 [26:00<53:30,  8.86it/s]

 33%|███████████▉                        | 14096/42525 [26:01<54:21,  8.72it/s]

 33%|███████████▉                        | 14099/42525 [26:01<57:27,  8.25it/s]

 33%|███████████▉                        | 14102/42525 [26:01<53:03,  8.93it/s]

 33%|███████████▉                        | 14105/42525 [26:02<51:08,  9.26it/s]

 33%|███████████▉                        | 14107/42525 [26:02<53:08,  8.91it/s]

 33%|███████████▉                        | 14109/42525 [26:02<56:39,  8.36it/s]

 33%|███████████▉                        | 14111/42525 [26:02<55:17,  8.57it/s]

 33%|███████████▉                        | 14115/42525 [26:03<49:08,  9.63it/s]

 33%|███████████▉                        | 14117/42525 [26:03<53:31,  8.84it/s]

 33%|███████████▉                        | 14119/42525 [26:03<50:16,  9.42it/s]

 33%|███████████▉                        | 14122/42525 [26:04<55:31,  8.53it/s]

 33%|███████████▉                        | 14126/42525 [26:04<49:45,  9.51it/s]

 33%|███████████▉                        | 14128/42525 [26:04<48:15,  9.81it/s]

 33%|███████████▉                        | 14130/42525 [26:04<48:21,  9.79it/s]

 33%|███████████▉                        | 14133/42525 [26:05<52:08,  9.08it/s]

 33%|███████████▉                        | 14135/42525 [26:05<50:19,  9.40it/s]

 33%|███████████▉                        | 14138/42525 [26:05<52:07,  9.08it/s]

 33%|███████████▉                        | 14139/42525 [26:05<55:48,  8.48it/s]

 33%|███████████▉                        | 14143/42525 [26:06<51:42,  9.15it/s]

 33%|███████████▉                        | 14146/42525 [26:06<51:59,  9.10it/s]

 33%|███████████▉                        | 14149/42525 [26:07<51:51,  9.12it/s]

 33%|███████████▉                        | 14152/42525 [26:07<50:34,  9.35it/s]

 33%|███████████▉                        | 14154/42525 [26:07<48:59,  9.65it/s]

 33%|███████████▉                        | 14157/42525 [26:07<53:38,  8.82it/s]

 33%|███████████▉                        | 14160/42525 [26:08<49:49,  9.49it/s]

 33%|███████████▉                        | 14162/42525 [26:08<50:32,  9.35it/s]

 33%|███████████▉                        | 14165/42525 [26:08<51:09,  9.24it/s]

 33%|███████████▉                        | 14168/42525 [26:09<48:28,  9.75it/s]

 33%|███████████▉                        | 14169/42525 [26:09<48:46,  9.69it/s]

 33%|███████████▉                        | 14172/42525 [26:09<53:28,  8.84it/s]

 33%|████████████                        | 14175/42525 [26:09<59:41,  7.92it/s]

 33%|████████████                        | 14175/42525 [26:09<59:41,  7.92it/s]
  0%|                                                  | 0/788 [00:00<?, ?it/s]
  0%|                                          | 2/788 [00:00<00:42, 18.54it/s]

{'loss': '1.615', 'grad_norm': 'nan', 'learning_rate': '1.419e-05', 'epoch': '1'}

  1%|▏                                         | 4/788 [00:00<01:00, 13.05it/s]
  1%|▎                                         | 6/788 [00:00<01:05, 12.02it/s]

  1%|▍                                         | 8/788 [00:00<01:06, 11.77it/s]
  1%|▌                                        | 10/788 [00:00<00:59, 12.98it/s]

  2%|▌                                        | 12/788 [00:00<00:53, 14.45it/s]
  2%|▋                                        | 14/788 [00:01<00:56, 13.65it/s]

  2%|▊                                        | 16/788 [00:01<00:59, 12.90it/s]
  2%|▉                                        | 18/788 [00:01<01:04, 11.87it/s]

  3%|█                                        | 20/788 [00:01<01:10, 10.95it/s]
  3%|█▏                                       | 22/788 [00:01<01:10, 10.87it/s]

  3%|█▏                                       | 24/788 [00:01<01:06, 11.57it/s]
  3%|█▎                                       | 26/788 [00:02<01:04, 11.74it/s]

  4%|█▍                                       | 28/788 [00:02<01:03, 11.92it/s]
  4%|█▌                                       | 30/788 [00:02<01:01, 12.32it/s]

  4%|█▋                                       | 32/788 [00:02<01:00, 12.48it/s]
  4%|█▊                                       | 34/788 [00:02<01:01, 12.25it/s]

  5%|█▊                                       | 36/788 [00:02<01:04, 11.66it/s]
  5%|██                                       | 39/788 [00:03<00:58, 12.80it/s]

  5%|██▏                                      | 41/788 [00:03<00:54, 13.60it/s]
  5%|██▏                                      | 43/788 [00:03<00:55, 13.54it/s]

  6%|██▎                                      | 45/788 [00:03<00:53, 13.85it/s]

  6%|██▍                                      | 47/788 [00:03<01:00, 12.26it/s]
  6%|██▌                                      | 49/788 [00:03<00:58, 12.56it/s]

  7%|██▋                                      | 52/788 [00:04<00:49, 14.85it/s]
  7%|██▊                                      | 54/788 [00:04<00:51, 14.14it/s]

  7%|██▉                                      | 56/788 [00:04<00:50, 14.46it/s]
  7%|███                                      | 58/788 [00:04<00:52, 13.99it/s]

  8%|███                                      | 60/788 [00:04<00:53, 13.58it/s]
  8%|███▏                                     | 62/788 [00:04<00:56, 12.83it/s]

  8%|███▎                                     | 64/788 [00:05<01:01, 11.85it/s]
  8%|███▍                                     | 66/788 [00:05<00:59, 12.13it/s]

  9%|███▌                                     | 68/788 [00:05<00:59, 12.12it/s]

  9%|███▋                                     | 70/788 [00:05<01:04, 11.22it/s]
  9%|███▋                                     | 72/788 [00:05<00:59, 11.95it/s]

  9%|███▊                                     | 74/788 [00:05<01:04, 11.08it/s]
 10%|███▉                                     | 76/788 [00:06<00:59, 11.96it/s]

 10%|████                                     | 78/788 [00:06<01:01, 11.54it/s]
 10%|████▏                                    | 80/788 [00:06<01:03, 11.23it/s]

 10%|████▎                                    | 82/788 [00:06<01:06, 10.66it/s]
 11%|████▎                                    | 84/788 [00:06<01:01, 11.39it/s]

 11%|████▍                                    | 86/788 [00:06<01:01, 11.44it/s]
 11%|████▌                                    | 88/788 [00:07<00:59, 11.77it/s]

 11%|████▋                                    | 90/788 [00:07<00:55, 12.51it/s]

 12%|████▊                                    | 92/788 [00:07<01:00, 11.44it/s]

 12%|████▉                                    | 94/788 [00:07<01:04, 10.80it/s]
 12%|████▉                                    | 96/788 [00:07<00:58, 11.83it/s]

 12%|█████                                    | 98/788 [00:08<01:01, 11.20it/s]
 13%|█████▏                                  | 101/788 [00:08<00:53, 12.81it/s]

 13%|█████▏                                  | 103/788 [00:08<00:56, 12.14it/s]

 13%|█████▎                                  | 105/788 [00:08<01:00, 11.27it/s]
 14%|█████▍                                  | 107/788 [00:08<00:58, 11.72it/s]

 14%|█████▌                                  | 109/788 [00:08<00:56, 12.02it/s]
 14%|█████▋                                  | 111/788 [00:09<00:51, 13.12it/s]

 14%|█████▋                                  | 113/788 [00:09<00:49, 13.53it/s]

 15%|█████▊                                  | 115/788 [00:09<00:56, 11.98it/s]
 15%|█████▉                                  | 117/788 [00:09<00:57, 11.73it/s]

 15%|██████                                  | 119/788 [00:09<00:56, 11.85it/s]
 15%|██████▏                                 | 121/788 [00:09<00:56, 11.85it/s]

 16%|██████▏                                 | 123/788 [00:10<00:57, 11.56it/s]
 16%|██████▎                                 | 125/788 [00:10<00:51, 12.94it/s]

 16%|██████▍                                 | 127/788 [00:10<00:45, 14.40it/s]
 16%|██████▌                                 | 129/788 [00:10<00:42, 15.35it/s]

 17%|██████▋                                 | 131/788 [00:10<00:46, 14.18it/s]
 17%|██████▊                                 | 133/788 [00:10<00:47, 13.86it/s]

 17%|██████▊                                 | 135/788 [00:10<00:47, 13.82it/s]
 17%|██████▉                                 | 137/788 [00:11<00:47, 13.82it/s]

 18%|███████                                 | 139/788 [00:11<00:48, 13.48it/s]
 18%|███████▏                                | 141/788 [00:11<00:50, 12.82it/s]

 18%|███████▎                                | 143/788 [00:11<00:50, 12.75it/s]
 18%|███████▎                                | 145/788 [00:11<00:50, 12.62it/s]

 19%|███████▌                                | 148/788 [00:11<00:41, 15.34it/s]
 19%|███████▋                                | 151/788 [00:11<00:39, 16.10it/s]

 19%|███████▊                                | 153/788 [00:12<00:40, 15.73it/s]
 20%|███████▊                                | 155/788 [00:12<00:43, 14.49it/s]

 20%|███████▉                                | 157/788 [00:12<00:42, 14.85it/s]
 20%|████████                                | 159/788 [00:12<00:45, 13.86it/s]

 20%|████████▏                               | 161/788 [00:12<00:45, 13.68it/s]

 21%|████████▎                               | 163/788 [00:12<00:51, 12.12it/s]
 21%|████████▍                               | 165/788 [00:13<00:47, 13.04it/s]

 21%|████████▍                               | 167/788 [00:13<00:52, 11.79it/s]
 21%|████████▌                               | 169/788 [00:13<00:52, 11.72it/s]

 22%|████████▋                               | 171/788 [00:13<00:49, 12.39it/s]
 22%|████████▊                               | 173/788 [00:13<00:47, 12.87it/s]

 22%|████████▉                               | 175/788 [00:13<00:49, 12.32it/s]
 22%|████████▉                               | 177/788 [00:14<00:51, 11.82it/s]

 23%|█████████                               | 179/788 [00:14<00:52, 11.60it/s]
 23%|█████████▏                              | 181/788 [00:14<00:54, 11.11it/s]

 23%|█████████▎                              | 183/788 [00:14<00:53, 11.33it/s]
 23%|█████████▍                              | 185/788 [00:14<00:53, 11.29it/s]

 24%|█████████▍                              | 187/788 [00:14<00:52, 11.47it/s]
 24%|█████████▌                              | 189/788 [00:15<00:50, 11.95it/s]

 24%|█████████▋                              | 191/788 [00:15<00:53, 11.16it/s]
 24%|█████████▊                              | 193/788 [00:15<00:51, 11.45it/s]

 25%|█████████▉                              | 195/788 [00:15<00:45, 12.92it/s]
 25%|██████████                              | 197/788 [00:15<00:43, 13.64it/s]

 25%|██████████                              | 199/788 [00:15<00:48, 12.07it/s]
 26%|██████████▏                             | 201/788 [00:16<00:47, 12.34it/s]

 26%|██████████▎                             | 203/788 [00:16<00:50, 11.57it/s]
 26%|██████████▍                             | 205/788 [00:16<00:47, 12.17it/s]

 26%|██████████▌                             | 207/788 [00:16<00:43, 13.51it/s]
 27%|██████████▌                             | 209/788 [00:16<00:46, 12.57it/s]

 27%|██████████▋                             | 211/788 [00:16<00:47, 12.23it/s]
 27%|██████████▊                             | 213/788 [00:17<00:45, 12.65it/s]

 27%|██████████▉                             | 215/788 [00:17<00:47, 12.02it/s]
 28%|███████████                             | 217/788 [00:17<00:46, 12.29it/s]

 28%|███████████                             | 219/788 [00:17<00:41, 13.62it/s]
 28%|███████████▏                            | 221/788 [00:17<00:45, 12.59it/s]

 28%|███████████▎                            | 223/788 [00:17<00:42, 13.22it/s]
 29%|███████████▍                            | 225/788 [00:17<00:41, 13.58it/s]

 29%|███████████▌                            | 227/788 [00:18<00:39, 14.13it/s]
 29%|███████████▌                            | 229/788 [00:18<00:37, 15.05it/s]

 29%|███████████▋                            | 231/788 [00:18<00:39, 14.20it/s]
 30%|███████████▊                            | 233/788 [00:18<00:39, 14.22it/s]

 30%|███████████▉                            | 235/788 [00:18<00:40, 13.67it/s]
 30%|████████████                            | 237/788 [00:18<00:40, 13.51it/s]

 30%|████████████▏                           | 239/788 [00:18<00:40, 13.43it/s]
 31%|████████████▏                           | 241/788 [00:19<00:40, 13.53it/s]

 31%|████████████▎                           | 243/788 [00:19<00:41, 13.21it/s]
 31%|████████████▍                           | 245/788 [00:19<00:44, 12.16it/s]

 31%|████████████▌                           | 247/788 [00:19<00:43, 12.50it/s]

 32%|████████████▋                           | 249/788 [00:19<00:47, 11.45it/s]
 32%|████████████▋                           | 251/788 [00:19<00:45, 11.79it/s]

 32%|████████████▊                           | 253/788 [00:20<00:44, 11.93it/s]
 32%|████████████▉                           | 255/788 [00:20<00:42, 12.65it/s]

 33%|█████████████                           | 257/788 [00:20<00:41, 12.79it/s]
 33%|█████████████▏                          | 259/788 [00:20<00:43, 12.03it/s]

 33%|█████████████▏                          | 261/788 [00:20<00:39, 13.48it/s]

 33%|█████████████▎                          | 263/788 [00:20<00:43, 11.94it/s]
 34%|█████████████▍                          | 265/788 [00:21<00:42, 12.40it/s]

 34%|█████████████▌                          | 267/788 [00:21<00:38, 13.44it/s]

 34%|█████████████▋                          | 269/788 [00:21<00:43, 11.96it/s]
 34%|█████████████▊                          | 271/788 [00:21<00:42, 12.13it/s]

 35%|█████████████▊                          | 273/788 [00:21<00:44, 11.59it/s]
 35%|█████████████▉                          | 275/788 [00:21<00:44, 11.45it/s]

 35%|██████████████                          | 277/788 [00:22<00:47, 10.71it/s]
 35%|██████████████▏                         | 279/788 [00:22<00:46, 10.98it/s]

 36%|██████████████▎                         | 281/788 [00:22<00:43, 11.61it/s]
 36%|██████████████▎                         | 283/788 [00:22<00:43, 11.58it/s]

 36%|██████████████▍                         | 285/788 [00:22<00:43, 11.69it/s]
 36%|██████████████▌                         | 287/788 [00:22<00:38, 12.85it/s]

 37%|██████████████▋                         | 289/788 [00:23<00:38, 12.90it/s]
 37%|██████████████▊                         | 291/788 [00:23<00:34, 14.37it/s]

 37%|██████████████▊                         | 293/788 [00:23<00:33, 14.58it/s]
 37%|██████████████▉                         | 295/788 [00:23<00:35, 13.93it/s]

 38%|███████████████                         | 297/788 [00:23<00:35, 13.68it/s]
 38%|███████████████▏                        | 299/788 [00:23<00:37, 13.07it/s]

 38%|███████████████▎                        | 301/788 [00:23<00:36, 13.33it/s]
 38%|███████████████▍                        | 303/788 [00:24<00:36, 13.40it/s]

 39%|███████████████▍                        | 305/788 [00:24<00:36, 13.18it/s]
 39%|███████████████▌                        | 307/788 [00:24<00:36, 13.09it/s]

 39%|███████████████▋                        | 309/788 [00:24<00:36, 13.28it/s]
 39%|███████████████▊                        | 311/788 [00:24<00:37, 12.82it/s]

 40%|███████████████▉                        | 313/788 [00:24<00:37, 12.59it/s]
 40%|███████████████▉                        | 315/788 [00:25<00:35, 13.30it/s]

 40%|████████████████                        | 317/788 [00:25<00:35, 13.44it/s]
 40%|████████████████▏                       | 319/788 [00:25<00:37, 12.37it/s]

 41%|████████████████▎                       | 321/788 [00:25<00:38, 12.27it/s]
 41%|████████████████▍                       | 323/788 [00:25<00:36, 12.70it/s]

 41%|████████████████▍                       | 325/788 [00:25<00:40, 11.57it/s]
 41%|████████████████▌                       | 327/788 [00:25<00:37, 12.43it/s]

 42%|████████████████▋                       | 329/788 [00:26<00:37, 12.15it/s]
 42%|████████████████▊                       | 331/788 [00:26<00:36, 12.44it/s]

 42%|████████████████▉                       | 333/788 [00:26<00:35, 12.68it/s]
 43%|█████████████████                       | 335/788 [00:26<00:32, 14.07it/s]

 43%|█████████████████                       | 337/788 [00:26<00:32, 13.69it/s]
 43%|█████████████████▏                      | 339/788 [00:26<00:36, 12.32it/s]

 43%|█████████████████▎                      | 341/788 [00:27<00:37, 12.01it/s]
 44%|█████████████████▍                      | 343/788 [00:27<00:37, 11.82it/s]

 44%|█████████████████▌                      | 345/788 [00:27<00:40, 10.94it/s]

 44%|█████████████████▌                      | 347/788 [00:27<00:42, 10.50it/s]
 44%|█████████████████▋                      | 349/788 [00:27<00:38, 11.31it/s]

 45%|█████████████████▊                      | 351/788 [00:28<00:37, 11.74it/s]
 45%|█████████████████▉                      | 353/788 [00:28<00:35, 12.17it/s]

 45%|██████████████████                      | 355/788 [00:28<00:34, 12.62it/s]
 45%|██████████████████                      | 357/788 [00:28<00:34, 12.47it/s]

 46%|██████████████████▏                     | 359/788 [00:28<00:36, 11.91it/s]
 46%|██████████████████▎                     | 361/788 [00:28<00:32, 13.24it/s]

 46%|██████████████████▍                     | 364/788 [00:28<00:27, 15.19it/s]
 46%|██████████████████▌                     | 366/788 [00:29<00:28, 14.56it/s]

 47%|██████████████████▋                     | 368/788 [00:29<00:30, 13.93it/s]
 47%|██████████████████▊                     | 370/788 [00:29<00:29, 14.24it/s]

 47%|██████████████████▉                     | 372/788 [00:29<00:29, 14.19it/s]
 47%|██████████████████▉                     | 374/788 [00:29<00:27, 15.27it/s]

 48%|███████████████████                     | 376/788 [00:29<00:28, 14.52it/s]
 48%|███████████████████▏                    | 379/788 [00:29<00:26, 15.62it/s]

 48%|███████████████████▎                    | 381/788 [00:30<00:27, 15.06it/s]
 49%|███████████████████▍                    | 383/788 [00:30<00:28, 14.41it/s]

 49%|███████████████████▌                    | 385/788 [00:30<00:28, 14.20it/s]
 49%|███████████████████▋                    | 387/788 [00:30<00:31, 12.79it/s]

 49%|███████████████████▋                    | 389/788 [00:30<00:30, 13.04it/s]
 50%|███████████████████▊                    | 391/788 [00:30<00:32, 12.38it/s]

 50%|███████████████████▉                    | 393/788 [00:31<00:31, 12.51it/s]
 50%|████████████████████                    | 395/788 [00:31<00:30, 12.88it/s]

 50%|████████████████████▏                   | 397/788 [00:31<00:28, 13.83it/s]
 51%|████████████████████▎                   | 399/788 [00:31<00:30, 12.96it/s]

 51%|████████████████████▎                   | 401/788 [00:31<00:29, 13.29it/s]
 51%|████████████████████▍                   | 403/788 [00:31<00:28, 13.57it/s]

 51%|████████████████████▌                   | 405/788 [00:31<00:29, 12.98it/s]

 52%|████████████████████▋                   | 408/788 [00:32<00:27, 13.65it/s]
 52%|████████████████████▊                   | 411/788 [00:32<00:24, 15.29it/s]

 52%|████████████████████▉                   | 413/788 [00:32<00:26, 13.94it/s]
 53%|█████████████████████                   | 415/788 [00:32<00:25, 14.74it/s]

 53%|█████████████████████▏                  | 417/788 [00:32<00:28, 13.03it/s]

 53%|█████████████████████▎                  | 419/788 [00:33<00:31, 11.87it/s]

 53%|█████████████████████▎                  | 421/788 [00:33<00:33, 11.06it/s]
 54%|█████████████████████▍                  | 423/788 [00:33<00:31, 11.45it/s]

 54%|█████████████████████▌                  | 425/788 [00:33<00:32, 11.23it/s]
 54%|█████████████████████▋                  | 427/788 [00:33<00:31, 11.50it/s]

 54%|█████████████████████▊                  | 429/788 [00:33<00:30, 11.88it/s]
 55%|█████████████████████▉                  | 431/788 [00:34<00:27, 13.21it/s]

 55%|█████████████████████▉                  | 433/788 [00:34<00:25, 13.86it/s]
 55%|██████████████████████                  | 435/788 [00:34<00:28, 12.57it/s]

 55%|██████████████████████▏                 | 437/788 [00:34<00:27, 12.84it/s]
 56%|██████████████████████▎                 | 439/788 [00:34<00:27, 12.52it/s]

 56%|██████████████████████▍                 | 441/788 [00:34<00:26, 12.89it/s]
 56%|██████████████████████▍                 | 443/788 [00:34<00:27, 12.75it/s]

 56%|██████████████████████▌                 | 445/788 [00:35<00:27, 12.44it/s]
 57%|██████████████████████▋                 | 447/788 [00:35<00:28, 12.17it/s]

 57%|██████████████████████▊                 | 449/788 [00:35<00:26, 12.96it/s]
 57%|██████████████████████▉                 | 451/788 [00:35<00:26, 12.66it/s]

 57%|██████████████████████▉                 | 453/788 [00:35<00:25, 12.96it/s]
 58%|███████████████████████                 | 455/788 [00:35<00:25, 13.29it/s]

 58%|███████████████████████▏                | 457/788 [00:36<00:24, 13.70it/s]
 58%|███████████████████████▎                | 459/788 [00:36<00:24, 13.21it/s]

 59%|███████████████████████▍                | 461/788 [00:36<00:25, 12.89it/s]
 59%|███████████████████████▌                | 463/788 [00:36<00:26, 12.22it/s]

 59%|███████████████████████▋                | 466/788 [00:36<00:24, 13.17it/s]
 59%|███████████████████████▊                | 468/788 [00:36<00:25, 12.48it/s]

 60%|███████████████████████▊                | 470/788 [00:37<00:27, 11.50it/s]
 60%|███████████████████████▉                | 472/788 [00:37<00:27, 11.56it/s]

 60%|████████████████████████                | 474/788 [00:37<00:26, 11.80it/s]
 60%|████████████████████████▏               | 476/788 [00:37<00:25, 12.05it/s]

 61%|████████████████████████▎               | 478/788 [00:37<00:24, 12.74it/s]
 61%|████████████████████████▎               | 480/788 [00:37<00:24, 12.75it/s]

 61%|████████████████████████▍               | 482/788 [00:38<00:25, 12.07it/s]
 61%|████████████████████████▌               | 484/788 [00:38<00:25, 11.83it/s]

 62%|████████████████████████▋               | 486/788 [00:38<00:25, 11.80it/s]
 62%|████████████████████████▊               | 488/788 [00:38<00:25, 11.76it/s]

 62%|████████████████████████▊               | 490/788 [00:38<00:27, 10.95it/s]
 62%|████████████████████████▉               | 492/788 [00:38<00:25, 11.45it/s]

 63%|█████████████████████████               | 494/788 [00:39<00:25, 11.50it/s]
 63%|█████████████████████████▏              | 496/788 [00:39<00:23, 12.42it/s]

 63%|█████████████████████████▎              | 498/788 [00:39<00:21, 13.55it/s]
 63%|█████████████████████████▍              | 500/788 [00:39<00:20, 14.32it/s]

 64%|█████████████████████████▍              | 502/788 [00:39<00:21, 13.61it/s]
 64%|█████████████████████████▌              | 504/788 [00:39<00:22, 12.72it/s]

 64%|█████████████████████████▋              | 506/788 [00:39<00:19, 14.23it/s]
 64%|█████████████████████████▊              | 508/788 [00:40<00:19, 14.20it/s]

 65%|█████████████████████████▉              | 510/788 [00:40<00:21, 13.21it/s]
 65%|█████████████████████████▉              | 512/788 [00:40<00:18, 14.60it/s]

 65%|██████████████████████████              | 514/788 [00:40<00:18, 14.46it/s]
 65%|██████████████████████████▏             | 516/788 [00:40<00:18, 14.79it/s]

 66%|██████████████████████████▎             | 518/788 [00:40<00:18, 14.49it/s]
 66%|██████████████████████████▍             | 520/788 [00:40<00:18, 14.36it/s]

 66%|██████████████████████████▍             | 522/788 [00:41<00:18, 14.07it/s]
 66%|██████████████████████████▌             | 524/788 [00:41<00:18, 14.26it/s]

 67%|██████████████████████████▋             | 526/788 [00:41<00:20, 12.93it/s]
 67%|██████████████████████████▊             | 528/788 [00:41<00:19, 13.13it/s]

 67%|██████████████████████████▉             | 530/788 [00:41<00:20, 12.57it/s]
 68%|███████████████████████████             | 532/788 [00:41<00:19, 12.92it/s]

 68%|███████████████████████████             | 534/788 [00:42<00:20, 12.41it/s]
 68%|███████████████████████████▏            | 536/788 [00:42<00:20, 12.35it/s]

 68%|███████████████████████████▎            | 538/788 [00:42<00:22, 11.31it/s]

 69%|███████████████████████████▍            | 540/788 [00:42<00:22, 10.79it/s]
 69%|███████████████████████████▌            | 542/788 [00:42<00:23, 10.58it/s]

 69%|███████████████████████████▌            | 544/788 [00:43<00:23, 10.24it/s]
 69%|███████████████████████████▋            | 546/788 [00:43<00:22, 11.00it/s]

 70%|███████████████████████████▊            | 548/788 [00:43<00:21, 11.01it/s]
 70%|███████████████████████████▉            | 550/788 [00:43<00:20, 11.60it/s]

 70%|████████████████████████████            | 552/788 [00:43<00:18, 12.83it/s]
 70%|████████████████████████████            | 554/788 [00:43<00:17, 13.04it/s]

 71%|████████████████████████████▏           | 556/788 [00:43<00:19, 12.12it/s]
 71%|████████████████████████████▎           | 558/788 [00:44<00:17, 12.90it/s]

 71%|████████████████████████████▍           | 560/788 [00:44<00:16, 13.48it/s]
 71%|████████████████████████████▌           | 563/788 [00:44<00:14, 15.38it/s]

 72%|████████████████████████████▋           | 565/788 [00:44<00:16, 13.66it/s]
 72%|████████████████████████████▊           | 567/788 [00:44<00:17, 12.46it/s]

 72%|████████████████████████████▉           | 569/788 [00:44<00:15, 13.77it/s]
 72%|████████████████████████████▉           | 571/788 [00:45<00:16, 13.13it/s]

 73%|█████████████████████████████           | 573/788 [00:45<00:18, 11.79it/s]
 73%|█████████████████████████████▏          | 575/788 [00:45<00:17, 12.18it/s]

 73%|█████████████████████████████▎          | 577/788 [00:45<00:17, 12.22it/s]
 73%|█████████████████████████████▍          | 579/788 [00:45<00:16, 12.63it/s]

 74%|█████████████████████████████▍          | 581/788 [00:45<00:16, 12.84it/s]
 74%|█████████████████████████████▌          | 583/788 [00:46<00:17, 12.00it/s]

 74%|█████████████████████████████▋          | 585/788 [00:46<00:16, 12.26it/s]
 74%|█████████████████████████████▊          | 587/788 [00:46<00:16, 11.83it/s]

 75%|█████████████████████████████▉          | 589/788 [00:46<00:17, 11.21it/s]
 75%|██████████████████████████████          | 591/788 [00:46<00:15, 12.74it/s]

 75%|██████████████████████████████          | 593/788 [00:46<00:15, 12.63it/s]
 76%|██████████████████████████████▏         | 595/788 [00:47<00:16, 11.97it/s]

 76%|██████████████████████████████▎         | 597/788 [00:47<00:15, 12.46it/s]
 76%|██████████████████████████████▍         | 599/788 [00:47<00:14, 12.76it/s]

 76%|██████████████████████████████▌         | 601/788 [00:47<00:14, 13.27it/s]
 77%|██████████████████████████████▌         | 603/788 [00:47<00:14, 13.17it/s]

 77%|██████████████████████████████▋         | 605/788 [00:47<00:13, 13.46it/s]
 77%|██████████████████████████████▊         | 607/788 [00:47<00:12, 14.82it/s]

 77%|██████████████████████████████▉         | 609/788 [00:48<00:14, 12.67it/s]
 78%|███████████████████████████████         | 611/788 [00:48<00:14, 12.34it/s]

 78%|███████████████████████████████         | 613/788 [00:48<00:13, 13.39it/s]
 78%|███████████████████████████████▏        | 615/788 [00:48<00:12, 13.69it/s]

 78%|███████████████████████████████▎        | 617/788 [00:48<00:12, 13.17it/s]
 79%|███████████████████████████████▍        | 619/788 [00:48<00:12, 13.61it/s]

 79%|███████████████████████████████▌        | 621/788 [00:48<00:12, 13.67it/s]
 79%|███████████████████████████████▌        | 623/788 [00:49<00:11, 14.84it/s]

 79%|███████████████████████████████▋        | 625/788 [00:49<00:12, 12.88it/s]
 80%|███████████████████████████████▊        | 627/788 [00:49<00:13, 11.85it/s]

 80%|███████████████████████████████▉        | 629/788 [00:49<00:14, 10.95it/s]

 80%|████████████████████████████████        | 631/788 [00:49<00:15, 10.43it/s]
 80%|████████████████████████████████▏       | 633/788 [00:50<00:14, 10.96it/s]

 81%|████████████████████████████████▏       | 635/788 [00:50<00:12, 12.38it/s]
 81%|████████████████████████████████▎       | 637/788 [00:50<00:11, 12.60it/s]

 81%|████████████████████████████████▍       | 639/788 [00:50<00:12, 11.71it/s]
 81%|████████████████████████████████▌       | 642/788 [00:50<00:10, 13.71it/s]

 82%|████████████████████████████████▋       | 644/788 [00:50<00:10, 13.16it/s]
 82%|████████████████████████████████▊       | 646/788 [00:51<00:11, 12.73it/s]

 82%|████████████████████████████████▉       | 648/788 [00:51<00:10, 13.25it/s]
 83%|█████████████████████████████████       | 651/788 [00:51<00:09, 14.92it/s]

 83%|█████████████████████████████████▏      | 653/788 [00:51<00:09, 13.80it/s]
 83%|█████████████████████████████████▏      | 655/788 [00:51<00:10, 12.59it/s]

 83%|█████████████████████████████████▎      | 657/788 [00:51<00:10, 12.42it/s]
 84%|█████████████████████████████████▍      | 659/788 [00:52<00:10, 12.29it/s]

 84%|█████████████████████████████████▌      | 661/788 [00:52<00:10, 12.41it/s]
 84%|█████████████████████████████████▋      | 663/788 [00:52<00:10, 12.33it/s]

 84%|█████████████████████████████████▊      | 665/788 [00:52<00:09, 12.54it/s]

 85%|█████████████████████████████████▊      | 667/788 [00:52<00:10, 11.43it/s]
 85%|█████████████████████████████████▉      | 669/788 [00:52<00:09, 11.96it/s]

 85%|██████████████████████████████████      | 671/788 [00:53<00:09, 11.76it/s]
 85%|██████████████████████████████████▏     | 673/788 [00:53<00:09, 12.13it/s]

 86%|██████████████████████████████████▎     | 675/788 [00:53<00:09, 12.38it/s]
 86%|██████████████████████████████████▎     | 677/788 [00:53<00:08, 13.69it/s]

 86%|██████████████████████████████████▍     | 679/788 [00:53<00:08, 12.12it/s]
 86%|██████████████████████████████████▌     | 681/788 [00:53<00:08, 12.26it/s]

 87%|██████████████████████████████████▋     | 683/788 [00:53<00:07, 13.38it/s]
 87%|██████████████████████████████████▊     | 685/788 [00:54<00:08, 12.83it/s]

 87%|██████████████████████████████████▊     | 687/788 [00:54<00:08, 11.65it/s]
 87%|██████████████████████████████████▉     | 689/788 [00:54<00:08, 12.07it/s]

 88%|███████████████████████████████████     | 691/788 [00:54<00:08, 11.18it/s]
 88%|███████████████████████████████████▏    | 693/788 [00:54<00:07, 12.63it/s]

 88%|███████████████████████████████████▎    | 695/788 [00:54<00:07, 13.05it/s]
 88%|███████████████████████████████████▍    | 697/788 [00:55<00:07, 12.68it/s]

 89%|███████████████████████████████████▍    | 699/788 [00:55<00:06, 13.05it/s]
 89%|███████████████████████████████████▌    | 701/788 [00:55<00:07, 12.35it/s]

 89%|███████████████████████████████████▋    | 703/788 [00:55<00:07, 11.70it/s]
 89%|███████████████████████████████████▊    | 705/788 [00:55<00:07, 11.14it/s]

 90%|███████████████████████████████████▉    | 707/788 [00:56<00:07, 11.11it/s]
 90%|███████████████████████████████████▉    | 709/788 [00:56<00:06, 11.77it/s]

 90%|████████████████████████████████████    | 711/788 [00:56<00:06, 11.57it/s]
 90%|████████████████████████████████████▏   | 713/788 [00:56<00:06, 12.06it/s]

 91%|████████████████████████████████████▎   | 715/788 [00:56<00:05, 13.68it/s]
 91%|████████████████████████████████████▍   | 717/788 [00:56<00:04, 14.58it/s]

 91%|████████████████████████████████████▍   | 719/788 [00:56<00:04, 14.48it/s]
 91%|████████████████████████████████████▌   | 721/788 [00:57<00:05, 12.92it/s]

 92%|████████████████████████████████████▋   | 723/788 [00:57<00:05, 11.77it/s]
 92%|████████████████████████████████████▊   | 725/788 [00:57<00:05, 11.59it/s]

 92%|████████████████████████████████████▉   | 727/788 [00:57<00:05, 11.68it/s]
 93%|█████████████████████████████████████   | 729/788 [00:57<00:05, 11.17it/s]

 93%|█████████████████████████████████████   | 731/788 [00:57<00:05, 11.08it/s]
 93%|█████████████████████████████████████▏  | 733/788 [00:58<00:04, 12.07it/s]

 93%|█████████████████████████████████████▎  | 735/788 [00:58<00:04, 11.36it/s]

 94%|█████████████████████████████████████▍  | 737/788 [00:58<00:04, 10.88it/s]
 94%|█████████████████████████████████████▌  | 739/788 [00:58<00:04, 11.37it/s]

 94%|█████████████████████████████████████▌  | 741/788 [00:58<00:03, 12.60it/s]
 94%|█████████████████████████████████████▋  | 743/788 [00:58<00:03, 13.25it/s]

 95%|█████████████████████████████████████▊  | 745/788 [00:59<00:03, 13.73it/s]
 95%|█████████████████████████████████████▉  | 747/788 [00:59<00:03, 13.26it/s]

 95%|██████████████████████████████████████  | 749/788 [00:59<00:03, 12.38it/s]
 95%|██████████████████████████████████████  | 751/788 [00:59<00:03, 11.86it/s]

 96%|██████████████████████████████████████▏ | 753/788 [00:59<00:03, 11.15it/s]
 96%|██████████████████████████████████████▎ | 755/788 [00:59<00:02, 11.77it/s]

 96%|██████████████████████████████████████▍ | 757/788 [01:00<00:02, 11.58it/s]
 96%|██████████████████████████████████████▌ | 759/788 [01:00<00:02, 11.82it/s]

 97%|██████████████████████████████████████▋ | 761/788 [01:00<00:02, 12.17it/s]
 97%|██████████████████████████████████████▊ | 764/788 [01:00<00:01, 14.60it/s]

 97%|██████████████████████████████████████▉ | 766/788 [01:00<00:01, 14.25it/s]
 97%|██████████████████████████████████████▉ | 768/788 [01:00<00:01, 13.12it/s]

 98%|███████████████████████████████████████ | 770/788 [01:01<00:01, 14.08it/s]
 98%|███████████████████████████████████████▏| 772/788 [01:01<00:01, 12.96it/s]

 98%|███████████████████████████████████████▎| 774/788 [01:01<00:00, 14.40it/s]
 98%|███████████████████████████████████████▍| 776/788 [01:01<00:00, 14.05it/s]

 99%|███████████████████████████████████████▍| 778/788 [01:01<00:00, 13.94it/s]
 99%|███████████████████████████████████████▌| 780/788 [01:01<00:00, 14.84it/s]

 99%|███████████████████████████████████████▋| 782/788 [01:01<00:00, 13.97it/s]
 99%|███████████████████████████████████████▊| 784/788 [01:02<00:00, 14.43it/s]

 33%|████████████                        | 14175/42525 [27:12<59:41,  7.92it/s]
100%|████████████████████████████████████████| 788/788 [01:02<00:00, 14.40it/s]

{'eval_loss': 'nan', 'eval_accuracy': '0.2', 'eval_macro_f1': '0.06667', 'eval_mae': '2', 'eval_cil_score': '0.5', 'eval_quadratic_weighted_kappa': '0', 'eval_runtime': '62.31', 'eval_samples_per_second': '404.4', 'eval_steps_per_second': '12.65', 'epoch': '1'}

Writing model shards:   0%|                              | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|██████████████████████| 1/1 [00:00<00:00,  1.32it/s]

 33%|███████████                      | 14178/42525 [27:15<73:02:44,  9.28s/it]

 33%|███████████                      | 14182/42525 [27:15<30:56:12,  3.93s/it]

 33%|███████████                      | 14184/42525 [27:15<19:46:09,  2.51s/it]

 33%|███████████▎                      | 14188/42525 [27:16<8:18:11,  1.05s/it]

 33%|███████████▎                      | 14190/42525 [27:16<5:28:31,  1.44it/s]

 33%|███████████▎                      | 14192/42525 [27:16<3:30:15,  2.25it/s]

 33%|███████████▎                      | 14195/42525 [27:17<2:04:56,  3.78it/s]

 33%|███████████▎                      | 14198/42525 [27:17<1:23:28,  5.66it/s]

 33%|███████████▎                      | 14199/42525 [27:17<1:16:26,  6.18it/s]

 33%|███████████▎                      | 14202/42525 [27:17<1:04:08,  7.36it/s]

 33%|████████████                        | 14205/42525 [27:18<56:11,  8.40it/s]

 33%|████████████                        | 14207/42525 [27:18<59:06,  7.98it/s]

 33%|████████████                        | 14210/42525 [27:18<53:58,  8.74it/s]

 33%|████████████                        | 14212/42525 [27:19<57:00,  8.28it/s]

 33%|████████████                        | 14214/42525 [27:19<54:11,  8.71it/s]

 33%|████████████                        | 14217/42525 [27:19<53:03,  8.89it/s]

 33%|████████████                        | 14220/42525 [27:19<49:54,  9.45it/s]

 33%|████████████                        | 14221/42525 [27:20<49:53,  9.45it/s]

 33%|████████████                        | 14223/42525 [27:20<52:57,  8.91it/s]

 33%|████████████                        | 14226/42525 [27:20<54:05,  8.72it/s]

 33%|████████████                        | 14229/42525 [27:20<54:49,  8.60it/s]

 33%|████████████                        | 14231/42525 [27:21<56:38,  8.32it/s]

 33%|███████████▍                      | 14233/42525 [27:21<1:02:58,  7.49it/s]

 33%|███████████▍                      | 14235/42525 [27:21<1:02:07,  7.59it/s]

 33%|████████████                        | 14238/42525 [27:22<52:08,  9.04it/s]

 33%|████████████                        | 14241/42525 [27:22<51:28,  9.16it/s]

 33%|████████████                        | 14243/42525 [27:22<58:57,  8.00it/s]

 33%|████████████                        | 14245/42525 [27:22<53:11,  8.86it/s]

 34%|████████████                        | 14248/42525 [27:23<51:33,  9.14it/s]

 34%|████████████                        | 14251/42525 [27:23<48:48,  9.65it/s]

 34%|████████████                        | 14254/42525 [27:23<48:00,  9.81it/s]

 34%|████████████                        | 14258/42525 [27:24<46:46, 10.07it/s]

 34%|████████████                        | 14260/42525 [27:24<45:56, 10.25it/s]

 34%|████████████                        | 14263/42525 [27:24<49:02,  9.61it/s]

 34%|████████████                        | 14265/42525 [27:24<50:43,  9.29it/s]

 34%|████████████                        | 14268/42525 [27:25<50:19,  9.36it/s]

 34%|████████████                        | 14270/42525 [27:25<49:50,  9.45it/s]

 34%|████████████                        | 14273/42525 [27:25<52:07,  9.03it/s]

 34%|████████████                        | 14275/42525 [27:26<54:16,  8.68it/s]

 34%|████████████                        | 14279/42525 [27:26<49:43,  9.47it/s]

 34%|████████████                        | 14282/42525 [27:26<50:21,  9.35it/s]

 34%|████████████                        | 14284/42525 [27:26<51:02,  9.22it/s]

 34%|████████████                        | 14285/42525 [27:27<52:43,  8.93it/s]

 34%|████████████                        | 14287/42525 [27:27<52:03,  9.04it/s]

 34%|████████████                        | 14289/42525 [27:27<50:30,  9.32it/s]

 34%|████████████                        | 14293/42525 [27:27<49:10,  9.57it/s]

 34%|████████████                        | 14297/42525 [27:28<47:32,  9.90it/s]

 34%|████████████                        | 14300/42525 [27:28<48:16,  9.74it/s]

 34%|████████████                        | 14303/42525 [27:28<48:07,  9.77it/s]

 34%|████████████                        | 14306/42525 [27:29<49:36,  9.48it/s]

 34%|████████████                        | 14310/42525 [27:29<49:02,  9.59it/s]

 34%|████████████                        | 14312/42525 [27:29<53:33,  8.78it/s]

 34%|████████████                        | 14313/42525 [27:30<52:40,  8.93it/s]

 34%|████████████                        | 14317/42525 [27:30<51:24,  9.15it/s]

 34%|████████████                        | 14318/42525 [27:30<50:37,  9.29it/s]

 34%|████████████                        | 14322/42525 [27:31<48:20,  9.72it/s]

 34%|████████████▏                       | 14324/42525 [27:31<50:29,  9.31it/s]

 34%|████████████▏                       | 14327/42525 [27:31<50:31,  9.30it/s]

 34%|████████████▏                       | 14329/42525 [27:31<51:56,  9.05it/s]

 34%|████████████▏                       | 14332/42525 [27:32<51:33,  9.11it/s]

 34%|████████████▏                       | 14336/42525 [27:32<48:12,  9.75it/s]

 34%|████████████▏                       | 14338/42525 [27:32<51:52,  9.05it/s]

 34%|████████████▏                       | 14340/42525 [27:33<55:41,  8.44it/s]

 34%|████████████▏                       | 14343/42525 [27:33<51:06,  9.19it/s]

 34%|████████████▏                       | 14346/42525 [27:33<51:01,  9.20it/s]

 34%|████████████▏                       | 14349/42525 [27:33<49:03,  9.57it/s]

 34%|████████████▏                       | 14352/42525 [27:34<51:25,  9.13it/s]

 34%|████████████▏                       | 14353/42525 [27:34<52:17,  8.98it/s]

 34%|████████████▏                       | 14357/42525 [27:34<49:28,  9.49it/s]

 34%|████████████▏                       | 14359/42525 [27:35<53:35,  8.76it/s]

 34%|████████████▏                       | 14361/42525 [27:35<56:20,  8.33it/s]

 34%|████████████▏                       | 14363/42525 [27:35<53:31,  8.77it/s]

 34%|████████████▏                       | 14367/42525 [27:35<48:23,  9.70it/s]

 34%|████████████▏                       | 14370/42525 [27:36<49:34,  9.47it/s]

 34%|████████████▏                       | 14372/42525 [27:36<51:12,  9.16it/s]

 34%|████████████▏                       | 14374/42525 [27:36<49:06,  9.56it/s]

 34%|████████████▏                       | 14377/42525 [27:37<51:22,  9.13it/s]

 34%|████████████▏                       | 14378/42525 [27:37<51:51,  9.04it/s]

 34%|████████████▏                       | 14381/42525 [27:37<54:27,  8.61it/s]

 34%|████████████▏                       | 14385/42525 [27:37<49:06,  9.55it/s]

 34%|████████████▏                       | 14387/42525 [27:38<53:54,  8.70it/s]

 34%|████████████▏                       | 14389/42525 [27:38<55:40,  8.42it/s]

 34%|████████████▏                       | 14391/42525 [27:38<57:44,  8.12it/s]

 34%|████████████▏                       | 14392/42525 [27:38<54:40,  8.58it/s]

 34%|████████████▏                       | 14396/42525 [27:39<51:37,  9.08it/s]

 34%|████████████▏                       | 14398/42525 [27:39<49:33,  9.46it/s]

 34%|████████████▏                       | 14401/42525 [27:39<49:10,  9.53it/s]

 34%|████████████▏                       | 14403/42525 [27:39<55:28,  8.45it/s]

 34%|████████████▏                       | 14406/42525 [27:40<53:16,  8.80it/s]

 34%|████████████▏                       | 14410/42525 [27:40<48:57,  9.57it/s]

 34%|████████████▏                       | 14413/42525 [27:41<50:25,  9.29it/s]

 34%|████████████▏                       | 14417/42525 [27:41<47:34,  9.85it/s]

 34%|████████████▏                       | 14419/42525 [27:41<47:32,  9.85it/s]

 34%|████████████▏                       | 14421/42525 [27:41<53:46,  8.71it/s]

 34%|████████████▏                       | 14423/42525 [27:42<52:54,  8.85it/s]

 34%|████████████▏                       | 14426/42525 [27:42<54:22,  8.61it/s]

 34%|████████████▏                       | 14429/42525 [27:42<50:03,  9.35it/s]

 34%|████████████▏                       | 14431/42525 [27:42<49:56,  9.37it/s]

 34%|████████████▏                       | 14434/42525 [27:43<50:52,  9.20it/s]

 34%|████████████▏                       | 14437/42525 [27:43<48:34,  9.64it/s]

 34%|████████████▏                       | 14440/42525 [27:43<51:48,  9.03it/s]

 34%|████████████▏                       | 14442/42525 [27:44<55:42,  8.40it/s]

 34%|████████████▏                       | 14444/42525 [27:44<59:41,  7.84it/s]

 34%|████████████▏                       | 14447/42525 [27:44<51:17,  9.12it/s]

 34%|████████████▏                       | 14449/42525 [27:44<49:03,  9.54it/s]

 34%|████████████▏                       | 14453/42525 [27:45<47:23,  9.87it/s]

 34%|████████████▏                       | 14457/42525 [27:45<46:26, 10.07it/s]

 34%|████████████▏                       | 14459/42525 [27:45<49:53,  9.38it/s]

 34%|████████████▏                       | 14461/42525 [27:46<49:15,  9.49it/s]

 34%|████████████▏                       | 14463/42525 [27:46<51:52,  9.02it/s]

 34%|████████████▏                       | 14466/42525 [27:46<50:22,  9.28it/s]

 34%|████████████▏                       | 14470/42525 [27:47<50:05,  9.33it/s]

 34%|████████████▎                       | 14473/42525 [27:47<49:12,  9.50it/s]

 34%|████████████▎                       | 14475/42525 [27:47<49:32,  9.44it/s]

 34%|████████████▎                       | 14478/42525 [27:48<51:03,  9.15it/s]

 34%|████████████▎                       | 14482/42525 [27:48<47:58,  9.74it/s]

 34%|████████████▎                       | 14485/42525 [27:48<51:31,  9.07it/s]

 34%|████████████▎                       | 14486/42525 [27:48<55:19,  8.45it/s]

 34%|████████████▎                       | 14489/42525 [27:49<52:35,  8.88it/s]

 34%|████████████▎                       | 14492/42525 [27:49<49:01,  9.53it/s]

 34%|████████████▎                       | 14494/42525 [27:49<52:02,  8.98it/s]

 34%|████████████▎                       | 14497/42525 [27:50<53:25,  8.74it/s]

 34%|████████████▎                       | 14499/42525 [27:50<56:07,  8.32it/s]

 34%|████████████▎                       | 14501/42525 [27:50<52:52,  8.83it/s]

 34%|████████████▎                       | 14504/42525 [27:50<55:11,  8.46it/s]

 34%|████████████▎                       | 14507/42525 [27:51<54:43,  8.53it/s]

 34%|████████████▎                       | 14509/42525 [27:51<55:47,  8.37it/s]

 34%|████████████▎                       | 14512/42525 [27:51<58:49,  7.94it/s]

 34%|████████████▎                       | 14515/42525 [27:52<54:27,  8.57it/s]

 34%|████████████▎                       | 14519/42525 [27:52<48:49,  9.56it/s]

 34%|████████████▎                       | 14521/42525 [27:52<56:27,  8.27it/s]

 34%|████████████▎                       | 14523/42525 [27:53<53:06,  8.79it/s]

 34%|████████████▎                       | 14525/42525 [27:53<55:42,  8.38it/s]

 34%|████████████▎                       | 14527/42525 [27:53<57:15,  8.15it/s]

 34%|████████████▎                       | 14530/42525 [27:53<52:16,  8.93it/s]

 34%|████████████▎                       | 14532/42525 [27:54<49:20,  9.45it/s]

 34%|████████████▎                       | 14534/42525 [27:54<52:08,  8.95it/s]

 34%|████████████▎                       | 14536/42525 [27:54<51:06,  9.13it/s]

 34%|████████████▎                       | 14539/42525 [27:54<53:40,  8.69it/s]

 34%|███████████▋                      | 14541/42525 [27:55<1:00:08,  7.75it/s]

 34%|███████████▋                      | 14542/42525 [27:55<1:02:19,  7.48it/s]

 34%|████████████▎                       | 14546/42525 [27:55<53:33,  8.71it/s]

 34%|████████████▎                       | 14549/42525 [27:56<50:55,  9.16it/s]

 34%|████████████▎                       | 14551/42525 [27:56<51:11,  9.11it/s]

 34%|████████████▎                       | 14554/42525 [27:56<50:10,  9.29it/s]

 34%|████████████▎                       | 14556/42525 [27:56<48:11,  9.67it/s]

 34%|████████████▎                       | 14559/42525 [27:57<48:03,  9.70it/s]

 34%|████████████▎                       | 14562/42525 [27:57<50:38,  9.20it/s]

 34%|████████████▎                       | 14564/42525 [27:57<49:14,  9.47it/s]

 34%|████████████▎                       | 14567/42525 [27:58<54:42,  8.52it/s]

 34%|████████████▎                       | 14569/42525 [27:58<51:23,  9.07it/s]

 34%|████████████▎                       | 14573/42525 [27:58<48:47,  9.55it/s]

 34%|████████████▎                       | 14575/42525 [27:58<53:46,  8.66it/s]

 34%|████████████▎                       | 14578/42525 [27:59<49:46,  9.36it/s]

 34%|████████████▎                       | 14581/42525 [27:59<50:29,  9.22it/s]

 34%|████████████▎                       | 14584/42525 [27:59<50:39,  9.19it/s]

 34%|████████████▎                       | 14587/42525 [28:00<49:40,  9.37it/s]

 34%|████████████▎                       | 14591/42525 [28:00<47:02,  9.90it/s]

 34%|████████████▎                       | 14594/42525 [28:00<49:22,  9.43it/s]

 34%|████████████▎                       | 14597/42525 [28:01<48:07,  9.67it/s]

 34%|████████████▎                       | 14600/42525 [28:01<47:39,  9.76it/s]

 34%|████████████▎                       | 14603/42525 [28:01<47:09,  9.87it/s]

 34%|████████████▎                       | 14606/42525 [28:02<47:25,  9.81it/s]

 34%|████████████▎                       | 14608/42525 [28:02<53:51,  8.64it/s]

 34%|████████████▎                       | 14611/42525 [28:02<50:50,  9.15it/s]

 34%|████████████▎                       | 14613/42525 [28:03<51:16,  9.07it/s]

 34%|████████████▎                       | 14616/42525 [28:03<50:49,  9.15it/s]

 34%|████████████▍                       | 14618/42525 [28:03<55:41,  8.35it/s]

 34%|████████████▍                       | 14622/42525 [28:04<49:07,  9.47it/s]

 34%|████████████▍                       | 14624/42525 [28:04<55:04,  8.44it/s]

 34%|████████████▍                       | 14627/42525 [28:04<53:36,  8.67it/s]

 34%|████████████▍                       | 14631/42525 [28:05<48:30,  9.58it/s]

 34%|████████████▍                       | 14633/42525 [28:05<48:51,  9.51it/s]

 34%|████████████▍                       | 14635/42525 [28:05<57:08,  8.14it/s]

 34%|████████████▍                       | 14638/42525 [28:05<56:11,  8.27it/s]

 34%|████████████▍                       | 14640/42525 [28:06<55:04,  8.44it/s]

 34%|████████████▍                       | 14641/42525 [28:06<58:43,  7.91it/s]

 34%|████████████▍                       | 14643/42525 [28:06<54:27,  8.53it/s]

 34%|████████████▍                       | 14645/42525 [28:06<55:35,  8.36it/s]

 34%|████████████▍                       | 14647/42525 [28:06<54:11,  8.57it/s]

 34%|████████████▍                       | 14649/42525 [28:07<55:05,  8.43it/s]

 34%|████████████▍                       | 14653/42525 [28:07<50:25,  9.21it/s]

 34%|████████████▍                       | 14656/42525 [28:07<49:07,  9.46it/s]

 34%|████████████▍                       | 14660/42525 [28:08<46:44,  9.94it/s]

 34%|████████████▍                       | 14663/42525 [28:08<50:51,  9.13it/s]

 34%|████████████▍                       | 14665/42525 [28:08<54:54,  8.46it/s]

 34%|████████████▍                       | 14668/42525 [28:09<55:27,  8.37it/s]

 34%|████████████▍                       | 14671/42525 [28:09<52:51,  8.78it/s]

 35%|████████████▍                       | 14673/42525 [28:09<53:57,  8.60it/s]

 35%|████████████▍                       | 14675/42525 [28:10<59:07,  7.85it/s]

 35%|████████████▍                       | 14676/42525 [28:10<56:22,  8.23it/s]

 35%|████████████▍                       | 14679/42525 [28:10<54:20,  8.54it/s]

 35%|████████████▍                       | 14682/42525 [28:10<51:17,  9.05it/s]

 35%|████████████▍                       | 14685/42525 [28:11<55:42,  8.33it/s]

 35%|████████████▍                       | 14687/42525 [28:11<54:17,  8.55it/s]

 35%|████████████▍                       | 14690/42525 [28:11<53:05,  8.74it/s]

 35%|████████████▍                       | 14693/42525 [28:12<51:32,  9.00it/s]

 35%|████████████▍                       | 14695/42525 [28:12<50:03,  9.26it/s]

 35%|████████████▍                       | 14697/42525 [28:12<52:23,  8.85it/s]

 35%|████████████▍                       | 14699/42525 [28:12<50:28,  9.19it/s]

 35%|████████████▍                       | 14701/42525 [28:13<51:31,  9.00it/s]

 35%|████████████▍                       | 14704/42525 [28:13<53:36,  8.65it/s]

 35%|████████████▍                       | 14706/42525 [28:13<54:23,  8.52it/s]

 35%|████████████▍                       | 14708/42525 [28:13<50:41,  9.14it/s]

 35%|████████████▍                       | 14710/42525 [28:14<52:59,  8.75it/s]

 35%|████████████▍                       | 14713/42525 [28:14<52:09,  8.89it/s]

 35%|████████████▍                       | 14715/42525 [28:14<51:41,  8.97it/s]

 35%|████████████▍                       | 14717/42525 [28:14<49:29,  9.36it/s]

 35%|████████████▍                       | 14719/42525 [28:15<54:50,  8.45it/s]

 35%|████████████▍                       | 14722/42525 [28:15<50:11,  9.23it/s]

 35%|████████████▍                       | 14724/42525 [28:15<51:51,  8.93it/s]

 35%|████████████▍                       | 14727/42525 [28:15<51:02,  9.08it/s]

 35%|████████████▍                       | 14730/42525 [28:16<48:24,  9.57it/s]

 35%|████████████▍                       | 14734/42525 [28:16<46:40,  9.92it/s]

 35%|████████████▍                       | 14737/42525 [28:16<47:30,  9.75it/s]

 35%|████████████▍                       | 14740/42525 [28:17<49:03,  9.44it/s]

 35%|████████████▍                       | 14742/42525 [28:17<48:56,  9.46it/s]

 35%|████████████▍                       | 14745/42525 [28:17<51:07,  9.06it/s]

 35%|████████████▍                       | 14749/42525 [28:18<47:44,  9.70it/s]

 35%|████████████▍                       | 14751/42525 [28:18<50:14,  9.21it/s]

 35%|████████████▍                       | 14753/42525 [28:18<50:16,  9.21it/s]

 35%|████████████▍                       | 14756/42525 [28:19<50:37,  9.14it/s]

 35%|████████████▍                       | 14759/42525 [28:19<49:18,  9.38it/s]

 35%|████████████▍                       | 14762/42525 [28:19<49:20,  9.38it/s]

 35%|████████████▍                       | 14764/42525 [28:19<49:36,  9.33it/s]

 35%|████████████▍                       | 14765/42525 [28:19<49:31,  9.34it/s]

 35%|████████████▌                       | 14768/42525 [28:20<48:08,  9.61it/s]

 35%|████████████▌                       | 14769/42525 [28:20<53:06,  8.71it/s]

 35%|████████████▌                       | 14772/42525 [28:20<51:52,  8.92it/s]

 35%|████████████▌                       | 14774/42525 [28:20<49:20,  9.37it/s]

 35%|████████████▌                       | 14778/42525 [28:21<47:21,  9.77it/s]

 35%|████████████▌                       | 14780/42525 [28:21<50:28,  9.16it/s]

 35%|████████████▌                       | 14781/42525 [28:21<50:17,  9.19it/s]

 35%|████████████▌                       | 14783/42525 [28:21<52:20,  8.83it/s]

 35%|████████████▌                       | 14785/42525 [28:22<53:52,  8.58it/s]

 35%|████████████▌                       | 14788/42525 [28:22<52:28,  8.81it/s]

 35%|████████████▌                       | 14792/42525 [28:22<48:14,  9.58it/s]

 35%|████████████▌                       | 14796/42525 [28:23<47:42,  9.69it/s]

 35%|████████████▌                       | 14798/42525 [28:23<46:46,  9.88it/s]

 35%|████████████▌                       | 14800/42525 [28:23<48:12,  9.59it/s]

 35%|████████████▌                       | 14803/42525 [28:24<52:28,  8.80it/s]

 35%|████████████▌                       | 14806/42525 [28:24<49:52,  9.26it/s]

 35%|████████████▌                       | 14809/42525 [28:24<52:11,  8.85it/s]

 35%|████████████▌                       | 14812/42525 [28:25<56:13,  8.21it/s]

 35%|████████████▌                       | 14814/42525 [28:25<55:59,  8.25it/s]

 35%|████████████▌                       | 14815/42525 [28:25<53:37,  8.61it/s]

 35%|████████████▌                       | 14819/42525 [28:25<49:04,  9.41it/s]

 35%|████████████▌                       | 14822/42525 [28:26<49:12,  9.38it/s]

 35%|████████████▌                       | 14825/42525 [28:26<49:39,  9.30it/s]

 35%|████████████▌                       | 14829/42525 [28:26<47:44,  9.67it/s]

 35%|████████████▌                       | 14831/42525 [28:27<51:47,  8.91it/s]

 35%|████████████▌                       | 14833/42525 [28:27<53:38,  8.60it/s]

 35%|████████████▌                       | 14835/42525 [28:27<51:22,  8.98it/s]

 35%|████████████▌                       | 14839/42525 [28:28<48:58,  9.42it/s]

 35%|████████████▌                       | 14841/42525 [28:28<53:32,  8.62it/s]

 35%|████████████▌                       | 14845/42525 [28:28<51:37,  8.94it/s]

 35%|████████████▌                       | 14847/42525 [28:28<52:16,  8.83it/s]

 35%|████████████▌                       | 14850/42525 [28:29<51:49,  8.90it/s]

 35%|████████████▌                       | 14851/42525 [28:29<52:49,  8.73it/s]

 35%|████████████▌                       | 14855/42525 [28:29<48:37,  9.48it/s]

 35%|████████████▌                       | 14859/42525 [28:30<47:46,  9.65it/s]

 35%|████████████▌                       | 14862/42525 [28:30<46:36,  9.89it/s]

 35%|████████████▌                       | 14864/42525 [28:30<51:29,  8.95it/s]

 35%|████████████▌                       | 14867/42525 [28:31<55:34,  8.30it/s]

 35%|████████████▌                       | 14869/42525 [28:31<51:18,  8.99it/s]

 35%|████████████▌                       | 14872/42525 [28:31<50:43,  9.08it/s]

 35%|████████████▌                       | 14875/42525 [28:32<49:54,  9.23it/s]

 35%|████████████▌                       | 14878/42525 [28:32<50:18,  9.16it/s]

 35%|████████████▌                       | 14882/42525 [28:32<47:14,  9.75it/s]

 35%|████████████▌                       | 14886/42525 [28:33<46:08,  9.98it/s]

 35%|████████████▌                       | 14888/42525 [28:33<54:09,  8.50it/s]

 35%|████████████▌                       | 14892/42525 [28:33<48:53,  9.42it/s]

 35%|████████████▌                       | 14896/42525 [28:34<46:47,  9.84it/s]

 35%|████████████▌                       | 14899/42525 [28:34<50:52,  9.05it/s]

 35%|████████████▌                       | 14901/42525 [28:34<50:28,  9.12it/s]

 35%|████████████▌                       | 14903/42525 [28:35<57:04,  8.07it/s]

 35%|████████████▌                       | 14906/42525 [28:35<56:17,  8.18it/s]

 35%|████████████▌                       | 14908/42525 [28:35<58:40,  7.84it/s]

 35%|████████████▌                       | 14911/42525 [28:36<54:07,  8.50it/s]

 35%|████████████▋                       | 14914/42525 [28:36<49:50,  9.23it/s]

 35%|████████████▋                       | 14917/42525 [28:36<52:09,  8.82it/s]

 35%|████████████▋                       | 14921/42525 [28:37<49:39,  9.26it/s]

 35%|████████████▋                       | 14923/42525 [28:37<54:30,  8.44it/s]

 35%|████████████▋                       | 14925/42525 [28:37<56:17,  8.17it/s]

 35%|████████████▋                       | 14927/42525 [28:37<53:20,  8.62it/s]

 35%|████████████▋                       | 14930/42525 [28:38<53:25,  8.61it/s]

 35%|████████████▋                       | 14933/42525 [28:38<50:02,  9.19it/s]

 35%|████████████▋                       | 14937/42525 [28:38<46:57,  9.79it/s]

 35%|████████████▋                       | 14939/42525 [28:39<51:30,  8.93it/s]

 35%|████████████▋                       | 14941/42525 [28:39<51:09,  8.99it/s]

 35%|████████████▋                       | 14943/42525 [28:39<54:50,  8.38it/s]

 35%|████████████▋                       | 14944/42525 [28:39<58:30,  7.86it/s]

 35%|████████████▋                       | 14946/42525 [28:40<53:11,  8.64it/s]

 35%|████████████▋                       | 14949/42525 [28:40<50:28,  9.10it/s]

 35%|████████████▋                       | 14951/42525 [28:40<48:12,  9.53it/s]

 35%|████████████▋                       | 14953/42525 [28:40<50:20,  9.13it/s]

 35%|████████████▋                       | 14955/42525 [28:40<48:58,  9.38it/s]

 35%|████████████▋                       | 14957/42525 [28:41<48:15,  9.52it/s]

 35%|████████████▋                       | 14960/42525 [28:41<52:01,  8.83it/s]

 35%|████████████▋                       | 14961/42525 [28:41<53:00,  8.67it/s]

 35%|████████████▋                       | 14964/42525 [28:42<55:24,  8.29it/s]

 35%|████████████▋                       | 14966/42525 [28:42<53:59,  8.51it/s]

 35%|████████████▋                       | 14969/42525 [28:42<54:53,  8.37it/s]

 35%|████████████▋                       | 14971/42525 [28:42<51:31,  8.91it/s]

 35%|████████████▋                       | 14974/42525 [28:43<51:01,  9.00it/s]

 35%|████████████▋                       | 14976/42525 [28:43<53:46,  8.54it/s]

 35%|████████████▋                       | 14978/42525 [28:43<53:31,  8.58it/s]

 35%|████████████▋                       | 14982/42525 [28:44<49:28,  9.28it/s]

 35%|████████████▋                       | 14984/42525 [28:44<47:45,  9.61it/s]

 35%|████████████▋                       | 14988/42525 [28:44<47:49,  9.59it/s]

 35%|████████████▋                       | 14989/42525 [28:44<49:36,  9.25it/s]

 35%|████████████▋                       | 14992/42525 [28:45<50:31,  9.08it/s]

 35%|████████████▋                       | 14994/42525 [28:45<47:52,  9.59it/s]

 35%|████████████▋                       | 14997/42525 [28:45<54:12,  8.46it/s]

 35%|████████████▋                       | 15000/42525 [28:45<50:18,  9.12it/s]

 35%|████████████▋                       | 15002/42525 [28:46<50:07,  9.15it/s]

 35%|████████████▋                       | 15005/42525 [28:46<48:54,  9.38it/s]

 35%|████████████▋                       | 15008/42525 [28:46<49:51,  9.20it/s]

 35%|████████████▋                       | 15010/42525 [28:47<47:41,  9.62it/s]

 35%|████████████▋                       | 15013/42525 [28:47<53:10,  8.62it/s]

 35%|████████████▋                       | 15014/42525 [28:47<52:52,  8.67it/s]

 35%|████████████▋                       | 15016/42525 [28:47<54:32,  8.41it/s]

 35%|████████████▋                       | 15019/42525 [28:48<50:48,  9.02it/s]

 35%|████████████▋                       | 15023/42525 [28:48<47:07,  9.73it/s]

 35%|████████████▋                       | 15027/42525 [28:48<46:03,  9.95it/s]

 35%|████████████▋                       | 15030/42525 [28:49<46:29,  9.86it/s]

 35%|████████████▋                       | 15034/42525 [28:49<45:18, 10.11it/s]

 35%|████████████▋                       | 15037/42525 [28:49<50:34,  9.06it/s]

 35%|████████████▋                       | 15040/42525 [28:50<49:28,  9.26it/s]

 35%|████████████▋                       | 15043/42525 [28:50<48:04,  9.53it/s]

 35%|████████████▋                       | 15047/42525 [28:50<46:51,  9.77it/s]

 35%|████████████▋                       | 15050/42525 [28:51<50:34,  9.05it/s]

 35%|████████████▋                       | 15053/42525 [28:51<48:07,  9.51it/s]

 35%|████████████▋                       | 15055/42525 [28:51<48:19,  9.47it/s]

 35%|████████████▋                       | 15057/42525 [28:52<54:12,  8.45it/s]

 35%|████████████▋                       | 15059/42525 [28:52<56:46,  8.06it/s]

 35%|████████████▊                       | 15061/42525 [28:52<59:03,  7.75it/s]

 35%|████████████                      | 15063/42525 [28:52<1:00:57,  7.51it/s]

 35%|████████████▊                       | 15067/42525 [28:53<50:06,  9.13it/s]

 35%|████████████▊                       | 15069/42525 [28:53<49:56,  9.16it/s]

 35%|████████████▊                       | 15071/42525 [28:53<52:21,  8.74it/s]

 35%|████████████▊                       | 15072/42525 [28:53<50:56,  8.98it/s]

 35%|████████████▊                       | 15076/42525 [28:54<49:56,  9.16it/s]

 35%|████████████▊                       | 15079/42525 [28:54<51:19,  8.91it/s]

 35%|████████████▊                       | 15081/42525 [28:54<48:49,  9.37it/s]

 35%|████████████▊                       | 15084/42525 [28:55<49:09,  9.30it/s]

 35%|████████████▊                       | 15086/42525 [28:55<57:08,  8.00it/s]

 35%|████████████▊                       | 15088/42525 [28:55<56:04,  8.15it/s]

 35%|████████████▊                       | 15092/42525 [28:56<48:18,  9.46it/s]

 35%|████████████▊                       | 15095/42525 [28:56<51:15,  8.92it/s]

 36%|████████████▊                       | 15099/42525 [28:56<47:34,  9.61it/s]

 36%|████████████▊                       | 15101/42525 [28:57<50:01,  9.14it/s]

 36%|████████████▊                       | 15103/42525 [28:57<52:10,  8.76it/s]

 36%|████████████▊                       | 15106/42525 [28:57<53:33,  8.53it/s]

 36%|████████████▊                       | 15109/42525 [28:58<51:59,  8.79it/s]

 36%|████████████▊                       | 15112/42525 [28:58<51:46,  8.83it/s]

 36%|████████████▊                       | 15114/42525 [28:58<54:40,  8.35it/s]

 36%|████████████▊                       | 15118/42525 [28:59<51:15,  8.91it/s]

 36%|████████████▊                       | 15120/42525 [28:59<54:07,  8.44it/s]

 36%|████████████▊                       | 15121/42525 [28:59<52:05,  8.77it/s]

 36%|████████████▊                       | 15125/42525 [28:59<50:29,  9.05it/s]

 36%|████████████▊                       | 15127/42525 [29:00<52:15,  8.74it/s]

 36%|████████████▊                       | 15130/42525 [29:00<48:35,  9.40it/s]

 36%|████████████▊                       | 15134/42525 [29:00<46:03,  9.91it/s]

 36%|████████████▊                       | 15136/42525 [29:00<45:19, 10.07it/s]

 36%|████████████▊                       | 15138/42525 [29:01<45:32, 10.02it/s]

 36%|████████████▊                       | 15142/42525 [29:01<47:18,  9.65it/s]

 36%|████████████▊                       | 15144/42525 [29:01<51:47,  8.81it/s]

 36%|████████████▊                       | 15148/42525 [29:02<47:09,  9.68it/s]

 36%|████████████▊                       | 15151/42525 [29:02<48:43,  9.36it/s]

 36%|████████████▊                       | 15153/42525 [29:02<50:33,  9.02it/s]

 36%|████████████▊                       | 15154/42525 [29:02<50:42,  9.00it/s]

 36%|████████████▊                       | 15157/42525 [29:03<51:54,  8.79it/s]

 36%|████████████▊                       | 15161/42525 [29:03<47:45,  9.55it/s]

 36%|████████████▊                       | 15165/42525 [29:04<48:31,  9.40it/s]

 36%|████████████▊                       | 15168/42525 [29:04<47:15,  9.65it/s]

 36%|████████████▊                       | 15170/42525 [29:04<47:57,  9.50it/s]

 36%|████████████▊                       | 15174/42525 [29:05<49:23,  9.23it/s]

 36%|████████████▊                       | 15177/42525 [29:05<51:30,  8.85it/s]

 36%|████████████▊                       | 15179/42525 [29:05<50:54,  8.95it/s]

 36%|████████████▊                       | 15180/42525 [29:05<52:08,  8.74it/s]

 36%|████████████▊                       | 15183/42525 [29:06<50:16,  9.06it/s]

 36%|████████████▊                       | 15186/42525 [29:06<50:17,  9.06it/s]

 36%|████████████▊                       | 15189/42525 [29:06<47:50,  9.52it/s]

 36%|████████████▊                       | 15190/42525 [29:06<48:15,  9.44it/s]

 36%|████████████▊                       | 15192/42525 [29:07<51:25,  8.86it/s]

 36%|████████████▊                       | 15195/42525 [29:07<50:23,  9.04it/s]

 36%|████████████▊                       | 15197/42525 [29:07<48:02,  9.48it/s]

 36%|████████████▊                       | 15201/42525 [29:08<46:20,  9.83it/s]

 36%|████████████▊                       | 15203/42525 [29:08<46:40,  9.76it/s]

 36%|████████████▊                       | 15207/42525 [29:08<46:15,  9.84it/s]

 36%|████████████▉                       | 15209/42525 [29:08<48:23,  9.41it/s]

 36%|████████████▉                       | 15212/42525 [29:09<46:50,  9.72it/s]

 36%|████████████▉                       | 15215/42525 [29:09<52:07,  8.73it/s]

 36%|████████████▉                       | 15218/42525 [29:09<48:27,  9.39it/s]

 36%|████████████▉                       | 15221/42525 [29:10<47:17,  9.62it/s]

 36%|████████████▉                       | 15224/42525 [29:10<48:35,  9.37it/s]

 36%|████████████▉                       | 15226/42525 [29:10<49:17,  9.23it/s]

 36%|████████████▉                       | 15227/42525 [29:10<48:59,  9.29it/s]

 36%|████████████▉                       | 15230/42525 [29:11<50:05,  9.08it/s]

 36%|████████████▉                       | 15234/42525 [29:11<46:41,  9.74it/s]

 36%|████████████▉                       | 15237/42525 [29:11<45:49,  9.92it/s]

 36%|████████████▉                       | 15240/42525 [29:12<46:17,  9.82it/s]

 36%|████████████▉                       | 15242/42525 [29:12<49:28,  9.19it/s]

 36%|████████████▉                       | 15244/42525 [29:12<47:02,  9.66it/s]

 36%|████████████▉                       | 15246/42525 [29:12<46:57,  9.68it/s]

 36%|████████████▉                       | 15248/42525 [29:12<50:08,  9.07it/s]

 36%|████████████▉                       | 15251/42525 [29:13<49:07,  9.25it/s]

 36%|████████████▉                       | 15254/42525 [29:13<51:34,  8.81it/s]

 36%|████████████▉                       | 15257/42525 [29:13<48:38,  9.34it/s]

 36%|████████████▉                       | 15259/42525 [29:14<56:17,  8.07it/s]

 36%|████████████▉                       | 15261/42525 [29:14<57:42,  7.87it/s]

 36%|████████████▉                       | 15263/42525 [29:14<55:21,  8.21it/s]

 36%|████████████▉                       | 15265/42525 [29:14<54:06,  8.40it/s]

 36%|████████████▉                       | 15266/42525 [29:15<56:01,  8.11it/s]

 36%|████████████▉                       | 15269/42525 [29:15<59:07,  7.68it/s]

 36%|████████████▏                     | 15271/42525 [29:15<1:01:05,  7.44it/s]

 36%|████████████▉                       | 15274/42525 [29:16<56:58,  7.97it/s]

 36%|████████████▉                       | 15278/42525 [29:16<49:07,  9.24it/s]

 36%|████████████▉                       | 15281/42525 [29:16<47:18,  9.60it/s]

 36%|████████████▉                       | 15283/42525 [29:17<50:25,  9.00it/s]

 36%|████████████▉                       | 15285/42525 [29:17<48:47,  9.30it/s]

 36%|████████████▉                       | 15288/42525 [29:17<50:12,  9.04it/s]

 36%|████████████▉                       | 15290/42525 [29:17<50:31,  8.98it/s]

 36%|████████████▉                       | 15292/42525 [29:18<58:28,  7.76it/s]

 36%|████████████▏                     | 15294/42525 [29:18<1:00:01,  7.56it/s]

 36%|████████████▉                       | 15298/42525 [29:18<49:27,  9.18it/s]

 36%|████████████▉                       | 15300/42525 [29:19<51:30,  8.81it/s]

 36%|████████████▉                       | 15302/42525 [29:19<48:35,  9.34it/s]

 36%|████████████▉                       | 15305/42525 [29:19<51:08,  8.87it/s]

 36%|████████████▉                       | 15309/42525 [29:19<46:50,  9.69it/s]

 36%|████████████▉                       | 15312/42525 [29:20<46:22,  9.78it/s]

 36%|████████████▉                       | 15315/42525 [29:20<47:01,  9.65it/s]

 36%|████████████▉                       | 15317/42525 [29:20<49:55,  9.08it/s]

 36%|████████████▉                       | 15319/42525 [29:21<53:42,  8.44it/s]

 36%|████████████▉                       | 15323/42525 [29:21<47:24,  9.56it/s]

 36%|████████████▉                       | 15324/42525 [29:21<48:32,  9.34it/s]

 36%|████████████▉                       | 15328/42525 [29:22<48:37,  9.32it/s]

 36%|████████████▉                       | 15330/42525 [29:22<54:03,  8.38it/s]

 36%|████████████▉                       | 15332/42525 [29:22<55:38,  8.15it/s]

 36%|████████████▉                       | 15335/42525 [29:22<57:27,  7.89it/s]

 36%|████████████▉                       | 15337/42525 [29:23<59:19,  7.64it/s]

 36%|████████████▎                     | 15339/42525 [29:23<1:03:05,  7.18it/s]

 36%|████████████▉                       | 15342/42525 [29:23<54:53,  8.25it/s]

 36%|████████████▉                       | 15344/42525 [29:24<54:00,  8.39it/s]

 36%|████████████▉                       | 15346/42525 [29:24<57:28,  7.88it/s]

 36%|████████████▉                       | 15350/42525 [29:24<48:25,  9.35it/s]

 36%|████████████▉                       | 15352/42525 [29:24<50:00,  9.06it/s]

 36%|████████████▉                       | 15353/42525 [29:25<54:17,  8.34it/s]

 36%|█████████████                       | 15357/42525 [29:25<50:39,  8.94it/s]

 36%|█████████████                       | 15361/42525 [29:25<46:54,  9.65it/s]

 36%|█████████████                       | 15363/42525 [29:26<48:21,  9.36it/s]

 36%|█████████████                       | 15366/42525 [29:26<47:00,  9.63it/s]

 36%|█████████████                       | 15368/42525 [29:26<45:42,  9.90it/s]

 36%|█████████████                       | 15370/42525 [29:26<46:02,  9.83it/s]

 36%|█████████████                       | 15373/42525 [29:27<52:15,  8.66it/s]

 36%|█████████████                       | 15375/42525 [29:27<50:33,  8.95it/s]

 36%|█████████████                       | 15377/42525 [29:27<53:52,  8.40it/s]

 36%|█████████████                       | 15380/42525 [29:28<49:25,  9.15it/s]

 36%|█████████████                       | 15383/42525 [29:28<47:14,  9.58it/s]

 36%|█████████████                       | 15385/42525 [29:28<50:16,  9.00it/s]

 36%|█████████████                       | 15388/42525 [29:28<51:21,  8.81it/s]

 36%|█████████████                       | 15391/42525 [29:29<48:45,  9.27it/s]

 36%|█████████████                       | 15393/42525 [29:29<50:28,  8.96it/s]

 36%|█████████████                       | 15396/42525 [29:29<49:53,  9.06it/s]

 36%|█████████████                       | 15400/42525 [29:30<46:39,  9.69it/s]

 36%|█████████████                       | 15404/42525 [29:30<44:56, 10.06it/s]

 36%|█████████████                       | 15406/42525 [29:30<44:59, 10.05it/s]

 36%|█████████████                       | 15409/42525 [29:31<47:10,  9.58it/s]

 36%|█████████████                       | 15412/42525 [29:31<48:23,  9.34it/s]

 36%|█████████████                       | 15415/42525 [29:31<47:32,  9.50it/s]

 36%|█████████████                       | 15417/42525 [29:31<49:47,  9.07it/s]

 36%|█████████████                       | 15420/42525 [29:32<52:05,  8.67it/s]

 36%|█████████████                       | 15422/42525 [29:32<50:22,  8.97it/s]

 36%|█████████████                       | 15424/42525 [29:32<53:19,  8.47it/s]

 36%|█████████████                       | 15427/42525 [29:33<51:04,  8.84it/s]

 36%|█████████████                       | 15430/42525 [29:33<55:52,  8.08it/s]

 36%|█████████████                       | 15434/42525 [29:33<49:36,  9.10it/s]

 36%|█████████████                       | 15438/42525 [29:34<46:36,  9.69it/s]

 36%|█████████████                       | 15439/42525 [29:34<46:29,  9.71it/s]

 36%|█████████████                       | 15442/42525 [29:34<49:57,  9.04it/s]

 36%|█████████████                       | 15445/42525 [29:35<48:01,  9.40it/s]

 36%|█████████████                       | 15448/42525 [29:35<46:18,  9.74it/s]

 36%|█████████████                       | 15452/42525 [29:35<45:00, 10.02it/s]

 36%|█████████████                       | 15455/42525 [29:36<45:40,  9.88it/s]

 36%|█████████████                       | 15457/42525 [29:36<50:43,  8.90it/s]

 36%|█████████████                       | 15459/42525 [29:36<50:45,  8.89it/s]

 36%|█████████████                       | 15461/42525 [29:36<49:52,  9.04it/s]

 36%|█████████████                       | 15463/42525 [29:37<49:48,  9.06it/s]

 36%|█████████████                       | 15467/42525 [29:37<45:40,  9.87it/s]

 36%|█████████████                       | 15469/42525 [29:37<47:45,  9.44it/s]

 36%|█████████████                       | 15471/42525 [29:37<48:07,  9.37it/s]

 36%|█████████████                       | 15474/42525 [29:38<46:05,  9.78it/s]

 36%|█████████████                       | 15478/42525 [29:38<45:33,  9.89it/s]

 36%|█████████████                       | 15481/42525 [29:38<47:16,  9.53it/s]

 36%|█████████████                       | 15485/42525 [29:39<45:28,  9.91it/s]

 36%|█████████████                       | 15488/42525 [29:39<45:38,  9.87it/s]

 36%|█████████████                       | 15490/42525 [29:39<48:11,  9.35it/s]

 36%|█████████████                       | 15492/42525 [29:40<52:28,  8.59it/s]

 36%|█████████████                       | 15495/42525 [29:40<51:04,  8.82it/s]

 36%|█████████████                       | 15498/42525 [29:40<49:51,  9.03it/s]

 36%|█████████████                       | 15500/42525 [29:40<49:55,  9.02it/s]

 36%|█████████████                       | 15502/42525 [29:41<49:31,  9.10it/s]

 36%|█████████████▏                      | 15504/42525 [29:41<53:38,  8.39it/s]

 36%|█████████████▏                      | 15507/42525 [29:41<48:02,  9.37it/s]

 36%|█████████████▏                      | 15508/42525 [29:41<47:56,  9.39it/s]

 36%|█████████████▏                      | 15512/42525 [29:42<46:26,  9.70it/s]

 36%|█████████████▏                      | 15513/42525 [29:42<50:34,  8.90it/s]

 36%|█████████████▏                      | 15517/42525 [29:42<48:01,  9.37it/s]

 36%|█████████████▏                      | 15519/42525 [29:43<49:42,  9.05it/s]

 37%|█████████████▏                      | 15522/42525 [29:43<54:12,  8.30it/s]

 37%|█████████████▏                      | 15525/42525 [29:43<51:41,  8.71it/s]

 37%|█████████████▏                      | 15528/42525 [29:44<49:23,  9.11it/s]

 37%|█████████████▏                      | 15530/42525 [29:44<48:04,  9.36it/s]

 37%|█████████████▏                      | 15533/42525 [29:44<53:47,  8.36it/s]

 37%|█████████████▏                      | 15536/42525 [29:44<50:52,  8.84it/s]

 37%|█████████████▏                      | 15538/42525 [29:45<57:35,  7.81it/s]

 37%|█████████████▏                      | 15541/42525 [29:45<53:34,  8.39it/s]

 37%|█████████████▏                      | 15545/42525 [29:45<47:20,  9.50it/s]

 37%|█████████████▏                      | 15548/42525 [29:46<50:13,  8.95it/s]

 37%|█████████████▏                      | 15550/42525 [29:46<53:26,  8.41it/s]

 37%|█████████████▏                      | 15552/42525 [29:46<55:32,  8.09it/s]

 37%|█████████████▏                      | 15553/42525 [29:46<54:11,  8.29it/s]

 37%|█████████████▏                      | 15556/42525 [29:47<55:42,  8.07it/s]

 37%|█████████████▏                      | 15559/42525 [29:47<51:13,  8.77it/s]

 37%|█████████████▏                      | 15562/42525 [29:47<47:37,  9.44it/s]

 37%|█████████████▏                      | 15565/42525 [29:48<47:59,  9.36it/s]

 37%|█████████████▏                      | 15566/42525 [29:48<50:24,  8.91it/s]

 37%|█████████████▏                      | 15570/42525 [29:48<48:06,  9.34it/s]

 37%|█████████████▏                      | 15574/42525 [29:49<45:20,  9.91it/s]

 37%|█████████████▏                      | 15576/42525 [29:49<46:22,  9.68it/s]

 37%|█████████████▏                      | 15579/42525 [29:49<48:39,  9.23it/s]

 37%|█████████████▏                      | 15583/42525 [29:50<46:40,  9.62it/s]

 37%|█████████████▏                      | 15584/42525 [29:50<47:02,  9.54it/s]

 37%|█████████████▏                      | 15587/42525 [29:50<47:11,  9.51it/s]

 37%|█████████████▏                      | 15588/42525 [29:50<47:06,  9.53it/s]

 37%|█████████████▏                      | 15592/42525 [29:51<47:10,  9.52it/s]

 37%|█████████████▏                      | 15595/42525 [29:51<49:58,  8.98it/s]

 37%|█████████████▏                      | 15597/42525 [29:51<55:28,  8.09it/s]

 37%|█████████████▏                      | 15599/42525 [29:51<50:45,  8.84it/s]

 37%|█████████████▏                      | 15603/42525 [29:52<47:32,  9.44it/s]

 37%|█████████████▏                      | 15607/42525 [29:52<47:59,  9.35it/s]

 37%|█████████████▏                      | 15610/42525 [29:53<47:24,  9.46it/s]

 37%|█████████████▏                      | 15613/42525 [29:53<46:39,  9.61it/s]

 37%|█████████████▏                      | 15615/42525 [29:53<49:47,  9.01it/s]

 37%|█████████████▏                      | 15618/42525 [29:53<50:27,  8.89it/s]

 37%|█████████████▏                      | 15619/42525 [29:54<51:44,  8.67it/s]

 37%|█████████████▏                      | 15622/42525 [29:54<49:21,  9.08it/s]

 37%|█████████████▏                      | 15624/42525 [29:54<53:04,  8.45it/s]

 37%|█████████████▏                      | 15625/42525 [29:54<51:09,  8.76it/s]

 37%|█████████████▏                      | 15629/42525 [29:55<47:21,  9.47it/s]

 37%|█████████████▏                      | 15632/42525 [29:55<48:09,  9.31it/s]

 37%|█████████████▏                      | 15634/42525 [29:55<48:53,  9.17it/s]

 37%|█████████████▏                      | 15637/42525 [29:56<49:13,  9.10it/s]

 37%|█████████████▏                      | 15639/42525 [29:56<48:26,  9.25it/s]

 37%|█████████████▏                      | 15640/42525 [29:56<48:19,  9.27it/s]

 37%|█████████████▏                      | 15643/42525 [29:56<53:55,  8.31it/s]

 37%|█████████████▏                      | 15645/42525 [29:57<53:48,  8.33it/s]

 37%|█████████████▏                      | 15647/42525 [29:57<55:35,  8.06it/s]

 37%|█████████████▏                      | 15649/42525 [29:57<52:57,  8.46it/s]

 37%|█████████████▎                      | 15653/42525 [29:57<46:48,  9.57it/s]

 37%|█████████████▎                      | 15655/42525 [29:58<49:50,  8.99it/s]

 37%|█████████████▎                      | 15659/42525 [29:58<48:12,  9.29it/s]

 37%|█████████████▎                      | 15662/42525 [29:58<48:10,  9.29it/s]

 37%|█████████████▎                      | 15664/42525 [29:59<49:13,  9.09it/s]

 37%|█████████████▎                      | 15667/42525 [29:59<49:10,  9.10it/s]

 37%|█████████████▎                      | 15670/42525 [29:59<50:10,  8.92it/s]

 37%|█████████████▎                      | 15673/42525 [30:00<48:41,  9.19it/s]

 37%|█████████████▎                      | 15675/42525 [30:00<52:41,  8.49it/s]

 37%|█████████████▎                      | 15677/42525 [30:00<48:47,  9.17it/s]

 37%|█████████████▎                      | 15679/42525 [30:00<47:33,  9.41it/s]

 37%|█████████████▎                      | 15681/42525 [30:00<48:37,  9.20it/s]

 37%|█████████████▎                      | 15683/42525 [30:01<50:14,  8.91it/s]

 37%|█████████████▎                      | 15687/42525 [30:01<47:01,  9.51it/s]

 37%|█████████████▎                      | 15691/42525 [30:02<45:14,  9.89it/s]

 37%|█████████████▎                      | 15694/42525 [30:02<47:04,  9.50it/s]

 37%|█████████████▎                      | 15696/42525 [30:02<51:57,  8.60it/s]

 37%|█████████████▎                      | 15700/42525 [30:03<46:43,  9.57it/s]

 37%|█████████████▎                      | 15704/42525 [30:03<44:56,  9.95it/s]

 37%|█████████████▎                      | 15707/42525 [30:03<46:58,  9.51it/s]

 37%|█████████████▎                      | 15709/42525 [30:03<45:49,  9.75it/s]

 37%|█████████████▎                      | 15712/42525 [30:04<48:29,  9.22it/s]

 37%|█████████████▎                      | 15715/42525 [30:04<50:32,  8.84it/s]

 37%|█████████████▎                      | 15717/42525 [30:04<53:09,  8.41it/s]

 37%|█████████████▎                      | 15720/42525 [30:05<48:52,  9.14it/s]

 37%|█████████████▎                      | 15723/42525 [30:05<48:57,  9.12it/s]

 37%|█████████████▎                      | 15726/42525 [30:05<46:00,  9.71it/s]

 37%|█████████████▎                      | 15728/42525 [30:05<44:56,  9.94it/s]

 37%|█████████████▎                      | 15732/42525 [30:06<46:32,  9.59it/s]

 37%|█████████████▎                      | 15734/42525 [30:06<47:22,  9.42it/s]

 37%|█████████████▎                      | 15736/42525 [30:06<48:39,  9.18it/s]

 37%|█████████████▎                      | 15738/42525 [30:07<51:56,  8.60it/s]

 37%|█████████████▎                      | 15742/42525 [30:07<47:24,  9.42it/s]

 37%|█████████████▎                      | 15744/42525 [30:07<51:49,  8.61it/s]

 37%|█████████████▎                      | 15748/42525 [30:08<46:44,  9.55it/s]

 37%|█████████████▎                      | 15749/42525 [30:08<46:40,  9.56it/s]

 37%|█████████████▎                      | 15752/42525 [30:08<48:03,  9.29it/s]

 37%|█████████████▎                      | 15754/42525 [30:08<50:45,  8.79it/s]

 37%|█████████████▎                      | 15758/42525 [30:09<46:28,  9.60it/s]

 37%|█████████████▎                      | 15762/42525 [30:09<47:29,  9.39it/s]

 37%|█████████████▎                      | 15765/42525 [30:10<47:50,  9.32it/s]

 37%|█████████████▎                      | 15767/42525 [30:10<46:06,  9.67it/s]

 37%|█████████████▎                      | 15769/42525 [30:10<49:02,  9.09it/s]

 37%|█████████████▎                      | 15772/42525 [30:10<53:13,  8.38it/s]

 37%|█████████████▎                      | 15774/42525 [30:11<50:39,  8.80it/s]

 37%|█████████████▎                      | 15777/42525 [30:11<48:35,  9.17it/s]

 37%|█████████████▎                      | 15781/42525 [30:11<46:20,  9.62it/s]

 37%|█████████████▎                      | 15783/42525 [30:12<48:31,  9.18it/s]

 37%|█████████████▎                      | 15785/42525 [30:12<52:32,  8.48it/s]

 37%|█████████████▎                      | 15787/42525 [30:12<49:32,  9.00it/s]

 37%|█████████████▎                      | 15790/42525 [30:12<52:37,  8.47it/s]

 37%|█████████████▎                      | 15793/42525 [30:13<48:06,  9.26it/s]

 37%|█████████████▎                      | 15796/42525 [30:13<50:34,  8.81it/s]

 37%|█████████████▎                      | 15797/42525 [30:13<53:54,  8.26it/s]

 37%|█████████████▍                      | 15801/42525 [30:14<50:32,  8.81it/s]

 37%|█████████████▍                      | 15805/42525 [30:14<46:20,  9.61it/s]

 37%|█████████████▍                      | 15807/42525 [30:14<45:14,  9.84it/s]

 37%|█████████████▍                      | 15810/42525 [30:14<46:23,  9.60it/s]

 37%|█████████████▍                      | 15812/42525 [30:15<46:14,  9.63it/s]

 37%|█████████████▍                      | 15815/42525 [30:15<49:23,  9.01it/s]

 37%|█████████████▍                      | 15818/42525 [30:15<49:10,  9.05it/s]

 37%|█████████████▍                      | 15821/42525 [30:16<47:36,  9.35it/s]

 37%|█████████████▍                      | 15824/42525 [30:16<45:48,  9.71it/s]

 37%|█████████████▍                      | 15826/42525 [30:16<47:28,  9.37it/s]

 37%|█████████████▍                      | 15829/42525 [30:17<50:30,  8.81it/s]

 37%|█████████████▍                      | 15831/42525 [30:17<47:35,  9.35it/s]

 37%|█████████████▍                      | 15833/42525 [30:17<50:11,  8.86it/s]

 37%|█████████████▍                      | 15836/42525 [30:17<51:08,  8.70it/s]

 37%|█████████████▍                      | 15839/42525 [30:18<48:17,  9.21it/s]

 37%|█████████████▍                      | 15842/42525 [30:18<54:05,  8.22it/s]

 37%|█████████████▍                      | 15844/42525 [30:18<54:25,  8.17it/s]

 37%|█████████████▍                      | 15848/42525 [30:19<50:35,  8.79it/s]

 37%|█████████████▍                      | 15850/42525 [30:19<50:40,  8.77it/s]

 37%|█████████████▍                      | 15853/42525 [30:19<47:48,  9.30it/s]

 37%|█████████████▍                      | 15856/42525 [30:20<47:51,  9.29it/s]

 37%|█████████████▍                      | 15858/42525 [30:20<53:06,  8.37it/s]

 37%|█████████████▍                      | 15861/42525 [30:20<50:59,  8.72it/s]

 37%|█████████████▍                      | 15864/42525 [30:20<49:39,  8.95it/s]

 37%|█████████████▍                      | 15867/42525 [30:21<51:22,  8.65it/s]

 37%|█████████████▍                      | 15870/42525 [30:21<52:13,  8.51it/s]

 37%|█████████████▍                      | 15872/42525 [30:21<51:12,  8.68it/s]

 37%|█████████████▍                      | 15875/42525 [30:22<49:32,  8.97it/s]

 37%|█████████████▍                      | 15877/42525 [30:22<51:11,  8.67it/s]

 37%|█████████████▍                      | 15879/42525 [30:22<50:05,  8.86it/s]

 37%|█████████████▍                      | 15881/42525 [30:22<51:42,  8.59it/s]

 37%|█████████████▍                      | 15884/42525 [30:23<46:40,  9.51it/s]

 37%|█████████████▍                      | 15886/42525 [30:23<44:55,  9.88it/s]

 37%|█████████████▍                      | 15890/42525 [30:23<46:33,  9.54it/s]

 37%|█████████████▍                      | 15892/42525 [30:24<49:06,  9.04it/s]

 37%|█████████████▍                      | 15896/42525 [30:24<48:18,  9.19it/s]

 37%|█████████████▍                      | 15899/42525 [30:24<48:24,  9.17it/s]

 37%|█████████████▍                      | 15902/42525 [30:25<50:22,  8.81it/s]

 37%|█████████████▍                      | 15905/42525 [30:25<51:24,  8.63it/s]

 37%|█████████████▍                      | 15908/42525 [30:25<47:27,  9.35it/s]

 37%|█████████████▍                      | 15911/42525 [30:26<50:12,  8.84it/s]

 37%|█████████████▍                      | 15913/42525 [30:26<51:18,  8.65it/s]

 37%|█████████████▍                      | 15916/42525 [30:26<52:10,  8.50it/s]

 37%|█████████████▍                      | 15919/42525 [30:27<48:37,  9.12it/s]

 37%|█████████████▍                      | 15922/42525 [30:27<47:20,  9.37it/s]

 37%|█████████████▍                      | 15924/42525 [30:27<48:17,  9.18it/s]

 37%|█████████████▍                      | 15927/42525 [30:27<47:42,  9.29it/s]

 37%|█████████████▍                      | 15928/42525 [30:28<51:36,  8.59it/s]

 37%|█████████████▍                      | 15931/42525 [30:28<53:05,  8.35it/s]

 37%|█████████████▍                      | 15932/42525 [30:28<55:32,  7.98it/s]

 37%|█████████████▍                      | 15936/42525 [30:29<50:23,  8.79it/s]

 37%|█████████████▍                      | 15939/42525 [30:29<54:30,  8.13it/s]

 37%|█████████████▍                      | 15941/42525 [30:29<50:22,  8.79it/s]

 37%|█████████████▍                      | 15944/42525 [30:29<50:23,  8.79it/s]

 38%|█████████████▌                      | 15947/42525 [30:30<49:11,  9.00it/s]

 38%|█████████████▌                      | 15949/42525 [30:30<48:53,  9.06it/s]

 38%|█████████████▌                      | 15951/42525 [30:30<46:30,  9.52it/s]

 38%|█████████████▌                      | 15953/42525 [30:30<46:52,  9.45it/s]

 38%|█████████████▌                      | 15955/42525 [30:31<46:47,  9.47it/s]

 38%|█████████████▌                      | 15958/42525 [30:31<49:24,  8.96it/s]

 38%|█████████████▌                      | 15961/42525 [30:31<54:06,  8.18it/s]

 38%|█████████████▌                      | 15965/42525 [30:32<48:09,  9.19it/s]

 38%|█████████████▌                      | 15968/42525 [30:32<45:50,  9.65it/s]

 38%|█████████████▌                      | 15971/42525 [30:32<45:05,  9.81it/s]

 38%|█████████████▌                      | 15974/42525 [30:33<47:07,  9.39it/s]

 38%|█████████████▌                      | 15975/42525 [30:33<49:26,  8.95it/s]

 38%|█████████████▌                      | 15979/42525 [30:33<46:02,  9.61it/s]

 38%|█████████████▌                      | 15983/42525 [30:34<45:40,  9.68it/s]

 38%|█████████████▌                      | 15986/42525 [30:34<46:36,  9.49it/s]

 38%|█████████████▌                      | 15988/42525 [30:34<54:02,  8.18it/s]

 38%|█████████████▌                      | 15991/42525 [30:35<49:20,  8.96it/s]

 38%|█████████████▌                      | 15992/42525 [30:35<48:37,  9.09it/s]

 38%|█████████████▌                      | 15996/42525 [30:35<47:57,  9.22it/s]

 38%|█████████████▌                      | 16000/42525 [30:35<44:51,  9.86it/s]

 38%|█████████████▌                      | 16002/42525 [30:36<44:00, 10.05it/s]

 38%|█████████████▌                      | 16006/42525 [30:36<43:55, 10.06it/s]

 38%|█████████████▌                      | 16010/42525 [30:37<44:39,  9.90it/s]

 38%|█████████████▌                      | 16012/42525 [30:37<44:06, 10.02it/s]

 38%|█████████████▌                      | 16014/42525 [30:37<44:59,  9.82it/s]

 38%|█████████████▌                      | 16017/42525 [30:37<51:10,  8.63it/s]

 38%|█████████████▌                      | 16019/42525 [30:38<53:52,  8.20it/s]

 38%|█████████████▌                      | 16021/42525 [30:38<51:09,  8.63it/s]

 38%|█████████████▌                      | 16024/42525 [30:38<50:05,  8.82it/s]

 38%|█████████████▌                      | 16025/42525 [30:38<51:49,  8.52it/s]

 38%|█████████████▌                      | 16028/42525 [30:39<53:43,  8.22it/s]

 38%|█████████████▌                      | 16030/42525 [30:39<52:13,  8.45it/s]

 38%|█████████████▌                      | 16032/42525 [30:39<57:06,  7.73it/s]

 38%|█████████████▌                      | 16035/42525 [30:39<48:51,  9.04it/s]

 38%|█████████████▌                      | 16037/42525 [30:40<46:50,  9.42it/s]

 38%|█████████████▌                      | 16039/42525 [30:40<49:35,  8.90it/s]

 38%|█████████████▌                      | 16042/42525 [30:40<52:06,  8.47it/s]

 38%|█████████████▌                      | 16044/42525 [30:40<48:59,  9.01it/s]

 38%|█████████████▌                      | 16047/42525 [30:41<51:02,  8.65it/s]

 38%|█████████████▌                      | 16050/42525 [30:41<47:32,  9.28it/s]

 38%|█████████████▌                      | 16051/42525 [30:41<51:23,  8.59it/s]

 38%|█████████████▌                      | 16053/42525 [30:41<52:28,  8.41it/s]

 38%|█████████████▌                      | 16057/42525 [30:42<50:01,  8.82it/s]

 38%|█████████████▌                      | 16060/42525 [30:42<48:16,  9.14it/s]

 38%|█████████████▌                      | 16062/42525 [30:42<51:49,  8.51it/s]

 38%|█████████████▌                      | 16064/42525 [30:43<50:44,  8.69it/s]

 38%|█████████████▌                      | 16066/42525 [30:43<51:40,  8.53it/s]

 38%|█████████████▌                      | 16069/42525 [30:43<49:43,  8.87it/s]

 38%|█████████████▌                      | 16072/42525 [30:44<46:29,  9.48it/s]

 38%|█████████████▌                      | 16075/42525 [30:44<46:27,  9.49it/s]

 38%|█████████████▌                      | 16078/42525 [30:44<45:12,  9.75it/s]

 38%|█████████████▌                      | 16079/42525 [30:44<49:50,  8.84it/s]

 38%|█████████████▌                      | 16082/42525 [30:45<48:13,  9.14it/s]

 38%|█████████████▌                      | 16085/42525 [30:45<45:30,  9.68it/s]

 38%|█████████████▌                      | 16087/42525 [30:45<45:09,  9.76it/s]

 38%|█████████████▌                      | 16090/42525 [30:45<45:44,  9.63it/s]

 38%|█████████████▌                      | 16092/42525 [30:46<44:42,  9.85it/s]

 38%|█████████████▋                      | 16096/42525 [30:46<45:17,  9.73it/s]

 38%|█████████████▋                      | 16100/42525 [30:47<46:32,  9.46it/s]

 38%|█████████████▋                      | 16103/42525 [30:47<47:55,  9.19it/s]

 38%|█████████████▋                      | 16104/42525 [30:47<47:34,  9.25it/s]

 38%|█████████████▋                      | 16107/42525 [30:47<52:01,  8.46it/s]

 38%|█████████████▋                      | 16109/42525 [30:48<55:29,  7.93it/s]

 38%|█████████████▋                      | 16111/42525 [30:48<52:40,  8.36it/s]

 38%|█████████████▋                      | 16114/42525 [30:48<50:34,  8.70it/s]

 38%|█████████████▋                      | 16117/42525 [30:49<51:05,  8.61it/s]

 38%|█████████████▋                      | 16120/42525 [30:49<48:01,  9.16it/s]

 38%|█████████████▋                      | 16123/42525 [30:49<49:02,  8.97it/s]

 38%|█████████████▋                      | 16125/42525 [30:49<46:35,  9.44it/s]

 38%|█████████████▋                      | 16128/42525 [30:50<49:55,  8.81it/s]

 38%|█████████████▋                      | 16130/42525 [30:50<48:38,  9.04it/s]

 38%|█████████████▋                      | 16132/42525 [30:50<48:23,  9.09it/s]

 38%|█████████████▋                      | 16134/42525 [30:50<53:06,  8.28it/s]

 38%|█████████████▋                      | 16135/42525 [30:51<56:36,  7.77it/s]

 38%|█████████████▋                      | 16139/42525 [30:51<50:23,  8.73it/s]

 38%|█████████████▋                      | 16143/42525 [30:51<46:38,  9.43it/s]

 38%|█████████████▋                      | 16146/42525 [30:52<49:58,  8.80it/s]

 38%|█████████████▋                      | 16149/42525 [30:52<51:15,  8.57it/s]

 38%|█████████████▋                      | 16151/42525 [30:52<54:06,  8.12it/s]

 38%|█████████████▋                      | 16154/42525 [30:53<49:37,  8.86it/s]

 38%|█████████████▋                      | 16157/42525 [30:53<49:01,  8.96it/s]

 38%|█████████████▋                      | 16159/42525 [30:53<52:37,  8.35it/s]

 38%|█████████████▋                      | 16160/42525 [30:53<52:58,  8.30it/s]

 38%|█████████████▋                      | 16163/42525 [30:54<53:12,  8.26it/s]

 38%|█████████████▋                      | 16164/42525 [30:54<53:20,  8.24it/s]

 38%|█████████████▋                      | 16166/42525 [30:54<52:38,  8.35it/s]

 38%|█████████████▋                      | 16170/42525 [30:55<49:03,  8.95it/s]

 38%|█████████████▋                      | 16174/42525 [30:55<45:28,  9.66it/s]

 38%|█████████████▋                      | 16177/42525 [30:55<44:47,  9.80it/s]

 38%|█████████████▋                      | 16180/42525 [30:56<45:56,  9.56it/s]

 38%|█████████████▋                      | 16181/42525 [30:56<45:41,  9.61it/s]

 38%|█████████████▋                      | 16185/42525 [30:56<46:16,  9.49it/s]

 38%|█████████████▋                      | 16187/42525 [30:56<49:03,  8.95it/s]

 38%|█████████████▋                      | 16190/42525 [30:57<46:22,  9.47it/s]

 38%|█████████████▋                      | 16193/42525 [30:57<47:57,  9.15it/s]

 38%|█████████████▋                      | 16196/42525 [30:57<45:35,  9.62it/s]

 38%|█████████████▋                      | 16197/42525 [30:57<49:51,  8.80it/s]

 38%|█████████████▋                      | 16201/42525 [30:58<47:47,  9.18it/s]

 38%|█████████████▋                      | 16204/42525 [30:58<46:55,  9.35it/s]

 38%|█████████████▋                      | 16206/42525 [30:58<47:40,  9.20it/s]

 38%|█████████████▋                      | 16209/42525 [30:59<46:04,  9.52it/s]

 38%|█████████████▋                      | 16210/42525 [30:59<45:50,  9.57it/s]

 38%|█████████████▋                      | 16214/42525 [30:59<46:35,  9.41it/s]

 38%|█████████████▋                      | 16217/42525 [31:00<45:49,  9.57it/s]

 38%|█████████████▋                      | 16221/42525 [31:00<44:47,  9.79it/s]

 38%|█████████████▋                      | 16223/42525 [31:00<45:52,  9.56it/s]

 38%|█████████████▋                      | 16226/42525 [31:01<49:18,  8.89it/s]

 38%|█████████████▋                      | 16229/42525 [31:01<47:33,  9.22it/s]

 38%|█████████████▋                      | 16232/42525 [31:01<45:25,  9.65it/s]

 38%|█████████████▋                      | 16236/42525 [31:02<43:37, 10.04it/s]

 38%|█████████████▋                      | 16238/42525 [31:02<43:14, 10.13it/s]

 38%|█████████████▋                      | 16241/42525 [31:02<50:34,  8.66it/s]

 38%|█████████████▊                      | 16243/42525 [31:02<54:34,  8.03it/s]

 38%|█████████████▊                      | 16245/42525 [31:03<53:41,  8.16it/s]

 38%|█████████████▊                      | 16248/42525 [31:03<50:42,  8.64it/s]

 38%|█████████████▊                      | 16250/42525 [31:03<49:06,  8.92it/s]

 38%|█████████████▊                      | 16253/42525 [31:04<50:35,  8.65it/s]

 38%|█████████████▊                      | 16255/42525 [31:04<48:37,  9.00it/s]

 38%|█████████████▊                      | 16258/42525 [31:04<50:12,  8.72it/s]

 38%|█████████████▊                      | 16259/42525 [31:04<48:40,  8.99it/s]

 38%|█████████████▊                      | 16263/42525 [31:05<47:38,  9.19it/s]

 38%|█████████████▊                      | 16267/42525 [31:05<44:28,  9.84it/s]

 38%|█████████████▊                      | 16271/42525 [31:05<44:11,  9.90it/s]

 38%|█████████████▊                      | 16272/42525 [31:06<44:23,  9.86it/s]

 38%|█████████████▊                      | 16275/42525 [31:06<45:39,  9.58it/s]

 38%|█████████████▊                      | 16277/42525 [31:06<53:33,  8.17it/s]

 38%|█████████████▊                      | 16278/42525 [31:06<51:10,  8.55it/s]

 38%|█████████████▊                      | 16281/42525 [31:07<49:57,  8.76it/s]

 38%|█████████████▊                      | 16285/42525 [31:07<48:09,  9.08it/s]

 38%|█████████████▊                      | 16287/42525 [31:07<51:41,  8.46it/s]

 38%|█████████████▊                      | 16288/42525 [31:07<54:27,  8.03it/s]

 38%|█████████████▊                      | 16291/42525 [31:08<51:55,  8.42it/s]

 38%|█████████████▊                      | 16293/42525 [31:08<57:54,  7.55it/s]

 38%|█████████████▊                      | 16294/42525 [31:08<54:39,  8.00it/s]

 38%|█████████████▊                      | 16297/42525 [31:09<53:04,  8.24it/s]

 38%|█████████████▊                      | 16300/42525 [31:09<51:19,  8.51it/s]

 38%|█████████████▊                      | 16301/42525 [31:09<51:54,  8.42it/s]

 38%|█████████████▊                      | 16305/42525 [31:09<49:01,  8.91it/s]

 38%|█████████████▊                      | 16308/42525 [31:10<47:47,  9.14it/s]

 38%|█████████████▊                      | 16310/42525 [31:10<46:24,  9.41it/s]

 38%|█████████████▊                      | 16312/42525 [31:10<49:03,  8.90it/s]

 38%|█████████████▊                      | 16314/42525 [31:10<47:50,  9.13it/s]

 38%|█████████████▊                      | 16318/42525 [31:11<46:38,  9.37it/s]

 38%|█████████████▊                      | 16321/42525 [31:11<45:26,  9.61it/s]

 38%|█████████████▊                      | 16325/42525 [31:12<43:50,  9.96it/s]

 38%|█████████████▊                      | 16328/42525 [31:12<47:27,  9.20it/s]

 38%|█████████████▊                      | 16331/42525 [31:12<47:49,  9.13it/s]

 38%|█████████████▊                      | 16333/42525 [31:13<54:40,  7.98it/s]

 38%|█████████████▊                      | 16335/42525 [31:13<55:14,  7.90it/s]

 38%|█████████████▊                      | 16338/42525 [31:13<50:30,  8.64it/s]

 38%|█████████████▊                      | 16340/42525 [31:13<48:41,  8.96it/s]

 38%|█████████████▊                      | 16342/42525 [31:14<51:19,  8.50it/s]

 38%|█████████████▊                      | 16345/42525 [31:14<49:25,  8.83it/s]

 38%|█████████████▊                      | 16348/42525 [31:14<51:02,  8.55it/s]

 38%|█████████████▊                      | 16351/42525 [31:15<49:25,  8.83it/s]

 38%|█████████████▊                      | 16353/42525 [31:15<50:59,  8.55it/s]

 38%|█████████████▊                      | 16357/42525 [31:15<47:11,  9.24it/s]

 38%|█████████████▊                      | 16359/42525 [31:15<49:45,  8.76it/s]

 38%|█████████████▊                      | 16361/42525 [31:16<50:30,  8.63it/s]

 38%|█████████████▊                      | 16364/42525 [31:16<48:54,  8.92it/s]

 38%|█████████████▊                      | 16366/42525 [31:16<50:39,  8.61it/s]

 38%|█████████████▊                      | 16368/42525 [31:17<48:53,  8.92it/s]

 38%|█████████████▊                      | 16371/42525 [31:17<48:54,  8.91it/s]

 38%|█████████████▊                      | 16372/42525 [31:17<48:12,  9.04it/s]

 39%|█████████████▊                      | 16375/42525 [31:17<47:36,  9.16it/s]

 39%|█████████████▊                      | 16377/42525 [31:17<48:37,  8.96it/s]

 39%|█████████████▊                      | 16379/42525 [31:18<45:39,  9.54it/s]

 39%|█████████████▊                      | 16382/42525 [31:18<46:38,  9.34it/s]

 39%|█████████████▊                      | 16385/42525 [31:18<45:17,  9.62it/s]

 39%|█████████████▊                      | 16389/42525 [31:19<43:55,  9.92it/s]

 39%|█████████████▉                      | 16392/42525 [31:19<43:33, 10.00it/s]

 39%|█████████████▉                      | 16395/42525 [31:19<47:40,  9.14it/s]

 39%|█████████████▉                      | 16398/42525 [31:20<47:14,  9.22it/s]

 39%|█████████████▉                      | 16400/42525 [31:20<45:56,  9.48it/s]

 39%|█████████████▉                      | 16404/42525 [31:20<46:30,  9.36it/s]

 39%|█████████████▉                      | 16407/42525 [31:21<45:11,  9.63it/s]

 39%|█████████████▉                      | 16410/42525 [31:21<48:05,  9.05it/s]

 39%|█████████████▉                      | 16413/42525 [31:21<48:00,  9.07it/s]

 39%|█████████████▉                      | 16416/42525 [31:22<50:03,  8.69it/s]

 39%|█████████████▉                      | 16419/42525 [31:22<48:00,  9.06it/s]

 39%|█████████████▉                      | 16421/42525 [31:22<54:57,  7.92it/s]

 39%|█████████████▉                      | 16424/42525 [31:23<48:46,  8.92it/s]

 39%|█████████████▉                      | 16427/42525 [31:23<50:57,  8.53it/s]

 39%|█████████████▉                      | 16428/42525 [31:23<54:09,  8.03it/s]

 39%|█████████████▉                      | 16431/42525 [31:23<50:30,  8.61it/s]

 39%|█████████████▉                      | 16434/42525 [31:24<51:46,  8.40it/s]

 39%|█████████████▉                      | 16437/42525 [31:24<48:09,  9.03it/s]

 39%|█████████████▉                      | 16440/42525 [31:24<44:56,  9.67it/s]

 39%|█████████████▉                      | 16443/42525 [31:25<45:19,  9.59it/s]

 39%|█████████████▉                      | 16446/42525 [31:25<44:26,  9.78it/s]

 39%|█████████████▉                      | 16449/42525 [31:25<45:32,  9.54it/s]

 39%|█████████████▉                      | 16452/42525 [31:26<44:26,  9.78it/s]

 39%|█████████████▉                      | 16455/42525 [31:26<50:43,  8.57it/s]

 39%|█████████████▉                      | 16457/42525 [31:26<51:20,  8.46it/s]

 39%|█████████████▉                      | 16459/42525 [31:26<52:54,  8.21it/s]

 39%|█████████████▉                      | 16462/42525 [31:27<47:41,  9.11it/s]

 39%|█████████████▉                      | 16466/42525 [31:27<44:53,  9.68it/s]

 39%|█████████████▉                      | 16468/42525 [31:27<52:26,  8.28it/s]

 39%|█████████████▉                      | 16472/42525 [31:28<47:05,  9.22it/s]

 39%|█████████████▉                      | 16476/42525 [31:28<44:05,  9.85it/s]

 39%|█████████████▉                      | 16478/42525 [31:29<48:03,  9.03it/s]

 39%|█████████████▉                      | 16480/42525 [31:29<51:14,  8.47it/s]

 39%|█████████████▉                      | 16484/42525 [31:29<45:27,  9.55it/s]

 39%|█████████████▉                      | 16488/42525 [31:30<46:18,  9.37it/s]

 39%|█████████████▉                      | 16491/42525 [31:30<44:58,  9.65it/s]

 39%|█████████████▉                      | 16493/42525 [31:30<51:38,  8.40it/s]

 39%|█████████████▉                      | 16495/42525 [31:30<51:55,  8.36it/s]

 39%|█████████████▉                      | 16498/42525 [31:31<46:25,  9.34it/s]

 39%|█████████████▉                      | 16500/42525 [31:31<50:57,  8.51it/s]

 39%|█████████████▉                      | 16502/42525 [31:31<49:23,  8.78it/s]

 39%|█████████████▉                      | 16505/42525 [31:32<50:58,  8.51it/s]

 39%|█████████████▉                      | 16508/42525 [31:32<49:04,  8.84it/s]

 39%|█████████████▉                      | 16510/42525 [31:32<48:06,  9.01it/s]

 39%|█████████████▉                      | 16513/42525 [31:32<47:57,  9.04it/s]

 39%|█████████████▉                      | 16515/42525 [31:33<49:04,  8.83it/s]

 39%|█████████████▉                      | 16517/42525 [31:33<48:09,  9.00it/s]

 39%|█████████████▉                      | 16521/42525 [31:33<45:31,  9.52it/s]

 39%|█████████████▉                      | 16523/42525 [31:34<47:42,  9.08it/s]

 39%|█████████████▉                      | 16525/42525 [31:34<49:47,  8.70it/s]

 39%|█████████████▉                      | 16528/42525 [31:34<49:54,  8.68it/s]

 39%|█████████████▉                      | 16532/42525 [31:35<46:10,  9.38it/s]

 39%|█████████████▉                      | 16536/42525 [31:35<43:59,  9.85it/s]

 39%|██████████████                      | 16539/42525 [31:35<50:05,  8.65it/s]

 39%|██████████████                      | 16541/42525 [31:36<52:23,  8.27it/s]

 39%|██████████████                      | 16543/42525 [31:36<50:24,  8.59it/s]

 39%|██████████████                      | 16545/42525 [31:36<46:43,  9.27it/s]

 39%|██████████████                      | 16549/42525 [31:36<46:40,  9.28it/s]

 39%|██████████████                      | 16553/42525 [31:37<44:14,  9.78it/s]

 39%|██████████████                      | 16556/42525 [31:37<46:02,  9.40it/s]

 39%|██████████████                      | 16557/42525 [31:37<45:52,  9.43it/s]

 39%|██████████████                      | 16559/42525 [31:37<47:51,  9.04it/s]

 39%|██████████████                      | 16562/42525 [31:38<51:18,  8.43it/s]

 39%|██████████████                      | 16564/42525 [31:38<51:24,  8.42it/s]

 39%|██████████████                      | 16567/42525 [31:38<49:16,  8.78it/s]

 39%|██████████████                      | 16570/42525 [31:39<47:34,  9.09it/s]

 39%|██████████████                      | 16572/42525 [31:39<55:00,  7.86it/s]

 39%|██████████████                      | 16574/42525 [31:39<53:30,  8.08it/s]

 39%|██████████████                      | 16575/42525 [31:39<56:28,  7.66it/s]

 39%|██████████████                      | 16579/42525 [31:40<50:16,  8.60it/s]

 39%|██████████████                      | 16580/42525 [31:40<49:13,  8.78it/s]

 39%|██████████████                      | 16582/42525 [31:40<48:11,  8.97it/s]

 39%|██████████████                      | 16586/42525 [31:41<47:13,  9.16it/s]

 39%|██████████████                      | 16588/42525 [31:41<45:26,  9.51it/s]

 39%|██████████████                      | 16592/42525 [31:41<46:13,  9.35it/s]

 39%|██████████████                      | 16593/42525 [31:41<49:23,  8.75it/s]

 39%|██████████████                      | 16596/42525 [31:42<48:48,  8.85it/s]

 39%|██████████████                      | 16598/42525 [31:42<49:14,  8.78it/s]

 39%|██████████████                      | 16601/42525 [31:42<45:10,  9.56it/s]

 39%|██████████████                      | 16603/42525 [31:42<43:46,  9.87it/s]

 39%|██████████████                      | 16607/42525 [31:43<45:24,  9.51it/s]

 39%|██████████████                      | 16610/42525 [31:43<44:53,  9.62it/s]

 39%|██████████████                      | 16613/42525 [31:44<43:37,  9.90it/s]

 39%|██████████████                      | 16617/42525 [31:44<43:02, 10.03it/s]

 39%|██████████████                      | 16621/42525 [31:44<42:12, 10.23it/s]

 39%|██████████████                      | 16623/42525 [31:45<42:07, 10.25it/s]

 39%|██████████████                      | 16627/42525 [31:45<45:24,  9.51it/s]

 39%|██████████████                      | 16630/42525 [31:45<45:05,  9.57it/s]

 39%|██████████████                      | 16631/42525 [31:45<48:48,  8.84it/s]

 39%|██████████████                      | 16633/42525 [31:46<47:32,  9.08it/s]

 39%|██████████████                      | 16636/42525 [31:46<48:19,  8.93it/s]

 39%|██████████████                      | 16639/42525 [31:46<45:55,  9.39it/s]

 39%|██████████████                      | 16643/42525 [31:47<43:26,  9.93it/s]

 39%|██████████████                      | 16645/42525 [31:47<45:36,  9.46it/s]

 39%|██████████████                      | 16648/42525 [31:47<48:47,  8.84it/s]

 39%|██████████████                      | 16651/42525 [31:48<47:12,  9.13it/s]

 39%|██████████████                      | 16652/42525 [31:48<46:34,  9.26it/s]

 39%|██████████████                      | 16656/42525 [31:48<45:03,  9.57it/s]

 39%|██████████████                      | 16658/42525 [31:48<43:47,  9.85it/s]

 39%|██████████████                      | 16662/42525 [31:49<43:03, 10.01it/s]

 39%|██████████████                      | 16664/42525 [31:49<47:33,  9.06it/s]

 39%|██████████████                      | 16667/42525 [31:49<44:54,  9.60it/s]

 39%|██████████████                      | 16670/42525 [31:50<46:42,  9.22it/s]

 39%|██████████████                      | 16672/42525 [31:50<46:22,  9.29it/s]

 39%|██████████████                      | 16673/42525 [31:50<46:52,  9.19it/s]

 39%|██████████████                      | 16677/42525 [31:50<45:59,  9.37it/s]

 39%|██████████████                      | 16680/42525 [31:51<46:34,  9.25it/s]

 39%|██████████████                      | 16682/42525 [31:51<47:10,  9.13it/s]

 39%|██████████████                      | 16685/42525 [31:51<49:31,  8.70it/s]

 39%|██████████████▏                     | 16686/42525 [31:51<48:31,  8.88it/s]

 39%|██████████████▏                     | 16688/42525 [31:52<47:34,  9.05it/s]

 39%|██████████████▏                     | 16692/42525 [31:52<46:55,  9.18it/s]

 39%|██████████████▏                     | 16694/42525 [31:52<47:02,  9.15it/s]

 39%|██████████████▏                     | 16697/42525 [31:53<46:00,  9.36it/s]

 39%|██████████████▏                     | 16699/42525 [31:53<44:28,  9.68it/s]

 39%|██████████████▏                     | 16703/42525 [31:53<43:23,  9.92it/s]

 39%|██████████████▏                     | 16705/42525 [31:53<44:01,  9.78it/s]

 39%|██████████████▏                     | 16708/42525 [31:54<47:25,  9.07it/s]

 39%|██████████████▏                     | 16711/42525 [31:54<49:43,  8.65it/s]

 39%|██████████████▏                     | 16713/42525 [31:54<48:50,  8.81it/s]

 39%|██████████████▏                     | 16715/42525 [31:54<50:47,  8.47it/s]

 39%|██████████████▏                     | 16716/42525 [31:55<48:44,  8.82it/s]

 39%|██████████████▏                     | 16720/42525 [31:55<47:00,  9.15it/s]

 39%|██████████████▏                     | 16721/42525 [31:55<46:25,  9.26it/s]

 39%|██████████████▏                     | 16724/42525 [31:55<45:49,  9.39it/s]

 39%|██████████████▏                     | 16727/42525 [31:56<46:43,  9.20it/s]

 39%|██████████████▏                     | 16729/42525 [31:56<45:54,  9.36it/s]

 39%|██████████████▏                     | 16731/42525 [31:56<45:41,  9.41it/s]

 39%|██████████████▏                     | 16734/42525 [31:56<45:21,  9.48it/s]

 39%|██████████████▏                     | 16736/42525 [31:57<47:33,  9.04it/s]

 39%|██████████████▏                     | 16739/42525 [31:57<45:23,  9.47it/s]

 39%|██████████████▏                     | 16741/42525 [31:57<45:43,  9.40it/s]

 39%|██████████████▏                     | 16744/42525 [31:58<45:21,  9.47it/s]

 39%|██████████████▏                     | 16746/42525 [31:58<49:13,  8.73it/s]

 39%|██████████████▏                     | 16749/42525 [31:58<45:34,  9.42it/s]

 39%|██████████████▏                     | 16751/42525 [31:58<48:26,  8.87it/s]

 39%|██████████████▏                     | 16754/42525 [31:59<53:43,  7.99it/s]

 39%|██████████████▏                     | 16756/42525 [31:59<52:54,  8.12it/s]

 39%|██████████████▏                     | 16759/42525 [31:59<46:08,  9.31it/s]

 39%|██████████████▏                     | 16762/42525 [32:00<46:58,  9.14it/s]

 39%|██████████████▏                     | 16765/42525 [32:00<45:01,  9.53it/s]

 39%|██████████████▏                     | 16769/42525 [32:00<43:26,  9.88it/s]

 39%|██████████████▏                     | 16772/42525 [32:01<47:07,  9.11it/s]

 39%|██████████████▏                     | 16773/42525 [32:01<46:41,  9.19it/s]

 39%|██████████████▏                     | 16776/42525 [32:01<51:46,  8.29it/s]

 39%|██████████████▏                     | 16780/42525 [32:02<46:25,  9.24it/s]

 39%|██████████████▏                     | 16784/42525 [32:02<44:32,  9.63it/s]

 39%|██████████████▏                     | 16786/42525 [32:02<49:02,  8.75it/s]

 39%|██████████████▏                     | 16789/42525 [32:03<46:52,  9.15it/s]

 39%|██████████████▏                     | 16792/42525 [32:03<47:24,  9.05it/s]

 39%|██████████████▏                     | 16793/42525 [32:03<46:54,  9.14it/s]

 39%|██████████████▏                     | 16796/42525 [32:03<48:26,  8.85it/s]

 40%|██████████████▏                     | 16799/42525 [32:04<49:39,  8.63it/s]

 40%|██████████████▏                     | 16802/42525 [32:04<48:28,  8.84it/s]

 40%|██████████████▏                     | 16805/42525 [32:04<46:23,  9.24it/s]

 40%|██████████████▏                     | 16809/42525 [32:05<46:14,  9.27it/s]

 40%|██████████████▏                     | 16811/42525 [32:05<47:21,  9.05it/s]

 40%|██████████████▏                     | 16814/42525 [32:05<44:37,  9.60it/s]

 40%|██████████████▏                     | 16817/42525 [32:06<43:47,  9.79it/s]

 40%|██████████████▏                     | 16819/42525 [32:06<43:56,  9.75it/s]

 40%|██████████████▏                     | 16822/42525 [32:06<46:46,  9.16it/s]

 40%|██████████████▏                     | 16824/42525 [32:06<45:36,  9.39it/s]

 40%|██████████████▏                     | 16827/42525 [32:07<46:04,  9.30it/s]

 40%|██████████████▏                     | 16830/42525 [32:07<44:13,  9.68it/s]

 40%|██████████████▏                     | 16832/42525 [32:07<43:28,  9.85it/s]

 40%|██████████████▎                     | 16836/42525 [32:08<45:05,  9.50it/s]

 40%|██████████████▎                     | 16839/42525 [32:08<44:59,  9.52it/s]

 40%|██████████████▎                     | 16841/42525 [32:08<44:58,  9.52it/s]

 40%|██████████████▎                     | 16844/42525 [32:09<44:10,  9.69it/s]

 40%|██████████████▎                     | 16847/42525 [32:09<43:47,  9.77it/s]

 40%|██████████████▎                     | 16849/42525 [32:09<46:30,  9.20it/s]

 40%|██████████████▎                     | 16851/42525 [32:09<52:05,  8.21it/s]

 40%|██████████████▎                     | 16854/42525 [32:10<49:04,  8.72it/s]

 40%|██████████████▎                     | 16857/42525 [32:10<45:24,  9.42it/s]

 40%|██████████████▎                     | 16860/42525 [32:10<44:26,  9.62it/s]

 40%|██████████████▎                     | 16862/42525 [32:11<50:33,  8.46it/s]

 40%|██████████████▎                     | 16865/42525 [32:11<50:11,  8.52it/s]

 40%|██████████████▎                     | 16867/42525 [32:11<52:23,  8.16it/s]

 40%|██████████████▎                     | 16870/42525 [32:11<46:48,  9.13it/s]

 40%|██████████████▎                     | 16873/42525 [32:12<44:07,  9.69it/s]

 40%|██████████████▎                     | 16875/42525 [32:12<43:07,  9.91it/s]

 40%|██████████████▎                     | 16878/42525 [32:12<45:47,  9.34it/s]

 40%|██████████████▎                     | 16880/42525 [32:13<49:59,  8.55it/s]

 40%|██████████████▎                     | 16883/42525 [32:13<45:59,  9.29it/s]

 40%|██████████████▎                     | 16885/42525 [32:13<49:50,  8.57it/s]

 40%|██████████████▎                     | 16889/42525 [32:13<45:08,  9.47it/s]

 40%|██████████████▎                     | 16891/42525 [32:14<44:33,  9.59it/s]

 40%|██████████████▎                     | 16893/42525 [32:14<49:31,  8.62it/s]

 40%|██████████████▎                     | 16895/42525 [32:14<45:46,  9.33it/s]

 40%|██████████████▎                     | 16897/42525 [32:14<48:19,  8.84it/s]

 40%|██████████████▎                     | 16900/42525 [32:15<49:18,  8.66it/s]

 40%|██████████████▎                     | 16902/42525 [32:15<48:36,  8.78it/s]

 40%|██████████████▎                     | 16904/42525 [32:15<46:56,  9.10it/s]

 40%|██████████████▎                     | 16907/42525 [32:15<44:41,  9.55it/s]

 40%|██████████████▎                     | 16908/42525 [32:16<49:19,  8.66it/s]

 40%|██████████████▎                     | 16912/42525 [32:16<45:44,  9.33it/s]

 40%|██████████████▎                     | 16915/42525 [32:16<45:14,  9.43it/s]

 40%|██████████████▎                     | 16918/42525 [32:17<44:06,  9.68it/s]

 40%|██████████████▎                     | 16921/42525 [32:17<45:14,  9.43it/s]

 40%|██████████████▎                     | 16924/42525 [32:17<44:45,  9.53it/s]

 40%|██████████████▎                     | 16927/42525 [32:18<44:40,  9.55it/s]

 40%|██████████████▎                     | 16928/42525 [32:18<46:22,  9.20it/s]

 40%|██████████████▎                     | 16931/42525 [32:18<47:57,  8.89it/s]

 40%|██████████████▎                     | 16933/42525 [32:18<48:08,  8.86it/s]

 40%|██████████████▎                     | 16936/42525 [32:19<45:31,  9.37it/s]

 40%|██████████████▎                     | 16938/42525 [32:19<47:32,  8.97it/s]

 40%|██████████████▎                     | 16942/42525 [32:19<43:39,  9.77it/s]

 40%|██████████████▎                     | 16945/42525 [32:20<50:49,  8.39it/s]

 40%|██████████████▎                     | 16947/42525 [32:20<51:21,  8.30it/s]

 40%|██████████████▎                     | 16951/42525 [32:20<47:44,  8.93it/s]

 40%|██████████████▎                     | 16952/42525 [32:20<47:51,  8.91it/s]

 40%|██████████████▎                     | 16956/42525 [32:21<45:22,  9.39it/s]

 40%|██████████████▎                     | 16959/42525 [32:21<45:34,  9.35it/s]

 40%|██████████████▎                     | 16961/42525 [32:21<51:17,  8.31it/s]

 40%|██████████████▎                     | 16963/42525 [32:22<48:55,  8.71it/s]

 40%|██████████████▎                     | 16967/42525 [32:22<43:53,  9.71it/s]

 40%|██████████████▎                     | 16969/42525 [32:22<44:07,  9.65it/s]

 40%|██████████████▎                     | 16972/42525 [32:23<45:51,  9.29it/s]

 40%|██████████████▎                     | 16974/42525 [32:23<49:58,  8.52it/s]

 40%|██████████████▎                     | 16977/42525 [32:23<48:10,  8.84it/s]

 40%|██████████████▎                     | 16980/42525 [32:24<47:19,  9.00it/s]

 40%|██████████████▍                     | 16982/42525 [32:24<45:16,  9.40it/s]

 40%|██████████████▍                     | 16985/42525 [32:24<46:11,  9.21it/s]

 40%|██████████████▍                     | 16988/42525 [32:24<45:02,  9.45it/s]

 40%|██████████████▍                     | 16991/42525 [32:25<45:34,  9.34it/s]

 40%|██████████████▍                     | 16994/42525 [32:25<48:13,  8.82it/s]

 40%|██████████████▍                     | 16996/42525 [32:25<47:11,  9.02it/s]

 40%|██████████████▍                     | 16999/42525 [32:26<49:09,  8.66it/s]

 40%|██████████████▍                     | 17001/42525 [32:26<45:52,  9.27it/s]

 40%|██████████████▍                     | 17004/42525 [32:26<48:59,  8.68it/s]

 40%|██████████████▍                     | 17008/42525 [32:27<43:54,  9.69it/s]

 40%|██████████████▍                     | 17011/42525 [32:27<43:55,  9.68it/s]

 40%|██████████████▍                     | 17013/42525 [32:27<42:36,  9.98it/s]

 40%|██████████████▍                     | 17017/42525 [32:27<44:31,  9.55it/s]

 40%|██████████████▍                     | 17021/42525 [32:28<42:42,  9.95it/s]

 40%|██████████████▍                     | 17024/42525 [32:28<45:08,  9.41it/s]

 40%|██████████████▍                     | 17027/42525 [32:29<46:01,  9.23it/s]

 40%|██████████████▍                     | 17029/42525 [32:29<47:13,  9.00it/s]

 40%|██████████████▍                     | 17031/42525 [32:29<45:11,  9.40it/s]

 40%|██████████████▍                     | 17034/42525 [32:29<46:53,  9.06it/s]

 40%|██████████████▍                     | 17036/42525 [32:30<46:02,  9.23it/s]

 40%|██████████████▍                     | 17040/42525 [32:30<43:59,  9.66it/s]

 40%|██████████████▍                     | 17041/42525 [32:30<45:41,  9.30it/s]

 40%|██████████████▍                     | 17044/42525 [32:30<51:08,  8.30it/s]

 40%|██████████████▍                     | 17047/42525 [32:31<50:48,  8.36it/s]

 40%|██████████████▍                     | 17050/42525 [32:31<47:45,  8.89it/s]

 40%|██████████████▍                     | 17052/42525 [32:31<51:32,  8.24it/s]

 40%|██████████████▍                     | 17055/42525 [32:32<48:44,  8.71it/s]

 40%|██████████████▍                     | 17057/42525 [32:32<48:02,  8.84it/s]

 40%|██████████████▍                     | 17059/42525 [32:32<51:00,  8.32it/s]

 40%|██████████████▍                     | 17061/42525 [32:32<48:19,  8.78it/s]

 40%|██████████████▍                     | 17064/42525 [32:33<45:50,  9.26it/s]

 40%|██████████████▍                     | 17066/42525 [32:33<49:55,  8.50it/s]

 40%|██████████████▍                     | 17069/42525 [32:33<46:41,  9.09it/s]

 40%|██████████████▍                     | 17073/42525 [32:34<46:29,  9.12it/s]

 40%|██████████████▍                     | 17074/42525 [32:34<49:44,  8.53it/s]

 40%|██████████████▍                     | 17077/42525 [32:34<51:47,  8.19it/s]

 40%|██████████████▍                     | 17080/42525 [32:34<46:46,  9.07it/s]

 40%|██████████████▍                     | 17082/42525 [32:35<52:02,  8.15it/s]

 40%|██████████████▍                     | 17084/42525 [32:35<53:38,  7.90it/s]

 40%|██████████████▍                     | 17086/42525 [32:35<50:27,  8.40it/s]

 40%|██████████████▍                     | 17087/42525 [32:35<50:27,  8.40it/s]

 40%|██████████████▍                     | 17090/42525 [32:36<50:49,  8.34it/s]

 40%|██████████████▍                     | 17092/42525 [32:36<50:49,  8.34it/s]

 40%|██████████████▍                     | 17095/42525 [32:36<47:52,  8.85it/s]

 40%|██████████████▍                     | 17097/42525 [32:37<49:29,  8.56it/s]

 40%|██████████████▍                     | 17101/42525 [32:37<47:16,  8.96it/s]

 40%|██████████████▍                     | 17105/42525 [32:37<43:35,  9.72it/s]

 40%|██████████████▍                     | 17108/42525 [32:38<49:18,  8.59it/s]

 40%|██████████████▍                     | 17110/42525 [32:38<50:21,  8.41it/s]

 40%|██████████████▍                     | 17113/42525 [32:38<48:45,  8.68it/s]

 40%|██████████████▍                     | 17115/42525 [32:39<51:34,  8.21it/s]

 40%|██████████████▍                     | 17118/42525 [32:39<50:12,  8.43it/s]

 40%|██████████████▍                     | 17120/42525 [32:39<53:29,  7.92it/s]

 40%|██████████████▍                     | 17121/42525 [32:39<55:52,  7.58it/s]

 40%|██████████████▍                     | 17124/42525 [32:40<52:56,  8.00it/s]

 40%|██████████████▍                     | 17127/42525 [32:40<48:33,  8.72it/s]

 40%|██████████████▌                     | 17129/42525 [32:40<53:23,  7.93it/s]

 40%|██████████████▌                     | 17132/42525 [32:41<53:10,  7.96it/s]

 40%|██████████████▌                     | 17133/42525 [32:41<51:55,  8.15it/s]

 40%|██████████████▌                     | 17136/42525 [32:41<47:10,  8.97it/s]

 40%|██████████████▌                     | 17138/42525 [32:41<49:16,  8.59it/s]

 40%|██████████████▌                     | 17141/42525 [32:42<51:34,  8.20it/s]

 40%|██████████████▌                     | 17143/42525 [32:42<47:56,  8.82it/s]

 40%|██████████████▌                     | 17146/42525 [32:42<50:21,  8.40it/s]

 40%|██████████████▌                     | 17148/42525 [32:43<50:50,  8.32it/s]

 40%|██████████████▌                     | 17151/42525 [32:43<47:47,  8.85it/s]

 40%|██████████████▌                     | 17154/42525 [32:43<45:10,  9.36it/s]

 40%|██████████████▌                     | 17157/42525 [32:44<45:09,  9.36it/s]

 40%|██████████████▌                     | 17160/42525 [32:44<47:17,  8.94it/s]

 40%|██████████████▌                     | 17162/42525 [32:44<49:23,  8.56it/s]

 40%|██████████████▌                     | 17165/42525 [32:44<47:44,  8.85it/s]

 40%|██████████████▌                     | 17167/42525 [32:45<47:15,  8.94it/s]

 40%|██████████████▌                     | 17169/42525 [32:45<46:49,  9.02it/s]

 40%|██████████████▌                     | 17172/42525 [32:45<46:31,  9.08it/s]

 40%|██████████████▌                     | 17175/42525 [32:45<44:05,  9.58it/s]

 40%|██████████████▌                     | 17177/42525 [32:46<44:18,  9.53it/s]

 40%|██████████████▌                     | 17178/42525 [32:46<47:47,  8.84it/s]

 40%|██████████████▌                     | 17181/42525 [32:46<49:32,  8.53it/s]

 40%|██████████████▌                     | 17183/42525 [32:46<52:10,  8.10it/s]

 40%|██████████████▌                     | 17187/42525 [32:47<44:43,  9.44it/s]

 40%|██████████████▌                     | 17188/42525 [32:47<47:36,  8.87it/s]

 40%|██████████████▌                     | 17191/42525 [32:47<50:31,  8.36it/s]

 40%|██████████████▌                     | 17193/42525 [32:48<46:53,  9.00it/s]

 40%|██████████████▌                     | 17197/42525 [32:48<45:22,  9.30it/s]

 40%|██████████████▌                     | 17199/42525 [32:48<48:27,  8.71it/s]

 40%|██████████████▌                     | 17202/42525 [32:49<49:11,  8.58it/s]

 40%|██████████████▌                     | 17204/42525 [32:49<47:58,  8.80it/s]

 40%|██████████████▌                     | 17206/42525 [32:49<51:03,  8.26it/s]

 40%|██████████████▌                     | 17208/42525 [32:49<52:28,  8.04it/s]

 40%|██████████████▌                     | 17210/42525 [32:49<48:06,  8.77it/s]

 40%|██████████████▌                     | 17211/42525 [32:50<49:43,  8.48it/s]

 40%|██████████████▌                     | 17215/42525 [32:50<47:03,  8.96it/s]

 40%|██████████████▌                     | 17218/42525 [32:50<44:29,  9.48it/s]

 40%|██████████████▌                     | 17220/42525 [32:51<47:29,  8.88it/s]

 41%|██████████████▌                     | 17224/42525 [32:51<43:11,  9.76it/s]

 41%|██████████████▌                     | 17226/42525 [32:51<43:18,  9.74it/s]

 41%|██████████████▌                     | 17228/42525 [32:51<45:32,  9.26it/s]

 41%|██████████████▌                     | 17231/42525 [32:52<44:25,  9.49it/s]

 41%|██████████████▌                     | 17233/42525 [32:52<48:27,  8.70it/s]

 41%|██████████████▌                     | 17236/42525 [32:52<47:33,  8.86it/s]

 41%|██████████████▌                     | 17239/42525 [32:53<48:54,  8.62it/s]

 41%|██████████████▌                     | 17240/42525 [32:53<47:17,  8.91it/s]

 41%|██████████████▌                     | 17242/42525 [32:53<46:29,  9.06it/s]

 41%|██████████████▌                     | 17246/42525 [32:53<43:57,  9.58it/s]

 41%|██████████████▌                     | 17247/42525 [32:54<47:36,  8.85it/s]

 41%|██████████████▌                     | 17249/42525 [32:54<45:54,  9.18it/s]

 41%|██████████████▌                     | 17251/42525 [32:54<45:43,  9.21it/s]

 41%|██████████████▌                     | 17254/42525 [32:54<47:30,  8.87it/s]

 41%|██████████████▌                     | 17257/42525 [32:55<46:50,  8.99it/s]

 41%|██████████████▌                     | 17259/42525 [32:55<51:40,  8.15it/s]

 41%|██████████████▌                     | 17262/42525 [32:55<48:35,  8.66it/s]

 41%|██████████████▌                     | 17264/42525 [32:55<45:16,  9.30it/s]

 41%|██████████████▌                     | 17266/42525 [32:56<44:49,  9.39it/s]

 41%|██████████████▌                     | 17270/42525 [32:56<43:39,  9.64it/s]

 41%|██████████████▌                     | 17272/42525 [32:56<50:24,  8.35it/s]

 41%|██████████████▌                     | 17274/42525 [32:57<49:14,  8.55it/s]

 41%|██████████████▋                     | 17276/42525 [32:57<47:02,  8.94it/s]

 41%|██████████████▋                     | 17279/42525 [32:57<49:43,  8.46it/s]

 41%|██████████████▋                     | 17281/42525 [32:57<47:34,  8.84it/s]

 41%|██████████████▋                     | 17283/42525 [32:58<46:27,  9.05it/s]

 41%|██████████████▋                     | 17285/42525 [32:58<46:24,  9.07it/s]

 41%|██████████████▋                     | 17287/42525 [32:58<48:20,  8.70it/s]

 41%|██████████████▋                     | 17291/42525 [32:58<44:52,  9.37it/s]

 41%|██████████████▋                     | 17295/42525 [32:59<42:25,  9.91it/s]

 41%|██████████████▋                     | 17299/42525 [32:59<42:54,  9.80it/s]

 41%|██████████████▋                     | 17302/42525 [33:00<43:58,  9.56it/s]

 41%|██████████████▋                     | 17304/42525 [33:00<45:46,  9.18it/s]

 41%|██████████████▋                     | 17307/42525 [33:00<46:34,  9.02it/s]

 41%|██████████████▋                     | 17309/42525 [33:00<46:43,  9.00it/s]

 41%|██████████████▋                     | 17312/42525 [33:01<44:08,  9.52it/s]

 41%|██████████████▋                     | 17313/42525 [33:01<47:57,  8.76it/s]

 41%|██████████████▋                     | 17316/42525 [33:01<45:36,  9.21it/s]

 41%|██████████████▋                     | 17319/42525 [33:01<43:01,  9.76it/s]

 41%|██████████████▋                     | 17322/42525 [33:02<46:31,  9.03it/s]

 41%|██████████████▋                     | 17326/42525 [33:02<45:50,  9.16it/s]

 41%|██████████████▋                     | 17328/42525 [33:02<48:58,  8.57it/s]

 41%|██████████████▋                     | 17330/42525 [33:03<46:59,  8.94it/s]

 41%|██████████████▋                     | 17332/42525 [33:03<44:14,  9.49it/s]

 41%|██████████████▋                     | 17335/42525 [33:03<50:12,  8.36it/s]

 41%|██████████████▋                     | 17339/42525 [33:04<44:33,  9.42it/s]

 41%|██████████████▋                     | 17341/42525 [33:04<49:36,  8.46it/s]

 41%|██████████████▋                     | 17344/42525 [33:04<51:29,  8.15it/s]

 41%|██████████████▋                     | 17347/42525 [33:05<48:26,  8.66it/s]

 41%|██████████████▋                     | 17349/42525 [33:05<46:09,  9.09it/s]

 41%|██████████████▋                     | 17352/42525 [33:05<47:08,  8.90it/s]

 41%|██████████████▋                     | 17356/42525 [33:06<43:02,  9.75it/s]

 41%|██████████████▋                     | 17360/42525 [33:06<42:24,  9.89it/s]

 41%|██████████████▋                     | 17363/42525 [33:06<44:59,  9.32it/s]

 41%|██████████████▋                     | 17366/42525 [33:07<43:04,  9.74it/s]

 41%|██████████████▋                     | 17367/42525 [33:07<47:12,  8.88it/s]

 41%|██████████████▋                     | 17370/42525 [33:07<51:58,  8.07it/s]

 41%|██████████████▋                     | 17373/42525 [33:07<49:17,  8.51it/s]

 41%|██████████████▋                     | 17376/42525 [33:08<47:57,  8.74it/s]

 41%|██████████████▋                     | 17380/42525 [33:08<43:48,  9.57it/s]

 41%|██████████████▋                     | 17382/42525 [33:08<46:20,  9.04it/s]

 41%|██████████████▋                     | 17385/42525 [33:09<47:42,  8.78it/s]

 41%|██████████████▋                     | 17388/42525 [33:09<46:01,  9.10it/s]

 41%|██████████████▋                     | 17392/42525 [33:09<42:52,  9.77it/s]

 41%|██████████████▋                     | 17396/42525 [33:10<41:43, 10.04it/s]

 41%|██████████████▋                     | 17398/42525 [33:10<41:11, 10.17it/s]

 41%|██████████████▋                     | 17400/42525 [33:10<41:34, 10.07it/s]

 41%|██████████████▋                     | 17402/42525 [33:10<42:42,  9.81it/s]

 41%|██████████████▋                     | 17406/42525 [33:11<42:55,  9.75it/s]

 41%|██████████████▋                     | 17408/42525 [33:11<46:35,  8.98it/s]

 41%|██████████████▋                     | 17412/42525 [33:12<43:01,  9.73it/s]

 41%|██████████████▋                     | 17413/42525 [33:12<46:43,  8.96it/s]

 41%|██████████████▋                     | 17416/42525 [33:12<51:13,  8.17it/s]

 41%|██████████████▋                     | 17417/42525 [33:12<49:28,  8.46it/s]

 41%|██████████████▋                     | 17421/42525 [33:13<46:43,  8.95it/s]

 41%|██████████████▋                     | 17422/42525 [33:13<49:48,  8.40it/s]

 41%|██████████████▊                     | 17425/42525 [33:13<50:50,  8.23it/s]

 41%|██████████████▊                     | 17427/42525 [33:13<55:21,  7.56it/s]

 41%|██████████████▊                     | 17430/42525 [33:14<47:45,  8.76it/s]

 41%|██████████████▊                     | 17432/42525 [33:14<49:11,  8.50it/s]

 41%|██████████████▊                     | 17435/42525 [33:14<45:32,  9.18it/s]

 41%|██████████████▊                     | 17439/42525 [33:15<45:22,  9.22it/s]

 41%|██████████████▊                     | 17442/42525 [33:15<47:17,  8.84it/s]

 41%|██████████████▊                     | 17446/42525 [33:16<44:26,  9.41it/s]

 41%|██████████████▊                     | 17449/42525 [33:16<45:15,  9.23it/s]

 41%|██████████████▊                     | 17451/42525 [33:16<45:14,  9.24it/s]

 41%|██████████████▊                     | 17454/42525 [33:16<46:36,  8.96it/s]

 41%|██████████████▊                     | 17456/42525 [33:17<46:58,  8.89it/s]

 41%|██████████████▊                     | 17459/42525 [33:17<47:33,  8.78it/s]

 41%|██████████████▊                     | 17462/42525 [33:17<49:51,  8.38it/s]

 41%|██████████████▊                     | 17465/42525 [33:18<50:15,  8.31it/s]

 41%|██████████████▊                     | 17467/42525 [33:18<55:17,  7.55it/s]

 41%|██████████████▊                     | 17469/42525 [33:18<48:53,  8.54it/s]

 41%|██████████████▊                     | 17472/42525 [33:19<49:00,  8.52it/s]

 41%|██████████████▊                     | 17475/42525 [33:19<45:05,  9.26it/s]

 41%|██████████████▊                     | 17477/42525 [33:19<45:36,  9.15it/s]

 41%|██████████████▊                     | 17479/42525 [33:19<53:00,  7.88it/s]

 41%|██████████████▊                     | 17483/42525 [33:20<44:52,  9.30it/s]

 41%|██████████████▊                     | 17487/42525 [33:20<44:40,  9.34it/s]

 41%|██████████████▊                     | 17490/42525 [33:21<42:42,  9.77it/s]

 41%|██████████████▊                     | 17493/42525 [33:21<44:58,  9.28it/s]

 41%|██████████████▊                     | 17496/42525 [33:21<43:21,  9.62it/s]

 41%|██████████████▊                     | 17498/42525 [33:21<50:49,  8.21it/s]

 41%|██████████████▊                     | 17501/42525 [33:22<50:11,  8.31it/s]

 41%|██████████████▊                     | 17504/42525 [33:22<44:55,  9.28it/s]

 41%|██████████████▊                     | 17506/42525 [33:22<43:29,  9.59it/s]

 41%|██████████████▊                     | 17510/42525 [33:23<42:40,  9.77it/s]

 41%|██████████████▊                     | 17511/42525 [33:23<42:39,  9.77it/s]

 41%|██████████████▊                     | 17513/42525 [33:23<43:10,  9.65it/s]

 41%|██████████████▊                     | 17517/42525 [33:23<42:10,  9.88it/s]

 41%|██████████████▊                     | 17519/42525 [33:24<41:31, 10.04it/s]

 41%|██████████████▊                     | 17521/42525 [33:24<44:32,  9.36it/s]

 41%|██████████████▊                     | 17523/42525 [33:24<44:27,  9.37it/s]

 41%|██████████████▊                     | 17526/42525 [33:24<44:12,  9.42it/s]

 41%|██████████████▊                     | 17528/42525 [33:25<44:50,  9.29it/s]

 41%|██████████████▊                     | 17529/42525 [33:25<48:50,  8.53it/s]

 41%|██████████████▊                     | 17532/42525 [33:25<46:46,  8.91it/s]

 41%|██████████████▊                     | 17534/42525 [33:25<49:45,  8.37it/s]

 41%|██████████████▊                     | 17538/42525 [33:26<43:48,  9.51it/s]

 41%|██████████████▊                     | 17541/42525 [33:26<45:36,  9.13it/s]

 41%|██████████████▊                     | 17544/42525 [33:26<45:35,  9.13it/s]

 41%|██████████████▊                     | 17547/42525 [33:27<46:35,  8.94it/s]

 41%|██████████████▊                     | 17550/42525 [33:27<45:12,  9.21it/s]

 41%|██████████████▊                     | 17553/42525 [33:27<47:33,  8.75it/s]

 41%|██████████████▊                     | 17556/42525 [33:28<44:44,  9.30it/s]

 41%|██████████████▊                     | 17559/42525 [33:28<42:31,  9.79it/s]

 41%|██████████████▊                     | 17562/42525 [33:28<43:25,  9.58it/s]

 41%|██████████████▊                     | 17565/42525 [33:29<42:20,  9.83it/s]

 41%|██████████████▊                     | 17569/42525 [33:29<41:01, 10.14it/s]

 41%|██████████████▊                     | 17571/42525 [33:29<43:13,  9.62it/s]

 41%|██████████████▉                     | 17574/42525 [33:30<47:08,  8.82it/s]

 41%|██████████████▉                     | 17576/42525 [33:30<46:16,  8.98it/s]

 41%|██████████████▉                     | 17579/42525 [33:30<43:09,  9.63it/s]

 41%|██████████████▉                     | 17582/42525 [33:30<41:48,  9.94it/s]

 41%|██████████████▉                     | 17584/42525 [33:31<41:19, 10.06it/s]

 41%|██████████████▉                     | 17588/42525 [33:31<41:50,  9.93it/s]

 41%|██████████████▉                     | 17592/42525 [33:31<40:56, 10.15it/s]

 41%|██████████████▉                     | 17594/42525 [33:32<44:13,  9.40it/s]

 41%|██████████████▉                     | 17597/42525 [33:32<46:48,  8.88it/s]

 41%|██████████████▉                     | 17599/42525 [33:32<45:51,  9.06it/s]

 41%|██████████████▉                     | 17600/42525 [33:32<44:49,  9.27it/s]

 41%|██████████████▉                     | 17604/42525 [33:33<42:09,  9.85it/s]

 41%|██████████████▉                     | 17607/42525 [33:33<45:24,  9.15it/s]

 41%|██████████████▉                     | 17610/42525 [33:33<44:33,  9.32it/s]

 41%|██████████████▉                     | 17614/42525 [33:34<42:01,  9.88it/s]

 41%|██████████████▉                     | 17617/42525 [33:34<45:10,  9.19it/s]

 41%|██████████████▉                     | 17620/42525 [33:34<43:15,  9.60it/s]

 41%|██████████████▉                     | 17623/42525 [33:35<44:51,  9.25it/s]

 41%|██████████████▉                     | 17626/42525 [33:35<46:31,  8.92it/s]

 41%|██████████████▉                     | 17628/42525 [33:35<48:04,  8.63it/s]

 41%|██████████████▉                     | 17630/42525 [33:36<45:26,  9.13it/s]

 41%|██████████████▉                     | 17633/42525 [33:36<44:27,  9.33it/s]

 41%|██████████████▉                     | 17636/42525 [33:36<47:39,  8.70it/s]

 41%|██████████████▉                     | 17639/42525 [33:37<48:33,  8.54it/s]

 41%|██████████████▉                     | 17642/42525 [33:37<46:55,  8.84it/s]

 41%|██████████████▉                     | 17644/42525 [33:37<50:32,  8.20it/s]

 41%|██████████████▉                     | 17646/42525 [33:37<47:04,  8.81it/s]

 42%|██████████████▉                     | 17648/42525 [33:38<46:53,  8.84it/s]

 42%|██████████████▉                     | 17649/42525 [33:38<50:35,  8.19it/s]

 42%|██████████████▉                     | 17653/42525 [33:38<45:45,  9.06it/s]

 42%|██████████████▉                     | 17655/42525 [33:38<45:41,  9.07it/s]

 42%|██████████████▉                     | 17657/42525 [33:39<44:07,  9.39it/s]

 42%|██████████████▉                     | 17660/42525 [33:39<45:40,  9.07it/s]

 42%|██████████████▉                     | 17663/42525 [33:39<47:31,  8.72it/s]

 42%|██████████████▉                     | 17665/42525 [33:39<46:37,  8.89it/s]

 42%|██████████████▉                     | 17669/42525 [33:40<41:56,  9.88it/s]

 42%|██████████████▉                     | 17673/42525 [33:40<41:09, 10.07it/s]

 42%|██████████████▉                     | 17676/42525 [33:41<42:19,  9.79it/s]

 42%|██████████████▉                     | 17678/42525 [33:41<48:41,  8.50it/s]

 42%|██████████████▉                     | 17681/42525 [33:41<46:16,  8.95it/s]

 42%|██████████████▉                     | 17683/42525 [33:41<43:49,  9.45it/s]

 42%|██████████████▉                     | 17686/42525 [33:42<46:06,  8.98it/s]

 42%|██████████████▉                     | 17687/42525 [33:42<49:28,  8.37it/s]

 42%|██████████████▉                     | 17690/42525 [33:42<45:53,  9.02it/s]

 42%|██████████████▉                     | 17694/42525 [33:43<42:26,  9.75it/s]

 42%|██████████████▉                     | 17697/42525 [33:43<41:46,  9.91it/s]

 42%|██████████████▉                     | 17699/42525 [33:43<44:56,  9.21it/s]

 42%|██████████████▉                     | 17701/42525 [33:43<44:52,  9.22it/s]

 42%|██████████████▉                     | 17704/42525 [33:44<47:10,  8.77it/s]

 42%|██████████████▉                     | 17707/42525 [33:44<44:02,  9.39it/s]

 42%|██████████████▉                     | 17711/42525 [33:44<41:48,  9.89it/s]

 42%|██████████████▉                     | 17714/42525 [33:45<45:10,  9.15it/s]

 42%|██████████████▉                     | 17717/42525 [33:45<50:23,  8.20it/s]

 42%|███████████████                     | 17720/42525 [33:45<47:33,  8.69it/s]

 42%|███████████████                     | 17723/42525 [33:46<47:36,  8.68it/s]

 42%|███████████████                     | 17724/42525 [33:46<46:57,  8.80it/s]

 42%|███████████████                     | 17728/42525 [33:46<43:59,  9.39it/s]

 42%|███████████████                     | 17732/42525 [33:47<44:01,  9.39it/s]

 42%|███████████████                     | 17735/42525 [33:47<43:32,  9.49it/s]

 42%|███████████████                     | 17738/42525 [33:47<45:52,  9.00it/s]

 42%|███████████████                     | 17741/42525 [33:48<45:15,  9.13it/s]

 42%|███████████████                     | 17744/42525 [33:48<45:16,  9.12it/s]

 42%|███████████████                     | 17745/42525 [33:48<48:37,  8.49it/s]

 42%|███████████████                     | 17749/42525 [33:49<45:23,  9.10it/s]

 42%|███████████████                     | 17752/42525 [33:49<48:27,  8.52it/s]

 42%|███████████████                     | 17756/42525 [33:49<43:49,  9.42it/s]

 42%|███████████████                     | 17759/42525 [33:50<49:00,  8.42it/s]

 42%|███████████████                     | 17761/42525 [33:50<46:25,  8.89it/s]

 42%|███████████████                     | 17764/42525 [33:50<46:09,  8.94it/s]

 42%|███████████████                     | 17767/42525 [33:51<45:09,  9.14it/s]

 42%|███████████████                     | 17771/42525 [33:51<42:08,  9.79it/s]

 42%|███████████████                     | 17774/42525 [33:51<43:43,  9.43it/s]

 42%|███████████████                     | 17777/42525 [33:52<42:46,  9.64it/s]

 42%|███████████████                     | 17780/42525 [33:52<42:27,  9.71it/s]

 42%|███████████████                     | 17781/42525 [33:52<45:29,  9.06it/s]

 42%|███████████████                     | 17784/42525 [33:52<44:07,  9.34it/s]

 42%|███████████████                     | 17786/42525 [33:53<46:39,  8.84it/s]

 42%|███████████████                     | 17789/42525 [33:53<50:56,  8.09it/s]

 42%|███████████████                     | 17792/42525 [33:53<47:28,  8.68it/s]

 42%|███████████████                     | 17794/42525 [33:54<44:35,  9.24it/s]

 42%|███████████████                     | 17798/42525 [33:54<43:49,  9.40it/s]

 42%|███████████████                     | 17800/42525 [33:54<42:42,  9.65it/s]

 42%|███████████████                     | 17802/42525 [33:54<43:36,  9.45it/s]

 42%|███████████████                     | 17804/42525 [33:55<45:25,  9.07it/s]

 42%|███████████████                     | 17808/42525 [33:55<42:40,  9.65it/s]

 42%|███████████████                     | 17812/42525 [33:55<41:13,  9.99it/s]

 42%|███████████████                     | 17814/42525 [33:56<44:33,  9.24it/s]

 42%|███████████████                     | 17817/42525 [33:56<44:49,  9.19it/s]

 42%|███████████████                     | 17820/42525 [33:56<49:23,  8.34it/s]

 42%|███████████████                     | 17822/42525 [33:57<52:04,  7.91it/s]

 42%|███████████████                     | 17825/42525 [33:57<51:57,  7.92it/s]

 42%|███████████████                     | 17828/42525 [33:57<46:33,  8.84it/s]

 42%|███████████████                     | 17830/42525 [33:58<49:19,  8.35it/s]

 42%|███████████████                     | 17831/42525 [33:58<51:44,  7.95it/s]

 42%|███████████████                     | 17834/42525 [33:58<48:14,  8.53it/s]

 42%|███████████████                     | 17837/42525 [33:58<45:32,  9.03it/s]

 42%|███████████████                     | 17840/42525 [33:59<45:25,  9.06it/s]

 42%|███████████████                     | 17842/42525 [33:59<47:31,  8.66it/s]

 42%|███████████████                     | 17845/42525 [33:59<48:17,  8.52it/s]

 42%|███████████████                     | 17848/42525 [34:00<45:32,  9.03it/s]

 42%|███████████████                     | 17850/42525 [34:00<43:30,  9.45it/s]

 42%|███████████████                     | 17853/42525 [34:00<44:02,  9.34it/s]

 42%|███████████████                     | 17855/42525 [34:00<48:54,  8.41it/s]

 42%|███████████████                     | 17857/42525 [34:01<47:40,  8.62it/s]

 42%|███████████████                     | 17858/42525 [34:01<46:18,  8.88it/s]

 42%|███████████████                     | 17862/42525 [34:01<42:33,  9.66it/s]

 42%|███████████████                     | 17863/42525 [34:01<42:28,  9.68it/s]

 42%|███████████████▏                    | 17867/42525 [34:02<43:36,  9.43it/s]

 42%|███████████████▏                    | 17870/42525 [34:02<45:31,  9.03it/s]

 42%|███████████████▏                    | 17872/42525 [34:02<45:53,  8.95it/s]

 42%|███████████████▏                    | 17874/42525 [34:02<43:12,  9.51it/s]

 42%|███████████████▏                    | 17876/42525 [34:03<42:30,  9.66it/s]

 42%|███████████████▏                    | 17879/42525 [34:03<43:13,  9.50it/s]

 42%|███████████████▏                    | 17883/42525 [34:03<42:19,  9.70it/s]

 42%|███████████████▏                    | 17886/42525 [34:04<41:48,  9.82it/s]

 42%|███████████████▏                    | 17889/42525 [34:04<45:40,  8.99it/s]

 42%|███████████████▏                    | 17892/42525 [34:04<43:06,  9.52it/s]

 42%|███████████████▏                    | 17894/42525 [34:05<46:22,  8.85it/s]

 42%|███████████████▏                    | 17895/42525 [34:05<45:12,  9.08it/s]

 42%|███████████████▏                    | 17898/42525 [34:05<50:19,  8.16it/s]

 42%|███████████████▏                    | 17902/42525 [34:06<44:14,  9.28it/s]

 42%|███████████████▏                    | 17904/42525 [34:06<44:21,  9.25it/s]

 42%|███████████████▏                    | 17906/42525 [34:06<47:09,  8.70it/s]

 42%|███████████████▏                    | 17908/42525 [34:06<43:50,  9.36it/s]

 42%|███████████████▏                    | 17911/42525 [34:07<46:47,  8.77it/s]

 42%|███████████████▏                    | 17913/42525 [34:07<50:43,  8.09it/s]

 42%|███████████████▏                    | 17917/42525 [34:07<43:45,  9.37it/s]

 42%|███████████████▏                    | 17921/42525 [34:08<41:59,  9.77it/s]

 42%|███████████████▏                    | 17924/42525 [34:08<42:59,  9.54it/s]

 42%|███████████████▏                    | 17927/42525 [34:08<42:06,  9.74it/s]

 42%|███████████████▏                    | 17930/42525 [34:09<45:09,  9.08it/s]

 42%|███████████████▏                    | 17933/42525 [34:09<45:07,  9.08it/s]

 42%|███████████████▏                    | 17936/42525 [34:09<46:46,  8.76it/s]

 42%|███████████████▏                    | 17939/42525 [34:10<44:32,  9.20it/s]

 42%|███████████████▏                    | 17941/42525 [34:10<42:44,  9.59it/s]

 42%|███████████████▏                    | 17943/42525 [34:10<42:20,  9.68it/s]

 42%|███████████████▏                    | 17947/42525 [34:10<41:26,  9.88it/s]

 42%|███████████████▏                    | 17950/42525 [34:11<46:22,  8.83it/s]

 42%|███████████████▏                    | 17952/42525 [34:11<44:42,  9.16it/s]

 42%|███████████████▏                    | 17956/42525 [34:11<42:52,  9.55it/s]

 42%|███████████████▏                    | 17960/42525 [34:12<42:01,  9.74it/s]

 42%|███████████████▏                    | 17963/42525 [34:12<41:09,  9.95it/s]

 42%|███████████████▏                    | 17964/42525 [34:12<44:15,  9.25it/s]

 42%|███████████████▏                    | 17967/42525 [34:13<47:37,  8.59it/s]

 42%|███████████████▏                    | 17971/42525 [34:13<42:46,  9.57it/s]

 42%|███████████████▏                    | 17973/42525 [34:13<47:20,  8.64it/s]

 42%|███████████████▏                    | 17974/42525 [34:13<47:34,  8.60it/s]

 42%|███████████████▏                    | 17978/42525 [34:14<45:14,  9.04it/s]

 42%|███████████████▏                    | 17980/42525 [34:14<43:49,  9.33it/s]

 42%|███████████████▏                    | 17984/42525 [34:14<41:05,  9.95it/s]

 42%|███████████████▏                    | 17986/42525 [34:15<40:29, 10.10it/s]

 42%|███████████████▏                    | 17989/42525 [34:15<40:55,  9.99it/s]

 42%|███████████████▏                    | 17992/42525 [34:15<44:04,  9.28it/s]

 42%|███████████████▏                    | 17995/42525 [34:16<44:14,  9.24it/s]

 42%|███████████████▏                    | 17996/42525 [34:16<47:44,  8.56it/s]

 42%|███████████████▏                    | 17998/42525 [34:16<48:41,  8.40it/s]

 42%|███████████████▏                    | 18001/42525 [34:16<49:19,  8.29it/s]

 42%|███████████████▏                    | 18005/42525 [34:17<43:33,  9.38it/s]

 42%|███████████████▏                    | 18007/42525 [34:17<50:10,  8.14it/s]

 42%|███████████████▏                    | 18009/42525 [34:17<54:04,  7.56it/s]

 42%|███████████████▏                    | 18012/42525 [34:18<49:20,  8.28it/s]

 42%|███████████████▎                    | 18016/42525 [34:18<44:06,  9.26it/s]

 42%|███████████████▎                    | 18019/42525 [34:18<43:24,  9.41it/s]

 42%|███████████████▎                    | 18021/42525 [34:19<44:58,  9.08it/s]

 42%|███████████████▎                    | 18024/42525 [34:19<43:19,  9.42it/s]

 42%|███████████████▎                    | 18026/42525 [34:19<44:31,  9.17it/s]

 42%|███████████████▎                    | 18029/42525 [34:19<42:18,  9.65it/s]

 42%|███████████████▎                    | 18032/42525 [34:20<45:12,  9.03it/s]

 42%|███████████████▎                    | 18034/42525 [34:20<46:59,  8.68it/s]

 42%|███████████████▎                    | 18036/42525 [34:20<49:34,  8.23it/s]

 42%|███████████████▎                    | 18037/42525 [34:20<48:13,  8.46it/s]

 42%|███████████████▎                    | 18040/42525 [34:21<50:13,  8.13it/s]

 42%|███████████████▎                    | 18042/42525 [34:21<51:26,  7.93it/s]

 42%|███████████████▎                    | 18046/42525 [34:21<43:48,  9.31it/s]

 42%|███████████████▎                    | 18048/42525 [34:22<50:25,  8.09it/s]

 42%|███████████████▎                    | 18050/42525 [34:22<50:27,  8.08it/s]

 42%|███████████████▎                    | 18052/42525 [34:22<52:45,  7.73it/s]

 42%|███████████████▎                    | 18055/42525 [34:22<47:48,  8.53it/s]

 42%|███████████████▎                    | 18057/42525 [34:23<50:29,  8.08it/s]

 42%|███████████████▎                    | 18059/42525 [34:23<54:07,  7.53it/s]

 42%|███████████████▎                    | 18061/42525 [34:23<53:16,  7.65it/s]

 42%|███████████████▎                    | 18064/42525 [34:24<47:40,  8.55it/s]

 42%|███████████████▎                    | 18065/42525 [34:24<46:08,  8.83it/s]

 42%|███████████████▎                    | 18069/42525 [34:24<42:12,  9.66it/s]

 42%|███████████████▎                    | 18071/42525 [34:24<41:12,  9.89it/s]

 43%|███████████████▎                    | 18074/42525 [34:25<46:25,  8.78it/s]

 43%|███████████████▎                    | 18075/42525 [34:25<47:25,  8.59it/s]

 43%|███████████████▎                    | 18078/42525 [34:25<46:14,  8.81it/s]

 43%|███████████████▎                    | 18081/42525 [34:25<44:26,  9.17it/s]

 43%|███████████████▎                    | 18084/42525 [34:26<44:37,  9.13it/s]

 43%|███████████████▎                    | 18086/42525 [34:26<42:42,  9.54it/s]

 43%|███████████████▎                    | 18089/42525 [34:26<44:29,  9.15it/s]

 43%|███████████████▎                    | 18090/42525 [34:26<43:54,  9.28it/s]

 43%|███████████████▎                    | 18092/42525 [34:27<46:08,  8.82it/s]

 43%|███████████████▎                    | 18096/42525 [34:27<44:51,  9.08it/s]

 43%|███████████████▎                    | 18098/42525 [34:27<47:45,  8.53it/s]

 43%|███████████████▎                    | 18100/42525 [34:28<48:05,  8.46it/s]

 43%|███████████████▎                    | 18103/42525 [34:28<49:17,  8.26it/s]

 43%|███████████████▎                    | 18106/42525 [34:28<48:01,  8.48it/s]

 43%|███████████████▎                    | 18109/42525 [34:29<43:46,  9.29it/s]

 43%|███████████████▎                    | 18113/42525 [34:29<42:41,  9.53it/s]

 43%|███████████████▎                    | 18115/42525 [34:29<43:00,  9.46it/s]

 43%|███████████████▎                    | 18117/42525 [34:29<43:27,  9.36it/s]

 43%|███████████████▎                    | 18121/42525 [34:30<42:04,  9.67it/s]

 43%|███████████████▎                    | 18122/42525 [34:30<42:40,  9.53it/s]

 43%|███████████████▎                    | 18125/42525 [34:30<45:31,  8.93it/s]

 43%|███████████████▎                    | 18127/42525 [34:31<43:05,  9.44it/s]

 43%|███████████████▎                    | 18131/42525 [34:31<43:29,  9.35it/s]

 43%|███████████████▎                    | 18133/42525 [34:31<44:01,  9.23it/s]

 43%|███████████████▎                    | 18135/42525 [34:31<44:28,  9.14it/s]

 43%|███████████████▎                    | 18138/42525 [34:32<42:01,  9.67it/s]

 43%|███████████████▎                    | 18142/42525 [34:32<40:10, 10.12it/s]

 43%|███████████████▎                    | 18146/42525 [34:33<39:27, 10.30it/s]

 43%|███████████████▎                    | 18150/42525 [34:33<39:16, 10.34it/s]

 43%|███████████████▎                    | 18152/42525 [34:33<39:51, 10.19it/s]

 43%|███████████████▎                    | 18155/42525 [34:33<42:35,  9.54it/s]

 43%|███████████████▎                    | 18158/42525 [34:34<43:31,  9.33it/s]

 43%|███████████████▎                    | 18160/42525 [34:34<42:40,  9.51it/s]

 43%|███████████████▍                    | 18164/42525 [34:34<42:35,  9.53it/s]

 43%|███████████████▍                    | 18167/42525 [34:35<43:26,  9.35it/s]

 43%|███████████████▍                    | 18169/42525 [34:35<45:37,  8.90it/s]

 43%|███████████████▍                    | 18173/42525 [34:35<44:44,  9.07it/s]

 43%|███████████████▍                    | 18175/42525 [34:36<47:40,  8.51it/s]

 43%|███████████████▍                    | 18177/42525 [34:36<53:03,  7.65it/s]

 43%|███████████████▍                    | 18180/42525 [34:36<50:24,  8.05it/s]

 43%|███████████████▍                    | 18181/42525 [34:36<48:36,  8.35it/s]

 43%|███████████████▍                    | 18184/42525 [34:37<45:43,  8.87it/s]

 43%|███████████████▍                    | 18187/42525 [34:37<43:56,  9.23it/s]

 43%|███████████████▍                    | 18190/42525 [34:37<44:36,  9.09it/s]

 43%|███████████████▍                    | 18192/42525 [34:38<47:50,  8.48it/s]

 43%|███████████████▍                    | 18193/42525 [34:38<50:52,  7.97it/s]

 43%|███████████████▍                    | 18196/42525 [34:38<51:41,  7.85it/s]

 43%|███████████████▍                    | 18198/42525 [34:38<52:21,  7.74it/s]

 43%|███████████████▍                    | 18201/42525 [34:39<48:39,  8.33it/s]

 43%|███████████████▍                    | 18204/42525 [34:39<45:01,  9.00it/s]

 43%|███████████████▍                    | 18206/42525 [34:39<47:51,  8.47it/s]

 43%|███████████████▍                    | 18208/42525 [34:40<46:42,  8.68it/s]

 43%|███████████████▍                    | 18210/42525 [34:40<47:37,  8.51it/s]

 43%|███████████████▍                    | 18211/42525 [34:40<47:25,  8.55it/s]

 43%|███████████████▍                    | 18215/42525 [34:40<43:16,  9.36it/s]

 43%|███████████████▍                    | 18218/42525 [34:41<44:27,  9.11it/s]

 43%|███████████████▍                    | 18220/42525 [34:41<43:28,  9.32it/s]

 43%|███████████████▍                    | 18223/42525 [34:41<42:12,  9.60it/s]

 43%|███████████████▍                    | 18227/42525 [34:42<40:51,  9.91it/s]

 43%|███████████████▍                    | 18230/42525 [34:42<43:30,  9.31it/s]

 43%|███████████████▍                    | 18232/42525 [34:42<45:48,  8.84it/s]

 43%|███████████████▍                    | 18235/42525 [34:42<43:55,  9.22it/s]

 43%|███████████████▍                    | 18238/42525 [34:43<45:59,  8.80it/s]

 43%|███████████████▍                    | 18240/42525 [34:43<49:51,  8.12it/s]

 43%|███████████████▍                    | 18243/42525 [34:43<46:52,  8.63it/s]

 43%|███████████████▍                    | 18246/42525 [34:44<43:57,  9.21it/s]

 43%|███████████████▍                    | 18248/42525 [34:44<47:46,  8.47it/s]

 43%|███████████████▍                    | 18251/42525 [34:44<46:17,  8.74it/s]

 43%|███████████████▍                    | 18253/42525 [34:45<46:52,  8.63it/s]

 43%|███████████████▍                    | 18255/42525 [34:45<49:22,  8.19it/s]

 43%|███████████████▍                    | 18257/42525 [34:45<50:19,  8.04it/s]

 43%|███████████████▍                    | 18260/42525 [34:45<45:02,  8.98it/s]

 43%|███████████████▍                    | 18261/42525 [34:45<44:22,  9.11it/s]

 43%|███████████████▍                    | 18265/42525 [34:46<41:42,  9.69it/s]

 43%|███████████████▍                    | 18268/42525 [34:46<42:10,  9.59it/s]

 43%|███████████████▍                    | 18271/42525 [34:46<41:58,  9.63it/s]

 43%|███████████████▍                    | 18272/42525 [34:47<42:59,  9.40it/s]

 43%|███████████████▍                    | 18275/42525 [34:47<43:19,  9.33it/s]

 43%|███████████████▍                    | 18278/42525 [34:47<41:23,  9.76it/s]

 43%|███████████████▍                    | 18280/42525 [34:47<45:03,  8.97it/s]

 43%|███████████████▍                    | 18282/42525 [34:48<47:05,  8.58it/s]

 43%|███████████████▍                    | 18286/42525 [34:48<42:50,  9.43it/s]

 43%|███████████████▍                    | 18288/42525 [34:48<42:49,  9.43it/s]

 43%|███████████████▍                    | 18290/42525 [34:49<41:27,  9.74it/s]

 43%|███████████████▍                    | 18293/42525 [34:49<43:41,  9.24it/s]

 43%|███████████████▍                    | 18295/42525 [34:49<50:41,  7.97it/s]

 43%|███████████████▍                    | 18297/42525 [34:49<48:19,  8.36it/s]

 43%|███████████████▍                    | 18299/42525 [34:50<45:38,  8.85it/s]

 43%|███████████████▍                    | 18301/42525 [34:50<49:00,  8.24it/s]

 43%|███████████████▍                    | 18304/42525 [34:50<43:55,  9.19it/s]

 43%|███████████████▍                    | 18306/42525 [34:50<42:11,  9.57it/s]

 43%|███████████████▌                    | 18310/42525 [34:51<41:27,  9.73it/s]

 43%|███████████████▌                    | 18313/42525 [34:51<41:08,  9.81it/s]

 43%|███████████████▌                    | 18315/42525 [34:51<40:37,  9.93it/s]

 43%|███████████████▌                    | 18317/42525 [34:52<42:29,  9.50it/s]

 43%|███████████████▌                    | 18320/42525 [34:52<45:33,  8.85it/s]

 43%|███████████████▌                    | 18323/42525 [34:52<44:38,  9.04it/s]

 43%|███████████████▌                    | 18325/42525 [34:52<44:09,  9.13it/s]

 43%|███████████████▌                    | 18327/42525 [34:53<47:44,  8.45it/s]

 43%|███████████████▌                    | 18329/42525 [34:53<48:47,  8.27it/s]

 43%|███████████████▌                    | 18332/42525 [34:53<43:02,  9.37it/s]

 43%|███████████████▌                    | 18334/42525 [34:53<44:22,  9.09it/s]

 43%|███████████████▌                    | 18335/42525 [34:54<48:27,  8.32it/s]

 43%|███████████████▌                    | 18339/42525 [34:54<44:53,  8.98it/s]

 43%|███████████████▌                    | 18341/42525 [34:54<42:44,  9.43it/s]

 43%|███████████████▌                    | 18344/42525 [34:54<42:17,  9.53it/s]

 43%|███████████████▌                    | 18347/42525 [34:55<40:53,  9.85it/s]

 43%|███████████████▌                    | 18350/42525 [34:55<40:29,  9.95it/s]

 43%|███████████████▌                    | 18354/42525 [34:55<39:49, 10.11it/s]

 43%|███████████████▌                    | 18357/42525 [34:56<41:22,  9.73it/s]

 43%|███████████████▌                    | 18360/42525 [34:56<42:31,  9.47it/s]

 43%|███████████████▌                    | 18362/42525 [34:56<45:28,  8.85it/s]

 43%|███████████████▌                    | 18364/42525 [34:57<45:32,  8.84it/s]

 43%|███████████████▌                    | 18367/42525 [34:57<42:44,  9.42it/s]

 43%|███████████████▌                    | 18370/42525 [34:57<42:38,  9.44it/s]

 43%|███████████████▌                    | 18372/42525 [34:57<44:04,  9.13it/s]

 43%|███████████████▌                    | 18375/42525 [34:58<41:39,  9.66it/s]

 43%|███████████████▌                    | 18378/42525 [34:58<45:00,  8.94it/s]

 43%|███████████████▌                    | 18381/42525 [34:58<42:10,  9.54it/s]

 43%|███████████████▌                    | 18385/42525 [34:59<40:59,  9.81it/s]

 43%|███████████████▌                    | 18386/42525 [34:59<41:03,  9.80it/s]

 43%|███████████████▌                    | 18390/42525 [34:59<41:28,  9.70it/s]

 43%|███████████████▌                    | 18392/42525 [35:00<41:32,  9.68it/s]

 43%|███████████████▌                    | 18395/42525 [35:00<44:56,  8.95it/s]

 43%|███████████████▌                    | 18399/42525 [35:00<42:02,  9.56it/s]

 43%|███████████████▌                    | 18400/42525 [35:00<42:06,  9.55it/s]

 43%|███████████████▌                    | 18404/42525 [35:01<41:43,  9.63it/s]

 43%|███████████████▌                    | 18407/42525 [35:01<42:37,  9.43it/s]

 43%|███████████████▌                    | 18408/42525 [35:01<43:43,  9.19it/s]

 43%|███████████████▌                    | 18412/42525 [35:02<43:34,  9.22it/s]

 43%|███████████████▌                    | 18414/42525 [35:02<45:26,  8.84it/s]

 43%|███████████████▌                    | 18416/42525 [35:02<45:10,  8.90it/s]

 43%|███████████████▌                    | 18418/42525 [35:02<45:25,  8.85it/s]

 43%|███████████████▌                    | 18422/42525 [35:03<44:21,  9.06it/s]

 43%|███████████████▌                    | 18425/42525 [35:03<43:30,  9.23it/s]

 43%|███████████████▌                    | 18428/42525 [35:03<42:43,  9.40it/s]

 43%|███████████████▌                    | 18432/42525 [35:04<40:20,  9.95it/s]

 43%|███████████████▌                    | 18436/42525 [35:04<40:15,  9.97it/s]

 43%|███████████████▌                    | 18437/42525 [35:04<40:36,  9.89it/s]

 43%|███████████████▌                    | 18441/42525 [35:05<41:01,  9.78it/s]

 43%|███████████████▌                    | 18445/42525 [35:05<40:11,  9.99it/s]

 43%|███████████████▌                    | 18446/42525 [35:05<43:16,  9.27it/s]

 43%|███████████████▌                    | 18448/42525 [35:05<42:37,  9.41it/s]

 43%|███████████████▌                    | 18451/42525 [35:06<41:47,  9.60it/s]

 43%|███████████████▌                    | 18454/42525 [35:06<41:06,  9.76it/s]

 43%|███████████████▌                    | 18456/42525 [35:06<42:14,  9.50it/s]

 43%|███████████████▋                    | 18458/42525 [35:07<44:24,  9.03it/s]

 43%|███████████████▋                    | 18461/42525 [35:07<43:24,  9.24it/s]

 43%|███████████████▋                    | 18464/42525 [35:07<44:04,  9.10it/s]

 43%|███████████████▋                    | 18468/42525 [35:08<41:00,  9.78it/s]

 43%|███████████████▋                    | 18470/42525 [35:08<41:21,  9.69it/s]

 43%|███████████████▋                    | 18472/42525 [35:08<44:23,  9.03it/s]

 43%|███████████████▋                    | 18475/42525 [35:08<44:06,  9.09it/s]

 43%|███████████████▋                    | 18478/42525 [35:09<42:18,  9.47it/s]

 43%|███████████████▋                    | 18480/42525 [35:09<40:52,  9.80it/s]

 43%|███████████████▋                    | 18482/42525 [35:09<43:43,  9.16it/s]

 43%|███████████████▋                    | 18484/42525 [35:09<45:29,  8.81it/s]

 43%|███████████████▋                    | 18486/42525 [35:10<44:05,  9.09it/s]

 43%|███████████████▋                    | 18489/42525 [35:10<48:37,  8.24it/s]

 43%|███████████████▋                    | 18492/42525 [35:10<46:04,  8.69it/s]

 43%|███████████████▋                    | 18493/42525 [35:10<45:41,  8.77it/s]

 43%|███████████████▋                    | 18497/42525 [35:11<43:46,  9.15it/s]

 44%|███████████████▋                    | 18500/42525 [35:11<45:32,  8.79it/s]

 44%|███████████████▋                    | 18501/42525 [35:11<44:29,  9.00it/s]

 44%|███████████████▋                    | 18505/42525 [35:12<43:51,  9.13it/s]

 44%|███████████████▋                    | 18506/42525 [35:12<46:41,  8.57it/s]

 44%|███████████████▋                    | 18508/42525 [35:12<44:53,  8.92it/s]

 44%|███████████████▋                    | 18511/42525 [35:12<46:15,  8.65it/s]

 44%|███████████████▋                    | 18512/42525 [35:13<49:23,  8.10it/s]

 44%|███████████████▋                    | 18516/42525 [35:13<44:49,  8.93it/s]

 44%|███████████████▋                    | 18519/42525 [35:13<47:18,  8.46it/s]

 44%|███████████████▋                    | 18523/42525 [35:14<45:10,  8.86it/s]

 44%|███████████████▋                    | 18526/42525 [35:14<43:30,  9.19it/s]

 44%|███████████████▋                    | 18528/42525 [35:14<47:32,  8.41it/s]

 44%|███████████████▋                    | 18529/42525 [35:15<46:27,  8.61it/s]

 44%|███████████████▋                    | 18531/42525 [35:15<44:28,  8.99it/s]

 44%|███████████████▋                    | 18535/42525 [35:15<41:41,  9.59it/s]

 44%|███████████████▋                    | 18537/42525 [35:15<45:09,  8.85it/s]

 44%|███████████████▋                    | 18540/42525 [35:16<46:17,  8.64it/s]

 44%|███████████████▋                    | 18544/42525 [35:16<41:38,  9.60it/s]

 44%|███████████████▋                    | 18548/42525 [35:17<40:16,  9.92it/s]

 44%|███████████████▋                    | 18550/42525 [35:17<41:51,  9.55it/s]

 44%|███████████████▋                    | 18552/42525 [35:17<41:49,  9.55it/s]

 44%|███████████████▋                    | 18554/42525 [35:17<41:50,  9.55it/s]

 44%|███████████████▋                    | 18557/42525 [35:18<43:18,  9.23it/s]

 44%|███████████████▋                    | 18559/42525 [35:18<42:56,  9.30it/s]

 44%|███████████████▋                    | 18562/42525 [35:18<44:35,  8.95it/s]

 44%|███████████████▋                    | 18564/42525 [35:18<48:16,  8.27it/s]

 44%|███████████████▋                    | 18566/42525 [35:19<52:56,  7.54it/s]

 44%|███████████████▋                    | 18569/42525 [35:19<46:52,  8.52it/s]

 44%|███████████████▋                    | 18571/42525 [35:19<50:07,  7.97it/s]

 44%|███████████████▋                    | 18573/42525 [35:19<51:19,  7.78it/s]

 44%|███████████████▋                    | 18575/42525 [35:20<45:48,  8.71it/s]

 44%|███████████████▋                    | 18577/42525 [35:20<43:44,  9.12it/s]

 44%|███████████████▋                    | 18581/42525 [35:20<41:16,  9.67it/s]

 44%|███████████████▋                    | 18583/42525 [35:21<43:37,  9.15it/s]

 44%|███████████████▋                    | 18586/42525 [35:21<43:24,  9.19it/s]

 44%|███████████████▋                    | 18589/42525 [35:21<43:26,  9.18it/s]

 44%|███████████████▋                    | 18592/42525 [35:21<43:46,  9.11it/s]

 44%|███████████████▋                    | 18595/42525 [35:22<42:39,  9.35it/s]

 44%|███████████████▋                    | 18597/42525 [35:22<44:33,  8.95it/s]

 44%|███████████████▋                    | 18600/42525 [35:22<42:53,  9.30it/s]

 44%|███████████████▋                    | 18601/42525 [35:22<45:48,  8.70it/s]

 44%|███████████████▋                    | 18604/42525 [35:23<44:24,  8.98it/s]

 44%|███████████████▊                    | 18607/42525 [35:23<46:41,  8.54it/s]

 44%|███████████████▊                    | 18610/42525 [35:24<45:15,  8.81it/s]

 44%|███████████████▊                    | 18613/42525 [35:24<44:19,  8.99it/s]

 44%|███████████████▊                    | 18617/42525 [35:24<43:32,  9.15it/s]

 44%|███████████████▊                    | 18620/42525 [35:25<45:44,  8.71it/s]

 44%|███████████████▊                    | 18623/42525 [35:25<44:00,  9.05it/s]

 44%|███████████████▊                    | 18625/42525 [35:25<47:07,  8.45it/s]

 44%|███████████████▊                    | 18628/42525 [35:26<44:35,  8.93it/s]

 44%|███████████████▊                    | 18630/42525 [35:26<43:41,  9.12it/s]

 44%|███████████████▊                    | 18633/42525 [35:26<47:37,  8.36it/s]

 44%|███████████████▊                    | 18635/42525 [35:26<48:32,  8.20it/s]

 44%|███████████████▊                    | 18639/42525 [35:27<44:45,  8.90it/s]

 44%|███████████████▊                    | 18641/42525 [35:27<42:54,  9.28it/s]

 44%|███████████████▊                    | 18642/42525 [35:27<42:42,  9.32it/s]

 44%|███████████████▊                    | 18646/42525 [35:28<41:29,  9.59it/s]

 44%|███████████████▊                    | 18649/42525 [35:28<44:14,  8.99it/s]

 44%|███████████████▊                    | 18652/42525 [35:28<44:01,  9.04it/s]

 44%|███████████████▊                    | 18654/42525 [35:28<47:35,  8.36it/s]

 44%|███████████████▊                    | 18655/42525 [35:29<46:14,  8.60it/s]

 44%|███████████████▊                    | 18659/42525 [35:29<42:10,  9.43it/s]

 44%|███████████████▊                    | 18661/42525 [35:29<41:44,  9.53it/s]

 44%|███████████████▊                    | 18662/42525 [35:29<44:36,  8.92it/s]

 44%|███████████████▊                    | 18665/42525 [35:30<44:36,  8.92it/s]

 44%|███████████████▊                    | 18668/42525 [35:30<45:17,  8.78it/s]

 44%|███████████████▊                    | 18670/42525 [35:30<43:03,  9.23it/s]

 44%|███████████████▊                    | 18672/42525 [35:30<44:41,  8.89it/s]

 44%|███████████████▊                    | 18676/42525 [35:31<43:57,  9.04it/s]

 44%|███████████████▊                    | 18679/42525 [35:31<42:47,  9.29it/s]

 44%|███████████████▊                    | 18682/42525 [35:32<45:22,  8.76it/s]

 44%|███████████████▊                    | 18685/42525 [35:32<41:59,  9.46it/s]

 44%|███████████████▊                    | 18689/42525 [35:32<40:46,  9.74it/s]

 44%|███████████████▊                    | 18692/42525 [35:33<40:58,  9.69it/s]

 44%|███████████████▊                    | 18694/42525 [35:33<45:02,  8.82it/s]

 44%|███████████████▊                    | 18697/42525 [35:33<42:30,  9.34it/s]

 44%|███████████████▊                    | 18700/42525 [35:33<40:53,  9.71it/s]

 44%|███████████████▊                    | 18703/42525 [35:34<43:34,  9.11it/s]

 44%|███████████████▊                    | 18706/42525 [35:34<41:21,  9.60it/s]

 44%|███████████████▊                    | 18708/42525 [35:34<48:40,  8.15it/s]

 44%|███████████████▊                    | 18711/42525 [35:35<46:24,  8.55it/s]

 44%|███████████████▊                    | 18715/42525 [35:35<41:29,  9.57it/s]

 44%|███████████████▊                    | 18718/42525 [35:35<40:24,  9.82it/s]

 44%|███████████████▊                    | 18721/42525 [35:36<40:00,  9.92it/s]

 44%|███████████████▊                    | 18725/42525 [35:36<41:38,  9.53it/s]

 44%|███████████████▊                    | 18728/42525 [35:37<41:55,  9.46it/s]

 44%|███████████████▊                    | 18730/42525 [35:37<41:27,  9.56it/s]

 44%|███████████████▊                    | 18733/42525 [35:37<45:27,  8.72it/s]

 44%|███████████████▊                    | 18736/42525 [35:37<46:09,  8.59it/s]

 44%|███████████████▊                    | 18740/42525 [35:38<43:36,  9.09it/s]

 44%|███████████████▊                    | 18743/42525 [35:38<41:24,  9.57it/s]

 44%|███████████████▊                    | 18747/42525 [35:39<39:46,  9.96it/s]

 44%|███████████████▊                    | 18749/42525 [35:39<39:19, 10.08it/s]

 44%|███████████████▊                    | 18752/42525 [35:39<45:11,  8.77it/s]

 44%|███████████████▉                    | 18754/42525 [35:39<42:46,  9.26it/s]

 44%|███████████████▉                    | 18757/42525 [35:40<43:11,  9.17it/s]

 44%|███████████████▉                    | 18760/42525 [35:40<45:02,  8.79it/s]

 44%|███████████████▉                    | 18763/42525 [35:40<42:22,  9.35it/s]

 44%|███████████████▉                    | 18767/42525 [35:41<39:48,  9.95it/s]

 44%|███████████████▉                    | 18770/42525 [35:41<40:50,  9.69it/s]

 44%|███████████████▉                    | 18772/42525 [35:41<40:02,  9.89it/s]

 44%|███████████████▉                    | 18775/42525 [35:41<40:05,  9.87it/s]

 44%|███████████████▉                    | 18778/42525 [35:42<41:44,  9.48it/s]

 44%|███████████████▉                    | 18781/42525 [35:42<41:19,  9.58it/s]

 44%|███████████████▉                    | 18784/42525 [35:42<42:24,  9.33it/s]

 44%|███████████████▉                    | 18788/42525 [35:43<39:47,  9.94it/s]

 44%|███████████████▉                    | 18789/42525 [35:43<40:18,  9.81it/s]

 44%|███████████████▉                    | 18791/42525 [35:43<40:41,  9.72it/s]

 44%|███████████████▉                    | 18794/42525 [35:44<43:06,  9.18it/s]

 44%|███████████████▉                    | 18795/42525 [35:44<44:29,  8.89it/s]

 44%|███████████████▉                    | 18798/42525 [35:44<47:17,  8.36it/s]

 44%|███████████████▉                    | 18802/42525 [35:44<43:31,  9.08it/s]

 44%|███████████████▉                    | 18805/42525 [35:45<42:28,  9.31it/s]

 44%|███████████████▉                    | 18806/42525 [35:45<43:34,  9.07it/s]

 44%|███████████████▉                    | 18808/42525 [35:45<43:45,  9.03it/s]

 44%|███████████████▉                    | 18811/42525 [35:45<45:57,  8.60it/s]

 44%|███████████████▉                    | 18813/42525 [35:46<43:03,  9.18it/s]

 44%|███████████████▉                    | 18816/42525 [35:46<43:25,  9.10it/s]

 44%|███████████████▉                    | 18818/42525 [35:46<49:41,  7.95it/s]

 44%|███████████████▉                    | 18820/42525 [35:47<52:36,  7.51it/s]

 44%|███████████████▉                    | 18823/42525 [35:47<45:59,  8.59it/s]

 44%|███████████████▉                    | 18826/42525 [35:47<42:44,  9.24it/s]

 44%|███████████████▉                    | 18829/42525 [35:47<40:30,  9.75it/s]

 44%|███████████████▉                    | 18832/42525 [35:48<43:39,  9.04it/s]

 44%|███████████████▉                    | 18833/42525 [35:48<43:22,  9.10it/s]

 44%|███████████████▉                    | 18836/42525 [35:48<43:21,  9.10it/s]

 44%|███████████████▉                    | 18838/42525 [35:48<44:10,  8.94it/s]

 44%|███████████████▉                    | 18840/42525 [35:49<48:14,  8.18it/s]

 44%|███████████████▉                    | 18843/42525 [35:49<42:33,  9.27it/s]

 44%|███████████████▉                    | 18845/42525 [35:49<47:37,  8.29it/s]

 44%|███████████████▉                    | 18846/42525 [35:49<48:40,  8.11it/s]

 44%|███████████████▉                    | 18849/42525 [35:50<49:32,  7.97it/s]

 44%|███████████████▉                    | 18851/42525 [35:50<49:58,  7.90it/s]

 44%|███████████████▉                    | 18854/42525 [35:50<48:02,  8.21it/s]

 44%|███████████████▉                    | 18857/42525 [35:51<48:08,  8.19it/s]

 44%|███████████████▉                    | 18860/42525 [35:51<46:23,  8.50it/s]

 44%|███████████████▉                    | 18861/42525 [35:51<49:17,  8.00it/s]

 44%|███████████████▉                    | 18864/42525 [35:52<47:54,  8.23it/s]

 44%|███████████████▉                    | 18867/42525 [35:52<46:31,  8.47it/s]

 44%|███████████████▉                    | 18869/42525 [35:52<45:51,  8.60it/s]

 44%|███████████████▉                    | 18870/42525 [35:52<45:26,  8.67it/s]

 44%|███████████████▉                    | 18874/42525 [35:53<42:17,  9.32it/s]

 44%|███████████████▉                    | 18877/42525 [35:53<44:48,  8.80it/s]

 44%|███████████████▉                    | 18879/42525 [35:53<45:48,  8.60it/s]

 44%|███████████████▉                    | 18881/42525 [35:54<48:35,  8.11it/s]

 44%|███████████████▉                    | 18882/42525 [35:54<48:32,  8.12it/s]

 44%|███████████████▉                    | 18885/42525 [35:54<46:40,  8.44it/s]

 44%|███████████████▉                    | 18887/42525 [35:54<47:13,  8.34it/s]

 44%|███████████████▉                    | 18889/42525 [35:54<43:32,  9.05it/s]

 44%|███████████████▉                    | 18893/42525 [35:55<42:19,  9.31it/s]

 44%|███████████████▉                    | 18895/42525 [35:55<44:29,  8.85it/s]

 44%|███████████████▉                    | 18897/42525 [35:55<43:49,  8.99it/s]

 44%|███████████████▉                    | 18899/42525 [35:56<47:32,  8.28it/s]

 44%|████████████████                    | 18902/42525 [35:56<42:08,  9.34it/s]

 44%|████████████████                    | 18904/42525 [35:56<43:07,  9.13it/s]

 44%|████████████████                    | 18907/42525 [35:56<40:50,  9.64it/s]

 44%|████████████████                    | 18908/42525 [35:57<40:58,  9.61it/s]

 44%|████████████████                    | 18911/42525 [35:57<45:24,  8.67it/s]

 44%|████████████████                    | 18913/42525 [35:57<48:16,  8.15it/s]

 44%|████████████████                    | 18916/42525 [35:58<45:34,  8.64it/s]

 44%|████████████████                    | 18919/42525 [35:58<44:17,  8.88it/s]

 44%|████████████████                    | 18921/42525 [35:58<42:00,  9.36it/s]

 44%|████████████████                    | 18923/42525 [35:58<41:42,  9.43it/s]

 45%|████████████████                    | 18926/42525 [35:59<46:57,  8.38it/s]

 45%|████████████████                    | 18929/42525 [35:59<42:42,  9.21it/s]

 45%|████████████████                    | 18930/42525 [35:59<42:21,  9.29it/s]

 45%|████████████████                    | 18933/42525 [35:59<44:45,  8.79it/s]

 45%|████████████████                    | 18935/42525 [36:00<45:55,  8.56it/s]

 45%|████████████████                    | 18937/42525 [36:00<48:07,  8.17it/s]

 45%|████████████████                    | 18940/42525 [36:00<43:17,  9.08it/s]

 45%|████████████████                    | 18942/42525 [36:00<47:37,  8.25it/s]

 45%|████████████████                    | 18944/42525 [36:01<46:02,  8.54it/s]

 45%|████████████████                    | 18945/42525 [36:01<44:35,  8.81it/s]

 45%|████████████████                    | 18949/42525 [36:01<40:54,  9.60it/s]

 45%|████████████████                    | 18952/42525 [36:02<42:34,  9.23it/s]

 45%|████████████████                    | 18953/42525 [36:02<42:20,  9.28it/s]

 45%|████████████████                    | 18957/42525 [36:02<42:16,  9.29it/s]

 45%|████████████████                    | 18959/42525 [36:02<43:17,  9.07it/s]

 45%|████████████████                    | 18961/42525 [36:03<41:06,  9.55it/s]

 45%|████████████████                    | 18963/42525 [36:03<40:38,  9.66it/s]

 45%|████████████████                    | 18966/42525 [36:03<45:18,  8.67it/s]

 45%|████████████████                    | 18968/42525 [36:03<47:28,  8.27it/s]

 45%|████████████████                    | 18971/42525 [36:04<43:14,  9.08it/s]

 45%|████████████████                    | 18975/42525 [36:04<39:40,  9.89it/s]

 45%|████████████████                    | 18978/42525 [36:04<41:05,  9.55it/s]

 45%|████████████████                    | 18981/42525 [36:05<46:38,  8.41it/s]

 45%|████████████████                    | 18983/42525 [36:05<44:04,  8.90it/s]

 45%|████████████████                    | 18986/42525 [36:05<42:06,  9.32it/s]

 45%|████████████████                    | 18987/42525 [36:05<45:36,  8.60it/s]

 45%|████████████████                    | 18990/42525 [36:06<42:55,  9.14it/s]

 45%|████████████████                    | 18993/42525 [36:06<40:53,  9.59it/s]

 45%|████████████████                    | 18996/42525 [36:06<44:51,  8.74it/s]

 45%|████████████████                    | 18999/42525 [36:07<40:55,  9.58it/s]

 45%|████████████████                    | 19003/42525 [36:07<40:16,  9.73it/s]

 45%|████████████████                    | 19007/42525 [36:08<39:26,  9.94it/s]

 45%|████████████████                    | 19011/42525 [36:08<38:26, 10.20it/s]

 45%|████████████████                    | 19014/42525 [36:08<45:02,  8.70it/s]

 45%|████████████████                    | 19016/42525 [36:09<43:35,  8.99it/s]

 45%|████████████████                    | 19019/42525 [36:09<47:17,  8.28it/s]

 45%|████████████████                    | 19022/42525 [36:09<46:11,  8.48it/s]

 45%|████████████████                    | 19025/42525 [36:10<42:35,  9.20it/s]

 45%|████████████████                    | 19027/42525 [36:10<47:03,  8.32it/s]

 45%|████████████████                    | 19030/42525 [36:10<45:13,  8.66it/s]

 45%|████████████████                    | 19031/42525 [36:10<47:03,  8.32it/s]

 45%|████████████████                    | 19033/42525 [36:11<45:16,  8.65it/s]

 45%|████████████████                    | 19036/42525 [36:11<48:59,  7.99it/s]

 45%|████████████████                    | 19038/42525 [36:11<46:17,  8.45it/s]

 45%|████████████████                    | 19040/42525 [36:11<43:26,  9.01it/s]

 45%|████████████████                    | 19044/42525 [36:12<41:56,  9.33it/s]

 45%|████████████████▏                   | 19048/42525 [36:12<41:57,  9.33it/s]

 45%|████████████████▏                   | 19050/42525 [36:12<44:27,  8.80it/s]

 45%|████████████████▏                   | 19053/42525 [36:13<43:45,  8.94it/s]

 45%|████████████████▏                   | 19056/42525 [36:13<44:32,  8.78it/s]

 45%|████████████████▏                   | 19058/42525 [36:13<47:07,  8.30it/s]

 45%|████████████████▏                   | 19060/42525 [36:14<44:19,  8.82it/s]

 45%|████████████████▏                   | 19064/42525 [36:14<40:36,  9.63it/s]

 45%|████████████████▏                   | 19066/42525 [36:14<42:43,  9.15it/s]

 45%|████████████████▏                   | 19068/42525 [36:14<40:40,  9.61it/s]

 45%|████████████████▏                   | 19070/42525 [36:15<43:07,  9.06it/s]

 45%|████████████████▏                   | 19073/42525 [36:15<44:03,  8.87it/s]

 45%|████████████████▏                   | 19076/42525 [36:15<45:45,  8.54it/s]

 45%|████████████████▏                   | 19079/42525 [36:16<41:57,  9.31it/s]

 45%|████████████████▏                   | 19083/42525 [36:16<39:11,  9.97it/s]

 45%|████████████████▏                   | 19085/42525 [36:16<39:41,  9.84it/s]

 45%|████████████████▏                   | 19087/42525 [36:16<42:20,  9.23it/s]

 45%|████████████████▏                   | 19090/42525 [36:17<43:18,  9.02it/s]

 45%|████████████████▏                   | 19094/42525 [36:17<42:24,  9.21it/s]

 45%|████████████████▏                   | 19098/42525 [36:18<39:48,  9.81it/s]

 45%|████████████████▏                   | 19100/42525 [36:18<39:30,  9.88it/s]

 45%|████████████████▏                   | 19103/42525 [36:18<43:06,  9.06it/s]

 45%|████████████████▏                   | 19106/42525 [36:19<41:01,  9.51it/s]

 45%|████████████████▏                   | 19108/42525 [36:19<46:30,  8.39it/s]

 45%|████████████████▏                   | 19112/42525 [36:19<41:04,  9.50it/s]

 45%|████████████████▏                   | 19115/42525 [36:20<43:21,  9.00it/s]

 45%|████████████████▏                   | 19119/42525 [36:20<40:11,  9.71it/s]

 45%|████████████████▏                   | 19122/42525 [36:20<40:11,  9.70it/s]

 45%|████████████████▏                   | 19125/42525 [36:21<43:37,  8.94it/s]

 45%|████████████████▏                   | 19127/42525 [36:21<43:59,  8.86it/s]

 45%|████████████████▏                   | 19131/42525 [36:21<39:54,  9.77it/s]

 45%|████████████████▏                   | 19133/42525 [36:21<41:13,  9.46it/s]

 45%|████████████████▏                   | 19135/42525 [36:22<48:20,  8.06it/s]

 45%|████████████████▏                   | 19139/42525 [36:22<41:33,  9.38it/s]

 45%|████████████████▏                   | 19142/42525 [36:22<40:47,  9.55it/s]

 45%|████████████████▏                   | 19143/42525 [36:23<40:59,  9.51it/s]

 45%|████████████████▏                   | 19147/42525 [36:23<39:53,  9.77it/s]

 45%|████████████████▏                   | 19151/42525 [36:23<38:44, 10.06it/s]

 45%|████████████████▏                   | 19154/42525 [36:24<38:31, 10.11it/s]

 45%|████████████████▏                   | 19156/42525 [36:24<41:36,  9.36it/s]

 45%|████████████████▏                   | 19159/42525 [36:24<44:35,  8.73it/s]

 45%|████████████████▏                   | 19163/42525 [36:25<40:45,  9.55it/s]

 45%|████████████████▏                   | 19166/42525 [36:25<44:56,  8.66it/s]

 45%|████████████████▏                   | 19168/42525 [36:25<48:36,  8.01it/s]

 45%|████████████████▏                   | 19170/42525 [36:25<47:59,  8.11it/s]

 45%|████████████████▏                   | 19173/42525 [36:26<47:11,  8.25it/s]

 45%|████████████████▏                   | 19175/42525 [36:26<43:37,  8.92it/s]

 45%|████████████████▏                   | 19176/42525 [36:26<43:00,  9.05it/s]

 45%|████████████████▏                   | 19180/42525 [36:27<42:45,  9.10it/s]

 45%|████████████████▏                   | 19182/42525 [36:27<45:11,  8.61it/s]

 45%|████████████████▏                   | 19183/42525 [36:27<48:18,  8.05it/s]

 45%|████████████████▏                   | 19186/42525 [36:27<48:21,  8.04it/s]

 45%|████████████████▏                   | 19189/42525 [36:28<47:03,  8.27it/s]

 45%|████████████████▏                   | 19192/42525 [36:28<42:10,  9.22it/s]

 45%|████████████████▏                   | 19193/42525 [36:28<45:30,  8.54it/s]

 45%|████████████████▎                   | 19196/42525 [36:29<45:06,  8.62it/s]

 45%|████████████████▎                   | 19197/42525 [36:29<44:16,  8.78it/s]

 45%|████████████████▎                   | 19200/42525 [36:29<43:17,  8.98it/s]

 45%|████████████████▎                   | 19202/42525 [36:29<47:14,  8.23it/s]

 45%|████████████████▎                   | 19204/42525 [36:29<43:56,  8.84it/s]

 45%|████████████████▎                   | 19206/42525 [36:30<50:50,  7.64it/s]

 45%|████████████████▎                   | 19208/42525 [36:30<50:36,  7.68it/s]

 45%|████████████████▎                   | 19211/42525 [36:30<48:07,  8.07it/s]

 45%|████████████████▎                   | 19213/42525 [36:31<44:24,  8.75it/s]

 45%|████████████████▎                   | 19216/42525 [36:31<43:19,  8.97it/s]

 45%|████████████████▎                   | 19218/42525 [36:31<41:09,  9.44it/s]

 45%|████████████████▎                   | 19220/42525 [36:31<41:26,  9.37it/s]

 45%|████████████████▎                   | 19223/42525 [36:32<40:59,  9.47it/s]

 45%|████████████████▎                   | 19226/42525 [36:32<41:14,  9.42it/s]

 45%|████████████████▎                   | 19227/42525 [36:32<41:16,  9.41it/s]

 45%|████████████████▎                   | 19229/42525 [36:32<40:40,  9.55it/s]

 45%|████████████████▎                   | 19233/42525 [36:33<40:33,  9.57it/s]

 45%|████████████████▎                   | 19234/42525 [36:33<43:15,  8.97it/s]

 45%|████████████████▎                   | 19236/42525 [36:33<42:21,  9.16it/s]

 45%|████████████████▎                   | 19240/42525 [36:33<40:12,  9.65it/s]

 45%|████████████████▎                   | 19243/42525 [36:34<39:30,  9.82it/s]

 45%|████████████████▎                   | 19246/42525 [36:34<41:10,  9.42it/s]

 45%|████████████████▎                   | 19249/42525 [36:34<41:58,  9.24it/s]

 45%|████████████████▎                   | 19250/42525 [36:34<41:28,  9.35it/s]

 45%|████████████████▎                   | 19253/42525 [36:35<41:44,  9.29it/s]

 45%|████████████████▎                   | 19256/42525 [36:35<39:38,  9.78it/s]

 45%|████████████████▎                   | 19258/42525 [36:35<45:06,  8.60it/s]

 45%|████████████████▎                   | 19260/42525 [36:36<46:14,  8.39it/s]

 45%|████████████████▎                   | 19264/42525 [36:36<41:12,  9.41it/s]

 45%|████████████████▎                   | 19267/42525 [36:36<40:41,  9.53it/s]

 45%|████████████████▎                   | 19270/42525 [36:37<42:04,  9.21it/s]

 45%|████████████████▎                   | 19272/42525 [36:37<41:59,  9.23it/s]

 45%|████████████████▎                   | 19275/42525 [36:37<42:06,  9.20it/s]

 45%|████████████████▎                   | 19277/42525 [36:37<45:27,  8.52it/s]

 45%|████████████████▎                   | 19279/42525 [36:38<46:21,  8.36it/s]

 45%|████████████████▎                   | 19282/42525 [36:38<41:43,  9.28it/s]

 45%|████████████████▎                   | 19283/42525 [36:38<42:48,  9.05it/s]

 45%|████████████████▎                   | 19286/42525 [36:38<42:39,  9.08it/s]

 45%|████████████████▎                   | 19287/42525 [36:39<42:17,  9.16it/s]

 45%|████████████████▎                   | 19291/42525 [36:39<41:47,  9.27it/s]

 45%|████████████████▎                   | 19293/42525 [36:39<40:24,  9.58it/s]

 45%|████████████████▎                   | 19296/42525 [36:39<40:19,  9.60it/s]

 45%|████████████████▎                   | 19298/42525 [36:40<44:13,  8.75it/s]

 45%|████████████████▎                   | 19300/42525 [36:40<48:12,  8.03it/s]

 45%|████████████████▎                   | 19303/42525 [36:40<48:28,  7.98it/s]

 45%|████████████████▎                   | 19305/42525 [36:41<50:05,  7.72it/s]

 45%|████████████████▎                   | 19307/42525 [36:41<44:37,  8.67it/s]

 45%|████████████████▎                   | 19310/42525 [36:41<48:26,  7.99it/s]

 45%|████████████████▎                   | 19313/42525 [36:42<45:13,  8.55it/s]

 45%|████████████████▎                   | 19317/42525 [36:42<42:07,  9.18it/s]

 45%|████████████████▎                   | 19319/42525 [36:42<41:35,  9.30it/s]

 45%|████████████████▎                   | 19322/42525 [36:43<45:02,  8.59it/s]

 45%|████████████████▎                   | 19325/42525 [36:43<42:22,  9.12it/s]

 45%|████████████████▎                   | 19326/42525 [36:43<45:38,  8.47it/s]

 45%|████████████████▎                   | 19328/42525 [36:43<46:09,  8.38it/s]

 45%|████████████████▎                   | 19331/42525 [36:44<46:05,  8.39it/s]

 45%|████████████████▎                   | 19333/42525 [36:44<43:19,  8.92it/s]

 45%|████████████████▎                   | 19336/42525 [36:44<40:52,  9.45it/s]

 45%|████████████████▎                   | 19338/42525 [36:44<39:22,  9.81it/s]

 45%|████████████████▎                   | 19342/42525 [36:45<40:42,  9.49it/s]

 45%|████████████████▍                   | 19344/42525 [36:45<43:06,  8.96it/s]

 45%|████████████████▍                   | 19347/42525 [36:45<42:26,  9.10it/s]

 46%|████████████████▍                   | 19349/42525 [36:46<40:32,  9.53it/s]

 46%|████████████████▍                   | 19352/42525 [36:46<42:46,  9.03it/s]

 46%|████████████████▍                   | 19354/42525 [36:46<43:07,  8.95it/s]

 46%|████████████████▍                   | 19356/42525 [36:46<40:46,  9.47it/s]

 46%|████████████████▍                   | 19358/42525 [36:46<40:03,  9.64it/s]

 46%|████████████████▍                   | 19362/42525 [36:47<39:04,  9.88it/s]

 46%|████████████████▍                   | 19366/42525 [36:47<38:00, 10.15it/s]

 46%|████████████████▍                   | 19368/42525 [36:47<38:27, 10.04it/s]

 46%|████████████████▍                   | 19370/42525 [36:48<41:06,  9.39it/s]

 46%|████████████████▍                   | 19374/42525 [36:48<39:57,  9.66it/s]

 46%|████████████████▍                   | 19376/42525 [36:48<41:04,  9.39it/s]

 46%|████████████████▍                   | 19379/42525 [36:49<41:45,  9.24it/s]

 46%|████████████████▍                   | 19382/42525 [36:49<41:36,  9.27it/s]

 46%|████████████████▍                   | 19386/42525 [36:49<39:33,  9.75it/s]

 46%|████████████████▍                   | 19390/42525 [36:50<38:08, 10.11it/s]

 46%|████████████████▍                   | 19392/42525 [36:50<37:46, 10.21it/s]

 46%|████████████████▍                   | 19395/42525 [36:50<39:43,  9.70it/s]

 46%|████████████████▍                   | 19398/42525 [36:51<40:19,  9.56it/s]

 46%|████████████████▍                   | 19400/42525 [36:51<41:46,  9.22it/s]

 46%|████████████████▍                   | 19404/42525 [36:51<39:40,  9.71it/s]

 46%|████████████████▍                   | 19407/42525 [36:52<38:42,  9.95it/s]

 46%|████████████████▍                   | 19409/42525 [36:52<38:04, 10.12it/s]

 46%|████████████████▍                   | 19412/42525 [36:52<43:02,  8.95it/s]

 46%|████████████████▍                   | 19413/42525 [36:52<42:43,  9.02it/s]

 46%|████████████████▍                   | 19416/42525 [36:53<42:08,  9.14it/s]

 46%|████████████████▍                   | 19419/42525 [36:53<45:12,  8.52it/s]

 46%|████████████████▍                   | 19422/42525 [36:53<47:00,  8.19it/s]

 46%|████████████████▍                   | 19425/42525 [36:54<44:24,  8.67it/s]

 46%|████████████████▍                   | 19428/42525 [36:54<40:51,  9.42it/s]

 46%|████████████████▍                   | 19430/42525 [36:54<40:54,  9.41it/s]

 46%|████████████████▍                   | 19433/42525 [36:54<43:11,  8.91it/s]

 46%|████████████████▍                   | 19436/42525 [36:55<43:53,  8.77it/s]

 46%|████████████████▍                   | 19437/42525 [36:55<43:39,  8.82it/s]

 46%|████████████████▍                   | 19441/42525 [36:55<42:44,  9.00it/s]

 46%|████████████████▍                   | 19442/42525 [36:55<41:57,  9.17it/s]

 46%|████████████████▍                   | 19446/42525 [36:56<40:19,  9.54it/s]

 46%|████████████████▍                   | 19448/42525 [36:56<41:05,  9.36it/s]

 46%|████████████████▍                   | 19449/42525 [36:56<40:46,  9.43it/s]

 46%|████████████████▍                   | 19452/42525 [36:57<43:09,  8.91it/s]

 46%|████████████████▍                   | 19455/42525 [36:57<40:11,  9.57it/s]

 46%|████████████████▍                   | 19458/42525 [36:57<43:07,  8.92it/s]

 46%|████████████████▍                   | 19460/42525 [36:57<44:29,  8.64it/s]

 46%|████████████████▍                   | 19463/42525 [36:58<40:52,  9.40it/s]

 46%|████████████████▍                   | 19467/42525 [36:58<39:11,  9.80it/s]

 46%|████████████████▍                   | 19469/42525 [36:58<41:50,  9.19it/s]

 46%|████████████████▍                   | 19470/42525 [36:59<44:42,  8.59it/s]

 46%|████████████████▍                   | 19474/42525 [36:59<40:53,  9.39it/s]

 46%|████████████████▍                   | 19477/42525 [36:59<40:38,  9.45it/s]

 46%|████████████████▍                   | 19480/42525 [37:00<43:11,  8.89it/s]

 46%|████████████████▍                   | 19481/42525 [37:00<42:13,  9.09it/s]

 46%|████████████████▍                   | 19484/42525 [37:00<47:02,  8.16it/s]

 46%|████████████████▍                   | 19485/42525 [37:00<44:58,  8.54it/s]

 46%|████████████████▍                   | 19489/42525 [37:01<40:44,  9.42it/s]

 46%|████████████████▌                   | 19492/42525 [37:01<41:27,  9.26it/s]

 46%|████████████████▌                   | 19494/42525 [37:01<39:47,  9.65it/s]

 46%|████████████████▌                   | 19497/42525 [37:01<40:06,  9.57it/s]

 46%|████████████████▌                   | 19500/42525 [37:02<43:01,  8.92it/s]

 46%|████████████████▌                   | 19501/42525 [37:02<42:08,  9.10it/s]

 46%|████████████████▌                   | 19504/42525 [37:02<42:55,  8.94it/s]

 46%|████████████████▌                   | 19506/42525 [37:02<42:43,  8.98it/s]

 46%|████████████████▌                   | 19507/42525 [37:03<46:26,  8.26it/s]

 46%|████████████████▌                   | 19511/42525 [37:03<43:48,  8.76it/s]

 46%|████████████████▌                   | 19513/42525 [37:03<46:23,  8.27it/s]

 46%|████████████████▌                   | 19515/42525 [37:04<43:07,  8.89it/s]

 46%|████████████████▌                   | 19519/42525 [37:04<42:02,  9.12it/s]

 46%|████████████████▌                   | 19522/42525 [37:04<41:37,  9.21it/s]

 46%|████████████████▌                   | 19524/42525 [37:05<45:19,  8.46it/s]

 46%|████████████████▌                   | 19527/42525 [37:05<43:03,  8.90it/s]

 46%|████████████████▌                   | 19530/42525 [37:05<41:07,  9.32it/s]

 46%|████████████████▌                   | 19533/42525 [37:05<39:13,  9.77it/s]

 46%|████████████████▌                   | 19536/42525 [37:06<42:33,  9.00it/s]

 46%|████████████████▌                   | 19539/42525 [37:06<42:33,  9.00it/s]

 46%|████████████████▌                   | 19541/42525 [37:06<42:12,  9.08it/s]

 46%|████████████████▌                   | 19543/42525 [37:07<42:02,  9.11it/s]

 46%|████████████████▌                   | 19546/42525 [37:07<39:43,  9.64it/s]

 46%|████████████████▌                   | 19547/42525 [37:07<43:31,  8.80it/s]

 46%|████████████████▌                   | 19551/42525 [37:07<42:01,  9.11it/s]

 46%|████████████████▌                   | 19555/42525 [37:08<39:20,  9.73it/s]

 46%|████████████████▌                   | 19559/42525 [37:08<38:22,  9.98it/s]

 46%|████████████████▌                   | 19560/42525 [37:08<39:02,  9.80it/s]

 46%|████████████████▌                   | 19562/42525 [37:09<38:55,  9.83it/s]

 46%|████████████████▌                   | 19566/42525 [37:09<38:35,  9.92it/s]

 46%|████████████████▌                   | 19570/42525 [37:09<38:37,  9.91it/s]

 46%|████████████████▌                   | 19574/42525 [37:10<38:18,  9.99it/s]

 46%|████████████████▌                   | 19576/42525 [37:10<37:54, 10.09it/s]

 46%|████████████████▌                   | 19579/42525 [37:10<39:12,  9.75it/s]

 46%|████████████████▌                   | 19582/42525 [37:11<39:37,  9.65it/s]

 46%|████████████████▌                   | 19584/42525 [37:11<38:50,  9.85it/s]

 46%|████████████████▌                   | 19588/42525 [37:11<39:04,  9.78it/s]

 46%|████████████████▌                   | 19591/42525 [37:12<40:11,  9.51it/s]

 46%|████████████████▌                   | 19593/42525 [37:12<41:46,  9.15it/s]

 46%|████████████████▌                   | 19595/42525 [37:12<45:06,  8.47it/s]

 46%|████████████████▌                   | 19598/42525 [37:12<44:32,  8.58it/s]

 46%|████████████████▌                   | 19599/42525 [37:12<44:56,  8.50it/s]

 46%|████████████████▌                   | 19602/42525 [37:13<42:59,  8.89it/s]

 46%|████████████████▌                   | 19604/42525 [37:13<43:18,  8.82it/s]

 46%|████████████████▌                   | 19607/42525 [37:13<45:26,  8.40it/s]

 46%|████████████████▌                   | 19610/42525 [37:14<42:00,  9.09it/s]

 46%|████████████████▌                   | 19613/42525 [37:14<42:11,  9.05it/s]

 46%|████████████████▌                   | 19614/42525 [37:14<45:28,  8.40it/s]

 46%|████████████████▌                   | 19617/42525 [37:15<47:09,  8.10it/s]

 46%|████████████████▌                   | 19618/42525 [37:15<45:17,  8.43it/s]

 46%|████████████████▌                   | 19620/42525 [37:15<43:04,  8.86it/s]

 46%|████████████████▌                   | 19623/42525 [37:15<46:09,  8.27it/s]

 46%|████████████████▌                   | 19627/42525 [37:16<43:13,  8.83it/s]

 46%|████████████████▌                   | 19629/42525 [37:16<48:40,  7.84it/s]

 46%|████████████████▌                   | 19632/42525 [37:16<44:09,  8.64it/s]

 46%|████████████████▌                   | 19636/42525 [37:17<39:39,  9.62it/s]

 46%|████████████████▋                   | 19639/42525 [37:17<43:32,  8.76it/s]

 46%|████████████████▋                   | 19642/42525 [37:17<44:12,  8.63it/s]

 46%|████████████████▋                   | 19643/42525 [37:18<46:51,  8.14it/s]

 46%|████████████████▋                   | 19646/42525 [37:18<43:07,  8.84it/s]

 46%|████████████████▋                   | 19648/42525 [37:18<45:26,  8.39it/s]

 46%|████████████████▋                   | 19651/42525 [37:18<41:19,  9.23it/s]

 46%|████████████████▋                   | 19655/42525 [37:19<38:50,  9.81it/s]

 46%|████████████████▋                   | 19657/42525 [37:19<39:20,  9.69it/s]

 46%|████████████████▋                   | 19660/42525 [37:19<40:31,  9.40it/s]

 46%|████████████████▋                   | 19663/42525 [37:20<39:18,  9.69it/s]

 46%|████████████████▋                   | 19666/42525 [37:20<39:45,  9.58it/s]

 46%|████████████████▋                   | 19668/42525 [37:20<38:55,  9.79it/s]

 46%|████████████████▋                   | 19670/42525 [37:20<38:57,  9.78it/s]

 46%|████████████████▋                   | 19674/42525 [37:21<38:23,  9.92it/s]

 46%|████████████████▋                   | 19677/42525 [37:21<41:34,  9.16it/s]

 46%|████████████████▋                   | 19679/42525 [37:21<42:14,  9.02it/s]

 46%|████████████████▋                   | 19680/42525 [37:21<43:02,  8.85it/s]

 46%|████████████████▋                   | 19683/42525 [37:22<45:42,  8.33it/s]

 46%|████████████████▋                   | 19686/42525 [37:22<42:57,  8.86it/s]

 46%|████████████████▋                   | 19687/42525 [37:22<42:52,  8.88it/s]

 46%|████████████████▋                   | 19690/42525 [37:23<42:51,  8.88it/s]

 46%|████████████████▋                   | 19691/42525 [37:23<42:26,  8.97it/s]

 46%|████████████████▋                   | 19693/42525 [37:23<43:15,  8.80it/s]

 46%|████████████████▋                   | 19695/42525 [37:23<42:48,  8.89it/s]

 46%|████████████████▋                   | 19697/42525 [37:23<44:20,  8.58it/s]

 46%|████████████████▋                   | 19700/42525 [37:24<43:34,  8.73it/s]

 46%|████████████████▋                   | 19704/42525 [37:24<39:56,  9.52it/s]

 46%|████████████████▋                   | 19707/42525 [37:24<38:45,  9.81it/s]

 46%|████████████████▋                   | 19710/42525 [37:25<39:23,  9.65it/s]

 46%|████████████████▋                   | 19712/42525 [37:25<45:19,  8.39it/s]

 46%|████████████████▋                   | 19713/42525 [37:25<47:59,  7.92it/s]

 46%|████████████████▋                   | 19717/42525 [37:26<41:05,  9.25it/s]

 46%|████████████████▋                   | 19720/42525 [37:26<40:21,  9.42it/s]

 46%|████████████████▋                   | 19722/42525 [37:26<42:21,  8.97it/s]

 46%|████████████████▋                   | 19725/42525 [37:27<43:18,  8.78it/s]

 46%|████████████████▋                   | 19727/42525 [37:27<40:58,  9.27it/s]

 46%|████████████████▋                   | 19730/42525 [37:27<43:56,  8.65it/s]

 46%|████████████████▋                   | 19733/42525 [37:27<41:14,  9.21it/s]

 46%|████████████████▋                   | 19737/42525 [37:28<38:31,  9.86it/s]

 46%|████████████████▋                   | 19740/42525 [37:28<40:00,  9.49it/s]

 46%|████████████████▋                   | 19742/42525 [37:28<41:16,  9.20it/s]

 46%|████████████████▋                   | 19745/42525 [37:29<39:54,  9.51it/s]

 46%|████████████████▋                   | 19748/42525 [37:29<38:56,  9.75it/s]

 46%|████████████████▋                   | 19751/42525 [37:29<39:38,  9.57it/s]

 46%|████████████████▋                   | 19753/42525 [37:29<38:21,  9.89it/s]

 46%|████████████████▋                   | 19756/42525 [37:30<39:15,  9.67it/s]

 46%|████████████████▋                   | 19757/42525 [37:30<39:25,  9.63it/s]

 46%|████████████████▋                   | 19760/42525 [37:30<44:44,  8.48it/s]

 46%|████████████████▋                   | 19763/42525 [37:31<42:34,  8.91it/s]

 46%|████████████████▋                   | 19765/42525 [37:31<45:23,  8.36it/s]

 46%|████████████████▋                   | 19766/42525 [37:31<48:08,  7.88it/s]

 46%|████████████████▋                   | 19769/42525 [37:31<45:20,  8.37it/s]

 46%|████████████████▋                   | 19772/42525 [37:32<41:34,  9.12it/s]

 46%|████████████████▋                   | 19774/42525 [37:32<45:40,  8.30it/s]

 47%|████████████████▋                   | 19775/42525 [37:32<48:35,  7.80it/s]

 47%|████████████████▋                   | 19779/42525 [37:32<41:35,  9.12it/s]

 47%|████████████████▋                   | 19781/42525 [37:33<39:37,  9.57it/s]

 47%|████████████████▋                   | 19783/42525 [37:33<40:20,  9.39it/s]

 47%|████████████████▊                   | 19787/42525 [37:33<40:28,  9.36it/s]

 47%|████████████████▊                   | 19788/42525 [37:33<40:52,  9.27it/s]

 47%|████████████████▊                   | 19790/42525 [37:34<42:46,  8.86it/s]

 47%|████████████████▊                   | 19794/42525 [37:34<41:37,  9.10it/s]

 47%|████████████████▊                   | 19798/42525 [37:34<39:10,  9.67it/s]

 47%|████████████████▊                   | 19800/42525 [37:35<44:18,  8.55it/s]

 47%|████████████████▊                   | 19803/42525 [37:35<43:14,  8.76it/s]

 47%|████████████████▊                   | 19807/42525 [37:36<39:38,  9.55it/s]

 47%|████████████████▊                   | 19810/42525 [37:36<39:13,  9.65it/s]

 47%|████████████████▊                   | 19813/42525 [37:36<38:08,  9.93it/s]

 47%|████████████████▊                   | 19817/42525 [37:36<37:07, 10.20it/s]

 47%|████████████████▊                   | 19821/42525 [37:37<37:05, 10.20it/s]

 47%|████████████████▊                   | 19824/42525 [37:37<42:55,  8.81it/s]

 47%|████████████████▊                   | 19828/42525 [37:38<39:11,  9.65it/s]

 47%|████████████████▊                   | 19832/42525 [37:38<37:56,  9.97it/s]

 47%|████████████████▊                   | 19833/42525 [37:38<41:19,  9.15it/s]

 47%|████████████████▊                   | 19836/42525 [37:39<42:13,  8.96it/s]

 47%|████████████████▊                   | 19840/42525 [37:39<38:58,  9.70it/s]

 47%|████████████████▊                   | 19844/42525 [37:39<37:46, 10.00it/s]

 47%|████████████████▊                   | 19846/42525 [37:40<41:09,  9.18it/s]

 47%|████████████████▊                   | 19849/42525 [37:40<39:41,  9.52it/s]

 47%|████████████████▊                   | 19852/42525 [37:40<39:16,  9.62it/s]

 47%|████████████████▊                   | 19854/42525 [37:40<39:36,  9.54it/s]

 47%|████████████████▊                   | 19857/42525 [37:41<40:15,  9.38it/s]

 47%|████████████████▊                   | 19859/42525 [37:41<43:57,  8.60it/s]

 47%|████████████████▊                   | 19862/42525 [37:41<41:31,  9.10it/s]

 47%|████████████████▊                   | 19864/42525 [37:42<43:09,  8.75it/s]

 47%|████████████████▊                   | 19866/42525 [37:42<40:15,  9.38it/s]

 47%|████████████████▊                   | 19868/42525 [37:42<39:35,  9.54it/s]

 47%|████████████████▊                   | 19872/42525 [37:42<40:15,  9.38it/s]

 47%|████████████████▊                   | 19875/42525 [37:43<39:03,  9.66it/s]

 47%|████████████████▊                   | 19877/42525 [37:43<39:56,  9.45it/s]

 47%|████████████████▊                   | 19879/42525 [37:43<39:49,  9.48it/s]

 47%|████████████████▊                   | 19883/42525 [37:44<40:09,  9.40it/s]

 47%|████████████████▊                   | 19885/42525 [37:44<46:26,  8.13it/s]

 47%|████████████████▊                   | 19888/42525 [37:44<41:36,  9.07it/s]

 47%|████████████████▊                   | 19890/42525 [37:44<39:39,  9.51it/s]

 47%|████████████████▊                   | 19893/42525 [37:45<42:32,  8.86it/s]

 47%|████████████████▊                   | 19896/42525 [37:45<39:51,  9.46it/s]

 47%|████████████████▊                   | 19899/42525 [37:45<40:43,  9.26it/s]

 47%|████████████████▊                   | 19901/42525 [37:45<39:09,  9.63it/s]

 47%|████████████████▊                   | 19905/42525 [37:46<39:54,  9.44it/s]

 47%|████████████████▊                   | 19907/42525 [37:46<43:07,  8.74it/s]

 47%|████████████████▊                   | 19908/42525 [37:46<46:01,  8.19it/s]

 47%|████████████████▊                   | 19911/42525 [37:47<43:04,  8.75it/s]

 47%|████████████████▊                   | 19913/42525 [37:47<44:01,  8.56it/s]

 47%|████████████████▊                   | 19914/42525 [37:47<43:51,  8.59it/s]

 47%|████████████████▊                   | 19918/42525 [37:47<39:28,  9.54it/s]

 47%|████████████████▊                   | 19921/42525 [37:48<38:45,  9.72it/s]

 47%|████████████████▊                   | 19924/42525 [37:48<39:53,  9.44it/s]

 47%|████████████████▊                   | 19928/42525 [37:48<40:19,  9.34it/s]

 47%|████████████████▊                   | 19932/42525 [37:49<40:41,  9.26it/s]

 47%|████████████████▉                   | 19934/42525 [37:49<44:12,  8.52it/s]

 47%|████████████████▉                   | 19936/42525 [37:49<41:55,  8.98it/s]

 47%|████████████████▉                   | 19939/42525 [37:50<45:50,  8.21it/s]

 47%|████████████████▉                   | 19942/42525 [37:50<45:04,  8.35it/s]

 47%|████████████████▉                   | 19946/42525 [37:51<42:15,  8.90it/s]

 47%|████████████████▉                   | 19950/42525 [37:51<38:55,  9.66it/s]

 47%|████████████████▉                   | 19952/42525 [37:51<41:07,  9.15it/s]

 47%|████████████████▉                   | 19954/42525 [37:51<39:07,  9.62it/s]

 47%|████████████████▉                   | 19956/42525 [37:52<41:40,  9.02it/s]

 47%|████████████████▉                   | 19959/42525 [37:52<45:04,  8.34it/s]

 47%|████████████████▉                   | 19962/42525 [37:52<43:39,  8.61it/s]

 47%|████████████████▉                   | 19966/42525 [37:53<39:10,  9.60it/s]

 47%|████████████████▉                   | 19969/42525 [37:53<39:52,  9.43it/s]

 47%|████████████████▉                   | 19972/42525 [37:53<42:41,  8.80it/s]

 47%|████████████████▉                   | 19974/42525 [37:54<42:30,  8.84it/s]

 47%|████████████████▉                   | 19976/42525 [37:54<39:59,  9.40it/s]

 47%|████████████████▉                   | 19980/42525 [37:54<40:15,  9.33it/s]

 47%|████████████████▉                   | 19981/42525 [37:54<41:53,  8.97it/s]

 47%|████████████████▉                   | 19983/42525 [37:55<43:21,  8.67it/s]

 47%|████████████████▉                   | 19987/42525 [37:55<40:08,  9.36it/s]

 47%|████████████████▉                   | 19989/42525 [37:55<41:52,  8.97it/s]

 47%|████████████████▉                   | 19991/42525 [37:56<44:19,  8.47it/s]

 47%|████████████████▉                   | 19993/42525 [37:56<43:33,  8.62it/s]

 47%|████████████████▉                   | 19997/42525 [37:56<39:13,  9.57it/s]

 47%|████████████████▉                   | 20000/42525 [37:56<38:02,  9.87it/s]

 47%|████████████████▉                   | 20003/42525 [37:57<42:55,  8.74it/s]

 47%|████████████████▉                   | 20006/42525 [37:57<40:37,  9.24it/s]

 47%|████████████████▉                   | 20007/42525 [37:57<42:29,  8.83it/s]

 47%|████████████████▉                   | 20011/42525 [37:58<41:03,  9.14it/s]

 47%|████████████████▉                   | 20014/42525 [37:58<42:45,  8.77it/s]

 47%|████████████████▉                   | 20017/42525 [37:58<41:00,  9.15it/s]

 47%|████████████████▉                   | 20021/42525 [37:59<38:05,  9.85it/s]

 47%|████████████████▉                   | 20024/42525 [37:59<40:51,  9.18it/s]

 47%|████████████████▉                   | 20027/42525 [37:59<41:01,  9.14it/s]

 47%|████████████████▉                   | 20031/42525 [38:00<38:17,  9.79it/s]

 47%|████████████████▉                   | 20035/42525 [38:00<37:09, 10.09it/s]

 47%|████████████████▉                   | 20037/42525 [38:00<36:58, 10.14it/s]

 47%|████████████████▉                   | 20040/42525 [38:01<39:02,  9.60it/s]

 47%|████████████████▉                   | 20042/42525 [38:01<42:05,  8.90it/s]

 47%|████████████████▉                   | 20045/42525 [38:01<43:12,  8.67it/s]

 47%|████████████████▉                   | 20046/42525 [38:01<44:41,  8.38it/s]

 47%|████████████████▉                   | 20050/42525 [38:02<41:09,  9.10it/s]

 47%|████████████████▉                   | 20053/42525 [38:02<39:56,  9.38it/s]

 47%|████████████████▉                   | 20054/42525 [38:02<41:12,  9.09it/s]

 47%|████████████████▉                   | 20057/42525 [38:03<44:02,  8.50it/s]

 47%|████████████████▉                   | 20059/42525 [38:03<41:03,  9.12it/s]

 47%|████████████████▉                   | 20061/42525 [38:03<39:54,  9.38it/s]

 47%|████████████████▉                   | 20064/42525 [38:03<43:55,  8.52it/s]

 47%|████████████████▉                   | 20066/42525 [38:04<42:52,  8.73it/s]

 47%|████████████████▉                   | 20069/42525 [38:04<39:32,  9.47it/s]

 47%|████████████████▉                   | 20073/42525 [38:04<40:13,  9.30it/s]

 47%|████████████████▉                   | 20075/42525 [38:05<44:16,  8.45it/s]

 47%|████████████████▉                   | 20077/42525 [38:05<43:21,  8.63it/s]

 47%|████████████████▉                   | 20079/42525 [38:05<47:31,  7.87it/s]

 47%|█████████████████                   | 20082/42525 [38:05<42:21,  8.83it/s]

 47%|█████████████████                   | 20084/42525 [38:06<44:13,  8.46it/s]

 47%|█████████████████                   | 20088/42525 [38:06<39:03,  9.57it/s]

 47%|█████████████████                   | 20090/42525 [38:06<39:28,  9.47it/s]

 47%|█████████████████                   | 20093/42525 [38:07<40:14,  9.29it/s]

 47%|█████████████████                   | 20096/42525 [38:07<42:07,  8.87it/s]

 47%|█████████████████                   | 20099/42525 [38:07<43:29,  8.59it/s]

 47%|█████████████████                   | 20102/42525 [38:08<41:58,  8.90it/s]

 47%|█████████████████                   | 20105/42525 [38:08<39:28,  9.47it/s]

 47%|█████████████████                   | 20109/42525 [38:08<38:20,  9.74it/s]

 47%|█████████████████                   | 20112/42525 [38:09<41:03,  9.10it/s]

 47%|█████████████████                   | 20115/42525 [38:09<40:17,  9.27it/s]

 47%|█████████████████                   | 20116/42525 [38:09<43:36,  8.56it/s]

 47%|█████████████████                   | 20118/42525 [38:09<42:47,  8.73it/s]

 47%|█████████████████                   | 20121/42525 [38:10<46:16,  8.07it/s]

 47%|█████████████████                   | 20125/42525 [38:10<41:05,  9.09it/s]

 47%|█████████████████                   | 20127/42525 [38:10<41:25,  9.01it/s]

 47%|█████████████████                   | 20130/42525 [38:11<39:01,  9.56it/s]

 47%|█████████████████                   | 20131/42525 [38:11<42:33,  8.77it/s]

 47%|█████████████████                   | 20135/42525 [38:11<40:59,  9.10it/s]

 47%|█████████████████                   | 20139/42525 [38:12<38:22,  9.72it/s]

 47%|█████████████████                   | 20140/42525 [38:12<38:33,  9.68it/s]

 47%|█████████████████                   | 20142/42525 [38:12<40:59,  9.10it/s]

 47%|█████████████████                   | 20145/42525 [38:12<43:21,  8.60it/s]

 47%|█████████████████                   | 20148/42525 [38:13<42:16,  8.82it/s]

 47%|█████████████████                   | 20152/42525 [38:13<39:46,  9.38it/s]

 47%|█████████████████                   | 20156/42525 [38:14<40:06,  9.29it/s]

 47%|█████████████████                   | 20159/42525 [38:14<42:07,  8.85it/s]

 47%|█████████████████                   | 20162/42525 [38:14<39:55,  9.34it/s]

 47%|█████████████████                   | 20165/42525 [38:15<40:20,  9.24it/s]

 47%|█████████████████                   | 20167/42525 [38:15<40:39,  9.16it/s]

 47%|█████████████████                   | 20171/42525 [38:15<37:59,  9.81it/s]

 47%|█████████████████                   | 20174/42525 [38:16<38:57,  9.56it/s]

 47%|█████████████████                   | 20177/42525 [38:16<37:50,  9.84it/s]

 47%|█████████████████                   | 20180/42525 [38:16<40:53,  9.11it/s]

 47%|█████████████████                   | 20182/42525 [38:16<43:39,  8.53it/s]

 47%|█████████████████                   | 20185/42525 [38:17<44:14,  8.42it/s]

 47%|█████████████████                   | 20187/42525 [38:17<44:39,  8.34it/s]

 47%|█████████████████                   | 20189/42525 [38:17<42:31,  8.75it/s]

 47%|█████████████████                   | 20192/42525 [38:18<42:34,  8.74it/s]

 47%|█████████████████                   | 20196/42525 [38:18<38:49,  9.58it/s]

 47%|█████████████████                   | 20199/42525 [38:18<38:26,  9.68it/s]

 48%|█████████████████                   | 20200/42525 [38:18<40:33,  9.17it/s]

 48%|█████████████████                   | 20204/42525 [38:19<38:52,  9.57it/s]

 48%|█████████████████                   | 20207/42525 [38:19<41:51,  8.89it/s]

 48%|█████████████████                   | 20208/42525 [38:19<44:33,  8.35it/s]

 48%|█████████████████                   | 20211/42525 [38:20<44:41,  8.32it/s]

 48%|█████████████████                   | 20214/42525 [38:20<41:52,  8.88it/s]

 48%|█████████████████                   | 20216/42525 [38:20<44:08,  8.42it/s]

 48%|█████████████████                   | 20219/42525 [38:21<41:02,  9.06it/s]

 48%|█████████████████                   | 20223/42525 [38:21<38:17,  9.71it/s]

 48%|█████████████████                   | 20226/42525 [38:21<41:58,  8.86it/s]

 48%|█████████████████                   | 20228/42525 [38:22<44:28,  8.36it/s]

 48%|█████████████████▏                  | 20229/42525 [38:22<47:10,  7.88it/s]

 48%|█████████████████▏                  | 20233/42525 [38:22<40:30,  9.17it/s]

 48%|█████████████████▏                  | 20237/42525 [38:23<38:48,  9.57it/s]

 48%|█████████████████▏                  | 20240/42525 [38:23<40:09,  9.25it/s]

 48%|█████████████████▏                  | 20242/42525 [38:23<45:16,  8.20it/s]

 48%|█████████████████▏                  | 20244/42525 [38:23<44:35,  8.33it/s]

 48%|█████████████████▏                  | 20247/42525 [38:24<41:25,  8.96it/s]

 48%|█████████████████▏                  | 20250/42525 [38:24<42:52,  8.66it/s]

 48%|█████████████████▏                  | 20252/42525 [38:24<41:42,  8.90it/s]

 48%|█████████████████▏                  | 20256/42525 [38:25<37:52,  9.80it/s]

 48%|█████████████████▏                  | 20258/42525 [38:25<44:07,  8.41it/s]

 48%|█████████████████▏                  | 20262/42525 [38:25<38:52,  9.54it/s]

 48%|█████████████████▏                  | 20265/42525 [38:26<40:28,  9.16it/s]

 48%|█████████████████▏                  | 20266/42525 [38:26<40:43,  9.11it/s]

 48%|█████████████████▏                  | 20270/42525 [38:26<40:16,  9.21it/s]

 48%|█████████████████▏                  | 20274/42525 [38:27<38:26,  9.65it/s]

 48%|█████████████████▏                  | 20276/42525 [38:27<38:46,  9.56it/s]

 48%|█████████████████▏                  | 20280/42525 [38:27<39:25,  9.40it/s]

 48%|█████████████████▏                  | 20283/42525 [38:28<39:56,  9.28it/s]

 48%|█████████████████▏                  | 20285/42525 [38:28<38:26,  9.64it/s]

 48%|█████████████████▏                  | 20287/42525 [38:28<40:48,  9.08it/s]

 48%|█████████████████▏                  | 20290/42525 [38:28<42:47,  8.66it/s]

 48%|█████████████████▏                  | 20292/42525 [38:29<40:26,  9.16it/s]

 48%|█████████████████▏                  | 20295/42525 [38:29<40:39,  9.11it/s]

 48%|█████████████████▏                  | 20297/42525 [38:29<39:04,  9.48it/s]

 48%|█████████████████▏                  | 20301/42525 [38:30<39:27,  9.39it/s]

 48%|█████████████████▏                  | 20303/42525 [38:30<38:27,  9.63it/s]

 48%|█████████████████▏                  | 20306/42525 [38:30<39:04,  9.48it/s]

 48%|█████████████████▏                  | 20309/42525 [38:30<42:07,  8.79it/s]

 48%|█████████████████▏                  | 20310/42525 [38:31<42:27,  8.72it/s]

 48%|█████████████████▏                  | 20313/42525 [38:31<40:33,  9.13it/s]

 48%|█████████████████▏                  | 20316/42525 [38:31<40:58,  9.03it/s]

 48%|█████████████████▏                  | 20318/42525 [38:31<45:43,  8.09it/s]

 48%|█████████████████▏                  | 20320/42525 [38:32<41:38,  8.89it/s]

 48%|█████████████████▏                  | 20323/42525 [38:32<45:33,  8.12it/s]

 48%|█████████████████▏                  | 20325/42525 [38:32<46:26,  7.97it/s]

 48%|█████████████████▏                  | 20327/42525 [38:33<46:49,  7.90it/s]

 48%|█████████████████▏                  | 20329/42525 [38:33<47:16,  7.83it/s]

 48%|█████████████████▏                  | 20332/42525 [38:33<41:27,  8.92it/s]

 48%|█████████████████▏                  | 20335/42525 [38:33<42:41,  8.66it/s]

 48%|█████████████████▏                  | 20339/42525 [38:34<38:26,  9.62it/s]

 48%|█████████████████▏                  | 20341/42525 [38:34<37:21,  9.90it/s]

 48%|█████████████████▏                  | 20343/42525 [38:34<39:55,  9.26it/s]

 48%|█████████████████▏                  | 20345/42525 [38:34<39:04,  9.46it/s]

 48%|█████████████████▏                  | 20349/42525 [38:35<38:15,  9.66it/s]

 48%|█████████████████▏                  | 20351/42525 [38:35<38:50,  9.51it/s]

 48%|█████████████████▏                  | 20354/42525 [38:35<40:52,  9.04it/s]

 48%|█████████████████▏                  | 20356/42525 [38:36<40:24,  9.14it/s]

 48%|█████████████████▏                  | 20358/42525 [38:36<41:36,  8.88it/s]

 48%|█████████████████▏                  | 20360/42525 [38:36<40:00,  9.23it/s]

 48%|█████████████████▏                  | 20363/42525 [38:36<40:45,  9.06it/s]

 48%|█████████████████▏                  | 20365/42525 [38:37<44:36,  8.28it/s]

 48%|█████████████████▏                  | 20367/42525 [38:37<46:07,  8.01it/s]

 48%|█████████████████▏                  | 20369/42525 [38:37<41:40,  8.86it/s]

 48%|█████████████████▏                  | 20371/42525 [38:37<43:56,  8.40it/s]

 48%|█████████████████▏                  | 20373/42525 [38:38<45:37,  8.09it/s]

 48%|█████████████████▏                  | 20375/42525 [38:38<44:05,  8.37it/s]

 48%|█████████████████▏                  | 20376/42525 [38:38<43:20,  8.52it/s]

 48%|█████████████████▎                  | 20379/42525 [38:38<43:03,  8.57it/s]

 48%|█████████████████▎                  | 20381/42525 [38:39<39:50,  9.27it/s]

 48%|█████████████████▎                  | 20385/42525 [38:39<37:55,  9.73it/s]

 48%|█████████████████▎                  | 20388/42525 [38:39<39:40,  9.30it/s]

 48%|█████████████████▎                  | 20390/42525 [38:39<39:36,  9.31it/s]

 48%|█████████████████▎                  | 20392/42525 [38:40<46:26,  7.94it/s]

 48%|█████████████████▎                  | 20394/42525 [38:40<42:42,  8.64it/s]

 48%|█████████████████▎                  | 20396/42525 [38:40<43:31,  8.47it/s]

 48%|█████████████████▎                  | 20398/42525 [38:41<46:25,  7.94it/s]

 48%|█████████████████▎                  | 20401/42525 [38:41<44:59,  8.19it/s]

 48%|█████████████████▎                  | 20403/42525 [38:41<46:52,  7.87it/s]

 48%|█████████████████▎                  | 20406/42525 [38:41<40:31,  9.10it/s]

 48%|█████████████████▎                  | 20410/42525 [38:42<39:55,  9.23it/s]

 48%|█████████████████▎                  | 20412/42525 [38:42<43:23,  8.49it/s]

 48%|█████████████████▎                  | 20413/42525 [38:42<42:01,  8.77it/s]

 48%|█████████████████▎                  | 20417/42525 [38:43<40:26,  9.11it/s]

 48%|█████████████████▎                  | 20421/42525 [38:43<37:34,  9.81it/s]

 48%|█████████████████▎                  | 20424/42525 [38:43<38:02,  9.68it/s]

 48%|█████████████████▎                  | 20425/42525 [38:44<41:24,  8.89it/s]

 48%|█████████████████▎                  | 20428/42525 [38:44<39:30,  9.32it/s]

 48%|█████████████████▎                  | 20432/42525 [38:44<37:12,  9.90it/s]

 48%|█████████████████▎                  | 20434/42525 [38:45<43:46,  8.41it/s]

 48%|█████████████████▎                  | 20438/42525 [38:45<38:41,  9.52it/s]

 48%|█████████████████▎                  | 20440/42525 [38:45<38:42,  9.51it/s]

 48%|█████████████████▎                  | 20442/42525 [38:45<42:39,  8.63it/s]

 48%|█████████████████▎                  | 20444/42525 [38:46<42:20,  8.69it/s]

 48%|█████████████████▎                  | 20445/42525 [38:46<45:48,  8.03it/s]

 48%|█████████████████▎                  | 20447/42525 [38:46<45:30,  8.08it/s]

 48%|█████████████████▎                  | 20450/42525 [38:46<43:54,  8.38it/s]

 48%|█████████████████▎                  | 20454/42525 [38:47<39:16,  9.37it/s]

 48%|█████████████████▎                  | 20458/42525 [38:47<37:43,  9.75it/s]

 48%|█████████████████▎                  | 20460/42525 [38:47<40:03,  9.18it/s]

 48%|█████████████████▎                  | 20464/42525 [38:48<37:23,  9.83it/s]

 48%|█████████████████▎                  | 20468/42525 [38:48<36:51,  9.97it/s]

 48%|█████████████████▎                  | 20470/42525 [38:48<38:16,  9.60it/s]

 48%|█████████████████▎                  | 20474/42525 [38:49<38:48,  9.47it/s]

 48%|█████████████████▎                  | 20478/42525 [38:49<37:54,  9.69it/s]

 48%|█████████████████▎                  | 20482/42525 [38:50<36:36, 10.04it/s]

 48%|█████████████████▎                  | 20486/42525 [38:50<36:30, 10.06it/s]

 48%|█████████████████▎                  | 20490/42525 [38:50<37:58,  9.67it/s]

 48%|█████████████████▎                  | 20494/42525 [38:51<37:00,  9.92it/s]

 48%|█████████████████▎                  | 20498/42525 [38:51<36:26, 10.08it/s]

 48%|█████████████████▎                  | 20502/42525 [38:52<37:45,  9.72it/s]

 48%|█████████████████▎                  | 20504/42525 [38:52<36:50,  9.96it/s]

 48%|█████████████████▎                  | 20508/42525 [38:52<36:52,  9.95it/s]

 48%|█████████████████▎                  | 20511/42525 [38:53<37:37,  9.75it/s]

 48%|█████████████████▎                  | 20513/42525 [38:53<44:05,  8.32it/s]

 48%|█████████████████▎                  | 20514/42525 [38:53<42:29,  8.63it/s]

 48%|█████████████████▎                  | 20517/42525 [38:53<44:07,  8.31it/s]

 48%|█████████████████▎                  | 20519/42525 [38:54<44:02,  8.33it/s]

 48%|█████████████████▎                  | 20521/42525 [38:54<47:07,  7.78it/s]

 48%|█████████████████▎                  | 20524/42525 [38:54<43:25,  8.44it/s]

 48%|█████████████████▍                  | 20527/42525 [38:55<40:19,  9.09it/s]

 48%|█████████████████▍                  | 20529/42525 [38:55<45:19,  8.09it/s]

 48%|█████████████████▍                  | 20531/42525 [38:55<46:10,  7.94it/s]

 48%|█████████████████▍                  | 20533/42525 [38:55<46:46,  7.84it/s]

 48%|█████████████████▍                  | 20536/42525 [38:56<41:16,  8.88it/s]

 48%|█████████████████▍                  | 20538/42525 [38:56<44:16,  8.28it/s]

 48%|█████████████████▍                  | 20540/42525 [38:56<42:59,  8.52it/s]

 48%|█████████████████▍                  | 20543/42525 [38:56<39:07,  9.36it/s]

 48%|█████████████████▍                  | 20544/42525 [38:57<42:48,  8.56it/s]

 48%|█████████████████▍                  | 20548/42525 [38:57<40:41,  9.00it/s]

 48%|█████████████████▍                  | 20552/42525 [38:57<39:56,  9.17it/s]

 48%|█████████████████▍                  | 20555/42525 [38:58<38:42,  9.46it/s]

 48%|█████████████████▍                  | 20557/42525 [38:58<40:18,  9.08it/s]

 48%|█████████████████▍                  | 20560/42525 [38:58<38:47,  9.44it/s]

 48%|█████████████████▍                  | 20563/42525 [38:59<41:06,  8.90it/s]

 48%|█████████████████▍                  | 20566/42525 [38:59<38:51,  9.42it/s]

 48%|█████████████████▍                  | 20569/42525 [38:59<44:11,  8.28it/s]

 48%|█████████████████▍                  | 20571/42525 [39:00<42:22,  8.64it/s]

 48%|█████████████████▍                  | 20573/42525 [39:00<43:08,  8.48it/s]

 48%|█████████████████▍                  | 20575/42525 [39:00<44:31,  8.22it/s]

 48%|█████████████████▍                  | 20576/42525 [39:00<43:55,  8.33it/s]

 48%|█████████████████▍                  | 20578/42525 [39:00<44:30,  8.22it/s]

 48%|█████████████████▍                  | 20580/42525 [39:01<44:41,  8.18it/s]

 48%|█████████████████▍                  | 20582/42525 [39:01<41:59,  8.71it/s]

 48%|█████████████████▍                  | 20585/42525 [39:01<40:21,  9.06it/s]

 48%|█████████████████▍                  | 20587/42525 [39:01<41:45,  8.76it/s]

 48%|█████████████████▍                  | 20589/42525 [39:02<41:56,  8.72it/s]

 48%|█████████████████▍                  | 20591/42525 [39:02<41:16,  8.86it/s]

 48%|█████████████████▍                  | 20595/42525 [39:02<37:50,  9.66it/s]

 48%|█████████████████▍                  | 20597/42525 [39:02<38:59,  9.37it/s]

 48%|█████████████████▍                  | 20600/42525 [39:03<39:42,  9.20it/s]

 48%|█████████████████▍                  | 20603/42525 [39:03<37:40,  9.70it/s]

 48%|█████████████████▍                  | 20605/42525 [39:03<41:22,  8.83it/s]

 48%|█████████████████▍                  | 20608/42525 [39:04<42:40,  8.56it/s]

 48%|█████████████████▍                  | 20610/42525 [39:04<44:27,  8.22it/s]

 48%|█████████████████▍                  | 20613/42525 [39:04<39:50,  9.17it/s]

 48%|█████████████████▍                  | 20616/42525 [39:05<38:50,  9.40it/s]

 48%|█████████████████▍                  | 20618/42525 [39:05<42:27,  8.60it/s]

 48%|█████████████████▍                  | 20619/42525 [39:05<43:55,  8.31it/s]

 48%|█████████████████▍                  | 20621/42525 [39:05<41:33,  8.78it/s]

 49%|█████████████████▍                  | 20625/42525 [39:06<38:25,  9.50it/s]

 49%|█████████████████▍                  | 20628/42525 [39:06<37:35,  9.71it/s]

 49%|█████████████████▍                  | 20631/42525 [39:06<41:44,  8.74it/s]

 49%|█████████████████▍                  | 20634/42525 [39:07<42:43,  8.54it/s]

 49%|█████████████████▍                  | 20637/42525 [39:07<41:21,  8.82it/s]

 49%|█████████████████▍                  | 20638/42525 [39:07<40:25,  9.02it/s]

 49%|█████████████████▍                  | 20641/42525 [39:07<42:30,  8.58it/s]

 49%|█████████████████▍                  | 20642/42525 [39:08<42:34,  8.57it/s]

 49%|█████████████████▍                  | 20646/42525 [39:08<38:44,  9.41it/s]

 49%|█████████████████▍                  | 20648/42525 [39:08<37:36,  9.70it/s]

 49%|█████████████████▍                  | 20650/42525 [39:08<39:29,  9.23it/s]

 49%|█████████████████▍                  | 20652/42525 [39:09<39:36,  9.20it/s]

 49%|█████████████████▍                  | 20655/42525 [39:09<38:53,  9.37it/s]

 49%|█████████████████▍                  | 20657/42525 [39:09<41:45,  8.73it/s]

 49%|█████████████████▍                  | 20659/42525 [39:09<40:46,  8.94it/s]

 49%|█████████████████▍                  | 20661/42525 [39:10<38:17,  9.52it/s]

 49%|█████████████████▍                  | 20664/42525 [39:10<38:12,  9.53it/s]

 49%|█████████████████▍                  | 20666/42525 [39:10<42:22,  8.60it/s]

 49%|█████████████████▍                  | 20669/42525 [39:10<40:45,  8.94it/s]

 49%|█████████████████▍                  | 20671/42525 [39:11<42:05,  8.65it/s]

 49%|█████████████████▌                  | 20675/42525 [39:11<40:01,  9.10it/s]

 49%|█████████████████▌                  | 20678/42525 [39:11<41:36,  8.75it/s]

 49%|█████████████████▌                  | 20681/42525 [39:12<40:01,  9.10it/s]

 49%|█████████████████▌                  | 20684/42525 [39:12<40:25,  9.00it/s]

 49%|█████████████████▌                  | 20687/42525 [39:12<40:35,  8.97it/s]

 49%|█████████████████▌                  | 20689/42525 [39:13<40:09,  9.06it/s]

 49%|█████████████████▌                  | 20691/42525 [39:13<42:07,  8.64it/s]

 49%|█████████████████▌                  | 20694/42525 [39:13<40:50,  8.91it/s]

 49%|█████████████████▌                  | 20697/42525 [39:14<39:24,  9.23it/s]

 49%|█████████████████▌                  | 20700/42525 [39:14<39:30,  9.21it/s]

 49%|█████████████████▌                  | 20702/42525 [39:14<40:16,  9.03it/s]

 49%|█████████████████▌                  | 20704/42525 [39:14<39:17,  9.26it/s]

 49%|█████████████████▌                  | 20705/42525 [39:14<39:48,  9.14it/s]

 49%|█████████████████▌                  | 20707/42525 [39:15<38:41,  9.40it/s]

 49%|█████████████████▌                  | 20710/42525 [39:15<40:22,  9.00it/s]

 49%|█████████████████▌                  | 20712/42525 [39:15<39:20,  9.24it/s]

 49%|█████████████████▌                  | 20715/42525 [39:16<39:30,  9.20it/s]

 49%|█████████████████▌                  | 20718/42525 [39:16<39:13,  9.27it/s]

 49%|█████████████████▌                  | 20719/42525 [39:16<39:03,  9.30it/s]

 49%|█████████████████▌                  | 20722/42525 [39:16<42:26,  8.56it/s]

 49%|█████████████████▌                  | 20726/42525 [39:17<39:06,  9.29it/s]

 49%|█████████████████▌                  | 20730/42525 [39:17<37:56,  9.57it/s]

 49%|█████████████████▌                  | 20732/42525 [39:17<40:02,  9.07it/s]

 49%|█████████████████▌                  | 20733/42525 [39:18<43:14,  8.40it/s]

 49%|█████████████████▌                  | 20737/42525 [39:18<39:34,  9.18it/s]

 49%|█████████████████▌                  | 20741/42525 [39:18<36:50,  9.85it/s]

 49%|█████████████████▌                  | 20743/42525 [39:19<37:59,  9.55it/s]

 49%|█████████████████▌                  | 20746/42525 [39:19<42:34,  8.53it/s]

 49%|█████████████████▌                  | 20749/42525 [39:19<40:41,  8.92it/s]

 49%|█████████████████▌                  | 20750/42525 [39:19<43:30,  8.34it/s]

 49%|█████████████████▌                  | 20754/42525 [39:20<39:06,  9.28it/s]

 49%|█████████████████▌                  | 20757/42525 [39:20<39:12,  9.25it/s]

 49%|█████████████████▌                  | 20760/42525 [39:20<39:05,  9.28it/s]

 49%|█████████████████▌                  | 20762/42525 [39:21<40:40,  8.92it/s]

 49%|█████████████████▌                  | 20765/42525 [39:21<39:21,  9.21it/s]

 49%|█████████████████▌                  | 20767/42525 [39:21<37:39,  9.63it/s]

 49%|█████████████████▌                  | 20771/42525 [39:22<37:58,  9.55it/s]

 49%|█████████████████▌                  | 20774/42525 [39:22<38:56,  9.31it/s]

 49%|█████████████████▌                  | 20776/42525 [39:22<41:22,  8.76it/s]

 49%|█████████████████▌                  | 20777/42525 [39:22<41:16,  8.78it/s]

 49%|█████████████████▌                  | 20779/42525 [39:23<39:44,  9.12it/s]

 49%|█████████████████▌                  | 20782/42525 [39:23<42:06,  8.60it/s]

 49%|█████████████████▌                  | 20783/42525 [39:23<41:43,  8.69it/s]

 49%|█████████████████▌                  | 20786/42525 [39:23<41:36,  8.71it/s]

 49%|█████████████████▌                  | 20789/42525 [39:24<39:03,  9.27it/s]

 49%|█████████████████▌                  | 20791/42525 [39:24<38:37,  9.38it/s]

 49%|█████████████████▌                  | 20795/42525 [39:24<38:44,  9.35it/s]

 49%|█████████████████▌                  | 20798/42525 [39:25<37:58,  9.53it/s]

 49%|█████████████████▌                  | 20801/42525 [39:25<37:20,  9.70it/s]

 49%|█████████████████▌                  | 20804/42525 [39:25<36:51,  9.82it/s]

 49%|█████████████████▌                  | 20806/42525 [39:25<37:14,  9.72it/s]

 49%|█████████████████▌                  | 20810/42525 [39:26<36:04, 10.03it/s]

 49%|█████████████████▌                  | 20813/42525 [39:26<36:15,  9.98it/s]

 49%|█████████████████▌                  | 20817/42525 [39:27<35:47, 10.11it/s]

 49%|█████████████████▋                  | 20820/42525 [39:27<41:20,  8.75it/s]

 49%|█████████████████▋                  | 20822/42525 [39:27<40:41,  8.89it/s]

 49%|█████████████████▋                  | 20825/42525 [39:28<38:54,  9.30it/s]

 49%|█████████████████▋                  | 20827/42525 [39:28<39:51,  9.07it/s]

 49%|█████████████████▋                  | 20830/42525 [39:28<42:03,  8.60it/s]

 49%|█████████████████▋                  | 20834/42525 [39:28<39:10,  9.23it/s]

 49%|█████████████████▋                  | 20836/42525 [39:29<43:03,  8.40it/s]

 49%|█████████████████▋                  | 20838/42525 [39:29<46:36,  7.76it/s]

 49%|█████████████████▋                  | 20840/42525 [39:29<46:20,  7.80it/s]

 49%|█████████████████▋                  | 20841/42525 [39:29<43:38,  8.28it/s]

 49%|█████████████████▋                  | 20844/42525 [39:30<44:17,  8.16it/s]

 49%|█████████████████▋                  | 20848/42525 [39:30<38:40,  9.34it/s]

 49%|█████████████████▋                  | 20852/42525 [39:31<37:22,  9.66it/s]

 49%|█████████████████▋                  | 20854/42525 [39:31<43:21,  8.33it/s]

 49%|█████████████████▋                  | 20856/42525 [39:31<41:35,  8.68it/s]

 49%|█████████████████▋                  | 20860/42525 [39:32<38:37,  9.35it/s]

 49%|█████████████████▋                  | 20862/42525 [39:32<41:43,  8.65it/s]

 49%|█████████████████▋                  | 20864/42525 [39:32<41:03,  8.79it/s]

 49%|█████████████████▋                  | 20866/42525 [39:32<42:14,  8.54it/s]

 49%|█████████████████▋                  | 20870/42525 [39:33<38:23,  9.40it/s]

 49%|█████████████████▋                  | 20872/42525 [39:33<37:19,  9.67it/s]

 49%|█████████████████▋                  | 20876/42525 [39:33<36:25,  9.90it/s]

 49%|█████████████████▋                  | 20878/42525 [39:33<35:47, 10.08it/s]

 49%|█████████████████▋                  | 20880/42525 [39:34<37:35,  9.59it/s]

 49%|█████████████████▋                  | 20882/42525 [39:34<38:07,  9.46it/s]

 49%|█████████████████▋                  | 20886/42525 [39:34<37:33,  9.60it/s]

 49%|█████████████████▋                  | 20888/42525 [39:35<42:11,  8.55it/s]

 49%|█████████████████▋                  | 20891/42525 [39:35<39:21,  9.16it/s]

 49%|█████████████████▋                  | 20893/42525 [39:35<39:35,  9.11it/s]

 49%|█████████████████▋                  | 20895/42525 [39:35<38:36,  9.34it/s]

 49%|█████████████████▋                  | 20898/42525 [39:36<38:37,  9.33it/s]

 49%|█████████████████▋                  | 20900/42525 [39:36<41:31,  8.68it/s]

 49%|█████████████████▋                  | 20903/42525 [39:36<38:39,  9.32it/s]

 49%|█████████████████▋                  | 20905/42525 [39:36<39:44,  9.07it/s]

 49%|█████████████████▋                  | 20908/42525 [39:37<41:27,  8.69it/s]

 49%|█████████████████▋                  | 20912/42525 [39:37<37:03,  9.72it/s]

 49%|█████████████████▋                  | 20915/42525 [39:37<37:23,  9.63it/s]

 49%|█████████████████▋                  | 20918/42525 [39:38<36:54,  9.76it/s]

 49%|█████████████████▋                  | 20921/42525 [39:38<37:22,  9.63it/s]

 49%|█████████████████▋                  | 20924/42525 [39:38<36:36,  9.83it/s]

 49%|█████████████████▋                  | 20925/42525 [39:38<39:10,  9.19it/s]

 49%|█████████████████▋                  | 20929/42525 [39:39<38:51,  9.26it/s]

 49%|█████████████████▋                  | 20932/42525 [39:39<37:46,  9.53it/s]

 49%|█████████████████▋                  | 20933/42525 [39:39<40:56,  8.79it/s]

 49%|█████████████████▋                  | 20937/42525 [39:40<39:18,  9.15it/s]

 49%|█████████████████▋                  | 20939/42525 [39:40<39:12,  9.18it/s]

 49%|█████████████████▋                  | 20941/42525 [39:40<40:41,  8.84it/s]

 49%|█████████████████▋                  | 20943/42525 [39:41<41:16,  8.72it/s]

 49%|█████████████████▋                  | 20946/42525 [39:41<38:47,  9.27it/s]

 49%|█████████████████▋                  | 20949/42525 [39:41<38:46,  9.27it/s]

 49%|█████████████████▋                  | 20953/42525 [39:42<36:34,  9.83it/s]

 49%|█████████████████▋                  | 20957/42525 [39:42<35:28, 10.13it/s]

 49%|█████████████████▋                  | 20959/42525 [39:42<35:09, 10.22it/s]

 49%|█████████████████▋                  | 20962/42525 [39:42<38:07,  9.43it/s]

 49%|█████████████████▋                  | 20965/42525 [39:43<39:57,  8.99it/s]

 49%|█████████████████▋                  | 20967/42525 [39:43<39:51,  9.02it/s]

 49%|█████████████████▊                  | 20970/42525 [39:43<37:49,  9.50it/s]

 49%|█████████████████▊                  | 20973/42525 [39:44<40:11,  8.94it/s]

 49%|█████████████████▊                  | 20977/42525 [39:44<36:46,  9.77it/s]

 49%|█████████████████▊                  | 20980/42525 [39:44<36:52,  9.74it/s]

 49%|█████████████████▊                  | 20982/42525 [39:45<40:46,  8.80it/s]

 49%|█████████████████▊                  | 20985/42525 [39:45<38:32,  9.32it/s]

 49%|█████████████████▊                  | 20988/42525 [39:45<37:41,  9.52it/s]

 49%|█████████████████▊                  | 20990/42525 [39:45<41:22,  8.67it/s]

 49%|█████████████████▊                  | 20992/42525 [39:46<38:29,  9.33it/s]

 49%|█████████████████▊                  | 20995/42525 [39:46<38:31,  9.31it/s]

 49%|█████████████████▊                  | 20999/42525 [39:46<36:20,  9.87it/s]

 49%|█████████████████▊                  | 21001/42525 [39:47<39:52,  9.00it/s]

 49%|█████████████████▊                  | 21004/42525 [39:47<38:52,  9.23it/s]

 49%|█████████████████▊                  | 21007/42525 [39:47<41:17,  8.68it/s]

 49%|█████████████████▊                  | 21010/42525 [39:48<41:49,  8.57it/s]

 49%|█████████████████▊                  | 21014/42525 [39:48<38:05,  9.41it/s]

 49%|█████████████████▊                  | 21017/42525 [39:48<36:37,  9.79it/s]

 49%|█████████████████▊                  | 21019/42525 [39:49<35:41, 10.04it/s]

 49%|█████████████████▊                  | 21021/42525 [39:49<38:29,  9.31it/s]

 49%|█████████████████▊                  | 21025/42525 [39:49<38:24,  9.33it/s]

 49%|█████████████████▊                  | 21027/42525 [39:49<41:35,  8.61it/s]

 49%|█████████████████▊                  | 21029/42525 [39:50<46:24,  7.72it/s]

 49%|█████████████████▊                  | 21031/42525 [39:50<41:23,  8.65it/s]

 49%|█████████████████▊                  | 21035/42525 [39:50<39:27,  9.08it/s]

 49%|█████████████████▊                  | 21037/42525 [39:51<39:01,  9.18it/s]

 49%|█████████████████▊                  | 21040/42525 [39:51<37:11,  9.63it/s]

 49%|█████████████████▊                  | 21041/42525 [39:51<37:58,  9.43it/s]

 49%|█████████████████▊                  | 21044/42525 [39:51<40:22,  8.87it/s]

 49%|█████████████████▊                  | 21046/42525 [39:52<37:54,  9.45it/s]

 49%|█████████████████▊                  | 21049/42525 [39:52<37:09,  9.63it/s]

 50%|█████████████████▊                  | 21052/42525 [39:52<36:06,  9.91it/s]

 50%|█████████████████▊                  | 21055/42525 [39:53<38:39,  9.26it/s]

 50%|█████████████████▊                  | 21057/42525 [39:53<37:17,  9.59it/s]

 50%|█████████████████▊                  | 21061/42525 [39:53<38:20,  9.33it/s]

 50%|█████████████████▊                  | 21063/42525 [39:53<37:07,  9.63it/s]

 50%|█████████████████▊                  | 21067/42525 [39:54<36:17,  9.85it/s]

 50%|█████████████████▊                  | 21069/42525 [39:54<38:11,  9.36it/s]

 50%|█████████████████▊                  | 21070/42525 [39:54<40:00,  8.94it/s]

 50%|█████████████████▊                  | 21073/42525 [39:54<43:31,  8.21it/s]

 50%|█████████████████▊                  | 21075/42525 [39:55<39:56,  8.95it/s]

 50%|█████████████████▊                  | 21078/42525 [39:55<43:14,  8.27it/s]

 50%|█████████████████▊                  | 21081/42525 [39:55<40:19,  8.86it/s]

 50%|█████████████████▊                  | 21085/42525 [39:56<37:10,  9.61it/s]

 50%|█████████████████▊                  | 21088/42525 [39:56<40:08,  8.90it/s]

 50%|█████████████████▊                  | 21090/42525 [39:56<42:17,  8.45it/s]

 50%|█████████████████▊                  | 21093/42525 [39:57<39:08,  9.13it/s]

 50%|█████████████████▊                  | 21096/42525 [39:57<39:59,  8.93it/s]

 50%|█████████████████▊                  | 21098/42525 [39:57<41:42,  8.56it/s]

 50%|█████████████████▊                  | 21101/42525 [39:58<40:28,  8.82it/s]

 50%|█████████████████▊                  | 21103/42525 [39:58<40:18,  8.86it/s]

 50%|█████████████████▊                  | 21105/42525 [39:58<41:35,  8.58it/s]

 50%|█████████████████▊                  | 21108/42525 [39:58<37:40,  9.47it/s]

 50%|█████████████████▊                  | 21110/42525 [39:59<39:23,  9.06it/s]

 50%|█████████████████▊                  | 21112/42525 [39:59<39:13,  9.10it/s]

 50%|█████████████████▊                  | 21113/42525 [39:59<38:44,  9.21it/s]

 50%|█████████████████▉                  | 21117/42525 [39:59<37:06,  9.62it/s]

 50%|█████████████████▉                  | 21121/42525 [40:00<35:31, 10.04it/s]

 50%|█████████████████▉                  | 21123/42525 [40:00<35:40, 10.00it/s]

 50%|█████████████████▉                  | 21127/42525 [40:00<35:31, 10.04it/s]

 50%|█████████████████▉                  | 21129/42525 [40:01<35:09, 10.14it/s]

 50%|█████████████████▉                  | 21132/42525 [40:01<41:11,  8.65it/s]

 50%|█████████████████▉                  | 21134/42525 [40:01<38:59,  9.14it/s]

 50%|█████████████████▉                  | 21136/42525 [40:01<38:33,  9.25it/s]

 50%|█████████████████▉                  | 21140/42525 [40:02<37:51,  9.41it/s]

 50%|█████████████████▉                  | 21143/42525 [40:02<36:34,  9.74it/s]

 50%|█████████████████▉                  | 21146/42525 [40:02<37:59,  9.38it/s]

 50%|█████████████████▉                  | 21149/42525 [40:03<37:32,  9.49it/s]

 50%|█████████████████▉                  | 21151/42525 [40:03<39:52,  8.93it/s]

 50%|█████████████████▉                  | 21154/42525 [40:03<43:36,  8.17it/s]

 50%|█████████████████▉                  | 21155/42525 [40:03<41:51,  8.51it/s]

 50%|█████████████████▉                  | 21158/42525 [40:04<43:56,  8.10it/s]

 50%|█████████████████▉                  | 21159/42525 [40:04<46:00,  7.74it/s]

 50%|█████████████████▉                  | 21161/42525 [40:04<42:00,  8.48it/s]

 50%|█████████████████▉                  | 21164/42525 [40:05<42:49,  8.31it/s]

 50%|█████████████████▉                  | 21167/42525 [40:05<39:19,  9.05it/s]

 50%|█████████████████▉                  | 21169/42525 [40:05<40:57,  8.69it/s]

 50%|█████████████████▉                  | 21171/42525 [40:05<38:22,  9.28it/s]

 50%|█████████████████▉                  | 21175/42525 [40:06<36:54,  9.64it/s]

 50%|█████████████████▉                  | 21177/42525 [40:06<37:43,  9.43it/s]

 50%|█████████████████▉                  | 21179/42525 [40:06<37:40,  9.44it/s]

 50%|█████████████████▉                  | 21182/42525 [40:06<36:56,  9.63it/s]

 50%|█████████████████▉                  | 21185/42525 [40:07<36:18,  9.80it/s]

 50%|█████████████████▉                  | 21187/42525 [40:07<35:24, 10.04it/s]

 50%|█████████████████▉                  | 21191/42525 [40:07<36:52,  9.64it/s]

 50%|█████████████████▉                  | 21193/42525 [40:08<36:01,  9.87it/s]

 50%|█████████████████▉                  | 21197/42525 [40:08<36:28,  9.74it/s]

 50%|█████████████████▉                  | 21200/42525 [40:08<35:59,  9.88it/s]

 50%|█████████████████▉                  | 21202/42525 [40:09<42:29,  8.37it/s]

 50%|█████████████████▉                  | 21204/42525 [40:09<45:02,  7.89it/s]

 50%|█████████████████▉                  | 21205/42525 [40:09<43:39,  8.14it/s]

 50%|█████████████████▉                  | 21209/42525 [40:09<39:00,  9.11it/s]

 50%|█████████████████▉                  | 21211/42525 [40:10<37:11,  9.55it/s]

 50%|█████████████████▉                  | 21213/42525 [40:10<37:27,  9.48it/s]

 50%|█████████████████▉                  | 21216/42525 [40:10<42:06,  8.43it/s]

 50%|█████████████████▉                  | 21219/42525 [40:11<40:50,  8.70it/s]

 50%|█████████████████▉                  | 21222/42525 [40:11<38:53,  9.13it/s]

 50%|█████████████████▉                  | 21226/42525 [40:11<36:41,  9.68it/s]

 50%|█████████████████▉                  | 21228/42525 [40:11<39:57,  8.88it/s]

 50%|█████████████████▉                  | 21231/42525 [40:12<39:34,  8.97it/s]

 50%|█████████████████▉                  | 21233/42525 [40:12<38:57,  9.11it/s]

 50%|█████████████████▉                  | 21236/42525 [40:12<38:36,  9.19it/s]

 50%|█████████████████▉                  | 21237/42525 [40:13<41:55,  8.46it/s]

 50%|█████████████████▉                  | 21240/42525 [40:13<43:03,  8.24it/s]

 50%|█████████████████▉                  | 21243/42525 [40:13<40:37,  8.73it/s]

 50%|█████████████████▉                  | 21246/42525 [40:14<40:15,  8.81it/s]

 50%|█████████████████▉                  | 21249/42525 [40:14<39:38,  8.94it/s]

 50%|█████████████████▉                  | 21251/42525 [40:14<39:18,  9.02it/s]

 50%|█████████████████▉                  | 21255/42525 [40:14<35:58,  9.85it/s]

 50%|█████████████████▉                  | 21258/42525 [40:15<36:19,  9.76it/s]

 50%|█████████████████▉                  | 21260/42525 [40:15<40:24,  8.77it/s]

 50%|██████████████████                  | 21263/42525 [40:15<39:31,  8.97it/s]

 50%|██████████████████                  | 21266/42525 [40:16<38:26,  9.22it/s]

 50%|██████████████████                  | 21268/42525 [40:16<43:04,  8.23it/s]

 50%|██████████████████                  | 21270/42525 [40:16<42:20,  8.37it/s]

 50%|██████████████████                  | 21272/42525 [40:16<38:55,  9.10it/s]

 50%|██████████████████                  | 21275/42525 [40:17<40:52,  8.67it/s]

 50%|██████████████████                  | 21277/42525 [40:17<45:10,  7.84it/s]

 50%|██████████████████                  | 21278/42525 [40:17<43:25,  8.16it/s]

 50%|██████████████████                  | 21281/42525 [40:17<43:00,  8.23it/s]

 50%|██████████████████                  | 21283/42525 [40:18<45:01,  7.86it/s]

 50%|██████████████████                  | 21286/42525 [40:18<38:47,  9.13it/s]

 50%|██████████████████                  | 21289/42525 [40:18<38:29,  9.20it/s]

 50%|██████████████████                  | 21292/42525 [40:19<37:36,  9.41it/s]

 50%|██████████████████                  | 21294/42525 [40:19<37:38,  9.40it/s]

 50%|██████████████████                  | 21296/42525 [40:19<39:19,  9.00it/s]

 50%|██████████████████                  | 21298/42525 [40:19<46:02,  7.69it/s]

 50%|██████████████████                  | 21299/42525 [40:20<47:49,  7.40it/s]

 50%|██████████████████                  | 21302/42525 [40:20<44:41,  7.91it/s]

 50%|██████████████████                  | 21305/42525 [40:20<41:22,  8.55it/s]

 50%|██████████████████                  | 21308/42525 [40:21<38:55,  9.08it/s]

 50%|██████████████████                  | 21310/42525 [40:21<38:21,  9.22it/s]

 50%|██████████████████                  | 21312/42525 [40:21<41:46,  8.46it/s]

 50%|██████████████████                  | 21315/42525 [40:21<37:31,  9.42it/s]

 50%|██████████████████                  | 21317/42525 [40:22<37:10,  9.51it/s]

 50%|██████████████████                  | 21318/42525 [40:22<40:48,  8.66it/s]

 50%|██████████████████                  | 21321/42525 [40:22<44:36,  7.92it/s]

 50%|██████████████████                  | 21323/42525 [40:22<42:22,  8.34it/s]

 50%|██████████████████                  | 21326/42525 [40:23<38:46,  9.11it/s]

 50%|██████████████████                  | 21329/42525 [40:23<38:49,  9.10it/s]

 50%|██████████████████                  | 21331/42525 [40:23<37:02,  9.53it/s]

 50%|██████████████████                  | 21335/42525 [40:24<35:32,  9.94it/s]

 50%|██████████████████                  | 21337/42525 [40:24<34:56, 10.11it/s]

 50%|██████████████████                  | 21341/42525 [40:24<35:10, 10.04it/s]

 50%|██████████████████                  | 21344/42525 [40:24<36:59,  9.54it/s]

 50%|██████████████████                  | 21348/42525 [40:25<35:03, 10.07it/s]

 50%|██████████████████                  | 21350/42525 [40:25<34:36, 10.20it/s]

 50%|██████████████████                  | 21353/42525 [40:25<38:53,  9.07it/s]

 50%|██████████████████                  | 21356/42525 [40:26<38:44,  9.11it/s]

 50%|██████████████████                  | 21359/42525 [40:26<38:41,  9.12it/s]

 50%|██████████████████                  | 21363/42525 [40:26<36:06,  9.77it/s]

 50%|██████████████████                  | 21365/42525 [40:27<35:26,  9.95it/s]

 50%|██████████████████                  | 21367/42525 [40:27<36:19,  9.71it/s]

 50%|██████████████████                  | 21371/42525 [40:27<36:35,  9.63it/s]

 50%|██████████████████                  | 21372/42525 [40:27<36:43,  9.60it/s]

 50%|██████████████████                  | 21374/42525 [40:28<36:40,  9.61it/s]

 50%|██████████████████                  | 21378/42525 [40:28<37:11,  9.48it/s]

 50%|██████████████████                  | 21379/42525 [40:28<37:19,  9.44it/s]

 50%|██████████████████                  | 21381/42525 [40:28<39:20,  8.96it/s]

 50%|██████████████████                  | 21385/42525 [40:29<38:34,  9.13it/s]

 50%|██████████████████                  | 21388/42525 [40:29<38:12,  9.22it/s]

 50%|██████████████████                  | 21390/42525 [40:29<41:12,  8.55it/s]

 50%|██████████████████                  | 21392/42525 [40:30<39:58,  8.81it/s]

 50%|██████████████████                  | 21395/42525 [40:30<37:21,  9.43it/s]

 50%|██████████████████                  | 21397/42525 [40:30<43:04,  8.18it/s]

 50%|██████████████████                  | 21399/42525 [40:30<39:32,  8.91it/s]

 50%|██████████████████                  | 21401/42525 [40:31<38:27,  9.15it/s]

 50%|██████████████████                  | 21404/42525 [40:31<38:16,  9.20it/s]

 50%|██████████████████                  | 21406/42525 [40:31<43:00,  8.18it/s]

 50%|██████████████████                  | 21409/42525 [40:32<42:21,  8.31it/s]

 50%|██████████████████▏                 | 21412/42525 [40:32<39:51,  8.83it/s]

 50%|██████████████████▏                 | 21414/42525 [40:32<41:38,  8.45it/s]

 50%|██████████████████▏                 | 21416/42525 [40:32<42:29,  8.28it/s]

 50%|██████████████████▏                 | 21419/42525 [40:33<42:37,  8.25it/s]

 50%|██████████████████▏                 | 21422/42525 [40:33<42:25,  8.29it/s]

 50%|██████████████████▏                 | 21424/42525 [40:33<39:14,  8.96it/s]

 50%|██████████████████▏                 | 21428/42525 [40:34<38:25,  9.15it/s]

 50%|██████████████████▏                 | 21430/42525 [40:34<37:18,  9.42it/s]

 50%|██████████████████▏                 | 21432/42525 [40:34<37:21,  9.41it/s]

 50%|██████████████████▏                 | 21434/42525 [40:34<39:07,  8.98it/s]

 50%|██████████████████▏                 | 21438/42525 [40:35<37:26,  9.39it/s]

 50%|██████████████████▏                 | 21441/42525 [40:35<36:15,  9.69it/s]

 50%|██████████████████▏                 | 21444/42525 [40:35<37:34,  9.35it/s]

 50%|██████████████████▏                 | 21446/42525 [40:36<42:03,  8.35it/s]

 50%|██████████████████▏                 | 21450/42525 [40:36<39:06,  8.98it/s]

 50%|██████████████████▏                 | 21452/42525 [40:36<38:38,  9.09it/s]

 50%|██████████████████▏                 | 21455/42525 [40:37<42:09,  8.33it/s]

 50%|██████████████████▏                 | 21459/42525 [40:37<37:23,  9.39it/s]

 50%|██████████████████▏                 | 21463/42525 [40:38<37:27,  9.37it/s]

 50%|██████████████████▏                 | 21467/42525 [40:38<37:03,  9.47it/s]

 50%|██████████████████▏                 | 21471/42525 [40:38<35:32,  9.87it/s]

 50%|██████████████████▏                 | 21473/42525 [40:39<35:07,  9.99it/s]

 51%|██████████████████▏                 | 21476/42525 [40:39<35:29,  9.89it/s]

 51%|██████████████████▏                 | 21479/42525 [40:39<35:55,  9.77it/s]

 51%|██████████████████▏                 | 21482/42525 [40:40<41:19,  8.49it/s]

 51%|██████████████████▏                 | 21484/42525 [40:40<40:02,  8.76it/s]

 51%|██████████████████▏                 | 21485/42525 [40:40<42:33,  8.24it/s]

 51%|██████████████████▏                 | 21488/42525 [40:40<40:23,  8.68it/s]

 51%|██████████████████▏                 | 21491/42525 [40:41<37:28,  9.35it/s]

 51%|██████████████████▏                 | 21494/42525 [40:41<36:24,  9.63it/s]

 51%|██████████████████▏                 | 21495/42525 [40:41<40:00,  8.76it/s]

 51%|██████████████████▏                 | 21499/42525 [40:41<37:02,  9.46it/s]

 51%|██████████████████▏                 | 21502/42525 [40:42<36:00,  9.73it/s]

 51%|██████████████████▏                 | 21504/42525 [40:42<40:20,  8.69it/s]

 51%|██████████████████▏                 | 21507/42525 [40:42<39:36,  8.84it/s]

 51%|██████████████████▏                 | 21510/42525 [40:43<38:46,  9.03it/s]

 51%|██████████████████▏                 | 21514/42525 [40:43<38:05,  9.19it/s]

 51%|██████████████████▏                 | 21518/42525 [40:44<35:50,  9.77it/s]

 51%|██████████████████▏                 | 21521/42525 [40:44<39:06,  8.95it/s]

 51%|██████████████████▏                 | 21523/42525 [40:44<41:11,  8.50it/s]

 51%|██████████████████▏                 | 21524/42525 [40:44<39:53,  8.77it/s]

 51%|██████████████████▏                 | 21527/42525 [40:45<41:30,  8.43it/s]

 51%|██████████████████▏                 | 21529/42525 [40:45<38:29,  9.09it/s]

 51%|██████████████████▏                 | 21532/42525 [40:45<39:52,  8.77it/s]

 51%|██████████████████▏                 | 21535/42525 [40:45<41:25,  8.45it/s]

 51%|██████████████████▏                 | 21538/42525 [40:46<37:47,  9.25it/s]

 51%|██████████████████▏                 | 21541/42525 [40:46<39:48,  8.79it/s]

 51%|██████████████████▏                 | 21544/42525 [40:46<37:20,  9.36it/s]

 51%|██████████████████▏                 | 21548/42525 [40:47<35:45,  9.78it/s]

 51%|██████████████████▏                 | 21550/42525 [40:47<40:13,  8.69it/s]

 51%|██████████████████▏                 | 21553/42525 [40:47<37:48,  9.24it/s]

 51%|██████████████████▏                 | 21555/42525 [40:48<36:04,  9.69it/s]

 51%|██████████████████▎                 | 21559/42525 [40:48<35:36,  9.82it/s]

 51%|██████████████████▎                 | 21562/42525 [40:48<38:15,  9.13it/s]

 51%|██████████████████▎                 | 21564/42525 [40:49<39:17,  8.89it/s]

 51%|██████████████████▎                 | 21566/42525 [40:49<40:43,  8.58it/s]

 51%|██████████████████▎                 | 21568/42525 [40:49<44:36,  7.83it/s]

 51%|██████████████████▎                 | 21572/42525 [40:49<37:35,  9.29it/s]

 51%|██████████████████▎                 | 21574/42525 [40:50<36:11,  9.65it/s]

 51%|██████████████████▎                 | 21577/42525 [40:50<38:41,  9.02it/s]

 51%|██████████████████▎                 | 21578/42525 [40:50<37:57,  9.20it/s]

 51%|██████████████████▎                 | 21580/42525 [40:50<39:38,  8.81it/s]

 51%|██████████████████▎                 | 21584/42525 [40:51<37:50,  9.22it/s]

 51%|██████████████████▎                 | 21587/42525 [40:51<39:40,  8.80it/s]

 51%|██████████████████▎                 | 21589/42525 [40:51<43:34,  8.01it/s]

 51%|██████████████████▎                 | 21590/42525 [40:52<42:46,  8.16it/s]

 51%|██████████████████▎                 | 21594/42525 [40:52<39:19,  8.87it/s]

 51%|██████████████████▎                 | 21597/42525 [40:52<40:13,  8.67it/s]

 51%|██████████████████▎                 | 21599/42525 [40:53<38:07,  9.15it/s]

 51%|██████████████████▎                 | 21602/42525 [40:53<39:28,  8.83it/s]

 51%|██████████████████▎                 | 21605/42525 [40:53<37:49,  9.22it/s]

 51%|██████████████████▎                 | 21609/42525 [40:54<35:41,  9.77it/s]

 51%|██████████████████▎                 | 21611/42525 [40:54<35:05,  9.93it/s]

 51%|██████████████████▎                 | 21615/42525 [40:54<34:48, 10.01it/s]

 51%|██████████████████▎                 | 21619/42525 [40:55<34:26, 10.12it/s]

 51%|██████████████████▎                 | 21623/42525 [40:55<35:32,  9.80it/s]

 51%|██████████████████▎                 | 21625/42525 [40:55<36:02,  9.67it/s]

 51%|██████████████████▎                 | 21628/42525 [40:56<39:07,  8.90it/s]

 51%|██████████████████▎                 | 21630/42525 [40:56<38:43,  8.99it/s]

 51%|██████████████████▎                 | 21632/42525 [40:56<44:49,  7.77it/s]

 51%|██████████████████▎                 | 21635/42525 [40:56<38:45,  8.98it/s]

 51%|██████████████████▎                 | 21639/42525 [40:57<35:47,  9.72it/s]

 51%|██████████████████▎                 | 21642/42525 [40:57<35:43,  9.74it/s]

 51%|██████████████████▎                 | 21645/42525 [40:57<34:55,  9.96it/s]

 51%|██████████████████▎                 | 21648/42525 [40:58<35:14,  9.87it/s]

 51%|██████████████████▎                 | 21652/42525 [40:58<34:51,  9.98it/s]

 51%|██████████████████▎                 | 21654/42525 [40:58<35:57,  9.67it/s]

 51%|██████████████████▎                 | 21657/42525 [40:59<38:32,  9.02it/s]

 51%|██████████████████▎                 | 21659/42525 [40:59<37:51,  9.19it/s]

 51%|██████████████████▎                 | 21662/42525 [40:59<36:08,  9.62it/s]

 51%|██████████████████▎                 | 21663/42525 [40:59<35:49,  9.70it/s]

 51%|██████████████████▎                 | 21666/42525 [41:00<39:15,  8.85it/s]

 51%|██████████████████▎                 | 21670/42525 [41:00<36:01,  9.65it/s]

 51%|██████████████████▎                 | 21674/42525 [41:00<36:46,  9.45it/s]

 51%|██████████████████▎                 | 21676/42525 [41:01<38:51,  8.94it/s]

 51%|██████████████████▎                 | 21678/42525 [41:01<38:57,  8.92it/s]

 51%|██████████████████▎                 | 21681/42525 [41:01<37:43,  9.21it/s]

 51%|██████████████████▎                 | 21683/42525 [41:01<39:39,  8.76it/s]

 51%|██████████████████▎                 | 21686/42525 [41:02<37:14,  9.33it/s]

 51%|██████████████████▎                 | 21689/42525 [41:02<35:55,  9.67it/s]

 51%|██████████████████▎                 | 21691/42525 [41:02<42:08,  8.24it/s]

 51%|██████████████████▎                 | 21694/42525 [41:03<37:48,  9.18it/s]

 51%|██████████████████▎                 | 21696/42525 [41:03<36:03,  9.63it/s]

 51%|██████████████████▎                 | 21699/42525 [41:03<38:11,  9.09it/s]

 51%|██████████████████▎                 | 21703/42525 [41:04<35:37,  9.74it/s]

 51%|██████████████████▍                 | 21706/42525 [41:04<36:38,  9.47it/s]

 51%|██████████████████▍                 | 21709/42525 [41:04<38:46,  8.95it/s]

 51%|██████████████████▍                 | 21711/42525 [41:05<41:36,  8.34it/s]

 51%|██████████████████▍                 | 21714/42525 [41:05<38:28,  9.02it/s]

 51%|██████████████████▍                 | 21717/42525 [41:05<35:49,  9.68it/s]

 51%|██████████████████▍                 | 21720/42525 [41:05<36:34,  9.48it/s]

 51%|██████████████████▍                 | 21723/42525 [41:06<36:20,  9.54it/s]

 51%|██████████████████▍                 | 21727/42525 [41:06<35:07,  9.87it/s]

 51%|██████████████████▍                 | 21730/42525 [41:07<35:29,  9.77it/s]

 51%|██████████████████▍                 | 21732/42525 [41:07<34:41,  9.99it/s]

 51%|██████████████████▍                 | 21736/42525 [41:07<36:01,  9.62it/s]

 51%|██████████████████▍                 | 21737/42525 [41:07<37:42,  9.19it/s]

 51%|██████████████████▍                 | 21740/42525 [41:08<38:47,  8.93it/s]

 51%|██████████████████▍                 | 21743/42525 [41:08<39:12,  8.83it/s]

 51%|██████████████████▍                 | 21745/42525 [41:08<37:13,  9.30it/s]

 51%|██████████████████▍                 | 21748/42525 [41:09<40:09,  8.62it/s]

 51%|██████████████████▍                 | 21750/42525 [41:09<43:36,  7.94it/s]

 51%|██████████████████▍                 | 21753/42525 [41:09<38:20,  9.03it/s]

 51%|██████████████████▍                 | 21756/42525 [41:09<37:47,  9.16it/s]

 51%|██████████████████▍                 | 21759/42525 [41:10<36:01,  9.61it/s]

 51%|██████████████████▍                 | 21763/42525 [41:10<34:39,  9.98it/s]

 51%|██████████████████▍                 | 21766/42525 [41:10<35:44,  9.68it/s]

 51%|██████████████████▍                 | 21769/42525 [41:11<35:44,  9.68it/s]

 51%|██████████████████▍                 | 21770/42525 [41:11<39:01,  8.86it/s]

 51%|██████████████████▍                 | 21773/42525 [41:11<38:05,  9.08it/s]

 51%|██████████████████▍                 | 21775/42525 [41:11<41:56,  8.25it/s]

 51%|██████████████████▍                 | 21777/42525 [41:12<41:48,  8.27it/s]

 51%|██████████████████▍                 | 21780/42525 [41:12<41:26,  8.34it/s]

 51%|██████████████████▍                 | 21784/42525 [41:12<36:26,  9.49it/s]

 51%|██████████████████▍                 | 21786/42525 [41:13<41:48,  8.27it/s]

 51%|██████████████████▍                 | 21789/42525 [41:13<37:35,  9.19it/s]

 51%|██████████████████▍                 | 21793/42525 [41:13<37:17,  9.26it/s]

 51%|██████████████████▍                 | 21797/42525 [41:14<36:11,  9.55it/s]

 51%|██████████████████▍                 | 21799/42525 [41:14<35:16,  9.79it/s]

 51%|██████████████████▍                 | 21803/42525 [41:14<34:36,  9.98it/s]

 51%|██████████████████▍                 | 21805/42525 [41:15<35:40,  9.68it/s]

 51%|██████████████████▍                 | 21809/42525 [41:15<34:40,  9.96it/s]

 51%|██████████████████▍                 | 21813/42525 [41:15<33:57, 10.16it/s]

 51%|██████████████████▍                 | 21815/42525 [41:16<33:46, 10.22it/s]

 51%|██████████████████▍                 | 21819/42525 [41:16<33:54, 10.18it/s]

 51%|██████████████████▍                 | 21821/42525 [41:16<34:04, 10.13it/s]

 51%|██████████████████▍                 | 21823/42525 [41:16<34:13, 10.08it/s]

 51%|██████████████████▍                 | 21826/42525 [41:17<38:17,  9.01it/s]

 51%|██████████████████▍                 | 21829/42525 [41:17<40:34,  8.50it/s]

 51%|██████████████████▍                 | 21833/42525 [41:18<36:12,  9.52it/s]

 51%|██████████████████▍                 | 21837/42525 [41:18<36:31,  9.44it/s]

 51%|██████████████████▍                 | 21840/42525 [41:18<37:09,  9.28it/s]

 51%|██████████████████▍                 | 21841/42525 [41:18<39:06,  8.82it/s]

 51%|██████████████████▍                 | 21844/42525 [41:19<37:53,  9.10it/s]

 51%|██████████████████▍                 | 21848/42525 [41:19<35:42,  9.65it/s]

 51%|██████████████████▍                 | 21852/42525 [41:20<36:13,  9.51it/s]

 51%|██████████████████▌                 | 21854/42525 [41:20<40:15,  8.56it/s]

 51%|██████████████████▌                 | 21856/42525 [41:20<39:13,  8.78it/s]

 51%|██████████████████▌                 | 21859/42525 [41:20<36:26,  9.45it/s]

 51%|██████████████████▌                 | 21861/42525 [41:21<40:02,  8.60it/s]

 51%|██████████████████▌                 | 21864/42525 [41:21<39:32,  8.71it/s]

 51%|██████████████████▌                 | 21866/42525 [41:21<37:12,  9.25it/s]

 51%|██████████████████▌                 | 21869/42525 [41:22<41:39,  8.27it/s]

 51%|██████████████████▌                 | 21872/42525 [41:22<39:35,  8.69it/s]

 51%|██████████████████▌                 | 21874/42525 [41:22<39:54,  8.62it/s]

 51%|██████████████████▌                 | 21876/42525 [41:22<40:27,  8.50it/s]

 51%|██████████████████▌                 | 21878/42525 [41:23<41:12,  8.35it/s]

 51%|██████████████████▌                 | 21879/42525 [41:23<39:16,  8.76it/s]

 51%|██████████████████▌                 | 21882/42525 [41:23<41:18,  8.33it/s]

 51%|██████████████████▌                 | 21886/42525 [41:24<36:18,  9.47it/s]

 51%|██████████████████▌                 | 21889/42525 [41:24<35:59,  9.56it/s]

 51%|██████████████████▌                 | 21892/42525 [41:24<35:10,  9.78it/s]

 51%|██████████████████▌                 | 21895/42525 [41:24<36:24,  9.44it/s]

 51%|██████████████████▌                 | 21897/42525 [41:25<35:36,  9.65it/s]

 51%|██████████████████▌                 | 21899/42525 [41:25<35:25,  9.70it/s]

 52%|██████████████████▌                 | 21901/42525 [41:25<36:07,  9.51it/s]

 52%|██████████████████▌                 | 21905/42525 [41:25<34:59,  9.82it/s]

 52%|██████████████████▌                 | 21909/42525 [41:26<34:09, 10.06it/s]

 52%|██████████████████▌                 | 21913/42525 [41:26<34:35,  9.93it/s]

 52%|██████████████████▌                 | 21917/42525 [41:27<34:34,  9.93it/s]

 52%|██████████████████▌                 | 21920/42525 [41:27<38:17,  8.97it/s]

 52%|██████████████████▌                 | 21923/42525 [41:27<36:39,  9.37it/s]

 52%|██████████████████▌                 | 21925/42525 [41:28<38:26,  8.93it/s]

 52%|██████████████████▌                 | 21927/42525 [41:28<39:44,  8.64it/s]

 52%|██████████████████▌                 | 21929/42525 [41:28<39:59,  8.59it/s]

 52%|██████████████████▌                 | 21933/42525 [41:28<36:13,  9.47it/s]

 52%|██████████████████▌                 | 21936/42525 [41:29<38:29,  8.91it/s]

 52%|██████████████████▌                 | 21938/42525 [41:29<41:52,  8.19it/s]

 52%|██████████████████▌                 | 21940/42525 [41:29<41:55,  8.18it/s]

 52%|██████████████████▌                 | 21944/42525 [41:30<39:09,  8.76it/s]

 52%|██████████████████▌                 | 21947/42525 [41:30<36:51,  9.30it/s]

 52%|██████████████████▌                 | 21949/42525 [41:30<39:37,  8.65it/s]

 52%|██████████████████▌                 | 21951/42525 [41:31<36:59,  9.27it/s]

 52%|██████████████████▌                 | 21954/42525 [41:31<38:45,  8.85it/s]

 52%|██████████████████▌                 | 21956/42525 [41:31<36:44,  9.33it/s]

 52%|██████████████████▌                 | 21959/42525 [41:31<37:00,  9.26it/s]

 52%|██████████████████▌                 | 21963/42525 [41:32<34:42,  9.87it/s]

 52%|██████████████████▌                 | 21966/42525 [41:32<37:43,  9.08it/s]

 52%|██████████████████▌                 | 21967/42525 [41:32<40:29,  8.46it/s]

 52%|██████████████████▌                 | 21970/42525 [41:33<43:30,  7.87it/s]

 52%|██████████████████▌                 | 21972/42525 [41:33<43:05,  7.95it/s]

 52%|██████████████████▌                 | 21975/42525 [41:33<39:12,  8.74it/s]

 52%|██████████████████▌                 | 21977/42525 [41:34<43:16,  7.91it/s]

 52%|██████████████████▌                 | 21979/42525 [41:34<42:18,  8.09it/s]

 52%|██████████████████▌                 | 21983/42525 [41:34<36:18,  9.43it/s]

 52%|██████████████████▌                 | 21986/42525 [41:34<35:30,  9.64it/s]

 52%|██████████████████▌                 | 21990/42525 [41:35<34:21,  9.96it/s]

 52%|██████████████████▌                 | 21993/42525 [41:35<35:57,  9.52it/s]

 52%|██████████████████▌                 | 21995/42525 [41:35<35:45,  9.57it/s]

 52%|██████████████████▌                 | 21997/42525 [41:36<36:06,  9.48it/s]

 52%|██████████████████▌                 | 21999/42525 [41:36<38:06,  8.98it/s]

 52%|██████████████████▋                 | 22001/42525 [41:36<44:09,  7.75it/s]

 52%|██████████████████▋                 | 22003/42525 [41:36<42:57,  7.96it/s]

 52%|██████████████████▋                 | 22005/42525 [41:37<38:40,  8.84it/s]

 52%|██████████████████▋                 | 22008/42525 [41:37<37:48,  9.04it/s]

 52%|██████████████████▋                 | 22010/42525 [41:37<43:46,  7.81it/s]

 52%|██████████████████▋                 | 22014/42525 [41:38<37:02,  9.23it/s]

 52%|██████████████████▋                 | 22016/42525 [41:38<38:17,  8.93it/s]

 52%|██████████████████▋                 | 22019/42525 [41:38<39:32,  8.64it/s]

 52%|██████████████████▋                 | 22022/42525 [41:39<40:19,  8.47it/s]

 52%|██████████████████▋                 | 22024/42525 [41:39<39:28,  8.66it/s]

 52%|██████████████████▋                 | 22026/42525 [41:39<39:04,  8.74it/s]

 52%|██████████████████▋                 | 22029/42525 [41:39<39:57,  8.55it/s]

 52%|██████████████████▋                 | 22030/42525 [41:39<39:28,  8.65it/s]

 52%|██████████████████▋                 | 22032/42525 [41:40<38:34,  8.85it/s]

 52%|██████████████████▋                 | 22035/42525 [41:40<42:02,  8.12it/s]

 52%|██████████████████▋                 | 22038/42525 [41:40<38:11,  8.94it/s]

 52%|██████████████████▋                 | 22040/42525 [41:41<35:43,  9.56it/s]

 52%|██████████████████▋                 | 22043/42525 [41:41<36:12,  9.43it/s]

 52%|██████████████████▋                 | 22045/42525 [41:41<42:54,  7.96it/s]

 52%|██████████████████▋                 | 22047/42525 [41:41<43:43,  7.81it/s]

 52%|██████████████████▋                 | 22050/42525 [41:42<41:21,  8.25it/s]

 52%|██████████████████▋                 | 22053/42525 [41:42<37:44,  9.04it/s]

 52%|██████████████████▋                 | 22056/42525 [41:42<38:51,  8.78it/s]

 52%|██████████████████▋                 | 22060/42525 [41:43<35:08,  9.70it/s]

 52%|██████████████████▋                 | 22063/42525 [41:43<34:48,  9.80it/s]

 52%|██████████████████▋                 | 22066/42525 [41:43<34:19,  9.94it/s]

 52%|██████████████████▋                 | 22068/42525 [41:44<38:18,  8.90it/s]

 52%|██████████████████▋                 | 22072/42525 [41:44<34:54,  9.76it/s]

 52%|██████████████████▋                 | 22075/42525 [41:44<34:30,  9.88it/s]

 52%|██████████████████▋                 | 22078/42525 [41:45<36:04,  9.45it/s]

 52%|██████████████████▋                 | 22081/42525 [41:45<34:47,  9.79it/s]

 52%|██████████████████▋                 | 22085/42525 [41:45<34:25,  9.90it/s]

 52%|██████████████████▋                 | 22087/42525 [41:46<38:00,  8.96it/s]

 52%|██████████████████▋                 | 22089/42525 [41:46<37:56,  8.98it/s]

 52%|██████████████████▋                 | 22092/42525 [41:46<37:48,  9.01it/s]

 52%|██████████████████▋                 | 22093/42525 [41:46<37:25,  9.10it/s]

 52%|██████████████████▋                 | 22096/42525 [41:47<41:59,  8.11it/s]

 52%|██████████████████▋                 | 22098/42525 [41:47<39:39,  8.58it/s]

 52%|██████████████████▋                 | 22101/42525 [41:47<37:57,  8.97it/s]

 52%|██████████████████▋                 | 22103/42525 [41:48<39:28,  8.62it/s]

 52%|██████████████████▋                 | 22106/42525 [41:48<36:47,  9.25it/s]

 52%|██████████████████▋                 | 22108/42525 [41:48<36:02,  9.44it/s]

 52%|██████████████████▋                 | 22111/42525 [41:48<36:40,  9.28it/s]

 52%|██████████████████▋                 | 22114/42525 [41:49<36:13,  9.39it/s]

 52%|██████████████████▋                 | 22117/42525 [41:49<35:21,  9.62it/s]

 52%|██████████████████▋                 | 22120/42525 [41:49<35:09,  9.68it/s]

 52%|██████████████████▋                 | 22121/42525 [41:49<38:23,  8.86it/s]

 52%|██████████████████▋                 | 22124/42525 [41:50<40:11,  8.46it/s]

 52%|██████████████████▋                 | 22127/42525 [41:50<36:59,  9.19it/s]

 52%|██████████████████▋                 | 22129/42525 [41:50<42:18,  8.04it/s]

 52%|██████████████████▋                 | 22132/42525 [41:51<37:37,  9.03it/s]

 52%|██████████████████▋                 | 22134/42525 [41:51<40:17,  8.44it/s]

 52%|██████████████████▋                 | 22136/42525 [41:51<41:45,  8.14it/s]

 52%|██████████████████▋                 | 22139/42525 [41:52<37:13,  9.13it/s]

 52%|██████████████████▋                 | 22141/42525 [41:52<35:27,  9.58it/s]

 52%|██████████████████▋                 | 22143/42525 [41:52<36:06,  9.41it/s]

 52%|██████████████████▋                 | 22147/42525 [41:52<36:23,  9.33it/s]

 52%|██████████████████▊                 | 22150/42525 [41:53<38:48,  8.75it/s]

 52%|██████████████████▊                 | 22152/42525 [41:53<37:03,  9.16it/s]

 52%|██████████████████▊                 | 22156/42525 [41:53<35:24,  9.59it/s]

 52%|██████████████████▊                 | 22158/42525 [41:54<38:26,  8.83it/s]

 52%|██████████████████▊                 | 22162/42525 [41:54<34:49,  9.75it/s]

 52%|██████████████████▊                 | 22166/42525 [41:54<33:49, 10.03it/s]

 52%|██████████████████▊                 | 22168/42525 [41:55<38:59,  8.70it/s]

 52%|██████████████████▊                 | 22170/42525 [41:55<40:55,  8.29it/s]

 52%|██████████████████▊                 | 22173/42525 [41:55<39:20,  8.62it/s]

 52%|██████████████████▊                 | 22175/42525 [41:55<41:57,  8.08it/s]

 52%|██████████████████▊                 | 22176/42525 [41:56<42:23,  8.00it/s]

 52%|██████████████████▊                 | 22178/42525 [41:56<42:07,  8.05it/s]

 52%|██████████████████▊                 | 22182/42525 [41:56<37:58,  8.93it/s]

 52%|██████████████████▊                 | 22184/42525 [41:56<36:09,  9.38it/s]

 52%|██████████████████▊                 | 22187/42525 [41:57<37:46,  8.97it/s]

 52%|██████████████████▊                 | 22188/42525 [41:57<40:18,  8.41it/s]

 52%|██████████████████▊                 | 22192/42525 [41:57<38:17,  8.85it/s]

 52%|██████████████████▊                 | 22194/42525 [41:58<39:36,  8.55it/s]

 52%|██████████████████▊                 | 22196/42525 [41:58<41:45,  8.11it/s]

 52%|██████████████████▊                 | 22200/42525 [41:58<36:24,  9.31it/s]

 52%|██████████████████▊                 | 22202/42525 [41:59<40:07,  8.44it/s]

 52%|██████████████████▊                 | 22204/42525 [41:59<40:58,  8.26it/s]

 52%|██████████████████▊                 | 22207/42525 [41:59<40:44,  8.31it/s]

 52%|██████████████████▊                 | 22209/42525 [41:59<42:19,  8.00it/s]

 52%|██████████████████▊                 | 22211/42525 [42:00<42:41,  7.93it/s]

 52%|██████████████████▊                 | 22214/42525 [42:00<39:29,  8.57it/s]

 52%|██████████████████▊                 | 22216/42525 [42:00<39:10,  8.64it/s]

 52%|██████████████████▊                 | 22220/42525 [42:01<36:13,  9.34it/s]

 52%|██████████████████▊                 | 22223/42525 [42:01<37:26,  9.04it/s]

 52%|██████████████████▊                 | 22225/42525 [42:01<40:24,  8.37it/s]

 52%|██████████████████▊                 | 22227/42525 [42:01<38:13,  8.85it/s]

 52%|██████████████████▊                 | 22229/42525 [42:02<40:43,  8.31it/s]

 52%|██████████████████▊                 | 22231/42525 [42:02<38:10,  8.86it/s]

 52%|██████████████████▊                 | 22233/42525 [42:02<37:45,  8.96it/s]

 52%|██████████████████▊                 | 22236/42525 [42:02<35:00,  9.66it/s]

 52%|██████████████████▊                 | 22239/42525 [42:03<35:51,  9.43it/s]

 52%|██████████████████▊                 | 22242/42525 [42:03<35:52,  9.42it/s]

 52%|██████████████████▊                 | 22244/42525 [42:03<35:44,  9.46it/s]

 52%|██████████████████▊                 | 22246/42525 [42:04<37:49,  8.93it/s]

 52%|██████████████████▊                 | 22249/42525 [42:04<39:48,  8.49it/s]

 52%|██████████████████▊                 | 22251/42525 [42:04<37:24,  9.03it/s]

 52%|██████████████████▊                 | 22255/42525 [42:05<36:13,  9.32it/s]

 52%|██████████████████▊                 | 22258/42525 [42:05<36:53,  9.15it/s]

 52%|██████████████████▊                 | 22259/42525 [42:05<37:33,  8.99it/s]

 52%|██████████████████▊                 | 22262/42525 [42:05<39:44,  8.50it/s]

 52%|██████████████████▊                 | 22266/42525 [42:06<35:55,  9.40it/s]

 52%|██████████████████▊                 | 22267/42525 [42:06<38:43,  8.72it/s]

 52%|██████████████████▊                 | 22271/42525 [42:06<35:36,  9.48it/s]

 52%|██████████████████▊                 | 22274/42525 [42:07<35:59,  9.38it/s]

 52%|██████████████████▊                 | 22275/42525 [42:07<36:44,  9.19it/s]

 52%|██████████████████▊                 | 22278/42525 [42:07<39:00,  8.65it/s]

 52%|██████████████████▊                 | 22279/42525 [42:07<38:06,  8.85it/s]

 52%|██████████████████▊                 | 22282/42525 [42:08<36:59,  9.12it/s]

 52%|██████████████████▊                 | 22286/42525 [42:08<34:16,  9.84it/s]

 52%|██████████████████▊                 | 22290/42525 [42:08<35:32,  9.49it/s]

 52%|██████████████████▊                 | 22291/42525 [42:08<35:56,  9.38it/s]

 52%|██████████████████▊                 | 22294/42525 [42:09<37:04,  9.09it/s]

 52%|██████████████████▊                 | 22295/42525 [42:09<39:53,  8.45it/s]

 52%|██████████████████▉                 | 22298/42525 [42:09<38:03,  8.86it/s]

 52%|██████████████████▉                 | 22300/42525 [42:09<35:55,  9.38it/s]

 52%|██████████████████▉                 | 22304/42525 [42:10<34:27,  9.78it/s]

 52%|██████████████████▉                 | 22306/42525 [42:10<33:48,  9.97it/s]

 52%|██████████████████▉                 | 22309/42525 [42:10<38:45,  8.69it/s]

 52%|██████████████████▉                 | 22311/42525 [42:11<40:35,  8.30it/s]

 52%|██████████████████▉                 | 22314/42525 [42:11<40:16,  8.36it/s]

 52%|██████████████████▉                 | 22317/42525 [42:11<36:39,  9.19it/s]

 52%|██████████████████▉                 | 22319/42525 [42:12<37:42,  8.93it/s]

 52%|██████████████████▉                 | 22321/42525 [42:12<40:18,  8.35it/s]

 52%|██████████████████▉                 | 22325/42525 [42:12<35:32,  9.47it/s]

 53%|██████████████████▉                 | 22326/42525 [42:12<35:58,  9.36it/s]

 53%|██████████████████▉                 | 22328/42525 [42:13<38:02,  8.85it/s]

 53%|██████████████████▉                 | 22332/42525 [42:13<35:54,  9.37it/s]

 53%|██████████████████▉                 | 22335/42525 [42:13<35:57,  9.36it/s]

 53%|██████████████████▉                 | 22339/42525 [42:14<34:28,  9.76it/s]

 53%|██████████████████▉                 | 22340/42525 [42:14<35:08,  9.57it/s]

 53%|██████████████████▉                 | 22343/42525 [42:14<36:56,  9.10it/s]

 53%|██████████████████▉                 | 22346/42525 [42:15<35:45,  9.41it/s]

 53%|██████████████████▉                 | 22348/42525 [42:15<37:28,  8.97it/s]

 53%|██████████████████▉                 | 22350/42525 [42:15<40:01,  8.40it/s]

 53%|██████████████████▉                 | 22352/42525 [42:15<38:52,  8.65it/s]

 53%|██████████████████▉                 | 22356/42525 [42:16<35:34,  9.45it/s]

 53%|██████████████████▉                 | 22359/42525 [42:16<34:50,  9.64it/s]

 53%|██████████████████▉                 | 22362/42525 [42:16<35:54,  9.36it/s]

 53%|██████████████████▉                 | 22365/42525 [42:17<34:41,  9.69it/s]

 53%|██████████████████▉                 | 22368/42525 [42:17<34:53,  9.63it/s]

 53%|██████████████████▉                 | 22371/42525 [42:17<35:47,  9.38it/s]

 53%|██████████████████▉                 | 22374/42525 [42:18<40:12,  8.35it/s]

 53%|██████████████████▉                 | 22376/42525 [42:18<40:13,  8.35it/s]

 53%|██████████████████▉                 | 22379/42525 [42:18<37:42,  8.90it/s]

 53%|██████████████████▉                 | 22383/42525 [42:19<35:02,  9.58it/s]

 53%|██████████████████▉                 | 22386/42525 [42:19<36:02,  9.31it/s]

 53%|██████████████████▉                 | 22388/42525 [42:19<41:25,  8.10it/s]

 53%|██████████████████▉                 | 22390/42525 [42:19<42:39,  7.87it/s]

 53%|██████████████████▉                 | 22394/42525 [42:20<37:10,  9.02it/s]

 53%|██████████████████▉                 | 22396/42525 [42:20<37:04,  9.05it/s]

 53%|██████████████████▉                 | 22398/42525 [42:20<38:32,  8.70it/s]

 53%|██████████████████▉                 | 22402/42525 [42:21<37:06,  9.04it/s]

 53%|██████████████████▉                 | 22405/42525 [42:21<37:32,  8.93it/s]

 53%|██████████████████▉                 | 22407/42525 [42:21<38:18,  8.75it/s]

 53%|██████████████████▉                 | 22410/42525 [42:22<35:50,  9.35it/s]

 53%|██████████████████▉                 | 22413/42525 [42:22<36:48,  9.11it/s]

 53%|██████████████████▉                 | 22415/42525 [42:22<35:12,  9.52it/s]

 53%|██████████████████▉                 | 22418/42525 [42:23<38:14,  8.76it/s]

 53%|██████████████████▉                 | 22422/42525 [42:23<34:57,  9.58it/s]

 53%|██████████████████▉                 | 22425/42525 [42:23<36:37,  9.15it/s]

 53%|██████████████████▉                 | 22428/42525 [42:24<37:56,  8.83it/s]

 53%|██████████████████▉                 | 22432/42525 [42:24<34:42,  9.65it/s]

 53%|██████████████████▉                 | 22436/42525 [42:24<33:36,  9.96it/s]

 53%|██████████████████▉                 | 22438/42525 [42:25<36:20,  9.21it/s]

 53%|██████████████████▉                 | 22440/42525 [42:25<34:41,  9.65it/s]

 53%|██████████████████▉                 | 22443/42525 [42:25<39:30,  8.47it/s]

 53%|███████████████████                 | 22446/42525 [42:26<38:10,  8.76it/s]

 53%|███████████████████                 | 22448/42525 [42:26<36:00,  9.29it/s]

 53%|███████████████████                 | 22451/42525 [42:26<36:55,  9.06it/s]

 53%|███████████████████                 | 22453/42525 [42:26<37:52,  8.83it/s]

 53%|███████████████████                 | 22456/42525 [42:27<38:18,  8.73it/s]

 53%|███████████████████                 | 22458/42525 [42:27<39:52,  8.39it/s]

 53%|███████████████████                 | 22460/42525 [42:27<40:38,  8.23it/s]

 53%|███████████████████                 | 22462/42525 [42:27<36:48,  9.08it/s]

 53%|███████████████████                 | 22465/42525 [42:28<38:44,  8.63it/s]

 53%|███████████████████                 | 22468/42525 [42:28<36:35,  9.14it/s]

 53%|███████████████████                 | 22470/42525 [42:28<35:45,  9.35it/s]

 53%|███████████████████                 | 22472/42525 [42:29<34:14,  9.76it/s]

 53%|███████████████████                 | 22475/42525 [42:29<38:09,  8.76it/s]

 53%|███████████████████                 | 22478/42525 [42:29<35:20,  9.46it/s]

 53%|███████████████████                 | 22480/42525 [42:29<37:17,  8.96it/s]

 53%|███████████████████                 | 22483/42525 [42:30<40:23,  8.27it/s]

 53%|███████████████████                 | 22486/42525 [42:30<36:46,  9.08it/s]

 53%|███████████████████                 | 22489/42525 [42:30<36:00,  9.27it/s]

 53%|███████████████████                 | 22491/42525 [42:31<37:53,  8.81it/s]

 53%|███████████████████                 | 22495/42525 [42:31<34:42,  9.62it/s]

 53%|███████████████████                 | 22497/42525 [42:31<34:25,  9.70it/s]

 53%|███████████████████                 | 22500/42525 [42:32<36:43,  9.09it/s]

 53%|███████████████████                 | 22504/42525 [42:32<34:32,  9.66it/s]

 53%|███████████████████                 | 22507/42525 [42:32<35:33,  9.38it/s]

 53%|███████████████████                 | 22509/42525 [42:33<35:40,  9.35it/s]

 53%|███████████████████                 | 22513/42525 [42:33<34:36,  9.64it/s]

 53%|███████████████████                 | 22516/42525 [42:33<36:54,  9.04it/s]

 53%|███████████████████                 | 22518/42525 [42:34<39:23,  8.47it/s]

 53%|███████████████████                 | 22521/42525 [42:34<35:48,  9.31it/s]

 53%|███████████████████                 | 22524/42525 [42:34<36:25,  9.15it/s]

 53%|███████████████████                 | 22526/42525 [42:34<37:33,  8.88it/s]

 53%|███████████████████                 | 22529/42525 [42:35<40:16,  8.27it/s]

 53%|███████████████████                 | 22533/42525 [42:35<35:30,  9.38it/s]

 53%|███████████████████                 | 22536/42525 [42:36<37:21,  8.92it/s]

 53%|███████████████████                 | 22539/42525 [42:36<38:19,  8.69it/s]

 53%|███████████████████                 | 22542/42525 [42:36<37:12,  8.95it/s]

 53%|███████████████████                 | 22546/42525 [42:37<34:11,  9.74it/s]

 53%|███████████████████                 | 22549/42525 [42:37<35:01,  9.51it/s]

 53%|███████████████████                 | 22550/42525 [42:37<35:03,  9.50it/s]

 53%|███████████████████                 | 22553/42525 [42:37<36:53,  9.02it/s]

 53%|███████████████████                 | 22556/42525 [42:38<36:18,  9.17it/s]

 53%|███████████████████                 | 22559/42525 [42:38<37:28,  8.88it/s]

 53%|███████████████████                 | 22560/42525 [42:38<40:11,  8.28it/s]

 53%|███████████████████                 | 22563/42525 [42:39<39:20,  8.46it/s]

 53%|███████████████████                 | 22566/42525 [42:39<38:27,  8.65it/s]

 53%|███████████████████                 | 22568/42525 [42:39<35:53,  9.27it/s]

 53%|███████████████████                 | 22570/42525 [42:39<37:36,  8.84it/s]

 53%|███████████████████                 | 22573/42525 [42:40<36:37,  9.08it/s]

 53%|███████████████████                 | 22576/42525 [42:40<35:35,  9.34it/s]

 53%|███████████████████                 | 22578/42525 [42:40<35:18,  9.42it/s]

 53%|███████████████████                 | 22580/42525 [42:40<34:37,  9.60it/s]

 53%|███████████████████                 | 22583/42525 [42:41<39:38,  8.38it/s]

 53%|███████████████████                 | 22586/42525 [42:41<38:25,  8.65it/s]

 53%|███████████████████                 | 22589/42525 [42:41<35:43,  9.30it/s]

 53%|███████████████████▏                | 22592/42525 [42:42<34:08,  9.73it/s]

 53%|███████████████████▏                | 22594/42525 [42:42<39:20,  8.44it/s]

 53%|███████████████████▏                | 22596/42525 [42:42<40:48,  8.14it/s]

 53%|███████████████████▏                | 22600/42525 [42:43<35:33,  9.34it/s]

 53%|███████████████████▏                | 22604/42525 [42:43<35:30,  9.35it/s]

 53%|███████████████████▏                | 22607/42525 [42:43<36:53,  9.00it/s]

 53%|███████████████████▏                | 22610/42525 [42:44<39:05,  8.49it/s]

 53%|███████████████████▏                | 22613/42525 [42:44<36:17,  9.15it/s]

 53%|███████████████████▏                | 22616/42525 [42:44<37:42,  8.80it/s]

 53%|███████████████████▏                | 22619/42525 [42:45<34:58,  9.49it/s]

 53%|███████████████████▏                | 22623/42525 [42:45<33:19,  9.95it/s]

 53%|███████████████████▏                | 22626/42525 [42:46<34:11,  9.70it/s]

 53%|███████████████████▏                | 22630/42525 [42:46<33:14,  9.98it/s]

 53%|███████████████████▏                | 22633/42525 [42:46<34:28,  9.62it/s]

 53%|███████████████████▏                | 22635/42525 [42:46<34:54,  9.50it/s]

 53%|███████████████████▏                | 22639/42525 [42:47<34:06,  9.72it/s]

 53%|███████████████████▏                | 22643/42525 [42:47<34:13,  9.68it/s]

 53%|███████████████████▏                | 22645/42525 [42:48<37:13,  8.90it/s]

 53%|███████████████████▏                | 22649/42525 [42:48<34:16,  9.66it/s]

 53%|███████████████████▏                | 22653/42525 [42:48<33:21,  9.93it/s]

 53%|███████████████████▏                | 22655/42525 [42:49<32:54, 10.06it/s]

 53%|███████████████████▏                | 22659/42525 [42:49<34:22,  9.63it/s]

 53%|███████████████████▏                | 22663/42525 [42:49<33:58,  9.74it/s]

 53%|███████████████████▏                | 22666/42525 [42:50<34:15,  9.66it/s]

 53%|███████████████████▏                | 22669/42525 [42:50<34:36,  9.56it/s]

 53%|███████████████████▏                | 22673/42525 [42:50<33:07,  9.99it/s]

 53%|███████████████████▏                | 22676/42525 [42:51<34:56,  9.47it/s]

 53%|███████████████████▏                | 22678/42525 [42:51<37:54,  8.72it/s]

 53%|███████████████████▏                | 22682/42525 [42:51<36:05,  9.16it/s]

 53%|███████████████████▏                | 22684/42525 [42:52<35:05,  9.42it/s]

 53%|███████████████████▏                | 22687/42525 [42:52<37:16,  8.87it/s]

 53%|███████████████████▏                | 22691/42525 [42:52<34:18,  9.64it/s]

 53%|███████████████████▏                | 22693/42525 [42:53<34:54,  9.47it/s]

 53%|███████████████████▏                | 22696/42525 [42:53<36:10,  9.14it/s]

 53%|███████████████████▏                | 22699/42525 [42:53<39:06,  8.45it/s]

 53%|███████████████████▏                | 22702/42525 [42:54<36:13,  9.12it/s]

 53%|███████████████████▏                | 22703/42525 [42:54<39:03,  8.46it/s]

 53%|███████████████████▏                | 22707/42525 [42:54<36:19,  9.09it/s]

 53%|███████████████████▏                | 22710/42525 [42:54<37:22,  8.83it/s]

 53%|███████████████████▏                | 22713/42525 [42:55<38:22,  8.60it/s]

 53%|███████████████████▏                | 22715/42525 [42:55<36:27,  9.06it/s]

 53%|███████████████████▏                | 22718/42525 [42:55<38:35,  8.55it/s]

 53%|███████████████████▏                | 22721/42525 [42:56<37:16,  8.86it/s]

 53%|███████████████████▏                | 22723/42525 [42:56<39:56,  8.26it/s]

 53%|███████████████████▏                | 22726/42525 [42:56<36:29,  9.04it/s]

 53%|███████████████████▏                | 22728/42525 [42:57<38:42,  8.53it/s]

 53%|███████████████████▏                | 22730/42525 [42:57<39:49,  8.28it/s]

 53%|███████████████████▏                | 22733/42525 [42:57<39:18,  8.39it/s]

 53%|███████████████████▏                | 22736/42525 [42:57<37:41,  8.75it/s]

 53%|███████████████████▏                | 22738/42525 [42:58<38:06,  8.65it/s]

 53%|███████████████████▎                | 22740/42525 [42:58<35:20,  9.33it/s]

 53%|███████████████████▎                | 22744/42525 [42:58<33:26,  9.86it/s]

 53%|███████████████████▎                | 22745/42525 [42:58<36:05,  9.14it/s]

 53%|███████████████████▎                | 22749/42525 [42:59<35:26,  9.30it/s]

 53%|███████████████████▎                | 22750/42525 [42:59<36:51,  8.94it/s]

 54%|███████████████████▎                | 22753/42525 [42:59<35:47,  9.21it/s]

 54%|███████████████████▎                | 22756/42525 [43:00<35:12,  9.36it/s]

 54%|███████████████████▎                | 22757/42525 [43:00<35:32,  9.27it/s]

 54%|███████████████████▎                | 22760/42525 [43:00<38:13,  8.62it/s]

 54%|███████████████████▎                | 22762/42525 [43:00<43:02,  7.65it/s]

 54%|███████████████████▎                | 22764/42525 [43:01<41:48,  7.88it/s]

 54%|███████████████████▎                | 22766/42525 [43:01<37:55,  8.68it/s]

 54%|███████████████████▎                | 22769/42525 [43:01<34:21,  9.58it/s]

 54%|███████████████████▎                | 22771/42525 [43:01<36:02,  9.14it/s]

 54%|███████████████████▎                | 22774/42525 [43:02<34:28,  9.55it/s]

 54%|███████████████████▎                | 22776/42525 [43:02<38:21,  8.58it/s]

 54%|███████████████████▎                | 22779/42525 [43:02<35:09,  9.36it/s]

 54%|███████████████████▎                | 22782/42525 [43:03<33:52,  9.71it/s]

 54%|███████████████████▎                | 22785/42525 [43:03<38:47,  8.48it/s]

 54%|███████████████████▎                | 22788/42525 [43:03<39:17,  8.37it/s]

 54%|███████████████████▎                | 22791/42525 [43:04<37:04,  8.87it/s]

 54%|███████████████████▎                | 22794/42525 [43:04<38:11,  8.61it/s]

 54%|███████████████████▎                | 22795/42525 [43:04<40:30,  8.12it/s]

 54%|███████████████████▎                | 22799/42525 [43:05<37:16,  8.82it/s]

 54%|███████████████████▎                | 22802/42525 [43:05<36:20,  9.05it/s]

 54%|███████████████████▎                | 22803/42525 [43:05<35:59,  9.13it/s]

 54%|███████████████████▎                | 22806/42525 [43:05<35:41,  9.21it/s]

 54%|███████████████████▎                | 22809/42525 [43:06<35:15,  9.32it/s]

 54%|███████████████████▎                | 22810/42525 [43:06<38:10,  8.61it/s]

 54%|███████████████████▎                | 22813/42525 [43:06<36:54,  8.90it/s]

 54%|███████████████████▎                | 22815/42525 [43:06<38:03,  8.63it/s]

 54%|███████████████████▎                | 22817/42525 [43:07<39:28,  8.32it/s]

 54%|███████████████████▎                | 22820/42525 [43:07<35:12,  9.33it/s]

 54%|███████████████████▎                | 22823/42525 [43:07<33:56,  9.67it/s]

 54%|███████████████████▎                | 22827/42525 [43:08<32:25, 10.12it/s]

 54%|███████████████████▎                | 22830/42525 [43:08<37:35,  8.73it/s]

 54%|███████████████████▎                | 22832/42525 [43:08<35:24,  9.27it/s]

 54%|███████████████████▎                | 22835/42525 [43:09<38:04,  8.62it/s]

 54%|███████████████████▎                | 22837/42525 [43:09<35:39,  9.20it/s]

 54%|███████████████████▎                | 22841/42525 [43:09<34:47,  9.43it/s]

 54%|███████████████████▎                | 22843/42525 [43:09<35:25,  9.26it/s]

 54%|███████████████████▎                | 22846/42525 [43:10<34:01,  9.64it/s]

 54%|███████████████████▎                | 22849/42525 [43:10<33:08,  9.90it/s]

 54%|███████████████████▎                | 22853/42525 [43:10<32:31, 10.08it/s]

 54%|███████████████████▎                | 22856/42525 [43:11<33:19,  9.83it/s]

 54%|███████████████████▎                | 22859/42525 [43:11<36:23,  9.01it/s]

 54%|███████████████████▎                | 22862/42525 [43:11<34:37,  9.47it/s]

 54%|███████████████████▎                | 22863/42525 [43:11<36:45,  8.91it/s]

 54%|███████████████████▎                | 22866/42525 [43:12<39:26,  8.31it/s]

 54%|███████████████████▎                | 22869/42525 [43:12<36:11,  9.05it/s]

 54%|███████████████████▎                | 22871/42525 [43:12<37:48,  8.66it/s]

 54%|███████████████████▎                | 22873/42525 [43:13<42:45,  7.66it/s]

 54%|███████████████████▎                | 22876/42525 [43:13<38:32,  8.50it/s]

 54%|███████████████████▎                | 22877/42525 [43:13<40:58,  7.99it/s]

 54%|███████████████████▎                | 22879/42525 [43:13<39:52,  8.21it/s]

 54%|███████████████████▎                | 22883/42525 [43:14<35:26,  9.24it/s]

 54%|███████████████████▎                | 22886/42525 [43:14<34:22,  9.52it/s]

 54%|███████████████████▍                | 22887/42525 [43:14<37:22,  8.76it/s]

 54%|███████████████████▍                | 22891/42525 [43:15<34:05,  9.60it/s]

 54%|███████████████████▍                | 22895/42525 [43:15<34:13,  9.56it/s]

 54%|███████████████████▍                | 22897/42525 [43:15<33:14,  9.84it/s]

 54%|███████████████████▍                | 22900/42525 [43:16<35:36,  9.18it/s]

 54%|███████████████████▍                | 22903/42525 [43:16<34:13,  9.56it/s]

 54%|███████████████████▍                | 22905/42525 [43:16<34:43,  9.42it/s]

 54%|███████████████████▍                | 22908/42525 [43:16<36:25,  8.98it/s]

 54%|███████████████████▍                | 22911/42525 [43:17<34:19,  9.52it/s]

 54%|███████████████████▍                | 22913/42525 [43:17<33:40,  9.70it/s]

 54%|███████████████████▍                | 22916/42525 [43:17<35:25,  9.23it/s]

 54%|███████████████████▍                | 22917/42525 [43:17<38:18,  8.53it/s]

 54%|███████████████████▍                | 22921/42525 [43:18<35:03,  9.32it/s]

 54%|███████████████████▍                | 22923/42525 [43:18<37:44,  8.66it/s]

 54%|███████████████████▍                | 22924/42525 [43:18<37:06,  8.80it/s]

 54%|███████████████████▍                | 22927/42525 [43:18<35:10,  9.29it/s]

 54%|███████████████████▍                | 22929/42525 [43:19<37:40,  8.67it/s]

 54%|███████████████████▍                | 22931/42525 [43:19<36:55,  8.84it/s]

 54%|███████████████████▍                | 22934/42525 [43:19<37:54,  8.61it/s]

 54%|███████████████████▍                | 22936/42525 [43:20<35:31,  9.19it/s]

 54%|███████████████████▍                | 22938/42525 [43:20<39:46,  8.21it/s]

 54%|███████████████████▍                | 22940/42525 [43:20<37:06,  8.80it/s]

 54%|███████████████████▍                | 22943/42525 [43:20<34:32,  9.45it/s]

 54%|███████████████████▍                | 22944/42525 [43:20<35:20,  9.23it/s]

 54%|███████████████████▍                | 22947/42525 [43:21<37:55,  8.60it/s]

 54%|███████████████████▍                | 22949/42525 [43:21<40:10,  8.12it/s]

 54%|███████████████████▍                | 22951/42525 [43:21<42:10,  7.73it/s]

 54%|███████████████████▍                | 22955/42525 [43:22<35:39,  9.15it/s]

 54%|███████████████████▍                | 22957/42525 [43:22<34:13,  9.53it/s]

 54%|███████████████████▍                | 22960/42525 [43:22<35:58,  9.06it/s]

 54%|███████████████████▍                | 22962/42525 [43:23<38:27,  8.48it/s]

 54%|███████████████████▍                | 22965/42525 [43:23<35:13,  9.26it/s]

 54%|███████████████████▍                | 22967/42525 [43:23<36:35,  8.91it/s]

 54%|███████████████████▍                | 22970/42525 [43:23<37:54,  8.60it/s]

 54%|███████████████████▍                | 22972/42525 [43:24<36:02,  9.04it/s]

 54%|███████████████████▍                | 22975/42525 [43:24<38:06,  8.55it/s]

 54%|███████████████████▍                | 22977/42525 [43:24<42:41,  7.63it/s]

 54%|███████████████████▍                | 22980/42525 [43:25<38:40,  8.42it/s]

 54%|███████████████████▍                | 22982/42525 [43:25<37:21,  8.72it/s]

 54%|███████████████████▍                | 22985/42525 [43:25<34:11,  9.53it/s]

 54%|███████████████████▍                | 22987/42525 [43:25<40:27,  8.05it/s]

 54%|███████████████████▍                | 22989/42525 [43:26<38:21,  8.49it/s]

 54%|███████████████████▍                | 22991/42525 [43:26<40:47,  7.98it/s]

 54%|███████████████████▍                | 22993/42525 [43:26<39:36,  8.22it/s]

 54%|███████████████████▍                | 22995/42525 [43:26<38:41,  8.41it/s]

 54%|███████████████████▍                | 22998/42525 [43:27<36:42,  8.87it/s]

 54%|███████████████████▍                | 23001/42525 [43:27<36:20,  8.95it/s]

 54%|███████████████████▍                | 23004/42525 [43:27<35:06,  9.27it/s]

 54%|███████████████████▍                | 23006/42525 [43:28<34:23,  9.46it/s]

 54%|███████████████████▍                | 23009/42525 [43:28<34:59,  9.30it/s]

 54%|███████████████████▍                | 23011/42525 [43:28<35:19,  9.21it/s]

 54%|███████████████████▍                | 23013/42525 [43:28<39:28,  8.24it/s]

 54%|███████████████████▍                | 23016/42525 [43:29<39:22,  8.26it/s]

 54%|███████████████████▍                | 23019/42525 [43:29<37:11,  8.74it/s]

 54%|███████████████████▍                | 23022/42525 [43:29<35:41,  9.11it/s]

 54%|███████████████████▍                | 23023/42525 [43:30<38:11,  8.51it/s]

 54%|███████████████████▍                | 23025/42525 [43:30<38:49,  8.37it/s]

 54%|███████████████████▍                | 23028/42525 [43:30<39:39,  8.19it/s]

 54%|███████████████████▍                | 23031/42525 [43:30<36:34,  8.88it/s]

 54%|███████████████████▌                | 23035/42525 [43:31<34:14,  9.49it/s]

 54%|███████████████████▌                | 23038/42525 [43:31<35:04,  9.26it/s]

 54%|███████████████████▌                | 23042/42525 [43:32<33:04,  9.82it/s]

 54%|███████████████████▌                | 23045/42525 [43:32<33:58,  9.56it/s]

 54%|███████████████████▌                | 23047/42525 [43:32<32:56,  9.85it/s]

 54%|███████████████████▌                | 23050/42525 [43:32<34:30,  9.40it/s]

 54%|███████████████████▌                | 23051/42525 [43:33<35:21,  9.18it/s]

 54%|███████████████████▌                | 23054/42525 [43:33<36:45,  8.83it/s]

 54%|███████████████████▌                | 23056/42525 [43:33<35:04,  9.25it/s]

 54%|███████████████████▌                | 23057/42525 [43:33<38:26,  8.44it/s]

 54%|███████████████████▌                | 23060/42525 [43:34<38:16,  8.48it/s]

 54%|███████████████████▌                | 23061/42525 [43:34<36:51,  8.80it/s]

 54%|███████████████████▌                | 23065/42525 [43:34<33:46,  9.60it/s]

 54%|███████████████████▌                | 23069/42525 [43:35<32:42,  9.92it/s]

 54%|███████████████████▌                | 23072/42525 [43:35<36:44,  8.83it/s]

 54%|███████████████████▌                | 23074/42525 [43:35<34:57,  9.27it/s]

 54%|███████████████████▌                | 23077/42525 [43:35<37:12,  8.71it/s]

 54%|███████████████████▌                | 23079/42525 [43:36<35:08,  9.22it/s]

 54%|███████████████████▌                | 23082/42525 [43:36<34:57,  9.27it/s]

 54%|███████████████████▌                | 23083/42525 [43:36<37:39,  8.60it/s]

 54%|███████████████████▌                | 23086/42525 [43:36<37:54,  8.55it/s]

 54%|███████████████████▌                | 23089/42525 [43:37<38:30,  8.41it/s]

 54%|███████████████████▌                | 23092/42525 [43:37<35:06,  9.23it/s]

 54%|███████████████████▌                | 23094/42525 [43:37<37:38,  8.60it/s]

 54%|███████████████████▌                | 23096/42525 [43:38<38:17,  8.46it/s]

 54%|███████████████████▌                | 23100/42525 [43:38<33:27,  9.68it/s]

 54%|███████████████████▌                | 23103/42525 [43:38<32:50,  9.86it/s]

 54%|███████████████████▌                | 23107/42525 [43:39<31:59, 10.12it/s]

 54%|███████████████████▌                | 23111/42525 [43:39<34:03,  9.50it/s]

 54%|███████████████████▌                | 23114/42525 [43:39<36:03,  8.97it/s]

 54%|███████████████████▌                | 23116/42525 [43:40<36:32,  8.85it/s]

 54%|███████████████████▌                | 23119/42525 [43:40<34:14,  9.44it/s]

 54%|███████████████████▌                | 23122/42525 [43:40<33:42,  9.60it/s]

 54%|███████████████████▌                | 23125/42525 [43:41<34:57,  9.25it/s]

 54%|███████████████████▌                | 23127/42525 [43:41<36:19,  8.90it/s]

 54%|███████████████████▌                | 23131/42525 [43:41<35:32,  9.09it/s]

 54%|███████████████████▌                | 23134/42525 [43:42<34:09,  9.46it/s]

 54%|███████████████████▌                | 23137/42525 [43:42<33:10,  9.74it/s]

 54%|███████████████████▌                | 23140/42525 [43:42<36:49,  8.77it/s]

 54%|███████████████████▌                | 23143/42525 [43:43<36:15,  8.91it/s]

 54%|███████████████████▌                | 23146/42525 [43:43<35:48,  9.02it/s]

 54%|███████████████████▌                | 23150/42525 [43:43<34:13,  9.43it/s]

 54%|███████████████████▌                | 23152/42525 [43:44<37:17,  8.66it/s]

 54%|███████████████████▌                | 23153/42525 [43:44<36:10,  8.92it/s]

 54%|███████████████████▌                | 23157/42525 [43:44<35:11,  9.17it/s]

 54%|███████████████████▌                | 23160/42525 [43:45<33:45,  9.56it/s]

 54%|███████████████████▌                | 23161/42525 [43:45<36:23,  8.87it/s]

 54%|███████████████████▌                | 23164/42525 [43:45<36:30,  8.84it/s]

 54%|███████████████████▌                | 23165/42525 [43:45<39:09,  8.24it/s]

 54%|███████████████████▌                | 23169/42525 [43:46<35:46,  9.02it/s]

 54%|███████████████████▌                | 23171/42525 [43:46<34:51,  9.25it/s]

 54%|███████████████████▌                | 23174/42525 [43:46<33:30,  9.63it/s]

 55%|███████████████████▌                | 23177/42525 [43:46<33:04,  9.75it/s]

 55%|███████████████████▌                | 23180/42525 [43:47<32:57,  9.78it/s]

 55%|███████████████████▌                | 23181/42525 [43:47<36:13,  8.90it/s]

 55%|███████████████████▋                | 23183/42525 [43:47<35:37,  9.05it/s]

 55%|███████████████████▋                | 23186/42525 [43:47<36:31,  8.83it/s]

 55%|███████████████████▋                | 23188/42525 [43:48<34:39,  9.30it/s]

 55%|███████████████████▋                | 23191/42525 [43:48<36:09,  8.91it/s]

 55%|███████████████████▋                | 23192/42525 [43:48<35:32,  9.07it/s]

 55%|███████████████████▋                | 23196/42525 [43:48<33:51,  9.52it/s]

 55%|███████████████████▋                | 23199/42525 [43:49<32:51,  9.80it/s]

 55%|███████████████████▋                | 23202/42525 [43:49<32:29,  9.91it/s]

 55%|███████████████████▋                | 23204/42525 [43:49<33:39,  9.57it/s]

 55%|███████████████████▋                | 23207/42525 [43:50<35:08,  9.16it/s]

 55%|███████████████████▋                | 23210/42525 [43:50<33:34,  9.59it/s]

 55%|███████████████████▋                | 23211/42525 [43:50<35:15,  9.13it/s]

 55%|███████████████████▋                | 23214/42525 [43:50<36:45,  8.76it/s]

 55%|███████████████████▋                | 23216/42525 [43:51<35:36,  9.04it/s]

 55%|███████████████████▋                | 23220/42525 [43:51<35:01,  9.19it/s]

 55%|███████████████████▋                | 23221/42525 [43:51<37:18,  8.62it/s]

 55%|███████████████████▋                | 23225/42525 [43:52<34:13,  9.40it/s]

 55%|███████████████████▋                | 23229/42525 [43:52<33:31,  9.59it/s]

 55%|███████████████████▋                | 23232/42525 [43:52<33:55,  9.48it/s]

 55%|███████████████████▋                | 23235/42525 [43:53<35:25,  9.07it/s]

 55%|███████████████████▋                | 23238/42525 [43:53<34:43,  9.26it/s]

 55%|███████████████████▋                | 23240/42525 [43:53<38:58,  8.25it/s]

 55%|███████████████████▋                | 23243/42525 [43:54<36:11,  8.88it/s]

 55%|███████████████████▋                | 23245/42525 [43:54<38:58,  8.25it/s]

 55%|███████████████████▋                | 23247/42525 [43:54<39:25,  8.15it/s]

 55%|███████████████████▋                | 23250/42525 [43:54<35:21,  9.09it/s]

 55%|███████████████████▋                | 23253/42525 [43:55<35:18,  9.10it/s]

 55%|███████████████████▋                | 23255/42525 [43:55<37:27,  8.57it/s]

 55%|███████████████████▋                | 23258/42525 [43:55<33:57,  9.46it/s]

 55%|███████████████████▋                | 23259/42525 [43:55<33:58,  9.45it/s]

 55%|███████████████████▋                | 23262/42525 [43:56<38:36,  8.31it/s]

 55%|███████████████████▋                | 23264/42525 [43:56<39:38,  8.10it/s]

 55%|███████████████████▋                | 23266/42525 [43:56<36:54,  8.70it/s]

 55%|███████████████████▋                | 23268/42525 [43:56<35:51,  8.95it/s]

 55%|███████████████████▋                | 23272/42525 [43:57<35:05,  9.15it/s]

 55%|███████████████████▋                | 23276/42525 [43:57<34:45,  9.23it/s]

 55%|███████████████████▋                | 23278/42525 [43:58<37:56,  8.45it/s]

 55%|███████████████████▋                | 23280/42525 [43:58<35:29,  9.04it/s]

 55%|███████████████████▋                | 23283/42525 [43:58<39:07,  8.20it/s]

 55%|███████████████████▋                | 23286/42525 [43:59<35:36,  9.00it/s]

 55%|███████████████████▋                | 23288/42525 [43:59<34:19,  9.34it/s]

 55%|███████████████████▋                | 23291/42525 [43:59<36:25,  8.80it/s]

 55%|███████████████████▋                | 23292/42525 [43:59<38:57,  8.23it/s]

 55%|███████████████████▋                | 23296/42525 [44:00<35:33,  9.01it/s]

 55%|███████████████████▋                | 23298/42525 [44:00<38:34,  8.31it/s]

 55%|███████████████████▋                | 23300/42525 [44:00<40:37,  7.89it/s]

 55%|███████████████████▋                | 23302/42525 [44:00<40:53,  7.83it/s]

 55%|███████████████████▋                | 23306/42525 [44:01<35:13,  9.09it/s]

 55%|███████████████████▋                | 23307/42525 [44:01<35:24,  9.05it/s]

 55%|███████████████████▋                | 23310/42525 [44:01<37:18,  8.58it/s]

 55%|███████████████████▋                | 23313/42525 [44:02<35:18,  9.07it/s]

 55%|███████████████████▋                | 23316/42525 [44:02<33:49,  9.47it/s]

 55%|███████████████████▋                | 23319/42525 [44:02<34:54,  9.17it/s]

 55%|███████████████████▋                | 23321/42525 [44:03<40:01,  8.00it/s]

 55%|███████████████████▋                | 23323/42525 [44:03<36:25,  8.79it/s]

 55%|███████████████████▋                | 23327/42525 [44:03<33:40,  9.50it/s]

 55%|███████████████████▊                | 23331/42525 [44:04<32:07,  9.96it/s]

 55%|███████████████████▊                | 23332/42525 [44:04<34:54,  9.17it/s]

 55%|███████████████████▊                | 23334/42525 [44:04<35:36,  8.98it/s]

 55%|███████████████████▊                | 23337/42525 [44:04<35:33,  8.99it/s]

 55%|███████████████████▊                | 23339/42525 [44:04<36:22,  8.79it/s]

 55%|███████████████████▊                | 23342/42525 [44:05<33:47,  9.46it/s]

 55%|███████████████████▊                | 23344/42525 [44:05<36:54,  8.66it/s]

 55%|███████████████████▊                | 23345/42525 [44:05<35:44,  8.94it/s]

 55%|███████████████████▊                | 23347/42525 [44:05<37:16,  8.57it/s]

 55%|███████████████████▊                | 23349/42525 [44:06<35:51,  8.91it/s]

 55%|███████████████████▊                | 23352/42525 [44:06<37:00,  8.63it/s]

 55%|███████████████████▊                | 23355/42525 [44:06<35:10,  9.08it/s]

 55%|███████████████████▊                | 23358/42525 [44:07<35:00,  9.12it/s]

 55%|███████████████████▊                | 23361/42525 [44:07<33:18,  9.59it/s]

 55%|███████████████████▊                | 23364/42525 [44:07<32:30,  9.83it/s]

 55%|███████████████████▊                | 23366/42525 [44:07<31:44, 10.06it/s]

 55%|███████████████████▊                | 23369/42525 [44:08<35:41,  8.95it/s]

 55%|███████████████████▊                | 23370/42525 [44:08<35:11,  9.07it/s]

 55%|███████████████████▊                | 23374/42525 [44:08<34:37,  9.22it/s]

 55%|███████████████████▊                | 23377/42525 [44:09<36:54,  8.65it/s]

 55%|███████████████████▊                | 23379/42525 [44:09<36:30,  8.74it/s]

 55%|███████████████████▊                | 23382/42525 [44:09<36:48,  8.67it/s]

 55%|███████████████████▊                | 23386/42525 [44:10<33:29,  9.52it/s]

 55%|███████████████████▊                | 23388/42525 [44:10<35:27,  8.99it/s]

 55%|███████████████████▊                | 23392/42525 [44:10<32:58,  9.67it/s]

 55%|███████████████████▊                | 23395/42525 [44:11<32:55,  9.68it/s]

 55%|███████████████████▊                | 23398/42525 [44:11<33:32,  9.51it/s]

 55%|███████████████████▊                | 23400/42525 [44:11<36:48,  8.66it/s]

 55%|███████████████████▊                | 23403/42525 [44:11<33:22,  9.55it/s]

 55%|███████████████████▊                | 23405/42525 [44:12<32:19,  9.86it/s]

 55%|███████████████████▊                | 23409/42525 [44:12<33:29,  9.51it/s]

 55%|███████████████████▊                | 23411/42525 [44:12<37:48,  8.42it/s]

 55%|███████████████████▊                | 23414/42525 [44:13<39:12,  8.12it/s]

 55%|███████████████████▊                | 23417/42525 [44:13<35:00,  9.10it/s]

 55%|███████████████████▊                | 23419/42525 [44:13<34:13,  9.30it/s]

 55%|███████████████████▊                | 23421/42525 [44:14<37:25,  8.51it/s]

 55%|███████████████████▊                | 23424/42525 [44:14<33:50,  9.41it/s]

 55%|███████████████████▊                | 23426/42525 [44:14<38:36,  8.25it/s]

 55%|███████████████████▊                | 23428/42525 [44:14<37:05,  8.58it/s]

 55%|███████████████████▊                | 23430/42525 [44:15<34:56,  9.11it/s]

 55%|███████████████████▊                | 23433/42525 [44:15<36:21,  8.75it/s]

 55%|███████████████████▊                | 23437/42525 [44:15<33:16,  9.56it/s]

 55%|███████████████████▊                | 23439/42525 [44:16<37:16,  8.53it/s]

 55%|███████████████████▊                | 23442/42525 [44:16<38:42,  8.22it/s]

 55%|███████████████████▊                | 23445/42525 [44:16<37:38,  8.45it/s]

 55%|███████████████████▊                | 23449/42525 [44:17<35:22,  8.99it/s]

 55%|███████████████████▊                | 23452/42525 [44:17<34:09,  9.31it/s]

 55%|███████████████████▊                | 23454/42525 [44:17<35:42,  8.90it/s]

 55%|███████████████████▊                | 23457/42525 [44:18<34:53,  9.11it/s]

 55%|███████████████████▊                | 23459/42525 [44:18<40:11,  7.91it/s]

 55%|███████████████████▊                | 23463/42525 [44:18<34:11,  9.29it/s]

 55%|███████████████████▊                | 23466/42525 [44:19<33:04,  9.60it/s]

 55%|███████████████████▊                | 23469/42525 [44:19<34:13,  9.28it/s]

 55%|███████████████████▊                | 23471/42525 [44:19<35:01,  9.07it/s]

 55%|███████████████████▊                | 23472/42525 [44:19<34:43,  9.14it/s]

 55%|███████████████████▊                | 23476/42525 [44:20<32:35,  9.74it/s]

 55%|███████████████████▉                | 23479/42525 [44:20<35:10,  9.02it/s]

 55%|███████████████████▉                | 23480/42525 [44:20<34:29,  9.20it/s]

 55%|███████████████████▉                | 23484/42525 [44:21<33:05,  9.59it/s]

 55%|███████████████████▉                | 23486/42525 [44:21<32:35,  9.74it/s]

 55%|███████████████████▉                | 23489/42525 [44:21<35:08,  9.03it/s]

 55%|███████████████████▉                | 23491/42525 [44:21<35:13,  9.01it/s]

 55%|███████████████████▉                | 23492/42525 [44:21<34:57,  9.07it/s]

 55%|███████████████████▉                | 23495/42525 [44:22<35:17,  8.99it/s]

 55%|███████████████████▉                | 23497/42525 [44:22<36:26,  8.70it/s]

 55%|███████████████████▉                | 23500/42525 [44:22<35:57,  8.82it/s]

 55%|███████████████████▉                | 23502/42525 [44:22<34:07,  9.29it/s]

 55%|███████████████████▉                | 23505/42525 [44:23<34:56,  9.07it/s]

 55%|███████████████████▉                | 23508/42525 [44:23<33:50,  9.37it/s]

 55%|███████████████████▉                | 23510/42525 [44:23<35:03,  9.04it/s]

 55%|███████████████████▉                | 23512/42525 [44:24<34:59,  9.06it/s]

 55%|███████████████████▉                | 23514/42525 [44:24<37:58,  8.35it/s]

 55%|███████████████████▉                | 23517/42525 [44:24<37:52,  8.37it/s]

 55%|███████████████████▉                | 23519/42525 [44:24<40:17,  7.86it/s]

 55%|███████████████████▉                | 23521/42525 [44:25<36:23,  8.70it/s]

 55%|███████████████████▉                | 23523/42525 [44:25<38:53,  8.14it/s]

 55%|███████████████████▉                | 23525/42525 [44:25<38:10,  8.29it/s]

 55%|███████████████████▉                | 23527/42525 [44:25<37:52,  8.36it/s]

 55%|███████████████████▉                | 23529/42525 [44:26<38:03,  8.32it/s]

 55%|███████████████████▉                | 23531/42525 [44:26<39:32,  8.00it/s]

 55%|███████████████████▉                | 23533/42525 [44:26<39:23,  8.04it/s]

 55%|███████████████████▉                | 23537/42525 [44:27<34:19,  9.22it/s]

 55%|███████████████████▉                | 23539/42525 [44:27<34:54,  9.06it/s]

 55%|███████████████████▉                | 23542/42525 [44:27<36:37,  8.64it/s]

 55%|███████████████████▉                | 23544/42525 [44:27<37:59,  8.33it/s]

 55%|███████████████████▉                | 23547/42525 [44:28<37:31,  8.43it/s]

 55%|███████████████████▉                | 23550/42525 [44:28<34:13,  9.24it/s]

 55%|███████████████████▉                | 23553/42525 [44:28<32:13,  9.81it/s]

 55%|███████████████████▉                | 23555/42525 [44:29<35:57,  8.79it/s]

 55%|███████████████████▉                | 23558/42525 [44:29<33:07,  9.54it/s]

 55%|███████████████████▉                | 23560/42525 [44:29<33:06,  9.55it/s]

 55%|███████████████████▉                | 23562/42525 [44:29<32:33,  9.71it/s]

 55%|███████████████████▉                | 23565/42525 [44:30<34:16,  9.22it/s]

 55%|███████████████████▉                | 23568/42525 [44:30<36:23,  8.68it/s]

 55%|███████████████████▉                | 23570/42525 [44:30<34:36,  9.13it/s]

 55%|███████████████████▉                | 23573/42525 [44:30<32:58,  9.58it/s]

 55%|███████████████████▉                | 23575/42525 [44:31<36:11,  8.73it/s]

 55%|███████████████████▉                | 23579/42525 [44:31<32:52,  9.60it/s]

 55%|███████████████████▉                | 23581/42525 [44:31<37:30,  8.42it/s]

 55%|███████████████████▉                | 23583/42525 [44:32<36:45,  8.59it/s]

 55%|███████████████████▉                | 23585/42525 [44:32<35:27,  8.90it/s]

 55%|███████████████████▉                | 23588/42525 [44:32<33:20,  9.47it/s]

 55%|███████████████████▉                | 23591/42525 [44:32<33:07,  9.53it/s]

 55%|███████████████████▉                | 23594/42525 [44:33<34:56,  9.03it/s]

 55%|███████████████████▉                | 23597/42525 [44:33<33:04,  9.54it/s]

 55%|███████████████████▉                | 23601/42525 [44:34<33:51,  9.32it/s]

 56%|███████████████████▉                | 23603/42525 [44:34<34:31,  9.13it/s]

 56%|███████████████████▉                | 23606/42525 [44:34<32:40,  9.65it/s]

 56%|███████████████████▉                | 23609/42525 [44:34<33:21,  9.45it/s]

 56%|███████████████████▉                | 23611/42525 [44:35<33:45,  9.34it/s]

 56%|███████████████████▉                | 23613/42525 [44:35<37:57,  8.30it/s]

 56%|███████████████████▉                | 23615/42525 [44:35<34:59,  9.01it/s]

 56%|███████████████████▉                | 23618/42525 [44:35<38:56,  8.09it/s]

 56%|███████████████████▉                | 23620/42525 [44:36<36:25,  8.65it/s]

 56%|███████████████████▉                | 23623/42525 [44:36<35:47,  8.80it/s]

 56%|████████████████████                | 23625/42525 [44:36<34:57,  9.01it/s]

 56%|████████████████████                | 23628/42525 [44:37<32:40,  9.64it/s]

 56%|████████████████████                | 23630/42525 [44:37<34:05,  9.24it/s]

 56%|████████████████████                | 23633/42525 [44:37<36:10,  8.70it/s]

 56%|████████████████████                | 23636/42525 [44:37<34:42,  9.07it/s]

 56%|████████████████████                | 23638/42525 [44:38<35:11,  8.95it/s]

 56%|████████████████████                | 23641/42525 [44:38<33:02,  9.53it/s]

 56%|████████████████████                | 23643/42525 [44:38<33:29,  9.40it/s]

 56%|████████████████████                | 23644/42525 [44:38<33:39,  9.35it/s]

 56%|████████████████████                | 23647/42525 [44:39<38:46,  8.12it/s]

 56%|████████████████████                | 23649/42525 [44:39<36:17,  8.67it/s]

 56%|████████████████████                | 23652/42525 [44:39<33:15,  9.46it/s]

 56%|████████████████████                | 23654/42525 [44:39<32:32,  9.66it/s]

 56%|████████████████████                | 23657/42525 [44:40<34:24,  9.14it/s]

 56%|████████████████████                | 23659/42525 [44:40<36:06,  8.71it/s]

 56%|████████████████████                | 23661/42525 [44:40<34:36,  9.09it/s]

 56%|████████████████████                | 23664/42525 [44:41<33:37,  9.35it/s]

 56%|████████████████████                | 23665/42525 [44:41<36:58,  8.50it/s]

 56%|████████████████████                | 23669/42525 [44:41<34:33,  9.10it/s]

 56%|████████████████████                | 23673/42525 [44:42<32:14,  9.74it/s]

 56%|████████████████████                | 23676/42525 [44:42<31:54,  9.85it/s]

 56%|████████████████████                | 23677/42525 [44:42<32:24,  9.69it/s]

 56%|████████████████████                | 23681/42525 [44:42<31:47,  9.88it/s]

 56%|████████████████████                | 23684/42525 [44:43<34:34,  9.08it/s]

 56%|████████████████████                | 23686/42525 [44:43<37:54,  8.28it/s]

 56%|████████████████████                | 23688/42525 [44:43<35:40,  8.80it/s]

 56%|████████████████████                | 23691/42525 [44:43<35:07,  8.94it/s]

 56%|████████████████████                | 23694/42525 [44:44<33:14,  9.44it/s]

 56%|████████████████████                | 23695/42525 [44:44<34:17,  9.15it/s]

 56%|████████████████████                | 23697/42525 [44:44<36:05,  8.69it/s]

 56%|████████████████████                | 23701/42525 [44:45<33:36,  9.34it/s]

 56%|████████████████████                | 23703/42525 [44:45<34:19,  9.14it/s]

 56%|████████████████████                | 23705/42525 [44:45<32:52,  9.54it/s]

 56%|████████████████████                | 23707/42525 [44:45<32:45,  9.57it/s]

 56%|████████████████████                | 23710/42525 [44:45<32:29,  9.65it/s]

 56%|████████████████████                | 23712/42525 [44:46<34:05,  9.20it/s]

 56%|████████████████████                | 23714/42525 [44:46<36:59,  8.47it/s]

 56%|████████████████████                | 23717/42525 [44:46<35:47,  8.76it/s]

 56%|████████████████████                | 23719/42525 [44:47<34:34,  9.06it/s]

 56%|████████████████████                | 23721/42525 [44:47<32:45,  9.57it/s]

 56%|████████████████████                | 23724/42525 [44:47<35:58,  8.71it/s]

 56%|████████████████████                | 23727/42525 [44:47<33:41,  9.30it/s]

 56%|████████████████████                | 23730/42525 [44:48<33:59,  9.21it/s]

 56%|████████████████████                | 23732/42525 [44:48<35:39,  8.78it/s]

 56%|████████████████████                | 23734/42525 [44:48<38:36,  8.11it/s]

 56%|████████████████████                | 23737/42525 [44:49<33:58,  9.22it/s]

 56%|████████████████████                | 23739/42525 [44:49<32:30,  9.63it/s]

 56%|████████████████████                | 23742/42525 [44:49<35:00,  8.94it/s]

 56%|████████████████████                | 23745/42525 [44:49<33:20,  9.39it/s]

 56%|████████████████████                | 23747/42525 [44:50<35:38,  8.78it/s]

 56%|████████████████████                | 23749/42525 [44:50<33:17,  9.40it/s]

 56%|████████████████████                | 23751/42525 [44:50<35:18,  8.86it/s]

 56%|████████████████████                | 23753/42525 [44:50<36:34,  8.56it/s]

 56%|████████████████████                | 23757/42525 [44:51<33:35,  9.31it/s]

 56%|████████████████████                | 23759/42525 [44:51<32:34,  9.60it/s]

 56%|████████████████████                | 23763/42525 [44:51<31:46,  9.84it/s]

 56%|████████████████████                | 23766/42525 [44:52<31:39,  9.87it/s]

 56%|████████████████████                | 23769/42525 [44:52<33:09,  9.43it/s]

 56%|████████████████████                | 23772/42525 [44:52<36:44,  8.51it/s]

 56%|████████████████████▏               | 23774/42525 [44:53<38:41,  8.08it/s]

 56%|████████████████████▏               | 23776/42525 [44:53<36:38,  8.53it/s]

 56%|████████████████████▏               | 23779/42525 [44:53<39:19,  7.95it/s]

 56%|████████████████████▏               | 23782/42525 [44:54<34:18,  9.11it/s]

 56%|████████████████████▏               | 23784/42525 [44:54<35:58,  8.68it/s]

 56%|████████████████████▏               | 23787/42525 [44:54<36:17,  8.61it/s]

 56%|████████████████████▏               | 23789/42525 [44:54<38:36,  8.09it/s]

 56%|████████████████████▏               | 23792/42525 [44:55<35:59,  8.67it/s]

 56%|████████████████████▏               | 23794/42525 [44:55<37:46,  8.26it/s]

 56%|████████████████████▏               | 23797/42525 [44:55<35:38,  8.76it/s]

 56%|████████████████████▏               | 23799/42525 [44:55<35:09,  8.88it/s]

 56%|████████████████████▏               | 23801/42525 [44:56<33:10,  9.41it/s]

 56%|████████████████████▏               | 23804/42525 [44:56<34:39,  9.00it/s]

 56%|████████████████████▏               | 23805/42525 [44:56<37:19,  8.36it/s]

 56%|████████████████████▏               | 23809/42525 [44:57<35:05,  8.89it/s]

 56%|████████████████████▏               | 23811/42525 [44:57<36:54,  8.45it/s]

 56%|████████████████████▏               | 23813/42525 [44:57<35:47,  8.71it/s]

 56%|████████████████████▏               | 23816/42525 [44:57<33:32,  9.30it/s]

 56%|████████████████████▏               | 23819/42525 [44:58<37:31,  8.31it/s]

 56%|████████████████████▏               | 23821/42525 [44:58<35:38,  8.75it/s]

 56%|████████████████████▏               | 23823/42525 [44:58<40:40,  7.66it/s]

 56%|████████████████████▏               | 23824/42525 [44:58<38:01,  8.20it/s]

 56%|████████████████████▏               | 23828/42525 [44:59<35:05,  8.88it/s]

 56%|████████████████████▏               | 23831/42525 [44:59<34:44,  8.97it/s]

 56%|████████████████████▏               | 23833/42525 [44:59<37:19,  8.35it/s]

 56%|████████████████████▏               | 23836/42525 [45:00<35:20,  8.81it/s]

 56%|████████████████████▏               | 23837/42525 [45:00<36:00,  8.65it/s]

 56%|████████████████████▏               | 23840/42525 [45:00<35:36,  8.74it/s]

 56%|████████████████████▏               | 23844/42525 [45:01<32:12,  9.67it/s]

 56%|████████████████████▏               | 23847/42525 [45:01<34:35,  9.00it/s]

 56%|████████████████████▏               | 23849/42525 [45:01<36:01,  8.64it/s]

 56%|████████████████████▏               | 23853/42525 [45:02<32:25,  9.60it/s]

 56%|████████████████████▏               | 23857/42525 [45:02<31:22,  9.92it/s]

 56%|████████████████████▏               | 23860/42525 [45:02<32:48,  9.48it/s]

 56%|████████████████████▏               | 23862/42525 [45:03<35:45,  8.70it/s]

 56%|████████████████████▏               | 23863/42525 [45:03<34:41,  8.96it/s]

 56%|████████████████████▏               | 23866/42525 [45:03<33:11,  9.37it/s]

 56%|████████████████████▏               | 23868/42525 [45:03<35:10,  8.84it/s]

 56%|████████████████████▏               | 23870/42525 [45:03<33:35,  9.26it/s]

 56%|████████████████████▏               | 23873/42525 [45:04<36:55,  8.42it/s]

 56%|████████████████████▏               | 23876/42525 [45:04<37:01,  8.39it/s]

 56%|████████████████████▏               | 23879/42525 [45:05<39:19,  7.90it/s]

 56%|████████████████████▏               | 23881/42525 [45:05<40:26,  7.68it/s]

 56%|████████████████████▏               | 23884/42525 [45:05<36:56,  8.41it/s]

 56%|████████████████████▏               | 23888/42525 [45:06<32:47,  9.47it/s]

 56%|████████████████████▏               | 23890/42525 [45:06<32:25,  9.58it/s]

 56%|████████████████████▏               | 23892/42525 [45:06<32:20,  9.60it/s]

 56%|████████████████████▏               | 23895/42525 [45:06<34:27,  9.01it/s]

 56%|████████████████████▏               | 23898/42525 [45:07<33:14,  9.34it/s]

 56%|████████████████████▏               | 23902/42525 [45:07<31:32,  9.84it/s]

 56%|████████████████████▏               | 23903/42525 [45:07<33:34,  9.24it/s]

 56%|████████████████████▏               | 23905/42525 [45:07<33:29,  9.27it/s]

 56%|████████████████████▏               | 23908/42525 [45:08<37:19,  8.31it/s]

 56%|████████████████████▏               | 23911/42525 [45:08<34:57,  8.87it/s]

 56%|████████████████████▏               | 23913/42525 [45:08<34:07,  9.09it/s]

 56%|████████████████████▏               | 23916/42525 [45:09<35:44,  8.68it/s]

 56%|████████████████████▏               | 23919/42525 [45:09<34:02,  9.11it/s]

 56%|████████████████████▎               | 23921/42525 [45:09<32:55,  9.42it/s]

 56%|████████████████████▎               | 23924/42525 [45:10<36:40,  8.45it/s]

 56%|████████████████████▎               | 23926/42525 [45:10<37:41,  8.22it/s]

 56%|████████████████████▎               | 23928/42525 [45:10<39:04,  7.93it/s]

 56%|████████████████████▎               | 23930/42525 [45:10<35:35,  8.71it/s]

 56%|████████████████████▎               | 23934/42525 [45:11<31:32,  9.82it/s]

 56%|████████████████████▎               | 23936/42525 [45:11<32:06,  9.65it/s]

 56%|████████████████████▎               | 23939/42525 [45:11<33:33,  9.23it/s]

 56%|████████████████████▎               | 23943/42525 [45:12<31:20,  9.88it/s]

 56%|████████████████████▎               | 23946/42525 [45:12<34:05,  9.08it/s]

 56%|████████████████████▎               | 23949/42525 [45:12<33:05,  9.35it/s]

 56%|████████████████████▎               | 23951/42525 [45:12<35:47,  8.65it/s]

 56%|████████████████████▎               | 23953/42525 [45:13<35:46,  8.65it/s]

 56%|████████████████████▎               | 23957/42525 [45:13<32:30,  9.52it/s]

 56%|████████████████████▎               | 23960/42525 [45:13<31:27,  9.83it/s]

 56%|████████████████████▎               | 23964/42525 [45:14<31:11,  9.92it/s]

 56%|████████████████████▎               | 23965/42525 [45:14<34:01,  9.09it/s]

 56%|████████████████████▎               | 23968/42525 [45:14<32:50,  9.42it/s]

 56%|████████████████████▎               | 23971/42525 [45:15<32:41,  9.46it/s]

 56%|████████████████████▎               | 23975/42525 [45:15<30:58,  9.98it/s]

 56%|████████████████████▎               | 23977/42525 [45:15<32:22,  9.55it/s]

 56%|████████████████████▎               | 23981/42525 [45:16<31:18,  9.87it/s]

 56%|████████████████████▎               | 23984/42525 [45:16<33:26,  9.24it/s]

 56%|████████████████████▎               | 23988/42525 [45:16<33:07,  9.32it/s]

 56%|████████████████████▎               | 23990/42525 [45:17<32:04,  9.63it/s]

 56%|████████████████████▎               | 23994/42525 [45:17<31:50,  9.70it/s]

 56%|████████████████████▎               | 23998/42525 [45:17<30:47, 10.03it/s]

 56%|████████████████████▎               | 24001/42525 [45:18<33:58,  9.09it/s]

 56%|████████████████████▎               | 24002/42525 [45:18<35:19,  8.74it/s]

 56%|████████████████████▎               | 24006/42525 [45:18<32:37,  9.46it/s]

 56%|████████████████████▎               | 24010/42525 [45:19<32:30,  9.49it/s]

 56%|████████████████████▎               | 24013/42525 [45:19<31:34,  9.77it/s]

 56%|████████████████████▎               | 24015/42525 [45:19<30:54,  9.98it/s]

 56%|████████████████████▎               | 24017/42525 [45:19<32:34,  9.47it/s]

 56%|████████████████████▎               | 24021/42525 [45:20<32:49,  9.39it/s]

 56%|████████████████████▎               | 24025/42525 [45:20<31:01,  9.94it/s]

 57%|████████████████████▎               | 24027/42525 [45:21<33:12,  9.28it/s]

 57%|████████████████████▎               | 24030/42525 [45:21<35:47,  8.61it/s]

 57%|████████████████████▎               | 24033/42525 [45:21<36:12,  8.51it/s]

 57%|████████████████████▎               | 24036/42525 [45:22<35:08,  8.77it/s]

 57%|████████████████████▎               | 24039/42525 [45:22<33:42,  9.14it/s]

 57%|████████████████████▎               | 24042/42525 [45:22<34:51,  8.84it/s]

 57%|████████████████████▎               | 24045/42525 [45:23<34:16,  8.99it/s]

 57%|████████████████████▎               | 24049/42525 [45:23<31:44,  9.70it/s]

 57%|████████████████████▎               | 24051/42525 [45:23<32:42,  9.41it/s]

 57%|████████████████████▎               | 24053/42525 [45:23<38:36,  7.98it/s]

 57%|████████████████████▎               | 24055/42525 [45:24<35:18,  8.72it/s]

 57%|████████████████████▎               | 24058/42525 [45:24<32:25,  9.49it/s]

 57%|████████████████████▎               | 24061/42525 [45:24<33:12,  9.27it/s]

 57%|████████████████████▎               | 24063/42525 [45:24<31:36,  9.74it/s]

 57%|████████████████████▎               | 24066/42525 [45:25<35:10,  8.75it/s]

 57%|████████████████████▍               | 24069/42525 [45:25<34:15,  8.98it/s]

 57%|████████████████████▍               | 24071/42525 [45:25<34:52,  8.82it/s]

 57%|████████████████████▍               | 24075/42525 [45:26<31:37,  9.72it/s]

 57%|████████████████████▍               | 24078/42525 [45:26<31:22,  9.80it/s]

 57%|████████████████████▍               | 24081/42525 [45:26<30:56,  9.94it/s]

 57%|████████████████████▍               | 24084/42525 [45:27<31:18,  9.82it/s]

 57%|████████████████████▍               | 24086/42525 [45:27<35:22,  8.69it/s]

 57%|████████████████████▍               | 24087/42525 [45:27<37:53,  8.11it/s]

 57%|████████████████████▍               | 24090/42525 [45:27<35:46,  8.59it/s]

 57%|████████████████████▍               | 24092/42525 [45:28<38:30,  7.98it/s]

 57%|████████████████████▍               | 24094/42525 [45:28<34:33,  8.89it/s]

 57%|████████████████████▍               | 24097/42525 [45:28<34:58,  8.78it/s]

 57%|████████████████████▍               | 24100/42525 [45:29<32:20,  9.50it/s]

 57%|████████████████████▍               | 24101/42525 [45:29<32:30,  9.45it/s]

 57%|████████████████████▍               | 24105/42525 [45:29<31:34,  9.72it/s]

 57%|████████████████████▍               | 24109/42525 [45:29<30:25, 10.09it/s]

 57%|████████████████████▍               | 24112/42525 [45:30<34:58,  8.77it/s]

 57%|████████████████████▍               | 24115/42525 [45:30<35:28,  8.65it/s]

 57%|████████████████████▍               | 24117/42525 [45:30<35:50,  8.56it/s]

 57%|████████████████████▍               | 24119/42525 [45:31<38:04,  8.06it/s]

 57%|████████████████████▍               | 24121/42525 [45:31<34:39,  8.85it/s]

 57%|████████████████████▍               | 24124/42525 [45:31<33:49,  9.07it/s]

 57%|████████████████████▍               | 24125/42525 [45:31<35:30,  8.64it/s]

 57%|████████████████████▍               | 24128/42525 [45:32<35:07,  8.73it/s]

 57%|████████████████████▍               | 24131/42525 [45:32<32:59,  9.29it/s]

 57%|████████████████████▍               | 24134/42525 [45:32<33:54,  9.04it/s]

 57%|████████████████████▍               | 24138/42525 [45:33<31:00,  9.88it/s]

 57%|████████████████████▍               | 24142/42525 [45:33<30:12, 10.14it/s]

 57%|████████████████████▍               | 24146/42525 [45:33<30:01, 10.20it/s]

 57%|████████████████████▍               | 24149/42525 [45:34<35:17,  8.68it/s]

 57%|████████████████████▍               | 24152/42525 [45:34<33:57,  9.02it/s]

 57%|████████████████████▍               | 24154/42525 [45:35<37:22,  8.19it/s]

 57%|████████████████████▍               | 24157/42525 [45:35<36:06,  8.48it/s]

 57%|████████████████████▍               | 24159/42525 [45:35<38:29,  7.95it/s]

 57%|████████████████████▍               | 24163/42525 [45:36<32:37,  9.38it/s]

 57%|████████████████████▍               | 24165/42525 [45:36<31:30,  9.71it/s]

 57%|████████████████████▍               | 24167/42525 [45:36<31:18,  9.77it/s]

 57%|████████████████████▍               | 24170/42525 [45:36<35:03,  8.72it/s]

 57%|████████████████████▍               | 24171/42525 [45:36<35:20,  8.66it/s]

 57%|████████████████████▍               | 24174/42525 [45:37<34:24,  8.89it/s]

 57%|████████████████████▍               | 24178/42525 [45:37<31:44,  9.63it/s]

 57%|████████████████████▍               | 24181/42525 [45:37<31:09,  9.81it/s]

 57%|████████████████████▍               | 24182/42525 [45:38<31:08,  9.82it/s]

 57%|████████████████████▍               | 24185/42525 [45:38<32:14,  9.48it/s]

 57%|████████████████████▍               | 24186/42525 [45:38<32:06,  9.52it/s]

 57%|████████████████████▍               | 24189/42525 [45:38<31:55,  9.57it/s]

 57%|████████████████████▍               | 24190/42525 [45:38<35:00,  8.73it/s]

 57%|████████████████████▍               | 24194/42525 [45:39<33:45,  9.05it/s]

 57%|████████████████████▍               | 24197/42525 [45:39<33:42,  9.06it/s]

 57%|████████████████████▍               | 24200/42525 [45:39<33:34,  9.10it/s]

 57%|████████████████████▍               | 24203/42525 [45:40<34:56,  8.74it/s]

 57%|████████████████████▍               | 24206/42525 [45:40<33:03,  9.24it/s]

 57%|████████████████████▍               | 24209/42525 [45:40<31:33,  9.67it/s]

 57%|████████████████████▍               | 24212/42525 [45:41<32:42,  9.33it/s]

 57%|████████████████████▍               | 24213/42525 [45:41<33:00,  9.25it/s]

 57%|████████████████████▌               | 24216/42525 [45:41<32:31,  9.38it/s]

 57%|████████████████████▌               | 24219/42525 [45:42<33:03,  9.23it/s]

 57%|████████████████████▌               | 24221/42525 [45:42<33:07,  9.21it/s]

 57%|████████████████████▌               | 24225/42525 [45:42<31:02,  9.83it/s]

 57%|████████████████████▌               | 24227/42525 [45:42<30:25, 10.02it/s]

 57%|████████████████████▌               | 24229/42525 [45:43<31:22,  9.72it/s]

 57%|████████████████████▌               | 24232/42525 [45:43<32:12,  9.47it/s]

 57%|████████████████████▌               | 24235/42525 [45:43<31:37,  9.64it/s]

 57%|████████████████████▌               | 24239/42525 [45:44<30:23, 10.03it/s]

 57%|████████████████████▌               | 24241/42525 [45:44<34:00,  8.96it/s]

 57%|████████████████████▌               | 24243/42525 [45:44<33:49,  9.01it/s]

 57%|████████████████████▌               | 24246/42525 [45:44<31:58,  9.53it/s]

 57%|████████████████████▌               | 24249/42525 [45:45<31:22,  9.71it/s]

 57%|████████████████████▌               | 24253/42525 [45:45<30:27, 10.00it/s]

 57%|████████████████████▌               | 24255/42525 [45:45<34:40,  8.78it/s]

 57%|████████████████████▌               | 24259/42525 [45:46<33:36,  9.06it/s]

 57%|████████████████████▌               | 24261/42525 [45:46<35:54,  8.48it/s]

 57%|████████████████████▌               | 24265/42525 [45:46<32:01,  9.50it/s]

 57%|████████████████████▌               | 24267/42525 [45:47<35:03,  8.68it/s]

 57%|████████████████████▌               | 24269/42525 [45:47<36:00,  8.45it/s]

 57%|████████████████████▌               | 24271/42525 [45:47<34:22,  8.85it/s]

 57%|████████████████████▌               | 24274/42525 [45:47<32:59,  9.22it/s]

 57%|████████████████████▌               | 24277/42525 [45:48<33:16,  9.14it/s]

 57%|████████████████████▌               | 24280/42525 [45:48<32:54,  9.24it/s]

 57%|████████████████████▌               | 24283/42525 [45:48<34:18,  8.86it/s]

 57%|████████████████████▌               | 24285/42525 [45:49<32:26,  9.37it/s]

 57%|████████████████████▌               | 24288/42525 [45:49<34:37,  8.78it/s]

 57%|████████████████████▌               | 24291/42525 [45:49<32:15,  9.42it/s]

 57%|████████████████████▌               | 24294/42525 [45:50<31:24,  9.67it/s]

 57%|████████████████████▌               | 24298/42525 [45:50<30:21, 10.01it/s]

 57%|████████████████████▌               | 24302/42525 [45:50<29:51, 10.17it/s]

 57%|████████████████████▌               | 24304/42525 [45:51<30:15, 10.03it/s]

 57%|████████████████████▌               | 24307/42525 [45:51<33:52,  8.96it/s]

 57%|████████████████████▌               | 24309/42525 [45:51<37:04,  8.19it/s]

 57%|████████████████████▌               | 24312/42525 [45:52<33:35,  9.04it/s]

 57%|████████████████████▌               | 24314/42525 [45:52<36:03,  8.42it/s]

 57%|████████████████████▌               | 24316/42525 [45:52<37:02,  8.19it/s]

 57%|████████████████████▌               | 24319/42525 [45:52<32:44,  9.27it/s]

 57%|████████████████████▌               | 24321/42525 [45:53<33:49,  8.97it/s]

 57%|████████████████████▌               | 24323/42525 [45:53<33:49,  8.97it/s]

 57%|████████████████████▌               | 24326/42525 [45:53<31:43,  9.56it/s]

 57%|████████████████████▌               | 24328/42525 [45:53<31:23,  9.66it/s]

 57%|████████████████████▌               | 24330/42525 [45:54<33:22,  9.09it/s]

 57%|████████████████████▌               | 24332/42525 [45:54<33:24,  9.08it/s]

 57%|████████████████████▌               | 24336/42525 [45:54<30:54,  9.81it/s]

 57%|████████████████████▌               | 24338/42525 [45:54<33:09,  9.14it/s]

 57%|████████████████████▌               | 24340/42525 [45:55<32:52,  9.22it/s]

 57%|████████████████████▌               | 24342/42525 [45:55<32:28,  9.33it/s]

 57%|████████████████████▌               | 24344/42525 [45:55<34:28,  8.79it/s]

 57%|████████████████████▌               | 24348/42525 [45:56<33:35,  9.02it/s]

 57%|████████████████████▌               | 24350/42525 [45:56<36:51,  8.22it/s]

 57%|████████████████████▌               | 24352/42525 [45:56<36:04,  8.40it/s]

 57%|████████████████████▌               | 24356/42525 [45:56<31:58,  9.47it/s]

 57%|████████████████████▌               | 24358/42525 [45:57<34:05,  8.88it/s]

 57%|████████████████████▌               | 24360/42525 [45:57<36:11,  8.37it/s]

 57%|████████████████████▌               | 24363/42525 [45:57<35:56,  8.42it/s]

 57%|████████████████████▋               | 24365/42525 [45:57<34:40,  8.73it/s]

 57%|████████████████████▋               | 24368/42525 [45:58<34:36,  8.75it/s]

 57%|████████████████████▋               | 24371/42525 [45:58<35:01,  8.64it/s]

 57%|████████████████████▋               | 24375/42525 [45:59<31:36,  9.57it/s]

 57%|████████████████████▋               | 24378/42525 [45:59<31:22,  9.64it/s]

 57%|████████████████████▋               | 24381/42525 [45:59<30:27,  9.93it/s]

 57%|████████████████████▋               | 24385/42525 [46:00<29:36, 10.21it/s]

 57%|████████████████████▋               | 24388/42525 [46:00<31:01,  9.75it/s]

 57%|████████████████████▋               | 24390/42525 [46:00<30:14,  9.99it/s]

 57%|████████████████████▋               | 24393/42525 [46:00<31:44,  9.52it/s]

 57%|████████████████████▋               | 24396/42525 [46:01<32:16,  9.36it/s]

 57%|████████████████████▋               | 24399/42525 [46:01<32:10,  9.39it/s]

 57%|████████████████████▋               | 24402/42525 [46:01<34:06,  8.86it/s]

 57%|████████████████████▋               | 24404/42525 [46:02<32:27,  9.31it/s]

 57%|████████████████████▋               | 24407/42525 [46:02<33:27,  9.03it/s]

 57%|████████████████████▋               | 24410/42525 [46:02<31:57,  9.45it/s]

 57%|████████████████████▋               | 24413/42525 [46:03<30:39,  9.85it/s]

 57%|████████████████████▋               | 24417/42525 [46:03<31:34,  9.56it/s]

 57%|████████████████████▋               | 24420/42525 [46:03<30:56,  9.75it/s]

 57%|████████████████████▋               | 24423/42525 [46:04<30:23,  9.93it/s]

 57%|████████████████████▋               | 24425/42525 [46:04<29:52, 10.10it/s]

 57%|████████████████████▋               | 24427/42525 [46:04<33:09,  9.10it/s]

 57%|████████████████████▋               | 24430/42525 [46:04<33:36,  8.97it/s]

 57%|████████████████████▋               | 24431/42525 [46:04<35:52,  8.41it/s]

 57%|████████████████████▋               | 24433/42525 [46:05<36:14,  8.32it/s]

 57%|████████████████████▋               | 24436/42525 [46:05<36:10,  8.33it/s]

 57%|████████████████████▋               | 24438/42525 [46:05<34:25,  8.76it/s]

 57%|████████████████████▋               | 24442/42525 [46:06<33:02,  9.12it/s]

 57%|████████████████████▋               | 24444/42525 [46:06<34:34,  8.71it/s]

 57%|████████████████████▋               | 24447/42525 [46:06<37:31,  8.03it/s]

 57%|████████████████████▋               | 24449/42525 [46:07<35:19,  8.53it/s]

 57%|████████████████████▋               | 24451/42525 [46:07<39:48,  7.57it/s]

 58%|████████████████████▋               | 24454/42525 [46:07<36:05,  8.34it/s]

 58%|████████████████████▋               | 24457/42525 [46:08<36:13,  8.31it/s]

 58%|████████████████████▋               | 24460/42525 [46:08<33:12,  9.07it/s]

 58%|████████████████████▋               | 24463/42525 [46:08<34:27,  8.74it/s]

 58%|████████████████████▋               | 24466/42525 [46:09<32:16,  9.33it/s]

 58%|████████████████████▋               | 24469/42525 [46:09<31:00,  9.71it/s]

 58%|████████████████████▋               | 24471/42525 [46:09<31:21,  9.59it/s]

 58%|████████████████████▋               | 24474/42525 [46:09<33:42,  8.93it/s]

 58%|████████████████████▋               | 24476/42525 [46:10<36:05,  8.34it/s]

 58%|████████████████████▋               | 24479/42525 [46:10<35:52,  8.38it/s]

 58%|████████████████████▋               | 24481/42525 [46:10<33:05,  9.09it/s]

 58%|████████████████████▋               | 24483/42525 [46:10<33:05,  9.09it/s]

 58%|████████████████████▋               | 24487/42525 [46:11<31:23,  9.58it/s]

 58%|████████████████████▋               | 24489/42525 [46:11<31:34,  9.52it/s]

 58%|████████████████████▋               | 24492/42525 [46:11<33:37,  8.94it/s]

 58%|████████████████████▋               | 24494/42525 [46:12<34:59,  8.59it/s]

 58%|████████████████████▋               | 24496/42525 [46:12<35:00,  8.58it/s]

 58%|████████████████████▋               | 24499/42525 [46:12<32:56,  9.12it/s]

 58%|████████████████████▋               | 24502/42525 [46:13<33:11,  9.05it/s]

 58%|████████████████████▋               | 24505/42525 [46:13<33:04,  9.08it/s]

 58%|████████████████████▋               | 24509/42525 [46:13<30:44,  9.77it/s]

 58%|████████████████████▊               | 24512/42525 [46:14<32:24,  9.26it/s]

 58%|████████████████████▊               | 24515/42525 [46:14<32:34,  9.21it/s]

 58%|████████████████████▊               | 24518/42525 [46:14<33:07,  9.06it/s]

 58%|████████████████████▊               | 24521/42525 [46:15<34:19,  8.74it/s]

 58%|████████████████████▊               | 24523/42525 [46:15<38:44,  7.74it/s]

 58%|████████████████████▊               | 24525/42525 [46:15<37:27,  8.01it/s]

 58%|████████████████████▊               | 24527/42525 [46:15<39:10,  7.66it/s]

 58%|████████████████████▊               | 24530/42525 [46:16<33:35,  8.93it/s]

 58%|████████████████████▊               | 24532/42525 [46:16<32:43,  9.17it/s]

 58%|████████████████████▊               | 24535/42525 [46:16<34:32,  8.68it/s]

 58%|████████████████████▊               | 24539/42525 [46:17<31:18,  9.58it/s]

 58%|████████████████████▊               | 24542/42525 [46:17<31:17,  9.58it/s]

 58%|████████████████████▊               | 24546/42525 [46:17<30:11,  9.93it/s]

 58%|████████████████████▊               | 24548/42525 [46:18<31:32,  9.50it/s]

 58%|████████████████████▊               | 24550/42525 [46:18<31:29,  9.51it/s]

 58%|████████████████████▊               | 24552/42525 [46:18<35:04,  8.54it/s]

 58%|████████████████████▊               | 24554/42525 [46:18<35:41,  8.39it/s]

 58%|████████████████████▊               | 24556/42525 [46:19<36:25,  8.22it/s]

 58%|████████████████████▊               | 24559/42525 [46:19<33:17,  9.00it/s]

 58%|████████████████████▊               | 24562/42525 [46:19<31:25,  9.53it/s]

 58%|████████████████████▊               | 24566/42525 [46:20<31:51,  9.39it/s]

 58%|████████████████████▊               | 24568/42525 [46:20<34:25,  8.69it/s]

 58%|████████████████████▊               | 24571/42525 [46:20<32:47,  9.12it/s]

 58%|████████████████████▊               | 24573/42525 [46:20<35:43,  8.38it/s]

 58%|████████████████████▊               | 24576/42525 [46:21<32:57,  9.07it/s]

 58%|████████████████████▊               | 24578/42525 [46:21<33:24,  8.95it/s]

 58%|████████████████████▊               | 24581/42525 [46:21<31:33,  9.48it/s]

 58%|████████████████████▊               | 24585/42525 [46:22<31:05,  9.62it/s]

 58%|████████████████████▊               | 24587/42525 [46:22<33:16,  8.98it/s]

 58%|████████████████████▊               | 24589/42525 [46:22<35:34,  8.40it/s]

 58%|████████████████████▊               | 24592/42525 [46:23<33:24,  8.95it/s]

 58%|████████████████████▊               | 24596/42525 [46:23<32:37,  9.16it/s]

 58%|████████████████████▊               | 24599/42525 [46:23<33:51,  8.82it/s]

 58%|████████████████████▊               | 24601/42525 [46:23<32:07,  9.30it/s]

 58%|████████████████████▊               | 24603/42525 [46:24<33:39,  8.87it/s]

 58%|████████████████████▊               | 24607/42525 [46:24<32:55,  9.07it/s]

 58%|████████████████████▊               | 24610/42525 [46:25<33:15,  8.98it/s]

 58%|████████████████████▊               | 24613/42525 [46:25<31:22,  9.51it/s]

 58%|████████████████████▊               | 24615/42525 [46:25<36:30,  8.18it/s]

 58%|████████████████████▊               | 24617/42525 [46:25<39:16,  7.60it/s]

 58%|████████████████████▊               | 24619/42525 [46:26<35:19,  8.45it/s]

 58%|████████████████████▊               | 24622/42525 [46:26<32:15,  9.25it/s]

 58%|████████████████████▊               | 24625/42525 [46:26<32:22,  9.21it/s]

 58%|████████████████████▊               | 24627/42525 [46:27<34:35,  8.62it/s]

 58%|████████████████████▊               | 24631/42525 [46:27<31:26,  9.49it/s]

 58%|████████████████████▊               | 24635/42525 [46:27<29:59,  9.94it/s]

 58%|████████████████████▊               | 24638/42525 [46:28<32:35,  9.15it/s]

 58%|████████████████████▊               | 24640/42525 [46:28<31:11,  9.56it/s]

 58%|████████████████████▊               | 24643/42525 [46:28<32:28,  9.18it/s]

 58%|████████████████████▊               | 24645/42525 [46:28<34:48,  8.56it/s]

 58%|████████████████████▊               | 24648/42525 [46:29<32:50,  9.07it/s]

 58%|████████████████████▊               | 24650/42525 [46:29<34:21,  8.67it/s]

 58%|████████████████████▊               | 24652/42525 [46:29<33:42,  8.84it/s]

 58%|████████████████████▊               | 24654/42525 [46:29<32:41,  9.11it/s]

 58%|████████████████████▊               | 24657/42525 [46:30<34:15,  8.69it/s]

 58%|████████████████████▉               | 24659/42525 [46:30<35:01,  8.50it/s]

 58%|████████████████████▉               | 24661/42525 [46:30<32:28,  9.17it/s]

 58%|████████████████████▉               | 24664/42525 [46:31<34:44,  8.57it/s]

 58%|████████████████████▉               | 24666/42525 [46:31<36:03,  8.25it/s]

 58%|████████████████████▉               | 24669/42525 [46:31<34:37,  8.60it/s]

 58%|████████████████████▉               | 24673/42525 [46:32<31:06,  9.57it/s]

 58%|████████████████████▉               | 24675/42525 [46:32<30:37,  9.71it/s]

 58%|████████████████████▉               | 24678/42525 [46:32<30:38,  9.71it/s]

 58%|████████████████████▉               | 24681/42525 [46:32<32:46,  9.07it/s]

 58%|████████████████████▉               | 24684/42525 [46:33<34:07,  8.71it/s]

 58%|████████████████████▉               | 24686/42525 [46:33<32:10,  9.24it/s]

 58%|████████████████████▉               | 24690/42525 [46:33<30:52,  9.63it/s]

 58%|████████████████████▉               | 24693/42525 [46:34<32:59,  9.01it/s]

 58%|████████████████████▉               | 24697/42525 [46:34<30:59,  9.59it/s]

 58%|████████████████████▉               | 24698/42525 [46:34<31:06,  9.55it/s]

 58%|████████████████████▉               | 24701/42525 [46:35<31:34,  9.41it/s]

 58%|████████████████████▉               | 24704/42525 [46:35<32:10,  9.23it/s]

 58%|████████████████████▉               | 24707/42525 [46:35<32:25,  9.16it/s]

 58%|████████████████████▉               | 24710/42525 [46:36<31:42,  9.37it/s]

 58%|████████████████████▉               | 24712/42525 [46:36<34:51,  8.52it/s]

 58%|████████████████████▉               | 24714/42525 [46:36<37:15,  7.97it/s]

 58%|████████████████████▉               | 24716/42525 [46:36<36:57,  8.03it/s]

 58%|████████████████████▉               | 24718/42525 [46:37<39:44,  7.47it/s]

 58%|████████████████████▉               | 24720/42525 [46:37<40:01,  7.42it/s]

 58%|████████████████████▉               | 24723/42525 [46:37<34:00,  8.72it/s]

 58%|████████████████████▉               | 24725/42525 [46:37<32:06,  9.24it/s]

 58%|████████████████████▉               | 24727/42525 [46:38<32:50,  9.03it/s]

 58%|████████████████████▉               | 24731/42525 [46:38<31:51,  9.31it/s]

 58%|████████████████████▉               | 24735/42525 [46:38<30:29,  9.72it/s]

 58%|████████████████████▉               | 24738/42525 [46:39<31:20,  9.46it/s]

 58%|████████████████████▉               | 24741/42525 [46:39<30:13,  9.80it/s]

 58%|████████████████████▉               | 24743/42525 [46:39<32:17,  9.18it/s]

 58%|████████████████████▉               | 24746/42525 [46:40<32:38,  9.08it/s]

 58%|████████████████████▉               | 24749/42525 [46:40<31:19,  9.46it/s]

 58%|████████████████████▉               | 24753/42525 [46:40<30:08,  9.83it/s]

 58%|████████████████████▉               | 24756/42525 [46:41<32:24,  9.14it/s]

 58%|████████████████████▉               | 24759/42525 [46:41<31:12,  9.49it/s]

 58%|████████████████████▉               | 24763/42525 [46:41<29:50,  9.92it/s]

 58%|████████████████████▉               | 24767/42525 [46:42<29:05, 10.17it/s]

 58%|████████████████████▉               | 24770/42525 [46:42<30:00,  9.86it/s]

 58%|████████████████████▉               | 24773/42525 [46:42<29:35, 10.00it/s]

 58%|████████████████████▉               | 24775/42525 [46:43<29:38,  9.98it/s]

 58%|████████████████████▉               | 24777/42525 [46:43<31:10,  9.49it/s]

 58%|████████████████████▉               | 24780/42525 [46:43<30:05,  9.83it/s]

 58%|████████████████████▉               | 24783/42525 [46:43<31:25,  9.41it/s]

 58%|████████████████████▉               | 24785/42525 [46:44<32:37,  9.06it/s]

 58%|████████████████████▉               | 24789/42525 [46:44<31:29,  9.39it/s]

 58%|████████████████████▉               | 24791/42525 [46:44<31:21,  9.42it/s]

 58%|████████████████████▉               | 24793/42525 [46:45<36:49,  8.02it/s]

 58%|████████████████████▉               | 24796/42525 [46:45<33:58,  8.70it/s]

 58%|████████████████████▉               | 24798/42525 [46:45<35:51,  8.24it/s]

 58%|████████████████████▉               | 24800/42525 [46:45<34:11,  8.64it/s]

 58%|████████████████████▉               | 24802/42525 [46:46<38:17,  7.71it/s]

 58%|████████████████████▉               | 24805/42525 [46:46<34:07,  8.66it/s]

 58%|█████████████████████               | 24809/42525 [46:46<32:52,  8.98it/s]

 58%|█████████████████████               | 24811/42525 [46:47<32:11,  9.17it/s]

 58%|█████████████████████               | 24813/42525 [46:47<35:20,  8.35it/s]

 58%|█████████████████████               | 24816/42525 [46:47<31:33,  9.35it/s]

 58%|█████████████████████               | 24817/42525 [46:47<31:13,  9.45it/s]

 58%|█████████████████████               | 24820/42525 [46:48<30:51,  9.56it/s]

 58%|█████████████████████               | 24822/42525 [46:48<36:37,  8.05it/s]

 58%|█████████████████████               | 24824/42525 [46:48<36:02,  8.18it/s]

 58%|█████████████████████               | 24826/42525 [46:48<33:59,  8.68it/s]

 58%|█████████████████████               | 24828/42525 [46:49<36:06,  8.17it/s]

 58%|█████████████████████               | 24830/42525 [46:49<33:45,  8.73it/s]

 58%|█████████████████████               | 24832/42525 [46:49<32:58,  8.94it/s]

 58%|█████████████████████               | 24835/42525 [46:49<35:33,  8.29it/s]

 58%|█████████████████████               | 24837/42525 [46:50<37:34,  7.84it/s]

 58%|█████████████████████               | 24840/42525 [46:50<34:12,  8.62it/s]

 58%|█████████████████████               | 24842/42525 [46:50<32:37,  9.04it/s]

 58%|█████████████████████               | 24846/42525 [46:51<29:52,  9.86it/s]

 58%|█████████████████████               | 24849/42525 [46:51<31:51,  9.25it/s]

 58%|█████████████████████               | 24851/42525 [46:51<32:33,  9.05it/s]

 58%|█████████████████████               | 24853/42525 [46:51<33:53,  8.69it/s]

 58%|█████████████████████               | 24856/42525 [46:52<32:21,  9.10it/s]

 58%|█████████████████████               | 24858/42525 [46:52<32:01,  9.19it/s]

 58%|█████████████████████               | 24861/42525 [46:52<30:10,  9.76it/s]

 58%|█████████████████████               | 24862/42525 [46:52<31:12,  9.43it/s]

 58%|█████████████████████               | 24866/42525 [46:53<31:23,  9.38it/s]

 58%|█████████████████████               | 24868/42525 [46:53<31:58,  9.20it/s]

 58%|█████████████████████               | 24870/42525 [46:53<30:24,  9.68it/s]

 58%|█████████████████████               | 24873/42525 [46:54<34:05,  8.63it/s]

 58%|█████████████████████               | 24876/42525 [46:54<34:32,  8.52it/s]

 59%|█████████████████████               | 24880/42525 [46:54<31:16,  9.40it/s]

 59%|█████████████████████               | 24881/42525 [46:54<31:17,  9.40it/s]

 59%|█████████████████████               | 24884/42525 [46:55<31:37,  9.30it/s]

 59%|█████████████████████               | 24887/42525 [46:55<30:41,  9.58it/s]

 59%|█████████████████████               | 24889/42525 [46:55<33:41,  8.72it/s]

 59%|█████████████████████               | 24891/42525 [46:56<33:28,  8.78it/s]

 59%|█████████████████████               | 24895/42525 [46:56<32:24,  9.06it/s]

 59%|█████████████████████               | 24897/42525 [46:56<31:10,  9.42it/s]

 59%|█████████████████████               | 24900/42525 [46:57<32:26,  9.06it/s]

 59%|█████████████████████               | 24903/42525 [46:57<33:32,  8.76it/s]

 59%|█████████████████████               | 24907/42525 [46:57<30:38,  9.58it/s]

 59%|█████████████████████               | 24910/42525 [46:58<32:30,  9.03it/s]

 59%|█████████████████████               | 24913/42525 [46:58<33:57,  8.65it/s]

 59%|█████████████████████               | 24915/42525 [46:58<34:47,  8.44it/s]

 59%|█████████████████████               | 24917/42525 [46:58<35:45,  8.21it/s]

 59%|█████████████████████               | 24918/42525 [46:59<35:34,  8.25it/s]

 59%|█████████████████████               | 24921/42525 [46:59<35:20,  8.30it/s]

 59%|█████████████████████               | 24923/42525 [46:59<36:17,  8.08it/s]

 59%|█████████████████████               | 24927/42525 [47:00<31:30,  9.31it/s]

 59%|█████████████████████               | 24930/42525 [47:00<31:21,  9.35it/s]

 59%|█████████████████████               | 24931/42525 [47:00<34:02,  8.61it/s]

 59%|█████████████████████               | 24935/42525 [47:00<32:02,  9.15it/s]

 59%|█████████████████████               | 24939/42525 [47:01<29:55,  9.79it/s]

 59%|█████████████████████               | 24941/42525 [47:01<32:19,  9.06it/s]

 59%|█████████████████████               | 24944/42525 [47:01<32:16,  9.08it/s]

 59%|█████████████████████               | 24946/42525 [47:02<31:23,  9.33it/s]

 59%|█████████████████████               | 24948/42525 [47:02<32:50,  8.92it/s]

 59%|█████████████████████               | 24951/42525 [47:02<30:36,  9.57it/s]

 59%|█████████████████████               | 24952/42525 [47:02<30:16,  9.67it/s]

 59%|█████████████████████▏              | 24956/42525 [47:03<31:05,  9.42it/s]

 59%|█████████████████████▏              | 24959/42525 [47:03<29:52,  9.80it/s]

 59%|█████████████████████▏              | 24961/42525 [47:03<30:00,  9.76it/s]

 59%|█████████████████████▏              | 24963/42525 [47:03<33:50,  8.65it/s]

 59%|█████████████████████▏              | 24964/42525 [47:04<34:32,  8.47it/s]

 59%|█████████████████████▏              | 24967/42525 [47:04<34:28,  8.49it/s]

 59%|█████████████████████▏              | 24969/42525 [47:04<33:19,  8.78it/s]

 59%|█████████████████████▏              | 24970/42525 [47:04<35:51,  8.16it/s]

 59%|█████████████████████▏              | 24973/42525 [47:05<34:46,  8.41it/s]

 59%|█████████████████████▏              | 24975/42525 [47:05<34:07,  8.57it/s]

 59%|█████████████████████▏              | 24977/42525 [47:05<35:53,  8.15it/s]

 59%|█████████████████████▏              | 24979/42525 [47:05<33:02,  8.85it/s]

 59%|█████████████████████▏              | 24980/42525 [47:05<31:59,  9.14it/s]

 59%|█████████████████████▏              | 24982/42525 [47:06<31:45,  9.21it/s]

 59%|█████████████████████▏              | 24985/42525 [47:06<32:44,  8.93it/s]

 59%|█████████████████████▏              | 24987/42525 [47:06<34:52,  8.38it/s]

 59%|█████████████████████▏              | 24988/42525 [47:06<33:25,  8.75it/s]

 59%|█████████████████████▏              | 24991/42525 [47:07<35:26,  8.25it/s]

 59%|█████████████████████▏              | 24994/42525 [47:07<32:11,  9.08it/s]

 59%|█████████████████████▏              | 24997/42525 [47:07<32:21,  9.03it/s]

 59%|█████████████████████▏              | 24999/42525 [47:08<33:00,  8.85it/s]

 59%|█████████████████████▏              | 25001/42525 [47:08<34:06,  8.56it/s]

 59%|█████████████████████▏              | 25003/42525 [47:08<34:34,  8.45it/s]

 59%|█████████████████████▏              | 25007/42525 [47:09<30:35,  9.54it/s]

 59%|█████████████████████▏              | 25009/42525 [47:09<33:46,  8.65it/s]

 59%|█████████████████████▏              | 25011/42525 [47:09<35:37,  8.20it/s]

 59%|█████████████████████▏              | 25014/42525 [47:09<31:44,  9.19it/s]

 59%|█████████████████████▏              | 25018/42525 [47:10<29:59,  9.73it/s]

 59%|█████████████████████▏              | 25021/42525 [47:10<32:31,  8.97it/s]

 59%|█████████████████████▏              | 25023/42525 [47:10<32:22,  9.01it/s]

 59%|█████████████████████▏              | 25025/42525 [47:11<33:38,  8.67it/s]

 59%|█████████████████████▏              | 25027/42525 [47:11<32:45,  8.90it/s]

 59%|█████████████████████▏              | 25028/42525 [47:11<35:02,  8.32it/s]

 59%|█████████████████████▏              | 25032/42525 [47:11<31:10,  9.35it/s]

 59%|█████████████████████▏              | 25034/42525 [47:12<33:07,  8.80it/s]

 59%|█████████████████████▏              | 25036/42525 [47:12<32:22,  9.00it/s]

 59%|█████████████████████▏              | 25040/42525 [47:12<30:40,  9.50it/s]

 59%|█████████████████████▏              | 25043/42525 [47:12<29:39,  9.82it/s]

 59%|█████████████████████▏              | 25046/42525 [47:13<29:05, 10.01it/s]

 59%|█████████████████████▏              | 25048/42525 [47:13<28:49, 10.10it/s]

 59%|█████████████████████▏              | 25051/42525 [47:13<31:51,  9.14it/s]

 59%|█████████████████████▏              | 25054/42525 [47:14<32:04,  9.08it/s]

 59%|█████████████████████▏              | 25056/42525 [47:14<32:47,  8.88it/s]

 59%|█████████████████████▏              | 25058/42525 [47:14<34:52,  8.35it/s]

 59%|█████████████████████▏              | 25061/42525 [47:14<32:05,  9.07it/s]

 59%|█████████████████████▏              | 25062/42525 [47:15<32:27,  8.97it/s]

 59%|█████████████████████▏              | 25065/42525 [47:15<31:54,  9.12it/s]

 59%|█████████████████████▏              | 25069/42525 [47:15<29:38,  9.82it/s]

 59%|█████████████████████▏              | 25073/42525 [47:16<29:48,  9.76it/s]

 59%|█████████████████████▏              | 25076/42525 [47:16<29:55,  9.72it/s]

 59%|█████████████████████▏              | 25077/42525 [47:16<31:20,  9.28it/s]

 59%|█████████████████████▏              | 25080/42525 [47:16<30:37,  9.49it/s]

 59%|█████████████████████▏              | 25084/42525 [47:17<29:14,  9.94it/s]

 59%|█████████████████████▏              | 25088/42525 [47:17<28:42, 10.13it/s]

 59%|█████████████████████▏              | 25090/42525 [47:17<29:25,  9.88it/s]

 59%|█████████████████████▏              | 25092/42525 [47:18<29:26,  9.87it/s]

 59%|█████████████████████▏              | 25095/42525 [47:18<32:06,  9.05it/s]

 59%|█████████████████████▏              | 25097/42525 [47:18<31:23,  9.25it/s]

 59%|█████████████████████▏              | 25100/42525 [47:18<30:28,  9.53it/s]

 59%|█████████████████████▎              | 25104/42525 [47:19<29:58,  9.69it/s]

 59%|█████████████████████▎              | 25108/42525 [47:19<30:01,  9.67it/s]

 59%|█████████████████████▎              | 25109/42525 [47:19<30:52,  9.40it/s]

 59%|█████████████████████▎              | 25112/42525 [47:20<33:16,  8.72it/s]

 59%|█████████████████████▎              | 25114/42525 [47:20<31:47,  9.13it/s]

 59%|█████████████████████▎              | 25118/42525 [47:20<30:16,  9.58it/s]

 59%|█████████████████████▎              | 25120/42525 [47:21<30:32,  9.50it/s]

 59%|█████████████████████▎              | 25123/42525 [47:21<29:56,  9.69it/s]

 59%|█████████████████████▎              | 25126/42525 [47:21<29:20,  9.88it/s]

 59%|█████████████████████▎              | 25128/42525 [47:21<31:06,  9.32it/s]

 59%|█████████████████████▎              | 25130/42525 [47:22<31:11,  9.30it/s]

 59%|█████████████████████▎              | 25131/42525 [47:22<31:54,  9.09it/s]

 59%|█████████████████████▎              | 25133/42525 [47:22<33:45,  8.59it/s]

 59%|█████████████████████▎              | 25137/42525 [47:22<31:48,  9.11it/s]

 59%|█████████████████████▎              | 25140/42525 [47:23<32:08,  9.01it/s]

 59%|█████████████████████▎              | 25141/42525 [47:23<34:21,  8.43it/s]

 59%|█████████████████████▎              | 25144/42525 [47:23<34:52,  8.31it/s]

 59%|█████████████████████▎              | 25147/42525 [47:24<33:23,  8.67it/s]

 59%|█████████████████████▎              | 25148/42525 [47:24<33:30,  8.64it/s]

 59%|█████████████████████▎              | 25151/42525 [47:24<34:22,  8.43it/s]

 59%|█████████████████████▎              | 25153/42525 [47:24<32:46,  8.83it/s]

 59%|█████████████████████▎              | 25156/42525 [47:25<30:14,  9.57it/s]

 59%|█████████████████████▎              | 25160/42525 [47:25<29:01,  9.97it/s]

 59%|█████████████████████▎              | 25164/42525 [47:25<28:41, 10.08it/s]

 59%|█████████████████████▎              | 25168/42525 [47:26<28:11, 10.26it/s]

 59%|█████████████████████▎              | 25172/42525 [47:26<28:56,  9.99it/s]

 59%|█████████████████████▎              | 25175/42525 [47:27<30:02,  9.62it/s]

 59%|█████████████████████▎              | 25178/42525 [47:27<31:17,  9.24it/s]

 59%|█████████████████████▎              | 25181/42525 [47:27<31:38,  9.14it/s]

 59%|█████████████████████▎              | 25183/42525 [47:27<34:10,  8.46it/s]

 59%|█████████████████████▎              | 25185/42525 [47:28<32:03,  9.01it/s]

 59%|█████████████████████▎              | 25188/42525 [47:28<35:25,  8.16it/s]

 59%|█████████████████████▎              | 25191/42525 [47:28<34:19,  8.42it/s]

 59%|█████████████████████▎              | 25194/42525 [47:29<31:34,  9.15it/s]

 59%|█████████████████████▎              | 25197/42525 [47:29<32:57,  8.76it/s]

 59%|█████████████████████▎              | 25200/42525 [47:29<30:29,  9.47it/s]

 59%|█████████████████████▎              | 25202/42525 [47:30<33:38,  8.58it/s]

 59%|█████████████████████▎              | 25206/42525 [47:30<30:33,  9.45it/s]

 59%|█████████████████████▎              | 25207/42525 [47:30<30:52,  9.35it/s]

 59%|█████████████████████▎              | 25211/42525 [47:31<31:16,  9.23it/s]

 59%|█████████████████████▎              | 25213/42525 [47:31<30:23,  9.49it/s]

 59%|█████████████████████▎              | 25215/42525 [47:31<30:05,  9.59it/s]

 59%|█████████████████████▎              | 25219/42525 [47:31<29:28,  9.79it/s]

 59%|█████████████████████▎              | 25221/42525 [47:32<31:59,  9.01it/s]

 59%|█████████████████████▎              | 25223/42525 [47:32<36:07,  7.98it/s]

 59%|█████████████████████▎              | 25224/42525 [47:32<37:45,  7.64it/s]

 59%|█████████████████████▎              | 25226/42525 [47:32<34:29,  8.36it/s]

 59%|█████████████████████▎              | 25230/42525 [47:33<30:48,  9.36it/s]

 59%|█████████████████████▎              | 25234/42525 [47:33<29:08,  9.89it/s]

 59%|█████████████████████▎              | 25237/42525 [47:33<31:57,  9.01it/s]

 59%|█████████████████████▎              | 25240/42525 [47:34<31:54,  9.03it/s]

 59%|█████████████████████▎              | 25244/42525 [47:34<29:37,  9.72it/s]

 59%|█████████████████████▎              | 25247/42525 [47:34<29:03,  9.91it/s]

 59%|█████████████████████▎              | 25248/42525 [47:35<30:23,  9.48it/s]

 59%|█████████████████████▍              | 25251/42525 [47:35<31:05,  9.26it/s]

 59%|█████████████████████▍              | 25253/42525 [47:35<33:34,  8.57it/s]

 59%|█████████████████████▍              | 25256/42525 [47:35<31:58,  9.00it/s]

 59%|█████████████████████▍              | 25259/42525 [47:36<30:02,  9.58it/s]

 59%|█████████████████████▍              | 25262/42525 [47:36<32:45,  8.78it/s]

 59%|█████████████████████▍              | 25264/42525 [47:36<34:54,  8.24it/s]

 59%|█████████████████████▍              | 25267/42525 [47:37<33:10,  8.67it/s]

 59%|█████████████████████▍              | 25270/42525 [47:37<31:15,  9.20it/s]

 59%|█████████████████████▍              | 25272/42525 [47:37<32:46,  8.77it/s]

 59%|█████████████████████▍              | 25274/42525 [47:37<30:49,  9.33it/s]

 59%|█████████████████████▍              | 25277/42525 [47:38<31:51,  9.02it/s]

 59%|█████████████████████▍              | 25278/42525 [47:38<31:45,  9.05it/s]

 59%|█████████████████████▍              | 25281/42525 [47:38<34:17,  8.38it/s]

 59%|█████████████████████▍              | 25285/42525 [47:39<30:25,  9.45it/s]

 59%|█████████████████████▍              | 25288/42525 [47:39<31:05,  9.24it/s]

 59%|█████████████████████▍              | 25290/42525 [47:39<32:16,  8.90it/s]

 59%|█████████████████████▍              | 25292/42525 [47:39<31:28,  9.12it/s]

 59%|█████████████████████▍              | 25293/42525 [47:40<30:43,  9.35it/s]

 59%|█████████████████████▍              | 25296/42525 [47:40<31:47,  9.03it/s]

 59%|█████████████████████▍              | 25297/42525 [47:40<34:31,  8.32it/s]

 59%|█████████████████████▍              | 25300/42525 [47:40<33:12,  8.65it/s]

 59%|█████████████████████▍              | 25301/42525 [47:41<34:00,  8.44it/s]

 60%|█████████████████████▍              | 25305/42525 [47:41<32:06,  8.94it/s]

 60%|█████████████████████▍              | 25307/42525 [47:41<33:42,  8.51it/s]

 60%|█████████████████████▍              | 25310/42525 [47:42<31:36,  9.08it/s]

 60%|█████████████████████▍              | 25314/42525 [47:42<29:37,  9.68it/s]

 60%|█████████████████████▍              | 25316/42525 [47:42<31:55,  8.98it/s]

 60%|█████████████████████▍              | 25319/42525 [47:43<34:39,  8.27it/s]

 60%|█████████████████████▍              | 25321/42525 [47:43<36:38,  7.83it/s]

 60%|█████████████████████▍              | 25323/42525 [47:43<35:37,  8.05it/s]

 60%|█████████████████████▍              | 25325/42525 [47:43<34:58,  8.20it/s]

 60%|█████████████████████▍              | 25328/42525 [47:44<32:16,  8.88it/s]

 60%|█████████████████████▍              | 25330/42525 [47:44<30:46,  9.31it/s]

 60%|█████████████████████▍              | 25332/42525 [47:44<33:55,  8.45it/s]

 60%|█████████████████████▍              | 25334/42525 [47:44<36:07,  7.93it/s]

 60%|█████████████████████▍              | 25335/42525 [47:44<38:01,  7.54it/s]

 60%|█████████████████████▍              | 25337/42525 [47:45<34:33,  8.29it/s]

 60%|█████████████████████▍              | 25340/42525 [47:45<32:10,  8.90it/s]

 60%|█████████████████████▍              | 25341/42525 [47:45<34:35,  8.28it/s]

 60%|█████████████████████▍              | 25345/42525 [47:46<32:08,  8.91it/s]

 60%|█████████████████████▍              | 25349/42525 [47:46<29:53,  9.58it/s]

 60%|█████████████████████▍              | 25351/42525 [47:46<32:34,  8.79it/s]

 60%|█████████████████████▍              | 25353/42525 [47:46<31:13,  9.16it/s]

 60%|█████████████████████▍              | 25356/42525 [47:47<32:21,  8.85it/s]

 60%|█████████████████████▍              | 25358/42525 [47:47<30:45,  9.30it/s]

 60%|█████████████████████▍              | 25360/42525 [47:47<31:28,  9.09it/s]

 60%|█████████████████████▍              | 25363/42525 [47:48<32:26,  8.82it/s]

 60%|█████████████████████▍              | 25364/42525 [47:48<32:16,  8.86it/s]

 60%|█████████████████████▍              | 25368/42525 [47:48<29:59,  9.53it/s]

 60%|█████████████████████▍              | 25370/42525 [47:48<29:41,  9.63it/s]

 60%|█████████████████████▍              | 25372/42525 [47:49<32:11,  8.88it/s]

 60%|█████████████████████▍              | 25375/42525 [47:49<29:47,  9.59it/s]

 60%|█████████████████████▍              | 25379/42525 [47:49<29:10,  9.80it/s]

 60%|█████████████████████▍              | 25383/42525 [47:50<28:47,  9.92it/s]

 60%|█████████████████████▍              | 25387/42525 [47:50<28:18, 10.09it/s]

 60%|█████████████████████▍              | 25390/42525 [47:50<29:08,  9.80it/s]

 60%|█████████████████████▍              | 25392/42525 [47:51<34:20,  8.32it/s]

 60%|█████████████████████▍              | 25394/42525 [47:51<35:35,  8.02it/s]

 60%|█████████████████████▍              | 25396/42525 [47:51<35:39,  8.00it/s]

 60%|█████████████████████▌              | 25398/42525 [47:51<35:42,  7.99it/s]

 60%|█████████████████████▌              | 25400/42525 [47:52<33:47,  8.45it/s]

 60%|█████████████████████▌              | 25401/42525 [47:52<36:11,  7.89it/s]

 60%|█████████████████████▌              | 25403/42525 [47:52<34:18,  8.32it/s]

 60%|█████████████████████▌              | 25406/42525 [47:52<34:42,  8.22it/s]

 60%|█████████████████████▌              | 25409/42525 [47:53<31:00,  9.20it/s]

 60%|█████████████████████▌              | 25412/42525 [47:53<32:23,  8.80it/s]

 60%|█████████████████████▌              | 25414/42525 [47:53<34:13,  8.33it/s]

 60%|█████████████████████▌              | 25417/42525 [47:54<33:20,  8.55it/s]

 60%|█████████████████████▌              | 25419/42525 [47:54<31:15,  9.12it/s]

 60%|█████████████████████▌              | 25422/42525 [47:54<32:55,  8.66it/s]

 60%|█████████████████████▌              | 25425/42525 [47:55<33:47,  8.43it/s]

 60%|█████████████████████▌              | 25428/42525 [47:55<30:43,  9.27it/s]

 60%|█████████████████████▌              | 25430/42525 [47:55<35:32,  8.02it/s]

 60%|█████████████████████▌              | 25432/42525 [47:55<33:45,  8.44it/s]

 60%|█████████████████████▌              | 25435/42525 [47:56<30:48,  9.25it/s]

 60%|█████████████████████▌              | 25438/42525 [47:56<30:52,  9.23it/s]

 60%|█████████████████████▌              | 25441/42525 [47:56<29:57,  9.51it/s]

 60%|█████████████████████▌              | 25445/42525 [47:57<28:36,  9.95it/s]

 60%|█████████████████████▌              | 25447/42525 [47:57<33:43,  8.44it/s]

 60%|█████████████████████▌              | 25451/42525 [47:57<30:19,  9.38it/s]

 60%|█████████████████████▌              | 25453/42525 [47:58<32:59,  8.63it/s]

 60%|█████████████████████▌              | 25454/42525 [47:58<33:08,  8.58it/s]

 60%|█████████████████████▌              | 25456/42525 [47:58<33:47,  8.42it/s]

 60%|█████████████████████▌              | 25458/42525 [47:58<34:01,  8.36it/s]

 60%|█████████████████████▌              | 25460/42525 [47:58<32:11,  8.83it/s]

 60%|█████████████████████▌              | 25463/42525 [47:59<33:36,  8.46it/s]

 60%|█████████████████████▌              | 25465/42525 [47:59<37:00,  7.68it/s]

 60%|█████████████████████▌              | 25468/42525 [47:59<32:18,  8.80it/s]

 60%|█████████████████████▌              | 25470/42525 [48:00<33:24,  8.51it/s]

 60%|█████████████████████▌              | 25473/42525 [48:00<32:09,  8.84it/s]

 60%|█████████████████████▌              | 25476/42525 [48:00<35:23,  8.03it/s]

 60%|█████████████████████▌              | 25478/42525 [48:01<35:23,  8.03it/s]

 60%|█████████████████████▌              | 25480/42525 [48:01<34:49,  8.16it/s]

 60%|█████████████████████▌              | 25482/42525 [48:01<36:05,  7.87it/s]

 60%|█████████████████████▌              | 25484/42525 [48:01<36:40,  7.74it/s]

 60%|█████████████████████▌              | 25486/42525 [48:02<33:15,  8.54it/s]

 60%|█████████████████████▌              | 25489/42525 [48:02<30:48,  9.21it/s]

 60%|█████████████████████▌              | 25491/42525 [48:02<33:15,  8.54it/s]

 60%|█████████████████████▌              | 25494/42525 [48:03<32:10,  8.82it/s]

 60%|█████████████████████▌              | 25496/42525 [48:03<35:02,  8.10it/s]

 60%|█████████████████████▌              | 25498/42525 [48:03<35:26,  8.01it/s]

 60%|█████████████████████▌              | 25500/42525 [48:03<35:17,  8.04it/s]

 60%|█████████████████████▌              | 25502/42525 [48:03<32:04,  8.85it/s]

 60%|█████████████████████▌              | 25506/42525 [48:04<31:02,  9.14it/s]

 60%|█████████████████████▌              | 25509/42525 [48:04<31:47,  8.92it/s]

 60%|█████████████████████▌              | 25513/42525 [48:05<29:35,  9.58it/s]

 60%|█████████████████████▌              | 25515/42525 [48:05<29:20,  9.66it/s]

 60%|█████████████████████▌              | 25518/42525 [48:05<29:06,  9.74it/s]

 60%|█████████████████████▌              | 25519/42525 [48:05<32:08,  8.82it/s]

 60%|█████████████████████▌              | 25522/42525 [48:06<33:46,  8.39it/s]

 60%|█████████████████████▌              | 25524/42525 [48:06<34:19,  8.26it/s]

 60%|█████████████████████▌              | 25526/42525 [48:06<31:13,  9.07it/s]

 60%|█████████████████████▌              | 25528/42525 [48:06<32:40,  8.67it/s]

 60%|█████████████████████▌              | 25531/42525 [48:07<31:25,  9.01it/s]

 60%|█████████████████████▌              | 25533/42525 [48:07<31:31,  8.98it/s]

 60%|█████████████████████▌              | 25535/42525 [48:07<33:18,  8.50it/s]

 60%|█████████████████████▌              | 25538/42525 [48:08<32:08,  8.81it/s]

 60%|█████████████████████▌              | 25541/42525 [48:08<30:02,  9.42it/s]

 60%|█████████████████████▌              | 25544/42525 [48:08<32:02,  8.83it/s]

 60%|█████████████████████▋              | 25546/42525 [48:08<33:15,  8.51it/s]

 60%|█████████████████████▋              | 25549/42525 [48:09<30:21,  9.32it/s]

 60%|█████████████████████▋              | 25551/42525 [48:09<29:31,  9.58it/s]

 60%|█████████████████████▋              | 25554/42525 [48:09<28:55,  9.78it/s]

 60%|█████████████████████▋              | 25557/42525 [48:10<28:26,  9.94it/s]

 60%|█████████████████████▋              | 25558/42525 [48:10<29:02,  9.73it/s]

 60%|█████████████████████▋              | 25560/42525 [48:10<30:32,  9.26it/s]

 60%|█████████████████████▋              | 25564/42525 [48:10<29:26,  9.60it/s]

 60%|█████████████████████▋              | 25567/42525 [48:11<30:07,  9.38it/s]

 60%|█████████████████████▋              | 25568/42525 [48:11<29:47,  9.48it/s]

 60%|█████████████████████▋              | 25571/42525 [48:11<29:38,  9.53it/s]

 60%|█████████████████████▋              | 25574/42525 [48:11<29:27,  9.59it/s]

 60%|█████████████████████▋              | 25577/42525 [48:12<31:44,  8.90it/s]

 60%|█████████████████████▋              | 25580/42525 [48:12<29:28,  9.58it/s]

 60%|█████████████████████▋              | 25584/42525 [48:12<28:55,  9.76it/s]

 60%|█████████████████████▋              | 25588/42525 [48:13<28:08, 10.03it/s]

 60%|█████████████████████▋              | 25590/42525 [48:13<27:58, 10.09it/s]

 60%|█████████████████████▋              | 25593/42525 [48:13<32:11,  8.77it/s]

 60%|█████████████████████▋              | 25594/42525 [48:14<33:10,  8.50it/s]

 60%|█████████████████████▋              | 25597/42525 [48:14<34:31,  8.17it/s]

 60%|█████████████████████▋              | 25599/42525 [48:14<33:21,  8.46it/s]

 60%|█████████████████████▋              | 25601/42525 [48:14<33:45,  8.36it/s]

 60%|█████████████████████▋              | 25604/42525 [48:15<30:27,  9.26it/s]

 60%|█████████████████████▋              | 25607/42525 [48:15<29:31,  9.55it/s]

 60%|█████████████████████▋              | 25610/42525 [48:15<30:42,  9.18it/s]

 60%|█████████████████████▋              | 25614/42525 [48:16<29:07,  9.68it/s]

 60%|█████████████████████▋              | 25616/42525 [48:16<31:01,  9.08it/s]

 60%|█████████████████████▋              | 25619/42525 [48:16<32:17,  8.73it/s]

 60%|█████████████████████▋              | 25621/42525 [48:17<33:02,  8.52it/s]

 60%|█████████████████████▋              | 25623/42525 [48:17<32:18,  8.72it/s]

 60%|█████████████████████▋              | 25625/42525 [48:17<33:10,  8.49it/s]

 60%|█████████████████████▋              | 25629/42525 [48:17<31:35,  8.91it/s]

 60%|█████████████████████▋              | 25631/42525 [48:18<32:32,  8.65it/s]

 60%|█████████████████████▋              | 25633/42525 [48:18<34:19,  8.20it/s]

 60%|█████████████████████▋              | 25637/42525 [48:18<30:00,  9.38it/s]

 60%|█████████████████████▋              | 25641/42525 [48:19<29:13,  9.63it/s]

 60%|█████████████████████▋              | 25643/42525 [48:19<31:24,  8.96it/s]

 60%|█████████████████████▋              | 25645/42525 [48:19<32:45,  8.59it/s]

 60%|█████████████████████▋              | 25648/42525 [48:20<30:26,  9.24it/s]

 60%|█████████████████████▋              | 25651/42525 [48:20<34:06,  8.24it/s]

 60%|█████████████████████▋              | 25654/42525 [48:20<30:54,  9.10it/s]

 60%|█████████████████████▋              | 25657/42525 [48:21<29:06,  9.66it/s]

 60%|█████████████████████▋              | 25659/42525 [48:21<30:37,  9.18it/s]

 60%|█████████████████████▋              | 25663/42525 [48:21<30:26,  9.23it/s]

 60%|█████████████████████▋              | 25664/42525 [48:21<31:40,  8.87it/s]

 60%|█████████████████████▋              | 25667/42525 [48:22<33:06,  8.49it/s]

 60%|█████████████████████▋              | 25669/42525 [48:22<33:49,  8.31it/s]

 60%|█████████████████████▋              | 25671/42525 [48:22<36:15,  7.75it/s]

 60%|█████████████████████▋              | 25673/42525 [48:22<33:32,  8.37it/s]

 60%|█████████████████████▋              | 25677/42525 [48:23<29:49,  9.41it/s]

 60%|█████████████████████▋              | 25680/42525 [48:23<28:49,  9.74it/s]

 60%|█████████████████████▋              | 25682/42525 [48:23<31:54,  8.80it/s]

 60%|█████████████████████▋              | 25684/42525 [48:24<29:41,  9.45it/s]

 60%|█████████████████████▋              | 25688/42525 [48:24<28:37,  9.80it/s]

 60%|█████████████████████▋              | 25689/42525 [48:24<31:06,  9.02it/s]

 60%|█████████████████████▋              | 25692/42525 [48:25<33:17,  8.43it/s]

 60%|█████████████████████▊              | 25695/42525 [48:25<32:08,  8.73it/s]

 60%|█████████████████████▊              | 25698/42525 [48:25<30:19,  9.25it/s]

 60%|█████████████████████▊              | 25700/42525 [48:25<30:00,  9.35it/s]

 60%|█████████████████████▊              | 25702/42525 [48:26<32:26,  8.64it/s]

 60%|█████████████████████▊              | 25704/42525 [48:26<31:13,  8.98it/s]

 60%|█████████████████████▊              | 25707/42525 [48:26<32:19,  8.67it/s]

 60%|█████████████████████▊              | 25709/42525 [48:26<34:17,  8.17it/s]

 60%|█████████████████████▊              | 25713/42525 [48:27<30:49,  9.09it/s]

 60%|█████████████████████▊              | 25716/42525 [48:27<31:23,  8.93it/s]

 60%|█████████████████████▊              | 25718/42525 [48:27<32:45,  8.55it/s]

 60%|█████████████████████▊              | 25721/42525 [48:28<32:51,  8.52it/s]

 60%|█████████████████████▊              | 25723/42525 [48:28<33:02,  8.47it/s]

 60%|█████████████████████▊              | 25725/42525 [48:28<32:43,  8.56it/s]

 61%|█████████████████████▊              | 25729/42525 [48:29<29:00,  9.65it/s]

 61%|█████████████████████▊              | 25731/42525 [48:29<31:01,  9.02it/s]

 61%|█████████████████████▊              | 25734/42525 [48:29<30:38,  9.14it/s]

 61%|█████████████████████▊              | 25736/42525 [48:29<30:59,  9.03it/s]

 61%|█████████████████████▊              | 25739/42525 [48:30<29:34,  9.46it/s]

 61%|█████████████████████▊              | 25742/42525 [48:30<28:22,  9.86it/s]

 61%|█████████████████████▊              | 25744/42525 [48:30<27:44, 10.08it/s]

 61%|█████████████████████▊              | 25747/42525 [48:31<28:58,  9.65it/s]

 61%|█████████████████████▊              | 25751/42525 [48:31<29:25,  9.50it/s]

 61%|█████████████████████▊              | 25754/42525 [48:31<29:33,  9.46it/s]

 61%|█████████████████████▊              | 25756/42525 [48:32<28:36,  9.77it/s]

 61%|█████████████████████▊              | 25760/42525 [48:32<28:59,  9.64it/s]

 61%|█████████████████████▊              | 25761/42525 [48:32<31:13,  8.95it/s]

 61%|█████████████████████▊              | 25765/42525 [48:33<30:33,  9.14it/s]

 61%|█████████████████████▊              | 25767/42525 [48:33<34:31,  8.09it/s]

 61%|█████████████████████▊              | 25770/42525 [48:33<36:04,  7.74it/s]

 61%|█████████████████████▊              | 25773/42525 [48:34<32:10,  8.68it/s]

 61%|█████████████████████▊              | 25775/42525 [48:34<32:54,  8.48it/s]

 61%|█████████████████████▊              | 25778/42525 [48:34<33:29,  8.34it/s]

 61%|█████████████████████▊              | 25780/42525 [48:34<31:30,  8.86it/s]

 61%|█████████████████████▊              | 25782/42525 [48:35<29:48,  9.36it/s]

 61%|█████████████████████▊              | 25785/42525 [48:35<31:49,  8.77it/s]

 61%|█████████████████████▊              | 25787/42525 [48:35<30:17,  9.21it/s]

 61%|█████████████████████▊              | 25791/42525 [48:36<29:50,  9.35it/s]

 61%|█████████████████████▊              | 25793/42525 [48:36<30:14,  9.22it/s]

 61%|█████████████████████▊              | 25796/42525 [48:36<30:21,  9.19it/s]

 61%|█████████████████████▊              | 25800/42525 [48:37<28:46,  9.69it/s]

 61%|█████████████████████▊              | 25804/42525 [48:37<27:46, 10.03it/s]

 61%|█████████████████████▊              | 25806/42525 [48:37<32:00,  8.71it/s]

 61%|█████████████████████▊              | 25809/42525 [48:38<31:13,  8.92it/s]

 61%|█████████████████████▊              | 25812/42525 [48:38<30:59,  8.99it/s]

 61%|█████████████████████▊              | 25815/42525 [48:38<30:57,  9.00it/s]

 61%|█████████████████████▊              | 25819/42525 [48:39<30:26,  9.15it/s]

 61%|█████████████████████▊              | 25821/42525 [48:39<32:47,  8.49it/s]

 61%|█████████████████████▊              | 25824/42525 [48:39<30:01,  9.27it/s]

 61%|█████████████████████▊              | 25827/42525 [48:40<30:25,  9.15it/s]

 61%|█████████████████████▊              | 25831/42525 [48:40<29:59,  9.28it/s]

 61%|█████████████████████▊              | 25834/42525 [48:40<28:51,  9.64it/s]

 61%|█████████████████████▊              | 25838/42525 [48:41<29:26,  9.45it/s]

 61%|█████████████████████▉              | 25841/42525 [48:41<31:07,  8.93it/s]

 61%|█████████████████████▉              | 25842/42525 [48:41<33:14,  8.37it/s]

 61%|█████████████████████▉              | 25844/42525 [48:41<31:34,  8.80it/s]

 61%|█████████████████████▉              | 25847/42525 [48:42<34:19,  8.10it/s]

 61%|█████████████████████▉              | 25850/42525 [48:42<32:10,  8.64it/s]

 61%|█████████████████████▉              | 25852/42525 [48:42<30:50,  9.01it/s]

 61%|█████████████████████▉              | 25856/42525 [48:43<28:16,  9.83it/s]

 61%|█████████████████████▉              | 25860/42525 [48:43<27:29, 10.10it/s]

 61%|█████████████████████▉              | 25864/42525 [48:44<27:23, 10.14it/s]

 61%|█████████████████████▉              | 25866/42525 [48:44<27:11, 10.21it/s]

 61%|█████████████████████▉              | 25870/42525 [48:44<27:30, 10.09it/s]

 61%|█████████████████████▉              | 25872/42525 [48:44<27:21, 10.15it/s]

 61%|█████████████████████▉              | 25875/42525 [48:45<29:58,  9.26it/s]

 61%|█████████████████████▉              | 25878/42525 [48:45<30:01,  9.24it/s]

 61%|█████████████████████▉              | 25881/42525 [48:45<29:09,  9.51it/s]

 61%|█████████████████████▉              | 25884/42525 [48:46<29:44,  9.33it/s]

 61%|█████████████████████▉              | 25887/42525 [48:46<30:38,  9.05it/s]

 61%|█████████████████████▉              | 25891/42525 [48:46<30:06,  9.21it/s]

 61%|█████████████████████▉              | 25893/42525 [48:47<32:13,  8.60it/s]

 61%|█████████████████████▉              | 25896/42525 [48:47<31:04,  8.92it/s]

 61%|█████████████████████▉              | 25899/42525 [48:47<30:40,  9.03it/s]

 61%|█████████████████████▉              | 25901/42525 [48:48<29:05,  9.52it/s]

 61%|█████████████████████▉              | 25903/42525 [48:48<30:49,  8.99it/s]

 61%|█████████████████████▉              | 25906/42525 [48:48<33:30,  8.27it/s]

 61%|█████████████████████▉              | 25908/42525 [48:48<32:19,  8.57it/s]

 61%|█████████████████████▉              | 25910/42525 [48:49<33:58,  8.15it/s]

 61%|█████████████████████▉              | 25912/42525 [48:49<31:30,  8.79it/s]

 61%|█████████████████████▉              | 25915/42525 [48:49<32:34,  8.50it/s]

 61%|█████████████████████▉              | 25918/42525 [48:50<31:46,  8.71it/s]

 61%|█████████████████████▉              | 25921/42525 [48:50<32:17,  8.57it/s]

 61%|█████████████████████▉              | 25924/42525 [48:50<30:17,  9.14it/s]

 61%|█████████████████████▉              | 25928/42525 [48:51<30:01,  9.21it/s]

 61%|█████████████████████▉              | 25931/42525 [48:51<29:01,  9.53it/s]

 61%|█████████████████████▉              | 25935/42525 [48:51<29:23,  9.41it/s]

 61%|█████████████████████▉              | 25938/42525 [48:52<28:27,  9.71it/s]

 61%|█████████████████████▉              | 25940/42525 [48:52<28:13,  9.79it/s]

 61%|█████████████████████▉              | 25943/42525 [48:52<30:07,  9.17it/s]

 61%|█████████████████████▉              | 25944/42525 [48:52<31:12,  8.86it/s]

 61%|█████████████████████▉              | 25947/42525 [48:53<31:27,  8.78it/s]

 61%|█████████████████████▉              | 25949/42525 [48:53<30:36,  9.03it/s]

 61%|█████████████████████▉              | 25951/42525 [48:53<31:56,  8.65it/s]

 61%|█████████████████████▉              | 25954/42525 [48:54<32:10,  8.58it/s]

 61%|█████████████████████▉              | 25956/42525 [48:54<31:38,  8.73it/s]

 61%|█████████████████████▉              | 25958/42525 [48:54<30:23,  9.08it/s]

 61%|█████████████████████▉              | 25960/42525 [48:54<30:09,  9.16it/s]

 61%|█████████████████████▉              | 25962/42525 [48:54<32:24,  8.52it/s]

 61%|█████████████████████▉              | 25963/42525 [48:55<31:13,  8.84it/s]

 61%|█████████████████████▉              | 25966/42525 [48:55<31:20,  8.81it/s]

 61%|█████████████████████▉              | 25969/42525 [48:55<28:32,  9.67it/s]

 61%|█████████████████████▉              | 25972/42525 [48:55<28:14,  9.77it/s]

 61%|█████████████████████▉              | 25976/42525 [48:56<27:24, 10.06it/s]

 61%|█████████████████████▉              | 25979/42525 [48:56<29:54,  9.22it/s]

 61%|█████████████████████▉              | 25980/42525 [48:56<32:19,  8.53it/s]

 61%|█████████████████████▉              | 25982/42525 [48:57<30:54,  8.92it/s]

 61%|█████████████████████▉              | 25985/42525 [48:57<32:45,  8.42it/s]

 61%|██████████████████████              | 25988/42525 [48:57<31:53,  8.64it/s]

 61%|██████████████████████              | 25990/42525 [48:58<32:03,  8.60it/s]

 61%|██████████████████████              | 25991/42525 [48:58<30:56,  8.91it/s]

 61%|██████████████████████              | 25995/42525 [48:58<29:32,  9.32it/s]

 61%|██████████████████████              | 25998/42525 [48:58<30:13,  9.11it/s]

 61%|██████████████████████              | 26002/42525 [48:59<28:25,  9.69it/s]

 61%|██████████████████████              | 26004/42525 [48:59<29:10,  9.44it/s]

 61%|██████████████████████              | 26007/42525 [48:59<30:02,  9.16it/s]

 61%|██████████████████████              | 26009/42525 [49:00<34:26,  7.99it/s]

 61%|██████████████████████              | 26012/42525 [49:00<31:08,  8.84it/s]

 61%|██████████████████████              | 26015/42525 [49:00<31:55,  8.62it/s]

 61%|██████████████████████              | 26018/42525 [49:01<29:30,  9.33it/s]

 61%|██████████████████████              | 26020/42525 [49:01<28:53,  9.52it/s]

 61%|██████████████████████              | 26023/42525 [49:01<31:06,  8.84it/s]

 61%|██████████████████████              | 26024/42525 [49:01<30:37,  8.98it/s]

 61%|██████████████████████              | 26027/42525 [49:02<32:29,  8.46it/s]

 61%|██████████████████████              | 26030/42525 [49:02<32:42,  8.40it/s]

 61%|██████████████████████              | 26032/42525 [49:02<30:46,  8.93it/s]

 61%|██████████████████████              | 26035/42525 [49:03<29:58,  9.17it/s]

 61%|██████████████████████              | 26039/42525 [49:03<27:45,  9.90it/s]

 61%|██████████████████████              | 26041/42525 [49:03<27:34,  9.96it/s]

 61%|██████████████████████              | 26044/42525 [49:03<28:03,  9.79it/s]

 61%|██████████████████████              | 26046/42525 [49:04<28:14,  9.73it/s]

 61%|██████████████████████              | 26049/42525 [49:04<29:06,  9.43it/s]

 61%|██████████████████████              | 26053/42525 [49:04<27:52,  9.85it/s]

 61%|██████████████████████              | 26055/42525 [49:05<29:09,  9.41it/s]

 61%|██████████████████████              | 26057/42525 [49:05<29:39,  9.26it/s]

 61%|██████████████████████              | 26060/42525 [49:05<31:40,  8.66it/s]

 61%|██████████████████████              | 26062/42525 [49:05<32:13,  8.51it/s]

 61%|██████████████████████              | 26064/42525 [49:06<36:24,  7.54it/s]

 61%|██████████████████████              | 26067/42525 [49:06<32:43,  8.38it/s]

 61%|██████████████████████              | 26069/42525 [49:06<33:22,  8.22it/s]

 61%|██████████████████████              | 26071/42525 [49:07<32:00,  8.57it/s]

 61%|██████████████████████              | 26074/42525 [49:07<30:14,  9.07it/s]

 61%|██████████████████████              | 26078/42525 [49:07<28:07,  9.74it/s]

 61%|██████████████████████              | 26081/42525 [49:08<28:02,  9.77it/s]

 61%|██████████████████████              | 26085/42525 [49:08<27:24, 10.00it/s]

 61%|██████████████████████              | 26086/42525 [49:08<29:57,  9.14it/s]

 61%|██████████████████████              | 26089/42525 [49:08<30:25,  9.00it/s]

 61%|██████████████████████              | 26092/42525 [49:09<30:22,  9.02it/s]

 61%|██████████████████████              | 26093/42525 [49:09<32:34,  8.41it/s]

 61%|██████████████████████              | 26096/42525 [49:09<32:39,  8.39it/s]

 61%|██████████████████████              | 26099/42525 [49:10<29:50,  9.17it/s]

 61%|██████████████████████              | 26101/42525 [49:10<29:31,  9.27it/s]

 61%|██████████████████████              | 26102/42525 [49:10<32:20,  8.46it/s]

 61%|██████████████████████              | 26105/42525 [49:10<30:07,  9.08it/s]

 61%|██████████████████████              | 26107/42525 [49:10<33:04,  8.27it/s]

 61%|██████████████████████              | 26110/42525 [49:11<29:35,  9.24it/s]

 61%|██████████████████████              | 26112/42525 [49:11<28:56,  9.45it/s]

 61%|██████████████████████              | 26116/42525 [49:11<28:14,  9.69it/s]

 61%|██████████████████████              | 26118/42525 [49:12<29:09,  9.38it/s]

 61%|██████████████████████              | 26121/42525 [49:12<28:34,  9.57it/s]

 61%|██████████████████████              | 26123/42525 [49:12<27:40,  9.88it/s]

 61%|██████████████████████              | 26127/42525 [49:13<27:56,  9.78it/s]

 61%|██████████████████████              | 26129/42525 [49:13<28:31,  9.58it/s]

 61%|██████████████████████              | 26132/42525 [49:13<29:23,  9.29it/s]

 61%|██████████████████████▏             | 26136/42525 [49:13<27:47,  9.83it/s]

 61%|██████████████████████▏             | 26139/42525 [49:14<28:01,  9.75it/s]

 61%|██████████████████████▏             | 26142/42525 [49:14<30:19,  9.00it/s]

 61%|██████████████████████▏             | 26143/42525 [49:14<30:07,  9.06it/s]

 61%|██████████████████████▏             | 26146/42525 [49:15<33:00,  8.27it/s]

 61%|██████████████████████▏             | 26148/42525 [49:15<34:10,  7.99it/s]

 61%|██████████████████████▏             | 26150/42525 [49:15<34:42,  7.86it/s]

 61%|██████████████████████▏             | 26152/42525 [49:15<33:18,  8.19it/s]

 62%|██████████████████████▏             | 26154/42525 [49:16<35:30,  7.69it/s]

 62%|██████████████████████▏             | 26156/42525 [49:16<33:05,  8.24it/s]

 62%|██████████████████████▏             | 26158/42525 [49:16<32:49,  8.31it/s]

 62%|██████████████████████▏             | 26159/42525 [49:16<34:00,  8.02it/s]

 62%|██████████████████████▏             | 26162/42525 [49:17<32:08,  8.48it/s]

 62%|██████████████████████▏             | 26165/42525 [49:17<29:24,  9.27it/s]

 62%|██████████████████████▏             | 26167/42525 [49:17<32:42,  8.34it/s]

 62%|██████████████████████▏             | 26168/42525 [49:17<31:45,  8.58it/s]

 62%|██████████████████████▏             | 26171/42525 [49:18<29:33,  9.22it/s]

 62%|██████████████████████▏             | 26174/42525 [49:18<29:45,  9.16it/s]

 62%|██████████████████████▏             | 26175/42525 [49:18<29:27,  9.25it/s]

 62%|██████████████████████▏             | 26178/42525 [49:18<31:18,  8.70it/s]

 62%|██████████████████████▏             | 26180/42525 [49:19<32:24,  8.41it/s]

 62%|██████████████████████▏             | 26182/42525 [49:19<33:24,  8.15it/s]

 62%|██████████████████████▏             | 26186/42525 [49:19<28:35,  9.52it/s]

 62%|██████████████████████▏             | 26190/42525 [49:20<27:23,  9.94it/s]

 62%|██████████████████████▏             | 26193/42525 [49:20<27:51,  9.77it/s]

 62%|██████████████████████▏             | 26196/42525 [49:20<29:28,  9.23it/s]

 62%|██████████████████████▏             | 26199/42525 [49:21<28:55,  9.41it/s]

 62%|██████████████████████▏             | 26203/42525 [49:21<29:10,  9.32it/s]

 62%|██████████████████████▏             | 26207/42525 [49:21<27:35,  9.86it/s]

 62%|██████████████████████▏             | 26211/42525 [49:22<27:16,  9.97it/s]

 62%|██████████████████████▏             | 26214/42525 [49:22<29:51,  9.10it/s]

 62%|██████████████████████▏             | 26216/42525 [49:22<31:47,  8.55it/s]

 62%|██████████████████████▏             | 26219/42525 [49:23<33:00,  8.23it/s]

 62%|██████████████████████▏             | 26221/42525 [49:23<34:11,  7.95it/s]

 62%|██████████████████████▏             | 26222/42525 [49:23<35:02,  7.76it/s]

 62%|██████████████████████▏             | 26225/42525 [49:24<31:18,  8.68it/s]

 62%|██████████████████████▏             | 26226/42525 [49:24<30:38,  8.87it/s]

 62%|██████████████████████▏             | 26229/42525 [49:24<30:49,  8.81it/s]

 62%|██████████████████████▏             | 26232/42525 [49:24<28:38,  9.48it/s]

 62%|██████████████████████▏             | 26234/42525 [49:25<31:17,  8.68it/s]

 62%|██████████████████████▏             | 26236/42525 [49:25<29:18,  9.26it/s]

 62%|██████████████████████▏             | 26238/42525 [49:25<30:53,  8.79it/s]

 62%|██████████████████████▏             | 26242/42525 [49:25<30:07,  9.01it/s]

 62%|██████████████████████▏             | 26246/42525 [49:26<28:05,  9.66it/s]

 62%|██████████████████████▏             | 26250/42525 [49:26<27:16,  9.94it/s]

 62%|██████████████████████▏             | 26252/42525 [49:26<29:07,  9.31it/s]

 62%|██████████████████████▏             | 26255/42525 [49:27<30:32,  8.88it/s]

 62%|██████████████████████▏             | 26259/42525 [49:27<28:09,  9.63it/s]

 62%|██████████████████████▏             | 26261/42525 [49:27<28:35,  9.48it/s]

 62%|██████████████████████▏             | 26264/42525 [49:28<30:27,  8.90it/s]

 62%|██████████████████████▏             | 26267/42525 [49:28<28:57,  9.35it/s]

 62%|██████████████████████▏             | 26270/42525 [49:28<28:10,  9.61it/s]

 62%|██████████████████████▏             | 26273/42525 [49:29<27:29,  9.85it/s]

 62%|██████████████████████▏             | 26274/42525 [49:29<27:25,  9.88it/s]

 62%|██████████████████████▏             | 26278/42525 [49:29<28:25,  9.52it/s]

 62%|██████████████████████▏             | 26280/42525 [49:29<32:06,  8.43it/s]

 62%|██████████████████████▎             | 26283/42525 [49:30<30:34,  8.86it/s]

 62%|██████████████████████▎             | 26285/42525 [49:30<29:53,  9.05it/s]

 62%|██████████████████████▎             | 26289/42525 [49:30<28:04,  9.64it/s]

 62%|██████████████████████▎             | 26292/42525 [49:31<28:31,  9.48it/s]

 62%|██████████████████████▎             | 26296/42525 [49:31<28:14,  9.58it/s]

 62%|██████████████████████▎             | 26299/42525 [49:32<29:39,  9.12it/s]

 62%|██████████████████████▎             | 26301/42525 [49:32<30:07,  8.98it/s]

 62%|██████████████████████▎             | 26303/42525 [49:32<32:55,  8.21it/s]

 62%|██████████████████████▎             | 26305/42525 [49:32<30:16,  8.93it/s]

 62%|██████████████████████▎             | 26307/42525 [49:32<30:32,  8.85it/s]

 62%|██████████████████████▎             | 26310/42525 [49:33<31:08,  8.68it/s]

 62%|██████████████████████▎             | 26312/42525 [49:33<34:18,  7.88it/s]

 62%|██████████████████████▎             | 26314/42525 [49:33<30:59,  8.72it/s]

 62%|██████████████████████▎             | 26318/42525 [49:34<28:31,  9.47it/s]

 62%|██████████████████████▎             | 26319/42525 [49:34<29:21,  9.20it/s]

 62%|██████████████████████▎             | 26323/42525 [49:34<28:31,  9.47it/s]

 62%|██████████████████████▎             | 26324/42525 [49:34<28:47,  9.38it/s]

 62%|██████████████████████▎             | 26327/42525 [49:35<28:17,  9.54it/s]

 62%|██████████████████████▎             | 26330/42525 [49:35<29:13,  9.23it/s]

 62%|██████████████████████▎             | 26332/42525 [49:35<31:05,  8.68it/s]

 62%|██████████████████████▎             | 26335/42525 [49:36<29:49,  9.05it/s]

 62%|██████████████████████▎             | 26336/42525 [49:36<32:10,  8.39it/s]

 62%|██████████████████████▎             | 26340/42525 [49:36<30:10,  8.94it/s]

 62%|██████████████████████▎             | 26342/42525 [49:36<29:57,  9.00it/s]

 62%|██████████████████████▎             | 26346/42525 [49:37<27:38,  9.76it/s]

 62%|██████████████████████▎             | 26349/42525 [49:37<29:00,  9.29it/s]

 62%|██████████████████████▎             | 26351/42525 [49:37<31:50,  8.46it/s]

 62%|██████████████████████▎             | 26353/42525 [49:38<29:47,  9.05it/s]

 62%|██████████████████████▎             | 26356/42525 [49:38<30:01,  8.98it/s]

 62%|██████████████████████▎             | 26359/42525 [49:38<28:52,  9.33it/s]

 62%|██████████████████████▎             | 26363/42525 [49:39<27:25,  9.82it/s]

 62%|██████████████████████▎             | 26366/42525 [49:39<27:42,  9.72it/s]

 62%|██████████████████████▎             | 26367/42525 [49:39<27:35,  9.76it/s]

 62%|██████████████████████▎             | 26370/42525 [49:39<28:00,  9.61it/s]

 62%|██████████████████████▎             | 26372/42525 [49:40<30:01,  8.97it/s]

 62%|██████████████████████▎             | 26375/42525 [49:40<29:43,  9.06it/s]

 62%|██████████████████████▎             | 26378/42525 [49:40<31:31,  8.54it/s]

 62%|██████████████████████▎             | 26381/42525 [49:41<30:24,  8.85it/s]

 62%|██████████████████████▎             | 26383/42525 [49:41<31:32,  8.53it/s]

 62%|██████████████████████▎             | 26387/42525 [49:41<30:21,  8.86it/s]

 62%|██████████████████████▎             | 26389/42525 [49:42<32:02,  8.40it/s]

 62%|██████████████████████▎             | 26391/42525 [49:42<32:07,  8.37it/s]

 62%|██████████████████████▎             | 26395/42525 [49:42<29:19,  9.17it/s]

 62%|██████████████████████▎             | 26398/42525 [49:43<30:43,  8.75it/s]

 62%|██████████████████████▎             | 26399/42525 [49:43<31:53,  8.43it/s]

 62%|██████████████████████▎             | 26402/42525 [49:43<34:14,  7.85it/s]

 62%|██████████████████████▎             | 26404/42525 [49:43<33:28,  8.03it/s]

 62%|██████████████████████▎             | 26407/42525 [49:44<32:46,  8.19it/s]

 62%|██████████████████████▎             | 26408/42525 [49:44<31:49,  8.44it/s]

 62%|██████████████████████▎             | 26410/42525 [49:44<30:30,  8.80it/s]

 62%|██████████████████████▎             | 26414/42525 [49:44<28:29,  9.42it/s]

 62%|██████████████████████▎             | 26416/42525 [49:45<32:49,  8.18it/s]

 62%|██████████████████████▎             | 26419/42525 [49:45<32:25,  8.28it/s]

 62%|██████████████████████▎             | 26423/42525 [49:45<28:44,  9.34it/s]

 62%|██████████████████████▎             | 26425/42525 [49:46<31:46,  8.44it/s]

 62%|██████████████████████▎             | 26427/42525 [49:46<34:41,  7.73it/s]

 62%|██████████████████████▎             | 26430/42525 [49:46<30:10,  8.89it/s]

 62%|██████████████████████▍             | 26434/42525 [49:47<27:32,  9.74it/s]

 62%|██████████████████████▍             | 26437/42525 [49:47<29:51,  8.98it/s]

 62%|██████████████████████▍             | 26440/42525 [49:47<29:43,  9.02it/s]

 62%|██████████████████████▍             | 26441/42525 [49:47<31:23,  8.54it/s]

 62%|██████████████████████▍             | 26443/42525 [49:48<32:00,  8.37it/s]

 62%|██████████████████████▍             | 26446/42525 [49:48<34:01,  7.88it/s]

 62%|██████████████████████▍             | 26449/42525 [49:48<30:24,  8.81it/s]

 62%|██████████████████████▍             | 26452/42525 [49:49<31:49,  8.42it/s]

 62%|██████████████████████▍             | 26454/42525 [49:49<31:27,  8.52it/s]

 62%|██████████████████████▍             | 26456/42525 [49:49<35:21,  7.57it/s]

 62%|██████████████████████▍             | 26458/42525 [49:50<32:01,  8.36it/s]

 62%|██████████████████████▍             | 26460/42525 [49:50<31:48,  8.42it/s]

 62%|██████████████████████▍             | 26462/42525 [49:50<29:09,  9.18it/s]

 62%|██████████████████████▍             | 26465/42525 [49:50<29:50,  8.97it/s]

 62%|██████████████████████▍             | 26467/42525 [49:51<30:08,  8.88it/s]

 62%|██████████████████████▍             | 26469/42525 [49:51<31:09,  8.59it/s]

 62%|██████████████████████▍             | 26472/42525 [49:51<32:08,  8.33it/s]

 62%|██████████████████████▍             | 26474/42525 [49:51<31:35,  8.47it/s]

 62%|██████████████████████▍             | 26476/42525 [49:52<34:57,  7.65it/s]

 62%|██████████████████████▍             | 26480/42525 [49:52<29:19,  9.12it/s]

 62%|██████████████████████▍             | 26483/42525 [49:52<32:27,  8.24it/s]

 62%|██████████████████████▍             | 26487/42525 [49:53<28:41,  9.32it/s]

 62%|██████████████████████▍             | 26489/42525 [49:53<28:58,  9.22it/s]

 62%|██████████████████████▍             | 26492/42525 [49:53<28:11,  9.48it/s]

 62%|██████████████████████▍             | 26494/42525 [49:54<29:43,  8.99it/s]

 62%|██████████████████████▍             | 26498/42525 [49:54<27:21,  9.76it/s]

 62%|██████████████████████▍             | 26500/42525 [49:54<26:45,  9.98it/s]

 62%|██████████████████████▍             | 26502/42525 [49:54<27:02,  9.87it/s]

 62%|██████████████████████▍             | 26506/42525 [49:55<26:48,  9.96it/s]

 62%|██████████████████████▍             | 26508/42525 [49:55<29:28,  9.06it/s]

 62%|██████████████████████▍             | 26510/42525 [49:55<28:05,  9.50it/s]

 62%|██████████████████████▍             | 26513/42525 [49:56<28:47,  9.27it/s]

 62%|██████████████████████▍             | 26515/42525 [49:56<31:23,  8.50it/s]

 62%|██████████████████████▍             | 26516/42525 [49:56<30:44,  8.68it/s]

 62%|██████████████████████▍             | 26519/42525 [49:56<33:29,  7.97it/s]

 62%|██████████████████████▍             | 26521/42525 [49:57<33:31,  7.96it/s]

 62%|██████████████████████▍             | 26525/42525 [49:57<28:32,  9.34it/s]

 62%|██████████████████████▍             | 26526/42525 [49:57<30:49,  8.65it/s]

 62%|██████████████████████▍             | 26530/42525 [49:58<29:20,  9.09it/s]

 62%|██████████████████████▍             | 26532/42525 [49:58<29:16,  9.10it/s]

 62%|██████████████████████▍             | 26536/42525 [49:58<27:21,  9.74it/s]

 62%|██████████████████████▍             | 26540/42525 [49:59<26:33, 10.03it/s]

 62%|██████████████████████▍             | 26542/42525 [49:59<26:08, 10.19it/s]

 62%|██████████████████████▍             | 26546/42525 [49:59<26:24, 10.08it/s]

 62%|██████████████████████▍             | 26548/42525 [49:59<28:17,  9.41it/s]

 62%|██████████████████████▍             | 26552/42525 [50:00<27:19,  9.74it/s]

 62%|██████████████████████▍             | 26554/42525 [50:00<28:27,  9.36it/s]

 62%|██████████████████████▍             | 26557/42525 [50:00<28:41,  9.27it/s]

 62%|██████████████████████▍             | 26558/42525 [50:00<31:06,  8.56it/s]

 62%|██████████████████████▍             | 26561/42525 [50:01<31:24,  8.47it/s]

 62%|██████████████████████▍             | 26565/42525 [50:01<27:39,  9.61it/s]

 62%|██████████████████████▍             | 26568/42525 [50:02<29:34,  8.99it/s]

 62%|██████████████████████▍             | 26571/42525 [50:02<28:07,  9.45it/s]

 62%|██████████████████████▍             | 26573/42525 [50:02<31:02,  8.56it/s]

 62%|██████████████████████▍             | 26577/42525 [50:03<28:11,  9.43it/s]

 63%|██████████████████████▌             | 26580/42525 [50:03<27:16,  9.75it/s]

 63%|██████████████████████▌             | 26583/42525 [50:03<27:16,  9.74it/s]

 63%|██████████████████████▌             | 26585/42525 [50:03<27:45,  9.57it/s]

 63%|██████████████████████▌             | 26588/42525 [50:04<28:29,  9.32it/s]

 63%|██████████████████████▌             | 26589/42525 [50:04<28:20,  9.37it/s]

 63%|██████████████████████▌             | 26593/42525 [50:04<27:54,  9.52it/s]

 63%|██████████████████████▌             | 26594/42525 [50:04<28:22,  9.36it/s]

 63%|██████████████████████▌             | 26598/42525 [50:05<27:46,  9.56it/s]

 63%|██████████████████████▌             | 26601/42525 [50:05<29:16,  9.07it/s]

 63%|██████████████████████▌             | 26603/42525 [50:05<29:13,  9.08it/s]

 63%|██████████████████████▌             | 26606/42525 [50:06<27:25,  9.68it/s]

 63%|██████████████████████▌             | 26609/42525 [50:06<28:25,  9.33it/s]

 63%|██████████████████████▌             | 26612/42525 [50:06<29:51,  8.88it/s]

 63%|██████████████████████▌             | 26615/42525 [50:07<28:26,  9.32it/s]

 63%|██████████████████████▌             | 26618/42525 [50:07<30:41,  8.64it/s]

 63%|██████████████████████▌             | 26621/42525 [50:07<29:33,  8.97it/s]

 63%|██████████████████████▌             | 26624/42525 [50:08<27:54,  9.50it/s]

 63%|██████████████████████▌             | 26626/42525 [50:08<29:30,  8.98it/s]

 63%|██████████████████████▌             | 26629/42525 [50:08<27:23,  9.67it/s]

 63%|██████████████████████▌             | 26633/42525 [50:09<27:17,  9.70it/s]

 63%|██████████████████████▌             | 26636/42525 [50:09<28:18,  9.36it/s]

 63%|██████████████████████▌             | 26640/42525 [50:09<28:30,  9.28it/s]

 63%|██████████████████████▌             | 26644/42525 [50:10<26:53,  9.84it/s]

 63%|██████████████████████▌             | 26648/42525 [50:10<26:32,  9.97it/s]

 63%|██████████████████████▌             | 26650/42525 [50:10<26:09, 10.12it/s]

 63%|██████████████████████▌             | 26653/42525 [50:11<26:35,  9.95it/s]

 63%|██████████████████████▌             | 26655/42525 [50:11<27:47,  9.52it/s]

 63%|██████████████████████▌             | 26658/42525 [50:11<26:57,  9.81it/s]

 63%|██████████████████████▌             | 26659/42525 [50:11<26:50,  9.85it/s]

 63%|██████████████████████▌             | 26662/42525 [50:12<27:02,  9.77it/s]

 63%|██████████████████████▌             | 26663/42525 [50:12<27:26,  9.64it/s]

 63%|██████████████████████▌             | 26666/42525 [50:12<27:50,  9.50it/s]

 63%|██████████████████████▌             | 26667/42525 [50:12<28:57,  9.13it/s]

 63%|██████████████████████▌             | 26671/42525 [50:12<27:57,  9.45it/s]

 63%|██████████████████████▌             | 26673/42525 [50:13<27:25,  9.64it/s]

 63%|██████████████████████▌             | 26677/42525 [50:13<27:04,  9.76it/s]

 63%|██████████████████████▌             | 26680/42525 [50:13<30:25,  8.68it/s]

 63%|██████████████████████▌             | 26681/42525 [50:14<30:00,  8.80it/s]

 63%|██████████████████████▌             | 26684/42525 [50:14<31:28,  8.39it/s]

 63%|██████████████████████▌             | 26687/42525 [50:14<29:46,  8.87it/s]

 63%|██████████████████████▌             | 26688/42525 [50:14<30:09,  8.75it/s]

 63%|██████████████████████▌             | 26691/42525 [50:15<28:55,  9.12it/s]

 63%|██████████████████████▌             | 26695/42525 [50:15<27:43,  9.52it/s]

 63%|██████████████████████▌             | 26698/42525 [50:15<28:19,  9.31it/s]

 63%|██████████████████████▌             | 26700/42525 [50:16<31:24,  8.40it/s]

 63%|██████████████████████▌             | 26703/42525 [50:16<31:23,  8.40it/s]

 63%|██████████████████████▌             | 26707/42525 [50:16<27:49,  9.48it/s]

 63%|██████████████████████▌             | 26709/42525 [50:17<26:50,  9.82it/s]

 63%|██████████████████████▌             | 26713/42525 [50:17<26:31,  9.93it/s]

 63%|██████████████████████▌             | 26714/42525 [50:17<26:35,  9.91it/s]

 63%|██████████████████████▌             | 26718/42525 [50:18<27:21,  9.63it/s]

 63%|██████████████████████▌             | 26721/42525 [50:18<27:24,  9.61it/s]

 63%|██████████████████████▌             | 26723/42525 [50:18<29:09,  9.03it/s]

 63%|██████████████████████▌             | 26725/42525 [50:18<27:35,  9.54it/s]

 63%|██████████████████████▋             | 26727/42525 [50:19<29:09,  9.03it/s]

 63%|██████████████████████▋             | 26731/42525 [50:19<27:48,  9.47it/s]

 63%|██████████████████████▋             | 26733/42525 [50:19<30:16,  8.69it/s]

 63%|██████████████████████▋             | 26735/42525 [50:20<31:26,  8.37it/s]

 63%|██████████████████████▋             | 26737/42525 [50:20<34:58,  7.52it/s]

 63%|██████████████████████▋             | 26739/42525 [50:20<31:40,  8.31it/s]

 63%|██████████████████████▋             | 26743/42525 [50:20<29:31,  8.91it/s]

 63%|██████████████████████▋             | 26745/42525 [50:21<28:52,  9.11it/s]

 63%|██████████████████████▋             | 26746/42525 [50:21<28:41,  9.17it/s]

 63%|██████████████████████▋             | 26749/42525 [50:21<31:35,  8.32it/s]

 63%|██████████████████████▋             | 26750/42525 [50:21<33:23,  7.87it/s]

 63%|██████████████████████▋             | 26754/42525 [50:22<30:16,  8.68it/s]

 63%|██████████████████████▋             | 26757/42525 [50:22<29:37,  8.87it/s]

 63%|██████████████████████▋             | 26759/42525 [50:22<31:57,  8.22it/s]

 63%|██████████████████████▋             | 26762/42525 [50:23<30:13,  8.69it/s]

 63%|██████████████████████▋             | 26764/42525 [50:23<30:14,  8.69it/s]

 63%|██████████████████████▋             | 26768/42525 [50:23<28:56,  9.07it/s]

 63%|██████████████████████▋             | 26771/42525 [50:24<27:37,  9.51it/s]

 63%|██████████████████████▋             | 26774/42525 [50:24<27:10,  9.66it/s]

 63%|██████████████████████▋             | 26776/42525 [50:24<27:06,  9.68it/s]

 63%|██████████████████████▋             | 26780/42525 [50:25<25:52, 10.14it/s]

 63%|██████████████████████▋             | 26784/42525 [50:25<25:21, 10.34it/s]

 63%|██████████████████████▋             | 26788/42525 [50:25<25:43, 10.19it/s]

 63%|██████████████████████▋             | 26791/42525 [50:26<26:45,  9.80it/s]

 63%|██████████████████████▋             | 26795/42525 [50:26<26:20,  9.96it/s]

 63%|██████████████████████▋             | 26797/42525 [50:26<29:22,  8.92it/s]

 63%|██████████████████████▋             | 26800/42525 [50:27<27:56,  9.38it/s]

 63%|██████████████████████▋             | 26801/42525 [50:27<30:26,  8.61it/s]

 63%|██████████████████████▋             | 26804/42525 [50:27<31:08,  8.41it/s]

 63%|██████████████████████▋             | 26807/42525 [50:27<29:11,  8.98it/s]

 63%|██████████████████████▋             | 26810/42525 [50:28<29:25,  8.90it/s]

 63%|██████████████████████▋             | 26814/42525 [50:28<27:17,  9.59it/s]

 63%|██████████████████████▋             | 26816/42525 [50:28<27:13,  9.62it/s]

 63%|██████████████████████▋             | 26818/42525 [50:29<28:01,  9.34it/s]

 63%|██████████████████████▋             | 26821/42525 [50:29<27:14,  9.61it/s]

 63%|██████████████████████▋             | 26824/42525 [50:29<29:03,  9.01it/s]

 63%|██████████████████████▋             | 26827/42525 [50:30<32:05,  8.15it/s]

 63%|██████████████████████▋             | 26829/42525 [50:30<34:58,  7.48it/s]

 63%|██████████████████████▋             | 26832/42525 [50:30<29:26,  8.88it/s]

 63%|██████████████████████▋             | 26835/42525 [50:31<28:22,  9.21it/s]

 63%|██████████████████████▋             | 26838/42525 [50:31<29:36,  8.83it/s]

 63%|██████████████████████▋             | 26841/42525 [50:31<30:32,  8.56it/s]

 63%|██████████████████████▋             | 26843/42525 [50:32<32:53,  7.95it/s]

 63%|██████████████████████▋             | 26846/42525 [50:32<29:42,  8.80it/s]

 63%|██████████████████████▋             | 26848/42525 [50:32<29:55,  8.73it/s]

 63%|██████████████████████▋             | 26849/42525 [50:32<32:13,  8.11it/s]

 63%|██████████████████████▋             | 26852/42525 [50:33<29:17,  8.92it/s]

 63%|██████████████████████▋             | 26854/42525 [50:33<27:39,  9.44it/s]

 63%|██████████████████████▋             | 26857/42525 [50:33<29:54,  8.73it/s]

 63%|██████████████████████▋             | 26860/42525 [50:33<30:23,  8.59it/s]

 63%|██████████████████████▋             | 26862/42525 [50:34<29:08,  8.96it/s]

 63%|██████████████████████▋             | 26864/42525 [50:34<30:21,  8.60it/s]

 63%|██████████████████████▋             | 26865/42525 [50:34<29:29,  8.85it/s]

 63%|██████████████████████▋             | 26868/42525 [50:34<30:13,  8.63it/s]

 63%|██████████████████████▋             | 26870/42525 [50:35<29:06,  8.96it/s]

 63%|██████████████████████▋             | 26873/42525 [50:35<28:59,  9.00it/s]

 63%|██████████████████████▊             | 26876/42525 [50:35<27:04,  9.64it/s]

 63%|██████████████████████▊             | 26879/42525 [50:36<29:00,  8.99it/s]

 63%|██████████████████████▊             | 26882/42525 [50:36<28:03,  9.29it/s]

 63%|██████████████████████▊             | 26883/42525 [50:36<28:09,  9.26it/s]

 63%|██████████████████████▊             | 26886/42525 [50:36<27:51,  9.35it/s]

 63%|██████████████████████▊             | 26890/42525 [50:37<27:31,  9.47it/s]

 63%|██████████████████████▊             | 26891/42525 [50:37<29:45,  8.76it/s]

 63%|██████████████████████▊             | 26894/42525 [50:37<31:11,  8.35it/s]

 63%|██████████████████████▊             | 26896/42525 [50:37<32:13,  8.08it/s]

 63%|██████████████████████▊             | 26898/42525 [50:38<31:14,  8.34it/s]

 63%|██████████████████████▊             | 26901/42525 [50:38<28:45,  9.06it/s]

 63%|██████████████████████▊             | 26904/42525 [50:38<26:55,  9.67it/s]

 63%|██████████████████████▊             | 26907/42525 [50:39<27:19,  9.52it/s]

 63%|██████████████████████▊             | 26909/42525 [50:39<27:19,  9.53it/s]

 63%|██████████████████████▊             | 26913/42525 [50:39<26:00, 10.00it/s]

 63%|██████████████████████▊             | 26916/42525 [50:40<26:26,  9.84it/s]

 63%|██████████████████████▊             | 26918/42525 [50:40<29:20,  8.86it/s]

 63%|██████████████████████▊             | 26920/42525 [50:40<27:40,  9.40it/s]

 63%|██████████████████████▊             | 26923/42525 [50:40<28:09,  9.23it/s]

 63%|██████████████████████▊             | 26924/42525 [50:40<30:36,  8.50it/s]

 63%|██████████████████████▊             | 26927/42525 [50:41<29:52,  8.70it/s]

 63%|██████████████████████▊             | 26931/42525 [50:41<28:54,  8.99it/s]

 63%|██████████████████████▊             | 26934/42525 [50:42<27:37,  9.41it/s]

 63%|██████████████████████▊             | 26937/42525 [50:42<28:09,  9.23it/s]

 63%|██████████████████████▊             | 26941/42525 [50:42<26:26,  9.82it/s]

 63%|██████████████████████▊             | 26945/42525 [50:43<25:38, 10.12it/s]

 63%|██████████████████████▊             | 26947/42525 [50:43<25:42, 10.10it/s]

 63%|██████████████████████▊             | 26949/42525 [50:43<26:17,  9.87it/s]

 63%|██████████████████████▊             | 26952/42525 [50:43<26:53,  9.65it/s]

 63%|██████████████████████▊             | 26955/42525 [50:44<26:58,  9.62it/s]

 63%|██████████████████████▊             | 26957/42525 [50:44<30:46,  8.43it/s]

 63%|██████████████████████▊             | 26960/42525 [50:44<31:26,  8.25it/s]

 63%|██████████████████████▊             | 26963/42525 [50:45<28:15,  9.18it/s]

 63%|██████████████████████▊             | 26964/42525 [50:45<28:43,  9.03it/s]

 63%|██████████████████████▊             | 26966/42525 [50:45<27:48,  9.32it/s]

 63%|██████████████████████▊             | 26969/42525 [50:45<28:50,  8.99it/s]

 63%|██████████████████████▊             | 26971/42525 [50:46<27:36,  9.39it/s]

 63%|██████████████████████▊             | 26974/42525 [50:46<29:03,  8.92it/s]

 63%|██████████████████████▊             | 26976/42525 [50:46<30:06,  8.61it/s]

 63%|██████████████████████▊             | 26978/42525 [50:46<33:06,  7.83it/s]

 63%|██████████████████████▊             | 26982/42525 [50:47<28:10,  9.20it/s]

 63%|██████████████████████▊             | 26984/42525 [50:47<31:22,  8.25it/s]

 63%|██████████████████████▊             | 26987/42525 [50:47<31:07,  8.32it/s]

 63%|██████████████████████▊             | 26989/42525 [50:48<32:02,  8.08it/s]

 63%|██████████████████████▊             | 26991/42525 [50:48<29:05,  8.90it/s]

 63%|██████████████████████▊             | 26994/42525 [50:48<32:02,  8.08it/s]

 63%|██████████████████████▊             | 26995/42525 [50:48<32:35,  7.94it/s]

 63%|██████████████████████▊             | 26998/42525 [50:49<32:05,  8.06it/s]

 63%|██████████████████████▊             | 26999/42525 [50:49<31:16,  8.28it/s]

 63%|██████████████████████▊             | 27001/42525 [50:49<30:24,  8.51it/s]

 64%|██████████████████████▊             | 27005/42525 [50:49<28:14,  9.16it/s]

 64%|██████████████████████▊             | 27007/42525 [50:50<29:04,  8.89it/s]

 64%|██████████████████████▊             | 27009/42525 [50:50<29:40,  8.71it/s]

 64%|██████████████████████▊             | 27011/42525 [50:50<29:27,  8.78it/s]

 64%|██████████████████████▊             | 27012/42525 [50:50<31:53,  8.11it/s]

 64%|██████████████████████▊             | 27014/42525 [50:51<31:11,  8.29it/s]

 64%|██████████████████████▊             | 27018/42525 [50:51<27:57,  9.24it/s]

 64%|██████████████████████▉             | 27022/42525 [50:51<27:47,  9.30it/s]

 64%|██████████████████████▉             | 27024/42525 [50:52<29:50,  8.66it/s]

 64%|██████████████████████▉             | 27026/42525 [50:52<28:52,  8.95it/s]

 64%|██████████████████████▉             | 27030/42525 [50:52<26:07,  9.88it/s]

 64%|██████████████████████▉             | 27033/42525 [50:53<30:08,  8.57it/s]

 64%|██████████████████████▉             | 27035/42525 [50:53<31:22,  8.23it/s]

 64%|██████████████████████▉             | 27036/42525 [50:53<30:00,  8.60it/s]

 64%|██████████████████████▉             | 27038/42525 [50:53<28:25,  9.08it/s]

 64%|██████████████████████▉             | 27041/42525 [50:54<30:13,  8.54it/s]

 64%|██████████████████████▉             | 27044/42525 [50:54<28:58,  8.90it/s]

 64%|██████████████████████▉             | 27048/42525 [50:54<28:14,  9.14it/s]

 64%|██████████████████████▉             | 27050/42525 [50:55<26:51,  9.60it/s]

 64%|██████████████████████▉             | 27052/42525 [50:55<27:54,  9.24it/s]

 64%|██████████████████████▉             | 27056/42525 [50:55<27:54,  9.24it/s]

 64%|██████████████████████▉             | 27058/42525 [50:55<28:57,  8.90it/s]

 64%|██████████████████████▉             | 27061/42525 [50:56<30:38,  8.41it/s]

 64%|██████████████████████▉             | 27063/42525 [50:56<31:51,  8.09it/s]

 64%|██████████████████████▉             | 27066/42525 [50:56<28:30,  9.04it/s]

 64%|██████████████████████▉             | 27070/42525 [50:57<26:20,  9.78it/s]

 64%|██████████████████████▉             | 27074/42525 [50:57<25:23, 10.14it/s]

 64%|██████████████████████▉             | 27076/42525 [50:57<25:34, 10.07it/s]

 64%|██████████████████████▉             | 27079/42525 [50:58<27:43,  9.28it/s]

 64%|██████████████████████▉             | 27083/42525 [50:58<26:48,  9.60it/s]

 64%|██████████████████████▉             | 27084/42525 [50:58<28:52,  8.91it/s]

 64%|██████████████████████▉             | 27087/42525 [50:59<29:58,  8.58it/s]

 64%|██████████████████████▉             | 27089/42525 [50:59<31:37,  8.13it/s]

 64%|██████████████████████▉             | 27093/42525 [50:59<27:43,  9.27it/s]

 64%|██████████████████████▉             | 27095/42525 [50:59<27:03,  9.50it/s]

 64%|██████████████████████▉             | 27098/42525 [51:00<27:00,  9.52it/s]

 64%|██████████████████████▉             | 27099/42525 [51:00<26:48,  9.59it/s]

 64%|██████████████████████▉             | 27103/42525 [51:00<27:04,  9.49it/s]

 64%|██████████████████████▉             | 27106/42525 [51:01<26:40,  9.63it/s]

 64%|██████████████████████▉             | 27108/42525 [51:01<28:52,  8.90it/s]

 64%|██████████████████████▉             | 27110/42525 [51:01<28:20,  9.07it/s]

 64%|██████████████████████▉             | 27112/42525 [51:01<31:08,  8.25it/s]

 64%|██████████████████████▉             | 27114/42525 [51:02<31:20,  8.20it/s]

 64%|██████████████████████▉             | 27118/42525 [51:02<26:44,  9.60it/s]

 64%|██████████████████████▉             | 27121/42525 [51:02<27:51,  9.22it/s]

 64%|██████████████████████▉             | 27124/42525 [51:03<28:38,  8.96it/s]

 64%|██████████████████████▉             | 27127/42525 [51:03<27:54,  9.20it/s]

 64%|██████████████████████▉             | 27129/42525 [51:03<29:05,  8.82it/s]

 64%|██████████████████████▉             | 27131/42525 [51:03<32:23,  7.92it/s]

 64%|██████████████████████▉             | 27133/42525 [51:04<30:32,  8.40it/s]

 64%|██████████████████████▉             | 27135/42525 [51:04<33:25,  7.67it/s]

 64%|██████████████████████▉             | 27139/42525 [51:04<29:28,  8.70it/s]

 64%|██████████████████████▉             | 27141/42525 [51:05<30:10,  8.50it/s]

 64%|██████████████████████▉             | 27145/42525 [51:05<28:53,  8.87it/s]

 64%|██████████████████████▉             | 27148/42525 [51:05<27:32,  9.31it/s]

 64%|██████████████████████▉             | 27149/42525 [51:06<27:15,  9.40it/s]

 64%|██████████████████████▉             | 27152/42525 [51:06<28:02,  9.14it/s]

 64%|██████████████████████▉             | 27156/42525 [51:06<26:20,  9.72it/s]

 64%|██████████████████████▉             | 27160/42525 [51:07<25:04, 10.21it/s]

 64%|██████████████████████▉             | 27162/42525 [51:07<24:59, 10.25it/s]

 64%|██████████████████████▉             | 27164/42525 [51:07<26:49,  9.54it/s]

 64%|██████████████████████▉             | 27167/42525 [51:07<27:24,  9.34it/s]

 64%|███████████████████████             | 27169/42525 [51:08<29:53,  8.56it/s]

 64%|███████████████████████             | 27171/42525 [51:08<27:51,  9.19it/s]

 64%|███████████████████████             | 27174/42525 [51:08<29:42,  8.61it/s]

 64%|███████████████████████             | 27178/42525 [51:09<28:22,  9.01it/s]

 64%|███████████████████████             | 27180/42525 [51:09<31:53,  8.02it/s]

 64%|███████████████████████             | 27184/42525 [51:09<28:14,  9.05it/s]

 64%|███████████████████████             | 27185/42525 [51:09<27:49,  9.19it/s]

 64%|███████████████████████             | 27188/42525 [51:10<29:21,  8.70it/s]

 64%|███████████████████████             | 27190/42525 [51:10<30:56,  8.26it/s]

 64%|███████████████████████             | 27192/42525 [51:10<31:23,  8.14it/s]

 64%|███████████████████████             | 27195/42525 [51:11<28:30,  8.96it/s]

 64%|███████████████████████             | 27199/42525 [51:11<25:38,  9.96it/s]

 64%|███████████████████████             | 27203/42525 [51:11<24:55, 10.24it/s]

 64%|███████████████████████             | 27206/42525 [51:12<29:18,  8.71it/s]

 64%|███████████████████████             | 27209/42525 [51:12<27:03,  9.43it/s]

 64%|███████████████████████             | 27211/42525 [51:12<27:18,  9.35it/s]

 64%|███████████████████████             | 27214/42525 [51:13<26:31,  9.62it/s]

 64%|███████████████████████             | 27217/42525 [51:13<28:29,  8.95it/s]

 64%|███████████████████████             | 27220/42525 [51:13<28:13,  9.04it/s]

 64%|███████████████████████             | 27222/42525 [51:14<29:18,  8.70it/s]

 64%|███████████████████████             | 27225/42525 [51:14<28:15,  9.02it/s]

 64%|███████████████████████             | 27228/42525 [51:14<29:34,  8.62it/s]

 64%|███████████████████████             | 27230/42525 [51:14<28:56,  8.81it/s]

 64%|███████████████████████             | 27233/42525 [51:15<27:26,  9.29it/s]

 64%|███████████████████████             | 27237/42525 [51:15<25:29, 10.00it/s]

 64%|███████████████████████             | 27238/42525 [51:15<25:42,  9.91it/s]

 64%|███████████████████████             | 27240/42525 [51:15<25:43,  9.91it/s]

 64%|███████████████████████             | 27243/42525 [51:16<26:30,  9.61it/s]

 64%|███████████████████████             | 27245/42525 [51:16<29:45,  8.56it/s]

 64%|███████████████████████             | 27247/42525 [51:16<32:01,  7.95it/s]

 64%|███████████████████████             | 27250/42525 [51:17<28:58,  8.78it/s]

 64%|███████████████████████             | 27252/42525 [51:17<28:43,  8.86it/s]

 64%|███████████████████████             | 27255/42525 [51:17<26:05,  9.76it/s]

 64%|███████████████████████             | 27257/42525 [51:17<25:58,  9.80it/s]

 64%|███████████████████████             | 27261/42525 [51:18<26:10,  9.72it/s]

 64%|███████████████████████             | 27265/42525 [51:18<24:59, 10.17it/s]

 64%|███████████████████████             | 27267/42525 [51:18<24:42, 10.29it/s]

 64%|███████████████████████             | 27269/42525 [51:19<24:58, 10.18it/s]

 64%|███████████████████████             | 27272/42525 [51:19<28:41,  8.86it/s]

 64%|███████████████████████             | 27276/42525 [51:19<27:19,  9.30it/s]

 64%|███████████████████████             | 27278/42525 [51:20<27:07,  9.37it/s]

 64%|███████████████████████             | 27281/42525 [51:20<26:56,  9.43it/s]

 64%|███████████████████████             | 27283/42525 [51:20<25:55,  9.80it/s]

 64%|███████████████████████             | 27287/42525 [51:20<26:33,  9.56it/s]

 64%|███████████████████████             | 27290/42525 [51:21<29:49,  8.51it/s]

 64%|███████████████████████             | 27293/42525 [51:21<30:42,  8.27it/s]

 64%|███████████████████████             | 27296/42525 [51:22<32:19,  7.85it/s]

 64%|███████████████████████             | 27299/42525 [51:22<28:53,  8.78it/s]

 64%|███████████████████████             | 27301/42525 [51:22<27:47,  9.13it/s]

 64%|███████████████████████             | 27302/42525 [51:22<30:11,  8.40it/s]

 64%|███████████████████████             | 27306/42525 [51:23<28:00,  9.06it/s]

 64%|███████████████████████             | 27309/42525 [51:23<30:09,  8.41it/s]

 64%|███████████████████████             | 27312/42525 [51:23<28:44,  8.82it/s]

 64%|███████████████████████             | 27316/42525 [51:24<26:23,  9.61it/s]

 64%|███████████████████████▏            | 27318/42525 [51:24<27:59,  9.05it/s]

 64%|███████████████████████▏            | 27322/42525 [51:24<25:36,  9.89it/s]

 64%|███████████████████████▏            | 27326/42525 [51:25<25:05, 10.10it/s]

 64%|███████████████████████▏            | 27328/42525 [51:25<26:15,  9.65it/s]

 64%|███████████████████████▏            | 27332/42525 [51:25<25:30,  9.92it/s]

 64%|███████████████████████▏            | 27335/42525 [51:26<26:25,  9.58it/s]

 64%|███████████████████████▏            | 27337/42525 [51:26<26:29,  9.56it/s]

 64%|███████████████████████▏            | 27340/42525 [51:26<27:02,  9.36it/s]

 64%|███████████████████████▏            | 27341/42525 [51:26<27:37,  9.16it/s]

 64%|███████████████████████▏            | 27344/42525 [51:27<29:09,  8.68it/s]

 64%|███████████████████████▏            | 27347/42525 [51:27<27:38,  9.15it/s]

 64%|███████████████████████▏            | 27349/42525 [51:27<27:34,  9.17it/s]

 64%|███████████████████████▏            | 27352/42525 [51:28<26:27,  9.56it/s]

 64%|███████████████████████▏            | 27354/42525 [51:28<31:10,  8.11it/s]

 64%|███████████████████████▏            | 27355/42525 [51:28<29:38,  8.53it/s]

 64%|███████████████████████▏            | 27358/42525 [51:28<32:03,  7.88it/s]

 64%|███████████████████████▏            | 27359/42525 [51:29<31:19,  8.07it/s]

 64%|███████████████████████▏            | 27363/42525 [51:29<28:16,  8.94it/s]

 64%|███████████████████████▏            | 27365/42525 [51:29<26:38,  9.49it/s]

 64%|███████████████████████▏            | 27369/42525 [51:30<26:28,  9.54it/s]

 64%|███████████████████████▏            | 27372/42525 [51:30<26:23,  9.57it/s]

 64%|███████████████████████▏            | 27374/42525 [51:30<26:58,  9.36it/s]

 64%|███████████████████████▏            | 27377/42525 [51:30<26:56,  9.37it/s]

 64%|███████████████████████▏            | 27380/42525 [51:31<27:22,  9.22it/s]

 64%|███████████████████████▏            | 27382/42525 [51:31<29:32,  8.54it/s]

 64%|███████████████████████▏            | 27384/42525 [51:31<27:17,  9.25it/s]

 64%|███████████████████████▏            | 27387/42525 [51:32<27:03,  9.33it/s]

 64%|███████████████████████▏            | 27390/42525 [51:32<28:01,  9.00it/s]

 64%|███████████████████████▏            | 27392/42525 [51:32<31:45,  7.94it/s]

 64%|███████████████████████▏            | 27394/42525 [51:32<31:50,  7.92it/s]

 64%|███████████████████████▏            | 27397/42525 [51:33<28:02,  8.99it/s]

 64%|███████████████████████▏            | 27398/42525 [51:33<28:43,  8.78it/s]

 64%|███████████████████████▏            | 27401/42525 [51:33<27:56,  9.02it/s]

 64%|███████████████████████▏            | 27403/42525 [51:33<26:17,  9.59it/s]

 64%|███████████████████████▏            | 27407/42525 [51:34<26:18,  9.58it/s]

 64%|███████████████████████▏            | 27408/42525 [51:34<28:08,  8.95it/s]

 64%|███████████████████████▏            | 27410/42525 [51:34<28:45,  8.76it/s]

 64%|███████████████████████▏            | 27413/42525 [51:34<27:42,  9.09it/s]

 64%|███████████████████████▏            | 27416/42525 [51:35<27:32,  9.14it/s]

 64%|███████████████████████▏            | 27419/42525 [51:35<27:46,  9.06it/s]

 64%|███████████████████████▏            | 27422/42525 [51:35<26:15,  9.59it/s]

 64%|███████████████████████▏            | 27424/42525 [51:36<26:39,  9.44it/s]

 64%|███████████████████████▏            | 27426/42525 [51:36<27:52,  9.03it/s]

 64%|███████████████████████▏            | 27428/42525 [51:36<27:32,  9.14it/s]

 65%|███████████████████████▏            | 27431/42525 [51:37<30:17,  8.30it/s]

 65%|███████████████████████▏            | 27432/42525 [51:37<31:58,  7.87it/s]

 65%|███████████████████████▏            | 27436/42525 [51:37<28:59,  8.67it/s]

 65%|███████████████████████▏            | 27438/42525 [51:37<29:13,  8.61it/s]

 65%|███████████████████████▏            | 27440/42525 [51:38<29:59,  8.38it/s]

 65%|███████████████████████▏            | 27442/42525 [51:38<27:21,  9.19it/s]

 65%|███████████████████████▏            | 27445/42525 [51:38<29:02,  8.66it/s]

 65%|███████████████████████▏            | 27448/42525 [51:38<26:35,  9.45it/s]

 65%|███████████████████████▏            | 27451/42525 [51:39<28:23,  8.85it/s]

 65%|███████████████████████▏            | 27452/42525 [51:39<28:07,  8.93it/s]

 65%|███████████████████████▏            | 27454/42525 [51:39<28:39,  8.76it/s]

 65%|███████████████████████▏            | 27456/42525 [51:39<29:25,  8.54it/s]

 65%|███████████████████████▏            | 27460/42525 [51:40<27:48,  9.03it/s]

 65%|███████████████████████▏            | 27462/42525 [51:40<29:27,  8.52it/s]

 65%|███████████████████████▎            | 27465/42525 [51:40<28:13,  8.89it/s]

 65%|███████████████████████▎            | 27466/42525 [51:41<29:47,  8.43it/s]

 65%|███████████████████████▎            | 27470/42525 [51:41<28:01,  8.95it/s]

 65%|███████████████████████▎            | 27472/42525 [51:41<29:40,  8.45it/s]

 65%|███████████████████████▎            | 27473/42525 [51:41<31:30,  7.96it/s]

 65%|███████████████████████▎            | 27476/42525 [51:42<30:14,  8.29it/s]

 65%|███████████████████████▎            | 27477/42525 [51:42<29:42,  8.44it/s]

 65%|███████████████████████▎            | 27480/42525 [51:42<30:33,  8.21it/s]

 65%|███████████████████████▎            | 27482/42525 [51:42<28:29,  8.80it/s]

 65%|███████████████████████▎            | 27485/42525 [51:43<26:39,  9.40it/s]

 65%|███████████████████████▎            | 27487/42525 [51:43<29:20,  8.54it/s]

 65%|███████████████████████▎            | 27490/42525 [51:43<27:42,  9.04it/s]

 65%|███████████████████████▎            | 27493/42525 [51:44<28:04,  8.92it/s]

 65%|███████████████████████▎            | 27497/42525 [51:44<25:43,  9.74it/s]

 65%|███████████████████████▎            | 27499/42525 [51:44<27:08,  9.23it/s]

 65%|███████████████████████▎            | 27502/42525 [51:45<28:32,  8.77it/s]

 65%|███████████████████████▎            | 27504/42525 [51:45<29:26,  8.51it/s]

 65%|███████████████████████▎            | 27506/42525 [51:45<29:08,  8.59it/s]

 65%|███████████████████████▎            | 27508/42525 [51:45<28:38,  8.74it/s]

 65%|███████████████████████▎            | 27509/42525 [51:45<27:56,  8.96it/s]

 65%|███████████████████████▎            | 27513/42525 [51:46<26:11,  9.55it/s]

 65%|███████████████████████▎            | 27516/42525 [51:46<25:40,  9.74it/s]

 65%|███████████████████████▎            | 27518/42525 [51:46<27:12,  9.19it/s]

 65%|███████████████████████▎            | 27520/42525 [51:47<26:57,  9.27it/s]

 65%|███████████████████████▎            | 27521/42525 [51:47<28:00,  8.93it/s]

 65%|███████████████████████▎            | 27523/42525 [51:47<27:42,  9.02it/s]

 65%|███████████████████████▎            | 27525/42525 [51:47<27:31,  9.08it/s]

 65%|███████████████████████▎            | 27529/42525 [51:48<26:53,  9.29it/s]

 65%|███████████████████████▎            | 27532/42525 [51:48<25:46,  9.70it/s]

 65%|███████████████████████▎            | 27535/42525 [51:48<26:16,  9.51it/s]

 65%|███████████████████████▎            | 27539/42525 [51:49<26:28,  9.43it/s]

 65%|███████████████████████▎            | 27541/42525 [51:49<27:46,  8.99it/s]

 65%|███████████████████████▎            | 27544/42525 [51:49<26:25,  9.45it/s]

 65%|███████████████████████▎            | 27546/42525 [51:49<27:48,  8.98it/s]

 65%|███████████████████████▎            | 27550/42525 [51:50<27:18,  9.14it/s]

 65%|███████████████████████▎            | 27552/42525 [51:50<26:49,  9.30it/s]

 65%|███████████████████████▎            | 27555/42525 [51:50<25:27,  9.80it/s]

 65%|███████████████████████▎            | 27558/42525 [51:51<25:56,  9.62it/s]

 65%|███████████████████████▎            | 27562/42525 [51:51<25:36,  9.74it/s]

 65%|███████████████████████▎            | 27565/42525 [51:51<29:00,  8.59it/s]

 65%|███████████████████████▎            | 27568/42525 [51:52<30:09,  8.27it/s]

 65%|███████████████████████▎            | 27571/42525 [51:52<27:29,  9.07it/s]

 65%|███████████████████████▎            | 27573/42525 [51:52<27:55,  8.92it/s]

 65%|███████████████████████▎            | 27575/42525 [51:53<26:57,  9.24it/s]

 65%|███████████████████████▎            | 27577/42525 [51:53<31:42,  7.86it/s]

 65%|███████████████████████▎            | 27580/42525 [51:53<28:16,  8.81it/s]

 65%|███████████████████████▎            | 27582/42525 [51:53<26:58,  9.23it/s]

 65%|███████████████████████▎            | 27583/42525 [51:53<26:53,  9.26it/s]

 65%|███████████████████████▎            | 27587/42525 [51:54<25:08,  9.90it/s]

 65%|███████████████████████▎            | 27591/42525 [51:54<26:00,  9.57it/s]

 65%|███████████████████████▎            | 27595/42525 [51:55<26:13,  9.49it/s]

 65%|███████████████████████▎            | 27598/42525 [51:55<26:32,  9.37it/s]

 65%|███████████████████████▎            | 27600/42525 [51:55<26:27,  9.40it/s]

 65%|███████████████████████▎            | 27604/42525 [51:56<26:25,  9.41it/s]

 65%|███████████████████████▎            | 27608/42525 [51:56<25:03,  9.92it/s]

 65%|███████████████████████▍            | 27612/42525 [51:56<24:20, 10.21it/s]

 65%|███████████████████████▍            | 27614/42525 [51:57<24:25, 10.17it/s]

 65%|███████████████████████▍            | 27617/42525 [51:57<28:19,  8.77it/s]

 65%|███████████████████████▍            | 27621/42525 [51:57<25:32,  9.72it/s]

 65%|███████████████████████▍            | 27625/42525 [51:58<24:32, 10.12it/s]

 65%|███████████████████████▍            | 27628/42525 [51:58<28:00,  8.87it/s]

 65%|███████████████████████▍            | 27631/42525 [51:59<26:34,  9.34it/s]

 65%|███████████████████████▍            | 27633/42525 [51:59<27:13,  9.11it/s]

 65%|███████████████████████▍            | 27637/42525 [51:59<26:36,  9.33it/s]

 65%|███████████████████████▍            | 27639/42525 [51:59<28:06,  8.83it/s]

 65%|███████████████████████▍            | 27642/42525 [52:00<28:17,  8.77it/s]

 65%|███████████████████████▍            | 27646/42525 [52:00<25:33,  9.70it/s]

 65%|███████████████████████▍            | 27649/42525 [52:00<25:33,  9.70it/s]

 65%|███████████████████████▍            | 27653/42525 [52:01<24:44, 10.02it/s]

 65%|███████████████████████▍            | 27656/42525 [52:01<26:10,  9.47it/s]

 65%|███████████████████████▍            | 27658/42525 [52:01<26:39,  9.30it/s]

 65%|███████████████████████▍            | 27661/42525 [52:02<25:45,  9.62it/s]

 65%|███████████████████████▍            | 27664/42525 [52:02<25:57,  9.54it/s]

 65%|███████████████████████▍            | 27667/42525 [52:02<26:01,  9.51it/s]

 65%|███████████████████████▍            | 27670/42525 [52:03<25:22,  9.76it/s]

 65%|███████████████████████▍            | 27671/42525 [52:03<27:03,  9.15it/s]

 65%|███████████████████████▍            | 27673/42525 [52:03<28:18,  8.74it/s]

 65%|███████████████████████▍            | 27676/42525 [52:03<27:41,  8.94it/s]

 65%|███████████████████████▍            | 27679/42525 [52:04<27:30,  8.99it/s]

 65%|███████████████████████▍            | 27681/42525 [52:04<25:57,  9.53it/s]

 65%|███████████████████████▍            | 27685/42525 [52:04<25:26,  9.72it/s]

 65%|███████████████████████▍            | 27688/42525 [52:05<26:55,  9.19it/s]

 65%|███████████████████████▍            | 27691/42525 [52:05<29:46,  8.30it/s]

 65%|███████████████████████▍            | 27694/42525 [52:05<29:32,  8.37it/s]

 65%|███████████████████████▍            | 27697/42525 [52:06<26:55,  9.18it/s]

 65%|███████████████████████▍            | 27699/42525 [52:06<29:04,  8.50it/s]

 65%|███████████████████████▍            | 27703/42525 [52:06<25:44,  9.60it/s]

 65%|███████████████████████▍            | 27705/42525 [52:06<25:00,  9.88it/s]

 65%|███████████████████████▍            | 27707/42525 [52:07<26:46,  9.22it/s]

 65%|███████████████████████▍            | 27710/42525 [52:07<28:54,  8.54it/s]

 65%|███████████████████████▍            | 27713/42525 [52:07<26:50,  9.20it/s]

 65%|███████████████████████▍            | 27716/42525 [52:08<26:46,  9.22it/s]

 65%|███████████████████████▍            | 27718/42525 [52:08<28:11,  8.76it/s]

 65%|███████████████████████▍            | 27720/42525 [52:08<29:44,  8.30it/s]

 65%|███████████████████████▍            | 27722/42525 [52:08<29:41,  8.31it/s]

 65%|███████████████████████▍            | 27726/42525 [52:09<25:21,  9.73it/s]

 65%|███████████████████████▍            | 27728/42525 [52:09<25:30,  9.67it/s]

 65%|███████████████████████▍            | 27730/42525 [52:09<26:17,  9.38it/s]

 65%|███████████████████████▍            | 27732/42525 [52:09<26:00,  9.48it/s]

 65%|███████████████████████▍            | 27736/42525 [52:10<25:02,  9.84it/s]

 65%|███████████████████████▍            | 27740/42525 [52:10<24:14, 10.16it/s]

 65%|███████████████████████▍            | 27744/42525 [52:11<25:03,  9.83it/s]

 65%|███████████████████████▍            | 27746/42525 [52:11<24:38, 10.00it/s]

 65%|███████████████████████▍            | 27749/42525 [52:11<26:19,  9.35it/s]

 65%|███████████████████████▍            | 27751/42525 [52:11<25:17,  9.73it/s]

 65%|███████████████████████▍            | 27754/42525 [52:12<28:34,  8.62it/s]

 65%|███████████████████████▍            | 27757/42525 [52:12<28:19,  8.69it/s]

 65%|███████████████████████▍            | 27759/42525 [52:12<29:01,  8.48it/s]

 65%|███████████████████████▌            | 27762/42525 [52:13<26:50,  9.17it/s]

 65%|███████████████████████▌            | 27765/42525 [52:13<26:38,  9.23it/s]

 65%|███████████████████████▌            | 27769/42525 [52:13<24:58,  9.85it/s]

 65%|███████████████████████▌            | 27772/42525 [52:14<25:42,  9.56it/s]

 65%|███████████████████████▌            | 27775/42525 [52:14<25:50,  9.51it/s]

 65%|███████████████████████▌            | 27778/42525 [52:14<26:30,  9.27it/s]

 65%|███████████████████████▌            | 27781/42525 [52:15<29:30,  8.33it/s]

 65%|███████████████████████▌            | 27784/42525 [52:15<26:40,  9.21it/s]

 65%|███████████████████████▌            | 27788/42525 [52:15<25:35,  9.60it/s]

 65%|███████████████████████▌            | 27792/42525 [52:16<24:37,  9.97it/s]

 65%|███████████████████████▌            | 27793/42525 [52:16<24:38,  9.97it/s]

 65%|███████████████████████▌            | 27797/42525 [52:16<25:39,  9.57it/s]

 65%|███████████████████████▌            | 27798/42525 [52:17<25:52,  9.49it/s]

 65%|███████████████████████▌            | 27801/42525 [52:17<28:21,  8.65it/s]

 65%|███████████████████████▌            | 27804/42525 [52:17<26:42,  9.19it/s]

 65%|███████████████████████▌            | 27806/42525 [52:17<26:30,  9.26it/s]

 65%|███████████████████████▌            | 27809/42525 [52:18<25:46,  9.52it/s]

 65%|███████████████████████▌            | 27811/42525 [52:18<28:46,  8.52it/s]

 65%|███████████████████████▌            | 27813/42525 [52:18<32:06,  7.64it/s]

 65%|███████████████████████▌            | 27815/42525 [52:19<33:06,  7.41it/s]

 65%|███████████████████████▌            | 27816/42525 [52:19<31:05,  7.89it/s]

 65%|███████████████████████▌            | 27820/42525 [52:19<26:26,  9.27it/s]

 65%|███████████████████████▌            | 27822/42525 [52:19<28:00,  8.75it/s]

 65%|███████████████████████▌            | 27825/42525 [52:20<26:42,  9.17it/s]

 65%|███████████████████████▌            | 27826/42525 [52:20<29:04,  8.43it/s]

 65%|███████████████████████▌            | 27828/42525 [52:20<28:56,  8.46it/s]

 65%|███████████████████████▌            | 27832/42525 [52:20<26:58,  9.08it/s]

 65%|███████████████████████▌            | 27834/42525 [52:21<28:39,  8.54it/s]

 65%|███████████████████████▌            | 27836/42525 [52:21<27:41,  8.84it/s]

 65%|███████████████████████▌            | 27838/42525 [52:21<28:35,  8.56it/s]

 65%|███████████████████████▌            | 27841/42525 [52:22<30:18,  8.07it/s]

 65%|███████████████████████▌            | 27844/42525 [52:22<27:45,  8.81it/s]

 65%|███████████████████████▌            | 27848/42525 [52:22<25:25,  9.62it/s]

 65%|███████████████████████▌            | 27849/42525 [52:22<25:17,  9.67it/s]

 65%|███████████████████████▌            | 27852/42525 [52:23<27:45,  8.81it/s]

 66%|███████████████████████▌            | 27855/42525 [52:23<27:19,  8.95it/s]

 66%|███████████████████████▌            | 27858/42525 [52:23<26:52,  9.10it/s]

 66%|███████████████████████▌            | 27860/42525 [52:24<25:52,  9.44it/s]

 66%|███████████████████████▌            | 27862/42525 [52:24<27:18,  8.95it/s]

 66%|███████████████████████▌            | 27865/42525 [52:24<28:20,  8.62it/s]

 66%|███████████████████████▌            | 27868/42525 [52:24<26:09,  9.34it/s]

 66%|███████████████████████▌            | 27871/42525 [52:25<25:15,  9.67it/s]

 66%|███████████████████████▌            | 27873/42525 [52:25<25:45,  9.48it/s]

 66%|███████████████████████▌            | 27875/42525 [52:25<25:44,  9.49it/s]

 66%|███████████████████████▌            | 27878/42525 [52:26<27:16,  8.95it/s]

 66%|███████████████████████▌            | 27881/42525 [52:26<27:34,  8.85it/s]

 66%|███████████████████████▌            | 27885/42525 [52:26<25:27,  9.58it/s]

 66%|███████████████████████▌            | 27886/42525 [52:26<27:32,  8.86it/s]

 66%|███████████████████████▌            | 27889/42525 [52:27<30:13,  8.07it/s]

 66%|███████████████████████▌            | 27892/42525 [52:27<27:18,  8.93it/s]

 66%|███████████████████████▌            | 27895/42525 [52:28<30:00,  8.13it/s]

 66%|███████████████████████▌            | 27899/42525 [52:28<26:43,  9.12it/s]

 66%|███████████████████████▌            | 27902/42525 [52:28<26:04,  9.35it/s]

 66%|███████████████████████▌            | 27906/42525 [52:29<25:28,  9.56it/s]

 66%|███████████████████████▋            | 27909/42525 [52:29<26:50,  9.08it/s]

 66%|███████████████████████▋            | 27913/42525 [52:29<24:59,  9.74it/s]

 66%|███████████████████████▋            | 27917/42525 [52:30<23:55, 10.18it/s]

 66%|███████████████████████▋            | 27919/42525 [52:30<24:01, 10.13it/s]

 66%|███████████████████████▋            | 27921/42525 [52:30<25:37,  9.50it/s]

 66%|███████████████████████▋            | 27924/42525 [52:31<26:38,  9.13it/s]

 66%|███████████████████████▋            | 27927/42525 [52:31<25:54,  9.39it/s]

 66%|███████████████████████▋            | 27931/42525 [52:31<25:11,  9.65it/s]

 66%|███████████████████████▋            | 27934/42525 [52:32<25:03,  9.71it/s]

 66%|███████████████████████▋            | 27936/42525 [52:32<24:59,  9.73it/s]

 66%|███████████████████████▋            | 27938/42525 [52:32<27:35,  8.81it/s]

 66%|███████████████████████▋            | 27939/42525 [52:32<27:30,  8.84it/s]

 66%|███████████████████████▋            | 27942/42525 [52:32<27:38,  8.79it/s]

 66%|███████████████████████▋            | 27944/42525 [52:33<29:24,  8.26it/s]

 66%|███████████████████████▋            | 27947/42525 [52:33<28:04,  8.66it/s]

 66%|███████████████████████▋            | 27951/42525 [52:33<25:21,  9.58it/s]

 66%|███████████████████████▋            | 27953/42525 [52:34<29:34,  8.21it/s]

 66%|███████████████████████▋            | 27955/42525 [52:34<32:26,  7.49it/s]

 66%|███████████████████████▋            | 27959/42525 [52:34<26:25,  9.19it/s]

 66%|███████████████████████▋            | 27962/42525 [52:35<27:24,  8.85it/s]

 66%|███████████████████████▋            | 27964/42525 [52:35<26:07,  9.29it/s]

 66%|███████████████████████▋            | 27967/42525 [52:35<26:33,  9.14it/s]

 66%|███████████████████████▋            | 27971/42525 [52:36<26:10,  9.27it/s]

 66%|███████████████████████▋            | 27974/42525 [52:36<25:16,  9.60it/s]

 66%|███████████████████████▋            | 27978/42525 [52:36<24:46,  9.78it/s]

 66%|███████████████████████▋            | 27979/42525 [52:37<25:38,  9.46it/s]

 66%|███████████████████████▋            | 27981/42525 [52:37<27:02,  8.96it/s]

 66%|███████████████████████▋            | 27985/42525 [52:37<26:31,  9.14it/s]

 66%|███████████████████████▋            | 27989/42525 [52:38<25:01,  9.68it/s]

 66%|███████████████████████▋            | 27992/42525 [52:38<24:58,  9.70it/s]

 66%|███████████████████████▋            | 27995/42525 [52:38<26:39,  9.09it/s]

 66%|███████████████████████▋            | 27996/42525 [52:38<26:51,  9.02it/s]

 66%|███████████████████████▋            | 27999/42525 [52:39<28:54,  8.38it/s]

 66%|███████████████████████▋            | 28001/42525 [52:39<27:01,  8.96it/s]

 66%|███████████████████████▋            | 28004/42525 [52:39<25:30,  9.49it/s]

 66%|███████████████████████▋            | 28007/42525 [52:40<26:17,  9.20it/s]

 66%|███████████████████████▋            | 28010/42525 [52:40<25:17,  9.57it/s]

 66%|███████████████████████▋            | 28012/42525 [52:40<27:06,  8.92it/s]

 66%|███████████████████████▋            | 28015/42525 [52:41<26:45,  9.04it/s]

 66%|███████████████████████▋            | 28017/42525 [52:41<29:15,  8.27it/s]

 66%|███████████████████████▋            | 28019/42525 [52:41<30:30,  7.92it/s]

 66%|███████████████████████▋            | 28022/42525 [52:41<26:24,  9.15it/s]

 66%|███████████████████████▋            | 28025/42525 [52:42<27:24,  8.82it/s]

 66%|███████████████████████▋            | 28028/42525 [52:42<25:20,  9.53it/s]

 66%|███████████████████████▋            | 28030/42525 [52:42<24:54,  9.70it/s]

 66%|███████████████████████▋            | 28033/42525 [52:43<27:23,  8.82it/s]

 66%|███████████████████████▋            | 28035/42525 [52:43<28:11,  8.57it/s]

 66%|███████████████████████▋            | 28038/42525 [52:43<25:53,  9.33it/s]

 66%|███████████████████████▋            | 28041/42525 [52:43<24:59,  9.66it/s]

 66%|███████████████████████▋            | 28045/42525 [52:44<24:09,  9.99it/s]

 66%|███████████████████████▋            | 28047/42525 [52:44<25:45,  9.37it/s]

 66%|███████████████████████▋            | 28050/42525 [52:44<25:57,  9.29it/s]

 66%|███████████████████████▋            | 28052/42525 [52:45<28:13,  8.55it/s]

 66%|███████████████████████▊            | 28055/42525 [52:45<25:50,  9.33it/s]

 66%|███████████████████████▊            | 28058/42525 [52:45<27:37,  8.73it/s]

 66%|███████████████████████▊            | 28060/42525 [52:46<28:35,  8.43it/s]

 66%|███████████████████████▊            | 28061/42525 [52:46<30:31,  7.90it/s]

 66%|███████████████████████▊            | 28064/42525 [52:46<28:38,  8.41it/s]

 66%|███████████████████████▊            | 28067/42525 [52:46<26:41,  9.03it/s]

 66%|███████████████████████▊            | 28070/42525 [52:47<26:22,  9.13it/s]

 66%|███████████████████████▊            | 28072/42525 [52:47<27:25,  8.78it/s]

 66%|███████████████████████▊            | 28073/42525 [52:47<27:34,  8.73it/s]

 66%|███████████████████████▊            | 28075/42525 [52:47<28:30,  8.45it/s]

 66%|███████████████████████▊            | 28078/42525 [52:48<29:24,  8.19it/s]

 66%|███████████████████████▊            | 28082/42525 [52:48<25:40,  9.38it/s]

 66%|███████████████████████▊            | 28086/42525 [52:48<25:59,  9.26it/s]

 66%|███████████████████████▊            | 28090/42525 [52:49<24:34,  9.79it/s]

 66%|███████████████████████▊            | 28092/42525 [52:49<27:36,  8.71it/s]

 66%|███████████████████████▊            | 28093/42525 [52:49<27:10,  8.85it/s]

 66%|███████████████████████▊            | 28096/42525 [52:50<27:15,  8.82it/s]

 66%|███████████████████████▊            | 28099/42525 [52:50<29:00,  8.29it/s]

 66%|███████████████████████▊            | 28101/42525 [52:50<29:10,  8.24it/s]

 66%|███████████████████████▊            | 28104/42525 [52:50<26:25,  9.09it/s]

 66%|███████████████████████▊            | 28107/42525 [52:51<26:28,  9.08it/s]

 66%|███████████████████████▊            | 28111/42525 [52:51<24:09,  9.94it/s]

 66%|███████████████████████▊            | 28113/42525 [52:51<26:07,  9.20it/s]

 66%|███████████████████████▊            | 28115/42525 [52:52<26:07,  9.19it/s]

 66%|███████████████████████▊            | 28116/42525 [52:52<28:29,  8.43it/s]

 66%|███████████████████████▊            | 28120/42525 [52:52<25:42,  9.34it/s]

 66%|███████████████████████▊            | 28121/42525 [52:52<25:56,  9.25it/s]

 66%|███████████████████████▊            | 28123/42525 [52:53<27:23,  8.76it/s]

 66%|███████████████████████▊            | 28126/42525 [52:53<27:39,  8.68it/s]

 66%|███████████████████████▊            | 28129/42525 [52:53<26:39,  9.00it/s]

 66%|███████████████████████▊            | 28131/42525 [52:53<25:34,  9.38it/s]

 66%|███████████████████████▊            | 28133/42525 [52:54<27:15,  8.80it/s]

 66%|███████████████████████▊            | 28136/42525 [52:54<25:43,  9.32it/s]

 66%|███████████████████████▊            | 28140/42525 [52:54<24:10,  9.92it/s]

 66%|███████████████████████▊            | 28141/42525 [52:55<24:35,  9.75it/s]

 66%|███████████████████████▊            | 28145/42525 [52:55<24:10,  9.91it/s]

 66%|███████████████████████▊            | 28148/42525 [52:55<26:36,  9.00it/s]

 66%|███████████████████████▊            | 28149/42525 [52:55<28:28,  8.41it/s]

 66%|███████████████████████▊            | 28152/42525 [52:56<28:48,  8.32it/s]

 66%|███████████████████████▊            | 28153/42525 [52:56<28:30,  8.40it/s]

 66%|███████████████████████▊            | 28156/42525 [52:56<28:47,  8.32it/s]

 66%|███████████████████████▊            | 28159/42525 [52:57<28:39,  8.35it/s]

 66%|███████████████████████▊            | 28162/42525 [52:57<26:11,  9.14it/s]

 66%|███████████████████████▊            | 28164/42525 [52:57<27:00,  8.86it/s]

 66%|███████████████████████▊            | 28166/42525 [52:57<27:51,  8.59it/s]

 66%|███████████████████████▊            | 28168/42525 [52:58<31:38,  7.56it/s]

 66%|███████████████████████▊            | 28170/42525 [52:58<31:19,  7.64it/s]

 66%|███████████████████████▊            | 28173/42525 [52:58<26:41,  8.96it/s]

 66%|███████████████████████▊            | 28176/42525 [52:59<27:14,  8.78it/s]

 66%|███████████████████████▊            | 28179/42525 [52:59<27:00,  8.85it/s]

 66%|███████████████████████▊            | 28181/42525 [52:59<27:07,  8.81it/s]

 66%|███████████████████████▊            | 28185/42525 [53:00<24:51,  9.62it/s]

 66%|███████████████████████▊            | 28187/42525 [53:00<25:40,  9.30it/s]

 66%|███████████████████████▊            | 28191/42525 [53:00<24:32,  9.73it/s]

 66%|███████████████████████▊            | 28193/42525 [53:00<27:39,  8.64it/s]

 66%|███████████████████████▊            | 28195/42525 [53:01<26:15,  9.09it/s]

 66%|███████████████████████▊            | 28199/42525 [53:01<25:52,  9.23it/s]

 66%|███████████████████████▊            | 28202/42525 [53:01<25:20,  9.42it/s]

 66%|███████████████████████▉            | 28205/42525 [53:02<26:28,  9.01it/s]

 66%|███████████████████████▉            | 28208/42525 [53:02<27:26,  8.69it/s]

 66%|███████████████████████▉            | 28210/42525 [53:02<28:15,  8.44it/s]

 66%|███████████████████████▉            | 28212/42525 [53:03<31:45,  7.51it/s]

 66%|███████████████████████▉            | 28214/42525 [53:03<31:47,  7.50it/s]

 66%|███████████████████████▉            | 28217/42525 [53:03<28:33,  8.35it/s]

 66%|███████████████████████▉            | 28218/42525 [53:03<29:45,  8.01it/s]

 66%|███████████████████████▉            | 28221/42525 [53:04<28:38,  8.32it/s]

 66%|███████████████████████▉            | 28224/42525 [53:04<27:20,  8.72it/s]

 66%|███████████████████████▉            | 28226/42525 [53:04<28:59,  8.22it/s]

 66%|███████████████████████▉            | 28228/42525 [53:05<28:22,  8.40it/s]

 66%|███████████████████████▉            | 28229/42525 [53:05<30:14,  7.88it/s]

 66%|███████████████████████▉            | 28231/42525 [53:05<28:01,  8.50it/s]

 66%|███████████████████████▉            | 28234/42525 [53:05<28:38,  8.32it/s]

 66%|███████████████████████▉            | 28237/42525 [53:06<26:45,  8.90it/s]

 66%|███████████████████████▉            | 28240/42525 [53:06<25:22,  9.38it/s]

 66%|███████████████████████▉            | 28242/42525 [53:06<24:28,  9.73it/s]

 66%|███████████████████████▉            | 28244/42525 [53:06<26:08,  9.11it/s]

 66%|███████████████████████▉            | 28247/42525 [53:07<27:11,  8.75it/s]

 66%|███████████████████████▉            | 28250/42525 [53:07<25:35,  9.29it/s]

 66%|███████████████████████▉            | 28253/42525 [53:07<26:59,  8.81it/s]

 66%|███████████████████████▉            | 28256/42525 [53:08<26:04,  9.12it/s]

 66%|███████████████████████▉            | 28260/42525 [53:08<24:44,  9.61it/s]

 66%|███████████████████████▉            | 28263/42525 [53:08<26:06,  9.10it/s]

 66%|███████████████████████▉            | 28266/42525 [53:09<26:39,  8.92it/s]

 66%|███████████████████████▉            | 28270/42525 [53:09<24:49,  9.57it/s]

 66%|███████████████████████▉            | 28273/42525 [53:09<26:35,  8.93it/s]

 66%|███████████████████████▉            | 28275/42525 [53:10<25:44,  9.22it/s]

 66%|███████████████████████▉            | 28277/42525 [53:10<24:41,  9.62it/s]

 67%|███████████████████████▉            | 28280/42525 [53:10<27:46,  8.55it/s]

 67%|███████████████████████▉            | 28283/42525 [53:11<25:21,  9.36it/s]

 67%|███████████████████████▉            | 28286/42525 [53:11<25:19,  9.37it/s]

 67%|███████████████████████▉            | 28289/42525 [53:11<25:05,  9.46it/s]

 67%|███████████████████████▉            | 28293/42525 [53:12<23:59,  9.88it/s]

 67%|███████████████████████▉            | 28297/42525 [53:12<23:33, 10.07it/s]

 67%|███████████████████████▉            | 28299/42525 [53:12<24:59,  9.49it/s]

 67%|███████████████████████▉            | 28301/42525 [53:12<24:54,  9.51it/s]

 67%|███████████████████████▉            | 28304/42525 [53:13<26:52,  8.82it/s]

 67%|███████████████████████▉            | 28305/42525 [53:13<28:52,  8.21it/s]

 67%|███████████████████████▉            | 28308/42525 [53:13<26:40,  8.88it/s]

 67%|███████████████████████▉            | 28311/42525 [53:14<25:19,  9.35it/s]

 67%|███████████████████████▉            | 28313/42525 [53:14<26:21,  8.99it/s]

 67%|███████████████████████▉            | 28315/42525 [53:14<25:40,  9.22it/s]

 67%|███████████████████████▉            | 28317/42525 [53:14<24:54,  9.50it/s]

 67%|███████████████████████▉            | 28318/42525 [53:14<27:14,  8.69it/s]

 67%|███████████████████████▉            | 28320/42525 [53:15<28:04,  8.43it/s]

 67%|███████████████████████▉            | 28324/42525 [53:15<25:14,  9.38it/s]

 67%|███████████████████████▉            | 28326/42525 [53:15<26:49,  8.82it/s]

 67%|███████████████████████▉            | 28328/42525 [53:15<28:29,  8.31it/s]

 67%|███████████████████████▉            | 28331/42525 [53:16<27:02,  8.75it/s]

 67%|███████████████████████▉            | 28332/42525 [53:16<28:58,  8.17it/s]

 67%|███████████████████████▉            | 28334/42525 [53:16<27:20,  8.65it/s]

 67%|███████████████████████▉            | 28337/42525 [53:17<29:32,  8.01it/s]

 67%|███████████████████████▉            | 28339/42525 [53:17<31:31,  7.50it/s]

 67%|███████████████████████▉            | 28342/42525 [53:17<30:26,  7.76it/s]

 67%|███████████████████████▉            | 28346/42525 [53:18<25:43,  9.19it/s]

 67%|███████████████████████▉            | 28348/42525 [53:18<26:47,  8.82it/s]

 67%|████████████████████████            | 28350/42525 [53:18<30:00,  7.87it/s]
  0%|                                                  | 0/788 [00:00<?, ?it/s]
  0%|                                          | 2/788 [00:00<00:42, 18.66it/s]

{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '7.093e-06', 'epoch': '2'}

  1%|▏                                         | 4/788 [00:00<01:00, 13.03it/s]
  1%|▎                                         | 6/788 [00:00<01:05, 11.94it/s]

  1%|▍                                         | 8/788 [00:00<01:06, 11.68it/s]
  1%|▌                                        | 10/788 [00:00<01:00, 12.92it/s]

  2%|▌                                        | 12/788 [00:00<00:54, 14.34it/s]
  2%|▋                                        | 14/788 [00:01<00:57, 13.52it/s]

  2%|▊                                        | 16/788 [00:01<01:00, 12.81it/s]
  2%|▉                                        | 18/788 [00:01<01:05, 11.81it/s]

  3%|█                                        | 20/788 [00:01<01:10, 10.89it/s]
  3%|█▏                                       | 22/788 [00:01<01:10, 10.82it/s]

  3%|█▏                                       | 24/788 [00:01<01:06, 11.48it/s]
  3%|█▎                                       | 26/788 [00:02<01:05, 11.65it/s]

  4%|█▍                                       | 28/788 [00:02<01:04, 11.83it/s]
  4%|█▌                                       | 30/788 [00:02<01:01, 12.23it/s]

  4%|█▋                                       | 32/788 [00:02<01:01, 12.38it/s]
  4%|█▊                                       | 34/788 [00:02<01:02, 12.10it/s]

  5%|█▊                                       | 36/788 [00:02<01:05, 11.50it/s]

  5%|██                                       | 39/788 [00:03<00:59, 12.63it/s]
  5%|██▏                                      | 41/788 [00:03<00:55, 13.44it/s]

  5%|██▏                                      | 43/788 [00:03<00:55, 13.36it/s]
  6%|██▎                                      | 45/788 [00:03<00:54, 13.60it/s]

  6%|██▍                                      | 47/788 [00:03<01:01, 12.08it/s]
  6%|██▌                                      | 49/788 [00:03<00:59, 12.33it/s]

  7%|██▋                                      | 52/788 [00:04<00:50, 14.47it/s]
  7%|██▊                                      | 54/788 [00:04<00:53, 13.80it/s]

  7%|██▉                                      | 56/788 [00:04<00:51, 14.14it/s]
  7%|███                                      | 58/788 [00:04<00:53, 13.74it/s]

  8%|███                                      | 60/788 [00:04<00:54, 13.33it/s]
  8%|███▏                                     | 62/788 [00:04<00:57, 12.54it/s]

  8%|███▎                                     | 64/788 [00:05<01:02, 11.63it/s]
  8%|███▍                                     | 66/788 [00:05<01:00, 11.94it/s]

  9%|███▌                                     | 68/788 [00:05<01:00, 11.82it/s]

  9%|███▋                                     | 70/788 [00:05<01:05, 10.96it/s]
  9%|███▋                                     | 72/788 [00:05<01:01, 11.67it/s]

  9%|███▊                                     | 74/788 [00:06<01:05, 10.85it/s]
 10%|███▉                                     | 76/788 [00:06<01:00, 11.72it/s]

 10%|████                                     | 78/788 [00:06<01:02, 11.36it/s]
 10%|████▏                                    | 80/788 [00:06<01:03, 11.09it/s]

 10%|████▎                                    | 82/788 [00:06<01:07, 10.52it/s]
 11%|████▎                                    | 84/788 [00:06<01:02, 11.24it/s]

 11%|████▍                                    | 86/788 [00:07<01:02, 11.31it/s]
 11%|████▌                                    | 88/788 [00:07<01:00, 11.61it/s]

 11%|████▋                                    | 90/788 [00:07<00:56, 12.33it/s]

 12%|████▊                                    | 92/788 [00:07<01:01, 11.25it/s]

 12%|████▉                                    | 94/788 [00:07<01:05, 10.67it/s]
 12%|████▉                                    | 96/788 [00:07<00:59, 11.68it/s]

 12%|█████                                    | 98/788 [00:08<01:02, 11.08it/s]
 13%|█████▏                                  | 101/788 [00:08<00:54, 12.71it/s]

 13%|█████▏                                  | 103/788 [00:08<00:56, 12.04it/s]

 13%|█████▎                                  | 105/788 [00:08<01:01, 11.17it/s]
 14%|█████▍                                  | 107/788 [00:08<00:58, 11.64it/s]

 14%|█████▌                                  | 109/788 [00:09<00:56, 11.94it/s]
 14%|█████▋                                  | 111/788 [00:09<00:51, 13.03it/s]

 14%|█████▋                                  | 113/788 [00:09<00:50, 13.41it/s]

 15%|█████▊                                  | 115/788 [00:09<00:56, 11.89it/s]
 15%|█████▉                                  | 117/788 [00:09<00:57, 11.66it/s]

 15%|██████                                  | 119/788 [00:09<00:56, 11.75it/s]
 15%|██████▏                                 | 121/788 [00:10<00:56, 11.74it/s]

 16%|██████▏                                 | 123/788 [00:10<00:57, 11.47it/s]
 16%|██████▎                                 | 125/788 [00:10<00:51, 12.81it/s]

 16%|██████▍                                 | 127/788 [00:10<00:46, 14.18it/s]
 16%|██████▌                                 | 129/788 [00:10<00:43, 15.08it/s]

 17%|██████▋                                 | 131/788 [00:10<00:47, 13.94it/s]
 17%|██████▊                                 | 133/788 [00:10<00:47, 13.69it/s]

 17%|██████▊                                 | 135/788 [00:10<00:47, 13.68it/s]
 17%|██████▉                                 | 137/788 [00:11<00:47, 13.71it/s]

 18%|███████                                 | 139/788 [00:11<00:48, 13.37it/s]
 18%|███████▏                                | 141/788 [00:11<00:50, 12.72it/s]

 18%|███████▎                                | 143/788 [00:11<00:50, 12.67it/s]
 18%|███████▎                                | 145/788 [00:11<00:51, 12.50it/s]

 19%|███████▌                                | 148/788 [00:11<00:42, 15.06it/s]
 19%|███████▋                                | 151/788 [00:12<00:40, 15.87it/s]

 19%|███████▊                                | 153/788 [00:12<00:40, 15.54it/s]
 20%|███████▊                                | 155/788 [00:12<00:44, 14.33it/s]

 20%|███████▉                                | 157/788 [00:12<00:43, 14.64it/s]
 20%|████████                                | 159/788 [00:12<00:45, 13.71it/s]

 20%|████████▏                               | 161/788 [00:12<00:46, 13.56it/s]

 21%|████████▎                               | 163/788 [00:13<00:52, 12.02it/s]
 21%|████████▍                               | 165/788 [00:13<00:48, 12.88it/s]

 21%|████████▍                               | 167/788 [00:13<00:53, 11.68it/s]
 21%|████████▌                               | 169/788 [00:13<00:53, 11.61it/s]

 22%|████████▋                               | 171/788 [00:13<00:50, 12.23it/s]
 22%|████████▊                               | 173/788 [00:13<00:48, 12.71it/s]

 22%|████████▉                               | 175/788 [00:14<00:50, 12.19it/s]
 22%|████████▉                               | 177/788 [00:14<00:52, 11.69it/s]

 23%|█████████                               | 179/788 [00:14<00:53, 11.45it/s]
 23%|█████████▏                              | 181/788 [00:14<00:55, 10.98it/s]

 23%|█████████▎                              | 183/788 [00:14<00:53, 11.22it/s]
 23%|█████████▍                              | 185/788 [00:14<00:53, 11.17it/s]

 24%|█████████▍                              | 187/788 [00:15<00:52, 11.38it/s]
 24%|█████████▌                              | 189/788 [00:15<00:50, 11.86it/s]

 24%|█████████▋                              | 191/788 [00:15<00:53, 11.10it/s]
 24%|█████████▊                              | 193/788 [00:15<00:52, 11.37it/s]

 25%|█████████▉                              | 195/788 [00:15<00:46, 12.81it/s]
 25%|██████████                              | 197/788 [00:15<00:43, 13.54it/s]

 25%|██████████                              | 199/788 [00:16<00:49, 11.98it/s]
 26%|██████████▏                             | 201/788 [00:16<00:48, 12.21it/s]

 26%|██████████▎                             | 203/788 [00:16<00:50, 11.48it/s]
 26%|██████████▍                             | 205/788 [00:16<00:48, 12.09it/s]

 26%|██████████▌                             | 207/788 [00:16<00:43, 13.43it/s]
 27%|██████████▌                             | 209/788 [00:16<00:46, 12.46it/s]

 27%|██████████▋                             | 211/788 [00:17<00:47, 12.13it/s]
 27%|██████████▊                             | 213/788 [00:17<00:45, 12.53it/s]

 27%|██████████▉                             | 215/788 [00:17<00:48, 11.88it/s]
 28%|███████████                             | 217/788 [00:17<00:47, 12.14it/s]

 28%|███████████                             | 219/788 [00:17<00:42, 13.50it/s]
 28%|███████████▏                            | 221/788 [00:17<00:45, 12.50it/s]

 28%|███████████▎                            | 223/788 [00:18<00:43, 13.12it/s]
 29%|███████████▍                            | 225/788 [00:18<00:42, 13.40it/s]

 29%|███████████▌                            | 227/788 [00:18<00:40, 13.97it/s]
 29%|███████████▌                            | 229/788 [00:18<00:37, 14.90it/s]

 29%|███████████▋                            | 231/788 [00:18<00:39, 14.06it/s]
 30%|███████████▊                            | 233/788 [00:18<00:39, 14.09it/s]

 30%|███████████▉                            | 235/788 [00:18<00:40, 13.54it/s]
 30%|████████████                            | 237/788 [00:19<00:41, 13.39it/s]

 30%|████████████▏                           | 239/788 [00:19<00:41, 13.33it/s]
 31%|████████████▏                           | 241/788 [00:19<00:40, 13.43it/s]

 31%|████████████▎                           | 243/788 [00:19<00:41, 13.12it/s]
 31%|████████████▍                           | 245/788 [00:19<00:44, 12.08it/s]

 31%|████████████▌                           | 247/788 [00:19<00:43, 12.43it/s]

 32%|████████████▋                           | 249/788 [00:20<00:47, 11.39it/s]
 32%|████████████▋                           | 251/788 [00:20<00:45, 11.70it/s]

 32%|████████████▊                           | 253/788 [00:20<00:45, 11.84it/s]
 32%|████████████▉                           | 255/788 [00:20<00:42, 12.53it/s]

 33%|█████████████                           | 257/788 [00:20<00:41, 12.67it/s]
 33%|█████████████▏                          | 259/788 [00:20<00:44, 11.90it/s]

 33%|█████████████▏                          | 261/788 [00:20<00:39, 13.27it/s]

 33%|█████████████▎                          | 263/788 [00:21<00:45, 11.65it/s]
 34%|█████████████▍                          | 265/788 [00:21<00:43, 12.12it/s]

 34%|█████████████▌                          | 267/788 [00:21<00:39, 13.15it/s]

 34%|█████████████▋                          | 269/788 [00:21<00:44, 11.77it/s]
 34%|█████████████▊                          | 271/788 [00:21<00:43, 11.98it/s]

 35%|█████████████▊                          | 273/788 [00:22<00:44, 11.47it/s]
 35%|█████████████▉                          | 275/788 [00:22<00:45, 11.34it/s]

 35%|██████████████                          | 277/788 [00:22<00:47, 10.65it/s]
 35%|██████████████▏                         | 279/788 [00:22<00:46, 10.88it/s]

 36%|██████████████▎                         | 281/788 [00:22<00:44, 11.47it/s]
 36%|██████████████▎                         | 283/788 [00:22<00:44, 11.47it/s]

 36%|██████████████▍                         | 285/788 [00:23<00:43, 11.57it/s]
 36%|██████████████▌                         | 287/788 [00:23<00:39, 12.73it/s]

 37%|██████████████▋                         | 289/788 [00:23<00:38, 12.81it/s]
 37%|██████████████▊                         | 291/788 [00:23<00:34, 14.21it/s]

 37%|██████████████▊                         | 293/788 [00:23<00:34, 14.43it/s]
 37%|██████████████▉                         | 295/788 [00:23<00:35, 13.81it/s]

 38%|███████████████                         | 297/788 [00:23<00:36, 13.61it/s]
 38%|███████████████▏                        | 299/788 [00:24<00:37, 12.99it/s]

 38%|███████████████▎                        | 301/788 [00:24<00:36, 13.24it/s]
 38%|███████████████▍                        | 303/788 [00:24<00:36, 13.30it/s]

 39%|███████████████▍                        | 305/788 [00:24<00:36, 13.08it/s]
 39%|███████████████▌                        | 307/788 [00:24<00:37, 12.97it/s]

 39%|███████████████▋                        | 309/788 [00:24<00:36, 13.17it/s]
 39%|███████████████▊                        | 311/788 [00:24<00:37, 12.75it/s]

 40%|███████████████▉                        | 313/788 [00:25<00:37, 12.54it/s]
 40%|███████████████▉                        | 315/788 [00:25<00:35, 13.27it/s]

 40%|████████████████                        | 317/788 [00:25<00:35, 13.41it/s]
 40%|████████████████▏                       | 319/788 [00:25<00:38, 12.33it/s]

 41%|████████████████▎                       | 321/788 [00:25<00:38, 12.20it/s]
 41%|████████████████▍                       | 323/788 [00:25<00:37, 12.52it/s]

 41%|████████████████▍                       | 325/788 [00:26<00:40, 11.42it/s]
 41%|████████████████▌                       | 327/788 [00:26<00:37, 12.29it/s]

 42%|████████████████▋                       | 329/788 [00:26<00:38, 12.03it/s]
 42%|████████████████▊                       | 331/788 [00:26<00:36, 12.36it/s]

 42%|████████████████▉                       | 333/788 [00:26<00:36, 12.58it/s]
 43%|█████████████████                       | 335/788 [00:26<00:32, 13.93it/s]

 43%|█████████████████                       | 337/788 [00:27<00:33, 13.55it/s]

 43%|█████████████████▏                      | 339/788 [00:27<00:36, 12.21it/s]
 43%|█████████████████▎                      | 341/788 [00:27<00:37, 11.91it/s]

 44%|█████████████████▍                      | 343/788 [00:27<00:37, 11.73it/s]

 44%|█████████████████▌                      | 345/788 [00:27<00:40, 10.87it/s]

 44%|█████████████████▌                      | 347/788 [00:28<00:42, 10.43it/s]
 44%|█████████████████▋                      | 349/788 [00:28<00:39, 11.24it/s]

 45%|█████████████████▊                      | 351/788 [00:28<00:37, 11.67it/s]
 45%|█████████████████▉                      | 353/788 [00:28<00:36, 12.04it/s]

 45%|██████████████████                      | 355/788 [00:28<00:34, 12.46it/s]
 45%|██████████████████                      | 357/788 [00:28<00:34, 12.34it/s]

 46%|██████████████████▏                     | 359/788 [00:28<00:36, 11.80it/s]
 46%|██████████████████▎                     | 361/788 [00:29<00:32, 13.10it/s]

 46%|██████████████████▍                     | 363/788 [00:29<00:29, 14.59it/s]
 46%|██████████████████▌                     | 365/788 [00:29<00:30, 13.92it/s]

 47%|██████████████████▋                     | 367/788 [00:29<00:28, 14.87it/s]
 47%|██████████████████▋                     | 369/788 [00:29<00:31, 13.45it/s]

 47%|██████████████████▊                     | 371/788 [00:29<00:28, 14.52it/s]
 47%|██████████████████▉                     | 373/788 [00:29<00:28, 14.55it/s]

 48%|███████████████████                     | 376/788 [00:30<00:27, 14.77it/s]
 48%|███████████████████▏                    | 379/788 [00:30<00:25, 15.75it/s]

 48%|███████████████████▎                    | 381/788 [00:30<00:27, 14.98it/s]
 49%|███████████████████▍                    | 383/788 [00:30<00:28, 14.21it/s]

 49%|███████████████████▌                    | 385/788 [00:30<00:28, 13.99it/s]

 49%|███████████████████▋                    | 387/788 [00:30<00:31, 12.54it/s]
 49%|███████████████████▋                    | 389/788 [00:31<00:31, 12.78it/s]

 50%|███████████████████▊                    | 391/788 [00:31<00:32, 12.03it/s]
 50%|███████████████████▉                    | 393/788 [00:31<00:32, 12.15it/s]

 50%|████████████████████                    | 395/788 [00:31<00:31, 12.54it/s]
 50%|████████████████████▏                   | 397/788 [00:31<00:28, 13.55it/s]

 51%|████████████████████▎                   | 399/788 [00:31<00:30, 12.75it/s]
 51%|████████████████████▎                   | 401/788 [00:31<00:29, 13.10it/s]

 51%|████████████████████▍                   | 403/788 [00:32<00:28, 13.40it/s]
 51%|████████████████████▌                   | 405/788 [00:32<00:30, 12.75it/s]

 52%|████████████████████▋                   | 407/788 [00:32<00:27, 14.02it/s]
 52%|████████████████████▊                   | 409/788 [00:32<00:28, 13.49it/s]

 52%|████████████████████▉                   | 412/788 [00:32<00:26, 14.00it/s]
 53%|█████████████████████                   | 414/788 [00:32<00:25, 14.66it/s]

 53%|█████████████████████                   | 416/788 [00:33<00:26, 13.98it/s]

 53%|█████████████████████▏                  | 418/788 [00:33<00:30, 12.18it/s]

 53%|█████████████████████▎                  | 420/788 [00:33<00:32, 11.36it/s]
 54%|█████████████████████▍                  | 422/788 [00:33<00:33, 10.96it/s]

 54%|█████████████████████▌                  | 424/788 [00:33<00:31, 11.51it/s]

 54%|█████████████████████▌                  | 426/788 [00:34<00:33, 10.87it/s]
 54%|█████████████████████▋                  | 428/788 [00:34<00:29, 12.19it/s]

 55%|█████████████████████▊                  | 430/788 [00:34<00:28, 12.38it/s]
 55%|█████████████████████▉                  | 432/788 [00:34<00:26, 13.24it/s]

 55%|██████████████████████                  | 434/788 [00:34<00:28, 12.53it/s]
 55%|██████████████████████▏                 | 436/788 [00:34<00:29, 11.83it/s]

 56%|██████████████████████▏                 | 438/788 [00:34<00:27, 12.92it/s]
 56%|██████████████████████▎                 | 440/788 [00:35<00:27, 12.80it/s]

 56%|██████████████████████▍                 | 442/788 [00:35<00:29, 11.68it/s]
 56%|██████████████████████▌                 | 444/788 [00:35<00:29, 11.83it/s]

 57%|██████████████████████▋                 | 446/788 [00:35<00:28, 11.86it/s]
 57%|██████████████████████▋                 | 448/788 [00:35<00:27, 12.15it/s]

 57%|██████████████████████▊                 | 450/788 [00:35<00:27, 12.23it/s]
 57%|██████████████████████▉                 | 452/788 [00:36<00:27, 12.40it/s]

 58%|███████████████████████                 | 454/788 [00:36<00:26, 12.67it/s]
 58%|███████████████████████▏                | 456/788 [00:36<00:25, 13.00it/s]

 58%|███████████████████████▏                | 458/788 [00:36<00:24, 13.65it/s]

 58%|███████████████████████▎                | 460/788 [00:36<00:27, 11.95it/s]
 59%|███████████████████████▍                | 462/788 [00:36<00:26, 12.42it/s]

 59%|███████████████████████▌                | 464/788 [00:37<00:25, 12.69it/s]
 59%|███████████████████████▋                | 466/788 [00:37<00:25, 12.40it/s]

 59%|███████████████████████▊                | 468/788 [00:37<00:27, 11.85it/s]

 60%|███████████████████████▊                | 470/788 [00:37<00:28, 11.00it/s]
 60%|███████████████████████▉                | 472/788 [00:37<00:28, 11.21it/s]

 60%|████████████████████████                | 474/788 [00:37<00:27, 11.49it/s]
 60%|████████████████████████▏               | 476/788 [00:38<00:26, 11.81it/s]

 61%|████████████████████████▎               | 478/788 [00:38<00:24, 12.54it/s]
 61%|████████████████████████▎               | 480/788 [00:38<00:24, 12.58it/s]

 61%|████████████████████████▍               | 482/788 [00:38<00:25, 11.95it/s]
 61%|████████████████████████▌               | 484/788 [00:38<00:26, 11.66it/s]

 62%|████████████████████████▋               | 486/788 [00:38<00:25, 11.67it/s]
 62%|████████████████████████▊               | 488/788 [00:39<00:25, 11.60it/s]

 62%|████████████████████████▊               | 490/788 [00:39<00:27, 10.91it/s]
 62%|████████████████████████▉               | 492/788 [00:39<00:25, 11.40it/s]

 63%|█████████████████████████               | 494/788 [00:39<00:25, 11.46it/s]
 63%|█████████████████████████▏              | 496/788 [00:39<00:23, 12.39it/s]

 63%|█████████████████████████▎              | 498/788 [00:39<00:21, 13.47it/s]
 63%|█████████████████████████▍              | 500/788 [00:40<00:20, 14.30it/s]

 64%|█████████████████████████▍              | 502/788 [00:40<00:21, 13.59it/s]
 64%|█████████████████████████▌              | 504/788 [00:40<00:22, 12.71it/s]

 64%|█████████████████████████▋              | 506/788 [00:40<00:19, 14.23it/s]
 64%|█████████████████████████▊              | 508/788 [00:40<00:19, 14.27it/s]

 65%|█████████████████████████▉              | 510/788 [00:40<00:20, 13.26it/s]
 65%|█████████████████████████▉              | 512/788 [00:40<00:18, 14.63it/s]

 65%|██████████████████████████              | 514/788 [00:41<00:18, 14.48it/s]
 65%|██████████████████████████▏             | 516/788 [00:41<00:18, 14.82it/s]

 66%|██████████████████████████▎             | 518/788 [00:41<00:18, 14.52it/s]
 66%|██████████████████████████▍             | 520/788 [00:41<00:18, 14.38it/s]

 66%|██████████████████████████▍             | 522/788 [00:41<00:18, 14.08it/s]
 66%|██████████████████████████▌             | 524/788 [00:41<00:18, 14.25it/s]

 67%|██████████████████████████▋             | 526/788 [00:41<00:20, 12.93it/s]
 67%|██████████████████████████▊             | 528/788 [00:42<00:19, 13.13it/s]

 67%|██████████████████████████▉             | 530/788 [00:42<00:20, 12.64it/s]
 68%|███████████████████████████             | 532/788 [00:42<00:19, 12.98it/s]

 68%|███████████████████████████             | 534/788 [00:42<00:20, 12.44it/s]
 68%|███████████████████████████▏            | 536/788 [00:42<00:20, 12.38it/s]

 68%|███████████████████████████▎            | 538/788 [00:42<00:22, 11.32it/s]

 69%|███████████████████████████▍            | 540/788 [00:43<00:22, 10.80it/s]
 69%|███████████████████████████▌            | 542/788 [00:43<00:23, 10.59it/s]

 69%|███████████████████████████▌            | 544/788 [00:43<00:23, 10.24it/s]
 69%|███████████████████████████▋            | 546/788 [00:43<00:22, 10.99it/s]

 70%|███████████████████████████▊            | 548/788 [00:43<00:21, 11.00it/s]
 70%|███████████████████████████▉            | 550/788 [00:44<00:20, 11.58it/s]

 70%|████████████████████████████            | 552/788 [00:44<00:18, 12.80it/s]
 70%|████████████████████████████            | 554/788 [00:44<00:17, 13.02it/s]

 71%|████████████████████████████▏           | 556/788 [00:44<00:19, 12.10it/s]
 71%|████████████████████████████▎           | 558/788 [00:44<00:17, 12.89it/s]

 71%|████████████████████████████▍           | 560/788 [00:44<00:16, 13.48it/s]
 71%|████████████████████████████▌           | 563/788 [00:44<00:14, 15.40it/s]

 72%|████████████████████████████▋           | 565/788 [00:45<00:16, 13.70it/s]
 72%|████████████████████████████▊           | 567/788 [00:45<00:17, 12.50it/s]

 72%|████████████████████████████▉           | 569/788 [00:45<00:15, 13.82it/s]
 72%|████████████████████████████▉           | 571/788 [00:45<00:16, 13.17it/s]

 73%|█████████████████████████████           | 573/788 [00:45<00:18, 11.81it/s]
 73%|█████████████████████████████▏          | 575/788 [00:45<00:17, 12.22it/s]

 73%|█████████████████████████████▎          | 577/788 [00:46<00:17, 12.26it/s]
 73%|█████████████████████████████▍          | 579/788 [00:46<00:16, 12.69it/s]

 74%|█████████████████████████████▍          | 581/788 [00:46<00:16, 12.91it/s]
 74%|█████████████████████████████▌          | 583/788 [00:46<00:16, 12.07it/s]

 74%|█████████████████████████████▋          | 585/788 [00:46<00:16, 12.33it/s]
 74%|█████████████████████████████▊          | 587/788 [00:46<00:16, 11.90it/s]

 75%|█████████████████████████████▉          | 589/788 [00:47<00:17, 11.27it/s]
 75%|██████████████████████████████          | 591/788 [00:47<00:15, 12.80it/s]

 75%|██████████████████████████████          | 593/788 [00:47<00:15, 12.70it/s]
 76%|██████████████████████████████▏         | 595/788 [00:47<00:16, 12.04it/s]

 76%|██████████████████████████████▎         | 597/788 [00:47<00:15, 12.53it/s]
 76%|██████████████████████████████▍         | 599/788 [00:47<00:14, 12.83it/s]

 76%|██████████████████████████████▌         | 601/788 [00:47<00:14, 13.31it/s]
 77%|██████████████████████████████▌         | 603/788 [00:48<00:13, 13.22it/s]

 77%|██████████████████████████████▋         | 605/788 [00:48<00:13, 13.51it/s]
 77%|██████████████████████████████▊         | 607/788 [00:48<00:12, 14.83it/s]

 77%|██████████████████████████████▉         | 609/788 [00:48<00:14, 12.66it/s]
 78%|███████████████████████████████         | 611/788 [00:48<00:14, 12.36it/s]

 78%|███████████████████████████████         | 613/788 [00:48<00:13, 13.37it/s]
 78%|███████████████████████████████▏        | 615/788 [00:49<00:12, 13.67it/s]

 78%|███████████████████████████████▎        | 617/788 [00:49<00:12, 13.18it/s]
 79%|███████████████████████████████▍        | 619/788 [00:49<00:12, 13.62it/s]

 79%|███████████████████████████████▌        | 621/788 [00:49<00:12, 13.67it/s]
 79%|███████████████████████████████▌        | 623/788 [00:49<00:11, 14.87it/s]

 79%|███████████████████████████████▋        | 625/788 [00:49<00:12, 12.92it/s]
 80%|███████████████████████████████▊        | 627/788 [00:49<00:13, 11.88it/s]

 80%|███████████████████████████████▉        | 629/788 [00:50<00:14, 10.97it/s]

 80%|████████████████████████████████        | 631/788 [00:50<00:15, 10.44it/s]
 80%|████████████████████████████████▏       | 633/788 [00:50<00:14, 10.98it/s]

 81%|████████████████████████████████▏       | 635/788 [00:50<00:12, 12.41it/s]
 81%|████████████████████████████████▎       | 637/788 [00:50<00:11, 12.62it/s]

 81%|████████████████████████████████▍       | 639/788 [00:51<00:12, 11.73it/s]
 81%|████████████████████████████████▌       | 642/788 [00:51<00:10, 13.73it/s]

 82%|████████████████████████████████▋       | 644/788 [00:51<00:10, 13.14it/s]
 82%|████████████████████████████████▊       | 646/788 [00:51<00:11, 12.71it/s]

 82%|████████████████████████████████▉       | 648/788 [00:51<00:10, 13.23it/s]
 83%|█████████████████████████████████       | 651/788 [00:51<00:09, 14.88it/s]

 83%|█████████████████████████████████▏      | 653/788 [00:52<00:09, 13.77it/s]
 83%|█████████████████████████████████▏      | 655/788 [00:52<00:10, 12.55it/s]

 83%|█████████████████████████████████▎      | 657/788 [00:52<00:10, 12.42it/s]
 84%|█████████████████████████████████▍      | 659/788 [00:52<00:10, 12.31it/s]

 84%|█████████████████████████████████▌      | 661/788 [00:52<00:10, 12.42it/s]
 84%|█████████████████████████████████▋      | 663/788 [00:52<00:10, 12.33it/s]

 84%|█████████████████████████████████▊      | 665/788 [00:53<00:09, 12.51it/s]

 85%|█████████████████████████████████▊      | 667/788 [00:53<00:10, 11.42it/s]
 85%|█████████████████████████████████▉      | 669/788 [00:53<00:09, 11.96it/s]

 85%|██████████████████████████████████      | 671/788 [00:53<00:09, 11.76it/s]
 85%|██████████████████████████████████▏     | 673/788 [00:53<00:09, 12.12it/s]

 86%|██████████████████████████████████▎     | 675/788 [00:53<00:09, 12.39it/s]
 86%|██████████████████████████████████▎     | 677/788 [00:53<00:08, 13.73it/s]

 86%|██████████████████████████████████▍     | 679/788 [00:54<00:08, 12.15it/s]
 86%|██████████████████████████████████▌     | 681/788 [00:54<00:08, 12.29it/s]

 87%|██████████████████████████████████▋     | 683/788 [00:54<00:07, 13.38it/s]
 87%|██████████████████████████████████▊     | 685/788 [00:54<00:08, 12.82it/s]

 87%|██████████████████████████████████▊     | 687/788 [00:54<00:08, 11.65it/s]
 87%|██████████████████████████████████▉     | 689/788 [00:54<00:08, 12.06it/s]

 88%|███████████████████████████████████     | 691/788 [00:55<00:08, 11.18it/s]
 88%|███████████████████████████████████▏    | 693/788 [00:55<00:07, 12.58it/s]

 88%|███████████████████████████████████▎    | 695/788 [00:55<00:07, 12.99it/s]
 88%|███████████████████████████████████▍    | 697/788 [00:55<00:07, 12.63it/s]

 89%|███████████████████████████████████▍    | 699/788 [00:55<00:06, 13.00it/s]
 89%|███████████████████████████████████▌    | 701/788 [00:55<00:07, 12.34it/s]

 89%|███████████████████████████████████▋    | 703/788 [00:56<00:07, 11.70it/s]
 89%|███████████████████████████████████▊    | 705/788 [00:56<00:07, 11.14it/s]

 90%|███████████████████████████████████▉    | 707/788 [00:56<00:07, 11.11it/s]
 90%|███████████████████████████████████▉    | 709/788 [00:56<00:06, 11.77it/s]

 90%|████████████████████████████████████    | 711/788 [00:56<00:06, 11.57it/s]
 90%|████████████████████████████████████▏   | 713/788 [00:56<00:06, 12.06it/s]

 91%|████████████████████████████████████▎   | 716/788 [00:57<00:05, 14.30it/s]
 91%|████████████████████████████████████▍   | 718/788 [00:57<00:04, 15.08it/s]

 91%|████████████████████████████████████▌   | 720/788 [00:57<00:05, 13.28it/s]
 92%|████████████████████████████████████▋   | 722/788 [00:57<00:05, 12.43it/s]

 92%|████████████████████████████████████▊   | 724/788 [00:57<00:05, 11.42it/s]
 92%|████████████████████████████████████▊   | 726/788 [00:57<00:05, 12.18it/s]

 92%|████████████████████████████████████▉   | 728/788 [00:58<00:05, 11.51it/s]

 93%|█████████████████████████████████████   | 730/788 [00:58<00:05, 10.84it/s]
 93%|█████████████████████████████████████▏  | 732/788 [00:58<00:04, 11.73it/s]

 93%|█████████████████████████████████████▎  | 734/788 [00:58<00:04, 11.57it/s]
 93%|█████████████████████████████████████▎  | 736/788 [00:58<00:04, 11.22it/s]

 94%|█████████████████████████████████████▍  | 738/788 [00:59<00:04, 11.55it/s]
 94%|█████████████████████████████████████▌  | 740/788 [00:59<00:04, 11.67it/s]

 94%|█████████████████████████████████████▋  | 743/788 [00:59<00:03, 13.09it/s]
 95%|█████████████████████████████████████▊  | 745/788 [00:59<00:03, 13.57it/s]

 95%|█████████████████████████████████████▉  | 747/788 [00:59<00:03, 13.17it/s]
 95%|██████████████████████████████████████  | 749/788 [00:59<00:03, 12.35it/s]

 95%|██████████████████████████████████████  | 751/788 [01:00<00:03, 11.87it/s]

 96%|██████████████████████████████████████▏ | 753/788 [01:00<00:03, 11.18it/s]
 96%|██████████████████████████████████████▎ | 755/788 [01:00<00:02, 11.79it/s]

 96%|██████████████████████████████████████▍ | 757/788 [01:00<00:02, 11.58it/s]
 96%|██████████████████████████████████████▌ | 759/788 [01:00<00:02, 11.83it/s]

 97%|██████████████████████████████████████▋ | 761/788 [01:00<00:02, 12.18it/s]
 97%|██████████████████████████████████████▊ | 764/788 [01:01<00:01, 14.58it/s]

 97%|██████████████████████████████████████▉ | 766/788 [01:01<00:01, 14.28it/s]
 97%|██████████████████████████████████████▉ | 768/788 [01:01<00:01, 13.15it/s]

 98%|███████████████████████████████████████ | 770/788 [01:01<00:01, 14.09it/s]
 98%|███████████████████████████████████████▏| 772/788 [01:01<00:01, 12.97it/s]

 98%|███████████████████████████████████████▎| 774/788 [01:01<00:00, 14.43it/s]
 98%|███████████████████████████████████████▍| 776/788 [01:01<00:00, 14.08it/s]

 99%|███████████████████████████████████████▍| 778/788 [01:02<00:00, 13.97it/s]
 99%|███████████████████████████████████████▌| 780/788 [01:02<00:00, 14.86it/s]

 99%|███████████████████████████████████████▋| 782/788 [01:02<00:00, 14.00it/s]
 99%|███████████████████████████████████████▊| 784/788 [01:02<00:00, 14.43it/s]

 67%|████████████████████████            | 28350/42525 [54:21<30:00,  7.87it/s]
100%|████████████████████████████████████████| 788/788 [01:02<00:00, 14.43it/s]

Writing model shards:   0%|                              | 0/1 [00:00<?, ?it/s]

{'eval_loss': 'nan', 'eval_accuracy': '0.2', 'eval_macro_f1': '0.06667', 'eval_mae': '2', 'eval_cil_score': '0.5', 'eval_quadratic_weighted_kappa': '0', 'eval_runtime': '62.8', 'eval_samples_per_second': '401.3', 'eval_steps_per_second': '12.55', 'epoch': '2'}

Writing model shards: 100%|██████████████████████| 1/1 [00:00<00:00,  1.37it/s]

 67%|██████████████████████           | 28352/42525 [54:23<38:25:30,  9.76s/it]

 67%|██████████████████████           | 28356/42525 [54:23<15:44:19,  4.00s/it]

 67%|██████████████████████▋           | 28358/42525 [54:24<9:56:44,  2.53s/it]

 67%|██████████████████████▋           | 28362/42525 [54:24<4:08:25,  1.05s/it]

 67%|██████████████████████▋           | 28365/42525 [54:24<2:23:40,  1.64it/s]

 67%|██████████████████████▋           | 28368/42525 [54:25<1:26:02,  2.74it/s]

 67%|██████████████████████▋           | 28370/42525 [54:25<1:02:32,  3.77it/s]

 67%|████████████████████████            | 28373/42525 [54:25<43:50,  5.38it/s]

 67%|████████████████████████            | 28375/42525 [54:26<37:37,  6.27it/s]

 67%|████████████████████████            | 28377/42525 [54:26<34:47,  6.78it/s]

 67%|████████████████████████            | 28379/42525 [54:26<29:49,  7.91it/s]

 67%|████████████████████████            | 28383/42525 [54:26<25:42,  9.17it/s]

 67%|████████████████████████            | 28386/42525 [54:27<26:43,  8.82it/s]

 67%|████████████████████████            | 28390/42525 [54:27<25:08,  9.37it/s]

 67%|████████████████████████            | 28391/42525 [54:27<26:39,  8.84it/s]

 67%|████████████████████████            | 28393/42525 [54:28<27:26,  8.58it/s]

 67%|████████████████████████            | 28395/42525 [54:28<26:34,  8.86it/s]

 67%|████████████████████████            | 28399/42525 [54:28<24:56,  9.44it/s]

 67%|████████████████████████            | 28401/42525 [54:28<26:48,  8.78it/s]

 67%|████████████████████████            | 28404/42525 [54:29<25:23,  9.27it/s]

 67%|████████████████████████            | 28406/42525 [54:29<25:11,  9.34it/s]

 67%|████████████████████████            | 28409/42525 [54:29<26:35,  8.85it/s]

 67%|████████████████████████            | 28411/42525 [54:30<28:13,  8.33it/s]

 67%|████████████████████████            | 28414/42525 [54:30<26:10,  8.99it/s]

 67%|████████████████████████            | 28417/42525 [54:30<26:03,  9.02it/s]

 67%|████████████████████████            | 28420/42525 [54:31<24:33,  9.57it/s]

 67%|████████████████████████            | 28422/42525 [54:31<27:38,  8.50it/s]

 67%|████████████████████████            | 28425/42525 [54:31<25:30,  9.21it/s]

 67%|████████████████████████            | 28428/42525 [54:31<24:25,  9.62it/s]

 67%|████████████████████████            | 28431/42525 [54:32<23:48,  9.86it/s]

 67%|████████████████████████            | 28434/42525 [54:32<25:54,  9.07it/s]

 67%|████████████████████████            | 28436/42525 [54:32<25:17,  9.28it/s]

 67%|████████████████████████            | 28437/42525 [54:32<27:42,  8.47it/s]

 67%|████████████████████████            | 28441/42525 [54:33<25:05,  9.35it/s]

 67%|████████████████████████            | 28445/42525 [54:33<23:43,  9.89it/s]

 67%|████████████████████████            | 28449/42525 [54:34<24:27,  9.59it/s]

 67%|████████████████████████            | 28451/42525 [54:34<23:50,  9.84it/s]

 67%|████████████████████████            | 28455/42525 [54:34<23:48,  9.85it/s]

 67%|████████████████████████            | 28457/42525 [54:34<24:02,  9.75it/s]

 67%|████████████████████████            | 28461/42525 [54:35<24:22,  9.62it/s]

 67%|████████████████████████            | 28463/42525 [54:35<24:24,  9.60it/s]

 67%|████████████████████████            | 28466/42525 [54:35<26:32,  8.83it/s]

 67%|████████████████████████            | 28470/42525 [54:36<24:07,  9.71it/s]

 67%|████████████████████████            | 28472/42525 [54:36<27:56,  8.38it/s]

 67%|████████████████████████            | 28474/42525 [54:36<28:03,  8.35it/s]

 67%|████████████████████████            | 28478/42525 [54:37<26:36,  8.80it/s]

 67%|████████████████████████            | 28480/42525 [54:37<27:24,  8.54it/s]

 67%|████████████████████████            | 28484/42525 [54:37<24:56,  9.38it/s]

 67%|████████████████████████            | 28486/42525 [54:38<24:05,  9.71it/s]

 67%|████████████████████████            | 28488/42525 [54:38<25:32,  9.16it/s]

 67%|████████████████████████            | 28490/42525 [54:38<25:20,  9.23it/s]

 67%|████████████████████████            | 28493/42525 [54:38<25:42,  9.10it/s]

 67%|████████████████████████            | 28495/42525 [54:39<25:36,  9.13it/s]

 67%|████████████████████████▏           | 28498/42525 [54:39<26:47,  8.73it/s]

 67%|████████████████████████▏           | 28502/42525 [54:39<24:08,  9.68it/s]

 67%|████████████████████████▏           | 28504/42525 [54:40<23:25,  9.98it/s]

 67%|████████████████████████▏           | 28508/42525 [54:40<24:03,  9.71it/s]

 67%|████████████████████████▏           | 28512/42525 [54:40<24:29,  9.54it/s]

 67%|████████████████████████▏           | 28514/42525 [54:41<26:37,  8.77it/s]

 67%|████████████████████████▏           | 28517/42525 [54:41<26:00,  8.98it/s]

 67%|████████████████████████▏           | 28520/42525 [54:41<24:16,  9.62it/s]

 67%|████████████████████████▏           | 28522/42525 [54:42<24:40,  9.46it/s]

 67%|████████████████████████▏           | 28526/42525 [54:42<23:44,  9.83it/s]

 67%|████████████████████████▏           | 28530/42525 [54:42<23:00, 10.14it/s]

 67%|████████████████████████▏           | 28532/42525 [54:43<22:51, 10.20it/s]

 67%|████████████████████████▏           | 28535/42525 [54:43<25:20,  9.20it/s]

 67%|████████████████████████▏           | 28539/42525 [54:43<23:29,  9.92it/s]

 67%|████████████████████████▏           | 28542/42525 [54:44<24:52,  9.37it/s]

 67%|████████████████████████▏           | 28545/42525 [54:44<24:07,  9.66it/s]

 67%|████████████████████████▏           | 28548/42525 [54:44<24:20,  9.57it/s]

 67%|████████████████████████▏           | 28551/42525 [54:45<26:18,  8.85it/s]

 67%|████████████████████████▏           | 28555/42525 [54:45<24:11,  9.63it/s]

 67%|████████████████████████▏           | 28558/42525 [54:45<26:39,  8.73it/s]

 67%|████████████████████████▏           | 28562/42525 [54:46<24:23,  9.54it/s]

 67%|████████████████████████▏           | 28565/42525 [54:46<23:55,  9.72it/s]

 67%|████████████████████████▏           | 28569/42525 [54:46<23:06, 10.07it/s]

 67%|████████████████████████▏           | 28573/42525 [54:47<23:12, 10.02it/s]

 67%|████████████████████████▏           | 28575/42525 [54:47<23:45,  9.79it/s]

 67%|████████████████████████▏           | 28577/42525 [54:47<24:34,  9.46it/s]

 67%|████████████████████████▏           | 28580/42525 [54:48<23:36,  9.84it/s]

 67%|████████████████████████▏           | 28583/42525 [54:48<24:39,  9.42it/s]

 67%|████████████████████████▏           | 28586/42525 [54:48<23:53,  9.72it/s]

 67%|████████████████████████▏           | 28589/42525 [54:49<23:12, 10.01it/s]

 67%|████████████████████████▏           | 28591/42525 [54:49<24:07,  9.63it/s]

 67%|████████████████████████▏           | 28592/42525 [54:49<25:12,  9.21it/s]

 67%|████████████████████████▏           | 28595/42525 [54:49<25:46,  9.01it/s]

 67%|████████████████████████▏           | 28597/42525 [54:49<28:28,  8.15it/s]

 67%|████████████████████████▏           | 28601/42525 [54:50<26:17,  8.83it/s]

 67%|████████████████████████▏           | 28603/42525 [54:50<28:52,  8.04it/s]

 67%|████████████████████████▏           | 28607/42525 [54:51<24:57,  9.30it/s]

 67%|████████████████████████▏           | 28610/42525 [54:51<24:52,  9.33it/s]

 67%|████████████████████████▏           | 28614/42525 [54:51<24:34,  9.43it/s]

 67%|████████████████████████▏           | 28618/42525 [54:52<24:44,  9.37it/s]

 67%|████████████████████████▏           | 28620/42525 [54:52<25:34,  9.06it/s]

 67%|████████████████████████▏           | 28623/42525 [54:52<25:17,  9.16it/s]

 67%|████████████████████████▏           | 28626/42525 [54:53<24:09,  9.59it/s]

 67%|████████████████████████▏           | 28628/42525 [54:53<28:17,  8.19it/s]

 67%|████████████████████████▏           | 28629/42525 [54:53<29:45,  7.78it/s]

 67%|████████████████████████▏           | 28632/42525 [54:53<28:11,  8.22it/s]

 67%|████████████████████████▏           | 28635/42525 [54:54<27:30,  8.42it/s]

 67%|████████████████████████▏           | 28637/42525 [54:54<25:51,  8.95it/s]

 67%|████████████████████████▏           | 28640/42525 [54:54<26:23,  8.77it/s]

 67%|████████████████████████▏           | 28643/42525 [54:55<28:30,  8.11it/s]

 67%|████████████████████████▎           | 28646/42525 [54:55<25:34,  9.04it/s]

 67%|████████████████████████▎           | 28649/42525 [54:55<24:37,  9.39it/s]

 67%|████████████████████████▎           | 28652/42525 [54:56<24:25,  9.46it/s]

 67%|████████████████████████▎           | 28653/42525 [54:56<26:06,  8.86it/s]

 67%|████████████████████████▎           | 28657/42525 [54:56<25:27,  9.08it/s]

 67%|████████████████████████▎           | 28661/42525 [54:57<23:43,  9.74it/s]

 67%|████████████████████████▎           | 28665/42525 [54:57<23:15,  9.93it/s]

 67%|████████████████████████▎           | 28667/42525 [54:57<24:26,  9.45it/s]

 67%|████████████████████████▎           | 28670/42525 [54:58<25:11,  9.17it/s]

 67%|████████████████████████▎           | 28673/42525 [54:58<24:09,  9.56it/s]

 67%|████████████████████████▎           | 28676/42525 [54:58<24:07,  9.57it/s]

 67%|████████████████████████▎           | 28678/42525 [54:58<25:00,  9.23it/s]

 67%|████████████████████████▎           | 28680/42525 [54:59<25:35,  9.02it/s]

 67%|████████████████████████▎           | 28684/42525 [54:59<23:30,  9.82it/s]

 67%|████████████████████████▎           | 28685/42525 [54:59<24:00,  9.61it/s]

 67%|████████████████████████▎           | 28687/42525 [54:59<23:55,  9.64it/s]

 67%|████████████████████████▎           | 28691/42525 [55:00<23:16,  9.91it/s]

 67%|████████████████████████▎           | 28694/42525 [55:00<23:08,  9.96it/s]

 67%|████████████████████████▎           | 28696/42525 [55:00<26:47,  8.60it/s]

 67%|████████████████████████▎           | 28700/42525 [55:01<24:12,  9.52it/s]

 67%|████████████████████████▎           | 28702/42525 [55:01<23:52,  9.65it/s]

 68%|████████████████████████▎           | 28705/42525 [55:01<27:03,  8.51it/s]

 68%|████████████████████████▎           | 28708/42525 [55:02<24:55,  9.24it/s]

 68%|████████████████████████▎           | 28709/42525 [55:02<25:10,  9.15it/s]

 68%|████████████████████████▎           | 28713/42525 [55:02<24:01,  9.58it/s]

 68%|████████████████████████▎           | 28716/42525 [55:02<24:01,  9.58it/s]

 68%|████████████████████████▎           | 28720/42525 [55:03<23:03,  9.98it/s]

 68%|████████████████████████▎           | 28724/42525 [55:03<24:02,  9.57it/s]

 68%|████████████████████████▎           | 28726/42525 [55:03<23:24,  9.83it/s]

 68%|████████████████████████▎           | 28729/42525 [55:04<25:35,  8.98it/s]

 68%|████████████████████████▎           | 28732/42525 [55:04<24:12,  9.50it/s]

 68%|████████████████████████▎           | 28736/42525 [55:05<24:38,  9.33it/s]

 68%|████████████████████████▎           | 28739/42525 [55:05<24:03,  9.55it/s]

 68%|████████████████████████▎           | 28742/42525 [55:05<24:07,  9.52it/s]

 68%|████████████████████████▎           | 28745/42525 [55:05<23:25,  9.81it/s]

 68%|████████████████████████▎           | 28746/42525 [55:06<25:48,  8.90it/s]

 68%|████████████████████████▎           | 28750/42525 [55:06<24:03,  9.54it/s]

 68%|████████████████████████▎           | 28753/42525 [55:06<23:35,  9.73it/s]

 68%|████████████████████████▎           | 28755/42525 [55:07<24:34,  9.34it/s]

 68%|████████████████████████▎           | 28758/42525 [55:07<26:59,  8.50it/s]

 68%|████████████████████████▎           | 28760/42525 [55:07<26:37,  8.62it/s]

 68%|████████████████████████▎           | 28762/42525 [55:07<26:16,  8.73it/s]

 68%|████████████████████████▎           | 28764/42525 [55:08<25:14,  9.09it/s]

 68%|████████████████████████▎           | 28768/42525 [55:08<23:10,  9.89it/s]

 68%|████████████████████████▎           | 28770/42525 [55:08<27:43,  8.27it/s]

 68%|████████████████████████▎           | 28772/42525 [55:09<30:34,  7.50it/s]

 68%|████████████████████████▎           | 28775/42525 [55:09<26:01,  8.81it/s]

 68%|████████████████████████▎           | 28778/42525 [55:09<24:26,  9.38it/s]

 68%|████████████████████████▎           | 28781/42525 [55:10<24:32,  9.33it/s]

 68%|████████████████████████▎           | 28784/42525 [55:10<24:48,  9.23it/s]

 68%|████████████████████████▎           | 28785/42525 [55:10<24:48,  9.23it/s]

 68%|████████████████████████▎           | 28788/42525 [55:10<24:54,  9.19it/s]

 68%|████████████████████████▎           | 28792/42525 [55:11<23:10,  9.87it/s]

 68%|████████████████████████▍           | 28796/42525 [55:11<22:39, 10.10it/s]

 68%|████████████████████████▍           | 28800/42525 [55:11<23:45,  9.63it/s]

 68%|████████████████████████▍           | 28802/42525 [55:12<26:00,  8.80it/s]

 68%|████████████████████████▍           | 28804/42525 [55:12<25:58,  8.80it/s]

 68%|████████████████████████▍           | 28806/42525 [55:12<27:35,  8.28it/s]

 68%|████████████████████████▍           | 28810/42525 [55:13<24:13,  9.43it/s]

 68%|████████████████████████▍           | 28812/42525 [55:13<28:12,  8.10it/s]

 68%|████████████████████████▍           | 28815/42525 [55:13<26:36,  8.59it/s]

 68%|████████████████████████▍           | 28818/42525 [55:14<25:47,  8.86it/s]

 68%|████████████████████████▍           | 28820/42525 [55:14<25:15,  9.05it/s]

 68%|████████████████████████▍           | 28822/42525 [55:14<27:20,  8.35it/s]

 68%|████████████████████████▍           | 28824/42525 [55:14<27:42,  8.24it/s]

 68%|████████████████████████▍           | 28827/42525 [55:15<26:48,  8.51it/s]

 68%|████████████████████████▍           | 28828/42525 [55:15<28:27,  8.02it/s]

 68%|████████████████████████▍           | 28830/42525 [55:15<26:25,  8.64it/s]

 68%|████████████████████████▍           | 28833/42525 [55:15<28:33,  7.99it/s]

 68%|████████████████████████▍           | 28836/42525 [55:16<25:34,  8.92it/s]

 68%|████████████████████████▍           | 28839/42525 [55:16<25:32,  8.93it/s]

 68%|████████████████████████▍           | 28842/42525 [55:16<24:40,  9.24it/s]

 68%|████████████████████████▍           | 28844/42525 [55:17<25:18,  9.01it/s]

 68%|████████████████████████▍           | 28847/42525 [55:17<24:29,  9.31it/s]

 68%|████████████████████████▍           | 28850/42525 [55:17<24:52,  9.16it/s]

 68%|████████████████████████▍           | 28852/42525 [55:18<26:49,  8.50it/s]

 68%|████████████████████████▍           | 28854/42525 [55:18<25:12,  9.04it/s]

 68%|████████████████████████▍           | 28857/42525 [55:18<24:56,  9.14it/s]

 68%|████████████████████████▍           | 28860/42525 [55:18<24:22,  9.34it/s]

 68%|████████████████████████▍           | 28863/42525 [55:19<23:41,  9.61it/s]

 68%|████████████████████████▍           | 28865/42525 [55:19<25:34,  8.90it/s]

 68%|████████████████████████▍           | 28868/42525 [55:19<23:58,  9.50it/s]

 68%|████████████████████████▍           | 28872/42525 [55:20<22:58,  9.90it/s]

 68%|████████████████████████▍           | 28875/42525 [55:20<24:50,  9.16it/s]

 68%|████████████████████████▍           | 28877/42525 [55:20<26:12,  8.68it/s]

 68%|████████████████████████▍           | 28879/42525 [55:20<24:35,  9.25it/s]

 68%|████████████████████████▍           | 28881/42525 [55:21<24:55,  9.13it/s]

 68%|████████████████████████▍           | 28884/42525 [55:21<25:08,  9.05it/s]

 68%|████████████████████████▍           | 28887/42525 [55:21<24:42,  9.20it/s]

 68%|████████████████████████▍           | 28890/42525 [55:22<24:19,  9.34it/s]

 68%|████████████████████████▍           | 28893/42525 [55:22<23:51,  9.52it/s]

 68%|████████████████████████▍           | 28896/42525 [55:22<24:30,  9.27it/s]

 68%|████████████████████████▍           | 28900/42525 [55:23<23:04,  9.84it/s]

 68%|████████████████████████▍           | 28901/42525 [55:23<23:34,  9.63it/s]

 68%|████████████████████████▍           | 28904/42525 [55:23<23:32,  9.64it/s]

 68%|████████████████████████▍           | 28908/42525 [55:24<23:34,  9.63it/s]

 68%|████████████████████████▍           | 28912/42525 [55:24<23:08,  9.81it/s]

 68%|████████████████████████▍           | 28915/42525 [55:24<22:53,  9.91it/s]

 68%|████████████████████████▍           | 28918/42525 [55:25<23:01,  9.85it/s]

 68%|████████████████████████▍           | 28921/42525 [55:25<25:08,  9.02it/s]

 68%|████████████████████████▍           | 28925/42525 [55:25<23:25,  9.67it/s]

 68%|████████████████████████▍           | 28927/42525 [55:26<26:59,  8.39it/s]

 68%|████████████████████████▍           | 28929/42525 [55:26<25:09,  9.01it/s]

 68%|████████████████████████▍           | 28931/42525 [55:26<24:47,  9.14it/s]

 68%|████████████████████████▍           | 28934/42525 [55:26<26:00,  8.71it/s]

 68%|████████████████████████▍           | 28936/42525 [55:27<24:42,  9.17it/s]

 68%|████████████████████████▍           | 28939/42525 [55:27<26:44,  8.47it/s]

 68%|████████████████████████▌           | 28941/42525 [55:27<26:30,  8.54it/s]

 68%|████████████████████████▌           | 28943/42525 [55:27<25:52,  8.75it/s]

 68%|████████████████████████▌           | 28945/42525 [55:28<26:43,  8.47it/s]

 68%|████████████████████████▌           | 28946/42525 [55:28<28:41,  7.89it/s]

 68%|████████████████████████▌           | 28948/42525 [55:28<28:24,  7.96it/s]

 68%|████████████████████████▌           | 28950/42525 [55:28<28:11,  8.02it/s]

 68%|████████████████████████▌           | 28953/42525 [55:29<25:42,  8.80it/s]

 68%|████████████████████████▌           | 28955/42525 [55:29<28:22,  7.97it/s]

 68%|████████████████████████▌           | 28956/42525 [55:29<28:00,  8.07it/s]

 68%|████████████████████████▌           | 28959/42525 [55:29<26:26,  8.55it/s]

 68%|████████████████████████▌           | 28962/42525 [55:30<24:24,  9.26it/s]

 68%|████████████████████████▌           | 28966/42525 [55:30<24:27,  9.24it/s]

 68%|████████████████████████▌           | 28968/42525 [55:30<27:59,  8.07it/s]

 68%|████████████████████████▌           | 28970/42525 [55:31<25:45,  8.77it/s]

 68%|████████████████████████▌           | 28973/42525 [55:31<24:07,  9.36it/s]

 68%|████████████████████████▌           | 28975/42525 [55:31<28:27,  7.93it/s]

 68%|████████████████████████▌           | 28976/42525 [55:31<27:34,  8.19it/s]

 68%|████████████████████████▌           | 28980/42525 [55:32<24:12,  9.33it/s]

 68%|████████████████████████▌           | 28981/42525 [55:32<26:13,  8.61it/s]

 68%|████████████████████████▌           | 28983/42525 [55:32<25:27,  8.87it/s]

 68%|████████████████████████▌           | 28987/42525 [55:32<23:40,  9.53it/s]

 68%|████████████████████████▌           | 28989/42525 [55:33<25:02,  9.01it/s]

 68%|████████████████████████▌           | 28992/42525 [55:33<24:29,  9.21it/s]

 68%|████████████████████████▌           | 28995/42525 [55:33<24:42,  9.13it/s]

 68%|████████████████████████▌           | 28998/42525 [55:34<24:53,  9.06it/s]

 68%|████████████████████████▌           | 29001/42525 [55:34<25:52,  8.71it/s]

 68%|████████████████████████▌           | 29003/42525 [55:34<26:02,  8.66it/s]

 68%|████████████████████████▌           | 29005/42525 [55:34<25:49,  8.73it/s]

 68%|████████████████████████▌           | 29007/42525 [55:35<29:24,  7.66it/s]

 68%|████████████████████████▌           | 29009/42525 [55:35<29:10,  7.72it/s]

 68%|████████████████████████▌           | 29011/42525 [55:35<29:11,  7.71it/s]

 68%|████████████████████████▌           | 29015/42525 [55:36<24:46,  9.09it/s]

 68%|████████████████████████▌           | 29017/42525 [55:36<26:15,  8.58it/s]

 68%|████████████████████████▌           | 29020/42525 [55:36<24:15,  9.28it/s]

 68%|████████████████████████▌           | 29024/42525 [55:37<22:50,  9.85it/s]

 68%|████████████████████████▌           | 29027/42525 [55:37<26:18,  8.55it/s]

 68%|████████████████████████▌           | 29030/42525 [55:37<24:44,  9.09it/s]

 68%|████████████████████████▌           | 29032/42525 [55:38<23:29,  9.57it/s]

 68%|████████████████████████▌           | 29035/42525 [55:38<24:15,  9.27it/s]

 68%|████████████████████████▌           | 29037/42525 [55:38<24:27,  9.19it/s]

 68%|████████████████████████▌           | 29040/42525 [55:38<23:57,  9.38it/s]

 68%|████████████████████████▌           | 29044/42525 [55:39<22:55,  9.80it/s]

 68%|████████████████████████▌           | 29047/42525 [55:39<23:47,  9.44it/s]

 68%|████████████████████████▌           | 29050/42525 [55:39<24:09,  9.29it/s]

 68%|████████████████████████▌           | 29053/42525 [55:40<23:13,  9.67it/s]

 68%|████████████████████████▌           | 29056/42525 [55:40<23:05,  9.72it/s]

 68%|████████████████████████▌           | 29059/42525 [55:40<24:48,  9.05it/s]

 68%|████████████████████████▌           | 29061/42525 [55:41<25:02,  8.96it/s]

 68%|████████████████████████▌           | 29062/42525 [55:41<24:29,  9.16it/s]

 68%|████████████████████████▌           | 29065/42525 [55:41<26:04,  8.60it/s]

 68%|████████████████████████▌           | 29067/42525 [55:41<25:43,  8.72it/s]

 68%|████████████████████████▌           | 29069/42525 [55:42<24:52,  9.02it/s]

 68%|████████████████████████▌           | 29072/42525 [55:42<23:33,  9.52it/s]

 68%|████████████████████████▌           | 29075/42525 [55:42<25:07,  8.92it/s]

 68%|████████████████████████▌           | 29077/42525 [55:42<25:01,  8.95it/s]

 68%|████████████████████████▌           | 29080/42525 [55:43<26:02,  8.60it/s]

 68%|████████████████████████▌           | 29084/42525 [55:43<23:29,  9.54it/s]

 68%|████████████████████████▌           | 29087/42525 [55:43<24:01,  9.32it/s]

 68%|████████████████████████▋           | 29090/42525 [55:44<25:12,  8.89it/s]

 68%|████████████████████████▋           | 29093/42525 [55:44<26:23,  8.48it/s]

 68%|████████████████████████▋           | 29095/42525 [55:44<25:06,  8.91it/s]

 68%|████████████████████████▋           | 29098/42525 [55:45<24:22,  9.18it/s]

 68%|████████████████████████▋           | 29101/42525 [55:45<25:43,  8.70it/s]

 68%|████████████████████████▋           | 29104/42525 [55:45<27:16,  8.20it/s]

 68%|████████████████████████▋           | 29105/42525 [55:46<28:36,  7.82it/s]

 68%|████████████████████████▋           | 29108/42525 [55:46<26:55,  8.31it/s]

 68%|████████████████████████▋           | 29110/42525 [55:46<24:59,  8.95it/s]

 68%|████████████████████████▋           | 29113/42525 [55:46<24:26,  9.14it/s]

 68%|████████████████████████▋           | 29117/42525 [55:47<22:44,  9.82it/s]

 68%|████████████████████████▋           | 29120/42525 [55:47<24:32,  9.10it/s]

 68%|████████████████████████▋           | 29121/42525 [55:47<24:46,  9.02it/s]

 68%|████████████████████████▋           | 29123/42525 [55:48<25:04,  8.91it/s]

 68%|████████████████████████▋           | 29125/42525 [55:48<25:02,  8.92it/s]

 68%|████████████████████████▋           | 29128/42525 [55:48<25:23,  8.79it/s]

 69%|████████████████████████▋           | 29131/42525 [55:48<23:57,  9.32it/s]

 69%|████████████████████████▋           | 29133/42525 [55:49<23:50,  9.36it/s]

 69%|████████████████████████▋           | 29137/42525 [55:49<22:52,  9.76it/s]

 69%|████████████████████████▋           | 29140/42525 [55:49<22:29,  9.92it/s]

 69%|████████████████████████▋           | 29142/42525 [55:50<23:28,  9.50it/s]

 69%|████████████████████████▋           | 29146/42525 [55:50<22:26,  9.94it/s]

 69%|████████████████████████▋           | 29148/42525 [55:50<24:07,  9.24it/s]

 69%|████████████████████████▋           | 29151/42525 [55:51<24:26,  9.12it/s]

 69%|████████████████████████▋           | 29154/42525 [55:51<24:24,  9.13it/s]

 69%|████████████████████████▋           | 29157/42525 [55:51<23:47,  9.36it/s]

 69%|████████████████████████▋           | 29160/42525 [55:52<23:59,  9.29it/s]

 69%|████████████████████████▋           | 29162/42525 [55:52<23:01,  9.67it/s]

 69%|████████████████████████▋           | 29166/42525 [55:52<22:46,  9.77it/s]

 69%|████████████████████████▋           | 29168/42525 [55:52<22:18,  9.98it/s]

 69%|████████████████████████▋           | 29172/42525 [55:53<22:19,  9.97it/s]

 69%|████████████████████████▋           | 29174/42525 [55:53<21:59, 10.12it/s]

 69%|████████████████████████▋           | 29177/42525 [55:53<22:39,  9.82it/s]

 69%|████████████████████████▋           | 29180/42525 [55:54<23:03,  9.65it/s]

 69%|████████████████████████▋           | 29184/42525 [55:54<22:05, 10.06it/s]

 69%|████████████████████████▋           | 29186/42525 [55:54<21:51, 10.17it/s]

 69%|████████████████████████▋           | 29189/42525 [55:54<24:13,  9.17it/s]

 69%|████████████████████████▋           | 29191/42525 [55:55<25:58,  8.56it/s]

 69%|████████████████████████▋           | 29194/42525 [55:55<25:12,  8.82it/s]

 69%|████████████████████████▋           | 29196/42525 [55:55<25:52,  8.58it/s]

 69%|████████████████████████▋           | 29198/42525 [55:56<25:47,  8.61it/s]

 69%|████████████████████████▋           | 29200/42525 [55:56<24:02,  9.24it/s]

 69%|████████████████████████▋           | 29202/42525 [55:56<25:13,  8.80it/s]

 69%|████████████████████████▋           | 29205/42525 [55:56<24:26,  9.08it/s]

 69%|████████████████████████▋           | 29207/42525 [55:56<23:32,  9.43it/s]

 69%|████████████████████████▋           | 29210/42525 [55:57<24:51,  8.93it/s]

 69%|████████████████████████▋           | 29214/42525 [55:57<22:53,  9.69it/s]

 69%|████████████████████████▋           | 29217/42525 [55:58<23:20,  9.50it/s]

 69%|████████████████████████▋           | 29219/42525 [55:58<25:20,  8.75it/s]

 69%|████████████████████████▋           | 29221/42525 [55:58<24:38,  9.00it/s]

 69%|████████████████████████▋           | 29224/42525 [55:58<23:57,  9.25it/s]

 69%|████████████████████████▋           | 29228/42525 [55:59<22:29,  9.85it/s]

 69%|████████████████████████▋           | 29231/42525 [55:59<22:14,  9.96it/s]

 69%|████████████████████████▋           | 29235/42525 [55:59<21:49, 10.15it/s]

 69%|████████████████████████▊           | 29237/42525 [56:00<21:45, 10.18it/s]

 69%|████████████████████████▊           | 29241/42525 [56:00<22:25,  9.87it/s]

 69%|████████████████████████▊           | 29244/42525 [56:00<22:38,  9.77it/s]

 69%|████████████████████████▊           | 29246/42525 [56:01<22:30,  9.83it/s]

 69%|████████████████████████▊           | 29248/42525 [56:01<27:06,  8.17it/s]

 69%|████████████████████████▊           | 29252/42525 [56:01<23:27,  9.43it/s]

 69%|████████████████████████▊           | 29255/42525 [56:02<22:53,  9.66it/s]

 69%|████████████████████████▊           | 29258/42525 [56:02<23:38,  9.35it/s]

 69%|████████████████████████▊           | 29261/42525 [56:02<22:40,  9.75it/s]

 69%|████████████████████████▊           | 29263/42525 [56:02<25:19,  8.73it/s]

 69%|████████████████████████▊           | 29265/42525 [56:03<27:41,  7.98it/s]

 69%|████████████████████████▊           | 29268/42525 [56:03<25:41,  8.60it/s]

 69%|████████████████████████▊           | 29270/42525 [56:03<26:58,  8.19it/s]

 69%|████████████████████████▊           | 29273/42525 [56:04<25:18,  8.73it/s]

 69%|████████████████████████▊           | 29275/42525 [56:04<26:20,  8.38it/s]

 69%|████████████████████████▊           | 29279/42525 [56:04<23:17,  9.48it/s]

 69%|████████████████████████▊           | 29282/42525 [56:05<23:24,  9.43it/s]

 69%|████████████████████████▊           | 29283/42525 [56:05<24:42,  8.93it/s]

 69%|████████████████████████▊           | 29285/42525 [56:05<25:27,  8.67it/s]

 69%|████████████████████████▊           | 29289/42525 [56:05<24:03,  9.17it/s]

 69%|████████████████████████▊           | 29292/42525 [56:06<23:13,  9.50it/s]

 69%|████████████████████████▊           | 29294/42525 [56:06<25:44,  8.56it/s]

 69%|████████████████████████▊           | 29297/42525 [56:06<25:55,  8.50it/s]

 69%|████████████████████████▊           | 29299/42525 [56:06<24:15,  9.09it/s]

 69%|████████████████████████▊           | 29302/42525 [56:07<25:33,  8.62it/s]

 69%|████████████████████████▊           | 29304/42525 [56:07<25:39,  8.59it/s]

 69%|████████████████████████▊           | 29306/42525 [56:07<29:01,  7.59it/s]

 69%|████████████████████████▊           | 29307/42525 [56:08<30:00,  7.34it/s]

 69%|████████████████████████▊           | 29311/42525 [56:08<24:58,  8.82it/s]

 69%|████████████████████████▊           | 29312/42525 [56:08<26:39,  8.26it/s]

 69%|████████████████████████▊           | 29316/42525 [56:09<24:53,  8.85it/s]

 69%|████████████████████████▊           | 29318/42525 [56:09<23:38,  9.31it/s]

 69%|████████████████████████▊           | 29322/42525 [56:09<23:16,  9.45it/s]

 69%|████████████████████████▊           | 29324/42525 [56:09<22:38,  9.72it/s]

 69%|████████████████████████▊           | 29328/42525 [56:10<23:03,  9.54it/s]

 69%|████████████████████████▊           | 29330/42525 [56:10<25:02,  8.78it/s]

 69%|████████████████████████▊           | 29332/42525 [56:10<26:22,  8.33it/s]

 69%|████████████████████████▊           | 29336/42525 [56:11<23:11,  9.48it/s]

 69%|████████████████████████▊           | 29339/42525 [56:11<24:36,  8.93it/s]

 69%|████████████████████████▊           | 29341/42525 [56:11<24:18,  9.04it/s]

 69%|████████████████████████▊           | 29342/42525 [56:11<25:04,  8.76it/s]

 69%|████████████████████████▊           | 29345/42525 [56:12<25:00,  8.78it/s]

 69%|████████████████████████▊           | 29348/42525 [56:12<23:11,  9.47it/s]

 69%|████████████████████████▊           | 29350/42525 [56:12<24:42,  8.88it/s]

 69%|████████████████████████▊           | 29354/42525 [56:13<24:07,  9.10it/s]

 69%|████████████████████████▊           | 29358/42525 [56:13<23:09,  9.48it/s]

 69%|████████████████████████▊           | 29362/42525 [56:13<22:22,  9.81it/s]

 69%|████████████████████████▊           | 29364/42525 [56:14<21:57,  9.99it/s]

 69%|████████████████████████▊           | 29367/42525 [56:14<24:13,  9.05it/s]

 69%|████████████████████████▊           | 29370/42525 [56:14<23:15,  9.43it/s]

 69%|████████████████████████▊           | 29374/42525 [56:15<22:27,  9.76it/s]

 69%|████████████████████████▊           | 29377/42525 [56:15<22:55,  9.56it/s]

 69%|████████████████████████▊           | 29379/42525 [56:15<22:59,  9.53it/s]

 69%|████████████████████████▊           | 29381/42525 [56:16<26:01,  8.42it/s]

 69%|████████████████████████▊           | 29383/42525 [56:16<24:08,  9.07it/s]

 69%|████████████████████████▉           | 29386/42525 [56:16<25:28,  8.60it/s]

 69%|████████████████████████▉           | 29390/42525 [56:17<23:26,  9.34it/s]

 69%|████████████████████████▉           | 29393/42525 [56:17<25:15,  8.66it/s]

 69%|████████████████████████▉           | 29396/42525 [56:17<23:24,  9.35it/s]

 69%|████████████████████████▉           | 29399/42525 [56:17<22:42,  9.63it/s]

 69%|████████████████████████▉           | 29401/42525 [56:18<24:58,  8.76it/s]

 69%|████████████████████████▉           | 29403/42525 [56:18<23:27,  9.33it/s]

 69%|████████████████████████▉           | 29407/42525 [56:18<22:27,  9.74it/s]

 69%|████████████████████████▉           | 29411/42525 [56:19<23:02,  9.49it/s]

 69%|████████████████████████▉           | 29413/42525 [56:19<26:28,  8.25it/s]

 69%|████████████████████████▉           | 29414/42525 [56:19<27:03,  8.08it/s]

 69%|████████████████████████▉           | 29417/42525 [56:20<27:03,  8.08it/s]

 69%|████████████████████████▉           | 29421/42525 [56:20<23:59,  9.10it/s]

 69%|████████████████████████▉           | 29423/42525 [56:20<24:34,  8.88it/s]

 69%|████████████████████████▉           | 29425/42525 [56:20<25:20,  8.61it/s]

 69%|████████████████████████▉           | 29427/42525 [56:21<25:56,  8.42it/s]

 69%|████████████████████████▉           | 29430/42525 [56:21<23:28,  9.30it/s]

 69%|████████████████████████▉           | 29434/42525 [56:21<22:24,  9.74it/s]

 69%|████████████████████████▉           | 29437/42525 [56:22<24:02,  9.07it/s]

 69%|████████████████████████▉           | 29440/42525 [56:22<24:14,  8.99it/s]

 69%|████████████████████████▉           | 29442/42525 [56:22<23:00,  9.48it/s]

 69%|████████████████████████▉           | 29444/42525 [56:22<22:56,  9.51it/s]

 69%|████████████████████████▉           | 29447/42525 [56:23<25:49,  8.44it/s]

 69%|████████████████████████▉           | 29449/42525 [56:23<26:48,  8.13it/s]

 69%|████████████████████████▉           | 29451/42525 [56:23<27:26,  7.94it/s]

 69%|████████████████████████▉           | 29453/42525 [56:24<26:35,  8.19it/s]

 69%|████████████████████████▉           | 29456/42525 [56:24<26:58,  8.07it/s]

 69%|████████████████████████▉           | 29459/42525 [56:24<26:25,  8.24it/s]

 69%|████████████████████████▉           | 29461/42525 [56:25<27:03,  8.05it/s]

 69%|████████████████████████▉           | 29465/42525 [56:25<24:43,  8.80it/s]

 69%|████████████████████████▉           | 29466/42525 [56:25<25:29,  8.54it/s]

 69%|████████████████████████▉           | 29469/42525 [56:25<24:41,  8.81it/s]

 69%|████████████████████████▉           | 29471/42525 [56:26<26:24,  8.24it/s]

 69%|████████████████████████▉           | 29472/42525 [56:26<25:24,  8.56it/s]

 69%|████████████████████████▉           | 29475/42525 [56:26<26:08,  8.32it/s]

 69%|████████████████████████▉           | 29479/42525 [56:27<22:58,  9.47it/s]

 69%|████████████████████████▉           | 29481/42525 [56:27<24:03,  9.03it/s]

 69%|████████████████████████▉           | 29484/42525 [56:27<23:17,  9.33it/s]

 69%|████████████████████████▉           | 29487/42525 [56:28<23:43,  9.16it/s]

 69%|████████████████████████▉           | 29489/42525 [56:28<27:19,  7.95it/s]

 69%|████████████████████████▉           | 29492/42525 [56:28<24:46,  8.77it/s]

 69%|████████████████████████▉           | 29494/42525 [56:28<25:55,  8.38it/s]

 69%|████████████████████████▉           | 29498/42525 [56:29<23:46,  9.13it/s]

 69%|████████████████████████▉           | 29501/42525 [56:29<23:49,  9.11it/s]

 69%|████████████████████████▉           | 29504/42525 [56:29<23:11,  9.36it/s]

 69%|████████████████████████▉           | 29508/42525 [56:30<21:59,  9.86it/s]

 69%|████████████████████████▉           | 29510/42525 [56:30<22:18,  9.72it/s]

 69%|████████████████████████▉           | 29513/42525 [56:30<22:07,  9.80it/s]

 69%|████████████████████████▉           | 29516/42525 [56:31<23:02,  9.41it/s]

 69%|████████████████████████▉           | 29518/42525 [56:31<24:35,  8.82it/s]

 69%|████████████████████████▉           | 29522/42525 [56:31<22:23,  9.68it/s]

 69%|████████████████████████▉           | 29526/42525 [56:32<21:32, 10.06it/s]

 69%|████████████████████████▉           | 29528/42525 [56:32<21:29, 10.08it/s]

 69%|█████████████████████████           | 29532/42525 [56:32<21:20, 10.15it/s]

 69%|█████████████████████████           | 29536/42525 [56:33<22:31,  9.61it/s]

 69%|█████████████████████████           | 29538/42525 [56:33<25:51,  8.37it/s]

 69%|█████████████████████████           | 29540/42525 [56:33<24:00,  9.01it/s]

 69%|█████████████████████████           | 29543/42525 [56:34<24:40,  8.77it/s]

 69%|█████████████████████████           | 29545/42525 [56:34<23:44,  9.11it/s]

 69%|█████████████████████████           | 29546/42525 [56:34<23:33,  9.18it/s]

 69%|█████████████████████████           | 29549/42525 [56:34<26:30,  8.16it/s]

 69%|█████████████████████████           | 29552/42525 [56:35<23:50,  9.07it/s]

 70%|█████████████████████████           | 29555/42525 [56:35<22:54,  9.43it/s]

 70%|█████████████████████████           | 29558/42525 [56:35<22:10,  9.75it/s]

 70%|█████████████████████████           | 29559/42525 [56:35<24:17,  8.90it/s]

 70%|█████████████████████████           | 29561/42525 [56:36<25:05,  8.61it/s]

 70%|█████████████████████████           | 29564/42525 [56:36<26:07,  8.27it/s]

 70%|█████████████████████████           | 29567/42525 [56:36<24:09,  8.94it/s]

 70%|█████████████████████████           | 29569/42525 [56:37<27:33,  7.84it/s]

 70%|█████████████████████████           | 29571/42525 [56:37<24:42,  8.74it/s]

 70%|█████████████████████████           | 29575/42525 [56:37<23:50,  9.05it/s]

 70%|█████████████████████████           | 29579/42525 [56:38<22:26,  9.62it/s]

 70%|█████████████████████████           | 29581/42525 [56:38<21:59,  9.81it/s]

 70%|█████████████████████████           | 29584/42525 [56:38<24:53,  8.66it/s]

 70%|█████████████████████████           | 29587/42525 [56:39<23:48,  9.06it/s]

 70%|█████████████████████████           | 29591/42525 [56:39<22:38,  9.52it/s]

 70%|█████████████████████████           | 29594/42525 [56:39<22:12,  9.70it/s]

 70%|█████████████████████████           | 29597/42525 [56:40<21:35,  9.98it/s]

 70%|█████████████████████████           | 29600/42525 [56:40<24:41,  8.72it/s]

 70%|█████████████████████████           | 29602/42525 [56:40<25:59,  8.29it/s]

 70%|█████████████████████████           | 29604/42525 [56:40<24:03,  8.95it/s]

 70%|█████████████████████████           | 29607/42525 [56:41<24:40,  8.73it/s]

 70%|█████████████████████████           | 29610/42525 [56:41<24:17,  8.86it/s]

 70%|█████████████████████████           | 29612/42525 [56:41<25:46,  8.35it/s]

 70%|█████████████████████████           | 29614/42525 [56:42<24:54,  8.64it/s]

 70%|█████████████████████████           | 29615/42525 [56:42<24:16,  8.87it/s]

 70%|█████████████████████████           | 29619/42525 [56:42<23:30,  9.15it/s]

 70%|█████████████████████████           | 29621/42525 [56:42<25:25,  8.46it/s]

 70%|█████████████████████████           | 29624/42525 [56:43<24:12,  8.88it/s]

 70%|█████████████████████████           | 29627/42525 [56:43<23:05,  9.31it/s]

 70%|█████████████████████████           | 29628/42525 [56:43<25:00,  8.60it/s]

 70%|█████████████████████████           | 29630/42525 [56:43<23:54,  8.99it/s]

 70%|█████████████████████████           | 29633/42525 [56:44<24:43,  8.69it/s]

 70%|█████████████████████████           | 29636/42525 [56:44<22:57,  9.36it/s]

 70%|█████████████████████████           | 29639/42525 [56:44<23:06,  9.29it/s]

 70%|█████████████████████████           | 29642/42525 [56:45<24:12,  8.87it/s]

 70%|█████████████████████████           | 29644/42525 [56:45<23:12,  9.25it/s]

 70%|█████████████████████████           | 29646/42525 [56:45<22:00,  9.75it/s]

 70%|█████████████████████████           | 29650/42525 [56:45<22:43,  9.44it/s]

 70%|█████████████████████████           | 29653/42525 [56:46<23:11,  9.25it/s]

 70%|█████████████████████████           | 29656/42525 [56:46<23:05,  9.29it/s]

 70%|█████████████████████████           | 29659/42525 [56:46<24:50,  8.63it/s]

 70%|█████████████████████████           | 29661/42525 [56:47<24:58,  8.58it/s]

 70%|█████████████████████████           | 29665/42525 [56:47<22:19,  9.60it/s]

 70%|█████████████████████████           | 29668/42525 [56:47<22:27,  9.54it/s]

 70%|█████████████████████████           | 29669/42525 [56:48<23:31,  9.11it/s]

 70%|█████████████████████████           | 29672/42525 [56:48<24:06,  8.89it/s]

 70%|█████████████████████████           | 29675/42525 [56:48<24:14,  8.83it/s]

 70%|█████████████████████████▏          | 29679/42525 [56:49<22:15,  9.62it/s]

 70%|█████████████████████████▏          | 29681/42525 [56:49<25:17,  8.46it/s]

 70%|█████████████████████████▏          | 29684/42525 [56:49<24:23,  8.78it/s]

 70%|█████████████████████████▏          | 29688/42525 [56:50<22:06,  9.68it/s]

 70%|█████████████████████████▏          | 29691/42525 [56:50<24:41,  8.66it/s]

 70%|█████████████████████████▏          | 29694/42525 [56:50<23:05,  9.26it/s]

 70%|█████████████████████████▏          | 29696/42525 [56:51<24:11,  8.84it/s]

 70%|█████████████████████████▏          | 29698/42525 [56:51<25:01,  8.54it/s]

 70%|█████████████████████████▏          | 29700/42525 [56:51<24:49,  8.61it/s]

 70%|█████████████████████████▏          | 29702/42525 [56:51<23:40,  9.03it/s]

 70%|█████████████████████████▏          | 29706/42525 [56:52<22:41,  9.41it/s]

 70%|█████████████████████████▏          | 29709/42525 [56:52<22:55,  9.32it/s]

 70%|█████████████████████████▏          | 29711/42525 [56:52<23:11,  9.21it/s]

 70%|█████████████████████████▏          | 29715/42525 [56:53<23:00,  9.28it/s]

 70%|█████████████████████████▏          | 29718/42525 [56:53<23:32,  9.07it/s]

 70%|█████████████████████████▏          | 29720/42525 [56:53<22:30,  9.48it/s]

 70%|█████████████████████████▏          | 29723/42525 [56:54<22:45,  9.37it/s]

 70%|█████████████████████████▏          | 29726/42525 [56:54<23:20,  9.14it/s]

 70%|█████████████████████████▏          | 29730/42525 [56:54<21:36,  9.87it/s]

 70%|█████████████████████████▏          | 29734/42525 [56:55<20:51, 10.22it/s]

 70%|█████████████████████████▏          | 29737/42525 [56:55<24:16,  8.78it/s]

 70%|█████████████████████████▏          | 29741/42525 [56:55<23:37,  9.02it/s]

 70%|█████████████████████████▏          | 29743/42525 [56:56<24:20,  8.75it/s]

 70%|█████████████████████████▏          | 29744/42525 [56:56<24:00,  8.88it/s]

 70%|█████████████████████████▏          | 29748/42525 [56:56<22:16,  9.56it/s]

 70%|█████████████████████████▏          | 29751/42525 [56:57<23:20,  9.12it/s]

 70%|█████████████████████████▏          | 29753/42525 [56:57<25:09,  8.46it/s]

 70%|█████████████████████████▏          | 29754/42525 [56:57<24:11,  8.80it/s]

 70%|█████████████████████████▏          | 29757/42525 [56:57<24:40,  8.62it/s]

 70%|█████████████████████████▏          | 29758/42525 [56:57<24:00,  8.86it/s]

 70%|█████████████████████████▏          | 29761/42525 [56:58<25:00,  8.51it/s]

 70%|█████████████████████████▏          | 29764/42525 [56:58<23:49,  8.93it/s]

 70%|█████████████████████████▏          | 29766/42525 [56:58<25:01,  8.50it/s]

 70%|█████████████████████████▏          | 29769/42525 [56:59<22:47,  9.33it/s]

 70%|█████████████████████████▏          | 29773/42525 [56:59<21:26,  9.91it/s]

 70%|█████████████████████████▏          | 29775/42525 [56:59<21:13, 10.01it/s]

 70%|█████████████████████████▏          | 29779/42525 [57:00<22:07,  9.60it/s]

 70%|█████████████████████████▏          | 29781/42525 [57:00<25:40,  8.27it/s]

 70%|█████████████████████████▏          | 29783/42525 [57:00<25:43,  8.25it/s]

 70%|█████████████████████████▏          | 29786/42525 [57:00<22:54,  9.27it/s]

 70%|█████████████████████████▏          | 29790/42525 [57:01<21:31,  9.86it/s]

 70%|█████████████████████████▏          | 29793/42525 [57:01<22:03,  9.62it/s]

 70%|█████████████████████████▏          | 29795/42525 [57:01<25:04,  8.46it/s]

 70%|█████████████████████████▏          | 29798/42525 [57:02<23:02,  9.21it/s]

 70%|█████████████████████████▏          | 29801/42525 [57:02<23:49,  8.90it/s]

 70%|█████████████████████████▏          | 29804/42525 [57:02<22:54,  9.25it/s]

 70%|█████████████████████████▏          | 29807/42525 [57:03<23:53,  8.87it/s]

 70%|█████████████████████████▏          | 29809/42525 [57:03<22:37,  9.37it/s]

 70%|█████████████████████████▏          | 29813/42525 [57:03<21:38,  9.79it/s]

 70%|█████████████████████████▏          | 29815/42525 [57:04<22:38,  9.36it/s]

 70%|█████████████████████████▏          | 29819/42525 [57:04<21:38,  9.78it/s]

 70%|█████████████████████████▏          | 29823/42525 [57:04<20:54, 10.12it/s]

 70%|█████████████████████████▏          | 29825/42525 [57:05<20:52, 10.14it/s]

 70%|█████████████████████████▎          | 29828/42525 [57:05<24:14,  8.73it/s]

 70%|█████████████████████████▎          | 29831/42525 [57:05<22:33,  9.38it/s]

 70%|█████████████████████████▎          | 29833/42525 [57:05<22:32,  9.38it/s]

 70%|█████████████████████████▎          | 29835/42525 [57:06<21:40,  9.76it/s]

 70%|█████████████████████████▎          | 29838/42525 [57:06<22:12,  9.52it/s]

 70%|█████████████████████████▎          | 29842/42525 [57:06<21:31,  9.82it/s]

 70%|█████████████████████████▎          | 29844/42525 [57:07<21:06, 10.01it/s]

 70%|█████████████████████████▎          | 29847/42525 [57:07<21:20,  9.90it/s]

 70%|█████████████████████████▎          | 29850/42525 [57:07<21:43,  9.73it/s]

 70%|█████████████████████████▎          | 29853/42525 [57:07<22:29,  9.39it/s]

 70%|█████████████████████████▎          | 29856/42525 [57:08<24:12,  8.72it/s]

 70%|█████████████████████████▎          | 29857/42525 [57:08<25:45,  8.20it/s]

 70%|█████████████████████████▎          | 29859/42525 [57:08<25:36,  8.25it/s]

 70%|█████████████████████████▎          | 29862/42525 [57:09<24:49,  8.50it/s]

 70%|█████████████████████████▎          | 29865/42525 [57:09<23:05,  9.14it/s]

 70%|█████████████████████████▎          | 29869/42525 [57:09<21:19,  9.89it/s]

 70%|█████████████████████████▎          | 29871/42525 [57:09<20:48, 10.14it/s]

 70%|█████████████████████████▎          | 29873/42525 [57:10<21:04, 10.01it/s]

 70%|█████████████████████████▎          | 29875/42525 [57:10<21:12,  9.94it/s]

 70%|█████████████████████████▎          | 29877/42525 [57:10<22:42,  9.28it/s]

 70%|█████████████████████████▎          | 29881/42525 [57:11<22:26,  9.39it/s]

 70%|█████████████████████████▎          | 29884/42525 [57:11<22:34,  9.33it/s]

 70%|█████████████████████████▎          | 29886/42525 [57:11<24:41,  8.53it/s]

 70%|█████████████████████████▎          | 29889/42525 [57:11<23:47,  8.85it/s]

 70%|█████████████████████████▎          | 29891/42525 [57:12<24:23,  8.64it/s]

 70%|█████████████████████████▎          | 29894/42525 [57:12<22:41,  9.27it/s]

 70%|█████████████████████████▎          | 29896/42525 [57:12<24:49,  8.48it/s]

 70%|█████████████████████████▎          | 29899/42525 [57:13<22:48,  9.23it/s]

 70%|█████████████████████████▎          | 29901/42525 [57:13<24:02,  8.75it/s]

 70%|█████████████████████████▎          | 29904/42525 [57:13<23:19,  9.02it/s]

 70%|█████████████████████████▎          | 29907/42525 [57:13<22:40,  9.27it/s]

 70%|█████████████████████████▎          | 29910/42525 [57:14<21:43,  9.67it/s]

 70%|█████████████████████████▎          | 29912/42525 [57:14<23:07,  9.09it/s]

 70%|█████████████████████████▎          | 29915/42525 [57:14<22:36,  9.30it/s]

 70%|█████████████████████████▎          | 29918/42525 [57:15<23:01,  9.13it/s]

 70%|█████████████████████████▎          | 29921/42525 [57:15<22:38,  9.28it/s]

 70%|█████████████████████████▎          | 29923/42525 [57:15<24:29,  8.58it/s]

 70%|█████████████████████████▎          | 29926/42525 [57:16<22:38,  9.27it/s]

 70%|█████████████████████████▎          | 29930/42525 [57:16<21:30,  9.76it/s]

 70%|█████████████████████████▎          | 29932/42525 [57:16<23:32,  8.92it/s]

 70%|█████████████████████████▎          | 29935/42525 [57:17<22:28,  9.34it/s]

 70%|█████████████████████████▎          | 29938/42525 [57:17<22:06,  9.49it/s]

 70%|█████████████████████████▎          | 29940/42525 [57:17<26:02,  8.06it/s]

 70%|█████████████████████████▎          | 29941/42525 [57:17<26:06,  8.03it/s]

 70%|█████████████████████████▎          | 29944/42525 [57:18<25:03,  8.37it/s]

 70%|█████████████████████████▎          | 29945/42525 [57:18<24:37,  8.52it/s]

 70%|█████████████████████████▎          | 29949/42525 [57:18<23:24,  8.95it/s]

 70%|█████████████████████████▎          | 29951/42525 [57:18<25:37,  8.18it/s]

 70%|█████████████████████████▎          | 29953/42525 [57:19<25:43,  8.14it/s]

 70%|█████████████████████████▎          | 29955/42525 [57:19<25:40,  8.16it/s]

 70%|█████████████████████████▎          | 29958/42525 [57:19<23:44,  8.82it/s]

 70%|█████████████████████████▎          | 29962/42525 [57:20<21:30,  9.73it/s]

 70%|█████████████████████████▎          | 29966/42525 [57:20<20:42, 10.11it/s]

 70%|█████████████████████████▎          | 29969/42525 [57:20<21:37,  9.68it/s]

 70%|█████████████████████████▎          | 29971/42525 [57:21<25:22,  8.25it/s]

 70%|█████████████████████████▎          | 29974/42525 [57:21<22:44,  9.20it/s]

 70%|█████████████████████████▍          | 29976/42525 [57:21<24:45,  8.45it/s]

 70%|█████████████████████████▍          | 29978/42525 [57:21<24:55,  8.39it/s]

 71%|█████████████████████████▍          | 29982/42525 [57:22<21:38,  9.66it/s]

 71%|█████████████████████████▍          | 29984/42525 [57:22<24:20,  8.59it/s]

 71%|█████████████████████████▍          | 29987/42525 [57:22<23:00,  9.08it/s]

 71%|█████████████████████████▍          | 29990/42525 [57:23<23:56,  8.72it/s]

 71%|█████████████████████████▍          | 29993/42525 [57:23<22:10,  9.42it/s]

 71%|█████████████████████████▍          | 29996/42525 [57:23<21:53,  9.54it/s]

 71%|█████████████████████████▍          | 30000/42525 [57:24<20:33, 10.15it/s]

 71%|█████████████████████████▍          | 30004/42525 [57:24<20:37, 10.12it/s]

 71%|█████████████████████████▍          | 30006/42525 [57:24<20:32, 10.16it/s]

 71%|█████████████████████████▍          | 30008/42525 [57:25<20:43, 10.06it/s]

 71%|█████████████████████████▍          | 30011/42525 [57:25<23:24,  8.91it/s]

 71%|█████████████████████████▍          | 30013/42525 [57:25<24:51,  8.39it/s]

 71%|█████████████████████████▍          | 30016/42525 [57:25<23:33,  8.85it/s]

 71%|█████████████████████████▍          | 30018/42525 [57:26<24:58,  8.35it/s]

 71%|█████████████████████████▍          | 30021/42525 [57:26<23:09,  9.00it/s]

 71%|█████████████████████████▍          | 30023/42525 [57:26<25:03,  8.32it/s]

 71%|█████████████████████████▍          | 30027/42525 [57:27<22:49,  9.13it/s]

 71%|█████████████████████████▍          | 30031/42525 [57:27<21:34,  9.65it/s]

 71%|█████████████████████████▍          | 30032/42525 [57:27<21:33,  9.66it/s]

 71%|█████████████████████████▍          | 30035/42525 [57:28<24:39,  8.44it/s]

 71%|█████████████████████████▍          | 30039/42525 [57:28<21:56,  9.48it/s]

 71%|█████████████████████████▍          | 30042/42525 [57:28<22:58,  9.06it/s]

 71%|█████████████████████████▍          | 30046/42525 [57:29<21:28,  9.68it/s]

 71%|█████████████████████████▍          | 30049/42525 [57:29<21:11,  9.81it/s]

 71%|█████████████████████████▍          | 30051/42525 [57:29<23:16,  8.93it/s]

 71%|█████████████████████████▍          | 30054/42525 [57:30<22:52,  9.08it/s]

 71%|█████████████████████████▍          | 30057/42525 [57:30<22:48,  9.11it/s]

 71%|█████████████████████████▍          | 30061/42525 [57:30<21:07,  9.83it/s]

 71%|█████████████████████████▍          | 30065/42525 [57:31<21:29,  9.66it/s]

 71%|█████████████████████████▍          | 30068/42525 [57:31<23:21,  8.89it/s]

 71%|█████████████████████████▍          | 30069/42525 [57:31<24:49,  8.36it/s]

 71%|█████████████████████████▍          | 30071/42525 [57:31<23:20,  8.89it/s]

 71%|█████████████████████████▍          | 30075/42525 [57:32<21:57,  9.45it/s]

 71%|█████████████████████████▍          | 30078/42525 [57:32<22:14,  9.32it/s]

 71%|█████████████████████████▍          | 30080/42525 [57:32<21:29,  9.65it/s]

 71%|█████████████████████████▍          | 30083/42525 [57:33<23:04,  8.99it/s]

 71%|█████████████████████████▍          | 30086/42525 [57:33<23:51,  8.69it/s]

 71%|█████████████████████████▍          | 30088/42525 [57:33<22:50,  9.08it/s]

 71%|█████████████████████████▍          | 30091/42525 [57:34<22:53,  9.05it/s]

 71%|█████████████████████████▍          | 30093/42525 [57:34<24:29,  8.46it/s]

 71%|█████████████████████████▍          | 30096/42525 [57:34<24:57,  8.30it/s]

 71%|█████████████████████████▍          | 30099/42525 [57:35<24:50,  8.34it/s]

 71%|█████████████████████████▍          | 30101/42525 [57:35<23:37,  8.76it/s]

 71%|█████████████████████████▍          | 30102/42525 [57:35<25:31,  8.11it/s]

 71%|█████████████████████████▍          | 30105/42525 [57:35<25:41,  8.06it/s]

 71%|█████████████████████████▍          | 30109/42525 [57:36<23:23,  8.85it/s]

 71%|█████████████████████████▍          | 30112/42525 [57:36<22:40,  9.12it/s]

 71%|█████████████████████████▍          | 30116/42525 [57:36<21:06,  9.80it/s]

 71%|█████████████████████████▍          | 30119/42525 [57:37<20:28, 10.10it/s]

 71%|█████████████████████████▌          | 30123/42525 [57:37<20:17, 10.18it/s]

 71%|█████████████████████████▌          | 30127/42525 [57:38<21:02,  9.82it/s]

 71%|█████████████████████████▌          | 30131/42525 [57:38<20:23, 10.13it/s]

 71%|█████████████████████████▌          | 30133/42525 [57:38<20:10, 10.23it/s]

 71%|█████████████████████████▌          | 30136/42525 [57:38<21:56,  9.41it/s]

 71%|█████████████████████████▌          | 30138/42525 [57:39<21:05,  9.79it/s]

 71%|█████████████████████████▌          | 30142/42525 [57:39<20:35, 10.02it/s]

 71%|█████████████████████████▌          | 30144/42525 [57:39<22:32,  9.15it/s]

 71%|█████████████████████████▌          | 30145/42525 [57:39<24:22,  8.46it/s]

 71%|█████████████████████████▌          | 30148/42525 [57:40<24:16,  8.50it/s]

 71%|█████████████████████████▌          | 30152/42525 [57:40<21:33,  9.57it/s]

 71%|█████████████████████████▌          | 30156/42525 [57:41<20:25, 10.10it/s]

 71%|█████████████████████████▌          | 30160/42525 [57:41<20:03, 10.28it/s]

 71%|█████████████████████████▌          | 30163/42525 [57:41<22:28,  9.17it/s]

 71%|█████████████████████████▌          | 30166/42525 [57:42<22:18,  9.23it/s]

 71%|█████████████████████████▌          | 30168/42525 [57:42<22:51,  9.01it/s]

 71%|█████████████████████████▌          | 30172/42525 [57:42<21:18,  9.66it/s]

 71%|█████████████████████████▌          | 30176/42525 [57:43<20:36,  9.99it/s]

 71%|█████████████████████████▌          | 30178/42525 [57:43<20:59,  9.80it/s]

 71%|█████████████████████████▌          | 30179/42525 [57:43<20:56,  9.83it/s]

 71%|█████████████████████████▌          | 30182/42525 [57:43<21:05,  9.75it/s]

 71%|█████████████████████████▌          | 30186/42525 [57:44<20:17, 10.13it/s]

 71%|█████████████████████████▌          | 30189/42525 [57:44<22:27,  9.16it/s]

 71%|█████████████████████████▌          | 30192/42525 [57:44<22:41,  9.06it/s]

 71%|█████████████████████████▌          | 30195/42525 [57:45<22:37,  9.08it/s]

 71%|█████████████████████████▌          | 30197/42525 [57:45<21:33,  9.53it/s]

 71%|█████████████████████████▌          | 30199/42525 [57:45<21:25,  9.59it/s]

 71%|█████████████████████████▌          | 30202/42525 [57:45<23:43,  8.66it/s]

 71%|█████████████████████████▌          | 30206/42525 [57:46<21:33,  9.53it/s]

 71%|█████████████████████████▌          | 30209/42525 [57:46<21:02,  9.76it/s]

 71%|█████████████████████████▌          | 30211/42525 [57:46<22:15,  9.22it/s]

 71%|█████████████████████████▌          | 30213/42525 [57:47<22:37,  9.07it/s]

 71%|█████████████████████████▌          | 30215/42525 [57:47<21:26,  9.57it/s]

 71%|█████████████████████████▌          | 30218/42525 [57:47<22:18,  9.19it/s]

 71%|█████████████████████████▌          | 30221/42525 [57:48<22:26,  9.14it/s]

 71%|█████████████████████████▌          | 30224/42525 [57:48<21:59,  9.33it/s]

 71%|█████████████████████████▌          | 30226/42525 [57:48<24:49,  8.26it/s]

 71%|█████████████████████████▌          | 30228/42525 [57:48<25:29,  8.04it/s]

 71%|█████████████████████████▌          | 30230/42525 [57:49<23:39,  8.66it/s]

 71%|█████████████████████████▌          | 30234/42525 [57:49<21:20,  9.60it/s]

 71%|█████████████████████████▌          | 30235/42525 [57:49<22:13,  9.22it/s]

 71%|█████████████████████████▌          | 30237/42525 [57:49<23:20,  8.78it/s]

 71%|█████████████████████████▌          | 30240/42525 [57:50<24:26,  8.38it/s]

 71%|█████████████████████████▌          | 30243/42525 [57:50<22:26,  9.12it/s]

 71%|█████████████████████████▌          | 30245/42525 [57:50<21:29,  9.53it/s]

 71%|█████████████████████████▌          | 30248/42525 [57:51<24:13,  8.45it/s]

 71%|█████████████████████████▌          | 30252/42525 [57:51<21:46,  9.40it/s]

 71%|█████████████████████████▌          | 30255/42525 [57:51<23:41,  8.63it/s]

 71%|█████████████████████████▌          | 30258/42525 [57:52<24:01,  8.51it/s]

 71%|█████████████████████████▌          | 30260/42525 [57:52<24:16,  8.42it/s]

 71%|█████████████████████████▌          | 30262/42525 [57:52<27:06,  7.54it/s]

 71%|█████████████████████████▌          | 30265/42525 [57:53<23:18,  8.77it/s]

 71%|█████████████████████████▌          | 30268/42525 [57:53<23:45,  8.60it/s]

 71%|█████████████████████████▋          | 30272/42525 [57:53<21:20,  9.57it/s]

 71%|█████████████████████████▋          | 30275/42525 [57:54<20:40,  9.87it/s]

 71%|█████████████████████████▋          | 30279/42525 [57:54<20:17, 10.06it/s]

 71%|█████████████████████████▋          | 30283/42525 [57:54<22:18,  9.15it/s]

 71%|█████████████████████████▋          | 30286/42525 [57:55<21:49,  9.35it/s]

 71%|█████████████████████████▋          | 30289/42525 [57:55<21:37,  9.43it/s]

 71%|█████████████████████████▋          | 30291/42525 [57:55<22:02,  9.25it/s]

 71%|█████████████████████████▋          | 30292/42525 [57:55<22:24,  9.10it/s]

 71%|█████████████████████████▋          | 30296/42525 [57:56<20:59,  9.71it/s]

 71%|█████████████████████████▋          | 30299/42525 [57:56<21:38,  9.42it/s]

 71%|█████████████████████████▋          | 30302/42525 [57:57<23:50,  8.55it/s]

 71%|█████████████████████████▋          | 30304/42525 [57:57<22:49,  8.92it/s]

 71%|█████████████████████████▋          | 30307/42525 [57:57<21:46,  9.35it/s]

 71%|█████████████████████████▋          | 30310/42525 [57:57<21:26,  9.50it/s]

 71%|█████████████████████████▋          | 30314/42525 [57:58<20:52,  9.75it/s]

 71%|█████████████████████████▋          | 30316/42525 [57:58<24:25,  8.33it/s]

 71%|█████████████████████████▋          | 30319/42525 [57:58<22:30,  9.04it/s]

 71%|█████████████████████████▋          | 30321/42525 [57:59<25:13,  8.06it/s]

 71%|█████████████████████████▋          | 30324/42525 [57:59<23:28,  8.67it/s]

 71%|█████████████████████████▋          | 30326/42525 [57:59<24:27,  8.31it/s]

 71%|█████████████████████████▋          | 30329/42525 [58:00<22:50,  8.90it/s]

 71%|█████████████████████████▋          | 30332/42525 [58:00<21:17,  9.55it/s]

 71%|█████████████████████████▋          | 30335/42525 [58:00<20:52,  9.74it/s]

 71%|█████████████████████████▋          | 30337/42525 [58:00<20:22,  9.97it/s]

 71%|█████████████████████████▋          | 30340/42525 [58:01<20:46,  9.77it/s]

 71%|█████████████████████████▋          | 30343/42525 [58:01<22:22,  9.08it/s]

 71%|█████████████████████████▋          | 30345/42525 [58:01<23:56,  8.48it/s]

 71%|█████████████████████████▋          | 30348/42525 [58:02<21:58,  9.24it/s]

 71%|█████████████████████████▋          | 30351/42525 [58:02<22:45,  8.91it/s]

 71%|█████████████████████████▋          | 30353/42525 [58:02<22:27,  9.03it/s]

 71%|█████████████████████████▋          | 30355/42525 [58:02<22:16,  9.10it/s]

 71%|█████████████████████████▋          | 30357/42525 [58:03<24:37,  8.24it/s]

 71%|█████████████████████████▋          | 30359/42525 [58:03<24:24,  8.31it/s]

 71%|█████████████████████████▋          | 30361/42525 [58:03<22:24,  9.05it/s]

 71%|█████████████████████████▋          | 30364/42525 [58:03<20:56,  9.68it/s]

 71%|█████████████████████████▋          | 30366/42525 [58:04<22:01,  9.20it/s]

 71%|█████████████████████████▋          | 30369/42525 [58:04<22:04,  9.18it/s]

 71%|█████████████████████████▋          | 30371/42525 [58:04<23:57,  8.45it/s]

 71%|█████████████████████████▋          | 30373/42525 [58:04<24:08,  8.39it/s]

 71%|█████████████████████████▋          | 30377/42525 [58:05<21:21,  9.48it/s]

 71%|█████████████████████████▋          | 30381/42525 [58:05<20:18,  9.97it/s]

 71%|█████████████████████████▋          | 30383/42525 [58:05<21:47,  9.29it/s]

 71%|█████████████████████████▋          | 30387/42525 [58:06<21:28,  9.42it/s]

 71%|█████████████████████████▋          | 30390/42525 [58:06<22:37,  8.94it/s]

 71%|█████████████████████████▋          | 30392/42525 [58:06<22:59,  8.79it/s]

 71%|█████████████████████████▋          | 30395/42525 [58:07<21:39,  9.33it/s]

 71%|█████████████████████████▋          | 30396/42525 [58:07<22:50,  8.85it/s]

 71%|█████████████████████████▋          | 30399/42525 [58:07<24:57,  8.10it/s]

 71%|█████████████████████████▋          | 30401/42525 [58:07<23:38,  8.55it/s]

 71%|█████████████████████████▋          | 30403/42525 [58:08<24:30,  8.24it/s]

 71%|█████████████████████████▋          | 30405/42525 [58:08<22:18,  9.05it/s]

 72%|█████████████████████████▋          | 30408/42525 [58:08<23:01,  8.77it/s]

 72%|█████████████████████████▋          | 30410/42525 [58:08<21:38,  9.33it/s]

 72%|█████████████████████████▋          | 30413/42525 [58:09<22:33,  8.95it/s]

 72%|█████████████████████████▋          | 30416/42525 [58:09<22:47,  8.85it/s]

 72%|█████████████████████████▊          | 30419/42525 [58:10<23:51,  8.46it/s]

 72%|█████████████████████████▊          | 30422/42525 [58:10<22:35,  8.93it/s]

 72%|█████████████████████████▊          | 30425/42525 [58:10<22:16,  9.05it/s]

 72%|█████████████████████████▊          | 30427/42525 [58:10<21:13,  9.50it/s]

 72%|█████████████████████████▊          | 30430/42525 [58:11<21:21,  9.44it/s]

 72%|█████████████████████████▊          | 30433/42525 [58:11<21:35,  9.34it/s]

 72%|█████████████████████████▊          | 30435/42525 [58:11<25:08,  8.02it/s]

 72%|█████████████████████████▊          | 30437/42525 [58:12<24:40,  8.16it/s]

 72%|█████████████████████████▊          | 30440/42525 [58:12<22:48,  8.83it/s]

 72%|█████████████████████████▊          | 30444/42525 [58:12<20:45,  9.70it/s]

 72%|█████████████████████████▊          | 30446/42525 [58:13<24:21,  8.27it/s]

 72%|█████████████████████████▊          | 30449/42525 [58:13<21:48,  9.23it/s]

 72%|█████████████████████████▊          | 30451/42525 [58:13<24:45,  8.13it/s]

 72%|█████████████████████████▊          | 30453/42525 [58:13<25:15,  7.96it/s]

 72%|█████████████████████████▊          | 30456/42525 [58:14<22:09,  9.08it/s]

 72%|█████████████████████████▊          | 30457/42525 [58:14<22:00,  9.14it/s]

 72%|█████████████████████████▊          | 30461/42525 [58:14<20:38,  9.74it/s]

 72%|█████████████████████████▊          | 30464/42525 [58:15<20:50,  9.65it/s]

 72%|█████████████████████████▊          | 30466/42525 [58:15<24:07,  8.33it/s]

 72%|█████████████████████████▊          | 30469/42525 [58:15<21:36,  9.30it/s]

 72%|█████████████████████████▊          | 30473/42525 [58:15<20:09,  9.96it/s]

 72%|█████████████████████████▊          | 30476/42525 [58:16<21:44,  9.24it/s]

 72%|█████████████████████████▊          | 30478/42525 [58:16<20:50,  9.64it/s]

 72%|█████████████████████████▊          | 30480/42525 [58:16<22:08,  9.06it/s]

 72%|█████████████████████████▊          | 30483/42525 [58:17<21:44,  9.23it/s]

 72%|█████████████████████████▊          | 30486/42525 [58:17<21:53,  9.16it/s]

 72%|█████████████████████████▊          | 30488/42525 [58:17<23:32,  8.52it/s]

 72%|█████████████████████████▊          | 30491/42525 [58:17<21:24,  9.37it/s]

 72%|█████████████████████████▊          | 30494/42525 [58:18<21:18,  9.41it/s]

 72%|█████████████████████████▊          | 30497/42525 [58:18<20:27,  9.80it/s]

 72%|█████████████████████████▊          | 30500/42525 [58:18<20:38,  9.71it/s]

 72%|█████████████████████████▊          | 30503/42525 [58:19<22:18,  8.98it/s]

 72%|█████████████████████████▊          | 30506/42525 [58:19<23:02,  8.69it/s]

 72%|█████████████████████████▊          | 30508/42525 [58:19<22:12,  9.02it/s]

 72%|█████████████████████████▊          | 30509/42525 [58:19<21:44,  9.21it/s]

 72%|█████████████████████████▊          | 30512/42525 [58:20<23:02,  8.69it/s]

 72%|█████████████████████████▊          | 30514/42525 [58:20<24:22,  8.21it/s]

 72%|█████████████████████████▊          | 30518/42525 [58:20<21:20,  9.38it/s]

 72%|█████████████████████████▊          | 30520/42525 [58:21<20:47,  9.62it/s]

 72%|█████████████████████████▊          | 30523/42525 [58:21<21:58,  9.10it/s]

 72%|█████████████████████████▊          | 30525/42525 [58:21<21:47,  9.18it/s]

 72%|█████████████████████████▊          | 30528/42525 [58:22<22:06,  9.04it/s]

 72%|█████████████████████████▊          | 30530/42525 [58:22<21:26,  9.33it/s]

 72%|█████████████████████████▊          | 30533/42525 [58:22<22:45,  8.78it/s]

 72%|█████████████████████████▊          | 30535/42525 [58:22<22:09,  9.02it/s]

 72%|█████████████████████████▊          | 30537/42525 [58:23<23:21,  8.55it/s]

 72%|█████████████████████████▊          | 30538/42525 [58:23<25:06,  7.96it/s]

 72%|█████████████████████████▊          | 30540/42525 [58:23<23:23,  8.54it/s]

 72%|█████████████████████████▊          | 30542/42525 [58:23<23:55,  8.35it/s]

 72%|█████████████████████████▊          | 30546/42525 [58:24<21:36,  9.24it/s]

 72%|█████████████████████████▊          | 30549/42525 [58:24<20:52,  9.56it/s]

 72%|█████████████████████████▊          | 30551/42525 [58:24<23:51,  8.37it/s]

 72%|█████████████████████████▊          | 30553/42525 [58:24<23:21,  8.54it/s]

 72%|█████████████████████████▊          | 30556/42525 [58:25<22:47,  8.76it/s]

 72%|█████████████████████████▊          | 30559/42525 [58:25<23:36,  8.45it/s]

 72%|█████████████████████████▊          | 30562/42525 [58:25<21:44,  9.17it/s]

 72%|█████████████████████████▉          | 30565/42525 [58:26<20:44,  9.61it/s]

 72%|█████████████████████████▉          | 30567/42525 [58:26<20:04,  9.93it/s]

 72%|█████████████████████████▉          | 30570/42525 [58:26<22:45,  8.75it/s]

 72%|█████████████████████████▉          | 30573/42525 [58:27<21:40,  9.19it/s]

 72%|█████████████████████████▉          | 30576/42525 [58:27<21:15,  9.37it/s]

 72%|█████████████████████████▉          | 30579/42525 [58:27<21:20,  9.33it/s]

 72%|█████████████████████████▉          | 30582/42525 [58:27<20:19,  9.79it/s]

 72%|█████████████████████████▉          | 30584/42525 [58:28<22:23,  8.89it/s]

 72%|█████████████████████████▉          | 30587/42525 [58:28<24:45,  8.03it/s]

 72%|█████████████████████████▉          | 30588/42525 [58:28<23:35,  8.43it/s]

 72%|█████████████████████████▉          | 30592/42525 [58:29<21:05,  9.43it/s]

 72%|█████████████████████████▉          | 30595/42525 [58:29<20:29,  9.70it/s]

 72%|█████████████████████████▉          | 30598/42525 [58:29<22:30,  8.83it/s]

 72%|█████████████████████████▉          | 30599/42525 [58:29<22:08,  8.97it/s]

 72%|█████████████████████████▉          | 30602/42525 [58:30<21:33,  9.22it/s]

 72%|█████████████████████████▉          | 30604/42525 [58:30<24:17,  8.18it/s]

 72%|█████████████████████████▉          | 30607/42525 [58:30<23:40,  8.39it/s]

 72%|█████████████████████████▉          | 30610/42525 [58:31<24:26,  8.12it/s]

 72%|█████████████████████████▉          | 30613/42525 [58:31<21:45,  9.13it/s]

 72%|█████████████████████████▉          | 30616/42525 [58:31<20:31,  9.67it/s]

 72%|█████████████████████████▉          | 30619/42525 [58:32<20:56,  9.48it/s]

 72%|█████████████████████████▉          | 30623/42525 [58:32<19:53,  9.97it/s]

 72%|█████████████████████████▉          | 30626/42525 [58:32<21:30,  9.22it/s]

 72%|█████████████████████████▉          | 30629/42525 [58:33<20:25,  9.71it/s]

 72%|█████████████████████████▉          | 30631/42525 [58:33<20:46,  9.54it/s]

 72%|█████████████████████████▉          | 30635/42525 [58:33<19:33, 10.13it/s]

 72%|█████████████████████████▉          | 30639/42525 [58:34<19:25, 10.19it/s]

 72%|█████████████████████████▉          | 30642/42525 [58:34<20:27,  9.68it/s]

 72%|█████████████████████████▉          | 30644/42525 [58:34<20:09,  9.82it/s]

 72%|█████████████████████████▉          | 30648/42525 [58:35<20:52,  9.48it/s]

 72%|█████████████████████████▉          | 30650/42525 [58:35<21:11,  9.34it/s]

 72%|█████████████████████████▉          | 30653/42525 [58:35<20:49,  9.50it/s]

 72%|█████████████████████████▉          | 30655/42525 [58:35<23:04,  8.57it/s]

 72%|█████████████████████████▉          | 30656/42525 [58:36<24:31,  8.07it/s]

 72%|█████████████████████████▉          | 30659/42525 [58:36<23:20,  8.47it/s]

 72%|█████████████████████████▉          | 30662/42525 [58:36<23:47,  8.31it/s]

 72%|█████████████████████████▉          | 30664/42525 [58:36<24:33,  8.05it/s]

 72%|█████████████████████████▉          | 30667/42525 [58:37<21:27,  9.21it/s]

 72%|█████████████████████████▉          | 30670/42525 [58:37<20:27,  9.66it/s]

 72%|█████████████████████████▉          | 30673/42525 [58:37<21:03,  9.38it/s]

 72%|█████████████████████████▉          | 30675/42525 [58:38<23:31,  8.39it/s]

 72%|█████████████████████████▉          | 30678/42525 [58:38<21:47,  9.06it/s]

 72%|█████████████████████████▉          | 30680/42525 [58:38<22:11,  8.89it/s]

 72%|█████████████████████████▉          | 30683/42525 [58:39<20:32,  9.61it/s]

 72%|█████████████████████████▉          | 30685/42525 [58:39<24:18,  8.12it/s]

 72%|█████████████████████████▉          | 30688/42525 [58:39<23:37,  8.35it/s]

 72%|█████████████████████████▉          | 30690/42525 [58:39<22:11,  8.89it/s]

 72%|█████████████████████████▉          | 30694/42525 [58:40<20:16,  9.72it/s]

 72%|█████████████████████████▉          | 30695/42525 [58:40<22:10,  8.89it/s]

 72%|█████████████████████████▉          | 30699/42525 [58:40<20:37,  9.55it/s]

 72%|█████████████████████████▉          | 30703/42525 [58:41<19:57,  9.87it/s]

 72%|█████████████████████████▉          | 30705/42525 [58:41<21:04,  9.35it/s]

 72%|█████████████████████████▉          | 30706/42525 [58:41<20:56,  9.41it/s]

 72%|█████████████████████████▉          | 30709/42525 [58:41<22:05,  8.92it/s]

 72%|██████████████████████████          | 30713/42525 [58:42<21:30,  9.15it/s]

 72%|██████████████████████████          | 30714/42525 [58:42<23:06,  8.52it/s]

 72%|██████████████████████████          | 30716/42525 [58:42<22:20,  8.81it/s]

 72%|██████████████████████████          | 30719/42525 [58:43<24:14,  8.12it/s]

 72%|██████████████████████████          | 30721/42525 [58:43<24:43,  7.95it/s]

 72%|██████████████████████████          | 30724/42525 [58:43<21:55,  8.97it/s]

 72%|██████████████████████████          | 30727/42525 [58:43<20:33,  9.57it/s]

 72%|██████████████████████████          | 30730/42525 [58:44<19:46,  9.94it/s]

 72%|██████████████████████████          | 30734/42525 [58:44<19:14, 10.21it/s]

 72%|██████████████████████████          | 30738/42525 [58:45<19:14, 10.21it/s]

 72%|██████████████████████████          | 30741/42525 [58:45<23:27,  8.37it/s]

 72%|██████████████████████████          | 30744/42525 [58:45<21:44,  9.03it/s]

 72%|██████████████████████████          | 30746/42525 [58:46<23:56,  8.20it/s]

 72%|██████████████████████████          | 30748/42525 [58:46<23:19,  8.42it/s]

 72%|██████████████████████████          | 30751/42525 [58:46<21:55,  8.95it/s]

 72%|██████████████████████████          | 30753/42525 [58:46<23:23,  8.39it/s]

 72%|██████████████████████████          | 30756/42525 [58:47<24:01,  8.16it/s]

 72%|██████████████████████████          | 30758/42525 [58:47<23:45,  8.25it/s]

 72%|██████████████████████████          | 30759/42525 [58:47<25:11,  7.78it/s]

 72%|██████████████████████████          | 30761/42525 [58:47<23:11,  8.46it/s]

 72%|██████████████████████████          | 30765/42525 [58:48<21:24,  9.16it/s]

 72%|██████████████████████████          | 30768/42525 [58:48<21:01,  9.32it/s]

 72%|██████████████████████████          | 30770/42525 [58:48<23:19,  8.40it/s]

 72%|██████████████████████████          | 30772/42525 [58:49<23:12,  8.44it/s]

 72%|██████████████████████████          | 30774/42525 [58:49<23:43,  8.25it/s]

 72%|██████████████████████████          | 30776/42525 [58:49<21:39,  9.04it/s]

 72%|██████████████████████████          | 30779/42525 [58:49<21:55,  8.93it/s]

 72%|██████████████████████████          | 30781/42525 [58:50<20:47,  9.41it/s]

 72%|██████████████████████████          | 30784/42525 [58:50<22:07,  8.85it/s]

 72%|██████████████████████████          | 30786/42525 [58:50<21:37,  9.04it/s]

 72%|██████████████████████████          | 30790/42525 [58:51<20:10,  9.69it/s]

 72%|██████████████████████████          | 30794/42525 [58:51<19:21, 10.10it/s]

 72%|██████████████████████████          | 30798/42525 [58:51<20:57,  9.33it/s]

 72%|██████████████████████████          | 30799/42525 [58:52<22:24,  8.72it/s]

 72%|██████████████████████████          | 30802/42525 [58:52<22:24,  8.72it/s]

 72%|██████████████████████████          | 30804/42525 [58:52<24:54,  7.85it/s]

 72%|██████████████████████████          | 30808/42525 [58:53<20:57,  9.31it/s]

 72%|██████████████████████████          | 30812/42525 [58:53<19:46,  9.87it/s]

 72%|██████████████████████████          | 30814/42525 [58:53<19:23, 10.06it/s]

 72%|██████████████████████████          | 30816/42525 [58:53<20:12,  9.66it/s]

 72%|██████████████████████████          | 30818/42525 [58:54<21:18,  9.15it/s]

 72%|██████████████████████████          | 30821/42525 [58:54<23:13,  8.40it/s]

 72%|██████████████████████████          | 30823/42525 [58:54<22:36,  8.63it/s]

 72%|██████████████████████████          | 30825/42525 [58:54<21:21,  9.13it/s]

 72%|██████████████████████████          | 30827/42525 [58:55<20:54,  9.33it/s]

 72%|██████████████████████████          | 30830/42525 [58:55<22:01,  8.85it/s]

 73%|██████████████████████████          | 30834/42525 [58:55<20:08,  9.68it/s]

 73%|██████████████████████████          | 30838/42525 [58:56<19:32,  9.97it/s]

 73%|██████████████████████████          | 30840/42525 [58:56<19:17, 10.10it/s]

 73%|██████████████████████████          | 30843/42525 [58:56<23:05,  8.43it/s]

 73%|██████████████████████████          | 30846/42525 [58:57<21:26,  9.08it/s]

 73%|██████████████████████████          | 30848/42525 [58:57<20:23,  9.54it/s]

 73%|██████████████████████████          | 30850/42525 [58:57<21:28,  9.06it/s]

 73%|██████████████████████████          | 30852/42525 [58:57<21:04,  9.23it/s]

 73%|██████████████████████████          | 30854/42525 [58:58<20:47,  9.36it/s]

 73%|██████████████████████████          | 30856/42525 [58:58<20:40,  9.41it/s]

 73%|██████████████████████████          | 30860/42525 [58:58<19:36,  9.92it/s]

 73%|██████████████████████████▏         | 30864/42525 [58:59<20:07,  9.66it/s]

 73%|██████████████████████████▏         | 30867/42525 [58:59<20:42,  9.38it/s]

 73%|██████████████████████████▏         | 30870/42525 [58:59<21:36,  8.99it/s]

 73%|██████████████████████████▏         | 30874/42525 [59:00<19:52,  9.77it/s]

 73%|██████████████████████████▏         | 30876/42525 [59:00<23:15,  8.35it/s]

 73%|██████████████████████████▏         | 30879/42525 [59:00<21:24,  9.06it/s]

 73%|██████████████████████████▏         | 30883/42525 [59:01<19:46,  9.81it/s]

 73%|██████████████████████████▏         | 30886/42525 [59:01<19:26,  9.98it/s]

 73%|██████████████████████████▏         | 30889/42525 [59:01<19:00, 10.20it/s]

 73%|██████████████████████████▏         | 30893/42525 [59:02<19:56,  9.72it/s]

 73%|██████████████████████████▏         | 30895/42525 [59:02<19:53,  9.74it/s]

 73%|██████████████████████████▏         | 30898/42525 [59:02<19:27,  9.96it/s]

 73%|██████████████████████████▏         | 30902/42525 [59:03<18:58, 10.21it/s]

 73%|██████████████████████████▏         | 30904/42525 [59:03<18:50, 10.28it/s]

 73%|██████████████████████████▏         | 30908/42525 [59:03<19:36,  9.88it/s]

 73%|██████████████████████████▏         | 30912/42525 [59:04<19:12, 10.08it/s]

 73%|██████████████████████████▏         | 30914/42525 [59:04<18:59, 10.19it/s]

 73%|██████████████████████████▏         | 30916/42525 [59:04<19:30,  9.92it/s]

 73%|██████████████████████████▏         | 30918/42525 [59:04<20:49,  9.29it/s]

 73%|██████████████████████████▏         | 30921/42525 [59:05<22:54,  8.44it/s]

 73%|██████████████████████████▏         | 30924/42525 [59:05<23:25,  8.25it/s]

 73%|██████████████████████████▏         | 30927/42525 [59:05<23:27,  8.24it/s]

 73%|██████████████████████████▏         | 30929/42525 [59:06<21:56,  8.81it/s]

 73%|██████████████████████████▏         | 30931/42525 [59:06<23:31,  8.21it/s]

 73%|██████████████████████████▏         | 30934/42525 [59:06<21:55,  8.81it/s]

 73%|██████████████████████████▏         | 30937/42525 [59:06<20:33,  9.39it/s]

 73%|██████████████████████████▏         | 30940/42525 [59:07<20:03,  9.62it/s]

 73%|██████████████████████████▏         | 30941/42525 [59:07<22:02,  8.76it/s]

 73%|██████████████████████████▏         | 30944/42525 [59:07<21:10,  9.12it/s]

 73%|██████████████████████████▏         | 30947/42525 [59:07<20:18,  9.50it/s]

 73%|██████████████████████████▏         | 30950/42525 [59:08<21:25,  9.00it/s]

 73%|██████████████████████████▏         | 30954/42525 [59:08<19:50,  9.72it/s]

 73%|██████████████████████████▏         | 30955/42525 [59:08<20:58,  9.20it/s]

 73%|██████████████████████████▏         | 30957/42525 [59:09<20:41,  9.31it/s]

 73%|██████████████████████████▏         | 30961/42525 [59:09<20:44,  9.29it/s]

 73%|██████████████████████████▏         | 30964/42525 [59:09<20:32,  9.38it/s]

 73%|██████████████████████████▏         | 30966/42525 [59:10<21:38,  8.90it/s]

 73%|██████████████████████████▏         | 30969/42525 [59:10<22:08,  8.70it/s]

 73%|██████████████████████████▏         | 30973/42525 [59:10<20:11,  9.53it/s]

 73%|██████████████████████████▏         | 30977/42525 [59:11<20:23,  9.44it/s]

 73%|██████████████████████████▏         | 30980/42525 [59:11<21:03,  9.14it/s]

 73%|██████████████████████████▏         | 30983/42525 [59:11<21:48,  8.82it/s]

 73%|██████████████████████████▏         | 30985/42525 [59:12<23:15,  8.27it/s]

 73%|██████████████████████████▏         | 30987/42525 [59:12<21:25,  8.98it/s]

 73%|██████████████████████████▏         | 30989/42525 [59:12<22:11,  8.66it/s]

 73%|██████████████████████████▏         | 30992/42525 [59:12<22:39,  8.48it/s]

 73%|██████████████████████████▏         | 30994/42525 [59:13<22:53,  8.40it/s]

 73%|██████████████████████████▏         | 30996/42525 [59:13<25:05,  7.66it/s]

 73%|██████████████████████████▏         | 31000/42525 [59:13<21:45,  8.83it/s]

 73%|██████████████████████████▏         | 31003/42525 [59:14<20:39,  9.29it/s]

 73%|██████████████████████████▏         | 31006/42525 [59:14<20:17,  9.46it/s]

 73%|██████████████████████████▎         | 31009/42525 [59:14<20:57,  9.16it/s]

 73%|██████████████████████████▎         | 31010/42525 [59:15<22:34,  8.50it/s]

 73%|██████████████████████████▎         | 31013/42525 [59:15<21:31,  8.91it/s]

 73%|██████████████████████████▎         | 31015/42525 [59:15<20:20,  9.43it/s]

 73%|██████████████████████████▎         | 31018/42525 [59:15<22:54,  8.37it/s]

 73%|██████████████████████████▎         | 31021/42525 [59:16<21:31,  8.91it/s]

 73%|██████████████████████████▎         | 31023/42525 [59:16<23:23,  8.19it/s]

 73%|██████████████████████████▎         | 31025/42525 [59:16<22:24,  8.55it/s]

 73%|██████████████████████████▎         | 31027/42525 [59:17<25:22,  7.55it/s]

 73%|██████████████████████████▎         | 31030/42525 [59:17<23:00,  8.33it/s]

 73%|██████████████████████████▎         | 31034/42525 [59:17<20:29,  9.34it/s]

 73%|██████████████████████████▎         | 31036/42525 [59:17<20:41,  9.26it/s]

 73%|██████████████████████████▎         | 31039/42525 [59:18<21:08,  9.05it/s]

 73%|██████████████████████████▎         | 31041/42525 [59:18<20:21,  9.40it/s]

 73%|██████████████████████████▎         | 31044/42525 [59:18<22:41,  8.43it/s]

 73%|██████████████████████████▎         | 31048/42525 [59:19<20:22,  9.39it/s]

 73%|██████████████████████████▎         | 31049/42525 [59:19<20:09,  9.49it/s]

 73%|██████████████████████████▎         | 31051/42525 [59:19<20:20,  9.40it/s]

 73%|██████████████████████████▎         | 31053/42525 [59:19<20:25,  9.36it/s]

 73%|██████████████████████████▎         | 31056/42525 [59:20<21:50,  8.75it/s]

 73%|██████████████████████████▎         | 31059/42525 [59:20<20:48,  9.19it/s]

 73%|██████████████████████████▎         | 31061/42525 [59:20<19:54,  9.60it/s]

 73%|██████████████████████████▎         | 31064/42525 [59:21<21:29,  8.89it/s]

 73%|██████████████████████████▎         | 31066/42525 [59:21<21:00,  9.09it/s]

 73%|██████████████████████████▎         | 31068/42525 [59:21<20:24,  9.35it/s]

 73%|██████████████████████████▎         | 31070/42525 [59:21<20:05,  9.50it/s]

 73%|██████████████████████████▎         | 31073/42525 [59:22<21:13,  9.00it/s]

 73%|██████████████████████████▎         | 31076/42525 [59:22<20:01,  9.53it/s]

 73%|██████████████████████████▎         | 31079/42525 [59:22<19:33,  9.75it/s]

 73%|██████████████████████████▎         | 31080/42525 [59:22<19:35,  9.73it/s]

 73%|██████████████████████████▎         | 31084/42525 [59:23<19:15,  9.90it/s]

 73%|██████████████████████████▎         | 31086/42525 [59:23<19:00, 10.03it/s]

 73%|██████████████████████████▎         | 31089/42525 [59:23<20:19,  9.38it/s]

 73%|██████████████████████████▎         | 31092/42525 [59:24<21:28,  8.87it/s]

 73%|██████████████████████████▎         | 31094/42525 [59:24<20:54,  9.11it/s]

 73%|██████████████████████████▎         | 31096/42525 [59:24<22:38,  8.41it/s]

 73%|██████████████████████████▎         | 31098/42525 [59:24<23:36,  8.06it/s]

 73%|██████████████████████████▎         | 31099/42525 [59:24<23:00,  8.28it/s]

 73%|██████████████████████████▎         | 31102/42525 [59:25<22:38,  8.41it/s]

 73%|██████████████████████████▎         | 31105/42525 [59:25<21:56,  8.68it/s]

 73%|██████████████████████████▎         | 31106/42525 [59:25<21:20,  8.92it/s]

 73%|██████████████████████████▎         | 31108/42525 [59:25<22:08,  8.59it/s]

 73%|██████████████████████████▎         | 31110/42525 [59:26<22:35,  8.42it/s]

 73%|██████████████████████████▎         | 31112/42525 [59:26<22:45,  8.36it/s]

 73%|██████████████████████████▎         | 31115/42525 [59:26<22:59,  8.27it/s]

 73%|██████████████████████████▎         | 31116/42525 [59:26<23:33,  8.07it/s]

 73%|██████████████████████████▎         | 31120/42525 [59:27<21:34,  8.81it/s]

 73%|██████████████████████████▎         | 31123/42525 [59:27<21:44,  8.74it/s]

 73%|██████████████████████████▎         | 31125/42525 [59:27<20:58,  9.06it/s]

 73%|██████████████████████████▎         | 31127/42525 [59:28<20:26,  9.29it/s]

 73%|██████████████████████████▎         | 31130/42525 [59:28<21:42,  8.75it/s]

 73%|██████████████████████████▎         | 31134/42525 [59:28<19:40,  9.65it/s]

 73%|██████████████████████████▎         | 31137/42525 [59:29<22:22,  8.48it/s]

 73%|██████████████████████████▎         | 31139/42525 [59:29<23:52,  7.95it/s]

 73%|██████████████████████████▎         | 31142/42525 [59:29<21:08,  8.98it/s]

 73%|██████████████████████████▎         | 31143/42525 [59:29<22:47,  8.32it/s]

 73%|██████████████████████████▎         | 31145/42525 [59:30<21:15,  8.92it/s]

 73%|██████████████████████████▎         | 31148/42525 [59:30<20:28,  9.26it/s]

 73%|██████████████████████████▎         | 31151/42525 [59:30<21:19,  8.89it/s]

 73%|██████████████████████████▎         | 31153/42525 [59:31<21:23,  8.86it/s]

 73%|██████████████████████████▍         | 31156/42525 [59:31<21:17,  8.90it/s]

 73%|██████████████████████████▍         | 31159/42525 [59:31<19:59,  9.48it/s]

 73%|██████████████████████████▍         | 31160/42525 [59:31<20:22,  9.29it/s]

 73%|██████████████████████████▍         | 31164/42525 [59:32<19:18,  9.81it/s]

 73%|██████████████████████████▍         | 31165/42525 [59:32<19:44,  9.59it/s]

 73%|██████████████████████████▍         | 31168/42525 [59:32<21:51,  8.66it/s]

 73%|██████████████████████████▍         | 31170/42525 [59:32<20:54,  9.05it/s]

 73%|██████████████████████████▍         | 31174/42525 [59:33<20:47,  9.10it/s]

 73%|██████████████████████████▍         | 31178/42525 [59:33<19:23,  9.75it/s]

 73%|██████████████████████████▍         | 31181/42525 [59:34<19:08,  9.87it/s]

 73%|██████████████████████████▍         | 31184/42525 [59:34<20:38,  9.16it/s]

 73%|██████████████████████████▍         | 31187/42525 [59:34<19:32,  9.67it/s]

 73%|██████████████████████████▍         | 31190/42525 [59:35<21:57,  8.60it/s]

 73%|██████████████████████████▍         | 31192/42525 [59:35<21:19,  8.86it/s]

 73%|██████████████████████████▍         | 31193/42525 [59:35<20:50,  9.06it/s]

 73%|██████████████████████████▍         | 31196/42525 [59:35<20:27,  9.23it/s]

 73%|██████████████████████████▍         | 31198/42525 [59:35<20:23,  9.26it/s]

 73%|██████████████████████████▍         | 31201/42525 [59:36<19:56,  9.46it/s]

 73%|██████████████████████████▍         | 31205/42525 [59:36<18:54,  9.98it/s]

 73%|██████████████████████████▍         | 31208/42525 [59:36<20:35,  9.16it/s]

 73%|██████████████████████████▍         | 31210/42525 [59:37<21:33,  8.75it/s]

 73%|██████████████████████████▍         | 31212/42525 [59:37<22:07,  8.52it/s]

 73%|██████████████████████████▍         | 31215/42525 [59:37<22:08,  8.51it/s]

 73%|██████████████████████████▍         | 31217/42525 [59:38<22:59,  8.20it/s]

 73%|██████████████████████████▍         | 31221/42525 [59:38<20:08,  9.35it/s]

 73%|██████████████████████████▍         | 31223/42525 [59:38<21:10,  8.89it/s]

 73%|██████████████████████████▍         | 31226/42525 [59:39<23:02,  8.17it/s]

 73%|██████████████████████████▍         | 31227/42525 [59:39<23:28,  8.02it/s]

 73%|██████████████████████████▍         | 31230/42525 [59:39<24:24,  7.71it/s]

 73%|██████████████████████████▍         | 31232/42525 [59:39<22:08,  8.50it/s]

 73%|██████████████████████████▍         | 31234/42525 [59:40<23:00,  8.18it/s]

 73%|██████████████████████████▍         | 31238/42525 [59:40<20:03,  9.38it/s]

 73%|██████████████████████████▍         | 31241/42525 [59:40<22:09,  8.49it/s]

 73%|██████████████████████████▍         | 31243/42525 [59:41<23:01,  8.17it/s]

 73%|██████████████████████████▍         | 31246/42525 [59:41<20:47,  9.04it/s]

 73%|██████████████████████████▍         | 31247/42525 [59:41<21:44,  8.65it/s]

 73%|██████████████████████████▍         | 31250/42525 [59:41<21:37,  8.69it/s]

 73%|██████████████████████████▍         | 31253/42525 [59:42<21:16,  8.83it/s]

 74%|██████████████████████████▍         | 31257/42525 [59:42<19:21,  9.70it/s]

 74%|██████████████████████████▍         | 31260/42525 [59:42<20:39,  9.09it/s]

 74%|██████████████████████████▍         | 31263/42525 [59:43<21:09,  8.87it/s]

 74%|██████████████████████████▍         | 31266/42525 [59:43<20:52,  8.99it/s]

 74%|██████████████████████████▍         | 31268/42525 [59:43<21:40,  8.66it/s]

 74%|██████████████████████████▍         | 31270/42525 [59:44<22:05,  8.49it/s]

 74%|██████████████████████████▍         | 31273/42525 [59:44<21:28,  8.73it/s]

 74%|██████████████████████████▍         | 31275/42525 [59:44<24:06,  7.78it/s]

 74%|██████████████████████████▍         | 31278/42525 [59:45<22:17,  8.41it/s]

 74%|██████████████████████████▍         | 31280/42525 [59:45<23:06,  8.11it/s]

 74%|██████████████████████████▍         | 31282/42525 [59:45<21:38,  8.66it/s]

 74%|██████████████████████████▍         | 31285/42525 [59:45<21:52,  8.56it/s]

 74%|██████████████████████████▍         | 31288/42525 [59:46<22:16,  8.41it/s]

 74%|██████████████████████████▍         | 31291/42525 [59:46<21:28,  8.72it/s]

 74%|██████████████████████████▍         | 31294/42525 [59:46<19:56,  9.39it/s]

 74%|██████████████████████████▍         | 31296/42525 [59:47<20:58,  8.92it/s]

 74%|██████████████████████████▍         | 31300/42525 [59:47<20:06,  9.31it/s]

 74%|██████████████████████████▍         | 31302/42525 [59:47<19:24,  9.64it/s]

 74%|██████████████████████████▌         | 31306/42525 [59:48<19:46,  9.45it/s]

 74%|██████████████████████████▌         | 31308/42525 [59:48<19:19,  9.67it/s]

 74%|██████████████████████████▌         | 31312/42525 [59:48<19:42,  9.49it/s]

 74%|██████████████████████████▌         | 31314/42525 [59:48<19:28,  9.59it/s]

 74%|██████████████████████████▌         | 31317/42525 [59:49<19:24,  9.62it/s]

 74%|██████████████████████████▌         | 31320/42525 [59:49<19:36,  9.52it/s]

 74%|██████████████████████████▌         | 31324/42525 [59:50<18:42,  9.98it/s]

 74%|██████████████████████████▌         | 31328/42525 [59:50<19:49,  9.41it/s]

 74%|██████████████████████████▌         | 31332/42525 [59:50<19:55,  9.36it/s]

 74%|██████████████████████████▌         | 31336/42525 [59:51<19:13,  9.70it/s]

 74%|██████████████████████████▌         | 31337/42525 [59:51<19:20,  9.64it/s]

 74%|██████████████████████████▌         | 31340/42525 [59:51<20:21,  9.16it/s]

 74%|██████████████████████████▌         | 31342/42525 [59:52<23:16,  8.01it/s]

 74%|██████████████████████████▌         | 31345/42525 [59:52<22:52,  8.14it/s]

 74%|██████████████████████████▌         | 31347/42525 [59:52<22:29,  8.28it/s]

 74%|██████████████████████████▌         | 31350/42525 [59:52<21:39,  8.60it/s]

 74%|██████████████████████████▌         | 31352/42525 [59:53<21:07,  8.82it/s]

 74%|██████████████████████████▌         | 31356/42525 [59:53<19:57,  9.32it/s]

 74%|██████████████████████████▌         | 31358/42525 [59:53<19:17,  9.65it/s]

 74%|██████████████████████████▌         | 31362/42525 [59:54<19:13,  9.68it/s]

 74%|██████████████████████████▌         | 31365/42525 [59:54<19:17,  9.64it/s]

 74%|██████████████████████████▌         | 31367/42525 [59:54<19:59,  9.30it/s]

 74%|██████████████████████████▌         | 31369/42525 [59:54<19:43,  9.43it/s]

 74%|██████████████████████████▌         | 31372/42525 [59:55<20:42,  8.98it/s]

 74%|██████████████████████████▌         | 31375/42525 [59:55<19:36,  9.48it/s]

 74%|██████████████████████████▌         | 31377/42525 [59:55<20:34,  9.03it/s]

 74%|██████████████████████████▌         | 31381/42525 [59:56<19:12,  9.67it/s]

 74%|██████████████████████████▌         | 31384/42525 [59:56<20:47,  8.93it/s]

 74%|██████████████████████████▌         | 31387/42525 [59:56<19:41,  9.42it/s]

 74%|██████████████████████████▌         | 31390/42525 [59:57<19:11,  9.67it/s]

 74%|██████████████████████████▌         | 31393/42525 [59:57<19:33,  9.49it/s]

 74%|██████████████████████████▌         | 31396/42525 [59:57<19:53,  9.32it/s]

 74%|██████████████████████████▌         | 31398/42525 [59:58<20:01,  9.26it/s]

 74%|██████████████████████████▌         | 31399/42525 [59:58<20:03,  9.24it/s]

 74%|██████████████████████████▌         | 31402/42525 [59:58<20:15,  9.15it/s]

 74%|██████████████████████████▌         | 31404/42525 [59:58<22:41,  8.17it/s]

 74%|██████████████████████████▌         | 31406/42525 [59:59<21:45,  8.52it/s]

 74%|██████████████████████████▌         | 31408/42525 [59:59<23:02,  8.04it/s]

 74%|██████████████████████████▌         | 31410/42525 [59:59<22:22,  8.28it/s]

 74%|██████████████████████████▌         | 31413/42525 [59:59<22:51,  8.10it/s]

 74%|█████████████████████████         | 31416/42525 [1:00:00<21:23,  8.65it/s]

 74%|█████████████████████████         | 31418/42525 [1:00:00<22:38,  8.18it/s]

 74%|█████████████████████████         | 31420/42525 [1:00:00<23:10,  7.99it/s]

 74%|█████████████████████████         | 31424/42525 [1:00:01<20:05,  9.21it/s]

 74%|█████████████████████████▏        | 31427/42525 [1:00:01<19:00,  9.73it/s]

 74%|█████████████████████████▏        | 31429/42525 [1:00:01<18:32,  9.97it/s]

 74%|█████████████████████████▏        | 31432/42525 [1:00:02<21:28,  8.61it/s]

 74%|█████████████████████████▏        | 31435/42525 [1:00:02<20:00,  9.23it/s]

 74%|█████████████████████████▏        | 31438/42525 [1:00:02<20:59,  8.81it/s]

 74%|█████████████████████████▏        | 31441/42525 [1:00:03<20:07,  9.18it/s]

 74%|█████████████████████████▏        | 31443/42525 [1:00:03<22:01,  8.38it/s]

 74%|█████████████████████████▏        | 31445/42525 [1:00:03<22:56,  8.05it/s]

 74%|█████████████████████████▏        | 31447/42525 [1:00:03<22:36,  8.17it/s]

 74%|█████████████████████████▏        | 31448/42525 [1:00:03<22:24,  8.24it/s]

 74%|█████████████████████████▏        | 31450/42525 [1:00:04<20:45,  8.89it/s]

 74%|█████████████████████████▏        | 31453/42525 [1:00:04<22:58,  8.03it/s]

 74%|█████████████████████████▏        | 31456/42525 [1:00:04<21:27,  8.60it/s]

 74%|█████████████████████████▏        | 31460/42525 [1:00:05<20:37,  8.95it/s]

 74%|█████████████████████████▏        | 31464/42525 [1:00:05<19:09,  9.62it/s]

 74%|█████████████████████████▏        | 31467/42525 [1:00:06<19:35,  9.40it/s]

 74%|█████████████████████████▏        | 31469/42525 [1:00:06<19:21,  9.52it/s]

 74%|█████████████████████████▏        | 31472/42525 [1:00:06<19:12,  9.59it/s]

 74%|█████████████████████████▏        | 31474/42525 [1:00:06<22:17,  8.26it/s]

 74%|█████████████████████████▏        | 31477/42525 [1:00:07<20:53,  8.81it/s]

 74%|█████████████████████████▏        | 31478/42525 [1:00:07<21:20,  8.63it/s]

 74%|█████████████████████████▏        | 31480/42525 [1:00:07<20:26,  9.00it/s]

 74%|█████████████████████████▏        | 31484/42525 [1:00:07<19:22,  9.49it/s]

 74%|█████████████████████████▏        | 31487/42525 [1:00:08<19:02,  9.66it/s]

 74%|█████████████████████████▏        | 31489/42525 [1:00:08<18:59,  9.68it/s]

 74%|█████████████████████████▏        | 31492/42525 [1:00:08<19:23,  9.48it/s]

 74%|█████████████████████████▏        | 31495/42525 [1:00:09<18:50,  9.75it/s]

 74%|█████████████████████████▏        | 31498/42525 [1:00:09<18:39,  9.85it/s]

 74%|█████████████████████████▏        | 31500/42525 [1:00:09<22:19,  8.23it/s]

 74%|█████████████████████████▏        | 31503/42525 [1:00:09<20:19,  9.04it/s]

 74%|█████████████████████████▏        | 31507/42525 [1:00:10<19:15,  9.53it/s]

 74%|█████████████████████████▏        | 31510/42525 [1:00:10<18:59,  9.66it/s]

 74%|█████████████████████████▏        | 31512/42525 [1:00:10<18:33,  9.89it/s]

 74%|█████████████████████████▏        | 31516/42525 [1:00:11<18:29,  9.92it/s]

 74%|█████████████████████████▏        | 31520/42525 [1:00:11<17:59, 10.19it/s]

 74%|█████████████████████████▏        | 31522/42525 [1:00:11<17:52, 10.26it/s]

 74%|█████████████████████████▏        | 31524/42525 [1:00:12<18:45,  9.77it/s]

 74%|█████████████████████████▏        | 31527/42525 [1:00:12<19:12,  9.54it/s]

 74%|█████████████████████████▏        | 31530/42525 [1:00:12<18:53,  9.70it/s]

 74%|█████████████████████████▏        | 31532/42525 [1:00:12<20:29,  8.94it/s]

 74%|█████████████████████████▏        | 31535/42525 [1:00:13<19:34,  9.36it/s]

 74%|█████████████████████████▏        | 31539/42525 [1:00:13<18:36,  9.84it/s]

 74%|█████████████████████████▏        | 31541/42525 [1:00:13<18:18, 10.00it/s]

 74%|█████████████████████████▏        | 31544/42525 [1:00:14<18:52,  9.69it/s]

 74%|█████████████████████████▏        | 31547/42525 [1:00:14<18:32,  9.86it/s]

 74%|█████████████████████████▏        | 31549/42525 [1:00:14<19:28,  9.40it/s]

 74%|█████████████████████████▏        | 31550/42525 [1:00:14<21:21,  8.57it/s]

 74%|█████████████████████████▏        | 31552/42525 [1:00:15<20:27,  8.94it/s]

 74%|█████████████████████████▏        | 31555/42525 [1:00:15<21:19,  8.57it/s]

 74%|█████████████████████████▏        | 31558/42525 [1:00:15<20:02,  9.12it/s]

 74%|█████████████████████████▏        | 31560/42525 [1:00:15<19:26,  9.40it/s]

 74%|█████████████████████████▏        | 31562/42525 [1:00:16<19:08,  9.55it/s]

 74%|█████████████████████████▏        | 31564/42525 [1:00:16<19:33,  9.34it/s]

 74%|█████████████████████████▏        | 31566/42525 [1:00:16<20:30,  8.90it/s]

 74%|█████████████████████████▏        | 31570/42525 [1:00:16<20:06,  9.08it/s]

 74%|█████████████████████████▏        | 31572/42525 [1:00:17<20:49,  8.77it/s]

 74%|█████████████████████████▏        | 31574/42525 [1:00:17<19:35,  9.32it/s]

 74%|█████████████████████████▏        | 31578/42525 [1:00:17<18:50,  9.69it/s]

 74%|█████████████████████████▏        | 31581/42525 [1:00:18<18:47,  9.70it/s]

 74%|█████████████████████████▎        | 31583/42525 [1:00:18<18:22,  9.92it/s]

 74%|█████████████████████████▎        | 31586/42525 [1:00:18<19:25,  9.39it/s]

 74%|█████████████████████████▎        | 31588/42525 [1:00:18<18:46,  9.71it/s]

 74%|█████████████████████████▎        | 31590/42525 [1:00:19<19:58,  9.12it/s]

 74%|█████████████████████████▎        | 31592/42525 [1:00:19<20:00,  9.11it/s]

 74%|█████████████████████████▎        | 31595/42525 [1:00:19<19:38,  9.27it/s]

 74%|█████████████████████████▎        | 31597/42525 [1:00:19<20:54,  8.71it/s]

 74%|█████████████████████████▎        | 31600/42525 [1:00:20<20:42,  8.79it/s]

 74%|█████████████████████████▎        | 31603/42525 [1:00:20<19:35,  9.29it/s]

 74%|█████████████████████████▎        | 31606/42525 [1:00:20<19:50,  9.17it/s]

 74%|█████████████████████████▎        | 31610/42525 [1:00:21<18:34,  9.80it/s]

 74%|█████████████████████████▎        | 31612/42525 [1:00:21<19:38,  9.26it/s]

 74%|█████████████████████████▎        | 31615/42525 [1:00:21<18:45,  9.70it/s]

 74%|█████████████████████████▎        | 31618/42525 [1:00:22<18:38,  9.75it/s]

 74%|█████████████████████████▎        | 31621/42525 [1:00:22<19:22,  9.38it/s]

 74%|█████████████████████████▎        | 31624/42525 [1:00:22<18:55,  9.60it/s]

 74%|█████████████████████████▎        | 31626/42525 [1:00:23<22:13,  8.17it/s]

 74%|█████████████████████████▎        | 31629/42525 [1:00:23<20:55,  8.68it/s]

 74%|█████████████████████████▎        | 31632/42525 [1:00:23<19:17,  9.41it/s]

 74%|█████████████████████████▎        | 31634/42525 [1:00:23<20:26,  8.88it/s]

 74%|█████████████████████████▎        | 31636/42525 [1:00:24<20:18,  8.93it/s]

 74%|█████████████████████████▎        | 31638/42525 [1:00:24<19:00,  9.54it/s]

 74%|█████████████████████████▎        | 31640/42525 [1:00:24<19:04,  9.51it/s]

 74%|█████████████████████████▎        | 31643/42525 [1:00:24<18:49,  9.63it/s]

 74%|█████████████████████████▎        | 31646/42525 [1:00:25<19:50,  9.14it/s]

 74%|█████████████████████████▎        | 31649/42525 [1:00:25<19:57,  9.09it/s]

 74%|█████████████████████████▎        | 31651/42525 [1:00:25<19:38,  9.23it/s]

 74%|█████████████████████████▎        | 31654/42525 [1:00:26<21:58,  8.25it/s]

 74%|█████████████████████████▎        | 31656/42525 [1:00:26<20:32,  8.82it/s]

 74%|█████████████████████████▎        | 31660/42525 [1:00:26<19:11,  9.44it/s]

 74%|█████████████████████████▎        | 31662/42525 [1:00:27<20:11,  8.97it/s]

 74%|█████████████████████████▎        | 31664/42525 [1:00:27<21:30,  8.42it/s]

 74%|█████████████████████████▎        | 31668/42525 [1:00:27<20:14,  8.94it/s]

 74%|█████████████████████████▎        | 31672/42525 [1:00:28<18:50,  9.60it/s]

 74%|█████████████████████████▎        | 31675/42525 [1:00:28<19:19,  9.36it/s]

 74%|█████████████████████████▎        | 31677/42525 [1:00:28<20:17,  8.91it/s]

 74%|█████████████████████████▎        | 31679/42525 [1:00:28<20:54,  8.64it/s]

 74%|█████████████████████████▎        | 31681/42525 [1:00:29<20:04,  9.00it/s]

 75%|█████████████████████████▎        | 31684/42525 [1:00:29<19:49,  9.11it/s]

 75%|█████████████████████████▎        | 31687/42525 [1:00:29<18:51,  9.58it/s]

 75%|█████████████████████████▎        | 31690/42525 [1:00:30<18:33,  9.73it/s]

 75%|█████████████████████████▎        | 31692/42525 [1:00:30<18:09,  9.94it/s]

 75%|█████████████████████████▎        | 31695/42525 [1:00:30<20:53,  8.64it/s]

 75%|█████████████████████████▎        | 31699/42525 [1:00:31<18:50,  9.57it/s]

 75%|█████████████████████████▎        | 31702/42525 [1:00:31<21:11,  8.51it/s]

 75%|█████████████████████████▎        | 31704/42525 [1:00:31<19:54,  9.06it/s]

 75%|█████████████████████████▎        | 31707/42525 [1:00:31<21:18,  8.46it/s]

 75%|█████████████████████████▎        | 31710/42525 [1:00:32<21:11,  8.50it/s]

 75%|█████████████████████████▎        | 31712/42525 [1:00:32<23:30,  7.67it/s]

 75%|█████████████████████████▎        | 31714/42525 [1:00:32<21:09,  8.52it/s]

 75%|█████████████████████████▎        | 31718/42525 [1:00:33<19:17,  9.33it/s]

 75%|█████████████████████████▎        | 31720/42525 [1:00:33<20:55,  8.61it/s]

 75%|█████████████████████████▎        | 31723/42525 [1:00:33<20:36,  8.74it/s]

 75%|█████████████████████████▎        | 31726/42525 [1:00:34<21:19,  8.44it/s]

 75%|█████████████████████████▎        | 31729/42525 [1:00:34<21:42,  8.29it/s]

 75%|█████████████████████████▎        | 31730/42525 [1:00:34<22:50,  7.87it/s]

 75%|█████████████████████████▎        | 31734/42525 [1:00:35<20:37,  8.72it/s]

 75%|█████████████████████████▎        | 31737/42525 [1:00:35<20:45,  8.66it/s]

 75%|█████████████████████████▍        | 31741/42525 [1:00:35<18:59,  9.47it/s]

 75%|█████████████████████████▍        | 31745/42525 [1:00:36<17:58,  9.99it/s]

 75%|█████████████████████████▍        | 31749/42525 [1:00:36<17:49, 10.08it/s]

 75%|█████████████████████████▍        | 31752/42525 [1:00:37<20:36,  8.71it/s]

 75%|█████████████████████████▍        | 31754/42525 [1:00:37<21:33,  8.33it/s]

 75%|█████████████████████████▍        | 31757/42525 [1:00:37<22:50,  7.85it/s]

 75%|█████████████████████████▍        | 31758/42525 [1:00:37<22:39,  7.92it/s]

 75%|█████████████████████████▍        | 31762/42525 [1:00:38<20:24,  8.79it/s]

 75%|█████████████████████████▍        | 31764/42525 [1:00:38<21:05,  8.50it/s]

 75%|█████████████████████████▍        | 31767/42525 [1:00:38<19:21,  9.26it/s]

 75%|█████████████████████████▍        | 31770/42525 [1:00:39<18:45,  9.55it/s]

 75%|█████████████████████████▍        | 31772/42525 [1:00:39<19:44,  9.08it/s]

 75%|█████████████████████████▍        | 31775/42525 [1:00:39<18:44,  9.56it/s]

 75%|█████████████████████████▍        | 31778/42525 [1:00:39<19:27,  9.20it/s]

 75%|█████████████████████████▍        | 31781/42525 [1:00:40<19:17,  9.29it/s]

 75%|█████████████████████████▍        | 31784/42525 [1:00:40<18:26,  9.71it/s]

 75%|█████████████████████████▍        | 31786/42525 [1:00:40<20:44,  8.63it/s]

 75%|█████████████████████████▍        | 31788/42525 [1:00:41<19:20,  9.25it/s]

 75%|█████████████████████████▍        | 31790/42525 [1:00:41<19:08,  9.35it/s]

 75%|█████████████████████████▍        | 31793/42525 [1:00:41<20:04,  8.91it/s]

 75%|█████████████████████████▍        | 31794/42525 [1:00:41<19:38,  9.10it/s]

 75%|█████████████████████████▍        | 31796/42525 [1:00:41<19:02,  9.39it/s]

 75%|█████████████████████████▍        | 31800/42525 [1:00:42<19:16,  9.27it/s]

 75%|█████████████████████████▍        | 31804/42525 [1:00:42<18:23,  9.72it/s]

 75%|█████████████████████████▍        | 31805/42525 [1:00:42<18:24,  9.70it/s]

 75%|█████████████████████████▍        | 31808/42525 [1:00:43<20:14,  8.82it/s]

 75%|█████████████████████████▍        | 31810/42525 [1:00:43<22:49,  7.83it/s]

 75%|█████████████████████████▍        | 31814/42525 [1:00:43<19:20,  9.23it/s]

 75%|█████████████████████████▍        | 31817/42525 [1:00:44<19:25,  9.18it/s]

 75%|█████████████████████████▍        | 31820/42525 [1:00:44<19:00,  9.39it/s]

 75%|█████████████████████████▍        | 31824/42525 [1:00:44<17:58,  9.92it/s]

 75%|█████████████████████████▍        | 31825/42525 [1:00:45<18:11,  9.80it/s]

 75%|█████████████████████████▍        | 31828/42525 [1:00:45<19:29,  9.15it/s]

 75%|█████████████████████████▍        | 31830/42525 [1:00:45<20:55,  8.52it/s]

 75%|█████████████████████████▍        | 31833/42525 [1:00:45<19:28,  9.15it/s]

 75%|█████████████████████████▍        | 31836/42525 [1:00:46<20:45,  8.58it/s]

 75%|█████████████████████████▍        | 31839/42525 [1:00:46<19:20,  9.21it/s]

 75%|█████████████████████████▍        | 31840/42525 [1:00:46<20:53,  8.52it/s]

 75%|█████████████████████████▍        | 31843/42525 [1:00:47<20:40,  8.61it/s]

 75%|█████████████████████████▍        | 31845/42525 [1:00:47<19:18,  9.22it/s]

 75%|█████████████████████████▍        | 31847/42525 [1:00:47<19:25,  9.16it/s]

 75%|█████████████████████████▍        | 31850/42525 [1:00:47<19:13,  9.25it/s]

 75%|█████████████████████████▍        | 31852/42525 [1:00:48<19:15,  9.23it/s]

 75%|█████████████████████████▍        | 31854/42525 [1:00:48<18:24,  9.66it/s]

 75%|█████████████████████████▍        | 31856/42525 [1:00:48<19:42,  9.02it/s]

 75%|█████████████████████████▍        | 31859/42525 [1:00:48<19:18,  9.21it/s]

 75%|█████████████████████████▍        | 31862/42525 [1:00:49<19:06,  9.30it/s]

 75%|█████████████████████████▍        | 31865/42525 [1:00:49<18:24,  9.65it/s]

 75%|█████████████████████████▍        | 31867/42525 [1:00:49<20:09,  8.81it/s]

 75%|█████████████████████████▍        | 31870/42525 [1:00:50<20:26,  8.69it/s]

 75%|█████████████████████████▍        | 31872/42525 [1:00:50<19:56,  8.90it/s]

 75%|█████████████████████████▍        | 31874/42525 [1:00:50<20:37,  8.61it/s]

 75%|█████████████████████████▍        | 31877/42525 [1:00:50<21:05,  8.41it/s]

 75%|█████████████████████████▍        | 31880/42525 [1:00:51<20:02,  8.86it/s]

 75%|█████████████████████████▍        | 31883/42525 [1:00:51<19:45,  8.97it/s]

 75%|█████████████████████████▍        | 31886/42525 [1:00:51<18:42,  9.48it/s]

 75%|█████████████████████████▍        | 31889/42525 [1:00:52<19:45,  8.97it/s]

 75%|█████████████████████████▍        | 31891/42525 [1:00:52<21:30,  8.24it/s]

 75%|█████████████████████████▍        | 31893/42525 [1:00:52<22:05,  8.02it/s]

 75%|█████████████████████████▌        | 31896/42525 [1:00:53<19:27,  9.11it/s]

 75%|█████████████████████████▌        | 31898/42525 [1:00:53<19:29,  9.09it/s]

 75%|█████████████████████████▌        | 31901/42525 [1:00:53<19:53,  8.91it/s]

 75%|█████████████████████████▌        | 31903/42525 [1:00:53<18:35,  9.52it/s]

 75%|█████████████████████████▌        | 31907/42525 [1:00:54<18:49,  9.40it/s]

 75%|█████████████████████████▌        | 31910/42525 [1:00:54<19:47,  8.94it/s]

 75%|█████████████████████████▌        | 31913/42525 [1:00:54<18:53,  9.36it/s]

 75%|█████████████████████████▌        | 31915/42525 [1:00:55<19:51,  8.91it/s]

 75%|█████████████████████████▌        | 31917/42525 [1:00:55<21:06,  8.37it/s]

 75%|█████████████████████████▌        | 31919/42525 [1:00:55<19:37,  9.01it/s]

 75%|█████████████████████████▌        | 31920/42525 [1:00:55<19:59,  8.84it/s]

 75%|█████████████████████████▌        | 31923/42525 [1:00:56<20:07,  8.78it/s]

 75%|█████████████████████████▌        | 31925/42525 [1:00:56<20:40,  8.54it/s]

 75%|█████████████████████████▌        | 31928/42525 [1:00:56<19:55,  8.86it/s]

 75%|█████████████████████████▌        | 31930/42525 [1:00:56<19:44,  8.95it/s]

 75%|█████████████████████████▌        | 31933/42525 [1:00:57<19:32,  9.03it/s]

 75%|█████████████████████████▌        | 31936/42525 [1:00:57<19:04,  9.25it/s]

 75%|█████████████████████████▌        | 31940/42525 [1:00:57<18:01,  9.79it/s]

 75%|█████████████████████████▌        | 31942/42525 [1:00:58<18:42,  9.43it/s]

 75%|█████████████████████████▌        | 31945/42525 [1:00:58<18:59,  9.29it/s]

 75%|█████████████████████████▌        | 31946/42525 [1:00:58<20:34,  8.57it/s]

 75%|█████████████████████████▌        | 31950/42525 [1:00:59<19:40,  8.96it/s]

 75%|█████████████████████████▌        | 31953/42525 [1:00:59<21:29,  8.20it/s]

 75%|█████████████████████████▌        | 31954/42525 [1:00:59<22:27,  7.84it/s]

 75%|█████████████████████████▌        | 31958/42525 [1:01:00<20:18,  8.67it/s]

 75%|█████████████████████████▌        | 31959/42525 [1:01:00<20:47,  8.47it/s]

 75%|█████████████████████████▌        | 31962/42525 [1:01:00<19:58,  8.81it/s]

 75%|█████████████████████████▌        | 31964/42525 [1:01:00<20:03,  8.78it/s]

 75%|█████████████████████████▌        | 31967/42525 [1:01:01<20:42,  8.50it/s]

 75%|█████████████████████████▌        | 31970/42525 [1:01:01<19:27,  9.04it/s]

 75%|█████████████████████████▌        | 31973/42525 [1:01:01<19:00,  9.25it/s]

 75%|█████████████████████████▌        | 31976/42525 [1:01:02<19:59,  8.79it/s]

 75%|█████████████████████████▌        | 31978/42525 [1:01:02<21:30,  8.17it/s]

 75%|█████████████████████████▌        | 31980/42525 [1:01:02<19:41,  8.93it/s]

 75%|█████████████████████████▌        | 31982/42525 [1:01:02<19:02,  9.23it/s]

 75%|█████████████████████████▌        | 31985/42525 [1:01:03<21:20,  8.23it/s]

 75%|█████████████████████████▌        | 31987/42525 [1:01:03<21:52,  8.03it/s]

 75%|█████████████████████████▌        | 31989/42525 [1:01:03<20:58,  8.37it/s]

 75%|█████████████████████████▌        | 31992/42525 [1:01:03<20:49,  8.43it/s]

 75%|█████████████████████████▌        | 31995/42525 [1:01:04<18:52,  9.30it/s]

 75%|█████████████████████████▌        | 31997/42525 [1:01:04<19:10,  9.15it/s]

 75%|█████████████████████████▌        | 32000/42525 [1:01:04<18:29,  9.49it/s]

 75%|█████████████████████████▌        | 32002/42525 [1:01:04<17:50,  9.83it/s]

 75%|█████████████████████████▌        | 32006/42525 [1:01:05<18:31,  9.47it/s]

 75%|█████████████████████████▌        | 32008/42525 [1:01:05<18:46,  9.33it/s]

 75%|█████████████████████████▌        | 32011/42525 [1:01:05<19:30,  8.98it/s]

 75%|█████████████████████████▌        | 32013/42525 [1:01:06<20:53,  8.39it/s]

 75%|█████████████████████████▌        | 32017/42525 [1:01:06<18:26,  9.49it/s]

 75%|█████████████████████████▌        | 32018/42525 [1:01:06<20:02,  8.74it/s]

 75%|█████████████████████████▌        | 32021/42525 [1:01:07<20:22,  8.59it/s]

 75%|█████████████████████████▌        | 32023/42525 [1:01:07<22:34,  7.75it/s]

 75%|█████████████████████████▌        | 32025/42525 [1:01:07<23:08,  7.56it/s]

 75%|█████████████████████████▌        | 32027/42525 [1:01:07<21:09,  8.27it/s]

 75%|█████████████████████████▌        | 32030/42525 [1:01:08<19:23,  9.02it/s]

 75%|█████████████████████████▌        | 32033/42525 [1:01:08<21:32,  8.12it/s]

 75%|█████████████████████████▌        | 32035/42525 [1:01:08<19:46,  8.84it/s]

 75%|█████████████████████████▌        | 32038/42525 [1:01:09<20:38,  8.47it/s]

 75%|█████████████████████████▌        | 32041/42525 [1:01:09<19:52,  8.79it/s]

 75%|█████████████████████████▌        | 32043/42525 [1:01:09<21:20,  8.19it/s]

 75%|█████████████████████████▌        | 32045/42525 [1:01:09<20:07,  8.68it/s]

 75%|█████████████████████████▌        | 32046/42525 [1:01:10<19:55,  8.76it/s]

 75%|█████████████████████████▌        | 32049/42525 [1:01:10<20:54,  8.35it/s]

 75%|█████████████████████████▋        | 32051/42525 [1:01:10<19:18,  9.04it/s]

 75%|█████████████████████████▋        | 32054/42525 [1:01:10<18:50,  9.27it/s]

 75%|█████████████████████████▋        | 32057/42525 [1:01:11<18:02,  9.67it/s]

 75%|█████████████████████████▋        | 32060/42525 [1:01:11<17:35,  9.91it/s]

 75%|█████████████████████████▋        | 32061/42525 [1:01:11<19:24,  8.98it/s]

 75%|█████████████████████████▋        | 32064/42525 [1:01:12<20:32,  8.49it/s]

 75%|█████████████████████████▋        | 32067/42525 [1:01:12<20:42,  8.42it/s]

 75%|█████████████████████████▋        | 32069/42525 [1:01:12<22:55,  7.60it/s]

 75%|█████████████████████████▋        | 32071/42525 [1:01:12<20:23,  8.54it/s]

 75%|█████████████████████████▋        | 32075/42525 [1:01:13<18:50,  9.25it/s]

 75%|█████████████████████████▋        | 32079/42525 [1:01:13<17:51,  9.75it/s]

 75%|█████████████████████████▋        | 32082/42525 [1:01:14<18:25,  9.45it/s]

 75%|█████████████████████████▋        | 32085/42525 [1:01:14<18:09,  9.59it/s]

 75%|█████████████████████████▋        | 32087/42525 [1:01:14<21:04,  8.26it/s]

 75%|█████████████████████████▋        | 32090/42525 [1:01:14<19:24,  8.96it/s]

 75%|█████████████████████████▋        | 32092/42525 [1:01:15<20:44,  8.38it/s]

 75%|█████████████████████████▋        | 32094/42525 [1:01:15<19:26,  8.94it/s]

 75%|█████████████████████████▋        | 32095/42525 [1:01:15<19:48,  8.78it/s]

 75%|█████████████████████████▋        | 32098/42525 [1:01:15<19:45,  8.80it/s]

 75%|█████████████████████████▋        | 32100/42525 [1:01:16<19:15,  9.02it/s]

 75%|█████████████████████████▋        | 32103/42525 [1:01:16<18:10,  9.56it/s]

 76%|█████████████████████████▋        | 32107/42525 [1:01:16<17:48,  9.75it/s]

 76%|█████████████████████████▋        | 32111/42525 [1:01:17<17:08, 10.12it/s]

 76%|█████████████████████████▋        | 32115/42525 [1:01:17<17:07, 10.13it/s]

 76%|█████████████████████████▋        | 32118/42525 [1:01:17<19:24,  8.94it/s]

 76%|█████████████████████████▋        | 32121/42525 [1:01:18<18:48,  9.22it/s]

 76%|█████████████████████████▋        | 32123/42525 [1:01:18<18:04,  9.60it/s]

 76%|█████████████████████████▋        | 32127/42525 [1:01:18<18:18,  9.47it/s]

 76%|█████████████████████████▋        | 32131/42525 [1:01:19<17:41,  9.79it/s]

 76%|█████████████████████████▋        | 32133/42525 [1:01:19<18:35,  9.31it/s]

 76%|█████████████████████████▋        | 32134/42525 [1:01:19<19:39,  8.81it/s]

 76%|█████████████████████████▋        | 32138/42525 [1:01:20<19:14,  9.00it/s]

 76%|█████████████████████████▋        | 32141/42525 [1:01:20<19:31,  8.86it/s]

 76%|█████████████████████████▋        | 32143/42525 [1:01:20<20:04,  8.62it/s]

 76%|█████████████████████████▋        | 32145/42525 [1:01:20<20:59,  8.24it/s]

 76%|█████████████████████████▋        | 32148/42525 [1:01:21<19:04,  9.07it/s]

 76%|█████████████████████████▋        | 32151/42525 [1:01:21<19:04,  9.07it/s]

 76%|█████████████████████████▋        | 32153/42525 [1:01:21<18:46,  9.21it/s]

 76%|█████████████████████████▋        | 32155/42525 [1:01:22<20:42,  8.35it/s]

 76%|█████████████████████████▋        | 32159/42525 [1:01:22<18:10,  9.51it/s]

 76%|█████████████████████████▋        | 32161/42525 [1:01:22<20:16,  8.52it/s]

 76%|█████████████████████████▋        | 32163/42525 [1:01:23<22:42,  7.61it/s]

 76%|█████████████████████████▋        | 32165/42525 [1:01:23<22:38,  7.63it/s]

 76%|█████████████████████████▋        | 32167/42525 [1:01:23<20:22,  8.47it/s]

 76%|█████████████████████████▋        | 32170/42525 [1:01:23<21:07,  8.17it/s]

 76%|█████████████████████████▋        | 32173/42525 [1:01:24<19:37,  8.79it/s]

 76%|█████████████████████████▋        | 32177/42525 [1:01:24<17:51,  9.66it/s]

 76%|█████████████████████████▋        | 32179/42525 [1:01:24<18:24,  9.37it/s]

 76%|█████████████████████████▋        | 32183/42525 [1:01:25<18:32,  9.30it/s]

 76%|█████████████████████████▋        | 32185/42525 [1:01:25<17:50,  9.66it/s]

 76%|█████████████████████████▋        | 32187/42525 [1:01:25<17:50,  9.66it/s]

 76%|█████████████████████████▋        | 32189/42525 [1:01:25<17:49,  9.67it/s]

 76%|█████████████████████████▋        | 32193/42525 [1:01:26<18:04,  9.52it/s]

 76%|█████████████████████████▋        | 32196/42525 [1:01:26<20:10,  8.53it/s]

 76%|█████████████████████████▋        | 32200/42525 [1:01:27<18:31,  9.29it/s]

 76%|█████████████████████████▋        | 32203/42525 [1:01:27<18:00,  9.55it/s]

 76%|█████████████████████████▋        | 32205/42525 [1:01:27<19:10,  8.97it/s]

 76%|█████████████████████████▊        | 32208/42525 [1:01:27<19:48,  8.68it/s]

 76%|█████████████████████████▊        | 32211/42525 [1:01:28<18:17,  9.40it/s]

 76%|█████████████████████████▊        | 32214/42525 [1:01:28<20:38,  8.32it/s]

 76%|█████████████████████████▊        | 32216/42525 [1:01:28<20:45,  8.28it/s]

 76%|█████████████████████████▊        | 32219/42525 [1:01:29<20:38,  8.32it/s]

 76%|█████████████████████████▊        | 32220/42525 [1:01:29<20:26,  8.40it/s]

 76%|█████████████████████████▊        | 32222/42525 [1:01:29<19:55,  8.62it/s]

 76%|█████████████████████████▊        | 32226/42525 [1:01:29<18:09,  9.45it/s]

 76%|█████████████████████████▊        | 32229/42525 [1:01:30<20:13,  8.48it/s]

 76%|█████████████████████████▊        | 32231/42525 [1:01:30<19:14,  8.92it/s]

 76%|█████████████████████████▊        | 32235/42525 [1:01:30<17:35,  9.75it/s]

 76%|█████████████████████████▊        | 32238/42525 [1:01:31<18:20,  9.34it/s]

 76%|█████████████████████████▊        | 32240/42525 [1:01:31<19:27,  8.81it/s]

 76%|█████████████████████████▊        | 32243/42525 [1:01:31<20:09,  8.50it/s]

 76%|█████████████████████████▊        | 32246/42525 [1:01:32<19:56,  8.59it/s]

 76%|█████████████████████████▊        | 32248/42525 [1:01:32<21:44,  7.88it/s]

 76%|█████████████████████████▊        | 32251/42525 [1:01:32<20:03,  8.54it/s]

 76%|█████████████████████████▊        | 32253/42525 [1:01:33<21:03,  8.13it/s]

 76%|█████████████████████████▊        | 32254/42525 [1:01:33<20:05,  8.52it/s]

 76%|█████████████████████████▊        | 32257/42525 [1:01:33<21:47,  7.85it/s]

 76%|█████████████████████████▊        | 32260/42525 [1:01:33<19:09,  8.93it/s]

 76%|█████████████████████████▊        | 32263/42525 [1:01:34<17:56,  9.54it/s]

 76%|█████████████████████████▊        | 32266/42525 [1:01:34<17:22,  9.84it/s]

 76%|█████████████████████████▊        | 32267/42525 [1:01:34<17:24,  9.82it/s]

 76%|█████████████████████████▊        | 32270/42525 [1:01:35<20:16,  8.43it/s]

 76%|█████████████████████████▊        | 32272/42525 [1:01:35<19:08,  8.93it/s]

 76%|█████████████████████████▊        | 32275/42525 [1:01:35<18:25,  9.27it/s]

 76%|█████████████████████████▊        | 32276/42525 [1:01:35<18:06,  9.43it/s]

 76%|█████████████████████████▊        | 32279/42525 [1:01:36<19:32,  8.74it/s]

 76%|█████████████████████████▊        | 32281/42525 [1:01:36<18:47,  9.08it/s]

 76%|█████████████████████████▊        | 32282/42525 [1:01:36<18:37,  9.17it/s]

 76%|█████████████████████████▊        | 32284/42525 [1:01:36<19:16,  8.85it/s]

 76%|█████████████████████████▊        | 32288/42525 [1:01:36<17:49,  9.57it/s]

 76%|█████████████████████████▊        | 32291/42525 [1:01:37<17:08,  9.95it/s]

 76%|█████████████████████████▊        | 32294/42525 [1:01:37<18:42,  9.12it/s]

 76%|█████████████████████████▊        | 32297/42525 [1:01:37<18:35,  9.17it/s]

 76%|█████████████████████████▊        | 32300/42525 [1:01:38<17:49,  9.56it/s]

 76%|█████████████████████████▊        | 32303/42525 [1:01:38<17:35,  9.68it/s]

 76%|█████████████████████████▊        | 32305/42525 [1:01:38<20:45,  8.20it/s]

 76%|█████████████████████████▊        | 32309/42525 [1:01:39<19:13,  8.86it/s]

 76%|█████████████████████████▊        | 32312/42525 [1:01:39<19:20,  8.80it/s]

 76%|█████████████████████████▊        | 32313/42525 [1:01:39<20:08,  8.45it/s]

 76%|█████████████████████████▊        | 32316/42525 [1:01:40<19:49,  8.58it/s]

 76%|█████████████████████████▊        | 32318/42525 [1:01:40<19:36,  8.67it/s]

 76%|█████████████████████████▊        | 32319/42525 [1:01:40<21:05,  8.07it/s]

 76%|█████████████████████████▊        | 32322/42525 [1:01:40<20:54,  8.13it/s]

 76%|█████████████████████████▊        | 32324/42525 [1:01:41<20:56,  8.12it/s]

 76%|█████████████████████████▊        | 32326/42525 [1:01:41<20:03,  8.47it/s]

 76%|█████████████████████████▊        | 32330/42525 [1:01:41<19:09,  8.87it/s]

 76%|█████████████████████████▊        | 32333/42525 [1:01:42<18:05,  9.39it/s]

 76%|█████████████████████████▊        | 32335/42525 [1:01:42<19:21,  8.77it/s]

 76%|█████████████████████████▊        | 32337/42525 [1:01:42<20:40,  8.21it/s]

 76%|█████████████████████████▊        | 32340/42525 [1:01:42<18:26,  9.20it/s]

 76%|█████████████████████████▊        | 32344/42525 [1:01:43<17:21,  9.77it/s]

 76%|█████████████████████████▊        | 32347/42525 [1:01:43<16:57, 10.00it/s]

 76%|█████████████████████████▊        | 32349/42525 [1:01:43<16:48, 10.09it/s]

 76%|█████████████████████████▊        | 32351/42525 [1:01:44<17:55,  9.46it/s]

 76%|█████████████████████████▊        | 32354/42525 [1:01:44<19:19,  8.77it/s]

 76%|█████████████████████████▊        | 32355/42525 [1:01:44<19:03,  8.89it/s]

 76%|█████████████████████████▊        | 32358/42525 [1:01:44<20:04,  8.44it/s]

 76%|█████████████████████████▊        | 32361/42525 [1:01:45<19:20,  8.76it/s]

 76%|█████████████████████████▉        | 32364/42525 [1:01:45<20:34,  8.23it/s]

 76%|█████████████████████████▉        | 32366/42525 [1:01:45<21:23,  7.91it/s]

 76%|█████████████████████████▉        | 32368/42525 [1:01:46<20:51,  8.11it/s]

 76%|█████████████████████████▉        | 32371/42525 [1:01:46<18:48,  9.00it/s]

 76%|█████████████████████████▉        | 32374/42525 [1:01:46<18:40,  9.06it/s]

 76%|█████████████████████████▉        | 32378/42525 [1:01:47<17:22,  9.73it/s]

 76%|█████████████████████████▉        | 32380/42525 [1:01:47<17:56,  9.42it/s]

 76%|█████████████████████████▉        | 32382/42525 [1:01:47<19:42,  8.58it/s]

 76%|█████████████████████████▉        | 32384/42525 [1:01:47<20:43,  8.15it/s]

 76%|█████████████████████████▉        | 32387/42525 [1:01:48<18:27,  9.16it/s]

 76%|█████████████████████████▉        | 32390/42525 [1:01:48<17:54,  9.43it/s]

 76%|█████████████████████████▉        | 32393/42525 [1:01:48<18:56,  8.92it/s]

 76%|█████████████████████████▉        | 32397/42525 [1:01:49<18:10,  9.29it/s]

 76%|█████████████████████████▉        | 32400/42525 [1:01:49<19:14,  8.77it/s]

 76%|█████████████████████████▉        | 32403/42525 [1:01:49<18:57,  8.90it/s]

 76%|█████████████████████████▉        | 32405/42525 [1:01:50<17:53,  9.43it/s]

 76%|█████████████████████████▉        | 32408/42525 [1:01:50<17:52,  9.43it/s]

 76%|█████████████████████████▉        | 32410/42525 [1:01:50<17:14,  9.78it/s]

 76%|█████████████████████████▉        | 32413/42525 [1:01:50<18:00,  9.36it/s]

 76%|█████████████████████████▉        | 32415/42525 [1:01:51<17:53,  9.41it/s]

 76%|█████████████████████████▉        | 32418/42525 [1:01:51<18:03,  9.33it/s]

 76%|█████████████████████████▉        | 32421/42525 [1:01:51<17:16,  9.75it/s]

 76%|█████████████████████████▉        | 32424/42525 [1:01:52<19:01,  8.85it/s]

 76%|█████████████████████████▉        | 32426/42525 [1:01:52<19:31,  8.62it/s]

 76%|█████████████████████████▉        | 32427/42525 [1:01:52<18:57,  8.88it/s]

 76%|█████████████████████████▉        | 32430/42525 [1:01:52<19:06,  8.81it/s]

 76%|█████████████████████████▉        | 32433/42525 [1:01:53<18:00,  9.34it/s]

 76%|█████████████████████████▉        | 32436/42525 [1:01:53<18:17,  9.19it/s]

 76%|█████████████████████████▉        | 32437/42525 [1:01:53<18:04,  9.30it/s]

 76%|█████████████████████████▉        | 32440/42525 [1:01:53<17:54,  9.38it/s]

 76%|█████████████████████████▉        | 32443/42525 [1:01:54<18:18,  9.17it/s]

 76%|█████████████████████████▉        | 32446/42525 [1:01:54<19:11,  8.75it/s]

 76%|█████████████████████████▉        | 32448/42525 [1:01:54<19:50,  8.46it/s]

 76%|█████████████████████████▉        | 32451/42525 [1:01:55<19:46,  8.49it/s]

 76%|█████████████████████████▉        | 32453/42525 [1:01:55<18:28,  9.09it/s]

 76%|█████████████████████████▉        | 32457/42525 [1:01:55<17:48,  9.42it/s]

 76%|█████████████████████████▉        | 32460/42525 [1:01:56<17:50,  9.41it/s]

 76%|█████████████████████████▉        | 32463/42525 [1:01:56<17:54,  9.36it/s]

 76%|█████████████████████████▉        | 32465/42525 [1:01:56<19:12,  8.73it/s]

 76%|█████████████████████████▉        | 32469/42525 [1:01:57<17:16,  9.70it/s]

 76%|█████████████████████████▉        | 32472/42525 [1:01:57<17:35,  9.53it/s]

 76%|█████████████████████████▉        | 32475/42525 [1:01:57<17:48,  9.40it/s]

 76%|█████████████████████████▉        | 32477/42525 [1:01:58<19:27,  8.61it/s]

 76%|█████████████████████████▉        | 32480/42525 [1:01:58<19:49,  8.45it/s]

 76%|█████████████████████████▉        | 32482/42525 [1:01:58<20:32,  8.15it/s]

 76%|█████████████████████████▉        | 32485/42525 [1:01:58<19:54,  8.41it/s]

 76%|█████████████████████████▉        | 32488/42525 [1:01:59<19:16,  8.68it/s]

 76%|█████████████████████████▉        | 32489/42525 [1:01:59<19:51,  8.43it/s]

 76%|█████████████████████████▉        | 32493/42525 [1:01:59<17:55,  9.33it/s]

 76%|█████████████████████████▉        | 32495/42525 [1:02:00<18:40,  8.95it/s]

 76%|█████████████████████████▉        | 32498/42525 [1:02:00<19:26,  8.60it/s]

 76%|█████████████████████████▉        | 32500/42525 [1:02:00<19:45,  8.45it/s]

 76%|█████████████████████████▉        | 32502/42525 [1:02:00<18:47,  8.89it/s]

 76%|█████████████████████████▉        | 32506/42525 [1:02:01<17:10,  9.72it/s]

 76%|█████████████████████████▉        | 32507/42525 [1:02:01<18:45,  8.90it/s]

 76%|█████████████████████████▉        | 32510/42525 [1:02:01<18:01,  9.26it/s]

 76%|█████████████████████████▉        | 32513/42525 [1:02:02<17:17,  9.65it/s]

 76%|█████████████████████████▉        | 32515/42525 [1:02:02<18:52,  8.84it/s]

 76%|█████████████████████████▉        | 32517/42525 [1:02:02<20:09,  8.28it/s]

 76%|██████████████████████████        | 32520/42525 [1:02:02<18:18,  9.11it/s]

 76%|██████████████████████████        | 32523/42525 [1:02:03<18:09,  9.18it/s]

 76%|██████████████████████████        | 32526/42525 [1:02:03<19:02,  8.75it/s]

 76%|██████████████████████████        | 32528/42525 [1:02:03<19:43,  8.45it/s]

 76%|██████████████████████████        | 32530/42525 [1:02:04<20:23,  8.17it/s]

 77%|██████████████████████████        | 32532/42525 [1:02:04<20:51,  7.98it/s]

 77%|██████████████████████████        | 32535/42525 [1:02:04<20:32,  8.11it/s]

 77%|██████████████████████████        | 32537/42525 [1:02:04<22:09,  7.51it/s]

 77%|██████████████████████████        | 32540/42525 [1:02:05<19:17,  8.63it/s]

 77%|██████████████████████████        | 32543/42525 [1:02:05<18:20,  9.07it/s]

 77%|██████████████████████████        | 32545/42525 [1:02:05<19:03,  8.73it/s]

 77%|██████████████████████████        | 32548/42525 [1:02:06<19:28,  8.54it/s]

 77%|██████████████████████████        | 32551/42525 [1:02:06<18:02,  9.22it/s]

 77%|██████████████████████████        | 32554/42525 [1:02:06<17:15,  9.63it/s]

 77%|██████████████████████████        | 32558/42525 [1:02:07<17:26,  9.52it/s]

 77%|██████████████████████████        | 32561/42525 [1:02:07<18:58,  8.75it/s]

 77%|██████████████████████████        | 32563/42525 [1:02:07<18:17,  9.08it/s]

 77%|██████████████████████████        | 32567/42525 [1:02:08<16:53,  9.83it/s]

 77%|██████████████████████████        | 32570/42525 [1:02:08<16:58,  9.77it/s]

 77%|██████████████████████████        | 32573/42525 [1:02:08<18:51,  8.79it/s]

 77%|██████████████████████████        | 32576/42525 [1:02:09<20:16,  8.18it/s]

 77%|██████████████████████████        | 32579/42525 [1:02:09<18:01,  9.20it/s]

 77%|██████████████████████████        | 32582/42525 [1:02:09<17:22,  9.54it/s]

 77%|██████████████████████████        | 32584/42525 [1:02:09<17:07,  9.67it/s]

 77%|██████████████████████████        | 32588/42525 [1:02:10<16:52,  9.81it/s]

 77%|██████████████████████████        | 32592/42525 [1:02:10<16:20, 10.13it/s]

 77%|██████████████████████████        | 32594/42525 [1:02:10<16:15, 10.18it/s]

 77%|██████████████████████████        | 32598/42525 [1:02:11<16:42,  9.90it/s]

 77%|██████████████████████████        | 32600/42525 [1:02:11<19:30,  8.48it/s]

 77%|██████████████████████████        | 32603/42525 [1:02:12<18:43,  8.83it/s]

 77%|██████████████████████████        | 32607/42525 [1:02:12<18:11,  9.09it/s]

 77%|██████████████████████████        | 32611/42525 [1:02:12<17:00,  9.72it/s]

 77%|██████████████████████████        | 32615/42525 [1:02:13<17:04,  9.67it/s]

 77%|██████████████████████████        | 32619/42525 [1:02:13<16:27, 10.03it/s]

 77%|██████████████████████████        | 32623/42525 [1:02:14<16:08, 10.22it/s]

 77%|██████████████████████████        | 32626/42525 [1:02:14<17:54,  9.21it/s]

 77%|██████████████████████████        | 32630/42525 [1:02:14<16:52,  9.77it/s]

 77%|██████████████████████████        | 32632/42525 [1:02:15<16:55,  9.74it/s]

 77%|██████████████████████████        | 32635/42525 [1:02:15<17:59,  9.16it/s]

 77%|██████████████████████████        | 32637/42525 [1:02:15<19:59,  8.24it/s]

 77%|██████████████████████████        | 32638/42525 [1:02:15<20:59,  7.85it/s]

 77%|██████████████████████████        | 32641/42525 [1:02:16<20:46,  7.93it/s]

 77%|██████████████████████████        | 32644/42525 [1:02:16<18:17,  9.01it/s]

 77%|██████████████████████████        | 32646/42525 [1:02:16<19:16,  8.54it/s]

 77%|██████████████████████████        | 32649/42525 [1:02:17<17:41,  9.31it/s]

 77%|██████████████████████████        | 32651/42525 [1:02:17<18:22,  8.95it/s]

 77%|██████████████████████████        | 32653/42525 [1:02:17<17:18,  9.51it/s]

 77%|██████████████████████████        | 32657/42525 [1:02:17<17:34,  9.36it/s]

 77%|██████████████████████████        | 32659/42525 [1:02:18<17:57,  9.15it/s]

 77%|██████████████████████████        | 32662/42525 [1:02:18<18:44,  8.77it/s]

 77%|██████████████████████████        | 32664/42525 [1:02:18<18:09,  9.05it/s]

 77%|██████████████████████████        | 32666/42525 [1:02:18<17:58,  9.14it/s]

 77%|██████████████████████████        | 32670/42525 [1:02:19<17:46,  9.24it/s]

 77%|██████████████████████████        | 32672/42525 [1:02:19<17:30,  9.38it/s]

 77%|██████████████████████████        | 32674/42525 [1:02:19<20:36,  7.97it/s]

 77%|██████████████████████████▏       | 32677/42525 [1:02:20<18:06,  9.06it/s]

 77%|██████████████████████████▏       | 32681/42525 [1:02:20<16:45,  9.79it/s]

 77%|██████████████████████████▏       | 32685/42525 [1:02:20<16:25,  9.99it/s]

 77%|██████████████████████████▏       | 32687/42525 [1:02:21<16:13, 10.11it/s]

 77%|██████████████████████████▏       | 32691/42525 [1:02:21<16:50,  9.74it/s]

 77%|██████████████████████████▏       | 32692/42525 [1:02:21<18:09,  9.02it/s]

 77%|██████████████████████████▏       | 32695/42525 [1:02:22<18:19,  8.94it/s]

 77%|██████████████████████████▏       | 32697/42525 [1:02:22<18:10,  9.01it/s]

 77%|██████████████████████████▏       | 32700/42525 [1:02:22<17:01,  9.62it/s]

 77%|██████████████████████████▏       | 32703/42525 [1:02:22<17:47,  9.20it/s]

 77%|██████████████████████████▏       | 32706/42525 [1:02:23<17:41,  9.25it/s]

 77%|██████████████████████████▏       | 32707/42525 [1:02:23<19:09,  8.54it/s]

 77%|██████████████████████████▏       | 32710/42525 [1:02:23<18:36,  8.79it/s]

 77%|██████████████████████████▏       | 32713/42525 [1:02:24<19:07,  8.55it/s]

 77%|██████████████████████████▏       | 32716/42525 [1:02:24<18:31,  8.83it/s]

 77%|██████████████████████████▏       | 32718/42525 [1:02:24<19:19,  8.46it/s]

 77%|██████████████████████████▏       | 32721/42525 [1:02:24<17:48,  9.18it/s]

 77%|██████████████████████████▏       | 32725/42525 [1:02:25<16:37,  9.82it/s]

 77%|██████████████████████████▏       | 32728/42525 [1:02:25<16:33,  9.86it/s]

 77%|██████████████████████████▏       | 32729/42525 [1:02:25<16:33,  9.86it/s]

 77%|██████████████████████████▏       | 32732/42525 [1:02:26<19:02,  8.57it/s]

 77%|██████████████████████████▏       | 32734/42525 [1:02:26<20:16,  8.05it/s]

 77%|██████████████████████████▏       | 32736/42525 [1:02:26<19:48,  8.24it/s]

 77%|██████████████████████████▏       | 32737/42525 [1:02:26<20:26,  7.98it/s]

 77%|██████████████████████████▏       | 32740/42525 [1:02:27<18:50,  8.66it/s]

 77%|██████████████████████████▏       | 32742/42525 [1:02:27<18:18,  8.91it/s]

 77%|██████████████████████████▏       | 32746/42525 [1:02:27<16:35,  9.82it/s]

 77%|██████████████████████████▏       | 32749/42525 [1:02:27<17:18,  9.41it/s]

 77%|██████████████████████████▏       | 32752/42525 [1:02:28<17:30,  9.31it/s]

 77%|██████████████████████████▏       | 32754/42525 [1:02:28<16:52,  9.65it/s]

 77%|██████████████████████████▏       | 32758/42525 [1:02:28<16:25,  9.91it/s]

 77%|██████████████████████████▏       | 32760/42525 [1:02:29<16:25,  9.90it/s]

 77%|██████████████████████████▏       | 32762/42525 [1:02:29<18:56,  8.59it/s]

 77%|██████████████████████████▏       | 32766/42525 [1:02:29<17:12,  9.45it/s]

 77%|██████████████████████████▏       | 32770/42525 [1:02:30<16:18,  9.97it/s]

 77%|██████████████████████████▏       | 32773/42525 [1:02:30<16:19,  9.96it/s]

 77%|██████████████████████████▏       | 32774/42525 [1:02:30<16:29,  9.85it/s]

 77%|██████████████████████████▏       | 32778/42525 [1:02:31<16:45,  9.70it/s]

 77%|██████████████████████████▏       | 32780/42525 [1:02:31<16:29,  9.84it/s]

 77%|██████████████████████████▏       | 32782/42525 [1:02:31<17:32,  9.25it/s]

 77%|██████████████████████████▏       | 32786/42525 [1:02:31<17:02,  9.52it/s]

 77%|██████████████████████████▏       | 32789/42525 [1:02:32<17:57,  9.04it/s]

 77%|██████████████████████████▏       | 32792/42525 [1:02:32<17:08,  9.46it/s]

 77%|██████████████████████████▏       | 32794/42525 [1:02:32<19:37,  8.27it/s]

 77%|██████████████████████████▏       | 32796/42525 [1:02:33<20:04,  8.08it/s]

 77%|██████████████████████████▏       | 32800/42525 [1:02:33<17:30,  9.26it/s]

 77%|██████████████████████████▏       | 32802/42525 [1:02:33<18:22,  8.82it/s]

 77%|██████████████████████████▏       | 32805/42525 [1:02:34<18:33,  8.73it/s]

 77%|██████████████████████████▏       | 32808/42525 [1:02:34<18:09,  8.92it/s]

 77%|██████████████████████████▏       | 32809/42525 [1:02:34<18:22,  8.82it/s]

 77%|██████████████████████████▏       | 32813/42525 [1:02:34<17:39,  9.17it/s]

 77%|██████████████████████████▏       | 32815/42525 [1:02:35<16:56,  9.55it/s]

 77%|██████████████████████████▏       | 32817/42525 [1:02:35<17:52,  9.05it/s]

 77%|██████████████████████████▏       | 32820/42525 [1:02:35<18:36,  8.69it/s]

 77%|██████████████████████████▏       | 32823/42525 [1:02:36<17:50,  9.07it/s]

 77%|██████████████████████████▏       | 32826/42525 [1:02:36<17:04,  9.47it/s]

 77%|██████████████████████████▏       | 32828/42525 [1:02:36<18:38,  8.67it/s]

 77%|██████████████████████████▎       | 32832/42525 [1:02:37<17:53,  9.03it/s]

 77%|██████████████████████████▎       | 32834/42525 [1:02:37<17:51,  9.04it/s]

 77%|██████████████████████████▎       | 32836/42525 [1:02:37<16:55,  9.54it/s]

 77%|██████████████████████████▎       | 32840/42525 [1:02:37<17:16,  9.34it/s]

 77%|██████████████████████████▎       | 32842/42525 [1:02:38<16:42,  9.66it/s]

 77%|██████████████████████████▎       | 32844/42525 [1:02:38<17:41,  9.12it/s]

 77%|██████████████████████████▎       | 32846/42525 [1:02:38<17:19,  9.31it/s]

 77%|██████████████████████████▎       | 32848/42525 [1:02:38<18:05,  8.91it/s]

 77%|██████████████████████████▎       | 32852/42525 [1:02:39<17:42,  9.10it/s]

 77%|██████████████████████████▎       | 32854/42525 [1:02:39<18:49,  8.56it/s]

 77%|██████████████████████████▎       | 32857/42525 [1:02:39<17:39,  9.12it/s]

 77%|██████████████████████████▎       | 32859/42525 [1:02:40<18:28,  8.72it/s]

 77%|██████████████████████████▎       | 32861/42525 [1:02:40<17:58,  8.96it/s]

 77%|██████████████████████████▎       | 32864/42525 [1:02:40<17:04,  9.43it/s]

 77%|██████████████████████████▎       | 32867/42525 [1:02:40<17:21,  9.27it/s]

 77%|██████████████████████████▎       | 32870/42525 [1:02:41<17:17,  9.31it/s]

 77%|██████████████████████████▎       | 32873/42525 [1:02:41<16:43,  9.62it/s]

 77%|██████████████████████████▎       | 32877/42525 [1:02:41<16:04, 10.00it/s]

 77%|██████████████████████████▎       | 32881/42525 [1:02:42<15:45, 10.20it/s]

 77%|██████████████████████████▎       | 32885/42525 [1:02:42<15:47, 10.18it/s]

 77%|██████████████████████████▎       | 32887/42525 [1:02:42<15:34, 10.31it/s]

 77%|██████████████████████████▎       | 32889/42525 [1:02:43<16:00, 10.03it/s]

 77%|██████████████████████████▎       | 32892/42525 [1:02:43<18:06,  8.86it/s]

 77%|██████████████████████████▎       | 32894/42525 [1:02:43<19:08,  8.39it/s]

 77%|██████████████████████████▎       | 32896/42525 [1:02:44<18:22,  8.73it/s]

 77%|██████████████████████████▎       | 32898/42525 [1:02:44<17:34,  9.13it/s]

 77%|██████████████████████████▎       | 32900/42525 [1:02:44<18:04,  8.88it/s]

 77%|██████████████████████████▎       | 32903/42525 [1:02:44<18:40,  8.58it/s]

 77%|██████████████████████████▎       | 32906/42525 [1:02:45<17:30,  9.16it/s]

 77%|██████████████████████████▎       | 32908/42525 [1:02:45<18:50,  8.50it/s]

 77%|██████████████████████████▎       | 32912/42525 [1:02:45<16:51,  9.50it/s]

 77%|██████████████████████████▎       | 32916/42525 [1:02:46<16:10,  9.90it/s]

 77%|██████████████████████████▎       | 32918/42525 [1:02:46<19:02,  8.41it/s]

 77%|██████████████████████████▎       | 32920/42525 [1:02:46<19:20,  8.28it/s]

 77%|██████████████████████████▎       | 32923/42525 [1:02:47<17:14,  9.29it/s]

 77%|██████████████████████████▎       | 32927/42525 [1:02:47<17:10,  9.32it/s]

 77%|██████████████████████████▎       | 32929/42525 [1:02:47<18:18,  8.74it/s]

 77%|██████████████████████████▎       | 32932/42525 [1:02:48<17:31,  9.12it/s]

 77%|██████████████████████████▎       | 32934/42525 [1:02:48<17:06,  9.35it/s]

 77%|██████████████████████████▎       | 32938/42525 [1:02:48<16:31,  9.67it/s]

 77%|██████████████████████████▎       | 32940/42525 [1:02:48<16:30,  9.68it/s]

 77%|██████████████████████████▎       | 32942/42525 [1:02:49<18:33,  8.60it/s]

 77%|██████████████████████████▎       | 32946/42525 [1:02:49<16:39,  9.59it/s]

 77%|██████████████████████████▎       | 32948/42525 [1:02:49<16:10,  9.87it/s]

 77%|██████████████████████████▎       | 32952/42525 [1:02:50<16:42,  9.55it/s]

 77%|██████████████████████████▎       | 32954/42525 [1:02:50<16:13,  9.83it/s]

 78%|██████████████████████████▎       | 32958/42525 [1:02:50<15:54, 10.03it/s]

 78%|██████████████████████████▎       | 32960/42525 [1:02:50<17:41,  9.01it/s]

 78%|██████████████████████████▎       | 32964/42525 [1:02:51<17:24,  9.15it/s]

 78%|██████████████████████████▎       | 32968/42525 [1:02:51<16:28,  9.67it/s]

 78%|██████████████████████████▎       | 32971/42525 [1:02:52<16:07,  9.88it/s]

 78%|██████████████████████████▎       | 32973/42525 [1:02:52<15:48, 10.07it/s]

 78%|██████████████████████████▎       | 32976/42525 [1:02:52<16:20,  9.74it/s]

 78%|██████████████████████████▎       | 32979/42525 [1:02:52<16:08,  9.86it/s]

 78%|██████████████████████████▎       | 32981/42525 [1:02:53<18:01,  8.83it/s]

 78%|██████████████████████████▎       | 32983/42525 [1:02:53<18:40,  8.52it/s]

 78%|██████████████████████████▎       | 32987/42525 [1:02:53<17:35,  9.03it/s]

 78%|██████████████████████████▍       | 32991/42525 [1:02:54<17:23,  9.14it/s]

 78%|██████████████████████████▍       | 32993/42525 [1:02:54<19:37,  8.09it/s]

 78%|██████████████████████████▍       | 32997/42525 [1:02:54<17:07,  9.28it/s]

 78%|██████████████████████████▍       | 32999/42525 [1:02:55<17:54,  8.87it/s]

 78%|██████████████████████████▍       | 33002/42525 [1:02:55<17:34,  9.03it/s]

 78%|██████████████████████████▍       | 33005/42525 [1:02:55<16:42,  9.50it/s]

 78%|██████████████████████████▍       | 33009/42525 [1:02:56<16:12,  9.78it/s]

 78%|██████████████████████████▍       | 33010/42525 [1:02:56<16:27,  9.63it/s]

 78%|██████████████████████████▍       | 33013/42525 [1:02:56<18:47,  8.43it/s]

 78%|██████████████████████████▍       | 33015/42525 [1:02:56<19:28,  8.14it/s]

 78%|██████████████████████████▍       | 33018/42525 [1:02:57<17:43,  8.94it/s]

 78%|██████████████████████████▍       | 33022/42525 [1:02:57<16:19,  9.71it/s]

 78%|██████████████████████████▍       | 33026/42525 [1:02:58<16:31,  9.58it/s]

 78%|██████████████████████████▍       | 33028/42525 [1:02:58<16:05,  9.84it/s]

 78%|██████████████████████████▍       | 33032/42525 [1:02:58<16:38,  9.51it/s]

 78%|██████████████████████████▍       | 33034/42525 [1:02:58<16:41,  9.47it/s]

 78%|██████████████████████████▍       | 33035/42525 [1:02:59<17:10,  9.21it/s]

 78%|██████████████████████████▍       | 33039/42525 [1:02:59<17:03,  9.27it/s]

 78%|██████████████████████████▍       | 33041/42525 [1:02:59<16:29,  9.58it/s]

 78%|██████████████████████████▍       | 33044/42525 [1:03:00<16:34,  9.53it/s]

 78%|██████████████████████████▍       | 33047/42525 [1:03:00<18:13,  8.67it/s]

 78%|██████████████████████████▍       | 33051/42525 [1:03:00<16:28,  9.58it/s]

 78%|██████████████████████████▍       | 33053/42525 [1:03:01<18:13,  8.66it/s]

 78%|██████████████████████████▍       | 33055/42525 [1:03:01<19:06,  8.26it/s]

 78%|██████████████████████████▍       | 33058/42525 [1:03:01<18:25,  8.57it/s]

 78%|██████████████████████████▍       | 33060/42525 [1:03:01<20:40,  7.63it/s]

 78%|██████████████████████████▍       | 33062/42525 [1:03:02<19:28,  8.10it/s]

 78%|██████████████████████████▍       | 33066/42525 [1:03:02<16:55,  9.32it/s]

 78%|██████████████████████████▍       | 33069/42525 [1:03:02<16:26,  9.58it/s]

 78%|██████████████████████████▍       | 33071/42525 [1:03:03<17:30,  9.00it/s]

 78%|██████████████████████████▍       | 33073/42525 [1:03:03<18:01,  8.74it/s]

 78%|██████████████████████████▍       | 33075/42525 [1:03:03<16:56,  9.30it/s]

 78%|██████████████████████████▍       | 33078/42525 [1:03:03<18:03,  8.72it/s]

 78%|██████████████████████████▍       | 33082/42525 [1:03:04<16:27,  9.56it/s]

 78%|██████████████████████████▍       | 33086/42525 [1:03:04<15:44, 10.00it/s]

 78%|██████████████████████████▍       | 33088/42525 [1:03:04<16:01,  9.81it/s]

 78%|██████████████████████████▍       | 33090/42525 [1:03:05<17:49,  8.83it/s]

 78%|██████████████████████████▍       | 33094/42525 [1:03:05<17:19,  9.07it/s]

 78%|██████████████████████████▍       | 33096/42525 [1:03:05<18:45,  8.38it/s]

 78%|██████████████████████████▍       | 33099/42525 [1:03:06<17:13,  9.12it/s]

 78%|██████████████████████████▍       | 33101/42525 [1:03:06<17:16,  9.09it/s]

 78%|██████████████████████████▍       | 33102/42525 [1:03:06<17:39,  8.89it/s]

 78%|██████████████████████████▍       | 33106/42525 [1:03:06<17:17,  9.08it/s]

 78%|██████████████████████████▍       | 33109/42525 [1:03:07<17:23,  9.02it/s]

 78%|██████████████████████████▍       | 33110/42525 [1:03:07<17:35,  8.92it/s]

 78%|██████████████████████████▍       | 33113/42525 [1:03:07<17:47,  8.82it/s]

 78%|██████████████████████████▍       | 33117/42525 [1:03:08<16:07,  9.72it/s]

 78%|██████████████████████████▍       | 33121/42525 [1:03:08<15:48,  9.92it/s]

 78%|██████████████████████████▍       | 33124/42525 [1:03:08<16:25,  9.54it/s]

 78%|██████████████████████████▍       | 33126/42525 [1:03:09<16:01,  9.78it/s]

 78%|██████████████████████████▍       | 33129/42525 [1:03:09<16:05,  9.73it/s]

 78%|██████████████████████████▍       | 33131/42525 [1:03:09<16:56,  9.24it/s]

 78%|██████████████████████████▍       | 33133/42525 [1:03:09<16:38,  9.41it/s]

 78%|██████████████████████████▍       | 33137/42525 [1:03:10<15:44,  9.94it/s]

 78%|██████████████████████████▍       | 33139/42525 [1:03:10<17:33,  8.91it/s]

 78%|██████████████████████████▍       | 33142/42525 [1:03:10<17:03,  9.17it/s]

 78%|██████████████████████████▌       | 33145/42525 [1:03:11<17:26,  8.97it/s]

 78%|██████████████████████████▌       | 33148/42525 [1:03:11<16:26,  9.51it/s]

 78%|██████████████████████████▌       | 33150/42525 [1:03:11<18:13,  8.57it/s]

 78%|██████████████████████████▌       | 33153/42525 [1:03:12<17:04,  9.15it/s]

 78%|██████████████████████████▌       | 33155/42525 [1:03:12<17:40,  8.84it/s]

 78%|██████████████████████████▌       | 33157/42525 [1:03:12<17:22,  8.99it/s]

 78%|██████████████████████████▌       | 33159/42525 [1:03:12<16:59,  9.19it/s]

 78%|██████████████████████████▌       | 33161/42525 [1:03:12<18:10,  8.59it/s]

 78%|██████████████████████████▌       | 33163/42525 [1:03:13<17:42,  8.81it/s]

 78%|██████████████████████████▌       | 33165/42525 [1:03:13<16:50,  9.26it/s]

 78%|██████████████████████████▌       | 33167/42525 [1:03:13<16:56,  9.21it/s]

 78%|██████████████████████████▌       | 33169/42525 [1:03:13<17:16,  9.02it/s]

 78%|██████████████████████████▌       | 33171/42525 [1:03:14<19:05,  8.17it/s]

 78%|██████████████████████████▌       | 33173/42525 [1:03:14<18:01,  8.64it/s]

 78%|██████████████████████████▌       | 33175/42525 [1:03:14<18:42,  8.33it/s]

 78%|██████████████████████████▌       | 33176/42525 [1:03:14<18:47,  8.29it/s]

 78%|██████████████████████████▌       | 33179/42525 [1:03:15<19:01,  8.18it/s]

 78%|██████████████████████████▌       | 33181/42525 [1:03:15<18:32,  8.40it/s]

 78%|██████████████████████████▌       | 33183/42525 [1:03:15<17:23,  8.95it/s]

 78%|██████████████████████████▌       | 33185/42525 [1:03:15<19:12,  8.11it/s]

 78%|██████████████████████████▌       | 33187/42525 [1:03:16<20:06,  7.74it/s]

 78%|██████████████████████████▌       | 33188/42525 [1:03:16<20:57,  7.42it/s]

 78%|██████████████████████████▌       | 33192/42525 [1:03:16<18:13,  8.53it/s]

 78%|██████████████████████████▌       | 33193/42525 [1:03:16<18:01,  8.63it/s]

 78%|██████████████████████████▌       | 33195/42525 [1:03:16<17:20,  8.97it/s]

 78%|██████████████████████████▌       | 33198/42525 [1:03:17<18:34,  8.37it/s]

 78%|██████████████████████████▌       | 33199/42525 [1:03:17<18:18,  8.49it/s]

 78%|██████████████████████████▌       | 33201/42525 [1:03:17<17:25,  8.92it/s]

 78%|██████████████████████████▌       | 33204/42525 [1:03:17<17:31,  8.87it/s]

 78%|██████████████████████████▌       | 33205/42525 [1:03:18<17:32,  8.85it/s]

 78%|██████████████████████████▌       | 33208/42525 [1:03:18<16:47,  9.25it/s]

 78%|██████████████████████████▌       | 33212/42525 [1:03:18<15:51,  9.79it/s]

 78%|██████████████████████████▌       | 33214/42525 [1:03:19<18:31,  8.37it/s]

 78%|██████████████████████████▌       | 33215/42525 [1:03:19<17:53,  8.67it/s]

 78%|██████████████████████████▌       | 33218/42525 [1:03:19<18:08,  8.55it/s]

 78%|██████████████████████████▌       | 33221/42525 [1:03:19<16:36,  9.34it/s]

 78%|██████████████████████████▌       | 33223/42525 [1:03:20<16:48,  9.22it/s]

 78%|██████████████████████████▌       | 33225/42525 [1:03:20<17:31,  8.84it/s]

 78%|██████████████████████████▌       | 33228/42525 [1:03:20<16:04,  9.64it/s]

 78%|██████████████████████████▌       | 33231/42525 [1:03:20<15:54,  9.73it/s]

 78%|██████████████████████████▌       | 33234/42525 [1:03:21<16:39,  9.29it/s]

 78%|██████████████████████████▌       | 33236/42525 [1:03:21<16:08,  9.59it/s]

 78%|██████████████████████████▌       | 33239/42525 [1:03:21<17:03,  9.07it/s]

 78%|██████████████████████████▌       | 33242/42525 [1:03:22<16:09,  9.58it/s]

 78%|██████████████████████████▌       | 33244/42525 [1:03:22<17:10,  9.01it/s]

 78%|██████████████████████████▌       | 33246/42525 [1:03:22<16:55,  9.14it/s]

 78%|██████████████████████████▌       | 33249/42525 [1:03:22<17:20,  8.91it/s]

 78%|██████████████████████████▌       | 33251/42525 [1:03:23<17:01,  9.08it/s]

 78%|██████████████████████████▌       | 33253/42525 [1:03:23<16:16,  9.50it/s]

 78%|██████████████████████████▌       | 33256/42525 [1:03:23<17:33,  8.80it/s]

 78%|██████████████████████████▌       | 33260/42525 [1:03:24<16:05,  9.60it/s]

 78%|██████████████████████████▌       | 33262/42525 [1:03:24<16:13,  9.51it/s]

 78%|██████████████████████████▌       | 33264/42525 [1:03:24<17:07,  9.02it/s]

 78%|██████████████████████████▌       | 33267/42525 [1:03:24<18:08,  8.50it/s]

 78%|██████████████████████████▌       | 33269/42525 [1:03:25<17:53,  8.62it/s]

 78%|██████████████████████████▌       | 33272/42525 [1:03:25<17:30,  8.81it/s]

 78%|██████████████████████████▌       | 33275/42525 [1:03:25<18:01,  8.56it/s]

 78%|██████████████████████████▌       | 33278/42525 [1:03:26<16:38,  9.26it/s]

 78%|██████████████████████████▌       | 33280/42525 [1:03:26<15:59,  9.64it/s]

 78%|██████████████████████████▌       | 33282/42525 [1:03:26<16:47,  9.18it/s]

 78%|██████████████████████████▌       | 33286/42525 [1:03:26<16:27,  9.35it/s]

 78%|██████████████████████████▌       | 33288/42525 [1:03:27<17:01,  9.05it/s]

 78%|██████████████████████████▌       | 33290/42525 [1:03:27<16:38,  9.25it/s]

 78%|██████████████████████████▌       | 33292/42525 [1:03:27<16:38,  9.25it/s]

 78%|██████████████████████████▌       | 33294/42525 [1:03:27<16:47,  9.16it/s]

 78%|██████████████████████████▌       | 33297/42525 [1:03:28<17:53,  8.59it/s]

 78%|██████████████████████████▌       | 33299/42525 [1:03:28<19:03,  8.07it/s]

 78%|██████████████████████████▋       | 33301/42525 [1:03:28<18:09,  8.47it/s]

 78%|██████████████████████████▋       | 33305/42525 [1:03:29<15:58,  9.62it/s]

 78%|██████████████████████████▋       | 33308/42525 [1:03:29<15:38,  9.83it/s]

 78%|██████████████████████████▋       | 33310/42525 [1:03:29<15:38,  9.82it/s]

 78%|██████████████████████████▋       | 33312/42525 [1:03:29<16:12,  9.47it/s]

 78%|██████████████████████████▋       | 33314/42525 [1:03:29<16:57,  9.06it/s]

 78%|██████████████████████████▋       | 33316/42525 [1:03:30<20:21,  7.54it/s]

 78%|██████████████████████████▋       | 33318/42525 [1:03:30<19:15,  7.97it/s]

 78%|██████████████████████████▋       | 33320/42525 [1:03:30<17:04,  8.99it/s]

 78%|██████████████████████████▋       | 33324/42525 [1:03:31<16:38,  9.22it/s]

 78%|██████████████████████████▋       | 33327/42525 [1:03:31<18:18,  8.37it/s]

 78%|██████████████████████████▋       | 33329/42525 [1:03:31<18:40,  8.21it/s]

 78%|██████████████████████████▋       | 33331/42525 [1:03:32<18:08,  8.45it/s]

 78%|██████████████████████████▋       | 33333/42525 [1:03:32<18:00,  8.50it/s]

 78%|██████████████████████████▋       | 33335/42525 [1:03:32<18:59,  8.06it/s]

 78%|██████████████████████████▋       | 33338/42525 [1:03:32<16:56,  9.04it/s]

 78%|██████████████████████████▋       | 33340/42525 [1:03:33<16:22,  9.35it/s]

 78%|██████████████████████████▋       | 33342/42525 [1:03:33<16:58,  9.02it/s]

 78%|██████████████████████████▋       | 33345/42525 [1:03:33<17:40,  8.66it/s]

 78%|██████████████████████████▋       | 33347/42525 [1:03:33<18:14,  8.38it/s]

 78%|██████████████████████████▋       | 33349/42525 [1:03:34<17:42,  8.63it/s]

 78%|██████████████████████████▋       | 33350/42525 [1:03:34<17:06,  8.94it/s]

 78%|██████████████████████████▋       | 33353/42525 [1:03:34<17:30,  8.73it/s]

 78%|██████████████████████████▋       | 33354/42525 [1:03:34<17:03,  8.96it/s]

 78%|██████████████████████████▋       | 33357/42525 [1:03:34<17:38,  8.66it/s]

 78%|██████████████████████████▋       | 33359/42525 [1:03:35<16:46,  9.10it/s]

 78%|██████████████████████████▋       | 33361/42525 [1:03:35<17:41,  8.63it/s]

 78%|██████████████████████████▋       | 33363/42525 [1:03:35<17:40,  8.64it/s]

 78%|██████████████████████████▋       | 33365/42525 [1:03:35<16:59,  8.98it/s]

 78%|██████████████████████████▋       | 33367/42525 [1:03:36<18:14,  8.37it/s]

 78%|██████████████████████████▋       | 33369/42525 [1:03:36<17:16,  8.84it/s]

 78%|██████████████████████████▋       | 33372/42525 [1:03:36<17:26,  8.75it/s]

 78%|██████████████████████████▋       | 33374/42525 [1:03:36<18:13,  8.36it/s]

 78%|██████████████████████████▋       | 33376/42525 [1:03:37<17:24,  8.76it/s]

 78%|██████████████████████████▋       | 33378/42525 [1:03:37<18:23,  8.29it/s]

 78%|██████████████████████████▋       | 33380/42525 [1:03:37<20:25,  7.46it/s]

 78%|██████████████████████████▋       | 33382/42525 [1:03:37<19:52,  7.67it/s]

 79%|██████████████████████████▋       | 33384/42525 [1:03:38<20:21,  7.49it/s]

 79%|██████████████████████████▋       | 33386/42525 [1:03:38<19:51,  7.67it/s]

 79%|██████████████████████████▋       | 33388/42525 [1:03:38<18:25,  8.27it/s]

 79%|██████████████████████████▋       | 33390/42525 [1:03:38<19:13,  7.92it/s]

 79%|██████████████████████████▋       | 33392/42525 [1:03:39<19:11,  7.93it/s]

 79%|██████████████████████████▋       | 33394/42525 [1:03:39<18:00,  8.45it/s]

 79%|██████████████████████████▋       | 33396/42525 [1:03:39<17:08,  8.88it/s]

 79%|██████████████████████████▋       | 33398/42525 [1:03:39<16:41,  9.11it/s]

 79%|██████████████████████████▋       | 33400/42525 [1:03:40<16:44,  9.08it/s]

 79%|██████████████████████████▋       | 33402/42525 [1:03:40<18:15,  8.32it/s]

 79%|██████████████████████████▋       | 33404/42525 [1:03:40<19:31,  7.78it/s]

 79%|██████████████████████████▋       | 33406/42525 [1:03:40<18:34,  8.18it/s]

 79%|██████████████████████████▋       | 33408/42525 [1:03:41<17:15,  8.81it/s]

 79%|██████████████████████████▋       | 33410/42525 [1:03:41<18:01,  8.43it/s]

 79%|██████████████████████████▋       | 33413/42525 [1:03:41<16:37,  9.13it/s]

 79%|██████████████████████████▋       | 33415/42525 [1:03:41<18:25,  8.24it/s]

 79%|██████████████████████████▋       | 33417/42525 [1:03:42<17:51,  8.50it/s]

 79%|██████████████████████████▋       | 33419/42525 [1:03:42<17:39,  8.60it/s]

 79%|██████████████████████████▋       | 33421/42525 [1:03:42<16:59,  8.93it/s]

 79%|██████████████████████████▋       | 33423/42525 [1:03:42<16:13,  9.35it/s]

 79%|██████████████████████████▋       | 33426/42525 [1:03:43<16:17,  9.31it/s]

 79%|██████████████████████████▋       | 33428/42525 [1:03:43<16:01,  9.46it/s]

 79%|██████████████████████████▋       | 33430/42525 [1:03:43<17:18,  8.76it/s]

 79%|██████████████████████████▋       | 33432/42525 [1:03:43<18:18,  8.28it/s]

 79%|██████████████████████████▋       | 33434/42525 [1:03:44<17:24,  8.70it/s]

 79%|██████████████████████████▋       | 33436/42525 [1:03:44<19:38,  7.71it/s]

 79%|██████████████████████████▋       | 33438/42525 [1:03:44<19:40,  7.70it/s]

 79%|██████████████████████████▋       | 33440/42525 [1:03:44<20:07,  7.52it/s]

 79%|██████████████████████████▋       | 33442/42525 [1:03:45<18:21,  8.24it/s]

 79%|██████████████████████████▋       | 33444/42525 [1:03:45<17:29,  8.66it/s]

 79%|██████████████████████████▋       | 33446/42525 [1:03:45<17:36,  8.59it/s]

 79%|██████████████████████████▋       | 33448/42525 [1:03:45<17:03,  8.87it/s]

 79%|██████████████████████████▋       | 33450/42525 [1:03:45<18:29,  8.18it/s]

 79%|██████████████████████████▋       | 33452/42525 [1:03:46<17:28,  8.65it/s]

 79%|██████████████████████████▋       | 33454/42525 [1:03:46<17:30,  8.64it/s]

 79%|██████████████████████████▋       | 33456/42525 [1:03:46<17:06,  8.84it/s]

 79%|██████████████████████████▊       | 33458/42525 [1:03:46<16:55,  8.93it/s]

 79%|██████████████████████████▊       | 33460/42525 [1:03:47<16:58,  8.90it/s]

 79%|██████████████████████████▊       | 33462/42525 [1:03:47<16:40,  9.06it/s]

 79%|██████████████████████████▊       | 33464/42525 [1:03:47<16:00,  9.43it/s]

 79%|██████████████████████████▊       | 33466/42525 [1:03:47<16:45,  9.01it/s]

 79%|██████████████████████████▊       | 33468/42525 [1:03:47<15:59,  9.44it/s]

 79%|██████████████████████████▊       | 33471/42525 [1:03:48<16:31,  9.13it/s]

 79%|██████████████████████████▊       | 33473/42525 [1:03:48<17:28,  8.63it/s]

 79%|██████████████████████████▊       | 33474/42525 [1:03:48<16:58,  8.89it/s]

 79%|██████████████████████████▊       | 33477/42525 [1:03:48<16:36,  9.08it/s]

 79%|██████████████████████████▊       | 33479/42525 [1:03:49<17:33,  8.59it/s]

 79%|██████████████████████████▊       | 33481/42525 [1:03:49<17:00,  8.86it/s]

 79%|██████████████████████████▊       | 33482/42525 [1:03:49<16:55,  8.90it/s]

 79%|██████████████████████████▊       | 33484/42525 [1:03:49<16:09,  9.33it/s]

 79%|██████████████████████████▊       | 33487/42525 [1:03:50<16:53,  8.92it/s]

 79%|██████████████████████████▊       | 33489/42525 [1:03:50<18:24,  8.18it/s]

 79%|██████████████████████████▊       | 33491/42525 [1:03:50<18:25,  8.17it/s]

 79%|██████████████████████████▊       | 33493/42525 [1:03:50<18:21,  8.20it/s]

 79%|██████████████████████████▊       | 33495/42525 [1:03:51<18:42,  8.04it/s]

 79%|██████████████████████████▊       | 33497/42525 [1:03:51<17:32,  8.58it/s]

 79%|██████████████████████████▊       | 33499/42525 [1:03:51<18:25,  8.16it/s]

 79%|██████████████████████████▊       | 33500/42525 [1:03:51<19:36,  7.67it/s]

 79%|██████████████████████████▊       | 33503/42525 [1:03:52<19:19,  7.78it/s]

 79%|██████████████████████████▊       | 33505/42525 [1:03:52<19:02,  7.89it/s]

 79%|██████████████████████████▊       | 33508/42525 [1:03:52<18:34,  8.09it/s]

 79%|██████████████████████████▊       | 33510/42525 [1:03:52<18:13,  8.24it/s]

 79%|██████████████████████████▊       | 33512/42525 [1:03:53<18:33,  8.09it/s]

 79%|██████████████████████████▊       | 33514/42525 [1:03:53<18:31,  8.10it/s]

 79%|██████████████████████████▊       | 33516/42525 [1:03:53<20:04,  7.48it/s]

 79%|██████████████████████████▊       | 33518/42525 [1:03:53<19:13,  7.81it/s]

 79%|██████████████████████████▊       | 33519/42525 [1:03:54<19:01,  7.89it/s]

 79%|██████████████████████████▊       | 33523/42525 [1:03:54<16:22,  9.16it/s]

 79%|██████████████████████████▊       | 33526/42525 [1:03:54<16:03,  9.34it/s]

 79%|██████████████████████████▊       | 33528/42525 [1:03:55<17:01,  8.81it/s]

 79%|██████████████████████████▊       | 33531/42525 [1:03:55<17:06,  8.76it/s]

 79%|██████████████████████████▊       | 33533/42525 [1:03:55<18:01,  8.32it/s]

 79%|██████████████████████████▊       | 33536/42525 [1:03:56<17:45,  8.43it/s]

 79%|██████████████████████████▊       | 33538/42525 [1:03:56<19:31,  7.67it/s]

 79%|██████████████████████████▊       | 33540/42525 [1:03:56<18:00,  8.32it/s]

 79%|██████████████████████████▊       | 33542/42525 [1:03:56<17:02,  8.78it/s]

 79%|██████████████████████████▊       | 33544/42525 [1:03:56<16:21,  9.15it/s]

 79%|██████████████████████████▊       | 33546/42525 [1:03:57<16:02,  9.33it/s]

 79%|██████████████████████████▊       | 33548/42525 [1:03:57<17:29,  8.56it/s]

 79%|██████████████████████████▊       | 33550/42525 [1:03:57<16:54,  8.85it/s]

 79%|██████████████████████████▊       | 33552/42525 [1:03:57<17:08,  8.73it/s]

 79%|██████████████████████████▊       | 33554/42525 [1:03:58<18:30,  8.08it/s]

 79%|██████████████████████████▊       | 33556/42525 [1:03:58<18:33,  8.05it/s]

 79%|██████████████████████████▊       | 33558/42525 [1:03:58<18:03,  8.27it/s]

 79%|██████████████████████████▊       | 33560/42525 [1:03:58<17:19,  8.62it/s]

 79%|██████████████████████████▊       | 33562/42525 [1:03:59<16:45,  8.92it/s]

 79%|██████████████████████████▊       | 33565/42525 [1:03:59<15:34,  9.59it/s]

 79%|██████████████████████████▊       | 33568/42525 [1:03:59<15:59,  9.34it/s]

 79%|██████████████████████████▊       | 33570/42525 [1:03:59<16:36,  8.99it/s]

 79%|██████████████████████████▊       | 33573/42525 [1:04:00<16:20,  9.13it/s]

 79%|██████████████████████████▊       | 33574/42525 [1:04:00<17:10,  8.69it/s]

 79%|██████████████████████████▊       | 33577/42525 [1:04:00<16:10,  9.22it/s]

 79%|██████████████████████████▊       | 33579/42525 [1:04:00<15:48,  9.43it/s]

 79%|██████████████████████████▊       | 33581/42525 [1:04:01<15:47,  9.44it/s]

 79%|██████████████████████████▊       | 33583/42525 [1:04:01<16:13,  9.19it/s]

 79%|██████████████████████████▊       | 33585/42525 [1:04:01<17:18,  8.61it/s]

 79%|██████████████████████████▊       | 33587/42525 [1:04:01<17:24,  8.56it/s]

 79%|██████████████████████████▊       | 33589/42525 [1:04:02<17:22,  8.58it/s]

 79%|██████████████████████████▊       | 33591/42525 [1:04:02<16:21,  9.11it/s]

 79%|██████████████████████████▊       | 33594/42525 [1:04:02<15:32,  9.58it/s]

 79%|██████████████████████████▊       | 33596/42525 [1:04:02<15:44,  9.46it/s]

 79%|██████████████████████████▊       | 33599/42525 [1:04:03<15:45,  9.44it/s]

 79%|██████████████████████████▊       | 33601/42525 [1:04:03<16:30,  9.01it/s]

 79%|██████████████████████████▊       | 33603/42525 [1:04:03<17:58,  8.27it/s]

 79%|██████████████████████████▊       | 33605/42525 [1:04:03<18:49,  7.90it/s]

 79%|██████████████████████████▊       | 33607/42525 [1:04:04<17:53,  8.30it/s]

 79%|██████████████████████████▊       | 33609/42525 [1:04:04<17:01,  8.73it/s]

 79%|██████████████████████████▊       | 33611/42525 [1:04:04<18:18,  8.12it/s]

 79%|██████████████████████████▊       | 33613/42525 [1:04:04<16:58,  8.75it/s]

 79%|██████████████████████████▉       | 33614/42525 [1:04:04<17:55,  8.28it/s]

 79%|██████████████████████████▉       | 33616/42525 [1:04:05<16:38,  8.92it/s]

 79%|██████████████████████████▉       | 33619/42525 [1:04:05<16:17,  9.11it/s]

 79%|██████████████████████████▉       | 33620/42525 [1:04:05<16:24,  9.05it/s]

 79%|██████████████████████████▉       | 33623/42525 [1:04:05<16:25,  9.04it/s]

 79%|██████████████████████████▉       | 33626/42525 [1:04:06<15:41,  9.45it/s]

 79%|██████████████████████████▉       | 33627/42525 [1:04:06<17:14,  8.60it/s]

 79%|██████████████████████████▉       | 33629/42525 [1:04:06<17:39,  8.39it/s]

 79%|██████████████████████████▉       | 33633/42525 [1:04:06<15:45,  9.40it/s]

 79%|██████████████████████████▉       | 33636/42525 [1:04:07<16:04,  9.22it/s]

 79%|██████████████████████████▉       | 33639/42525 [1:04:07<15:31,  9.54it/s]

 79%|██████████████████████████▉       | 33641/42525 [1:04:07<15:42,  9.43it/s]

 79%|██████████████████████████▉       | 33644/42525 [1:04:08<17:56,  8.25it/s]

 79%|██████████████████████████▉       | 33647/42525 [1:04:08<15:45,  9.39it/s]

 79%|██████████████████████████▉       | 33651/42525 [1:04:08<15:00,  9.85it/s]

 79%|██████████████████████████▉       | 33653/42525 [1:04:09<16:24,  9.01it/s]

 79%|██████████████████████████▉       | 33655/42525 [1:04:09<16:13,  9.12it/s]

 79%|██████████████████████████▉       | 33658/42525 [1:04:09<15:18,  9.65it/s]

 79%|██████████████████████████▉       | 33662/42525 [1:04:10<15:14,  9.69it/s]

 79%|██████████████████████████▉       | 33666/42525 [1:04:10<14:40, 10.06it/s]

 79%|██████████████████████████▉       | 33670/42525 [1:04:10<15:12,  9.71it/s]

 79%|██████████████████████████▉       | 33672/42525 [1:04:11<16:40,  8.85it/s]

 79%|██████████████████████████▉       | 33675/42525 [1:04:11<16:03,  9.18it/s]

 79%|██████████████████████████▉       | 33678/42525 [1:04:11<15:05,  9.78it/s]

 79%|██████████████████████████▉       | 33680/42525 [1:04:12<16:48,  8.77it/s]

 79%|██████████████████████████▉       | 33682/42525 [1:04:12<16:45,  8.80it/s]

 79%|██████████████████████████▉       | 33684/42525 [1:04:12<16:19,  9.02it/s]

 79%|██████████████████████████▉       | 33686/42525 [1:04:12<15:56,  9.24it/s]

 79%|██████████████████████████▉       | 33688/42525 [1:04:12<17:52,  8.24it/s]

 79%|██████████████████████████▉       | 33690/42525 [1:04:13<17:51,  8.25it/s]

 79%|██████████████████████████▉       | 33692/42525 [1:04:13<18:18,  8.04it/s]

 79%|██████████████████████████▉       | 33694/42525 [1:04:13<17:00,  8.66it/s]

 79%|██████████████████████████▉       | 33696/42525 [1:04:13<16:23,  8.98it/s]

 79%|██████████████████████████▉       | 33698/42525 [1:04:14<17:27,  8.43it/s]

 79%|██████████████████████████▉       | 33700/42525 [1:04:14<17:13,  8.54it/s]

 79%|██████████████████████████▉       | 33702/42525 [1:04:14<16:30,  8.90it/s]

 79%|██████████████████████████▉       | 33704/42525 [1:04:14<15:44,  9.34it/s]

 79%|██████████████████████████▉       | 33705/42525 [1:04:14<17:34,  8.37it/s]

 79%|██████████████████████████▉       | 33707/42525 [1:04:15<16:21,  8.98it/s]

 79%|██████████████████████████▉       | 33710/42525 [1:04:15<17:12,  8.53it/s]

 79%|██████████████████████████▉       | 33712/42525 [1:04:15<16:16,  9.03it/s]

 79%|██████████████████████████▉       | 33714/42525 [1:04:16<18:22,  7.99it/s]

 79%|██████████████████████████▉       | 33717/42525 [1:04:16<17:23,  8.44it/s]

 79%|██████████████████████████▉       | 33719/42525 [1:04:16<16:48,  8.73it/s]

 79%|██████████████████████████▉       | 33721/42525 [1:04:16<18:34,  7.90it/s]

 79%|██████████████████████████▉       | 33723/42525 [1:04:17<18:48,  7.80it/s]

 79%|██████████████████████████▉       | 33725/42525 [1:04:17<16:59,  8.63it/s]

 79%|██████████████████████████▉       | 33727/42525 [1:04:17<18:25,  7.96it/s]

 79%|██████████████████████████▉       | 33728/42525 [1:04:17<19:25,  7.55it/s]

 79%|██████████████████████████▉       | 33731/42525 [1:04:18<18:14,  8.04it/s]

 79%|██████████████████████████▉       | 33733/42525 [1:04:18<17:14,  8.50it/s]

 79%|██████████████████████████▉       | 33735/42525 [1:04:18<18:23,  7.97it/s]

 79%|██████████████████████████▉       | 33737/42525 [1:04:18<16:50,  8.69it/s]

 79%|██████████████████████████▉       | 33739/42525 [1:04:19<16:10,  9.05it/s]

 79%|██████████████████████████▉       | 33741/42525 [1:04:19<16:36,  8.81it/s]

 79%|██████████████████████████▉       | 33744/42525 [1:04:19<15:46,  9.28it/s]

 79%|██████████████████████████▉       | 33746/42525 [1:04:19<15:28,  9.46it/s]

 79%|██████████████████████████▉       | 33749/42525 [1:04:20<15:17,  9.57it/s]

 79%|██████████████████████████▉       | 33751/42525 [1:04:20<16:37,  8.80it/s]

 79%|██████████████████████████▉       | 33752/42525 [1:04:20<18:02,  8.11it/s]

 79%|██████████████████████████▉       | 33754/42525 [1:04:20<16:39,  8.78it/s]

 79%|██████████████████████████▉       | 33757/42525 [1:04:20<15:41,  9.32it/s]

 79%|██████████████████████████▉       | 33760/42525 [1:04:21<15:28,  9.44it/s]

 79%|██████████████████████████▉       | 33763/42525 [1:04:21<16:12,  9.01it/s]

 79%|██████████████████████████▉       | 33767/42525 [1:04:22<14:45,  9.89it/s]

 79%|███████████████████████████       | 33771/42525 [1:04:22<15:05,  9.66it/s]

 79%|███████████████████████████       | 33773/42525 [1:04:22<16:27,  8.87it/s]

 79%|███████████████████████████       | 33776/42525 [1:04:23<15:55,  9.16it/s]

 79%|███████████████████████████       | 33778/42525 [1:04:23<17:21,  8.40it/s]

 79%|███████████████████████████       | 33780/42525 [1:04:23<17:17,  8.42it/s]

 79%|███████████████████████████       | 33782/42525 [1:04:23<16:19,  8.92it/s]

 79%|███████████████████████████       | 33784/42525 [1:04:23<18:05,  8.05it/s]

 79%|███████████████████████████       | 33786/42525 [1:04:24<18:17,  7.96it/s]

 79%|███████████████████████████       | 33789/42525 [1:04:24<17:37,  8.26it/s]

 79%|███████████████████████████       | 33791/42525 [1:04:24<17:48,  8.17it/s]

 79%|███████████████████████████       | 33793/42525 [1:04:25<18:00,  8.08it/s]

 79%|███████████████████████████       | 33795/42525 [1:04:25<18:44,  7.77it/s]

 79%|███████████████████████████       | 33797/42525 [1:04:25<16:51,  8.63it/s]

 79%|███████████████████████████       | 33800/42525 [1:04:25<15:24,  9.43it/s]

 79%|███████████████████████████       | 33802/42525 [1:04:26<16:08,  9.01it/s]

 79%|███████████████████████████       | 33804/42525 [1:04:26<15:55,  9.13it/s]

 79%|███████████████████████████       | 33806/42525 [1:04:26<15:57,  9.10it/s]

 80%|███████████████████████████       | 33808/42525 [1:04:26<17:52,  8.13it/s]

 80%|███████████████████████████       | 33810/42525 [1:04:27<16:45,  8.67it/s]

 80%|███████████████████████████       | 33812/42525 [1:04:27<18:08,  8.00it/s]

 80%|███████████████████████████       | 33813/42525 [1:04:27<17:56,  8.10it/s]

 80%|███████████████████████████       | 33816/42525 [1:04:27<17:28,  8.31it/s]

 80%|███████████████████████████       | 33818/42525 [1:04:28<18:22,  7.89it/s]

 80%|███████████████████████████       | 33820/42525 [1:04:28<18:36,  7.80it/s]

 80%|███████████████████████████       | 33822/42525 [1:04:28<16:50,  8.61it/s]

 80%|███████████████████████████       | 33824/42525 [1:04:28<18:01,  8.04it/s]

 80%|███████████████████████████       | 33826/42525 [1:04:28<17:02,  8.51it/s]

 80%|███████████████████████████       | 33828/42525 [1:04:29<16:57,  8.55it/s]

 80%|███████████████████████████       | 33830/42525 [1:04:29<16:28,  8.80it/s]

 80%|███████████████████████████       | 33832/42525 [1:04:29<17:53,  8.10it/s]

 80%|███████████████████████████       | 33834/42525 [1:04:29<17:13,  8.41it/s]

 80%|███████████████████████████       | 33836/42525 [1:04:30<16:16,  8.90it/s]

 80%|███████████████████████████       | 33838/42525 [1:04:30<17:28,  8.29it/s]

 80%|███████████████████████████       | 33840/42525 [1:04:30<16:03,  9.02it/s]

 80%|███████████████████████████       | 33842/42525 [1:04:30<15:43,  9.20it/s]

 80%|███████████████████████████       | 33844/42525 [1:04:31<15:13,  9.51it/s]

 80%|███████████████████████████       | 33845/42525 [1:04:31<15:23,  9.39it/s]

 80%|███████████████████████████       | 33848/42525 [1:04:31<15:28,  9.35it/s]

 80%|███████████████████████████       | 33850/42525 [1:04:31<17:23,  8.31it/s]

 80%|███████████████████████████       | 33853/42525 [1:04:32<15:53,  9.09it/s]

 80%|███████████████████████████       | 33855/42525 [1:04:32<17:03,  8.47it/s]

 80%|███████████████████████████       | 33856/42525 [1:04:32<16:30,  8.75it/s]

 80%|███████████████████████████       | 33859/42525 [1:04:32<17:24,  8.30it/s]

 80%|███████████████████████████       | 33861/42525 [1:04:32<16:31,  8.74it/s]

 80%|███████████████████████████       | 33862/42525 [1:04:33<17:47,  8.12it/s]

 80%|███████████████████████████       | 33865/42525 [1:04:33<16:17,  8.85it/s]

 80%|███████████████████████████       | 33868/42525 [1:04:33<16:09,  8.93it/s]

 80%|███████████████████████████       | 33869/42525 [1:04:33<17:26,  8.27it/s]

 80%|███████████████████████████       | 33873/42525 [1:04:34<15:29,  9.31it/s]

 80%|███████████████████████████       | 33875/42525 [1:04:34<16:50,  8.56it/s]

 80%|███████████████████████████       | 33877/42525 [1:04:34<17:07,  8.42it/s]

 80%|███████████████████████████       | 33879/42525 [1:04:35<16:46,  8.59it/s]

 80%|███████████████████████████       | 33881/42525 [1:04:35<17:04,  8.44it/s]

 80%|███████████████████████████       | 33883/42525 [1:04:35<16:21,  8.81it/s]

 80%|███████████████████████████       | 33885/42525 [1:04:35<16:39,  8.64it/s]

 80%|███████████████████████████       | 33886/42525 [1:04:35<16:58,  8.48it/s]

 80%|███████████████████████████       | 33889/42525 [1:04:36<15:45,  9.14it/s]

 80%|███████████████████████████       | 33891/42525 [1:04:36<16:33,  8.69it/s]

 80%|███████████████████████████       | 33893/42525 [1:04:36<17:18,  8.31it/s]

 80%|███████████████████████████       | 33895/42525 [1:04:36<16:50,  8.54it/s]

 80%|███████████████████████████       | 33897/42525 [1:04:37<16:26,  8.74it/s]

 80%|███████████████████████████       | 33899/42525 [1:04:37<18:43,  7.68it/s]

 80%|███████████████████████████       | 33902/42525 [1:04:37<16:03,  8.95it/s]

 80%|███████████████████████████       | 33905/42525 [1:04:38<15:12,  9.45it/s]

 80%|███████████████████████████       | 33906/42525 [1:04:38<15:46,  9.10it/s]

 80%|███████████████████████████       | 33909/42525 [1:04:38<15:36,  9.20it/s]

 80%|███████████████████████████       | 33911/42525 [1:04:38<15:16,  9.40it/s]

 80%|███████████████████████████       | 33913/42525 [1:04:38<14:59,  9.58it/s]

 80%|███████████████████████████       | 33914/42525 [1:04:39<16:44,  8.58it/s]

 80%|███████████████████████████       | 33917/42525 [1:04:39<15:27,  9.28it/s]

 80%|███████████████████████████       | 33920/42525 [1:04:39<15:06,  9.49it/s]

 80%|███████████████████████████       | 33922/42525 [1:04:39<16:10,  8.86it/s]

 80%|███████████████████████████       | 33924/42525 [1:04:40<15:48,  9.07it/s]

 80%|███████████████████████████       | 33925/42525 [1:04:40<15:39,  9.16it/s]

 80%|███████████████████████████▏      | 33927/42525 [1:04:40<15:15,  9.39it/s]

 80%|███████████████████████████▏      | 33931/42525 [1:04:40<14:48,  9.67it/s]

 80%|███████████████████████████▏      | 33934/42525 [1:04:41<15:05,  9.49it/s]

 80%|███████████████████████████▏      | 33937/42525 [1:04:41<15:09,  9.44it/s]

 80%|███████████████████████████▏      | 33939/42525 [1:04:41<15:02,  9.51it/s]

 80%|███████████████████████████▏      | 33940/42525 [1:04:41<15:01,  9.53it/s]

 80%|███████████████████████████▏      | 33943/42525 [1:04:42<16:14,  8.81it/s]

 80%|███████████████████████████▏      | 33946/42525 [1:04:42<15:16,  9.36it/s]

 80%|███████████████████████████▏      | 33948/42525 [1:04:42<15:59,  8.93it/s]

 80%|███████████████████████████▏      | 33950/42525 [1:04:42<15:56,  8.97it/s]

 80%|███████████████████████████▏      | 33952/42525 [1:04:43<15:14,  9.38it/s]

 80%|███████████████████████████▏      | 33955/42525 [1:04:43<15:53,  8.99it/s]

 80%|███████████████████████████▏      | 33957/42525 [1:04:43<17:08,  8.33it/s]

 80%|███████████████████████████▏      | 33959/42525 [1:04:43<17:53,  7.98it/s]

 80%|███████████████████████████▏      | 33961/42525 [1:04:44<16:34,  8.61it/s]

 80%|███████████████████████████▏      | 33964/42525 [1:04:44<16:52,  8.46it/s]

 80%|███████████████████████████▏      | 33966/42525 [1:04:44<16:15,  8.77it/s]

 80%|███████████████████████████▏      | 33968/42525 [1:04:45<17:30,  8.15it/s]

 80%|███████████████████████████▏      | 33970/42525 [1:04:45<17:57,  7.94it/s]

 80%|███████████████████████████▏      | 33972/42525 [1:04:45<18:26,  7.73it/s]

 80%|███████████████████████████▏      | 33974/42525 [1:04:45<17:52,  7.97it/s]

 80%|███████████████████████████▏      | 33977/42525 [1:04:46<16:10,  8.81it/s]

 80%|███████████████████████████▏      | 33979/42525 [1:04:46<17:14,  8.26it/s]

 80%|███████████████████████████▏      | 33981/42525 [1:04:46<17:18,  8.23it/s]

 80%|███████████████████████████▏      | 33982/42525 [1:04:46<16:47,  8.48it/s]

 80%|███████████████████████████▏      | 33985/42525 [1:04:47<17:16,  8.24it/s]

 80%|███████████████████████████▏      | 33988/42525 [1:04:47<15:26,  9.21it/s]

 80%|███████████████████████████▏      | 33991/42525 [1:04:47<15:07,  9.40it/s]

 80%|███████████████████████████▏      | 33994/42525 [1:04:48<15:17,  9.30it/s]

 80%|███████████████████████████▏      | 33997/42525 [1:04:48<15:12,  9.35it/s]

 80%|███████████████████████████▏      | 33998/42525 [1:04:48<15:21,  9.25it/s]

 80%|███████████████████████████▏      | 34001/42525 [1:04:48<14:59,  9.48it/s]

 80%|███████████████████████████▏      | 34003/42525 [1:04:49<16:26,  8.64it/s]

 80%|███████████████████████████▏      | 34006/42525 [1:04:49<16:28,  8.62it/s]

 80%|███████████████████████████▏      | 34008/42525 [1:04:49<16:50,  8.43it/s]

 80%|███████████████████████████▏      | 34010/42525 [1:04:49<16:35,  8.55it/s]

 80%|███████████████████████████▏      | 34012/42525 [1:04:50<16:31,  8.58it/s]

 80%|███████████████████████████▏      | 34014/42525 [1:04:50<16:17,  8.70it/s]

 80%|███████████████████████████▏      | 34016/42525 [1:04:50<16:00,  8.86it/s]

 80%|███████████████████████████▏      | 34018/42525 [1:04:50<16:15,  8.72it/s]

 80%|███████████████████████████▏      | 34020/42525 [1:04:50<15:57,  8.88it/s]

 80%|███████████████████████████▏      | 34022/42525 [1:04:51<17:25,  8.13it/s]

 80%|███████████████████████████▏      | 34024/42525 [1:04:51<16:12,  8.74it/s]

 80%|███████████████████████████▏      | 34026/42525 [1:04:51<15:30,  9.13it/s]

 80%|███████████████████████████▏      | 34028/42525 [1:04:51<16:59,  8.34it/s]

 80%|███████████████████████████▏      | 34031/42525 [1:04:52<15:02,  9.42it/s]

 80%|███████████████████████████▏      | 34033/42525 [1:04:52<15:02,  9.41it/s]

 80%|███████████████████████████▏      | 34037/42525 [1:04:52<14:24,  9.82it/s]

 80%|███████████████████████████▏      | 34040/42525 [1:04:53<14:11,  9.97it/s]

 80%|███████████████████████████▏      | 34042/42525 [1:04:53<14:07, 10.01it/s]

 80%|███████████████████████████▏      | 34046/42525 [1:04:53<14:46,  9.56it/s]

 80%|███████████████████████████▏      | 34049/42525 [1:04:54<15:18,  9.22it/s]

 80%|███████████████████████████▏      | 34052/42525 [1:04:54<14:45,  9.57it/s]

 80%|███████████████████████████▏      | 34054/42525 [1:04:54<16:28,  8.57it/s]

 80%|███████████████████████████▏      | 34056/42525 [1:04:54<17:22,  8.12it/s]

 80%|███████████████████████████▏      | 34058/42525 [1:04:55<17:21,  8.13it/s]

 80%|███████████████████████████▏      | 34060/42525 [1:04:55<17:13,  8.19it/s]

 80%|███████████████████████████▏      | 34063/42525 [1:04:55<15:26,  9.13it/s]

 80%|███████████████████████████▏      | 34065/42525 [1:04:55<15:51,  8.89it/s]

 80%|███████████████████████████▏      | 34068/42525 [1:04:56<14:57,  9.42it/s]

 80%|███████████████████████████▏      | 34070/42525 [1:04:56<15:15,  9.24it/s]

 80%|███████████████████████████▏      | 34072/42525 [1:04:56<16:09,  8.72it/s]

 80%|███████████████████████████▏      | 34074/42525 [1:04:56<16:10,  8.71it/s]

 80%|███████████████████████████▏      | 34076/42525 [1:04:57<15:36,  9.02it/s]

 80%|███████████████████████████▏      | 34077/42525 [1:04:57<15:13,  9.24it/s]

 80%|███████████████████████████▏      | 34080/42525 [1:04:57<17:01,  8.26it/s]

 80%|███████████████████████████▏      | 34082/42525 [1:04:57<17:54,  7.86it/s]

 80%|███████████████████████████▎      | 34084/42525 [1:04:58<17:39,  7.97it/s]

 80%|███████████████████████████▎      | 34086/42525 [1:04:58<16:46,  8.39it/s]

 80%|███████████████████████████▎      | 34088/42525 [1:04:58<15:55,  8.83it/s]

 80%|███████████████████████████▎      | 34090/42525 [1:04:58<15:39,  8.98it/s]

 80%|███████████████████████████▎      | 34092/42525 [1:04:59<17:16,  8.14it/s]

 80%|███████████████████████████▎      | 34094/42525 [1:04:59<17:09,  8.19it/s]

 80%|███████████████████████████▎      | 34097/42525 [1:04:59<17:15,  8.14it/s]

 80%|███████████████████████████▎      | 34099/42525 [1:04:59<17:09,  8.18it/s]

 80%|███████████████████████████▎      | 34101/42525 [1:05:00<18:31,  7.58it/s]

 80%|███████████████████████████▎      | 34104/42525 [1:05:00<17:28,  8.03it/s]

 80%|███████████████████████████▎      | 34106/42525 [1:05:00<16:03,  8.74it/s]

 80%|███████████████████████████▎      | 34109/42525 [1:05:01<15:22,  9.13it/s]

 80%|███████████████████████████▎      | 34111/42525 [1:05:01<15:36,  8.98it/s]

 80%|███████████████████████████▎      | 34114/42525 [1:05:01<16:20,  8.58it/s]

 80%|███████████████████████████▎      | 34115/42525 [1:05:01<15:52,  8.83it/s]

 80%|███████████████████████████▎      | 34118/42525 [1:05:02<16:14,  8.63it/s]

 80%|███████████████████████████▎      | 34120/42525 [1:05:02<17:18,  8.09it/s]

 80%|███████████████████████████▎      | 34122/42525 [1:05:02<18:26,  7.59it/s]

 80%|███████████████████████████▎      | 34124/42525 [1:05:02<16:44,  8.36it/s]

 80%|███████████████████████████▎      | 34126/42525 [1:05:03<17:31,  7.98it/s]

 80%|███████████████████████████▎      | 34128/42525 [1:05:03<16:01,  8.73it/s]

 80%|███████████████████████████▎      | 34131/42525 [1:05:03<16:13,  8.63it/s]

 80%|███████████████████████████▎      | 34133/42525 [1:05:03<17:16,  8.09it/s]

 80%|███████████████████████████▎      | 34134/42525 [1:05:04<17:12,  8.13it/s]

 80%|███████████████████████████▎      | 34137/42525 [1:05:04<17:06,  8.17it/s]

 80%|███████████████████████████▎      | 34140/42525 [1:05:04<15:16,  9.15it/s]

 80%|███████████████████████████▎      | 34142/42525 [1:05:04<14:51,  9.41it/s]

 80%|███████████████████████████▎      | 34144/42525 [1:05:05<14:45,  9.47it/s]

 80%|███████████████████████████▎      | 34146/42525 [1:05:05<14:43,  9.49it/s]

 80%|███████████████████████████▎      | 34148/42525 [1:05:05<14:59,  9.31it/s]

 80%|███████████████████████████▎      | 34150/42525 [1:05:05<14:50,  9.40it/s]

 80%|███████████████████████████▎      | 34152/42525 [1:05:06<14:44,  9.46it/s]

 80%|███████████████████████████▎      | 34154/42525 [1:05:06<16:37,  8.39it/s]

 80%|███████████████████████████▎      | 34157/42525 [1:05:06<15:05,  9.24it/s]

 80%|███████████████████████████▎      | 34159/42525 [1:05:06<14:45,  9.45it/s]

 80%|███████████████████████████▎      | 34161/42525 [1:05:07<15:11,  9.17it/s]

 80%|███████████████████████████▎      | 34163/42525 [1:05:07<15:47,  8.83it/s]

 80%|███████████████████████████▎      | 34165/42525 [1:05:07<16:12,  8.60it/s]

 80%|███████████████████████████▎      | 34167/42525 [1:05:07<16:41,  8.34it/s]

 80%|███████████████████████████▎      | 34169/42525 [1:05:07<15:48,  8.81it/s]

 80%|███████████████████████████▎      | 34171/42525 [1:05:08<15:04,  9.23it/s]

 80%|███████████████████████████▎      | 34173/42525 [1:05:08<15:06,  9.21it/s]

 80%|███████████████████████████▎      | 34175/42525 [1:05:08<15:28,  8.99it/s]

 80%|███████████████████████████▎      | 34177/42525 [1:05:08<16:20,  8.51it/s]

 80%|███████████████████████████▎      | 34179/42525 [1:05:09<15:58,  8.71it/s]

 80%|███████████████████████████▎      | 34181/42525 [1:05:09<18:39,  7.45it/s]

 80%|███████████████████████████▎      | 34184/42525 [1:05:09<16:32,  8.40it/s]

 80%|███████████████████████████▎      | 34186/42525 [1:05:09<17:28,  7.95it/s]

 80%|███████████████████████████▎      | 34188/42525 [1:05:10<18:58,  7.32it/s]

 80%|███████████████████████████▎      | 34190/42525 [1:05:10<18:44,  7.41it/s]

 80%|███████████████████████████▎      | 34192/42525 [1:05:10<18:32,  7.49it/s]

 80%|███████████████████████████▎      | 34194/42525 [1:05:11<18:28,  7.51it/s]

 80%|███████████████████████████▎      | 34196/42525 [1:05:11<17:29,  7.93it/s]

 80%|███████████████████████████▎      | 34198/42525 [1:05:11<17:12,  8.06it/s]

 80%|███████████████████████████▎      | 34200/42525 [1:05:11<16:30,  8.40it/s]

 80%|███████████████████████████▎      | 34203/42525 [1:05:12<16:25,  8.45it/s]

 80%|███████████████████████████▎      | 34205/42525 [1:05:12<15:23,  9.01it/s]

 80%|███████████████████████████▎      | 34207/42525 [1:05:12<15:23,  9.01it/s]

 80%|███████████████████████████▎      | 34209/42525 [1:05:12<14:54,  9.29it/s]

 80%|███████████████████████████▎      | 34211/42525 [1:05:13<16:41,  8.30it/s]

 80%|███████████████████████████▎      | 34213/42525 [1:05:13<16:09,  8.57it/s]

 80%|███████████████████████████▎      | 34215/42525 [1:05:13<15:19,  9.04it/s]

 80%|███████████████████████████▎      | 34217/42525 [1:05:13<16:53,  8.20it/s]

 80%|███████████████████████████▎      | 34219/42525 [1:05:13<17:24,  7.95it/s]

 80%|███████████████████████████▎      | 34221/42525 [1:05:14<17:41,  7.83it/s]

 80%|███████████████████████████▎      | 34224/42525 [1:05:14<17:11,  8.05it/s]

 80%|███████████████████████████▎      | 34226/42525 [1:05:14<17:01,  8.12it/s]

 80%|███████████████████████████▎      | 34229/42525 [1:05:15<17:03,  8.10it/s]

 80%|███████████████████████████▎      | 34231/42525 [1:05:15<17:25,  7.93it/s]

 81%|███████████████████████████▎      | 34233/42525 [1:05:15<16:00,  8.64it/s]

 81%|███████████████████████████▎      | 34235/42525 [1:05:15<15:50,  8.72it/s]

 81%|███████████████████████████▎      | 34238/42525 [1:05:16<16:48,  8.22it/s]

 81%|███████████████████████████▍      | 34240/42525 [1:05:16<15:53,  8.69it/s]

 81%|███████████████████████████▍      | 34242/42525 [1:05:16<15:07,  9.13it/s]

 81%|███████████████████████████▍      | 34244/42525 [1:05:16<16:11,  8.52it/s]

 81%|███████████████████████████▍      | 34245/42525 [1:05:17<15:38,  8.82it/s]

 81%|███████████████████████████▍      | 34248/42525 [1:05:17<14:55,  9.24it/s]

 81%|███████████████████████████▍      | 34250/42525 [1:05:17<15:19,  9.00it/s]

 81%|███████████████████████████▍      | 34253/42525 [1:05:17<16:00,  8.61it/s]

 81%|███████████████████████████▍      | 34255/42525 [1:05:18<15:52,  8.68it/s]

 81%|███████████████████████████▍      | 34257/42525 [1:05:18<15:07,  9.11it/s]

 81%|███████████████████████████▍      | 34259/42525 [1:05:18<16:27,  8.37it/s]

 81%|███████████████████████████▍      | 34262/42525 [1:05:18<14:39,  9.39it/s]

 81%|███████████████████████████▍      | 34265/42525 [1:05:19<14:38,  9.40it/s]

 81%|███████████████████████████▍      | 34268/42525 [1:05:19<14:17,  9.63it/s]

 81%|███████████████████████████▍      | 34271/42525 [1:05:19<15:31,  8.87it/s]

 81%|███████████████████████████▍      | 34274/42525 [1:05:20<15:31,  8.86it/s]

 81%|███████████████████████████▍      | 34276/42525 [1:05:20<14:53,  9.24it/s]

 81%|███████████████████████████▍      | 34278/42525 [1:05:20<15:46,  8.71it/s]

 81%|███████████████████████████▍      | 34279/42525 [1:05:20<15:17,  8.98it/s]

 81%|███████████████████████████▍      | 34282/42525 [1:05:21<14:30,  9.46it/s]

 81%|███████████████████████████▍      | 34284/42525 [1:05:21<15:06,  9.10it/s]

 81%|███████████████████████████▍      | 34287/42525 [1:05:21<15:24,  8.91it/s]

 81%|███████████████████████████▍      | 34290/42525 [1:05:22<16:07,  8.51it/s]

 81%|███████████████████████████▍      | 34292/42525 [1:05:22<17:59,  7.63it/s]

 81%|███████████████████████████▍      | 34294/42525 [1:05:22<16:08,  8.50it/s]

 81%|███████████████████████████▍      | 34296/42525 [1:05:22<15:25,  8.89it/s]

 81%|███████████████████████████▍      | 34299/42525 [1:05:23<15:20,  8.93it/s]

 81%|███████████████████████████▍      | 34301/42525 [1:05:23<14:41,  9.33it/s]

 81%|███████████████████████████▍      | 34304/42525 [1:05:23<14:11,  9.65it/s]

 81%|███████████████████████████▍      | 34307/42525 [1:05:23<13:54,  9.85it/s]

 81%|███████████████████████████▍      | 34309/42525 [1:05:24<14:18,  9.57it/s]

 81%|███████████████████████████▍      | 34311/42525 [1:05:24<15:17,  8.96it/s]

 81%|███████████████████████████▍      | 34313/42525 [1:05:24<16:05,  8.50it/s]

 81%|███████████████████████████▍      | 34315/42525 [1:05:24<15:04,  9.07it/s]

 81%|███████████████████████████▍      | 34317/42525 [1:05:24<14:15,  9.60it/s]

 81%|███████████████████████████▍      | 34320/42525 [1:05:25<15:23,  8.89it/s]

 81%|███████████████████████████▍      | 34322/42525 [1:05:25<14:45,  9.26it/s]

 81%|███████████████████████████▍      | 34324/42525 [1:05:25<17:37,  7.76it/s]

 81%|███████████████████████████▍      | 34325/42525 [1:05:25<16:45,  8.16it/s]

 81%|███████████████████████████▍      | 34328/42525 [1:05:26<16:10,  8.45it/s]

 81%|███████████████████████████▍      | 34330/42525 [1:05:26<15:22,  8.88it/s]

 81%|███████████████████████████▍      | 34333/42525 [1:05:26<14:33,  9.37it/s]

 81%|███████████████████████████▍      | 34335/42525 [1:05:27<16:07,  8.47it/s]

 81%|███████████████████████████▍      | 34337/42525 [1:05:27<17:05,  7.99it/s]

 81%|███████████████████████████▍      | 34339/42525 [1:05:27<17:29,  7.80it/s]

 81%|███████████████████████████▍      | 34341/42525 [1:05:27<15:53,  8.59it/s]

 81%|███████████████████████████▍      | 34343/42525 [1:05:28<17:05,  7.98it/s]

 81%|███████████████████████████▍      | 34345/42525 [1:05:28<15:29,  8.80it/s]

 81%|███████████████████████████▍      | 34347/42525 [1:05:28<16:38,  8.19it/s]

 81%|███████████████████████████▍      | 34349/42525 [1:05:28<15:29,  8.80it/s]

 81%|███████████████████████████▍      | 34350/42525 [1:05:28<16:10,  8.42it/s]

 81%|███████████████████████████▍      | 34353/42525 [1:05:29<15:11,  8.96it/s]

 81%|███████████████████████████▍      | 34355/42525 [1:05:29<15:00,  9.08it/s]

 81%|███████████████████████████▍      | 34357/42525 [1:05:29<14:41,  9.26it/s]

 81%|███████████████████████████▍      | 34359/42525 [1:05:29<14:45,  9.22it/s]

 81%|███████████████████████████▍      | 34361/42525 [1:05:30<15:48,  8.61it/s]

 81%|███████████████████████████▍      | 34363/42525 [1:05:30<15:32,  8.75it/s]

 81%|███████████████████████████▍      | 34366/42525 [1:05:30<14:25,  9.42it/s]

 81%|███████████████████████████▍      | 34368/42525 [1:05:30<15:27,  8.79it/s]

 81%|███████████████████████████▍      | 34370/42525 [1:05:31<15:28,  8.78it/s]

 81%|███████████████████████████▍      | 34372/42525 [1:05:31<14:46,  9.20it/s]

 81%|███████████████████████████▍      | 34374/42525 [1:05:31<14:32,  9.34it/s]

 81%|███████████████████████████▍      | 34376/42525 [1:05:31<16:37,  8.17it/s]

 81%|███████████████████████████▍      | 34378/42525 [1:05:31<15:24,  8.82it/s]

 81%|███████████████████████████▍      | 34380/42525 [1:05:32<15:37,  8.69it/s]

 81%|███████████████████████████▍      | 34382/42525 [1:05:32<15:26,  8.79it/s]

 81%|███████████████████████████▍      | 34384/42525 [1:05:32<15:29,  8.76it/s]

 81%|███████████████████████████▍      | 34386/42525 [1:05:32<15:53,  8.53it/s]

 81%|███████████████████████████▍      | 34388/42525 [1:05:33<15:05,  8.99it/s]

 81%|███████████████████████████▍      | 34390/42525 [1:05:33<15:49,  8.57it/s]

 81%|███████████████████████████▍      | 34392/42525 [1:05:33<16:03,  8.44it/s]

 81%|███████████████████████████▍      | 34394/42525 [1:05:33<15:36,  8.68it/s]

 81%|███████████████████████████▌      | 34396/42525 [1:05:34<14:44,  9.19it/s]

 81%|███████████████████████████▌      | 34399/42525 [1:05:34<14:14,  9.51it/s]

 81%|███████████████████████████▌      | 34401/42525 [1:05:34<14:21,  9.43it/s]

 81%|███████████████████████████▌      | 34403/42525 [1:05:34<15:39,  8.65it/s]

 81%|███████████████████████████▌      | 34405/42525 [1:05:35<15:44,  8.60it/s]

 81%|███████████████████████████▌      | 34407/42525 [1:05:35<15:23,  8.79it/s]

 81%|███████████████████████████▌      | 34409/42525 [1:05:35<15:22,  8.80it/s]

 81%|███████████████████████████▌      | 34411/42525 [1:05:35<16:09,  8.37it/s]

 81%|███████████████████████████▌      | 34413/42525 [1:05:36<16:16,  8.31it/s]

 81%|███████████████████████████▌      | 34415/42525 [1:05:36<17:27,  7.74it/s]

 81%|███████████████████████████▌      | 34416/42525 [1:05:36<16:23,  8.24it/s]

 81%|███████████████████████████▌      | 34419/42525 [1:05:36<15:20,  8.81it/s]

 81%|███████████████████████████▌      | 34421/42525 [1:05:36<15:53,  8.50it/s]

 81%|███████████████████████████▌      | 34423/42525 [1:05:37<16:50,  8.02it/s]

 81%|███████████████████████████▌      | 34425/42525 [1:05:37<15:51,  8.51it/s]

 81%|███████████████████████████▌      | 34427/42525 [1:05:37<16:40,  8.09it/s]

 81%|███████████████████████████▌      | 34429/42525 [1:05:37<15:34,  8.66it/s]

 81%|███████████████████████████▌      | 34431/42525 [1:05:38<16:00,  8.43it/s]

 81%|███████████████████████████▌      | 34434/42525 [1:05:38<14:53,  9.06it/s]

 81%|███████████████████████████▌      | 34436/42525 [1:05:38<14:35,  9.24it/s]

 81%|███████████████████████████▌      | 34437/42525 [1:05:38<14:29,  9.30it/s]

 81%|███████████████████████████▌      | 34440/42525 [1:05:39<15:33,  8.66it/s]

 81%|███████████████████████████▌      | 34441/42525 [1:05:39<15:17,  8.81it/s]

 81%|███████████████████████████▌      | 34444/42525 [1:05:39<15:10,  8.87it/s]

 81%|███████████████████████████▌      | 34446/42525 [1:05:39<14:54,  9.03it/s]

 81%|███████████████████████████▌      | 34448/42525 [1:05:40<15:49,  8.51it/s]

 81%|███████████████████████████▌      | 34450/42525 [1:05:40<14:49,  9.08it/s]

 81%|███████████████████████████▌      | 34452/42525 [1:05:40<15:19,  8.78it/s]

 81%|███████████████████████████▌      | 34454/42525 [1:05:40<15:01,  8.96it/s]

 81%|███████████████████████████▌      | 34456/42525 [1:05:41<17:29,  7.69it/s]

 81%|███████████████████████████▌      | 34458/42525 [1:05:41<15:50,  8.49it/s]

 81%|███████████████████████████▌      | 34461/42525 [1:05:41<15:22,  8.75it/s]

 81%|███████████████████████████▌      | 34464/42525 [1:05:41<14:54,  9.01it/s]

 81%|███████████████████████████▌      | 34466/42525 [1:05:42<15:53,  8.45it/s]

 81%|███████████████████████████▌      | 34468/42525 [1:05:42<14:59,  8.96it/s]

 81%|███████████████████████████▌      | 34471/42525 [1:05:42<14:10,  9.47it/s]

 81%|███████████████████████████▌      | 34473/42525 [1:05:42<15:37,  8.59it/s]

 81%|███████████████████████████▌      | 34475/42525 [1:05:43<14:43,  9.11it/s]

 81%|███████████████████████████▌      | 34476/42525 [1:05:43<15:50,  8.46it/s]

 81%|███████████████████████████▌      | 34479/42525 [1:05:43<15:58,  8.39it/s]

 81%|███████████████████████████▌      | 34481/42525 [1:05:43<16:39,  8.05it/s]

 81%|███████████████████████████▌      | 34483/42525 [1:05:44<16:43,  8.02it/s]

 81%|███████████████████████████▌      | 34486/42525 [1:05:44<14:33,  9.20it/s]

 81%|███████████████████████████▌      | 34488/42525 [1:05:44<14:35,  9.18it/s]

 81%|███████████████████████████▌      | 34490/42525 [1:05:44<14:10,  9.45it/s]

 81%|███████████████████████████▌      | 34493/42525 [1:05:45<14:30,  9.23it/s]

 81%|███████████████████████████▌      | 34496/42525 [1:05:45<13:48,  9.69it/s]

 81%|███████████████████████████▌      | 34497/42525 [1:05:45<13:45,  9.73it/s]

 81%|███████████████████████████▌      | 34501/42525 [1:05:45<13:25,  9.97it/s]

 81%|███████████████████████████▌      | 34503/42525 [1:05:46<13:16, 10.08it/s]

 81%|███████████████████████████▌      | 34507/42525 [1:05:46<13:26,  9.94it/s]

 81%|███████████████████████████▌      | 34510/42525 [1:05:46<14:00,  9.53it/s]

 81%|███████████████████████████▌      | 34513/42525 [1:05:47<14:42,  9.08it/s]

 81%|███████████████████████████▌      | 34515/42525 [1:05:47<16:47,  7.95it/s]

 81%|███████████████████████████▌      | 34517/42525 [1:05:47<17:12,  7.76it/s]

 81%|███████████████████████████▌      | 34518/42525 [1:05:47<16:35,  8.04it/s]

 81%|███████████████████████████▌      | 34520/42525 [1:05:48<16:24,  8.13it/s]

 81%|███████████████████████████▌      | 34522/42525 [1:05:48<15:18,  8.71it/s]

 81%|███████████████████████████▌      | 34525/42525 [1:05:48<15:08,  8.81it/s]

 81%|███████████████████████████▌      | 34527/42525 [1:05:48<14:12,  9.38it/s]

 81%|███████████████████████████▌      | 34529/42525 [1:05:49<14:49,  8.99it/s]

 81%|███████████████████████████▌      | 34532/42525 [1:05:49<14:25,  9.23it/s]

 81%|███████████████████████████▌      | 34534/42525 [1:05:49<16:33,  8.05it/s]

 81%|███████████████████████████▌      | 34536/42525 [1:05:50<15:43,  8.47it/s]

 81%|███████████████████████████▌      | 34538/42525 [1:05:50<15:02,  8.85it/s]

 81%|███████████████████████████▌      | 34540/42525 [1:05:50<14:40,  9.07it/s]

 81%|███████████████████████████▌      | 34542/42525 [1:05:50<14:35,  9.12it/s]

 81%|███████████████████████████▌      | 34544/42525 [1:05:50<14:21,  9.26it/s]

 81%|███████████████████████████▌      | 34547/42525 [1:05:51<14:15,  9.32it/s]

 81%|███████████████████████████▌      | 34549/42525 [1:05:51<15:39,  8.49it/s]

 81%|███████████████████████████▌      | 34551/42525 [1:05:51<14:44,  9.02it/s]

 81%|███████████████████████████▋      | 34554/42525 [1:05:51<13:57,  9.52it/s]

 81%|███████████████████████████▋      | 34556/42525 [1:05:52<13:52,  9.57it/s]

 81%|███████████████████████████▋      | 34558/42525 [1:05:52<13:49,  9.60it/s]

 81%|███████████████████████████▋      | 34560/42525 [1:05:52<14:21,  9.25it/s]

 81%|███████████████████████████▋      | 34562/42525 [1:05:52<14:45,  9.00it/s]

 81%|███████████████████████████▋      | 34563/42525 [1:05:52<16:08,  8.22it/s]

 81%|███████████████████████████▋      | 34566/42525 [1:05:53<14:55,  8.89it/s]

 81%|███████████████████████████▋      | 34568/42525 [1:05:53<15:06,  8.78it/s]

 81%|███████████████████████████▋      | 34571/42525 [1:05:53<14:43,  9.01it/s]

 81%|███████████████████████████▋      | 34573/42525 [1:05:54<15:32,  8.53it/s]

 81%|███████████████████████████▋      | 34575/42525 [1:05:54<17:27,  7.59it/s]

 81%|███████████████████████████▋      | 34577/42525 [1:05:54<16:02,  8.26it/s]

 81%|███████████████████████████▋      | 34579/42525 [1:05:54<17:11,  7.70it/s]

 81%|███████████████████████████▋      | 34582/42525 [1:05:55<15:57,  8.29it/s]

 81%|███████████████████████████▋      | 34584/42525 [1:05:55<16:38,  7.95it/s]

 81%|███████████████████████████▋      | 34586/42525 [1:05:55<16:38,  7.95it/s]

 81%|███████████████████████████▋      | 34588/42525 [1:05:55<16:25,  8.05it/s]

 81%|███████████████████████████▋      | 34590/42525 [1:05:56<16:56,  7.80it/s]

 81%|███████████████████████████▋      | 34592/42525 [1:05:56<17:17,  7.65it/s]

 81%|███████████████████████████▋      | 34593/42525 [1:05:56<17:18,  7.64it/s]

 81%|███████████████████████████▋      | 34596/42525 [1:05:56<15:17,  8.64it/s]

 81%|███████████████████████████▋      | 34598/42525 [1:05:57<14:41,  8.99it/s]

 81%|███████████████████████████▋      | 34600/42525 [1:05:57<15:25,  8.56it/s]

 81%|███████████████████████████▋      | 34602/42525 [1:05:57<15:41,  8.42it/s]

 81%|███████████████████████████▋      | 34604/42525 [1:05:57<14:59,  8.81it/s]

 81%|███████████████████████████▋      | 34606/42525 [1:05:58<14:09,  9.33it/s]

 81%|███████████████████████████▋      | 34608/42525 [1:05:58<15:18,  8.62it/s]

 81%|███████████████████████████▋      | 34611/42525 [1:05:58<14:31,  9.08it/s]

 81%|███████████████████████████▋      | 34613/42525 [1:05:58<14:57,  8.82it/s]

 81%|███████████████████████████▋      | 34614/42525 [1:05:59<15:34,  8.47it/s]

 81%|███████████████████████████▋      | 34617/42525 [1:05:59<14:19,  9.20it/s]

 81%|███████████████████████████▋      | 34619/42525 [1:05:59<14:06,  9.34it/s]

 81%|███████████████████████████▋      | 34622/42525 [1:05:59<13:52,  9.49it/s]

 81%|███████████████████████████▋      | 34625/42525 [1:06:00<13:46,  9.56it/s]

 81%|███████████████████████████▋      | 34627/42525 [1:06:00<15:04,  8.73it/s]

 81%|███████████████████████████▋      | 34629/42525 [1:06:00<16:04,  8.19it/s]

 81%|███████████████████████████▋      | 34631/42525 [1:06:00<14:55,  8.81it/s]

 81%|███████████████████████████▋      | 34633/42525 [1:06:01<14:45,  8.91it/s]

 81%|███████████████████████████▋      | 34635/42525 [1:06:01<15:02,  8.74it/s]

 81%|███████████████████████████▋      | 34637/42525 [1:06:01<14:55,  8.81it/s]

 81%|███████████████████████████▋      | 34639/42525 [1:06:01<16:42,  7.86it/s]

 81%|███████████████████████████▋      | 34641/42525 [1:06:02<15:48,  8.31it/s]

 81%|███████████████████████████▋      | 34643/42525 [1:06:02<17:25,  7.54it/s]

 81%|███████████████████████████▋      | 34645/42525 [1:06:02<15:50,  8.29it/s]

 81%|███████████████████████████▋      | 34647/42525 [1:06:02<15:56,  8.24it/s]

 81%|███████████████████████████▋      | 34649/42525 [1:06:03<15:58,  8.22it/s]

 81%|███████████████████████████▋      | 34651/42525 [1:06:03<16:16,  8.06it/s]

 81%|███████████████████████████▋      | 34653/42525 [1:06:03<18:09,  7.23it/s]

 81%|███████████████████████████▋      | 34655/42525 [1:06:03<16:01,  8.19it/s]

 81%|███████████████████████████▋      | 34657/42525 [1:06:04<16:07,  8.13it/s]

 82%|███████████████████████████▋      | 34659/42525 [1:06:04<14:48,  8.85it/s]

 82%|███████████████████████████▋      | 34661/42525 [1:06:04<14:44,  8.89it/s]

 82%|███████████████████████████▋      | 34663/42525 [1:06:04<14:07,  9.28it/s]

 82%|███████████████████████████▋      | 34666/42525 [1:06:05<13:25,  9.76it/s]

 82%|███████████████████████████▋      | 34668/42525 [1:06:05<14:51,  8.81it/s]

 82%|███████████████████████████▋      | 34671/42525 [1:06:05<15:23,  8.51it/s]

 82%|███████████████████████████▋      | 34673/42525 [1:06:05<14:57,  8.75it/s]

 82%|███████████████████████████▋      | 34675/42525 [1:06:06<14:28,  9.04it/s]

 82%|███████████████████████████▋      | 34678/42525 [1:06:06<14:18,  9.14it/s]

 82%|███████████████████████████▋      | 34680/42525 [1:06:06<14:37,  8.94it/s]

 82%|███████████████████████████▋      | 34682/42525 [1:06:06<14:32,  8.99it/s]

 82%|███████████████████████████▋      | 34684/42525 [1:06:07<15:21,  8.51it/s]

 82%|███████████████████████████▋      | 34686/42525 [1:06:07<14:44,  8.86it/s]

 82%|███████████████████████████▋      | 34689/42525 [1:06:07<13:52,  9.41it/s]

 82%|███████████████████████████▋      | 34690/42525 [1:06:07<13:48,  9.46it/s]

 82%|███████████████████████████▋      | 34693/42525 [1:06:08<13:43,  9.52it/s]

 82%|███████████████████████████▋      | 34695/42525 [1:06:08<15:28,  8.44it/s]

 82%|███████████████████████████▋      | 34697/42525 [1:06:08<14:39,  8.90it/s]

 82%|███████████████████████████▋      | 34699/42525 [1:06:08<15:10,  8.60it/s]

 82%|███████████████████████████▋      | 34701/42525 [1:06:09<15:40,  8.32it/s]

 82%|███████████████████████████▋      | 34703/42525 [1:06:09<15:12,  8.57it/s]

 82%|███████████████████████████▋      | 34705/42525 [1:06:09<14:31,  8.97it/s]

 82%|███████████████████████████▋      | 34707/42525 [1:06:09<15:46,  8.26it/s]

 82%|███████████████████████████▊      | 34709/42525 [1:06:09<15:03,  8.65it/s]

 82%|███████████████████████████▊      | 34712/42525 [1:06:10<14:02,  9.27it/s]

 82%|███████████████████████████▊      | 34714/42525 [1:06:10<13:39,  9.53it/s]

 82%|███████████████████████████▊      | 34716/42525 [1:06:10<15:33,  8.36it/s]

 82%|███████████████████████████▊      | 34718/42525 [1:06:10<14:47,  8.80it/s]

 82%|███████████████████████████▊      | 34720/42525 [1:06:11<14:10,  9.18it/s]

 82%|███████████████████████████▊      | 34722/42525 [1:06:11<14:03,  9.25it/s]

 82%|███████████████████████████▊      | 34724/42525 [1:06:11<14:09,  9.18it/s]

 82%|███████████████████████████▊      | 34726/42525 [1:06:11<14:46,  8.80it/s]

 82%|███████████████████████████▊      | 34728/42525 [1:06:12<15:17,  8.50it/s]

 82%|███████████████████████████▊      | 34730/42525 [1:06:12<15:04,  8.62it/s]

 82%|███████████████████████████▊      | 34732/42525 [1:06:12<17:22,  7.47it/s]

 82%|███████████████████████████▊      | 34735/42525 [1:06:12<14:52,  8.73it/s]

 82%|███████████████████████████▊      | 34738/42525 [1:06:13<13:49,  9.39it/s]

 82%|███████████████████████████▊      | 34742/42525 [1:06:13<13:19,  9.74it/s]

 82%|███████████████████████████▊      | 34744/42525 [1:06:13<13:44,  9.44it/s]

 82%|███████████████████████████▊      | 34746/42525 [1:06:14<13:33,  9.56it/s]

 82%|███████████████████████████▊      | 34748/42525 [1:06:14<15:41,  8.26it/s]

 82%|███████████████████████████▊      | 34751/42525 [1:06:14<15:03,  8.61it/s]

 82%|███████████████████████████▊      | 34753/42525 [1:06:14<14:20,  9.04it/s]

 82%|███████████████████████████▊      | 34755/42525 [1:06:15<15:42,  8.24it/s]

 82%|███████████████████████████▊      | 34757/42525 [1:06:15<14:40,  8.82it/s]

 82%|███████████████████████████▊      | 34759/42525 [1:06:15<14:03,  9.20it/s]

 82%|███████████████████████████▊      | 34761/42525 [1:06:15<14:05,  9.18it/s]

 82%|███████████████████████████▊      | 34763/42525 [1:06:15<13:42,  9.44it/s]

 82%|███████████████████████████▊      | 34765/42525 [1:06:16<14:17,  9.05it/s]

 82%|███████████████████████████▊      | 34767/42525 [1:06:16<14:12,  9.10it/s]

 82%|███████████████████████████▊      | 34769/42525 [1:06:16<15:21,  8.42it/s]

 82%|███████████████████████████▊      | 34771/42525 [1:06:16<15:40,  8.24it/s]

 82%|███████████████████████████▊      | 34773/42525 [1:06:17<15:59,  8.08it/s]

 82%|███████████████████████████▊      | 34775/42525 [1:06:17<14:51,  8.69it/s]

 82%|███████████████████████████▊      | 34777/42525 [1:06:17<14:07,  9.14it/s]

 82%|███████████████████████████▊      | 34779/42525 [1:06:17<13:46,  9.37it/s]

 82%|███████████████████████████▊      | 34782/42525 [1:06:18<13:23,  9.64it/s]

 82%|███████████████████████████▊      | 34784/42525 [1:06:18<14:35,  8.84it/s]

 82%|███████████████████████████▊      | 34786/42525 [1:06:18<14:40,  8.79it/s]

 82%|███████████████████████████▊      | 34788/42525 [1:06:18<14:47,  8.72it/s]

 82%|███████████████████████████▊      | 34791/42525 [1:06:19<13:43,  9.39it/s]

 82%|███████████████████████████▊      | 34793/42525 [1:06:19<14:21,  8.97it/s]

 82%|███████████████████████████▊      | 34796/42525 [1:06:19<13:54,  9.26it/s]

 82%|███████████████████████████▊      | 34798/42525 [1:06:19<14:46,  8.72it/s]

 82%|███████████████████████████▊      | 34800/42525 [1:06:20<15:12,  8.46it/s]

 82%|███████████████████████████▊      | 34802/42525 [1:06:20<14:54,  8.63it/s]

 82%|███████████████████████████▊      | 34804/42525 [1:06:20<14:03,  9.15it/s]

 82%|███████████████████████████▊      | 34806/42525 [1:06:20<15:58,  8.05it/s]

 82%|███████████████████████████▊      | 34808/42525 [1:06:21<16:51,  7.63it/s]

 82%|███████████████████████████▊      | 34810/42525 [1:06:21<15:01,  8.56it/s]

 82%|███████████████████████████▊      | 34812/42525 [1:06:21<16:12,  7.93it/s]

 82%|███████████████████████████▊      | 34814/42525 [1:06:21<16:31,  7.78it/s]

 82%|███████████████████████████▊      | 34817/42525 [1:06:22<15:52,  8.09it/s]

 82%|███████████████████████████▊      | 34819/42525 [1:06:22<14:45,  8.70it/s]

 82%|███████████████████████████▊      | 34821/42525 [1:06:22<14:03,  9.13it/s]

 82%|███████████████████████████▊      | 34822/42525 [1:06:22<15:14,  8.43it/s]

 82%|███████████████████████████▊      | 34825/42525 [1:06:23<14:02,  9.14it/s]

 82%|███████████████████████████▊      | 34827/42525 [1:06:23<14:10,  9.05it/s]

 82%|███████████████████████████▊      | 34830/42525 [1:06:23<13:57,  9.18it/s]

 82%|███████████████████████████▊      | 34832/42525 [1:06:23<14:47,  8.67it/s]

 82%|███████████████████████████▊      | 34834/42525 [1:06:24<14:13,  9.02it/s]

 82%|███████████████████████████▊      | 34836/42525 [1:06:24<14:15,  8.99it/s]

 82%|███████████████████████████▊      | 34838/42525 [1:06:24<13:41,  9.36it/s]

 82%|███████████████████████████▊      | 34841/42525 [1:06:24<13:09,  9.73it/s]

 82%|███████████████████████████▊      | 34843/42525 [1:06:25<13:58,  9.16it/s]

 82%|███████████████████████████▊      | 34845/42525 [1:06:25<14:40,  8.72it/s]

 82%|███████████████████████████▊      | 34847/42525 [1:06:25<15:12,  8.41it/s]

 82%|███████████████████████████▊      | 34849/42525 [1:06:25<14:37,  8.75it/s]

 82%|███████████████████████████▊      | 34851/42525 [1:06:26<15:30,  8.25it/s]

 82%|███████████████████████████▊      | 34853/42525 [1:06:26<14:56,  8.56it/s]

 82%|███████████████████████████▊      | 34855/42525 [1:06:26<17:01,  7.51it/s]

 82%|███████████████████████████▊      | 34857/42525 [1:06:26<16:13,  7.88it/s]

 82%|███████████████████████████▊      | 34860/42525 [1:06:27<14:07,  9.05it/s]

 82%|███████████████████████████▊      | 34861/42525 [1:06:27<15:16,  8.36it/s]

 82%|███████████████████████████▊      | 34864/42525 [1:06:27<14:02,  9.09it/s]

 82%|███████████████████████████▉      | 34867/42525 [1:06:27<14:55,  8.56it/s]

 82%|███████████████████████████▉      | 34868/42525 [1:06:28<14:24,  8.85it/s]

 82%|███████████████████████████▉      | 34871/42525 [1:06:28<14:51,  8.59it/s]

 82%|███████████████████████████▉      | 34872/42525 [1:06:28<14:31,  8.78it/s]

 82%|███████████████████████████▉      | 34874/42525 [1:06:28<13:59,  9.12it/s]

 82%|███████████████████████████▉      | 34877/42525 [1:06:29<13:40,  9.32it/s]

 82%|███████████████████████████▉      | 34879/42525 [1:06:29<14:47,  8.62it/s]

 82%|███████████████████████████▉      | 34881/42525 [1:06:29<15:51,  8.03it/s]

 82%|███████████████████████████▉      | 34883/42525 [1:06:29<14:25,  8.83it/s]

 82%|███████████████████████████▉      | 34886/42525 [1:06:30<14:54,  8.54it/s]

 82%|███████████████████████████▉      | 34889/42525 [1:06:30<13:37,  9.34it/s]

 82%|███████████████████████████▉      | 34891/42525 [1:06:30<13:36,  9.35it/s]

 82%|███████████████████████████▉      | 34893/42525 [1:06:30<15:25,  8.25it/s]

 82%|███████████████████████████▉      | 34896/42525 [1:06:31<14:52,  8.55it/s]

 82%|███████████████████████████▉      | 34898/42525 [1:06:31<16:46,  7.58it/s]

 82%|███████████████████████████▉      | 34900/42525 [1:06:31<15:26,  8.23it/s]

 82%|███████████████████████████▉      | 34902/42525 [1:06:31<14:54,  8.53it/s]

 82%|███████████████████████████▉      | 34904/42525 [1:06:32<14:55,  8.51it/s]

 82%|███████████████████████████▉      | 34906/42525 [1:06:32<16:00,  7.93it/s]

 82%|███████████████████████████▉      | 34908/42525 [1:06:32<14:43,  8.62it/s]

 82%|███████████████████████████▉      | 34909/42525 [1:06:32<14:07,  8.99it/s]

 82%|███████████████████████████▉      | 34912/42525 [1:06:33<15:47,  8.04it/s]

 82%|███████████████████████████▉      | 34915/42525 [1:06:33<14:20,  8.84it/s]

 82%|███████████████████████████▉      | 34917/42525 [1:06:33<15:36,  8.13it/s]

 82%|███████████████████████████▉      | 34919/42525 [1:06:33<14:56,  8.48it/s]

 82%|███████████████████████████▉      | 34921/42525 [1:06:34<15:48,  8.02it/s]

 82%|███████████████████████████▉      | 34923/42525 [1:06:34<15:11,  8.34it/s]

 82%|███████████████████████████▉      | 34925/42525 [1:06:34<14:36,  8.67it/s]

 82%|███████████████████████████▉      | 34927/42525 [1:06:34<13:41,  9.25it/s]

 82%|███████████████████████████▉      | 34929/42525 [1:06:35<14:23,  8.80it/s]

 82%|███████████████████████████▉      | 34931/42525 [1:06:35<13:41,  9.24it/s]

 82%|███████████████████████████▉      | 34933/42525 [1:06:35<13:12,  9.58it/s]

 82%|███████████████████████████▉      | 34936/42525 [1:06:35<12:53,  9.81it/s]

 82%|███████████████████████████▉      | 34938/42525 [1:06:36<13:02,  9.70it/s]

 82%|███████████████████████████▉      | 34941/42525 [1:06:36<14:22,  8.79it/s]

 82%|███████████████████████████▉      | 34944/42525 [1:06:36<13:29,  9.36it/s]

 82%|███████████████████████████▉      | 34946/42525 [1:06:37<15:32,  8.13it/s]

 82%|███████████████████████████▉      | 34948/42525 [1:06:37<15:58,  7.90it/s]

 82%|███████████████████████████▉      | 34949/42525 [1:06:37<16:14,  7.77it/s]

 82%|███████████████████████████▉      | 34952/42525 [1:06:37<15:31,  8.13it/s]

 82%|███████████████████████████▉      | 34954/42525 [1:06:37<15:17,  8.26it/s]

 82%|███████████████████████████▉      | 34957/42525 [1:06:38<15:25,  8.18it/s]

 82%|███████████████████████████▉      | 34960/42525 [1:06:38<13:50,  9.11it/s]

 82%|███████████████████████████▉      | 34962/42525 [1:06:38<14:38,  8.61it/s]

 82%|███████████████████████████▉      | 34965/42525 [1:06:39<13:46,  9.15it/s]

 82%|███████████████████████████▉      | 34968/42525 [1:06:39<14:00,  8.99it/s]

 82%|███████████████████████████▉      | 34970/42525 [1:06:39<13:36,  9.25it/s]

 82%|███████████████████████████▉      | 34972/42525 [1:06:39<13:17,  9.47it/s]

 82%|███████████████████████████▉      | 34974/42525 [1:06:40<13:30,  9.32it/s]

 82%|███████████████████████████▉      | 34976/42525 [1:06:40<15:40,  8.03it/s]

 82%|███████████████████████████▉      | 34979/42525 [1:06:40<13:47,  9.12it/s]

 82%|███████████████████████████▉      | 34982/42525 [1:06:41<14:02,  8.95it/s]

 82%|███████████████████████████▉      | 34984/42525 [1:06:41<14:11,  8.86it/s]

 82%|███████████████████████████▉      | 34986/42525 [1:06:41<14:21,  8.75it/s]

 82%|███████████████████████████▉      | 34987/42525 [1:06:41<13:51,  9.06it/s]

 82%|███████████████████████████▉      | 34990/42525 [1:06:42<14:05,  8.91it/s]

 82%|███████████████████████████▉      | 34993/42525 [1:06:42<13:20,  9.41it/s]

 82%|███████████████████████████▉      | 34995/42525 [1:06:42<14:06,  8.90it/s]

 82%|███████████████████████████▉      | 34997/42525 [1:06:42<13:42,  9.15it/s]

 82%|███████████████████████████▉      | 34999/42525 [1:06:43<14:29,  8.66it/s]

 82%|███████████████████████████▉      | 35001/42525 [1:06:43<14:36,  8.59it/s]

 82%|███████████████████████████▉      | 35003/42525 [1:06:43<14:01,  8.94it/s]

 82%|███████████████████████████▉      | 35006/42525 [1:06:43<13:11,  9.50it/s]

 82%|███████████████████████████▉      | 35009/42525 [1:06:44<13:58,  8.96it/s]

 82%|███████████████████████████▉      | 35011/42525 [1:06:44<14:21,  8.72it/s]

 82%|███████████████████████████▉      | 35013/42525 [1:06:44<15:15,  8.20it/s]

 82%|███████████████████████████▉      | 35015/42525 [1:06:44<14:22,  8.71it/s]

 82%|███████████████████████████▉      | 35016/42525 [1:06:44<13:53,  9.01it/s]

 82%|███████████████████████████▉      | 35019/42525 [1:06:45<14:14,  8.78it/s]

 82%|████████████████████████████      | 35021/42525 [1:06:45<14:51,  8.42it/s]

 82%|████████████████████████████      | 35023/42525 [1:06:45<16:08,  7.74it/s]

 82%|████████████████████████████      | 35025/42525 [1:06:46<14:30,  8.62it/s]

 82%|████████████████████████████      | 35027/42525 [1:06:46<14:01,  8.91it/s]

 82%|████████████████████████████      | 35029/42525 [1:06:46<13:44,  9.10it/s]

 82%|████████████████████████████      | 35031/42525 [1:06:46<13:40,  9.14it/s]

 82%|████████████████████████████      | 35034/42525 [1:06:47<13:48,  9.04it/s]

 82%|████████████████████████████      | 35036/42525 [1:06:47<13:35,  9.19it/s]

 82%|████████████████████████████      | 35038/42525 [1:06:47<14:32,  8.58it/s]

 82%|████████████████████████████      | 35040/42525 [1:06:47<14:23,  8.67it/s]

 82%|████████████████████████████      | 35042/42525 [1:06:48<16:46,  7.43it/s]

 82%|████████████████████████████      | 35044/42525 [1:06:48<15:45,  7.91it/s]

 82%|████████████████████████████      | 35046/42525 [1:06:48<14:16,  8.73it/s]

 82%|████████████████████████████      | 35048/42525 [1:06:48<14:43,  8.46it/s]

 82%|████████████████████████████      | 35050/42525 [1:06:48<13:24,  9.29it/s]

 82%|████████████████████████████      | 35053/42525 [1:06:49<13:12,  9.43it/s]

 82%|████████████████████████████      | 35055/42525 [1:06:49<13:33,  9.18it/s]

 82%|████████████████████████████      | 35057/42525 [1:06:49<13:51,  8.99it/s]

 82%|████████████████████████████      | 35059/42525 [1:06:49<13:32,  9.19it/s]

 82%|████████████████████████████      | 35061/42525 [1:06:50<14:55,  8.33it/s]

 82%|████████████████████████████      | 35063/42525 [1:06:50<14:22,  8.65it/s]

 82%|████████████████████████████      | 35065/42525 [1:06:50<16:17,  7.63it/s]

 82%|████████████████████████████      | 35067/42525 [1:06:50<16:25,  7.56it/s]

 82%|████████████████████████████      | 35069/42525 [1:06:51<15:26,  8.05it/s]

 82%|████████████████████████████      | 35071/42525 [1:06:51<14:12,  8.75it/s]

 82%|████████████████████████████      | 35073/42525 [1:06:51<13:40,  9.08it/s]

 82%|████████████████████████████      | 35075/42525 [1:06:51<14:27,  8.59it/s]

 82%|████████████████████████████      | 35077/42525 [1:06:52<14:23,  8.62it/s]

 82%|████████████████████████████      | 35079/42525 [1:06:52<13:32,  9.17it/s]

 82%|████████████████████████████      | 35081/42525 [1:06:52<13:37,  9.11it/s]

 82%|████████████████████████████      | 35083/42525 [1:06:52<14:51,  8.35it/s]

 83%|████████████████████████████      | 35085/42525 [1:06:53<15:37,  7.94it/s]

 83%|████████████████████████████      | 35087/42525 [1:06:53<14:14,  8.71it/s]

 83%|████████████████████████████      | 35090/42525 [1:06:53<13:26,  9.22it/s]

 83%|████████████████████████████      | 35091/42525 [1:06:53<13:14,  9.35it/s]

 83%|████████████████████████████      | 35094/42525 [1:06:53<14:08,  8.76it/s]

 83%|████████████████████████████      | 35098/42525 [1:06:54<12:58,  9.54it/s]

 83%|████████████████████████████      | 35100/42525 [1:06:54<13:14,  9.35it/s]

 83%|████████████████████████████      | 35103/42525 [1:06:54<13:32,  9.13it/s]

 83%|████████████████████████████      | 35105/42525 [1:06:55<14:35,  8.48it/s]

 83%|████████████████████████████      | 35107/42525 [1:06:55<13:34,  9.10it/s]

 83%|████████████████████████████      | 35110/42525 [1:06:55<12:57,  9.54it/s]

 83%|████████████████████████████      | 35112/42525 [1:06:55<13:34,  9.10it/s]

 83%|████████████████████████████      | 35114/42525 [1:06:56<14:09,  8.73it/s]

 83%|████████████████████████████      | 35116/42525 [1:06:56<14:27,  8.54it/s]

 83%|████████████████████████████      | 35118/42525 [1:06:56<16:32,  7.46it/s]

 83%|████████████████████████████      | 35120/42525 [1:06:56<16:40,  7.40it/s]

 83%|████████████████████████████      | 35122/42525 [1:06:57<16:32,  7.46it/s]

 83%|████████████████████████████      | 35124/42525 [1:06:57<16:33,  7.45it/s]

 83%|████████████████████████████      | 35126/42525 [1:06:57<15:18,  8.06it/s]

 83%|████████████████████████████      | 35128/42525 [1:06:57<13:49,  8.92it/s]

 83%|████████████████████████████      | 35130/42525 [1:06:58<13:57,  8.83it/s]

 83%|████████████████████████████      | 35132/42525 [1:06:58<14:29,  8.50it/s]

 83%|████████████████████████████      | 35135/42525 [1:06:58<13:58,  8.81it/s]

 83%|████████████████████████████      | 35137/42525 [1:06:58<13:23,  9.20it/s]

 83%|████████████████████████████      | 35139/42525 [1:06:59<13:16,  9.27it/s]

 83%|████████████████████████████      | 35141/42525 [1:06:59<13:30,  9.11it/s]

 83%|████████████████████████████      | 35143/42525 [1:06:59<15:21,  8.01it/s]

 83%|████████████████████████████      | 35145/42525 [1:06:59<14:09,  8.68it/s]

 83%|████████████████████████████      | 35147/42525 [1:07:00<13:24,  9.17it/s]

 83%|████████████████████████████      | 35149/42525 [1:07:00<13:48,  8.90it/s]

 83%|████████████████████████████      | 35151/42525 [1:07:00<13:31,  9.08it/s]

 83%|████████████████████████████      | 35153/42525 [1:07:00<14:23,  8.53it/s]

 83%|████████████████████████████      | 35155/42525 [1:07:01<14:43,  8.34it/s]

 83%|████████████████████████████      | 35157/42525 [1:07:01<14:02,  8.74it/s]

 83%|████████████████████████████      | 35159/42525 [1:07:01<14:12,  8.64it/s]

 83%|████████████████████████████      | 35161/42525 [1:07:01<13:57,  8.79it/s]

 83%|████████████████████████████      | 35163/42525 [1:07:01<15:13,  8.06it/s]

 83%|████████████████████████████      | 35165/42525 [1:07:02<15:11,  8.08it/s]

 83%|████████████████████████████      | 35167/42525 [1:07:02<15:42,  7.81it/s]

 83%|████████████████████████████      | 35169/42525 [1:07:02<14:17,  8.57it/s]

 83%|████████████████████████████      | 35171/42525 [1:07:02<13:32,  9.05it/s]

 83%|████████████████████████████      | 35174/42525 [1:07:03<12:57,  9.45it/s]

 83%|████████████████████████████▏     | 35177/42525 [1:07:03<12:32,  9.76it/s]

 83%|████████████████████████████▏     | 35180/42525 [1:07:03<13:38,  8.98it/s]

 83%|████████████████████████████▏     | 35181/42525 [1:07:03<13:25,  9.12it/s]

 83%|████████████████████████████▏     | 35183/42525 [1:07:04<13:35,  9.00it/s]

 83%|████████████████████████████▏     | 35187/42525 [1:07:04<12:44,  9.60it/s]

 83%|████████████████████████████▏     | 35189/42525 [1:07:04<13:27,  9.09it/s]

 83%|████████████████████████████▏     | 35191/42525 [1:07:05<14:02,  8.70it/s]

 83%|████████████████████████████▏     | 35195/42525 [1:07:05<13:25,  9.10it/s]

 83%|████████████████████████████▏     | 35197/42525 [1:07:05<12:51,  9.50it/s]

 83%|████████████████████████████▏     | 35201/42525 [1:07:06<12:58,  9.41it/s]

 83%|████████████████████████████▏     | 35204/42525 [1:07:06<12:58,  9.40it/s]

 83%|████████████████████████████▏     | 35206/42525 [1:07:06<12:52,  9.48it/s]

 83%|████████████████████████████▏     | 35209/42525 [1:07:07<13:47,  8.84it/s]

 83%|████████████████████████████▏     | 35212/42525 [1:07:07<14:03,  8.67it/s]

 83%|████████████████████████████▏     | 35214/42525 [1:07:07<13:21,  9.12it/s]

 83%|████████████████████████████▏     | 35217/42525 [1:07:07<13:03,  9.32it/s]

 83%|████████████████████████████▏     | 35220/42525 [1:07:08<12:57,  9.39it/s]

 83%|████████████████████████████▏     | 35222/42525 [1:07:08<13:21,  9.11it/s]

 83%|████████████████████████████▏     | 35224/42525 [1:07:08<13:12,  9.21it/s]

 83%|████████████████████████████▏     | 35226/42525 [1:07:08<13:58,  8.71it/s]

 83%|████████████████████████████▏     | 35228/42525 [1:07:09<13:36,  8.94it/s]

 83%|████████████████████████████▏     | 35230/42525 [1:07:09<14:49,  8.20it/s]

 83%|████████████████████████████▏     | 35232/42525 [1:07:09<14:23,  8.45it/s]

 83%|████████████████████████████▏     | 35234/42525 [1:07:09<15:11,  8.00it/s]

 83%|████████████████████████████▏     | 35236/42525 [1:07:10<15:08,  8.02it/s]

 83%|████████████████████████████▏     | 35238/42525 [1:07:10<15:05,  8.04it/s]

 83%|████████████████████████████▏     | 35240/42525 [1:07:10<13:31,  8.98it/s]

 83%|████████████████████████████▏     | 35243/42525 [1:07:10<13:00,  9.33it/s]

 83%|████████████████████████████▏     | 35246/42525 [1:07:11<12:36,  9.62it/s]

 83%|████████████████████████████▏     | 35249/42525 [1:07:11<12:59,  9.34it/s]

 83%|████████████████████████████▏     | 35251/42525 [1:07:11<13:48,  8.78it/s]

 83%|████████████████████████████▏     | 35254/42525 [1:07:12<13:54,  8.72it/s]

 83%|████████████████████████████▏     | 35258/42525 [1:07:12<12:40,  9.55it/s]

 83%|████████████████████████████▏     | 35261/42525 [1:07:12<12:22,  9.78it/s]

 83%|████████████████████████████▏     | 35264/42525 [1:07:13<12:56,  9.35it/s]

 83%|████████████████████████████▏     | 35266/42525 [1:07:13<12:27,  9.71it/s]

 83%|████████████████████████████▏     | 35269/42525 [1:07:13<13:03,  9.27it/s]

 83%|████████████████████████████▏     | 35271/42525 [1:07:13<14:31,  8.33it/s]

 83%|████████████████████████████▏     | 35274/42525 [1:07:14<13:48,  8.76it/s]

 83%|████████████████████████████▏     | 35277/42525 [1:07:14<14:00,  8.63it/s]

 83%|████████████████████████████▏     | 35280/42525 [1:07:14<12:54,  9.35it/s]

 83%|████████████████████████████▏     | 35283/42525 [1:07:15<14:32,  8.30it/s]

 83%|████████████████████████████▏     | 35285/42525 [1:07:15<14:32,  8.29it/s]

 83%|████████████████████████████▏     | 35289/42525 [1:07:15<12:46,  9.44it/s]

 83%|████████████████████████████▏     | 35292/42525 [1:07:16<12:30,  9.63it/s]

 83%|████████████████████████████▏     | 35295/42525 [1:07:16<13:25,  8.97it/s]

 83%|████████████████████████████▏     | 35298/42525 [1:07:16<14:10,  8.50it/s]

 83%|████████████████████████████▏     | 35300/42525 [1:07:17<14:28,  8.32it/s]

 83%|████████████████████████████▏     | 35302/42525 [1:07:17<14:22,  8.38it/s]

 83%|████████████████████████████▏     | 35304/42525 [1:07:17<13:37,  8.83it/s]

 83%|████████████████████████████▏     | 35306/42525 [1:07:17<14:18,  8.41it/s]

 83%|████████████████████████████▏     | 35308/42525 [1:07:18<14:02,  8.56it/s]

 83%|████████████████████████████▏     | 35310/42525 [1:07:18<13:24,  8.97it/s]

 83%|████████████████████████████▏     | 35312/42525 [1:07:18<14:00,  8.58it/s]

 83%|████████████████████████████▏     | 35314/42525 [1:07:18<13:05,  9.18it/s]

 83%|████████████████████████████▏     | 35317/42525 [1:07:19<13:57,  8.60it/s]

 83%|████████████████████████████▏     | 35320/42525 [1:07:19<13:17,  9.03it/s]

 83%|████████████████████████████▏     | 35323/42525 [1:07:19<12:28,  9.62it/s]

 83%|████████████████████████████▏     | 35326/42525 [1:07:20<13:21,  8.98it/s]

 83%|████████████████████████████▏     | 35329/42525 [1:07:20<13:08,  9.13it/s]

 83%|████████████████████████████▏     | 35331/42525 [1:07:20<12:53,  9.31it/s]

 83%|████████████████████████████▏     | 35333/42525 [1:07:20<12:49,  9.35it/s]

 83%|████████████████████████████▎     | 35336/42525 [1:07:21<13:06,  9.14it/s]

 83%|████████████████████████████▎     | 35339/42525 [1:07:21<13:10,  9.09it/s]

 83%|████████████████████████████▎     | 35341/42525 [1:07:21<13:17,  9.00it/s]

 83%|████████████████████████████▎     | 35343/42525 [1:07:21<15:36,  7.67it/s]

 83%|████████████████████████████▎     | 35345/42525 [1:07:22<14:31,  8.24it/s]

 83%|████████████████████████████▎     | 35346/42525 [1:07:22<15:31,  7.71it/s]

 83%|████████████████████████████▎     | 35349/42525 [1:07:22<15:04,  7.93it/s]

 83%|████████████████████████████▎     | 35351/42525 [1:07:22<13:56,  8.58it/s]

 83%|████████████████████████████▎     | 35354/42525 [1:07:23<13:16,  9.00it/s]

 83%|████████████████████████████▎     | 35356/42525 [1:07:23<13:51,  8.62it/s]

 83%|████████████████████████████▎     | 35358/42525 [1:07:23<15:46,  7.57it/s]

 83%|████████████████████████████▎     | 35360/42525 [1:07:24<15:48,  7.55it/s]

 83%|████████████████████████████▎     | 35362/42525 [1:07:24<14:21,  8.31it/s]

 83%|████████████████████████████▎     | 35364/42525 [1:07:24<14:13,  8.39it/s]

 83%|████████████████████████████▎     | 35366/42525 [1:07:24<14:54,  8.00it/s]

 83%|████████████████████████████▎     | 35368/42525 [1:07:25<16:18,  7.32it/s]

 83%|████████████████████████████▎     | 35372/42525 [1:07:25<13:29,  8.84it/s]

 83%|████████████████████████████▎     | 35374/42525 [1:07:25<13:17,  8.97it/s]

 83%|████████████████████████████▎     | 35377/42525 [1:07:26<12:48,  9.30it/s]

 83%|████████████████████████████▎     | 35379/42525 [1:07:26<13:48,  8.63it/s]

 83%|████████████████████████████▎     | 35382/42525 [1:07:26<13:38,  8.72it/s]

 83%|████████████████████████████▎     | 35384/42525 [1:07:26<15:27,  7.70it/s]

 83%|████████████████████████████▎     | 35386/42525 [1:07:27<16:18,  7.29it/s]

 83%|████████████████████████████▎     | 35388/42525 [1:07:27<16:00,  7.43it/s]

 83%|████████████████████████████▎     | 35389/42525 [1:07:27<14:53,  7.99it/s]

 83%|████████████████████████████▎     | 35392/42525 [1:07:27<13:42,  8.67it/s]

 83%|████████████████████████████▎     | 35393/42525 [1:07:28<14:42,  8.08it/s]

 83%|████████████████████████████▎     | 35396/42525 [1:07:28<15:20,  7.75it/s]

 83%|████████████████████████████▎     | 35399/42525 [1:07:28<13:27,  8.82it/s]

 83%|████████████████████████████▎     | 35401/42525 [1:07:28<13:22,  8.87it/s]

 83%|████████████████████████████▎     | 35403/42525 [1:07:29<13:14,  8.97it/s]

 83%|████████████████████████████▎     | 35405/42525 [1:07:29<13:17,  8.93it/s]

 83%|████████████████████████████▎     | 35407/42525 [1:07:29<13:23,  8.86it/s]

 83%|████████████████████████████▎     | 35409/42525 [1:07:29<13:14,  8.95it/s]

 83%|████████████████████████████▎     | 35411/42525 [1:07:30<14:17,  8.30it/s]

 83%|████████████████████████████▎     | 35413/42525 [1:07:30<14:08,  8.38it/s]

 83%|████████████████████████████▎     | 35415/42525 [1:07:30<13:42,  8.64it/s]

 83%|████████████████████████████▎     | 35417/42525 [1:07:30<13:47,  8.59it/s]

 83%|████████████████████████████▎     | 35420/42525 [1:07:31<12:53,  9.19it/s]

 83%|████████████████████████████▎     | 35423/42525 [1:07:31<12:48,  9.24it/s]

 83%|████████████████████████████▎     | 35425/42525 [1:07:31<14:25,  8.20it/s]

 83%|████████████████████████████▎     | 35427/42525 [1:07:31<14:27,  8.18it/s]

 83%|████████████████████████████▎     | 35429/42525 [1:07:32<13:49,  8.55it/s]

 83%|████████████████████████████▎     | 35431/42525 [1:07:32<14:53,  7.94it/s]

 83%|████████████████████████████▎     | 35433/42525 [1:07:32<13:48,  8.56it/s]

 83%|████████████████████████████▎     | 35435/42525 [1:07:32<13:20,  8.86it/s]

 83%|████████████████████████████▎     | 35437/42525 [1:07:33<12:56,  9.12it/s]

 83%|████████████████████████████▎     | 35439/42525 [1:07:33<14:34,  8.11it/s]

 83%|████████████████████████████▎     | 35441/42525 [1:07:33<15:13,  7.75it/s]

 83%|████████████████████████████▎     | 35443/42525 [1:07:33<13:37,  8.66it/s]

 83%|████████████████████████████▎     | 35445/42525 [1:07:34<12:48,  9.21it/s]

 83%|████████████████████████████▎     | 35447/42525 [1:07:34<13:15,  8.90it/s]

 83%|████████████████████████████▎     | 35449/42525 [1:07:34<12:39,  9.32it/s]

 83%|████████████████████████████▎     | 35451/42525 [1:07:34<12:40,  9.30it/s]

 83%|████████████████████████████▎     | 35453/42525 [1:07:34<14:42,  8.02it/s]

 83%|████████████████████████████▎     | 35455/42525 [1:07:35<13:37,  8.65it/s]

 83%|████████████████████████████▎     | 35457/42525 [1:07:35<12:54,  9.12it/s]

 83%|████████████████████████████▎     | 35460/42525 [1:07:35<13:39,  8.62it/s]

 83%|████████████████████████████▎     | 35462/42525 [1:07:35<13:27,  8.75it/s]

 83%|████████████████████████████▎     | 35464/42525 [1:07:36<14:29,  8.12it/s]

 83%|████████████████████████████▎     | 35466/42525 [1:07:36<14:29,  8.12it/s]

 83%|████████████████████████████▎     | 35468/42525 [1:07:36<14:44,  7.98it/s]

 83%|████████████████████████████▎     | 35471/42525 [1:07:37<13:06,  8.97it/s]

 83%|████████████████████████████▎     | 35473/42525 [1:07:37<13:30,  8.70it/s]

 83%|████████████████████████████▎     | 35475/42525 [1:07:37<14:07,  8.32it/s]

 83%|████████████████████████████▎     | 35477/42525 [1:07:37<13:04,  8.98it/s]

 83%|████████████████████████████▎     | 35480/42525 [1:07:38<12:49,  9.16it/s]

 83%|████████████████████████████▎     | 35482/42525 [1:07:38<13:28,  8.71it/s]

 83%|████████████████████████████▎     | 35484/42525 [1:07:38<13:25,  8.74it/s]

 83%|████████████████████████████▎     | 35486/42525 [1:07:38<13:21,  8.79it/s]

 83%|████████████████████████████▎     | 35488/42525 [1:07:38<13:35,  8.63it/s]

 83%|████████████████████████████▍     | 35490/42525 [1:07:39<13:53,  8.44it/s]

 83%|████████████████████████████▍     | 35492/42525 [1:07:39<13:19,  8.80it/s]

 83%|████████████████████████████▍     | 35494/42525 [1:07:39<15:20,  7.64it/s]

 83%|████████████████████████████▍     | 35496/42525 [1:07:39<15:30,  7.55it/s]

 83%|████████████████████████████▍     | 35498/42525 [1:07:40<14:13,  8.23it/s]

 83%|████████████████████████████▍     | 35501/42525 [1:07:40<12:38,  9.26it/s]

 83%|████████████████████████████▍     | 35503/42525 [1:07:40<12:18,  9.51it/s]

 83%|████████████████████████████▍     | 35506/42525 [1:07:41<13:42,  8.53it/s]

 83%|████████████████████████████▍     | 35508/42525 [1:07:41<13:49,  8.46it/s]

 84%|████████████████████████████▍     | 35510/42525 [1:07:41<13:15,  8.82it/s]

 84%|████████████████████████████▍     | 35512/42525 [1:07:41<12:52,  9.08it/s]

 84%|████████████████████████████▍     | 35514/42525 [1:07:42<13:43,  8.52it/s]

 84%|████████████████████████████▍     | 35516/42525 [1:07:42<12:56,  9.03it/s]

 84%|████████████████████████████▍     | 35518/42525 [1:07:42<13:57,  8.37it/s]

 84%|████████████████████████████▍     | 35520/42525 [1:07:42<14:05,  8.28it/s]

 84%|████████████████████████████▍     | 35522/42525 [1:07:42<13:29,  8.65it/s]

 84%|████████████████████████████▍     | 35525/42525 [1:07:43<12:32,  9.31it/s]

 84%|████████████████████████████▍     | 35527/42525 [1:07:43<12:31,  9.31it/s]

 84%|████████████████████████████▍     | 35529/42525 [1:07:43<12:36,  9.24it/s]

 84%|████████████████████████████▍     | 35531/42525 [1:07:43<12:50,  9.08it/s]

 84%|████████████████████████████▍     | 35533/42525 [1:07:44<12:35,  9.26it/s]

 84%|████████████████████████████▍     | 35535/42525 [1:07:44<12:30,  9.32it/s]

 84%|████████████████████████████▍     | 35538/42525 [1:07:44<11:58,  9.73it/s]

 84%|████████████████████████████▍     | 35541/42525 [1:07:44<12:32,  9.28it/s]

 84%|████████████████████████████▍     | 35543/42525 [1:07:45<12:54,  9.01it/s]

 84%|████████████████████████████▍     | 35544/42525 [1:07:45<12:46,  9.11it/s]

 84%|████████████████████████████▍     | 35547/42525 [1:07:45<12:14,  9.50it/s]

 84%|████████████████████████████▍     | 35549/42525 [1:07:45<12:13,  9.51it/s]

 84%|████████████████████████████▍     | 35551/42525 [1:07:46<13:20,  8.71it/s]

 84%|████████████████████████████▍     | 35553/42525 [1:07:46<13:09,  8.83it/s]

 84%|████████████████████████████▍     | 35555/42525 [1:07:46<13:15,  8.76it/s]

 84%|████████████████████████████▍     | 35557/42525 [1:07:46<12:34,  9.24it/s]

 84%|████████████████████████████▍     | 35559/42525 [1:07:47<14:02,  8.27it/s]

 84%|████████████████████████████▍     | 35561/42525 [1:07:47<14:07,  8.22it/s]

 84%|████████████████████████████▍     | 35563/42525 [1:07:47<14:02,  8.27it/s]

 84%|████████████████████████████▍     | 35565/42525 [1:07:47<14:19,  8.10it/s]

 84%|████████████████████████████▍     | 35567/42525 [1:07:47<13:21,  8.69it/s]

 84%|████████████████████████████▍     | 35569/42525 [1:07:48<13:54,  8.33it/s]

 84%|████████████████████████████▍     | 35570/42525 [1:07:48<13:37,  8.50it/s]

 84%|████████████████████████████▍     | 35574/42525 [1:07:48<12:02,  9.63it/s]

 84%|████████████████████████████▍     | 35578/42525 [1:07:49<11:31, 10.05it/s]

 84%|████████████████████████████▍     | 35581/42525 [1:07:49<12:08,  9.53it/s]

 84%|████████████████████████████▍     | 35584/42525 [1:07:49<12:06,  9.55it/s]

 84%|████████████████████████████▍     | 35586/42525 [1:07:49<12:14,  9.44it/s]

 84%|████████████████████████████▍     | 35588/42525 [1:07:50<14:19,  8.07it/s]

 84%|████████████████████████████▍     | 35590/42525 [1:07:50<14:40,  7.88it/s]

 84%|████████████████████████████▍     | 35591/42525 [1:07:50<14:21,  8.05it/s]

 84%|████████████████████████████▍     | 35594/42525 [1:07:50<13:43,  8.42it/s]

 84%|████████████████████████████▍     | 35596/42525 [1:07:51<13:01,  8.86it/s]

 84%|████████████████████████████▍     | 35598/42525 [1:07:51<12:30,  9.22it/s]

 84%|████████████████████████████▍     | 35601/42525 [1:07:51<12:00,  9.60it/s]

 84%|████████████████████████████▍     | 35603/42525 [1:07:51<11:57,  9.65it/s]

 84%|████████████████████████████▍     | 35605/42525 [1:07:52<12:58,  8.89it/s]

 84%|████████████████████████████▍     | 35607/42525 [1:07:52<13:13,  8.72it/s]

 84%|████████████████████████████▍     | 35609/42525 [1:07:52<13:36,  8.47it/s]

 84%|████████████████████████████▍     | 35611/42525 [1:07:52<14:01,  8.22it/s]

 84%|████████████████████████████▍     | 35613/42525 [1:07:53<12:50,  8.97it/s]

 84%|████████████████████████████▍     | 35616/42525 [1:07:53<12:07,  9.50it/s]

 84%|████████████████████████████▍     | 35620/42525 [1:07:53<11:49,  9.73it/s]

 84%|████████████████████████████▍     | 35621/42525 [1:07:53<12:12,  9.42it/s]

 84%|████████████████████████████▍     | 35624/42525 [1:07:54<13:22,  8.60it/s]

 84%|████████████████████████████▍     | 35626/42525 [1:07:54<13:42,  8.39it/s]

 84%|████████████████████████████▍     | 35628/42525 [1:07:54<14:24,  7.98it/s]

 84%|████████████████████████████▍     | 35630/42525 [1:07:55<14:30,  7.92it/s]

 84%|████████████████████████████▍     | 35632/42525 [1:07:55<13:30,  8.50it/s]

 84%|████████████████████████████▍     | 35634/42525 [1:07:55<13:07,  8.75it/s]

 84%|████████████████████████████▍     | 35636/42525 [1:07:55<13:10,  8.72it/s]

 84%|████████████████████████████▍     | 35638/42525 [1:07:55<13:09,  8.73it/s]

 84%|████████████████████████████▍     | 35640/42525 [1:07:56<12:47,  8.97it/s]

 84%|████████████████████████████▍     | 35642/42525 [1:07:56<12:29,  9.18it/s]

 84%|████████████████████████████▍     | 35644/42525 [1:07:56<12:05,  9.48it/s]

 84%|████████████████████████████▌     | 35646/42525 [1:07:56<14:43,  7.78it/s]

 84%|████████████████████████████▌     | 35648/42525 [1:07:57<13:25,  8.54it/s]

 84%|████████████████████████████▌     | 35650/42525 [1:07:57<13:07,  8.73it/s]

 84%|████████████████████████████▌     | 35652/42525 [1:07:57<13:28,  8.50it/s]

 84%|████████████████████████████▌     | 35654/42525 [1:07:57<13:42,  8.35it/s]

 84%|████████████████████████████▌     | 35656/42525 [1:07:58<13:16,  8.62it/s]

 84%|████████████████████████████▌     | 35659/42525 [1:07:58<12:52,  8.89it/s]

 84%|████████████████████████████▌     | 35661/42525 [1:07:58<12:55,  8.85it/s]

 84%|████████████████████████████▌     | 35663/42525 [1:07:58<13:32,  8.45it/s]

 84%|████████████████████████████▌     | 35665/42525 [1:07:59<12:46,  8.95it/s]

 84%|████████████████████████████▌     | 35667/42525 [1:07:59<12:48,  8.93it/s]

 84%|████████████████████████████▌     | 35669/42525 [1:07:59<12:54,  8.86it/s]

 84%|████████████████████████████▌     | 35671/42525 [1:07:59<12:50,  8.89it/s]

 84%|████████████████████████████▌     | 35673/42525 [1:07:59<13:29,  8.46it/s]

 84%|████████████████████████████▌     | 35675/42525 [1:08:00<12:54,  8.84it/s]

 84%|████████████████████████████▌     | 35678/42525 [1:08:00<12:04,  9.45it/s]

 84%|████████████████████████████▌     | 35680/42525 [1:08:00<13:26,  8.49it/s]

 84%|████████████████████████████▌     | 35683/42525 [1:08:01<12:36,  9.04it/s]

 84%|████████████████████████████▌     | 35685/42525 [1:08:01<12:51,  8.87it/s]

 84%|████████████████████████████▌     | 35687/42525 [1:08:01<13:33,  8.41it/s]

 84%|████████████████████████████▌     | 35689/42525 [1:08:01<13:43,  8.30it/s]

 84%|████████████████████████████▌     | 35691/42525 [1:08:02<13:46,  8.27it/s]

 84%|████████████████████████████▌     | 35693/42525 [1:08:02<14:25,  7.89it/s]

 84%|████████████████████████████▌     | 35695/42525 [1:08:02<14:15,  7.99it/s]

 84%|████████████████████████████▌     | 35697/42525 [1:08:02<13:15,  8.59it/s]

 84%|████████████████████████████▌     | 35699/42525 [1:08:03<13:24,  8.48it/s]

 84%|████████████████████████████▌     | 35701/42525 [1:08:03<13:11,  8.62it/s]

 84%|████████████████████████████▌     | 35703/42525 [1:08:03<12:29,  9.10it/s]

 84%|████████████████████████████▌     | 35705/42525 [1:08:03<13:12,  8.61it/s]

 84%|████████████████████████████▌     | 35709/42525 [1:08:04<12:19,  9.21it/s]

 84%|████████████████████████████▌     | 35711/42525 [1:08:04<12:34,  9.03it/s]

 84%|████████████████████████████▌     | 35713/42525 [1:08:04<12:26,  9.12it/s]

 84%|████████████████████████████▌     | 35715/42525 [1:08:04<13:06,  8.66it/s]

 84%|████████████████████████████▌     | 35718/42525 [1:08:05<12:47,  8.87it/s]

 84%|████████████████████████████▌     | 35720/42525 [1:08:05<13:39,  8.30it/s]

 84%|████████████████████████████▌     | 35722/42525 [1:08:05<12:51,  8.82it/s]

 84%|████████████████████████████▌     | 35724/42525 [1:08:05<13:25,  8.45it/s]

 84%|████████████████████████████▌     | 35726/42525 [1:08:06<12:30,  9.06it/s]

 84%|████████████████████████████▌     | 35728/42525 [1:08:06<12:10,  9.30it/s]

 84%|████████████████████████████▌     | 35731/42525 [1:08:06<11:54,  9.51it/s]

 84%|████████████████████████████▌     | 35732/42525 [1:08:06<11:53,  9.53it/s]

 84%|████████████████████████████▌     | 35735/42525 [1:08:07<12:02,  9.39it/s]

 84%|████████████████████████████▌     | 35737/42525 [1:08:07<13:15,  8.54it/s]

 84%|████████████████████████████▌     | 35739/42525 [1:08:07<14:17,  7.92it/s]

 84%|████████████████████████████▌     | 35741/42525 [1:08:07<14:14,  7.94it/s]

 84%|████████████████████████████▌     | 35743/42525 [1:08:08<13:24,  8.43it/s]

 84%|████████████████████████████▌     | 35745/42525 [1:08:08<14:52,  7.59it/s]

 84%|████████████████████████████▌     | 35748/42525 [1:08:08<13:34,  8.33it/s]

 84%|████████████████████████████▌     | 35750/42525 [1:08:08<12:45,  8.85it/s]

 84%|████████████████████████████▌     | 35752/42525 [1:08:09<12:42,  8.88it/s]

 84%|████████████████████████████▌     | 35754/42525 [1:08:09<13:07,  8.60it/s]

 84%|████████████████████████████▌     | 35756/42525 [1:08:09<12:48,  8.81it/s]

 84%|████████████████████████████▌     | 35758/42525 [1:08:09<12:12,  9.24it/s]

 84%|████████████████████████████▌     | 35760/42525 [1:08:09<12:20,  9.14it/s]

 84%|████████████████████████████▌     | 35763/42525 [1:08:10<13:49,  8.15it/s]

 84%|████████████████████████████▌     | 35764/42525 [1:08:10<13:14,  8.51it/s]

 84%|████████████████████████████▌     | 35767/42525 [1:08:10<12:33,  8.97it/s]

 84%|████████████████████████████▌     | 35769/42525 [1:08:11<12:08,  9.27it/s]

 84%|████████████████████████████▌     | 35771/42525 [1:08:11<12:25,  9.05it/s]

 84%|████████████████████████████▌     | 35773/42525 [1:08:11<12:16,  9.17it/s]

 84%|████████████████████████████▌     | 35775/42525 [1:08:11<12:22,  9.10it/s]

 84%|████████████████████████████▌     | 35777/42525 [1:08:11<13:16,  8.47it/s]

 84%|████████████████████████████▌     | 35779/42525 [1:08:12<12:47,  8.79it/s]

 84%|████████████████████████████▌     | 35781/42525 [1:08:12<13:51,  8.11it/s]

 84%|████████████████████████████▌     | 35784/42525 [1:08:12<12:29,  9.00it/s]

 84%|████████████████████████████▌     | 35786/42525 [1:08:12<12:11,  9.21it/s]

 84%|████████████████████████████▌     | 35788/42525 [1:08:13<12:18,  9.12it/s]

 84%|████████████████████████████▌     | 35790/42525 [1:08:13<11:59,  9.36it/s]

 84%|████████████████████████████▌     | 35791/42525 [1:08:13<12:20,  9.09it/s]

 84%|████████████████████████████▌     | 35794/42525 [1:08:13<13:01,  8.62it/s]

 84%|████████████████████████████▌     | 35796/42525 [1:08:14<13:42,  8.18it/s]

 84%|████████████████████████████▌     | 35799/42525 [1:08:14<13:26,  8.34it/s]

 84%|████████████████████████████▌     | 35801/42525 [1:08:14<13:54,  8.06it/s]

 84%|████████████████████████████▋     | 35803/42525 [1:08:14<15:13,  7.36it/s]

 84%|████████████████████████████▋     | 35805/42525 [1:08:15<15:09,  7.39it/s]

 84%|████████████████████████████▋     | 35807/42525 [1:08:15<13:40,  8.19it/s]

 84%|████████████████████████████▋     | 35809/42525 [1:08:15<14:04,  7.95it/s]

 84%|████████████████████████████▋     | 35811/42525 [1:08:15<13:53,  8.06it/s]

 84%|████████████████████████████▋     | 35814/42525 [1:08:16<12:09,  9.19it/s]

 84%|████████████████████████████▋     | 35816/42525 [1:08:16<12:27,  8.97it/s]

 84%|████████████████████████████▋     | 35818/42525 [1:08:16<12:29,  8.95it/s]

 84%|████████████████████████████▋     | 35819/42525 [1:08:16<13:18,  8.40it/s]

 84%|████████████████████████████▋     | 35822/42525 [1:08:17<14:18,  7.81it/s]

 84%|████████████████████████████▋     | 35825/42525 [1:08:17<12:45,  8.75it/s]

 84%|████████████████████████████▋     | 35827/42525 [1:08:17<12:01,  9.28it/s]

 84%|████████████████████████████▋     | 35830/42525 [1:08:18<12:06,  9.21it/s]

 84%|████████████████████████████▋     | 35833/42525 [1:08:18<11:52,  9.39it/s]

 84%|████████████████████████████▋     | 35836/42525 [1:08:18<11:40,  9.55it/s]

 84%|████████████████████████████▋     | 35838/42525 [1:08:18<11:41,  9.53it/s]

 84%|████████████████████████████▋     | 35840/42525 [1:08:19<13:06,  8.50it/s]

 84%|████████████████████████████▋     | 35843/42525 [1:08:19<13:20,  8.35it/s]

 84%|████████████████████████████▋     | 35845/42525 [1:08:19<12:24,  8.97it/s]

 84%|████████████████████████████▋     | 35847/42525 [1:08:19<12:07,  9.19it/s]

 84%|████████████████████████████▋     | 35849/42525 [1:08:20<11:45,  9.46it/s]

 84%|████████████████████████████▋     | 35851/42525 [1:08:20<11:34,  9.61it/s]

 84%|████████████████████████████▋     | 35854/42525 [1:08:20<12:29,  8.90it/s]

 84%|████████████████████████████▋     | 35857/42525 [1:08:21<11:56,  9.31it/s]

 84%|████████████████████████████▋     | 35859/42525 [1:08:21<11:54,  9.33it/s]

 84%|████████████████████████████▋     | 35861/42525 [1:08:21<11:33,  9.61it/s]

 84%|████████████████████████████▋     | 35862/42525 [1:08:21<11:56,  9.30it/s]

 84%|████████████████████████████▋     | 35865/42525 [1:08:21<12:56,  8.57it/s]

 84%|████████████████████████████▋     | 35867/42525 [1:08:22<13:18,  8.33it/s]

 84%|████████████████████████████▋     | 35870/42525 [1:08:22<14:13,  7.80it/s]

 84%|████████████████████████████▋     | 35872/42525 [1:08:22<13:01,  8.51it/s]

 84%|████████████████████████████▋     | 35875/42525 [1:08:23<11:56,  9.27it/s]

 84%|████████████████████████████▋     | 35876/42525 [1:08:23<11:56,  9.28it/s]

 84%|████████████████████████████▋     | 35879/42525 [1:08:23<12:23,  8.94it/s]

 84%|████████████████████████████▋     | 35880/42525 [1:08:23<13:20,  8.30it/s]

 84%|████████████████████████████▋     | 35883/42525 [1:08:24<12:56,  8.55it/s]

 84%|████████████████████████████▋     | 35885/42525 [1:08:24<13:10,  8.40it/s]

 84%|████████████████████████████▋     | 35887/42525 [1:08:24<12:17,  9.00it/s]

 84%|████████████████████████████▋     | 35890/42525 [1:08:24<12:48,  8.64it/s]

 84%|████████████████████████████▋     | 35893/42525 [1:08:25<11:46,  9.39it/s]

 84%|████████████████████████████▋     | 35896/42525 [1:08:25<12:04,  9.15it/s]

 84%|████████████████████████████▋     | 35899/42525 [1:08:25<11:36,  9.51it/s]

 84%|████████████████████████████▋     | 35901/42525 [1:08:25<11:45,  9.39it/s]

 84%|████████████████████████████▋     | 35903/42525 [1:08:26<12:18,  8.96it/s]

 84%|████████████████████████████▋     | 35904/42525 [1:08:26<12:01,  9.18it/s]

 84%|████████████████████████████▋     | 35907/42525 [1:08:26<13:00,  8.48it/s]

 84%|████████████████████████████▋     | 35909/42525 [1:08:26<14:00,  7.87it/s]

 84%|████████████████████████████▋     | 35912/42525 [1:08:27<12:17,  8.96it/s]

 84%|████████████████████████████▋     | 35914/42525 [1:08:27<12:49,  8.59it/s]

 84%|████████████████████████████▋     | 35916/42525 [1:08:27<12:01,  9.16it/s]

 84%|████████████████████████████▋     | 35919/42525 [1:08:28<12:47,  8.60it/s]

 84%|████████████████████████████▋     | 35921/42525 [1:08:28<13:54,  7.91it/s]

 84%|████████████████████████████▋     | 35923/42525 [1:08:28<12:54,  8.53it/s]

 84%|████████████████████████████▋     | 35925/42525 [1:08:28<12:53,  8.53it/s]

 84%|████████████████████████████▋     | 35927/42525 [1:08:29<13:13,  8.31it/s]

 84%|████████████████████████████▋     | 35929/42525 [1:08:29<13:54,  7.91it/s]

 84%|████████████████████████████▋     | 35931/42525 [1:08:29<14:14,  7.72it/s]

 84%|████████████████████████████▋     | 35933/42525 [1:08:29<12:49,  8.57it/s]

 85%|████████████████████████████▋     | 35935/42525 [1:08:29<12:28,  8.80it/s]

 85%|████████████████████████████▋     | 35937/42525 [1:08:30<12:07,  9.05it/s]

 85%|████████████████████████████▋     | 35939/42525 [1:08:30<11:56,  9.19it/s]

 85%|████████████████████████████▋     | 35942/42525 [1:08:30<11:35,  9.46it/s]

 85%|████████████████████████████▋     | 35944/42525 [1:08:30<12:18,  8.91it/s]

 85%|████████████████████████████▋     | 35946/42525 [1:08:31<11:55,  9.19it/s]

 85%|████████████████████████████▋     | 35949/42525 [1:08:31<12:06,  9.05it/s]

 85%|████████████████████████████▋     | 35951/42525 [1:08:31<12:02,  9.10it/s]

 85%|████████████████████████████▋     | 35953/42525 [1:08:31<13:06,  8.35it/s]

 85%|████████████████████████████▋     | 35955/42525 [1:08:32<12:31,  8.74it/s]

 85%|████████████████████████████▋     | 35956/42525 [1:08:32<12:41,  8.63it/s]

 85%|████████████████████████████▋     | 35958/42525 [1:08:32<11:58,  9.14it/s]

 85%|████████████████████████████▊     | 35961/42525 [1:08:32<11:38,  9.40it/s]

 85%|████████████████████████████▊     | 35963/42525 [1:08:33<12:43,  8.59it/s]

 85%|████████████████████████████▊     | 35964/42525 [1:08:33<13:12,  8.28it/s]

 85%|████████████████████████████▊     | 35967/42525 [1:08:33<13:52,  7.88it/s]

 85%|████████████████████████████▊     | 35969/42525 [1:08:33<13:18,  8.21it/s]

 85%|████████████████████████████▊     | 35971/42525 [1:08:34<13:39,  7.99it/s]

 85%|████████████████████████████▊     | 35973/42525 [1:08:34<13:20,  8.19it/s]

 85%|████████████████████████████▊     | 35976/42525 [1:08:34<12:06,  9.02it/s]

 85%|████████████████████████████▊     | 35978/42525 [1:08:34<11:58,  9.11it/s]

 85%|████████████████████████████▊     | 35980/42525 [1:08:35<11:47,  9.25it/s]

 85%|████████████████████████████▊     | 35982/42525 [1:08:35<13:54,  7.84it/s]

 85%|████████████████████████████▊     | 35983/42525 [1:08:35<13:08,  8.30it/s]

 85%|████████████████████████████▊     | 35986/42525 [1:08:35<13:15,  8.22it/s]

 85%|████████████████████████████▊     | 35989/42525 [1:08:36<11:51,  9.18it/s]

 85%|████████████████████████████▊     | 35992/42525 [1:08:36<11:18,  9.62it/s]

 85%|████████████████████████████▊     | 35994/42525 [1:08:36<11:34,  9.41it/s]

 85%|████████████████████████████▊     | 35996/42525 [1:08:36<12:35,  8.64it/s]

 85%|████████████████████████████▊     | 35998/42525 [1:08:37<11:41,  9.31it/s]

 85%|████████████████████████████▊     | 36001/42525 [1:08:37<12:07,  8.97it/s]

 85%|████████████████████████████▊     | 36003/42525 [1:08:37<11:53,  9.14it/s]

 85%|████████████████████████████▊     | 36005/42525 [1:08:37<12:18,  8.83it/s]

 85%|████████████████████████████▊     | 36008/42525 [1:08:38<12:03,  9.01it/s]

 85%|████████████████████████████▊     | 36011/42525 [1:08:38<12:50,  8.45it/s]

 85%|████████████████████████████▊     | 36015/42525 [1:08:38<11:29,  9.44it/s]

 85%|████████████████████████████▊     | 36017/42525 [1:08:39<12:17,  8.82it/s]

 85%|████████████████████████████▊     | 36019/42525 [1:08:39<12:12,  8.89it/s]

 85%|████████████████████████████▊     | 36021/42525 [1:08:39<12:45,  8.49it/s]

 85%|████████████████████████████▊     | 36023/42525 [1:08:39<13:04,  8.29it/s]

 85%|████████████████████████████▊     | 36024/42525 [1:08:40<12:26,  8.71it/s]

 85%|████████████████████████████▊     | 36027/42525 [1:08:40<11:50,  9.14it/s]

 85%|████████████████████████████▊     | 36029/42525 [1:08:40<11:34,  9.35it/s]

 85%|████████████████████████████▊     | 36031/42525 [1:08:40<12:51,  8.42it/s]

 85%|████████████████████████████▊     | 36033/42525 [1:08:41<11:55,  9.08it/s]

 85%|████████████████████████████▊     | 36035/42525 [1:08:41<11:27,  9.44it/s]

 85%|████████████████████████████▊     | 36037/42525 [1:08:41<12:29,  8.65it/s]

 85%|████████████████████████████▊     | 36039/42525 [1:08:41<12:14,  8.83it/s]

 85%|████████████████████████████▊     | 36041/42525 [1:08:42<13:43,  7.88it/s]

 85%|████████████████████████████▊     | 36043/42525 [1:08:42<12:18,  8.78it/s]

 85%|████████████████████████████▊     | 36045/42525 [1:08:42<12:46,  8.45it/s]

 85%|████████████████████████████▊     | 36047/42525 [1:08:42<11:56,  9.04it/s]

 85%|████████████████████████████▊     | 36049/42525 [1:08:42<11:45,  9.18it/s]

 85%|████████████████████████████▊     | 36051/42525 [1:08:43<12:18,  8.77it/s]

 85%|████████████████████████████▊     | 36053/42525 [1:08:43<13:34,  7.95it/s]

 85%|████████████████████████████▊     | 36055/42525 [1:08:43<13:16,  8.12it/s]

 85%|████████████████████████████▊     | 36057/42525 [1:08:43<14:21,  7.51it/s]

 85%|████████████████████████████▊     | 36059/42525 [1:08:44<13:56,  7.73it/s]

 85%|████████████████████████████▊     | 36061/42525 [1:08:44<12:35,  8.55it/s]

 85%|████████████████████████████▊     | 36063/42525 [1:08:44<13:47,  7.81it/s]

 85%|████████████████████████████▊     | 36065/42525 [1:08:44<13:27,  8.00it/s]

 85%|████████████████████████████▊     | 36067/42525 [1:08:45<12:56,  8.31it/s]

 85%|████████████████████████████▊     | 36069/42525 [1:08:45<12:09,  8.85it/s]

 85%|████████████████████████████▊     | 36071/42525 [1:08:45<12:48,  8.40it/s]

 85%|████████████████████████████▊     | 36073/42525 [1:08:45<12:20,  8.71it/s]

 85%|████████████████████████████▊     | 36075/42525 [1:08:46<12:44,  8.43it/s]

 85%|████████████████████████████▊     | 36077/42525 [1:08:46<14:31,  7.40it/s]

 85%|████████████████████████████▊     | 36079/42525 [1:08:46<13:31,  7.95it/s]

 85%|████████████████████████████▊     | 36080/42525 [1:08:46<13:18,  8.07it/s]

 85%|████████████████████████████▊     | 36083/42525 [1:08:47<12:04,  8.89it/s]

 85%|████████████████████████████▊     | 36086/42525 [1:08:47<11:52,  9.04it/s]

 85%|████████████████████████████▊     | 36088/42525 [1:08:47<11:52,  9.03it/s]

 85%|████████████████████████████▊     | 36090/42525 [1:08:47<11:43,  9.15it/s]

 85%|████████████████████████████▊     | 36092/42525 [1:08:47<11:31,  9.31it/s]

 85%|████████████████████████████▊     | 36094/42525 [1:08:48<11:22,  9.43it/s]

 85%|████████████████████████████▊     | 36096/42525 [1:08:48<11:12,  9.57it/s]

 85%|████████████████████████████▊     | 36098/42525 [1:08:48<11:01,  9.72it/s]

 85%|████████████████████████████▊     | 36100/42525 [1:08:48<12:40,  8.45it/s]

 85%|████████████████████████████▊     | 36102/42525 [1:08:49<12:55,  8.28it/s]

 85%|████████████████████████████▊     | 36104/42525 [1:08:49<13:23,  7.99it/s]

 85%|████████████████████████████▊     | 36106/42525 [1:08:49<14:26,  7.41it/s]

 85%|████████████████████████████▊     | 36108/42525 [1:08:49<12:35,  8.50it/s]

 85%|████████████████████████████▊     | 36111/42525 [1:08:50<11:23,  9.39it/s]

 85%|████████████████████████████▊     | 36113/42525 [1:08:50<12:17,  8.69it/s]

 85%|████████████████████████████▉     | 36115/42525 [1:08:50<12:04,  8.84it/s]

 85%|████████████████████████████▉     | 36116/42525 [1:08:50<12:03,  8.86it/s]

 85%|████████████████████████████▉     | 36119/42525 [1:08:51<11:27,  9.32it/s]

 85%|████████████████████████████▉     | 36121/42525 [1:08:51<12:04,  8.84it/s]

 85%|████████████████████████████▉     | 36123/42525 [1:08:51<13:40,  7.81it/s]

 85%|████████████████████████████▉     | 36125/42525 [1:08:51<12:15,  8.70it/s]

 85%|████████████████████████████▉     | 36128/42525 [1:08:52<11:50,  9.01it/s]

 85%|████████████████████████████▉     | 36130/42525 [1:08:52<12:59,  8.21it/s]

 85%|████████████████████████████▉     | 36133/42525 [1:08:52<11:35,  9.19it/s]

 85%|████████████████████████████▉     | 36136/42525 [1:08:53<11:05,  9.60it/s]

 85%|████████████████████████████▉     | 36138/42525 [1:08:53<12:18,  8.65it/s]

 85%|████████████████████████████▉     | 36140/42525 [1:08:53<12:42,  8.37it/s]

 85%|████████████████████████████▉     | 36143/42525 [1:08:53<12:09,  8.75it/s]

 85%|████████████████████████████▉     | 36144/42525 [1:08:53<13:03,  8.15it/s]

 85%|████████████████████████████▉     | 36148/42525 [1:08:54<12:07,  8.77it/s]

 85%|████████████████████████████▉     | 36151/42525 [1:08:54<11:49,  8.98it/s]

 85%|████████████████████████████▉     | 36153/42525 [1:08:55<12:15,  8.66it/s]

 85%|████████████████████████████▉     | 36155/42525 [1:08:55<11:43,  9.06it/s]

 85%|████████████████████████████▉     | 36157/42525 [1:08:55<11:40,  9.09it/s]

 85%|████████████████████████████▉     | 36159/42525 [1:08:55<12:17,  8.64it/s]

 85%|████████████████████████████▉     | 36162/42525 [1:08:55<11:16,  9.41it/s]

 85%|████████████████████████████▉     | 36164/42525 [1:08:56<12:00,  8.83it/s]

 85%|████████████████████████████▉     | 36165/42525 [1:08:56<13:00,  8.15it/s]

 85%|████████████████████████████▉     | 36168/42525 [1:08:56<12:49,  8.26it/s]

 85%|████████████████████████████▉     | 36171/42525 [1:08:57<12:37,  8.39it/s]

 85%|████████████████████████████▉     | 36173/42525 [1:08:57<14:04,  7.52it/s]

 85%|████████████████████████████▉     | 36174/42525 [1:08:57<13:40,  7.74it/s]

 85%|████████████████████████████▉     | 36177/42525 [1:08:57<14:00,  7.56it/s]

 85%|████████████████████████████▉     | 36179/42525 [1:08:58<12:45,  8.29it/s]

 85%|████████████████████████████▉     | 36182/42525 [1:08:58<12:38,  8.37it/s]

 85%|████████████████████████████▉     | 36184/42525 [1:08:58<13:05,  8.08it/s]

 85%|████████████████████████████▉     | 36186/42525 [1:08:58<13:02,  8.11it/s]

 85%|████████████████████████████▉     | 36188/42525 [1:08:59<12:09,  8.69it/s]

 85%|████████████████████████████▉     | 36190/42525 [1:08:59<12:53,  8.19it/s]

 85%|████████████████████████████▉     | 36192/42525 [1:08:59<13:03,  8.08it/s]

 85%|████████████████████████████▉     | 36195/42525 [1:09:00<11:41,  9.02it/s]

 85%|████████████████████████████▉     | 36197/42525 [1:09:00<11:19,  9.31it/s]

 85%|████████████████████████████▉     | 36199/42525 [1:09:00<11:15,  9.36it/s]

 85%|████████████████████████████▉     | 36202/42525 [1:09:00<11:37,  9.07it/s]

 85%|████████████████████████████▉     | 36205/42525 [1:09:01<12:08,  8.68it/s]

 85%|████████████████████████████▉     | 36206/42525 [1:09:01<12:58,  8.12it/s]

 85%|████████████████████████████▉     | 36209/42525 [1:09:01<11:43,  8.98it/s]

 85%|████████████████████████████▉     | 36211/42525 [1:09:01<12:58,  8.11it/s]

 85%|████████████████████████████▉     | 36212/42525 [1:09:01<13:39,  7.70it/s]

 85%|████████████████████████████▉     | 36215/42525 [1:09:02<11:58,  8.78it/s]

 85%|████████████████████████████▉     | 36218/42525 [1:09:02<11:56,  8.80it/s]

 85%|████████████████████████████▉     | 36220/42525 [1:09:02<12:43,  8.26it/s]

 85%|████████████████████████████▉     | 36223/42525 [1:09:03<12:22,  8.49it/s]

 85%|████████████████████████████▉     | 36225/42525 [1:09:03<12:08,  8.65it/s]

 85%|████████████████████████████▉     | 36228/42525 [1:09:03<11:13,  9.36it/s]

 85%|████████████████████████████▉     | 36231/42525 [1:09:04<11:01,  9.52it/s]

 85%|████████████████████████████▉     | 36233/42525 [1:09:04<12:16,  8.55it/s]

 85%|████████████████████████████▉     | 36235/42525 [1:09:04<11:47,  8.89it/s]

 85%|████████████████████████████▉     | 36238/42525 [1:09:04<11:02,  9.49it/s]

 85%|████████████████████████████▉     | 36240/42525 [1:09:05<10:52,  9.63it/s]

 85%|████████████████████████████▉     | 36242/42525 [1:09:05<12:03,  8.69it/s]

 85%|████████████████████████████▉     | 36244/42525 [1:09:05<11:33,  9.05it/s]

 85%|████████████████████████████▉     | 36246/42525 [1:09:05<11:02,  9.48it/s]

 85%|████████████████████████████▉     | 36249/42525 [1:09:06<11:01,  9.49it/s]

 85%|████████████████████████████▉     | 36250/42525 [1:09:06<10:55,  9.57it/s]

 85%|████████████████████████████▉     | 36253/42525 [1:09:06<10:57,  9.53it/s]

 85%|████████████████████████████▉     | 36255/42525 [1:09:06<12:07,  8.61it/s]

 85%|████████████████████████████▉     | 36257/42525 [1:09:06<11:56,  8.75it/s]

 85%|████████████████████████████▉     | 36259/42525 [1:09:07<12:26,  8.39it/s]

 85%|████████████████████████████▉     | 36262/42525 [1:09:07<11:12,  9.31it/s]

 85%|████████████████████████████▉     | 36265/42525 [1:09:07<11:27,  9.11it/s]

 85%|████████████████████████████▉     | 36267/42525 [1:09:08<11:34,  9.01it/s]

 85%|████████████████████████████▉     | 36269/42525 [1:09:08<11:16,  9.25it/s]

 85%|████████████████████████████▉     | 36271/42525 [1:09:08<10:57,  9.51it/s]

 85%|█████████████████████████████     | 36273/42525 [1:09:08<11:44,  8.88it/s]

 85%|█████████████████████████████     | 36276/42525 [1:09:09<12:13,  8.52it/s]

 85%|█████████████████████████████     | 36279/42525 [1:09:09<11:44,  8.86it/s]

 85%|█████████████████████████████     | 36281/42525 [1:09:09<11:21,  9.17it/s]

 85%|█████████████████████████████     | 36284/42525 [1:09:09<11:51,  8.77it/s]

 85%|█████████████████████████████     | 36287/42525 [1:09:10<11:05,  9.38it/s]

 85%|█████████████████████████████     | 36289/42525 [1:09:10<11:09,  9.32it/s]

 85%|█████████████████████████████     | 36292/42525 [1:09:10<11:52,  8.75it/s]

 85%|█████████████████████████████     | 36294/42525 [1:09:11<11:25,  9.09it/s]

 85%|█████████████████████████████     | 36296/42525 [1:09:11<11:59,  8.65it/s]

 85%|█████████████████████████████     | 36297/42525 [1:09:11<11:46,  8.82it/s]

 85%|█████████████████████████████     | 36300/42525 [1:09:11<12:29,  8.31it/s]

 85%|█████████████████████████████     | 36302/42525 [1:09:12<12:49,  8.09it/s]

 85%|█████████████████████████████     | 36305/42525 [1:09:12<12:37,  8.21it/s]

 85%|█████████████████████████████     | 36308/42525 [1:09:12<11:59,  8.65it/s]

 85%|█████████████████████████████     | 36310/42525 [1:09:12<11:22,  9.11it/s]

 85%|█████████████████████████████     | 36312/42525 [1:09:13<11:03,  9.37it/s]

 85%|█████████████████████████████     | 36314/42525 [1:09:13<11:58,  8.65it/s]

 85%|█████████████████████████████     | 36316/42525 [1:09:13<11:40,  8.86it/s]

 85%|█████████████████████████████     | 36319/42525 [1:09:13<11:01,  9.39it/s]

 85%|█████████████████████████████     | 36323/42525 [1:09:14<10:31,  9.82it/s]

 85%|█████████████████████████████     | 36326/42525 [1:09:14<10:15, 10.08it/s]

 85%|█████████████████████████████     | 36328/42525 [1:09:14<10:10, 10.15it/s]

 85%|█████████████████████████████     | 36331/42525 [1:09:15<11:23,  9.06it/s]

 85%|█████████████████████████████     | 36333/42525 [1:09:15<12:16,  8.41it/s]

 85%|█████████████████████████████     | 36335/42525 [1:09:15<11:46,  8.77it/s]

 85%|█████████████████████████████     | 36337/42525 [1:09:15<11:48,  8.74it/s]

 85%|█████████████████████████████     | 36339/42525 [1:09:16<11:51,  8.69it/s]

 85%|█████████████████████████████     | 36341/42525 [1:09:16<12:46,  8.07it/s]

 85%|█████████████████████████████     | 36343/42525 [1:09:16<11:55,  8.64it/s]

 85%|█████████████████████████████     | 36345/42525 [1:09:16<12:14,  8.41it/s]

 85%|█████████████████████████████     | 36347/42525 [1:09:17<12:17,  8.38it/s]

 85%|█████████████████████████████     | 36349/42525 [1:09:17<12:00,  8.57it/s]

 85%|█████████████████████████████     | 36352/42525 [1:09:17<10:54,  9.43it/s]

 85%|█████████████████████████████     | 36355/42525 [1:09:17<10:31,  9.77it/s]

 85%|█████████████████████████████     | 36358/42525 [1:09:18<10:52,  9.46it/s]

 86%|█████████████████████████████     | 36361/42525 [1:09:18<10:23,  9.88it/s]

 86%|█████████████████████████████     | 36362/42525 [1:09:18<11:21,  9.04it/s]

 86%|█████████████████████████████     | 36365/42525 [1:09:18<10:53,  9.43it/s]

 86%|█████████████████████████████     | 36367/42525 [1:09:19<10:58,  9.36it/s]

 86%|█████████████████████████████     | 36369/42525 [1:09:19<11:43,  8.76it/s]

 86%|█████████████████████████████     | 36371/42525 [1:09:19<11:38,  8.81it/s]

 86%|█████████████████████████████     | 36374/42525 [1:09:19<10:50,  9.45it/s]

 86%|█████████████████████████████     | 36376/42525 [1:09:20<11:07,  9.21it/s]

 86%|█████████████████████████████     | 36378/42525 [1:09:20<12:11,  8.40it/s]

 86%|█████████████████████████████     | 36380/42525 [1:09:20<12:21,  8.28it/s]

 86%|█████████████████████████████     | 36382/42525 [1:09:20<11:37,  8.81it/s]

 86%|█████████████████████████████     | 36384/42525 [1:09:21<13:26,  7.61it/s]

 86%|█████████████████████████████     | 36386/42525 [1:09:21<13:08,  7.79it/s]

 86%|█████████████████████████████     | 36389/42525 [1:09:21<11:36,  8.81it/s]

 86%|█████████████████████████████     | 36391/42525 [1:09:21<11:34,  8.83it/s]

 86%|█████████████████████████████     | 36393/42525 [1:09:22<12:24,  8.23it/s]

 86%|█████████████████████████████     | 36396/42525 [1:09:22<11:03,  9.24it/s]

 86%|█████████████████████████████     | 36398/42525 [1:09:22<11:41,  8.74it/s]

 86%|█████████████████████████████     | 36400/42525 [1:09:22<11:57,  8.54it/s]

 86%|█████████████████████████████     | 36402/42525 [1:09:23<12:24,  8.22it/s]

 86%|█████████████████████████████     | 36404/42525 [1:09:23<11:38,  8.77it/s]

 86%|█████████████████████████████     | 36407/42525 [1:09:23<12:00,  8.49it/s]

 86%|█████████████████████████████     | 36409/42525 [1:09:24<11:14,  9.07it/s]

 86%|█████████████████████████████     | 36410/42525 [1:09:24<11:42,  8.71it/s]

 86%|█████████████████████████████     | 36413/42525 [1:09:24<12:21,  8.25it/s]

 86%|█████████████████████████████     | 36415/42525 [1:09:24<12:38,  8.05it/s]

 86%|█████████████████████████████     | 36417/42525 [1:09:24<11:30,  8.85it/s]

 86%|█████████████████████████████     | 36421/42525 [1:09:25<10:23,  9.78it/s]

 86%|█████████████████████████████     | 36423/42525 [1:09:25<10:33,  9.63it/s]

 86%|█████████████████████████████     | 36425/42525 [1:09:25<11:17,  9.01it/s]

 86%|█████████████████████████████     | 36427/42525 [1:09:26<11:12,  9.07it/s]

 86%|█████████████████████████████▏    | 36429/42525 [1:09:26<11:13,  9.05it/s]

 86%|█████████████████████████████▏    | 36431/42525 [1:09:26<11:36,  8.75it/s]

 86%|█████████████████████████████▏    | 36433/42525 [1:09:26<12:11,  8.32it/s]

 86%|█████████████████████████████▏    | 36436/42525 [1:09:27<12:12,  8.31it/s]

 86%|█████████████████████████████▏    | 36437/42525 [1:09:27<11:46,  8.62it/s]

 86%|█████████████████████████████▏    | 36440/42525 [1:09:27<12:50,  7.90it/s]

 86%|█████████████████████████████▏    | 36443/42525 [1:09:27<12:03,  8.41it/s]

 86%|█████████████████████████████▏    | 36444/42525 [1:09:28<11:41,  8.67it/s]

 86%|█████████████████████████████▏    | 36447/42525 [1:09:28<11:12,  9.04it/s]

 86%|█████████████████████████████▏    | 36448/42525 [1:09:28<12:08,  8.34it/s]

 86%|█████████████████████████████▏    | 36451/42525 [1:09:28<11:13,  9.02it/s]

 86%|█████████████████████████████▏    | 36454/42525 [1:09:29<10:39,  9.50it/s]

 86%|█████████████████████████████▏    | 36456/42525 [1:09:29<10:36,  9.53it/s]

 86%|█████████████████████████████▏    | 36459/42525 [1:09:29<10:22,  9.75it/s]

 86%|█████████████████████████████▏    | 36461/42525 [1:09:29<11:19,  8.93it/s]

 86%|█████████████████████████████▏    | 36463/42525 [1:09:30<11:10,  9.04it/s]

 86%|█████████████████████████████▏    | 36464/42525 [1:09:30<12:16,  8.23it/s]

 86%|█████████████████████████████▏    | 36467/42525 [1:09:30<11:55,  8.46it/s]

 86%|█████████████████████████████▏    | 36469/42525 [1:09:30<12:36,  8.00it/s]

 86%|█████████████████████████████▏    | 36472/42525 [1:09:31<11:25,  8.83it/s]

 86%|█████████████████████████████▏    | 36474/42525 [1:09:31<11:07,  9.06it/s]

 86%|█████████████████████████████▏    | 36476/42525 [1:09:31<10:56,  9.22it/s]

 86%|█████████████████████████████▏    | 36478/42525 [1:09:31<11:01,  9.14it/s]

 86%|█████████████████████████████▏    | 36480/42525 [1:09:32<11:06,  9.07it/s]

 86%|█████████████████████████████▏    | 36483/42525 [1:09:32<10:30,  9.58it/s]

 86%|█████████████████████████████▏    | 36485/42525 [1:09:32<11:16,  8.92it/s]

 86%|█████████████████████████████▏    | 36488/42525 [1:09:32<10:52,  9.25it/s]

 86%|█████████████████████████████▏    | 36489/42525 [1:09:33<10:51,  9.26it/s]

 86%|█████████████████████████████▏    | 36492/42525 [1:09:33<11:11,  8.98it/s]

 86%|█████████████████████████████▏    | 36494/42525 [1:09:33<11:32,  8.71it/s]

 86%|█████████████████████████████▏    | 36496/42525 [1:09:33<10:57,  9.17it/s]

 86%|█████████████████████████████▏    | 36500/42525 [1:09:34<10:24,  9.65it/s]

 86%|█████████████████████████████▏    | 36502/42525 [1:09:34<11:23,  8.81it/s]

 86%|█████████████████████████████▏    | 36505/42525 [1:09:34<11:10,  8.98it/s]

 86%|█████████████████████████████▏    | 36508/42525 [1:09:35<11:17,  8.88it/s]

 86%|█████████████████████████████▏    | 36510/42525 [1:09:35<10:48,  9.27it/s]

 86%|█████████████████████████████▏    | 36513/42525 [1:09:35<11:16,  8.88it/s]

 86%|█████████████████████████████▏    | 36515/42525 [1:09:35<12:01,  8.33it/s]

 86%|█████████████████████████████▏    | 36518/42525 [1:09:36<11:09,  8.97it/s]

 86%|█████████████████████████████▏    | 36520/42525 [1:09:36<11:46,  8.50it/s]

 86%|█████████████████████████████▏    | 36523/42525 [1:09:36<10:38,  9.39it/s]

 86%|█████████████████████████████▏    | 36526/42525 [1:09:37<11:20,  8.82it/s]

 86%|█████████████████████████████▏    | 36528/42525 [1:09:37<11:00,  9.08it/s]

 86%|█████████████████████████████▏    | 36530/42525 [1:09:37<10:47,  9.26it/s]

 86%|█████████████████████████████▏    | 36533/42525 [1:09:37<11:20,  8.81it/s]

 86%|█████████████████████████████▏    | 36535/42525 [1:09:38<10:48,  9.23it/s]

 86%|█████████████████████████████▏    | 36539/42525 [1:09:38<10:19,  9.66it/s]

 86%|█████████████████████████████▏    | 36542/42525 [1:09:38<11:03,  9.02it/s]

 86%|█████████████████████████████▏    | 36544/42525 [1:09:39<11:06,  8.97it/s]

 86%|█████████████████████████████▏    | 36546/42525 [1:09:39<12:11,  8.17it/s]

 86%|█████████████████████████████▏    | 36548/42525 [1:09:39<12:13,  8.14it/s]

 86%|█████████████████████████████▏    | 36550/42525 [1:09:39<11:29,  8.67it/s]

 86%|█████████████████████████████▏    | 36552/42525 [1:09:40<11:02,  9.02it/s]

 86%|█████████████████████████████▏    | 36554/42525 [1:09:40<11:58,  8.31it/s]

 86%|█████████████████████████████▏    | 36558/42525 [1:09:40<10:20,  9.61it/s]

 86%|█████████████████████████████▏    | 36559/42525 [1:09:40<10:52,  9.15it/s]

 86%|█████████████████████████████▏    | 36563/42525 [1:09:41<10:39,  9.32it/s]

 86%|█████████████████████████████▏    | 36566/42525 [1:09:41<10:09,  9.77it/s]

 86%|█████████████████████████████▏    | 36570/42525 [1:09:41<09:45, 10.16it/s]

 86%|█████████████████████████████▏    | 36572/42525 [1:09:42<09:39, 10.27it/s]

 86%|█████████████████████████████▏    | 36574/42525 [1:09:42<09:53, 10.02it/s]

 86%|█████████████████████████████▏    | 36577/42525 [1:09:42<10:25,  9.52it/s]

 86%|█████████████████████████████▏    | 36579/42525 [1:09:42<10:33,  9.38it/s]

 86%|█████████████████████████████▏    | 36581/42525 [1:09:43<11:12,  8.83it/s]

 86%|█████████████████████████████▏    | 36584/42525 [1:09:43<10:55,  9.06it/s]

 86%|█████████████████████████████▎    | 36586/42525 [1:09:43<11:49,  8.37it/s]

 86%|█████████████████████████████▎    | 36589/42525 [1:09:44<10:32,  9.38it/s]

 86%|█████████████████████████████▎    | 36591/42525 [1:09:44<11:06,  8.90it/s]

 86%|█████████████████████████████▎    | 36594/42525 [1:09:44<11:27,  8.63it/s]

 86%|█████████████████████████████▎    | 36597/42525 [1:09:44<10:43,  9.21it/s]

 86%|█████████████████████████████▎    | 36600/42525 [1:09:45<10:31,  9.38it/s]

 86%|█████████████████████████████▎    | 36602/42525 [1:09:45<11:15,  8.76it/s]

 86%|█████████████████████████████▎    | 36604/42525 [1:09:45<12:33,  7.86it/s]

 86%|█████████████████████████████▎    | 36608/42525 [1:09:46<10:40,  9.23it/s]

 86%|█████████████████████████████▎    | 36610/42525 [1:09:46<11:10,  8.82it/s]

 86%|█████████████████████████████▎    | 36614/42525 [1:09:46<10:14,  9.62it/s]

 86%|█████████████████████████████▎    | 36617/42525 [1:09:47<10:12,  9.65it/s]

 86%|█████████████████████████████▎    | 36620/42525 [1:09:47<11:12,  8.78it/s]

 86%|█████████████████████████████▎    | 36622/42525 [1:09:47<11:24,  8.62it/s]

 86%|█████████████████████████████▎    | 36623/42525 [1:09:47<11:07,  8.84it/s]

 86%|█████████████████████████████▎    | 36627/42525 [1:09:48<10:28,  9.38it/s]

 86%|█████████████████████████████▎    | 36629/42525 [1:09:48<10:57,  8.97it/s]

 86%|█████████████████████████████▎    | 36631/42525 [1:09:48<11:28,  8.56it/s]

 86%|█████████████████████████████▎    | 36633/42525 [1:09:48<10:48,  9.09it/s]

 86%|█████████████████████████████▎    | 36635/42525 [1:09:49<11:22,  8.64it/s]

 86%|█████████████████████████████▎    | 36638/42525 [1:09:49<11:30,  8.53it/s]

 86%|█████████████████████████████▎    | 36640/42525 [1:09:49<10:40,  9.19it/s]

 86%|█████████████████████████████▎    | 36644/42525 [1:09:50<10:14,  9.57it/s]

 86%|█████████████████████████████▎    | 36646/42525 [1:09:50<10:49,  9.05it/s]

 86%|█████████████████████████████▎    | 36648/42525 [1:09:50<10:52,  9.01it/s]

 86%|█████████████████████████████▎    | 36650/42525 [1:09:50<10:35,  9.24it/s]

 86%|█████████████████████████████▎    | 36652/42525 [1:09:51<10:43,  9.13it/s]

 86%|█████████████████████████████▎    | 36655/42525 [1:09:51<10:39,  9.18it/s]

 86%|█████████████████████████████▎    | 36658/42525 [1:09:51<10:15,  9.53it/s]

 86%|█████████████████████████████▎    | 36661/42525 [1:09:52<10:48,  9.04it/s]

 86%|█████████████████████████████▎    | 36664/42525 [1:09:52<10:39,  9.16it/s]

 86%|█████████████████████████████▎    | 36666/42525 [1:09:52<10:42,  9.13it/s]

 86%|█████████████████████████████▎    | 36669/42525 [1:09:52<10:04,  9.68it/s]

 86%|█████████████████████████████▎    | 36672/42525 [1:09:53<09:56,  9.81it/s]

 86%|█████████████████████████████▎    | 36674/42525 [1:09:53<10:05,  9.66it/s]

 86%|█████████████████████████████▎    | 36675/42525 [1:09:53<11:01,  8.85it/s]

 86%|█████████████████████████████▎    | 36678/42525 [1:09:53<11:15,  8.66it/s]

 86%|█████████████████████████████▎    | 36681/42525 [1:09:54<11:32,  8.44it/s]

 86%|█████████████████████████████▎    | 36682/42525 [1:09:54<11:07,  8.75it/s]

 86%|█████████████████████████████▎    | 36684/42525 [1:09:54<11:23,  8.54it/s]

 86%|█████████████████████████████▎    | 36687/42525 [1:09:54<11:21,  8.57it/s]

 86%|█████████████████████████████▎    | 36688/42525 [1:09:55<11:07,  8.75it/s]

 86%|█████████████████████████████▎    | 36692/42525 [1:09:55<10:30,  9.26it/s]

 86%|█████████████████████████████▎    | 36694/42525 [1:09:55<11:33,  8.41it/s]

 86%|█████████████████████████████▎    | 36696/42525 [1:09:55<11:09,  8.71it/s]

 86%|█████████████████████████████▎    | 36698/42525 [1:09:56<10:34,  9.19it/s]

 86%|█████████████████████████████▎    | 36702/42525 [1:09:56<10:28,  9.27it/s]

 86%|█████████████████████████████▎    | 36704/42525 [1:09:56<10:55,  8.88it/s]

 86%|█████████████████████████████▎    | 36708/42525 [1:09:57<10:31,  9.21it/s]

 86%|█████████████████████████████▎    | 36712/42525 [1:09:57<10:26,  9.28it/s]

 86%|█████████████████████████████▎    | 36715/42525 [1:09:58<10:33,  9.17it/s]

 86%|█████████████████████████████▎    | 36718/42525 [1:09:58<10:00,  9.68it/s]

 86%|█████████████████████████████▎    | 36721/42525 [1:09:58<09:57,  9.71it/s]

 86%|█████████████████████████████▎    | 36723/42525 [1:09:58<10:14,  9.43it/s]

 86%|█████████████████████████████▎    | 36725/42525 [1:09:59<10:56,  8.83it/s]

 86%|█████████████████████████████▎    | 36727/42525 [1:09:59<11:55,  8.10it/s]

 86%|█████████████████████████████▎    | 36729/42525 [1:09:59<11:10,  8.65it/s]

 86%|█████████████████████████████▎    | 36731/42525 [1:09:59<10:33,  9.15it/s]

 86%|█████████████████████████████▎    | 36733/42525 [1:10:00<10:11,  9.47it/s]

 86%|█████████████████████████████▎    | 36734/42525 [1:10:00<10:14,  9.42it/s]

 86%|█████████████████████████████▎    | 36738/42525 [1:10:00<10:23,  9.27it/s]

 86%|█████████████████████████████▎    | 36740/42525 [1:10:00<11:35,  8.32it/s]

 86%|█████████████████████████████▍    | 36743/42525 [1:10:01<10:31,  9.15it/s]

 86%|█████████████████████████████▍    | 36746/42525 [1:10:01<10:23,  9.28it/s]

 86%|█████████████████████████████▍    | 36748/42525 [1:10:01<10:25,  9.23it/s]

 86%|█████████████████████████████▍    | 36751/42525 [1:10:02<11:10,  8.62it/s]

 86%|█████████████████████████████▍    | 36753/42525 [1:10:02<10:51,  8.85it/s]

 86%|█████████████████████████████▍    | 36755/42525 [1:10:02<12:23,  7.76it/s]

 86%|█████████████████████████████▍    | 36757/42525 [1:10:02<11:28,  8.37it/s]

 86%|█████████████████████████████▍    | 36758/42525 [1:10:02<10:56,  8.78it/s]

 86%|█████████████████████████████▍    | 36761/42525 [1:10:03<11:48,  8.14it/s]

 86%|█████████████████████████████▍    | 36763/42525 [1:10:03<12:01,  7.98it/s]

 86%|█████████████████████████████▍    | 36765/42525 [1:10:03<11:57,  8.03it/s]

 86%|█████████████████████████████▍    | 36767/42525 [1:10:03<11:33,  8.30it/s]

 86%|█████████████████████████████▍    | 36769/42525 [1:10:04<11:44,  8.16it/s]

 86%|█████████████████████████████▍    | 36771/42525 [1:10:04<11:25,  8.39it/s]

 86%|█████████████████████████████▍    | 36773/42525 [1:10:04<11:09,  8.59it/s]

 86%|█████████████████████████████▍    | 36775/42525 [1:10:04<10:49,  8.85it/s]

 86%|█████████████████████████████▍    | 36777/42525 [1:10:05<10:42,  8.95it/s]

 86%|█████████████████████████████▍    | 36779/42525 [1:10:05<10:14,  9.35it/s]

 86%|█████████████████████████████▍    | 36781/42525 [1:10:05<10:06,  9.47it/s]

 86%|█████████████████████████████▍    | 36783/42525 [1:10:05<10:52,  8.80it/s]

 87%|█████████████████████████████▍    | 36785/42525 [1:10:06<11:02,  8.67it/s]

 87%|█████████████████████████████▍    | 36788/42525 [1:10:06<10:20,  9.24it/s]

 87%|█████████████████████████████▍    | 36790/42525 [1:10:06<11:34,  8.26it/s]

 87%|█████████████████████████████▍    | 36793/42525 [1:10:06<11:19,  8.44it/s]

 87%|█████████████████████████████▍    | 36796/42525 [1:10:07<10:38,  8.97it/s]

 87%|█████████████████████████████▍    | 36798/42525 [1:10:07<11:24,  8.36it/s]

 87%|█████████████████████████████▍    | 36800/42525 [1:10:07<11:57,  7.98it/s]

 87%|█████████████████████████████▍    | 36801/42525 [1:10:07<12:32,  7.60it/s]

 87%|█████████████████████████████▍    | 36803/42525 [1:10:08<11:33,  8.26it/s]

 87%|█████████████████████████████▍    | 36805/42525 [1:10:08<10:50,  8.79it/s]

 87%|█████████████████████████████▍    | 36808/42525 [1:10:08<10:32,  9.04it/s]

 87%|█████████████████████████████▍    | 36810/42525 [1:10:08<10:23,  9.17it/s]

 87%|█████████████████████████████▍    | 36812/42525 [1:10:09<10:53,  8.75it/s]

 87%|█████████████████████████████▍    | 36814/42525 [1:10:09<11:51,  8.03it/s]

 87%|█████████████████████████████▍    | 36816/42525 [1:10:09<10:54,  8.72it/s]

 87%|█████████████████████████████▍    | 36818/42525 [1:10:09<11:03,  8.61it/s]

 87%|█████████████████████████████▍    | 36820/42525 [1:10:10<10:41,  8.89it/s]

 87%|█████████████████████████████▍    | 36823/42525 [1:10:10<10:39,  8.92it/s]

 87%|█████████████████████████████▍    | 36825/42525 [1:10:10<10:25,  9.12it/s]

 87%|█████████████████████████████▍    | 36827/42525 [1:10:10<10:18,  9.21it/s]

 87%|█████████████████████████████▍    | 36829/42525 [1:10:11<10:38,  8.92it/s]

 87%|█████████████████████████████▍    | 36831/42525 [1:10:11<11:17,  8.40it/s]

 87%|█████████████████████████████▍    | 36833/42525 [1:10:11<11:25,  8.30it/s]

 87%|█████████████████████████████▍    | 36836/42525 [1:10:11<10:59,  8.63it/s]

 87%|█████████████████████████████▍    | 36838/42525 [1:10:12<10:25,  9.09it/s]

 87%|█████████████████████████████▍    | 36841/42525 [1:10:12<10:24,  9.11it/s]

 87%|█████████████████████████████▍    | 36844/42525 [1:10:12<09:59,  9.48it/s]

 87%|█████████████████████████████▍    | 36845/42525 [1:10:12<09:59,  9.47it/s]

 87%|█████████████████████████████▍    | 36848/42525 [1:10:13<10:35,  8.94it/s]

 87%|█████████████████████████████▍    | 36851/42525 [1:10:13<10:14,  9.24it/s]

 87%|█████████████████████████████▍    | 36853/42525 [1:10:13<10:31,  8.98it/s]

 87%|█████████████████████████████▍    | 36855/42525 [1:10:14<11:27,  8.25it/s]

 87%|█████████████████████████████▍    | 36857/42525 [1:10:14<10:55,  8.64it/s]

 87%|█████████████████████████████▍    | 36859/42525 [1:10:14<10:59,  8.60it/s]

 87%|█████████████████████████████▍    | 36861/42525 [1:10:14<11:49,  7.98it/s]

 87%|█████████████████████████████▍    | 36865/42525 [1:10:15<10:18,  9.15it/s]

 87%|█████████████████████████████▍    | 36867/42525 [1:10:15<10:51,  8.69it/s]

 87%|█████████████████████████████▍    | 36869/42525 [1:10:15<11:26,  8.24it/s]

 87%|█████████████████████████████▍    | 36871/42525 [1:10:15<12:06,  7.78it/s]

 87%|█████████████████████████████▍    | 36873/42525 [1:10:16<11:16,  8.35it/s]

 87%|█████████████████████████████▍    | 36875/42525 [1:10:16<10:41,  8.80it/s]

 87%|█████████████████████████████▍    | 36876/42525 [1:10:16<10:23,  9.05it/s]

 87%|█████████████████████████████▍    | 36878/42525 [1:10:16<09:57,  9.45it/s]

 87%|█████████████████████████████▍    | 36882/42525 [1:10:17<10:09,  9.26it/s]

 87%|█████████████████████████████▍    | 36886/42525 [1:10:17<10:09,  9.26it/s]

 87%|█████████████████████████████▍    | 36888/42525 [1:10:17<10:57,  8.57it/s]

 87%|█████████████████████████████▍    | 36890/42525 [1:10:18<11:42,  8.02it/s]

 87%|█████████████████████████████▍    | 36892/42525 [1:10:18<11:23,  8.24it/s]

 87%|█████████████████████████████▍    | 36894/42525 [1:10:18<12:15,  7.66it/s]

 87%|█████████████████████████████▍    | 36896/42525 [1:10:18<11:18,  8.29it/s]

 87%|█████████████████████████████▌    | 36898/42525 [1:10:19<11:19,  8.28it/s]

 87%|█████████████████████████████▌    | 36900/42525 [1:10:19<11:12,  8.37it/s]

 87%|█████████████████████████████▌    | 36902/42525 [1:10:19<10:47,  8.68it/s]

 87%|█████████████████████████████▌    | 36904/42525 [1:10:19<11:07,  8.42it/s]

 87%|█████████████████████████████▌    | 36906/42525 [1:10:20<10:47,  8.68it/s]

 87%|█████████████████████████████▌    | 36908/42525 [1:10:20<10:15,  9.13it/s]

 87%|█████████████████████████████▌    | 36909/42525 [1:10:20<10:36,  8.82it/s]

 87%|█████████████████████████████▌    | 36912/42525 [1:10:20<10:16,  9.10it/s]

 87%|█████████████████████████████▌    | 36914/42525 [1:10:20<10:26,  8.95it/s]

 87%|█████████████████████████████▌    | 36916/42525 [1:10:21<10:05,  9.27it/s]

 87%|█████████████████████████████▌    | 36918/42525 [1:10:21<10:08,  9.21it/s]

 87%|█████████████████████████████▌    | 36920/42525 [1:10:21<09:53,  9.44it/s]

 87%|█████████████████████████████▌    | 36922/42525 [1:10:21<10:00,  9.32it/s]

 87%|█████████████████████████████▌    | 36924/42525 [1:10:22<11:29,  8.13it/s]

 87%|█████████████████████████████▌    | 36926/42525 [1:10:22<10:48,  8.63it/s]

 87%|█████████████████████████████▌    | 36928/42525 [1:10:22<10:20,  9.02it/s]

 87%|█████████████████████████████▌    | 36930/42525 [1:10:22<10:54,  8.54it/s]

 87%|█████████████████████████████▌    | 36932/42525 [1:10:22<10:54,  8.55it/s]

 87%|█████████████████████████████▌    | 36934/42525 [1:10:23<10:27,  8.90it/s]

 87%|█████████████████████████████▌    | 36936/42525 [1:10:23<10:04,  9.24it/s]

 87%|█████████████████████████████▌    | 36937/42525 [1:10:23<09:54,  9.41it/s]

 87%|█████████████████████████████▌    | 36940/42525 [1:10:23<10:03,  9.25it/s]

 87%|█████████████████████████████▌    | 36942/42525 [1:10:24<10:57,  8.50it/s]

 87%|█████████████████████████████▌    | 36944/42525 [1:10:24<11:45,  7.91it/s]

 87%|█████████████████████████████▌    | 36946/42525 [1:10:24<12:41,  7.33it/s]

 87%|█████████████████████████████▌    | 36949/42525 [1:10:24<10:32,  8.81it/s]

 87%|█████████████████████████████▌    | 36951/42525 [1:10:25<11:04,  8.38it/s]

 87%|█████████████████████████████▌    | 36954/42525 [1:10:25<10:25,  8.91it/s]

 87%|█████████████████████████████▌    | 36956/42525 [1:10:25<10:12,  9.09it/s]

 87%|█████████████████████████████▌    | 36958/42525 [1:10:26<11:56,  7.77it/s]

 87%|█████████████████████████████▌    | 36960/42525 [1:10:26<12:08,  7.64it/s]

 87%|█████████████████████████████▌    | 36962/42525 [1:10:26<11:55,  7.78it/s]

 87%|█████████████████████████████▌    | 36964/42525 [1:10:26<11:01,  8.40it/s]

 87%|█████████████████████████████▌    | 36966/42525 [1:10:26<10:40,  8.68it/s]

 87%|█████████████████████████████▌    | 36968/42525 [1:10:27<10:20,  8.96it/s]

 87%|█████████████████████████████▌    | 36969/42525 [1:10:27<10:05,  9.17it/s]

 87%|█████████████████████████████▌    | 36972/42525 [1:10:27<10:50,  8.54it/s]

 87%|█████████████████████████████▌    | 36974/42525 [1:10:27<10:38,  8.69it/s]

 87%|█████████████████████████████▌    | 36976/42525 [1:10:28<10:57,  8.44it/s]

 87%|█████████████████████████████▌    | 36978/42525 [1:10:28<10:22,  8.91it/s]

 87%|█████████████████████████████▌    | 36980/42525 [1:10:28<11:50,  7.80it/s]

 87%|█████████████████████████████▌    | 36982/42525 [1:10:28<10:39,  8.67it/s]

 87%|█████████████████████████████▌    | 36984/42525 [1:10:29<10:22,  8.90it/s]

 87%|█████████████████████████████▌    | 36986/42525 [1:10:29<10:38,  8.68it/s]

 87%|█████████████████████████████▌    | 36988/42525 [1:10:29<11:09,  8.26it/s]

 87%|█████████████████████████████▌    | 36990/42525 [1:10:29<10:24,  8.87it/s]

 87%|█████████████████████████████▌    | 36993/42525 [1:10:30<10:52,  8.48it/s]

 87%|█████████████████████████████▌    | 36996/42525 [1:10:30<10:03,  9.16it/s]

 87%|█████████████████████████████▌    | 37000/42525 [1:10:30<10:02,  9.18it/s]

 87%|█████████████████████████████▌    | 37002/42525 [1:10:31<10:25,  8.83it/s]

 87%|█████████████████████████████▌    | 37005/42525 [1:10:31<10:57,  8.40it/s]

 87%|█████████████████████████████▌    | 37007/42525 [1:10:31<10:48,  8.51it/s]

 87%|█████████████████████████████▌    | 37009/42525 [1:10:31<10:54,  8.42it/s]

 87%|█████████████████████████████▌    | 37011/42525 [1:10:32<10:53,  8.43it/s]

 87%|█████████████████████████████▌    | 37013/42525 [1:10:32<10:23,  8.84it/s]

 87%|█████████████████████████████▌    | 37015/42525 [1:10:32<10:12,  8.99it/s]

 87%|█████████████████████████████▌    | 37017/42525 [1:10:32<10:06,  9.08it/s]

 87%|█████████████████████████████▌    | 37019/42525 [1:10:33<10:05,  9.09it/s]

 87%|█████████████████████████████▌    | 37021/42525 [1:10:33<10:21,  8.86it/s]

 87%|█████████████████████████████▌    | 37023/42525 [1:10:33<10:22,  8.83it/s]

 87%|█████████████████████████████▌    | 37024/42525 [1:10:33<11:12,  8.19it/s]

 87%|█████████████████████████████▌    | 37026/42525 [1:10:33<10:24,  8.80it/s]

 87%|█████████████████████████████▌    | 37029/42525 [1:10:34<10:07,  9.05it/s]

 87%|█████████████████████████████▌    | 37031/42525 [1:10:34<10:41,  8.56it/s]

 87%|█████████████████████████████▌    | 37033/42525 [1:10:34<11:37,  7.87it/s]

 87%|█████████████████████████████▌    | 37035/42525 [1:10:34<11:13,  8.15it/s]

 87%|█████████████████████████████▌    | 37037/42525 [1:10:35<11:02,  8.28it/s]

 87%|█████████████████████████████▌    | 37039/42525 [1:10:35<10:44,  8.52it/s]

 87%|█████████████████████████████▌    | 37042/42525 [1:10:35<10:21,  8.82it/s]

 87%|█████████████████████████████▌    | 37044/42525 [1:10:35<10:07,  9.03it/s]

 87%|█████████████████████████████▌    | 37046/42525 [1:10:36<10:30,  8.69it/s]

 87%|█████████████████████████████▌    | 37048/42525 [1:10:36<10:02,  9.08it/s]

 87%|█████████████████████████████▌    | 37050/42525 [1:10:36<10:02,  9.09it/s]

 87%|█████████████████████████████▌    | 37052/42525 [1:10:36<10:03,  9.06it/s]

 87%|█████████████████████████████▌    | 37053/42525 [1:10:36<09:59,  9.13it/s]

 87%|█████████████████████████████▋    | 37056/42525 [1:10:37<09:58,  9.14it/s]

 87%|█████████████████████████████▋    | 37058/42525 [1:10:37<10:16,  8.87it/s]

 87%|█████████████████████████████▋    | 37060/42525 [1:10:37<10:55,  8.34it/s]

 87%|█████████████████████████████▋    | 37062/42525 [1:10:38<10:50,  8.40it/s]

 87%|█████████████████████████████▋    | 37063/42525 [1:10:38<10:54,  8.34it/s]

 87%|█████████████████████████████▋    | 37066/42525 [1:10:38<10:32,  8.63it/s]

 87%|█████████████████████████████▋    | 37068/42525 [1:10:38<10:12,  8.90it/s]

 87%|█████████████████████████████▋    | 37070/42525 [1:10:38<10:50,  8.38it/s]

 87%|█████████████████████████████▋    | 37072/42525 [1:10:39<11:04,  8.20it/s]

 87%|█████████████████████████████▋    | 37075/42525 [1:10:39<10:16,  8.85it/s]

 87%|█████████████████████████████▋    | 37077/42525 [1:10:39<09:54,  9.16it/s]

 87%|█████████████████████████████▋    | 37080/42525 [1:10:40<09:35,  9.47it/s]

 87%|█████████████████████████████▋    | 37083/42525 [1:10:40<09:13,  9.83it/s]

 87%|█████████████████████████████▋    | 37085/42525 [1:10:40<10:18,  8.79it/s]

 87%|█████████████████████████████▋    | 37088/42525 [1:10:40<10:14,  8.85it/s]

 87%|█████████████████████████████▋    | 37090/42525 [1:10:41<11:40,  7.76it/s]

 87%|█████████████████████████████▋    | 37092/42525 [1:10:41<10:43,  8.44it/s]

 87%|█████████████████████████████▋    | 37094/42525 [1:10:41<10:23,  8.71it/s]

 87%|█████████████████████████████▋    | 37095/42525 [1:10:41<10:11,  8.89it/s]

 87%|█████████████████████████████▋    | 37097/42525 [1:10:41<09:55,  9.12it/s]

 87%|█████████████████████████████▋    | 37100/42525 [1:10:42<09:38,  9.38it/s]

 87%|█████████████████████████████▋    | 37102/42525 [1:10:42<09:26,  9.58it/s]

 87%|█████████████████████████████▋    | 37105/42525 [1:10:42<09:11,  9.83it/s]

 87%|█████████████████████████████▋    | 37107/42525 [1:10:43<09:38,  9.36it/s]

 87%|█████████████████████████████▋    | 37109/42525 [1:10:43<10:10,  8.87it/s]

 87%|█████████████████████████████▋    | 37111/42525 [1:10:43<10:40,  8.45it/s]

 87%|█████████████████████████████▋    | 37114/42525 [1:10:43<09:38,  9.35it/s]

 87%|█████████████████████████████▋    | 37118/42525 [1:10:44<09:10,  9.83it/s]

 87%|█████████████████████████████▋    | 37121/42525 [1:10:44<10:04,  8.94it/s]

 87%|█████████████████████████████▋    | 37124/42525 [1:10:44<09:42,  9.27it/s]

 87%|█████████████████████████████▋    | 37127/42525 [1:10:45<09:25,  9.54it/s]

 87%|█████████████████████████████▋    | 37129/42525 [1:10:45<09:27,  9.50it/s]

 87%|█████████████████████████████▋    | 37131/42525 [1:10:45<09:32,  9.42it/s]

 87%|█████████████████████████████▋    | 37133/42525 [1:10:45<09:29,  9.46it/s]

 87%|█████████████████████████████▋    | 37135/42525 [1:10:46<09:24,  9.54it/s]

 87%|█████████████████████████████▋    | 37137/42525 [1:10:46<09:15,  9.70it/s]

 87%|█████████████████████████████▋    | 37139/42525 [1:10:46<10:31,  8.53it/s]

 87%|█████████████████████████████▋    | 37141/42525 [1:10:46<11:07,  8.06it/s]

 87%|█████████████████████████████▋    | 37143/42525 [1:10:46<10:16,  8.73it/s]

 87%|█████████████████████████████▋    | 37145/42525 [1:10:47<10:03,  8.92it/s]

 87%|█████████████████████████████▋    | 37147/42525 [1:10:47<10:56,  8.19it/s]

 87%|█████████████████████████████▋    | 37149/42525 [1:10:47<09:55,  9.03it/s]

 87%|█████████████████████████████▋    | 37152/42525 [1:10:48<10:24,  8.61it/s]

 87%|█████████████████████████████▋    | 37154/42525 [1:10:48<10:07,  8.84it/s]

 87%|█████████████████████████████▋    | 37156/42525 [1:10:48<09:55,  9.02it/s]

 87%|█████████████████████████████▋    | 37159/42525 [1:10:48<09:40,  9.25it/s]

 87%|█████████████████████████████▋    | 37161/42525 [1:10:49<10:05,  8.85it/s]

 87%|█████████████████████████████▋    | 37164/42525 [1:10:49<10:08,  8.81it/s]

 87%|█████████████████████████████▋    | 37166/42525 [1:10:49<10:38,  8.39it/s]

 87%|█████████████████████████████▋    | 37168/42525 [1:10:49<10:23,  8.59it/s]

 87%|█████████████████████████████▋    | 37170/42525 [1:10:50<11:07,  8.02it/s]

 87%|█████████████████████████████▋    | 37172/42525 [1:10:50<10:36,  8.41it/s]

 87%|█████████████████████████████▋    | 37174/42525 [1:10:50<10:29,  8.50it/s]

 87%|█████████████████████████████▋    | 37176/42525 [1:10:50<11:10,  7.98it/s]

 87%|█████████████████████████████▋    | 37178/42525 [1:10:51<10:36,  8.39it/s]

 87%|█████████████████████████████▋    | 37180/42525 [1:10:51<10:24,  8.56it/s]

 87%|█████████████████████████████▋    | 37182/42525 [1:10:51<11:06,  8.02it/s]

 87%|█████████████████████████████▋    | 37183/42525 [1:10:51<10:31,  8.45it/s]

 87%|█████████████████████████████▋    | 37186/42525 [1:10:51<10:25,  8.53it/s]

 87%|█████████████████████████████▋    | 37187/42525 [1:10:52<10:16,  8.65it/s]

 87%|█████████████████████████████▋    | 37190/42525 [1:10:52<10:14,  8.69it/s]

 87%|█████████████████████████████▋    | 37191/42525 [1:10:52<09:56,  8.95it/s]

 87%|█████████████████████████████▋    | 37194/42525 [1:10:52<10:02,  8.84it/s]

 87%|█████████████████████████████▋    | 37197/42525 [1:10:53<09:36,  9.24it/s]

 87%|█████████████████████████████▋    | 37199/42525 [1:10:53<10:29,  8.47it/s]

 87%|█████████████████████████████▋    | 37201/42525 [1:10:53<10:44,  8.27it/s]

 87%|█████████████████████████████▋    | 37203/42525 [1:10:53<10:07,  8.76it/s]

 87%|█████████████████████████████▋    | 37205/42525 [1:10:54<10:35,  8.37it/s]

 87%|█████████████████████████████▋    | 37207/42525 [1:10:54<10:39,  8.32it/s]

 87%|█████████████████████████████▋    | 37209/42525 [1:10:54<09:56,  8.91it/s]

 88%|█████████████████████████████▊    | 37212/42525 [1:10:54<10:20,  8.57it/s]

 88%|█████████████████████████████▊    | 37214/42525 [1:10:55<09:51,  8.99it/s]

 88%|█████████████████████████████▊    | 37216/42525 [1:10:55<09:45,  9.07it/s]

 88%|█████████████████████████████▊    | 37217/42525 [1:10:55<09:43,  9.10it/s]

 88%|█████████████████████████████▊    | 37219/42525 [1:10:55<09:26,  9.37it/s]

 88%|█████████████████████████████▊    | 37221/42525 [1:10:55<09:12,  9.60it/s]

 88%|█████████████████████████████▊    | 37224/42525 [1:10:56<09:55,  8.90it/s]

 88%|█████████████████████████████▊    | 37226/42525 [1:10:56<10:39,  8.28it/s]

 88%|█████████████████████████████▊    | 37228/42525 [1:10:56<11:57,  7.38it/s]

 88%|█████████████████████████████▊    | 37231/42525 [1:10:57<10:08,  8.70it/s]

 88%|█████████████████████████████▊    | 37235/42525 [1:10:57<09:14,  9.53it/s]

 88%|█████████████████████████████▊    | 37237/42525 [1:10:57<09:28,  9.30it/s]

 88%|█████████████████████████████▊    | 37239/42525 [1:10:58<10:59,  8.01it/s]

 88%|█████████████████████████████▊    | 37241/42525 [1:10:58<10:28,  8.41it/s]

 88%|█████████████████████████████▊    | 37243/42525 [1:10:58<10:33,  8.33it/s]

 88%|█████████████████████████████▊    | 37245/42525 [1:10:58<11:19,  7.78it/s]

 88%|█████████████████████████████▊    | 37246/42525 [1:10:58<11:55,  7.38it/s]

 88%|█████████████████████████████▊    | 37249/42525 [1:10:59<11:13,  7.83it/s]

 88%|█████████████████████████████▊    | 37251/42525 [1:10:59<10:22,  8.47it/s]

 88%|█████████████████████████████▊    | 37253/42525 [1:10:59<12:02,  7.30it/s]

 88%|█████████████████████████████▊    | 37255/42525 [1:11:00<12:18,  7.14it/s]

 88%|█████████████████████████████▊    | 37258/42525 [1:11:00<10:08,  8.66it/s]

 88%|█████████████████████████████▊    | 37260/42525 [1:11:00<09:42,  9.04it/s]

 88%|█████████████████████████████▊    | 37262/42525 [1:11:00<09:22,  9.36it/s]

 88%|█████████████████████████████▊    | 37264/42525 [1:11:01<10:48,  8.11it/s]

 88%|█████████████████████████████▊    | 37266/42525 [1:11:01<09:57,  8.80it/s]

 88%|█████████████████████████████▊    | 37268/42525 [1:11:01<11:36,  7.54it/s]

 88%|█████████████████████████████▊    | 37270/42525 [1:11:01<11:29,  7.62it/s]

 88%|█████████████████████████████▊    | 37272/42525 [1:11:02<12:00,  7.29it/s]

 88%|█████████████████████████████▊    | 37274/42525 [1:11:02<10:43,  8.16it/s]

 88%|█████████████████████████████▊    | 37276/42525 [1:11:02<11:03,  7.91it/s]

 88%|█████████████████████████████▊    | 37278/42525 [1:11:02<11:04,  7.90it/s]

 88%|█████████████████████████████▊    | 37280/42525 [1:11:03<10:58,  7.97it/s]

 88%|█████████████████████████████▊    | 37282/42525 [1:11:03<10:02,  8.71it/s]

 88%|█████████████████████████████▊    | 37285/42525 [1:11:03<09:15,  9.43it/s]

 88%|█████████████████████████████▊    | 37287/42525 [1:11:03<09:24,  9.28it/s]

 88%|█████████████████████████████▊    | 37289/42525 [1:11:04<09:27,  9.23it/s]

 88%|█████████████████████████████▊    | 37291/42525 [1:11:04<09:56,  8.78it/s]

 88%|█████████████████████████████▊    | 37294/42525 [1:11:04<09:16,  9.41it/s]

 88%|█████████████████████████████▊    | 37297/42525 [1:11:04<08:55,  9.76it/s]

 88%|█████████████████████████████▊    | 37300/42525 [1:11:05<08:53,  9.79it/s]

 88%|█████████████████████████████▊    | 37302/42525 [1:11:05<09:05,  9.57it/s]

 88%|█████████████████████████████▊    | 37304/42525 [1:11:05<09:27,  9.20it/s]

 88%|█████████████████████████████▊    | 37305/42525 [1:11:05<09:17,  9.36it/s]

 88%|█████████████████████████████▊    | 37308/42525 [1:11:06<09:26,  9.22it/s]

 88%|█████████████████████████████▊    | 37310/42525 [1:11:06<09:15,  9.39it/s]

 88%|█████████████████████████████▊    | 37313/42525 [1:11:06<09:29,  9.14it/s]

 88%|█████████████████████████████▊    | 37315/42525 [1:11:06<09:16,  9.37it/s]

 88%|█████████████████████████████▊    | 37317/42525 [1:11:07<09:03,  9.58it/s]

 88%|█████████████████████████████▊    | 37319/42525 [1:11:07<10:06,  8.58it/s]

 88%|█████████████████████████████▊    | 37321/42525 [1:11:07<09:30,  9.13it/s]

 88%|█████████████████████████████▊    | 37323/42525 [1:11:07<10:29,  8.27it/s]

 88%|█████████████████████████████▊    | 37325/42525 [1:11:08<11:24,  7.59it/s]

 88%|█████████████████████████████▊    | 37327/42525 [1:11:08<11:18,  7.66it/s]

 88%|█████████████████████████████▊    | 37328/42525 [1:11:08<10:34,  8.19it/s]

 88%|█████████████████████████████▊    | 37332/42525 [1:11:08<09:49,  8.81it/s]

 88%|█████████████████████████████▊    | 37335/42525 [1:11:09<09:32,  9.06it/s]

 88%|█████████████████████████████▊    | 37337/42525 [1:11:09<09:24,  9.20it/s]

 88%|█████████████████████████████▊    | 37340/42525 [1:11:09<09:46,  8.84it/s]

 88%|█████████████████████████████▊    | 37342/42525 [1:11:09<09:24,  9.18it/s]

 88%|█████████████████████████████▊    | 37344/42525 [1:11:10<10:17,  8.39it/s]

 88%|█████████████████████████████▊    | 37346/42525 [1:11:10<10:12,  8.46it/s]

 88%|█████████████████████████████▊    | 37349/42525 [1:11:10<09:22,  9.20it/s]

 88%|█████████████████████████████▊    | 37352/42525 [1:11:11<08:59,  9.59it/s]

 88%|█████████████████████████████▊    | 37356/42525 [1:11:11<08:36, 10.00it/s]

 88%|█████████████████████████████▊    | 37358/42525 [1:11:11<08:34, 10.05it/s]

 88%|█████████████████████████████▊    | 37361/42525 [1:11:11<08:53,  9.68it/s]

 88%|█████████████████████████████▊    | 37363/42525 [1:11:12<09:08,  9.41it/s]

 88%|█████████████████████████████▊    | 37365/42525 [1:11:12<09:40,  8.89it/s]

 88%|█████████████████████████████▉    | 37367/42525 [1:11:12<09:37,  8.93it/s]

 88%|█████████████████████████████▉    | 37369/42525 [1:11:12<10:31,  8.17it/s]

 88%|█████████████████████████████▉    | 37371/42525 [1:11:13<10:10,  8.44it/s]

 88%|█████████████████████████████▉    | 37373/42525 [1:11:13<09:40,  8.88it/s]

 88%|█████████████████████████████▉    | 37375/42525 [1:11:13<11:12,  7.66it/s]

 88%|█████████████████████████████▉    | 37378/42525 [1:11:13<10:41,  8.02it/s]

 88%|█████████████████████████████▉    | 37380/42525 [1:11:14<10:41,  8.02it/s]

 88%|█████████████████████████████▉    | 37382/42525 [1:11:14<10:48,  7.93it/s]

 88%|█████████████████████████████▉    | 37384/42525 [1:11:14<10:15,  8.36it/s]

 88%|█████████████████████████████▉    | 37386/42525 [1:11:14<11:14,  7.62it/s]

 88%|█████████████████████████████▉    | 37388/42525 [1:11:15<11:19,  7.56it/s]

 88%|█████████████████████████████▉    | 37390/42525 [1:11:15<10:01,  8.54it/s]

 88%|█████████████████████████████▉    | 37392/42525 [1:11:15<09:29,  9.01it/s]

 88%|█████████████████████████████▉    | 37393/42525 [1:11:15<09:30,  9.00it/s]

 88%|█████████████████████████████▉    | 37396/42525 [1:11:16<09:09,  9.33it/s]

 88%|█████████████████████████████▉    | 37398/42525 [1:11:16<09:29,  9.00it/s]

 88%|█████████████████████████████▉    | 37401/42525 [1:11:16<10:39,  8.02it/s]

 88%|█████████████████████████████▉    | 37403/42525 [1:11:16<09:52,  8.65it/s]

 88%|█████████████████████████████▉    | 37405/42525 [1:11:17<10:31,  8.10it/s]

 88%|█████████████████████████████▉    | 37407/42525 [1:11:17<09:44,  8.76it/s]

 88%|█████████████████████████████▉    | 37410/42525 [1:11:17<09:10,  9.28it/s]

 88%|█████████████████████████████▉    | 37412/42525 [1:11:17<09:15,  9.20it/s]

 88%|█████████████████████████████▉    | 37414/42525 [1:11:18<09:19,  9.14it/s]

 88%|█████████████████████████████▉    | 37416/42525 [1:11:18<09:12,  9.24it/s]

 88%|█████████████████████████████▉    | 37418/42525 [1:11:18<09:51,  8.64it/s]

 88%|█████████████████████████████▉    | 37420/42525 [1:11:18<10:05,  8.43it/s]

 88%|█████████████████████████████▉    | 37422/42525 [1:11:19<09:41,  8.77it/s]

 88%|█████████████████████████████▉    | 37424/42525 [1:11:19<09:44,  8.73it/s]

 88%|█████████████████████████████▉    | 37426/42525 [1:11:19<10:01,  8.47it/s]

 88%|█████████████████████████████▉    | 37428/42525 [1:11:19<09:39,  8.79it/s]

 88%|█████████████████████████████▉    | 37430/42525 [1:11:20<09:59,  8.50it/s]

 88%|█████████████████████████████▉    | 37433/42525 [1:11:20<09:09,  9.27it/s]

 88%|█████████████████████████████▉    | 37434/42525 [1:11:20<09:02,  9.39it/s]

 88%|█████████████████████████████▉    | 37437/42525 [1:11:20<09:06,  9.31it/s]

 88%|█████████████████████████████▉    | 37439/42525 [1:11:20<09:57,  8.52it/s]

 88%|█████████████████████████████▉    | 37441/42525 [1:11:21<09:49,  8.62it/s]

 88%|█████████████████████████████▉    | 37443/42525 [1:11:21<10:29,  8.08it/s]

 88%|█████████████████████████████▉    | 37445/42525 [1:11:21<09:41,  8.73it/s]

 88%|█████████████████████████████▉    | 37447/42525 [1:11:21<09:27,  8.95it/s]

 88%|█████████████████████████████▉    | 37449/42525 [1:11:22<10:22,  8.15it/s]

 88%|█████████████████████████████▉    | 37451/42525 [1:11:22<09:39,  8.76it/s]

 88%|█████████████████████████████▉    | 37454/42525 [1:11:22<09:06,  9.27it/s]

 88%|█████████████████████████████▉    | 37456/42525 [1:11:22<09:17,  9.10it/s]

 88%|█████████████████████████████▉    | 37459/42525 [1:11:23<09:07,  9.26it/s]

 88%|█████████████████████████████▉    | 37462/42525 [1:11:23<08:48,  9.57it/s]

 88%|█████████████████████████████▉    | 37464/42525 [1:11:23<09:26,  8.94it/s]

 88%|█████████████████████████████▉    | 37466/42525 [1:11:23<09:02,  9.32it/s]

 88%|█████████████████████████████▉    | 37468/42525 [1:11:24<08:53,  9.49it/s]

 88%|█████████████████████████████▉    | 37470/42525 [1:11:24<09:01,  9.34it/s]

 88%|█████████████████████████████▉    | 37473/42525 [1:11:24<08:55,  9.44it/s]

 88%|█████████████████████████████▉    | 37475/42525 [1:11:24<08:55,  9.44it/s]

 88%|█████████████████████████████▉    | 37477/42525 [1:11:25<09:43,  8.65it/s]

 88%|█████████████████████████████▉    | 37480/42525 [1:11:25<10:16,  8.19it/s]

 88%|█████████████████████████████▉    | 37481/42525 [1:11:25<10:41,  7.86it/s]

 88%|█████████████████████████████▉    | 37483/42525 [1:11:25<10:31,  7.98it/s]

 88%|█████████████████████████████▉    | 37486/42525 [1:11:26<10:15,  8.19it/s]

 88%|█████████████████████████████▉    | 37488/42525 [1:11:26<09:45,  8.60it/s]

 88%|█████████████████████████████▉    | 37491/42525 [1:11:26<09:44,  8.61it/s]

 88%|█████████████████████████████▉    | 37494/42525 [1:11:27<09:01,  9.29it/s]

 88%|█████████████████████████████▉    | 37496/42525 [1:11:27<09:26,  8.87it/s]

 88%|█████████████████████████████▉    | 37498/42525 [1:11:27<09:54,  8.46it/s]

 88%|█████████████████████████████▉    | 37500/42525 [1:11:27<10:33,  7.93it/s]

 88%|█████████████████████████████▉    | 37503/42525 [1:11:28<09:45,  8.58it/s]

 88%|█████████████████████████████▉    | 37506/42525 [1:11:28<09:01,  9.27it/s]

 88%|█████████████████████████████▉    | 37509/42525 [1:11:28<08:49,  9.47it/s]

 88%|█████████████████████████████▉    | 37511/42525 [1:11:29<08:31,  9.81it/s]

 88%|█████████████████████████████▉    | 37514/42525 [1:11:29<09:00,  9.27it/s]

 88%|█████████████████████████████▉    | 37516/42525 [1:11:29<08:49,  9.45it/s]

 88%|█████████████████████████████▉    | 37518/42525 [1:11:29<10:24,  8.01it/s]

 88%|█████████████████████████████▉    | 37520/42525 [1:11:30<10:20,  8.06it/s]

 88%|██████████████████████████████    | 37523/42525 [1:11:30<09:47,  8.52it/s]

 88%|██████████████████████████████    | 37526/42525 [1:11:30<09:40,  8.61it/s]

 88%|██████████████████████████████    | 37529/42525 [1:11:31<08:49,  9.43it/s]

 88%|██████████████████████████████    | 37531/42525 [1:11:31<09:10,  9.08it/s]

 88%|██████████████████████████████    | 37534/42525 [1:11:31<08:43,  9.54it/s]

 88%|██████████████████████████████    | 37537/42525 [1:11:32<09:39,  8.61it/s]

 88%|██████████████████████████████    | 37539/42525 [1:11:32<10:49,  7.67it/s]

 88%|██████████████████████████████    | 37541/42525 [1:11:32<10:49,  7.67it/s]

 88%|██████████████████████████████    | 37544/42525 [1:11:32<09:53,  8.40it/s]

 88%|██████████████████████████████    | 37546/42525 [1:11:33<10:35,  7.83it/s]

 88%|██████████████████████████████    | 37548/42525 [1:11:33<09:36,  8.64it/s]

 88%|██████████████████████████████    | 37550/42525 [1:11:33<09:16,  8.94it/s]

 88%|██████████████████████████████    | 37552/42525 [1:11:33<09:16,  8.93it/s]

 88%|██████████████████████████████    | 37554/42525 [1:11:34<10:12,  8.12it/s]

 88%|██████████████████████████████    | 37556/42525 [1:11:34<11:29,  7.21it/s]

 88%|██████████████████████████████    | 37558/42525 [1:11:34<11:13,  7.37it/s]

 88%|██████████████████████████████    | 37560/42525 [1:11:34<10:41,  7.74it/s]

 88%|██████████████████████████████    | 37562/42525 [1:11:35<09:50,  8.41it/s]

 88%|██████████████████████████████    | 37564/42525 [1:11:35<09:10,  9.01it/s]

 88%|██████████████████████████████    | 37568/42525 [1:11:35<08:55,  9.25it/s]

 88%|██████████████████████████████    | 37570/42525 [1:11:36<08:53,  9.29it/s]

 88%|██████████████████████████████    | 37574/42525 [1:11:36<08:28,  9.74it/s]

 88%|██████████████████████████████    | 37576/42525 [1:11:36<09:11,  8.97it/s]

 88%|██████████████████████████████    | 37578/42525 [1:11:36<09:22,  8.80it/s]

 88%|██████████████████████████████    | 37579/42525 [1:11:37<09:42,  8.49it/s]

 88%|██████████████████████████████    | 37583/42525 [1:11:37<08:47,  9.36it/s]

 88%|██████████████████████████████    | 37586/42525 [1:11:37<08:22,  9.83it/s]

 88%|██████████████████████████████    | 37589/42525 [1:11:38<08:54,  9.24it/s]

 88%|██████████████████████████████    | 37591/42525 [1:11:38<08:40,  9.48it/s]

 88%|██████████████████████████████    | 37595/42525 [1:11:38<08:09, 10.07it/s]

 88%|██████████████████████████████    | 37598/42525 [1:11:39<09:38,  8.51it/s]

 88%|██████████████████████████████    | 37599/42525 [1:11:39<09:28,  8.66it/s]

 88%|██████████████████████████████    | 37602/42525 [1:11:39<09:05,  9.02it/s]

 88%|██████████████████████████████    | 37605/42525 [1:11:39<08:48,  9.31it/s]

 88%|██████████████████████████████    | 37608/42525 [1:11:40<09:30,  8.61it/s]

 88%|██████████████████████████████    | 37610/42525 [1:11:40<10:27,  7.83it/s]

 88%|██████████████████████████████    | 37612/42525 [1:11:40<10:19,  7.93it/s]

 88%|██████████████████████████████    | 37614/42525 [1:11:40<09:33,  8.56it/s]

 88%|██████████████████████████████    | 37617/42525 [1:11:41<08:41,  9.41it/s]

 88%|██████████████████████████████    | 37618/42525 [1:11:41<08:59,  9.09it/s]

 88%|██████████████████████████████    | 37621/42525 [1:11:41<08:50,  9.24it/s]

 88%|██████████████████████████████    | 37624/42525 [1:11:41<08:49,  9.26it/s]

 88%|██████████████████████████████    | 37625/42525 [1:11:42<08:54,  9.16it/s]

 88%|██████████████████████████████    | 37627/42525 [1:11:42<09:19,  8.75it/s]

 88%|██████████████████████████████    | 37630/42525 [1:11:42<09:18,  8.77it/s]

 88%|██████████████████████████████    | 37631/42525 [1:11:42<09:55,  8.22it/s]

 88%|██████████████████████████████    | 37633/42525 [1:11:43<09:22,  8.70it/s]

 89%|██████████████████████████████    | 37637/42525 [1:11:43<08:57,  9.09it/s]

 89%|██████████████████████████████    | 37639/42525 [1:11:43<09:01,  9.02it/s]

 89%|██████████████████████████████    | 37642/42525 [1:11:44<08:42,  9.34it/s]

 89%|██████████████████████████████    | 37645/42525 [1:11:44<09:09,  8.88it/s]

 89%|██████████████████████████████    | 37647/42525 [1:11:44<09:27,  8.60it/s]

 89%|██████████████████████████████    | 37649/42525 [1:11:44<09:07,  8.91it/s]

 89%|██████████████████████████████    | 37651/42525 [1:11:45<10:00,  8.11it/s]

 89%|██████████████████████████████    | 37653/42525 [1:11:45<09:29,  8.55it/s]

 89%|██████████████████████████████    | 37655/42525 [1:11:45<08:59,  9.02it/s]

 89%|██████████████████████████████    | 37657/42525 [1:11:45<09:52,  8.22it/s]

 89%|██████████████████████████████    | 37660/42525 [1:11:46<08:49,  9.18it/s]

 89%|██████████████████████████████    | 37662/42525 [1:11:46<08:59,  9.01it/s]

 89%|██████████████████████████████    | 37664/42525 [1:11:46<09:25,  8.59it/s]

 89%|██████████████████████████████    | 37665/42525 [1:11:46<09:13,  8.79it/s]

 89%|██████████████████████████████    | 37668/42525 [1:11:47<09:06,  8.88it/s]

 89%|██████████████████████████████    | 37671/42525 [1:11:47<08:56,  9.05it/s]

 89%|██████████████████████████████    | 37674/42525 [1:11:47<08:31,  9.48it/s]

 89%|██████████████████████████████    | 37676/42525 [1:11:47<08:52,  9.11it/s]

 89%|██████████████████████████████    | 37678/42525 [1:11:48<08:47,  9.18it/s]

 89%|██████████████████████████████▏   | 37680/42525 [1:11:48<09:52,  8.17it/s]

 89%|██████████████████████████████▏   | 37682/42525 [1:11:48<09:16,  8.70it/s]

 89%|██████████████████████████████▏   | 37684/42525 [1:11:48<09:55,  8.14it/s]

 89%|██████████████████████████████▏   | 37686/42525 [1:11:49<09:13,  8.74it/s]

 89%|██████████████████████████████▏   | 37688/42525 [1:11:49<09:29,  8.49it/s]

 89%|██████████████████████████████▏   | 37690/42525 [1:11:49<09:01,  8.93it/s]

 89%|██████████████████████████████▏   | 37692/42525 [1:11:49<09:33,  8.42it/s]

 89%|██████████████████████████████▏   | 37694/42525 [1:11:50<08:59,  8.95it/s]

 89%|██████████████████████████████▏   | 37696/42525 [1:11:50<09:15,  8.69it/s]

 89%|██████████████████████████████▏   | 37698/42525 [1:11:50<09:56,  8.09it/s]

 89%|██████████████████████████████▏   | 37700/42525 [1:11:50<09:20,  8.61it/s]

 89%|██████████████████████████████▏   | 37702/42525 [1:11:50<08:44,  9.20it/s]

 89%|██████████████████████████████▏   | 37704/42525 [1:11:51<08:37,  9.32it/s]

 89%|██████████████████████████████▏   | 37706/42525 [1:11:51<09:33,  8.41it/s]

 89%|██████████████████████████████▏   | 37707/42525 [1:11:51<09:37,  8.35it/s]

 89%|██████████████████████████████▏   | 37711/42525 [1:11:51<08:33,  9.37it/s]

 89%|██████████████████████████████▏   | 37713/42525 [1:11:52<08:51,  9.05it/s]

 89%|██████████████████████████████▏   | 37715/42525 [1:11:52<08:29,  9.43it/s]

 89%|██████████████████████████████▏   | 37717/42525 [1:11:52<08:56,  8.96it/s]

 89%|██████████████████████████████▏   | 37721/42525 [1:11:52<08:21,  9.57it/s]

 89%|██████████████████████████████▏   | 37723/42525 [1:11:53<09:04,  8.82it/s]

 89%|██████████████████████████████▏   | 37726/42525 [1:11:53<08:44,  9.15it/s]

 89%|██████████████████████████████▏   | 37728/42525 [1:11:53<09:30,  8.41it/s]

 89%|██████████████████████████████▏   | 37730/42525 [1:11:54<09:10,  8.72it/s]

 89%|██████████████████████████████▏   | 37732/42525 [1:11:54<09:53,  8.07it/s]

 89%|██████████████████████████████▏   | 37734/42525 [1:11:54<09:27,  8.44it/s]

 89%|██████████████████████████████▏   | 37736/42525 [1:11:54<09:01,  8.84it/s]

 89%|██████████████████████████████▏   | 37738/42525 [1:11:54<08:49,  9.04it/s]

 89%|██████████████████████████████▏   | 37740/42525 [1:11:55<09:14,  8.64it/s]

 89%|██████████████████████████████▏   | 37742/42525 [1:11:55<09:37,  8.29it/s]

 89%|██████████████████████████████▏   | 37744/42525 [1:11:55<08:57,  8.90it/s]

 89%|██████████████████████████████▏   | 37746/42525 [1:11:55<09:10,  8.68it/s]

 89%|██████████████████████████████▏   | 37748/42525 [1:11:56<08:59,  8.85it/s]

 89%|██████████████████████████████▏   | 37750/42525 [1:11:56<09:55,  8.01it/s]

 89%|██████████████████████████████▏   | 37752/42525 [1:11:56<09:09,  8.69it/s]

 89%|██████████████████████████████▏   | 37754/42525 [1:11:56<08:51,  8.98it/s]

 89%|██████████████████████████████▏   | 37756/42525 [1:11:57<08:36,  9.23it/s]

 89%|██████████████████████████████▏   | 37758/42525 [1:11:57<09:43,  8.17it/s]

 89%|██████████████████████████████▏   | 37759/42525 [1:11:57<09:33,  8.30it/s]

 89%|██████████████████████████████▏   | 37762/42525 [1:11:57<09:17,  8.54it/s]

 89%|██████████████████████████████▏   | 37764/42525 [1:11:57<09:17,  8.54it/s]

 89%|██████████████████████████████▏   | 37767/42525 [1:11:58<08:26,  9.39it/s]

 89%|██████████████████████████████▏   | 37769/42525 [1:11:58<08:36,  9.21it/s]

 89%|██████████████████████████████▏   | 37771/42525 [1:11:58<09:26,  8.39it/s]

 89%|██████████████████████████████▏   | 37774/42525 [1:11:59<08:27,  9.36it/s]

 89%|██████████████████████████████▏   | 37777/42525 [1:11:59<07:58,  9.91it/s]

 89%|██████████████████████████████▏   | 37780/42525 [1:11:59<07:59,  9.90it/s]

 89%|██████████████████████████████▏   | 37784/42525 [1:12:00<07:44, 10.20it/s]

 89%|██████████████████████████████▏   | 37788/42525 [1:12:00<08:10,  9.66it/s]

 89%|██████████████████████████████▏   | 37790/42525 [1:12:00<08:31,  9.26it/s]

 89%|██████████████████████████████▏   | 37792/42525 [1:12:01<09:50,  8.02it/s]

 89%|██████████████████████████████▏   | 37795/42525 [1:12:01<08:57,  8.80it/s]

 89%|██████████████████████████████▏   | 37799/42525 [1:12:01<07:58,  9.88it/s]

 89%|██████████████████████████████▏   | 37802/42525 [1:12:02<07:54,  9.95it/s]

 89%|██████████████████████████████▏   | 37804/42525 [1:12:02<08:54,  8.83it/s]

 89%|██████████████████████████████▏   | 37807/42525 [1:12:02<08:43,  9.01it/s]

 89%|██████████████████████████████▏   | 37809/42525 [1:12:02<09:13,  8.53it/s]

 89%|██████████████████████████████▏   | 37811/42525 [1:12:03<09:49,  8.00it/s]

 89%|██████████████████████████████▏   | 37814/42525 [1:12:03<09:01,  8.70it/s]

 89%|██████████████████████████████▏   | 37818/42525 [1:12:03<08:11,  9.57it/s]

 89%|██████████████████████████████▏   | 37821/42525 [1:12:04<08:02,  9.76it/s]

 89%|██████████████████████████████▏   | 37824/42525 [1:12:04<08:34,  9.14it/s]

 89%|██████████████████████████████▏   | 37826/42525 [1:12:04<08:41,  9.01it/s]

 89%|██████████████████████████████▏   | 37828/42525 [1:12:04<08:54,  8.79it/s]

 89%|██████████████████████████████▏   | 37830/42525 [1:12:05<09:54,  7.90it/s]

 89%|██████████████████████████████▏   | 37831/42525 [1:12:05<10:31,  7.44it/s]

 89%|██████████████████████████████▎   | 37835/42525 [1:12:05<08:42,  8.97it/s]

 89%|██████████████████████████████▎   | 37838/42525 [1:12:06<08:07,  9.62it/s]

 89%|██████████████████████████████▎   | 37839/42525 [1:12:06<08:14,  9.48it/s]

 89%|██████████████████████████████▎   | 37842/42525 [1:12:06<08:38,  9.04it/s]

 89%|██████████████████████████████▎   | 37845/42525 [1:12:06<08:21,  9.32it/s]

 89%|██████████████████████████████▎   | 37848/42525 [1:12:07<08:32,  9.12it/s]

 89%|██████████████████████████████▎   | 37851/42525 [1:12:07<08:33,  9.11it/s]

 89%|██████████████████████████████▎   | 37853/42525 [1:12:07<09:13,  8.44it/s]

 89%|██████████████████████████████▎   | 37855/42525 [1:12:08<09:20,  8.34it/s]

 89%|██████████████████████████████▎   | 37857/42525 [1:12:08<10:00,  7.77it/s]

 89%|██████████████████████████████▎   | 37860/42525 [1:12:08<08:42,  8.92it/s]

 89%|██████████████████████████████▎   | 37862/42525 [1:12:08<09:31,  8.16it/s]

 89%|██████████████████████████████▎   | 37865/42525 [1:12:09<08:23,  9.26it/s]

 89%|██████████████████████████████▎   | 37868/42525 [1:12:09<08:21,  9.29it/s]

 89%|██████████████████████████████▎   | 37870/42525 [1:12:09<08:16,  9.37it/s]

 89%|██████████████████████████████▎   | 37874/42525 [1:12:10<07:42, 10.05it/s]

 89%|██████████████████████████████▎   | 37876/42525 [1:12:10<07:54,  9.80it/s]

 89%|██████████████████████████████▎   | 37879/42525 [1:12:10<08:07,  9.53it/s]

 89%|██████████████████████████████▎   | 37882/42525 [1:12:10<08:21,  9.27it/s]

 89%|██████████████████████████████▎   | 37885/42525 [1:12:11<07:57,  9.71it/s]

 89%|██████████████████████████████▎   | 37889/42525 [1:12:11<07:38, 10.11it/s]

 89%|██████████████████████████████▎   | 37893/42525 [1:12:11<07:27, 10.35it/s]

 89%|██████████████████████████████▎   | 37897/42525 [1:12:12<07:23, 10.44it/s]

 89%|██████████████████████████████▎   | 37900/42525 [1:12:12<08:06,  9.51it/s]

 89%|██████████████████████████████▎   | 37902/42525 [1:12:12<08:16,  9.32it/s]

 89%|██████████████████████████████▎   | 37904/42525 [1:12:13<08:22,  9.20it/s]

 89%|██████████████████████████████▎   | 37906/42525 [1:12:13<08:23,  9.17it/s]

 89%|██████████████████████████████▎   | 37908/42525 [1:12:13<08:31,  9.03it/s]

 89%|██████████████████████████████▎   | 37910/42525 [1:12:13<09:24,  8.18it/s]

 89%|██████████████████████████████▎   | 37912/42525 [1:12:14<09:46,  7.86it/s]

 89%|██████████████████████████████▎   | 37914/42525 [1:12:14<09:08,  8.41it/s]

 89%|██████████████████████████████▎   | 37917/42525 [1:12:14<08:25,  9.12it/s]

 89%|██████████████████████████████▎   | 37919/42525 [1:12:14<08:17,  9.26it/s]

 89%|██████████████████████████████▎   | 37921/42525 [1:12:15<09:00,  8.53it/s]

 89%|██████████████████████████████▎   | 37923/42525 [1:12:15<09:18,  8.24it/s]

 89%|██████████████████████████████▎   | 37925/42525 [1:12:15<09:20,  8.21it/s]

 89%|██████████████████████████████▎   | 37927/42525 [1:12:15<08:39,  8.85it/s]

 89%|██████████████████████████████▎   | 37930/42525 [1:12:16<08:07,  9.43it/s]

 89%|██████████████████████████████▎   | 37934/42525 [1:12:16<07:48,  9.81it/s]

 89%|██████████████████████████████▎   | 37936/42525 [1:12:16<07:52,  9.71it/s]

 89%|██████████████████████████████▎   | 37938/42525 [1:12:16<08:00,  9.55it/s]

 89%|██████████████████████████████▎   | 37939/42525 [1:12:17<08:12,  9.31it/s]

 89%|██████████████████████████████▎   | 37942/42525 [1:12:17<08:48,  8.67it/s]

 89%|██████████████████████████████▎   | 37945/42525 [1:12:17<08:37,  8.85it/s]

 89%|██████████████████████████████▎   | 37947/42525 [1:12:17<08:30,  8.97it/s]

 89%|██████████████████████████████▎   | 37949/42525 [1:12:18<08:42,  8.76it/s]

 89%|██████████████████████████████▎   | 37951/42525 [1:12:18<09:02,  8.44it/s]

 89%|██████████████████████████████▎   | 37953/42525 [1:12:18<09:25,  8.09it/s]

 89%|██████████████████████████████▎   | 37955/42525 [1:12:19<10:01,  7.60it/s]

 89%|██████████████████████████████▎   | 37958/42525 [1:12:19<08:55,  8.53it/s]

 89%|██████████████████████████████▎   | 37960/42525 [1:12:19<09:19,  8.16it/s]

 89%|██████████████████████████████▎   | 37962/42525 [1:12:19<09:18,  8.18it/s]

 89%|██████████████████████████████▎   | 37964/42525 [1:12:20<08:18,  9.14it/s]

 89%|██████████████████████████████▎   | 37966/42525 [1:12:20<08:07,  9.36it/s]

 89%|██████████████████████████████▎   | 37969/42525 [1:12:20<08:17,  9.16it/s]

 89%|██████████████████████████████▎   | 37971/42525 [1:12:20<08:40,  8.74it/s]

 89%|██████████████████████████████▎   | 37973/42525 [1:12:21<08:36,  8.82it/s]

 89%|██████████████████████████████▎   | 37975/42525 [1:12:21<08:50,  8.58it/s]

 89%|██████████████████████████████▎   | 37977/42525 [1:12:21<09:37,  7.88it/s]

 89%|██████████████████████████████▎   | 37979/42525 [1:12:21<10:12,  7.43it/s]

 89%|██████████████████████████████▎   | 37981/42525 [1:12:22<10:03,  7.53it/s]

 89%|██████████████████████████████▎   | 37983/42525 [1:12:22<09:09,  8.27it/s]

 89%|██████████████████████████████▎   | 37985/42525 [1:12:22<09:00,  8.40it/s]

 89%|██████████████████████████████▎   | 37987/42525 [1:12:22<09:25,  8.02it/s]

 89%|██████████████████████████████▎   | 37989/42525 [1:12:23<08:48,  8.58it/s]

 89%|██████████████████████████████▎   | 37991/42525 [1:12:23<09:30,  7.95it/s]

 89%|██████████████████████████████▍   | 37993/42525 [1:12:23<08:42,  8.67it/s]

 89%|██████████████████████████████▍   | 37995/42525 [1:12:23<09:13,  8.19it/s]

 89%|██████████████████████████████▍   | 37996/42525 [1:12:23<08:49,  8.56it/s]

 89%|██████████████████████████████▍   | 37999/42525 [1:12:24<08:15,  9.14it/s]

 89%|██████████████████████████████▍   | 38001/42525 [1:12:24<08:05,  9.32it/s]

 89%|██████████████████████████████▍   | 38003/42525 [1:12:24<08:52,  8.50it/s]

 89%|██████████████████████████████▍   | 38005/42525 [1:12:24<08:17,  9.08it/s]

 89%|██████████████████████████████▍   | 38006/42525 [1:12:24<09:07,  8.26it/s]

 89%|██████████████████████████████▍   | 38009/42525 [1:12:25<08:24,  8.95it/s]

 89%|██████████████████████████████▍   | 38011/42525 [1:12:25<08:07,  9.26it/s]

 89%|██████████████████████████████▍   | 38013/42525 [1:12:25<08:43,  8.62it/s]

 89%|██████████████████████████████▍   | 38015/42525 [1:12:25<08:45,  8.58it/s]

 89%|██████████████████████████████▍   | 38017/42525 [1:12:26<09:22,  8.01it/s]

 89%|██████████████████████████████▍   | 38019/42525 [1:12:26<08:41,  8.64it/s]

 89%|██████████████████████████████▍   | 38022/42525 [1:12:26<08:01,  9.35it/s]

 89%|██████████████████████████████▍   | 38025/42525 [1:12:27<07:41,  9.75it/s]

 89%|██████████████████████████████▍   | 38028/42525 [1:12:27<08:17,  9.04it/s]

 89%|██████████████████████████████▍   | 38030/42525 [1:12:27<09:08,  8.19it/s]

 89%|██████████████████████████████▍   | 38032/42525 [1:12:27<08:52,  8.44it/s]

 89%|██████████████████████████████▍   | 38034/42525 [1:12:28<08:40,  8.63it/s]

 89%|██████████████████████████████▍   | 38036/42525 [1:12:28<09:07,  8.20it/s]

 89%|██████████████████████████████▍   | 38038/42525 [1:12:28<08:58,  8.34it/s]

 89%|██████████████████████████████▍   | 38040/42525 [1:12:28<08:46,  8.52it/s]

 89%|██████████████████████████████▍   | 38042/42525 [1:12:29<08:16,  9.03it/s]

 89%|██████████████████████████████▍   | 38044/42525 [1:12:29<08:24,  8.89it/s]

 89%|██████████████████████████████▍   | 38045/42525 [1:12:29<08:09,  9.16it/s]

 89%|██████████████████████████████▍   | 38048/42525 [1:12:29<08:27,  8.82it/s]

 89%|██████████████████████████████▍   | 38050/42525 [1:12:30<09:41,  7.69it/s]

 89%|██████████████████████████████▍   | 38052/42525 [1:12:30<09:27,  7.88it/s]

 89%|██████████████████████████████▍   | 38054/42525 [1:12:30<09:09,  8.13it/s]

 89%|██████████████████████████████▍   | 38056/42525 [1:12:30<08:49,  8.44it/s]

 89%|██████████████████████████████▍   | 38059/42525 [1:12:31<07:50,  9.49it/s]

 90%|██████████████████████████████▍   | 38063/42525 [1:12:31<07:32,  9.85it/s]

 90%|██████████████████████████████▍   | 38065/42525 [1:12:31<08:07,  9.15it/s]

 90%|██████████████████████████████▍   | 38067/42525 [1:12:31<07:48,  9.52it/s]

 90%|██████████████████████████████▍   | 38070/42525 [1:12:32<07:51,  9.45it/s]

 90%|██████████████████████████████▍   | 38072/42525 [1:12:32<08:02,  9.23it/s]

 90%|██████████████████████████████▍   | 38074/42525 [1:12:32<08:35,  8.63it/s]

 90%|██████████████████████████████▍   | 38076/42525 [1:12:32<09:01,  8.21it/s]

 90%|██████████████████████████████▍   | 38078/42525 [1:12:33<08:18,  8.92it/s]

 90%|██████████████████████████████▍   | 38080/42525 [1:12:33<08:08,  9.11it/s]

 90%|██████████████████████████████▍   | 38081/42525 [1:12:33<08:12,  9.03it/s]

 90%|██████████████████████████████▍   | 38085/42525 [1:12:33<07:54,  9.36it/s]

 90%|██████████████████████████████▍   | 38088/42525 [1:12:34<07:37,  9.71it/s]

 90%|██████████████████████████████▍   | 38090/42525 [1:12:34<08:13,  8.98it/s]

 90%|██████████████████████████████▍   | 38093/42525 [1:12:34<09:05,  8.13it/s]

 90%|██████████████████████████████▍   | 38096/42525 [1:12:35<08:22,  8.82it/s]

 90%|██████████████████████████████▍   | 38097/42525 [1:12:35<08:09,  9.05it/s]

 90%|██████████████████████████████▍   | 38100/42525 [1:12:35<08:19,  8.86it/s]

 90%|██████████████████████████████▍   | 38102/42525 [1:12:35<09:00,  8.18it/s]

 90%|██████████████████████████████▍   | 38106/42525 [1:12:36<08:14,  8.93it/s]

 90%|██████████████████████████████▍   | 38109/42525 [1:12:36<07:42,  9.54it/s]

 90%|██████████████████████████████▍   | 38111/42525 [1:12:36<08:22,  8.79it/s]

 90%|██████████████████████████████▍   | 38112/42525 [1:12:37<08:59,  8.19it/s]

 90%|██████████████████████████████▍   | 38115/42525 [1:12:37<09:28,  7.76it/s]

 90%|██████████████████████████████▍   | 38118/42525 [1:12:37<08:29,  8.64it/s]

 90%|██████████████████████████████▍   | 38121/42525 [1:12:38<08:02,  9.13it/s]

 90%|██████████████████████████████▍   | 38123/42525 [1:12:38<08:41,  8.45it/s]

 90%|██████████████████████████████▍   | 38125/42525 [1:12:38<08:25,  8.70it/s]

 90%|██████████████████████████████▍   | 38128/42525 [1:12:38<07:57,  9.21it/s]

 90%|██████████████████████████████▍   | 38130/42525 [1:12:39<08:05,  9.05it/s]

 90%|██████████████████████████████▍   | 38132/42525 [1:12:39<08:02,  9.11it/s]

 90%|██████████████████████████████▍   | 38134/42525 [1:12:39<08:20,  8.78it/s]

 90%|██████████████████████████████▍   | 38136/42525 [1:12:39<08:19,  8.79it/s]

 90%|██████████████████████████████▍   | 38138/42525 [1:12:39<08:16,  8.84it/s]

 90%|██████████████████████████████▍   | 38140/42525 [1:12:40<07:58,  9.16it/s]

 90%|██████████████████████████████▍   | 38142/42525 [1:12:40<08:31,  8.58it/s]

 90%|██████████████████████████████▍   | 38144/42525 [1:12:40<08:04,  9.04it/s]

 90%|██████████████████████████████▍   | 38146/42525 [1:12:40<07:58,  9.15it/s]

 90%|██████████████████████████████▍   | 38147/42525 [1:12:40<08:49,  8.27it/s]

 90%|██████████████████████████████▌   | 38150/42525 [1:12:41<08:18,  8.78it/s]

 90%|██████████████████████████████▌   | 38153/42525 [1:12:41<08:02,  9.06it/s]

 90%|██████████████████████████████▌   | 38156/42525 [1:12:41<07:27,  9.76it/s]

 90%|██████████████████████████████▌   | 38158/42525 [1:12:42<07:14, 10.06it/s]

 90%|██████████████████████████████▌   | 38161/42525 [1:12:42<07:50,  9.27it/s]

 90%|██████████████████████████████▌   | 38163/42525 [1:12:42<08:07,  8.94it/s]

 90%|██████████████████████████████▌   | 38165/42525 [1:12:43<08:59,  8.07it/s]

 90%|██████████████████████████████▌   | 38167/42525 [1:12:43<08:28,  8.57it/s]

 90%|██████████████████████████████▌   | 38170/42525 [1:12:43<08:08,  8.91it/s]

 90%|██████████████████████████████▌   | 38171/42525 [1:12:43<07:58,  9.10it/s]

 90%|██████████████████████████████▌   | 38174/42525 [1:12:44<08:25,  8.61it/s]

 90%|██████████████████████████████▌   | 38177/42525 [1:12:44<07:48,  9.28it/s]

 90%|██████████████████████████████▌   | 38179/42525 [1:12:44<08:05,  8.95it/s]

 90%|██████████████████████████████▌   | 38182/42525 [1:12:44<08:21,  8.66it/s]

 90%|██████████████████████████████▌   | 38184/42525 [1:12:45<08:46,  8.25it/s]

 90%|██████████████████████████████▌   | 38186/42525 [1:12:45<09:02,  8.00it/s]

 90%|██████████████████████████████▌   | 38189/42525 [1:12:45<08:23,  8.61it/s]

 90%|██████████████████████████████▌   | 38190/42525 [1:12:45<08:24,  8.59it/s]

 90%|██████████████████████████████▌   | 38192/42525 [1:12:46<08:35,  8.40it/s]

 90%|██████████████████████████████▌   | 38195/42525 [1:12:46<08:17,  8.70it/s]

 90%|██████████████████████████████▌   | 38197/42525 [1:12:46<08:01,  8.99it/s]

 90%|██████████████████████████████▌   | 38199/42525 [1:12:46<09:00,  8.01it/s]

 90%|██████████████████████████████▌   | 38202/42525 [1:12:47<08:19,  8.65it/s]

 90%|██████████████████████████████▌   | 38204/42525 [1:12:47<08:33,  8.41it/s]

 90%|██████████████████████████████▌   | 38207/42525 [1:12:47<08:17,  8.68it/s]

 90%|██████████████████████████████▌   | 38209/42525 [1:12:48<07:47,  9.24it/s]

 90%|██████████████████████████████▌   | 38212/42525 [1:12:48<07:59,  9.00it/s]

 90%|██████████████████████████████▌   | 38215/42525 [1:12:48<07:47,  9.23it/s]

 90%|██████████████████████████████▌   | 38217/42525 [1:12:48<08:13,  8.73it/s]

 90%|██████████████████████████████▌   | 38218/42525 [1:12:49<07:58,  9.00it/s]

 90%|██████████████████████████████▌   | 38221/42525 [1:12:49<07:44,  9.26it/s]

 90%|██████████████████████████████▌   | 38222/42525 [1:12:49<08:19,  8.62it/s]

 90%|██████████████████████████████▌   | 38224/42525 [1:12:49<08:00,  8.95it/s]

 90%|██████████████████████████████▌   | 38227/42525 [1:12:50<07:49,  9.15it/s]

 90%|██████████████████████████████▌   | 38229/42525 [1:12:50<07:43,  9.27it/s]

 90%|██████████████████████████████▌   | 38231/42525 [1:12:50<07:34,  9.45it/s]

 90%|██████████████████████████████▌   | 38233/42525 [1:12:50<08:11,  8.74it/s]

 90%|██████████████████████████████▌   | 38235/42525 [1:12:50<08:40,  8.25it/s]

 90%|██████████████████████████████▌   | 38237/42525 [1:12:51<08:13,  8.68it/s]

 90%|██████████████████████████████▌   | 38240/42525 [1:12:51<08:09,  8.76it/s]

 90%|██████████████████████████████▌   | 38242/42525 [1:12:51<07:52,  9.07it/s]

 90%|██████████████████████████████▌   | 38245/42525 [1:12:52<07:22,  9.67it/s]

 90%|██████████████████████████████▌   | 38248/42525 [1:12:52<08:08,  8.76it/s]

 90%|██████████████████████████████▌   | 38251/42525 [1:12:52<08:05,  8.80it/s]

 90%|██████████████████████████████▌   | 38254/42525 [1:12:53<07:36,  9.36it/s]

 90%|██████████████████████████████▌   | 38257/42525 [1:12:53<07:16,  9.78it/s]

 90%|██████████████████████████████▌   | 38259/42525 [1:12:53<08:01,  8.85it/s]

 90%|██████████████████████████████▌   | 38260/42525 [1:12:53<07:48,  9.10it/s]

 90%|██████████████████████████████▌   | 38263/42525 [1:12:54<07:47,  9.12it/s]

 90%|██████████████████████████████▌   | 38265/42525 [1:12:54<07:48,  9.09it/s]

 90%|██████████████████████████████▌   | 38267/42525 [1:12:54<08:15,  8.59it/s]

 90%|██████████████████████████████▌   | 38270/42525 [1:12:54<07:58,  8.89it/s]

 90%|██████████████████████████████▌   | 38272/42525 [1:12:55<08:09,  8.70it/s]

 90%|██████████████████████████████▌   | 38275/42525 [1:12:55<07:34,  9.35it/s]

 90%|██████████████████████████████▌   | 38277/42525 [1:12:55<07:25,  9.53it/s]

 90%|██████████████████████████████▌   | 38279/42525 [1:12:55<07:28,  9.47it/s]

 90%|██████████████████████████████▌   | 38281/42525 [1:12:56<08:18,  8.51it/s]

 90%|██████████████████████████████▌   | 38283/42525 [1:12:56<08:16,  8.55it/s]

 90%|██████████████████████████████▌   | 38285/42525 [1:12:56<08:30,  8.31it/s]

 90%|██████████████████████████████▌   | 38287/42525 [1:12:56<08:01,  8.80it/s]

 90%|██████████████████████████████▌   | 38289/42525 [1:12:56<07:49,  9.01it/s]

 90%|██████████████████████████████▌   | 38291/42525 [1:12:57<08:36,  8.21it/s]

 90%|██████████████████████████████▌   | 38293/42525 [1:12:57<08:53,  7.93it/s]

 90%|██████████████████████████████▌   | 38295/42525 [1:12:57<08:02,  8.76it/s]

 90%|██████████████████████████████▌   | 38297/42525 [1:12:57<07:36,  9.27it/s]

 90%|██████████████████████████████▌   | 38299/42525 [1:12:58<07:43,  9.12it/s]

 90%|██████████████████████████████▌   | 38301/42525 [1:12:58<08:07,  8.66it/s]

 90%|██████████████████████████████▌   | 38303/42525 [1:12:58<08:08,  8.65it/s]

 90%|██████████████████████████████▋   | 38305/42525 [1:12:58<07:44,  9.09it/s]

 90%|██████████████████████████████▋   | 38307/42525 [1:12:58<07:42,  9.11it/s]

 90%|██████████████████████████████▋   | 38309/42525 [1:12:59<07:27,  9.43it/s]

 90%|██████████████████████████████▋   | 38311/42525 [1:12:59<08:04,  8.70it/s]

 90%|██████████████████████████████▋   | 38313/42525 [1:12:59<08:38,  8.13it/s]

 90%|██████████████████████████████▋   | 38315/42525 [1:12:59<07:56,  8.84it/s]

 90%|██████████████████████████████▋   | 38317/42525 [1:13:00<08:07,  8.63it/s]

 90%|██████████████████████████████▋   | 38319/42525 [1:13:00<07:57,  8.80it/s]

 90%|██████████████████████████████▋   | 38321/42525 [1:13:00<07:33,  9.27it/s]

 90%|██████████████████████████████▋   | 38323/42525 [1:13:00<08:26,  8.29it/s]

 90%|██████████████████████████████▋   | 38325/42525 [1:13:01<07:44,  9.05it/s]

 90%|██████████████████████████████▋   | 38327/42525 [1:13:01<07:46,  9.01it/s]

 90%|██████████████████████████████▋   | 38329/42525 [1:13:01<07:50,  8.93it/s]

 90%|██████████████████████████████▋   | 38330/42525 [1:13:01<07:52,  8.87it/s]

 90%|██████████████████████████████▋   | 38333/42525 [1:13:01<07:59,  8.73it/s]

 90%|██████████████████████████████▋   | 38335/42525 [1:13:02<07:41,  9.07it/s]

 90%|██████████████████████████████▋   | 38337/42525 [1:13:02<07:53,  8.85it/s]

 90%|██████████████████████████████▋   | 38339/42525 [1:13:02<08:05,  8.63it/s]

 90%|██████████████████████████████▋   | 38340/42525 [1:13:02<07:50,  8.90it/s]

 90%|██████████████████████████████▋   | 38343/42525 [1:13:03<07:46,  8.96it/s]

 90%|██████████████████████████████▋   | 38345/42525 [1:13:03<08:18,  8.38it/s]

 90%|██████████████████████████████▋   | 38348/42525 [1:13:03<07:40,  9.08it/s]

 90%|██████████████████████████████▋   | 38350/42525 [1:13:03<07:34,  9.19it/s]

 90%|██████████████████████████████▋   | 38352/42525 [1:13:04<07:27,  9.33it/s]

 90%|██████████████████████████████▋   | 38355/42525 [1:13:04<07:35,  9.15it/s]

 90%|██████████████████████████████▋   | 38357/42525 [1:13:04<08:38,  8.04it/s]

 90%|██████████████████████████████▋   | 38359/42525 [1:13:04<08:44,  7.95it/s]

 90%|██████████████████████████████▋   | 38361/42525 [1:13:05<08:11,  8.47it/s]

 90%|██████████████████████████████▋   | 38363/42525 [1:13:05<07:36,  9.12it/s]

 90%|██████████████████████████████▋   | 38365/42525 [1:13:05<07:29,  9.25it/s]

 90%|██████████████████████████████▋   | 38367/42525 [1:13:05<07:33,  9.16it/s]

 90%|██████████████████████████████▋   | 38369/42525 [1:13:06<08:26,  8.20it/s]

 90%|██████████████████████████████▋   | 38371/42525 [1:13:06<08:25,  8.22it/s]

 90%|██████████████████████████████▋   | 38373/42525 [1:13:06<07:53,  8.76it/s]

 90%|██████████████████████████████▋   | 38375/42525 [1:13:06<08:08,  8.49it/s]

 90%|██████████████████████████████▋   | 38377/42525 [1:13:06<07:54,  8.75it/s]

 90%|██████████████████████████████▋   | 38379/42525 [1:13:07<08:01,  8.60it/s]

 90%|██████████████████████████████▋   | 38381/42525 [1:13:07<07:33,  9.13it/s]

 90%|██████████████████████████████▋   | 38384/42525 [1:13:07<07:09,  9.65it/s]

 90%|██████████████████████████████▋   | 38386/42525 [1:13:07<07:44,  8.91it/s]

 90%|██████████████████████████████▋   | 38388/42525 [1:13:08<08:19,  8.28it/s]

 90%|██████████████████████████████▋   | 38391/42525 [1:13:08<07:30,  9.18it/s]

 90%|██████████████████████████████▋   | 38394/42525 [1:13:08<07:10,  9.60it/s]

 90%|██████████████████████████████▋   | 38397/42525 [1:13:09<07:27,  9.22it/s]

 90%|██████████████████████████████▋   | 38399/42525 [1:13:09<07:43,  8.90it/s]

 90%|██████████████████████████████▋   | 38400/42525 [1:13:09<07:51,  8.75it/s]

 90%|██████████████████████████████▋   | 38403/42525 [1:13:09<07:32,  9.10it/s]

 90%|██████████████████████████████▋   | 38405/42525 [1:13:10<07:26,  9.23it/s]

 90%|██████████████████████████████▋   | 38407/42525 [1:13:10<08:09,  8.42it/s]

 90%|██████████████████████████████▋   | 38409/42525 [1:13:10<08:30,  8.06it/s]

 90%|██████████████████████████████▋   | 38411/42525 [1:13:10<07:48,  8.78it/s]

 90%|██████████████████████████████▋   | 38413/42525 [1:13:10<07:50,  8.74it/s]

 90%|██████████████████████████████▋   | 38415/42525 [1:13:11<08:30,  8.05it/s]

 90%|██████████████████████████████▋   | 38417/42525 [1:13:11<07:58,  8.58it/s]

 90%|██████████████████████████████▋   | 38420/42525 [1:13:11<07:21,  9.30it/s]

 90%|██████████████████████████████▋   | 38423/42525 [1:13:12<07:03,  9.69it/s]

 90%|██████████████████████████████▋   | 38425/42525 [1:13:12<07:44,  8.83it/s]

 90%|██████████████████████████████▋   | 38427/42525 [1:13:12<08:19,  8.21it/s]

 90%|██████████████████████████████▋   | 38429/42525 [1:13:12<07:41,  8.87it/s]

 90%|██████████████████████████████▋   | 38432/42525 [1:13:13<07:08,  9.56it/s]

 90%|██████████████████████████████▋   | 38435/42525 [1:13:13<07:36,  8.97it/s]

 90%|██████████████████████████████▋   | 38438/42525 [1:13:13<07:32,  9.04it/s]

 90%|██████████████████████████████▋   | 38440/42525 [1:13:14<07:51,  8.66it/s]

 90%|██████████████████████████████▋   | 38442/42525 [1:13:14<07:51,  8.65it/s]

 90%|██████████████████████████████▋   | 38444/42525 [1:13:14<08:36,  7.90it/s]

 90%|██████████████████████████████▋   | 38445/42525 [1:13:14<09:03,  7.50it/s]

 90%|██████████████████████████████▋   | 38448/42525 [1:13:14<07:48,  8.70it/s]

 90%|██████████████████████████████▋   | 38451/42525 [1:13:15<07:51,  8.65it/s]

 90%|██████████████████████████████▋   | 38453/42525 [1:13:15<08:04,  8.40it/s]

 90%|██████████████████████████████▋   | 38455/42525 [1:13:15<07:28,  9.08it/s]

 90%|██████████████████████████████▋   | 38458/42525 [1:13:16<07:33,  8.96it/s]

 90%|██████████████████████████████▋   | 38460/42525 [1:13:16<08:09,  8.30it/s]

 90%|██████████████████████████████▊   | 38462/42525 [1:13:16<07:54,  8.57it/s]

 90%|██████████████████████████████▊   | 38464/42525 [1:13:16<07:30,  9.01it/s]

 90%|██████████████████████████████▊   | 38466/42525 [1:13:17<08:28,  7.99it/s]

 90%|██████████████████████████████▊   | 38469/42525 [1:13:17<07:26,  9.09it/s]

 90%|██████████████████████████████▊   | 38471/42525 [1:13:17<07:56,  8.51it/s]

 90%|██████████████████████████████▊   | 38473/42525 [1:13:17<07:27,  9.06it/s]

 90%|██████████████████████████████▊   | 38475/42525 [1:13:18<08:07,  8.31it/s]

 90%|██████████████████████████████▊   | 38478/42525 [1:13:18<07:28,  9.03it/s]

 90%|██████████████████████████████▊   | 38480/42525 [1:13:18<07:35,  8.88it/s]

 90%|██████████████████████████████▊   | 38482/42525 [1:13:18<08:26,  7.98it/s]

 90%|██████████████████████████████▊   | 38485/42525 [1:13:19<07:32,  8.92it/s]

 91%|██████████████████████████████▊   | 38487/42525 [1:13:19<08:04,  8.34it/s]

 91%|██████████████████████████████▊   | 38488/42525 [1:13:19<07:59,  8.41it/s]

 91%|██████████████████████████████▊   | 38491/42525 [1:13:19<07:43,  8.71it/s]

 91%|██████████████████████████████▊   | 38493/42525 [1:13:20<07:44,  8.68it/s]

 91%|██████████████████████████████▊   | 38495/42525 [1:13:20<07:26,  9.02it/s]

 91%|██████████████████████████████▊   | 38497/42525 [1:13:20<07:22,  9.11it/s]

 91%|██████████████████████████████▊   | 38499/42525 [1:13:20<07:53,  8.51it/s]

 91%|██████████████████████████████▊   | 38501/42525 [1:13:21<08:27,  7.94it/s]

 91%|██████████████████████████████▊   | 38503/42525 [1:13:21<07:40,  8.74it/s]

 91%|██████████████████████████████▊   | 38506/42525 [1:13:21<07:00,  9.56it/s]

 91%|██████████████████████████████▊   | 38508/42525 [1:13:21<07:05,  9.44it/s]

 91%|██████████████████████████████▊   | 38510/42525 [1:13:22<08:20,  8.03it/s]

 91%|██████████████████████████████▊   | 38513/42525 [1:13:22<08:12,  8.15it/s]

 91%|██████████████████████████████▊   | 38515/42525 [1:13:22<07:53,  8.47it/s]

 91%|██████████████████████████████▊   | 38516/42525 [1:13:22<08:08,  8.21it/s]

 91%|██████████████████████████████▊   | 38519/42525 [1:13:23<07:24,  9.01it/s]

 91%|██████████████████████████████▊   | 38521/42525 [1:13:23<07:14,  9.21it/s]

 91%|██████████████████████████████▊   | 38523/42525 [1:13:23<07:45,  8.60it/s]

 91%|██████████████████████████████▊   | 38525/42525 [1:13:23<07:23,  9.02it/s]

 91%|██████████████████████████████▊   | 38527/42525 [1:13:24<07:10,  9.28it/s]

 91%|██████████████████████████████▊   | 38529/42525 [1:13:24<07:41,  8.67it/s]

 91%|██████████████████████████████▊   | 38531/42525 [1:13:24<07:33,  8.82it/s]

 91%|██████████████████████████████▊   | 38532/42525 [1:13:24<07:41,  8.66it/s]

 91%|██████████████████████████████▊   | 38535/42525 [1:13:25<08:03,  8.25it/s]

 91%|██████████████████████████████▊   | 38537/42525 [1:13:25<07:38,  8.70it/s]

 91%|██████████████████████████████▊   | 38539/42525 [1:13:25<08:10,  8.13it/s]

 91%|██████████████████████████████▊   | 38541/42525 [1:13:25<07:32,  8.80it/s]

 91%|██████████████████████████████▊   | 38543/42525 [1:13:25<08:06,  8.18it/s]

 91%|██████████████████████████████▊   | 38545/42525 [1:13:26<07:57,  8.34it/s]

 91%|██████████████████████████████▊   | 38547/42525 [1:13:26<07:45,  8.54it/s]

 91%|██████████████████████████████▊   | 38549/42525 [1:13:26<07:55,  8.36it/s]

 91%|██████████████████████████████▊   | 38551/42525 [1:13:26<07:25,  8.91it/s]

 91%|██████████████████████████████▊   | 38553/42525 [1:13:27<07:22,  8.98it/s]

 91%|██████████████████████████████▊   | 38555/42525 [1:13:27<08:25,  7.86it/s]

 91%|██████████████████████████████▊   | 38557/42525 [1:13:27<08:38,  7.65it/s]

 91%|██████████████████████████████▊   | 38558/42525 [1:13:27<09:10,  7.20it/s]

 91%|██████████████████████████████▊   | 38561/42525 [1:13:28<07:53,  8.37it/s]

 91%|██████████████████████████████▊   | 38563/42525 [1:13:28<07:40,  8.60it/s]

 91%|██████████████████████████████▊   | 38566/42525 [1:13:28<07:03,  9.36it/s]

 91%|██████████████████████████████▊   | 38569/42525 [1:13:28<06:48,  9.68it/s]

 91%|██████████████████████████████▊   | 38571/42525 [1:13:29<07:31,  8.76it/s]

 91%|██████████████████████████████▊   | 38573/42525 [1:13:29<07:20,  8.97it/s]

 91%|██████████████████████████████▊   | 38575/42525 [1:13:29<07:27,  8.83it/s]

 91%|██████████████████████████████▊   | 38577/42525 [1:13:29<07:16,  9.04it/s]

 91%|██████████████████████████████▊   | 38578/42525 [1:13:29<07:06,  9.25it/s]

 91%|██████████████████████████████▊   | 38581/42525 [1:13:30<07:18,  8.99it/s]

 91%|██████████████████████████████▊   | 38583/42525 [1:13:30<07:09,  9.19it/s]

 91%|██████████████████████████████▊   | 38585/42525 [1:13:30<07:17,  9.01it/s]

 91%|██████████████████████████████▊   | 38588/42525 [1:13:31<07:03,  9.29it/s]

 91%|██████████████████████████████▊   | 38590/42525 [1:13:31<07:02,  9.31it/s]

 91%|██████████████████████████████▊   | 38592/42525 [1:13:31<07:21,  8.90it/s]

 91%|██████████████████████████████▊   | 38595/42525 [1:13:31<06:58,  9.40it/s]

 91%|██████████████████████████████▊   | 38596/42525 [1:13:31<07:12,  9.08it/s]

 91%|██████████████████████████████▊   | 38599/42525 [1:13:32<06:53,  9.49it/s]

 91%|██████████████████████████████▊   | 38601/42525 [1:13:32<07:03,  9.27it/s]

 91%|██████████████████████████████▊   | 38604/42525 [1:13:32<07:08,  9.16it/s]

 91%|██████████████████████████████▊   | 38605/42525 [1:13:32<07:02,  9.29it/s]

 91%|██████████████████████████████▊   | 38608/42525 [1:13:33<08:00,  8.15it/s]

 91%|██████████████████████████████▊   | 38610/42525 [1:13:33<07:50,  8.33it/s]

 91%|██████████████████████████████▊   | 38612/42525 [1:13:33<07:58,  8.18it/s]

 91%|██████████████████████████████▊   | 38614/42525 [1:13:34<08:00,  8.13it/s]

 91%|██████████████████████████████▊   | 38616/42525 [1:13:34<07:31,  8.66it/s]

 91%|██████████████████████████████▉   | 38618/42525 [1:13:34<07:59,  8.15it/s]

 91%|██████████████████████████████▉   | 38620/42525 [1:13:34<07:18,  8.91it/s]

 91%|██████████████████████████████▉   | 38622/42525 [1:13:34<07:27,  8.72it/s]

 91%|██████████████████████████████▉   | 38624/42525 [1:13:35<07:20,  8.85it/s]

 91%|██████████████████████████████▉   | 38626/42525 [1:13:35<07:59,  8.13it/s]

 91%|██████████████████████████████▉   | 38627/42525 [1:13:35<07:38,  8.50it/s]

 91%|██████████████████████████████▉   | 38630/42525 [1:13:35<07:46,  8.36it/s]

 91%|██████████████████████████████▉   | 38632/42525 [1:13:36<07:53,  8.23it/s]

 91%|██████████████████████████████▉   | 38634/42525 [1:13:36<08:04,  8.03it/s]

 91%|██████████████████████████████▉   | 38636/42525 [1:13:36<07:39,  8.47it/s]

 91%|██████████████████████████████▉   | 38638/42525 [1:13:36<07:21,  8.80it/s]

 91%|██████████████████████████████▉   | 38640/42525 [1:13:37<07:20,  8.82it/s]

 91%|██████████████████████████████▉   | 38642/42525 [1:13:37<07:03,  9.17it/s]

 91%|██████████████████████████████▉   | 38644/42525 [1:13:37<07:38,  8.47it/s]

 91%|██████████████████████████████▉   | 38646/42525 [1:13:37<07:59,  8.09it/s]

 91%|██████████████████████████████▉   | 38648/42525 [1:13:37<07:20,  8.79it/s]

 91%|██████████████████████████████▉   | 38649/42525 [1:13:38<07:13,  8.95it/s]

 91%|██████████████████████████████▉   | 38651/42525 [1:13:38<07:06,  9.08it/s]

 91%|██████████████████████████████▉   | 38654/42525 [1:13:38<07:24,  8.71it/s]

 91%|██████████████████████████████▉   | 38657/42525 [1:13:38<07:32,  8.54it/s]

 91%|██████████████████████████████▉   | 38660/42525 [1:13:39<07:16,  8.85it/s]

 91%|██████████████████████████████▉   | 38662/42525 [1:13:39<07:08,  9.01it/s]

 91%|██████████████████████████████▉   | 38664/42525 [1:13:39<07:58,  8.07it/s]

 91%|██████████████████████████████▉   | 38667/42525 [1:13:40<07:08,  9.01it/s]

 91%|██████████████████████████████▉   | 38669/42525 [1:13:40<06:52,  9.34it/s]

 91%|██████████████████████████████▉   | 38671/42525 [1:13:40<07:12,  8.90it/s]

 91%|██████████████████████████████▉   | 38673/42525 [1:13:40<08:06,  7.91it/s]

 91%|██████████████████████████████▉   | 38676/42525 [1:13:41<07:07,  9.01it/s]

 91%|██████████████████████████████▉   | 38678/42525 [1:13:41<07:17,  8.79it/s]

 91%|██████████████████████████████▉   | 38680/42525 [1:13:41<07:28,  8.57it/s]

 91%|██████████████████████████████▉   | 38682/42525 [1:13:41<07:20,  8.72it/s]

 91%|██████████████████████████████▉   | 38684/42525 [1:13:42<07:02,  9.08it/s]

 91%|██████████████████████████████▉   | 38686/42525 [1:13:42<06:52,  9.30it/s]

 91%|██████████████████████████████▉   | 38688/42525 [1:13:42<07:53,  8.11it/s]

 91%|██████████████████████████████▉   | 38690/42525 [1:13:42<08:10,  7.82it/s]

 91%|██████████████████████████████▉   | 38691/42525 [1:13:42<07:53,  8.10it/s]

 91%|██████████████████████████████▉   | 38694/42525 [1:13:43<07:07,  8.95it/s]

 91%|██████████████████████████████▉   | 38697/42525 [1:13:43<06:46,  9.42it/s]

 91%|██████████████████████████████▉   | 38700/42525 [1:13:43<06:37,  9.62it/s]

 91%|██████████████████████████████▉   | 38702/42525 [1:13:44<07:02,  9.06it/s]

 91%|██████████████████████████████▉   | 38704/42525 [1:13:44<07:23,  8.62it/s]

 91%|██████████████████████████████▉   | 38706/42525 [1:13:44<08:23,  7.58it/s]

 91%|██████████████████████████████▉   | 38708/42525 [1:13:44<07:26,  8.55it/s]

 91%|██████████████████████████████▉   | 38709/42525 [1:13:44<07:13,  8.81it/s]

 91%|██████████████████████████████▉   | 38712/42525 [1:13:45<07:28,  8.49it/s]

 91%|██████████████████████████████▉   | 38715/42525 [1:13:45<06:57,  9.12it/s]

 91%|██████████████████████████████▉   | 38716/42525 [1:13:45<06:49,  9.30it/s]

 91%|██████████████████████████████▉   | 38719/42525 [1:13:46<07:02,  9.01it/s]

 91%|██████████████████████████████▉   | 38721/42525 [1:13:46<06:53,  9.19it/s]

 91%|██████████████████████████████▉   | 38724/42525 [1:13:46<06:42,  9.45it/s]

 91%|██████████████████████████████▉   | 38725/42525 [1:13:46<06:43,  9.43it/s]

 91%|██████████████████████████████▉   | 38728/42525 [1:13:46<06:37,  9.56it/s]

 91%|██████████████████████████████▉   | 38730/42525 [1:13:47<06:40,  9.48it/s]

 91%|██████████████████████████████▉   | 38732/42525 [1:13:47<07:04,  8.93it/s]

 91%|██████████████████████████████▉   | 38734/42525 [1:13:47<06:55,  9.11it/s]

 91%|██████████████████████████████▉   | 38735/42525 [1:13:47<07:38,  8.26it/s]

 91%|██████████████████████████████▉   | 38738/42525 [1:13:48<07:44,  8.15it/s]

 91%|██████████████████████████████▉   | 38741/42525 [1:13:48<07:21,  8.57it/s]

 91%|██████████████████████████████▉   | 38743/42525 [1:13:48<07:43,  8.16it/s]

 91%|██████████████████████████████▉   | 38745/42525 [1:13:48<07:13,  8.72it/s]

 91%|██████████████████████████████▉   | 38747/42525 [1:13:49<07:20,  8.58it/s]

 91%|██████████████████████████████▉   | 38749/42525 [1:13:49<07:59,  7.87it/s]

 91%|██████████████████████████████▉   | 38751/42525 [1:13:49<08:21,  7.53it/s]

 91%|██████████████████████████████▉   | 38753/42525 [1:13:49<07:29,  8.40it/s]

 91%|██████████████████████████████▉   | 38754/42525 [1:13:50<07:21,  8.55it/s]

 91%|██████████████████████████████▉   | 38756/42525 [1:13:50<06:54,  9.09it/s]

 91%|██████████████████████████████▉   | 38759/42525 [1:13:50<07:20,  8.54it/s]

 91%|██████████████████████████████▉   | 38761/42525 [1:13:50<07:21,  8.53it/s]

 91%|██████████████████████████████▉   | 38763/42525 [1:13:51<07:47,  8.04it/s]

 91%|██████████████████████████████▉   | 38764/42525 [1:13:51<07:28,  8.38it/s]

 91%|██████████████████████████████▉   | 38767/42525 [1:13:51<07:30,  8.33it/s]

 91%|██████████████████████████████▉   | 38769/42525 [1:13:51<07:57,  7.87it/s]

 91%|██████████████████████████████▉   | 38771/42525 [1:13:52<07:31,  8.31it/s]

 91%|███████████████████████████████   | 38773/42525 [1:13:52<07:31,  8.31it/s]

 91%|███████████████████████████████   | 38775/42525 [1:13:52<07:42,  8.11it/s]

 91%|███████████████████████████████   | 38777/42525 [1:13:52<07:21,  8.48it/s]

 91%|███████████████████████████████   | 38780/42525 [1:13:53<07:24,  8.42it/s]

 91%|███████████████████████████████   | 38782/42525 [1:13:53<07:57,  7.84it/s]

 91%|███████████████████████████████   | 38784/42525 [1:13:53<07:21,  8.48it/s]

 91%|███████████████████████████████   | 38786/42525 [1:13:53<08:03,  7.73it/s]

 91%|███████████████████████████████   | 38788/42525 [1:13:54<07:43,  8.06it/s]

 91%|███████████████████████████████   | 38790/42525 [1:13:54<07:56,  7.84it/s]

 91%|███████████████████████████████   | 38792/42525 [1:13:54<07:27,  8.35it/s]

 91%|███████████████████████████████   | 38794/42525 [1:13:54<07:01,  8.85it/s]

 91%|███████████████████████████████   | 38796/42525 [1:13:55<06:46,  9.18it/s]

 91%|███████████████████████████████   | 38799/42525 [1:13:55<06:35,  9.42it/s]

 91%|███████████████████████████████   | 38801/42525 [1:13:55<07:19,  8.48it/s]

 91%|███████████████████████████████   | 38803/42525 [1:13:55<06:56,  8.94it/s]

 91%|███████████████████████████████   | 38805/42525 [1:13:56<06:40,  9.28it/s]

 91%|███████████████████████████████   | 38808/42525 [1:13:56<07:12,  8.60it/s]

 91%|███████████████████████████████   | 38810/42525 [1:13:56<07:50,  7.90it/s]

 91%|███████████████████████████████   | 38812/42525 [1:13:56<07:24,  8.35it/s]

 91%|███████████████████████████████   | 38813/42525 [1:13:57<07:53,  7.84it/s]

 91%|███████████████████████████████   | 38816/42525 [1:13:57<07:52,  7.85it/s]

 91%|███████████████████████████████   | 38818/42525 [1:13:57<08:26,  7.31it/s]

 91%|███████████████████████████████   | 38821/42525 [1:13:58<07:18,  8.46it/s]

 91%|███████████████████████████████   | 38823/42525 [1:13:58<07:17,  8.46it/s]

 91%|███████████████████████████████   | 38825/42525 [1:13:58<07:42,  8.00it/s]

 91%|███████████████████████████████   | 38827/42525 [1:13:58<07:00,  8.79it/s]

 91%|███████████████████████████████   | 38829/42525 [1:13:58<07:36,  8.10it/s]

 91%|███████████████████████████████   | 38831/42525 [1:13:59<07:14,  8.51it/s]

 91%|███████████████████████████████   | 38833/42525 [1:13:59<07:30,  8.19it/s]

 91%|███████████████████████████████   | 38835/42525 [1:13:59<06:55,  8.88it/s]

 91%|███████████████████████████████   | 38837/42525 [1:13:59<07:08,  8.61it/s]

 91%|███████████████████████████████   | 38839/42525 [1:14:00<07:42,  7.97it/s]

 91%|███████████████████████████████   | 38841/42525 [1:14:00<07:10,  8.55it/s]

 91%|███████████████████████████████   | 38843/42525 [1:14:00<07:06,  8.64it/s]

 91%|███████████████████████████████   | 38845/42525 [1:14:00<06:47,  9.04it/s]

 91%|███████████████████████████████   | 38847/42525 [1:14:01<07:04,  8.67it/s]

 91%|███████████████████████████████   | 38849/42525 [1:14:01<07:36,  8.06it/s]

 91%|███████████████████████████████   | 38851/42525 [1:14:01<07:00,  8.73it/s]

 91%|███████████████████████████████   | 38853/42525 [1:14:01<06:40,  9.16it/s]

 91%|███████████████████████████████   | 38855/42525 [1:14:01<06:45,  9.04it/s]

 91%|███████████████████████████████   | 38857/42525 [1:14:02<06:40,  9.15it/s]

 91%|███████████████████████████████   | 38859/42525 [1:14:02<06:43,  9.09it/s]

 91%|███████████████████████████████   | 38861/42525 [1:14:02<06:49,  8.95it/s]

 91%|███████████████████████████████   | 38863/42525 [1:14:02<07:27,  8.17it/s]

 91%|███████████████████████████████   | 38865/42525 [1:14:03<06:48,  8.96it/s]

 91%|███████████████████████████████   | 38868/42525 [1:14:03<07:01,  8.67it/s]

 91%|███████████████████████████████   | 38870/42525 [1:14:03<06:53,  8.83it/s]

 91%|███████████████████████████████   | 38872/42525 [1:14:03<07:41,  7.91it/s]

 91%|███████████████████████████████   | 38874/42525 [1:14:04<07:14,  8.40it/s]

 91%|███████████████████████████████   | 38876/42525 [1:14:04<07:39,  7.94it/s]

 91%|███████████████████████████████   | 38878/42525 [1:14:04<07:51,  7.74it/s]

 91%|███████████████████████████████   | 38881/42525 [1:14:05<06:59,  8.69it/s]

 91%|███████████████████████████████   | 38883/42525 [1:14:05<07:29,  8.10it/s]

 91%|███████████████████████████████   | 38885/42525 [1:14:05<07:41,  7.88it/s]

 91%|███████████████████████████████   | 38887/42525 [1:14:05<07:18,  8.30it/s]

 91%|███████████████████████████████   | 38889/42525 [1:14:06<06:57,  8.71it/s]

 91%|███████████████████████████████   | 38891/42525 [1:14:06<07:39,  7.91it/s]

 91%|███████████████████████████████   | 38892/42525 [1:14:06<08:01,  7.55it/s]

 91%|███████████████████████████████   | 38896/42525 [1:14:06<06:40,  9.06it/s]

 91%|███████████████████████████████   | 38898/42525 [1:14:07<07:09,  8.44it/s]

 91%|███████████████████████████████   | 38900/42525 [1:14:07<06:45,  8.94it/s]

 91%|███████████████████████████████   | 38902/42525 [1:14:07<06:50,  8.83it/s]

 91%|███████████████████████████████   | 38904/42525 [1:14:07<06:50,  8.82it/s]

 91%|███████████████████████████████   | 38906/42525 [1:14:08<07:23,  8.16it/s]

 91%|███████████████████████████████   | 38908/42525 [1:14:08<06:47,  8.88it/s]

 91%|███████████████████████████████   | 38910/42525 [1:14:08<07:04,  8.52it/s]

 92%|███████████████████████████████   | 38912/42525 [1:14:08<06:58,  8.64it/s]

 92%|███████████████████████████████   | 38914/42525 [1:14:08<06:33,  9.18it/s]

 92%|███████████████████████████████   | 38915/42525 [1:14:09<06:24,  9.39it/s]

 92%|███████████████████████████████   | 38917/42525 [1:14:09<06:16,  9.58it/s]

 92%|███████████████████████████████   | 38920/42525 [1:14:09<06:11,  9.71it/s]

 92%|███████████████████████████████   | 38923/42525 [1:14:09<06:29,  9.25it/s]

 92%|███████████████████████████████   | 38925/42525 [1:14:10<07:30,  8.00it/s]

 92%|███████████████████████████████   | 38928/42525 [1:14:10<06:40,  8.99it/s]

 92%|███████████████████████████████▏  | 38930/42525 [1:14:10<06:41,  8.94it/s]

 92%|███████████████████████████████▏  | 38932/42525 [1:14:10<06:28,  9.25it/s]

 92%|███████████████████████████████▏  | 38934/42525 [1:14:11<06:38,  9.01it/s]

 92%|███████████████████████████████▏  | 38937/42525 [1:14:11<06:20,  9.42it/s]

 92%|███████████████████████████████▏  | 38939/42525 [1:14:11<07:01,  8.51it/s]

 92%|███████████████████████████████▏  | 38940/42525 [1:14:11<06:44,  8.87it/s]

 92%|███████████████████████████████▏  | 38943/42525 [1:14:12<06:56,  8.59it/s]

 92%|███████████████████████████████▏  | 38946/42525 [1:14:12<06:27,  9.23it/s]

 92%|███████████████████████████████▏  | 38948/42525 [1:14:12<06:32,  9.11it/s]

 92%|███████████████████████████████▏  | 38950/42525 [1:14:12<06:20,  9.39it/s]

 92%|███████████████████████████████▏  | 38952/42525 [1:14:13<06:44,  8.83it/s]

 92%|███████████████████████████████▏  | 38954/42525 [1:14:13<07:12,  8.26it/s]

 92%|███████████████████████████████▏  | 38956/42525 [1:14:13<06:41,  8.89it/s]

 92%|███████████████████████████████▏  | 38958/42525 [1:14:13<06:35,  9.02it/s]

 92%|███████████████████████████████▏  | 38959/42525 [1:14:13<07:01,  8.45it/s]

 92%|███████████████████████████████▏  | 38963/42525 [1:14:14<06:11,  9.58it/s]

 92%|███████████████████████████████▏  | 38965/42525 [1:14:14<06:12,  9.55it/s]

 92%|███████████████████████████████▏  | 38967/42525 [1:14:14<06:21,  9.33it/s]

 92%|███████████████████████████████▏  | 38969/42525 [1:14:14<06:40,  8.87it/s]

 92%|███████████████████████████████▏  | 38971/42525 [1:14:15<07:23,  8.02it/s]

 92%|███████████████████████████████▏  | 38973/42525 [1:14:15<07:25,  7.98it/s]

 92%|███████████████████████████████▏  | 38975/42525 [1:14:15<06:57,  8.50it/s]

 92%|███████████████████████████████▏  | 38977/42525 [1:14:15<06:43,  8.80it/s]

 92%|███████████████████████████████▏  | 38979/42525 [1:14:16<06:36,  8.95it/s]

 92%|███████████████████████████████▏  | 38981/42525 [1:14:16<06:37,  8.92it/s]

 92%|███████████████████████████████▏  | 38983/42525 [1:14:16<06:24,  9.22it/s]

 92%|███████████████████████████████▏  | 38985/42525 [1:14:16<06:32,  9.01it/s]

 92%|███████████████████████████████▏  | 38987/42525 [1:14:17<06:23,  9.23it/s]

 92%|███████████████████████████████▏  | 38989/42525 [1:14:17<06:20,  9.29it/s]

 92%|███████████████████████████████▏  | 38991/42525 [1:14:17<06:51,  8.58it/s]

 92%|███████████████████████████████▏  | 38994/42525 [1:14:17<06:58,  8.43it/s]

 92%|███████████████████████████████▏  | 38996/42525 [1:14:18<06:33,  8.96it/s]

 92%|███████████████████████████████▏  | 38998/42525 [1:14:18<06:30,  9.02it/s]

 92%|███████████████████████████████▏  | 39000/42525 [1:14:18<06:25,  9.14it/s]

 92%|███████████████████████████████▏  | 39002/42525 [1:14:18<06:15,  9.39it/s]

 92%|███████████████████████████████▏  | 39004/42525 [1:14:18<06:42,  8.74it/s]

 92%|███████████████████████████████▏  | 39006/42525 [1:14:19<06:56,  8.45it/s]

 92%|███████████████████████████████▏  | 39007/42525 [1:14:19<06:42,  8.74it/s]

 92%|███████████████████████████████▏  | 39010/42525 [1:14:19<06:36,  8.87it/s]

 92%|███████████████████████████████▏  | 39012/42525 [1:14:19<06:57,  8.42it/s]

 92%|███████████████████████████████▏  | 39014/42525 [1:14:20<07:48,  7.50it/s]

 92%|███████████████████████████████▏  | 39017/42525 [1:14:20<06:41,  8.74it/s]

 92%|███████████████████████████████▏  | 39020/42525 [1:14:20<06:45,  8.64it/s]

 92%|███████████████████████████████▏  | 39021/42525 [1:14:21<07:12,  8.11it/s]

 92%|███████████████████████████████▏  | 39025/42525 [1:14:21<06:19,  9.22it/s]

 92%|███████████████████████████████▏  | 39027/42525 [1:14:21<06:50,  8.53it/s]

 92%|███████████████████████████████▏  | 39029/42525 [1:14:21<06:30,  8.95it/s]

 92%|███████████████████████████████▏  | 39032/42525 [1:14:22<06:28,  8.99it/s]

 92%|███████████████████████████████▏  | 39034/42525 [1:14:22<06:45,  8.62it/s]

 92%|███████████████████████████████▏  | 39037/42525 [1:14:22<06:31,  8.92it/s]

 92%|███████████████████████████████▏  | 39039/42525 [1:14:23<07:05,  8.19it/s]

 92%|███████████████████████████████▏  | 39041/42525 [1:14:23<06:39,  8.72it/s]

 92%|███████████████████████████████▏  | 39043/42525 [1:14:23<06:28,  8.97it/s]

 92%|███████████████████████████████▏  | 39045/42525 [1:14:23<06:55,  8.37it/s]

 92%|███████████████████████████████▏  | 39047/42525 [1:14:23<06:33,  8.83it/s]

 92%|███████████████████████████████▏  | 39049/42525 [1:14:24<07:35,  7.62it/s]

 92%|███████████████████████████████▏  | 39051/42525 [1:14:24<07:07,  8.12it/s]

 92%|███████████████████████████████▏  | 39053/42525 [1:14:24<07:23,  7.82it/s]

 92%|███████████████████████████████▏  | 39055/42525 [1:14:25<08:05,  7.15it/s]

 92%|███████████████████████████████▏  | 39057/42525 [1:14:25<07:06,  8.13it/s]

 92%|███████████████████████████████▏  | 39059/42525 [1:14:25<06:54,  8.37it/s]

 92%|███████████████████████████████▏  | 39061/42525 [1:14:25<06:35,  8.76it/s]

 92%|███████████████████████████████▏  | 39063/42525 [1:14:25<07:03,  8.17it/s]

 92%|███████████████████████████████▏  | 39066/42525 [1:14:26<06:23,  9.02it/s]

 92%|███████████████████████████████▏  | 39068/42525 [1:14:26<06:59,  8.25it/s]

 92%|███████████████████████████████▏  | 39070/42525 [1:14:26<07:24,  7.76it/s]

 92%|███████████████████████████████▏  | 39072/42525 [1:14:27<06:42,  8.58it/s]

 92%|███████████████████████████████▏  | 39074/42525 [1:14:27<07:05,  8.10it/s]

 92%|███████████████████████████████▏  | 39077/42525 [1:14:27<06:18,  9.10it/s]

 92%|███████████████████████████████▏  | 39080/42525 [1:14:27<06:35,  8.70it/s]

 92%|███████████████████████████████▏  | 39082/42525 [1:14:28<06:25,  8.92it/s]

 92%|███████████████████████████████▏  | 39084/42525 [1:14:28<06:55,  8.28it/s]

 92%|███████████████████████████████▎  | 39086/42525 [1:14:28<07:08,  8.03it/s]

 92%|███████████████████████████████▎  | 39088/42525 [1:14:28<06:33,  8.74it/s]

 92%|███████████████████████████████▎  | 39092/42525 [1:14:29<05:57,  9.60it/s]

 92%|███████████████████████████████▎  | 39094/42525 [1:14:29<06:23,  8.96it/s]

 92%|███████████████████████████████▎  | 39096/42525 [1:14:29<06:07,  9.32it/s]

 92%|███████████████████████████████▎  | 39099/42525 [1:14:30<06:31,  8.74it/s]

 92%|███████████████████████████████▎  | 39101/42525 [1:14:30<07:02,  8.10it/s]

 92%|███████████████████████████████▎  | 39104/42525 [1:14:30<06:59,  8.16it/s]

 92%|███████████████████████████████▎  | 39105/42525 [1:14:30<07:20,  7.77it/s]

 92%|███████████████████████████████▎  | 39108/42525 [1:14:31<06:29,  8.77it/s]

 92%|███████████████████████████████▎  | 39110/42525 [1:14:31<06:16,  9.08it/s]

 92%|███████████████████████████████▎  | 39112/42525 [1:14:31<06:42,  8.48it/s]

 92%|███████████████████████████████▎  | 39114/42525 [1:14:31<07:39,  7.43it/s]

 92%|███████████████████████████████▎  | 39116/42525 [1:14:32<06:57,  8.17it/s]

 92%|███████████████████████████████▎  | 39118/42525 [1:14:32<06:26,  8.80it/s]

 92%|███████████████████████████████▎  | 39120/42525 [1:14:32<06:46,  8.37it/s]

 92%|███████████████████████████████▎  | 39122/42525 [1:14:32<06:52,  8.25it/s]

 92%|███████████████████████████████▎  | 39124/42525 [1:14:33<06:54,  8.21it/s]

 92%|███████████████████████████████▎  | 39126/42525 [1:14:33<06:40,  8.49it/s]

 92%|███████████████████████████████▎  | 39128/42525 [1:14:33<06:14,  9.07it/s]

 92%|███████████████████████████████▎  | 39130/42525 [1:14:33<06:52,  8.23it/s]

 92%|███████████████████████████████▎  | 39132/42525 [1:14:34<06:42,  8.42it/s]

 92%|███████████████████████████████▎  | 39134/42525 [1:14:34<07:11,  7.86it/s]

 92%|███████████████████████████████▎  | 39136/42525 [1:14:34<07:01,  8.04it/s]

 92%|███████████████████████████████▎  | 39138/42525 [1:14:34<06:35,  8.57it/s]

 92%|███████████████████████████████▎  | 39141/42525 [1:14:35<06:17,  8.97it/s]

 92%|███████████████████████████████▎  | 39143/42525 [1:14:35<06:55,  8.14it/s]

 92%|███████████████████████████████▎  | 39145/42525 [1:14:35<06:21,  8.86it/s]

 92%|███████████████████████████████▎  | 39147/42525 [1:14:35<07:17,  7.71it/s]

 92%|███████████████████████████████▎  | 39149/42525 [1:14:36<07:52,  7.14it/s]

 92%|███████████████████████████████▎  | 39151/42525 [1:14:36<07:19,  7.67it/s]

 92%|███████████████████████████████▎  | 39152/42525 [1:14:36<07:05,  7.92it/s]

 92%|███████████████████████████████▎  | 39155/42525 [1:14:36<06:21,  8.84it/s]

 92%|███████████████████████████████▎  | 39157/42525 [1:14:37<06:53,  8.14it/s]

 92%|███████████████████████████████▎  | 39159/42525 [1:14:37<06:51,  8.17it/s]

 92%|███████████████████████████████▎  | 39162/42525 [1:14:37<06:14,  8.97it/s]

 92%|███████████████████████████████▎  | 39163/42525 [1:14:37<06:05,  9.21it/s]

 92%|███████████████████████████████▎  | 39166/42525 [1:14:38<06:27,  8.67it/s]

 92%|███████████████████████████████▎  | 39168/42525 [1:14:38<06:52,  8.13it/s]

 92%|███████████████████████████████▎  | 39170/42525 [1:14:38<06:15,  8.93it/s]

 92%|███████████████████████████████▎  | 39172/42525 [1:14:38<06:36,  8.45it/s]

 92%|███████████████████████████████▎  | 39174/42525 [1:14:39<06:42,  8.32it/s]

 92%|███████████████████████████████▎  | 39176/42525 [1:14:39<06:32,  8.53it/s]

 92%|███████████████████████████████▎  | 39178/42525 [1:14:39<06:11,  9.02it/s]

 92%|███████████████████████████████▎  | 39180/42525 [1:14:39<06:18,  8.85it/s]

 92%|███████████████████████████████▎  | 39182/42525 [1:14:40<06:43,  8.29it/s]

 92%|███████████████████████████████▎  | 39184/42525 [1:14:40<06:10,  9.03it/s]

 92%|███████████████████████████████▎  | 39186/42525 [1:14:40<06:04,  9.15it/s]

 92%|███████████████████████████████▎  | 39188/42525 [1:14:40<06:05,  9.12it/s]

 92%|███████████████████████████████▎  | 39191/42525 [1:14:40<06:10,  9.00it/s]

 92%|███████████████████████████████▎  | 39193/42525 [1:14:41<07:04,  7.85it/s]

 92%|███████████████████████████████▎  | 39195/42525 [1:14:41<06:39,  8.34it/s]

 92%|███████████████████████████████▎  | 39197/42525 [1:14:41<06:56,  8.00it/s]

 92%|███████████████████████████████▎  | 39199/42525 [1:14:42<06:55,  8.01it/s]

 92%|███████████████████████████████▎  | 39201/42525 [1:14:42<07:42,  7.19it/s]

 92%|███████████████████████████████▎  | 39203/42525 [1:14:42<06:57,  7.95it/s]

 92%|███████████████████████████████▎  | 39206/42525 [1:14:42<06:15,  8.84it/s]

 92%|███████████████████████████████▎  | 39210/42525 [1:14:43<05:46,  9.57it/s]

 92%|███████████████████████████████▎  | 39212/42525 [1:14:43<06:11,  8.93it/s]

 92%|███████████████████████████████▎  | 39216/42525 [1:14:43<05:41,  9.69it/s]

 92%|███████████████████████████████▎  | 39219/42525 [1:14:44<05:45,  9.56it/s]

 92%|███████████████████████████████▎  | 39221/42525 [1:14:44<05:54,  9.31it/s]

 92%|███████████████████████████████▎  | 39224/42525 [1:14:44<05:42,  9.63it/s]

 92%|███████████████████████████████▎  | 39225/42525 [1:14:44<05:48,  9.46it/s]

 92%|███████████████████████████████▎  | 39229/42525 [1:14:45<05:55,  9.28it/s]

 92%|███████████████████████████████▎  | 39231/42525 [1:14:45<05:53,  9.33it/s]

 92%|███████████████████████████████▎  | 39235/42525 [1:14:45<05:33,  9.86it/s]

 92%|███████████████████████████████▎  | 39237/42525 [1:14:46<05:48,  9.44it/s]

 92%|███████████████████████████████▎  | 39240/42525 [1:14:46<05:35,  9.80it/s]

 92%|███████████████████████████████▍  | 39242/42525 [1:14:46<05:38,  9.69it/s]

 92%|███████████████████████████████▍  | 39244/42525 [1:14:46<05:44,  9.52it/s]

 92%|███████████████████████████████▍  | 39246/42525 [1:14:47<06:23,  8.55it/s]

 92%|███████████████████████████████▍  | 39249/42525 [1:14:47<06:17,  8.69it/s]

 92%|███████████████████████████████▍  | 39251/42525 [1:14:47<06:45,  8.07it/s]

 92%|███████████████████████████████▍  | 39253/42525 [1:14:47<06:58,  7.82it/s]

 92%|███████████████████████████████▍  | 39255/42525 [1:14:48<06:16,  8.70it/s]

 92%|███████████████████████████████▍  | 39257/42525 [1:14:48<07:04,  7.71it/s]

 92%|███████████████████████████████▍  | 39259/42525 [1:14:48<06:27,  8.44it/s]

 92%|███████████████████████████████▍  | 39261/42525 [1:14:48<05:57,  9.13it/s]

 92%|███████████████████████████████▍  | 39262/42525 [1:14:49<06:35,  8.25it/s]

 92%|███████████████████████████████▍  | 39265/42525 [1:14:49<06:20,  8.57it/s]

 92%|███████████████████████████████▍  | 39267/42525 [1:14:49<07:03,  7.70it/s]

 92%|███████████████████████████████▍  | 39269/42525 [1:14:49<06:22,  8.51it/s]

 92%|███████████████████████████████▍  | 39271/42525 [1:14:50<05:58,  9.07it/s]

 92%|███████████████████████████████▍  | 39274/42525 [1:14:50<06:20,  8.53it/s]

 92%|███████████████████████████████▍  | 39276/42525 [1:14:50<06:05,  8.88it/s]

 92%|███████████████████████████████▍  | 39277/42525 [1:14:50<06:07,  8.84it/s]

 92%|███████████████████████████████▍  | 39279/42525 [1:14:50<06:08,  8.80it/s]

 92%|███████████████████████████████▍  | 39282/42525 [1:14:51<06:09,  8.78it/s]

 92%|███████████████████████████████▍  | 39284/42525 [1:14:51<06:40,  8.10it/s]

 92%|███████████████████████████████▍  | 39286/42525 [1:14:51<06:11,  8.71it/s]

 92%|███████████████████████████████▍  | 39288/42525 [1:14:52<06:00,  8.97it/s]

 92%|███████████████████████████████▍  | 39290/42525 [1:14:52<06:31,  8.26it/s]

 92%|███████████████████████████████▍  | 39292/42525 [1:14:52<06:57,  7.74it/s]

 92%|███████████████████████████████▍  | 39294/42525 [1:14:52<07:03,  7.64it/s]

 92%|███████████████████████████████▍  | 39295/42525 [1:14:52<07:23,  7.29it/s]

 92%|███████████████████████████████▍  | 39298/42525 [1:14:53<06:49,  7.87it/s]

 92%|███████████████████████████████▍  | 39300/42525 [1:14:53<06:14,  8.61it/s]

 92%|███████████████████████████████▍  | 39302/42525 [1:14:53<05:58,  9.00it/s]

 92%|███████████████████████████████▍  | 39304/42525 [1:14:53<05:48,  9.25it/s]

 92%|███████████████████████████████▍  | 39307/42525 [1:14:54<05:33,  9.66it/s]

 92%|███████████████████████████████▍  | 39309/42525 [1:14:54<05:34,  9.62it/s]

 92%|███████████████████████████████▍  | 39311/42525 [1:14:54<05:35,  9.58it/s]

 92%|███████████████████████████████▍  | 39313/42525 [1:14:54<05:46,  9.27it/s]

 92%|███████████████████████████████▍  | 39314/42525 [1:14:55<06:22,  8.40it/s]

 92%|███████████████████████████████▍  | 39317/42525 [1:14:55<05:53,  9.07it/s]

 92%|███████████████████████████████▍  | 39319/42525 [1:14:55<05:40,  9.42it/s]

 92%|███████████████████████████████▍  | 39321/42525 [1:14:55<05:38,  9.47it/s]

 92%|███████████████████████████████▍  | 39323/42525 [1:14:55<05:37,  9.49it/s]

 92%|███████████████████████████████▍  | 39325/42525 [1:14:56<06:01,  8.85it/s]

 92%|███████████████████████████████▍  | 39327/42525 [1:14:56<06:26,  8.28it/s]

 92%|███████████████████████████████▍  | 39329/42525 [1:14:56<06:16,  8.50it/s]

 92%|███████████████████████████████▍  | 39331/42525 [1:14:56<06:12,  8.57it/s]

 92%|███████████████████████████████▍  | 39333/42525 [1:14:57<06:25,  8.29it/s]

 92%|███████████████████████████████▍  | 39335/42525 [1:14:57<06:08,  8.66it/s]

 93%|███████████████████████████████▍  | 39337/42525 [1:14:57<05:53,  9.03it/s]

 93%|███████████████████████████████▍  | 39339/42525 [1:14:57<06:11,  8.56it/s]

 93%|███████████████████████████████▍  | 39341/42525 [1:14:58<06:43,  7.90it/s]

 93%|███████████████████████████████▍  | 39343/42525 [1:14:58<06:15,  8.48it/s]

 93%|███████████████████████████████▍  | 39346/42525 [1:14:58<05:40,  9.33it/s]

 93%|███████████████████████████████▍  | 39348/42525 [1:14:58<06:26,  8.23it/s]

 93%|███████████████████████████████▍  | 39350/42525 [1:14:59<05:59,  8.83it/s]

 93%|███████████████████████████████▍  | 39352/42525 [1:14:59<06:37,  7.99it/s]

 93%|███████████████████████████████▍  | 39354/42525 [1:14:59<06:46,  7.81it/s]

 93%|███████████████████████████████▍  | 39356/42525 [1:14:59<06:34,  8.04it/s]

 93%|███████████████████████████████▍  | 39358/42525 [1:15:00<06:30,  8.12it/s]

 93%|███████████████████████████████▍  | 39360/42525 [1:15:00<06:18,  8.37it/s]

 93%|███████████████████████████████▍  | 39362/42525 [1:15:00<06:04,  8.67it/s]

 93%|███████████████████████████████▍  | 39364/42525 [1:15:00<06:14,  8.44it/s]

 93%|███████████████████████████████▍  | 39366/42525 [1:15:01<06:30,  8.08it/s]

 93%|███████████████████████████████▍  | 39367/42525 [1:15:01<06:14,  8.43it/s]

 93%|███████████████████████████████▍  | 39371/42525 [1:15:01<05:38,  9.31it/s]

 93%|███████████████████████████████▍  | 39373/42525 [1:15:01<05:39,  9.28it/s]

 93%|███████████████████████████████▍  | 39375/42525 [1:15:02<05:59,  8.76it/s]

 93%|███████████████████████████████▍  | 39378/42525 [1:15:02<05:50,  8.99it/s]

 93%|███████████████████████████████▍  | 39380/42525 [1:15:02<05:45,  9.10it/s]

 93%|███████████████████████████████▍  | 39382/42525 [1:15:02<05:53,  8.90it/s]

 93%|███████████████████████████████▍  | 39383/42525 [1:15:02<05:42,  9.17it/s]

 93%|███████████████████████████████▍  | 39385/42525 [1:15:03<05:33,  9.41it/s]

 93%|███████████████████████████████▍  | 39388/42525 [1:15:03<06:00,  8.71it/s]

 93%|███████████████████████████████▍  | 39390/42525 [1:15:03<06:10,  8.47it/s]

 93%|███████████████████████████████▍  | 39392/42525 [1:15:04<06:42,  7.77it/s]

 93%|███████████████████████████████▍  | 39394/42525 [1:15:04<06:45,  7.71it/s]

 93%|███████████████████████████████▍  | 39396/42525 [1:15:04<06:45,  7.71it/s]

 93%|███████████████████████████████▍  | 39397/42525 [1:15:04<06:29,  8.03it/s]

 93%|███████████████████████████████▌  | 39400/42525 [1:15:05<05:46,  9.01it/s]

 93%|███████████████████████████████▌  | 39402/42525 [1:15:05<05:58,  8.71it/s]

 93%|███████████████████████████████▌  | 39404/42525 [1:15:05<06:03,  8.58it/s]

 93%|███████████████████████████████▌  | 39406/42525 [1:15:05<06:11,  8.40it/s]

 93%|███████████████████████████████▌  | 39408/42525 [1:15:05<05:53,  8.83it/s]

 93%|███████████████████████████████▌  | 39410/42525 [1:15:06<06:12,  8.35it/s]

 93%|███████████████████████████████▌  | 39411/42525 [1:15:06<06:10,  8.41it/s]

 93%|███████████████████████████████▌  | 39414/42525 [1:15:06<06:12,  8.35it/s]

 93%|███████████████████████████████▌  | 39416/42525 [1:15:06<05:52,  8.81it/s]

 93%|███████████████████████████████▌  | 39418/42525 [1:15:07<05:50,  8.87it/s]

 93%|███████████████████████████████▌  | 39420/42525 [1:15:07<06:43,  7.69it/s]

 93%|███████████████████████████████▌  | 39422/42525 [1:15:07<06:37,  7.81it/s]

 93%|███████████████████████████████▌  | 39424/42525 [1:15:07<06:43,  7.68it/s]

 93%|███████████████████████████████▌  | 39425/42525 [1:15:08<06:23,  8.08it/s]

 93%|███████████████████████████████▌  | 39428/42525 [1:15:08<05:49,  8.86it/s]

 93%|███████████████████████████████▌  | 39430/42525 [1:15:08<05:34,  9.26it/s]

 93%|███████████████████████████████▌  | 39433/42525 [1:15:08<05:26,  9.46it/s]

 93%|███████████████████████████████▌  | 39435/42525 [1:15:09<05:38,  9.12it/s]

 93%|███████████████████████████████▌  | 39437/42525 [1:15:09<06:19,  8.13it/s]

 93%|███████████████████████████████▌  | 39439/42525 [1:15:09<05:52,  8.75it/s]

 93%|███████████████████████████████▌  | 39441/42525 [1:15:09<05:54,  8.70it/s]

 93%|███████████████████████████████▌  | 39443/42525 [1:15:09<05:34,  9.22it/s]

 93%|███████████████████████████████▌  | 39445/42525 [1:15:10<06:07,  8.39it/s]

 93%|███████████████████████████████▌  | 39447/42525 [1:15:10<05:52,  8.74it/s]

 93%|███████████████████████████████▌  | 39449/42525 [1:15:10<05:39,  9.06it/s]

 93%|███████████████████████████████▌  | 39451/42525 [1:15:10<06:00,  8.54it/s]

 93%|███████████████████████████████▌  | 39453/42525 [1:15:11<05:33,  9.20it/s]

 93%|███████████████████████████████▌  | 39455/42525 [1:15:11<05:28,  9.33it/s]

 93%|███████████████████████████████▌  | 39457/42525 [1:15:11<05:26,  9.41it/s]

 93%|███████████████████████████████▌  | 39459/42525 [1:15:11<05:51,  8.73it/s]

 93%|███████████████████████████████▌  | 39461/42525 [1:15:12<05:51,  8.71it/s]

 93%|███████████████████████████████▌  | 39463/42525 [1:15:12<06:11,  8.23it/s]

 93%|███████████████████████████████▌  | 39465/42525 [1:15:12<05:44,  8.87it/s]

 93%|███████████████████████████████▌  | 39468/42525 [1:15:12<05:48,  8.77it/s]

 93%|███████████████████████████████▌  | 39470/42525 [1:15:13<06:22,  7.99it/s]

 93%|███████████████████████████████▌  | 39472/42525 [1:15:13<05:56,  8.58it/s]

 93%|███████████████████████████████▌  | 39474/42525 [1:15:13<05:58,  8.52it/s]

 93%|███████████████████████████████▌  | 39476/42525 [1:15:13<05:40,  8.96it/s]

 93%|███████████████████████████████▌  | 39478/42525 [1:15:13<05:27,  9.30it/s]

 93%|███████████████████████████████▌  | 39480/42525 [1:15:14<05:30,  9.21it/s]

 93%|███████████████████████████████▌  | 39482/42525 [1:15:14<06:14,  8.12it/s]

 93%|███████████████████████████████▌  | 39484/42525 [1:15:14<06:58,  7.26it/s]

 93%|███████████████████████████████▌  | 39486/42525 [1:15:15<06:16,  8.07it/s]

 93%|███████████████████████████████▌  | 39488/42525 [1:15:15<06:24,  7.91it/s]

 93%|███████████████████████████████▌  | 39490/42525 [1:15:15<05:54,  8.55it/s]

 93%|███████████████████████████████▌  | 39492/42525 [1:15:15<05:45,  8.79it/s]

 93%|███████████████████████████████▌  | 39495/42525 [1:15:15<05:16,  9.57it/s]

 93%|███████████████████████████████▌  | 39497/42525 [1:15:16<05:14,  9.62it/s]

 93%|███████████████████████████████▌  | 39499/42525 [1:15:16<05:28,  9.22it/s]

 93%|███████████████████████████████▌  | 39501/42525 [1:15:16<06:15,  8.04it/s]

 93%|███████████████████████████████▌  | 39503/42525 [1:15:16<06:05,  8.26it/s]

 93%|███████████████████████████████▌  | 39505/42525 [1:15:17<06:00,  8.37it/s]

 93%|███████████████████████████████▌  | 39507/42525 [1:15:17<06:06,  8.22it/s]

 93%|███████████████████████████████▌  | 39509/42525 [1:15:17<05:48,  8.67it/s]

 93%|███████████████████████████████▌  | 39510/42525 [1:15:17<05:44,  8.75it/s]

 93%|███████████████████████████████▌  | 39513/42525 [1:15:18<05:22,  9.33it/s]

 93%|███████████████████████████████▌  | 39515/42525 [1:15:18<05:29,  9.14it/s]

 93%|███████████████████████████████▌  | 39517/42525 [1:15:18<05:45,  8.71it/s]

 93%|███████████████████████████████▌  | 39520/42525 [1:15:18<05:29,  9.13it/s]

 93%|███████████████████████████████▌  | 39522/42525 [1:15:19<05:56,  8.42it/s]

 93%|███████████████████████████████▌  | 39524/42525 [1:15:19<06:06,  8.19it/s]

 93%|███████████████████████████████▌  | 39526/42525 [1:15:19<06:34,  7.60it/s]

 93%|███████████████████████████████▌  | 39528/42525 [1:15:19<06:01,  8.30it/s]

 93%|███████████████████████████████▌  | 39530/42525 [1:15:20<05:43,  8.72it/s]

 93%|███████████████████████████████▌  | 39532/42525 [1:15:20<06:01,  8.28it/s]

 93%|███████████████████████████████▌  | 39534/42525 [1:15:20<05:34,  8.94it/s]

 93%|███████████████████████████████▌  | 39536/42525 [1:15:20<05:51,  8.50it/s]

 93%|███████████████████████████████▌  | 39538/42525 [1:15:21<05:55,  8.40it/s]

 93%|███████████████████████████████▌  | 39540/42525 [1:15:21<06:23,  7.79it/s]

 93%|███████████████████████████████▌  | 39543/42525 [1:15:21<05:44,  8.66it/s]

 93%|███████████████████████████████▌  | 39544/42525 [1:15:21<05:49,  8.53it/s]

 93%|███████████████████████████████▌  | 39547/42525 [1:15:22<05:40,  8.75it/s]

 93%|███████████████████████████████▌  | 39549/42525 [1:15:22<05:57,  8.32it/s]

 93%|███████████████████████████████▌  | 39551/42525 [1:15:22<05:37,  8.80it/s]

 93%|███████████████████████████████▌  | 39553/42525 [1:15:22<05:23,  9.19it/s]

 93%|███████████████████████████████▌  | 39554/42525 [1:15:22<05:28,  9.03it/s]

 93%|███████████████████████████████▋  | 39557/42525 [1:15:23<05:26,  9.10it/s]

 93%|███████████████████████████████▋  | 39560/42525 [1:15:23<05:09,  9.57it/s]

 93%|███████████████████████████████▋  | 39562/42525 [1:15:23<05:23,  9.15it/s]

 93%|███████████████████████████████▋  | 39564/42525 [1:15:23<05:19,  9.26it/s]

 93%|███████████████████████████████▋  | 39566/42525 [1:15:24<05:35,  8.83it/s]

 93%|███████████████████████████████▋  | 39568/42525 [1:15:24<05:42,  8.62it/s]

 93%|███████████████████████████████▋  | 39570/42525 [1:15:24<05:48,  8.48it/s]

 93%|███████████████████████████████▋  | 39572/42525 [1:15:24<05:35,  8.81it/s]

 93%|███████████████████████████████▋  | 39574/42525 [1:15:25<05:40,  8.68it/s]

 93%|███████████████████████████████▋  | 39576/42525 [1:15:25<05:48,  8.47it/s]

 93%|███████████████████████████████▋  | 39578/42525 [1:15:25<06:14,  7.88it/s]

 93%|███████████████████████████████▋  | 39580/42525 [1:15:25<06:26,  7.61it/s]

 93%|███████████████████████████████▋  | 39582/42525 [1:15:26<05:54,  8.31it/s]

 93%|███████████████████████████████▋  | 39584/42525 [1:15:26<05:53,  8.32it/s]

 93%|███████████████████████████████▋  | 39586/42525 [1:15:26<05:55,  8.28it/s]

 93%|███████████████████████████████▋  | 39588/42525 [1:15:26<06:00,  8.15it/s]

 93%|███████████████████████████████▋  | 39590/42525 [1:15:27<05:41,  8.60it/s]

 93%|███████████████████████████████▋  | 39592/42525 [1:15:27<05:20,  9.15it/s]

 93%|███████████████████████████████▋  | 39594/42525 [1:15:27<05:52,  8.32it/s]

 93%|███████████████████████████████▋  | 39597/42525 [1:15:27<05:25,  9.00it/s]

 93%|███████████████████████████████▋  | 39599/42525 [1:15:28<06:11,  7.88it/s]

 93%|███████████████████████████████▋  | 39601/42525 [1:15:28<05:49,  8.38it/s]

 93%|███████████████████████████████▋  | 39604/42525 [1:15:28<05:40,  8.57it/s]

 93%|███████████████████████████████▋  | 39606/42525 [1:15:28<05:24,  9.00it/s]

 93%|███████████████████████████████▋  | 39608/42525 [1:15:29<05:38,  8.62it/s]

 93%|███████████████████████████████▋  | 39611/42525 [1:15:29<05:11,  9.34it/s]

 93%|███████████████████████████████▋  | 39613/42525 [1:15:29<05:43,  8.47it/s]

 93%|███████████████████████████████▋  | 39615/42525 [1:15:29<05:49,  8.33it/s]

 93%|███████████████████████████████▋  | 39617/42525 [1:15:30<05:50,  8.30it/s]

 93%|███████████████████████████████▋  | 39619/42525 [1:15:30<05:28,  8.86it/s]

 93%|███████████████████████████████▋  | 39621/42525 [1:15:30<05:16,  9.18it/s]

 93%|███████████████████████████████▋  | 39623/42525 [1:15:30<05:28,  8.83it/s]

 93%|███████████████████████████████▋  | 39626/42525 [1:15:31<05:09,  9.37it/s]

 93%|███████████████████████████████▋  | 39628/42525 [1:15:31<05:16,  9.14it/s]

 93%|███████████████████████████████▋  | 39630/42525 [1:15:31<05:17,  9.12it/s]

 93%|███████████████████████████████▋  | 39633/42525 [1:15:31<05:13,  9.23it/s]

 93%|███████████████████████████████▋  | 39636/42525 [1:15:32<04:58,  9.69it/s]

 93%|███████████████████████████████▋  | 39638/42525 [1:15:32<05:31,  8.71it/s]

 93%|███████████████████████████████▋  | 39640/42525 [1:15:32<05:39,  8.50it/s]

 93%|███████████████████████████████▋  | 39642/42525 [1:15:33<05:56,  8.08it/s]

 93%|███████████████████████████████▋  | 39644/42525 [1:15:33<06:00,  7.99it/s]

 93%|███████████████████████████████▋  | 39646/42525 [1:15:33<06:02,  7.95it/s]

 93%|███████████████████████████████▋  | 39648/42525 [1:15:33<05:36,  8.56it/s]

 93%|███████████████████████████████▋  | 39651/42525 [1:15:34<05:07,  9.35it/s]

 93%|███████████████████████████████▋  | 39653/42525 [1:15:34<05:19,  8.98it/s]

 93%|███████████████████████████████▋  | 39655/42525 [1:15:34<05:10,  9.25it/s]

 93%|███████████████████████████████▋  | 39657/42525 [1:15:34<05:23,  8.88it/s]

 93%|███████████████████████████████▋  | 39659/42525 [1:15:34<05:53,  8.10it/s]

 93%|███████████████████████████████▋  | 39661/42525 [1:15:35<05:29,  8.69it/s]

 93%|███████████████████████████████▋  | 39663/42525 [1:15:35<05:11,  9.20it/s]

 93%|███████████████████████████████▋  | 39665/42525 [1:15:35<05:05,  9.35it/s]

 93%|███████████████████████████████▋  | 39667/42525 [1:15:35<05:29,  8.69it/s]

 93%|███████████████████████████████▋  | 39669/42525 [1:15:36<05:11,  9.18it/s]

 93%|███████████████████████████████▋  | 39671/42525 [1:15:36<05:37,  8.46it/s]

 93%|███████████████████████████████▋  | 39673/42525 [1:15:36<05:26,  8.73it/s]

 93%|███████████████████████████████▋  | 39675/42525 [1:15:36<05:51,  8.11it/s]

 93%|███████████████████████████████▋  | 39676/42525 [1:15:36<06:15,  7.59it/s]

 93%|███████████████████████████████▋  | 39679/42525 [1:15:37<05:29,  8.65it/s]

 93%|███████████████████████████████▋  | 39681/42525 [1:15:37<06:10,  7.68it/s]

 93%|███████████████████████████████▋  | 39684/42525 [1:15:37<05:43,  8.28it/s]

 93%|███████████████████████████████▋  | 39686/42525 [1:15:38<06:00,  7.87it/s]

 93%|███████████████████████████████▋  | 39688/42525 [1:15:38<05:31,  8.55it/s]

 93%|███████████████████████████████▋  | 39691/42525 [1:15:38<05:03,  9.34it/s]

 93%|███████████████████████████████▋  | 39693/42525 [1:15:38<05:02,  9.37it/s]

 93%|███████████████████████████████▋  | 39695/42525 [1:15:39<05:44,  8.20it/s]

 93%|███████████████████████████████▋  | 39697/42525 [1:15:39<05:34,  8.46it/s]

 93%|███████████████████████████████▋  | 39699/42525 [1:15:39<05:14,  8.97it/s]

 93%|███████████████████████████████▋  | 39701/42525 [1:15:39<05:43,  8.22it/s]

 93%|███████████████████████████████▋  | 39704/42525 [1:15:40<05:08,  9.14it/s]

 93%|███████████████████████████████▋  | 39706/42525 [1:15:40<05:12,  9.03it/s]

 93%|███████████████████████████████▋  | 39708/42525 [1:15:40<05:13,  8.99it/s]

 93%|███████████████████████████████▋  | 39710/42525 [1:15:40<05:47,  8.10it/s]

 93%|███████████████████████████████▊  | 39713/42525 [1:15:41<05:05,  9.19it/s]

 93%|███████████████████████████████▊  | 39715/42525 [1:15:41<05:02,  9.28it/s]

 93%|███████████████████████████████▊  | 39717/42525 [1:15:41<05:34,  8.39it/s]

 93%|███████████████████████████████▊  | 39719/42525 [1:15:41<05:37,  8.31it/s]

 93%|███████████████████████████████▊  | 39720/42525 [1:15:42<05:26,  8.59it/s]

 93%|███████████████████████████████▊  | 39723/42525 [1:15:42<05:21,  8.73it/s]

 93%|███████████████████████████████▊  | 39725/42525 [1:15:42<05:10,  9.03it/s]

 93%|███████████████████████████████▊  | 39727/42525 [1:15:42<04:59,  9.35it/s]

 93%|███████████████████████████████▊  | 39729/42525 [1:15:43<05:16,  8.84it/s]

 93%|███████████████████████████████▊  | 39731/42525 [1:15:43<05:28,  8.50it/s]

 93%|███████████████████████████████▊  | 39732/42525 [1:15:43<05:14,  8.87it/s]

 93%|███████████████████████████████▊  | 39735/42525 [1:15:43<05:32,  8.39it/s]

 93%|███████████████████████████████▊  | 39738/42525 [1:15:44<05:06,  9.09it/s]

 93%|███████████████████████████████▊  | 39741/42525 [1:15:44<04:48,  9.64it/s]

 93%|███████████████████████████████▊  | 39743/42525 [1:15:44<04:48,  9.64it/s]

 93%|███████████████████████████████▊  | 39745/42525 [1:15:44<05:21,  8.64it/s]

 93%|███████████████████████████████▊  | 39747/42525 [1:15:44<05:04,  9.12it/s]

 93%|███████████████████████████████▊  | 39749/42525 [1:15:45<05:15,  8.81it/s]

 93%|███████████████████████████████▊  | 39750/42525 [1:15:45<05:13,  8.84it/s]

 93%|███████████████████████████████▊  | 39753/42525 [1:15:45<05:18,  8.71it/s]

 93%|███████████████████████████████▊  | 39755/42525 [1:15:45<05:24,  8.54it/s]

 93%|███████████████████████████████▊  | 39757/42525 [1:15:46<05:20,  8.65it/s]

 93%|███████████████████████████████▊  | 39759/42525 [1:15:46<05:48,  7.94it/s]

 94%|███████████████████████████████▊  | 39761/42525 [1:15:46<05:33,  8.29it/s]

 94%|███████████████████████████████▊  | 39763/42525 [1:15:46<05:59,  7.69it/s]

 94%|███████████████████████████████▊  | 39765/42525 [1:15:47<06:05,  7.55it/s]

 94%|███████████████████████████████▊  | 39767/42525 [1:15:47<05:51,  7.84it/s]

 94%|███████████████████████████████▊  | 39769/42525 [1:15:47<05:19,  8.63it/s]

 94%|███████████████████████████████▊  | 39771/42525 [1:15:47<05:37,  8.16it/s]

 94%|███████████████████████████████▊  | 39773/42525 [1:15:48<06:04,  7.56it/s]

 94%|███████████████████████████████▊  | 39775/42525 [1:15:48<06:02,  7.58it/s]

 94%|███████████████████████████████▊  | 39777/42525 [1:15:48<05:20,  8.57it/s]

 94%|███████████████████████████████▊  | 39780/42525 [1:15:48<05:01,  9.10it/s]

 94%|███████████████████████████████▊  | 39782/42525 [1:15:49<05:10,  8.82it/s]

 94%|███████████████████████████████▊  | 39784/42525 [1:15:49<05:04,  9.01it/s]

 94%|███████████████████████████████▊  | 39786/42525 [1:15:49<05:16,  8.64it/s]

 94%|███████████████████████████████▊  | 39788/42525 [1:15:49<05:11,  8.79it/s]

 94%|███████████████████████████████▊  | 39790/42525 [1:15:50<05:07,  8.88it/s]

 94%|███████████████████████████████▊  | 39792/42525 [1:15:50<05:45,  7.90it/s]

 94%|███████████████████████████████▊  | 39795/42525 [1:15:50<05:19,  8.55it/s]

 94%|███████████████████████████████▊  | 39797/42525 [1:15:50<05:10,  8.77it/s]

 94%|███████████████████████████████▊  | 39799/42525 [1:15:51<05:15,  8.63it/s]

 94%|███████████████████████████████▊  | 39801/42525 [1:15:51<05:23,  8.43it/s]

 94%|███████████████████████████████▊  | 39803/42525 [1:15:51<05:20,  8.48it/s]

 94%|███████████████████████████████▊  | 39805/42525 [1:15:51<05:33,  8.15it/s]

 94%|███████████████████████████████▊  | 39807/42525 [1:15:52<05:12,  8.70it/s]

 94%|███████████████████████████████▊  | 39809/42525 [1:15:52<05:15,  8.60it/s]

 94%|███████████████████████████████▊  | 39811/42525 [1:15:52<05:00,  9.03it/s]

 94%|███████████████████████████████▊  | 39813/42525 [1:15:52<05:09,  8.77it/s]

 94%|███████████████████████████████▊  | 39815/42525 [1:15:53<05:08,  8.79it/s]

 94%|███████████████████████████████▊  | 39817/42525 [1:15:53<05:20,  8.45it/s]

 94%|███████████████████████████████▊  | 39820/42525 [1:15:53<04:57,  9.09it/s]

 94%|███████████████████████████████▊  | 39822/42525 [1:15:53<05:13,  8.62it/s]

 94%|███████████████████████████████▊  | 39824/42525 [1:15:54<05:34,  8.08it/s]

 94%|███████████████████████████████▊  | 39826/42525 [1:15:54<05:17,  8.50it/s]

 94%|███████████████████████████████▊  | 39828/42525 [1:15:54<05:49,  7.71it/s]

 94%|███████████████████████████████▊  | 39830/42525 [1:15:54<05:23,  8.33it/s]

 94%|███████████████████████████████▊  | 39832/42525 [1:15:55<05:02,  8.90it/s]

 94%|███████████████████████████████▊  | 39834/42525 [1:15:55<04:54,  9.12it/s]

 94%|███████████████████████████████▊  | 39836/42525 [1:15:55<05:04,  8.84it/s]

 94%|███████████████████████████████▊  | 39838/42525 [1:15:55<04:52,  9.19it/s]

 94%|███████████████████████████████▊  | 39840/42525 [1:15:55<05:53,  7.61it/s]

 94%|███████████████████████████████▊  | 39842/42525 [1:15:56<05:33,  8.04it/s]

 94%|███████████████████████████████▊  | 39844/42525 [1:15:56<05:30,  8.11it/s]

 94%|███████████████████████████████▊  | 39846/42525 [1:15:56<05:19,  8.39it/s]

 94%|███████████████████████████████▊  | 39848/42525 [1:15:56<05:24,  8.25it/s]

 94%|███████████████████████████████▊  | 39851/42525 [1:15:57<04:57,  8.99it/s]

 94%|███████████████████████████████▊  | 39853/42525 [1:15:57<05:17,  8.41it/s]

 94%|███████████████████████████████▊  | 39855/42525 [1:15:57<05:01,  8.85it/s]

 94%|███████████████████████████████▊  | 39858/42525 [1:15:58<04:38,  9.56it/s]

 94%|███████████████████████████████▊  | 39860/42525 [1:15:58<05:01,  8.83it/s]

 94%|███████████████████████████████▊  | 39862/42525 [1:15:58<05:13,  8.49it/s]

 94%|███████████████████████████████▊  | 39864/42525 [1:15:58<05:25,  8.18it/s]

 94%|███████████████████████████████▊  | 39866/42525 [1:15:59<05:51,  7.57it/s]

 94%|███████████████████████████████▉  | 39868/42525 [1:15:59<06:02,  7.33it/s]

 94%|███████████████████████████████▉  | 39870/42525 [1:15:59<05:34,  7.95it/s]

 94%|███████████████████████████████▉  | 39872/42525 [1:15:59<05:17,  8.36it/s]

 94%|███████████████████████████████▉  | 39874/42525 [1:16:00<05:42,  7.74it/s]

 94%|███████████████████████████████▉  | 39876/42525 [1:16:00<05:55,  7.45it/s]

 94%|███████████████████████████████▉  | 39879/42525 [1:16:00<05:29,  8.04it/s]

 94%|███████████████████████████████▉  | 39881/42525 [1:16:00<05:16,  8.37it/s]

 94%|███████████████████████████████▉  | 39884/42525 [1:16:01<04:49,  9.13it/s]

 94%|███████████████████████████████▉  | 39886/42525 [1:16:01<04:51,  9.06it/s]

 94%|███████████████████████████████▉  | 39888/42525 [1:16:01<05:30,  7.98it/s]

 94%|███████████████████████████████▉  | 39890/42525 [1:16:02<05:27,  8.04it/s]

 94%|███████████████████████████████▉  | 39892/42525 [1:16:02<05:11,  8.45it/s]

 94%|███████████████████████████████▉  | 39894/42525 [1:16:02<04:55,  8.89it/s]

 94%|███████████████████████████████▉  | 39896/42525 [1:16:02<04:44,  9.25it/s]

 94%|███████████████████████████████▉  | 39899/42525 [1:16:03<05:04,  8.63it/s]

 94%|███████████████████████████████▉  | 39901/42525 [1:16:03<05:04,  8.63it/s]

 94%|███████████████████████████████▉  | 39903/42525 [1:16:03<05:13,  8.37it/s]

 94%|███████████████████████████████▉  | 39904/42525 [1:16:03<05:34,  7.83it/s]

 94%|███████████████████████████████▉  | 39907/42525 [1:16:03<05:00,  8.72it/s]

 94%|███████████████████████████████▉  | 39909/42525 [1:16:04<05:00,  8.72it/s]

 94%|███████████████████████████████▉  | 39911/42525 [1:16:04<04:46,  9.13it/s]

 94%|███████████████████████████████▉  | 39913/42525 [1:16:04<05:15,  8.29it/s]

 94%|███████████████████████████████▉  | 39916/42525 [1:16:04<04:42,  9.24it/s]

 94%|███████████████████████████████▉  | 39918/42525 [1:16:05<04:50,  8.97it/s]

 94%|███████████████████████████████▉  | 39919/42525 [1:16:05<04:47,  9.08it/s]

 94%|███████████████████████████████▉  | 39922/42525 [1:16:05<04:37,  9.37it/s]

 94%|███████████████████████████████▉  | 39924/42525 [1:16:05<04:36,  9.42it/s]

 94%|███████████████████████████████▉  | 39927/42525 [1:16:06<04:32,  9.55it/s]

 94%|███████████████████████████████▉  | 39929/42525 [1:16:06<04:31,  9.58it/s]

 94%|███████████████████████████████▉  | 39931/42525 [1:16:06<04:29,  9.61it/s]

 94%|███████████████████████████████▉  | 39933/42525 [1:16:06<04:48,  8.98it/s]

 94%|███████████████████████████████▉  | 39936/42525 [1:16:07<04:38,  9.31it/s]

 94%|███████████████████████████████▉  | 39938/42525 [1:16:07<04:59,  8.64it/s]

 94%|███████████████████████████████▉  | 39941/42525 [1:16:07<04:40,  9.20it/s]

 94%|███████████████████████████████▉  | 39943/42525 [1:16:07<04:54,  8.76it/s]

 94%|███████████████████████████████▉  | 39945/42525 [1:16:08<05:21,  8.03it/s]

 94%|███████████████████████████████▉  | 39947/42525 [1:16:08<05:29,  7.83it/s]

 94%|███████████████████████████████▉  | 39949/42525 [1:16:08<05:26,  7.89it/s]

 94%|███████████████████████████████▉  | 39951/42525 [1:16:08<05:28,  7.84it/s]

 94%|███████████████████████████████▉  | 39953/42525 [1:16:09<04:58,  8.62it/s]

 94%|███████████████████████████████▉  | 39956/42525 [1:16:09<04:45,  8.99it/s]

 94%|███████████████████████████████▉  | 39958/42525 [1:16:09<04:38,  9.21it/s]

 94%|███████████████████████████████▉  | 39960/42525 [1:16:09<04:38,  9.22it/s]

 94%|███████████████████████████████▉  | 39964/42525 [1:16:10<04:21,  9.80it/s]

 94%|███████████████████████████████▉  | 39967/42525 [1:16:10<04:17,  9.93it/s]

 94%|███████████████████████████████▉  | 39969/42525 [1:16:10<04:19,  9.87it/s]

 94%|███████████████████████████████▉  | 39971/42525 [1:16:11<04:55,  8.64it/s]

 94%|███████████████████████████████▉  | 39973/42525 [1:16:11<05:17,  8.03it/s]

 94%|███████████████████████████████▉  | 39975/42525 [1:16:11<05:44,  7.41it/s]

 94%|███████████████████████████████▉  | 39977/42525 [1:16:11<05:38,  7.53it/s]

 94%|███████████████████████████████▉  | 39979/42525 [1:16:12<05:07,  8.27it/s]

 94%|███████████████████████████████▉  | 39981/42525 [1:16:12<05:06,  8.29it/s]

 94%|███████████████████████████████▉  | 39983/42525 [1:16:12<04:46,  8.87it/s]

 94%|███████████████████████████████▉  | 39985/42525 [1:16:12<04:44,  8.94it/s]

 94%|███████████████████████████████▉  | 39987/42525 [1:16:13<04:46,  8.85it/s]

 94%|███████████████████████████████▉  | 39989/42525 [1:16:13<04:44,  8.90it/s]

 94%|███████████████████████████████▉  | 39992/42525 [1:16:13<04:32,  9.31it/s]

 94%|███████████████████████████████▉  | 39995/42525 [1:16:13<04:24,  9.55it/s]

 94%|███████████████████████████████▉  | 39996/42525 [1:16:13<04:22,  9.64it/s]

 94%|███████████████████████████████▉  | 39999/42525 [1:16:14<04:44,  8.89it/s]

 94%|███████████████████████████████▉  | 40001/42525 [1:16:14<05:04,  8.29it/s]

 94%|███████████████████████████████▉  | 40003/42525 [1:16:14<04:41,  8.97it/s]

 94%|███████████████████████████████▉  | 40005/42525 [1:16:15<05:07,  8.21it/s]

 94%|███████████████████████████████▉  | 40007/42525 [1:16:15<05:06,  8.23it/s]

 94%|███████████████████████████████▉  | 40010/42525 [1:16:15<04:44,  8.85it/s]

 94%|███████████████████████████████▉  | 40012/42525 [1:16:15<04:39,  9.00it/s]

 94%|███████████████████████████████▉  | 40014/42525 [1:16:16<04:36,  9.08it/s]

 94%|███████████████████████████████▉  | 40018/42525 [1:16:16<04:23,  9.52it/s]

 94%|███████████████████████████████▉  | 40021/42525 [1:16:16<04:28,  9.33it/s]

 94%|███████████████████████████████▉  | 40022/42525 [1:16:16<04:39,  8.95it/s]

 94%|████████████████████████████████  | 40026/42525 [1:16:17<04:21,  9.56it/s]

 94%|████████████████████████████████  | 40028/42525 [1:16:17<04:43,  8.80it/s]

 94%|████████████████████████████████  | 40029/42525 [1:16:17<04:43,  8.82it/s]

 94%|████████████████████████████████  | 40032/42525 [1:16:18<04:38,  8.95it/s]

 94%|████████████████████████████████  | 40034/42525 [1:16:18<04:20,  9.57it/s]

 94%|████████████████████████████████  | 40037/42525 [1:16:18<04:22,  9.47it/s]

 94%|████████████████████████████████  | 40039/42525 [1:16:18<04:36,  8.99it/s]

 94%|████████████████████████████████  | 40041/42525 [1:16:19<04:59,  8.29it/s]

 94%|████████████████████████████████  | 40043/42525 [1:16:19<05:14,  7.88it/s]

 94%|████████████████████████████████  | 40045/42525 [1:16:19<05:34,  7.42it/s]

 94%|████████████████████████████████  | 40047/42525 [1:16:19<05:27,  7.56it/s]

 94%|████████████████████████████████  | 40049/42525 [1:16:20<04:58,  8.29it/s]

 94%|████████████████████████████████  | 40051/42525 [1:16:20<05:04,  8.12it/s]

 94%|████████████████████████████████  | 40053/42525 [1:16:20<04:50,  8.51it/s]

 94%|████████████████████████████████  | 40055/42525 [1:16:20<04:39,  8.83it/s]

 94%|████████████████████████████████  | 40057/42525 [1:16:21<04:48,  8.55it/s]

 94%|████████████████████████████████  | 40059/42525 [1:16:21<05:13,  7.87it/s]

 94%|████████████████████████████████  | 40061/42525 [1:16:21<04:47,  8.56it/s]

 94%|████████████████████████████████  | 40063/42525 [1:16:21<04:38,  8.85it/s]

 94%|████████████████████████████████  | 40065/42525 [1:16:21<04:32,  9.01it/s]

 94%|████████████████████████████████  | 40067/42525 [1:16:22<04:32,  9.00it/s]

 94%|████████████████████████████████  | 40069/42525 [1:16:22<05:19,  7.68it/s]

 94%|████████████████████████████████  | 40071/42525 [1:16:22<05:22,  7.61it/s]

 94%|████████████████████████████████  | 40073/42525 [1:16:23<05:43,  7.14it/s]

 94%|████████████████████████████████  | 40074/42525 [1:16:23<05:14,  7.79it/s]

 94%|████████████████████████████████  | 40077/42525 [1:16:23<04:35,  8.89it/s]

 94%|████████████████████████████████  | 40079/42525 [1:16:23<04:49,  8.45it/s]

 94%|████████████████████████████████  | 40081/42525 [1:16:23<04:32,  8.96it/s]

 94%|████████████████████████████████  | 40083/42525 [1:16:24<04:27,  9.13it/s]

 94%|████████████████████████████████  | 40085/42525 [1:16:24<04:28,  9.09it/s]

 94%|████████████████████████████████  | 40087/42525 [1:16:24<04:36,  8.82it/s]

 94%|████████████████████████████████  | 40089/42525 [1:16:24<04:28,  9.08it/s]

 94%|████████████████████████████████  | 40091/42525 [1:16:25<04:31,  8.97it/s]

 94%|████████████████████████████████  | 40093/42525 [1:16:25<04:32,  8.93it/s]

 94%|████████████████████████████████  | 40095/42525 [1:16:25<04:29,  9.02it/s]

 94%|████████████████████████████████  | 40096/42525 [1:16:25<04:22,  9.26it/s]

 94%|████████████████████████████████  | 40099/42525 [1:16:25<04:35,  8.82it/s]

 94%|████████████████████████████████  | 40101/42525 [1:16:26<04:51,  8.32it/s]

 94%|████████████████████████████████  | 40102/42525 [1:16:26<05:09,  7.83it/s]

 94%|████████████████████████████████  | 40106/42525 [1:16:26<04:27,  9.04it/s]

 94%|████████████████████████████████  | 40109/42525 [1:16:27<04:18,  9.34it/s]

 94%|████████████████████████████████  | 40111/42525 [1:16:27<04:21,  9.22it/s]

 94%|████████████████████████████████  | 40113/42525 [1:16:27<04:21,  9.22it/s]

 94%|████████████████████████████████  | 40115/42525 [1:16:27<04:23,  9.14it/s]

 94%|████████████████████████████████  | 40117/42525 [1:16:27<04:32,  8.83it/s]

 94%|████████████████████████████████  | 40119/42525 [1:16:28<04:30,  8.89it/s]

 94%|████████████████████████████████  | 40121/42525 [1:16:28<04:30,  8.90it/s]

 94%|████████████████████████████████  | 40123/42525 [1:16:28<04:43,  8.47it/s]

 94%|████████████████████████████████  | 40125/42525 [1:16:28<05:05,  7.86it/s]

 94%|████████████████████████████████  | 40127/42525 [1:16:29<04:41,  8.53it/s]

 94%|████████████████████████████████  | 40129/42525 [1:16:29<04:54,  8.13it/s]

 94%|████████████████████████████████  | 40131/42525 [1:16:29<04:42,  8.49it/s]

 94%|████████████████████████████████  | 40133/42525 [1:16:29<04:45,  8.39it/s]

 94%|████████████████████████████████  | 40135/42525 [1:16:30<05:00,  7.96it/s]

 94%|████████████████████████████████  | 40137/42525 [1:16:30<05:05,  7.81it/s]

 94%|████████████████████████████████  | 40139/42525 [1:16:30<04:37,  8.60it/s]

 94%|████████████████████████████████  | 40141/42525 [1:16:30<04:29,  8.86it/s]

 94%|████████████████████████████████  | 40144/42525 [1:16:31<04:58,  7.97it/s]

 94%|████████████████████████████████  | 40147/42525 [1:16:31<04:24,  8.98it/s]

 94%|████████████████████████████████  | 40150/42525 [1:16:31<04:07,  9.61it/s]

 94%|████████████████████████████████  | 40153/42525 [1:16:32<04:04,  9.72it/s]

 94%|████████████████████████████████  | 40157/42525 [1:16:32<03:56, 10.01it/s]

 94%|████████████████████████████████  | 40159/42525 [1:16:32<04:18,  9.15it/s]

 94%|████████████████████████████████  | 40161/42525 [1:16:32<04:11,  9.40it/s]

 94%|████████████████████████████████  | 40164/42525 [1:16:33<04:03,  9.70it/s]

 94%|████████████████████████████████  | 40166/42525 [1:16:33<04:43,  8.31it/s]

 94%|████████████████████████████████  | 40168/42525 [1:16:33<04:27,  8.81it/s]

 94%|████████████████████████████████  | 40171/42525 [1:16:34<04:14,  9.26it/s]

 94%|████████████████████████████████  | 40173/42525 [1:16:34<04:13,  9.27it/s]

 94%|████████████████████████████████  | 40176/42525 [1:16:34<04:17,  9.11it/s]

 94%|████████████████████████████████  | 40179/42525 [1:16:34<04:09,  9.41it/s]

 94%|████████████████████████████████▏ | 40182/42525 [1:16:35<04:08,  9.43it/s]

 94%|████████████████████████████████▏ | 40185/42525 [1:16:35<04:19,  9.02it/s]

 95%|████████████████████████████████▏ | 40187/42525 [1:16:35<04:11,  9.30it/s]

 95%|████████████████████████████████▏ | 40191/42525 [1:16:36<03:57,  9.85it/s]

 95%|████████████████████████████████▏ | 40194/42525 [1:16:36<04:08,  9.39it/s]

 95%|████████████████████████████████▏ | 40196/42525 [1:16:36<04:31,  8.58it/s]

 95%|████████████████████████████████▏ | 40198/42525 [1:16:36<04:43,  8.21it/s]

 95%|████████████████████████████████▏ | 40201/42525 [1:16:37<04:16,  9.05it/s]

 95%|████████████████████████████████▏ | 40202/42525 [1:16:37<04:17,  9.01it/s]

 95%|████████████████████████████████▏ | 40205/42525 [1:16:37<04:25,  8.73it/s]

 95%|████████████████████████████████▏ | 40206/42525 [1:16:37<04:20,  8.90it/s]

 95%|████████████████████████████████▏ | 40210/42525 [1:16:38<04:07,  9.34it/s]

 95%|████████████████████████████████▏ | 40214/42525 [1:16:38<03:51,  9.98it/s]

 95%|████████████████████████████████▏ | 40218/42525 [1:16:39<03:44, 10.28it/s]

 95%|████████████████████████████████▏ | 40222/42525 [1:16:39<03:56,  9.75it/s]

 95%|████████████████████████████████▏ | 40225/42525 [1:16:39<03:54,  9.80it/s]

 95%|████████████████████████████████▏ | 40228/42525 [1:16:40<04:01,  9.50it/s]

 95%|████████████████████████████████▏ | 40231/42525 [1:16:40<04:21,  8.79it/s]

 95%|████████████████████████████████▏ | 40234/42525 [1:16:40<04:08,  9.21it/s]

 95%|████████████████████████████████▏ | 40236/42525 [1:16:41<03:59,  9.54it/s]

 95%|████████████████████████████████▏ | 40238/42525 [1:16:41<03:57,  9.63it/s]

 95%|████████████████████████████████▏ | 40240/42525 [1:16:41<03:58,  9.59it/s]

 95%|████████████████████████████████▏ | 40243/42525 [1:16:41<03:58,  9.57it/s]

 95%|████████████████████████████████▏ | 40245/42525 [1:16:41<04:07,  9.20it/s]

 95%|████████████████████████████████▏ | 40247/42525 [1:16:42<04:06,  9.25it/s]

 95%|████████████████████████████████▏ | 40249/42525 [1:16:42<04:03,  9.34it/s]

 95%|████████████████████████████████▏ | 40250/42525 [1:16:42<04:30,  8.41it/s]

 95%|████████████████████████████████▏ | 40254/42525 [1:16:42<04:11,  9.02it/s]

 95%|████████████████████████████████▏ | 40258/42525 [1:16:43<03:55,  9.63it/s]

 95%|████████████████████████████████▏ | 40261/42525 [1:16:43<03:50,  9.82it/s]

 95%|████████████████████████████████▏ | 40264/42525 [1:16:44<04:12,  8.95it/s]

 95%|████████████████████████████████▏ | 40266/42525 [1:16:44<04:19,  8.71it/s]

 95%|████████████████████████████████▏ | 40268/42525 [1:16:44<04:12,  8.95it/s]

 95%|████████████████████████████████▏ | 40270/42525 [1:16:44<04:18,  8.74it/s]

 95%|████████████████████████████████▏ | 40272/42525 [1:16:44<04:27,  8.42it/s]

 95%|████████████████████████████████▏ | 40274/42525 [1:16:45<04:41,  7.99it/s]

 95%|████████████████████████████████▏ | 40276/42525 [1:16:45<04:17,  8.75it/s]

 95%|████████████████████████████████▏ | 40278/42525 [1:16:45<04:11,  8.92it/s]

 95%|████████████████████████████████▏ | 40280/42525 [1:16:45<04:21,  8.60it/s]

 95%|████████████████████████████████▏ | 40283/42525 [1:16:46<04:01,  9.30it/s]

 95%|████████████████████████████████▏ | 40285/42525 [1:16:46<04:48,  7.77it/s]

 95%|████████████████████████████████▏ | 40287/42525 [1:16:46<05:11,  7.18it/s]

 95%|████████████████████████████████▏ | 40289/42525 [1:16:47<05:09,  7.23it/s]

 95%|████████████████████████████████▏ | 40291/42525 [1:16:47<04:41,  7.95it/s]

 95%|████████████████████████████████▏ | 40293/42525 [1:16:47<04:37,  8.05it/s]

 95%|████████████████████████████████▏ | 40296/42525 [1:16:47<04:11,  8.85it/s]

 95%|████████████████████████████████▏ | 40298/42525 [1:16:48<04:17,  8.64it/s]

 95%|████████████████████████████████▏ | 40300/42525 [1:16:48<04:06,  9.02it/s]

 95%|████████████████████████████████▏ | 40303/42525 [1:16:48<04:00,  9.22it/s]

 95%|████████████████████████████████▏ | 40304/42525 [1:16:48<04:23,  8.44it/s]

 95%|████████████████████████████████▏ | 40307/42525 [1:16:49<04:20,  8.50it/s]

 95%|████████████████████████████████▏ | 40310/42525 [1:16:49<04:12,  8.76it/s]

 95%|████████████████████████████████▏ | 40312/42525 [1:16:49<04:12,  8.76it/s]

 95%|████████████████████████████████▏ | 40314/42525 [1:16:49<03:58,  9.26it/s]

 95%|████████████████████████████████▏ | 40316/42525 [1:16:50<04:14,  8.66it/s]

 95%|████████████████████████████████▏ | 40317/42525 [1:16:50<04:35,  8.01it/s]

 95%|████████████████████████████████▏ | 40320/42525 [1:16:50<04:21,  8.44it/s]

 95%|████████████████████████████████▏ | 40322/42525 [1:16:50<04:24,  8.32it/s]

 95%|████████████████████████████████▏ | 40325/42525 [1:16:51<04:07,  8.90it/s]

 95%|████████████████████████████████▏ | 40327/42525 [1:16:51<04:03,  9.02it/s]

 95%|████████████████████████████████▏ | 40329/42525 [1:16:51<04:44,  7.72it/s]

 95%|████████████████████████████████▏ | 40331/42525 [1:16:51<04:40,  7.82it/s]

 95%|████████████████████████████████▏ | 40333/42525 [1:16:52<04:26,  8.21it/s]

 95%|████████████████████████████████▏ | 40335/42525 [1:16:52<04:11,  8.72it/s]

 95%|████████████████████████████████▎ | 40337/42525 [1:16:52<03:55,  9.29it/s]

 95%|████████████████████████████████▎ | 40339/42525 [1:16:52<03:53,  9.37it/s]

 95%|████████████████████████████████▎ | 40341/42525 [1:16:53<03:58,  9.17it/s]

 95%|████████████████████████████████▎ | 40343/42525 [1:16:53<04:34,  7.95it/s]

 95%|████████████████████████████████▎ | 40346/42525 [1:16:53<03:59,  9.08it/s]

 95%|████████████████████████████████▎ | 40348/42525 [1:16:53<03:59,  9.08it/s]

 95%|████████████████████████████████▎ | 40349/42525 [1:16:53<03:54,  9.28it/s]

 95%|████████████████████████████████▎ | 40352/42525 [1:16:54<04:03,  8.93it/s]

 95%|████████████████████████████████▎ | 40354/42525 [1:16:54<04:29,  8.07it/s]

 95%|████████████████████████████████▎ | 40357/42525 [1:16:54<04:00,  9.00it/s]

 95%|████████████████████████████████▎ | 40359/42525 [1:16:55<04:19,  8.33it/s]

 95%|████████████████████████████████▎ | 40361/42525 [1:16:55<04:14,  8.50it/s]

 95%|████████████████████████████████▎ | 40363/42525 [1:16:55<04:25,  8.15it/s]

 95%|████████████████████████████████▎ | 40365/42525 [1:16:55<04:13,  8.51it/s]

 95%|████████████████████████████████▎ | 40368/42525 [1:16:56<04:22,  8.23it/s]

 95%|████████████████████████████████▎ | 40369/42525 [1:16:56<04:23,  8.20it/s]

 95%|████████████████████████████████▎ | 40372/42525 [1:16:56<04:18,  8.34it/s]

 95%|████████████████████████████████▎ | 40374/42525 [1:16:56<04:03,  8.83it/s]

 95%|████████████████████████████████▎ | 40377/42525 [1:16:57<03:43,  9.60it/s]

 95%|████████████████████████████████▎ | 40379/42525 [1:16:57<03:53,  9.20it/s]

 95%|████████████████████████████████▎ | 40381/42525 [1:16:57<03:53,  9.19it/s]

 95%|████████████████████████████████▎ | 40383/42525 [1:16:57<04:24,  8.10it/s]

 95%|████████████████████████████████▎ | 40385/42525 [1:16:58<04:25,  8.06it/s]

 95%|████████████████████████████████▎ | 40388/42525 [1:16:58<03:57,  8.98it/s]

 95%|████████████████████████████████▎ | 40390/42525 [1:16:58<04:17,  8.30it/s]

 95%|████████████████████████████████▎ | 40392/42525 [1:16:58<04:26,  8.00it/s]

 95%|████████████████████████████████▎ | 40394/42525 [1:16:59<04:04,  8.73it/s]

 95%|████████████████████████████████▎ | 40396/42525 [1:16:59<04:26,  7.99it/s]

 95%|████████████████████████████████▎ | 40398/42525 [1:16:59<04:11,  8.45it/s]

 95%|████████████████████████████████▎ | 40400/42525 [1:16:59<04:24,  8.02it/s]

 95%|████████████████████████████████▎ | 40403/42525 [1:17:00<03:51,  9.17it/s]

 95%|████████████████████████████████▎ | 40405/42525 [1:17:00<04:02,  8.74it/s]

 95%|████████████████████████████████▎ | 40407/42525 [1:17:00<03:57,  8.93it/s]

 95%|████████████████████████████████▎ | 40409/42525 [1:17:00<04:00,  8.80it/s]

 95%|████████████████████████████████▎ | 40412/42525 [1:17:01<03:52,  9.09it/s]

 95%|████████████████████████████████▎ | 40414/42525 [1:17:01<03:42,  9.47it/s]

 95%|████████████████████████████████▎ | 40417/42525 [1:17:01<03:42,  9.49it/s]

 95%|████████████████████████████████▎ | 40419/42525 [1:17:02<04:22,  8.02it/s]

 95%|████████████████████████████████▎ | 40421/42525 [1:17:02<04:06,  8.54it/s]

 95%|████████████████████████████████▎ | 40423/42525 [1:17:02<03:50,  9.11it/s]

 95%|████████████████████████████████▎ | 40425/42525 [1:17:02<03:55,  8.93it/s]

 95%|████████████████████████████████▎ | 40428/42525 [1:17:03<03:49,  9.16it/s]

 95%|████████████████████████████████▎ | 40430/42525 [1:17:03<03:42,  9.43it/s]

 95%|████████████████████████████████▎ | 40432/42525 [1:17:03<04:09,  8.38it/s]

 95%|████████████████████████████████▎ | 40434/42525 [1:17:03<03:53,  8.96it/s]

 95%|████████████████████████████████▎ | 40436/42525 [1:17:03<04:15,  8.17it/s]

 95%|████████████████████████████████▎ | 40438/42525 [1:17:04<04:03,  8.56it/s]

 95%|████████████████████████████████▎ | 40440/42525 [1:17:04<03:45,  9.23it/s]

 95%|████████████████████████████████▎ | 40443/42525 [1:17:04<03:53,  8.91it/s]

 95%|████████████████████████████████▎ | 40444/42525 [1:17:04<03:50,  9.01it/s]

 95%|████████████████████████████████▎ | 40447/42525 [1:17:05<04:04,  8.51it/s]

 95%|████████████████████████████████▎ | 40449/42525 [1:17:05<03:52,  8.92it/s]

 95%|████████████████████████████████▎ | 40452/42525 [1:17:05<03:39,  9.42it/s]

 95%|████████████████████████████████▎ | 40453/42525 [1:17:05<03:49,  9.04it/s]

 95%|████████████████████████████████▎ | 40457/42525 [1:17:06<03:35,  9.60it/s]

 95%|████████████████████████████████▎ | 40460/42525 [1:17:06<03:43,  9.25it/s]

 95%|████████████████████████████████▎ | 40462/42525 [1:17:06<04:03,  8.46it/s]

 95%|████████████████████████████████▎ | 40465/42525 [1:17:07<03:45,  9.14it/s]

 95%|████████████████████████████████▎ | 40467/42525 [1:17:07<03:56,  8.69it/s]

 95%|████████████████████████████████▎ | 40470/42525 [1:17:07<03:51,  8.86it/s]

 95%|████████████████████████████████▎ | 40472/42525 [1:17:08<04:23,  7.78it/s]

 95%|████████████████████████████████▎ | 40475/42525 [1:17:08<03:53,  8.77it/s]

 95%|████████████████████████████████▎ | 40478/42525 [1:17:08<03:39,  9.32it/s]

 95%|████████████████████████████████▎ | 40480/42525 [1:17:08<03:37,  9.38it/s]

 95%|████████████████████████████████▎ | 40483/42525 [1:17:09<03:33,  9.58it/s]

 95%|████████████████████████████████▎ | 40485/42525 [1:17:09<03:42,  9.16it/s]

 95%|████████████████████████████████▎ | 40487/42525 [1:17:09<03:55,  8.66it/s]

 95%|████████████████████████████████▎ | 40489/42525 [1:17:09<04:11,  8.11it/s]

 95%|████████████████████████████████▎ | 40492/42525 [1:17:10<03:42,  9.12it/s]

 95%|████████████████████████████████▍ | 40494/42525 [1:17:10<03:43,  9.09it/s]

 95%|████████████████████████████████▍ | 40496/42525 [1:17:10<03:36,  9.36it/s]

 95%|████████████████████████████████▍ | 40498/42525 [1:17:10<03:33,  9.49it/s]

 95%|████████████████████████████████▍ | 40501/42525 [1:17:11<03:29,  9.65it/s]

 95%|████████████████████████████████▍ | 40503/42525 [1:17:11<03:35,  9.39it/s]

 95%|████████████████████████████████▍ | 40505/42525 [1:17:11<03:31,  9.56it/s]

 95%|████████████████████████████████▍ | 40507/42525 [1:17:11<03:29,  9.64it/s]

 95%|████████████████████████████████▍ | 40509/42525 [1:17:12<03:41,  9.12it/s]

 95%|████████████████████████████████▍ | 40510/42525 [1:17:12<03:35,  9.34it/s]

 95%|████████████████████████████████▍ | 40513/42525 [1:17:12<03:54,  8.58it/s]

 95%|████████████████████████████████▍ | 40515/42525 [1:17:12<03:42,  9.05it/s]

 95%|████████████████████████████████▍ | 40517/42525 [1:17:12<03:41,  9.06it/s]

 95%|████████████████████████████████▍ | 40519/42525 [1:17:13<03:36,  9.27it/s]

 95%|████████████████████████████████▍ | 40520/42525 [1:17:13<03:34,  9.34it/s]

 95%|████████████████████████████████▍ | 40523/42525 [1:17:13<03:35,  9.27it/s]

 95%|████████████████████████████████▍ | 40525/42525 [1:17:13<04:00,  8.31it/s]

 95%|████████████████████████████████▍ | 40526/42525 [1:17:13<03:50,  8.69it/s]

 95%|████████████████████████████████▍ | 40529/42525 [1:17:14<03:34,  9.29it/s]

 95%|████████████████████████████████▍ | 40532/42525 [1:17:14<03:25,  9.71it/s]

 95%|████████████████████████████████▍ | 40534/42525 [1:17:14<03:25,  9.69it/s]

 95%|████████████████████████████████▍ | 40536/42525 [1:17:15<03:55,  8.44it/s]

 95%|████████████████████████████████▍ | 40538/42525 [1:17:15<03:57,  8.38it/s]

 95%|████████████████████████████████▍ | 40540/42525 [1:17:15<03:43,  8.87it/s]

 95%|████████████████████████████████▍ | 40542/42525 [1:17:15<04:00,  8.26it/s]

 95%|████████████████████████████████▍ | 40545/42525 [1:17:16<04:00,  8.24it/s]

 95%|████████████████████████████████▍ | 40548/42525 [1:17:16<03:51,  8.54it/s]

 95%|████████████████████████████████▍ | 40550/42525 [1:17:16<03:41,  8.91it/s]

 95%|████████████████████████████████▍ | 40552/42525 [1:17:16<03:36,  9.10it/s]

 95%|████████████████████████████████▍ | 40554/42525 [1:17:17<03:33,  9.23it/s]

 95%|████████████████████████████████▍ | 40556/42525 [1:17:17<03:57,  8.29it/s]

 95%|████████████████████████████████▍ | 40558/42525 [1:17:17<03:45,  8.71it/s]

 95%|████████████████████████████████▍ | 40560/42525 [1:17:17<04:00,  8.18it/s]

 95%|████████████████████████████████▍ | 40561/42525 [1:17:17<03:47,  8.64it/s]

 95%|████████████████████████████████▍ | 40563/42525 [1:17:18<03:36,  9.06it/s]

 95%|████████████████████████████████▍ | 40566/42525 [1:17:18<03:37,  9.00it/s]

 95%|████████████████████████████████▍ | 40568/42525 [1:17:18<04:11,  7.79it/s]

 95%|████████████████████████████████▍ | 40570/42525 [1:17:18<04:01,  8.08it/s]

 95%|████████████████████████████████▍ | 40572/42525 [1:17:19<04:19,  7.54it/s]

 95%|████████████████████████████████▍ | 40574/42525 [1:17:19<04:03,  8.00it/s]

 95%|████████████████████████████████▍ | 40576/42525 [1:17:19<04:18,  7.55it/s]

 95%|████████████████████████████████▍ | 40578/42525 [1:17:20<04:01,  8.06it/s]

 95%|████████████████████████████████▍ | 40580/42525 [1:17:20<03:43,  8.70it/s]

 95%|████████████████████████████████▍ | 40582/42525 [1:17:20<03:32,  9.15it/s]

 95%|████████████████████████████████▍ | 40584/42525 [1:17:20<03:33,  9.09it/s]

 95%|████████████████████████████████▍ | 40586/42525 [1:17:20<04:01,  8.04it/s]

 95%|████████████████████████████████▍ | 40588/42525 [1:17:21<04:16,  7.56it/s]

 95%|████████████████████████████████▍ | 40590/42525 [1:17:21<04:07,  7.81it/s]

 95%|████████████████████████████████▍ | 40592/42525 [1:17:21<04:08,  7.77it/s]

 95%|████████████████████████████████▍ | 40594/42525 [1:17:21<04:04,  7.90it/s]

 95%|████████████████████████████████▍ | 40597/42525 [1:17:22<03:54,  8.22it/s]

 95%|████████████████████████████████▍ | 40600/42525 [1:17:22<03:39,  8.77it/s]

 95%|████████████████████████████████▍ | 40602/42525 [1:17:22<03:56,  8.12it/s]

 95%|████████████████████████████████▍ | 40604/42525 [1:17:23<03:53,  8.23it/s]

 95%|████████████████████████████████▍ | 40606/42525 [1:17:23<03:42,  8.63it/s]

 95%|████████████████████████████████▍ | 40608/42525 [1:17:23<03:33,  8.99it/s]

 95%|████████████████████████████████▍ | 40611/42525 [1:17:23<03:23,  9.41it/s]

 96%|████████████████████████████████▍ | 40613/42525 [1:17:24<03:21,  9.50it/s]

 96%|████████████████████████████████▍ | 40615/42525 [1:17:24<03:21,  9.48it/s]

 96%|████████████████████████████████▍ | 40617/42525 [1:17:24<03:38,  8.75it/s]

 96%|████████████████████████████████▍ | 40619/42525 [1:17:24<03:33,  8.91it/s]

 96%|████████████████████████████████▍ | 40621/42525 [1:17:24<03:34,  8.87it/s]

 96%|████████████████████████████████▍ | 40623/42525 [1:17:25<03:54,  8.12it/s]

 96%|████████████████████████████████▍ | 40625/42525 [1:17:25<04:04,  7.77it/s]

 96%|████████████████████████████████▍ | 40627/42525 [1:17:25<03:41,  8.58it/s]

 96%|████████████████████████████████▍ | 40630/42525 [1:17:26<03:28,  9.10it/s]

 96%|████████████████████████████████▍ | 40632/42525 [1:17:26<03:26,  9.18it/s]

 96%|████████████████████████████████▍ | 40634/42525 [1:17:26<03:41,  8.53it/s]

 96%|████████████████████████████████▍ | 40636/42525 [1:17:26<03:27,  9.10it/s]

 96%|████████████████████████████████▍ | 40638/42525 [1:17:26<03:35,  8.76it/s]

 96%|████████████████████████████████▍ | 40640/42525 [1:17:27<03:28,  9.06it/s]

 96%|████████████████████████████████▍ | 40642/42525 [1:17:27<03:27,  9.08it/s]

 96%|████████████████████████████████▍ | 40644/42525 [1:17:27<04:06,  7.63it/s]

 96%|████████████████████████████████▍ | 40646/42525 [1:17:27<03:45,  8.32it/s]

 96%|████████████████████████████████▍ | 40648/42525 [1:17:28<03:46,  8.27it/s]

 96%|████████████████████████████████▌ | 40649/42525 [1:17:28<03:42,  8.42it/s]

 96%|████████████████████████████████▌ | 40652/42525 [1:17:28<03:33,  8.79it/s]

 96%|████████████████████████████████▌ | 40654/42525 [1:17:28<03:29,  8.93it/s]

 96%|████████████████████████████████▌ | 40656/42525 [1:17:29<03:27,  9.01it/s]

 96%|████████████████████████████████▌ | 40658/42525 [1:17:29<03:38,  8.53it/s]

 96%|████████████████████████████████▌ | 40660/42525 [1:17:29<03:31,  8.82it/s]

 96%|████████████████████████████████▌ | 40662/42525 [1:17:29<03:32,  8.75it/s]

 96%|████████████████████████████████▌ | 40664/42525 [1:17:29<03:33,  8.73it/s]

 96%|████████████████████████████████▌ | 40666/42525 [1:17:30<03:43,  8.31it/s]

 96%|████████████████████████████████▌ | 40668/42525 [1:17:30<03:40,  8.44it/s]

 96%|████████████████████████████████▌ | 40670/42525 [1:17:30<03:50,  8.04it/s]

 96%|████████████████████████████████▌ | 40672/42525 [1:17:30<04:03,  7.61it/s]

 96%|████████████████████████████████▌ | 40674/42525 [1:17:31<03:48,  8.09it/s]

 96%|████████████████████████████████▌ | 40676/42525 [1:17:31<03:33,  8.64it/s]

 96%|████████████████████████████████▌ | 40678/42525 [1:17:31<03:29,  8.83it/s]

 96%|████████████████████████████████▌ | 40680/42525 [1:17:31<03:29,  8.79it/s]

 96%|████████████████████████████████▌ | 40682/42525 [1:17:32<03:24,  9.01it/s]

 96%|████████████████████████████████▌ | 40684/42525 [1:17:32<03:46,  8.12it/s]

 96%|████████████████████████████████▌ | 40686/42525 [1:17:32<04:15,  7.21it/s]

 96%|████████████████████████████████▌ | 40688/42525 [1:17:32<03:44,  8.17it/s]

 96%|████████████████████████████████▌ | 40690/42525 [1:17:33<03:27,  8.86it/s]

 96%|████████████████████████████████▌ | 40692/42525 [1:17:33<03:39,  8.36it/s]

 96%|████████████████████████████████▌ | 40694/42525 [1:17:33<03:52,  7.88it/s]

 96%|████████████████████████████████▌ | 40696/42525 [1:17:33<03:35,  8.47it/s]

 96%|████████████████████████████████▌ | 40698/42525 [1:17:34<03:56,  7.73it/s]

 96%|████████████████████████████████▌ | 40700/42525 [1:17:34<03:34,  8.51it/s]

 96%|████████████████████████████████▌ | 40702/42525 [1:17:34<03:24,  8.93it/s]

 96%|████████████████████████████████▌ | 40704/42525 [1:17:34<03:45,  8.09it/s]

 96%|████████████████████████████████▌ | 40706/42525 [1:17:35<03:33,  8.52it/s]

 96%|████████████████████████████████▌ | 40709/42525 [1:17:35<03:24,  8.87it/s]

 96%|████████████████████████████████▌ | 40711/42525 [1:17:35<03:11,  9.46it/s]

 96%|████████████████████████████████▌ | 40714/42525 [1:17:35<03:22,  8.96it/s]

 96%|████████████████████████████████▌ | 40716/42525 [1:17:36<03:26,  8.75it/s]

 96%|████████████████████████████████▌ | 40718/42525 [1:17:36<03:26,  8.73it/s]

 96%|████████████████████████████████▌ | 40720/42525 [1:17:36<03:17,  9.16it/s]

 96%|████████████████████████████████▌ | 40722/42525 [1:17:36<03:13,  9.31it/s]

 96%|████████████████████████████████▌ | 40724/42525 [1:17:37<03:38,  8.25it/s]

 96%|████████████████████████████████▌ | 40726/42525 [1:17:37<03:25,  8.76it/s]

 96%|████████████████████████████████▌ | 40728/42525 [1:17:37<03:29,  8.59it/s]

 96%|████████████████████████████████▌ | 40729/42525 [1:17:37<03:24,  8.78it/s]

 96%|████████████████████████████████▌ | 40732/42525 [1:17:38<03:48,  7.86it/s]

 96%|████████████████████████████████▌ | 40734/42525 [1:17:38<03:35,  8.31it/s]

 96%|████████████████████████████████▌ | 40736/42525 [1:17:38<03:28,  8.56it/s]

 96%|████████████████████████████████▌ | 40737/42525 [1:17:38<03:26,  8.66it/s]

 96%|████████████████████████████████▌ | 40740/42525 [1:17:38<03:34,  8.34it/s]

 96%|████████████████████████████████▌ | 40742/42525 [1:17:39<03:55,  7.58it/s]

 96%|████████████████████████████████▌ | 40744/42525 [1:17:39<03:34,  8.32it/s]

 96%|████████████████████████████████▌ | 40746/42525 [1:17:39<03:35,  8.27it/s]

 96%|████████████████████████████████▌ | 40748/42525 [1:17:39<03:26,  8.62it/s]

 96%|████████████████████████████████▌ | 40750/42525 [1:17:40<03:26,  8.61it/s]

 96%|████████████████████████████████▌ | 40752/42525 [1:17:40<03:15,  9.05it/s]

 96%|████████████████████████████████▌ | 40754/42525 [1:17:40<03:11,  9.25it/s]

 96%|████████████████████████████████▌ | 40756/42525 [1:17:40<03:26,  8.58it/s]

 96%|████████████████████████████████▌ | 40758/42525 [1:17:41<03:21,  8.79it/s]

 96%|████████████████████████████████▌ | 40760/42525 [1:17:41<03:18,  8.90it/s]

 96%|████████████████████████████████▌ | 40762/42525 [1:17:41<03:24,  8.60it/s]

 96%|████████████████████████████████▌ | 40764/42525 [1:17:41<03:40,  8.00it/s]

 96%|████████████████████████████████▌ | 40766/42525 [1:17:42<03:54,  7.49it/s]

 96%|████████████████████████████████▌ | 40769/42525 [1:17:42<03:46,  7.77it/s]

 96%|████████████████████████████████▌ | 40771/42525 [1:17:42<03:26,  8.47it/s]

 96%|████████████████████████████████▌ | 40773/42525 [1:17:42<03:15,  8.95it/s]

 96%|████████████████████████████████▌ | 40775/42525 [1:17:43<03:43,  7.82it/s]

 96%|████████████████████████████████▌ | 40777/42525 [1:17:43<03:47,  7.70it/s]

 96%|████████████████████████████████▌ | 40779/42525 [1:17:43<03:26,  8.44it/s]

 96%|████████████████████████████████▌ | 40781/42525 [1:17:43<03:11,  9.12it/s]

 96%|████████████████████████████████▌ | 40783/42525 [1:17:44<03:11,  9.08it/s]

 96%|████████████████████████████████▌ | 40786/42525 [1:17:44<03:04,  9.42it/s]

 96%|████████████████████████████████▌ | 40788/42525 [1:17:44<03:11,  9.06it/s]

 96%|████████████████████████████████▌ | 40790/42525 [1:17:44<03:23,  8.53it/s]

 96%|████████████████████████████████▌ | 40792/42525 [1:17:45<03:12,  9.01it/s]

 96%|████████████████████████████████▌ | 40794/42525 [1:17:45<03:10,  9.08it/s]

 96%|████████████████████████████████▌ | 40796/42525 [1:17:45<03:08,  9.18it/s]

 96%|████████████████████████████████▌ | 40798/42525 [1:17:45<03:20,  8.62it/s]

 96%|████████████████████████████████▌ | 40800/42525 [1:17:45<03:31,  8.16it/s]

 96%|████████████████████████████████▌ | 40802/42525 [1:17:46<03:14,  8.86it/s]

 96%|████████████████████████████████▌ | 40804/42525 [1:17:46<03:23,  8.44it/s]

 96%|████████████████████████████████▋ | 40806/42525 [1:17:46<03:16,  8.74it/s]

 96%|████████████████████████████████▋ | 40808/42525 [1:17:46<03:22,  8.47it/s]

 96%|████████████████████████████████▋ | 40810/42525 [1:17:47<03:31,  8.10it/s]

 96%|████████████████████████████████▋ | 40813/42525 [1:17:47<03:18,  8.63it/s]

 96%|████████████████████████████████▋ | 40815/42525 [1:17:47<03:10,  9.00it/s]

 96%|████████████████████████████████▋ | 40817/42525 [1:17:47<03:25,  8.30it/s]

 96%|████████████████████████████████▋ | 40820/42525 [1:17:48<03:02,  9.33it/s]

 96%|████████████████████████████████▋ | 40822/42525 [1:17:48<02:58,  9.55it/s]

 96%|████████████████████████████████▋ | 40825/42525 [1:17:48<02:54,  9.76it/s]

 96%|████████████████████████████████▋ | 40827/42525 [1:17:49<03:24,  8.32it/s]

 96%|████████████████████████████████▋ | 40829/42525 [1:17:49<03:34,  7.89it/s]

 96%|████████████████████████████████▋ | 40831/42525 [1:17:49<03:16,  8.62it/s]

 96%|████████████████████████████████▋ | 40833/42525 [1:17:49<03:22,  8.34it/s]

 96%|████████████████████████████████▋ | 40834/42525 [1:17:49<03:22,  8.36it/s]

 96%|████████████████████████████████▋ | 40838/42525 [1:17:50<02:57,  9.52it/s]

 96%|████████████████████████████████▋ | 40841/42525 [1:17:50<02:59,  9.40it/s]

 96%|████████████████████████████████▋ | 40842/42525 [1:17:50<03:06,  9.02it/s]

 96%|████████████████████████████████▋ | 40845/42525 [1:17:51<02:59,  9.36it/s]

 96%|████████████████████████████████▋ | 40848/42525 [1:17:51<03:00,  9.29it/s]

 96%|████████████████████████████████▋ | 40850/42525 [1:17:51<02:58,  9.41it/s]

 96%|████████████████████████████████▋ | 40852/42525 [1:17:51<02:55,  9.54it/s]

 96%|████████████████████████████████▋ | 40855/42525 [1:17:52<02:52,  9.67it/s]

 96%|████████████████████████████████▋ | 40857/42525 [1:17:52<03:13,  8.61it/s]

 96%|████████████████████████████████▋ | 40859/42525 [1:17:52<03:12,  8.67it/s]

 96%|████████████████████████████████▋ | 40861/42525 [1:17:52<03:03,  9.08it/s]

 96%|████████████████████████████████▋ | 40863/42525 [1:17:53<03:22,  8.22it/s]

 96%|████████████████████████████████▋ | 40865/42525 [1:17:53<03:35,  7.70it/s]

 96%|████████████████████████████████▋ | 40866/42525 [1:17:53<03:46,  7.34it/s]

 96%|████████████████████████████████▋ | 40869/42525 [1:17:53<03:33,  7.75it/s]

 96%|████████████████████████████████▋ | 40871/42525 [1:17:54<03:16,  8.40it/s]

 96%|████████████████████████████████▋ | 40874/42525 [1:17:54<03:00,  9.12it/s]

 96%|████████████████████████████████▋ | 40876/42525 [1:17:54<03:01,  9.10it/s]

 96%|████████████████████████████████▋ | 40877/42525 [1:17:54<03:04,  8.94it/s]

 96%|████████████████████████████████▋ | 40880/42525 [1:17:55<02:58,  9.20it/s]

 96%|████████████████████████████████▋ | 40882/42525 [1:17:55<03:15,  8.43it/s]

 96%|████████████████████████████████▋ | 40884/42525 [1:17:55<03:14,  8.43it/s]

 96%|████████████████████████████████▋ | 40886/42525 [1:17:55<03:05,  8.85it/s]

 96%|████████████████████████████████▋ | 40888/42525 [1:17:55<03:05,  8.82it/s]

 96%|████████████████████████████████▋ | 40890/42525 [1:17:56<03:11,  8.56it/s]

 96%|████████████████████████████████▋ | 40892/42525 [1:17:56<03:26,  7.92it/s]

 96%|████████████████████████████████▋ | 40894/42525 [1:17:56<03:14,  8.40it/s]

 96%|████████████████████████████████▋ | 40896/42525 [1:17:56<03:03,  8.89it/s]

 96%|████████████████████████████████▋ | 40898/42525 [1:17:57<03:11,  8.51it/s]

 96%|████████████████████████████████▋ | 40900/42525 [1:17:57<03:22,  8.01it/s]

 96%|████████████████████████████████▋ | 40902/42525 [1:17:57<03:12,  8.45it/s]

 96%|████████████████████████████████▋ | 40904/42525 [1:17:57<02:59,  9.06it/s]

 96%|████████████████████████████████▋ | 40906/42525 [1:17:58<02:53,  9.31it/s]

 96%|████████████████████████████████▋ | 40908/42525 [1:17:58<03:16,  8.22it/s]

 96%|████████████████████████████████▋ | 40910/42525 [1:17:58<03:23,  7.94it/s]

 96%|████████████████████████████████▋ | 40912/42525 [1:17:58<03:10,  8.45it/s]

 96%|████████████████████████████████▋ | 40914/42525 [1:17:59<03:39,  7.35it/s]

 96%|████████████████████████████████▋ | 40916/42525 [1:17:59<03:18,  8.10it/s]

 96%|████████████████████████████████▋ | 40919/42525 [1:17:59<02:57,  9.07it/s]

 96%|████████████████████████████████▋ | 40921/42525 [1:17:59<02:57,  9.03it/s]

 96%|████████████████████████████████▋ | 40923/42525 [1:18:00<02:57,  9.02it/s]

 96%|████████████████████████████████▋ | 40925/42525 [1:18:00<03:09,  8.44it/s]

 96%|████████████████████████████████▋ | 40927/42525 [1:18:00<03:17,  8.09it/s]

 96%|████████████████████████████████▋ | 40929/42525 [1:18:00<03:10,  8.38it/s]

 96%|████████████████████████████████▋ | 40931/42525 [1:18:01<02:58,  8.92it/s]

 96%|████████████████████████████████▋ | 40933/42525 [1:18:01<03:15,  8.12it/s]

 96%|████████████████████████████████▋ | 40935/42525 [1:18:01<03:05,  8.58it/s]

 96%|████████████████████████████████▋ | 40937/42525 [1:18:01<03:00,  8.79it/s]

 96%|████████████████████████████████▋ | 40939/42525 [1:18:01<02:58,  8.87it/s]

 96%|████████████████████████████████▋ | 40941/42525 [1:18:02<02:58,  8.89it/s]

 96%|████████████████████████████████▋ | 40943/42525 [1:18:02<02:54,  9.09it/s]

 96%|████████████████████████████████▋ | 40945/42525 [1:18:02<02:46,  9.51it/s]

 96%|████████████████████████████████▋ | 40948/42525 [1:18:02<02:47,  9.40it/s]

 96%|████████████████████████████████▋ | 40950/42525 [1:18:03<03:06,  8.44it/s]

 96%|████████████████████████████████▋ | 40953/42525 [1:18:03<02:50,  9.21it/s]

 96%|████████████████████████████████▋ | 40956/42525 [1:18:03<02:45,  9.46it/s]

 96%|████████████████████████████████▋ | 40958/42525 [1:18:04<02:50,  9.18it/s]

 96%|████████████████████████████████▋ | 40960/42525 [1:18:04<02:52,  9.06it/s]

 96%|████████████████████████████████▊ | 40962/42525 [1:18:04<03:12,  8.11it/s]

 96%|████████████████████████████████▊ | 40964/42525 [1:18:04<02:59,  8.69it/s]

 96%|████████████████████████████████▊ | 40966/42525 [1:18:04<02:59,  8.69it/s]

 96%|████████████████████████████████▊ | 40968/42525 [1:18:05<03:11,  8.14it/s]

 96%|████████████████████████████████▊ | 40971/42525 [1:18:05<02:54,  8.89it/s]

 96%|████████████████████████████████▊ | 40973/42525 [1:18:05<02:49,  9.15it/s]

 96%|████████████████████████████████▊ | 40975/42525 [1:18:05<02:51,  9.06it/s]

 96%|████████████████████████████████▊ | 40977/42525 [1:18:06<03:06,  8.31it/s]

 96%|████████████████████████████████▊ | 40979/42525 [1:18:06<03:12,  8.03it/s]

 96%|████████████████████████████████▊ | 40983/42525 [1:18:06<02:48,  9.18it/s]

 96%|████████████████████████████████▊ | 40985/42525 [1:18:07<02:46,  9.24it/s]

 96%|████████████████████████████████▊ | 40987/42525 [1:18:07<03:06,  8.26it/s]

 96%|████████████████████████████████▊ | 40989/42525 [1:18:07<03:08,  8.17it/s]

 96%|████████████████████████████████▊ | 40991/42525 [1:18:07<03:06,  8.22it/s]

 96%|████████████████████████████████▊ | 40992/42525 [1:18:07<03:05,  8.27it/s]

 96%|████████████████████████████████▊ | 40995/42525 [1:18:08<03:12,  7.97it/s]

 96%|████████████████████████████████▊ | 40997/42525 [1:18:08<03:28,  7.33it/s]

 96%|████████████████████████████████▊ | 40999/42525 [1:18:08<03:04,  8.28it/s]

 96%|████████████████████████████████▊ | 41001/42525 [1:18:09<02:58,  8.55it/s]

 96%|████████████████████████████████▊ | 41003/42525 [1:18:09<02:55,  8.68it/s]

 96%|████████████████████████████████▊ | 41005/42525 [1:18:09<02:49,  8.95it/s]

 96%|████████████████████████████████▊ | 41007/42525 [1:18:09<03:09,  8.02it/s]

 96%|████████████████████████████████▊ | 41009/42525 [1:18:10<02:55,  8.66it/s]

 96%|████████████████████████████████▊ | 41011/42525 [1:18:10<02:49,  8.96it/s]

 96%|████████████████████████████████▊ | 41013/42525 [1:18:10<03:14,  7.79it/s]

 96%|████████████████████████████████▊ | 41015/42525 [1:18:10<03:30,  7.17it/s]

 96%|████████████████████████████████▊ | 41018/42525 [1:18:11<02:54,  8.63it/s]

 96%|████████████████████████████████▊ | 41021/42525 [1:18:11<02:49,  8.85it/s]

 96%|████████████████████████████████▊ | 41023/42525 [1:18:11<02:48,  8.94it/s]

 96%|████████████████████████████████▊ | 41025/42525 [1:18:11<02:42,  9.22it/s]

 96%|████████████████████████████████▊ | 41027/42525 [1:18:12<02:58,  8.40it/s]

 96%|████████████████████████████████▊ | 41029/42525 [1:18:12<02:49,  8.83it/s]

 96%|████████████████████████████████▊ | 41032/42525 [1:18:12<02:58,  8.34it/s]

 96%|████████████████████████████████▊ | 41034/42525 [1:18:12<02:47,  8.88it/s]

 96%|████████████████████████████████▊ | 41035/42525 [1:18:13<02:44,  9.07it/s]

 97%|████████████████████████████████▊ | 41038/42525 [1:18:13<02:51,  8.65it/s]

 97%|████████████████████████████████▊ | 41040/42525 [1:18:13<03:00,  8.24it/s]

 97%|████████████████████████████████▊ | 41042/42525 [1:18:13<03:20,  7.41it/s]

 97%|████████████████████████████████▊ | 41044/42525 [1:18:14<03:23,  7.26it/s]

 97%|████████████████████████████████▊ | 41046/42525 [1:18:14<03:11,  7.73it/s]

 97%|████████████████████████████████▊ | 41047/42525 [1:18:14<03:21,  7.35it/s]

 97%|████████████████████████████████▊ | 41050/42525 [1:18:14<02:50,  8.65it/s]

 97%|████████████████████████████████▊ | 41052/42525 [1:18:15<03:01,  8.10it/s]

 97%|████████████████████████████████▊ | 41054/42525 [1:18:15<02:52,  8.52it/s]

 97%|████████████████████████████████▊ | 41056/42525 [1:18:15<02:45,  8.90it/s]

 97%|████████████████████████████████▊ | 41058/42525 [1:18:15<03:06,  7.85it/s]

 97%|████████████████████████████████▊ | 41060/42525 [1:18:16<02:54,  8.39it/s]

 97%|████████████████████████████████▊ | 41062/42525 [1:18:16<02:41,  9.04it/s]

 97%|████████████████████████████████▊ | 41066/42525 [1:18:16<02:34,  9.43it/s]

 97%|████████████████████████████████▊ | 41068/42525 [1:18:16<02:34,  9.40it/s]

 97%|████████████████████████████████▊ | 41070/42525 [1:18:17<02:44,  8.82it/s]

 97%|████████████████████████████████▊ | 41072/42525 [1:18:17<02:38,  9.17it/s]

 97%|████████████████████████████████▊ | 41074/42525 [1:18:17<02:51,  8.47it/s]

 97%|████████████████████████████████▊ | 41077/42525 [1:18:18<02:37,  9.18it/s]

 97%|████████████████████████████████▊ | 41079/42525 [1:18:18<02:40,  8.99it/s]

 97%|████████████████████████████████▊ | 41082/42525 [1:18:18<02:33,  9.38it/s]

 97%|████████████████████████████████▊ | 41085/42525 [1:18:18<02:30,  9.56it/s]

 97%|████████████████████████████████▊ | 41087/42525 [1:18:19<02:47,  8.58it/s]

 97%|████████████████████████████████▊ | 41090/42525 [1:18:19<02:36,  9.19it/s]

 97%|████████████████████████████████▊ | 41093/42525 [1:18:19<02:29,  9.60it/s]

 97%|████████████████████████████████▊ | 41094/42525 [1:18:19<02:31,  9.47it/s]

 97%|████████████████████████████████▊ | 41097/42525 [1:18:20<02:37,  9.09it/s]

 97%|████████████████████████████████▊ | 41101/42525 [1:18:20<02:27,  9.67it/s]

 97%|████████████████████████████████▊ | 41103/42525 [1:18:20<02:26,  9.68it/s]

 97%|████████████████████████████████▊ | 41105/42525 [1:18:21<02:44,  8.64it/s]

 97%|████████████████████████████████▊ | 41107/42525 [1:18:21<02:45,  8.58it/s]

 97%|████████████████████████████████▊ | 41111/42525 [1:18:21<02:28,  9.53it/s]

 97%|████████████████████████████████▊ | 41114/42525 [1:18:22<02:32,  9.25it/s]

 97%|████████████████████████████████▊ | 41115/42525 [1:18:22<02:44,  8.56it/s]

 97%|████████████████████████████████▉ | 41118/42525 [1:18:22<02:47,  8.42it/s]

 97%|████████████████████████████████▉ | 41121/42525 [1:18:22<02:32,  9.20it/s]

 97%|████████████████████████████████▉ | 41123/42525 [1:18:23<02:46,  8.42it/s]

 97%|████████████████████████████████▉ | 41125/42525 [1:18:23<02:52,  8.12it/s]

 97%|████████████████████████████████▉ | 41127/42525 [1:18:23<02:38,  8.80it/s]

 97%|████████████████████████████████▉ | 41129/42525 [1:18:23<03:02,  7.65it/s]

 97%|████████████████████████████████▉ | 41131/42525 [1:18:24<03:02,  7.63it/s]

 97%|████████████████████████████████▉ | 41132/42525 [1:18:24<03:02,  7.63it/s]

 97%|████████████████████████████████▉ | 41135/42525 [1:18:24<03:04,  7.54it/s]

 97%|████████████████████████████████▉ | 41136/42525 [1:18:24<02:53,  7.99it/s]

 97%|████████████████████████████████▉ | 41139/42525 [1:18:25<02:38,  8.73it/s]

 97%|████████████████████████████████▉ | 41142/42525 [1:18:25<02:29,  9.23it/s]

 97%|████████████████████████████████▉ | 41145/42525 [1:18:25<02:24,  9.56it/s]

 97%|████████████████████████████████▉ | 41148/42525 [1:18:26<02:30,  9.18it/s]

 97%|████████████████████████████████▉ | 41150/42525 [1:18:26<02:27,  9.34it/s]

 97%|████████████████████████████████▉ | 41152/42525 [1:18:26<02:43,  8.40it/s]

 97%|████████████████████████████████▉ | 41154/42525 [1:18:26<02:47,  8.20it/s]

 97%|████████████████████████████████▉ | 41156/42525 [1:18:27<02:40,  8.55it/s]

 97%|████████████████████████████████▉ | 41158/42525 [1:18:27<02:32,  8.98it/s]

 97%|████████████████████████████████▉ | 41160/42525 [1:18:27<02:28,  9.20it/s]

 97%|████████████████████████████████▉ | 41162/42525 [1:18:27<02:57,  7.68it/s]

 97%|████████████████████████████████▉ | 41164/42525 [1:18:28<03:08,  7.21it/s]

 97%|████████████████████████████████▉ | 41166/42525 [1:18:28<03:07,  7.23it/s]

 97%|████████████████████████████████▉ | 41168/42525 [1:18:28<03:03,  7.39it/s]

 97%|████████████████████████████████▉ | 41171/42525 [1:18:28<02:44,  8.24it/s]

 97%|████████████████████████████████▉ | 41173/42525 [1:18:29<02:49,  7.96it/s]

 97%|████████████████████████████████▉ | 41175/42525 [1:18:29<02:44,  8.22it/s]

 97%|████████████████████████████████▉ | 41177/42525 [1:18:29<02:43,  8.23it/s]

 97%|████████████████████████████████▉ | 41179/42525 [1:18:29<02:49,  7.93it/s]

 97%|████████████████████████████████▉ | 41181/42525 [1:18:30<02:51,  7.86it/s]

 97%|████████████████████████████████▉ | 41183/42525 [1:18:30<02:36,  8.56it/s]

 97%|████████████████████████████████▉ | 41186/42525 [1:18:30<02:25,  9.21it/s]

 97%|████████████████████████████████▉ | 41188/42525 [1:18:30<02:35,  8.59it/s]

 97%|████████████████████████████████▉ | 41190/42525 [1:18:31<02:46,  8.01it/s]

 97%|████████████████████████████████▉ | 41192/42525 [1:18:31<02:34,  8.60it/s]

 97%|████████████████████████████████▉ | 41194/42525 [1:18:31<02:34,  8.64it/s]

 97%|████████████████████████████████▉ | 41196/42525 [1:18:31<02:49,  7.85it/s]

 97%|████████████████████████████████▉ | 41198/42525 [1:18:32<02:40,  8.25it/s]

 97%|████████████████████████████████▉ | 41200/42525 [1:18:32<02:49,  7.81it/s]

 97%|████████████████████████████████▉ | 41202/42525 [1:18:32<02:48,  7.85it/s]

 97%|████████████████████████████████▉ | 41204/42525 [1:18:32<02:39,  8.26it/s]

 97%|████████████████████████████████▉ | 41206/42525 [1:18:33<02:42,  8.13it/s]

 97%|████████████████████████████████▉ | 41208/42525 [1:18:33<03:04,  7.14it/s]

 97%|████████████████████████████████▉ | 41210/42525 [1:18:33<02:55,  7.49it/s]

 97%|████████████████████████████████▉ | 41212/42525 [1:18:33<02:37,  8.36it/s]

 97%|████████████████████████████████▉ | 41214/42525 [1:18:34<02:47,  7.85it/s]

 97%|████████████████████████████████▉ | 41215/42525 [1:18:34<02:37,  8.31it/s]

 97%|████████████████████████████████▉ | 41217/42525 [1:18:34<02:29,  8.73it/s]

 97%|████████████████████████████████▉ | 41220/42525 [1:18:34<02:25,  8.99it/s]

 97%|████████████████████████████████▉ | 41222/42525 [1:18:35<02:32,  8.52it/s]

 97%|████████████████████████████████▉ | 41224/42525 [1:18:35<02:27,  8.83it/s]

 97%|████████████████████████████████▉ | 41226/42525 [1:18:35<02:42,  7.98it/s]

 97%|████████████████████████████████▉ | 41228/42525 [1:18:35<02:36,  8.31it/s]

 97%|████████████████████████████████▉ | 41230/42525 [1:18:36<02:41,  8.00it/s]

 97%|████████████████████████████████▉ | 41232/42525 [1:18:36<02:32,  8.46it/s]

 97%|████████████████████████████████▉ | 41234/42525 [1:18:36<02:38,  8.13it/s]

 97%|████████████████████████████████▉ | 41236/42525 [1:18:36<02:44,  7.84it/s]

 97%|████████████████████████████████▉ | 41238/42525 [1:18:37<02:41,  7.95it/s]

 97%|████████████████████████████████▉ | 41241/42525 [1:18:37<02:18,  9.26it/s]

 97%|████████████████████████████████▉ | 41242/42525 [1:18:37<02:16,  9.37it/s]

 97%|████████████████████████████████▉ | 41245/42525 [1:18:37<02:30,  8.51it/s]

 97%|████████████████████████████████▉ | 41248/42525 [1:18:38<02:32,  8.35it/s]

 97%|████████████████████████████████▉ | 41249/42525 [1:18:38<02:26,  8.68it/s]

 97%|████████████████████████████████▉ | 41252/42525 [1:18:38<02:16,  9.30it/s]

 97%|████████████████████████████████▉ | 41254/42525 [1:18:38<02:14,  9.44it/s]

 97%|████████████████████████████████▉ | 41256/42525 [1:18:39<02:26,  8.68it/s]

 97%|████████████████████████████████▉ | 41258/42525 [1:18:39<02:17,  9.25it/s]

 97%|████████████████████████████████▉ | 41260/42525 [1:18:39<02:36,  8.10it/s]

 97%|████████████████████████████████▉ | 41262/42525 [1:18:39<02:36,  8.08it/s]

 97%|████████████████████████████████▉ | 41263/42525 [1:18:39<02:34,  8.15it/s]

 97%|████████████████████████████████▉ | 41265/42525 [1:18:40<02:34,  8.15it/s]

 97%|████████████████████████████████▉ | 41269/42525 [1:18:40<02:14,  9.31it/s]

 97%|████████████████████████████████▉ | 41272/42525 [1:18:40<02:18,  9.05it/s]

 97%|████████████████████████████████▉ | 41274/42525 [1:18:41<02:37,  7.95it/s]

 97%|█████████████████████████████████ | 41277/42525 [1:18:41<02:19,  8.95it/s]

 97%|█████████████████████████████████ | 41279/42525 [1:18:41<02:14,  9.28it/s]

 97%|█████████████████████████████████ | 41281/42525 [1:18:41<02:11,  9.45it/s]

 97%|█████████████████████████████████ | 41284/42525 [1:18:42<02:09,  9.57it/s]

 97%|█████████████████████████████████ | 41285/42525 [1:18:42<02:11,  9.44it/s]

 97%|█████████████████████████████████ | 41287/42525 [1:18:42<02:08,  9.61it/s]

 97%|█████████████████████████████████ | 41290/42525 [1:18:42<02:07,  9.70it/s]

 97%|█████████████████████████████████ | 41292/42525 [1:18:43<02:13,  9.26it/s]

 97%|█████████████████████████████████ | 41294/42525 [1:18:43<02:29,  8.22it/s]

 97%|█████████████████████████████████ | 41296/42525 [1:18:43<02:23,  8.55it/s]

 97%|█████████████████████████████████ | 41298/42525 [1:18:43<02:15,  9.04it/s]

 97%|█████████████████████████████████ | 41300/42525 [1:18:43<02:12,  9.27it/s]

 97%|█████████████████████████████████ | 41302/42525 [1:18:44<02:20,  8.68it/s]

 97%|█████████████████████████████████ | 41304/42525 [1:18:44<02:12,  9.23it/s]

 97%|█████████████████████████████████ | 41306/42525 [1:18:44<02:15,  9.02it/s]

 97%|█████████████████████████████████ | 41308/42525 [1:18:44<02:24,  8.43it/s]

 97%|█████████████████████████████████ | 41310/42525 [1:18:45<02:34,  7.86it/s]

 97%|█████████████████████████████████ | 41312/42525 [1:18:45<02:29,  8.11it/s]

 97%|█████████████████████████████████ | 41314/42525 [1:18:45<02:21,  8.55it/s]

 97%|█████████████████████████████████ | 41316/42525 [1:18:45<02:18,  8.72it/s]

 97%|█████████████████████████████████ | 41318/42525 [1:18:46<02:18,  8.73it/s]

 97%|█████████████████████████████████ | 41320/42525 [1:18:46<02:14,  8.96it/s]

 97%|█████████████████████████████████ | 41322/42525 [1:18:46<02:25,  8.29it/s]

 97%|█████████████████████████████████ | 41324/42525 [1:18:46<02:16,  8.81it/s]

 97%|█████████████████████████████████ | 41326/42525 [1:18:46<02:13,  9.00it/s]

 97%|█████████████████████████████████ | 41328/42525 [1:18:47<02:33,  7.82it/s]

 97%|█████████████████████████████████ | 41330/42525 [1:18:47<02:23,  8.34it/s]

 97%|█████████████████████████████████ | 41332/42525 [1:18:47<02:11,  9.04it/s]

 97%|█████████████████████████████████ | 41334/42525 [1:18:47<02:20,  8.50it/s]

 97%|█████████████████████████████████ | 41336/42525 [1:18:48<02:11,  9.03it/s]

 97%|█████████████████████████████████ | 41338/42525 [1:18:48<02:21,  8.37it/s]

 97%|█████████████████████████████████ | 41341/42525 [1:18:48<02:08,  9.24it/s]

 97%|█████████████████████████████████ | 41342/42525 [1:18:48<02:09,  9.15it/s]

 97%|█████████████████████████████████ | 41344/42525 [1:18:49<02:05,  9.41it/s]

 97%|█████████████████████████████████ | 41347/42525 [1:18:49<02:02,  9.58it/s]

 97%|█████████████████████████████████ | 41350/42525 [1:18:49<02:06,  9.31it/s]

 97%|█████████████████████████████████ | 41353/42525 [1:18:50<02:08,  9.13it/s]

 97%|█████████████████████████████████ | 41355/42525 [1:18:50<02:09,  9.05it/s]

 97%|█████████████████████████████████ | 41357/42525 [1:18:50<02:10,  8.92it/s]

 97%|█████████████████████████████████ | 41359/42525 [1:18:50<02:10,  8.96it/s]

 97%|█████████████████████████████████ | 41361/42525 [1:18:50<02:07,  9.11it/s]

 97%|█████████████████████████████████ | 41363/42525 [1:18:51<02:07,  9.13it/s]

 97%|█████████████████████████████████ | 41366/42525 [1:18:51<02:00,  9.58it/s]

 97%|█████████████████████████████████ | 41368/42525 [1:18:51<02:08,  8.99it/s]

 97%|█████████████████████████████████ | 41371/42525 [1:18:51<02:06,  9.14it/s]

 97%|█████████████████████████████████ | 41373/42525 [1:18:52<02:03,  9.30it/s]

 97%|█████████████████████████████████ | 41376/42525 [1:18:52<02:00,  9.51it/s]

 97%|█████████████████████████████████ | 41378/42525 [1:18:52<02:03,  9.28it/s]

 97%|█████████████████████████████████ | 41381/42525 [1:18:53<01:58,  9.65it/s]

 97%|█████████████████████████████████ | 41383/42525 [1:18:53<01:57,  9.71it/s]

 97%|█████████████████████████████████ | 41385/42525 [1:18:53<01:59,  9.55it/s]

 97%|█████████████████████████████████ | 41387/42525 [1:18:53<02:15,  8.43it/s]

 97%|█████████████████████████████████ | 41389/42525 [1:18:53<02:08,  8.85it/s]

 97%|█████████████████████████████████ | 41391/42525 [1:18:54<02:24,  7.87it/s]

 97%|█████████████████████████████████ | 41393/42525 [1:18:54<02:17,  8.25it/s]

 97%|█████████████████████████████████ | 41395/42525 [1:18:54<02:21,  7.98it/s]

 97%|█████████████████████████████████ | 41398/42525 [1:18:55<02:19,  8.09it/s]

 97%|█████████████████████████████████ | 41400/42525 [1:18:55<02:19,  8.07it/s]

 97%|█████████████████████████████████ | 41402/42525 [1:18:55<02:26,  7.65it/s]

 97%|█████████████████████████████████ | 41405/42525 [1:18:55<02:07,  8.81it/s]

 97%|█████████████████████████████████ | 41406/42525 [1:18:56<02:12,  8.44it/s]

 97%|█████████████████████████████████ | 41410/42525 [1:18:56<01:58,  9.44it/s]

 97%|█████████████████████████████████ | 41412/42525 [1:18:56<01:55,  9.61it/s]

 97%|█████████████████████████████████ | 41414/42525 [1:18:56<02:17,  8.10it/s]

 97%|█████████████████████████████████ | 41416/42525 [1:18:57<02:20,  7.88it/s]

 97%|█████████████████████████████████ | 41418/42525 [1:18:57<02:08,  8.61it/s]

 97%|█████████████████████████████████ | 41421/42525 [1:18:57<02:01,  9.09it/s]

 97%|█████████████████████████████████ | 41423/42525 [1:18:57<02:05,  8.79it/s]

 97%|█████████████████████████████████ | 41426/42525 [1:18:58<02:02,  8.99it/s]

 97%|█████████████████████████████████ | 41428/42525 [1:18:58<02:20,  7.79it/s]

 97%|█████████████████████████████████ | 41429/42525 [1:18:58<02:16,  8.01it/s]

 97%|█████████████████████████████████▏| 41432/42525 [1:18:59<02:06,  8.67it/s]

 97%|█████████████████████████████████▏| 41434/42525 [1:18:59<02:24,  7.55it/s]

 97%|█████████████████████████████████▏| 41436/42525 [1:18:59<02:23,  7.58it/s]

 97%|█████████████████████████████████▏| 41438/42525 [1:18:59<02:13,  8.17it/s]

 97%|█████████████████████████████████▏| 41440/42525 [1:19:00<02:05,  8.63it/s]

 97%|█████████████████████████████████▏| 41442/42525 [1:19:00<01:59,  9.04it/s]

 97%|█████████████████████████████████▏| 41444/42525 [1:19:00<01:59,  9.08it/s]

 97%|█████████████████████████████████▏| 41446/42525 [1:19:00<02:00,  8.92it/s]

 97%|█████████████████████████████████▏| 41448/42525 [1:19:00<02:11,  8.20it/s]

 97%|█████████████████████████████████▏| 41450/42525 [1:19:01<02:21,  7.59it/s]

 97%|█████████████████████████████████▏| 41452/42525 [1:19:01<02:05,  8.57it/s]

 97%|█████████████████████████████████▏| 41454/42525 [1:19:01<02:03,  8.66it/s]

 97%|█████████████████████████████████▏| 41456/42525 [1:19:01<01:57,  9.08it/s]

 97%|█████████████████████████████████▏| 41458/42525 [1:19:02<02:03,  8.61it/s]

 97%|█████████████████████████████████▏| 41460/42525 [1:19:02<01:59,  8.90it/s]

 98%|█████████████████████████████████▏| 41462/42525 [1:19:02<02:01,  8.72it/s]

 98%|█████████████████████████████████▏| 41464/42525 [1:19:02<02:04,  8.51it/s]

 98%|█████████████████████████████████▏| 41466/42525 [1:19:03<01:55,  9.14it/s]

 98%|█████████████████████████████████▏| 41470/42525 [1:19:03<01:48,  9.75it/s]

 98%|█████████████████████████████████▏| 41472/42525 [1:19:03<01:48,  9.75it/s]

 98%|█████████████████████████████████▏| 41474/42525 [1:19:03<02:09,  8.13it/s]

 98%|█████████████████████████████████▏| 41476/42525 [1:19:04<02:02,  8.59it/s]

 98%|█████████████████████████████████▏| 41478/42525 [1:19:04<02:01,  8.60it/s]

 98%|█████████████████████████████████▏| 41479/42525 [1:19:04<01:59,  8.72it/s]

 98%|█████████████████████████████████▏| 41482/42525 [1:19:04<02:03,  8.48it/s]

 98%|█████████████████████████████████▏| 41484/42525 [1:19:05<02:01,  8.57it/s]

 98%|█████████████████████████████████▏| 41486/42525 [1:19:05<01:54,  9.05it/s]

 98%|█████████████████████████████████▏| 41488/42525 [1:19:05<01:50,  9.35it/s]

 98%|█████████████████████████████████▏| 41491/42525 [1:19:05<01:55,  8.99it/s]

 98%|█████████████████████████████████▏| 41493/42525 [1:19:06<01:59,  8.62it/s]

 98%|█████████████████████████████████▏| 41496/42525 [1:19:06<01:49,  9.41it/s]

 98%|█████████████████████████████████▏| 41498/42525 [1:19:06<01:50,  9.33it/s]

 98%|█████████████████████████████████▏| 41499/42525 [1:19:06<01:49,  9.41it/s]

 98%|█████████████████████████████████▏| 41502/42525 [1:19:07<01:56,  8.76it/s]

 98%|█████████████████████████████████▏| 41504/42525 [1:19:07<02:00,  8.49it/s]

 98%|█████████████████████████████████▏| 41507/42525 [1:19:07<01:58,  8.57it/s]

 98%|█████████████████████████████████▏| 41510/42525 [1:19:07<01:53,  8.97it/s]

 98%|█████████████████████████████████▏| 41511/42525 [1:19:08<01:50,  9.16it/s]

 98%|█████████████████████████████████▏| 41514/42525 [1:19:08<01:56,  8.65it/s]

 98%|█████████████████████████████████▏| 41516/42525 [1:19:08<01:53,  8.86it/s]

 98%|█████████████████████████████████▏| 41518/42525 [1:19:08<01:52,  8.94it/s]

 98%|█████████████████████████████████▏| 41520/42525 [1:19:09<01:50,  9.09it/s]

 98%|█████████████████████████████████▏| 41522/42525 [1:19:09<01:56,  8.62it/s]

 98%|█████████████████████████████████▏| 41524/42525 [1:19:09<01:50,  9.06it/s]

 98%|█████████████████████████████████▏| 41527/42525 [1:19:09<01:44,  9.51it/s]

 98%|█████████████████████████████████▏| 41528/42525 [1:19:09<01:46,  9.39it/s]

 98%|█████████████████████████████████▏| 41531/42525 [1:19:10<01:53,  8.72it/s]

 98%|█████████████████████████████████▏| 41533/42525 [1:19:10<02:00,  8.23it/s]

 98%|█████████████████████████████████▏| 41535/42525 [1:19:10<01:54,  8.67it/s]

 98%|█████████████████████████████████▏| 41537/42525 [1:19:11<01:53,  8.73it/s]

 98%|█████████████████████████████████▏| 41540/42525 [1:19:11<01:44,  9.41it/s]

 98%|█████████████████████████████████▏| 41541/42525 [1:19:11<01:53,  8.66it/s]

 98%|█████████████████████████████████▏| 41544/42525 [1:19:11<01:45,  9.29it/s]

 98%|█████████████████████████████████▏| 41545/42525 [1:19:11<01:52,  8.71it/s]

 98%|█████████████████████████████████▏| 41548/42525 [1:19:12<01:50,  8.84it/s]

 98%|█████████████████████████████████▏| 41551/42525 [1:19:12<01:55,  8.46it/s]

 98%|█████████████████████████████████▏| 41553/42525 [1:19:12<01:50,  8.77it/s]

 98%|█████████████████████████████████▏| 41555/42525 [1:19:13<01:48,  8.91it/s]

 98%|█████████████████████████████████▏| 41557/42525 [1:19:13<01:58,  8.15it/s]

 98%|█████████████████████████████████▏| 41558/42525 [1:19:13<01:55,  8.40it/s]

 98%|█████████████████████████████████▏| 41561/42525 [1:19:13<01:56,  8.26it/s]

 98%|█████████████████████████████████▏| 41563/42525 [1:19:14<02:01,  7.89it/s]

 98%|█████████████████████████████████▏| 41565/42525 [1:19:14<01:49,  8.73it/s]

 98%|█████████████████████████████████▏| 41567/42525 [1:19:14<02:03,  7.76it/s]

 98%|█████████████████████████████████▏| 41569/42525 [1:19:14<01:53,  8.39it/s]

 98%|█████████████████████████████████▏| 41572/42525 [1:19:15<01:47,  8.87it/s]

 98%|█████████████████████████████████▏| 41575/42525 [1:19:15<01:41,  9.38it/s]

 98%|█████████████████████████████████▏| 41577/42525 [1:19:15<01:52,  8.41it/s]

 98%|█████████████████████████████████▏| 41579/42525 [1:19:15<01:57,  8.05it/s]

 98%|█████████████████████████████████▏| 41581/42525 [1:19:16<01:48,  8.71it/s]

 98%|█████████████████████████████████▏| 41583/42525 [1:19:16<01:43,  9.13it/s]

 98%|█████████████████████████████████▏| 41585/42525 [1:19:16<01:38,  9.51it/s]

 98%|█████████████████████████████████▎| 41587/42525 [1:19:16<01:40,  9.34it/s]

 98%|█████████████████████████████████▎| 41589/42525 [1:19:16<01:49,  8.51it/s]

 98%|█████████████████████████████████▎| 41591/42525 [1:19:17<01:43,  9.03it/s]

 98%|█████████████████████████████████▎| 41592/42525 [1:19:17<01:42,  9.10it/s]

 98%|█████████████████████████████████▎| 41595/42525 [1:19:17<01:38,  9.44it/s]

 98%|█████████████████████████████████▎| 41597/42525 [1:19:17<01:38,  9.47it/s]

 98%|█████████████████████████████████▎| 41599/42525 [1:19:18<01:38,  9.43it/s]

 98%|█████████████████████████████████▎| 41602/42525 [1:19:18<01:40,  9.19it/s]

 98%|█████████████████████████████████▎| 41604/42525 [1:19:18<01:45,  8.71it/s]

 98%|█████████████████████████████████▎| 41605/42525 [1:19:18<01:47,  8.52it/s]

 98%|█████████████████████████████████▎| 41608/42525 [1:19:19<01:44,  8.74it/s]

 98%|█████████████████████████████████▎| 41609/42525 [1:19:19<01:43,  8.89it/s]

 98%|█████████████████████████████████▎| 41611/42525 [1:19:19<01:40,  9.08it/s]

 98%|█████████████████████████████████▎| 41614/42525 [1:19:19<01:47,  8.48it/s]

 98%|█████████████████████████████████▎| 41616/42525 [1:19:19<01:42,  8.91it/s]

 98%|█████████████████████████████████▎| 41618/42525 [1:19:20<01:42,  8.81it/s]

 98%|█████████████████████████████████▎| 41620/42525 [1:19:20<01:40,  8.96it/s]

 98%|█████████████████████████████████▎| 41622/42525 [1:19:20<01:41,  8.91it/s]

 98%|█████████████████████████████████▎| 41624/42525 [1:19:20<01:41,  8.87it/s]

 98%|█████████████████████████████████▎| 41626/42525 [1:19:21<01:39,  9.03it/s]

 98%|█████████████████████████████████▎| 41628/42525 [1:19:21<01:41,  8.85it/s]

 98%|█████████████████████████████████▎| 41630/42525 [1:19:21<01:51,  7.99it/s]

 98%|█████████████████████████████████▎| 41632/42525 [1:19:21<01:51,  8.00it/s]

 98%|█████████████████████████████████▎| 41635/42525 [1:19:22<01:38,  9.06it/s]

 98%|█████████████████████████████████▎| 41637/42525 [1:19:22<01:54,  7.78it/s]

 98%|█████████████████████████████████▎| 41638/42525 [1:19:22<01:59,  7.42it/s]

 98%|█████████████████████████████████▎| 41641/42525 [1:19:22<01:44,  8.49it/s]

 98%|█████████████████████████████████▎| 41643/42525 [1:19:23<01:38,  8.96it/s]

 98%|█████████████████████████████████▎| 41645/42525 [1:19:23<01:41,  8.67it/s]

 98%|█████████████████████████████████▎| 41647/42525 [1:19:23<01:40,  8.72it/s]

 98%|█████████████████████████████████▎| 41649/42525 [1:19:23<01:37,  8.95it/s]

 98%|█████████████████████████████████▎| 41651/42525 [1:19:24<01:37,  8.96it/s]

 98%|█████████████████████████████████▎| 41653/42525 [1:19:24<01:35,  9.15it/s]

 98%|█████████████████████████████████▎| 41655/42525 [1:19:24<01:31,  9.48it/s]

 98%|█████████████████████████████████▎| 41658/42525 [1:19:24<01:32,  9.40it/s]

 98%|█████████████████████████████████▎| 41659/42525 [1:19:24<01:31,  9.47it/s]

 98%|█████████████████████████████████▎| 41662/42525 [1:19:25<01:30,  9.49it/s]

 98%|█████████████████████████████████▎| 41664/42525 [1:19:25<01:31,  9.37it/s]

 98%|█████████████████████████████████▎| 41666/42525 [1:19:25<01:39,  8.63it/s]

 98%|█████████████████████████████████▎| 41668/42525 [1:19:25<01:33,  9.13it/s]

 98%|█████████████████████████████████▎| 41670/42525 [1:19:26<01:39,  8.58it/s]

 98%|█████████████████████████████████▎| 41672/42525 [1:19:26<01:46,  7.99it/s]

 98%|█████████████████████████████████▎| 41674/42525 [1:19:26<01:46,  8.01it/s]

 98%|█████████████████████████████████▎| 41676/42525 [1:19:26<01:37,  8.72it/s]

 98%|█████████████████████████████████▎| 41679/42525 [1:19:27<01:31,  9.21it/s]

 98%|█████████████████████████████████▎| 41681/42525 [1:19:27<01:34,  8.96it/s]

 98%|█████████████████████████████████▎| 41683/42525 [1:19:27<01:31,  9.21it/s]

 98%|█████████████████████████████████▎| 41685/42525 [1:19:27<01:28,  9.47it/s]

 98%|█████████████████████████████████▎| 41687/42525 [1:19:28<01:38,  8.51it/s]

 98%|█████████████████████████████████▎| 41689/42525 [1:19:28<01:39,  8.37it/s]

 98%|█████████████████████████████████▎| 41691/42525 [1:19:28<01:38,  8.43it/s]

 98%|█████████████████████████████████▎| 41693/42525 [1:19:28<01:45,  7.87it/s]

 98%|█████████████████████████████████▎| 41695/42525 [1:19:29<01:36,  8.64it/s]

 98%|█████████████████████████████████▎| 41697/42525 [1:19:29<01:41,  8.15it/s]

 98%|█████████████████████████████████▎| 41700/42525 [1:19:29<01:28,  9.28it/s]

 98%|█████████████████████████████████▎| 41702/42525 [1:19:29<01:33,  8.78it/s]

 98%|█████████████████████████████████▎| 41704/42525 [1:19:30<01:31,  8.93it/s]

 98%|█████████████████████████████████▎| 41706/42525 [1:19:30<01:32,  8.83it/s]

 98%|█████████████████████████████████▎| 41708/42525 [1:19:30<01:31,  8.92it/s]

 98%|█████████████████████████████████▎| 41710/42525 [1:19:30<01:28,  9.23it/s]

 98%|█████████████████████████████████▎| 41713/42525 [1:19:31<01:24,  9.57it/s]

 98%|█████████████████████████████████▎| 41715/42525 [1:19:31<01:31,  8.83it/s]

 98%|█████████████████████████████████▎| 41717/42525 [1:19:31<01:31,  8.87it/s]

 98%|█████████████████████████████████▎| 41719/42525 [1:19:31<01:28,  9.08it/s]

 98%|█████████████████████████████████▎| 41721/42525 [1:19:31<01:26,  9.30it/s]

 98%|█████████████████████████████████▎| 41723/42525 [1:19:32<01:29,  8.98it/s]

 98%|█████████████████████████████████▎| 41725/42525 [1:19:32<01:34,  8.47it/s]

 98%|█████████████████████████████████▎| 41727/42525 [1:19:32<01:29,  8.89it/s]

 98%|█████████████████████████████████▎| 41729/42525 [1:19:32<01:38,  8.10it/s]

 98%|█████████████████████████████████▎| 41731/42525 [1:19:33<01:41,  7.81it/s]

 98%|█████████████████████████████████▎| 41734/42525 [1:19:33<01:30,  8.77it/s]

 98%|█████████████████████████████████▎| 41736/42525 [1:19:33<01:26,  9.17it/s]

 98%|█████████████████████████████████▎| 41738/42525 [1:19:33<01:22,  9.52it/s]

 98%|█████████████████████████████████▎| 41741/42525 [1:19:34<01:30,  8.64it/s]

 98%|█████████████████████████████████▎| 41743/42525 [1:19:34<01:29,  8.75it/s]

 98%|█████████████████████████████████▍| 41744/42525 [1:19:34<01:34,  8.28it/s]

 98%|█████████████████████████████████▍| 41748/42525 [1:19:34<01:23,  9.31it/s]

 98%|█████████████████████████████████▍| 41750/42525 [1:19:35<01:21,  9.46it/s]

 98%|█████████████████████████████████▍| 41753/42525 [1:19:35<01:21,  9.48it/s]

 98%|█████████████████████████████████▍| 41754/42525 [1:19:35<01:24,  9.10it/s]

 98%|█████████████████████████████████▍| 41756/42525 [1:19:35<01:21,  9.39it/s]

 98%|█████████████████████████████████▍| 41759/42525 [1:19:36<01:25,  8.92it/s]

 98%|█████████████████████████████████▍| 41761/42525 [1:19:36<01:26,  8.79it/s]

 98%|█████████████████████████████████▍| 41763/42525 [1:19:36<01:37,  7.83it/s]

 98%|█████████████████████████████████▍| 41765/42525 [1:19:36<01:28,  8.62it/s]

 98%|█████████████████████████████████▍| 41768/42525 [1:19:37<01:22,  9.22it/s]

 98%|█████████████████████████████████▍| 41770/42525 [1:19:37<01:25,  8.85it/s]

 98%|█████████████████████████████████▍| 41772/42525 [1:19:37<01:23,  9.03it/s]

 98%|█████████████████████████████████▍| 41774/42525 [1:19:37<01:30,  8.30it/s]

 98%|█████████████████████████████████▍| 41776/42525 [1:19:38<01:33,  8.04it/s]

 98%|█████████████████████████████████▍| 41778/42525 [1:19:38<01:26,  8.68it/s]

 98%|█████████████████████████████████▍| 41780/42525 [1:19:38<01:29,  8.35it/s]

 98%|█████████████████████████████████▍| 41782/42525 [1:19:38<01:23,  8.91it/s]

 98%|█████████████████████████████████▍| 41783/42525 [1:19:38<01:21,  9.09it/s]

 98%|█████████████████████████████████▍| 41786/42525 [1:19:39<01:18,  9.41it/s]

 98%|█████████████████████████████████▍| 41788/42525 [1:19:39<01:25,  8.67it/s]

 98%|█████████████████████████████████▍| 41789/42525 [1:19:39<01:26,  8.55it/s]

 98%|█████████████████████████████████▍| 41791/42525 [1:19:39<01:21,  8.96it/s]

 98%|█████████████████████████████████▍| 41794/42525 [1:19:40<01:23,  8.72it/s]

 98%|█████████████████████████████████▍| 41796/42525 [1:19:40<01:27,  8.28it/s]

 98%|█████████████████████████████████▍| 41799/42525 [1:19:40<01:28,  8.16it/s]

 98%|█████████████████████████████████▍| 41801/42525 [1:19:41<01:22,  8.81it/s]

 98%|█████████████████████████████████▍| 41803/42525 [1:19:41<01:35,  7.58it/s]

 98%|█████████████████████████████████▍| 41806/42525 [1:19:41<01:25,  8.37it/s]

 98%|█████████████████████████████████▍| 41808/42525 [1:19:41<01:20,  8.96it/s]

 98%|█████████████████████████████████▍| 41810/42525 [1:19:42<01:26,  8.30it/s]

 98%|█████████████████████████████████▍| 41813/42525 [1:19:42<01:17,  9.22it/s]

 98%|█████████████████████████████████▍| 41815/42525 [1:19:42<01:17,  9.13it/s]

 98%|█████████████████████████████████▍| 41817/42525 [1:19:42<01:15,  9.33it/s]

 98%|█████████████████████████████████▍| 41819/42525 [1:19:43<01:27,  8.03it/s]

 98%|█████████████████████████████████▍| 41822/42525 [1:19:43<01:20,  8.70it/s]

 98%|█████████████████████████████████▍| 41825/42525 [1:19:43<01:19,  8.85it/s]

 98%|█████████████████████████████████▍| 41827/42525 [1:19:44<01:19,  8.73it/s]

 98%|█████████████████████████████████▍| 41829/42525 [1:19:44<01:31,  7.64it/s]

 98%|█████████████████████████████████▍| 41831/42525 [1:19:44<01:25,  8.08it/s]

 98%|█████████████████████████████████▍| 41834/42525 [1:19:44<01:24,  8.22it/s]

 98%|█████████████████████████████████▍| 41836/42525 [1:19:45<01:22,  8.31it/s]

 98%|█████████████████████████████████▍| 41839/42525 [1:19:45<01:16,  8.95it/s]

 98%|█████████████████████████████████▍| 41841/42525 [1:19:45<01:17,  8.87it/s]

 98%|█████████████████████████████████▍| 41843/42525 [1:19:45<01:14,  9.18it/s]

 98%|█████████████████████████████████▍| 41846/42525 [1:19:46<01:11,  9.44it/s]

 98%|█████████████████████████████████▍| 41848/42525 [1:19:46<01:16,  8.83it/s]

 98%|█████████████████████████████████▍| 41851/42525 [1:19:46<01:12,  9.28it/s]

 98%|█████████████████████████████████▍| 41853/42525 [1:19:46<01:13,  9.18it/s]

 98%|█████████████████████████████████▍| 41855/42525 [1:19:47<01:14,  8.95it/s]

 98%|█████████████████████████████████▍| 41857/42525 [1:19:47<01:12,  9.22it/s]

 98%|█████████████████████████████████▍| 41859/42525 [1:19:47<01:12,  9.13it/s]

 98%|█████████████████████████████████▍| 41861/42525 [1:19:47<01:11,  9.30it/s]

 98%|█████████████████████████████████▍| 41863/42525 [1:19:48<01:21,  8.13it/s]

 98%|█████████████████████████████████▍| 41866/42525 [1:19:48<01:16,  8.60it/s]

 98%|█████████████████████████████████▍| 41868/42525 [1:19:48<01:22,  7.96it/s]

 98%|█████████████████████████████████▍| 41870/42525 [1:19:49<01:25,  7.68it/s]

 98%|█████████████████████████████████▍| 41871/42525 [1:19:49<01:20,  8.17it/s]

 98%|█████████████████████████████████▍| 41874/42525 [1:19:49<01:19,  8.17it/s]

 98%|█████████████████████████████████▍| 41877/42525 [1:19:49<01:12,  8.88it/s]

 98%|█████████████████████████████████▍| 41879/42525 [1:19:50<01:17,  8.36it/s]

 98%|█████████████████████████████████▍| 41882/42525 [1:19:50<01:11,  9.05it/s]

 98%|█████████████████████████████████▍| 41884/42525 [1:19:50<01:08,  9.34it/s]

 98%|█████████████████████████████████▍| 41887/42525 [1:19:50<01:06,  9.59it/s]

 99%|█████████████████████████████████▍| 41889/42525 [1:19:51<01:14,  8.55it/s]

 99%|█████████████████████████████████▍| 41891/42525 [1:19:51<01:17,  8.21it/s]

 99%|█████████████████████████████████▍| 41894/42525 [1:19:51<01:09,  9.03it/s]

 99%|█████████████████████████████████▍| 41897/42525 [1:19:52<01:09,  8.98it/s]

 99%|█████████████████████████████████▍| 41899/42525 [1:19:52<01:16,  8.22it/s]

 99%|█████████████████████████████████▌| 41901/42525 [1:19:52<01:11,  8.67it/s]

 99%|█████████████████████████████████▌| 41904/42525 [1:19:52<01:07,  9.14it/s]

 99%|█████████████████████████████████▌| 41906/42525 [1:19:53<01:06,  9.33it/s]

 99%|█████████████████████████████████▌| 41908/42525 [1:19:53<01:06,  9.31it/s]

 99%|█████████████████████████████████▌| 41910/42525 [1:19:53<01:11,  8.62it/s]

 99%|█████████████████████████████████▌| 41911/42525 [1:19:53<01:09,  8.90it/s]

 99%|█████████████████████████████████▌| 41914/42525 [1:19:53<01:09,  8.73it/s]

 99%|█████████████████████████████████▌| 41916/42525 [1:19:54<01:13,  8.28it/s]

 99%|█████████████████████████████████▌| 41918/42525 [1:19:54<01:18,  7.76it/s]

 99%|█████████████████████████████████▌| 41920/42525 [1:19:54<01:13,  8.25it/s]

 99%|█████████████████████████████████▌| 41922/42525 [1:19:54<01:08,  8.74it/s]

 99%|█████████████████████████████████▌| 41924/42525 [1:19:55<01:19,  7.52it/s]

 99%|█████████████████████████████████▌| 41926/42525 [1:19:55<01:13,  8.20it/s]

 99%|█████████████████████████████████▌| 41928/42525 [1:19:55<01:08,  8.72it/s]

 99%|█████████████████████████████████▌| 41930/42525 [1:19:55<01:14,  7.96it/s]

 99%|█████████████████████████████████▌| 41932/42525 [1:19:56<01:15,  7.82it/s]

 99%|█████████████████████████████████▌| 41934/42525 [1:19:56<01:10,  8.42it/s]

 99%|█████████████████████████████████▌| 41937/42525 [1:19:56<01:03,  9.22it/s]

 99%|█████████████████████████████████▌| 41939/42525 [1:19:56<01:03,  9.27it/s]

 99%|█████████████████████████████████▌| 41941/42525 [1:19:57<01:11,  8.19it/s]

 99%|█████████████████████████████████▌| 41943/42525 [1:19:57<01:07,  8.61it/s]

 99%|█████████████████████████████████▌| 41945/42525 [1:19:57<01:09,  8.38it/s]

 99%|█████████████████████████████████▌| 41947/42525 [1:19:57<01:12,  7.99it/s]

 99%|█████████████████████████████████▌| 41949/42525 [1:19:58<01:07,  8.48it/s]

 99%|█████████████████████████████████▌| 41951/42525 [1:19:58<01:09,  8.28it/s]

 99%|█████████████████████████████████▌| 41953/42525 [1:19:58<01:10,  8.08it/s]

 99%|█████████████████████████████████▌| 41955/42525 [1:19:58<01:13,  7.80it/s]

 99%|█████████████████████████████████▌| 41957/42525 [1:19:59<01:06,  8.56it/s]

 99%|█████████████████████████████████▌| 41960/42525 [1:19:59<01:00,  9.41it/s]

 99%|█████████████████████████████████▌| 41963/42525 [1:19:59<00:59,  9.48it/s]

 99%|█████████████████████████████████▌| 41965/42525 [1:19:59<00:59,  9.46it/s]

 99%|█████████████████████████████████▌| 41967/42525 [1:20:00<01:05,  8.57it/s]

 99%|█████████████████████████████████▌| 41970/42525 [1:20:00<01:00,  9.19it/s]

 99%|█████████████████████████████████▌| 41972/42525 [1:20:00<01:05,  8.51it/s]

 99%|█████████████████████████████████▌| 41974/42525 [1:20:01<01:05,  8.36it/s]

 99%|█████████████████████████████████▌| 41975/42525 [1:20:01<01:04,  8.52it/s]

 99%|█████████████████████████████████▌| 41979/42525 [1:20:01<00:58,  9.35it/s]

 99%|█████████████████████████████████▌| 41981/42525 [1:20:01<01:02,  8.77it/s]

 99%|█████████████████████████████████▌| 41983/42525 [1:20:02<01:07,  8.05it/s]

 99%|█████████████████████████████████▌| 41985/42525 [1:20:02<01:05,  8.19it/s]

 99%|█████████████████████████████████▌| 41988/42525 [1:20:02<01:04,  8.28it/s]

 99%|█████████████████████████████████▌| 41990/42525 [1:20:02<01:07,  7.93it/s]

 99%|█████████████████████████████████▌| 41992/42525 [1:20:03<01:06,  8.00it/s]

 99%|█████████████████████████████████▌| 41994/42525 [1:20:03<01:01,  8.61it/s]

 99%|█████████████████████████████████▌| 41996/42525 [1:20:03<01:05,  8.11it/s]

 99%|█████████████████████████████████▌| 41998/42525 [1:20:03<00:58,  8.93it/s]

 99%|█████████████████████████████████▌| 42001/42525 [1:20:04<00:55,  9.43it/s]

 99%|█████████████████████████████████▌| 42003/42525 [1:20:04<00:54,  9.66it/s]

 99%|█████████████████████████████████▌| 42006/42525 [1:20:04<00:58,  8.86it/s]

 99%|█████████████████████████████████▌| 42008/42525 [1:20:04<01:01,  8.47it/s]

 99%|█████████████████████████████████▌| 42011/42525 [1:20:05<00:55,  9.23it/s]

 99%|█████████████████████████████████▌| 42014/42525 [1:20:05<00:57,  8.88it/s]

 99%|█████████████████████████████████▌| 42017/42525 [1:20:05<00:53,  9.49it/s]

 99%|█████████████████████████████████▌| 42019/42525 [1:20:06<00:55,  9.13it/s]

 99%|█████████████████████████████████▌| 42022/42525 [1:20:06<00:54,  9.31it/s]

 99%|█████████████████████████████████▌| 42024/42525 [1:20:06<00:55,  9.06it/s]

 99%|█████████████████████████████████▌| 42026/42525 [1:20:06<00:53,  9.33it/s]

 99%|█████████████████████████████████▌| 42029/42525 [1:20:07<00:56,  8.71it/s]

 99%|█████████████████████████████████▌| 42031/42525 [1:20:07<01:00,  8.10it/s]

 99%|█████████████████████████████████▌| 42033/42525 [1:20:07<00:56,  8.67it/s]

 99%|█████████████████████████████████▌| 42034/42525 [1:20:07<00:55,  8.90it/s]

 99%|█████████████████████████████████▌| 42037/42525 [1:20:08<00:52,  9.28it/s]

 99%|█████████████████████████████████▌| 42040/42525 [1:20:08<00:48,  9.92it/s]

 99%|█████████████████████████████████▌| 42043/42525 [1:20:08<00:47, 10.05it/s]

 99%|█████████████████████████████████▌| 42045/42525 [1:20:08<00:52,  9.21it/s]

 99%|█████████████████████████████████▌| 42047/42525 [1:20:09<00:52,  9.08it/s]

 99%|█████████████████████████████████▌| 42050/42525 [1:20:09<00:50,  9.39it/s]

 99%|█████████████████████████████████▌| 42052/42525 [1:20:09<00:54,  8.72it/s]

 99%|█████████████████████████████████▌| 42054/42525 [1:20:09<00:52,  8.89it/s]

 99%|█████████████████████████████████▋| 42056/42525 [1:20:10<00:58,  8.05it/s]

 99%|█████████████████████████████████▋| 42058/42525 [1:20:10<01:00,  7.78it/s]

 99%|█████████████████████████████████▋| 42060/42525 [1:20:10<01:01,  7.59it/s]

 99%|█████████████████████████████████▋| 42062/42525 [1:20:11<00:58,  7.87it/s]

 99%|█████████████████████████████████▋| 42064/42525 [1:20:11<00:59,  7.69it/s]

 99%|█████████████████████████████████▋| 42066/42525 [1:20:11<00:54,  8.45it/s]

 99%|█████████████████████████████████▋| 42068/42525 [1:20:11<00:52,  8.79it/s]

 99%|█████████████████████████████████▋| 42070/42525 [1:20:11<00:50,  9.05it/s]

 99%|█████████████████████████████████▋| 42072/42525 [1:20:12<00:59,  7.65it/s]

 99%|█████████████████████████████████▋| 42075/42525 [1:20:12<00:53,  8.43it/s]

 99%|█████████████████████████████████▋| 42077/42525 [1:20:12<00:50,  8.94it/s]

 99%|█████████████████████████████████▋| 42080/42525 [1:20:13<00:46,  9.63it/s]

 99%|█████████████████████████████████▋| 42083/42525 [1:20:13<00:44,  9.84it/s]

 99%|█████████████████████████████████▋| 42085/42525 [1:20:13<00:47,  9.28it/s]

 99%|█████████████████████████████████▋| 42087/42525 [1:20:13<00:51,  8.52it/s]

 99%|█████████████████████████████████▋| 42089/42525 [1:20:14<00:48,  8.92it/s]

 99%|█████████████████████████████████▋| 42091/42525 [1:20:14<00:50,  8.63it/s]

 99%|█████████████████████████████████▋| 42093/42525 [1:20:14<00:57,  7.55it/s]

 99%|█████████████████████████████████▋| 42096/42525 [1:20:14<00:53,  7.99it/s]

 99%|█████████████████████████████████▋| 42098/42525 [1:20:15<00:56,  7.57it/s]

 99%|█████████████████████████████████▋| 42100/42525 [1:20:15<00:55,  7.67it/s]

 99%|█████████████████████████████████▋| 42102/42525 [1:20:15<00:51,  8.20it/s]

 99%|█████████████████████████████████▋| 42103/42525 [1:20:15<00:48,  8.63it/s]

 99%|█████████████████████████████████▋| 42106/42525 [1:20:16<00:48,  8.63it/s]

 99%|█████████████████████████████████▋| 42108/42525 [1:20:16<00:49,  8.49it/s]

 99%|█████████████████████████████████▋| 42110/42525 [1:20:16<00:52,  7.87it/s]

 99%|█████████████████████████████████▋| 42112/42525 [1:20:16<00:48,  8.48it/s]

 99%|█████████████████████████████████▋| 42115/42525 [1:20:17<00:49,  8.36it/s]

 99%|█████████████████████████████████▋| 42117/42525 [1:20:17<00:51,  7.86it/s]

 99%|█████████████████████████████████▋| 42119/42525 [1:20:17<00:49,  8.15it/s]

 99%|█████████████████████████████████▋| 42122/42525 [1:20:18<00:45,  8.88it/s]

 99%|█████████████████████████████████▋| 42126/42525 [1:20:18<00:41,  9.68it/s]

 99%|█████████████████████████████████▋| 42129/42525 [1:20:18<00:40,  9.84it/s]

 99%|█████████████████████████████████▋| 42131/42525 [1:20:18<00:40,  9.71it/s]

 99%|█████████████████████████████████▋| 42133/42525 [1:20:19<00:43,  9.00it/s]

 99%|█████████████████████████████████▋| 42134/42525 [1:20:19<00:42,  9.13it/s]

 99%|█████████████████████████████████▋| 42136/42525 [1:20:19<00:42,  9.10it/s]

 99%|█████████████████████████████████▋| 42139/42525 [1:20:19<00:40,  9.44it/s]

 99%|█████████████████████████████████▋| 42142/42525 [1:20:20<00:41,  9.19it/s]

 99%|█████████████████████████████████▋| 42145/42525 [1:20:20<00:40,  9.30it/s]

 99%|█████████████████████████████████▋| 42148/42525 [1:20:20<00:39,  9.58it/s]

 99%|█████████████████████████████████▋| 42151/42525 [1:20:21<00:39,  9.42it/s]

 99%|█████████████████████████████████▋| 42154/42525 [1:20:21<00:38,  9.74it/s]

 99%|█████████████████████████████████▋| 42157/42525 [1:20:21<00:38,  9.52it/s]

 99%|█████████████████████████████████▋| 42160/42525 [1:20:22<00:38,  9.53it/s]

 99%|█████████████████████████████████▋| 42162/42525 [1:20:22<00:37,  9.75it/s]

 99%|█████████████████████████████████▋| 42164/42525 [1:20:22<00:39,  9.20it/s]

 99%|█████████████████████████████████▋| 42168/42525 [1:20:22<00:38,  9.27it/s]

 99%|█████████████████████████████████▋| 42172/42525 [1:20:23<00:36,  9.69it/s]

 99%|█████████████████████████████████▋| 42174/42525 [1:20:23<00:36,  9.49it/s]

 99%|█████████████████████████████████▋| 42178/42525 [1:20:23<00:35,  9.87it/s]

 99%|█████████████████████████████████▋| 42181/42525 [1:20:24<00:34,  9.90it/s]

 99%|█████████████████████████████████▋| 42183/42525 [1:20:24<00:35,  9.68it/s]

 99%|█████████████████████████████████▋| 42185/42525 [1:20:24<00:37,  9.04it/s]

 99%|█████████████████████████████████▋| 42188/42525 [1:20:25<00:35,  9.58it/s]

 99%|█████████████████████████████████▋| 42191/42525 [1:20:25<00:34,  9.72it/s]

 99%|█████████████████████████████████▋| 42194/42525 [1:20:25<00:35,  9.37it/s]

 99%|█████████████████████████████████▋| 42195/42525 [1:20:25<00:35,  9.21it/s]

 99%|█████████████████████████████████▋| 42198/42525 [1:20:26<00:37,  8.70it/s]

 99%|█████████████████████████████████▋| 42202/42525 [1:20:26<00:36,  8.96it/s]

 99%|█████████████████████████████████▋| 42205/42525 [1:20:26<00:34,  9.29it/s]

 99%|█████████████████████████████████▋| 42207/42525 [1:20:27<00:34,  9.18it/s]

 99%|█████████████████████████████████▋| 42210/42525 [1:20:27<00:32,  9.57it/s]

 99%|█████████████████████████████████▊| 42213/42525 [1:20:27<00:34,  9.01it/s]

 99%|█████████████████████████████████▊| 42215/42525 [1:20:27<00:34,  8.98it/s]

 99%|█████████████████████████████████▊| 42217/42525 [1:20:28<00:38,  8.09it/s]

 99%|█████████████████████████████████▊| 42220/42525 [1:20:28<00:33,  9.20it/s]

 99%|█████████████████████████████████▊| 42223/42525 [1:20:28<00:32,  9.31it/s]

 99%|█████████████████████████████████▊| 42225/42525 [1:20:29<00:32,  9.36it/s]

 99%|█████████████████████████████████▊| 42229/42525 [1:20:29<00:30,  9.83it/s]

 99%|█████████████████████████████████▊| 42231/42525 [1:20:29<00:32,  8.92it/s]

 99%|█████████████████████████████████▊| 42232/42525 [1:20:29<00:32,  9.09it/s]

 99%|█████████████████████████████████▊| 42235/42525 [1:20:30<00:32,  8.87it/s]

 99%|█████████████████████████████████▊| 42237/42525 [1:20:30<00:31,  9.19it/s]

 99%|█████████████████████████████████▊| 42240/42525 [1:20:30<00:30,  9.35it/s]

 99%|█████████████████████████████████▊| 42243/42525 [1:20:31<00:30,  9.29it/s]

 99%|█████████████████████████████████▊| 42244/42525 [1:20:31<00:30,  9.11it/s]

 99%|█████████████████████████████████▊| 42247/42525 [1:20:31<00:29,  9.49it/s]

 99%|█████████████████████████████████▊| 42250/42525 [1:20:31<00:28,  9.63it/s]

 99%|█████████████████████████████████▊| 42251/42525 [1:20:31<00:28,  9.64it/s]

 99%|█████████████████████████████████▊| 42254/42525 [1:20:32<00:29,  9.14it/s]

 99%|█████████████████████████████████▊| 42255/42525 [1:20:32<00:31,  8.59it/s]

 99%|█████████████████████████████████▊| 42258/42525 [1:20:32<00:31,  8.54it/s]

 99%|█████████████████████████████████▊| 42260/42525 [1:20:32<00:29,  8.99it/s]

 99%|█████████████████████████████████▊| 42263/42525 [1:20:33<00:28,  9.32it/s]

 99%|█████████████████████████████████▊| 42266/42525 [1:20:33<00:27,  9.56it/s]

 99%|█████████████████████████████████▊| 42268/42525 [1:20:33<00:27,  9.50it/s]

 99%|█████████████████████████████████▊| 42270/42525 [1:20:33<00:27,  9.44it/s]

 99%|█████████████████████████████████▊| 42273/42525 [1:20:34<00:25,  9.87it/s]

 99%|█████████████████████████████████▊| 42275/42525 [1:20:34<00:24, 10.06it/s]

 99%|█████████████████████████████████▊| 42278/42525 [1:20:34<00:28,  8.63it/s]

 99%|█████████████████████████████████▊| 42280/42525 [1:20:35<00:26,  9.16it/s]

 99%|█████████████████████████████████▊| 42283/42525 [1:20:35<00:28,  8.56it/s]

 99%|█████████████████████████████████▊| 42286/42525 [1:20:35<00:28,  8.47it/s]

 99%|█████████████████████████████████▊| 42287/42525 [1:20:35<00:29,  8.03it/s]

 99%|█████████████████████████████████▊| 42290/42525 [1:20:36<00:26,  8.88it/s]

 99%|█████████████████████████████████▊| 42293/42525 [1:20:36<00:25,  9.23it/s]

 99%|█████████████████████████████████▊| 42296/42525 [1:20:36<00:27,  8.41it/s]

 99%|█████████████████████████████████▊| 42299/42525 [1:20:37<00:26,  8.43it/s]

 99%|█████████████████████████████████▊| 42303/42525 [1:20:37<00:23,  9.40it/s]

 99%|█████████████████████████████████▊| 42306/42525 [1:20:37<00:24,  8.86it/s]

 99%|█████████████████████████████████▊| 42308/42525 [1:20:38<00:25,  8.57it/s]

 99%|█████████████████████████████████▊| 42311/42525 [1:20:38<00:24,  8.79it/s]

100%|█████████████████████████████████▊| 42315/42525 [1:20:38<00:21,  9.79it/s]

100%|█████████████████████████████████▊| 42318/42525 [1:20:39<00:21,  9.54it/s]

100%|█████████████████████████████████▊| 42320/42525 [1:20:39<00:20,  9.84it/s]

100%|█████████████████████████████████▊| 42323/42525 [1:20:39<00:21,  9.51it/s]

100%|█████████████████████████████████▊| 42325/42525 [1:20:40<00:24,  8.16it/s]

100%|█████████████████████████████████▊| 42327/42525 [1:20:40<00:24,  8.01it/s]

100%|█████████████████████████████████▊| 42329/42525 [1:20:40<00:22,  8.56it/s]

100%|█████████████████████████████████▊| 42331/42525 [1:20:40<00:23,  8.36it/s]

100%|█████████████████████████████████▊| 42333/42525 [1:20:41<00:22,  8.59it/s]

100%|█████████████████████████████████▊| 42334/42525 [1:20:41<00:21,  8.96it/s]

100%|█████████████████████████████████▊| 42337/42525 [1:20:41<00:20,  9.31it/s]

100%|█████████████████████████████████▊| 42339/42525 [1:20:41<00:19,  9.53it/s]

100%|█████████████████████████████████▊| 42340/42525 [1:20:41<00:19,  9.28it/s]

100%|█████████████████████████████████▊| 42343/42525 [1:20:42<00:19,  9.39it/s]

100%|█████████████████████████████████▊| 42345/42525 [1:20:42<00:18,  9.48it/s]

100%|█████████████████████████████████▊| 42347/42525 [1:20:42<00:20,  8.86it/s]

100%|█████████████████████████████████▊| 42350/42525 [1:20:42<00:18,  9.34it/s]

100%|█████████████████████████████████▊| 42352/42525 [1:20:43<00:20,  8.52it/s]

100%|█████████████████████████████████▊| 42354/42525 [1:20:43<00:18,  9.07it/s]

100%|█████████████████████████████████▊| 42357/42525 [1:20:43<00:18,  9.11it/s]

100%|█████████████████████████████████▊| 42360/42525 [1:20:43<00:18,  9.04it/s]

100%|█████████████████████████████████▊| 42362/42525 [1:20:44<00:19,  8.43it/s]

100%|█████████████████████████████████▊| 42364/42525 [1:20:44<00:19,  8.14it/s]

100%|█████████████████████████████████▊| 42366/42525 [1:20:44<00:21,  7.32it/s]

100%|█████████████████████████████████▊| 42368/42525 [1:20:45<00:19,  8.22it/s]

100%|█████████████████████████████████▉| 42370/42525 [1:20:45<00:20,  7.51it/s]

100%|█████████████████████████████████▉| 42372/42525 [1:20:45<00:19,  7.71it/s]

100%|█████████████████████████████████▉| 42374/42525 [1:20:45<00:17,  8.51it/s]

100%|█████████████████████████████████▉| 42376/42525 [1:20:46<00:18,  8.07it/s]

100%|█████████████████████████████████▉| 42378/42525 [1:20:46<00:16,  8.76it/s]

100%|█████████████████████████████████▉| 42380/42525 [1:20:46<00:15,  9.14it/s]

100%|█████████████████████████████████▉| 42382/42525 [1:20:46<00:16,  8.86it/s]

100%|█████████████████████████████████▉| 42384/42525 [1:20:46<00:16,  8.57it/s]

100%|█████████████████████████████████▉| 42386/42525 [1:20:47<00:17,  8.09it/s]

100%|█████████████████████████████████▉| 42388/42525 [1:20:47<00:16,  8.19it/s]

100%|█████████████████████████████████▉| 42389/42525 [1:20:47<00:17,  7.69it/s]

100%|█████████████████████████████████▉| 42392/42525 [1:20:47<00:16,  7.95it/s]

100%|█████████████████████████████████▉| 42394/42525 [1:20:48<00:17,  7.41it/s]

100%|█████████████████████████████████▉| 42397/42525 [1:20:48<00:14,  8.73it/s]

100%|█████████████████████████████████▉| 42399/42525 [1:20:48<00:14,  8.72it/s]

100%|█████████████████████████████████▉| 42401/42525 [1:20:48<00:13,  8.87it/s]

100%|█████████████████████████████████▉| 42403/42525 [1:20:49<00:15,  7.76it/s]

100%|█████████████████████████████████▉| 42405/42525 [1:20:49<00:15,  7.73it/s]

100%|█████████████████████████████████▉| 42407/42525 [1:20:49<00:14,  8.00it/s]

100%|█████████████████████████████████▉| 42410/42525 [1:20:50<00:12,  8.94it/s]

100%|█████████████████████████████████▉| 42412/42525 [1:20:50<00:12,  8.79it/s]

100%|█████████████████████████████████▉| 42414/42525 [1:20:50<00:12,  8.77it/s]

100%|█████████████████████████████████▉| 42416/42525 [1:20:50<00:14,  7.78it/s]

100%|█████████████████████████████████▉| 42418/42525 [1:20:51<00:13,  7.95it/s]

100%|█████████████████████████████████▉| 42420/42525 [1:20:51<00:13,  7.53it/s]

100%|█████████████████████████████████▉| 42421/42525 [1:20:51<00:12,  8.02it/s]

100%|█████████████████████████████████▉| 42425/42525 [1:20:51<00:10,  9.16it/s]

100%|█████████████████████████████████▉| 42427/42525 [1:20:52<00:10,  9.13it/s]

100%|█████████████████████████████████▉| 42429/42525 [1:20:52<00:10,  9.05it/s]

100%|█████████████████████████████████▉| 42431/42525 [1:20:52<00:10,  8.74it/s]

100%|█████████████████████████████████▉| 42433/42525 [1:20:52<00:10,  8.97it/s]

100%|█████████████████████████████████▉| 42435/42525 [1:20:52<00:09,  9.32it/s]

100%|█████████████████████████████████▉| 42437/42525 [1:20:53<00:09,  9.21it/s]

100%|█████████████████████████████████▉| 42440/42525 [1:20:53<00:08,  9.47it/s]

100%|█████████████████████████████████▉| 42442/42525 [1:20:53<00:08,  9.67it/s]

100%|█████████████████████████████████▉| 42444/42525 [1:20:53<00:08,  9.11it/s]

100%|█████████████████████████████████▉| 42446/42525 [1:20:54<00:09,  8.01it/s]

100%|█████████████████████████████████▉| 42449/42525 [1:20:54<00:08,  8.72it/s]

100%|█████████████████████████████████▉| 42451/42525 [1:20:54<00:08,  9.21it/s]

100%|█████████████████████████████████▉| 42453/42525 [1:20:54<00:07,  9.24it/s]

100%|█████████████████████████████████▉| 42455/42525 [1:20:55<00:08,  8.73it/s]

100%|█████████████████████████████████▉| 42458/42525 [1:20:55<00:07,  8.46it/s]

100%|█████████████████████████████████▉| 42462/42525 [1:20:55<00:06,  9.33it/s]

100%|█████████████████████████████████▉| 42464/42525 [1:20:56<00:06,  8.88it/s]

100%|█████████████████████████████████▉| 42467/42525 [1:20:56<00:06,  9.50it/s]

100%|█████████████████████████████████▉| 42469/42525 [1:20:56<00:06,  8.45it/s]

100%|█████████████████████████████████▉| 42471/42525 [1:20:56<00:06,  8.63it/s]

100%|█████████████████████████████████▉| 42475/42525 [1:20:57<00:05,  9.65it/s]

100%|█████████████████████████████████▉| 42477/42525 [1:20:57<00:05,  9.17it/s]

100%|█████████████████████████████████▉| 42480/42525 [1:20:57<00:04,  9.68it/s]

100%|█████████████████████████████████▉| 42482/42525 [1:20:58<00:04,  9.24it/s]

100%|█████████████████████████████████▉| 42484/42525 [1:20:58<00:04,  9.44it/s]

100%|█████████████████████████████████▉| 42487/42525 [1:20:58<00:03,  9.59it/s]

100%|█████████████████████████████████▉| 42489/42525 [1:20:58<00:04,  8.23it/s]

100%|█████████████████████████████████▉| 42491/42525 [1:20:59<00:03,  8.51it/s]

100%|█████████████████████████████████▉| 42493/42525 [1:20:59<00:03,  8.62it/s]

100%|█████████████████████████████████▉| 42495/42525 [1:20:59<00:03,  8.43it/s]

100%|█████████████████████████████████▉| 42497/42525 [1:20:59<00:03,  8.16it/s]

100%|█████████████████████████████████▉| 42499/42525 [1:21:00<00:03,  8.32it/s]

100%|█████████████████████████████████▉| 42501/42525 [1:21:00<00:02,  8.35it/s]

100%|█████████████████████████████████▉| 42503/42525 [1:21:00<00:02,  8.24it/s]

100%|█████████████████████████████████▉| 42505/42525 [1:21:00<00:02,  8.56it/s]

100%|█████████████████████████████████▉| 42507/42525 [1:21:01<00:02,  7.95it/s]

100%|█████████████████████████████████▉| 42510/42525 [1:21:01<00:01,  8.15it/s]

100%|█████████████████████████████████▉| 42512/42525 [1:21:01<00:01,  8.14it/s]

100%|█████████████████████████████████▉| 42514/42525 [1:21:01<00:01,  7.72it/s]

100%|█████████████████████████████████▉| 42516/42525 [1:21:02<00:01,  7.64it/s]

100%|█████████████████████████████████▉| 42518/42525 [1:21:02<00:00,  7.91it/s]

100%|█████████████████████████████████▉| 42520/42525 [1:21:02<00:00,  8.76it/s]

100%|█████████████████████████████████▉| 42522/42525 [1:21:02<00:00,  8.73it/s]

100%|█████████████████████████████████▉| 42523/42525 [1:21:03<00:00,  8.81it/s]

100%|██████████████████████████████████| 42525/42525 [1:21:03<00:00,  6.86it/s]
  0%|                                                  | 0/788 [00:00<?, ?it/s]
  0%|                                          | 2/788 [00:00<00:42, 18.63it/s]

{'loss': '0', 'grad_norm': 'nan', 'learning_rate': '5.003e-10', 'epoch': '3'}

  1%|▏                                         | 4/788 [00:00<01:00, 12.87it/s]
  1%|▎                                         | 6/788 [00:00<01:06, 11.73it/s]

  1%|▍                                         | 8/788 [00:00<01:07, 11.58it/s]
  1%|▌                                        | 10/788 [00:00<01:01, 12.70it/s]

  2%|▌                                        | 12/788 [00:00<00:56, 13.68it/s]
  2%|▋                                        | 14/788 [00:01<00:59, 13.06it/s]

  2%|▊                                        | 16/788 [00:01<01:02, 12.39it/s]
  2%|▉                                        | 18/788 [00:01<01:06, 11.53it/s]

  3%|█                                        | 20/788 [00:01<01:12, 10.54it/s]
  3%|█▏                                       | 22/788 [00:01<01:12, 10.58it/s]

  3%|█▏                                       | 24/788 [00:02<01:07, 11.26it/s]
  3%|█▎                                       | 26/788 [00:02<01:06, 11.37it/s]

  4%|█▍                                       | 28/788 [00:02<01:06, 11.50it/s]
  4%|█▌                                       | 30/788 [00:02<01:03, 11.88it/s]

  4%|█▋                                       | 32/788 [00:02<01:04, 11.79it/s]
  4%|█▊                                       | 34/788 [00:02<01:04, 11.73it/s]

  5%|█▊                                       | 36/788 [00:03<01:06, 11.23it/s]
  5%|█▉                                       | 38/788 [00:03<00:58, 12.89it/s]

  5%|██                                       | 40/788 [00:03<00:58, 12.72it/s]
  5%|██▏                                      | 42/788 [00:03<00:59, 12.56it/s]

  6%|██▎                                      | 45/788 [00:03<00:54, 13.56it/s]

  6%|██▍                                      | 47/788 [00:03<01:01, 12.10it/s]
  6%|██▌                                      | 49/788 [00:04<00:59, 12.41it/s]

  7%|██▋                                      | 52/788 [00:04<00:50, 14.52it/s]
  7%|██▊                                      | 54/788 [00:04<00:53, 13.78it/s]

  7%|██▉                                      | 56/788 [00:04<00:51, 14.09it/s]
  7%|███                                      | 58/788 [00:04<00:53, 13.70it/s]

  8%|███                                      | 60/788 [00:04<00:54, 13.29it/s]
  8%|███▏                                     | 62/788 [00:04<00:57, 12.61it/s]

  8%|███▎                                     | 64/788 [00:05<01:01, 11.68it/s]
  8%|███▍                                     | 66/788 [00:05<01:00, 11.99it/s]

  9%|███▌                                     | 68/788 [00:05<01:00, 11.98it/s]

  9%|███▋                                     | 70/788 [00:05<01:04, 11.09it/s]
  9%|███▋                                     | 72/788 [00:05<01:01, 11.70it/s]

  9%|███▊                                     | 74/788 [00:06<01:05, 10.86it/s]
 10%|███▉                                     | 76/788 [00:06<01:00, 11.71it/s]

 10%|████                                     | 78/788 [00:06<01:03, 11.17it/s]
 10%|████▏                                    | 80/788 [00:06<01:04, 10.96it/s]

 10%|████▎                                    | 82/788 [00:06<01:07, 10.42it/s]
 11%|████▎                                    | 84/788 [00:06<01:03, 11.14it/s]

 11%|████▍                                    | 86/788 [00:07<01:02, 11.25it/s]
 11%|████▌                                    | 88/788 [00:07<01:00, 11.57it/s]

 11%|████▋                                    | 90/788 [00:07<00:57, 12.18it/s]

 12%|████▊                                    | 92/788 [00:07<01:02, 11.18it/s]

 12%|████▉                                    | 94/788 [00:07<01:05, 10.60it/s]
 12%|████▉                                    | 96/788 [00:08<01:00, 11.52it/s]

 12%|█████                                    | 98/788 [00:08<01:03, 10.95it/s]
 13%|█████▏                                  | 101/788 [00:08<00:54, 12.52it/s]

 13%|█████▏                                  | 103/788 [00:08<00:57, 11.88it/s]

 13%|█████▎                                  | 105/788 [00:08<01:01, 11.08it/s]
 14%|█████▍                                  | 107/788 [00:08<00:59, 11.51it/s]

 14%|█████▌                                  | 109/788 [00:09<00:57, 11.84it/s]
 14%|█████▋                                  | 111/788 [00:09<00:52, 12.95it/s]

 14%|█████▋                                  | 113/788 [00:09<00:50, 13.34it/s]

 15%|█████▊                                  | 115/788 [00:09<00:56, 11.81it/s]
 15%|█████▉                                  | 117/788 [00:09<00:57, 11.58it/s]

 15%|██████                                  | 119/788 [00:09<00:57, 11.70it/s]
 15%|██████▏                                 | 121/788 [00:10<00:57, 11.65it/s]

 16%|██████▏                                 | 123/788 [00:10<00:58, 11.40it/s]
 16%|██████▎                                 | 125/788 [00:10<00:52, 12.72it/s]

 16%|██████▍                                 | 127/788 [00:10<00:47, 14.03it/s]
 16%|██████▌                                 | 129/788 [00:10<00:43, 15.03it/s]

 17%|██████▋                                 | 131/788 [00:10<00:47, 13.94it/s]
 17%|██████▊                                 | 133/788 [00:10<00:47, 13.66it/s]

 17%|██████▊                                 | 135/788 [00:11<00:48, 13.53it/s]
 17%|██████▉                                 | 137/788 [00:11<00:48, 13.47it/s]

 18%|███████                                 | 139/788 [00:11<00:49, 13.18it/s]
 18%|███████▏                                | 141/788 [00:11<00:51, 12.59it/s]

 18%|███████▎                                | 143/788 [00:11<00:52, 12.35it/s]
 18%|███████▎                                | 145/788 [00:11<00:52, 12.25it/s]

 19%|███████▌                                | 148/788 [00:12<00:43, 14.69it/s]
 19%|███████▋                                | 151/788 [00:12<00:41, 15.51it/s]

 19%|███████▊                                | 153/788 [00:12<00:41, 15.21it/s]
 20%|███████▊                                | 155/788 [00:12<00:45, 13.83it/s]

 20%|███████▉                                | 157/788 [00:12<00:44, 14.29it/s]
 20%|████████                                | 159/788 [00:12<00:46, 13.38it/s]

 20%|████████▏                               | 161/788 [00:13<00:47, 13.11it/s]

 21%|████████▎                               | 163/788 [00:13<00:53, 11.76it/s]
 21%|████████▍                               | 165/788 [00:13<00:49, 12.62it/s]

 21%|████████▍                               | 167/788 [00:13<00:55, 11.25it/s]
 21%|████████▌                               | 169/788 [00:13<00:54, 11.28it/s]

 22%|████████▋                               | 171/788 [00:13<00:51, 11.99it/s]
 22%|████████▊                               | 173/788 [00:14<00:49, 12.52it/s]

 22%|████████▉                               | 175/788 [00:14<00:50, 12.05it/s]
 22%|████████▉                               | 177/788 [00:14<00:52, 11.61it/s]

 23%|█████████                               | 179/788 [00:14<00:53, 11.39it/s]
 23%|█████████▏                              | 181/788 [00:14<00:55, 10.94it/s]

 23%|█████████▎                              | 183/788 [00:14<00:54, 11.17it/s]
 23%|█████████▍                              | 185/788 [00:15<00:54, 11.16it/s]

 24%|█████████▍                              | 187/788 [00:15<00:52, 11.35it/s]
 24%|█████████▌                              | 189/788 [00:15<00:50, 11.81it/s]

 24%|█████████▋                              | 191/788 [00:15<00:54, 11.04it/s]
 24%|█████████▊                              | 193/788 [00:15<00:52, 11.34it/s]

 25%|█████████▉                              | 195/788 [00:15<00:46, 12.79it/s]
 25%|██████████                              | 197/788 [00:16<00:43, 13.51it/s]

 25%|██████████                              | 199/788 [00:16<00:49, 11.99it/s]
 26%|██████████▏                             | 201/788 [00:16<00:47, 12.28it/s]

 26%|██████████▎                             | 203/788 [00:16<00:50, 11.48it/s]
 26%|██████████▍                             | 205/788 [00:16<00:48, 12.08it/s]

 26%|██████████▌                             | 207/788 [00:16<00:43, 13.44it/s]
 27%|██████████▌                             | 209/788 [00:17<00:46, 12.52it/s]

 27%|██████████▋                             | 211/788 [00:17<00:47, 12.19it/s]
 27%|██████████▊                             | 213/788 [00:17<00:45, 12.55it/s]

 27%|██████████▉                             | 215/788 [00:17<00:48, 11.93it/s]
 28%|███████████                             | 217/788 [00:17<00:46, 12.17it/s]

 28%|███████████                             | 219/788 [00:17<00:42, 13.50it/s]
 28%|███████████▏                            | 221/788 [00:18<00:45, 12.38it/s]

 28%|███████████▎                            | 223/788 [00:18<00:44, 12.81it/s]
 29%|███████████▍                            | 225/788 [00:18<00:43, 13.00it/s]

 29%|███████████▌                            | 227/788 [00:18<00:41, 13.53it/s]
 29%|███████████▌                            | 229/788 [00:18<00:38, 14.44it/s]

 29%|███████████▋                            | 231/788 [00:18<00:40, 13.72it/s]
 30%|███████████▊                            | 233/788 [00:18<00:40, 13.82it/s]

 30%|███████████▉                            | 235/788 [00:19<00:41, 13.38it/s]
 30%|████████████                            | 237/788 [00:19<00:41, 13.20it/s]

 30%|████████████▏                           | 239/788 [00:19<00:42, 13.06it/s]
 31%|████████████▏                           | 241/788 [00:19<00:41, 13.22it/s]

 31%|████████████▎                           | 243/788 [00:19<00:42, 12.97it/s]
 31%|████████████▍                           | 245/788 [00:19<00:45, 11.95it/s]

 31%|████████████▌                           | 247/788 [00:20<00:43, 12.30it/s]

 32%|████████████▋                           | 249/788 [00:20<00:47, 11.30it/s]
 32%|████████████▋                           | 251/788 [00:20<00:46, 11.61it/s]

 32%|████████████▊                           | 253/788 [00:20<00:45, 11.69it/s]
 32%|████████████▉                           | 255/788 [00:20<00:43, 12.31it/s]

 33%|█████████████                           | 257/788 [00:20<00:42, 12.49it/s]
 33%|█████████████▏                          | 259/788 [00:21<00:44, 11.79it/s]

 33%|█████████████▏                          | 261/788 [00:21<00:39, 13.20it/s]

 33%|█████████████▎                          | 263/788 [00:21<00:44, 11.69it/s]
 34%|█████████████▍                          | 265/788 [00:21<00:43, 12.13it/s]

 34%|█████████████▌                          | 267/788 [00:21<00:39, 13.06it/s]

 34%|█████████████▋                          | 269/788 [00:21<00:44, 11.59it/s]
 34%|█████████████▊                          | 271/788 [00:22<00:43, 11.79it/s]

 35%|█████████████▊                          | 273/788 [00:22<00:45, 11.23it/s]
 35%|█████████████▉                          | 275/788 [00:22<00:46, 11.08it/s]

 35%|██████████████                          | 277/788 [00:22<00:48, 10.46it/s]
 35%|██████████████▏                         | 279/788 [00:22<00:47, 10.74it/s]

 36%|██████████████▎                         | 281/788 [00:22<00:44, 11.38it/s]
 36%|██████████████▎                         | 283/788 [00:23<00:44, 11.25it/s]

 36%|██████████████▍                         | 285/788 [00:23<00:44, 11.35it/s]
 36%|██████████████▌                         | 287/788 [00:23<00:39, 12.54it/s]

 37%|██████████████▋                         | 289/788 [00:23<00:39, 12.60it/s]
 37%|██████████████▊                         | 291/788 [00:23<00:35, 13.94it/s]

 37%|██████████████▊                         | 293/788 [00:23<00:35, 14.09it/s]
 37%|██████████████▉                         | 295/788 [00:24<00:36, 13.49it/s]

 38%|███████████████                         | 297/788 [00:24<00:36, 13.34it/s]
 38%|███████████████▏                        | 299/788 [00:24<00:38, 12.79it/s]

 38%|███████████████▎                        | 301/788 [00:24<00:37, 13.03it/s]
 38%|███████████████▍                        | 303/788 [00:24<00:37, 13.08it/s]

 39%|███████████████▍                        | 305/788 [00:24<00:37, 12.76it/s]
 39%|███████████████▌                        | 307/788 [00:24<00:37, 12.70it/s]

 39%|███████████████▋                        | 309/788 [00:25<00:37, 12.79it/s]
 39%|███████████████▊                        | 311/788 [00:25<00:38, 12.45it/s]

 40%|███████████████▉                        | 313/788 [00:25<00:38, 12.27it/s]
 40%|███████████████▉                        | 315/788 [00:25<00:36, 12.99it/s]

 40%|████████████████                        | 317/788 [00:25<00:36, 13.00it/s]
 40%|████████████████▏                       | 319/788 [00:25<00:38, 12.06it/s]

 41%|████████████████▎                       | 321/788 [00:26<00:38, 11.99it/s]
 41%|████████████████▍                       | 323/788 [00:26<00:37, 12.39it/s]

 41%|████████████████▍                       | 325/788 [00:26<00:41, 11.26it/s]
 41%|████████████████▌                       | 327/788 [00:26<00:37, 12.14it/s]

 42%|████████████████▋                       | 329/788 [00:26<00:38, 11.91it/s]
 42%|████████████████▊                       | 331/788 [00:26<00:37, 12.22it/s]

 42%|████████████████▉                       | 333/788 [00:27<00:36, 12.44it/s]
 43%|█████████████████                       | 335/788 [00:27<00:32, 13.81it/s]

 43%|█████████████████                       | 337/788 [00:27<00:33, 13.46it/s]

 43%|█████████████████▏                      | 339/788 [00:27<00:37, 12.12it/s]
 43%|█████████████████▎                      | 341/788 [00:27<00:37, 11.82it/s]

 44%|█████████████████▍                      | 343/788 [00:27<00:38, 11.59it/s]

 44%|█████████████████▌                      | 345/788 [00:28<00:41, 10.74it/s]

 44%|█████████████████▌                      | 347/788 [00:28<00:42, 10.33it/s]
 44%|█████████████████▋                      | 349/788 [00:28<00:39, 11.10it/s]

 45%|█████████████████▊                      | 351/788 [00:28<00:37, 11.55it/s]
 45%|█████████████████▉                      | 353/788 [00:28<00:36, 11.85it/s]

 45%|██████████████████                      | 355/788 [00:28<00:35, 12.33it/s]
 45%|██████████████████                      | 357/788 [00:29<00:35, 12.18it/s]

 46%|██████████████████▏                     | 359/788 [00:29<00:37, 11.51it/s]
 46%|██████████████████▎                     | 361/788 [00:29<00:33, 12.74it/s]

 46%|██████████████████▍                     | 363/788 [00:29<00:29, 14.18it/s]
 46%|██████████████████▌                     | 365/788 [00:29<00:31, 13.62it/s]

 47%|██████████████████▋                     | 367/788 [00:29<00:28, 14.63it/s]
 47%|██████████████████▋                     | 369/788 [00:30<00:31, 13.29it/s]

 47%|██████████████████▊                     | 371/788 [00:30<00:29, 14.27it/s]
 47%|██████████████████▉                     | 373/788 [00:30<00:28, 14.34it/s]

 48%|███████████████████                     | 376/788 [00:30<00:28, 14.60it/s]
 48%|███████████████████▏                    | 379/788 [00:30<00:26, 15.51it/s]

 48%|███████████████████▎                    | 381/788 [00:30<00:27, 14.99it/s]
 49%|███████████████████▍                    | 383/788 [00:30<00:28, 14.40it/s]

 49%|███████████████████▌                    | 385/788 [00:31<00:28, 14.18it/s]
 49%|███████████████████▋                    | 387/788 [00:31<00:31, 12.76it/s]

 49%|███████████████████▋                    | 389/788 [00:31<00:30, 12.93it/s]
 50%|███████████████████▊                    | 391/788 [00:31<00:32, 12.19it/s]

 50%|███████████████████▉                    | 393/788 [00:31<00:32, 12.34it/s]
 50%|████████████████████                    | 395/788 [00:31<00:30, 12.73it/s]

 50%|████████████████████▏                   | 397/788 [00:32<00:28, 13.68it/s]
 51%|████████████████████▎                   | 399/788 [00:32<00:30, 12.79it/s]

 51%|████████████████████▎                   | 401/788 [00:32<00:29, 13.10it/s]
 51%|████████████████████▍                   | 403/788 [00:32<00:28, 13.44it/s]

 51%|████████████████████▌                   | 405/788 [00:32<00:29, 12.85it/s]
 52%|████████████████████▋                   | 407/788 [00:32<00:27, 13.87it/s]

 52%|████████████████████▊                   | 409/788 [00:32<00:28, 13.33it/s]
 52%|████████████████████▊                   | 411/788 [00:33<00:25, 14.81it/s]

 52%|████████████████████▉                   | 413/788 [00:33<00:27, 13.40it/s]
 53%|█████████████████████                   | 415/788 [00:33<00:25, 14.44it/s]

 53%|█████████████████████▏                  | 417/788 [00:33<00:29, 12.65it/s]

 53%|█████████████████████▎                  | 419/788 [00:33<00:31, 11.65it/s]

 53%|█████████████████████▎                  | 421/788 [00:33<00:33, 10.82it/s]
 54%|█████████████████████▍                  | 423/788 [00:34<00:32, 11.22it/s]

 54%|█████████████████████▌                  | 425/788 [00:34<00:32, 11.03it/s]
 54%|█████████████████████▋                  | 427/788 [00:34<00:31, 11.31it/s]

 54%|█████████████████████▊                  | 429/788 [00:34<00:30, 11.72it/s]
 55%|█████████████████████▉                  | 431/788 [00:34<00:27, 13.02it/s]

 55%|█████████████████████▉                  | 433/788 [00:34<00:25, 13.68it/s]
 55%|██████████████████████                  | 435/788 [00:35<00:28, 12.45it/s]

 55%|██████████████████████▏                 | 437/788 [00:35<00:27, 12.75it/s]
 56%|██████████████████████▎                 | 439/788 [00:35<00:28, 12.46it/s]

 56%|██████████████████████▍                 | 441/788 [00:35<00:27, 12.84it/s]
 56%|██████████████████████▍                 | 443/788 [00:35<00:27, 12.72it/s]

 56%|██████████████████████▌                 | 445/788 [00:35<00:27, 12.38it/s]
 57%|██████████████████████▋                 | 447/788 [00:36<00:28, 12.09it/s]

 57%|██████████████████████▊                 | 449/788 [00:36<00:26, 12.83it/s]
 57%|██████████████████████▉                 | 451/788 [00:36<00:26, 12.54it/s]

 57%|██████████████████████▉                 | 453/788 [00:36<00:26, 12.71it/s]
 58%|███████████████████████                 | 455/788 [00:36<00:25, 13.04it/s]

 58%|███████████████████████▏                | 457/788 [00:36<00:24, 13.46it/s]
 58%|███████████████████████▎                | 459/788 [00:36<00:25, 13.00it/s]

 59%|███████████████████████▍                | 461/788 [00:37<00:25, 12.72it/s]
 59%|███████████████████████▌                | 463/788 [00:37<00:26, 12.06it/s]

 59%|███████████████████████▋                | 466/788 [00:37<00:24, 12.96it/s]
 59%|███████████████████████▊                | 468/788 [00:37<00:25, 12.32it/s]

 60%|███████████████████████▊                | 470/788 [00:37<00:27, 11.38it/s]
 60%|███████████████████████▉                | 472/788 [00:38<00:27, 11.45it/s]

 60%|████████████████████████                | 474/788 [00:38<00:26, 11.69it/s]
 60%|████████████████████████▏               | 476/788 [00:38<00:26, 11.95it/s]

 61%|████████████████████████▎               | 478/788 [00:38<00:24, 12.64it/s]
 61%|████████████████████████▎               | 480/788 [00:38<00:24, 12.60it/s]

 61%|████████████████████████▍               | 482/788 [00:38<00:25, 11.97it/s]
 61%|████████████████████████▌               | 484/788 [00:39<00:25, 11.72it/s]

 62%|████████████████████████▋               | 486/788 [00:39<00:25, 11.73it/s]
 62%|████████████████████████▊               | 488/788 [00:39<00:25, 11.68it/s]

 62%|████████████████████████▊               | 490/788 [00:39<00:27, 10.93it/s]
 62%|████████████████████████▉               | 492/788 [00:39<00:25, 11.42it/s]

 63%|█████████████████████████               | 494/788 [00:39<00:25, 11.48it/s]
 63%|█████████████████████████▏              | 496/788 [00:40<00:23, 12.39it/s]

 63%|█████████████████████████▎              | 498/788 [00:40<00:21, 13.53it/s]
 63%|█████████████████████████▍              | 500/788 [00:40<00:20, 14.33it/s]

 64%|█████████████████████████▍              | 502/788 [00:40<00:21, 13.55it/s]
 64%|█████████████████████████▌              | 504/788 [00:40<00:22, 12.69it/s]

 64%|█████████████████████████▋              | 506/788 [00:40<00:19, 14.19it/s]
 64%|█████████████████████████▊              | 508/788 [00:40<00:19, 14.14it/s]

 65%|█████████████████████████▉              | 510/788 [00:41<00:21, 13.17it/s]
 65%|█████████████████████████▉              | 512/788 [00:41<00:18, 14.54it/s]

 65%|██████████████████████████              | 514/788 [00:41<00:19, 14.40it/s]
 65%|██████████████████████████▏             | 516/788 [00:41<00:18, 14.74it/s]

 66%|██████████████████████████▎             | 518/788 [00:41<00:18, 14.44it/s]
 66%|██████████████████████████▍             | 520/788 [00:41<00:18, 14.20it/s]

 66%|██████████████████████████▍             | 522/788 [00:41<00:19, 13.93it/s]
 66%|██████████████████████████▌             | 524/788 [00:42<00:18, 14.14it/s]

 67%|██████████████████████████▋             | 526/788 [00:42<00:20, 12.75it/s]
 67%|██████████████████████████▊             | 528/788 [00:42<00:20, 12.99it/s]

 67%|██████████████████████████▉             | 530/788 [00:42<00:20, 12.54it/s]
 68%|███████████████████████████             | 532/788 [00:42<00:19, 12.89it/s]

 68%|███████████████████████████             | 534/788 [00:42<00:20, 12.35it/s]
 68%|███████████████████████████▏            | 536/788 [00:43<00:20, 12.31it/s]

 68%|███████████████████████████▎            | 538/788 [00:43<00:22, 11.23it/s]

 69%|███████████████████████████▍            | 540/788 [00:43<00:23, 10.67it/s]
 69%|███████████████████████████▌            | 542/788 [00:43<00:23, 10.46it/s]

 69%|███████████████████████████▌            | 544/788 [00:43<00:24, 10.12it/s]
 69%|███████████████████████████▋            | 546/788 [00:44<00:22, 10.85it/s]

 70%|███████████████████████████▊            | 548/788 [00:44<00:22, 10.90it/s]
 70%|███████████████████████████▉            | 550/788 [00:44<00:20, 11.45it/s]

 70%|████████████████████████████            | 552/788 [00:44<00:18, 12.58it/s]
 70%|████████████████████████████            | 554/788 [00:44<00:18, 12.82it/s]

 71%|████████████████████████████▏           | 556/788 [00:44<00:19, 11.97it/s]
 71%|████████████████████████████▎           | 558/788 [00:44<00:18, 12.69it/s]

 71%|████████████████████████████▍           | 560/788 [00:45<00:17, 13.28it/s]
 71%|████████████████████████████▌           | 563/788 [00:45<00:14, 15.09it/s]

 72%|████████████████████████████▋           | 565/788 [00:45<00:16, 13.49it/s]
 72%|████████████████████████████▊           | 567/788 [00:45<00:17, 12.30it/s]

 72%|████████████████████████████▉           | 569/788 [00:45<00:16, 13.41it/s]
 72%|████████████████████████████▉           | 571/788 [00:45<00:16, 12.86it/s]

 73%|█████████████████████████████           | 573/788 [00:46<00:18, 11.57it/s]
 73%|█████████████████████████████▏          | 575/788 [00:46<00:17, 11.86it/s]

 73%|█████████████████████████████▎          | 577/788 [00:46<00:17, 11.98it/s]
 73%|█████████████████████████████▍          | 579/788 [00:46<00:16, 12.31it/s]

 74%|█████████████████████████████▍          | 581/788 [00:46<00:16, 12.53it/s]
 74%|█████████████████████████████▌          | 583/788 [00:46<00:17, 11.79it/s]

 74%|█████████████████████████████▋          | 585/788 [00:47<00:16, 12.07it/s]
 74%|█████████████████████████████▊          | 587/788 [00:47<00:17, 11.56it/s]

 75%|█████████████████████████████▉          | 589/788 [00:47<00:18, 10.97it/s]
 75%|██████████████████████████████          | 591/788 [00:47<00:16, 12.23it/s]

 75%|██████████████████████████████          | 593/788 [00:47<00:15, 12.27it/s]
 76%|██████████████████████████████▏         | 595/788 [00:47<00:16, 11.68it/s]

 76%|██████████████████████████████▎         | 597/788 [00:48<00:15, 12.19it/s]
 76%|██████████████████████████████▍         | 599/788 [00:48<00:15, 12.57it/s]

 76%|██████████████████████████████▌         | 601/788 [00:48<00:14, 12.99it/s]
 77%|██████████████████████████████▌         | 603/788 [00:48<00:14, 12.88it/s]

 77%|██████████████████████████████▋         | 605/788 [00:48<00:13, 13.24it/s]
 77%|██████████████████████████████▊         | 607/788 [00:48<00:12, 14.61it/s]

 77%|██████████████████████████████▉         | 609/788 [00:49<00:14, 12.49it/s]
 78%|███████████████████████████████         | 611/788 [00:49<00:14, 12.17it/s]

 78%|███████████████████████████████         | 613/788 [00:49<00:13, 13.15it/s]
 78%|███████████████████████████████▏        | 615/788 [00:49<00:12, 13.48it/s]

 78%|███████████████████████████████▎        | 617/788 [00:49<00:13, 12.92it/s]
 79%|███████████████████████████████▍        | 619/788 [00:49<00:12, 13.32it/s]

 79%|███████████████████████████████▌        | 621/788 [00:49<00:12, 13.32it/s]
 79%|███████████████████████████████▌        | 623/788 [00:50<00:11, 14.41it/s]

 79%|███████████████████████████████▋        | 625/788 [00:50<00:13, 12.45it/s]

 80%|███████████████████████████████▊        | 627/788 [00:50<00:14, 11.49it/s]

 80%|███████████████████████████████▉        | 629/788 [00:50<00:14, 10.72it/s]

 80%|████████████████████████████████        | 631/788 [00:50<00:15, 10.25it/s]
 80%|████████████████████████████████▏       | 633/788 [00:51<00:14, 10.81it/s]

 81%|████████████████████████████████▏       | 635/788 [00:51<00:12, 12.16it/s]
 81%|████████████████████████████████▎       | 637/788 [00:51<00:12, 12.41it/s]

 81%|████████████████████████████████▍       | 639/788 [00:51<00:12, 11.59it/s]
 81%|████████████████████████████████▌       | 642/788 [00:51<00:10, 13.62it/s]

 82%|████████████████████████████████▋       | 644/788 [00:51<00:11, 13.05it/s]
 82%|████████████████████████████████▊       | 646/788 [00:52<00:11, 12.58it/s]

 82%|████████████████████████████████▉       | 648/788 [00:52<00:10, 13.12it/s]
 83%|█████████████████████████████████       | 651/788 [00:52<00:09, 14.79it/s]

 83%|█████████████████████████████████▏      | 653/788 [00:52<00:09, 13.66it/s]
 83%|█████████████████████████████████▏      | 655/788 [00:52<00:10, 12.44it/s]

 83%|█████████████████████████████████▎      | 657/788 [00:52<00:10, 12.21it/s]
 84%|█████████████████████████████████▍      | 659/788 [00:53<00:10, 12.06it/s]

 84%|█████████████████████████████████▌      | 661/788 [00:53<00:10, 12.23it/s]
 84%|█████████████████████████████████▋      | 663/788 [00:53<00:10, 12.19it/s]

 84%|█████████████████████████████████▊      | 665/788 [00:53<00:09, 12.30it/s]

 85%|█████████████████████████████████▊      | 667/788 [00:53<00:10, 11.24it/s]
 85%|█████████████████████████████████▉      | 669/788 [00:53<00:10, 11.80it/s]

 85%|██████████████████████████████████      | 671/788 [00:54<00:10, 11.62it/s]
 85%|██████████████████████████████████▏     | 673/788 [00:54<00:09, 12.02it/s]

 86%|██████████████████████████████████▎     | 675/788 [00:54<00:09, 12.28it/s]
 86%|██████████████████████████████████▎     | 677/788 [00:54<00:08, 13.50it/s]

 86%|██████████████████████████████████▍     | 679/788 [00:54<00:09, 12.01it/s]
 86%|██████████████████████████████████▌     | 681/788 [00:54<00:08, 12.09it/s]

 87%|██████████████████████████████████▋     | 683/788 [00:54<00:08, 13.08it/s]
 87%|██████████████████████████████████▊     | 685/788 [00:55<00:08, 12.60it/s]

 87%|██████████████████████████████████▊     | 687/788 [00:55<00:08, 11.51it/s]
 87%|██████████████████████████████████▉     | 689/788 [00:55<00:08, 11.96it/s]

 88%|███████████████████████████████████     | 691/788 [00:55<00:08, 11.08it/s]
 88%|███████████████████████████████████▏    | 693/788 [00:55<00:07, 12.44it/s]

 88%|███████████████████████████████████▎    | 695/788 [00:55<00:07, 12.80it/s]
 88%|███████████████████████████████████▍    | 697/788 [00:56<00:07, 12.49it/s]

 89%|███████████████████████████████████▍    | 699/788 [00:56<00:06, 12.84it/s]
 89%|███████████████████████████████████▌    | 701/788 [00:56<00:07, 12.24it/s]

 89%|███████████████████████████████████▋    | 703/788 [00:56<00:07, 11.60it/s]
 89%|███████████████████████████████████▊    | 705/788 [00:56<00:07, 11.07it/s]

 90%|███████████████████████████████████▉    | 707/788 [00:57<00:07, 10.98it/s]
 90%|███████████████████████████████████▉    | 709/788 [00:57<00:06, 11.67it/s]

 90%|████████████████████████████████████    | 711/788 [00:57<00:06, 11.45it/s]
 90%|████████████████████████████████████▏   | 713/788 [00:57<00:06, 11.76it/s]

 91%|████████████████████████████████████▎   | 715/788 [00:57<00:05, 13.11it/s]
 91%|████████████████████████████████████▍   | 717/788 [00:57<00:05, 14.09it/s]

 91%|████████████████████████████████████▍   | 719/788 [00:57<00:04, 14.09it/s]
 91%|████████████████████████████████████▌   | 721/788 [00:58<00:05, 12.68it/s]

 92%|████████████████████████████████████▋   | 723/788 [00:58<00:05, 11.51it/s]
 92%|████████████████████████████████████▊   | 725/788 [00:58<00:05, 11.35it/s]

 92%|████████████████████████████████████▉   | 727/788 [00:58<00:05, 11.25it/s]
 93%|█████████████████████████████████████   | 729/788 [00:58<00:05, 10.86it/s]

 93%|█████████████████████████████████████   | 731/788 [00:59<00:05, 10.84it/s]
 93%|█████████████████████████████████████▏  | 733/788 [00:59<00:04, 11.78it/s]

 93%|█████████████████████████████████████▎  | 735/788 [00:59<00:04, 11.17it/s]

 94%|█████████████████████████████████████▍  | 737/788 [00:59<00:04, 10.66it/s]
 94%|█████████████████████████████████████▌  | 739/788 [00:59<00:04, 11.06it/s]

 94%|█████████████████████████████████████▌  | 741/788 [00:59<00:03, 12.29it/s]
 94%|█████████████████████████████████████▋  | 743/788 [01:00<00:03, 12.86it/s]

 95%|█████████████████████████████████████▊  | 745/788 [01:00<00:03, 13.42it/s]
 95%|█████████████████████████████████████▉  | 747/788 [01:00<00:03, 12.89it/s]

 95%|██████████████████████████████████████  | 749/788 [01:00<00:03, 12.12it/s]
 95%|██████████████████████████████████████  | 751/788 [01:00<00:03, 11.62it/s]

 96%|██████████████████████████████████████▏ | 753/788 [01:00<00:03, 10.90it/s]
 96%|██████████████████████████████████████▎ | 755/788 [01:01<00:02, 11.54it/s]

 96%|██████████████████████████████████████▍ | 757/788 [01:01<00:02, 11.37it/s]
 96%|██████████████████████████████████████▌ | 759/788 [01:01<00:02, 11.63it/s]

 97%|██████████████████████████████████████▋ | 761/788 [01:01<00:02, 12.01it/s]
 97%|██████████████████████████████████████▋ | 763/788 [01:01<00:01, 13.58it/s]

 97%|██████████████████████████████████████▊ | 765/788 [01:01<00:01, 14.98it/s]

 97%|██████████████████████████████████████▉ | 767/788 [01:01<00:01, 12.98it/s]
 98%|███████████████████████████████████████ | 769/788 [01:02<00:01, 13.57it/s]

 98%|███████████████████████████████████████▏| 771/788 [01:02<00:01, 12.90it/s]
 98%|███████████████████████████████████████▏| 773/788 [01:02<00:01, 13.41it/s]

 98%|███████████████████████████████████████▎| 775/788 [01:02<00:00, 13.76it/s]
 99%|███████████████████████████████████████▍| 777/788 [01:02<00:00, 13.02it/s]

 99%|███████████████████████████████████████▌| 779/788 [01:02<00:00, 14.47it/s]
 99%|███████████████████████████████████████▋| 781/788 [01:02<00:00, 14.10it/s]

 99%|███████████████████████████████████████▋| 783/788 [01:03<00:00, 14.33it/s]
100%|███████████████████████████████████████▊| 785/788 [01:03<00:00, 14.19it/s]

100%|██████████████████████████████████| 42525/42525 [1:22:06<00:00,  6.86it/s]
100%|████████████████████████████████████████| 788/788 [01:03<00:00, 14.00it/s]

Writing model shards:   0%|                              | 0/1 [00:00<?, ?it/s]

{'eval_loss': 'nan', 'eval_accuracy': '0.2', 'eval_macro_f1': '0.06667', 'eval_mae': '2', 'eval_cil_score': '0.5', 'eval_quadratic_weighted_kappa': '0', 'eval_runtime': '63.55', 'eval_samples_per_second': '396.6', 'eval_steps_per_second': '12.4', 'epoch': '3'}

Writing model shards: 100%|██████████████████████| 1/1 [00:00<00:00,  1.17it/s]

100%|██████████████████████████████████| 42525/42525 [1:22:09<00:00,  6.86it/s]

100%|██████████████████████████████████| 42525/42525 [1:22:09<00:00,  8.63it/s]
  0%|                                          | 2/788 [00:00<00:41, 18.72it/s]

{'train_runtime': '4929', 'train_samples_per_second': '138', 'train_steps_per_second': '8.627', 'train_loss': '0.5383', 'epoch': '3'}

  1%|▎                                         | 6/788 [00:00<01:06, 11.70it/s]

  1%|▌                                        | 10/788 [00:00<01:01, 12.73it/s]

  2%|▋                                        | 14/788 [00:01<00:58, 13.30it/s]

  2%|▊                                        | 16/788 [00:01<01:01, 12.59it/s]

  2%|▉                                        | 18/788 [00:01<01:06, 11.62it/s]

  3%|█▏                                       | 22/788 [00:01<01:12, 10.61it/s]

  3%|█▎                                       | 26/788 [00:02<01:06, 11.41it/s]

  4%|█▌                                       | 30/788 [00:02<01:02, 12.12it/s]

  4%|█▊                                       | 34/788 [00:02<01:02, 12.04it/s]

  5%|█▉                                       | 38/788 [00:03<00:58, 12.86it/s]

  5%|██▏                                      | 42/788 [00:03<00:59, 12.49it/s]

  6%|██▎                                      | 45/788 [00:03<00:54, 13.59it/s]

  6%|██▌                                      | 49/788 [00:04<00:59, 12.35it/s]

  7%|██▊                                      | 54/788 [00:04<00:53, 13.68it/s]

  7%|███                                      | 58/788 [00:04<00:53, 13.62it/s]

  8%|███▏                                     | 62/788 [00:04<00:57, 12.58it/s]

  8%|███▍                                     | 66/788 [00:05<01:00, 11.91it/s]

  9%|███▌                                     | 68/788 [00:05<01:00, 11.90it/s]

  9%|███▋                                     | 72/788 [00:05<01:01, 11.68it/s]

 10%|███▉                                     | 76/788 [00:06<01:00, 11.73it/s]

 10%|████▏                                    | 80/788 [00:06<01:03, 11.11it/s]

 11%|████▎                                    | 84/788 [00:06<01:02, 11.20it/s]

 11%|████▌                                    | 88/788 [00:07<01:00, 11.57it/s]

 11%|████▋                                    | 90/788 [00:07<00:56, 12.28it/s]

 12%|████▊                                    | 92/788 [00:07<01:01, 11.27it/s]

 12%|████▉                                    | 96/788 [00:07<00:59, 11.69it/s]

 13%|█████▏                                  | 101/788 [00:08<00:54, 12.64it/s]

 13%|█████▏                                  | 103/788 [00:08<00:57, 11.97it/s]

 14%|█████▍                                  | 107/788 [00:08<00:58, 11.58it/s]

 14%|█████▋                                  | 111/788 [00:09<00:52, 12.86it/s]

 14%|█████▋                                  | 113/788 [00:09<00:51, 13.17it/s]

 15%|█████▉                                  | 117/788 [00:09<00:58, 11.53it/s]

 15%|██████▏                                 | 121/788 [00:10<00:57, 11.64it/s]

 16%|██████▎                                 | 125/788 [00:10<00:52, 12.71it/s]

 16%|██████▌                                 | 129/788 [00:10<00:43, 15.11it/s]

 17%|██████▊                                 | 133/788 [00:10<00:47, 13.69it/s]

 17%|██████▉                                 | 137/788 [00:11<00:47, 13.76it/s]

 18%|███████▏                                | 141/788 [00:11<00:50, 12.79it/s]

 18%|███████▎                                | 145/788 [00:11<00:51, 12.57it/s]

 19%|███████▋                                | 151/788 [00:12<00:39, 15.97it/s]

 20%|███████▊                                | 155/788 [00:12<00:43, 14.39it/s]

 20%|████████                                | 159/788 [00:12<00:46, 13.59it/s]

 20%|████████▏                               | 161/788 [00:12<00:46, 13.44it/s]

 21%|████████▍                               | 165/788 [00:13<00:48, 12.76it/s]

 21%|████████▌                               | 169/788 [00:13<00:53, 11.47it/s]

 22%|████████▊                               | 173/788 [00:13<00:49, 12.52it/s]

 22%|████████▉                               | 177/788 [00:14<00:52, 11.57it/s]

 23%|█████████                               | 179/788 [00:14<00:53, 11.34it/s]

 23%|█████████▎                              | 183/788 [00:14<00:55, 11.00it/s]

 24%|█████████▍                              | 187/788 [00:15<00:54, 11.12it/s]

 24%|█████████▌                              | 189/788 [00:15<00:52, 11.45it/s]

 24%|█████████▊                              | 193/788 [00:15<00:53, 11.06it/s]

 25%|██████████                              | 197/788 [00:16<00:45, 13.12it/s]

 26%|██████████▏                             | 201/788 [00:16<00:48, 11.98it/s]

 26%|██████████▍                             | 205/788 [00:16<00:49, 11.88it/s]

 27%|██████████▌                             | 209/788 [00:17<00:47, 12.29it/s]

 27%|██████████▊                             | 213/788 [00:17<00:46, 12.45it/s]

 28%|███████████                             | 217/788 [00:17<00:47, 12.08it/s]

 28%|███████████▏                            | 221/788 [00:18<00:45, 12.43it/s]

 29%|███████████▍                            | 225/788 [00:18<00:42, 13.33it/s]

 29%|███████████▌                            | 229/788 [00:18<00:38, 14.57it/s]

 30%|███████████▊                            | 233/788 [00:18<00:39, 13.97it/s]

 30%|████████████                            | 237/788 [00:19<00:41, 13.27it/s]

 31%|████████████▏                           | 241/788 [00:19<00:40, 13.34it/s]

 31%|████████████▍                           | 245/788 [00:19<00:45, 11.94it/s]

 31%|████████████▌                           | 247/788 [00:19<00:44, 12.28it/s]

 32%|████████████▋                           | 251/788 [00:20<00:46, 11.67it/s]

 32%|████████████▉                           | 255/788 [00:20<00:42, 12.52it/s]

 33%|█████████████▏                          | 259/788 [00:21<00:44, 11.90it/s]

 33%|█████████████▏                          | 261/788 [00:21<00:39, 13.33it/s]

 34%|█████████████▍                          | 265/788 [00:21<00:42, 12.27it/s]

 34%|█████████████▌                          | 267/788 [00:21<00:39, 13.25it/s]

 34%|█████████████▊                          | 271/788 [00:21<00:43, 11.93it/s]

 35%|█████████████▉                          | 275/788 [00:22<00:45, 11.18it/s]

 35%|██████████████▏                         | 279/788 [00:22<00:46, 10.83it/s]

 36%|██████████████▎                         | 283/788 [00:23<00:44, 11.26it/s]

 36%|██████████████▌                         | 287/788 [00:23<00:40, 12.43it/s]

 37%|██████████████▊                         | 291/788 [00:23<00:36, 13.78it/s]

 37%|██████████████▉                         | 295/788 [00:23<00:36, 13.62it/s]

 38%|███████████████▏                        | 299/788 [00:24<00:38, 12.86it/s]

 38%|███████████████▍                        | 303/788 [00:24<00:36, 13.20it/s]

 39%|███████████████▌                        | 307/788 [00:24<00:37, 12.93it/s]

 39%|███████████████▊                        | 311/788 [00:25<00:37, 12.77it/s]

 40%|███████████████▉                        | 315/788 [00:25<00:35, 13.19it/s]

 40%|████████████████▏                       | 319/788 [00:25<00:38, 12.31it/s]

 41%|████████████████▍                       | 323/788 [00:26<00:36, 12.65it/s]

 41%|████████████████▌                       | 327/788 [00:26<00:37, 12.34it/s]

 42%|████████████████▊                       | 331/788 [00:26<00:37, 12.23it/s]

 43%|█████████████████                       | 335/788 [00:27<00:33, 13.38it/s]

 43%|█████████████████                       | 337/788 [00:27<00:34, 13.22it/s]

 43%|█████████████████▎                      | 341/788 [00:27<00:38, 11.74it/s]

 44%|█████████████████▍                      | 343/788 [00:27<00:38, 11.59it/s]

 44%|█████████████████▌                      | 345/788 [00:28<00:41, 10.77it/s]

 44%|█████████████████▋                      | 349/788 [00:28<00:39, 11.03it/s]

 45%|█████████████████▉                      | 353/788 [00:28<00:37, 11.73it/s]

 45%|██████████████████                      | 357/788 [00:29<00:35, 12.13it/s]

 46%|██████████████████▎                     | 361/788 [00:29<00:32, 12.95it/s]

 46%|██████████████████▌                     | 366/788 [00:29<00:29, 14.29it/s]

 47%|██████████████████▊                     | 370/788 [00:29<00:30, 13.91it/s]

 47%|██████████████████▉                     | 374/788 [00:30<00:27, 14.89it/s]

 48%|███████████████████▏                    | 379/788 [00:30<00:26, 15.37it/s]

 49%|███████████████████▍                    | 383/788 [00:30<00:28, 14.18it/s]

 49%|███████████████████▌                    | 385/788 [00:30<00:29, 13.86it/s]

 49%|███████████████████▋                    | 389/788 [00:31<00:31, 12.76it/s]

 50%|███████████████████▉                    | 393/788 [00:31<00:32, 12.26it/s]

 50%|████████████████████▏                   | 397/788 [00:31<00:29, 13.46it/s]

 51%|████████████████████▎                   | 401/788 [00:32<00:30, 12.86it/s]

 51%|████████████████████▌                   | 405/788 [00:32<00:30, 12.70it/s]

 52%|████████████████████▊                   | 409/788 [00:32<00:28, 13.51it/s]

 52%|████████████████████▉                   | 413/788 [00:33<00:28, 13.39it/s]

 53%|█████████████████████▏                  | 417/788 [00:33<00:29, 12.55it/s]

 53%|█████████████████████▎                  | 419/788 [00:33<00:31, 11.65it/s]

 54%|█████████████████████▍                  | 423/788 [00:34<00:32, 11.22it/s]

 54%|█████████████████████▋                  | 427/788 [00:34<00:31, 11.36it/s]

 55%|█████████████████████▉                  | 431/788 [00:34<00:27, 12.92it/s]

 55%|██████████████████████                  | 435/788 [00:35<00:28, 12.22it/s]

 56%|██████████████████████▎                 | 439/788 [00:35<00:28, 12.28it/s]

 56%|██████████████████████▍                 | 443/788 [00:35<00:27, 12.55it/s]

 57%|██████████████████████▋                 | 447/788 [00:35<00:28, 11.96it/s]

 57%|██████████████████████▉                 | 451/788 [00:36<00:27, 12.45it/s]

 58%|███████████████████████                 | 455/788 [00:36<00:25, 13.13it/s]

 58%|███████████████████████▎                | 459/788 [00:36<00:25, 13.06it/s]

 59%|███████████████████████▌                | 463/788 [00:37<00:26, 12.04it/s]

 59%|███████████████████████▋                | 467/788 [00:37<00:25, 12.74it/s]

 60%|███████████████████████▉                | 471/788 [00:37<00:27, 11.59it/s]

 60%|████████████████████████                | 475/788 [00:38<00:27, 11.58it/s]

 61%|████████████████████████▎               | 479/788 [00:38<00:26, 11.88it/s]

 61%|████████████████████████▌               | 483/788 [00:38<00:25, 12.05it/s]

 62%|████████████████████████▋               | 487/788 [00:39<00:25, 11.93it/s]

 62%|████████████████████████▊               | 489/788 [00:39<00:27, 11.05it/s]

 63%|█████████████████████████               | 493/788 [00:39<00:25, 11.55it/s]

 63%|█████████████████████████▏              | 497/788 [00:40<00:22, 12.71it/s]

 64%|█████████████████████████▍              | 501/788 [00:40<00:20, 14.27it/s]

 64%|█████████████████████████▋              | 505/788 [00:40<00:21, 13.08it/s]

 65%|█████████████████████████▊              | 509/788 [00:40<00:20, 13.71it/s]

 65%|██████████████████████████              | 513/788 [00:41<00:19, 14.33it/s]

 66%|██████████████████████████▏             | 517/788 [00:41<00:19, 13.98it/s]

 66%|██████████████████████████▍             | 521/788 [00:41<00:18, 14.35it/s]

 67%|██████████████████████████▋             | 525/788 [00:42<00:19, 13.50it/s]

 67%|██████████████████████████▊             | 529/788 [00:42<00:19, 13.21it/s]

 68%|███████████████████████████             | 533/788 [00:42<00:20, 12.25it/s]

 68%|███████████████████████████▏            | 535/788 [00:42<00:19, 12.99it/s]

 68%|███████████████████████████▎            | 537/788 [00:43<00:21, 11.64it/s]

 68%|███████████████████████████▎            | 539/788 [00:43<00:22, 11.01it/s]

 69%|███████████████████████████▌            | 543/788 [00:43<00:23, 10.32it/s]

 69%|███████████████████████████▊            | 547/788 [00:44<00:22, 10.92it/s]

 70%|███████████████████████████▉            | 551/788 [00:44<00:20, 11.58it/s]

 70%|████████████████████████████▏           | 555/788 [00:44<00:18, 12.27it/s]

 71%|████████████████████████████▍           | 559/788 [00:45<00:18, 12.46it/s]

 71%|████████████████████████████▌           | 563/788 [00:45<00:14, 15.24it/s]

 72%|████████████████████████████▊           | 567/788 [00:45<00:18, 12.24it/s]

 72%|████████████████████████████▉           | 571/788 [00:45<00:16, 12.86it/s]

 73%|█████████████████████████████▏          | 575/788 [00:46<00:17, 11.97it/s]

 73%|█████████████████████████████▍          | 579/788 [00:46<00:16, 12.35it/s]

 74%|█████████████████████████████▌          | 583/788 [00:46<00:17, 11.84it/s]

 74%|█████████████████████████████▊          | 587/788 [00:47<00:17, 11.76it/s]

 75%|██████████████████████████████          | 591/788 [00:47<00:15, 12.62it/s]

 76%|██████████████████████████████▏         | 595/788 [00:47<00:16, 11.90it/s]

 76%|██████████████████████████████▍         | 599/788 [00:48<00:14, 12.65it/s]

 77%|██████████████████████████████▌         | 603/788 [00:48<00:14, 12.99it/s]

 77%|██████████████████████████████▊         | 607/788 [00:48<00:12, 14.57it/s]

 78%|███████████████████████████████         | 611/788 [00:49<00:14, 12.18it/s]

 78%|███████████████████████████████▏        | 615/788 [00:49<00:12, 13.40it/s]

 79%|███████████████████████████████▍        | 619/788 [00:49<00:12, 13.42it/s]

 79%|███████████████████████████████▌        | 623/788 [00:50<00:11, 14.69it/s]

 79%|███████████████████████████████▋        | 625/788 [00:50<00:12, 12.79it/s]

 80%|███████████████████████████████▊        | 627/788 [00:50<00:13, 11.66it/s]

 80%|███████████████████████████████▉        | 629/788 [00:50<00:14, 10.75it/s]

 80%|████████████████████████████████▏       | 633/788 [00:51<00:14, 10.82it/s]

 81%|████████████████████████████████▎       | 637/788 [00:51<00:12, 12.37it/s]

 81%|████████████████████████████████▌       | 642/788 [00:51<00:10, 13.44it/s]

 82%|████████████████████████████████▊       | 646/788 [00:51<00:11, 12.48it/s]

 82%|████████████████████████████████▉       | 650/788 [00:52<00:09, 14.46it/s]

 83%|█████████████████████████████████▏      | 654/788 [00:52<00:10, 12.85it/s]

 84%|█████████████████████████████████▍      | 658/788 [00:52<00:10, 12.32it/s]

 84%|█████████████████████████████████▌      | 662/788 [00:53<00:10, 11.76it/s]

 84%|█████████████████████████████████▋      | 664/788 [00:53<00:09, 12.87it/s]

 85%|█████████████████████████████████▉      | 668/788 [00:53<00:10, 11.49it/s]

 85%|██████████████████████████████████      | 672/788 [00:54<00:09, 11.91it/s]

 86%|██████████████████████████████████▎     | 676/788 [00:54<00:08, 12.92it/s]

 86%|██████████████████████████████████▌     | 680/788 [00:54<00:08, 12.69it/s]

 87%|██████████████████████████████████▋     | 684/788 [00:55<00:07, 13.02it/s]

 87%|██████████████████████████████████▉     | 688/788 [00:55<00:08, 12.32it/s]

 88%|███████████████████████████████████▏    | 692/788 [00:55<00:08, 11.49it/s]

 88%|███████████████████████████████████▎    | 696/788 [00:56<00:07, 13.06it/s]

 89%|███████████████████████████████████▌    | 700/788 [00:56<00:07, 12.10it/s]

 89%|███████████████████████████████████▋    | 704/788 [00:56<00:07, 11.31it/s]

 90%|███████████████████████████████████▉    | 708/788 [00:57<00:07, 11.01it/s]

 90%|████████████████████████████████████▏   | 712/788 [00:57<00:06, 11.45it/s]

 91%|████████████████████████████████████▍   | 717/788 [00:57<00:04, 14.44it/s]

 91%|████████████████████████████████████▌   | 721/788 [00:58<00:05, 12.91it/s]

 92%|████████████████████████████████████▊   | 725/788 [00:58<00:05, 11.46it/s]

 93%|█████████████████████████████████████   | 729/788 [00:58<00:05, 10.97it/s]

 93%|█████████████████████████████████████▏  | 733/788 [00:59<00:04, 11.78it/s]

 93%|█████████████████████████████████████▎  | 735/788 [00:59<00:04, 11.18it/s]

 94%|█████████████████████████████████████▌  | 739/788 [00:59<00:04, 11.20it/s]

 94%|█████████████████████████████████████▋  | 743/788 [00:59<00:03, 13.09it/s]

 95%|█████████████████████████████████████▉  | 747/788 [01:00<00:03, 13.12it/s]

 95%|██████████████████████████████████████  | 751/788 [01:00<00:03, 11.77it/s]

 96%|██████████████████████████████████████▎ | 755/788 [01:01<00:02, 11.65it/s]

 96%|██████████████████████████████████████▌ | 759/788 [01:01<00:02, 11.71it/s]

 97%|██████████████████████████████████████▊ | 764/788 [01:01<00:01, 14.52it/s]

 97%|██████████████████████████████████████▉ | 768/788 [01:01<00:01, 13.07it/s]

 98%|███████████████████████████████████████▏| 772/788 [01:02<00:01, 12.90it/s]

 98%|███████████████████████████████████████▍| 776/788 [01:02<00:00, 14.00it/s]

 99%|███████████████████████████████████████▌| 780/788 [01:02<00:00, 14.76it/s]

 99%|███████████████████████████████████████▊| 784/788 [01:03<00:00, 14.08it/s]

100%|████████████████████████████████████████| 788/788 [01:03<00:00, 12.44it/s]
Writing model shards:   0%|                              | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|██████████████████████| 1/1 [00:00<00:00,  1.27it/s]

Wrote experiments/transformers/20260521_115409_TRANSFORMER_BASELINES/microsoft__deberta-v3-base__fine_tuned/transformer_results.csv
Wrote experiments/transformers/20260521_115409_TRANSFORMER_BASELINES/microsoft__deberta-v3-base__fine_tuned/transformer_best_by_family.csv
Wrote experiments/transformers/20260521_115409_TRANSFORMER_BASELINES/microsoft__deberta-v3-base__fine_tuned/transformer_epoch_history.csv
[ok] transformer__microsoft__deberta-v3-base__fine_tuned: best_epoch=1.0 score=0.50000 mae=2.00000 acc=0.20000 macro_f1=0.06667

/cluster/courses/cil/envs/envs/text-5060/bin/python -m baselines.train_review_model --model-name nlptown/bert-base-multilingual-uncased-sentiment --experiment-name transformer__nlptown__bert-base-multilingual-uncased-sentiment__fine_tuned --train-path data/train.csv --output-dir experiments/transformers/20260521_115409_TRANSFORMER_BASELINES/nlptown__bert-base-multilingual-uncased-sentiment__fine_tuned --validation-size 0.1 --random-state 42 --max-length 256 --epochs 3 --batch-size 16 --eval-batch-size 32 --learning-rate 2e-05 --weight-decay 0.01 --fp16

Model: nlptown/bert-base-multilingual-uncased-sentiment
Variant: fine_tuned
Train examples: 226800
Validation examples: 25200
Class counts: {0: 45360, 1: 45360, 2: 45360, 3: 45360, 4: 45360}

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights: 100%|████████████████████| 201/201 [00:00<00:00, 23994.74it/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

  0%|                                                | 0/42525 [00:00<?, ?it/s]

  0%|                                      | 3/42525 [00:01<4:04:59,  2.89it/s]

  0%|                                      | 7/42525 [00:01<1:52:09,  6.32it/s]

  0%|                                     | 11/42525 [00:01<1:19:32,  8.91it/s]

  0%|                                     | 15/42525 [00:02<1:10:34, 10.04it/s]

  0%|                                     | 19/42525 [00:02<1:03:20, 11.18it/s]

  0%|                                     | 23/42525 [00:02<1:02:13, 11.38it/s]

  0%|                                     | 27/42525 [00:03<1:04:40, 10.95it/s]

  0%|                                     | 31/42525 [00:03<1:05:12, 10.86it/s]

  0%|                                     | 35/42525 [00:04<1:07:48, 10.44it/s]

  0%|                                     | 39/42525 [00:04<1:06:58, 10.57it/s]

  0%|                                     | 43/42525 [00:04<1:07:20, 10.51it/s]

  0%|                                     | 47/42525 [00:05<1:08:38, 10.31it/s]

  0%|                                     | 51/42525 [00:05<1:07:28, 10.49it/s]

  0%|                                     | 55/42525 [00:05<1:05:19, 10.84it/s]

  0%|                                     | 59/42525 [00:06<1:04:21, 11.00it/s]

  0%|                                     | 63/42525 [00:06<1:03:54, 11.07it/s]

  0%|                                     | 67/42525 [00:07<1:03:01, 11.23it/s]

  0%|                                     | 71/42525 [00:07<1:08:01, 10.40it/s]

  0%|                                     | 75/42525 [00:07<1:06:52, 10.58it/s]

  0%|                                     | 79/42525 [00:08<1:02:25, 11.33it/s]

  0%|                                     | 83/42525 [00:08<1:00:43, 11.65it/s]

  0%|                                       | 87/42525 [00:08<59:22, 11.91it/s]

  0%|                                     | 91/42525 [00:09<1:00:50, 11.62it/s]

  0%|                                     | 95/42525 [00:09<1:01:14, 11.55it/s]

  0%|                                       | 99/42525 [00:09<57:20, 12.33it/s]

  0%|                                      | 103/42525 [00:10<57:00, 12.40it/s]

  0%|                                      | 107/42525 [00:10<58:08, 12.16it/s]

  0%|                                      | 111/42525 [00:10<57:16, 12.34it/s]

  0%|                                    | 113/42525 [00:11<1:03:01, 11.22it/s]

  0%|                                    | 117/42525 [00:11<1:07:03, 10.54it/s]

  0%|                                    | 121/42525 [00:11<1:04:27, 10.96it/s]

  0%|                                    | 125/42525 [00:12<1:01:55, 11.41it/s]

  0%|                                    | 129/42525 [00:12<1:04:38, 10.93it/s]

  0%|                                    | 133/42525 [00:12<1:02:14, 11.35it/s]

  0%|                                    | 137/42525 [00:13<1:03:46, 11.08it/s]

  0%|                                    | 141/42525 [00:13<1:00:50, 11.61it/s]

  0%|                                    | 145/42525 [00:13<1:01:19, 11.52it/s]

  0%|▏                                     | 149/42525 [00:14<58:50, 12.00it/s]

  0%|▏                                     | 153/42525 [00:14<59:09, 11.94it/s]

  0%|▏                                   | 157/42525 [00:14<1:01:16, 11.52it/s]

  0%|▏                                     | 161/42525 [00:15<59:33, 11.85it/s]

  0%|▏                                   | 165/42525 [00:15<1:02:07, 11.37it/s]

  0%|▏                                   | 169/42525 [00:15<1:03:21, 11.14it/s]

  0%|▏                                   | 171/42525 [00:16<1:05:32, 10.77it/s]

  0%|▏                                   | 175/42525 [00:16<1:05:11, 10.83it/s]

  0%|▏                                   | 179/42525 [00:16<1:07:43, 10.42it/s]

  0%|▏                                   | 183/42525 [00:17<1:07:53, 10.39it/s]

  0%|▏                                   | 187/42525 [00:17<1:04:00, 11.02it/s]

  0%|▏                                   | 191/42525 [00:18<1:03:06, 11.18it/s]

  0%|▏                                   | 195/42525 [00:18<1:01:30, 11.47it/s]

  0%|▏                                   | 199/42525 [00:18<1:02:59, 11.20it/s]

  0%|▏                                   | 203/42525 [00:19<1:02:33, 11.28it/s]

  0%|▏                                   | 207/42525 [00:19<1:02:42, 11.25it/s]

  0%|▏                                   | 211/42525 [00:19<1:02:00, 11.37it/s]

  1%|▏                                   | 213/42525 [00:19<1:04:42, 10.90it/s]

  1%|▏                                   | 217/42525 [00:20<1:04:57, 10.86it/s]

  1%|▏                                   | 221/42525 [00:20<1:04:51, 10.87it/s]

  1%|▏                                   | 225/42525 [00:21<1:04:11, 10.98it/s]

  1%|▏                                   | 229/42525 [00:21<1:04:57, 10.85it/s]

  1%|▏                                   | 233/42525 [00:21<1:03:02, 11.18it/s]

  1%|▏                                   | 237/42525 [00:22<1:05:29, 10.76it/s]

  1%|▏                                   | 241/42525 [00:22<1:05:32, 10.75it/s]

  1%|▏                                   | 245/42525 [00:22<1:02:03, 11.36it/s]

  1%|▏                                   | 249/42525 [00:23<1:05:09, 10.81it/s]

  1%|▏                                   | 253/42525 [00:23<1:03:56, 11.02it/s]

  1%|▏                                   | 257/42525 [00:24<1:06:10, 10.64it/s]

  1%|▏                                   | 261/42525 [00:24<1:04:31, 10.92it/s]

  1%|▏                                   | 263/42525 [00:24<1:01:09, 11.52it/s]

  1%|▏                                   | 267/42525 [00:24<1:02:32, 11.26it/s]

  1%|▏                                   | 271/42525 [00:25<1:02:04, 11.34it/s]

  1%|▏                                   | 275/42525 [00:25<1:01:05, 11.53it/s]

  1%|▏                                   | 279/42525 [00:25<1:02:06, 11.34it/s]

  1%|▏                                   | 283/42525 [00:26<1:04:56, 10.84it/s]

  1%|▏                                   | 287/42525 [00:26<1:02:45, 11.22it/s]

  1%|▏                                   | 291/42525 [00:27<1:00:34, 11.62it/s]

  1%|▏                                   | 295/42525 [00:27<1:01:19, 11.48it/s]

  1%|▎                                   | 299/42525 [00:27<1:02:04, 11.34it/s]

  1%|▎                                   | 303/42525 [00:28<1:02:31, 11.25it/s]

  1%|▎                                   | 307/42525 [00:28<1:02:38, 11.23it/s]

  1%|▎                                   | 311/42525 [00:28<1:00:27, 11.64it/s]

  1%|▎                                   | 315/42525 [00:29<1:02:29, 11.26it/s]

  1%|▎                                   | 319/42525 [00:29<1:03:06, 11.15it/s]

  1%|▎                                   | 323/42525 [00:29<1:03:01, 11.16it/s]

  1%|▎                                   | 327/42525 [00:30<1:04:21, 10.93it/s]

  1%|▎                                   | 331/42525 [00:30<1:04:42, 10.87it/s]

  1%|▎                                   | 335/42525 [00:30<1:04:34, 10.89it/s]

  1%|▎                                   | 339/42525 [00:31<1:06:24, 10.59it/s]

  1%|▎                                   | 343/42525 [00:31<1:05:49, 10.68it/s]

  1%|▎                                   | 347/42525 [00:32<1:03:58, 10.99it/s]

  1%|▎                                   | 351/42525 [00:32<1:02:57, 11.16it/s]

  1%|▎                                   | 355/42525 [00:32<1:04:26, 10.91it/s]

  1%|▎                                   | 359/42525 [00:33<1:05:47, 10.68it/s]

  1%|▎                                   | 361/42525 [00:33<1:05:51, 10.67it/s]

  1%|▎                                   | 365/42525 [00:33<1:05:54, 10.66it/s]

  1%|▎                                   | 369/42525 [00:34<1:04:55, 10.82it/s]

  1%|▎                                   | 373/42525 [00:34<1:03:26, 11.07it/s]

  1%|▎                                   | 375/42525 [00:34<1:03:38, 11.04it/s]

  1%|▎                                   | 379/42525 [00:35<1:04:32, 10.88it/s]

  1%|▎                                   | 383/42525 [00:35<1:04:43, 10.85it/s]

  1%|▎                                   | 387/42525 [00:35<1:04:00, 10.97it/s]

  1%|▎                                   | 391/42525 [00:36<1:02:35, 11.22it/s]

  1%|▎                                   | 395/42525 [00:36<1:03:49, 11.00it/s]

  1%|▎                                   | 399/42525 [00:36<1:05:59, 10.64it/s]

  1%|▎                                   | 403/42525 [00:37<1:03:53, 10.99it/s]

  1%|▎                                   | 407/42525 [00:37<1:04:06, 10.95it/s]

  1%|▎                                   | 411/42525 [00:37<1:06:39, 10.53it/s]

  1%|▎                                   | 413/42525 [00:38<1:05:38, 10.69it/s]

  1%|▎                                   | 417/42525 [00:38<1:06:41, 10.52it/s]

  1%|▎                                   | 421/42525 [00:38<1:07:43, 10.36it/s]

  1%|▎                                   | 423/42525 [00:39<1:07:21, 10.42it/s]

  1%|▎                                   | 427/42525 [00:39<1:08:19, 10.27it/s]

  1%|▎                                   | 431/42525 [00:39<1:07:08, 10.45it/s]

  1%|▎                                   | 435/42525 [00:40<1:05:23, 10.73it/s]

  1%|▎                                   | 439/42525 [00:40<1:07:10, 10.44it/s]

  1%|▍                                   | 443/42525 [00:41<1:05:49, 10.65it/s]

  1%|▍                                   | 447/42525 [00:41<1:03:20, 11.07it/s]

  1%|▍                                     | 451/42525 [00:41<58:31, 11.98it/s]

  1%|▍                                     | 455/42525 [00:42<56:50, 12.34it/s]

  1%|▍                                   | 459/42525 [00:42<1:00:04, 11.67it/s]

  1%|▍                                     | 463/42525 [00:42<56:20, 12.44it/s]

  1%|▍                                   | 467/42525 [00:43<1:02:47, 11.16it/s]

  1%|▍                                   | 471/42525 [00:43<1:05:20, 10.73it/s]

  1%|▍                                   | 475/42525 [00:43<1:07:25, 10.39it/s]

  1%|▍                                   | 479/42525 [00:44<1:06:40, 10.51it/s]

  1%|▍                                   | 483/42525 [00:44<1:07:32, 10.37it/s]

  1%|▍                                   | 487/42525 [00:45<1:07:06, 10.44it/s]

  1%|▍                                   | 491/42525 [00:45<1:07:41, 10.35it/s]

  1%|▍                                   | 495/42525 [00:45<1:08:25, 10.24it/s]

  1%|▍                                   | 499/42525 [00:46<1:06:06, 10.60it/s]

  1%|▍                                   | 503/42525 [00:46<1:04:57, 10.78it/s]

  1%|▍                                   | 507/42525 [00:46<1:05:32, 10.68it/s]

  1%|▍                                   | 511/42525 [00:47<1:04:53, 10.79it/s]

  1%|▍                                   | 515/42525 [00:47<1:04:12, 10.90it/s]

  1%|▍                                   | 519/42525 [00:48<1:06:33, 10.52it/s]

  1%|▍                                   | 523/42525 [00:48<1:04:21, 10.88it/s]

  1%|▍                                   | 527/42525 [00:48<1:04:07, 10.92it/s]

  1%|▍                                   | 531/42525 [00:49<1:05:31, 10.68it/s]

  1%|▍                                   | 535/42525 [00:49<1:03:35, 11.01it/s]

  1%|▍                                   | 537/42525 [00:49<1:03:03, 11.10it/s]

  1%|▍                                   | 541/42525 [00:50<1:05:10, 10.74it/s]

  1%|▍                                   | 545/42525 [00:50<1:06:58, 10.45it/s]

  1%|▍                                   | 547/42525 [00:50<1:05:33, 10.67it/s]

  1%|▍                                   | 551/42525 [00:51<1:05:31, 10.68it/s]

  1%|▍                                   | 555/42525 [00:51<1:03:44, 10.97it/s]

  1%|▍                                   | 559/42525 [00:51<1:02:22, 11.21it/s]

  1%|▍                                   | 563/42525 [00:52<1:03:49, 10.96it/s]

  1%|▍                                   | 565/42525 [00:52<1:05:41, 10.64it/s]

  1%|▍                                   | 569/42525 [00:52<1:06:26, 10.52it/s]

  1%|▍                                   | 573/42525 [00:53<1:05:38, 10.65it/s]

  1%|▍                                   | 577/42525 [00:53<1:03:20, 11.04it/s]

  1%|▍                                   | 581/42525 [00:53<1:03:20, 11.04it/s]

  1%|▍                                   | 585/42525 [00:54<1:05:37, 10.65it/s]

  1%|▍                                   | 587/42525 [00:54<1:04:17, 10.87it/s]

  1%|▌                                   | 591/42525 [00:54<1:06:57, 10.44it/s]

  1%|▌                                   | 595/42525 [00:55<1:07:31, 10.35it/s]

  1%|▌                                   | 599/42525 [00:55<1:05:37, 10.65it/s]

  1%|▌                                   | 603/42525 [00:55<1:04:27, 10.84it/s]

  1%|▌                                   | 607/42525 [00:56<1:03:01, 11.08it/s]

  1%|▌                                   | 611/42525 [00:56<1:02:20, 11.20it/s]

  1%|▌                                   | 615/42525 [00:56<1:04:39, 10.80it/s]

  1%|▌                                   | 619/42525 [00:57<1:01:59, 11.27it/s]

  1%|▌                                   | 623/42525 [00:57<1:00:44, 11.50it/s]

  1%|▌                                   | 627/42525 [00:57<1:01:53, 11.28it/s]

  1%|▌                                   | 631/42525 [00:58<1:02:06, 11.24it/s]

  1%|▌                                   | 635/42525 [00:58<1:00:53, 11.47it/s]

  2%|▌                                     | 639/42525 [00:58<56:14, 12.41it/s]

  2%|▌                                   | 643/42525 [00:59<1:00:32, 11.53it/s]

  2%|▌                                   | 647/42525 [00:59<1:02:13, 11.22it/s]

  2%|▌                                   | 649/42525 [00:59<1:02:27, 11.18it/s]

  2%|▌                                   | 653/42525 [01:00<1:04:15, 10.86it/s]

  2%|▌                                   | 657/42525 [01:00<1:05:21, 10.68it/s]

  2%|▌                                   | 661/42525 [01:00<1:04:02, 10.89it/s]

  2%|▌                                   | 665/42525 [01:01<1:03:18, 11.02it/s]

  2%|▌                                   | 669/42525 [01:01<1:03:32, 10.98it/s]

  2%|▌                                   | 673/42525 [01:02<1:03:38, 10.96it/s]

  2%|▌                                   | 677/42525 [01:02<1:05:04, 10.72it/s]

  2%|▌                                   | 679/42525 [01:02<1:08:13, 10.22it/s]

  2%|▌                                   | 683/42525 [01:03<1:07:00, 10.41it/s]

  2%|▌                                   | 687/42525 [01:03<1:04:14, 10.85it/s]

  2%|▌                                   | 691/42525 [01:03<1:03:04, 11.05it/s]

  2%|▌                                   | 695/42525 [01:04<1:04:10, 10.86it/s]

  2%|▌                                   | 699/42525 [01:04<1:05:28, 10.65it/s]

  2%|▌                                   | 703/42525 [01:04<1:04:22, 10.83it/s]

  2%|▌                                   | 707/42525 [01:05<1:06:13, 10.52it/s]

  2%|▌                                   | 711/42525 [01:05<1:07:06, 10.39it/s]

  2%|▌                                   | 715/42525 [01:06<1:07:05, 10.39it/s]

  2%|▌                                   | 719/42525 [01:06<1:05:31, 10.63it/s]

  2%|▌                                   | 721/42525 [01:06<1:05:27, 10.64it/s]

  2%|▌                                   | 725/42525 [01:07<1:07:56, 10.25it/s]

  2%|▌                                   | 729/42525 [01:07<1:05:13, 10.68it/s]

  2%|▌                                   | 733/42525 [01:07<1:08:35, 10.16it/s]

  2%|▌                                   | 737/42525 [01:08<1:05:44, 10.59it/s]

  2%|▋                                   | 741/42525 [01:08<1:05:33, 10.62it/s]

  2%|▋                                   | 745/42525 [01:08<1:04:00, 10.88it/s]

  2%|▋                                   | 749/42525 [01:09<1:03:52, 10.90it/s]

  2%|▋                                   | 753/42525 [01:09<1:05:00, 10.71it/s]

  2%|▋                                   | 755/42525 [01:09<1:03:30, 10.96it/s]

  2%|▋                                   | 759/42525 [01:10<1:05:20, 10.65it/s]

  2%|▋                                   | 763/42525 [01:10<1:04:37, 10.77it/s]

  2%|▋                                   | 767/42525 [01:10<1:03:38, 10.93it/s]

  2%|▋                                   | 771/42525 [01:11<1:04:29, 10.79it/s]

  2%|▋                                   | 775/42525 [01:11<1:02:45, 11.09it/s]

  2%|▋                                   | 779/42525 [01:12<1:05:02, 10.70it/s]

  2%|▋                                   | 783/42525 [01:12<1:04:36, 10.77it/s]

  2%|▋                                   | 787/42525 [01:12<1:04:26, 10.79it/s]

  2%|▋                                   | 791/42525 [01:13<1:03:07, 11.02it/s]

  2%|▋                                   | 795/42525 [01:13<1:00:00, 11.59it/s]

  2%|▋                                   | 799/42525 [01:13<1:00:00, 11.59it/s]

  2%|▋                                   | 803/42525 [01:14<1:00:25, 11.51it/s]

  2%|▋                                   | 807/42525 [01:14<1:04:11, 10.83it/s]

  2%|▋                                   | 811/42525 [01:14<1:04:40, 10.75it/s]

  2%|▋                                   | 815/42525 [01:15<1:03:37, 10.93it/s]

  2%|▋                                   | 819/42525 [01:15<1:02:10, 11.18it/s]

  2%|▋                                   | 823/42525 [01:16<1:02:16, 11.16it/s]

  2%|▋                                   | 827/42525 [01:16<1:02:53, 11.05it/s]

  2%|▋                                   | 831/42525 [01:16<1:02:24, 11.13it/s]

  2%|▋                                   | 835/42525 [01:17<1:03:48, 10.89it/s]

  2%|▋                                   | 839/42525 [01:17<1:03:04, 11.01it/s]

  2%|▋                                   | 843/42525 [01:17<1:04:50, 10.71it/s]

  2%|▋                                   | 847/42525 [01:18<1:02:50, 11.05it/s]

  2%|▋                                   | 849/42525 [01:18<1:03:13, 10.99it/s]

  2%|▋                                   | 853/42525 [01:18<1:06:50, 10.39it/s]

  2%|▋                                   | 857/42525 [01:19<1:06:48, 10.39it/s]

  2%|▋                                   | 859/42525 [01:19<1:05:29, 10.60it/s]

  2%|▋                                   | 863/42525 [01:19<1:06:10, 10.49it/s]

  2%|▋                                   | 867/42525 [01:20<1:08:27, 10.14it/s]

  2%|▋                                   | 871/42525 [01:20<1:03:43, 10.89it/s]

  2%|▋                                   | 875/42525 [01:20<1:03:35, 10.92it/s]

  2%|▊                                     | 879/42525 [01:21<59:09, 11.73it/s]

  2%|▊                                     | 883/42525 [01:21<57:02, 12.17it/s]

  2%|▊                                     | 887/42525 [01:21<58:56, 11.77it/s]

  2%|▊                                     | 891/42525 [01:22<57:00, 12.17it/s]

  2%|▊                                     | 895/42525 [01:22<56:01, 12.38it/s]

  2%|▊                                     | 899/42525 [01:22<55:17, 12.55it/s]

  2%|▊                                     | 903/42525 [01:23<53:51, 12.88it/s]

  2%|▊                                     | 907/42525 [01:23<58:01, 11.95it/s]

  2%|▊                                   | 911/42525 [01:23<1:00:18, 11.50it/s]

  2%|▊                                   | 915/42525 [01:24<1:02:56, 11.02it/s]

  2%|▊                                   | 919/42525 [01:24<1:05:26, 10.60it/s]

  2%|▊                                   | 921/42525 [01:24<1:07:45, 10.23it/s]

  2%|▊                                   | 923/42525 [01:25<1:09:18, 10.00it/s]

  2%|▊                                   | 927/42525 [01:25<1:08:00, 10.19it/s]

  2%|▊                                   | 931/42525 [01:25<1:01:44, 11.23it/s]

  2%|▊                                   | 935/42525 [01:26<1:03:50, 10.86it/s]

  2%|▊                                     | 939/42525 [01:26<58:36, 11.83it/s]

  2%|▊                                     | 943/42525 [01:26<58:10, 11.91it/s]

  2%|▊                                     | 947/42525 [01:27<56:54, 12.18it/s]

  2%|▊                                   | 951/42525 [01:27<1:00:56, 11.37it/s]

  2%|▊                                     | 955/42525 [01:27<59:26, 11.66it/s]

  2%|▊                                     | 959/42525 [01:28<54:29, 12.71it/s]

  2%|▊                                     | 963/42525 [01:28<55:17, 12.53it/s]

  2%|▊                                     | 967/42525 [01:28<58:35, 11.82it/s]

  2%|▊                                     | 971/42525 [01:29<55:21, 12.51it/s]

  2%|▊                                     | 973/42525 [01:29<58:00, 11.94it/s]

  2%|▊                                   | 977/42525 [01:29<1:03:29, 10.91it/s]

  2%|▉                                     | 981/42525 [01:29<58:15, 11.89it/s]

  2%|▉                                     | 983/42525 [01:30<58:58, 11.74it/s]

  2%|▊                                   | 987/42525 [01:30<1:04:48, 10.68it/s]

  2%|▊                                   | 991/42525 [01:30<1:05:15, 10.61it/s]

  2%|▊                                   | 993/42525 [01:31<1:08:37, 10.09it/s]

  2%|▊                                   | 997/42525 [01:31<1:08:03, 10.17it/s]

  2%|▊                                  | 1001/42525 [01:31<1:06:24, 10.42it/s]

  2%|▊                                  | 1005/42525 [01:32<1:05:44, 10.53it/s]

  2%|▊                                  | 1009/42525 [01:32<1:06:05, 10.47it/s]

  2%|▊                                  | 1011/42525 [01:32<1:07:42, 10.22it/s]

  2%|▊                                  | 1015/42525 [01:33<1:08:39, 10.08it/s]

  2%|▊                                  | 1019/42525 [01:33<1:06:47, 10.36it/s]

  2%|▊                                  | 1023/42525 [01:33<1:04:08, 10.78it/s]

  2%|▊                                  | 1025/42525 [01:34<1:03:03, 10.97it/s]

  2%|▊                                  | 1029/42525 [01:34<1:05:07, 10.62it/s]

  2%|▊                                  | 1031/42525 [01:34<1:03:48, 10.84it/s]

  2%|▊                                  | 1035/42525 [01:35<1:04:53, 10.66it/s]

  2%|▊                                  | 1037/42525 [01:35<1:03:53, 10.82it/s]

  2%|▊                                  | 1041/42525 [01:35<1:05:29, 10.56it/s]

  2%|▊                                  | 1045/42525 [01:36<1:05:13, 10.60it/s]

  2%|▊                                  | 1049/42525 [01:36<1:04:14, 10.76it/s]

  2%|▊                                  | 1053/42525 [01:36<1:02:06, 11.13it/s]

  2%|▊                                  | 1057/42525 [01:37<1:04:21, 10.74it/s]

  2%|▊                                  | 1059/42525 [01:37<1:03:05, 10.95it/s]

  2%|▊                                  | 1063/42525 [01:37<1:05:13, 10.60it/s]

  3%|▉                                  | 1067/42525 [01:38<1:06:06, 10.45it/s]

  3%|▉                                  | 1071/42525 [01:38<1:03:41, 10.85it/s]

  3%|▉                                  | 1073/42525 [01:38<1:03:58, 10.80it/s]

  3%|▉                                  | 1077/42525 [01:39<1:04:21, 10.74it/s]

  3%|▉                                  | 1081/42525 [01:39<1:03:23, 10.90it/s]

  3%|▉                                  | 1085/42525 [01:39<1:03:58, 10.80it/s]

  3%|▉                                  | 1089/42525 [01:40<1:04:21, 10.73it/s]

  3%|▉                                  | 1093/42525 [01:40<1:05:15, 10.58it/s]

  3%|▉                                  | 1097/42525 [01:40<1:05:30, 10.54it/s]

  3%|▉                                  | 1101/42525 [01:41<1:03:27, 10.88it/s]

  3%|▉                                  | 1105/42525 [01:41<1:04:21, 10.73it/s]

  3%|▉                                  | 1109/42525 [01:42<1:04:54, 10.63it/s]

  3%|▉                                  | 1111/42525 [01:42<1:06:31, 10.38it/s]

  3%|▉                                  | 1115/42525 [01:42<1:07:59, 10.15it/s]

  3%|▉                                  | 1119/42525 [01:43<1:07:18, 10.25it/s]

  3%|▉                                  | 1123/42525 [01:43<1:05:46, 10.49it/s]

  3%|▉                                  | 1127/42525 [01:43<1:03:11, 10.92it/s]

  3%|▉                                  | 1131/42525 [01:44<1:03:42, 10.83it/s]

  3%|▉                                  | 1135/42525 [01:44<1:05:58, 10.46it/s]

  3%|▉                                  | 1139/42525 [01:44<1:06:08, 10.43it/s]

  3%|▉                                  | 1143/42525 [01:45<1:08:07, 10.12it/s]

  3%|▉                                  | 1147/42525 [01:45<1:07:44, 10.18it/s]

  3%|▉                                  | 1151/42525 [01:46<1:04:40, 10.66it/s]

  3%|▉                                  | 1155/42525 [01:46<1:03:16, 10.90it/s]

  3%|▉                                  | 1159/42525 [01:46<1:03:30, 10.86it/s]

  3%|▉                                  | 1163/42525 [01:47<1:02:51, 10.97it/s]

  3%|▉                                  | 1167/42525 [01:47<1:03:37, 10.83it/s]

  3%|▉                                  | 1169/42525 [01:47<1:03:05, 10.92it/s]

  3%|▉                                  | 1173/42525 [01:48<1:03:32, 10.85it/s]

  3%|▉                                  | 1177/42525 [01:48<1:02:59, 10.94it/s]

  3%|▉                                  | 1181/42525 [01:48<1:03:23, 10.87it/s]

  3%|▉                                  | 1185/42525 [01:49<1:02:50, 10.97it/s]

  3%|▉                                  | 1189/42525 [01:49<1:04:25, 10.69it/s]

  3%|▉                                  | 1193/42525 [01:49<1:05:45, 10.48it/s]

  3%|▉                                  | 1197/42525 [01:50<1:03:26, 10.86it/s]

  3%|▉                                  | 1201/42525 [01:50<1:01:55, 11.12it/s]

  3%|▉                                  | 1205/42525 [01:51<1:04:48, 10.63it/s]

  3%|▉                                  | 1209/42525 [01:51<1:03:46, 10.80it/s]

  3%|▉                                  | 1213/42525 [01:51<1:01:48, 11.14it/s]

  3%|█                                    | 1217/42525 [01:52<59:52, 11.50it/s]

  3%|█                                    | 1221/42525 [01:52<58:19, 11.80it/s]

  3%|█                                    | 1225/42525 [01:52<58:05, 11.85it/s]

  3%|█                                    | 1229/42525 [01:53<58:42, 11.72it/s]

  3%|█                                    | 1233/42525 [01:53<59:30, 11.56it/s]

  3%|█                                    | 1237/42525 [01:53<59:49, 11.50it/s]

  3%|█                                  | 1241/42525 [01:54<1:01:49, 11.13it/s]

  3%|█                                  | 1245/42525 [01:54<1:00:23, 11.39it/s]

  3%|█                                    | 1249/42525 [01:54<57:37, 11.94it/s]

  3%|█                                    | 1253/42525 [01:55<59:46, 11.51it/s]

  3%|█                                    | 1257/42525 [01:55<55:22, 12.42it/s]

  3%|█                                    | 1261/42525 [01:55<58:10, 11.82it/s]

  3%|█                                  | 1265/42525 [01:56<1:00:29, 11.37it/s]

  3%|█                                  | 1269/42525 [01:56<1:01:20, 11.21it/s]

  3%|█                                  | 1273/42525 [01:56<1:00:16, 11.41it/s]

  3%|█                                  | 1277/42525 [01:57<1:02:12, 11.05it/s]

  3%|█                                  | 1281/42525 [01:57<1:03:08, 10.89it/s]

  3%|█                                  | 1285/42525 [01:58<1:04:16, 10.69it/s]

  3%|█                                  | 1289/42525 [01:58<1:03:39, 10.80it/s]

  3%|█                                  | 1293/42525 [01:58<1:02:28, 11.00it/s]

  3%|█                                  | 1297/42525 [01:59<1:02:47, 10.94it/s]

  3%|█                                  | 1301/42525 [01:59<1:03:52, 10.76it/s]

  3%|█                                  | 1305/42525 [01:59<1:03:34, 10.81it/s]

  3%|█                                  | 1309/42525 [02:00<1:04:09, 10.71it/s]

  3%|█                                  | 1313/42525 [02:00<1:03:55, 10.74it/s]

  3%|█                                  | 1315/42525 [02:00<1:03:03, 10.89it/s]

  3%|█                                  | 1319/42525 [02:01<1:04:13, 10.69it/s]

  3%|█                                  | 1323/42525 [02:01<1:05:31, 10.48it/s]

  3%|█                                  | 1327/42525 [02:01<1:03:16, 10.85it/s]

  3%|█                                  | 1331/42525 [02:02<1:02:44, 10.94it/s]

  3%|█                                  | 1335/42525 [02:02<1:01:08, 11.23it/s]

  3%|█                                  | 1339/42525 [02:03<1:03:29, 10.81it/s]

  3%|█                                  | 1343/42525 [02:03<1:05:11, 10.53it/s]

  3%|█                                  | 1347/42525 [02:03<1:05:13, 10.52it/s]

  3%|█                                  | 1351/42525 [02:04<1:03:50, 10.75it/s]

  3%|█                                  | 1355/42525 [02:04<1:04:13, 10.68it/s]

  3%|█                                  | 1359/42525 [02:04<1:04:42, 10.60it/s]

  3%|█                                  | 1363/42525 [02:05<1:01:14, 11.20it/s]

  3%|█▏                                   | 1367/42525 [02:05<59:44, 11.48it/s]

  3%|█▏                                   | 1371/42525 [02:05<58:01, 11.82it/s]

  3%|█▏                                 | 1375/42525 [02:06<1:02:51, 10.91it/s]

  3%|█▏                                 | 1379/42525 [02:06<1:05:07, 10.53it/s]

  3%|█▏                                 | 1383/42525 [02:07<1:02:12, 11.02it/s]

  3%|█▏                                 | 1387/42525 [02:07<1:01:18, 11.18it/s]

  3%|█▏                                 | 1391/42525 [02:07<1:04:59, 10.55it/s]

  3%|█▏                                 | 1395/42525 [02:08<1:02:55, 10.90it/s]

  3%|█▏                                 | 1399/42525 [02:08<1:01:19, 11.18it/s]

  3%|█▏                                 | 1403/42525 [02:08<1:03:06, 10.86it/s]

  3%|█▏                                 | 1407/42525 [02:09<1:02:18, 11.00it/s]

  3%|█▏                                 | 1411/42525 [02:09<1:04:51, 10.56it/s]

  3%|█▏                                 | 1415/42525 [02:10<1:02:08, 11.03it/s]

  3%|█▏                                 | 1419/42525 [02:10<1:01:35, 11.12it/s]

  3%|█▏                                 | 1423/42525 [02:10<1:02:41, 10.93it/s]

  3%|█▏                                 | 1425/42525 [02:10<1:03:05, 10.86it/s]

  3%|█▏                                 | 1429/42525 [02:11<1:04:21, 10.64it/s]

  3%|█▏                                 | 1433/42525 [02:11<1:02:15, 11.00it/s]

  3%|█▏                                 | 1437/42525 [02:12<1:00:33, 11.31it/s]

  3%|█▏                                 | 1441/42525 [02:12<1:01:35, 11.12it/s]

  3%|█▏                                 | 1443/42525 [02:12<1:02:45, 10.91it/s]

  3%|█▏                                 | 1447/42525 [02:12<1:03:38, 10.76it/s]

  3%|█▏                                 | 1451/42525 [02:13<1:02:40, 10.92it/s]

  3%|█▏                                 | 1455/42525 [02:13<1:04:11, 10.66it/s]

  3%|█▏                                 | 1459/42525 [02:14<1:02:40, 10.92it/s]

  3%|█▏                                 | 1461/42525 [02:14<1:03:45, 10.73it/s]

  3%|█▏                                 | 1465/42525 [02:14<1:03:37, 10.75it/s]

  3%|█▏                                 | 1469/42525 [02:15<1:03:19, 10.80it/s]

  3%|█▏                                 | 1473/42525 [02:15<1:03:46, 10.73it/s]

  3%|█▏                                 | 1477/42525 [02:15<1:02:52, 10.88it/s]

  3%|█▏                                 | 1481/42525 [02:16<1:01:14, 11.17it/s]

  3%|█▏                                 | 1485/42525 [02:16<1:01:18, 11.16it/s]

  4%|█▏                                 | 1489/42525 [02:16<1:02:52, 10.88it/s]

  4%|█▏                                 | 1491/42525 [02:17<1:01:15, 11.17it/s]

  4%|█▏                                 | 1495/42525 [02:17<1:03:11, 10.82it/s]

  4%|█▏                                 | 1499/42525 [02:17<1:00:41, 11.27it/s]

  4%|█▏                                 | 1503/42525 [02:18<1:01:53, 11.05it/s]

  4%|█▏                                 | 1507/42525 [02:18<1:01:29, 11.12it/s]

  4%|█▏                                 | 1511/42525 [02:18<1:01:05, 11.19it/s]

  4%|█▏                                 | 1515/42525 [02:19<1:02:57, 10.86it/s]

  4%|█▎                                 | 1519/42525 [02:19<1:01:26, 11.12it/s]

  4%|█▎                                 | 1523/42525 [02:19<1:02:46, 10.88it/s]

  4%|█▎                                 | 1527/42525 [02:20<1:02:24, 10.95it/s]

  4%|█▎                                 | 1531/42525 [02:20<1:00:48, 11.24it/s]

  4%|█▎                                 | 1535/42525 [02:21<1:01:28, 11.11it/s]

  4%|█▎                                 | 1539/42525 [02:21<1:02:12, 10.98it/s]

  4%|█▎                                 | 1543/42525 [02:21<1:02:18, 10.96it/s]

  4%|█▎                                 | 1545/42525 [02:21<1:01:32, 11.10it/s]

  4%|█▎                                 | 1549/42525 [02:22<1:02:55, 10.85it/s]

  4%|█▎                                 | 1551/42525 [02:22<1:02:36, 10.91it/s]

  4%|█▎                                 | 1555/42525 [02:22<1:03:48, 10.70it/s]

  4%|█▎                                 | 1559/42525 [02:23<1:04:44, 10.55it/s]

  4%|█▎                                 | 1563/42525 [02:23<1:03:40, 10.72it/s]

  4%|█▎                                 | 1567/42525 [02:24<1:05:19, 10.45it/s]

  4%|█▎                                 | 1571/42525 [02:24<1:03:43, 10.71it/s]

  4%|█▎                                 | 1575/42525 [02:24<1:02:23, 10.94it/s]

  4%|█▎                                 | 1579/42525 [02:25<1:01:33, 11.09it/s]

  4%|█▎                                 | 1583/42525 [02:25<1:01:31, 11.09it/s]

  4%|█▎                                 | 1587/42525 [02:25<1:02:10, 10.97it/s]

  4%|█▎                                 | 1591/42525 [02:26<1:01:10, 11.15it/s]

  4%|█▎                                 | 1595/42525 [02:26<1:02:49, 10.86it/s]

  4%|█▎                                 | 1599/42525 [02:26<1:01:11, 11.15it/s]

  4%|█▎                                 | 1603/42525 [02:27<1:03:14, 10.79it/s]

  4%|█▎                                 | 1607/42525 [02:27<1:01:14, 11.14it/s]

  4%|█▎                                 | 1609/42525 [02:27<1:02:58, 10.83it/s]

  4%|█▎                                 | 1613/42525 [02:28<1:07:04, 10.17it/s]

  4%|█▎                                 | 1617/42525 [02:28<1:05:07, 10.47it/s]

  4%|█▎                                 | 1621/42525 [02:29<1:05:58, 10.33it/s]

  4%|█▎                                 | 1625/42525 [02:29<1:04:31, 10.56it/s]

  4%|█▎                                 | 1629/42525 [02:29<1:02:47, 10.86it/s]

  4%|█▎                                 | 1633/42525 [02:30<1:03:35, 10.72it/s]

  4%|█▎                                 | 1637/42525 [02:30<1:06:42, 10.21it/s]

  4%|█▎                                 | 1641/42525 [02:30<1:03:23, 10.75it/s]

  4%|█▎                                 | 1645/42525 [02:31<1:04:04, 10.63it/s]

  4%|█▎                                 | 1649/42525 [02:31<1:05:46, 10.36it/s]

  4%|█▎                                 | 1653/42525 [02:32<1:05:14, 10.44it/s]

  4%|█▎                                 | 1657/42525 [02:32<1:02:01, 10.98it/s]

  4%|█▎                                 | 1659/42525 [02:32<1:01:47, 11.02it/s]

  4%|█▎                                 | 1661/42525 [02:32<1:05:44, 10.36it/s]

  4%|█▎                                 | 1665/42525 [02:33<1:06:44, 10.20it/s]

  4%|█▎                                 | 1669/42525 [02:33<1:04:20, 10.58it/s]

  4%|█▍                                 | 1673/42525 [02:33<1:02:23, 10.91it/s]

  4%|█▍                                 | 1677/42525 [02:34<1:03:16, 10.76it/s]

  4%|█▍                                 | 1679/42525 [02:34<1:02:03, 10.97it/s]

  4%|█▍                                 | 1683/42525 [02:34<1:02:06, 10.96it/s]

  4%|█▍                                 | 1687/42525 [02:35<1:01:09, 11.13it/s]

  4%|█▍                                 | 1691/42525 [02:35<1:03:18, 10.75it/s]

  4%|█▍                                 | 1695/42525 [02:35<1:02:10, 10.94it/s]

  4%|█▍                                 | 1699/42525 [02:36<1:00:19, 11.28it/s]

  4%|█▍                                 | 1703/42525 [02:36<1:01:32, 11.06it/s]

  4%|█▍                                 | 1707/42525 [02:37<1:00:42, 11.21it/s]

  4%|█▍                                 | 1711/42525 [02:37<1:03:34, 10.70it/s]

  4%|█▍                                 | 1715/42525 [02:37<1:01:51, 11.00it/s]

  4%|█▍                                 | 1719/42525 [02:38<1:02:21, 10.91it/s]

  4%|█▍                                 | 1723/42525 [02:38<1:03:25, 10.72it/s]

  4%|█▍                                 | 1727/42525 [02:38<1:03:09, 10.76it/s]

  4%|█▍                                 | 1731/42525 [02:39<1:01:04, 11.13it/s]

  4%|█▍                                 | 1735/42525 [02:39<1:04:45, 10.50it/s]

  4%|█▍                                 | 1739/42525 [02:39<1:03:11, 10.76it/s]

  4%|█▍                                 | 1743/42525 [02:40<1:02:12, 10.93it/s]

  4%|█▍                                 | 1747/42525 [02:40<1:02:21, 10.90it/s]

  4%|█▍                                 | 1751/42525 [02:41<1:01:37, 11.03it/s]

  4%|█▍                                 | 1755/42525 [02:41<1:00:59, 11.14it/s]

  4%|█▍                                 | 1759/42525 [02:41<1:00:22, 11.25it/s]

  4%|█▍                                 | 1763/42525 [02:42<1:01:36, 11.03it/s]

  4%|█▍                                 | 1767/42525 [02:42<1:02:28, 10.87it/s]

  4%|█▍                                 | 1771/42525 [02:42<1:01:14, 11.09it/s]

  4%|█▍                                 | 1775/42525 [02:43<1:03:56, 10.62it/s]

  4%|█▍                                 | 1779/42525 [02:43<1:03:30, 10.69it/s]

  4%|█▍                                 | 1783/42525 [02:44<1:04:25, 10.54it/s]

  4%|█▍                                 | 1787/42525 [02:44<1:02:41, 10.83it/s]

  4%|█▍                                 | 1791/42525 [02:44<1:01:09, 11.10it/s]

  4%|█▍                                 | 1795/42525 [02:45<1:00:48, 11.16it/s]

  4%|█▍                                 | 1799/42525 [02:45<1:00:16, 11.26it/s]

  4%|█▌                                   | 1803/42525 [02:45<59:24, 11.42it/s]

  4%|█▍                                 | 1807/42525 [02:46<1:02:07, 10.92it/s]

  4%|█▍                                 | 1811/42525 [02:46<1:00:02, 11.30it/s]

  4%|█▌                                   | 1815/42525 [02:46<59:17, 11.44it/s]

  4%|█▍                                 | 1819/42525 [02:47<1:01:23, 11.05it/s]

  4%|█▌                                   | 1823/42525 [02:47<59:57, 11.32it/s]

  4%|█▌                                 | 1827/42525 [02:47<1:01:20, 11.06it/s]

  4%|█▌                                 | 1829/42525 [02:48<1:01:00, 11.12it/s]

  4%|█▌                                 | 1833/42525 [02:48<1:02:12, 10.90it/s]

  4%|█▌                                   | 1837/42525 [02:48<59:53, 11.32it/s]

  4%|█▌                                 | 1841/42525 [02:49<1:02:48, 10.80it/s]

  4%|█▌                                 | 1845/42525 [02:49<1:03:35, 10.66it/s]

  4%|█▌                                 | 1849/42525 [02:50<1:03:10, 10.73it/s]

  4%|█▌                                 | 1851/42525 [02:50<1:05:17, 10.38it/s]

  4%|█▌                                 | 1853/42525 [02:50<1:07:46, 10.00it/s]

  4%|█▌                                 | 1857/42525 [02:50<1:06:05, 10.26it/s]

  4%|█▌                                 | 1861/42525 [02:51<1:03:21, 10.70it/s]

  4%|█▌                                 | 1865/42525 [02:51<1:02:57, 10.76it/s]

  4%|█▌                                 | 1869/42525 [02:51<1:00:45, 11.15it/s]

  4%|█▋                                   | 1873/42525 [02:52<59:51, 11.32it/s]

  4%|█▋                                   | 1877/42525 [02:52<59:34, 11.37it/s]

  4%|█▋                                   | 1881/42525 [02:52<59:52, 11.31it/s]

  4%|█▋                                   | 1885/42525 [02:53<59:49, 11.32it/s]

  4%|█▋                                   | 1889/42525 [02:53<59:52, 11.31it/s]

  4%|█▌                                 | 1893/42525 [02:54<1:00:08, 11.26it/s]

  4%|█▌                                 | 1897/42525 [02:54<1:00:28, 11.20it/s]

  4%|█▌                                 | 1901/42525 [02:54<1:01:23, 11.03it/s]

  4%|█▌                                 | 1905/42525 [02:55<1:01:31, 11.00it/s]

  4%|█▌                                 | 1909/42525 [02:55<1:02:47, 10.78it/s]

  4%|█▌                                 | 1913/42525 [02:55<1:01:46, 10.96it/s]

  5%|█▌                                 | 1917/42525 [02:56<1:02:06, 10.90it/s]

  5%|█▌                                 | 1921/42525 [02:56<1:00:27, 11.19it/s]

  5%|█▋                                   | 1925/42525 [02:56<59:54, 11.29it/s]

  5%|█▌                                 | 1929/42525 [02:57<1:01:13, 11.05it/s]

  5%|█▌                                 | 1933/42525 [02:57<1:01:43, 10.96it/s]

  5%|█▌                                 | 1937/42525 [02:58<1:00:51, 11.12it/s]

  5%|█▌                                 | 1939/42525 [02:58<1:01:17, 11.04it/s]

  5%|█▌                                 | 1943/42525 [02:58<1:04:40, 10.46it/s]

  5%|█▌                                 | 1947/42525 [02:58<1:05:44, 10.29it/s]

  5%|█▌                                 | 1951/42525 [02:59<1:03:14, 10.69it/s]

  5%|█▌                                 | 1955/42525 [02:59<1:02:20, 10.85it/s]

  5%|█▌                                 | 1959/42525 [03:00<1:00:45, 11.13it/s]

  5%|█▌                                 | 1963/42525 [03:00<1:02:12, 10.87it/s]

  5%|█▌                                 | 1967/42525 [03:00<1:02:17, 10.85it/s]

  5%|█▌                                 | 1971/42525 [03:01<1:01:25, 11.00it/s]

  5%|█▋                                 | 1975/42525 [03:01<1:03:54, 10.57it/s]

  5%|█▋                                 | 1979/42525 [03:01<1:02:45, 10.77it/s]

  5%|█▋                                 | 1983/42525 [03:02<1:02:29, 10.81it/s]

  5%|█▋                                 | 1987/42525 [03:02<1:01:30, 10.99it/s]

  5%|█▋                                 | 1991/42525 [03:03<1:02:33, 10.80it/s]

  5%|█▋                                 | 1995/42525 [03:03<1:02:18, 10.84it/s]

  5%|█▋                                 | 1999/42525 [03:03<1:04:00, 10.55it/s]

  5%|█▋                                 | 2003/42525 [03:04<1:02:02, 10.88it/s]

  5%|█▋                                 | 2007/42525 [03:04<1:01:14, 11.03it/s]

  5%|█▋                                 | 2011/42525 [03:04<1:00:40, 11.13it/s]

  5%|█▋                                 | 2015/42525 [03:05<1:01:14, 11.03it/s]

  5%|█▊                                   | 2019/42525 [03:05<57:38, 11.71it/s]

  5%|█▊                                   | 2023/42525 [03:05<55:09, 12.24it/s]

  5%|█▊                                   | 2027/42525 [03:06<53:26, 12.63it/s]

  5%|█▊                                   | 2031/42525 [03:06<54:32, 12.38it/s]

  5%|█▊                                   | 2035/42525 [03:06<55:08, 12.24it/s]

  5%|█▊                                   | 2039/42525 [03:07<54:09, 12.46it/s]

  5%|█▊                                   | 2043/42525 [03:07<56:58, 11.84it/s]

  5%|█▊                                   | 2047/42525 [03:07<57:07, 11.81it/s]

  5%|█▊                                   | 2051/42525 [03:08<54:58, 12.27it/s]

  5%|█▊                                   | 2055/42525 [03:08<59:33, 11.32it/s]

  5%|█▊                                   | 2059/42525 [03:08<54:19, 12.42it/s]

  5%|█▊                                   | 2063/42525 [03:09<53:26, 12.62it/s]

  5%|█▊                                   | 2067/42525 [03:09<52:35, 12.82it/s]

  5%|█▊                                   | 2071/42525 [03:09<58:56, 11.44it/s]

  5%|█▋                                 | 2075/42525 [03:10<1:00:16, 11.19it/s]

  5%|█▊                                   | 2079/42525 [03:10<53:25, 12.62it/s]

  5%|█▊                                   | 2083/42525 [03:10<56:28, 11.93it/s]

  5%|█▊                                   | 2087/42525 [03:11<57:10, 11.79it/s]

  5%|█▊                                   | 2091/42525 [03:11<58:11, 11.58it/s]

  5%|█▋                                 | 2095/42525 [03:11<1:01:18, 10.99it/s]

  5%|█▋                                 | 2099/42525 [03:12<1:02:13, 10.83it/s]

  5%|█▋                                 | 2103/42525 [03:12<1:04:24, 10.46it/s]

  5%|█▋                                 | 2107/42525 [03:13<1:02:04, 10.85it/s]

  5%|█▋                                 | 2111/42525 [03:13<1:03:03, 10.68it/s]

  5%|█▋                                 | 2115/42525 [03:13<1:04:11, 10.49it/s]

  5%|█▋                                 | 2119/42525 [03:14<1:01:07, 11.02it/s]

  5%|█▋                                 | 2121/42525 [03:14<1:02:18, 10.81it/s]

  5%|█▋                                 | 2125/42525 [03:14<1:04:08, 10.50it/s]

  5%|█▊                                 | 2129/42525 [03:15<1:01:53, 10.88it/s]

  5%|█▊                                 | 2133/42525 [03:15<1:01:05, 11.02it/s]

  5%|█▊                                 | 2137/42525 [03:15<1:01:08, 11.01it/s]

  5%|█▊                                 | 2141/42525 [03:16<1:00:12, 11.18it/s]

  5%|█▊                                   | 2143/42525 [03:16<59:10, 11.37it/s]

  5%|█▊                                 | 2147/42525 [03:16<1:01:17, 10.98it/s]

  5%|█▊                                   | 2151/42525 [03:17<59:41, 11.27it/s]

  5%|█▊                                 | 2155/42525 [03:17<1:00:57, 11.04it/s]

  5%|█▊                                 | 2159/42525 [03:17<1:03:03, 10.67it/s]

  5%|█▊                                 | 2163/42525 [03:18<1:02:07, 10.83it/s]

  5%|█▊                                 | 2167/42525 [03:18<1:00:12, 11.17it/s]

  5%|█▊                                 | 2171/42525 [03:18<1:00:35, 11.10it/s]

  5%|█▊                                 | 2175/42525 [03:19<1:00:26, 11.13it/s]

  5%|█▊                                 | 2179/42525 [03:19<1:00:54, 11.04it/s]

  5%|█▊                                 | 2183/42525 [03:20<1:02:56, 10.68it/s]

  5%|█▊                                 | 2187/42525 [03:20<1:02:03, 10.83it/s]

  5%|█▊                                 | 2191/42525 [03:20<1:01:11, 10.99it/s]

  5%|█▊                                 | 2195/42525 [03:21<1:02:40, 10.72it/s]

  5%|█▊                                 | 2199/42525 [03:21<1:01:05, 11.00it/s]

  5%|█▊                                 | 2203/42525 [03:21<1:01:59, 10.84it/s]

  5%|█▊                                 | 2207/42525 [03:22<1:00:25, 11.12it/s]

  5%|█▊                                 | 2211/42525 [03:22<1:02:47, 10.70it/s]

  5%|█▊                                 | 2215/42525 [03:22<1:02:28, 10.75it/s]

  5%|█▊                                 | 2219/42525 [03:23<1:01:04, 11.00it/s]

  5%|█▊                                 | 2223/42525 [03:23<1:00:34, 11.09it/s]

  5%|█▊                                 | 2227/42525 [03:24<1:02:40, 10.71it/s]

  5%|█▊                                 | 2231/42525 [03:24<1:01:22, 10.94it/s]

  5%|█▊                                 | 2235/42525 [03:24<1:02:59, 10.66it/s]

  5%|█▊                                 | 2239/42525 [03:25<1:05:33, 10.24it/s]

  5%|█▊                                 | 2243/42525 [03:25<1:04:33, 10.40it/s]

  5%|█▊                                 | 2247/42525 [03:25<1:01:36, 10.90it/s]

  5%|█▉                                   | 2251/42525 [03:26<59:23, 11.30it/s]

  5%|█▊                                 | 2255/42525 [03:26<1:01:54, 10.84it/s]

  5%|█▊                                 | 2259/42525 [03:27<1:02:43, 10.70it/s]

  5%|█▊                                 | 2263/42525 [03:27<1:01:59, 10.83it/s]

  5%|█▊                                 | 2265/42525 [03:27<1:00:53, 11.02it/s]

  5%|█▊                                 | 2269/42525 [03:27<1:01:36, 10.89it/s]

  5%|█▊                                 | 2273/42525 [03:28<1:02:23, 10.75it/s]

  5%|█▉                                   | 2277/42525 [03:28<59:39, 11.24it/s]

  5%|█▉                                   | 2279/42525 [03:28<58:40, 11.43it/s]

  5%|█▉                                 | 2283/42525 [03:29<1:00:24, 11.10it/s]

  5%|█▉                                   | 2287/42525 [03:29<55:24, 12.10it/s]

  5%|█▉                                   | 2291/42525 [03:29<56:49, 11.80it/s]

  5%|█▉                                   | 2295/42525 [03:30<55:43, 12.03it/s]

  5%|██                                   | 2299/42525 [03:30<53:24, 12.55it/s]

  5%|██                                   | 2303/42525 [03:30<55:54, 11.99it/s]

  5%|██                                   | 2307/42525 [03:31<55:33, 12.06it/s]

  5%|█▉                                 | 2311/42525 [03:31<1:00:53, 11.01it/s]

  5%|█▉                                 | 2315/42525 [03:31<1:00:54, 11.00it/s]

  5%|█▉                                 | 2319/42525 [03:32<1:01:16, 10.94it/s]

  5%|█▉                                 | 2323/42525 [03:32<1:00:43, 11.03it/s]

  5%|█▉                                 | 2327/42525 [03:33<1:00:10, 11.13it/s]

  5%|█▉                                 | 2331/42525 [03:33<1:00:59, 10.98it/s]

  5%|█▉                                 | 2333/42525 [03:33<1:01:14, 10.94it/s]

  5%|█▉                                 | 2337/42525 [03:33<1:02:38, 10.69it/s]

  6%|█▉                                 | 2341/42525 [03:34<1:01:38, 10.87it/s]

  6%|█▉                                 | 2345/42525 [03:34<1:01:34, 10.88it/s]

  6%|█▉                                 | 2349/42525 [03:35<1:00:15, 11.11it/s]

  6%|█▉                                 | 2353/42525 [03:35<1:01:50, 10.83it/s]

  6%|██                                   | 2357/42525 [03:35<59:44, 11.21it/s]

  6%|██                                   | 2361/42525 [03:36<59:58, 11.16it/s]

  6%|█▉                                 | 2365/42525 [03:36<1:03:11, 10.59it/s]

  6%|█▉                                 | 2369/42525 [03:36<1:03:34, 10.53it/s]

  6%|█▉                                 | 2373/42525 [03:37<1:03:27, 10.55it/s]

  6%|█▉                                 | 2377/42525 [03:37<1:01:15, 10.92it/s]

  6%|█▉                                 | 2381/42525 [03:38<1:01:49, 10.82it/s]

  6%|█▉                                 | 2385/42525 [03:38<1:03:03, 10.61it/s]

  6%|█▉                                 | 2389/42525 [03:38<1:01:18, 10.91it/s]

  6%|█▉                                 | 2393/42525 [03:39<1:02:10, 10.76it/s]

  6%|█▉                                 | 2395/42525 [03:39<1:01:01, 10.96it/s]

  6%|█▉                                 | 2399/42525 [03:39<1:01:11, 10.93it/s]

  6%|█▉                                 | 2403/42525 [03:40<1:02:26, 10.71it/s]

  6%|█▉                                 | 2407/42525 [03:40<1:01:19, 10.90it/s]

  6%|█▉                                 | 2411/42525 [03:40<1:01:06, 10.94it/s]

  6%|█▉                                 | 2415/42525 [03:41<1:02:07, 10.76it/s]

  6%|█▉                                 | 2419/42525 [03:41<1:02:53, 10.63it/s]

  6%|█▉                                 | 2423/42525 [03:41<1:03:37, 10.50it/s]

  6%|█▉                                 | 2427/42525 [03:42<1:00:51, 10.98it/s]

  6%|██                                 | 2431/42525 [03:42<1:00:37, 11.02it/s]

  6%|██                                   | 2435/42525 [03:42<59:32, 11.22it/s]

  6%|██                                   | 2439/42525 [03:43<59:21, 11.25it/s]

  6%|██▏                                  | 2443/42525 [03:43<59:04, 11.31it/s]

  6%|██▏                                  | 2447/42525 [03:44<58:19, 11.45it/s]

  6%|██▏                                  | 2451/42525 [03:44<58:02, 11.51it/s]

  6%|██▏                                  | 2455/42525 [03:44<57:56, 11.53it/s]

  6%|██▏                                  | 2459/42525 [03:45<58:45, 11.36it/s]

  6%|██▏                                  | 2463/42525 [03:45<58:36, 11.39it/s]

  6%|██                                 | 2467/42525 [03:45<1:00:20, 11.06it/s]

  6%|██                                 | 2471/42525 [03:46<1:00:38, 11.01it/s]

  6%|██▏                                  | 2475/42525 [03:46<59:30, 11.22it/s]

  6%|██▏                                  | 2479/42525 [03:46<59:19, 11.25it/s]

  6%|██▏                                  | 2483/42525 [03:47<59:18, 11.25it/s]

  6%|██                                 | 2485/42525 [03:47<1:01:05, 10.92it/s]

  6%|██                                 | 2489/42525 [03:47<1:02:30, 10.67it/s]

  6%|██                                 | 2493/42525 [03:48<1:02:36, 10.66it/s]

  6%|██                                 | 2497/42525 [03:48<1:01:10, 10.90it/s]

  6%|██                                 | 2501/42525 [03:48<1:02:00, 10.76it/s]

  6%|██▏                                  | 2505/42525 [03:49<59:55, 11.13it/s]

  6%|██                                 | 2509/42525 [03:49<1:01:02, 10.93it/s]

  6%|██▏                                  | 2513/42525 [03:50<59:09, 11.27it/s]

  6%|██▏                                  | 2517/42525 [03:50<57:57, 11.50it/s]

  6%|██▏                                  | 2521/42525 [03:50<57:56, 11.51it/s]

  6%|██▏                                  | 2525/42525 [03:51<57:31, 11.59it/s]

  6%|██▏                                  | 2529/42525 [03:51<59:40, 11.17it/s]

  6%|██                                 | 2533/42525 [03:51<1:01:35, 10.82it/s]

  6%|██                                 | 2537/42525 [03:52<1:01:38, 10.81it/s]

  6%|██                                 | 2541/42525 [03:52<1:01:24, 10.85it/s]

  6%|██                                 | 2545/42525 [03:52<1:00:49, 10.95it/s]

  6%|██                                 | 2549/42525 [03:53<1:01:10, 10.89it/s]

  6%|██▏                                  | 2553/42525 [03:53<59:19, 11.23it/s]

  6%|██▏                                  | 2557/42525 [03:53<58:16, 11.43it/s]

  6%|██▏                                  | 2559/42525 [03:54<58:20, 11.42it/s]

  6%|██                                 | 2563/42525 [03:54<1:00:43, 10.97it/s]

  6%|██                                 | 2567/42525 [03:54<1:00:11, 11.06it/s]

  6%|██▏                                  | 2571/42525 [03:55<59:32, 11.18it/s]

  6%|██▏                                  | 2575/42525 [03:55<59:02, 11.28it/s]

  6%|██                                 | 2579/42525 [03:55<1:00:21, 11.03it/s]

  6%|██▏                                | 2583/42525 [03:56<1:00:31, 11.00it/s]

  6%|██▏                                | 2587/42525 [03:56<1:02:21, 10.68it/s]

  6%|██▏                                | 2591/42525 [03:57<1:02:36, 10.63it/s]

  6%|██▏                                | 2593/42525 [03:57<1:01:17, 10.86it/s]

  6%|██▏                                | 2597/42525 [03:57<1:01:48, 10.77it/s]

  6%|██▎                                  | 2601/42525 [03:58<59:52, 11.11it/s]

  6%|██▎                                  | 2605/42525 [03:58<59:21, 11.21it/s]

  6%|██▏                                | 2609/42525 [03:58<1:00:46, 10.95it/s]

  6%|██▏                                | 2613/42525 [03:59<1:01:24, 10.83it/s]

  6%|██▏                                | 2615/42525 [03:59<1:02:43, 10.61it/s]

  6%|██▏                                | 2619/42525 [03:59<1:02:43, 10.60it/s]

  6%|██▏                                | 2623/42525 [04:00<1:02:46, 10.60it/s]

  6%|██▏                                | 2627/42525 [04:00<1:02:32, 10.63it/s]

  6%|██▏                                | 2631/42525 [04:00<1:03:44, 10.43it/s]

  6%|██▏                                | 2635/42525 [04:01<1:00:09, 11.05it/s]

  6%|██▎                                  | 2639/42525 [04:01<59:05, 11.25it/s]

  6%|██▏                                | 2643/42525 [04:01<1:00:39, 10.96it/s]

  6%|██▏                                | 2645/42525 [04:02<1:00:13, 11.04it/s]

  6%|██▏                                | 2647/42525 [04:02<1:02:25, 10.65it/s]

  6%|██▏                                | 2649/42525 [04:02<1:04:12, 10.35it/s]

  6%|██▏                                | 2653/42525 [04:02<1:04:22, 10.32it/s]

  6%|██▏                                | 2657/42525 [04:03<1:04:40, 10.27it/s]

  6%|██▏                                | 2659/42525 [04:03<1:06:09, 10.04it/s]

  6%|██▏                                | 2663/42525 [04:03<1:05:46, 10.10it/s]

  6%|██▏                                | 2667/42525 [04:04<1:02:27, 10.63it/s]

  6%|██▏                                | 2671/42525 [04:04<1:03:09, 10.52it/s]

  6%|██▎                                  | 2675/42525 [04:04<59:52, 11.09it/s]

  6%|██▎                                  | 2679/42525 [04:05<58:33, 11.34it/s]

  6%|██▎                                  | 2683/42525 [04:05<57:35, 11.53it/s]

  6%|██▎                                  | 2687/42525 [04:05<57:50, 11.48it/s]

  6%|██▎                                  | 2691/42525 [04:06<57:54, 11.47it/s]

  6%|██▎                                  | 2695/42525 [04:06<59:06, 11.23it/s]

  6%|██▏                                | 2699/42525 [04:07<1:02:30, 10.62it/s]

  6%|██▏                                | 2701/42525 [04:07<1:00:07, 11.04it/s]

  6%|██▏                                | 2705/42525 [04:07<1:01:19, 10.82it/s]

  6%|██▏                                | 2709/42525 [04:08<1:00:24, 10.99it/s]

  6%|██▎                                  | 2713/42525 [04:08<58:58, 11.25it/s]

  6%|██▏                                | 2717/42525 [04:08<1:02:00, 10.70it/s]

  6%|██▏                                | 2721/42525 [04:09<1:02:16, 10.65it/s]

  6%|██▏                                | 2725/42525 [04:09<1:03:24, 10.46it/s]

  6%|██▏                                | 2729/42525 [04:09<1:00:29, 10.96it/s]

  6%|██▏                                | 2733/42525 [04:10<1:00:47, 10.91it/s]

  6%|██▎                                | 2737/42525 [04:10<1:01:28, 10.79it/s]

  6%|██▎                                | 2741/42525 [04:10<1:00:18, 10.99it/s]

  6%|██▎                                | 2745/42525 [04:11<1:01:27, 10.79it/s]

  6%|██▍                                  | 2749/42525 [04:11<59:32, 11.14it/s]

  6%|██▍                                  | 2753/42525 [04:12<56:04, 11.82it/s]

  6%|██▍                                  | 2757/42525 [04:12<58:45, 11.28it/s]

  6%|██▍                                  | 2761/42525 [04:12<56:15, 11.78it/s]

  6%|██▍                                  | 2763/42525 [04:12<55:47, 11.88it/s]

  7%|██▍                                  | 2767/42525 [04:13<57:51, 11.45it/s]

  7%|██▍                                  | 2771/42525 [04:13<59:22, 11.16it/s]

  7%|██▎                                | 2773/42525 [04:13<1:02:27, 10.61it/s]

  7%|██▎                                | 2775/42525 [04:14<1:04:05, 10.34it/s]

  7%|██▎                                | 2779/42525 [04:14<1:03:05, 10.50it/s]

  7%|██▎                                | 2783/42525 [04:14<1:00:47, 10.90it/s]

  7%|██▍                                  | 2787/42525 [04:15<59:54, 11.06it/s]

  7%|██▍                                  | 2791/42525 [04:15<59:21, 11.16it/s]

  7%|██▍                                  | 2795/42525 [04:15<59:06, 11.20it/s]

  7%|██▎                                | 2799/42525 [04:16<1:00:25, 10.96it/s]

  7%|██▎                                | 2803/42525 [04:16<1:01:02, 10.85it/s]

  7%|██▍                                  | 2807/42525 [04:16<59:56, 11.04it/s]

  7%|██▍                                  | 2811/42525 [04:17<59:56, 11.04it/s]

  7%|██▍                                  | 2815/42525 [04:17<58:59, 11.22it/s]

  7%|██▎                                | 2819/42525 [04:18<1:01:41, 10.73it/s]

  7%|██▎                                | 2823/42525 [04:18<1:00:27, 10.95it/s]

  7%|██▎                                | 2827/42525 [04:18<1:00:51, 10.87it/s]

  7%|██▎                                | 2831/42525 [04:19<1:01:01, 10.84it/s]

  7%|██▍                                  | 2835/42525 [04:19<59:41, 11.08it/s]

  7%|██▎                                | 2839/42525 [04:19<1:02:13, 10.63it/s]

  7%|██▎                                | 2843/42525 [04:20<1:02:04, 10.66it/s]

  7%|██▎                                | 2847/42525 [04:20<1:02:00, 10.66it/s]

  7%|██▎                                | 2851/42525 [04:21<1:02:26, 10.59it/s]

  7%|██▎                                | 2855/42525 [04:21<1:00:00, 11.02it/s]

  7%|██▎                                | 2859/42525 [04:21<1:00:02, 11.01it/s]

  7%|██▍                                  | 2863/42525 [04:22<59:04, 11.19it/s]

  7%|██▍                                  | 2867/42525 [04:22<58:01, 11.39it/s]

  7%|██▎                                | 2871/42525 [04:22<1:00:04, 11.00it/s]

  7%|██▌                                  | 2875/42525 [04:23<58:56, 11.21it/s]

  7%|██▌                                  | 2879/42525 [04:23<57:40, 11.46it/s]

  7%|██▌                                  | 2881/42525 [04:23<57:40, 11.46it/s]

  7%|██▌                                  | 2885/42525 [04:24<59:24, 11.12it/s]

  7%|██▌                                  | 2889/42525 [04:24<57:54, 11.41it/s]

  7%|██▍                                | 2893/42525 [04:24<1:01:11, 10.79it/s]

  7%|██▌                                  | 2897/42525 [04:25<59:40, 11.07it/s]

  7%|██▌                                  | 2901/42525 [04:25<59:22, 11.12it/s]

  7%|██▌                                  | 2905/42525 [04:25<59:19, 11.13it/s]

  7%|██▍                                | 2909/42525 [04:26<1:00:20, 10.94it/s]

  7%|██▍                                | 2913/42525 [04:26<1:01:23, 10.75it/s]

  7%|██▍                                | 2917/42525 [04:26<1:00:10, 10.97it/s]

  7%|██▌                                  | 2921/42525 [04:27<59:01, 11.18it/s]

  7%|██▌                                  | 2925/42525 [04:27<57:53, 11.40it/s]

  7%|██▌                                  | 2929/42525 [04:27<58:26, 11.29it/s]

  7%|██▍                                | 2933/42525 [04:28<1:00:02, 10.99it/s]

  7%|██▌                                  | 2937/42525 [04:28<59:36, 11.07it/s]

  7%|██▍                                | 2941/42525 [04:29<1:01:33, 10.72it/s]

  7%|██▍                                | 2945/42525 [04:29<1:01:07, 10.79it/s]

  7%|██▌                                  | 2947/42525 [04:29<59:32, 11.08it/s]

  7%|██▍                                | 2951/42525 [04:30<1:01:22, 10.75it/s]

  7%|██▍                                | 2953/42525 [04:30<1:02:20, 10.58it/s]

  7%|██▍                                | 2957/42525 [04:30<1:01:50, 10.66it/s]

  7%|██▌                                  | 2961/42525 [04:30<59:43, 11.04it/s]

  7%|██▌                                  | 2965/42525 [04:31<58:59, 11.18it/s]

  7%|██▌                                  | 2969/42525 [04:31<57:49, 11.40it/s]

  7%|██▌                                  | 2971/42525 [04:31<59:38, 11.05it/s]

  7%|██▍                                | 2975/42525 [04:32<1:03:03, 10.45it/s]

  7%|██▍                                | 2979/42525 [04:32<1:00:47, 10.84it/s]

  7%|██▌                                  | 2983/42525 [04:32<58:39, 11.23it/s]

  7%|██▍                                | 2987/42525 [04:33<1:00:17, 10.93it/s]

  7%|██▍                                | 2991/42525 [04:33<1:00:16, 10.93it/s]

  7%|██▍                                | 2995/42525 [04:34<1:01:22, 10.74it/s]

  7%|██▍                                | 2999/42525 [04:34<1:03:05, 10.44it/s]

  7%|██▍                                | 3003/42525 [04:34<1:02:20, 10.57it/s]

  7%|██▍                                | 3007/42525 [04:35<1:01:58, 10.63it/s]

  7%|██▍                                | 3011/42525 [04:35<1:04:03, 10.28it/s]

  7%|██▍                                | 3015/42525 [04:35<1:01:09, 10.77it/s]

  7%|██▋                                  | 3019/42525 [04:36<59:19, 11.10it/s]

  7%|██▋                                  | 3023/42525 [04:36<58:28, 11.26it/s]

  7%|██▋                                  | 3027/42525 [04:37<57:52, 11.37it/s]

  7%|██▋                                  | 3031/42525 [04:37<58:46, 11.20it/s]

  7%|██▋                                  | 3035/42525 [04:37<59:08, 11.13it/s]

  7%|██▋                                  | 3039/42525 [04:38<58:37, 11.23it/s]

  7%|██▌                                | 3043/42525 [04:38<1:00:17, 10.92it/s]

  7%|██▌                                | 3047/42525 [04:38<1:00:20, 10.90it/s]

  7%|██▋                                  | 3051/42525 [04:39<59:16, 11.10it/s]

  7%|██▋                                  | 3055/42525 [04:39<57:09, 11.51it/s]

  7%|██▋                                  | 3059/42525 [04:39<57:17, 11.48it/s]

  7%|██▋                                  | 3063/42525 [04:40<57:44, 11.39it/s]

  7%|██▋                                  | 3067/42525 [04:40<56:42, 11.60it/s]

  7%|██▋                                  | 3071/42525 [04:40<56:56, 11.55it/s]

  7%|██▋                                  | 3073/42525 [04:41<57:39, 11.40it/s]

  7%|██▋                                  | 3077/42525 [04:41<59:11, 11.11it/s]

  7%|██▌                                | 3081/42525 [04:41<1:02:16, 10.56it/s]

  7%|██▌                                | 3085/42525 [04:42<1:01:49, 10.63it/s]

  7%|██▋                                  | 3089/42525 [04:42<58:56, 11.15it/s]

  7%|██▋                                  | 3093/42525 [04:42<57:55, 11.35it/s]

  7%|██▋                                  | 3097/42525 [04:43<57:15, 11.48it/s]

  7%|██▌                                | 3101/42525 [04:43<1:00:17, 10.90it/s]

  7%|██▌                                | 3105/42525 [04:44<1:00:04, 10.94it/s]

  7%|██▌                                | 3109/42525 [04:44<1:00:03, 10.94it/s]

  7%|██▋                                  | 3113/42525 [04:44<59:44, 11.00it/s]

  7%|██▌                                | 3117/42525 [04:45<1:00:43, 10.82it/s]

  7%|██▌                                | 3121/42525 [04:45<1:02:52, 10.44it/s]

  7%|██▋                                  | 3125/42525 [04:45<59:42, 11.00it/s]

  7%|██▋                                  | 3129/42525 [04:46<58:19, 11.26it/s]

  7%|██▋                                  | 3133/42525 [04:46<59:51, 10.97it/s]

  7%|██▌                                | 3137/42525 [04:47<1:02:11, 10.56it/s]

  7%|██▌                                | 3141/42525 [04:47<1:02:30, 10.50it/s]

  7%|██▌                                | 3145/42525 [04:47<1:00:46, 10.80it/s]

  7%|██▌                                | 3149/42525 [04:48<1:00:09, 10.91it/s]

  7%|██▌                                | 3153/42525 [04:48<1:01:29, 10.67it/s]

  7%|██▋                                  | 3157/42525 [04:48<59:34, 11.01it/s]

  7%|██▊                                  | 3161/42525 [04:49<59:42, 10.99it/s]

  7%|██▌                                | 3165/42525 [04:49<1:01:37, 10.65it/s]

  7%|██▊                                  | 3169/42525 [04:49<59:59, 10.93it/s]

  7%|██▊                                  | 3173/42525 [04:50<58:39, 11.18it/s]

  7%|██▊                                  | 3177/42525 [04:50<58:16, 11.25it/s]

  7%|██▊                                  | 3181/42525 [04:51<58:01, 11.30it/s]

  7%|██▊                                  | 3185/42525 [04:51<57:33, 11.39it/s]

  7%|██▊                                  | 3189/42525 [04:51<56:58, 11.51it/s]

  8%|██▊                                  | 3191/42525 [04:51<57:18, 11.44it/s]

  8%|██▊                                  | 3195/42525 [04:52<59:50, 10.95it/s]

  8%|██▊                                  | 3199/42525 [04:52<59:47, 10.96it/s]

  8%|██▋                                | 3203/42525 [04:53<1:00:03, 10.91it/s]

  8%|██▊                                  | 3207/42525 [04:53<58:12, 11.26it/s]

  8%|██▊                                  | 3211/42525 [04:53<59:57, 10.93it/s]

  8%|██▊                                  | 3213/42525 [04:53<59:47, 10.96it/s]

  8%|██▋                                | 3217/42525 [04:54<1:00:44, 10.78it/s]

  8%|██▊                                  | 3221/42525 [04:54<59:27, 11.02it/s]

  8%|██▊                                  | 3225/42525 [04:54<58:21, 11.22it/s]

  8%|██▊                                  | 3229/42525 [04:55<59:26, 11.02it/s]

  8%|██▋                                | 3233/42525 [04:55<1:00:26, 10.84it/s]

  8%|██▊                                  | 3237/42525 [04:56<59:31, 11.00it/s]

  8%|██▊                                  | 3241/42525 [04:56<58:15, 11.24it/s]

  8%|██▊                                  | 3245/42525 [04:56<57:22, 11.41it/s]

  8%|██▊                                  | 3249/42525 [04:57<57:42, 11.34it/s]

  8%|██▋                                | 3251/42525 [04:57<1:00:07, 10.89it/s]

  8%|██▋                                | 3255/42525 [04:57<1:00:13, 10.87it/s]

  8%|██▊                                  | 3259/42525 [04:58<53:48, 12.16it/s]

  8%|██▊                                  | 3263/42525 [04:58<51:57, 12.59it/s]

  8%|██▊                                  | 3267/42525 [04:58<56:21, 11.61it/s]

  8%|██▊                                  | 3269/42525 [04:58<57:15, 11.43it/s]

  8%|██▋                                | 3273/42525 [04:59<1:01:02, 10.72it/s]

  8%|██▊                                  | 3277/42525 [04:59<59:41, 10.96it/s]

  8%|██▋                                | 3281/42525 [05:00<1:00:02, 10.89it/s]

  8%|██▊                                  | 3285/42525 [05:00<58:30, 11.18it/s]

  8%|██▊                                  | 3289/42525 [05:00<58:15, 11.22it/s]

  8%|██▊                                  | 3291/42525 [05:00<57:47, 11.31it/s]

  8%|██▊                                  | 3295/42525 [05:01<59:05, 11.07it/s]

  8%|██▊                                  | 3299/42525 [05:01<57:16, 11.42it/s]

  8%|██▊                                  | 3303/42525 [05:01<57:40, 11.33it/s]

  8%|██▉                                  | 3307/42525 [05:02<57:27, 11.37it/s]

  8%|██▉                                  | 3311/42525 [05:02<58:45, 11.12it/s]

  8%|██▉                                  | 3315/42525 [05:03<57:17, 11.41it/s]

  8%|██▉                                  | 3319/42525 [05:03<57:23, 11.39it/s]

  8%|██▉                                  | 3323/42525 [05:03<58:28, 11.17it/s]

  8%|██▉                                  | 3327/42525 [05:04<57:08, 11.43it/s]

  8%|██▉                                  | 3331/42525 [05:04<59:29, 10.98it/s]

  8%|██▉                                  | 3335/42525 [05:04<59:59, 10.89it/s]

  8%|██▋                                | 3339/42525 [05:05<1:00:20, 10.82it/s]

  8%|██▊                                | 3343/42525 [05:05<1:00:46, 10.75it/s]

  8%|██▉                                  | 3347/42525 [05:05<58:41, 11.12it/s]

  8%|██▉                                  | 3351/42525 [05:06<59:57, 10.89it/s]

  8%|██▉                                  | 3355/42525 [05:06<58:05, 11.24it/s]

  8%|██▉                                  | 3359/42525 [05:06<56:58, 11.46it/s]

  8%|██▉                                  | 3363/42525 [05:07<57:58, 11.26it/s]

  8%|██▉                                  | 3367/42525 [05:07<59:34, 10.95it/s]

  8%|██▉                                  | 3371/42525 [05:08<59:41, 10.93it/s]

  8%|██▊                                | 3375/42525 [05:08<1:00:44, 10.74it/s]

  8%|██▊                                | 3379/42525 [05:08<1:00:27, 10.79it/s]

  8%|██▉                                  | 3383/42525 [05:09<58:21, 11.18it/s]

  8%|██▉                                  | 3387/42525 [05:09<56:38, 11.52it/s]

  8%|██▉                                  | 3391/42525 [05:09<58:09, 11.22it/s]

  8%|██▉                                  | 3395/42525 [05:10<56:58, 11.45it/s]

  8%|██▉                                  | 3399/42525 [05:10<56:37, 11.52it/s]

  8%|██▉                                  | 3403/42525 [05:10<58:11, 11.20it/s]

  8%|██▉                                  | 3407/42525 [05:11<57:12, 11.40it/s]

  8%|██▉                                  | 3411/42525 [05:11<59:13, 11.01it/s]

  8%|██▉                                  | 3415/42525 [05:12<58:56, 11.06it/s]

  8%|██▉                                  | 3419/42525 [05:12<59:28, 10.96it/s]

  8%|██▊                                | 3423/42525 [05:12<1:00:30, 10.77it/s]

  8%|██▊                                | 3427/42525 [05:13<1:00:03, 10.85it/s]

  8%|██▊                                | 3431/42525 [05:13<1:01:23, 10.61it/s]

  8%|██▊                                | 3435/42525 [05:13<1:01:04, 10.67it/s]

  8%|██▉                                  | 3439/42525 [05:14<59:23, 10.97it/s]

  8%|██▉                                  | 3443/42525 [05:14<57:22, 11.35it/s]

  8%|██▉                                  | 3447/42525 [05:14<59:28, 10.95it/s]

  8%|███                                  | 3451/42525 [05:15<59:24, 10.96it/s]

  8%|███                                  | 3455/42525 [05:15<57:10, 11.39it/s]

  8%|███                                  | 3459/42525 [05:16<57:51, 11.25it/s]

  8%|███                                  | 3463/42525 [05:16<57:34, 11.31it/s]

  8%|███                                  | 3467/42525 [05:16<57:45, 11.27it/s]

  8%|███                                  | 3471/42525 [05:17<56:43, 11.48it/s]

  8%|███                                  | 3475/42525 [05:17<57:51, 11.25it/s]

  8%|███                                  | 3479/42525 [05:17<57:06, 11.40it/s]

  8%|██▊                                | 3483/42525 [05:18<1:00:29, 10.76it/s]

  8%|██▊                                | 3487/42525 [05:18<1:00:02, 10.84it/s]

  8%|██▊                                | 3491/42525 [05:18<1:01:31, 10.57it/s]

  8%|██▉                                | 3495/42525 [05:19<1:03:00, 10.33it/s]

  8%|██▉                                | 3497/42525 [05:19<1:03:25, 10.25it/s]

  8%|██▉                                | 3501/42525 [05:19<1:01:58, 10.49it/s]

  8%|███                                  | 3505/42525 [05:20<59:38, 10.90it/s]

  8%|██▉                                | 3509/42525 [05:20<1:00:34, 10.73it/s]

  8%|███                                  | 3513/42525 [05:20<58:17, 11.15it/s]

  8%|███                                  | 3517/42525 [05:21<59:22, 10.95it/s]

  8%|███                                  | 3521/42525 [05:21<59:21, 10.95it/s]

  8%|███                                  | 3525/42525 [05:22<59:14, 10.97it/s]

  8%|███                                  | 3529/42525 [05:22<58:26, 11.12it/s]

  8%|███                                  | 3533/42525 [05:22<57:54, 11.22it/s]

  8%|███                                  | 3537/42525 [05:23<56:53, 11.42it/s]

  8%|███                                  | 3541/42525 [05:23<57:25, 11.31it/s]

  8%|███                                  | 3543/42525 [05:23<59:19, 10.95it/s]

  8%|██▉                                | 3547/42525 [05:24<1:01:06, 10.63it/s]

  8%|██▉                                | 3551/42525 [05:24<1:01:51, 10.50it/s]

  8%|██▉                                | 3555/42525 [05:24<1:00:53, 10.67it/s]

  8%|██▉                                | 3559/42525 [05:25<1:01:47, 10.51it/s]

  8%|███                                  | 3563/42525 [05:25<59:54, 10.84it/s]

  8%|███                                  | 3567/42525 [05:25<58:50, 11.03it/s]

  8%|███                                  | 3571/42525 [05:26<59:07, 10.98it/s]

  8%|███                                  | 3575/42525 [05:26<58:13, 11.15it/s]

  8%|███                                  | 3579/42525 [05:27<57:04, 11.37it/s]

  8%|██▉                                | 3583/42525 [05:27<1:00:07, 10.79it/s]

  8%|██▉                                | 3587/42525 [05:27<1:00:36, 10.71it/s]

  8%|███                                  | 3591/42525 [05:28<59:45, 10.86it/s]

  8%|███▏                                 | 3595/42525 [05:28<59:42, 10.87it/s]

  8%|███▏                                 | 3599/42525 [05:28<59:20, 10.93it/s]

  8%|██▉                                | 3603/42525 [05:29<1:00:07, 10.79it/s]

  8%|██▉                                | 3607/42525 [05:29<1:00:03, 10.80it/s]

  8%|███▏                                 | 3611/42525 [05:29<59:07, 10.97it/s]

  9%|███▏                                 | 3615/42525 [05:30<59:35, 10.88it/s]

  9%|███▏                                 | 3619/42525 [05:30<57:50, 11.21it/s]

  9%|██▉                                | 3623/42525 [05:31<1:00:52, 10.65it/s]

  9%|███▏                                 | 3627/42525 [05:31<58:10, 11.14it/s]

  9%|██▉                                | 3631/42525 [05:31<1:01:22, 10.56it/s]

  9%|██▉                                | 3635/42525 [05:32<1:00:31, 10.71it/s]

  9%|██▉                                | 3639/42525 [05:32<1:00:44, 10.67it/s]

  9%|███▏                                 | 3643/42525 [05:32<59:44, 10.85it/s]

  9%|███                                | 3647/42525 [05:33<1:00:07, 10.78it/s]

  9%|███                                | 3651/42525 [05:33<1:02:06, 10.43it/s]

  9%|███                                | 3655/42525 [05:34<1:03:03, 10.27it/s]

  9%|███                                | 3658/42525 [05:34<1:05:34,  9.88it/s]

  9%|███                                | 3661/42525 [05:34<1:05:02,  9.96it/s]

  9%|███                                | 3664/42525 [05:35<1:02:31, 10.36it/s]

  9%|███                                | 3666/42525 [05:35<1:02:35, 10.35it/s]

  9%|███                                | 3670/42525 [05:35<1:03:41, 10.17it/s]

  9%|███                                | 3674/42525 [05:35<1:03:12, 10.24it/s]

  9%|███▏                                 | 3678/42525 [05:36<59:58, 10.80it/s]

  9%|███                                | 3680/42525 [05:36<1:00:23, 10.72it/s]

  9%|███                                | 3684/42525 [05:36<1:02:32, 10.35it/s]

  9%|███                                | 3686/42525 [05:37<1:01:36, 10.51it/s]

  9%|███                                | 3690/42525 [05:37<1:03:19, 10.22it/s]

  9%|███                                | 3694/42525 [05:37<1:01:28, 10.53it/s]

  9%|███                                | 3698/42525 [05:38<1:00:07, 10.76it/s]

  9%|███▏                                 | 3702/42525 [05:38<59:58, 10.79it/s]

  9%|███                                | 3706/42525 [05:38<1:00:14, 10.74it/s]

  9%|███▏                                 | 3710/42525 [05:39<59:32, 10.87it/s]

  9%|███▏                                 | 3714/42525 [05:39<57:49, 11.19it/s]

  9%|███▏                                 | 3718/42525 [05:40<58:05, 11.13it/s]

  9%|███▏                                 | 3722/42525 [05:40<58:16, 11.10it/s]

  9%|███▏                                 | 3726/42525 [05:40<57:42, 11.21it/s]

  9%|███▏                                 | 3728/42525 [05:40<57:30, 11.24it/s]

  9%|███                                | 3732/42525 [05:41<1:00:49, 10.63it/s]

  9%|███▎                                 | 3736/42525 [05:41<59:24, 10.88it/s]

  9%|███▎                                 | 3740/42525 [05:42<59:17, 10.90it/s]

  9%|███                                | 3744/42525 [05:42<1:00:05, 10.76it/s]

  9%|███                                | 3748/42525 [05:42<1:01:00, 10.59it/s]

  9%|███▎                                 | 3752/42525 [05:43<59:10, 10.92it/s]

  9%|███▎                                 | 3756/42525 [05:43<58:26, 11.06it/s]

  9%|███                                | 3758/42525 [05:43<1:00:28, 10.68it/s]

  9%|███                                | 3762/42525 [05:44<1:01:24, 10.52it/s]

  9%|███▎                                 | 3766/42525 [05:44<59:01, 10.95it/s]

  9%|███▎                                 | 3770/42525 [05:44<57:08, 11.31it/s]

  9%|███▎                                 | 3774/42525 [05:45<58:50, 10.98it/s]

  9%|███▎                                 | 3778/42525 [05:45<58:30, 11.04it/s]

  9%|███▎                                 | 3782/42525 [05:45<59:37, 10.83it/s]

  9%|███▎                                 | 3786/42525 [05:46<59:25, 10.87it/s]

  9%|███▎                                 | 3790/42525 [05:46<57:12, 11.28it/s]

  9%|███▎                                 | 3794/42525 [05:47<57:59, 11.13it/s]

  9%|███▎                                 | 3798/42525 [05:47<57:46, 11.17it/s]

  9%|███▎                                 | 3802/42525 [05:47<58:26, 11.04it/s]

  9%|███▎                                 | 3806/42525 [05:48<56:52, 11.35it/s]

  9%|███▎                                 | 3810/42525 [05:48<58:56, 10.95it/s]

  9%|███▏                               | 3814/42525 [05:48<1:00:27, 10.67it/s]

  9%|███▎                                 | 3818/42525 [05:49<58:37, 11.00it/s]

  9%|███▏                               | 3822/42525 [05:49<1:01:36, 10.47it/s]

  9%|███▎                                 | 3826/42525 [05:49<58:46, 10.97it/s]

  9%|███▏                               | 3830/42525 [05:50<1:00:31, 10.65it/s]

  9%|███▏                               | 3834/42525 [05:50<1:01:50, 10.43it/s]

  9%|███▏                               | 3836/42525 [05:50<1:00:35, 10.64it/s]

  9%|███▏                               | 3840/42525 [05:51<1:01:44, 10.44it/s]

  9%|███▎                                 | 3844/42525 [05:51<59:48, 10.78it/s]

  9%|███▎                                 | 3846/42525 [05:51<58:43, 10.98it/s]

  9%|███▏                               | 3850/42525 [05:52<1:00:20, 10.68it/s]

  9%|███▏                               | 3854/42525 [05:52<1:00:19, 10.68it/s]

  9%|███▎                                 | 3858/42525 [05:52<58:29, 11.02it/s]

  9%|███▎                                 | 3860/42525 [05:53<58:19, 11.05it/s]

  9%|███▎                                 | 3864/42525 [05:53<59:56, 10.75it/s]

  9%|███▏                               | 3866/42525 [05:53<1:01:13, 10.52it/s]

  9%|███▏                               | 3870/42525 [05:54<1:01:51, 10.41it/s]

  9%|███▏                               | 3874/42525 [05:54<1:00:36, 10.63it/s]

  9%|███▎                                 | 3878/42525 [05:54<58:13, 11.06it/s]

  9%|███▍                                 | 3882/42525 [05:55<59:03, 10.91it/s]

  9%|███▍                                 | 3886/42525 [05:55<57:43, 11.16it/s]

  9%|███▍                                 | 3890/42525 [05:55<58:37, 10.98it/s]

  9%|███▍                                 | 3894/42525 [05:56<58:52, 10.94it/s]

  9%|███▍                                 | 3898/42525 [05:56<57:28, 11.20it/s]

  9%|███▍                                 | 3902/42525 [05:56<57:50, 11.13it/s]

  9%|███▍                                 | 3906/42525 [05:57<59:48, 10.76it/s]

  9%|███▍                                 | 3910/42525 [05:57<58:18, 11.04it/s]

  9%|███▏                               | 3914/42525 [05:58<1:01:18, 10.50it/s]

  9%|███▍                                 | 3918/42525 [05:58<59:02, 10.90it/s]

  9%|███▏                               | 3922/42525 [05:58<1:00:44, 10.59it/s]

  9%|███▍                                 | 3926/42525 [05:59<59:15, 10.85it/s]

  9%|███▏                               | 3930/42525 [05:59<1:00:03, 10.71it/s]

  9%|███▍                                 | 3934/42525 [05:59<58:46, 10.94it/s]

  9%|███▍                                 | 3938/42525 [06:00<58:43, 10.95it/s]

  9%|███▏                               | 3942/42525 [06:00<1:00:00, 10.71it/s]

  9%|███▍                                 | 3946/42525 [06:01<59:48, 10.75it/s]

  9%|███▍                                 | 3950/42525 [06:01<57:59, 11.09it/s]

  9%|███▍                                 | 3954/42525 [06:01<59:42, 10.77it/s]

  9%|███▍                                 | 3958/42525 [06:02<58:25, 11.00it/s]

  9%|███▍                                 | 3962/42525 [06:02<58:45, 10.94it/s]

  9%|███▍                                 | 3966/42525 [06:02<59:56, 10.72it/s]

  9%|███▍                                 | 3968/42525 [06:03<59:50, 10.74it/s]

  9%|███▍                                 | 3972/42525 [06:03<59:45, 10.75it/s]

  9%|███▎                               | 3976/42525 [06:03<1:00:11, 10.67it/s]

  9%|███▍                                 | 3980/42525 [06:04<59:44, 10.75it/s]

  9%|███▍                                 | 3984/42525 [06:04<57:22, 11.20it/s]

  9%|███▍                                 | 3988/42525 [06:04<56:03, 11.46it/s]

  9%|███▍                                 | 3992/42525 [06:05<57:47, 11.11it/s]

  9%|███▍                                 | 3996/42525 [06:05<59:50, 10.73it/s]

  9%|███▎                               | 4000/42525 [06:06<1:00:35, 10.60it/s]

  9%|███▎                               | 4004/42525 [06:06<1:01:15, 10.48it/s]

  9%|███▍                                 | 4008/42525 [06:06<59:10, 10.85it/s]

  9%|███▎                               | 4012/42525 [06:07<1:00:20, 10.64it/s]

  9%|███▍                                 | 4016/42525 [06:07<58:01, 11.06it/s]

  9%|███▍                                 | 4018/42525 [06:07<57:12, 11.22it/s]

  9%|███▎                               | 4020/42525 [06:07<1:00:03, 10.69it/s]

  9%|███▎                               | 4024/42525 [06:08<1:00:22, 10.63it/s]

  9%|███▌                                 | 4028/42525 [06:08<59:10, 10.84it/s]

  9%|███▌                                 | 4032/42525 [06:08<59:09, 10.85it/s]

  9%|███▌                                 | 4036/42525 [06:09<57:32, 11.15it/s]

 10%|███▌                                 | 4040/42525 [06:09<57:18, 11.19it/s]

 10%|███▌                                 | 4044/42525 [06:10<58:01, 11.05it/s]

 10%|███▌                                 | 4048/42525 [06:10<57:37, 11.13it/s]

 10%|███▌                                 | 4052/42525 [06:10<56:50, 11.28it/s]

 10%|███▌                                 | 4056/42525 [06:11<56:31, 11.34it/s]

 10%|███▌                                 | 4060/42525 [06:11<56:16, 11.39it/s]

 10%|███▌                                 | 4064/42525 [06:11<57:35, 11.13it/s]

 10%|███▌                                 | 4068/42525 [06:12<57:00, 11.24it/s]

 10%|███▌                                 | 4072/42525 [06:12<58:11, 11.01it/s]

 10%|███▌                                 | 4076/42525 [06:12<57:11, 11.21it/s]

 10%|███▌                                 | 4080/42525 [06:13<56:52, 11.27it/s]

 10%|███▌                                 | 4084/42525 [06:13<57:45, 11.09it/s]

 10%|███▌                                 | 4088/42525 [06:13<56:41, 11.30it/s]

 10%|███▌                                 | 4092/42525 [06:14<55:32, 11.53it/s]

 10%|███▌                                 | 4096/42525 [06:14<57:45, 11.09it/s]

 10%|███▌                                 | 4100/42525 [06:15<56:19, 11.37it/s]

 10%|███▌                                 | 4104/42525 [06:15<56:10, 11.40it/s]

 10%|███▌                                 | 4108/42525 [06:15<55:52, 11.46it/s]

 10%|███▌                                 | 4112/42525 [06:16<55:35, 11.52it/s]

 10%|███▌                                 | 4116/42525 [06:16<56:10, 11.39it/s]

 10%|███▌                                 | 4120/42525 [06:16<56:32, 11.32it/s]

 10%|███▌                                 | 4124/42525 [06:17<57:12, 11.19it/s]

 10%|███▌                                 | 4128/42525 [06:17<58:43, 10.90it/s]

 10%|███▌                                 | 4132/42525 [06:17<57:33, 11.12it/s]

 10%|███▌                                 | 4136/42525 [06:18<56:16, 11.37it/s]

 10%|███▌                                 | 4140/42525 [06:18<55:20, 11.56it/s]

 10%|███▌                                 | 4144/42525 [06:18<55:32, 11.52it/s]

 10%|███▌                                 | 4148/42525 [06:19<56:03, 11.41it/s]

 10%|███▌                                 | 4152/42525 [06:19<56:14, 11.37it/s]

 10%|███▌                                 | 4156/42525 [06:20<57:12, 11.18it/s]

 10%|███▌                                 | 4160/42525 [06:20<56:43, 11.27it/s]

 10%|███▌                                 | 4164/42525 [06:20<57:21, 11.15it/s]

 10%|███▋                                 | 4168/42525 [06:21<58:04, 11.01it/s]

 10%|███▋                                 | 4172/42525 [06:21<58:23, 10.95it/s]

 10%|███▋                                 | 4176/42525 [06:21<57:56, 11.03it/s]

 10%|███▋                                 | 4180/42525 [06:22<56:15, 11.36it/s]

 10%|███▋                                 | 4184/42525 [06:22<57:28, 11.12it/s]

 10%|███▋                                 | 4188/42525 [06:22<55:45, 11.46it/s]

 10%|███▋                                 | 4192/42525 [06:23<55:39, 11.48it/s]

 10%|███▋                                 | 4196/42525 [06:23<56:25, 11.32it/s]

 10%|███▋                                 | 4200/42525 [06:23<59:04, 10.81it/s]

 10%|███▋                                 | 4204/42525 [06:24<59:31, 10.73it/s]

 10%|███▍                               | 4208/42525 [06:24<1:01:06, 10.45it/s]

 10%|███▍                               | 4210/42525 [06:24<1:00:43, 10.52it/s]

 10%|███▍                               | 4214/42525 [06:25<1:01:20, 10.41it/s]

 10%|███▋                                 | 4218/42525 [06:25<59:16, 10.77it/s]

 10%|███▋                                 | 4222/42525 [06:26<55:51, 11.43it/s]

 10%|███▋                                 | 4226/42525 [06:26<55:15, 11.55it/s]

 10%|███▋                                 | 4230/42525 [06:26<53:07, 12.02it/s]

 10%|███▋                                 | 4234/42525 [06:27<52:16, 12.21it/s]

 10%|███▋                                 | 4238/42525 [06:27<55:34, 11.48it/s]

 10%|███▋                                 | 4242/42525 [06:27<52:37, 12.12it/s]

 10%|███▋                                 | 4246/42525 [06:28<54:30, 11.70it/s]

 10%|███▋                                 | 4250/42525 [06:28<52:19, 12.19it/s]

 10%|███▋                                 | 4254/42525 [06:28<53:56, 11.82it/s]

 10%|███▋                                 | 4258/42525 [06:29<51:31, 12.38it/s]

 10%|███▋                                 | 4262/42525 [06:29<54:24, 11.72it/s]

 10%|███▋                                 | 4266/42525 [06:29<56:01, 11.38it/s]

 10%|███▋                                 | 4268/42525 [06:29<53:08, 12.00it/s]

 10%|███▋                                 | 4272/42525 [06:30<54:25, 11.71it/s]

 10%|███▋                                 | 4276/42525 [06:30<55:16, 11.53it/s]

 10%|███▋                                 | 4280/42525 [06:30<57:04, 11.17it/s]

 10%|███▋                                 | 4284/42525 [06:31<53:16, 11.96it/s]

 10%|███▋                                 | 4288/42525 [06:31<51:20, 12.41it/s]

 10%|███▋                                 | 4292/42525 [06:31<53:31, 11.90it/s]

 10%|███▋                                 | 4296/42525 [06:32<53:36, 11.89it/s]

 10%|███▋                                 | 4300/42525 [06:32<53:24, 11.93it/s]

 10%|███▋                                 | 4304/42525 [06:32<54:52, 11.61it/s]

 10%|███▋                                 | 4306/42525 [06:33<59:07, 10.77it/s]

 10%|███▊                                 | 4310/42525 [06:33<56:29, 11.27it/s]

 10%|███▊                                 | 4314/42525 [06:33<53:46, 11.84it/s]

 10%|███▊                                 | 4318/42525 [06:34<55:41, 11.43it/s]

 10%|███▊                                 | 4322/42525 [06:34<51:43, 12.31it/s]

 10%|███▊                                 | 4326/42525 [06:34<54:23, 11.70it/s]

 10%|███▊                                 | 4330/42525 [06:35<55:29, 11.47it/s]

 10%|███▊                                 | 4334/42525 [06:35<53:41, 11.85it/s]

 10%|███▊                                 | 4338/42525 [06:35<53:45, 11.84it/s]

 10%|███▊                                 | 4342/42525 [06:36<55:10, 11.53it/s]

 10%|███▊                                 | 4346/42525 [06:36<54:18, 11.72it/s]

 10%|███▊                                 | 4350/42525 [06:36<51:27, 12.36it/s]

 10%|███▊                                 | 4354/42525 [06:37<49:19, 12.90it/s]

 10%|███▊                                 | 4358/42525 [06:37<53:58, 11.79it/s]

 10%|███▊                                 | 4362/42525 [06:37<57:59, 10.97it/s]

 10%|███▊                                 | 4364/42525 [06:38<59:10, 10.75it/s]

 10%|███▌                               | 4368/42525 [06:38<1:00:40, 10.48it/s]

 10%|███▌                               | 4372/42525 [06:38<1:00:36, 10.49it/s]

 10%|███▌                               | 4376/42525 [06:39<1:01:10, 10.39it/s]

 10%|███▌                               | 4380/42525 [06:39<1:00:16, 10.55it/s]

 10%|███▌                               | 4382/42525 [06:39<1:00:22, 10.53it/s]

 10%|███▌                               | 4386/42525 [06:40<1:01:43, 10.30it/s]

 10%|███▌                               | 4390/42525 [06:40<1:01:08, 10.40it/s]

 10%|███▊                                 | 4394/42525 [06:41<59:05, 10.75it/s]

 10%|███▊                                 | 4398/42525 [06:41<58:09, 10.93it/s]

 10%|███▊                                 | 4402/42525 [06:41<59:20, 10.71it/s]

 10%|███▊                                 | 4406/42525 [06:42<58:34, 10.85it/s]

 10%|███▊                                 | 4410/42525 [06:42<58:20, 10.89it/s]

 10%|███▊                                 | 4414/42525 [06:42<58:16, 10.90it/s]

 10%|███▊                                 | 4418/42525 [06:43<56:56, 11.15it/s]

 10%|███▊                                 | 4422/42525 [06:43<57:57, 10.96it/s]

 10%|███▊                                 | 4424/42525 [06:43<58:21, 10.88it/s]

 10%|███▋                               | 4426/42525 [06:43<1:00:03, 10.57it/s]

 10%|███▋                               | 4430/42525 [06:44<1:00:39, 10.47it/s]

 10%|███▊                                 | 4434/42525 [06:44<59:29, 10.67it/s]

 10%|███▋                               | 4438/42525 [06:45<1:01:32, 10.31it/s]

 10%|███▊                                 | 4442/42525 [06:45<58:48, 10.79it/s]

 10%|███▊                                 | 4446/42525 [06:45<56:57, 11.14it/s]

 10%|███▊                                 | 4450/42525 [06:46<57:12, 11.09it/s]

 10%|███▉                                 | 4454/42525 [06:46<58:36, 10.83it/s]

 10%|███▉                                 | 4456/42525 [06:46<58:56, 10.76it/s]

 10%|███▋                               | 4460/42525 [06:47<1:01:35, 10.30it/s]

 10%|███▉                                 | 4464/42525 [06:47<58:59, 10.75it/s]

 11%|███▉                                 | 4468/42525 [06:47<59:19, 10.69it/s]

 11%|███▉                                 | 4472/42525 [06:48<57:54, 10.95it/s]

 11%|███▋                               | 4476/42525 [06:48<1:00:34, 10.47it/s]

 11%|███▉                                 | 4480/42525 [06:49<59:43, 10.62it/s]

 11%|███▋                               | 4484/42525 [06:49<1:00:27, 10.49it/s]

 11%|███▉                                 | 4488/42525 [06:49<59:18, 10.69it/s]

 11%|███▉                                 | 4492/42525 [06:50<58:06, 10.91it/s]

 11%|███▉                                 | 4496/42525 [06:50<56:36, 11.20it/s]

 11%|███▉                                 | 4498/42525 [06:50<58:08, 10.90it/s]

 11%|███▋                               | 4500/42525 [06:50<1:01:07, 10.37it/s]

 11%|███▋                               | 4504/42525 [06:51<1:00:10, 10.53it/s]

 11%|███▉                                 | 4508/42525 [06:51<57:36, 11.00it/s]

 11%|███▉                                 | 4512/42525 [06:51<57:22, 11.04it/s]

 11%|███▉                                 | 4516/42525 [06:52<56:43, 11.17it/s]

 11%|███▉                                 | 4520/42525 [06:52<57:12, 11.07it/s]

 11%|███▉                                 | 4524/42525 [06:53<57:34, 11.00it/s]

 11%|███▉                                 | 4528/42525 [06:53<57:40, 10.98it/s]

 11%|███▉                                 | 4532/42525 [06:53<56:24, 11.23it/s]

 11%|███▉                                 | 4536/42525 [06:54<59:16, 10.68it/s]

 11%|███▉                                 | 4540/42525 [06:54<58:01, 10.91it/s]

 11%|███▉                                 | 4544/42525 [06:54<56:04, 11.29it/s]

 11%|███▉                                 | 4548/42525 [06:55<55:18, 11.44it/s]

 11%|███▉                                 | 4552/42525 [06:55<55:59, 11.30it/s]

 11%|███▉                                 | 4556/42525 [06:55<55:04, 11.49it/s]

 11%|███▉                                 | 4560/42525 [06:56<56:42, 11.16it/s]

 11%|███▉                                 | 4564/42525 [06:56<57:05, 11.08it/s]

 11%|███▉                                 | 4568/42525 [06:57<56:04, 11.28it/s]

 11%|███▉                                 | 4572/42525 [06:57<55:25, 11.41it/s]

 11%|███▉                                 | 4576/42525 [06:57<56:36, 11.17it/s]

 11%|███▉                                 | 4580/42525 [06:58<57:17, 11.04it/s]

 11%|███▉                                 | 4584/42525 [06:58<57:16, 11.04it/s]

 11%|███▉                                 | 4588/42525 [06:58<56:04, 11.27it/s]

 11%|███▉                                 | 4592/42525 [06:59<57:59, 10.90it/s]

 11%|███▉                                 | 4596/42525 [06:59<58:27, 10.81it/s]

 11%|████                                 | 4600/42525 [06:59<55:30, 11.39it/s]

 11%|████                                 | 4604/42525 [07:00<49:37, 12.74it/s]

 11%|████                                 | 4608/42525 [07:00<50:47, 12.44it/s]

 11%|████                                 | 4612/42525 [07:00<52:29, 12.04it/s]

 11%|████                                 | 4614/42525 [07:01<54:29, 11.59it/s]

 11%|████                                 | 4618/42525 [07:01<57:52, 10.92it/s]

 11%|████                                 | 4622/42525 [07:01<58:09, 10.86it/s]

 11%|████                                 | 4626/42525 [07:02<58:16, 10.84it/s]

 11%|████                                 | 4628/42525 [07:02<58:46, 10.75it/s]

 11%|████                                 | 4632/42525 [07:02<58:57, 10.71it/s]

 11%|████                                 | 4636/42525 [07:03<56:54, 11.10it/s]

 11%|████                                 | 4640/42525 [07:03<58:01, 10.88it/s]

 11%|████                                 | 4644/42525 [07:03<58:35, 10.78it/s]

 11%|████                                 | 4646/42525 [07:04<58:58, 10.71it/s]

 11%|████                                 | 4650/42525 [07:04<59:26, 10.62it/s]

 11%|████                                 | 4652/42525 [07:04<58:22, 10.81it/s]

 11%|████                                 | 4656/42525 [07:04<58:57, 10.71it/s]

 11%|████                                 | 4660/42525 [07:05<56:37, 11.14it/s]

 11%|████                                 | 4664/42525 [07:05<57:11, 11.03it/s]

 11%|████                                 | 4668/42525 [07:06<56:04, 11.25it/s]

 11%|████                                 | 4672/42525 [07:06<55:08, 11.44it/s]

 11%|████                                 | 4676/42525 [07:06<56:40, 11.13it/s]

 11%|████                                 | 4680/42525 [07:07<58:02, 10.87it/s]

 11%|████                                 | 4682/42525 [07:07<59:43, 10.56it/s]

 11%|███▊                               | 4686/42525 [07:07<1:00:05, 10.50it/s]

 11%|███▊                               | 4690/42525 [07:08<1:00:44, 10.38it/s]

 11%|████                                 | 4694/42525 [07:08<57:59, 10.87it/s]

 11%|████                                 | 4698/42525 [07:08<55:43, 11.32it/s]

 11%|████                                 | 4702/42525 [07:09<54:34, 11.55it/s]

 11%|████                                 | 4704/42525 [07:09<55:13, 11.41it/s]

 11%|████                                 | 4708/42525 [07:09<56:58, 11.06it/s]

 11%|████                                 | 4710/42525 [07:09<56:37, 11.13it/s]

 11%|███▉                               | 4714/42525 [07:10<1:00:35, 10.40it/s]

 11%|████                                 | 4718/42525 [07:10<58:31, 10.77it/s]

 11%|████                                 | 4722/42525 [07:10<57:49, 10.90it/s]

 11%|████                                 | 4726/42525 [07:11<57:26, 10.97it/s]

 11%|████                                 | 4730/42525 [07:11<55:52, 11.27it/s]

 11%|████                                 | 4734/42525 [07:12<57:25, 10.97it/s]

 11%|████                                 | 4738/42525 [07:12<56:15, 11.20it/s]

 11%|████▏                                | 4742/42525 [07:12<55:22, 11.37it/s]

 11%|████▏                                | 4746/42525 [07:13<57:40, 10.92it/s]

 11%|████▏                                | 4750/42525 [07:13<56:11, 11.20it/s]

 11%|████▏                                | 4752/42525 [07:13<57:40, 10.92it/s]

 11%|███▉                               | 4756/42525 [07:14<1:01:06, 10.30it/s]

 11%|████▏                                | 4760/42525 [07:14<59:17, 10.62it/s]

 11%|████▏                                | 4764/42525 [07:14<57:52, 10.88it/s]

 11%|████▏                                | 4768/42525 [07:15<58:33, 10.75it/s]

 11%|████▏                                | 4772/42525 [07:15<57:30, 10.94it/s]

 11%|████▏                                | 4776/42525 [07:15<57:32, 10.93it/s]

 11%|████▏                                | 4780/42525 [07:16<58:49, 10.69it/s]

 11%|████▏                                | 4784/42525 [07:16<58:20, 10.78it/s]

 11%|████▏                                | 4788/42525 [07:17<57:17, 10.98it/s]

 11%|████▏                                | 4792/42525 [07:17<57:41, 10.90it/s]

 11%|████▏                                | 4796/42525 [07:17<55:44, 11.28it/s]

 11%|████▏                                | 4800/42525 [07:18<57:30, 10.93it/s]

 11%|████▏                                | 4804/42525 [07:18<56:43, 11.08it/s]

 11%|████▏                                | 4808/42525 [07:18<55:47, 11.27it/s]

 11%|████▏                                | 4812/42525 [07:19<56:35, 11.11it/s]

 11%|████▏                                | 4816/42525 [07:19<55:58, 11.23it/s]

 11%|████▏                                | 4820/42525 [07:19<57:29, 10.93it/s]

 11%|████▏                                | 4822/42525 [07:20<57:22, 10.95it/s]

 11%|████▏                                | 4826/42525 [07:20<59:12, 10.61it/s]

 11%|████▏                                | 4828/42525 [07:20<58:43, 10.70it/s]

 11%|████▏                                | 4832/42525 [07:21<59:14, 10.60it/s]

 11%|████▏                                | 4836/42525 [07:21<57:44, 10.88it/s]

 11%|████▏                                | 4840/42525 [07:21<58:11, 10.79it/s]

 11%|████▏                                | 4842/42525 [07:21<58:09, 10.80it/s]

 11%|███▉                               | 4844/42525 [07:22<1:00:20, 10.41it/s]

 11%|███▉                               | 4848/42525 [07:22<1:00:32, 10.37it/s]

 11%|████▏                                | 4852/42525 [07:22<57:47, 10.86it/s]

 11%|████▏                                | 4856/42525 [07:23<58:30, 10.73it/s]

 11%|████▏                                | 4860/42525 [07:23<57:15, 10.96it/s]

 11%|████▏                                | 4864/42525 [07:24<57:08, 10.98it/s]

 11%|████▏                                | 4868/42525 [07:24<56:10, 11.17it/s]

 11%|████▏                                | 4872/42525 [07:24<56:00, 11.20it/s]

 11%|████▏                                | 4876/42525 [07:25<57:37, 10.89it/s]

 11%|████▏                                | 4880/42525 [07:25<59:36, 10.53it/s]

 11%|████▏                                | 4884/42525 [07:25<57:51, 10.84it/s]

 11%|████▎                                | 4888/42525 [07:26<56:25, 11.12it/s]

 12%|████▎                                | 4892/42525 [07:26<59:37, 10.52it/s]

 12%|████▎                                | 4896/42525 [07:26<57:28, 10.91it/s]

 12%|████▎                                | 4900/42525 [07:27<57:37, 10.88it/s]

 12%|████▎                                | 4904/42525 [07:27<57:35, 10.89it/s]

 12%|████▎                                | 4908/42525 [07:28<55:40, 11.26it/s]

 12%|████▎                                | 4912/42525 [07:28<58:39, 10.69it/s]

 12%|████▎                                | 4916/42525 [07:28<56:44, 11.05it/s]

 12%|████▎                                | 4920/42525 [07:29<58:02, 10.80it/s]

 12%|████▎                                | 4924/42525 [07:29<57:33, 10.89it/s]

 12%|████▎                                | 4928/42525 [07:29<55:33, 11.28it/s]

 12%|████▎                                | 4932/42525 [07:30<56:04, 11.17it/s]

 12%|████▎                                | 4936/42525 [07:30<55:29, 11.29it/s]

 12%|████▎                                | 4940/42525 [07:30<58:28, 10.71it/s]

 12%|████▎                                | 4944/42525 [07:31<58:46, 10.66it/s]

 12%|████▎                                | 4948/42525 [07:31<56:36, 11.06it/s]

 12%|████▎                                | 4952/42525 [07:32<56:27, 11.09it/s]

 12%|████▎                                | 4956/42525 [07:32<55:26, 11.29it/s]

 12%|████▎                                | 4960/42525 [07:32<55:40, 11.25it/s]

 12%|████▎                                | 4962/42525 [07:32<55:31, 11.28it/s]

 12%|████▎                                | 4966/42525 [07:33<57:18, 10.92it/s]

 12%|████▎                                | 4970/42525 [07:33<57:26, 10.90it/s]

 12%|████▎                                | 4974/42525 [07:34<57:30, 10.88it/s]

 12%|████▎                                | 4978/42525 [07:34<56:28, 11.08it/s]

 12%|████▎                                | 4982/42525 [07:34<57:34, 10.87it/s]

 12%|████▎                                | 4986/42525 [07:35<55:58, 11.18it/s]

 12%|████▎                                | 4990/42525 [07:35<58:16, 10.74it/s]

 12%|████▎                                | 4994/42525 [07:35<56:56, 10.99it/s]

 12%|████▎                                | 4998/42525 [07:36<59:29, 10.51it/s]

 12%|████▎                                | 5002/42525 [07:36<57:53, 10.80it/s]

 12%|████▎                                | 5006/42525 [07:36<55:41, 11.23it/s]

 12%|████▎                                | 5010/42525 [07:37<57:36, 10.85it/s]

 12%|████▏                              | 5014/42525 [07:37<1:00:30, 10.33it/s]

 12%|████▏                              | 5018/42525 [07:38<1:00:24, 10.35it/s]

 12%|████▎                                | 5022/42525 [07:38<58:24, 10.70it/s]

 12%|████▎                                | 5024/42525 [07:38<58:01, 10.77it/s]

 12%|████▎                                | 5028/42525 [07:39<58:40, 10.65it/s]

 12%|████▍                                | 5032/42525 [07:39<56:36, 11.04it/s]

 12%|████▍                                | 5034/42525 [07:39<57:03, 10.95it/s]

 12%|████▏                              | 5038/42525 [07:40<1:00:14, 10.37it/s]

 12%|████▍                                | 5042/42525 [07:40<59:50, 10.44it/s]

 12%|████▍                                | 5046/42525 [07:40<59:40, 10.47it/s]

 12%|████▍                                | 5050/42525 [07:41<56:50, 10.99it/s]

 12%|████▍                                | 5054/42525 [07:41<56:05, 11.13it/s]

 12%|████▍                                | 5058/42525 [07:41<55:46, 11.20it/s]

 12%|████▍                                | 5062/42525 [07:42<57:11, 10.92it/s]

 12%|████▍                                | 5066/42525 [07:42<57:15, 10.90it/s]

 12%|████▍                                | 5068/42525 [07:42<57:51, 10.79it/s]

 12%|████▍                                | 5072/42525 [07:43<58:52, 10.60it/s]

 12%|████▍                                | 5076/42525 [07:43<59:06, 10.56it/s]

 12%|████▍                                | 5080/42525 [07:43<57:24, 10.87it/s]

 12%|████▍                                | 5084/42525 [07:44<58:26, 10.68it/s]

 12%|████▍                                | 5088/42525 [07:44<56:27, 11.05it/s]

 12%|████▍                                | 5092/42525 [07:45<55:16, 11.29it/s]

 12%|████▍                                | 5096/42525 [07:45<56:29, 11.04it/s]

 12%|████▍                                | 5100/42525 [07:45<55:15, 11.29it/s]

 12%|████▍                                | 5104/42525 [07:46<55:54, 11.15it/s]

 12%|████▍                                | 5108/42525 [07:46<57:46, 10.79it/s]

 12%|████▍                                | 5112/42525 [07:46<58:07, 10.73it/s]

 12%|████▍                                | 5116/42525 [07:47<56:20, 11.06it/s]

 12%|████▍                                | 5120/42525 [07:47<58:56, 10.58it/s]

 12%|████▍                                | 5124/42525 [07:47<58:36, 10.64it/s]

 12%|████▍                                | 5128/42525 [07:48<58:23, 10.67it/s]

 12%|████▍                                | 5132/42525 [07:48<56:38, 11.00it/s]

 12%|████▍                                | 5136/42525 [07:49<57:50, 10.77it/s]

 12%|████▍                                | 5140/42525 [07:49<55:51, 11.15it/s]

 12%|████▍                                | 5144/42525 [07:49<57:02, 10.92it/s]

 12%|████▍                                | 5148/42525 [07:50<58:27, 10.66it/s]

 12%|████▍                                | 5152/42525 [07:50<57:59, 10.74it/s]

 12%|████▍                                | 5156/42525 [07:50<56:22, 11.05it/s]

 12%|████▍                                | 5160/42525 [07:51<55:48, 11.16it/s]

 12%|████▍                                | 5162/42525 [07:51<56:08, 11.09it/s]

 12%|████▍                                | 5166/42525 [07:51<57:30, 10.83it/s]

 12%|████▍                                | 5170/42525 [07:52<57:39, 10.80it/s]

 12%|████▌                                | 5174/42525 [07:52<57:44, 10.78it/s]

 12%|████▌                                | 5178/42525 [07:52<58:04, 10.72it/s]

 12%|████▌                                | 5182/42525 [07:53<57:45, 10.78it/s]

 12%|████▌                                | 5186/42525 [07:53<59:24, 10.48it/s]

 12%|████▌                                | 5190/42525 [07:54<56:23, 11.04it/s]

 12%|████▌                                | 5194/42525 [07:54<57:01, 10.91it/s]

 12%|████▌                                | 5198/42525 [07:54<57:42, 10.78it/s]

 12%|████▌                                | 5202/42525 [07:55<57:15, 10.86it/s]

 12%|████▌                                | 5206/42525 [07:55<55:15, 11.25it/s]

 12%|████▌                                | 5210/42525 [07:55<54:17, 11.45it/s]

 12%|████▌                                | 5214/42525 [07:56<55:34, 11.19it/s]

 12%|████▌                                | 5218/42525 [07:56<54:44, 11.36it/s]

 12%|████▌                                | 5222/42525 [07:56<54:38, 11.38it/s]

 12%|████▌                                | 5226/42525 [07:57<56:46, 10.95it/s]

 12%|████▌                                | 5230/42525 [07:57<57:03, 10.89it/s]

 12%|████▌                                | 5232/42525 [07:57<57:20, 10.84it/s]

 12%|████▌                                | 5234/42525 [07:58<59:44, 10.40it/s]

 12%|████▎                              | 5236/42525 [07:58<1:01:00, 10.19it/s]

 12%|████▎                              | 5240/42525 [07:58<1:00:42, 10.24it/s]

 12%|████▌                                | 5244/42525 [07:59<59:05, 10.52it/s]

 12%|████▌                                | 5246/42525 [07:59<57:52, 10.73it/s]

 12%|████▌                                | 5250/42525 [07:59<57:22, 10.83it/s]

 12%|████▌                                | 5254/42525 [07:59<57:42, 10.76it/s]

 12%|████▌                                | 5258/42525 [08:00<57:06, 10.88it/s]

 12%|████▌                                | 5262/42525 [08:00<56:29, 10.99it/s]

 12%|████▌                                | 5264/42525 [08:00<56:07, 11.06it/s]

 12%|████▌                                | 5268/42525 [08:01<58:08, 10.68it/s]

 12%|████▌                                | 5272/42525 [08:01<57:42, 10.76it/s]

 12%|████▌                                | 5276/42525 [08:01<55:47, 11.13it/s]

 12%|████▌                                | 5280/42525 [08:02<54:35, 11.37it/s]

 12%|████▌                                | 5284/42525 [08:02<54:08, 11.46it/s]

 12%|████▌                                | 5286/42525 [08:02<54:28, 11.39it/s]

 12%|████▌                                | 5290/42525 [08:03<58:05, 10.68it/s]

 12%|████▌                                | 5294/42525 [08:03<56:23, 11.00it/s]

 12%|████▌                                | 5298/42525 [08:03<55:46, 11.12it/s]

 12%|████▌                                | 5302/42525 [08:04<55:53, 11.10it/s]

 12%|████▌                                | 5306/42525 [08:04<55:19, 11.21it/s]

 12%|████▌                                | 5310/42525 [08:05<55:02, 11.27it/s]

 12%|████▌                                | 5314/42525 [08:05<55:14, 11.23it/s]

 13%|████▋                                | 5318/42525 [08:05<55:30, 11.17it/s]

 13%|████▋                                | 5322/42525 [08:06<57:20, 10.81it/s]

 13%|████▋                                | 5326/42525 [08:06<54:57, 11.28it/s]

 13%|████▋                                | 5330/42525 [08:06<54:26, 11.39it/s]

 13%|████▋                                | 5334/42525 [08:07<55:47, 11.11it/s]

 13%|████▋                                | 5338/42525 [08:07<57:42, 10.74it/s]

 13%|████▋                                | 5342/42525 [08:07<57:14, 10.83it/s]

 13%|████▋                                | 5346/42525 [08:08<54:56, 11.28it/s]

 13%|████▋                                | 5350/42525 [08:08<54:23, 11.39it/s]

 13%|████▋                                | 5354/42525 [08:08<54:46, 11.31it/s]

 13%|████▋                                | 5356/42525 [08:09<54:25, 11.38it/s]

 13%|████▋                                | 5360/42525 [08:09<58:08, 10.65it/s]

 13%|████▋                                | 5364/42525 [08:09<57:47, 10.72it/s]

 13%|████▋                                | 5368/42525 [08:10<55:22, 11.18it/s]

 13%|████▋                                | 5372/42525 [08:10<55:11, 11.22it/s]

 13%|████▋                                | 5376/42525 [08:10<55:39, 11.12it/s]

 13%|████▋                                | 5380/42525 [08:11<53:52, 11.49it/s]

 13%|████▋                                | 5384/42525 [08:11<53:12, 11.63it/s]

 13%|████▋                                | 5388/42525 [08:12<55:42, 11.11it/s]

 13%|████▋                                | 5392/42525 [08:12<58:10, 10.64it/s]

 13%|████▋                                | 5396/42525 [08:12<58:11, 10.63it/s]

 13%|████▋                                | 5398/42525 [08:12<58:27, 10.59it/s]

 13%|████▍                              | 5402/42525 [08:13<1:00:23, 10.24it/s]

 13%|████▋                                | 5406/42525 [08:13<58:53, 10.51it/s]

 13%|████▋                                | 5410/42525 [08:14<59:00, 10.48it/s]

 13%|████▋                                | 5414/42525 [08:14<59:15, 10.44it/s]

 13%|████▍                              | 5418/42525 [08:14<1:00:20, 10.25it/s]

 13%|████▋                                | 5422/42525 [08:15<58:17, 10.61it/s]

 13%|████▋                                | 5426/42525 [08:15<55:47, 11.08it/s]

 13%|████▋                                | 5430/42525 [08:16<56:03, 11.03it/s]

 13%|████▋                                | 5434/42525 [08:16<56:07, 11.01it/s]

 13%|████▋                                | 5438/42525 [08:16<55:26, 11.15it/s]

 13%|████▋                                | 5442/42525 [08:17<57:29, 10.75it/s]

 13%|████▋                                | 5446/42525 [08:17<56:14, 10.99it/s]

 13%|████▋                                | 5450/42525 [08:17<56:27, 10.95it/s]

 13%|████▋                                | 5452/42525 [08:18<55:33, 11.12it/s]

 13%|████▋                                | 5456/42525 [08:18<57:25, 10.76it/s]

 13%|████▋                                | 5458/42525 [08:18<56:57, 10.85it/s]

 13%|████▊                                | 5462/42525 [08:18<58:40, 10.53it/s]

 13%|████▊                                | 5466/42525 [08:19<59:10, 10.44it/s]

 13%|████▊                                | 5470/42525 [08:19<59:06, 10.45it/s]

 13%|████▊                                | 5474/42525 [08:20<58:06, 10.63it/s]

 13%|████▊                                | 5478/42525 [08:20<58:02, 10.64it/s]

 13%|████▊                                | 5482/42525 [08:20<55:48, 11.06it/s]

 13%|████▊                                | 5486/42525 [08:21<56:29, 10.93it/s]

 13%|████▊                                | 5490/42525 [08:21<55:20, 11.15it/s]

 13%|████▊                                | 5494/42525 [08:21<53:45, 11.48it/s]

 13%|████▊                                | 5498/42525 [08:22<57:42, 10.69it/s]

 13%|████▊                                | 5502/42525 [08:22<58:38, 10.52it/s]

 13%|████▊                                | 5506/42525 [08:23<56:03, 11.00it/s]

 13%|████▊                                | 5510/42525 [08:23<55:18, 11.16it/s]

 13%|████▊                                | 5514/42525 [08:23<53:59, 11.43it/s]

 13%|████▊                                | 5518/42525 [08:24<53:29, 11.53it/s]

 13%|████▊                                | 5522/42525 [08:24<56:18, 10.95it/s]

 13%|████▊                                | 5526/42525 [08:24<55:31, 11.11it/s]

 13%|████▊                                | 5530/42525 [08:25<56:15, 10.96it/s]

 13%|████▊                                | 5534/42525 [08:25<54:18, 11.35it/s]

 13%|████▊                                | 5538/42525 [08:25<56:21, 10.94it/s]

 13%|████▊                                | 5542/42525 [08:26<56:59, 10.81it/s]

 13%|████▊                                | 5546/42525 [08:26<57:42, 10.68it/s]

 13%|████▊                                | 5550/42525 [08:27<56:18, 10.94it/s]

 13%|████▊                                | 5554/42525 [08:27<54:21, 11.34it/s]

 13%|████▊                                | 5558/42525 [08:27<55:16, 11.15it/s]

 13%|████▊                                | 5562/42525 [08:28<54:06, 11.39it/s]

 13%|████▊                                | 5566/42525 [08:28<56:16, 10.94it/s]

 13%|████▊                                | 5570/42525 [08:28<56:06, 10.98it/s]

 13%|████▊                                | 5574/42525 [08:29<57:37, 10.69it/s]

 13%|████▊                                | 5578/42525 [08:29<57:47, 10.65it/s]

 13%|████▊                                | 5582/42525 [08:29<58:40, 10.49it/s]

 13%|████▊                                | 5586/42525 [08:30<56:23, 10.92it/s]

 13%|████▊                                | 5590/42525 [08:30<56:26, 10.91it/s]

 13%|████▊                                | 5594/42525 [08:31<55:43, 11.05it/s]

 13%|████▊                                | 5598/42525 [08:31<55:38, 11.06it/s]

 13%|████▊                                | 5602/42525 [08:31<53:49, 11.43it/s]

 13%|████▉                                | 5606/42525 [08:32<55:17, 11.13it/s]

 13%|████▉                                | 5608/42525 [08:32<55:44, 11.04it/s]

 13%|████▉                                | 5612/42525 [08:32<56:33, 10.88it/s]

 13%|████▉                                | 5616/42525 [08:33<56:46, 10.83it/s]

 13%|████▉                                | 5620/42525 [08:33<55:00, 11.18it/s]

 13%|████▉                                | 5624/42525 [08:33<54:28, 11.29it/s]

 13%|████▉                                | 5628/42525 [08:34<56:24, 10.90it/s]

 13%|████▉                                | 5632/42525 [08:34<57:40, 10.66it/s]

 13%|████▉                                | 5636/42525 [08:34<57:14, 10.74it/s]

 13%|████▉                                | 5640/42525 [08:35<56:02, 10.97it/s]

 13%|████▉                                | 5644/42525 [08:35<55:38, 11.05it/s]

 13%|████▉                                | 5648/42525 [08:35<56:16, 10.92it/s]

 13%|████▉                                | 5652/42525 [08:36<54:34, 11.26it/s]

 13%|████▉                                | 5656/42525 [08:36<54:18, 11.32it/s]

 13%|████▉                                | 5660/42525 [08:37<56:28, 10.88it/s]

 13%|████▉                                | 5664/42525 [08:37<57:01, 10.77it/s]

 13%|████▉                                | 5668/42525 [08:37<54:34, 11.26it/s]

 13%|████▉                                | 5672/42525 [08:38<53:53, 11.40it/s]

 13%|████▉                                | 5676/42525 [08:38<53:38, 11.45it/s]

 13%|████▉                                | 5680/42525 [08:38<54:55, 11.18it/s]

 13%|████▉                                | 5684/42525 [08:39<55:25, 11.08it/s]

 13%|████▉                                | 5688/42525 [08:39<56:51, 10.80it/s]

 13%|████▉                                | 5692/42525 [08:39<57:04, 10.76it/s]

 13%|████▉                                | 5696/42525 [08:40<58:12, 10.55it/s]

 13%|████▉                                | 5700/42525 [08:40<58:18, 10.52it/s]

 13%|████▉                                | 5704/42525 [08:41<57:16, 10.71it/s]

 13%|████▉                                | 5708/42525 [08:41<55:24, 11.08it/s]

 13%|████▉                                | 5712/42525 [08:41<55:09, 11.12it/s]

 13%|████▉                                | 5716/42525 [08:42<54:29, 11.26it/s]

 13%|████▉                                | 5720/42525 [08:42<55:14, 11.10it/s]

 13%|████▉                                | 5724/42525 [08:42<56:46, 10.80it/s]

 13%|████▉                                | 5728/42525 [08:43<58:51, 10.42it/s]

 13%|████▉                                | 5732/42525 [08:43<56:00, 10.95it/s]

 13%|████▉                                | 5736/42525 [08:44<54:51, 11.18it/s]

 13%|████▉                                | 5740/42525 [08:44<55:19, 11.08it/s]

 14%|████▉                                | 5744/42525 [08:44<53:41, 11.42it/s]

 14%|█████                                | 5748/42525 [08:45<49:04, 12.49it/s]

 14%|█████                                | 5752/42525 [08:45<50:48, 12.06it/s]

 14%|█████                                | 5754/42525 [08:45<48:55, 12.53it/s]

 14%|█████                                | 5758/42525 [08:45<54:15, 11.29it/s]

 14%|█████                                | 5760/42525 [08:46<55:52, 10.97it/s]

 14%|█████                                | 5762/42525 [08:46<58:12, 10.53it/s]

 14%|█████                                | 5764/42525 [08:46<59:38, 10.27it/s]

 14%|█████                                | 5768/42525 [08:46<59:43, 10.26it/s]

 14%|█████                                | 5772/42525 [08:47<59:17, 10.33it/s]

 14%|█████                                | 5776/42525 [08:47<56:50, 10.77it/s]

 14%|█████                                | 5780/42525 [08:47<55:35, 11.02it/s]

 14%|█████                                | 5784/42525 [08:48<56:46, 10.79it/s]

 14%|█████                                | 5786/42525 [08:48<58:59, 10.38it/s]

 14%|█████                                | 5790/42525 [08:48<59:42, 10.25it/s]

 14%|█████                                | 5792/42525 [08:49<58:22, 10.49it/s]

 14%|█████                                | 5796/42525 [08:49<58:13, 10.51it/s]

 14%|█████                                | 5798/42525 [08:49<58:56, 10.39it/s]

 14%|█████                                | 5802/42525 [08:50<57:58, 10.56it/s]

 14%|█████                                | 5804/42525 [08:50<59:04, 10.36it/s]

 14%|█████                                | 5808/42525 [08:50<59:39, 10.26it/s]

 14%|█████                                | 5812/42525 [08:51<58:33, 10.45it/s]

 14%|█████                                | 5816/42525 [08:51<58:50, 10.40it/s]

 14%|█████                                | 5820/42525 [08:51<56:37, 10.80it/s]

 14%|█████                                | 5824/42525 [08:52<54:59, 11.12it/s]

 14%|█████                                | 5828/42525 [08:52<54:24, 11.24it/s]

 14%|█████                                | 5832/42525 [08:52<53:34, 11.41it/s]

 14%|█████                                | 5836/42525 [08:53<53:25, 11.45it/s]

 14%|█████                                | 5840/42525 [08:53<56:12, 10.88it/s]

 14%|█████                                | 5844/42525 [08:53<55:37, 10.99it/s]

 14%|█████                                | 5848/42525 [08:54<55:17, 11.06it/s]

 14%|█████                                | 5852/42525 [08:54<55:09, 11.08it/s]

 14%|█████                                | 5856/42525 [08:55<54:14, 11.27it/s]

 14%|█████                                | 5858/42525 [08:55<54:16, 11.26it/s]

 14%|█████                                | 5862/42525 [08:55<56:36, 10.80it/s]

 14%|█████                                | 5866/42525 [08:55<57:08, 10.69it/s]

 14%|█████                                | 5868/42525 [08:56<57:40, 10.59it/s]

 14%|█████                                | 5872/42525 [08:56<58:15, 10.49it/s]

 14%|█████                                | 5876/42525 [08:56<56:44, 10.76it/s]

 14%|█████                                | 5880/42525 [08:57<54:58, 11.11it/s]

 14%|█████                                | 5884/42525 [08:57<54:31, 11.20it/s]

 14%|█████                                | 5888/42525 [08:58<57:34, 10.60it/s]

 14%|█████▏                               | 5892/42525 [08:58<56:27, 10.81it/s]

 14%|█████▏                               | 5896/42525 [08:58<55:24, 11.02it/s]

 14%|█████▏                               | 5900/42525 [08:59<55:13, 11.05it/s]

 14%|█████▏                               | 5902/42525 [08:59<54:45, 11.15it/s]

 14%|█████▏                               | 5904/42525 [08:59<57:31, 10.61it/s]

 14%|█████▏                               | 5908/42525 [08:59<58:36, 10.41it/s]

 14%|█████▏                               | 5912/42525 [09:00<57:14, 10.66it/s]

 14%|█████▏                               | 5916/42525 [09:00<58:54, 10.36it/s]

 14%|█████▏                               | 5920/42525 [09:01<58:36, 10.41it/s]

 14%|█████▏                               | 5924/42525 [09:01<57:50, 10.55it/s]

 14%|█████▏                               | 5928/42525 [09:01<54:59, 11.09it/s]

 14%|█████▏                               | 5932/42525 [09:02<57:24, 10.62it/s]

 14%|█████▏                               | 5936/42525 [09:02<57:37, 10.58it/s]

 14%|█████▏                               | 5940/42525 [09:02<57:00, 10.69it/s]

 14%|█████▏                               | 5944/42525 [09:03<55:27, 10.99it/s]

 14%|█████▏                               | 5948/42525 [09:03<56:03, 10.87it/s]

 14%|█████▏                               | 5952/42525 [09:04<58:37, 10.40it/s]

 14%|█████▏                               | 5956/42525 [09:04<57:51, 10.53it/s]

 14%|█████▏                               | 5960/42525 [09:04<56:05, 10.87it/s]

 14%|█████▏                               | 5964/42525 [09:05<57:12, 10.65it/s]

 14%|█████▏                               | 5968/42525 [09:05<55:46, 10.92it/s]

 14%|█████▏                               | 5972/42525 [09:05<55:02, 11.07it/s]

 14%|█████▏                               | 5976/42525 [09:06<55:24, 10.99it/s]

 14%|█████▏                               | 5980/42525 [09:06<54:27, 11.18it/s]

 14%|█████▏                               | 5984/42525 [09:06<54:06, 11.26it/s]

 14%|█████▏                               | 5988/42525 [09:07<55:20, 11.00it/s]

 14%|█████▏                               | 5990/42525 [09:07<56:37, 10.75it/s]

 14%|█████▏                               | 5994/42525 [09:07<57:29, 10.59it/s]

 14%|█████▏                               | 5998/42525 [09:08<56:35, 10.76it/s]

 14%|█████▏                               | 6002/42525 [09:08<58:36, 10.39it/s]

 14%|█████▏                               | 6006/42525 [09:08<55:23, 10.99it/s]

 14%|█████▏                               | 6010/42525 [09:09<53:53, 11.29it/s]

 14%|█████▏                               | 6014/42525 [09:09<54:02, 11.26it/s]

 14%|█████▏                               | 6018/42525 [09:10<54:28, 11.17it/s]

 14%|█████▏                               | 6022/42525 [09:10<53:43, 11.32it/s]

 14%|█████▏                               | 6026/42525 [09:10<54:27, 11.17it/s]

 14%|█████▏                               | 6030/42525 [09:11<54:01, 11.26it/s]

 14%|█████▎                               | 6034/42525 [09:11<55:05, 11.04it/s]

 14%|█████▎                               | 6038/42525 [09:11<55:01, 11.05it/s]

 14%|█████▎                               | 6042/42525 [09:12<53:51, 11.29it/s]

 14%|█████▎                               | 6046/42525 [09:12<53:26, 11.38it/s]

 14%|█████▎                               | 6050/42525 [09:12<54:51, 11.08it/s]

 14%|█████▎                               | 6054/42525 [09:13<53:46, 11.30it/s]

 14%|█████▎                               | 6058/42525 [09:13<54:59, 11.05it/s]

 14%|█████▎                               | 6062/42525 [09:14<55:46, 10.89it/s]

 14%|█████▎                               | 6066/42525 [09:14<54:50, 11.08it/s]

 14%|█████▎                               | 6070/42525 [09:14<54:20, 11.18it/s]

 14%|█████▎                               | 6074/42525 [09:15<55:29, 10.95it/s]

 14%|█████▎                               | 6078/42525 [09:15<54:05, 11.23it/s]

 14%|█████▎                               | 6082/42525 [09:15<57:07, 10.63it/s]

 14%|█████▎                               | 6086/42525 [09:16<57:02, 10.65it/s]

 14%|█████▎                               | 6090/42525 [09:16<57:05, 10.64it/s]

 14%|█████▎                               | 6094/42525 [09:16<58:05, 10.45it/s]

 14%|█████▎                               | 6098/42525 [09:17<55:54, 10.86it/s]

 14%|█████▎                               | 6102/42525 [09:17<54:05, 11.22it/s]

 14%|█████▎                               | 6106/42525 [09:18<55:07, 11.01it/s]

 14%|█████▎                               | 6110/42525 [09:18<54:38, 11.11it/s]

 14%|█████▎                               | 6114/42525 [09:18<54:42, 11.09it/s]

 14%|█████▎                               | 6118/42525 [09:19<55:40, 10.90it/s]

 14%|█████▎                               | 6122/42525 [09:19<54:05, 11.22it/s]

 14%|█████▎                               | 6126/42525 [09:19<54:58, 11.04it/s]

 14%|█████▎                               | 6130/42525 [09:20<54:33, 11.12it/s]

 14%|█████▎                               | 6134/42525 [09:20<54:15, 11.18it/s]

 14%|█████▎                               | 6138/42525 [09:20<55:12, 10.99it/s]

 14%|█████▎                               | 6142/42525 [09:21<54:47, 11.07it/s]

 14%|█████▎                               | 6146/42525 [09:21<53:21, 11.36it/s]

 14%|█████▎                               | 6150/42525 [09:22<54:39, 11.09it/s]

 14%|█████▎                               | 6154/42525 [09:22<54:04, 11.21it/s]

 14%|█████▎                               | 6158/42525 [09:22<53:18, 11.37it/s]

 14%|█████▎                               | 6162/42525 [09:23<52:49, 11.47it/s]

 14%|█████▎                               | 6166/42525 [09:23<53:31, 11.32it/s]

 15%|█████▎                               | 6170/42525 [09:23<53:00, 11.43it/s]

 15%|█████▎                               | 6174/42525 [09:24<55:32, 10.91it/s]

 15%|█████▍                               | 6178/42525 [09:24<55:21, 10.94it/s]

 15%|█████▍                               | 6182/42525 [09:24<56:03, 10.81it/s]

 15%|█████▍                               | 6186/42525 [09:25<54:23, 11.14it/s]

 15%|█████▍                               | 6190/42525 [09:25<54:38, 11.08it/s]

 15%|█████▍                               | 6194/42525 [09:25<54:43, 11.06it/s]

 15%|█████▍                               | 6196/42525 [09:26<53:55, 11.23it/s]

 15%|█████▍                               | 6200/42525 [09:26<57:34, 10.52it/s]

 15%|█████▍                               | 6204/42525 [09:26<54:47, 11.05it/s]

 15%|█████▍                               | 6208/42525 [09:27<55:56, 10.82it/s]

 15%|█████▍                               | 6212/42525 [09:27<53:23, 11.33it/s]

 15%|█████▍                               | 6216/42525 [09:27<52:41, 11.48it/s]

 15%|█████▍                               | 6220/42525 [09:28<52:48, 11.46it/s]

 15%|█████▍                               | 6224/42525 [09:28<55:53, 10.82it/s]

 15%|█████▍                               | 6228/42525 [09:29<54:10, 11.17it/s]

 15%|█████▍                               | 6232/42525 [09:29<56:16, 10.75it/s]

 15%|█████▍                               | 6236/42525 [09:29<54:41, 11.06it/s]

 15%|█████▍                               | 6240/42525 [09:30<54:24, 11.11it/s]

 15%|█████▍                               | 6244/42525 [09:30<54:48, 11.03it/s]

 15%|█████▍                               | 6246/42525 [09:30<55:47, 10.84it/s]

 15%|█████▍                               | 6250/42525 [09:31<57:51, 10.45it/s]

 15%|█████▍                               | 6254/42525 [09:31<56:49, 10.64it/s]

 15%|█████▍                               | 6258/42525 [09:31<57:25, 10.53it/s]

 15%|█████▍                               | 6262/42525 [09:32<58:00, 10.42it/s]

 15%|█████▍                               | 6266/42525 [09:32<56:48, 10.64it/s]

 15%|█████▍                               | 6270/42525 [09:32<55:45, 10.84it/s]

 15%|█████▍                               | 6274/42525 [09:33<54:59, 10.99it/s]

 15%|█████▍                               | 6278/42525 [09:33<56:35, 10.67it/s]

 15%|█████▍                               | 6282/42525 [09:34<58:29, 10.33it/s]

 15%|█████▍                               | 6286/42525 [09:34<56:28, 10.70it/s]

 15%|█████▍                               | 6290/42525 [09:34<56:22, 10.71it/s]

 15%|█████▍                               | 6294/42525 [09:35<56:42, 10.65it/s]

 15%|█████▍                               | 6298/42525 [09:35<54:37, 11.05it/s]

 15%|█████▍                               | 6302/42525 [09:35<56:53, 10.61it/s]

 15%|█████▍                               | 6306/42525 [09:36<54:43, 11.03it/s]

 15%|█████▍                               | 6310/42525 [09:36<55:53, 10.80it/s]

 15%|█████▍                               | 6314/42525 [09:37<55:56, 10.79it/s]

 15%|█████▍                               | 6318/42525 [09:37<54:33, 11.06it/s]

 15%|█████▍                               | 6320/42525 [09:37<54:36, 11.05it/s]

 15%|█████▌                               | 6324/42525 [09:37<55:27, 10.88it/s]

 15%|█████▌                               | 6328/42525 [09:38<56:05, 10.75it/s]

 15%|█████▌                               | 6332/42525 [09:38<53:54, 11.19it/s]

 15%|█████▌                               | 6336/42525 [09:39<52:09, 11.56it/s]

 15%|█████▌                               | 6338/42525 [09:39<52:45, 11.43it/s]

 15%|█████▌                               | 6342/42525 [09:39<53:52, 11.20it/s]

 15%|█████▌                               | 6344/42525 [09:39<50:59, 11.83it/s]

 15%|█████▌                               | 6348/42525 [09:40<53:49, 11.20it/s]

 15%|█████▌                               | 6352/42525 [09:40<50:11, 12.01it/s]

 15%|█████▌                               | 6356/42525 [09:40<50:18, 11.98it/s]

 15%|█████▌                               | 6360/42525 [09:41<49:37, 12.15it/s]

 15%|█████▌                               | 6364/42525 [09:41<50:51, 11.85it/s]

 15%|█████▌                               | 6368/42525 [09:41<50:51, 11.85it/s]

 15%|█████▌                               | 6372/42525 [09:42<48:34, 12.41it/s]

 15%|█████▌                               | 6376/42525 [09:42<46:36, 12.93it/s]

 15%|█████▌                               | 6380/42525 [09:42<49:49, 12.09it/s]

 15%|█████▌                               | 6384/42525 [09:43<50:46, 11.86it/s]

 15%|█████▌                               | 6388/42525 [09:43<50:01, 12.04it/s]

 15%|█████▌                               | 6392/42525 [09:43<52:12, 11.53it/s]

 15%|█████▌                               | 6396/42525 [09:44<47:16, 12.74it/s]

 15%|█████▌                               | 6398/42525 [09:44<48:05, 12.52it/s]

 15%|█████▌                               | 6402/42525 [09:44<52:35, 11.45it/s]

 15%|█████▌                               | 6404/42525 [09:44<53:32, 11.24it/s]

 15%|█████▌                               | 6406/42525 [09:44<56:31, 10.65it/s]

 15%|█████▌                               | 6410/42525 [09:45<57:34, 10.45it/s]

 15%|█████▌                               | 6414/42525 [09:45<57:20, 10.50it/s]

 15%|█████▌                               | 6418/42525 [09:46<56:35, 10.64it/s]

 15%|█████▌                               | 6422/42525 [09:46<55:14, 10.89it/s]

 15%|█████▌                               | 6426/42525 [09:46<55:41, 10.80it/s]

 15%|█████▌                               | 6430/42525 [09:47<57:29, 10.46it/s]

 15%|█████▌                               | 6434/42525 [09:47<58:02, 10.36it/s]

 15%|█████▌                               | 6436/42525 [09:47<58:04, 10.36it/s]

 15%|█████▌                               | 6440/42525 [09:48<58:59, 10.19it/s]

 15%|█████▌                               | 6442/42525 [09:48<58:41, 10.25it/s]

 15%|█████▌                               | 6446/42525 [09:48<57:40, 10.43it/s]

 15%|█████▌                               | 6450/42525 [09:49<54:27, 11.04it/s]

 15%|█████▌                               | 6454/42525 [09:49<55:05, 10.91it/s]

 15%|█████▌                               | 6458/42525 [09:49<54:32, 11.02it/s]

 15%|█████▌                               | 6462/42525 [09:50<56:04, 10.72it/s]

 15%|█████▋                               | 6466/42525 [09:50<55:45, 10.78it/s]

 15%|█████▋                               | 6470/42525 [09:50<53:22, 11.26it/s]

 15%|█████▋                               | 6474/42525 [09:51<53:37, 11.20it/s]

 15%|█████▋                               | 6478/42525 [09:51<52:20, 11.48it/s]

 15%|█████▋                               | 6482/42525 [09:52<50:57, 11.79it/s]

 15%|█████▋                               | 6486/42525 [09:52<51:05, 11.76it/s]

 15%|█████▋                               | 6490/42525 [09:52<55:14, 10.87it/s]

 15%|█████▋                               | 6494/42525 [09:53<55:42, 10.78it/s]

 15%|█████▋                               | 6498/42525 [09:53<56:06, 10.70it/s]

 15%|█████▋                               | 6502/42525 [09:53<52:03, 11.53it/s]

 15%|█████▋                               | 6506/42525 [09:54<52:01, 11.54it/s]

 15%|█████▋                               | 6510/42525 [09:54<50:14, 11.95it/s]

 15%|█████▋                               | 6514/42525 [09:54<51:15, 11.71it/s]

 15%|█████▋                               | 6518/42525 [09:55<50:55, 11.78it/s]

 15%|█████▋                               | 6522/42525 [09:55<48:32, 12.36it/s]

 15%|█████▋                               | 6526/42525 [09:55<46:26, 12.92it/s]

 15%|█████▋                               | 6530/42525 [09:56<48:42, 12.32it/s]

 15%|█████▋                               | 6534/42525 [09:56<47:49, 12.54it/s]

 15%|█████▋                               | 6538/42525 [09:56<46:40, 12.85it/s]

 15%|█████▋                               | 6542/42525 [09:57<49:59, 12.00it/s]

 15%|█████▋                               | 6546/42525 [09:57<52:37, 11.39it/s]

 15%|█████▋                               | 6550/42525 [09:57<52:30, 11.42it/s]

 15%|█████▋                               | 6554/42525 [09:58<54:52, 10.93it/s]

 15%|█████▋                               | 6558/42525 [09:58<51:18, 11.68it/s]

 15%|█████▋                               | 6562/42525 [09:58<48:51, 12.27it/s]

 15%|█████▋                               | 6566/42525 [09:59<49:40, 12.06it/s]

 15%|█████▋                               | 6570/42525 [09:59<51:27, 11.64it/s]

 15%|█████▋                               | 6572/42525 [09:59<51:39, 11.60it/s]

 15%|█████▋                               | 6574/42525 [09:59<54:36, 10.97it/s]

 15%|█████▋                               | 6576/42525 [10:00<57:11, 10.48it/s]

 15%|█████▋                               | 6580/42525 [10:00<59:42, 10.03it/s]

 15%|█████▋                               | 6584/42525 [10:00<54:31, 10.99it/s]

 15%|█████▋                               | 6588/42525 [10:01<53:34, 11.18it/s]

 16%|█████▋                               | 6592/42525 [10:01<52:20, 11.44it/s]

 16%|█████▋                               | 6596/42525 [10:01<49:23, 12.12it/s]

 16%|█████▋                               | 6600/42525 [10:02<47:52, 12.51it/s]

 16%|█████▋                               | 6604/42525 [10:02<45:48, 13.07it/s]

 16%|█████▋                               | 6608/42525 [10:02<46:18, 12.93it/s]

 16%|█████▊                               | 6610/42525 [10:02<49:38, 12.06it/s]

 16%|█████▊                               | 6614/42525 [10:03<50:36, 11.83it/s]

 16%|█████▊                               | 6618/42525 [10:03<49:35, 12.07it/s]

 16%|█████▊                               | 6622/42525 [10:04<53:27, 11.19it/s]

 16%|█████▊                               | 6626/42525 [10:04<48:01, 12.46it/s]

 16%|█████▊                               | 6630/42525 [10:04<49:23, 12.11it/s]

 16%|█████▊                               | 6634/42525 [10:04<46:31, 12.86it/s]

 16%|█████▊                               | 6638/42525 [10:05<48:26, 12.35it/s]

 16%|█████▊                               | 6642/42525 [10:05<48:19, 12.37it/s]

 16%|█████▊                               | 6646/42525 [10:05<48:21, 12.37it/s]

 16%|█████▊                               | 6650/42525 [10:06<48:17, 12.38it/s]

 16%|█████▊                               | 6654/42525 [10:06<51:05, 11.70it/s]

 16%|█████▊                               | 6658/42525 [10:06<50:27, 11.85it/s]

 16%|█████▊                               | 6662/42525 [10:07<50:32, 11.83it/s]

 16%|█████▊                               | 6666/42525 [10:07<48:11, 12.40it/s]

 16%|█████▊                               | 6670/42525 [10:08<54:12, 11.02it/s]

 16%|█████▊                               | 6674/42525 [10:08<50:33, 11.82it/s]

 16%|█████▊                               | 6678/42525 [10:08<49:34, 12.05it/s]

 16%|█████▊                               | 6682/42525 [10:09<51:01, 11.71it/s]

 16%|█████▊                               | 6686/42525 [10:09<53:26, 11.18it/s]

 16%|█████▊                               | 6690/42525 [10:09<53:49, 11.09it/s]

 16%|█████▊                               | 6694/42525 [10:10<53:29, 11.16it/s]

 16%|█████▊                               | 6696/42525 [10:10<55:18, 10.80it/s]

 16%|█████▊                               | 6700/42525 [10:10<55:21, 10.79it/s]

 16%|█████▊                               | 6704/42525 [10:11<55:06, 10.83it/s]

 16%|█████▊                               | 6706/42525 [10:11<54:07, 11.03it/s]

 16%|█████▊                               | 6710/42525 [10:11<55:20, 10.78it/s]

 16%|█████▊                               | 6714/42525 [10:11<55:19, 10.79it/s]

 16%|█████▊                               | 6718/42525 [10:12<51:57, 11.49it/s]

 16%|█████▊                               | 6722/42525 [10:12<49:30, 12.05it/s]

 16%|█████▊                               | 6726/42525 [10:12<51:46, 11.52it/s]

 16%|█████▊                               | 6730/42525 [10:13<51:23, 11.61it/s]

 16%|█████▊                               | 6734/42525 [10:13<52:11, 11.43it/s]

 16%|█████▊                               | 6736/42525 [10:13<55:23, 10.77it/s]

 16%|█████▊                               | 6740/42525 [10:14<56:38, 10.53it/s]

 16%|█████▊                               | 6744/42525 [10:14<53:30, 11.15it/s]

 16%|█████▊                               | 6748/42525 [10:14<50:47, 11.74it/s]

 16%|█████▊                               | 6752/42525 [10:15<51:35, 11.56it/s]

 16%|█████▉                               | 6756/42525 [10:15<52:36, 11.33it/s]

 16%|█████▉                               | 6760/42525 [10:15<50:14, 11.86it/s]

 16%|█████▉                               | 6764/42525 [10:16<51:29, 11.57it/s]

 16%|█████▉                               | 6768/42525 [10:16<52:04, 11.44it/s]

 16%|█████▉                               | 6772/42525 [10:17<50:56, 11.70it/s]

 16%|█████▉                               | 6776/42525 [10:17<50:58, 11.69it/s]

 16%|█████▉                               | 6780/42525 [10:17<52:52, 11.27it/s]

 16%|█████▉                               | 6784/42525 [10:18<53:24, 11.15it/s]

 16%|█████▉                               | 6788/42525 [10:18<53:00, 11.23it/s]

 16%|█████▉                               | 6792/42525 [10:18<53:12, 11.19it/s]

 16%|█████▉                               | 6796/42525 [10:19<53:20, 11.16it/s]

 16%|█████▉                               | 6800/42525 [10:19<51:46, 11.50it/s]

 16%|█████▉                               | 6804/42525 [10:19<52:13, 11.40it/s]

 16%|█████▉                               | 6808/42525 [10:20<52:45, 11.28it/s]

 16%|█████▉                               | 6812/42525 [10:20<52:57, 11.24it/s]

 16%|█████▉                               | 6816/42525 [10:20<54:06, 11.00it/s]

 16%|█████▉                               | 6820/42525 [10:21<54:12, 10.98it/s]

 16%|█████▉                               | 6824/42525 [10:21<55:15, 10.77it/s]

 16%|█████▉                               | 6828/42525 [10:22<55:27, 10.73it/s]

 16%|█████▉                               | 6832/42525 [10:22<56:39, 10.50it/s]

 16%|█████▉                               | 6836/42525 [10:22<52:54, 11.24it/s]

 16%|█████▉                               | 6840/42525 [10:23<53:07, 11.19it/s]

 16%|█████▉                               | 6844/42525 [10:23<53:02, 11.21it/s]

 16%|█████▉                               | 6848/42525 [10:23<55:02, 10.80it/s]

 16%|█████▉                               | 6852/42525 [10:24<52:51, 11.25it/s]

 16%|█████▉                               | 6856/42525 [10:24<51:29, 11.55it/s]

 16%|█████▉                               | 6860/42525 [10:24<53:57, 11.02it/s]

 16%|█████▉                               | 6864/42525 [10:25<53:57, 11.02it/s]

 16%|█████▉                               | 6868/42525 [10:25<53:08, 11.18it/s]

 16%|█████▉                               | 6872/42525 [10:25<51:58, 11.43it/s]

 16%|█████▉                               | 6876/42525 [10:26<48:43, 12.19it/s]

 16%|█████▉                               | 6880/42525 [10:26<45:30, 13.05it/s]

 16%|█████▉                               | 6884/42525 [10:26<47:30, 12.50it/s]

 16%|█████▉                               | 6888/42525 [10:27<51:49, 11.46it/s]

 16%|█████▉                               | 6892/42525 [10:27<53:10, 11.17it/s]

 16%|██████                               | 6896/42525 [10:28<54:22, 10.92it/s]

 16%|██████                               | 6900/42525 [10:28<55:46, 10.65it/s]

 16%|██████                               | 6904/42525 [10:28<55:28, 10.70it/s]

 16%|██████                               | 6908/42525 [10:29<56:48, 10.45it/s]

 16%|██████                               | 6912/42525 [10:29<55:47, 10.64it/s]

 16%|██████                               | 6916/42525 [10:29<55:57, 10.61it/s]

 16%|██████                               | 6920/42525 [10:30<54:01, 10.98it/s]

 16%|██████                               | 6924/42525 [10:30<53:23, 11.11it/s]

 16%|██████                               | 6928/42525 [10:31<54:33, 10.88it/s]

 16%|██████                               | 6932/42525 [10:31<55:20, 10.72it/s]

 16%|██████                               | 6936/42525 [10:31<55:55, 10.61it/s]

 16%|██████                               | 6940/42525 [10:32<55:35, 10.67it/s]

 16%|██████                               | 6944/42525 [10:32<55:12, 10.74it/s]

 16%|██████                               | 6948/42525 [10:32<54:48, 10.82it/s]

 16%|██████                               | 6952/42525 [10:33<54:53, 10.80it/s]

 16%|██████                               | 6956/42525 [10:33<55:35, 10.66it/s]

 16%|██████                               | 6960/42525 [10:33<54:59, 10.78it/s]

 16%|██████                               | 6964/42525 [10:34<54:24, 10.89it/s]

 16%|██████                               | 6968/42525 [10:34<52:09, 11.36it/s]

 16%|██████                               | 6972/42525 [10:35<53:19, 11.11it/s]

 16%|██████                               | 6976/42525 [10:35<50:47, 11.67it/s]

 16%|██████                               | 6980/42525 [10:35<52:27, 11.29it/s]

 16%|██████                               | 6982/42525 [10:35<56:35, 10.47it/s]

 16%|█████▋                             | 6985/42525 [10:36<1:02:13,  9.52it/s]

 16%|█████▊                             | 6988/42525 [10:36<1:01:23,  9.65it/s]

 16%|██████                               | 6992/42525 [10:37<57:09, 10.36it/s]

 16%|██████                               | 6994/42525 [10:37<56:59, 10.39it/s]

 16%|██████                               | 6998/42525 [10:37<56:44, 10.43it/s]

 16%|██████                               | 7002/42525 [10:37<54:45, 10.81it/s]

 16%|██████                               | 7006/42525 [10:38<54:12, 10.92it/s]

 16%|██████                               | 7010/42525 [10:38<56:00, 10.57it/s]

 16%|██████                               | 7014/42525 [10:39<57:55, 10.22it/s]

 17%|██████                               | 7018/42525 [10:39<55:42, 10.62it/s]

 17%|██████                               | 7020/42525 [10:39<54:09, 10.93it/s]

 17%|██████                               | 7024/42525 [10:40<55:30, 10.66it/s]

 17%|██████                               | 7026/42525 [10:40<55:02, 10.75it/s]

 17%|██████                               | 7028/42525 [10:40<56:23, 10.49it/s]

 17%|██████                               | 7032/42525 [10:40<57:47, 10.24it/s]

 17%|██████                               | 7036/42525 [10:41<55:45, 10.61it/s]

 17%|██████                               | 7038/42525 [10:41<54:32, 10.84it/s]

 17%|██████▏                              | 7042/42525 [10:41<55:26, 10.67it/s]

 17%|██████▏                              | 7046/42525 [10:42<53:42, 11.01it/s]

 17%|██████▏                              | 7048/42525 [10:42<52:57, 11.17it/s]

 17%|██████▏                              | 7052/42525 [10:42<53:42, 11.01it/s]

 17%|██████▏                              | 7056/42525 [10:43<54:58, 10.75it/s]

 17%|██████▏                              | 7060/42525 [10:43<54:23, 10.87it/s]

 17%|██████▏                              | 7064/42525 [10:43<55:37, 10.62it/s]

 17%|██████▏                              | 7068/42525 [10:44<55:37, 10.62it/s]

 17%|██████▏                              | 7072/42525 [10:44<53:52, 10.97it/s]

 17%|██████▏                              | 7076/42525 [10:44<53:24, 11.06it/s]

 17%|██████▏                              | 7080/42525 [10:45<52:30, 11.25it/s]

 17%|██████▏                              | 7084/42525 [10:45<51:18, 11.51it/s]

 17%|██████▏                              | 7088/42525 [10:45<52:24, 11.27it/s]

 17%|██████▏                              | 7092/42525 [10:46<51:13, 11.53it/s]

 17%|██████▏                              | 7096/42525 [10:46<51:53, 11.38it/s]

 17%|██████▏                              | 7100/42525 [10:46<51:18, 11.51it/s]

 17%|██████▏                              | 7104/42525 [10:47<52:55, 11.15it/s]

 17%|██████▏                              | 7108/42525 [10:47<54:02, 10.92it/s]

 17%|██████▏                              | 7112/42525 [10:48<54:17, 10.87it/s]

 17%|██████▏                              | 7116/42525 [10:48<51:51, 11.38it/s]

 17%|██████▏                              | 7120/42525 [10:48<51:51, 11.38it/s]

 17%|██████▏                              | 7124/42525 [10:49<53:52, 10.95it/s]

 17%|██████▏                              | 7128/42525 [10:49<52:23, 11.26it/s]

 17%|██████▏                              | 7132/42525 [10:49<53:56, 10.94it/s]

 17%|██████▏                              | 7136/42525 [10:50<53:00, 11.13it/s]

 17%|██████▏                              | 7140/42525 [10:50<53:38, 10.99it/s]

 17%|██████▏                              | 7144/42525 [10:50<54:37, 10.79it/s]

 17%|██████▏                              | 7146/42525 [10:51<52:56, 11.14it/s]

 17%|██████▏                              | 7150/42525 [10:51<54:47, 10.76it/s]

 17%|██████▏                              | 7154/42525 [10:51<52:36, 11.20it/s]

 17%|██████▏                              | 7158/42525 [10:52<52:53, 11.14it/s]

 17%|██████▏                              | 7162/42525 [10:52<51:32, 11.44it/s]

 17%|██████▏                              | 7166/42525 [10:52<54:27, 10.82it/s]

 17%|██████▏                              | 7170/42525 [10:53<51:36, 11.42it/s]

 17%|██████▏                              | 7174/42525 [10:53<47:48, 12.32it/s]

 17%|██████▏                              | 7176/42525 [10:53<49:58, 11.79it/s]

 17%|██████▏                              | 7180/42525 [10:54<52:49, 11.15it/s]

 17%|██████▎                              | 7184/42525 [10:54<52:29, 11.22it/s]

 17%|██████▎                              | 7188/42525 [10:54<52:33, 11.20it/s]

 17%|██████▎                              | 7192/42525 [10:55<55:41, 10.57it/s]

 17%|██████▎                              | 7196/42525 [10:55<54:48, 10.74it/s]

 17%|██████▎                              | 7200/42525 [10:56<54:52, 10.73it/s]

 17%|██████▎                              | 7204/42525 [10:56<53:58, 10.91it/s]

 17%|██████▎                              | 7206/42525 [10:56<55:28, 10.61it/s]

 17%|██████▎                              | 7208/42525 [10:56<57:21, 10.26it/s]

 17%|██████▎                              | 7210/42525 [10:56<58:12, 10.11it/s]

 17%|██████▎                              | 7214/42525 [10:57<57:28, 10.24it/s]

 17%|██████▎                              | 7218/42525 [10:57<56:46, 10.36it/s]

 17%|██████▎                              | 7222/42525 [10:58<54:41, 10.76it/s]

 17%|██████▎                              | 7226/42525 [10:58<54:51, 10.72it/s]

 17%|██████▎                              | 7228/42525 [10:58<54:38, 10.76it/s]

 17%|██████▎                              | 7232/42525 [10:59<53:22, 11.02it/s]

 17%|██████▎                              | 7236/42525 [10:59<52:29, 11.20it/s]

 17%|██████▎                              | 7240/42525 [10:59<50:32, 11.63it/s]

 17%|██████▎                              | 7244/42525 [11:00<50:42, 11.60it/s]

 17%|██████▎                              | 7248/42525 [11:00<52:18, 11.24it/s]

 17%|██████▎                              | 7252/42525 [11:00<50:26, 11.66it/s]

 17%|██████▎                              | 7254/42525 [11:00<50:10, 11.72it/s]

 17%|██████▎                              | 7258/42525 [11:01<51:09, 11.49it/s]

 17%|██████▎                              | 7262/42525 [11:01<54:27, 10.79it/s]

 17%|██████▎                              | 7266/42525 [11:02<54:17, 10.82it/s]

 17%|██████▎                              | 7270/42525 [11:02<52:57, 11.09it/s]

 17%|██████▎                              | 7272/42525 [11:02<52:47, 11.13it/s]

 17%|██████▎                              | 7276/42525 [11:02<54:13, 10.83it/s]

 17%|██████▎                              | 7278/42525 [11:03<54:05, 10.86it/s]

 17%|██████▎                              | 7282/42525 [11:03<56:56, 10.31it/s]

 17%|██████▎                              | 7284/42525 [11:03<55:20, 10.61it/s]

 17%|██████▎                              | 7286/42525 [11:03<56:31, 10.39it/s]

 17%|██████▎                              | 7290/42525 [11:04<57:03, 10.29it/s]

 17%|██████▎                              | 7294/42525 [11:04<54:24, 10.79it/s]

 17%|██████▎                              | 7298/42525 [11:05<53:54, 10.89it/s]

 17%|██████▎                              | 7302/42525 [11:05<55:05, 10.65it/s]

 17%|██████▎                              | 7306/42525 [11:05<52:54, 11.10it/s]

 17%|██████▎                              | 7310/42525 [11:06<54:19, 10.80it/s]

 17%|██████▎                              | 7314/42525 [11:06<55:56, 10.49it/s]

 17%|██████▎                              | 7318/42525 [11:06<54:46, 10.71it/s]

 17%|██████▎                              | 7320/42525 [11:07<53:16, 11.01it/s]

 17%|██████▎                              | 7324/42525 [11:07<55:10, 10.63it/s]

 17%|██████▍                              | 7328/42525 [11:07<53:59, 10.86it/s]

 17%|██████▍                              | 7332/42525 [11:08<56:44, 10.34it/s]

 17%|██████▍                              | 7336/42525 [11:08<53:15, 11.01it/s]

 17%|██████▍                              | 7340/42525 [11:08<49:51, 11.76it/s]

 17%|██████▍                              | 7344/42525 [11:09<51:28, 11.39it/s]

 17%|██████▍                              | 7348/42525 [11:09<50:10, 11.68it/s]

 17%|██████▍                              | 7352/42525 [11:09<51:18, 11.43it/s]

 17%|██████▍                              | 7356/42525 [11:10<53:59, 10.86it/s]

 17%|██████▍                              | 7360/42525 [11:10<51:53, 11.30it/s]

 17%|██████▍                              | 7364/42525 [11:11<49:15, 11.90it/s]

 17%|██████▍                              | 7368/42525 [11:11<50:54, 11.51it/s]

 17%|██████▍                              | 7372/42525 [11:11<50:01, 11.71it/s]

 17%|██████▍                              | 7376/42525 [11:12<52:21, 11.19it/s]

 17%|██████▍                              | 7380/42525 [11:12<52:55, 11.07it/s]

 17%|██████▍                              | 7382/42525 [11:12<51:53, 11.29it/s]

 17%|██████▍                              | 7386/42525 [11:13<52:58, 11.05it/s]

 17%|██████▍                              | 7390/42525 [11:13<53:49, 10.88it/s]

 17%|██████▍                              | 7394/42525 [11:13<52:30, 11.15it/s]

 17%|██████▍                              | 7398/42525 [11:14<51:44, 11.31it/s]

 17%|██████▍                              | 7400/42525 [11:14<53:12, 11.00it/s]

 17%|██████▍                              | 7404/42525 [11:14<55:44, 10.50it/s]

 17%|██████▍                              | 7408/42525 [11:15<53:18, 10.98it/s]

 17%|██████▍                              | 7412/42525 [11:15<51:39, 11.33it/s]

 17%|██████▍                              | 7416/42525 [11:15<52:33, 11.13it/s]

 17%|██████▍                              | 7420/42525 [11:16<51:00, 11.47it/s]

 17%|██████▍                              | 7424/42525 [11:16<54:06, 10.81it/s]

 17%|██████▍                              | 7428/42525 [11:16<53:53, 10.86it/s]

 17%|██████▍                              | 7432/42525 [11:17<52:11, 11.21it/s]

 17%|██████▍                              | 7436/42525 [11:17<50:40, 11.54it/s]

 17%|██████▍                              | 7440/42525 [11:17<51:54, 11.27it/s]

 18%|██████▍                              | 7442/42525 [11:18<49:34, 11.80it/s]

 18%|██████▍                              | 7446/42525 [11:18<50:14, 11.64it/s]

 18%|██████▍                              | 7450/42525 [11:18<51:57, 11.25it/s]

 18%|██████▍                              | 7454/42525 [11:19<47:53, 12.20it/s]

 18%|██████▍                              | 7458/42525 [11:19<48:13, 12.12it/s]

 18%|██████▍                              | 7462/42525 [11:19<46:40, 12.52it/s]

 18%|██████▍                              | 7466/42525 [11:20<52:55, 11.04it/s]

 18%|██████▍                              | 7470/42525 [11:20<55:42, 10.49it/s]

 18%|██████▌                              | 7474/42525 [11:20<55:35, 10.51it/s]

 18%|██████▌                              | 7478/42525 [11:21<55:28, 10.53it/s]

 18%|██████▌                              | 7482/42525 [11:21<54:19, 10.75it/s]

 18%|██████▌                              | 7486/42525 [11:22<53:54, 10.83it/s]

 18%|██████▌                              | 7490/42525 [11:22<52:30, 11.12it/s]

 18%|██████▌                              | 7494/42525 [11:22<53:31, 10.91it/s]

 18%|██████▌                              | 7498/42525 [11:23<52:48, 11.05it/s]

 18%|██████▌                              | 7502/42525 [11:23<52:09, 11.19it/s]

 18%|██████▌                              | 7506/42525 [11:23<52:15, 11.17it/s]

 18%|██████▌                              | 7508/42525 [11:23<51:42, 11.28it/s]

 18%|██████▌                              | 7512/42525 [11:24<55:25, 10.53it/s]

 18%|██████▌                              | 7516/42525 [11:24<53:58, 10.81it/s]

 18%|██████▌                              | 7520/42525 [11:25<53:14, 10.96it/s]

 18%|██████▌                              | 7524/42525 [11:25<54:20, 10.73it/s]

 18%|██████▌                              | 7528/42525 [11:25<54:47, 10.64it/s]

 18%|██████▌                              | 7532/42525 [11:26<55:30, 10.51it/s]

 18%|██████▌                              | 7536/42525 [11:26<53:27, 10.91it/s]

 18%|██████▌                              | 7540/42525 [11:26<51:49, 11.25it/s]

 18%|██████▌                              | 7544/42525 [11:27<51:21, 11.35it/s]

 18%|██████▌                              | 7548/42525 [11:27<53:00, 11.00it/s]

 18%|██████▌                              | 7552/42525 [11:28<52:45, 11.05it/s]

 18%|██████▌                              | 7556/42525 [11:28<52:49, 11.03it/s]

 18%|██████▌                              | 7560/42525 [11:28<51:25, 11.33it/s]

 18%|██████▌                              | 7564/42525 [11:29<52:03, 11.19it/s]

 18%|██████▌                              | 7568/42525 [11:29<51:48, 11.25it/s]

 18%|██████▌                              | 7570/42525 [11:29<51:16, 11.36it/s]

 18%|██████▌                              | 7574/42525 [11:30<53:19, 10.92it/s]

 18%|██████▌                              | 7578/42525 [11:30<55:01, 10.59it/s]

 18%|██████▌                              | 7580/42525 [11:30<54:28, 10.69it/s]

 18%|██████▌                              | 7584/42525 [11:30<55:02, 10.58it/s]

 18%|██████▌                              | 7588/42525 [11:31<54:25, 10.70it/s]

 18%|██████▌                              | 7592/42525 [11:31<54:25, 10.70it/s]

 18%|██████▌                              | 7596/42525 [11:32<56:27, 10.31it/s]

 18%|██████▌                              | 7598/42525 [11:32<57:45, 10.08it/s]

 18%|██████▌                              | 7602/42525 [11:32<56:59, 10.21it/s]

 18%|██████▌                              | 7606/42525 [11:33<53:27, 10.89it/s]

 18%|██████▌                              | 7610/42525 [11:33<54:00, 10.78it/s]

 18%|██████▌                              | 7614/42525 [11:33<52:58, 10.98it/s]

 18%|██████▋                              | 7618/42525 [11:34<52:02, 11.18it/s]

 18%|██████▋                              | 7622/42525 [11:34<53:17, 10.92it/s]

 18%|██████▋                              | 7626/42525 [11:34<52:04, 11.17it/s]

 18%|██████▋                              | 7630/42525 [11:35<52:40, 11.04it/s]

 18%|██████▋                              | 7632/42525 [11:35<52:05, 11.17it/s]

 18%|██████▋                              | 7636/42525 [11:35<54:40, 10.64it/s]

 18%|██████▋                              | 7640/42525 [11:36<55:46, 10.43it/s]

 18%|██████▋                              | 7644/42525 [11:36<54:32, 10.66it/s]

 18%|██████▋                              | 7648/42525 [11:36<54:04, 10.75it/s]

 18%|██████▋                              | 7652/42525 [11:37<53:15, 10.91it/s]

 18%|██████▋                              | 7656/42525 [11:37<50:54, 11.42it/s]

 18%|██████▋                              | 7660/42525 [11:37<49:40, 11.70it/s]

 18%|██████▋                              | 7664/42525 [11:38<49:44, 11.68it/s]

 18%|██████▋                              | 7668/42525 [11:38<48:36, 11.95it/s]

 18%|██████▋                              | 7672/42525 [11:38<48:04, 12.08it/s]

 18%|██████▋                              | 7676/42525 [11:39<50:02, 11.61it/s]

 18%|██████▋                              | 7680/42525 [11:39<51:16, 11.32it/s]

 18%|██████▋                              | 7684/42525 [11:39<48:41, 11.93it/s]

 18%|██████▋                              | 7688/42525 [11:40<46:09, 12.58it/s]

 18%|██████▋                              | 7692/42525 [11:40<48:01, 12.09it/s]

 18%|██████▋                              | 7694/42525 [11:40<50:29, 11.50it/s]

 18%|██████▋                              | 7696/42525 [11:41<54:04, 10.73it/s]

 18%|██████▋                              | 7700/42525 [11:41<56:15, 10.32it/s]

 18%|██████▋                              | 7704/42525 [11:41<53:44, 10.80it/s]

 18%|██████▋                              | 7708/42525 [11:42<52:42, 11.01it/s]

 18%|██████▋                              | 7712/42525 [11:42<53:06, 10.92it/s]

 18%|██████▋                              | 7716/42525 [11:42<52:43, 11.00it/s]

 18%|██████▋                              | 7720/42525 [11:43<51:32, 11.25it/s]

 18%|██████▋                              | 7724/42525 [11:43<51:55, 11.17it/s]

 18%|██████▋                              | 7728/42525 [11:43<50:49, 11.41it/s]

 18%|██████▋                              | 7732/42525 [11:44<53:34, 10.82it/s]

 18%|██████▋                              | 7736/42525 [11:44<49:22, 11.74it/s]

 18%|██████▋                              | 7740/42525 [11:44<47:35, 12.18it/s]

 18%|██████▋                              | 7744/42525 [11:45<50:09, 11.56it/s]

 18%|██████▋                              | 7748/42525 [11:45<53:06, 10.91it/s]

 18%|██████▋                              | 7752/42525 [11:46<52:09, 11.11it/s]

 18%|██████▋                              | 7756/42525 [11:46<51:55, 11.16it/s]

 18%|██████▊                              | 7760/42525 [11:46<52:41, 11.00it/s]

 18%|██████▊                              | 7764/42525 [11:47<51:28, 11.25it/s]

 18%|██████▊                              | 7768/42525 [11:47<52:38, 11.00it/s]

 18%|██████▊                              | 7772/42525 [11:47<52:12, 11.09it/s]

 18%|██████▊                              | 7776/42525 [11:48<53:27, 10.83it/s]

 18%|██████▊                              | 7780/42525 [11:48<50:53, 11.38it/s]

 18%|██████▊                              | 7784/42525 [11:48<48:15, 12.00it/s]

 18%|██████▊                              | 7788/42525 [11:49<52:24, 11.05it/s]

 18%|██████▊                              | 7792/42525 [11:49<50:23, 11.49it/s]

 18%|██████▊                              | 7796/42525 [11:49<50:48, 11.39it/s]

 18%|██████▊                              | 7800/42525 [11:50<52:04, 11.11it/s]

 18%|██████▊                              | 7804/42525 [11:50<52:50, 10.95it/s]

 18%|██████▊                              | 7808/42525 [11:51<54:57, 10.53it/s]

 18%|██████▊                              | 7812/42525 [11:51<52:04, 11.11it/s]

 18%|██████▊                              | 7816/42525 [11:51<53:07, 10.89it/s]

 18%|██████▊                              | 7820/42525 [11:52<53:06, 10.89it/s]

 18%|██████▊                              | 7824/42525 [11:52<53:45, 10.76it/s]

 18%|██████▊                              | 7828/42525 [11:52<54:40, 10.58it/s]

 18%|██████▊                              | 7832/42525 [11:53<51:55, 11.13it/s]

 18%|██████▊                              | 7836/42525 [11:53<51:03, 11.32it/s]

 18%|██████▊                              | 7840/42525 [11:54<52:05, 11.10it/s]

 18%|██████▊                              | 7844/42525 [11:54<50:07, 11.53it/s]

 18%|██████▊                              | 7848/42525 [11:54<50:01, 11.55it/s]

 18%|██████▊                              | 7852/42525 [11:55<49:56, 11.57it/s]

 18%|██████▊                              | 7856/42525 [11:55<49:58, 11.56it/s]

 18%|██████▊                              | 7860/42525 [11:55<49:33, 11.66it/s]

 18%|██████▊                              | 7864/42525 [11:56<49:39, 11.63it/s]

 19%|██████▊                              | 7868/42525 [11:56<49:20, 11.71it/s]

 19%|██████▊                              | 7872/42525 [11:56<51:10, 11.28it/s]

 19%|██████▊                              | 7876/42525 [11:57<48:49, 11.83it/s]

 19%|██████▊                              | 7880/42525 [11:57<50:05, 11.53it/s]

 19%|██████▊                              | 7884/42525 [11:57<50:28, 11.44it/s]

 19%|██████▊                              | 7888/42525 [11:58<49:12, 11.73it/s]

 19%|██████▊                              | 7892/42525 [11:58<48:28, 11.91it/s]

 19%|██████▊                              | 7896/42525 [11:58<52:08, 11.07it/s]

 19%|██████▊                              | 7900/42525 [11:59<54:06, 10.66it/s]

 19%|██████▉                              | 7904/42525 [11:59<55:11, 10.46it/s]

 19%|██████▉                              | 7908/42525 [12:00<54:34, 10.57it/s]

 19%|██████▉                              | 7912/42525 [12:00<52:52, 10.91it/s]

 19%|██████▉                              | 7916/42525 [12:00<51:50, 11.13it/s]

 19%|██████▉                              | 7920/42525 [12:01<54:39, 10.55it/s]

 19%|██████▉                              | 7924/42525 [12:01<54:42, 10.54it/s]

 19%|██████▉                              | 7928/42525 [12:01<52:36, 10.96it/s]

 19%|██████▉                              | 7932/42525 [12:02<52:46, 10.92it/s]

 19%|██████▉                              | 7936/42525 [12:02<51:27, 11.20it/s]

 19%|██████▉                              | 7940/42525 [12:02<50:28, 11.42it/s]

 19%|██████▉                              | 7944/42525 [12:03<49:14, 11.70it/s]

 19%|██████▉                              | 7948/42525 [12:03<48:19, 11.92it/s]

 19%|██████▉                              | 7952/42525 [12:03<51:02, 11.29it/s]

 19%|██████▉                              | 7956/42525 [12:04<52:47, 10.91it/s]

 19%|██████▉                              | 7958/42525 [12:04<54:31, 10.57it/s]

 19%|██████▉                              | 7962/42525 [12:04<53:20, 10.80it/s]

 19%|██████▉                              | 7966/42525 [12:05<49:00, 11.75it/s]

 19%|██████▉                              | 7970/42525 [12:05<48:08, 11.96it/s]

 19%|██████▉                              | 7974/42525 [12:05<50:08, 11.49it/s]

 19%|██████▉                              | 7978/42525 [12:06<50:27, 11.41it/s]

 19%|██████▉                              | 7982/42525 [12:06<49:15, 11.69it/s]

 19%|██████▉                              | 7986/42525 [12:06<49:49, 11.55it/s]

 19%|██████▉                              | 7990/42525 [12:07<47:40, 12.07it/s]

 19%|██████▉                              | 7994/42525 [12:07<48:36, 11.84it/s]

 19%|██████▉                              | 7998/42525 [12:07<48:09, 11.95it/s]

 19%|██████▉                              | 8000/42525 [12:08<50:08, 11.48it/s]

 19%|██████▉                              | 8004/42525 [12:08<52:40, 10.92it/s]

 19%|██████▉                              | 8008/42525 [12:08<49:12, 11.69it/s]

 19%|██████▉                              | 8012/42525 [12:09<46:36, 12.34it/s]

 19%|██████▉                              | 8016/42525 [12:09<50:22, 11.42it/s]

 19%|██████▉                              | 8020/42525 [12:09<48:24, 11.88it/s]

 19%|██████▉                              | 8024/42525 [12:10<49:17, 11.67it/s]

 19%|██████▉                              | 8028/42525 [12:10<49:18, 11.66it/s]

 19%|██████▉                              | 8032/42525 [12:10<48:47, 11.78it/s]

 19%|██████▉                              | 8036/42525 [12:11<49:10, 11.69it/s]

 19%|██████▉                              | 8040/42525 [12:11<51:37, 11.13it/s]

 19%|██████▉                              | 8044/42525 [12:11<49:28, 11.61it/s]

 19%|███████                              | 8048/42525 [12:12<49:44, 11.55it/s]

 19%|███████                              | 8052/42525 [12:12<49:02, 11.71it/s]

 19%|███████                              | 8056/42525 [12:12<48:22, 11.87it/s]

 19%|███████                              | 8060/42525 [12:13<48:56, 11.74it/s]

 19%|███████                              | 8062/42525 [12:13<48:55, 11.74it/s]

 19%|███████                              | 8066/42525 [12:13<50:16, 11.42it/s]

 19%|███████                              | 8070/42525 [12:14<51:19, 11.19it/s]

 19%|███████                              | 8074/42525 [12:14<52:16, 10.98it/s]

 19%|███████                              | 8078/42525 [12:14<49:52, 11.51it/s]

 19%|███████                              | 8082/42525 [12:15<50:51, 11.29it/s]

 19%|███████                              | 8086/42525 [12:15<52:27, 10.94it/s]

 19%|███████                              | 8090/42525 [12:15<49:12, 11.66it/s]

 19%|███████                              | 8094/42525 [12:16<49:25, 11.61it/s]

 19%|███████                              | 8098/42525 [12:16<49:57, 11.49it/s]

 19%|███████                              | 8102/42525 [12:16<49:12, 11.66it/s]

 19%|███████                              | 8106/42525 [12:17<50:07, 11.44it/s]

 19%|███████                              | 8110/42525 [12:17<47:51, 11.99it/s]

 19%|███████                              | 8112/42525 [12:17<50:03, 11.46it/s]

 19%|███████                              | 8116/42525 [12:18<52:51, 10.85it/s]

 19%|███████                              | 8120/42525 [12:18<51:09, 11.21it/s]

 19%|███████                              | 8124/42525 [12:18<47:42, 12.02it/s]

 19%|███████                              | 8128/42525 [12:19<48:58, 11.70it/s]

 19%|███████                              | 8132/42525 [12:19<47:35, 12.04it/s]

 19%|███████                              | 8136/42525 [12:19<47:32, 12.06it/s]

 19%|███████                              | 8140/42525 [12:20<50:15, 11.40it/s]

 19%|███████                              | 8144/42525 [12:20<51:24, 11.15it/s]

 19%|███████                              | 8148/42525 [12:21<52:08, 10.99it/s]

 19%|███████                              | 8152/42525 [12:21<52:33, 10.90it/s]

 19%|███████                              | 8156/42525 [12:21<51:23, 11.15it/s]

 19%|███████                              | 8160/42525 [12:22<51:53, 11.04it/s]

 19%|███████                              | 8164/42525 [12:22<52:33, 10.90it/s]

 19%|███████                              | 8168/42525 [12:22<51:45, 11.06it/s]

 19%|███████                              | 8172/42525 [12:23<53:13, 10.76it/s]

 19%|███████                              | 8176/42525 [12:23<54:04, 10.59it/s]

 19%|███████                              | 8180/42525 [12:23<53:39, 10.67it/s]

 19%|███████                              | 8184/42525 [12:24<52:08, 10.98it/s]

 19%|███████                              | 8188/42525 [12:24<52:13, 10.96it/s]

 19%|███████▏                             | 8192/42525 [12:25<52:11, 10.96it/s]

 19%|███████▏                             | 8196/42525 [12:25<51:17, 11.15it/s]

 19%|███████▏                             | 8200/42525 [12:25<51:26, 11.12it/s]

 19%|███████▏                             | 8204/42525 [12:26<54:16, 10.54it/s]

 19%|███████▏                             | 8208/42525 [12:26<54:39, 10.46it/s]

 19%|███████▏                             | 8212/42525 [12:26<53:34, 10.68it/s]

 19%|███████▏                             | 8216/42525 [12:27<53:13, 10.74it/s]

 19%|███████▏                             | 8220/42525 [12:27<52:11, 10.95it/s]

 19%|███████▏                             | 8224/42525 [12:28<52:38, 10.86it/s]

 19%|███████▏                             | 8228/42525 [12:28<50:40, 11.28it/s]

 19%|███████▏                             | 8232/42525 [12:28<51:44, 11.05it/s]

 19%|███████▏                             | 8234/42525 [12:28<52:38, 10.86it/s]

 19%|███████▏                             | 8238/42525 [12:29<51:05, 11.18it/s]

 19%|███████▏                             | 8242/42525 [12:29<47:13, 12.10it/s]

 19%|███████▏                             | 8246/42525 [12:29<44:04, 12.96it/s]

 19%|███████▏                             | 8250/42525 [12:30<46:01, 12.41it/s]

 19%|███████▏                             | 8254/42525 [12:30<51:25, 11.11it/s]

 19%|███████▏                             | 8258/42525 [12:31<52:50, 10.81it/s]

 19%|███████▏                             | 8260/42525 [12:31<51:19, 11.13it/s]

 19%|███████▏                             | 8264/42525 [12:31<53:15, 10.72it/s]

 19%|███████▏                             | 8268/42525 [12:31<49:16, 11.59it/s]

 19%|███████▏                             | 8272/42525 [12:32<49:58, 11.42it/s]

 19%|███████▏                             | 8276/42525 [12:32<46:37, 12.24it/s]

 19%|███████▏                             | 8280/42525 [12:32<48:54, 11.67it/s]

 19%|███████▏                             | 8284/42525 [12:33<48:25, 11.78it/s]

 19%|███████▏                             | 8288/42525 [12:33<49:39, 11.49it/s]

 19%|███████▏                             | 8292/42525 [12:33<45:17, 12.60it/s]

 20%|███████▏                             | 8296/42525 [12:34<46:11, 12.35it/s]

 20%|███████▏                             | 8300/42525 [12:34<48:02, 11.88it/s]

 20%|███████▏                             | 8304/42525 [12:34<49:13, 11.59it/s]

 20%|███████▏                             | 8308/42525 [12:35<48:22, 11.79it/s]

 20%|███████▏                             | 8312/42525 [12:35<47:44, 11.94it/s]

 20%|███████▏                             | 8316/42525 [12:35<46:12, 12.34it/s]

 20%|███████▏                             | 8320/42525 [12:36<49:11, 11.59it/s]

 20%|███████▏                             | 8324/42525 [12:36<46:44, 12.19it/s]

 20%|███████▏                             | 8328/42525 [12:36<47:54, 11.90it/s]

 20%|███████▏                             | 8332/42525 [12:37<48:09, 11.83it/s]

 20%|███████▎                             | 8336/42525 [12:37<47:49, 11.92it/s]

 20%|███████▎                             | 8340/42525 [12:37<48:00, 11.87it/s]

 20%|███████▎                             | 8344/42525 [12:38<47:50, 11.91it/s]

 20%|███████▎                             | 8348/42525 [12:38<47:29, 11.99it/s]

 20%|███████▎                             | 8352/42525 [12:38<43:56, 12.96it/s]

 20%|███████▎                             | 8356/42525 [12:39<47:10, 12.07it/s]

 20%|███████▎                             | 8360/42525 [12:39<46:17, 12.30it/s]

 20%|███████▎                             | 8362/42525 [12:39<45:17, 12.57it/s]

 20%|███████▎                             | 8366/42525 [12:40<47:48, 11.91it/s]

 20%|███████▎                             | 8370/42525 [12:40<51:30, 11.05it/s]

 20%|███████▎                             | 8374/42525 [12:40<51:38, 11.02it/s]

 20%|███████▎                             | 8378/42525 [12:41<50:05, 11.36it/s]

 20%|███████▎                             | 8382/42525 [12:41<47:40, 11.94it/s]

 20%|███████▎                             | 8384/42525 [12:41<47:51, 11.89it/s]

 20%|███████▎                             | 8388/42525 [12:42<50:22, 11.29it/s]

 20%|███████▎                             | 8392/42525 [12:42<52:07, 10.92it/s]

 20%|███████▎                             | 8396/42525 [12:42<50:48, 11.19it/s]

 20%|███████▎                             | 8400/42525 [12:43<49:37, 11.46it/s]

 20%|███████▎                             | 8404/42525 [12:43<47:57, 11.86it/s]

 20%|███████▎                             | 8408/42525 [12:43<49:19, 11.53it/s]

 20%|███████▎                             | 8412/42525 [12:44<49:43, 11.43it/s]

 20%|███████▎                             | 8416/42525 [12:44<48:14, 11.78it/s]

 20%|███████▎                             | 8420/42525 [12:44<44:14, 12.85it/s]

 20%|███████▎                             | 8424/42525 [12:45<45:52, 12.39it/s]

 20%|███████▎                             | 8428/42525 [12:45<46:40, 12.18it/s]

 20%|███████▎                             | 8432/42525 [12:45<45:35, 12.47it/s]

 20%|███████▎                             | 8436/42525 [12:46<46:50, 12.13it/s]

 20%|███████▎                             | 8440/42525 [12:46<48:02, 11.82it/s]

 20%|███████▎                             | 8444/42525 [12:46<50:20, 11.28it/s]

 20%|███████▎                             | 8448/42525 [12:47<47:12, 12.03it/s]

 20%|███████▎                             | 8452/42525 [12:47<50:18, 11.29it/s]

 20%|███████▎                             | 8456/42525 [12:47<45:37, 12.44it/s]

 20%|███████▎                             | 8460/42525 [12:48<44:29, 12.76it/s]

 20%|███████▎                             | 8464/42525 [12:48<45:44, 12.41it/s]

 20%|███████▎                             | 8468/42525 [12:48<47:07, 12.04it/s]

 20%|███████▎                             | 8472/42525 [12:49<49:48, 11.39it/s]

 20%|███████▎                             | 8476/42525 [12:49<47:47, 11.87it/s]

 20%|███████▍                             | 8480/42525 [12:49<47:40, 11.90it/s]

 20%|███████▍                             | 8484/42525 [12:50<51:45, 10.96it/s]

 20%|███████▍                             | 8488/42525 [12:50<49:03, 11.56it/s]

 20%|███████▍                             | 8492/42525 [12:50<46:02, 12.32it/s]

 20%|███████▍                             | 8496/42525 [12:51<43:04, 13.17it/s]

 20%|███████▍                             | 8500/42525 [12:51<45:35, 12.44it/s]

 20%|███████▍                             | 8504/42525 [12:51<49:19, 11.50it/s]

 20%|███████▍                             | 8508/42525 [12:52<50:49, 11.15it/s]

 20%|███████▍                             | 8512/42525 [12:52<46:47, 12.12it/s]

 20%|███████▍                             | 8516/42525 [12:52<44:55, 12.62it/s]

 20%|███████▍                             | 8520/42525 [12:53<47:14, 12.00it/s]

 20%|███████▍                             | 8524/42525 [12:53<44:40, 12.68it/s]

 20%|███████▍                             | 8528/42525 [12:53<43:49, 12.93it/s]

 20%|███████▍                             | 8532/42525 [12:54<47:28, 11.93it/s]

 20%|███████▍                             | 8534/42525 [12:54<49:11, 11.52it/s]

 20%|███████▍                             | 8538/42525 [12:54<53:18, 10.63it/s]

 20%|███████▍                             | 8542/42525 [12:55<53:55, 10.50it/s]

 20%|███████▍                             | 8546/42525 [12:55<52:28, 10.79it/s]

 20%|███████▍                             | 8550/42525 [12:55<50:51, 11.13it/s]

 20%|███████▍                             | 8554/42525 [12:56<50:40, 11.17it/s]

 20%|███████▍                             | 8558/42525 [12:56<50:26, 11.22it/s]

 20%|███████▍                             | 8562/42525 [12:56<53:04, 10.66it/s]

 20%|███████▍                             | 8564/42525 [12:57<52:50, 10.71it/s]

 20%|███████▍                             | 8568/42525 [12:57<52:56, 10.69it/s]

 20%|███████▍                             | 8572/42525 [12:57<54:07, 10.45it/s]

 20%|███████▍                             | 8576/42525 [12:58<51:06, 11.07it/s]

 20%|███████▍                             | 8580/42525 [12:58<50:01, 11.31it/s]

 20%|███████▍                             | 8584/42525 [12:58<52:00, 10.88it/s]

 20%|███████▍                             | 8588/42525 [12:59<52:57, 10.68it/s]

 20%|███████▍                             | 8592/42525 [12:59<51:56, 10.89it/s]

 20%|███████▍                             | 8596/42525 [13:00<51:47, 10.92it/s]

 20%|███████▍                             | 8600/42525 [13:00<52:24, 10.79it/s]

 20%|███████▍                             | 8604/42525 [13:00<52:03, 10.86it/s]

 20%|███████▍                             | 8608/42525 [13:01<49:47, 11.35it/s]

 20%|███████▍                             | 8612/42525 [13:01<50:23, 11.22it/s]

 20%|███████▍                             | 8616/42525 [13:01<49:31, 11.41it/s]

 20%|███████▌                             | 8620/42525 [13:02<50:38, 11.16it/s]

 20%|███████▌                             | 8622/42525 [13:02<50:26, 11.20it/s]

 20%|███████▌                             | 8626/42525 [13:02<52:18, 10.80it/s]

 20%|███████▌                             | 8630/42525 [13:03<52:53, 10.68it/s]

 20%|███████▌                             | 8634/42525 [13:03<50:49, 11.11it/s]

 20%|███████▌                             | 8638/42525 [13:03<52:08, 10.83it/s]

 20%|███████▌                             | 8642/42525 [13:04<52:13, 10.81it/s]

 20%|███████▌                             | 8646/42525 [13:04<50:32, 11.17it/s]

 20%|███████▌                             | 8650/42525 [13:04<50:08, 11.26it/s]

 20%|███████▌                             | 8654/42525 [13:05<52:52, 10.68it/s]

 20%|███████▌                             | 8658/42525 [13:05<51:00, 11.07it/s]

 20%|███████▌                             | 8662/42525 [13:06<51:16, 11.01it/s]

 20%|███████▌                             | 8666/42525 [13:06<50:48, 11.11it/s]

 20%|███████▌                             | 8670/42525 [13:06<51:28, 10.96it/s]

 20%|███████▌                             | 8674/42525 [13:07<51:19, 10.99it/s]

 20%|███████▌                             | 8678/42525 [13:07<51:28, 10.96it/s]

 20%|███████▌                             | 8682/42525 [13:07<53:35, 10.53it/s]

 20%|███████▌                             | 8686/42525 [13:08<51:48, 10.89it/s]

 20%|███████▌                             | 8690/42525 [13:08<51:00, 11.05it/s]

 20%|███████▌                             | 8694/42525 [13:09<52:40, 10.70it/s]

 20%|███████▌                             | 8698/42525 [13:09<51:58, 10.85it/s]

 20%|███████▌                             | 8702/42525 [13:09<53:30, 10.54it/s]

 20%|███████▌                             | 8706/42525 [13:10<51:10, 11.01it/s]

 20%|███████▌                             | 8710/42525 [13:10<50:43, 11.11it/s]

 20%|███████▌                             | 8714/42525 [13:10<50:42, 11.11it/s]

 21%|███████▌                             | 8718/42525 [13:11<52:02, 10.83it/s]

 21%|███████▌                             | 8722/42525 [13:11<50:51, 11.08it/s]

 21%|███████▌                             | 8726/42525 [13:11<52:12, 10.79it/s]

 21%|███████▌                             | 8730/42525 [13:12<50:07, 11.24it/s]

 21%|███████▌                             | 8734/42525 [13:12<50:49, 11.08it/s]

 21%|███████▌                             | 8738/42525 [13:13<51:07, 11.01it/s]

 21%|███████▌                             | 8742/42525 [13:13<52:24, 10.74it/s]

 21%|███████▌                             | 8746/42525 [13:13<51:23, 10.95it/s]

 21%|███████▌                             | 8748/42525 [13:13<53:33, 10.51it/s]

 21%|███████▌                             | 8752/42525 [13:14<54:14, 10.38it/s]

 21%|███████▌                             | 8756/42525 [13:14<52:51, 10.65it/s]

 21%|███████▌                             | 8760/42525 [13:15<50:22, 11.17it/s]

 21%|███████▋                             | 8764/42525 [13:15<50:04, 11.24it/s]

 21%|███████▋                             | 8768/42525 [13:15<49:45, 11.31it/s]

 21%|███████▋                             | 8772/42525 [13:16<49:49, 11.29it/s]

 21%|███████▋                             | 8776/42525 [13:16<50:24, 11.16it/s]

 21%|███████▋                             | 8780/42525 [13:16<49:41, 11.32it/s]

 21%|███████▋                             | 8784/42525 [13:17<50:25, 11.15it/s]

 21%|███████▋                             | 8788/42525 [13:17<51:32, 10.91it/s]

 21%|███████▋                             | 8792/42525 [13:17<52:11, 10.77it/s]

 21%|███████▋                             | 8796/42525 [13:18<50:34, 11.11it/s]

 21%|███████▋                             | 8800/42525 [13:18<50:31, 11.12it/s]

 21%|███████▋                             | 8804/42525 [13:19<51:30, 10.91it/s]

 21%|███████▋                             | 8808/42525 [13:19<50:03, 11.23it/s]

 21%|███████▋                             | 8812/42525 [13:19<49:04, 11.45it/s]

 21%|███████▋                             | 8816/42525 [13:20<50:10, 11.20it/s]

 21%|███████▋                             | 8820/42525 [13:20<50:42, 11.08it/s]

 21%|███████▋                             | 8824/42525 [13:20<52:25, 10.72it/s]

 21%|███████▋                             | 8828/42525 [13:21<52:44, 10.65it/s]

 21%|███████▋                             | 8832/42525 [13:21<51:58, 10.81it/s]

 21%|███████▋                             | 8836/42525 [13:21<50:32, 11.11it/s]

 21%|███████▋                             | 8840/42525 [13:22<49:31, 11.34it/s]

 21%|███████▋                             | 8844/42525 [13:22<51:40, 10.86it/s]

 21%|███████▋                             | 8848/42525 [13:23<51:56, 10.81it/s]

 21%|███████▋                             | 8852/42525 [13:23<50:19, 11.15it/s]

 21%|███████▋                             | 8856/42525 [13:23<50:00, 11.22it/s]

 21%|███████▋                             | 8860/42525 [13:24<51:19, 10.93it/s]

 21%|███████▋                             | 8864/42525 [13:24<50:40, 11.07it/s]

 21%|███████▋                             | 8868/42525 [13:24<51:03, 10.99it/s]

 21%|███████▋                             | 8872/42525 [13:25<50:14, 11.16it/s]

 21%|███████▋                             | 8876/42525 [13:25<52:50, 10.61it/s]

 21%|███████▋                             | 8880/42525 [13:25<51:30, 10.89it/s]

 21%|███████▋                             | 8884/42525 [13:26<51:49, 10.82it/s]

 21%|███████▋                             | 8888/42525 [13:26<51:52, 10.81it/s]

 21%|███████▋                             | 8892/42525 [13:27<51:26, 10.90it/s]

 21%|███████▋                             | 8896/42525 [13:27<49:59, 11.21it/s]

 21%|███████▋                             | 8900/42525 [13:27<50:26, 11.11it/s]

 21%|███████▋                             | 8904/42525 [13:28<50:42, 11.05it/s]

 21%|███████▊                             | 8908/42525 [13:28<49:26, 11.33it/s]

 21%|███████▊                             | 8912/42525 [13:28<51:04, 10.97it/s]

 21%|███████▊                             | 8914/42525 [13:29<51:23, 10.90it/s]

 21%|███████▊                             | 8918/42525 [13:29<52:54, 10.59it/s]

 21%|███████▊                             | 8922/42525 [13:29<52:00, 10.77it/s]

 21%|███████▊                             | 8926/42525 [13:30<51:23, 10.90it/s]

 21%|███████▊                             | 8930/42525 [13:30<51:46, 10.81it/s]

 21%|███████▊                             | 8934/42525 [13:30<51:41, 10.83it/s]

 21%|███████▊                             | 8938/42525 [13:31<51:18, 10.91it/s]

 21%|███████▊                             | 8942/42525 [13:31<52:15, 10.71it/s]

 21%|███████▊                             | 8946/42525 [13:32<52:20, 10.69it/s]

 21%|███████▊                             | 8948/42525 [13:32<52:46, 10.60it/s]

 21%|███████▊                             | 8952/42525 [13:32<53:05, 10.54it/s]

 21%|███████▊                             | 8956/42525 [13:32<52:28, 10.66it/s]

 21%|███████▊                             | 8960/42525 [13:33<50:28, 11.08it/s]

 21%|███████▊                             | 8964/42525 [13:33<50:25, 11.09it/s]

 21%|███████▊                             | 8968/42525 [13:34<51:08, 10.94it/s]

 21%|███████▊                             | 8972/42525 [13:34<50:41, 11.03it/s]

 21%|███████▊                             | 8976/42525 [13:34<50:30, 11.07it/s]

 21%|███████▊                             | 8980/42525 [13:35<50:57, 10.97it/s]

 21%|███████▊                             | 8982/42525 [13:35<49:21, 11.33it/s]

 21%|███████▊                             | 8986/42525 [13:35<51:20, 10.89it/s]

 21%|███████▊                             | 8990/42525 [13:36<47:02, 11.88it/s]

 21%|███████▊                             | 8994/42525 [13:36<47:11, 11.84it/s]

 21%|███████▊                             | 8998/42525 [13:36<47:19, 11.81it/s]

 21%|███████▊                             | 9002/42525 [13:37<51:06, 10.93it/s]

 21%|███████▊                             | 9006/42525 [13:37<47:54, 11.66it/s]

 21%|███████▊                             | 9010/42525 [13:37<50:43, 11.01it/s]

 21%|███████▊                             | 9014/42525 [13:38<49:55, 11.19it/s]

 21%|███████▊                             | 9018/42525 [13:38<48:38, 11.48it/s]

 21%|███████▊                             | 9022/42525 [13:38<50:26, 11.07it/s]

 21%|███████▊                             | 9026/42525 [13:39<49:07, 11.37it/s]

 21%|███████▊                             | 9030/42525 [13:39<49:47, 11.21it/s]

 21%|███████▊                             | 9034/42525 [13:39<48:35, 11.49it/s]

 21%|███████▊                             | 9038/42525 [13:40<48:33, 11.49it/s]

 21%|███████▊                             | 9042/42525 [13:40<47:32, 11.74it/s]

 21%|███████▊                             | 9046/42525 [13:40<50:33, 11.04it/s]

 21%|███████▊                             | 9050/42525 [13:41<48:48, 11.43it/s]

 21%|███████▉                             | 9054/42525 [13:41<49:16, 11.32it/s]

 21%|███████▉                             | 9058/42525 [13:41<48:53, 11.41it/s]

 21%|███████▉                             | 9062/42525 [13:42<48:20, 11.54it/s]

 21%|███████▉                             | 9066/42525 [13:42<48:39, 11.46it/s]

 21%|███████▉                             | 9070/42525 [13:43<49:48, 11.19it/s]

 21%|███████▉                             | 9074/42525 [13:43<50:08, 11.12it/s]

 21%|███████▉                             | 9078/42525 [13:43<50:13, 11.10it/s]

 21%|███████▉                             | 9082/42525 [13:44<49:16, 11.31it/s]

 21%|███████▉                             | 9084/42525 [13:44<51:14, 10.88it/s]

 21%|███████▉                             | 9088/42525 [13:44<52:49, 10.55it/s]

 21%|███████▉                             | 9092/42525 [13:45<51:56, 10.73it/s]

 21%|███████▉                             | 9096/42525 [13:45<51:31, 10.81it/s]

 21%|███████▉                             | 9098/42525 [13:45<49:51, 11.18it/s]

 21%|███████▉                             | 9102/42525 [13:46<53:34, 10.40it/s]

 21%|███████▉                             | 9106/42525 [13:46<50:40, 10.99it/s]

 21%|███████▉                             | 9110/42525 [13:46<48:25, 11.50it/s]

 21%|███████▉                             | 9114/42525 [13:47<48:52, 11.40it/s]

 21%|███████▉                             | 9118/42525 [13:47<48:07, 11.57it/s]

 21%|███████▉                             | 9122/42525 [13:47<48:07, 11.57it/s]

 21%|███████▉                             | 9126/42525 [13:48<47:54, 11.62it/s]

 21%|███████▉                             | 9130/42525 [13:48<48:25, 11.49it/s]

 21%|███████▉                             | 9134/42525 [13:48<48:37, 11.45it/s]

 21%|███████▉                             | 9138/42525 [13:49<45:40, 12.18it/s]

 21%|███████▉                             | 9142/42525 [13:49<47:34, 11.70it/s]

 22%|███████▉                             | 9146/42525 [13:49<45:58, 12.10it/s]

 22%|███████▉                             | 9150/42525 [13:50<43:13, 12.87it/s]

 22%|███████▉                             | 9154/42525 [13:50<46:08, 12.05it/s]

 22%|███████▉                             | 9158/42525 [13:50<47:08, 11.80it/s]

 22%|███████▉                             | 9162/42525 [13:51<48:15, 11.52it/s]

 22%|███████▉                             | 9166/42525 [13:51<49:29, 11.23it/s]

 22%|███████▉                             | 9170/42525 [13:51<47:54, 11.60it/s]

 22%|███████▉                             | 9174/42525 [13:52<49:25, 11.24it/s]

 22%|███████▉                             | 9178/42525 [13:52<50:06, 11.09it/s]

 22%|███████▉                             | 9182/42525 [13:52<51:06, 10.87it/s]

 22%|███████▉                             | 9186/42525 [13:53<51:37, 10.76it/s]

 22%|███████▉                             | 9190/42525 [13:53<50:07, 11.08it/s]

 22%|███████▉                             | 9194/42525 [13:54<51:22, 10.81it/s]

 22%|████████                             | 9198/42525 [13:54<50:42, 10.95it/s]

 22%|████████                             | 9202/42525 [13:54<47:18, 11.74it/s]

 22%|████████                             | 9206/42525 [13:55<50:27, 11.01it/s]

 22%|████████                             | 9210/42525 [13:55<46:50, 11.85it/s]

 22%|████████                             | 9214/42525 [13:55<48:28, 11.45it/s]

 22%|████████                             | 9218/42525 [13:56<48:01, 11.56it/s]

 22%|████████                             | 9220/42525 [13:56<48:57, 11.34it/s]

 22%|████████                             | 9224/42525 [13:56<49:20, 11.25it/s]

 22%|████████                             | 9228/42525 [13:57<47:28, 11.69it/s]

 22%|████████                             | 9232/42525 [13:57<47:36, 11.66it/s]

 22%|████████                             | 9236/42525 [13:57<45:49, 12.11it/s]

 22%|████████                             | 9240/42525 [13:58<46:20, 11.97it/s]

 22%|████████                             | 9244/42525 [13:58<48:32, 11.43it/s]

 22%|████████                             | 9248/42525 [13:58<47:29, 11.68it/s]

 22%|████████                             | 9252/42525 [13:59<46:52, 11.83it/s]

 22%|████████                             | 9256/42525 [13:59<47:50, 11.59it/s]

 22%|████████                             | 9260/42525 [13:59<48:27, 11.44it/s]

 22%|████████                             | 9264/42525 [14:00<48:17, 11.48it/s]

 22%|████████                             | 9268/42525 [14:00<49:17, 11.24it/s]

 22%|████████                             | 9272/42525 [14:00<48:57, 11.32it/s]

 22%|████████                             | 9276/42525 [14:01<47:44, 11.61it/s]

 22%|████████                             | 9280/42525 [14:01<50:02, 11.07it/s]

 22%|████████                             | 9284/42525 [14:01<48:08, 11.51it/s]

 22%|████████                             | 9288/42525 [14:02<46:53, 11.81it/s]

 22%|████████                             | 9292/42525 [14:02<45:58, 12.05it/s]

 22%|████████                             | 9296/42525 [14:02<43:25, 12.75it/s]

 22%|████████                             | 9300/42525 [14:03<46:12, 11.98it/s]

 22%|████████                             | 9304/42525 [14:03<44:51, 12.34it/s]

 22%|████████                             | 9308/42525 [14:03<47:47, 11.58it/s]

 22%|████████                             | 9312/42525 [14:04<46:40, 11.86it/s]

 22%|████████                             | 9316/42525 [14:04<44:44, 12.37it/s]

 22%|████████                             | 9320/42525 [14:04<47:21, 11.69it/s]

 22%|████████                             | 9324/42525 [14:05<51:18, 10.78it/s]

 22%|████████                             | 9328/42525 [14:05<48:23, 11.43it/s]

 22%|████████                             | 9332/42525 [14:05<46:30, 11.90it/s]

 22%|████████                             | 9336/42525 [14:06<49:01, 11.28it/s]

 22%|████████▏                            | 9340/42525 [14:06<46:59, 11.77it/s]

 22%|████████▏                            | 9344/42525 [14:06<47:30, 11.64it/s]

 22%|████████▏                            | 9348/42525 [14:07<48:18, 11.45it/s]

 22%|████████▏                            | 9352/42525 [14:07<48:33, 11.39it/s]

 22%|████████▏                            | 9356/42525 [14:07<43:53, 12.59it/s]

 22%|████████▏                            | 9360/42525 [14:08<46:20, 11.93it/s]

 22%|████████▏                            | 9364/42525 [14:08<46:59, 11.76it/s]

 22%|████████▏                            | 9368/42525 [14:09<50:35, 10.92it/s]

 22%|████████▏                            | 9372/42525 [14:09<52:40, 10.49it/s]

 22%|████████▏                            | 9376/42525 [14:09<53:01, 10.42it/s]

 22%|████████▏                            | 9380/42525 [14:10<51:18, 10.77it/s]

 22%|████████▏                            | 9384/42525 [14:10<48:45, 11.33it/s]

 22%|████████▏                            | 9386/42525 [14:10<45:51, 12.04it/s]

 22%|████████▏                            | 9388/42525 [14:10<48:58, 11.28it/s]

 22%|████████▏                            | 9392/42525 [14:11<51:41, 10.68it/s]

 22%|████████▏                            | 9396/42525 [14:11<51:25, 10.74it/s]

 22%|████████▏                            | 9400/42525 [14:11<51:36, 10.70it/s]

 22%|████████▏                            | 9404/42525 [14:12<51:20, 10.75it/s]

 22%|████████▏                            | 9408/42525 [14:12<53:15, 10.36it/s]

 22%|████████▏                            | 9412/42525 [14:13<51:56, 10.63it/s]

 22%|████████▏                            | 9416/42525 [14:13<51:24, 10.73it/s]

 22%|████████▏                            | 9420/42525 [14:13<51:16, 10.76it/s]

 22%|████████▏                            | 9424/42525 [14:14<52:19, 10.54it/s]

 22%|████████▏                            | 9428/42525 [14:14<51:52, 10.63it/s]

 22%|████████▏                            | 9432/42525 [14:15<53:09, 10.38it/s]

 22%|████████▏                            | 9434/42525 [14:15<55:31,  9.93it/s]

 22%|████████▏                            | 9438/42525 [14:15<55:21,  9.96it/s]

 22%|████████▏                            | 9442/42525 [14:16<52:12, 10.56it/s]

 22%|████████▏                            | 9446/42525 [14:16<52:07, 10.58it/s]

 22%|████████▏                            | 9450/42525 [14:16<51:56, 10.61it/s]

 22%|████████▏                            | 9454/42525 [14:17<49:47, 11.07it/s]

 22%|████████▏                            | 9458/42525 [14:17<49:47, 11.07it/s]

 22%|████████▏                            | 9462/42525 [14:17<50:47, 10.85it/s]

 22%|████████▏                            | 9466/42525 [14:18<50:22, 10.94it/s]

 22%|████████▏                            | 9470/42525 [14:18<48:27, 11.37it/s]

 22%|████████▏                            | 9474/42525 [14:18<50:18, 10.95it/s]

 22%|████████▏                            | 9476/42525 [14:19<48:27, 11.37it/s]

 22%|████████▏                            | 9480/42525 [14:19<50:27, 10.91it/s]

 22%|████████▎                            | 9484/42525 [14:19<48:36, 11.33it/s]

 22%|████████▎                            | 9488/42525 [14:20<50:03, 11.00it/s]

 22%|████████▎                            | 9490/42525 [14:20<48:52, 11.27it/s]

 22%|████████▎                            | 9494/42525 [14:20<51:34, 10.67it/s]

 22%|████████▎                            | 9498/42525 [14:21<50:52, 10.82it/s]

 22%|████████▎                            | 9502/42525 [14:21<49:00, 11.23it/s]

 22%|████████▎                            | 9506/42525 [14:21<45:38, 12.06it/s]

 22%|████████▎                            | 9510/42525 [14:22<45:26, 12.11it/s]

 22%|████████▎                            | 9514/42525 [14:22<44:01, 12.50it/s]

 22%|████████▎                            | 9518/42525 [14:22<47:14, 11.65it/s]

 22%|████████▎                            | 9522/42525 [14:23<49:49, 11.04it/s]

 22%|████████▎                            | 9526/42525 [14:23<45:42, 12.03it/s]

 22%|████████▎                            | 9530/42525 [14:23<50:54, 10.80it/s]

 22%|████████▎                            | 9534/42525 [14:24<47:53, 11.48it/s]

 22%|████████▎                            | 9538/42525 [14:24<47:34, 11.56it/s]

 22%|████████▎                            | 9542/42525 [14:24<47:58, 11.46it/s]

 22%|████████▎                            | 9546/42525 [14:25<45:41, 12.03it/s]

 22%|████████▎                            | 9550/42525 [14:25<47:43, 11.51it/s]

 22%|████████▎                            | 9554/42525 [14:25<48:58, 11.22it/s]

 22%|████████▎                            | 9558/42525 [14:26<46:58, 11.70it/s]

 22%|████████▎                            | 9562/42525 [14:26<47:31, 11.56it/s]

 22%|████████▎                            | 9566/42525 [14:27<47:42, 11.51it/s]

 23%|████████▎                            | 9570/42525 [14:27<45:40, 12.02it/s]

 23%|████████▎                            | 9574/42525 [14:27<45:33, 12.05it/s]

 23%|████████▎                            | 9578/42525 [14:28<47:34, 11.54it/s]

 23%|████████▎                            | 9582/42525 [14:28<45:15, 12.13it/s]

 23%|████████▎                            | 9586/42525 [14:28<44:17, 12.39it/s]

 23%|████████▎                            | 9590/42525 [14:28<44:47, 12.26it/s]

 23%|████████▎                            | 9594/42525 [14:29<43:53, 12.50it/s]

 23%|████████▎                            | 9596/42525 [14:29<47:03, 11.66it/s]

 23%|████████▎                            | 9600/42525 [14:29<51:21, 10.68it/s]

 23%|████████▎                            | 9604/42525 [14:30<46:45, 11.73it/s]

 23%|████████▎                            | 9608/42525 [14:30<47:18, 11.60it/s]

 23%|████████▎                            | 9612/42525 [14:30<49:00, 11.19it/s]

 23%|████████▎                            | 9616/42525 [14:31<49:11, 11.15it/s]

 23%|████████▎                            | 9620/42525 [14:31<46:38, 11.76it/s]

 23%|████████▎                            | 9624/42525 [14:31<45:58, 11.93it/s]

 23%|████████▍                            | 9628/42525 [14:32<45:59, 11.92it/s]

 23%|████████▍                            | 9632/42525 [14:32<45:17, 12.11it/s]

 23%|████████▍                            | 9636/42525 [14:32<45:38, 12.01it/s]

 23%|████████▍                            | 9640/42525 [14:33<46:42, 11.73it/s]

 23%|████████▍                            | 9644/42525 [14:33<47:18, 11.58it/s]

 23%|████████▍                            | 9648/42525 [14:33<44:39, 12.27it/s]

 23%|████████▍                            | 9652/42525 [14:34<44:25, 12.33it/s]

 23%|████████▍                            | 9656/42525 [14:34<45:05, 12.15it/s]

 23%|████████▍                            | 9660/42525 [14:34<47:13, 11.60it/s]

 23%|████████▍                            | 9664/42525 [14:35<46:29, 11.78it/s]

 23%|████████▍                            | 9668/42525 [14:35<44:44, 12.24it/s]

 23%|████████▍                            | 9672/42525 [14:35<46:24, 11.80it/s]

 23%|████████▍                            | 9676/42525 [14:36<48:05, 11.38it/s]

 23%|████████▍                            | 9680/42525 [14:36<48:30, 11.29it/s]

 23%|████████▍                            | 9682/42525 [14:36<48:14, 11.35it/s]

 23%|████████▍                            | 9686/42525 [14:37<47:53, 11.43it/s]

 23%|████████▍                            | 9690/42525 [14:37<45:24, 12.05it/s]

 23%|████████▍                            | 9694/42525 [14:37<44:14, 12.37it/s]

 23%|████████▍                            | 9698/42525 [14:38<44:51, 12.20it/s]

 23%|████████▍                            | 9702/42525 [14:38<43:58, 12.44it/s]

 23%|████████▍                            | 9706/42525 [14:38<46:13, 11.83it/s]

 23%|████████▍                            | 9710/42525 [14:39<45:41, 11.97it/s]

 23%|████████▍                            | 9714/42525 [14:39<45:16, 12.08it/s]

 23%|████████▍                            | 9718/42525 [14:39<48:29, 11.28it/s]

 23%|████████▍                            | 9722/42525 [14:40<48:12, 11.34it/s]

 23%|████████▍                            | 9726/42525 [14:40<45:48, 11.94it/s]

 23%|████████▍                            | 9730/42525 [14:40<43:33, 12.55it/s]

 23%|████████▍                            | 9734/42525 [14:41<43:29, 12.57it/s]

 23%|████████▍                            | 9738/42525 [14:41<45:21, 12.05it/s]

 23%|████████▍                            | 9742/42525 [14:41<48:04, 11.36it/s]

 23%|████████▍                            | 9746/42525 [14:42<46:31, 11.74it/s]

 23%|████████▍                            | 9750/42525 [14:42<45:55, 11.89it/s]

 23%|████████▍                            | 9754/42525 [14:42<42:22, 12.89it/s]

 23%|████████▍                            | 9758/42525 [14:43<41:58, 13.01it/s]

 23%|████████▍                            | 9762/42525 [14:43<46:27, 11.76it/s]

 23%|████████▍                            | 9766/42525 [14:43<49:23, 11.06it/s]

 23%|████████▌                            | 9770/42525 [14:44<47:29, 11.49it/s]

 23%|████████▌                            | 9774/42525 [14:44<45:02, 12.12it/s]

 23%|████████▌                            | 9778/42525 [14:44<44:26, 12.28it/s]

 23%|████████▌                            | 9782/42525 [14:45<42:22, 12.88it/s]

 23%|████████▌                            | 9786/42525 [14:45<42:29, 12.84it/s]

 23%|████████▌                            | 9790/42525 [14:45<44:00, 12.40it/s]

 23%|████████▌                            | 9794/42525 [14:46<44:22, 12.29it/s]

 23%|████████▌                            | 9798/42525 [14:46<45:04, 12.10it/s]

 23%|████████▌                            | 9802/42525 [14:46<43:21, 12.58it/s]

 23%|████████▌                            | 9806/42525 [14:47<44:11, 12.34it/s]

 23%|████████▌                            | 9810/42525 [14:47<46:05, 11.83it/s]

 23%|████████▌                            | 9814/42525 [14:47<42:25, 12.85it/s]

 23%|████████▌                            | 9818/42525 [14:48<41:40, 13.08it/s]

 23%|████████▌                            | 9822/42525 [14:48<44:12, 12.33it/s]

 23%|████████▌                            | 9826/42525 [14:48<43:16, 12.59it/s]

 23%|████████▌                            | 9830/42525 [14:49<45:56, 11.86it/s]

 23%|████████▌                            | 9834/42525 [14:49<48:46, 11.17it/s]

 23%|████████▌                            | 9838/42525 [14:49<49:05, 11.10it/s]

 23%|████████▌                            | 9842/42525 [14:50<44:24, 12.27it/s]

 23%|████████▌                            | 9846/42525 [14:50<43:45, 12.45it/s]

 23%|████████▌                            | 9850/42525 [14:50<45:23, 12.00it/s]

 23%|████████▌                            | 9852/42525 [14:50<44:25, 12.26it/s]

 23%|████████▌                            | 9854/42525 [14:51<47:46, 11.40it/s]

 23%|████████▌                            | 9858/42525 [14:51<50:51, 10.71it/s]

 23%|████████▌                            | 9862/42525 [14:51<46:49, 11.63it/s]

 23%|████████▌                            | 9866/42525 [14:52<47:06, 11.55it/s]

 23%|████████▌                            | 9870/42525 [14:52<46:48, 11.63it/s]

 23%|████████▌                            | 9874/42525 [14:52<44:44, 12.16it/s]

 23%|████████▌                            | 9878/42525 [14:53<45:32, 11.95it/s]

 23%|████████▌                            | 9882/42525 [14:53<44:29, 12.23it/s]

 23%|████████▌                            | 9886/42525 [14:53<45:22, 11.99it/s]

 23%|████████▌                            | 9888/42525 [14:54<43:27, 12.52it/s]

 23%|████████▌                            | 9892/42525 [14:54<47:20, 11.49it/s]

 23%|████████▌                            | 9896/42525 [14:54<48:23, 11.24it/s]

 23%|████████▌                            | 9900/42525 [14:55<47:21, 11.48it/s]

 23%|████████▌                            | 9904/42525 [14:55<49:02, 11.09it/s]

 23%|████████▌                            | 9908/42525 [14:55<43:50, 12.40it/s]

 23%|████████▌                            | 9912/42525 [14:56<42:06, 12.91it/s]

 23%|████████▋                            | 9916/42525 [14:56<42:18, 12.84it/s]

 23%|████████▋                            | 9920/42525 [14:56<47:22, 11.47it/s]

 23%|████████▋                            | 9922/42525 [14:56<49:23, 11.00it/s]

 23%|████████▋                            | 9926/42525 [14:57<51:48, 10.49it/s]

 23%|████████▋                            | 9930/42525 [14:57<47:13, 11.51it/s]

 23%|████████▋                            | 9934/42525 [14:58<43:58, 12.35it/s]

 23%|████████▋                            | 9938/42525 [14:58<42:51, 12.67it/s]

 23%|████████▋                            | 9940/42525 [14:58<43:18, 12.54it/s]

 23%|████████▋                            | 9944/42525 [14:58<48:35, 11.17it/s]

 23%|████████▋                            | 9948/42525 [14:59<47:09, 11.51it/s]

 23%|████████▋                            | 9952/42525 [14:59<44:16, 12.26it/s]

 23%|████████▋                            | 9956/42525 [14:59<41:55, 12.95it/s]

 23%|████████▋                            | 9960/42525 [15:00<44:37, 12.16it/s]

 23%|████████▋                            | 9964/42525 [15:00<45:54, 11.82it/s]

 23%|████████▋                            | 9968/42525 [15:00<42:41, 12.71it/s]

 23%|████████▋                            | 9972/42525 [15:01<43:07, 12.58it/s]

 23%|████████▋                            | 9976/42525 [15:01<41:37, 13.04it/s]

 23%|████████▋                            | 9980/42525 [15:01<44:38, 12.15it/s]

 23%|████████▋                            | 9984/42525 [15:02<47:07, 11.51it/s]

 23%|████████▋                            | 9988/42525 [15:02<46:14, 11.73it/s]

 23%|████████▋                            | 9992/42525 [15:02<46:22, 11.69it/s]

 24%|████████▋                            | 9996/42525 [15:03<45:29, 11.92it/s]

 24%|████████▍                           | 10000/42525 [15:03<45:49, 11.83it/s]

 24%|████████▍                           | 10004/42525 [15:03<45:52, 11.81it/s]

 24%|████████▍                           | 10008/42525 [15:04<47:49, 11.33it/s]

 24%|████████▍                           | 10012/42525 [15:04<48:31, 11.17it/s]

 24%|████████▍                           | 10016/42525 [15:04<44:28, 12.18it/s]

 24%|████████▍                           | 10020/42525 [15:05<42:30, 12.74it/s]

 24%|████████▍                           | 10024/42525 [15:05<44:39, 12.13it/s]

 24%|████████▍                           | 10028/42525 [15:05<42:46, 12.66it/s]

 24%|████████▍                           | 10032/42525 [15:06<41:54, 12.92it/s]

 24%|████████▍                           | 10036/42525 [15:06<40:35, 13.34it/s]

 24%|████████▍                           | 10040/42525 [15:06<40:31, 13.36it/s]

 24%|████████▌                           | 10044/42525 [15:07<44:09, 12.26it/s]

 24%|████████▌                           | 10048/42525 [15:07<47:56, 11.29it/s]

 24%|████████▌                           | 10052/42525 [15:07<49:15, 10.99it/s]

 24%|████████▌                           | 10056/42525 [15:08<48:03, 11.26it/s]

 24%|████████▌                           | 10058/42525 [15:08<47:50, 11.31it/s]

 24%|████████▌                           | 10062/42525 [15:08<48:58, 11.05it/s]

 24%|████████▌                           | 10066/42525 [15:09<48:08, 11.24it/s]

 24%|████████▌                           | 10070/42525 [15:09<50:32, 10.70it/s]

 24%|████████▌                           | 10074/42525 [15:09<50:14, 10.76it/s]

 24%|████████▌                           | 10078/42525 [15:10<50:31, 10.70it/s]

 24%|████████▌                           | 10082/42525 [15:10<49:11, 10.99it/s]

 24%|████████▌                           | 10086/42525 [15:10<47:57, 11.27it/s]

 24%|████████▌                           | 10090/42525 [15:11<49:24, 10.94it/s]

 24%|████████▌                           | 10094/42525 [15:11<48:01, 11.26it/s]

 24%|████████▌                           | 10098/42525 [15:11<47:50, 11.30it/s]

 24%|████████▌                           | 10102/42525 [15:12<46:38, 11.59it/s]

 24%|████████▌                           | 10106/42525 [15:12<43:39, 12.38it/s]

 24%|████████▌                           | 10110/42525 [15:12<49:11, 10.98it/s]

 24%|████████▌                           | 10114/42525 [15:13<46:32, 11.61it/s]

 24%|████████▌                           | 10118/42525 [15:13<46:48, 11.54it/s]

 24%|████████▌                           | 10122/42525 [15:13<45:16, 11.93it/s]

 24%|████████▌                           | 10126/42525 [15:14<43:15, 12.48it/s]

 24%|████████▌                           | 10130/42525 [15:14<43:44, 12.34it/s]

 24%|████████▌                           | 10134/42525 [15:14<41:26, 13.03it/s]

 24%|████████▌                           | 10138/42525 [15:15<43:10, 12.50it/s]

 24%|████████▌                           | 10142/42525 [15:15<43:47, 12.32it/s]

 24%|████████▌                           | 10146/42525 [15:15<46:14, 11.67it/s]

 24%|████████▌                           | 10150/42525 [15:16<45:51, 11.77it/s]

 24%|████████▌                           | 10154/42525 [15:16<46:37, 11.57it/s]

 24%|████████▌                           | 10158/42525 [15:16<45:34, 11.84it/s]

 24%|████████▌                           | 10162/42525 [15:17<45:03, 11.97it/s]

 24%|████████▌                           | 10166/42525 [15:17<44:23, 12.15it/s]

 24%|████████▌                           | 10170/42525 [15:17<45:28, 11.86it/s]

 24%|████████▌                           | 10174/42525 [15:18<45:00, 11.98it/s]

 24%|████████▌                           | 10178/42525 [15:18<44:29, 12.12it/s]

 24%|████████▌                           | 10182/42525 [15:18<42:43, 12.62it/s]

 24%|████████▌                           | 10186/42525 [15:19<43:51, 12.29it/s]

 24%|████████▋                           | 10190/42525 [15:19<43:38, 12.35it/s]

 24%|████████▋                           | 10194/42525 [15:19<45:35, 11.82it/s]

 24%|████████▋                           | 10198/42525 [15:20<45:43, 11.78it/s]

 24%|████████▋                           | 10202/42525 [15:20<46:32, 11.58it/s]

 24%|████████▋                           | 10206/42525 [15:20<44:07, 12.21it/s]

 24%|████████▋                           | 10208/42525 [15:21<43:25, 12.41it/s]

 24%|████████▋                           | 10212/42525 [15:21<45:50, 11.75it/s]

 24%|████████▋                           | 10216/42525 [15:21<46:37, 11.55it/s]

 24%|████████▋                           | 10220/42525 [15:22<45:31, 11.83it/s]

 24%|████████▋                           | 10224/42525 [15:22<44:19, 12.15it/s]

 24%|████████▋                           | 10228/42525 [15:22<41:28, 12.98it/s]

 24%|████████▋                           | 10232/42525 [15:23<44:47, 12.02it/s]

 24%|████████▋                           | 10236/42525 [15:23<42:21, 12.70it/s]

 24%|████████▋                           | 10240/42525 [15:23<43:30, 12.37it/s]

 24%|████████▋                           | 10244/42525 [15:24<45:19, 11.87it/s]

 24%|████████▋                           | 10248/42525 [15:24<46:20, 11.61it/s]

 24%|████████▋                           | 10252/42525 [15:24<44:44, 12.02it/s]

 24%|████████▋                           | 10256/42525 [15:25<46:59, 11.44it/s]

 24%|████████▋                           | 10260/42525 [15:25<46:02, 11.68it/s]

 24%|████████▋                           | 10264/42525 [15:25<44:18, 12.14it/s]

 24%|████████▋                           | 10268/42525 [15:26<43:27, 12.37it/s]

 24%|████████▋                           | 10272/42525 [15:26<47:01, 11.43it/s]

 24%|████████▋                           | 10276/42525 [15:26<47:34, 11.30it/s]

 24%|████████▋                           | 10280/42525 [15:27<44:10, 12.17it/s]

 24%|████████▋                           | 10284/42525 [15:27<43:11, 12.44it/s]

 24%|████████▋                           | 10288/42525 [15:27<47:12, 11.38it/s]

 24%|████████▋                           | 10292/42525 [15:28<46:33, 11.54it/s]

 24%|████████▋                           | 10296/42525 [15:28<48:08, 11.16it/s]

 24%|████████▋                           | 10300/42525 [15:28<47:54, 11.21it/s]

 24%|████████▋                           | 10304/42525 [15:29<47:00, 11.42it/s]

 24%|████████▋                           | 10308/42525 [15:29<48:27, 11.08it/s]

 24%|████████▋                           | 10312/42525 [15:29<48:05, 11.16it/s]

 24%|████████▋                           | 10316/42525 [15:30<47:15, 11.36it/s]

 24%|████████▋                           | 10320/42525 [15:30<46:44, 11.48it/s]

 24%|████████▋                           | 10324/42525 [15:31<48:17, 11.11it/s]

 24%|████████▋                           | 10328/42525 [15:31<48:27, 11.07it/s]

 24%|████████▋                           | 10332/42525 [15:31<48:28, 11.07it/s]

 24%|████████▊                           | 10336/42525 [15:32<51:02, 10.51it/s]

 24%|████████▊                           | 10340/42525 [15:32<49:31, 10.83it/s]

 24%|████████▊                           | 10344/42525 [15:32<49:53, 10.75it/s]

 24%|████████▊                           | 10348/42525 [15:33<47:30, 11.29it/s]

 24%|████████▊                           | 10352/42525 [15:33<48:48, 10.99it/s]

 24%|████████▊                           | 10356/42525 [15:33<45:57, 11.66it/s]

 24%|████████▊                           | 10360/42525 [15:34<42:32, 12.60it/s]

 24%|████████▊                           | 10364/42525 [15:34<41:50, 12.81it/s]

 24%|████████▊                           | 10368/42525 [15:34<45:10, 11.87it/s]

 24%|████████▊                           | 10372/42525 [15:35<44:53, 11.94it/s]

 24%|████████▊                           | 10376/42525 [15:35<44:51, 11.94it/s]

 24%|████████▊                           | 10380/42525 [15:35<47:59, 11.16it/s]

 24%|████████▊                           | 10382/42525 [15:36<48:56, 10.94it/s]

 24%|████████▊                           | 10386/42525 [15:36<46:41, 11.47it/s]

 24%|████████▊                           | 10390/42525 [15:36<44:30, 12.03it/s]

 24%|████████▊                           | 10394/42525 [15:37<42:47, 12.52it/s]

 24%|████████▊                           | 10398/42525 [15:37<43:57, 12.18it/s]

 24%|████████▊                           | 10402/42525 [15:37<44:46, 11.96it/s]

 24%|████████▊                           | 10406/42525 [15:38<42:58, 12.46it/s]

 24%|████████▊                           | 10410/42525 [15:38<44:08, 12.13it/s]

 24%|████████▊                           | 10414/42525 [15:38<42:03, 12.72it/s]

 24%|████████▊                           | 10418/42525 [15:39<43:31, 12.29it/s]

 25%|████████▊                           | 10422/42525 [15:39<42:55, 12.46it/s]

 25%|████████▊                           | 10426/42525 [15:39<43:30, 12.30it/s]

 25%|████████▊                           | 10430/42525 [15:40<44:13, 12.10it/s]

 25%|████████▊                           | 10434/42525 [15:40<42:35, 12.56it/s]

 25%|████████▊                           | 10438/42525 [15:40<46:38, 11.47it/s]

 25%|████████▊                           | 10442/42525 [15:41<46:17, 11.55it/s]

 25%|████████▊                           | 10446/42525 [15:41<42:49, 12.48it/s]

 25%|████████▊                           | 10448/42525 [15:41<42:42, 12.52it/s]

 25%|████████▊                           | 10450/42525 [15:41<46:30, 11.50it/s]

 25%|████████▊                           | 10454/42525 [15:42<50:17, 10.63it/s]

 25%|████████▊                           | 10458/42525 [15:42<50:38, 10.55it/s]

 25%|████████▊                           | 10462/42525 [15:42<50:04, 10.67it/s]

 25%|████████▊                           | 10466/42525 [15:43<48:32, 11.01it/s]

 25%|████████▊                           | 10470/42525 [15:43<48:58, 10.91it/s]

 25%|████████▊                           | 10474/42525 [15:43<47:14, 11.31it/s]

 25%|████████▊                           | 10478/42525 [15:44<46:30, 11.48it/s]

 25%|████████▊                           | 10482/42525 [15:44<49:33, 10.78it/s]

 25%|████████▉                           | 10486/42525 [15:45<48:55, 10.92it/s]

 25%|████████▉                           | 10488/42525 [15:45<48:03, 11.11it/s]

 25%|████████▉                           | 10492/42525 [15:45<49:58, 10.68it/s]

 25%|████████▉                           | 10496/42525 [15:45<48:33, 10.99it/s]

 25%|████████▉                           | 10500/42525 [15:46<49:15, 10.84it/s]

 25%|████████▉                           | 10504/42525 [15:46<50:39, 10.54it/s]

 25%|████████▉                           | 10508/42525 [15:47<50:12, 10.63it/s]

 25%|████████▉                           | 10510/42525 [15:47<49:01, 10.88it/s]

 25%|████████▉                           | 10514/42525 [15:47<49:14, 10.84it/s]

 25%|████████▉                           | 10518/42525 [15:47<47:41, 11.19it/s]

 25%|████████▉                           | 10522/42525 [15:48<47:28, 11.23it/s]

 25%|████████▉                           | 10526/42525 [15:48<46:36, 11.44it/s]

 25%|████████▉                           | 10530/42525 [15:49<46:23, 11.50it/s]

 25%|████████▉                           | 10534/42525 [15:49<47:26, 11.24it/s]

 25%|████████▉                           | 10538/42525 [15:49<47:33, 11.21it/s]

 25%|████████▉                           | 10542/42525 [15:50<46:52, 11.37it/s]

 25%|████████▉                           | 10546/42525 [15:50<46:37, 11.43it/s]

 25%|████████▉                           | 10550/42525 [15:50<49:09, 10.84it/s]

 25%|████████▉                           | 10554/42525 [15:51<49:02, 10.87it/s]

 25%|████████▉                           | 10558/42525 [15:51<49:06, 10.85it/s]

 25%|████████▉                           | 10562/42525 [15:51<46:22, 11.49it/s]

 25%|████████▉                           | 10566/42525 [15:52<45:38, 11.67it/s]

 25%|████████▉                           | 10570/42525 [15:52<43:50, 12.15it/s]

 25%|████████▉                           | 10574/42525 [15:52<42:00, 12.68it/s]

 25%|████████▉                           | 10578/42525 [15:53<42:32, 12.51it/s]

 25%|████████▉                           | 10582/42525 [15:53<42:00, 12.68it/s]

 25%|████████▉                           | 10586/42525 [15:53<40:08, 13.26it/s]

 25%|████████▉                           | 10590/42525 [15:54<42:54, 12.41it/s]

 25%|████████▉                           | 10594/42525 [15:54<41:58, 12.68it/s]

 25%|████████▉                           | 10598/42525 [15:54<40:37, 13.10it/s]

 25%|████████▉                           | 10602/42525 [15:55<43:53, 12.12it/s]

 25%|████████▉                           | 10606/42525 [15:55<44:09, 12.05it/s]

 25%|████████▉                           | 10610/42525 [15:55<44:16, 12.01it/s]

 25%|████████▉                           | 10614/42525 [15:56<42:38, 12.47it/s]

 25%|████████▉                           | 10618/42525 [15:56<41:37, 12.78it/s]

 25%|████████▉                           | 10622/42525 [15:56<41:00, 12.97it/s]

 25%|████████▉                           | 10626/42525 [15:57<42:16, 12.57it/s]

 25%|████████▉                           | 10628/42525 [15:57<43:02, 12.35it/s]

 25%|████████▉                           | 10630/42525 [15:57<47:03, 11.30it/s]

 25%|█████████                           | 10634/42525 [15:57<50:01, 10.62it/s]

 25%|█████████                           | 10638/42525 [15:58<48:29, 10.96it/s]

 25%|█████████                           | 10642/42525 [15:58<46:55, 11.32it/s]

 25%|█████████                           | 10646/42525 [15:58<46:10, 11.51it/s]

 25%|█████████                           | 10650/42525 [15:59<46:28, 11.43it/s]

 25%|█████████                           | 10654/42525 [15:59<47:57, 11.08it/s]

 25%|█████████                           | 10658/42525 [15:59<50:05, 10.60it/s]

 25%|█████████                           | 10662/42525 [16:00<47:33, 11.17it/s]

 25%|█████████                           | 10666/42525 [16:00<46:46, 11.35it/s]

 25%|█████████                           | 10670/42525 [16:00<46:07, 11.51it/s]

 25%|█████████                           | 10674/42525 [16:01<48:06, 11.04it/s]

 25%|█████████                           | 10678/42525 [16:01<50:05, 10.60it/s]

 25%|█████████                           | 10680/42525 [16:01<47:58, 11.06it/s]

 25%|█████████                           | 10684/42525 [16:02<48:31, 10.93it/s]

 25%|█████████                           | 10688/42525 [16:02<45:55, 11.55it/s]

 25%|█████████                           | 10692/42525 [16:02<43:48, 12.11it/s]

 25%|█████████                           | 10696/42525 [16:03<44:27, 11.93it/s]

 25%|█████████                           | 10700/42525 [16:03<43:53, 12.09it/s]

 25%|█████████                           | 10704/42525 [16:03<45:07, 11.75it/s]

 25%|█████████                           | 10708/42525 [16:04<45:06, 11.75it/s]

 25%|█████████                           | 10712/42525 [16:04<45:49, 11.57it/s]

 25%|█████████                           | 10716/42525 [16:05<45:44, 11.59it/s]

 25%|█████████                           | 10720/42525 [16:05<46:56, 11.29it/s]

 25%|█████████                           | 10724/42525 [16:05<48:17, 10.98it/s]

 25%|█████████                           | 10728/42525 [16:06<47:26, 11.17it/s]

 25%|█████████                           | 10732/42525 [16:06<47:52, 11.07it/s]

 25%|█████████                           | 10736/42525 [16:06<47:20, 11.19it/s]

 25%|█████████                           | 10740/42525 [16:07<46:57, 11.28it/s]

 25%|█████████                           | 10744/42525 [16:07<47:56, 11.05it/s]

 25%|█████████                           | 10748/42525 [16:07<47:11, 11.22it/s]

 25%|█████████                           | 10752/42525 [16:08<46:11, 11.47it/s]

 25%|█████████                           | 10756/42525 [16:08<45:43, 11.58it/s]

 25%|█████████                           | 10760/42525 [16:08<48:22, 10.94it/s]

 25%|█████████                           | 10764/42525 [16:09<47:55, 11.04it/s]

 25%|█████████                           | 10768/42525 [16:09<49:20, 10.73it/s]

 25%|█████████                           | 10772/42525 [16:10<47:09, 11.22it/s]

 25%|█████████                           | 10776/42525 [16:10<47:55, 11.04it/s]

 25%|█████████▏                          | 10780/42525 [16:10<48:52, 10.83it/s]

 25%|█████████▏                          | 10784/42525 [16:11<48:16, 10.96it/s]

 25%|█████████▏                          | 10788/42525 [16:11<46:40, 11.33it/s]

 25%|█████████▏                          | 10792/42525 [16:11<48:17, 10.95it/s]

 25%|█████████▏                          | 10796/42525 [16:12<47:22, 11.16it/s]

 25%|█████████▏                          | 10800/42525 [16:12<47:18, 11.18it/s]

 25%|█████████▏                          | 10804/42525 [16:12<46:25, 11.39it/s]

 25%|█████████▏                          | 10808/42525 [16:13<46:48, 11.29it/s]

 25%|█████████▏                          | 10812/42525 [16:13<46:12, 11.44it/s]

 25%|█████████▏                          | 10816/42525 [16:14<47:23, 11.15it/s]

 25%|█████████▏                          | 10820/42525 [16:14<47:32, 11.12it/s]

 25%|█████████▏                          | 10824/42525 [16:14<46:34, 11.34it/s]

 25%|█████████▏                          | 10828/42525 [16:15<46:26, 11.37it/s]

 25%|█████████▏                          | 10832/42525 [16:15<47:55, 11.02it/s]

 25%|█████████▏                          | 10836/42525 [16:15<49:12, 10.73it/s]

 25%|█████████▏                          | 10840/42525 [16:16<47:17, 11.17it/s]

 26%|█████████▏                          | 10844/42525 [16:16<47:55, 11.02it/s]

 26%|█████████▏                          | 10848/42525 [16:16<47:33, 11.10it/s]

 26%|█████████▏                          | 10852/42525 [16:17<46:11, 11.43it/s]

 26%|█████████▏                          | 10856/42525 [16:17<46:13, 11.42it/s]

 26%|█████████▏                          | 10860/42525 [16:17<46:48, 11.27it/s]

 26%|█████████▏                          | 10864/42525 [16:18<47:23, 11.13it/s]

 26%|█████████▏                          | 10868/42525 [16:18<47:29, 11.11it/s]

 26%|█████████▏                          | 10872/42525 [16:19<48:04, 10.97it/s]

 26%|█████████▏                          | 10876/42525 [16:19<46:34, 11.32it/s]

 26%|█████████▏                          | 10880/42525 [16:19<45:43, 11.54it/s]

 26%|█████████▏                          | 10884/42525 [16:20<49:11, 10.72it/s]

 26%|█████████▏                          | 10888/42525 [16:20<46:57, 11.23it/s]

 26%|█████████▏                          | 10892/42525 [16:20<47:38, 11.06it/s]

 26%|█████████▏                          | 10896/42525 [16:21<47:09, 11.18it/s]

 26%|█████████▏                          | 10900/42525 [16:21<46:07, 11.43it/s]

 26%|█████████▏                          | 10902/42525 [16:21<44:49, 11.76it/s]

 26%|█████████▏                          | 10906/42525 [16:22<46:52, 11.24it/s]

 26%|█████████▏                          | 10910/42525 [16:22<42:44, 12.33it/s]

 26%|█████████▏                          | 10912/42525 [16:22<41:23, 12.73it/s]

 26%|█████████▏                          | 10916/42525 [16:22<46:20, 11.37it/s]

 26%|█████████▏                          | 10920/42525 [16:23<45:54, 11.48it/s]

 26%|█████████▏                          | 10924/42525 [16:23<46:42, 11.27it/s]

 26%|█████████▎                          | 10928/42525 [16:23<45:59, 11.45it/s]

 26%|█████████▎                          | 10932/42525 [16:24<47:50, 11.01it/s]

 26%|█████████▎                          | 10936/42525 [16:24<47:44, 11.03it/s]

 26%|█████████▎                          | 10940/42525 [16:24<44:05, 11.94it/s]

 26%|█████████▎                          | 10944/42525 [16:25<42:28, 12.39it/s]

 26%|█████████▎                          | 10948/42525 [16:25<44:40, 11.78it/s]

 26%|█████████▎                          | 10952/42525 [16:25<42:29, 12.38it/s]

 26%|█████████▎                          | 10956/42525 [16:26<45:49, 11.48it/s]

 26%|█████████▎                          | 10960/42525 [16:26<45:18, 11.61it/s]

 26%|█████████▎                          | 10964/42525 [16:26<43:02, 12.22it/s]

 26%|█████████▎                          | 10968/42525 [16:27<43:02, 12.22it/s]

 26%|█████████▎                          | 10972/42525 [16:27<45:01, 11.68it/s]

 26%|█████████▎                          | 10976/42525 [16:28<46:40, 11.26it/s]

 26%|█████████▎                          | 10980/42525 [16:28<47:54, 10.97it/s]

 26%|█████████▎                          | 10984/42525 [16:28<48:19, 10.88it/s]

 26%|█████████▎                          | 10988/42525 [16:29<47:41, 11.02it/s]

 26%|█████████▎                          | 10992/42525 [16:29<46:09, 11.39it/s]

 26%|█████████▎                          | 10996/42525 [16:29<45:18, 11.60it/s]

 26%|█████████▎                          | 11000/42525 [16:30<45:05, 11.65it/s]

 26%|█████████▎                          | 11004/42525 [16:30<45:26, 11.56it/s]

 26%|█████████▎                          | 11008/42525 [16:30<45:31, 11.54it/s]

 26%|█████████▎                          | 11012/42525 [16:31<46:31, 11.29it/s]

 26%|█████████▎                          | 11016/42525 [16:31<48:12, 10.89it/s]

 26%|█████████▎                          | 11020/42525 [16:31<49:20, 10.64it/s]

 26%|█████████▎                          | 11024/42525 [16:32<48:38, 10.79it/s]

 26%|█████████▎                          | 11028/42525 [16:32<47:04, 11.15it/s]

 26%|█████████▎                          | 11032/42525 [16:33<47:10, 11.12it/s]

 26%|█████████▎                          | 11036/42525 [16:33<46:31, 11.28it/s]

 26%|█████████▎                          | 11040/42525 [16:33<44:33, 11.78it/s]

 26%|█████████▎                          | 11044/42525 [16:34<46:36, 11.26it/s]

 26%|█████████▎                          | 11048/42525 [16:34<44:54, 11.68it/s]

 26%|█████████▎                          | 11052/42525 [16:34<42:51, 12.24it/s]

 26%|█████████▎                          | 11056/42525 [16:35<41:02, 12.78it/s]

 26%|█████████▎                          | 11058/42525 [16:35<41:57, 12.50it/s]

 26%|█████████▎                          | 11062/42525 [16:35<46:13, 11.34it/s]

 26%|█████████▎                          | 11066/42525 [16:35<45:42, 11.47it/s]

 26%|█████████▎                          | 11070/42525 [16:36<45:48, 11.44it/s]

 26%|█████████▎                          | 11074/42525 [16:36<42:22, 12.37it/s]

 26%|█████████▍                          | 11078/42525 [16:36<42:18, 12.39it/s]

 26%|█████████▍                          | 11082/42525 [16:37<40:13, 13.03it/s]

 26%|█████████▍                          | 11086/42525 [16:37<42:26, 12.35it/s]

 26%|█████████▍                          | 11090/42525 [16:37<43:41, 11.99it/s]

 26%|█████████▍                          | 11094/42525 [16:38<46:09, 11.35it/s]

 26%|█████████▍                          | 11098/42525 [16:38<41:38, 12.58it/s]

 26%|█████████▍                          | 11102/42525 [16:38<41:34, 12.60it/s]

 26%|█████████▍                          | 11106/42525 [16:39<42:23, 12.35it/s]

 26%|█████████▍                          | 11110/42525 [16:39<42:40, 12.27it/s]

 26%|█████████▍                          | 11112/42525 [16:39<41:38, 12.57it/s]

 26%|█████████▍                          | 11116/42525 [16:40<44:34, 11.75it/s]

 26%|█████████▍                          | 11120/42525 [16:40<41:50, 12.51it/s]

 26%|█████████▍                          | 11124/42525 [16:40<43:17, 12.09it/s]

 26%|█████████▍                          | 11128/42525 [16:41<44:39, 11.72it/s]

 26%|█████████▍                          | 11132/42525 [16:41<42:26, 12.33it/s]

 26%|█████████▍                          | 11136/42525 [16:41<41:47, 12.52it/s]

 26%|█████████▍                          | 11140/42525 [16:42<44:22, 11.79it/s]

 26%|█████████▍                          | 11144/42525 [16:42<42:50, 12.21it/s]

 26%|█████████▍                          | 11148/42525 [16:42<45:11, 11.57it/s]

 26%|█████████▍                          | 11152/42525 [16:43<42:37, 12.27it/s]

 26%|█████████▍                          | 11156/42525 [16:43<39:45, 13.15it/s]

 26%|█████████▍                          | 11160/42525 [16:43<43:00, 12.15it/s]

 26%|█████████▍                          | 11164/42525 [16:43<44:17, 11.80it/s]

 26%|█████████▍                          | 11168/42525 [16:44<42:10, 12.39it/s]

 26%|█████████▍                          | 11172/42525 [16:44<40:08, 13.02it/s]

 26%|█████████▍                          | 11176/42525 [16:44<43:26, 12.03it/s]

 26%|█████████▍                          | 11180/42525 [16:45<45:21, 11.52it/s]

 26%|█████████▍                          | 11184/42525 [16:45<44:35, 11.71it/s]

 26%|█████████▍                          | 11188/42525 [16:45<41:15, 12.66it/s]

 26%|█████████▍                          | 11192/42525 [16:46<40:38, 12.85it/s]

 26%|█████████▍                          | 11196/42525 [16:46<40:27, 12.90it/s]

 26%|█████████▍                          | 11200/42525 [16:46<39:21, 13.27it/s]

 26%|█████████▍                          | 11204/42525 [16:47<39:21, 13.26it/s]

 26%|█████████▍                          | 11208/42525 [16:47<43:47, 11.92it/s]

 26%|█████████▍                          | 11212/42525 [16:47<40:46, 12.80it/s]

 26%|█████████▍                          | 11216/42525 [16:48<39:21, 13.26it/s]

 26%|█████████▍                          | 11220/42525 [16:48<43:48, 11.91it/s]

 26%|█████████▌                          | 11224/42525 [16:48<42:04, 12.40it/s]

 26%|█████████▌                          | 11226/42525 [16:48<41:21, 12.61it/s]

 26%|█████████▌                          | 11230/42525 [16:49<45:16, 11.52it/s]

 26%|█████████▌                          | 11234/42525 [16:49<44:02, 11.84it/s]

 26%|█████████▌                          | 11238/42525 [16:49<42:24, 12.29it/s]

 26%|█████████▌                          | 11242/42525 [16:50<41:46, 12.48it/s]

 26%|█████████▌                          | 11246/42525 [16:50<40:54, 12.74it/s]

 26%|█████████▌                          | 11250/42525 [16:50<39:21, 13.24it/s]

 26%|█████████▌                          | 11254/42525 [16:51<41:10, 12.66it/s]

 26%|█████████▌                          | 11258/42525 [16:51<40:46, 12.78it/s]

 26%|█████████▌                          | 11262/42525 [16:51<40:50, 12.76it/s]

 26%|█████████▌                          | 11266/42525 [16:52<38:46, 13.44it/s]

 27%|█████████▌                          | 11270/42525 [16:52<38:50, 13.41it/s]

 27%|█████████▌                          | 11274/42525 [16:52<42:33, 12.24it/s]

 27%|█████████▌                          | 11278/42525 [16:53<40:33, 12.84it/s]

 27%|█████████▌                          | 11280/42525 [16:53<41:13, 12.63it/s]

 27%|█████████▌                          | 11284/42525 [16:53<43:05, 12.08it/s]

 27%|█████████▌                          | 11288/42525 [16:53<41:09, 12.65it/s]

 27%|█████████▌                          | 11292/42525 [16:54<39:21, 13.22it/s]

 27%|█████████▌                          | 11296/42525 [16:54<39:39, 13.12it/s]

 27%|█████████▌                          | 11300/42525 [16:54<38:11, 13.63it/s]

 27%|█████████▌                          | 11304/42525 [16:55<40:01, 13.00it/s]

 27%|█████████▌                          | 11308/42525 [16:55<44:51, 11.60it/s]

 27%|█████████▌                          | 11312/42525 [16:55<44:02, 11.81it/s]

 27%|█████████▌                          | 11316/42525 [16:56<41:33, 12.52it/s]

 27%|█████████▌                          | 11320/42525 [16:56<43:31, 11.95it/s]

 27%|█████████▌                          | 11324/42525 [16:56<42:20, 12.28it/s]

 27%|█████████▌                          | 11328/42525 [16:57<44:25, 11.70it/s]

 27%|█████████▌                          | 11332/42525 [16:57<45:44, 11.36it/s]

 27%|█████████▌                          | 11336/42525 [16:57<42:02, 12.36it/s]

 27%|█████████▌                          | 11340/42525 [16:58<40:34, 12.81it/s]

 27%|█████████▌                          | 11344/42525 [16:58<40:27, 12.84it/s]

 27%|█████████▌                          | 11348/42525 [16:58<41:27, 12.54it/s]

 27%|█████████▌                          | 11350/42525 [16:58<41:04, 12.65it/s]

 27%|█████████▌                          | 11354/42525 [16:59<42:14, 12.30it/s]

 27%|█████████▌                          | 11358/42525 [16:59<42:47, 12.14it/s]

 27%|█████████▌                          | 11362/42525 [16:59<41:20, 12.56it/s]

 27%|█████████▌                          | 11364/42525 [17:00<42:50, 12.12it/s]

 27%|█████████▌                          | 11368/42525 [17:00<43:12, 12.02it/s]

 27%|█████████▋                          | 11372/42525 [17:00<42:02, 12.35it/s]

 27%|█████████▋                          | 11376/42525 [17:00<40:36, 12.78it/s]

 27%|█████████▋                          | 11380/42525 [17:01<40:05, 12.95it/s]

 27%|█████████▋                          | 11384/42525 [17:01<42:04, 12.34it/s]

 27%|█████████▋                          | 11388/42525 [17:01<43:57, 11.80it/s]

 27%|█████████▋                          | 11392/42525 [17:02<43:34, 11.91it/s]

 27%|█████████▋                          | 11396/42525 [17:02<46:10, 11.24it/s]

 27%|█████████▋                          | 11400/42525 [17:03<46:45, 11.09it/s]

 27%|█████████▋                          | 11404/42525 [17:03<45:19, 11.44it/s]

 27%|█████████▋                          | 11408/42525 [17:03<46:42, 11.10it/s]

 27%|█████████▋                          | 11412/42525 [17:04<46:47, 11.08it/s]

 27%|█████████▋                          | 11416/42525 [17:04<44:30, 11.65it/s]

 27%|█████████▋                          | 11420/42525 [17:04<44:13, 11.72it/s]

 27%|█████████▋                          | 11424/42525 [17:05<41:48, 12.40it/s]

 27%|█████████▋                          | 11428/42525 [17:05<43:21, 11.95it/s]

 27%|█████████▋                          | 11432/42525 [17:05<42:00, 12.34it/s]

 27%|█████████▋                          | 11436/42525 [17:06<45:31, 11.38it/s]

 27%|█████████▋                          | 11440/42525 [17:06<43:17, 11.97it/s]

 27%|█████████▋                          | 11444/42525 [17:06<44:36, 11.61it/s]

 27%|█████████▋                          | 11448/42525 [17:07<43:49, 11.82it/s]

 27%|█████████▋                          | 11452/42525 [17:07<42:45, 12.11it/s]

 27%|█████████▋                          | 11456/42525 [17:07<40:19, 12.84it/s]

 27%|█████████▋                          | 11460/42525 [17:08<44:01, 11.76it/s]

 27%|█████████▋                          | 11464/42525 [17:08<45:29, 11.38it/s]

 27%|█████████▋                          | 11468/42525 [17:08<45:24, 11.40it/s]

 27%|█████████▋                          | 11472/42525 [17:09<45:27, 11.39it/s]

 27%|█████████▋                          | 11476/42525 [17:09<43:15, 11.96it/s]

 27%|█████████▋                          | 11480/42525 [17:09<42:48, 12.09it/s]

 27%|█████████▋                          | 11484/42525 [17:10<42:54, 12.06it/s]

 27%|█████████▋                          | 11488/42525 [17:10<42:15, 12.24it/s]

 27%|█████████▋                          | 11492/42525 [17:10<44:17, 11.68it/s]

 27%|█████████▋                          | 11496/42525 [17:11<46:56, 11.02it/s]

 27%|█████████▋                          | 11500/42525 [17:11<46:09, 11.20it/s]

 27%|█████████▋                          | 11504/42525 [17:11<46:41, 11.07it/s]

 27%|█████████▋                          | 11508/42525 [17:12<45:31, 11.35it/s]

 27%|█████████▋                          | 11512/42525 [17:12<43:44, 11.82it/s]

 27%|█████████▋                          | 11516/42525 [17:12<44:42, 11.56it/s]

 27%|█████████▊                          | 11520/42525 [17:13<43:15, 11.94it/s]

 27%|█████████▊                          | 11524/42525 [17:13<42:14, 12.23it/s]

 27%|█████████▊                          | 11528/42525 [17:13<41:04, 12.58it/s]

 27%|█████████▊                          | 11532/42525 [17:14<46:31, 11.10it/s]

 27%|█████████▊                          | 11536/42525 [17:14<45:27, 11.36it/s]

 27%|█████████▊                          | 11540/42525 [17:15<43:51, 11.78it/s]

 27%|█████████▊                          | 11544/42525 [17:15<45:47, 11.28it/s]

 27%|█████████▊                          | 11548/42525 [17:15<46:13, 11.17it/s]

 27%|█████████▊                          | 11552/42525 [17:16<42:25, 12.17it/s]

 27%|█████████▊                          | 11556/42525 [17:16<43:57, 11.74it/s]

 27%|█████████▊                          | 11560/42525 [17:16<41:56, 12.31it/s]

 27%|█████████▊                          | 11564/42525 [17:17<40:38, 12.70it/s]

 27%|█████████▊                          | 11568/42525 [17:17<41:58, 12.29it/s]

 27%|█████████▊                          | 11572/42525 [17:17<40:42, 12.67it/s]

 27%|█████████▊                          | 11576/42525 [17:17<40:55, 12.60it/s]

 27%|█████████▊                          | 11580/42525 [17:18<40:24, 12.77it/s]

 27%|█████████▊                          | 11584/42525 [17:18<42:28, 12.14it/s]

 27%|█████████▊                          | 11588/42525 [17:18<44:24, 11.61it/s]

 27%|█████████▊                          | 11592/42525 [17:19<46:03, 11.19it/s]

 27%|█████████▊                          | 11596/42525 [17:19<45:13, 11.40it/s]

 27%|█████████▊                          | 11600/42525 [17:20<46:36, 11.06it/s]

 27%|█████████▊                          | 11604/42525 [17:20<46:07, 11.17it/s]

 27%|█████████▊                          | 11608/42525 [17:20<47:01, 10.96it/s]

 27%|█████████▊                          | 11612/42525 [17:21<47:46, 10.79it/s]

 27%|█████████▊                          | 11616/42525 [17:21<46:02, 11.19it/s]

 27%|█████████▊                          | 11618/42525 [17:21<46:22, 11.11it/s]

 27%|█████████▊                          | 11622/42525 [17:22<49:14, 10.46it/s]

 27%|█████████▊                          | 11626/42525 [17:22<46:46, 11.01it/s]

 27%|█████████▊                          | 11630/42525 [17:22<47:01, 10.95it/s]

 27%|█████████▊                          | 11634/42525 [17:23<45:13, 11.39it/s]

 27%|█████████▊                          | 11638/42525 [17:23<45:19, 11.36it/s]

 27%|█████████▊                          | 11642/42525 [17:23<44:41, 11.52it/s]

 27%|█████████▊                          | 11646/42525 [17:24<45:44, 11.25it/s]

 27%|█████████▊                          | 11650/42525 [17:24<45:41, 11.26it/s]

 27%|█████████▊                          | 11654/42525 [17:24<44:26, 11.58it/s]

 27%|█████████▊                          | 11658/42525 [17:25<44:21, 11.60it/s]

 27%|█████████▊                          | 11662/42525 [17:25<47:13, 10.89it/s]

 27%|█████████▉                          | 11666/42525 [17:25<45:11, 11.38it/s]

 27%|█████████▉                          | 11670/42525 [17:26<44:23, 11.59it/s]

 27%|█████████▉                          | 11674/42525 [17:26<43:44, 11.75it/s]

 27%|█████████▉                          | 11678/42525 [17:26<43:22, 11.85it/s]

 27%|█████████▉                          | 11682/42525 [17:27<45:18, 11.35it/s]

 27%|█████████▉                          | 11686/42525 [17:27<45:55, 11.19it/s]

 27%|█████████▉                          | 11690/42525 [17:28<45:18, 11.34it/s]

 27%|█████████▉                          | 11694/42525 [17:28<44:10, 11.63it/s]

 28%|█████████▉                          | 11698/42525 [17:28<45:36, 11.27it/s]

 28%|█████████▉                          | 11702/42525 [17:29<45:36, 11.26it/s]

 28%|█████████▉                          | 11706/42525 [17:29<44:27, 11.55it/s]

 28%|█████████▉                          | 11710/42525 [17:29<44:49, 11.46it/s]

 28%|█████████▉                          | 11714/42525 [17:30<45:16, 11.34it/s]

 28%|█████████▉                          | 11718/42525 [17:30<44:53, 11.44it/s]

 28%|█████████▉                          | 11722/42525 [17:30<44:36, 11.51it/s]

 28%|█████████▉                          | 11726/42525 [17:31<46:20, 11.08it/s]

 28%|█████████▉                          | 11730/42525 [17:31<46:16, 11.09it/s]

 28%|█████████▉                          | 11734/42525 [17:31<46:25, 11.06it/s]

 28%|█████████▉                          | 11738/42525 [17:32<45:23, 11.30it/s]

 28%|█████████▉                          | 11742/42525 [17:32<45:41, 11.23it/s]

 28%|█████████▉                          | 11746/42525 [17:33<45:31, 11.27it/s]

 28%|█████████▉                          | 11748/42525 [17:33<44:53, 11.42it/s]

 28%|█████████▉                          | 11752/42525 [17:33<47:42, 10.75it/s]

 28%|█████████▉                          | 11756/42525 [17:33<47:34, 10.78it/s]

 28%|█████████▉                          | 11760/42525 [17:34<46:05, 11.13it/s]

 28%|█████████▉                          | 11764/42525 [17:34<45:28, 11.28it/s]

 28%|█████████▉                          | 11768/42525 [17:35<47:20, 10.83it/s]

 28%|█████████▉                          | 11772/42525 [17:35<45:22, 11.29it/s]

 28%|█████████▉                          | 11774/42525 [17:35<44:48, 11.44it/s]

 28%|█████████▉                          | 11778/42525 [17:35<46:29, 11.02it/s]

 28%|█████████▉                          | 11782/42525 [17:36<47:01, 10.90it/s]

 28%|█████████▉                          | 11786/42525 [17:36<47:40, 10.74it/s]

 28%|█████████▉                          | 11790/42525 [17:37<45:34, 11.24it/s]

 28%|█████████▉                          | 11794/42525 [17:37<45:47, 11.18it/s]

 28%|█████████▉                          | 11798/42525 [17:37<46:21, 11.05it/s]

 28%|█████████▉                          | 11802/42525 [17:38<45:57, 11.14it/s]

 28%|█████████▉                          | 11806/42525 [17:38<45:12, 11.33it/s]

 28%|█████████▉                          | 11810/42525 [17:38<44:13, 11.58it/s]

 28%|██████████                          | 11814/42525 [17:39<43:56, 11.65it/s]

 28%|██████████                          | 11818/42525 [17:39<44:16, 11.56it/s]

 28%|██████████                          | 11822/42525 [17:39<44:08, 11.59it/s]

 28%|██████████                          | 11826/42525 [17:40<45:34, 11.23it/s]

 28%|██████████                          | 11830/42525 [17:40<46:06, 11.10it/s]

 28%|██████████                          | 11834/42525 [17:40<47:58, 10.66it/s]

 28%|██████████                          | 11838/42525 [17:41<47:54, 10.68it/s]

 28%|██████████                          | 11842/42525 [17:41<45:11, 11.32it/s]

 28%|██████████                          | 11846/42525 [17:41<43:58, 11.63it/s]

 28%|██████████                          | 11850/42525 [17:42<46:57, 10.89it/s]

 28%|██████████                          | 11854/42525 [17:42<45:42, 11.18it/s]

 28%|██████████                          | 11858/42525 [17:43<45:34, 11.21it/s]

 28%|██████████                          | 11862/42525 [17:43<46:20, 11.03it/s]

 28%|██████████                          | 11866/42525 [17:43<45:24, 11.25it/s]

 28%|██████████                          | 11870/42525 [17:44<44:29, 11.48it/s]

 28%|██████████                          | 11874/42525 [17:44<43:43, 11.68it/s]

 28%|██████████                          | 11878/42525 [17:44<45:48, 11.15it/s]

 28%|██████████                          | 11882/42525 [17:45<45:47, 11.15it/s]

 28%|██████████                          | 11886/42525 [17:45<45:42, 11.17it/s]

 28%|██████████                          | 11890/42525 [17:45<45:40, 11.18it/s]

 28%|██████████                          | 11894/42525 [17:46<45:38, 11.18it/s]

 28%|██████████                          | 11898/42525 [17:46<44:26, 11.49it/s]

 28%|██████████                          | 11902/42525 [17:46<43:38, 11.69it/s]

 28%|██████████                          | 11906/42525 [17:47<43:07, 11.83it/s]

 28%|██████████                          | 11910/42525 [17:47<44:04, 11.57it/s]

 28%|██████████                          | 11914/42525 [17:48<45:37, 11.18it/s]

 28%|██████████                          | 11918/42525 [17:48<44:07, 11.56it/s]

 28%|██████████                          | 11922/42525 [17:48<44:06, 11.56it/s]

 28%|██████████                          | 11926/42525 [17:49<44:41, 11.41it/s]

 28%|██████████                          | 11930/42525 [17:49<44:11, 11.54it/s]

 28%|██████████                          | 11934/42525 [17:49<43:52, 11.62it/s]

 28%|██████████                          | 11938/42525 [17:50<45:30, 11.20it/s]

 28%|██████████                          | 11940/42525 [17:50<46:49, 10.89it/s]

 28%|██████████                          | 11944/42525 [17:50<47:11, 10.80it/s]

 28%|██████████                          | 11948/42525 [17:51<47:00, 10.84it/s]

 28%|██████████                          | 11952/42525 [17:51<45:32, 11.19it/s]

 28%|██████████                          | 11956/42525 [17:51<43:56, 11.60it/s]

 28%|██████████                          | 11960/42525 [17:52<44:21, 11.48it/s]

 28%|██████████▏                         | 11964/42525 [17:52<43:20, 11.75it/s]

 28%|██████████▏                         | 11968/42525 [17:52<43:17, 11.76it/s]

 28%|██████████▏                         | 11972/42525 [17:53<45:03, 11.30it/s]

 28%|██████████▏                         | 11976/42525 [17:53<44:50, 11.35it/s]

 28%|██████████▏                         | 11980/42525 [17:53<45:26, 11.20it/s]

 28%|██████████▏                         | 11984/42525 [17:54<47:17, 10.76it/s]

 28%|██████████▏                         | 11988/42525 [17:54<45:02, 11.30it/s]

 28%|██████████▏                         | 11992/42525 [17:54<43:58, 11.57it/s]

 28%|██████████▏                         | 11996/42525 [17:55<44:17, 11.49it/s]

 28%|██████████▏                         | 12000/42525 [17:55<45:31, 11.17it/s]

 28%|██████████▏                         | 12004/42525 [17:56<45:33, 11.17it/s]

 28%|██████████▏                         | 12008/42525 [17:56<46:05, 11.04it/s]

 28%|██████████▏                         | 12012/42525 [17:56<45:17, 11.23it/s]

 28%|██████████▏                         | 12016/42525 [17:57<43:59, 11.56it/s]

 28%|██████████▏                         | 12020/42525 [17:57<45:35, 11.15it/s]

 28%|██████████▏                         | 12024/42525 [17:57<45:29, 11.18it/s]

 28%|██████████▏                         | 12026/42525 [17:57<44:55, 11.32it/s]

 28%|██████████▏                         | 12030/42525 [17:58<47:54, 10.61it/s]

 28%|██████████▏                         | 12034/42525 [17:58<47:52, 10.61it/s]

 28%|██████████▏                         | 12038/42525 [17:59<47:19, 10.74it/s]

 28%|██████████▏                         | 12042/42525 [17:59<46:31, 10.92it/s]

 28%|██████████▏                         | 12046/42525 [17:59<46:42, 10.88it/s]

 28%|██████████▏                         | 12050/42525 [18:00<46:00, 11.04it/s]

 28%|██████████▏                         | 12054/42525 [18:00<44:28, 11.42it/s]

 28%|██████████▏                         | 12058/42525 [18:00<45:22, 11.19it/s]

 28%|██████████▏                         | 12060/42525 [18:01<44:42, 11.36it/s]

 28%|██████████▏                         | 12064/42525 [18:01<47:29, 10.69it/s]

 28%|██████████▏                         | 12068/42525 [18:01<46:39, 10.88it/s]

 28%|██████████▏                         | 12072/42525 [18:02<46:01, 11.03it/s]

 28%|██████████▏                         | 12076/42525 [18:02<47:54, 10.59it/s]

 28%|██████████▏                         | 12080/42525 [18:02<46:44, 10.85it/s]

 28%|██████████▏                         | 12084/42525 [18:03<46:54, 10.82it/s]

 28%|██████████▏                         | 12088/42525 [18:03<48:49, 10.39it/s]

 28%|██████████▏                         | 12092/42525 [18:04<47:23, 10.70it/s]

 28%|██████████▏                         | 12096/42525 [18:04<48:17, 10.50it/s]

 28%|██████████▏                         | 12100/42525 [18:04<48:00, 10.56it/s]

 28%|██████████▏                         | 12104/42525 [18:05<45:13, 11.21it/s]

 28%|██████████▎                         | 12108/42525 [18:05<44:59, 11.27it/s]

 28%|██████████▎                         | 12112/42525 [18:05<47:07, 10.76it/s]

 28%|██████████▎                         | 12116/42525 [18:06<45:27, 11.15it/s]

 29%|██████████▎                         | 12120/42525 [18:06<44:58, 11.27it/s]

 29%|██████████▎                         | 12124/42525 [18:06<45:37, 11.10it/s]

 29%|██████████▎                         | 12128/42525 [18:07<45:14, 11.20it/s]

 29%|██████████▎                         | 12132/42525 [18:07<47:56, 10.57it/s]

 29%|██████████▎                         | 12136/42525 [18:08<47:29, 10.66it/s]

 29%|██████████▎                         | 12140/42525 [18:08<46:48, 10.82it/s]

 29%|██████████▎                         | 12144/42525 [18:08<44:40, 11.34it/s]

 29%|██████████▎                         | 12148/42525 [18:09<43:38, 11.60it/s]

 29%|██████████▎                         | 12152/42525 [18:09<45:23, 11.15it/s]

 29%|██████████▎                         | 12156/42525 [18:09<43:55, 11.52it/s]

 29%|██████████▎                         | 12160/42525 [18:10<44:04, 11.48it/s]

 29%|██████████▎                         | 12164/42525 [18:10<45:04, 11.23it/s]

 29%|██████████▎                         | 12168/42525 [18:10<45:12, 11.19it/s]

 29%|██████████▎                         | 12172/42525 [18:11<43:50, 11.54it/s]

 29%|██████████▎                         | 12176/42525 [18:11<42:57, 11.77it/s]

 29%|██████████▎                         | 12180/42525 [18:11<44:33, 11.35it/s]

 29%|██████████▎                         | 12184/42525 [18:12<43:49, 11.54it/s]

 29%|██████████▎                         | 12188/42525 [18:12<46:44, 10.82it/s]

 29%|██████████▎                         | 12190/42525 [18:12<46:33, 10.86it/s]

 29%|██████████▎                         | 12194/42525 [18:13<44:24, 11.38it/s]

 29%|██████████▎                         | 12198/42525 [18:13<42:48, 11.81it/s]

 29%|██████████▎                         | 12202/42525 [18:13<42:17, 11.95it/s]

 29%|██████████▎                         | 12206/42525 [18:14<43:23, 11.64it/s]

 29%|██████████▎                         | 12210/42525 [18:14<45:25, 11.12it/s]

 29%|██████████▎                         | 12214/42525 [18:14<45:31, 11.10it/s]

 29%|██████████▎                         | 12218/42525 [18:15<40:57, 12.33it/s]

 29%|██████████▎                         | 12222/42525 [18:15<39:19, 12.84it/s]

 29%|██████████▎                         | 12226/42525 [18:15<40:59, 12.32it/s]

 29%|██████████▎                         | 12230/42525 [18:16<38:47, 13.02it/s]

 29%|██████████▎                         | 12234/42525 [18:16<40:26, 12.49it/s]

 29%|██████████▎                         | 12238/42525 [18:16<39:51, 12.66it/s]

 29%|██████████▎                         | 12242/42525 [18:17<40:19, 12.52it/s]

 29%|██████████▎                         | 12244/42525 [18:17<38:37, 13.07it/s]

 29%|██████████▎                         | 12248/42525 [18:17<42:44, 11.81it/s]

 29%|██████████▎                         | 12252/42525 [18:18<44:32, 11.33it/s]

 29%|██████████▍                         | 12256/42525 [18:18<42:17, 11.93it/s]

 29%|██████████▍                         | 12260/42525 [18:18<41:22, 12.19it/s]

 29%|██████████▍                         | 12264/42525 [18:19<42:51, 11.77it/s]

 29%|██████████▍                         | 12268/42525 [18:19<40:50, 12.34it/s]

 29%|██████████▍                         | 12272/42525 [18:19<41:28, 12.16it/s]

 29%|██████████▍                         | 12276/42525 [18:20<40:56, 12.31it/s]

 29%|██████████▍                         | 12280/42525 [18:20<40:25, 12.47it/s]

 29%|██████████▍                         | 12284/42525 [18:20<41:14, 12.22it/s]

 29%|██████████▍                         | 12288/42525 [18:20<39:21, 12.81it/s]

 29%|██████████▍                         | 12292/42525 [18:21<40:23, 12.48it/s]

 29%|██████████▍                         | 12296/42525 [18:21<41:00, 12.29it/s]

 29%|██████████▍                         | 12300/42525 [18:21<38:34, 13.06it/s]

 29%|██████████▍                         | 12304/42525 [18:22<38:06, 13.21it/s]

 29%|██████████▍                         | 12308/42525 [18:22<42:34, 11.83it/s]

 29%|██████████▍                         | 12312/42525 [18:22<41:30, 12.13it/s]

 29%|██████████▍                         | 12316/42525 [18:23<44:29, 11.32it/s]

 29%|██████████▍                         | 12320/42525 [18:23<45:42, 11.02it/s]

 29%|██████████▍                         | 12324/42525 [18:23<43:25, 11.59it/s]

 29%|██████████▍                         | 12328/42525 [18:24<42:46, 11.77it/s]

 29%|██████████▍                         | 12330/42525 [18:24<42:42, 11.78it/s]

 29%|██████████▍                         | 12334/42525 [18:24<46:29, 10.82it/s]

 29%|██████████▍                         | 12338/42525 [18:25<41:24, 12.15it/s]

 29%|██████████▍                         | 12342/42525 [18:25<42:36, 11.80it/s]

 29%|██████████▍                         | 12346/42525 [18:25<40:23, 12.45it/s]

 29%|██████████▍                         | 12350/42525 [18:26<41:46, 12.04it/s]

 29%|██████████▍                         | 12354/42525 [18:26<40:19, 12.47it/s]

 29%|██████████▍                         | 12358/42525 [18:26<37:58, 13.24it/s]

 29%|██████████▍                         | 12362/42525 [18:27<36:47, 13.66it/s]

 29%|██████████▍                         | 12366/42525 [18:27<40:32, 12.40it/s]

 29%|██████████▍                         | 12370/42525 [18:27<41:47, 12.03it/s]

 29%|██████████▍                         | 12374/42525 [18:28<43:12, 11.63it/s]

 29%|██████████▍                         | 12378/42525 [18:28<44:59, 11.17it/s]

 29%|██████████▍                         | 12382/42525 [18:28<44:50, 11.20it/s]

 29%|██████████▍                         | 12386/42525 [18:29<43:37, 11.51it/s]

 29%|██████████▍                         | 12390/42525 [18:29<43:43, 11.49it/s]

 29%|██████████▍                         | 12394/42525 [18:29<44:16, 11.34it/s]

 29%|██████████▍                         | 12398/42525 [18:30<44:48, 11.20it/s]

 29%|██████████▍                         | 12402/42525 [18:30<44:39, 11.24it/s]

 29%|██████████▌                         | 12406/42525 [18:30<44:40, 11.24it/s]

 29%|██████████▌                         | 12410/42525 [18:31<44:33, 11.27it/s]

 29%|██████████▌                         | 12414/42525 [18:31<43:41, 11.49it/s]

 29%|██████████▌                         | 12416/42525 [18:31<43:49, 11.45it/s]

 29%|██████████▌                         | 12420/42525 [18:32<46:49, 10.71it/s]

 29%|██████████▌                         | 12424/42525 [18:32<45:16, 11.08it/s]

 29%|██████████▌                         | 12428/42525 [18:32<43:45, 11.46it/s]

 29%|██████████▌                         | 12432/42525 [18:33<44:30, 11.27it/s]

 29%|██████████▌                         | 12436/42525 [18:33<45:50, 10.94it/s]

 29%|██████████▌                         | 12440/42525 [18:33<45:11, 11.09it/s]

 29%|██████████▌                         | 12444/42525 [18:34<45:32, 11.01it/s]

 29%|██████████▌                         | 12448/42525 [18:34<44:44, 11.21it/s]

 29%|██████████▌                         | 12452/42525 [18:35<44:56, 11.15it/s]

 29%|██████████▌                         | 12456/42525 [18:35<44:10, 11.34it/s]

 29%|██████████▌                         | 12460/42525 [18:35<46:12, 10.84it/s]

 29%|██████████▌                         | 12464/42525 [18:36<45:14, 11.07it/s]

 29%|██████████▌                         | 12468/42525 [18:36<43:52, 11.42it/s]

 29%|██████████▌                         | 12472/42525 [18:36<43:25, 11.54it/s]

 29%|██████████▌                         | 12476/42525 [18:37<46:43, 10.72it/s]

 29%|██████████▌                         | 12480/42525 [18:37<44:33, 11.24it/s]

 29%|██████████▌                         | 12484/42525 [18:37<45:19, 11.05it/s]

 29%|██████████▌                         | 12488/42525 [18:38<47:32, 10.53it/s]

 29%|██████████▌                         | 12492/42525 [18:38<45:12, 11.07it/s]

 29%|██████████▌                         | 12496/42525 [18:39<44:53, 11.15it/s]

 29%|██████████▌                         | 12500/42525 [18:39<45:17, 11.05it/s]

 29%|██████████▌                         | 12504/42525 [18:39<46:48, 10.69it/s]

 29%|██████████▌                         | 12508/42525 [18:40<46:25, 10.78it/s]

 29%|██████████▌                         | 12512/42525 [18:40<44:45, 11.17it/s]

 29%|██████████▌                         | 12516/42525 [18:40<44:34, 11.22it/s]

 29%|██████████▌                         | 12520/42525 [18:41<43:45, 11.43it/s]

 29%|██████████▌                         | 12524/42525 [18:41<43:01, 11.62it/s]

 29%|██████████▌                         | 12528/42525 [18:41<44:59, 11.11it/s]

 29%|██████████▌                         | 12532/42525 [18:42<46:02, 10.86it/s]

 29%|██████████▌                         | 12536/42525 [18:42<45:18, 11.03it/s]

 29%|██████████▌                         | 12540/42525 [18:43<43:55, 11.38it/s]

 29%|██████████▌                         | 12544/42525 [18:43<43:55, 11.37it/s]

 30%|██████████▌                         | 12548/42525 [18:43<45:37, 10.95it/s]

 30%|██████████▋                         | 12552/42525 [18:44<47:29, 10.52it/s]

 30%|██████████▋                         | 12556/42525 [18:44<44:55, 11.12it/s]

 30%|██████████▋                         | 12560/42525 [18:44<44:51, 11.13it/s]

 30%|██████████▋                         | 12564/42525 [18:45<43:32, 11.47it/s]

 30%|██████████▋                         | 12568/42525 [18:45<43:17, 11.53it/s]

 30%|██████████▋                         | 12572/42525 [18:45<43:38, 11.44it/s]

 30%|██████████▋                         | 12576/42525 [18:46<42:58, 11.61it/s]

 30%|██████████▋                         | 12580/42525 [18:46<42:44, 11.68it/s]

 30%|██████████▋                         | 12582/42525 [18:46<42:45, 11.67it/s]

 30%|██████████▋                         | 12586/42525 [18:47<44:19, 11.26it/s]

 30%|██████████▋                         | 12590/42525 [18:47<43:21, 11.51it/s]

 30%|██████████▋                         | 12594/42525 [18:47<43:02, 11.59it/s]

 30%|██████████▋                         | 12598/42525 [18:48<43:04, 11.58it/s]

 30%|██████████▋                         | 12602/42525 [18:48<42:54, 11.62it/s]

 30%|██████████▋                         | 12606/42525 [18:48<42:47, 11.65it/s]

 30%|██████████▋                         | 12610/42525 [18:49<45:21, 10.99it/s]

 30%|██████████▋                         | 12614/42525 [18:49<44:33, 11.19it/s]

 30%|██████████▋                         | 12618/42525 [18:49<43:40, 11.41it/s]

 30%|██████████▋                         | 12620/42525 [18:50<43:17, 11.51it/s]

 30%|██████████▋                         | 12624/42525 [18:50<44:22, 11.23it/s]

 30%|██████████▋                         | 12628/42525 [18:50<43:26, 11.47it/s]

 30%|██████████▋                         | 12632/42525 [18:51<44:45, 11.13it/s]

 30%|██████████▋                         | 12636/42525 [18:51<47:26, 10.50it/s]

 30%|██████████▋                         | 12640/42525 [18:51<44:49, 11.11it/s]

 30%|██████████▋                         | 12644/42525 [18:52<43:51, 11.36it/s]

 30%|██████████▋                         | 12648/42525 [18:52<43:05, 11.56it/s]

 30%|██████████▋                         | 12652/42525 [18:52<42:26, 11.73it/s]

 30%|██████████▋                         | 12656/42525 [18:53<42:25, 11.73it/s]

 30%|██████████▋                         | 12660/42525 [18:53<43:28, 11.45it/s]

 30%|██████████▋                         | 12664/42525 [18:54<46:29, 10.71it/s]

 30%|██████████▋                         | 12668/42525 [18:54<45:20, 10.97it/s]

 30%|██████████▋                         | 12672/42525 [18:54<45:25, 10.95it/s]

 30%|██████████▋                         | 12676/42525 [18:55<43:50, 11.35it/s]

 30%|██████████▋                         | 12680/42525 [18:55<44:45, 11.11it/s]

 30%|██████████▋                         | 12682/42525 [18:55<44:46, 11.11it/s]

 30%|██████████▋                         | 12686/42525 [18:55<46:13, 10.76it/s]

 30%|██████████▋                         | 12690/42525 [18:56<45:36, 10.90it/s]

 30%|██████████▋                         | 12694/42525 [18:56<44:56, 11.06it/s]

 30%|██████████▋                         | 12698/42525 [18:57<47:05, 10.56it/s]

 30%|██████████▊                         | 12702/42525 [18:57<45:21, 10.96it/s]

 30%|██████████▊                         | 12706/42525 [18:57<43:53, 11.32it/s]

 30%|██████████▊                         | 12710/42525 [18:58<43:05, 11.53it/s]

 30%|██████████▊                         | 12712/42525 [18:58<42:45, 11.62it/s]

 30%|██████████▊                         | 12716/42525 [18:58<44:39, 11.12it/s]

 30%|██████████▊                         | 12720/42525 [18:59<46:24, 10.70it/s]

 30%|██████████▊                         | 12724/42525 [18:59<44:02, 11.28it/s]

 30%|██████████▊                         | 12728/42525 [18:59<43:01, 11.54it/s]

 30%|██████████▊                         | 12732/42525 [19:00<42:34, 11.66it/s]

 30%|██████████▊                         | 12736/42525 [19:00<43:51, 11.32it/s]

 30%|██████████▊                         | 12738/42525 [19:00<45:05, 11.01it/s]

 30%|██████████▊                         | 12742/42525 [19:01<45:38, 10.88it/s]

 30%|██████████▊                         | 12744/42525 [19:01<44:48, 11.08it/s]

 30%|██████████▊                         | 12748/42525 [19:01<47:42, 10.40it/s]

 30%|██████████▊                         | 12752/42525 [19:01<45:52, 10.82it/s]

 30%|██████████▊                         | 12756/42525 [19:02<44:09, 11.24it/s]

 30%|██████████▊                         | 12760/42525 [19:02<45:48, 10.83it/s]

 30%|██████████▊                         | 12764/42525 [19:03<46:04, 10.76it/s]

 30%|██████████▊                         | 12768/42525 [19:03<47:00, 10.55it/s]

 30%|██████████▊                         | 12772/42525 [19:03<44:46, 11.08it/s]

 30%|██████████▊                         | 12776/42525 [19:04<43:14, 11.47it/s]

 30%|██████████▊                         | 12780/42525 [19:04<45:49, 10.82it/s]

 30%|██████████▊                         | 12784/42525 [19:04<45:42, 10.84it/s]

 30%|██████████▊                         | 12788/42525 [19:05<44:02, 11.25it/s]

 30%|██████████▊                         | 12792/42525 [19:05<44:05, 11.24it/s]

 30%|██████████▊                         | 12796/42525 [19:05<43:32, 11.38it/s]

 30%|██████████▊                         | 12800/42525 [19:06<42:20, 11.70it/s]

 30%|██████████▊                         | 12804/42525 [19:06<42:44, 11.59it/s]

 30%|██████████▊                         | 12808/42525 [19:06<43:08, 11.48it/s]

 30%|██████████▊                         | 12812/42525 [19:07<43:07, 11.48it/s]

 30%|██████████▊                         | 12816/42525 [19:07<42:44, 11.59it/s]

 30%|██████████▊                         | 12820/42525 [19:08<42:40, 11.60it/s]

 30%|██████████▊                         | 12824/42525 [19:08<44:59, 11.00it/s]

 30%|██████████▊                         | 12828/42525 [19:08<43:45, 11.31it/s]

 30%|██████████▊                         | 12832/42525 [19:09<43:35, 11.35it/s]

 30%|██████████▊                         | 12836/42525 [19:09<44:38, 11.08it/s]

 30%|██████████▊                         | 12840/42525 [19:09<43:04, 11.49it/s]

 30%|██████████▊                         | 12844/42525 [19:10<44:01, 11.24it/s]

 30%|██████████▉                         | 12848/42525 [19:10<44:47, 11.04it/s]

 30%|██████████▉                         | 12852/42525 [19:10<43:15, 11.43it/s]

 30%|██████████▉                         | 12856/42525 [19:11<42:43, 11.58it/s]

 30%|██████████▉                         | 12860/42525 [19:11<43:02, 11.49it/s]

 30%|██████████▉                         | 12864/42525 [19:11<42:30, 11.63it/s]

 30%|██████████▉                         | 12868/42525 [19:12<42:16, 11.69it/s]

 30%|██████████▉                         | 12872/42525 [19:12<42:12, 11.71it/s]

 30%|██████████▉                         | 12876/42525 [19:12<43:18, 11.41it/s]

 30%|██████████▉                         | 12880/42525 [19:13<44:46, 11.03it/s]

 30%|██████████▉                         | 12884/42525 [19:13<45:54, 10.76it/s]

 30%|██████████▉                         | 12888/42525 [19:14<44:48, 11.02it/s]

 30%|██████████▉                         | 12892/42525 [19:14<47:25, 10.41it/s]

 30%|██████████▉                         | 12896/42525 [19:14<44:41, 11.05it/s]

 30%|██████████▉                         | 12900/42525 [19:15<43:38, 11.31it/s]

 30%|██████████▉                         | 12904/42525 [19:15<45:30, 10.85it/s]

 30%|██████████▉                         | 12908/42525 [19:15<45:30, 10.85it/s]

 30%|██████████▉                         | 12912/42525 [19:16<43:59, 11.22it/s]

 30%|██████████▉                         | 12916/42525 [19:16<44:16, 11.15it/s]

 30%|██████████▉                         | 12920/42525 [19:16<43:07, 11.44it/s]

 30%|██████████▉                         | 12924/42525 [19:17<42:45, 11.54it/s]

 30%|██████████▉                         | 12928/42525 [19:17<44:30, 11.08it/s]

 30%|██████████▉                         | 12932/42525 [19:18<44:53, 10.99it/s]

 30%|██████████▉                         | 12936/42525 [19:18<44:27, 11.09it/s]

 30%|██████████▉                         | 12940/42525 [19:18<44:14, 11.14it/s]

 30%|██████████▉                         | 12944/42525 [19:19<45:36, 10.81it/s]

 30%|██████████▉                         | 12948/42525 [19:19<43:44, 11.27it/s]

 30%|██████████▉                         | 12952/42525 [19:19<44:00, 11.20it/s]

 30%|██████████▉                         | 12956/42525 [19:20<44:57, 10.96it/s]

 30%|██████████▉                         | 12960/42525 [19:20<43:37, 11.29it/s]

 30%|██████████▉                         | 12964/42525 [19:20<45:41, 10.78it/s]

 30%|██████████▉                         | 12968/42525 [19:21<44:18, 11.12it/s]

 31%|██████████▉                         | 12972/42525 [19:21<43:55, 11.21it/s]

 31%|██████████▉                         | 12976/42525 [19:21<43:03, 11.44it/s]

 31%|██████████▉                         | 12980/42525 [19:22<42:24, 11.61it/s]

 31%|██████████▉                         | 12984/42525 [19:22<42:04, 11.70it/s]

 31%|██████████▉                         | 12988/42525 [19:23<44:03, 11.17it/s]

 31%|██████████▉                         | 12992/42525 [19:23<45:20, 10.85it/s]

 31%|███████████                         | 12996/42525 [19:23<45:34, 10.80it/s]

 31%|███████████                         | 13000/42525 [19:24<46:33, 10.57it/s]

 31%|███████████                         | 13004/42525 [19:24<44:51, 10.97it/s]

 31%|███████████                         | 13006/42525 [19:24<44:05, 11.16it/s]

 31%|███████████                         | 13010/42525 [19:25<45:12, 10.88it/s]

 31%|███████████                         | 13014/42525 [19:25<44:33, 11.04it/s]

 31%|███████████                         | 13018/42525 [19:25<44:17, 11.10it/s]

 31%|███████████                         | 13022/42525 [19:26<43:45, 11.24it/s]

 31%|███████████                         | 13026/42525 [19:26<42:35, 11.54it/s]

 31%|███████████                         | 13030/42525 [19:26<43:55, 11.19it/s]

 31%|███████████                         | 13034/42525 [19:27<45:37, 10.77it/s]

 31%|███████████                         | 13038/42525 [19:27<45:04, 10.90it/s]

 31%|███████████                         | 13042/42525 [19:27<45:07, 10.89it/s]

 31%|███████████                         | 13046/42525 [19:28<46:21, 10.60it/s]

 31%|███████████                         | 13050/42525 [19:28<45:16, 10.85it/s]

 31%|███████████                         | 13054/42525 [19:29<44:31, 11.03it/s]

 31%|███████████                         | 13056/42525 [19:29<43:33, 11.28it/s]

 31%|███████████                         | 13060/42525 [19:29<46:04, 10.66it/s]

 31%|███████████                         | 13064/42525 [19:29<44:38, 11.00it/s]

 31%|███████████                         | 13068/42525 [19:30<45:57, 10.68it/s]

 31%|███████████                         | 13072/42525 [19:30<43:47, 11.21it/s]

 31%|███████████                         | 13076/42525 [19:31<44:35, 11.01it/s]

 31%|███████████                         | 13080/42525 [19:31<44:44, 10.97it/s]

 31%|███████████                         | 13084/42525 [19:31<43:23, 11.31it/s]

 31%|███████████                         | 13088/42525 [19:32<45:17, 10.83it/s]

 31%|███████████                         | 13092/42525 [19:32<43:41, 11.23it/s]

 31%|███████████                         | 13096/42525 [19:32<44:51, 10.94it/s]

 31%|███████████                         | 13100/42525 [19:33<44:25, 11.04it/s]

 31%|███████████                         | 13104/42525 [19:33<44:13, 11.09it/s]

 31%|███████████                         | 13108/42525 [19:34<45:43, 10.72it/s]

 31%|███████████                         | 13112/42525 [19:34<43:54, 11.17it/s]

 31%|███████████                         | 13116/42525 [19:34<42:37, 11.50it/s]

 31%|███████████                         | 13120/42525 [19:35<45:08, 10.86it/s]

 31%|███████████                         | 13124/42525 [19:35<43:34, 11.24it/s]

 31%|███████████                         | 13128/42525 [19:35<42:22, 11.56it/s]

 31%|███████████                         | 13132/42525 [19:36<42:58, 11.40it/s]

 31%|███████████                         | 13134/42525 [19:36<42:39, 11.48it/s]

 31%|███████████                         | 13138/42525 [19:36<44:13, 11.07it/s]

 31%|███████████▏                        | 13142/42525 [19:37<45:53, 10.67it/s]

 31%|███████████▏                        | 13144/42525 [19:37<44:44, 10.95it/s]

 31%|███████████▏                        | 13148/42525 [19:37<45:05, 10.86it/s]

 31%|███████████▏                        | 13152/42525 [19:37<44:35, 10.98it/s]

 31%|███████████▏                        | 13156/42525 [19:38<44:57, 10.89it/s]

 31%|███████████▏                        | 13160/42525 [19:38<43:17, 11.31it/s]

 31%|███████████▏                        | 13162/42525 [19:38<42:57, 11.39it/s]

 31%|███████████▏                        | 13166/42525 [19:39<43:48, 11.17it/s]

 31%|███████████▏                        | 13170/42525 [19:39<44:17, 11.04it/s]

 31%|███████████▏                        | 13174/42525 [19:39<42:48, 11.43it/s]

 31%|███████████▏                        | 13178/42525 [19:40<42:06, 11.62it/s]

 31%|███████████▏                        | 13182/42525 [19:40<41:50, 11.69it/s]

 31%|███████████▏                        | 13186/42525 [19:40<41:31, 11.78it/s]

 31%|███████████▏                        | 13190/42525 [19:41<41:40, 11.73it/s]

 31%|███████████▏                        | 13194/42525 [19:41<42:24, 11.53it/s]

 31%|███████████▏                        | 13198/42525 [19:41<43:35, 11.21it/s]

 31%|███████████▏                        | 13202/42525 [19:42<44:12, 11.05it/s]

 31%|███████████▏                        | 13206/42525 [19:42<44:41, 10.93it/s]

 31%|███████████▏                        | 13210/42525 [19:43<43:53, 11.13it/s]

 31%|███████████▏                        | 13214/42525 [19:43<43:39, 11.19it/s]

 31%|███████████▏                        | 13218/42525 [19:43<43:18, 11.28it/s]

 31%|███████████▏                        | 13222/42525 [19:44<42:29, 11.49it/s]

 31%|███████████▏                        | 13226/42525 [19:44<44:44, 10.91it/s]

 31%|███████████▏                        | 13230/42525 [19:44<45:40, 10.69it/s]

 31%|███████████▏                        | 13234/42525 [19:45<44:53, 10.87it/s]

 31%|███████████▏                        | 13238/42525 [19:45<43:21, 11.26it/s]

 31%|███████████▏                        | 13242/42525 [19:45<42:31, 11.48it/s]

 31%|███████████▏                        | 13246/42525 [19:46<43:05, 11.32it/s]

 31%|███████████▏                        | 13250/42525 [19:46<44:50, 10.88it/s]

 31%|███████████▏                        | 13254/42525 [19:47<44:57, 10.85it/s]

 31%|███████████▏                        | 13258/42525 [19:47<45:03, 10.82it/s]

 31%|███████████▏                        | 13262/42525 [19:47<43:20, 11.25it/s]

 31%|███████████▏                        | 13266/42525 [19:48<42:22, 11.51it/s]

 31%|███████████▏                        | 13270/42525 [19:48<43:09, 11.30it/s]

 31%|███████████▏                        | 13274/42525 [19:48<43:37, 11.18it/s]

 31%|███████████▏                        | 13278/42525 [19:49<42:32, 11.46it/s]

 31%|███████████▏                        | 13282/42525 [19:49<42:04, 11.59it/s]

 31%|███████████▏                        | 13286/42525 [19:49<43:56, 11.09it/s]

 31%|███████████▎                        | 13290/42525 [19:50<43:57, 11.08it/s]

 31%|███████████▎                        | 13294/42525 [19:50<43:19, 11.25it/s]

 31%|███████████▎                        | 13298/42525 [19:50<44:13, 11.01it/s]

 31%|███████████▎                        | 13302/42525 [19:51<43:05, 11.30it/s]

 31%|███████████▎                        | 13306/42525 [19:51<42:30, 11.46it/s]

 31%|███████████▎                        | 13310/42525 [19:52<43:36, 11.17it/s]

 31%|███████████▎                        | 13314/42525 [19:52<42:54, 11.34it/s]

 31%|███████████▎                        | 13318/42525 [19:52<45:29, 10.70it/s]

 31%|███████████▎                        | 13322/42525 [19:53<45:39, 10.66it/s]

 31%|███████████▎                        | 13326/42525 [19:53<44:14, 11.00it/s]

 31%|███████████▎                        | 13330/42525 [19:53<44:14, 11.00it/s]

 31%|███████████▎                        | 13334/42525 [19:54<43:00, 11.31it/s]

 31%|███████████▎                        | 13338/42525 [19:54<43:19, 11.23it/s]

 31%|███████████▎                        | 13342/42525 [19:54<43:13, 11.25it/s]

 31%|███████████▎                        | 13346/42525 [19:55<42:20, 11.49it/s]

 31%|███████████▎                        | 13350/42525 [19:55<41:52, 11.61it/s]

 31%|███████████▎                        | 13354/42525 [19:55<42:51, 11.34it/s]

 31%|███████████▎                        | 13358/42525 [19:56<45:09, 10.77it/s]

 31%|███████████▎                        | 13362/42525 [19:56<45:00, 10.80it/s]

 31%|███████████▎                        | 13366/42525 [19:57<44:33, 10.91it/s]

 31%|███████████▎                        | 13370/42525 [19:57<46:11, 10.52it/s]

 31%|███████████▎                        | 13374/42525 [19:57<44:14, 10.98it/s]

 31%|███████████▎                        | 13378/42525 [19:58<42:53, 11.33it/s]

 31%|███████████▎                        | 13382/42525 [19:58<43:13, 11.23it/s]

 31%|███████████▎                        | 13386/42525 [19:58<44:01, 11.03it/s]

 31%|███████████▎                        | 13390/42525 [19:59<45:26, 10.69it/s]

 31%|███████████▎                        | 13394/42525 [19:59<44:08, 11.00it/s]

 32%|███████████▎                        | 13398/42525 [19:59<43:52, 11.07it/s]

 32%|███████████▎                        | 13400/42525 [20:00<43:14, 11.23it/s]

 32%|███████████▎                        | 13404/42525 [20:00<44:33, 10.89it/s]

 32%|███████████▎                        | 13406/42525 [20:00<43:43, 11.10it/s]

 32%|███████████▎                        | 13410/42525 [20:01<45:58, 10.55it/s]

 32%|███████████▎                        | 13414/42525 [20:01<43:23, 11.18it/s]

 32%|███████████▎                        | 13418/42525 [20:01<43:40, 11.11it/s]

 32%|███████████▎                        | 13422/42525 [20:02<43:03, 11.26it/s]

 32%|███████████▎                        | 13426/42525 [20:02<44:54, 10.80it/s]

 32%|███████████▎                        | 13430/42525 [20:02<43:24, 11.17it/s]

 32%|███████████▎                        | 13434/42525 [20:03<42:17, 11.47it/s]

 32%|███████████▍                        | 13438/42525 [20:03<42:53, 11.30it/s]

 32%|███████████▍                        | 13442/42525 [20:03<43:12, 11.22it/s]

 32%|███████████▍                        | 13446/42525 [20:04<42:10, 11.49it/s]

 32%|███████████▍                        | 13448/42525 [20:04<42:49, 11.31it/s]

 32%|███████████▍                        | 13452/42525 [20:04<44:11, 10.96it/s]

 32%|███████████▍                        | 13456/42525 [20:05<44:10, 10.97it/s]

 32%|███████████▍                        | 13460/42525 [20:05<45:29, 10.65it/s]

 32%|███████████▍                        | 13464/42525 [20:05<43:12, 11.21it/s]

 32%|███████████▍                        | 13468/42525 [20:06<42:02, 11.52it/s]

 32%|███████████▍                        | 13472/42525 [20:06<42:32, 11.38it/s]

 32%|███████████▍                        | 13476/42525 [20:07<42:35, 11.37it/s]

 32%|███████████▍                        | 13480/42525 [20:07<41:39, 11.62it/s]

 32%|███████████▍                        | 13484/42525 [20:07<41:43, 11.60it/s]

 32%|███████████▍                        | 13488/42525 [20:08<41:31, 11.65it/s]

 32%|███████████▍                        | 13492/42525 [20:08<41:10, 11.75it/s]

 32%|███████████▍                        | 13496/42525 [20:08<41:16, 11.72it/s]

 32%|███████████▍                        | 13500/42525 [20:09<42:49, 11.30it/s]

 32%|███████████▍                        | 13504/42525 [20:09<42:55, 11.27it/s]

 32%|███████████▍                        | 13508/42525 [20:09<44:18, 10.91it/s]

 32%|███████████▍                        | 13510/42525 [20:09<44:12, 10.94it/s]

 32%|███████████▍                        | 13514/42525 [20:10<44:18, 10.91it/s]

 32%|███████████▍                        | 13518/42525 [20:10<43:43, 11.06it/s]

 32%|███████████▍                        | 13522/42525 [20:11<43:38, 11.08it/s]

 32%|███████████▍                        | 13526/42525 [20:11<43:19, 11.16it/s]

 32%|███████████▍                        | 13530/42525 [20:11<42:18, 11.42it/s]

 32%|███████████▍                        | 13534/42525 [20:12<43:42, 11.06it/s]

 32%|███████████▍                        | 13538/42525 [20:12<44:14, 10.92it/s]

 32%|███████████▍                        | 13542/42525 [20:12<44:04, 10.96it/s]

 32%|███████████▍                        | 13546/42525 [20:13<44:41, 10.81it/s]

 32%|███████████▍                        | 13550/42525 [20:13<43:53, 11.00it/s]

 32%|███████████▍                        | 13554/42525 [20:13<42:31, 11.35it/s]

 32%|███████████▍                        | 13558/42525 [20:14<42:57, 11.24it/s]

 32%|███████████▍                        | 13562/42525 [20:14<44:46, 10.78it/s]

 32%|███████████▍                        | 13566/42525 [20:15<43:29, 11.10it/s]

 32%|███████████▍                        | 13570/42525 [20:15<43:53, 10.99it/s]

 32%|███████████▍                        | 13574/42525 [20:15<42:10, 11.44it/s]

 32%|███████████▍                        | 13578/42525 [20:16<41:35, 11.60it/s]

 32%|███████████▍                        | 13582/42525 [20:16<44:07, 10.93it/s]

 32%|███████████▌                        | 13586/42525 [20:16<42:35, 11.33it/s]

 32%|███████████▌                        | 13590/42525 [20:17<41:49, 11.53it/s]

 32%|███████████▌                        | 13594/42525 [20:17<42:09, 11.44it/s]

 32%|███████████▌                        | 13598/42525 [20:17<41:31, 11.61it/s]

 32%|███████████▌                        | 13602/42525 [20:18<41:12, 11.70it/s]

 32%|███████████▌                        | 13606/42525 [20:18<42:44, 11.28it/s]

 32%|███████████▌                        | 13610/42525 [20:18<42:21, 11.38it/s]

 32%|███████████▌                        | 13614/42525 [20:19<43:41, 11.03it/s]

 32%|███████████▌                        | 13618/42525 [20:19<43:24, 11.10it/s]

 32%|███████████▌                        | 13622/42525 [20:20<43:29, 11.08it/s]

 32%|███████████▌                        | 13626/42525 [20:20<43:25, 11.09it/s]

 32%|███████████▌                        | 13630/42525 [20:20<41:57, 11.48it/s]

 32%|███████████▌                        | 13634/42525 [20:21<43:04, 11.18it/s]

 32%|███████████▌                        | 13638/42525 [20:21<42:39, 11.29it/s]

 32%|███████████▌                        | 13642/42525 [20:21<41:40, 11.55it/s]

 32%|███████████▌                        | 13646/42525 [20:22<41:27, 11.61it/s]

 32%|███████████▌                        | 13650/42525 [20:22<42:14, 11.39it/s]

 32%|███████████▌                        | 13654/42525 [20:22<42:40, 11.28it/s]

 32%|███████████▌                        | 13658/42525 [20:23<42:26, 11.33it/s]

 32%|███████████▌                        | 13662/42525 [20:23<44:41, 10.76it/s]

 32%|███████████▌                        | 13666/42525 [20:23<44:59, 10.69it/s]

 32%|███████████▌                        | 13670/42525 [20:24<43:58, 10.94it/s]

 32%|███████████▌                        | 13674/42525 [20:24<42:28, 11.32it/s]

 32%|███████████▌                        | 13678/42525 [20:25<43:06, 11.15it/s]

 32%|███████████▌                        | 13682/42525 [20:25<44:30, 10.80it/s]

 32%|███████████▌                        | 13686/42525 [20:25<43:31, 11.04it/s]

 32%|███████████▌                        | 13690/42525 [20:26<42:58, 11.18it/s]

 32%|███████████▌                        | 13694/42525 [20:26<42:05, 11.41it/s]

 32%|███████████▌                        | 13698/42525 [20:26<42:26, 11.32it/s]

 32%|███████████▌                        | 13702/42525 [20:27<42:06, 11.41it/s]

 32%|███████████▌                        | 13706/42525 [20:27<42:12, 11.38it/s]

 32%|███████████▌                        | 13710/42525 [20:27<43:26, 11.06it/s]

 32%|███████████▌                        | 13714/42525 [20:28<43:09, 11.12it/s]

 32%|███████████▌                        | 13718/42525 [20:28<43:04, 11.15it/s]

 32%|███████████▌                        | 13722/42525 [20:28<42:48, 11.22it/s]

 32%|███████████▌                        | 13726/42525 [20:29<43:18, 11.08it/s]

 32%|███████████▌                        | 13730/42525 [20:29<41:49, 11.47it/s]

 32%|███████████▋                        | 13734/42525 [20:30<41:26, 11.58it/s]

 32%|███████████▋                        | 13738/42525 [20:30<41:15, 11.63it/s]

 32%|███████████▋                        | 13742/42525 [20:30<41:15, 11.63it/s]

 32%|███████████▋                        | 13746/42525 [20:31<41:41, 11.51it/s]

 32%|███████████▋                        | 13750/42525 [20:31<41:07, 11.66it/s]

 32%|███████████▋                        | 13754/42525 [20:31<42:03, 11.40it/s]

 32%|███████████▋                        | 13758/42525 [20:32<41:46, 11.48it/s]

 32%|███████████▋                        | 13762/42525 [20:32<40:55, 11.71it/s]

 32%|███████████▋                        | 13764/42525 [20:32<40:54, 11.72it/s]

 32%|███████████▋                        | 13768/42525 [20:33<44:03, 10.88it/s]

 32%|███████████▋                        | 13772/42525 [20:33<43:04, 11.12it/s]

 32%|███████████▋                        | 13776/42525 [20:33<42:48, 11.19it/s]

 32%|███████████▋                        | 13780/42525 [20:34<43:06, 11.12it/s]

 32%|███████████▋                        | 13784/42525 [20:34<41:36, 11.51it/s]

 32%|███████████▋                        | 13788/42525 [20:34<41:08, 11.64it/s]

 32%|███████████▋                        | 13792/42525 [20:35<41:53, 11.43it/s]

 32%|███████████▋                        | 13796/42525 [20:35<43:18, 11.06it/s]

 32%|███████████▋                        | 13800/42525 [20:35<43:33, 10.99it/s]

 32%|███████████▋                        | 13804/42525 [20:36<43:12, 11.08it/s]

 32%|███████████▋                        | 13808/42525 [20:36<43:37, 10.97it/s]

 32%|███████████▋                        | 13812/42525 [20:36<43:12, 11.08it/s]

 32%|███████████▋                        | 13816/42525 [20:37<42:38, 11.22it/s]

 32%|███████████▋                        | 13820/42525 [20:37<44:26, 10.77it/s]

 33%|███████████▋                        | 13824/42525 [20:38<43:37, 10.96it/s]

 33%|███████████▋                        | 13828/42525 [20:38<42:09, 11.34it/s]

 33%|███████████▋                        | 13832/42525 [20:38<42:27, 11.26it/s]

 33%|███████████▋                        | 13836/42525 [20:39<41:29, 11.53it/s]

 33%|███████████▋                        | 13840/42525 [20:39<41:09, 11.62it/s]

 33%|███████████▋                        | 13844/42525 [20:39<42:34, 11.23it/s]

 33%|███████████▋                        | 13848/42525 [20:40<43:30, 10.98it/s]

 33%|███████████▋                        | 13852/42525 [20:40<42:56, 11.13it/s]

 33%|███████████▋                        | 13856/42525 [20:40<43:30, 10.98it/s]

 33%|███████████▋                        | 13860/42525 [20:41<43:38, 10.95it/s]

 33%|███████████▋                        | 13864/42525 [20:41<41:53, 11.40it/s]

 33%|███████████▋                        | 13868/42525 [20:41<40:54, 11.68it/s]

 33%|███████████▋                        | 13872/42525 [20:42<40:57, 11.66it/s]

 33%|███████████▋                        | 13876/42525 [20:42<43:24, 11.00it/s]

 33%|███████████▊                        | 13880/42525 [20:42<42:07, 11.33it/s]

 33%|███████████▊                        | 13884/42525 [20:43<43:04, 11.08it/s]

 33%|███████████▊                        | 13888/42525 [20:43<44:09, 10.81it/s]

 33%|███████████▊                        | 13892/42525 [20:44<44:55, 10.62it/s]

 33%|███████████▊                        | 13896/42525 [20:44<43:24, 10.99it/s]

 33%|███████████▊                        | 13900/42525 [20:44<42:57, 11.10it/s]

 33%|███████████▊                        | 13904/42525 [20:45<43:12, 11.04it/s]

 33%|███████████▊                        | 13908/42525 [20:45<41:44, 11.43it/s]

 33%|███████████▊                        | 13912/42525 [20:45<41:20, 11.53it/s]

 33%|███████████▊                        | 13916/42525 [20:46<40:59, 11.63it/s]

 33%|███████████▊                        | 13920/42525 [20:46<40:48, 11.68it/s]

 33%|███████████▊                        | 13924/42525 [20:46<40:46, 11.69it/s]

 33%|███████████▊                        | 13928/42525 [20:47<41:47, 11.41it/s]

 33%|███████████▊                        | 13932/42525 [20:47<40:51, 11.66it/s]

 33%|███████████▊                        | 13936/42525 [20:47<42:12, 11.29it/s]

 33%|███████████▊                        | 13940/42525 [20:48<42:58, 11.09it/s]

 33%|███████████▊                        | 13944/42525 [20:48<41:47, 11.40it/s]

 33%|███████████▊                        | 13948/42525 [20:48<40:57, 11.63it/s]

 33%|███████████▊                        | 13952/42525 [20:49<40:33, 11.74it/s]

 33%|███████████▊                        | 13956/42525 [20:49<41:10, 11.57it/s]

 33%|███████████▊                        | 13960/42525 [20:50<41:44, 11.41it/s]

 33%|███████████▊                        | 13964/42525 [20:50<43:22, 10.97it/s]

 33%|███████████▊                        | 13968/42525 [20:50<43:08, 11.03it/s]

 33%|███████████▊                        | 13972/42525 [20:51<42:43, 11.14it/s]

 33%|███████████▊                        | 13976/42525 [20:51<43:18, 10.99it/s]

 33%|███████████▊                        | 13980/42525 [20:51<42:41, 11.15it/s]

 33%|███████████▊                        | 13984/42525 [20:52<42:32, 11.18it/s]

 33%|███████████▊                        | 13988/42525 [20:52<43:01, 11.05it/s]

 33%|███████████▊                        | 13992/42525 [20:52<41:18, 11.51it/s]

 33%|███████████▊                        | 13996/42525 [20:53<41:34, 11.44it/s]

 33%|███████████▊                        | 14000/42525 [20:53<40:54, 11.62it/s]

 33%|███████████▊                        | 14004/42525 [20:53<37:27, 12.69it/s]

 33%|███████████▊                        | 14008/42525 [20:54<37:31, 12.67it/s]

 33%|███████████▊                        | 14012/42525 [20:54<39:06, 12.15it/s]

 33%|███████████▊                        | 14016/42525 [20:54<38:05, 12.47it/s]

 33%|███████████▊                        | 14020/42525 [20:55<40:08, 11.84it/s]

 33%|███████████▊                        | 14024/42525 [20:55<40:18, 11.79it/s]

 33%|███████████▉                        | 14028/42525 [20:55<40:24, 11.75it/s]

 33%|███████████▉                        | 14032/42525 [20:56<40:44, 11.66it/s]

 33%|███████████▉                        | 14036/42525 [20:56<42:07, 11.27it/s]

 33%|███████████▉                        | 14040/42525 [20:56<41:11, 11.52it/s]

 33%|███████████▉                        | 14044/42525 [20:57<41:32, 11.43it/s]

 33%|███████████▉                        | 14048/42525 [20:57<41:59, 11.30it/s]

 33%|███████████▉                        | 14052/42525 [20:58<41:25, 11.46it/s]

 33%|███████████▉                        | 14056/42525 [20:58<41:49, 11.34it/s]

 33%|███████████▉                        | 14060/42525 [20:58<41:10, 11.52it/s]

 33%|███████████▉                        | 14064/42525 [20:59<42:16, 11.22it/s]

 33%|███████████▉                        | 14068/42525 [20:59<42:52, 11.06it/s]

 33%|███████████▉                        | 14072/42525 [20:59<44:00, 10.78it/s]

 33%|███████████▉                        | 14076/42525 [21:00<44:15, 10.71it/s]

 33%|███████████▉                        | 14080/42525 [21:00<42:28, 11.16it/s]

 33%|███████████▉                        | 14084/42525 [21:00<41:29, 11.43it/s]

 33%|███████████▉                        | 14088/42525 [21:01<42:54, 11.05it/s]

 33%|███████████▉                        | 14092/42525 [21:01<41:41, 11.37it/s]

 33%|███████████▉                        | 14096/42525 [21:01<42:44, 11.09it/s]

 33%|███████████▉                        | 14100/42525 [21:02<43:17, 10.94it/s]

 33%|███████████▉                        | 14104/42525 [21:02<42:13, 11.22it/s]

 33%|███████████▉                        | 14108/42525 [21:03<42:12, 11.22it/s]

 33%|███████████▉                        | 14112/42525 [21:03<43:02, 11.00it/s]

 33%|███████████▉                        | 14116/42525 [21:03<43:16, 10.94it/s]

 33%|███████████▉                        | 14120/42525 [21:04<41:38, 11.37it/s]

 33%|███████████▉                        | 14124/42525 [21:04<42:57, 11.02it/s]

 33%|███████████▉                        | 14128/42525 [21:04<41:24, 11.43it/s]

 33%|███████████▉                        | 14132/42525 [21:05<41:10, 11.49it/s]

 33%|███████████▉                        | 14136/42525 [21:05<41:54, 11.29it/s]

 33%|███████████▉                        | 14140/42525 [21:05<43:53, 10.78it/s]

 33%|███████████▉                        | 14144/42525 [21:06<43:26, 10.89it/s]

 33%|███████████▉                        | 14148/42525 [21:06<43:06, 10.97it/s]

 33%|███████████▉                        | 14152/42525 [21:07<41:26, 11.41it/s]

 33%|███████████▉                        | 14156/42525 [21:07<40:40, 11.63it/s]

 33%|███████████▉                        | 14160/42525 [21:07<41:31, 11.39it/s]

 33%|███████████▉                        | 14164/42525 [21:08<40:41, 11.62it/s]

 33%|███████████▉                        | 14168/42525 [21:08<40:23, 11.70it/s]

 33%|███████████▉                        | 14172/42525 [21:08<41:51, 11.29it/s]

 33%|████████████                        | 14175/42525 [21:09<41:17, 11.44it/s]

{'loss': '0.8582', 'grad_norm': '6.445', 'learning_rate': '1.419e-05', 'epoch': '1'}

  0%|                                                  | 0/788 [00:00<?, ?it/s]
  0%|▏                                         | 3/788 [00:00<00:30, 26.06it/s]

  1%|▎                                         | 6/788 [00:00<00:35, 21.92it/s]
  1%|▍                                         | 9/788 [00:00<00:34, 22.82it/s]

  2%|▌                                        | 12/788 [00:00<00:31, 24.99it/s]
  2%|▊                                        | 15/788 [00:00<00:32, 23.56it/s]

  2%|▉                                        | 18/788 [00:00<00:35, 21.92it/s]
  3%|█                                        | 21/788 [00:00<00:36, 21.14it/s]

  3%|█▏                                       | 24/788 [00:01<00:35, 21.70it/s]
  3%|█▍                                       | 27/788 [00:01<00:36, 21.10it/s]

  4%|█▌                                       | 30/788 [00:01<00:34, 21.66it/s]
  4%|█▋                                       | 33/788 [00:01<00:35, 21.37it/s]

  5%|█▊                                       | 36/788 [00:01<00:37, 20.10it/s]
  5%|██                                       | 39/788 [00:01<00:35, 21.30it/s]

  5%|██▏                                      | 42/788 [00:01<00:33, 22.42it/s]
  6%|██▎                                      | 45/788 [00:02<00:31, 23.94it/s]

  6%|██▍                                      | 48/788 [00:02<00:32, 22.83it/s]
  6%|██▋                                      | 51/788 [00:02<00:30, 23.80it/s]

  7%|██▊                                      | 54/788 [00:02<00:30, 24.37it/s]
  7%|██▉                                      | 57/788 [00:02<00:30, 23.61it/s]

  8%|███                                      | 60/788 [00:02<00:29, 24.63it/s]
  8%|███▎                                     | 63/788 [00:02<00:31, 22.71it/s]

  8%|███▍                                     | 66/788 [00:02<00:31, 23.21it/s]
  9%|███▌                                     | 69/788 [00:03<00:32, 22.00it/s]

  9%|███▋                                     | 72/788 [00:03<00:32, 21.82it/s]
 10%|███▉                                     | 75/788 [00:03<00:33, 21.19it/s]

 10%|████                                     | 78/788 [00:03<00:33, 21.29it/s]
 10%|████▏                                    | 81/788 [00:03<00:34, 20.70it/s]

 11%|████▎                                    | 84/788 [00:03<00:34, 20.51it/s]
 11%|████▌                                    | 87/788 [00:03<00:33, 20.90it/s]

 11%|████▋                                    | 90/788 [00:04<00:33, 21.12it/s]
 12%|████▊                                    | 93/788 [00:04<00:34, 19.97it/s]

 12%|████▉                                    | 96/788 [00:04<00:33, 20.46it/s]
 13%|█████▏                                   | 99/788 [00:04<00:33, 20.66it/s]

 13%|█████▏                                  | 102/788 [00:04<00:32, 20.85it/s]
 13%|█████▎                                  | 105/788 [00:04<00:33, 20.10it/s]

 14%|█████▍                                  | 108/788 [00:04<00:32, 21.03it/s]
 14%|█████▋                                  | 111/788 [00:05<00:29, 22.63it/s]

 14%|█████▊                                  | 114/788 [00:05<00:29, 22.51it/s]
 15%|█████▉                                  | 117/788 [00:05<00:31, 21.35it/s]

 15%|██████                                  | 120/788 [00:05<00:31, 21.05it/s]
 16%|██████▏                                 | 123/788 [00:05<00:32, 20.64it/s]

 16%|██████▍                                 | 127/788 [00:05<00:28, 23.52it/s]
 16%|██████▌                                 | 130/788 [00:05<00:28, 22.87it/s]

 17%|██████▊                                 | 133/788 [00:06<00:28, 22.78it/s]
 17%|██████▉                                 | 136/788 [00:06<00:27, 23.44it/s]

 18%|███████                                 | 139/788 [00:06<00:28, 22.58it/s]
 18%|███████▏                                | 142/788 [00:06<00:28, 22.67it/s]

 18%|███████▎                                | 145/788 [00:06<00:29, 21.67it/s]
 19%|███████▌                                | 149/788 [00:06<00:25, 25.25it/s]

 19%|███████▋                                | 152/788 [00:06<00:24, 25.83it/s]
 20%|███████▊                                | 155/788 [00:06<00:26, 23.79it/s]

 20%|████████                                | 158/788 [00:07<00:26, 24.12it/s]
 20%|████████▏                               | 161/788 [00:07<00:27, 22.97it/s]

 21%|████████▎                               | 164/788 [00:07<00:28, 21.84it/s]
 21%|████████▍                               | 167/788 [00:07<00:29, 21.34it/s]

 22%|████████▋                               | 170/788 [00:07<00:28, 21.51it/s]
 22%|████████▊                               | 173/788 [00:07<00:26, 22.86it/s]

 22%|████████▉                               | 176/788 [00:07<00:28, 21.85it/s]
 23%|█████████                               | 179/788 [00:08<00:28, 21.50it/s]

 23%|█████████▏                              | 182/788 [00:08<00:30, 20.12it/s]
 23%|█████████▍                              | 185/788 [00:08<00:28, 20.81it/s]

 24%|█████████▌                              | 188/788 [00:08<00:27, 21.92it/s]
 24%|█████████▋                              | 191/788 [00:08<00:29, 20.21it/s]

 25%|█████████▊                              | 194/788 [00:08<00:27, 21.32it/s]
 25%|██████████                              | 197/788 [00:08<00:25, 22.79it/s]

 25%|██████████▏                             | 200/788 [00:09<00:26, 21.95it/s]
 26%|██████████▎                             | 203/788 [00:09<00:26, 21.93it/s]

 26%|██████████▍                             | 206/788 [00:09<00:25, 23.18it/s]
 27%|██████████▌                             | 209/788 [00:09<00:25, 22.61it/s]

 27%|██████████▊                             | 212/788 [00:09<00:26, 21.66it/s]
 27%|██████████▉                             | 215/788 [00:09<00:25, 22.10it/s]

 28%|███████████                             | 218/788 [00:09<00:25, 22.28it/s]
 28%|███████████▏                            | 221/788 [00:10<00:25, 22.57it/s]

 28%|███████████▎                            | 224/788 [00:10<00:24, 23.28it/s]
 29%|███████████▌                            | 227/788 [00:10<00:23, 23.90it/s]

 29%|███████████▋                            | 230/788 [00:10<00:22, 25.33it/s]
 30%|███████████▊                            | 233/788 [00:10<00:22, 24.19it/s]

 30%|███████████▉                            | 236/788 [00:10<00:24, 22.79it/s]
 30%|████████████▏                           | 239/788 [00:10<00:23, 23.02it/s]

 31%|████████████▎                           | 242/788 [00:10<00:22, 23.80it/s]
 31%|████████████▍                           | 245/788 [00:11<00:24, 21.82it/s]

 31%|████████████▌                           | 248/788 [00:11<00:25, 20.99it/s]
 32%|████████████▋                           | 251/788 [00:11<00:24, 21.51it/s]

 32%|████████████▉                           | 254/788 [00:11<00:25, 21.19it/s]
 33%|█████████████                           | 257/788 [00:11<00:24, 22.02it/s]

 33%|█████████████▏                          | 260/788 [00:11<00:23, 22.11it/s]
 33%|█████████████▎                          | 263/788 [00:11<00:24, 21.27it/s]

 34%|█████████████▌                          | 266/788 [00:12<00:23, 21.80it/s]
 34%|█████████████▋                          | 269/788 [00:12<00:24, 21.02it/s]

 35%|█████████████▊                          | 272/788 [00:12<00:25, 20.58it/s]
 35%|█████████████▉                          | 275/788 [00:12<00:25, 20.17it/s]

 35%|██████████████                          | 278/788 [00:12<00:26, 19.02it/s]
 36%|██████████████▏                         | 280/788 [00:12<00:26, 19.05it/s]

 36%|██████████████▎                         | 283/788 [00:12<00:25, 20.07it/s]
 36%|██████████████▌                         | 286/788 [00:13<00:23, 21.45it/s]

 33%|████████████                        | 14175/42525 [21:22<41:17, 11.44it/s]
 37%|██████████████▊                         | 292/788 [00:13<00:20, 24.15it/s]

 37%|██████████████▉                         | 295/788 [00:13<00:21, 23.24it/s]
 38%|███████████████▏                        | 298/788 [00:13<00:21, 22.81it/s]

 38%|███████████████▎                        | 301/788 [00:13<00:20, 23.47it/s]
 39%|███████████████▍                        | 304/788 [00:13<00:20, 23.41it/s]

 39%|███████████████▌                        | 307/788 [00:13<00:20, 22.97it/s]
 39%|███████████████▋                        | 310/788 [00:14<00:20, 23.30it/s]

 40%|███████████████▉                        | 313/788 [00:14<00:21, 22.50it/s]
 40%|████████████████                        | 316/788 [00:14<00:20, 22.90it/s]

 40%|████████████████▏                       | 319/788 [00:14<00:20, 22.69it/s]
 41%|████████████████▎                       | 322/788 [00:14<00:20, 22.77it/s]

 41%|████████████████▍                       | 325/788 [00:14<00:21, 21.73it/s]
 42%|████████████████▋                       | 328/788 [00:14<00:20, 22.03it/s]

 42%|████████████████▊                       | 331/788 [00:14<00:20, 22.43it/s]
 42%|████████████████▉                       | 334/788 [00:15<00:19, 23.79it/s]

 43%|█████████████████                       | 337/788 [00:15<00:18, 23.98it/s]
 43%|█████████████████▎                      | 340/788 [00:15<00:19, 22.99it/s]

 44%|█████████████████▍                      | 343/788 [00:15<00:20, 21.42it/s]
 44%|█████████████████▌                      | 346/788 [00:15<00:22, 19.79it/s]

 44%|█████████████████▋                      | 349/788 [00:15<00:21, 20.48it/s]
 45%|█████████████████▊                      | 352/788 [00:15<00:19, 22.03it/s]

 45%|██████████████████                      | 355/788 [00:16<00:19, 21.96it/s]
 45%|██████████████████▏                     | 358/788 [00:16<00:20, 21.36it/s]

 46%|██████████████████▎                     | 361/788 [00:16<00:18, 22.76it/s]
 46%|██████████████████▍                     | 364/788 [00:16<00:17, 24.44it/s]

 47%|██████████████████▋                     | 367/788 [00:16<00:17, 23.79it/s]
 47%|██████████████████▊                     | 370/788 [00:16<00:17, 24.27it/s]

 47%|██████████████████▉                     | 373/788 [00:16<00:16, 24.84it/s]
 48%|███████████████████                     | 376/788 [00:16<00:16, 25.11it/s]

 48%|███████████████████▎                    | 380/788 [00:17<00:15, 26.70it/s]
 49%|███████████████████▍                    | 383/788 [00:17<00:15, 25.69it/s]

 49%|███████████████████▌                    | 386/788 [00:17<00:16, 24.59it/s]
 49%|███████████████████▋                    | 389/788 [00:17<00:16, 23.53it/s]

 50%|███████████████████▉                    | 392/788 [00:17<00:17, 22.01it/s]
 50%|████████████████████                    | 395/788 [00:17<00:17, 23.10it/s]

 51%|████████████████████▏                   | 398/788 [00:17<00:17, 22.67it/s]
 51%|████████████████████▎                   | 401/788 [00:17<00:16, 23.21it/s]

 51%|████████████████████▌                   | 404/788 [00:18<00:15, 24.12it/s]
 52%|████████████████████▋                   | 407/788 [00:18<00:15, 24.48it/s]

 52%|████████████████████▊                   | 410/788 [00:18<00:15, 25.06it/s]
 52%|████████████████████▉                   | 413/788 [00:18<00:15, 24.45it/s]

 53%|█████████████████████                   | 416/788 [00:18<00:15, 24.12it/s]
 53%|█████████████████████▎                  | 419/788 [00:18<00:17, 21.62it/s]

 54%|█████████████████████▍                  | 422/788 [00:18<00:17, 21.27it/s]
 54%|█████████████████████▌                  | 425/788 [00:19<00:16, 21.55it/s]

 54%|█████████████████████▋                  | 428/788 [00:19<00:16, 22.29it/s]
 55%|█████████████████████▉                  | 431/788 [00:19<00:15, 23.45it/s]

 55%|██████████████████████                  | 434/788 [00:19<00:15, 22.99it/s]
 55%|██████████████████████▏                 | 437/788 [00:19<00:15, 22.35it/s]

 56%|██████████████████████▎                 | 440/788 [00:19<00:15, 22.23it/s]
 56%|██████████████████████▍                 | 443/788 [00:19<00:15, 21.78it/s]

 57%|██████████████████████▋                 | 446/788 [00:19<00:15, 21.72it/s]
 57%|██████████████████████▊                 | 449/788 [00:20<00:14, 22.82it/s]

 57%|██████████████████████▉                 | 452/788 [00:20<00:15, 22.29it/s]
 58%|███████████████████████                 | 455/788 [00:20<00:14, 22.47it/s]

 58%|███████████████████████▏                | 458/788 [00:20<00:13, 24.00it/s]
 59%|███████████████████████▍                | 461/788 [00:20<00:14, 22.78it/s]

 59%|███████████████████████▌                | 464/788 [00:20<00:14, 22.38it/s]
 59%|███████████████████████▋                | 467/788 [00:20<00:14, 22.35it/s]

 60%|███████████████████████▊                | 470/788 [00:21<00:15, 20.79it/s]
 60%|████████████████████████                | 473/788 [00:21<00:15, 20.59it/s]

 60%|████████████████████████▏               | 476/788 [00:21<00:14, 21.02it/s]
 61%|████████████████████████▎               | 479/788 [00:21<00:14, 21.49it/s]

 61%|████████████████████████▍               | 482/788 [00:21<00:13, 21.97it/s]
 62%|████████████████████████▌               | 485/788 [00:21<00:13, 21.71it/s]

 62%|████████████████████████▊               | 488/788 [00:21<00:13, 21.46it/s]
 62%|████████████████████████▉               | 491/788 [00:22<00:14, 20.37it/s]

 63%|█████████████████████████               | 494/788 [00:22<00:14, 20.93it/s]
 63%|█████████████████████████▎              | 498/788 [00:22<00:12, 23.51it/s]

 64%|█████████████████████████▍              | 501/788 [00:22<00:12, 23.61it/s]
 64%|█████████████████████████▌              | 504/788 [00:22<00:12, 23.00it/s]

 64%|█████████████████████████▋              | 507/788 [00:22<00:11, 24.50it/s]
 65%|█████████████████████████▉              | 510/788 [00:22<00:11, 23.41it/s]

 65%|██████████████████████████              | 513/788 [00:22<00:11, 24.80it/s]
 65%|██████████████████████████▏             | 516/788 [00:23<00:11, 24.55it/s]

 66%|██████████████████████████▎             | 519/788 [00:23<00:11, 23.92it/s]
 66%|██████████████████████████▍             | 522/788 [00:23<00:11, 24.08it/s]

 67%|██████████████████████████▋             | 525/788 [00:23<00:10, 24.66it/s]
 67%|██████████████████████████▊             | 528/788 [00:23<00:11, 23.34it/s]

 67%|██████████████████████████▉             | 531/788 [00:23<00:11, 21.67it/s]
 68%|███████████████████████████             | 534/788 [00:23<00:11, 22.34it/s]

 68%|███████████████████████████▎            | 537/788 [00:24<00:11, 21.52it/s]
 69%|███████████████████████████▍            | 540/788 [00:24<00:11, 20.94it/s]

 69%|███████████████████████████▌            | 543/788 [00:24<00:12, 20.06it/s]
 69%|███████████████████████████▋            | 546/788 [00:24<00:12, 19.75it/s]

 70%|███████████████████████████▊            | 549/788 [00:24<00:11, 20.49it/s]
 70%|████████████████████████████            | 552/788 [00:24<00:11, 21.15it/s]

 70%|████████████████████████████▏           | 555/788 [00:24<00:11, 21.13it/s]
 71%|████████████████████████████▎           | 558/788 [00:25<00:10, 22.33it/s]

 71%|████████████████████████████▍           | 561/788 [00:25<00:09, 24.01it/s]
 72%|████████████████████████████▋           | 564/788 [00:25<00:09, 24.55it/s]

 72%|████████████████████████████▊           | 567/788 [00:25<00:09, 23.06it/s]
 72%|████████████████████████████▉           | 570/788 [00:25<00:09, 23.77it/s]

 73%|█████████████████████████████           | 573/788 [00:25<00:09, 21.95it/s]
 73%|█████████████████████████████▏          | 576/788 [00:25<00:09, 22.53it/s]

 73%|█████████████████████████████▍          | 579/788 [00:25<00:09, 22.03it/s]
 74%|█████████████████████████████▌          | 582/788 [00:26<00:09, 21.48it/s]

 74%|█████████████████████████████▋          | 585/788 [00:26<00:09, 21.32it/s]
 75%|█████████████████████████████▊          | 588/788 [00:26<00:09, 20.86it/s]

 75%|██████████████████████████████          | 591/788 [00:26<00:09, 21.67it/s]
 75%|██████████████████████████████▏         | 594/788 [00:26<00:08, 21.99it/s]

 76%|██████████████████████████████▎         | 597/788 [00:26<00:08, 22.19it/s]
 76%|██████████████████████████████▍         | 600/788 [00:26<00:08, 23.17it/s]

 77%|██████████████████████████████▌         | 603/788 [00:27<00:08, 22.95it/s]
 77%|██████████████████████████████▊         | 606/788 [00:27<00:07, 24.31it/s]

 77%|██████████████████████████████▉         | 609/788 [00:27<00:07, 23.02it/s]
 78%|███████████████████████████████         | 612/788 [00:27<00:07, 24.14it/s]

 78%|███████████████████████████████▏        | 615/788 [00:27<00:07, 23.51it/s]
 78%|███████████████████████████████▎        | 618/788 [00:27<00:07, 22.66it/s]

 79%|███████████████████████████████▌        | 621/788 [00:27<00:07, 23.39it/s]
 79%|███████████████████████████████▋        | 624/788 [00:27<00:06, 24.57it/s]

 80%|███████████████████████████████▊        | 627/788 [00:28<00:07, 22.84it/s]
 80%|███████████████████████████████▉        | 630/788 [00:28<00:07, 20.95it/s]

 80%|████████████████████████████████▏       | 633/788 [00:28<00:07, 21.02it/s]
 81%|████████████████████████████████▎       | 636/788 [00:28<00:06, 22.91it/s]

 81%|████████████████████████████████▍       | 639/788 [00:28<00:07, 21.19it/s]
 82%|████████████████████████████████▋       | 643/788 [00:28<00:06, 24.05it/s]

 82%|████████████████████████████████▊       | 646/788 [00:28<00:05, 23.83it/s]
 82%|████████████████████████████████▉       | 649/788 [00:28<00:05, 24.99it/s]

 83%|█████████████████████████████████       | 652/788 [00:29<00:05, 25.43it/s]
 83%|█████████████████████████████████▏      | 655/788 [00:29<00:05, 24.60it/s]

 84%|█████████████████████████████████▍      | 658/788 [00:29<00:05, 24.00it/s]
 84%|█████████████████████████████████▌      | 661/788 [00:29<00:05, 23.14it/s]

 84%|█████████████████████████████████▋      | 664/788 [00:29<00:05, 23.56it/s]
 85%|█████████████████████████████████▊      | 667/788 [00:29<00:05, 22.39it/s]

 85%|██████████████████████████████████      | 670/788 [00:29<00:05, 22.79it/s]
 85%|██████████████████████████████████▏     | 673/788 [00:30<00:05, 22.18it/s]

 86%|██████████████████████████████████▎     | 676/788 [00:30<00:04, 22.58it/s]
 86%|██████████████████████████████████▍     | 679/788 [00:30<00:04, 22.00it/s]

 87%|██████████████████████████████████▌     | 682/788 [00:30<00:04, 22.72it/s]
 87%|██████████████████████████████████▊     | 685/788 [00:30<00:04, 23.12it/s]

 87%|██████████████████████████████████▉     | 688/788 [00:30<00:04, 22.72it/s]
 88%|███████████████████████████████████     | 691/788 [00:30<00:04, 20.94it/s]

 88%|███████████████████████████████████▏    | 694/788 [00:30<00:04, 22.76it/s]
 88%|███████████████████████████████████▍    | 697/788 [00:31<00:03, 22.99it/s]

 89%|███████████████████████████████████▌    | 700/788 [00:31<00:03, 22.68it/s]
 89%|███████████████████████████████████▋    | 703/788 [00:31<00:03, 21.38it/s]

 90%|███████████████████████████████████▊    | 706/788 [00:31<00:04, 20.43it/s]
 90%|███████████████████████████████████▉    | 709/788 [00:31<00:03, 20.98it/s]

 90%|████████████████████████████████████▏   | 712/788 [00:31<00:03, 20.86it/s]
 91%|████████████████████████████████████▎   | 715/788 [00:31<00:03, 22.70it/s]

 91%|████████████████████████████████████▍   | 719/788 [00:32<00:02, 23.96it/s]
 92%|████████████████████████████████████▋   | 722/788 [00:32<00:02, 23.41it/s]

 92%|████████████████████████████████████▊   | 725/788 [00:32<00:02, 22.25it/s]
 92%|████████████████████████████████████▉   | 728/788 [00:32<00:02, 21.83it/s]

 93%|█████████████████████████████████████   | 731/788 [00:32<00:02, 20.96it/s]
 93%|█████████████████████████████████████▎  | 734/788 [00:32<00:02, 21.14it/s]

 94%|█████████████████████████████████████▍  | 737/788 [00:32<00:02, 20.99it/s]
 94%|█████████████████████████████████████▌  | 740/788 [00:33<00:02, 21.07it/s]

 94%|█████████████████████████████████████▋  | 743/788 [00:33<00:01, 22.86it/s]
 95%|█████████████████████████████████████▊  | 746/788 [00:33<00:01, 22.20it/s]

 95%|██████████████████████████████████████  | 749/788 [00:33<00:01, 22.63it/s]
 95%|██████████████████████████████████████▏ | 752/788 [00:33<00:01, 21.51it/s]

 96%|██████████████████████████████████████▎ | 755/788 [00:33<00:01, 21.49it/s]
 96%|██████████████████████████████████████▍ | 758/788 [00:33<00:01, 22.35it/s]

 97%|██████████████████████████████████████▋ | 761/788 [00:34<00:01, 21.97it/s]
 97%|██████████████████████████████████████▊ | 765/788 [00:34<00:00, 24.65it/s]

 97%|██████████████████████████████████████▉ | 768/788 [00:34<00:00, 22.91it/s]
 98%|███████████████████████████████████████▏| 771/788 [00:34<00:00, 23.13it/s]

 98%|███████████████████████████████████████▎| 774/788 [00:34<00:00, 24.36it/s]
 99%|███████████████████████████████████████▍| 777/788 [00:34<00:00, 22.85it/s]

 99%|███████████████████████████████████████▋| 781/788 [00:34<00:00, 24.25it/s]
 99%|███████████████████████████████████████▊| 784/788 [00:34<00:00, 24.45it/s]

 33%|████████████                        | 14175/42525 [21:44<41:17, 11.44it/s]
100%|████████████████████████████████████████| 788/788 [00:35<00:00, 24.77it/s]

{'eval_loss': '0.8341', 'eval_accuracy': '0.6369', 'eval_macro_f1': '0.6399', 'eval_mae': '0.4083', 'eval_cil_score': '0.8979', 'eval_quadratic_weighted_kappa': '0.8669', 'eval_runtime': '35.16', 'eval_samples_per_second': '716.7', 'eval_steps_per_second': '22.41', 'epoch': '1'}

Writing model shards:   0%|                              | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|██████████████████████| 1/1 [00:01<00:00,  1.28s/it]

 33%|███████████                      | 14178/42525 [21:48<33:00:55,  4.19s/it]

 33%|███████████                      | 14182/42525 [21:48<16:30:55,  2.10s/it]

 33%|███████████▎                      | 14186/42525 [21:49<8:26:03,  1.07s/it]

 33%|███████████▎                      | 14190/42525 [21:49<4:28:26,  1.76it/s]

 33%|███████████▎                      | 14194/42525 [21:49<2:33:32,  3.08it/s]

 33%|███████████▎                      | 14198/42525 [21:50<1:36:13,  4.91it/s]

 33%|███████████▎                      | 14202/42525 [21:50<1:09:46,  6.77it/s]

 33%|████████████                        | 14206/42525 [21:50<56:32,  8.35it/s]

 33%|████████████                        | 14210/42525 [21:51<48:57,  9.64it/s]

 33%|████████████                        | 14214/42525 [21:51<44:06, 10.70it/s]

 33%|████████████                        | 14218/42525 [21:51<42:36, 11.07it/s]

 33%|████████████                        | 14222/42525 [21:52<39:05, 12.07it/s]

 33%|████████████                        | 14226/42525 [21:52<41:12, 11.44it/s]

 33%|████████████                        | 14230/42525 [21:52<41:19, 11.41it/s]

 33%|████████████                        | 14232/42525 [21:53<43:05, 10.94it/s]

 33%|████████████                        | 14236/42525 [21:53<44:58, 10.48it/s]

 33%|████████████                        | 14240/42525 [21:53<42:24, 11.12it/s]

 33%|████████████                        | 14244/42525 [21:54<41:21, 11.39it/s]

 34%|████████████                        | 14248/42525 [21:54<39:59, 11.78it/s]

 34%|████████████                        | 14252/42525 [21:54<37:40, 12.51it/s]

 34%|████████████                        | 14256/42525 [21:55<36:10, 13.03it/s]

 34%|████████████                        | 14260/42525 [21:55<36:09, 13.03it/s]

 34%|████████████                        | 14264/42525 [21:55<39:35, 11.90it/s]

 34%|████████████                        | 14268/42525 [21:56<38:20, 12.28it/s]

 34%|████████████                        | 14272/42525 [21:56<37:35, 12.53it/s]

 34%|████████████                        | 14276/42525 [21:56<39:05, 12.04it/s]

 34%|████████████                        | 14280/42525 [21:57<39:12, 12.01it/s]

 34%|████████████                        | 14284/42525 [21:57<39:24, 11.94it/s]

 34%|████████████                        | 14288/42525 [21:57<39:56, 11.78it/s]

 34%|████████████                        | 14292/42525 [21:58<39:40, 11.86it/s]

 34%|████████████                        | 14296/42525 [21:58<38:17, 12.28it/s]

 34%|████████████                        | 14300/42525 [21:58<38:10, 12.32it/s]

 34%|████████████                        | 14304/42525 [21:59<37:50, 12.43it/s]

 34%|████████████                        | 14308/42525 [21:59<37:14, 12.63it/s]

 34%|████████████                        | 14312/42525 [21:59<39:39, 11.86it/s]

 34%|████████████                        | 14316/42525 [22:00<40:29, 11.61it/s]

 34%|████████████                        | 14320/42525 [22:00<38:24, 12.24it/s]

 34%|████████████▏                       | 14324/42525 [22:00<38:14, 12.29it/s]

 34%|████████████▏                       | 14328/42525 [22:00<38:10, 12.31it/s]

 34%|████████████▏                       | 14332/42525 [22:01<39:12, 11.98it/s]

 34%|████████████▏                       | 14336/42525 [22:01<39:19, 11.95it/s]

 34%|████████████▏                       | 14340/42525 [22:02<42:33, 11.04it/s]

 34%|████████████▏                       | 14344/42525 [22:02<41:03, 11.44it/s]

 34%|████████████▏                       | 14348/42525 [22:02<40:16, 11.66it/s]

 34%|████████████▏                       | 14352/42525 [22:03<39:59, 11.74it/s]

 34%|████████████▏                       | 14356/42525 [22:03<40:11, 11.68it/s]

 34%|████████████▏                       | 14360/42525 [22:03<41:58, 11.18it/s]

 34%|████████████▏                       | 14364/42525 [22:04<42:42, 10.99it/s]

 34%|████████████▏                       | 14368/42525 [22:04<41:10, 11.40it/s]

 34%|████████████▏                       | 14372/42525 [22:04<41:01, 11.44it/s]

 34%|████████████▏                       | 14376/42525 [22:05<40:30, 11.58it/s]

 34%|████████████▏                       | 14380/42525 [22:05<40:59, 11.44it/s]

 34%|████████████▏                       | 14384/42525 [22:05<40:19, 11.63it/s]

 34%|████████████▏                       | 14388/42525 [22:06<41:26, 11.32it/s]

 34%|████████████▏                       | 14392/42525 [22:06<41:18, 11.35it/s]

 34%|████████████▏                       | 14396/42525 [22:06<41:09, 11.39it/s]

 34%|████████████▏                       | 14400/42525 [22:07<39:07, 11.98it/s]

 34%|████████████▏                       | 14402/42525 [22:07<39:25, 11.89it/s]

 34%|████████████▏                       | 14406/42525 [22:07<40:45, 11.50it/s]

 34%|████████████▏                       | 14410/42525 [22:08<37:32, 12.48it/s]

 34%|████████████▏                       | 14414/42525 [22:08<38:13, 12.26it/s]

 34%|████████████▏                       | 14418/42525 [22:08<36:17, 12.91it/s]

 34%|████████████▏                       | 14422/42525 [22:09<39:08, 11.97it/s]

 34%|████████████▏                       | 14426/42525 [22:09<38:42, 12.10it/s]

 34%|████████████▏                       | 14430/42525 [22:09<37:18, 12.55it/s]

 34%|████████████▏                       | 14434/42525 [22:10<37:29, 12.49it/s]

 34%|████████████▏                       | 14438/42525 [22:10<36:48, 12.72it/s]

 34%|████████████▏                       | 14442/42525 [22:10<39:21, 11.89it/s]

 34%|████████████▏                       | 14446/42525 [22:11<39:15, 11.92it/s]

 34%|████████████▏                       | 14450/42525 [22:11<37:14, 12.57it/s]

 34%|████████████▏                       | 14454/42525 [22:11<35:42, 13.10it/s]

 34%|████████████▏                       | 14458/42525 [22:11<36:33, 12.80it/s]

 34%|████████████▏                       | 14462/42525 [22:12<38:16, 12.22it/s]

 34%|████████████▏                       | 14466/42525 [22:12<39:19, 11.89it/s]

 34%|████████████▏                       | 14470/42525 [22:12<37:59, 12.31it/s]

 34%|████████████▎                       | 14474/42525 [22:13<37:10, 12.57it/s]

 34%|████████████▎                       | 14478/42525 [22:13<39:34, 11.81it/s]

 34%|████████████▎                       | 14482/42525 [22:13<36:14, 12.90it/s]

 34%|████████████▎                       | 14484/42525 [22:14<35:51, 13.03it/s]

 34%|████████████▎                       | 14488/42525 [22:14<41:47, 11.18it/s]

 34%|████████████▎                       | 14492/42525 [22:14<38:12, 12.23it/s]

 34%|████████████▎                       | 14496/42525 [22:15<38:14, 12.22it/s]

 34%|████████████▎                       | 14500/42525 [22:15<39:53, 11.71it/s]

 34%|████████████▎                       | 14502/42525 [22:15<37:52, 12.33it/s]

 34%|████████████▎                       | 14506/42525 [22:15<39:06, 11.94it/s]

 34%|████████████▎                       | 14510/42525 [22:16<39:53, 11.70it/s]

 34%|████████████▎                       | 14514/42525 [22:16<40:18, 11.58it/s]

 34%|████████████▎                       | 14518/42525 [22:16<37:45, 12.36it/s]

 34%|████████████▎                       | 14522/42525 [22:17<40:23, 11.55it/s]

 34%|████████████▎                       | 14526/42525 [22:17<40:58, 11.39it/s]

 34%|████████████▎                       | 14530/42525 [22:18<38:14, 12.20it/s]

 34%|████████████▎                       | 14534/42525 [22:18<37:58, 12.29it/s]

 34%|████████████▎                       | 14538/42525 [22:18<36:45, 12.69it/s]

 34%|████████████▎                       | 14540/42525 [22:18<40:57, 11.39it/s]

 34%|████████████▎                       | 14544/42525 [22:19<43:36, 10.70it/s]

 34%|████████████▎                       | 14548/42525 [22:19<42:19, 11.02it/s]

 34%|████████████▎                       | 14550/42525 [22:19<41:37, 11.20it/s]

 34%|████████████▎                       | 14554/42525 [22:20<43:52, 10.63it/s]

 34%|████████████▎                       | 14558/42525 [22:20<39:51, 11.69it/s]

 34%|████████████▎                       | 14562/42525 [22:20<39:53, 11.68it/s]

 34%|████████████▎                       | 14566/42525 [22:21<39:15, 11.87it/s]

 34%|████████████▎                       | 14570/42525 [22:21<37:50, 12.31it/s]

 34%|████████████▎                       | 14574/42525 [22:21<39:25, 11.81it/s]

 34%|████████████▎                       | 14578/42525 [22:22<38:05, 12.23it/s]

 34%|████████████▎                       | 14582/42525 [22:22<38:48, 12.00it/s]

 34%|████████████▎                       | 14586/42525 [22:22<36:51, 12.64it/s]

 34%|████████████▎                       | 14590/42525 [22:23<35:24, 13.15it/s]

 34%|████████████▎                       | 14594/42525 [22:23<37:59, 12.25it/s]

 34%|████████████▎                       | 14598/42525 [22:23<38:41, 12.03it/s]

 34%|████████████▎                       | 14602/42525 [22:24<39:13, 11.86it/s]

 34%|████████████▎                       | 14606/42525 [22:24<39:42, 11.72it/s]

 34%|████████████▎                       | 14610/42525 [22:24<40:29, 11.49it/s]

 34%|████████████▎                       | 14614/42525 [22:25<41:51, 11.11it/s]

 34%|████████████▎                       | 14616/42525 [22:25<41:21, 11.25it/s]

 34%|████████████▍                       | 14620/42525 [22:25<42:24, 10.97it/s]

 34%|████████████▍                       | 14624/42525 [22:26<42:29, 10.95it/s]

 34%|████████████▍                       | 14628/42525 [22:26<41:10, 11.29it/s]

 34%|████████████▍                       | 14632/42525 [22:26<39:16, 11.84it/s]

 34%|████████████▍                       | 14636/42525 [22:27<40:50, 11.38it/s]

 34%|████████████▍                       | 14640/42525 [22:27<42:19, 10.98it/s]

 34%|████████████▍                       | 14644/42525 [22:27<41:02, 11.32it/s]

 34%|████████████▍                       | 14648/42525 [22:28<43:13, 10.75it/s]

 34%|████████████▍                       | 14652/42525 [22:28<42:58, 10.81it/s]

 34%|████████████▍                       | 14656/42525 [22:28<41:33, 11.18it/s]

 34%|████████████▍                       | 14660/42525 [22:29<40:42, 11.41it/s]

 34%|████████████▍                       | 14664/42525 [22:29<42:29, 10.93it/s]

 34%|████████████▍                       | 14668/42525 [22:30<42:27, 10.93it/s]

 35%|████████████▍                       | 14672/42525 [22:30<43:04, 10.78it/s]

 35%|████████████▍                       | 14676/42525 [22:30<42:37, 10.89it/s]

 35%|████████████▍                       | 14680/42525 [22:31<42:46, 10.85it/s]

 35%|████████████▍                       | 14684/42525 [22:31<41:14, 11.25it/s]

 35%|████████████▍                       | 14688/42525 [22:31<41:27, 11.19it/s]

 35%|████████████▍                       | 14692/42525 [22:32<42:21, 10.95it/s]

 35%|████████████▍                       | 14696/42525 [22:32<41:55, 11.06it/s]

 35%|████████████▍                       | 14700/42525 [22:32<42:28, 10.92it/s]

 35%|████████████▍                       | 14704/42525 [22:33<42:51, 10.82it/s]

 35%|████████████▍                       | 14708/42525 [22:33<41:41, 11.12it/s]

 35%|████████████▍                       | 14712/42525 [22:34<41:38, 11.13it/s]

 35%|████████████▍                       | 14716/42525 [22:34<40:46, 11.37it/s]

 35%|████████████▍                       | 14720/42525 [22:34<41:32, 11.16it/s]

 35%|████████████▍                       | 14724/42525 [22:35<41:12, 11.24it/s]

 35%|████████████▍                       | 14728/42525 [22:35<41:05, 11.27it/s]

 35%|████████████▍                       | 14732/42525 [22:35<40:10, 11.53it/s]

 35%|████████████▍                       | 14736/42525 [22:36<40:21, 11.48it/s]

 35%|████████████▍                       | 14740/42525 [22:36<40:59, 11.30it/s]

 35%|████████████▍                       | 14744/42525 [22:36<39:59, 11.58it/s]

 35%|████████████▍                       | 14748/42525 [22:37<40:08, 11.53it/s]

 35%|████████████▍                       | 14752/42525 [22:37<40:10, 11.52it/s]

 35%|████████████▍                       | 14756/42525 [22:37<40:35, 11.40it/s]

 35%|████████████▍                       | 14760/42525 [22:38<40:47, 11.34it/s]

 35%|████████████▍                       | 14764/42525 [22:38<40:04, 11.54it/s]

 35%|████████████▌                       | 14768/42525 [22:38<40:31, 11.42it/s]

 35%|████████████▌                       | 14772/42525 [22:39<40:49, 11.33it/s]

 35%|████████████▌                       | 14776/42525 [22:39<40:05, 11.53it/s]

 35%|████████████▌                       | 14780/42525 [22:40<40:06, 11.53it/s]

 35%|████████████▌                       | 14784/42525 [22:40<40:06, 11.53it/s]

 35%|████████████▌                       | 14788/42525 [22:40<41:09, 11.23it/s]

 35%|████████████▌                       | 14792/42525 [22:41<40:27, 11.43it/s]

 35%|████████████▌                       | 14796/42525 [22:41<39:46, 11.62it/s]

 35%|████████████▌                       | 14800/42525 [22:41<39:42, 11.64it/s]

 35%|████████████▌                       | 14804/42525 [22:42<40:16, 11.47it/s]

 35%|████████████▌                       | 14808/42525 [22:42<39:42, 11.64it/s]

 35%|████████████▌                       | 14810/42525 [22:42<41:12, 11.21it/s]

 35%|████████████▌                       | 14814/42525 [22:43<42:46, 10.80it/s]

 35%|████████████▌                       | 14818/42525 [22:43<40:57, 11.27it/s]

 35%|████████████▌                       | 14822/42525 [22:43<39:51, 11.58it/s]

 35%|████████████▌                       | 14826/42525 [22:44<39:46, 11.61it/s]

 35%|████████████▌                       | 14830/42525 [22:44<40:15, 11.47it/s]

 35%|████████████▌                       | 14834/42525 [22:44<42:19, 10.90it/s]

 35%|████████████▌                       | 14838/42525 [22:45<40:36, 11.36it/s]

 35%|████████████▌                       | 14842/42525 [22:45<41:32, 11.11it/s]

 35%|████████████▌                       | 14846/42525 [22:45<42:10, 10.94it/s]

 35%|████████████▌                       | 14850/42525 [22:46<42:19, 10.90it/s]

 35%|████████████▌                       | 14854/42525 [22:46<41:32, 11.10it/s]

 35%|████████████▌                       | 14858/42525 [22:46<40:35, 11.36it/s]

 35%|████████████▌                       | 14862/42525 [22:47<40:01, 11.52it/s]

 35%|████████████▌                       | 14866/42525 [22:47<42:22, 10.88it/s]

 35%|████████████▌                       | 14870/42525 [22:48<41:27, 11.12it/s]

 35%|████████████▌                       | 14874/42525 [22:48<40:45, 11.31it/s]

 35%|████████████▌                       | 14878/42525 [22:48<40:26, 11.39it/s]

 35%|████████████▌                       | 14882/42525 [22:49<39:39, 11.62it/s]

 35%|████████████▌                       | 14886/42525 [22:49<39:34, 11.64it/s]

 35%|████████████▌                       | 14890/42525 [22:49<41:32, 11.09it/s]

 35%|████████████▌                       | 14894/42525 [22:50<40:31, 11.36it/s]

 35%|████████████▌                       | 14898/42525 [22:50<41:06, 11.20it/s]

 35%|████████████▌                       | 14902/42525 [22:50<41:10, 11.18it/s]

 35%|████████████▌                       | 14906/42525 [22:51<42:59, 10.71it/s]

 35%|████████████▌                       | 14910/42525 [22:51<44:22, 10.37it/s]

 35%|████████████▋                       | 14914/42525 [22:51<41:35, 11.06it/s]

 35%|████████████▋                       | 14918/42525 [22:52<41:54, 10.98it/s]

 35%|████████████▋                       | 14922/42525 [22:52<40:52, 11.26it/s]

 35%|████████████▋                       | 14926/42525 [22:53<41:25, 11.10it/s]

 35%|████████████▋                       | 14928/42525 [22:53<40:56, 11.24it/s]

 35%|████████████▋                       | 14932/42525 [22:53<41:56, 10.96it/s]

 35%|████████████▋                       | 14936/42525 [22:53<40:32, 11.34it/s]

 35%|████████████▋                       | 14940/42525 [22:54<41:08, 11.17it/s]

 35%|████████████▋                       | 14942/42525 [22:54<40:43, 11.29it/s]

 35%|████████████▋                       | 14946/42525 [22:54<41:56, 10.96it/s]

 35%|████████████▋                       | 14950/42525 [22:55<40:32, 11.34it/s]

 35%|████████████▋                       | 14954/42525 [22:55<40:25, 11.37it/s]

 35%|████████████▋                       | 14958/42525 [22:55<40:45, 11.27it/s]

 35%|████████████▋                       | 14962/42525 [22:56<42:33, 10.79it/s]

 35%|████████████▋                       | 14966/42525 [22:56<42:57, 10.69it/s]

 35%|████████████▋                       | 14970/42525 [22:57<42:33, 10.79it/s]

 35%|████████████▋                       | 14974/42525 [22:57<41:38, 11.03it/s]

 35%|████████████▋                       | 14978/42525 [22:57<42:07, 10.90it/s]

 35%|████████████▋                       | 14982/42525 [22:58<40:54, 11.22it/s]

 35%|████████████▋                       | 14986/42525 [22:58<40:25, 11.35it/s]

 35%|████████████▋                       | 14990/42525 [22:58<39:55, 11.49it/s]

 35%|████████████▋                       | 14994/42525 [22:59<40:20, 11.38it/s]

 35%|████████████▋                       | 14998/42525 [22:59<42:24, 10.82it/s]

 35%|████████████▋                       | 15002/42525 [22:59<40:53, 11.22it/s]

 35%|████████████▋                       | 15004/42525 [23:00<40:15, 11.39it/s]

 35%|████████████▋                       | 15008/42525 [23:00<41:10, 11.14it/s]

 35%|████████████▋                       | 15012/42525 [23:00<40:47, 11.24it/s]

 35%|████████████▋                       | 15016/42525 [23:01<42:07, 10.88it/s]

 35%|████████████▋                       | 15020/42525 [23:01<40:23, 11.35it/s]

 35%|████████████▋                       | 15024/42525 [23:01<39:35, 11.57it/s]

 35%|████████████▋                       | 15028/42525 [23:02<39:20, 11.65it/s]

 35%|████████████▋                       | 15032/42525 [23:02<39:05, 11.72it/s]

 35%|████████████▋                       | 15036/42525 [23:02<40:47, 11.23it/s]

 35%|████████████▋                       | 15040/42525 [23:03<39:46, 11.52it/s]

 35%|████████████▋                       | 15044/42525 [23:03<39:26, 11.61it/s]

 35%|████████████▋                       | 15048/42525 [23:03<39:05, 11.71it/s]

 35%|████████████▋                       | 15052/42525 [23:04<40:36, 11.28it/s]

 35%|████████████▋                       | 15056/42525 [23:04<40:34, 11.28it/s]

 35%|████████████▋                       | 15060/42525 [23:05<42:29, 10.77it/s]

 35%|████████████▊                       | 15064/42525 [23:05<42:21, 10.81it/s]

 35%|████████████▊                       | 15068/42525 [23:05<40:35, 11.28it/s]

 35%|████████████▊                       | 15072/42525 [23:06<40:11, 11.39it/s]

 35%|████████████▊                       | 15076/42525 [23:06<40:00, 11.44it/s]

 35%|████████████▊                       | 15080/42525 [23:06<40:00, 11.43it/s]

 35%|████████████▊                       | 15084/42525 [23:07<39:34, 11.55it/s]

 35%|████████████▊                       | 15088/42525 [23:07<41:40, 10.97it/s]

 35%|████████████▊                       | 15092/42525 [23:07<40:03, 11.42it/s]

 35%|████████████▊                       | 15096/42525 [23:08<40:06, 11.40it/s]

 36%|████████████▊                       | 15100/42525 [23:08<39:22, 11.61it/s]

 36%|████████████▊                       | 15104/42525 [23:08<40:36, 11.25it/s]

 36%|████████████▊                       | 15108/42525 [23:09<42:19, 10.80it/s]

 36%|████████████▊                       | 15112/42525 [23:09<41:24, 11.04it/s]

 36%|████████████▊                       | 15116/42525 [23:10<42:46, 10.68it/s]

 36%|████████████▊                       | 15120/42525 [23:10<41:30, 11.00it/s]

 36%|████████████▊                       | 15124/42525 [23:10<41:26, 11.02it/s]

 36%|████████████▊                       | 15128/42525 [23:11<41:13, 11.07it/s]

 36%|████████████▊                       | 15132/42525 [23:11<39:56, 11.43it/s]

 36%|████████████▊                       | 15136/42525 [23:11<39:13, 11.64it/s]

 36%|████████████▊                       | 15140/42525 [23:12<40:24, 11.29it/s]

 36%|████████████▊                       | 15144/42525 [23:12<40:49, 11.18it/s]

 36%|████████████▊                       | 15148/42525 [23:12<39:22, 11.59it/s]

 36%|████████████▊                       | 15152/42525 [23:13<40:53, 11.16it/s]

 36%|████████████▊                       | 15156/42525 [23:13<41:44, 10.93it/s]

 36%|████████████▊                       | 15160/42525 [23:13<40:49, 11.17it/s]

 36%|████████████▊                       | 15164/42525 [23:14<41:10, 11.08it/s]

 36%|████████████▊                       | 15168/42525 [23:14<40:05, 11.37it/s]

 36%|████████████▊                       | 15172/42525 [23:14<40:53, 11.15it/s]

 36%|████████████▊                       | 15176/42525 [23:15<39:50, 11.44it/s]

 36%|████████████▊                       | 15180/42525 [23:15<40:17, 11.31it/s]

 36%|████████████▊                       | 15182/42525 [23:15<39:58, 11.40it/s]

 36%|████████████▊                       | 15186/42525 [23:16<40:52, 11.15it/s]

 36%|████████████▊                       | 15190/42525 [23:16<39:54, 11.42it/s]

 36%|████████████▊                       | 15194/42525 [23:16<40:21, 11.29it/s]

 36%|████████████▊                       | 15198/42525 [23:17<39:28, 11.54it/s]

 36%|████████████▊                       | 15202/42525 [23:17<39:05, 11.65it/s]

 36%|████████████▊                       | 15206/42525 [23:17<38:59, 11.68it/s]

 36%|████████████▉                       | 15210/42525 [23:18<39:28, 11.53it/s]

 36%|████████████▉                       | 15214/42525 [23:18<39:16, 11.59it/s]

 36%|████████████▉                       | 15218/42525 [23:19<39:51, 11.42it/s]

 36%|████████████▉                       | 15222/42525 [23:19<39:43, 11.46it/s]

 36%|████████████▉                       | 15226/42525 [23:19<40:31, 11.23it/s]

 36%|████████████▉                       | 15230/42525 [23:20<41:27, 10.97it/s]

 36%|████████████▉                       | 15234/42525 [23:20<39:55, 11.39it/s]

 36%|████████████▉                       | 15238/42525 [23:20<39:06, 11.63it/s]

 36%|████████████▉                       | 15242/42525 [23:21<39:32, 11.50it/s]

 36%|████████████▉                       | 15244/42525 [23:21<39:14, 11.59it/s]

 36%|████████████▉                       | 15248/42525 [23:21<43:22, 10.48it/s]

 36%|████████████▉                       | 15252/42525 [23:22<42:01, 10.82it/s]

 36%|████████████▉                       | 15256/42525 [23:22<41:14, 11.02it/s]

 36%|████████████▉                       | 15258/42525 [23:22<41:27, 10.96it/s]

 36%|████████████▉                       | 15262/42525 [23:23<42:49, 10.61it/s]

 36%|████████████▉                       | 15266/42525 [23:23<41:28, 10.95it/s]

 36%|████████████▉                       | 15268/42525 [23:23<42:12, 10.76it/s]

 36%|████████████▉                       | 15272/42525 [23:23<42:02, 10.80it/s]

 36%|████████████▉                       | 15276/42525 [23:24<41:13, 11.02it/s]

 36%|████████████▉                       | 15280/42525 [23:24<39:51, 11.39it/s]

 36%|████████████▉                       | 15284/42525 [23:25<40:24, 11.24it/s]

 36%|████████████▉                       | 15288/42525 [23:25<41:27, 10.95it/s]

 36%|████████████▉                       | 15290/42525 [23:25<40:46, 11.13it/s]

 36%|████████████▉                       | 15292/42525 [23:25<43:18, 10.48it/s]

 36%|████████████▉                       | 15296/42525 [23:26<42:52, 10.59it/s]

 36%|████████████▉                       | 15300/42525 [23:26<41:43, 10.87it/s]

 36%|████████████▉                       | 15304/42525 [23:26<41:44, 10.87it/s]

 36%|████████████▉                       | 15308/42525 [23:27<40:05, 11.31it/s]

 36%|████████████▉                       | 15312/42525 [23:27<39:34, 11.46it/s]

 36%|████████████▉                       | 15316/42525 [23:27<39:31, 11.48it/s]

 36%|████████████▉                       | 15320/42525 [23:28<40:19, 11.24it/s]

 36%|████████████▉                       | 15324/42525 [23:28<39:28, 11.48it/s]

 36%|████████████▉                       | 15328/42525 [23:28<39:38, 11.44it/s]

 36%|████████████▉                       | 15332/42525 [23:29<40:53, 11.08it/s]

 36%|████████████▉                       | 15336/42525 [23:29<41:11, 11.00it/s]

 36%|████████████▉                       | 15340/42525 [23:30<43:29, 10.42it/s]

 36%|████████████▉                       | 15344/42525 [23:30<41:30, 10.92it/s]

 36%|████████████▉                       | 15348/42525 [23:30<41:03, 11.03it/s]

 36%|████████████▉                       | 15352/42525 [23:31<41:14, 10.98it/s]

 36%|████████████▉                       | 15356/42525 [23:31<42:16, 10.71it/s]

 36%|█████████████                       | 15360/42525 [23:31<40:24, 11.20it/s]

 36%|█████████████                       | 15364/42525 [23:32<39:22, 11.49it/s]

 36%|█████████████                       | 15368/42525 [23:32<38:47, 11.67it/s]

 36%|█████████████                       | 15372/42525 [23:32<39:24, 11.48it/s]

 36%|█████████████                       | 15376/42525 [23:33<40:10, 11.26it/s]

 36%|█████████████                       | 15380/42525 [23:33<40:21, 11.21it/s]

 36%|█████████████                       | 15384/42525 [23:33<39:26, 11.47it/s]

 36%|█████████████                       | 15388/42525 [23:34<41:18, 10.95it/s]

 36%|█████████████                       | 15392/42525 [23:34<40:30, 11.16it/s]

 36%|█████████████                       | 15396/42525 [23:35<41:04, 11.01it/s]

 36%|█████████████                       | 15400/42525 [23:35<39:35, 11.42it/s]

 36%|█████████████                       | 15404/42525 [23:35<38:37, 11.70it/s]

 36%|█████████████                       | 15408/42525 [23:36<38:51, 11.63it/s]

 36%|█████████████                       | 15412/42525 [23:36<39:34, 11.42it/s]

 36%|█████████████                       | 15416/42525 [23:36<40:00, 11.29it/s]

 36%|█████████████                       | 15420/42525 [23:37<41:31, 10.88it/s]

 36%|█████████████                       | 15424/42525 [23:37<42:05, 10.73it/s]

 36%|█████████████                       | 15428/42525 [23:37<41:02, 11.00it/s]

 36%|█████████████                       | 15432/42525 [23:38<41:40, 10.83it/s]

 36%|█████████████                       | 15436/42525 [23:38<40:25, 11.17it/s]

 36%|█████████████                       | 15440/42525 [23:39<39:17, 11.49it/s]

 36%|█████████████                       | 15444/42525 [23:39<40:12, 11.23it/s]

 36%|█████████████                       | 15448/42525 [23:39<39:15, 11.50it/s]

 36%|█████████████                       | 15452/42525 [23:40<38:33, 11.70it/s]

 36%|█████████████                       | 15456/42525 [23:40<40:03, 11.26it/s]

 36%|█████████████                       | 15460/42525 [23:40<39:19, 11.47it/s]

 36%|█████████████                       | 15464/42525 [23:41<39:11, 11.51it/s]

 36%|█████████████                       | 15468/42525 [23:41<38:39, 11.66it/s]

 36%|█████████████                       | 15472/42525 [23:41<38:32, 11.70it/s]

 36%|█████████████                       | 15476/42525 [23:42<38:22, 11.75it/s]

 36%|█████████████                       | 15480/42525 [23:42<38:28, 11.71it/s]

 36%|█████████████                       | 15484/42525 [23:42<39:00, 11.55it/s]

 36%|█████████████                       | 15488/42525 [23:43<38:38, 11.66it/s]

 36%|█████████████                       | 15492/42525 [23:43<39:09, 11.51it/s]

 36%|█████████████                       | 15496/42525 [23:43<38:43, 11.63it/s]

 36%|█████████████                       | 15500/42525 [23:44<39:50, 11.31it/s]

 36%|█████████████▏                      | 15504/42525 [23:44<40:42, 11.06it/s]

 36%|█████████████▏                      | 15508/42525 [23:44<39:34, 11.38it/s]

 36%|█████████████▏                      | 15512/42525 [23:45<39:40, 11.35it/s]

 36%|█████████████▏                      | 15516/42525 [23:45<41:16, 10.91it/s]

 36%|█████████████▏                      | 15520/42525 [23:46<41:26, 10.86it/s]

 37%|█████████████▏                      | 15524/42525 [23:46<42:57, 10.47it/s]

 37%|█████████████▏                      | 15528/42525 [23:46<40:32, 11.10it/s]

 37%|█████████████▏                      | 15532/42525 [23:47<41:33, 10.83it/s]

 37%|█████████████▏                      | 15536/42525 [23:47<41:08, 10.93it/s]

 37%|█████████████▏                      | 15540/42525 [23:47<41:48, 10.76it/s]

 37%|█████████████▏                      | 15544/42525 [23:48<40:00, 11.24it/s]

 37%|█████████████▏                      | 15548/42525 [23:48<40:35, 11.07it/s]

 37%|█████████████▏                      | 15552/42525 [23:48<41:55, 10.72it/s]

 37%|█████████████▏                      | 15556/42525 [23:49<42:03, 10.69it/s]

 37%|█████████████▏                      | 15560/42525 [23:49<40:45, 11.02it/s]

 37%|█████████████▏                      | 15564/42525 [23:50<39:56, 11.25it/s]

 37%|█████████████▏                      | 15568/42525 [23:50<40:53, 10.99it/s]

 37%|█████████████▏                      | 15572/42525 [23:50<39:15, 11.44it/s]

 37%|█████████████▏                      | 15576/42525 [23:51<38:34, 11.64it/s]

 37%|█████████████▏                      | 15580/42525 [23:51<39:11, 11.46it/s]

 37%|█████████████▏                      | 15584/42525 [23:51<38:37, 11.63it/s]

 37%|█████████████▏                      | 15588/42525 [23:52<38:21, 11.70it/s]

 37%|█████████████▏                      | 15592/42525 [23:52<38:28, 11.67it/s]

 37%|█████████████▏                      | 15596/42525 [23:52<40:08, 11.18it/s]

 37%|█████████████▏                      | 15600/42525 [23:53<40:07, 11.18it/s]

 37%|█████████████▏                      | 15604/42525 [23:53<39:36, 11.33it/s]

 37%|█████████████▏                      | 15608/42525 [23:53<39:42, 11.30it/s]

 37%|█████████████▏                      | 15612/42525 [23:54<38:55, 11.52it/s]

 37%|█████████████▏                      | 15616/42525 [23:54<38:30, 11.65it/s]

 37%|█████████████▏                      | 15620/42525 [23:54<39:15, 11.42it/s]

 37%|█████████████▏                      | 15624/42525 [23:55<40:54, 10.96it/s]

 37%|█████████████▏                      | 15628/42525 [23:55<39:23, 11.38it/s]

 37%|█████████████▏                      | 15632/42525 [23:56<38:04, 11.77it/s]

 37%|█████████████▏                      | 15636/42525 [23:56<38:43, 11.57it/s]

 37%|█████████████▏                      | 15640/42525 [23:56<38:52, 11.53it/s]

 37%|█████████████▏                      | 15642/42525 [23:56<39:57, 11.21it/s]

 37%|█████████████▏                      | 15646/42525 [23:57<41:48, 10.71it/s]

 37%|█████████████▏                      | 15650/42525 [23:57<42:12, 10.61it/s]

 37%|█████████████▎                      | 15654/42525 [23:58<40:05, 11.17it/s]

 37%|█████████████▎                      | 15658/42525 [23:58<40:20, 11.10it/s]

 37%|█████████████▎                      | 15662/42525 [23:58<39:51, 11.23it/s]

 37%|█████████████▎                      | 15666/42525 [23:59<40:51, 10.96it/s]

 37%|█████████████▎                      | 15670/42525 [23:59<39:33, 11.32it/s]

 37%|█████████████▎                      | 15674/42525 [23:59<39:41, 11.28it/s]

 37%|█████████████▎                      | 15678/42525 [24:00<39:39, 11.28it/s]

 37%|█████████████▎                      | 15682/42525 [24:00<39:12, 11.41it/s]

 37%|█████████████▎                      | 15686/42525 [24:00<39:34, 11.30it/s]

 37%|█████████████▎                      | 15690/42525 [24:01<38:42, 11.55it/s]

 37%|█████████████▎                      | 15694/42525 [24:01<39:33, 11.31it/s]

 37%|█████████████▎                      | 15698/42525 [24:01<39:24, 11.35it/s]

 37%|█████████████▎                      | 15702/42525 [24:02<38:40, 11.56it/s]

 37%|█████████████▎                      | 15706/42525 [24:02<40:05, 11.15it/s]

 37%|█████████████▎                      | 15710/42525 [24:02<39:03, 11.44it/s]

 37%|█████████████▎                      | 15714/42525 [24:03<39:35, 11.29it/s]

 37%|█████████████▎                      | 15718/42525 [24:03<40:42, 10.98it/s]

 37%|█████████████▎                      | 15722/42525 [24:04<40:52, 10.93it/s]

 37%|█████████████▎                      | 15726/42525 [24:04<39:17, 11.37it/s]

 37%|█████████████▎                      | 15730/42525 [24:04<40:14, 11.10it/s]

 37%|█████████████▎                      | 15734/42525 [24:05<39:53, 11.19it/s]

 37%|█████████████▎                      | 15738/42525 [24:05<41:10, 10.84it/s]

 37%|█████████████▎                      | 15742/42525 [24:05<40:03, 11.14it/s]

 37%|█████████████▎                      | 15746/42525 [24:06<39:39, 11.26it/s]

 37%|█████████████▎                      | 15750/42525 [24:06<38:07, 11.70it/s]

 37%|█████████████▎                      | 15754/42525 [24:06<40:03, 11.14it/s]

 37%|█████████████▎                      | 15758/42525 [24:07<38:40, 11.54it/s]

 37%|█████████████▎                      | 15762/42525 [24:07<39:18, 11.35it/s]

 37%|█████████████▎                      | 15766/42525 [24:07<38:55, 11.46it/s]

 37%|█████████████▎                      | 15770/42525 [24:08<39:34, 11.27it/s]

 37%|█████████████▎                      | 15774/42525 [24:08<40:18, 11.06it/s]

 37%|█████████████▎                      | 15778/42525 [24:09<39:14, 11.36it/s]

 37%|█████████████▎                      | 15782/42525 [24:09<39:14, 11.36it/s]

 37%|█████████████▎                      | 15786/42525 [24:09<40:16, 11.07it/s]

 37%|█████████████▎                      | 15790/42525 [24:10<40:00, 11.14it/s]

 37%|█████████████▎                      | 15794/42525 [24:10<37:10, 11.98it/s]

 37%|█████████████▎                      | 15798/42525 [24:10<38:53, 11.46it/s]

 37%|█████████████▍                      | 15802/42525 [24:11<38:03, 11.70it/s]

 37%|█████████████▍                      | 15806/42525 [24:11<35:45, 12.46it/s]

 37%|█████████████▍                      | 15810/42525 [24:11<35:43, 12.46it/s]

 37%|█████████████▍                      | 15814/42525 [24:12<36:46, 12.10it/s]

 37%|█████████████▍                      | 15818/42525 [24:12<38:28, 11.57it/s]

 37%|█████████████▍                      | 15822/42525 [24:12<38:07, 11.67it/s]

 37%|█████████████▍                      | 15826/42525 [24:13<38:34, 11.53it/s]

 37%|█████████████▍                      | 15830/42525 [24:13<39:32, 11.25it/s]

 37%|█████████████▍                      | 15834/42525 [24:13<39:33, 11.24it/s]

 37%|█████████████▍                      | 15838/42525 [24:14<39:12, 11.34it/s]

 37%|█████████████▍                      | 15840/42525 [24:14<38:48, 11.46it/s]

 37%|█████████████▍                      | 15844/42525 [24:14<41:33, 10.70it/s]

 37%|█████████████▍                      | 15848/42525 [24:15<40:46, 10.91it/s]

 37%|█████████████▍                      | 15852/42525 [24:15<39:25, 11.28it/s]

 37%|█████████████▍                      | 15856/42525 [24:15<38:40, 11.49it/s]

 37%|█████████████▍                      | 15860/42525 [24:16<38:47, 11.46it/s]

 37%|█████████████▍                      | 15864/42525 [24:16<39:33, 11.23it/s]

 37%|█████████████▍                      | 15868/42525 [24:16<39:18, 11.30it/s]

 37%|█████████████▍                      | 15872/42525 [24:17<40:42, 10.91it/s]

 37%|█████████████▍                      | 15876/42525 [24:17<40:36, 10.94it/s]

 37%|█████████████▍                      | 15880/42525 [24:17<40:06, 11.07it/s]

 37%|█████████████▍                      | 15884/42525 [24:18<38:58, 11.39it/s]

 37%|█████████████▍                      | 15888/42525 [24:18<39:46, 11.16it/s]

 37%|█████████████▍                      | 15892/42525 [24:19<40:15, 11.03it/s]

 37%|█████████████▍                      | 15896/42525 [24:19<39:57, 11.11it/s]

 37%|█████████████▍                      | 15900/42525 [24:19<38:35, 11.50it/s]

 37%|█████████████▍                      | 15904/42525 [24:20<39:06, 11.35it/s]

 37%|█████████████▍                      | 15908/42525 [24:20<39:19, 11.28it/s]

 37%|█████████████▍                      | 15910/42525 [24:20<38:38, 11.48it/s]

 37%|█████████████▍                      | 15914/42525 [24:21<39:39, 11.18it/s]

 37%|█████████████▍                      | 15918/42525 [24:21<39:51, 11.13it/s]

 37%|█████████████▍                      | 15922/42525 [24:21<38:30, 11.51it/s]

 37%|█████████████▍                      | 15926/42525 [24:22<38:00, 11.66it/s]

 37%|█████████████▍                      | 15930/42525 [24:22<40:02, 11.07it/s]

 37%|█████████████▍                      | 15934/42525 [24:22<40:52, 10.84it/s]

 37%|█████████████▍                      | 15938/42525 [24:23<40:52, 10.84it/s]

 37%|█████████████▍                      | 15942/42525 [24:23<40:09, 11.03it/s]

 37%|█████████████▍                      | 15946/42525 [24:23<39:47, 11.13it/s]

 38%|█████████████▌                      | 15950/42525 [24:24<40:09, 11.03it/s]

 38%|█████████████▌                      | 15954/42525 [24:24<38:35, 11.48it/s]

 38%|█████████████▌                      | 15958/42525 [24:24<38:23, 11.54it/s]

 38%|█████████████▌                      | 15962/42525 [24:25<40:33, 10.92it/s]

 38%|█████████████▌                      | 15966/42525 [24:25<39:18, 11.26it/s]

 38%|█████████████▌                      | 15970/42525 [24:25<37:47, 11.71it/s]

 38%|█████████████▌                      | 15974/42525 [24:26<38:58, 11.36it/s]

 38%|█████████████▌                      | 15978/42525 [24:26<38:27, 11.51it/s]

 38%|█████████████▌                      | 15982/42525 [24:27<39:23, 11.23it/s]

 38%|█████████████▌                      | 15986/42525 [24:27<39:58, 11.06it/s]

 38%|█████████████▌                      | 15990/42525 [24:27<40:55, 10.81it/s]

 38%|█████████████▌                      | 15994/42525 [24:28<40:06, 11.03it/s]

 38%|█████████████▌                      | 15998/42525 [24:28<38:46, 11.40it/s]

 38%|█████████████▌                      | 16002/42525 [24:28<38:15, 11.55it/s]

 38%|█████████████▌                      | 16006/42525 [24:29<37:46, 11.70it/s]

 38%|█████████████▌                      | 16010/42525 [24:29<37:37, 11.75it/s]

 38%|█████████████▌                      | 16014/42525 [24:29<37:34, 11.76it/s]

 38%|█████████████▌                      | 16016/42525 [24:30<39:20, 11.23it/s]

 38%|█████████████▌                      | 16020/42525 [24:30<40:43, 10.85it/s]

 38%|█████████████▌                      | 16024/42525 [24:30<39:30, 11.18it/s]

 38%|█████████████▌                      | 16026/42525 [24:30<40:29, 10.91it/s]

 38%|█████████████▌                      | 16030/42525 [24:31<41:23, 10.67it/s]

 38%|█████████████▌                      | 16034/42525 [24:31<41:21, 10.68it/s]

 38%|█████████████▌                      | 16038/42525 [24:32<39:34, 11.16it/s]

 38%|█████████████▌                      | 16040/42525 [24:32<40:21, 10.94it/s]

 38%|█████████████▌                      | 16044/42525 [24:32<40:18, 10.95it/s]

 38%|█████████████▌                      | 16048/42525 [24:33<40:32, 10.88it/s]

 38%|█████████████▌                      | 16052/42525 [24:33<40:32, 10.88it/s]

 38%|█████████████▌                      | 16056/42525 [24:33<41:33, 10.62it/s]

 38%|█████████████▌                      | 16060/42525 [24:34<39:28, 11.17it/s]

 38%|█████████████▌                      | 16064/42525 [24:34<39:59, 11.03it/s]

 38%|█████████████▌                      | 16068/42525 [24:34<40:22, 10.92it/s]

 38%|█████████████▌                      | 16072/42525 [24:35<38:50, 11.35it/s]

 38%|█████████████▌                      | 16076/42525 [24:35<39:07, 11.27it/s]

 38%|█████████████▌                      | 16080/42525 [24:35<39:38, 11.12it/s]

 38%|█████████████▌                      | 16084/42525 [24:36<38:21, 11.49it/s]

 38%|█████████████▌                      | 16088/42525 [24:36<37:45, 11.67it/s]

 38%|█████████████▌                      | 16092/42525 [24:36<37:37, 11.71it/s]

 38%|█████████████▋                      | 16096/42525 [24:37<37:53, 11.63it/s]

 38%|█████████████▋                      | 16100/42525 [24:37<37:22, 11.78it/s]

 38%|█████████████▋                      | 16104/42525 [24:37<36:52, 11.94it/s]

 38%|█████████████▋                      | 16108/42525 [24:38<39:10, 11.24it/s]

 38%|█████████████▋                      | 16112/42525 [24:38<38:38, 11.39it/s]

 38%|█████████████▋                      | 16116/42525 [24:39<38:17, 11.50it/s]

 38%|█████████████▋                      | 16120/42525 [24:39<37:51, 11.62it/s]

 38%|█████████████▋                      | 16124/42525 [24:39<38:30, 11.43it/s]

 38%|█████████████▋                      | 16128/42525 [24:40<38:47, 11.34it/s]

 38%|█████████████▋                      | 16132/42525 [24:40<39:04, 11.26it/s]

 38%|█████████████▋                      | 16136/42525 [24:40<39:13, 11.21it/s]

 38%|█████████████▋                      | 16140/42525 [24:41<37:01, 11.87it/s]

 38%|█████████████▋                      | 16144/42525 [24:41<35:51, 12.26it/s]

 38%|█████████████▋                      | 16148/42525 [24:41<39:03, 11.26it/s]

 38%|█████████████▋                      | 16150/42525 [24:41<38:17, 11.48it/s]

 38%|█████████████▋                      | 16154/42525 [24:42<38:55, 11.29it/s]

 38%|█████████████▋                      | 16158/42525 [24:42<37:39, 11.67it/s]

 38%|█████████████▋                      | 16162/42525 [24:43<39:03, 11.25it/s]

 38%|█████████████▋                      | 16166/42525 [24:43<38:03, 11.54it/s]

 38%|█████████████▋                      | 16170/42525 [24:43<36:14, 12.12it/s]

 38%|█████████████▋                      | 16174/42525 [24:44<34:46, 12.63it/s]

 38%|█████████████▋                      | 16178/42525 [24:44<36:22, 12.07it/s]

 38%|█████████████▋                      | 16182/42525 [24:44<34:50, 12.60it/s]

 38%|█████████████▋                      | 16186/42525 [24:44<36:02, 12.18it/s]

 38%|█████████████▋                      | 16190/42525 [24:45<35:49, 12.25it/s]

 38%|█████████████▋                      | 16194/42525 [24:45<37:11, 11.80it/s]

 38%|█████████████▋                      | 16198/42525 [24:45<37:03, 11.84it/s]

 38%|█████████████▋                      | 16202/42525 [24:46<36:03, 12.17it/s]

 38%|█████████████▋                      | 16206/42525 [24:46<36:47, 11.92it/s]

 38%|█████████████▋                      | 16210/42525 [24:46<36:52, 11.89it/s]

 38%|█████████████▋                      | 16214/42525 [24:47<38:04, 11.52it/s]

 38%|█████████████▋                      | 16218/42525 [24:47<37:34, 11.67it/s]

 38%|█████████████▋                      | 16222/42525 [24:48<37:55, 11.56it/s]

 38%|█████████████▋                      | 16226/42525 [24:48<39:32, 11.08it/s]

 38%|█████████████▋                      | 16230/42525 [24:48<39:57, 10.97it/s]

 38%|█████████████▋                      | 16234/42525 [24:49<38:37, 11.34it/s]

 38%|█████████████▋                      | 16238/42525 [24:49<37:53, 11.56it/s]

 38%|█████████████▋                      | 16240/42525 [24:49<38:32, 11.37it/s]

 38%|█████████████▋                      | 16242/42525 [24:49<40:50, 10.73it/s]

 38%|█████████████▊                      | 16246/42525 [24:50<41:02, 10.67it/s]

 38%|█████████████▊                      | 16250/42525 [24:50<39:52, 10.98it/s]

 38%|█████████████▊                      | 16254/42525 [24:50<39:05, 11.20it/s]

 38%|█████████████▊                      | 16258/42525 [24:51<39:50, 10.99it/s]

 38%|█████████████▊                      | 16262/42525 [24:51<39:43, 11.02it/s]

 38%|█████████████▊                      | 16266/42525 [24:52<38:19, 11.42it/s]

 38%|█████████████▊                      | 16270/42525 [24:52<37:42, 11.61it/s]

 38%|█████████████▊                      | 16274/42525 [24:52<37:14, 11.75it/s]

 38%|█████████████▊                      | 16278/42525 [24:53<39:38, 11.03it/s]

 38%|█████████████▊                      | 16282/42525 [24:53<39:28, 11.08it/s]

 38%|█████████████▊                      | 16286/42525 [24:53<39:22, 11.11it/s]

 38%|█████████████▊                      | 16290/42525 [24:54<39:46, 10.99it/s]

 38%|█████████████▊                      | 16294/42525 [24:54<40:15, 10.86it/s]

 38%|█████████████▊                      | 16298/42525 [24:54<39:49, 10.98it/s]

 38%|█████████████▊                      | 16302/42525 [24:55<39:55, 10.94it/s]

 38%|█████████████▊                      | 16306/42525 [24:55<39:55, 10.94it/s]

 38%|█████████████▊                      | 16310/42525 [24:55<38:20, 11.39it/s]

 38%|█████████████▊                      | 16314/42525 [24:56<39:03, 11.18it/s]

 38%|█████████████▊                      | 16318/42525 [24:56<39:01, 11.19it/s]

 38%|█████████████▊                      | 16322/42525 [24:57<38:03, 11.48it/s]

 38%|█████████████▊                      | 16326/42525 [24:57<37:39, 11.60it/s]

 38%|█████████████▊                      | 16330/42525 [24:57<38:38, 11.30it/s]

 38%|█████████████▊                      | 16334/42525 [24:58<41:28, 10.53it/s]

 38%|█████████████▊                      | 16338/42525 [24:58<40:21, 10.81it/s]

 38%|█████████████▊                      | 16342/42525 [24:58<40:48, 10.69it/s]

 38%|█████████████▊                      | 16346/42525 [24:59<39:27, 11.06it/s]

 38%|█████████████▊                      | 16350/42525 [24:59<40:43, 10.71it/s]

 38%|█████████████▊                      | 16354/42525 [25:00<40:16, 10.83it/s]

 38%|█████████████▊                      | 16358/42525 [25:00<40:16, 10.83it/s]

 38%|█████████████▊                      | 16362/42525 [25:00<39:19, 11.09it/s]

 38%|█████████████▊                      | 16366/42525 [25:01<38:30, 11.32it/s]

 38%|█████████████▊                      | 16370/42525 [25:01<37:57, 11.49it/s]

 39%|█████████████▊                      | 16374/42525 [25:01<39:11, 11.12it/s]

 39%|█████████████▊                      | 16378/42525 [25:02<39:02, 11.16it/s]

 39%|█████████████▊                      | 16382/42525 [25:02<38:05, 11.44it/s]

 39%|█████████████▊                      | 16386/42525 [25:02<37:36, 11.58it/s]

 39%|█████████████▉                      | 16390/42525 [25:03<37:27, 11.63it/s]

 39%|█████████████▉                      | 16394/42525 [25:03<37:12, 11.70it/s]

 39%|█████████████▉                      | 16398/42525 [25:03<38:04, 11.44it/s]

 39%|█████████████▉                      | 16402/42525 [25:04<39:15, 11.09it/s]

 39%|█████████████▉                      | 16406/42525 [25:04<38:08, 11.41it/s]

 39%|█████████████▉                      | 16410/42525 [25:04<38:56, 11.18it/s]

 39%|█████████████▉                      | 16414/42525 [25:05<39:05, 11.13it/s]

 39%|█████████████▉                      | 16418/42525 [25:05<39:01, 11.15it/s]

 39%|█████████████▉                      | 16422/42525 [25:06<41:09, 10.57it/s]

 39%|█████████████▉                      | 16426/42525 [25:06<39:08, 11.11it/s]

 39%|█████████████▉                      | 16430/42525 [25:06<39:44, 10.94it/s]

 39%|█████████████▉                      | 16434/42525 [25:07<39:54, 10.89it/s]

 39%|█████████████▉                      | 16438/42525 [25:07<38:27, 11.31it/s]

 39%|█████████████▉                      | 16442/42525 [25:07<37:35, 11.56it/s]

 39%|█████████████▉                      | 16446/42525 [25:08<37:53, 11.47it/s]

 39%|█████████████▉                      | 16450/42525 [25:08<37:43, 11.52it/s]

 39%|█████████████▉                      | 16454/42525 [25:08<38:16, 11.35it/s]

 39%|█████████████▉                      | 16458/42525 [25:09<39:42, 10.94it/s]

 39%|█████████████▉                      | 16462/42525 [25:09<38:42, 11.22it/s]

 39%|█████████████▉                      | 16466/42525 [25:09<38:22, 11.32it/s]

 39%|█████████████▉                      | 16470/42525 [25:10<39:44, 10.93it/s]

 39%|█████████████▉                      | 16474/42525 [25:10<38:07, 11.39it/s]

 39%|█████████████▉                      | 16478/42525 [25:11<38:32, 11.26it/s]

 39%|█████████████▉                      | 16482/42525 [25:11<38:44, 11.20it/s]

 39%|█████████████▉                      | 16486/42525 [25:11<39:16, 11.05it/s]

 39%|█████████████▉                      | 16490/42525 [25:12<38:10, 11.37it/s]

 39%|█████████████▉                      | 16494/42525 [25:12<38:50, 11.17it/s]

 39%|█████████████▉                      | 16498/42525 [25:12<38:14, 11.34it/s]

 39%|█████████████▉                      | 16502/42525 [25:13<38:34, 11.24it/s]

 39%|█████████████▉                      | 16504/42525 [25:13<38:07, 11.37it/s]

 39%|█████████████▉                      | 16508/42525 [25:13<39:25, 11.00it/s]

 39%|█████████████▉                      | 16512/42525 [25:14<39:19, 11.03it/s]

 39%|█████████████▉                      | 16516/42525 [25:14<38:06, 11.37it/s]

 39%|█████████████▉                      | 16520/42525 [25:14<37:53, 11.44it/s]

 39%|█████████████▉                      | 16524/42525 [25:15<39:02, 11.10it/s]

 39%|█████████████▉                      | 16528/42525 [25:15<39:13, 11.05it/s]

 39%|█████████████▉                      | 16532/42525 [25:15<38:02, 11.39it/s]

 39%|█████████████▉                      | 16536/42525 [25:16<37:25, 11.58it/s]

 39%|██████████████                      | 16540/42525 [25:16<39:38, 10.92it/s]

 39%|██████████████                      | 16544/42525 [25:16<39:35, 10.94it/s]

 39%|██████████████                      | 16548/42525 [25:17<38:39, 11.20it/s]

 39%|██████████████                      | 16552/42525 [25:17<37:43, 11.47it/s]

 39%|██████████████                      | 16556/42525 [25:18<38:27, 11.26it/s]

 39%|██████████████                      | 16560/42525 [25:18<38:05, 11.36it/s]

 39%|██████████████                      | 16564/42525 [25:18<39:22, 10.99it/s]

 39%|██████████████                      | 16568/42525 [25:19<38:14, 11.31it/s]

 39%|██████████████                      | 16570/42525 [25:19<38:33, 11.22it/s]

 39%|██████████████                      | 16574/42525 [25:19<41:23, 10.45it/s]

 39%|██████████████                      | 16578/42525 [25:20<41:30, 10.42it/s]

 39%|██████████████                      | 16582/42525 [25:20<40:25, 10.70it/s]

 39%|██████████████                      | 16586/42525 [25:20<39:09, 11.04it/s]

 39%|██████████████                      | 16590/42525 [25:21<39:37, 10.91it/s]

 39%|██████████████                      | 16594/42525 [25:21<39:43, 10.88it/s]

 39%|██████████████                      | 16598/42525 [25:21<38:56, 11.10it/s]

 39%|██████████████                      | 16602/42525 [25:22<37:46, 11.44it/s]

 39%|██████████████                      | 16606/42525 [25:22<38:41, 11.17it/s]

 39%|██████████████                      | 16610/42525 [25:22<37:55, 11.39it/s]

 39%|██████████████                      | 16614/42525 [25:23<37:07, 11.63it/s]

 39%|██████████████                      | 16618/42525 [25:23<36:22, 11.87it/s]

 39%|██████████████                      | 16622/42525 [25:23<36:08, 11.95it/s]

 39%|██████████████                      | 16626/42525 [25:24<37:17, 11.58it/s]

 39%|██████████████                      | 16630/42525 [25:24<37:36, 11.47it/s]

 39%|██████████████                      | 16634/42525 [25:24<38:19, 11.26it/s]

 39%|██████████████                      | 16638/42525 [25:25<37:36, 11.47it/s]

 39%|██████████████                      | 16642/42525 [25:25<37:07, 11.62it/s]

 39%|██████████████                      | 16646/42525 [25:26<37:52, 11.39it/s]

 39%|██████████████                      | 16650/42525 [25:26<37:35, 11.47it/s]

 39%|██████████████                      | 16654/42525 [25:26<37:09, 11.61it/s]

 39%|██████████████                      | 16658/42525 [25:27<36:50, 11.70it/s]

 39%|██████████████                      | 16662/42525 [25:27<37:12, 11.59it/s]

 39%|██████████████                      | 16666/42525 [25:27<38:11, 11.28it/s]

 39%|██████████████                      | 16670/42525 [25:28<37:59, 11.34it/s]

 39%|██████████████                      | 16674/42525 [25:28<37:08, 11.60it/s]

 39%|██████████████                      | 16678/42525 [25:28<38:56, 11.06it/s]

 39%|██████████████                      | 16682/42525 [25:29<37:55, 11.36it/s]

 39%|██████████████▏                     | 16686/42525 [25:29<37:46, 11.40it/s]

 39%|██████████████▏                     | 16690/42525 [25:29<38:12, 11.27it/s]

 39%|██████████████▏                     | 16694/42525 [25:30<38:12, 11.27it/s]

 39%|██████████████▏                     | 16698/42525 [25:30<37:50, 11.37it/s]

 39%|██████████████▏                     | 16702/42525 [25:30<37:09, 11.58it/s]

 39%|██████████████▏                     | 16706/42525 [25:31<37:27, 11.49it/s]

 39%|██████████████▏                     | 16710/42525 [25:31<38:01, 11.31it/s]

 39%|██████████████▏                     | 16714/42525 [25:32<39:55, 10.78it/s]

 39%|██████████████▏                     | 16718/42525 [25:32<40:07, 10.72it/s]

 39%|██████████████▏                     | 16722/42525 [25:32<38:54, 11.05it/s]

 39%|██████████████▏                     | 16726/42525 [25:33<39:08, 10.99it/s]

 39%|██████████████▏                     | 16730/42525 [25:33<38:03, 11.30it/s]

 39%|██████████████▏                     | 16734/42525 [25:33<38:04, 11.29it/s]

 39%|██████████████▏                     | 16738/42525 [25:34<39:32, 10.87it/s]

 39%|██████████████▏                     | 16742/42525 [25:34<38:03, 11.29it/s]

 39%|██████████████▏                     | 16746/42525 [25:34<38:59, 11.02it/s]

 39%|██████████████▏                     | 16750/42525 [25:35<38:50, 11.06it/s]

 39%|██████████████▏                     | 16752/42525 [25:35<38:10, 11.25it/s]

 39%|██████████████▏                     | 16756/42525 [25:35<39:59, 10.74it/s]

 39%|██████████████▏                     | 16760/42525 [25:36<38:05, 11.27it/s]

 39%|██████████████▏                     | 16764/42525 [25:36<38:15, 11.22it/s]

 39%|██████████████▏                     | 16768/42525 [25:36<37:17, 11.51it/s]

 39%|██████████████▏                     | 16770/42525 [25:37<37:05, 11.57it/s]

 39%|██████████████▏                     | 16774/42525 [25:37<38:27, 11.16it/s]

 39%|██████████████▏                     | 16778/42525 [25:37<38:31, 11.14it/s]

 39%|██████████████▏                     | 16782/42525 [25:38<37:23, 11.47it/s]

 39%|██████████████▏                     | 16784/42525 [25:38<37:13, 11.53it/s]

 39%|██████████████▏                     | 16788/42525 [25:38<38:20, 11.19it/s]

 39%|██████████████▏                     | 16792/42525 [25:39<37:59, 11.29it/s]

 39%|██████████████▏                     | 16796/42525 [25:39<38:37, 11.10it/s]

 40%|██████████████▏                     | 16798/42525 [25:39<38:29, 11.14it/s]

 40%|██████████████▏                     | 16802/42525 [25:39<39:25, 10.88it/s]

 40%|██████████████▏                     | 16806/42525 [25:40<38:53, 11.02it/s]

 40%|██████████████▏                     | 16810/42525 [25:40<38:36, 11.10it/s]

 40%|██████████████▏                     | 16814/42525 [25:40<37:27, 11.44it/s]

 40%|██████████████▏                     | 16818/42525 [25:41<36:37, 11.70it/s]

 40%|██████████████▏                     | 16822/42525 [25:41<37:43, 11.36it/s]

 40%|██████████████▏                     | 16826/42525 [25:42<37:00, 11.57it/s]

 40%|██████████████▏                     | 16830/42525 [25:42<37:27, 11.43it/s]

 40%|██████████████▎                     | 16834/42525 [25:42<38:26, 11.14it/s]

 40%|██████████████▎                     | 16838/42525 [25:43<38:46, 11.04it/s]

 40%|██████████████▎                     | 16842/42525 [25:43<37:32, 11.40it/s]

 40%|██████████████▎                     | 16846/42525 [25:43<37:03, 11.55it/s]

 40%|██████████████▎                     | 16850/42525 [25:44<38:54, 11.00it/s]

 40%|██████████████▎                     | 16854/42525 [25:44<38:24, 11.14it/s]

 40%|██████████████▎                     | 16858/42525 [25:44<37:33, 11.39it/s]

 40%|██████████████▎                     | 16862/42525 [25:45<37:54, 11.28it/s]

 40%|██████████████▎                     | 16866/42525 [25:45<38:40, 11.06it/s]

 40%|██████████████▎                     | 16870/42525 [25:45<38:37, 11.07it/s]

 40%|██████████████▎                     | 16874/42525 [25:46<37:29, 11.40it/s]

 40%|██████████████▎                     | 16878/42525 [25:46<37:52, 11.28it/s]

 40%|██████████████▎                     | 16882/42525 [25:47<38:11, 11.19it/s]

 40%|██████████████▎                     | 16886/42525 [25:47<38:32, 11.09it/s]

 40%|██████████████▎                     | 16890/42525 [25:47<37:12, 11.48it/s]

 40%|██████████████▎                     | 16894/42525 [25:48<38:21, 11.14it/s]

 40%|██████████████▎                     | 16898/42525 [25:48<38:48, 11.00it/s]

 40%|██████████████▎                     | 16902/42525 [25:48<38:22, 11.13it/s]

 40%|██████████████▎                     | 16906/42525 [25:49<37:58, 11.25it/s]

 40%|██████████████▎                     | 16910/42525 [25:49<38:49, 10.99it/s]

 40%|██████████████▎                     | 16914/42525 [25:49<37:31, 11.37it/s]

 40%|██████████████▎                     | 16918/42525 [25:50<37:54, 11.26it/s]

 40%|██████████████▎                     | 16922/42525 [25:50<38:08, 11.19it/s]

 40%|██████████████▎                     | 16926/42525 [25:50<38:36, 11.05it/s]

 40%|██████████████▎                     | 16930/42525 [25:51<38:22, 11.12it/s]

 40%|██████████████▎                     | 16934/42525 [25:51<38:32, 11.07it/s]

 40%|██████████████▎                     | 16938/42525 [25:52<39:22, 10.83it/s]

 40%|██████████████▎                     | 16942/42525 [25:52<37:27, 11.38it/s]

 40%|██████████████▎                     | 16944/42525 [25:52<37:06, 11.49it/s]

 40%|██████████████▎                     | 16948/42525 [25:52<38:57, 10.94it/s]

 40%|██████████████▎                     | 16952/42525 [25:53<38:30, 11.07it/s]

 40%|██████████████▎                     | 16956/42525 [25:53<37:37, 11.33it/s]

 40%|██████████████▎                     | 16960/42525 [25:54<38:13, 11.15it/s]

 40%|██████████████▎                     | 16964/42525 [25:54<38:26, 11.08it/s]

 40%|██████████████▎                     | 16968/42525 [25:54<36:20, 11.72it/s]

 40%|██████████████▎                     | 16972/42525 [25:55<35:17, 12.07it/s]

 40%|██████████████▎                     | 16976/42525 [25:55<35:16, 12.07it/s]

 40%|██████████████▎                     | 16980/42525 [25:55<35:12, 12.09it/s]

 40%|██████████████▍                     | 16984/42525 [25:56<35:38, 11.94it/s]

 40%|██████████████▍                     | 16988/42525 [25:56<34:16, 12.42it/s]

 40%|██████████████▍                     | 16992/42525 [25:56<35:21, 12.04it/s]

 40%|██████████████▍                     | 16996/42525 [25:57<36:56, 11.52it/s]

 40%|██████████████▍                     | 17000/42525 [25:57<38:19, 11.10it/s]

 40%|██████████████▍                     | 17004/42525 [25:57<38:54, 10.93it/s]

 40%|██████████████▍                     | 17008/42525 [25:58<37:35, 11.31it/s]

 40%|██████████████▍                     | 17012/42525 [25:58<36:55, 11.51it/s]

 40%|██████████████▍                     | 17016/42525 [25:58<38:01, 11.18it/s]

 40%|██████████████▍                     | 17020/42525 [25:59<37:10, 11.44it/s]

 40%|██████████████▍                     | 17024/42525 [25:59<38:29, 11.04it/s]

 40%|██████████████▍                     | 17028/42525 [25:59<38:32, 11.02it/s]

 40%|██████████████▍                     | 17032/42525 [26:00<37:54, 11.21it/s]

 40%|██████████████▍                     | 17036/42525 [26:00<37:58, 11.19it/s]

 40%|██████████████▍                     | 17040/42525 [26:00<37:20, 11.37it/s]

 40%|██████████████▍                     | 17042/42525 [26:01<38:29, 11.03it/s]

 40%|██████████████▍                     | 17046/42525 [26:01<39:20, 10.79it/s]

 40%|██████████████▍                     | 17050/42525 [26:01<38:21, 11.07it/s]

 40%|██████████████▍                     | 17054/42525 [26:02<38:25, 11.05it/s]

 40%|██████████████▍                     | 17058/42525 [26:02<38:06, 11.14it/s]

 40%|██████████████▍                     | 17062/42525 [26:03<38:53, 10.91it/s]

 40%|██████████████▍                     | 17066/42525 [26:03<39:15, 10.81it/s]

 40%|██████████████▍                     | 17070/42525 [26:03<37:40, 11.26it/s]

 40%|██████████████▍                     | 17074/42525 [26:04<38:00, 11.16it/s]

 40%|██████████████▍                     | 17078/42525 [26:04<38:58, 10.88it/s]

 40%|██████████████▍                     | 17080/42525 [26:04<38:08, 11.12it/s]

 40%|██████████████▍                     | 17082/42525 [26:04<40:01, 10.59it/s]

 40%|██████████████▍                     | 17086/42525 [26:05<40:28, 10.47it/s]

 40%|██████████████▍                     | 17090/42525 [26:05<40:12, 10.54it/s]

 40%|██████████████▍                     | 17094/42525 [26:05<39:43, 10.67it/s]

 40%|██████████████▍                     | 17098/42525 [26:06<39:09, 10.82it/s]

 40%|██████████████▍                     | 17102/42525 [26:06<37:54, 11.18it/s]

 40%|██████████████▍                     | 17106/42525 [26:07<36:49, 11.50it/s]

 40%|██████████████▍                     | 17110/42525 [26:07<39:55, 10.61it/s]

 40%|██████████████▍                     | 17114/42525 [26:07<38:47, 10.92it/s]

 40%|██████████████▍                     | 17118/42525 [26:08<39:00, 10.86it/s]

 40%|██████████████▍                     | 17122/42525 [26:08<40:52, 10.36it/s]

 40%|██████████████▍                     | 17126/42525 [26:08<39:41, 10.67it/s]

 40%|██████████████▌                     | 17130/42525 [26:09<40:53, 10.35it/s]

 40%|██████████████▌                     | 17134/42525 [26:09<40:16, 10.51it/s]

 40%|██████████████▌                     | 17138/42525 [26:10<39:25, 10.73it/s]

 40%|██████████████▌                     | 17142/42525 [26:10<38:56, 10.87it/s]

 40%|██████████████▌                     | 17144/42525 [26:10<38:07, 11.09it/s]

 40%|██████████████▌                     | 17148/42525 [26:11<39:53, 10.60it/s]

 40%|██████████████▌                     | 17152/42525 [26:11<38:55, 10.86it/s]

 40%|██████████████▌                     | 17156/42525 [26:11<38:02, 11.12it/s]

 40%|██████████████▌                     | 17160/42525 [26:12<38:40, 10.93it/s]

 40%|██████████████▌                     | 17164/42525 [26:12<38:37, 10.94it/s]

 40%|██████████████▌                     | 17168/42525 [26:12<37:31, 11.26it/s]

 40%|██████████████▌                     | 17172/42525 [26:13<36:50, 11.47it/s]

 40%|██████████████▌                     | 17176/42525 [26:13<36:27, 11.59it/s]

 40%|██████████████▌                     | 17180/42525 [26:13<36:41, 11.51it/s]

 40%|██████████████▌                     | 17184/42525 [26:14<38:09, 11.07it/s]

 40%|██████████████▌                     | 17188/42525 [26:14<37:43, 11.19it/s]

 40%|██████████████▌                     | 17192/42525 [26:14<37:56, 11.13it/s]

 40%|██████████████▌                     | 17196/42525 [26:15<37:21, 11.30it/s]

 40%|██████████████▌                     | 17200/42525 [26:15<37:43, 11.19it/s]

 40%|██████████████▌                     | 17204/42525 [26:16<38:41, 10.91it/s]

 40%|██████████████▌                     | 17208/42525 [26:16<39:09, 10.78it/s]

 40%|██████████████▌                     | 17212/42525 [26:16<38:21, 11.00it/s]

 40%|██████████████▌                     | 17216/42525 [26:17<38:00, 11.10it/s]

 40%|██████████████▌                     | 17220/42525 [26:17<37:55, 11.12it/s]

 41%|██████████████▌                     | 17224/42525 [26:17<34:25, 12.25it/s]

 41%|██████████████▌                     | 17228/42525 [26:18<36:25, 11.57it/s]

 41%|██████████████▌                     | 17232/42525 [26:18<36:44, 11.47it/s]

 41%|██████████████▌                     | 17236/42525 [26:18<35:51, 11.75it/s]

 41%|██████████████▌                     | 17240/42525 [26:19<35:34, 11.85it/s]

 41%|██████████████▌                     | 17244/42525 [26:19<34:15, 12.30it/s]

 41%|██████████████▌                     | 17248/42525 [26:19<34:34, 12.19it/s]

 41%|██████████████▌                     | 17252/42525 [26:20<35:06, 12.00it/s]

 41%|██████████████▌                     | 17256/42525 [26:20<35:17, 11.93it/s]

 41%|██████████████▌                     | 17260/42525 [26:20<38:12, 11.02it/s]

 41%|██████████████▌                     | 17264/42525 [26:21<34:30, 12.20it/s]

 41%|██████████████▌                     | 17268/42525 [26:21<33:46, 12.46it/s]

 41%|██████████████▌                     | 17270/42525 [26:21<33:24, 12.60it/s]

 41%|██████████████▌                     | 17274/42525 [26:21<36:25, 11.55it/s]

 41%|██████████████▋                     | 17278/42525 [26:22<35:06, 11.99it/s]

 41%|██████████████▋                     | 17282/42525 [26:22<36:08, 11.64it/s]

 41%|██████████████▋                     | 17286/42525 [26:22<35:09, 11.96it/s]

 41%|██████████████▋                     | 17290/42525 [26:23<35:21, 11.89it/s]

 41%|██████████████▋                     | 17294/42525 [26:23<33:00, 12.74it/s]

 41%|██████████████▋                     | 17298/42525 [26:23<33:50, 12.42it/s]

 41%|██████████████▋                     | 17302/42525 [26:24<33:36, 12.51it/s]

 41%|██████████████▋                     | 17306/42525 [26:24<34:43, 12.10it/s]

 41%|██████████████▋                     | 17310/42525 [26:24<34:09, 12.30it/s]

 41%|██████████████▋                     | 17314/42525 [26:25<34:15, 12.26it/s]

 41%|██████████████▋                     | 17318/42525 [26:25<33:55, 12.38it/s]

 41%|██████████████▋                     | 17322/42525 [26:25<35:06, 11.96it/s]

 41%|██████████████▋                     | 17326/42525 [26:26<34:41, 12.11it/s]

 41%|██████████████▋                     | 17330/42525 [26:26<36:23, 11.54it/s]

 41%|██████████████▋                     | 17334/42525 [26:26<35:20, 11.88it/s]

 41%|██████████████▋                     | 17338/42525 [26:27<34:50, 12.05it/s]

 41%|██████████████▋                     | 17342/42525 [26:27<35:57, 11.67it/s]

 41%|██████████████▋                     | 17346/42525 [26:27<36:55, 11.37it/s]

 41%|██████████████▋                     | 17350/42525 [26:28<35:01, 11.98it/s]

 41%|██████████████▋                     | 17354/42525 [26:28<36:18, 11.56it/s]

 41%|██████████████▋                     | 17358/42525 [26:29<36:45, 11.41it/s]

 41%|██████████████▋                     | 17362/42525 [26:29<36:40, 11.43it/s]

 41%|██████████████▋                     | 17366/42525 [26:29<36:07, 11.61it/s]

 41%|██████████████▋                     | 17368/42525 [26:29<37:22, 11.22it/s]

 41%|██████████████▋                     | 17372/42525 [26:30<38:12, 10.97it/s]

 41%|██████████████▋                     | 17376/42525 [26:30<38:31, 10.88it/s]

 41%|██████████████▋                     | 17380/42525 [26:30<37:05, 11.30it/s]

 41%|██████████████▋                     | 17384/42525 [26:31<37:06, 11.29it/s]

 41%|██████████████▋                     | 17388/42525 [26:31<34:37, 12.10it/s]

 41%|██████████████▋                     | 17392/42525 [26:31<34:01, 12.31it/s]

 41%|██████████████▋                     | 17396/42525 [26:32<32:50, 12.75it/s]

 41%|██████████████▋                     | 17400/42525 [26:32<32:35, 12.85it/s]

 41%|██████████████▋                     | 17404/42525 [26:32<34:49, 12.02it/s]

 41%|██████████████▋                     | 17408/42525 [26:33<35:31, 11.78it/s]

 41%|██████████████▋                     | 17412/42525 [26:33<32:57, 12.70it/s]

 41%|██████████████▋                     | 17414/42525 [26:33<34:25, 12.15it/s]

 41%|██████████████▋                     | 17418/42525 [26:34<36:22, 11.50it/s]

 41%|██████████████▋                     | 17422/42525 [26:34<36:30, 11.46it/s]

 41%|██████████████▊                     | 17426/42525 [26:34<37:59, 11.01it/s]

 41%|██████████████▊                     | 17430/42525 [26:35<37:11, 11.24it/s]

 41%|██████████████▊                     | 17434/42525 [26:35<37:25, 11.17it/s]

 41%|██████████████▊                     | 17438/42525 [26:35<37:28, 11.16it/s]

 41%|██████████████▊                     | 17442/42525 [26:36<37:27, 11.16it/s]

 41%|██████████████▊                     | 17446/42525 [26:36<37:06, 11.26it/s]

 41%|██████████████▊                     | 17450/42525 [26:36<37:34, 11.12it/s]

 41%|██████████████▊                     | 17454/42525 [26:37<38:15, 10.92it/s]

 41%|██████████████▊                     | 17458/42525 [26:37<39:16, 10.64it/s]

 41%|██████████████▊                     | 17462/42525 [26:38<38:35, 10.83it/s]

 41%|██████████████▊                     | 17466/42525 [26:38<39:21, 10.61it/s]

 41%|██████████████▊                     | 17470/42525 [26:38<38:05, 10.96it/s]

 41%|██████████████▊                     | 17474/42525 [26:39<37:57, 11.00it/s]

 41%|██████████████▊                     | 17478/42525 [26:39<37:49, 11.04it/s]

 41%|██████████████▊                     | 17482/42525 [26:39<37:03, 11.26it/s]

 41%|██████████████▊                     | 17486/42525 [26:40<36:51, 11.32it/s]

 41%|██████████████▊                     | 17490/42525 [26:40<36:07, 11.55it/s]

 41%|██████████████▊                     | 17494/42525 [26:40<36:54, 11.30it/s]

 41%|██████████████▊                     | 17496/42525 [26:41<35:22, 11.79it/s]

 41%|██████████████▊                     | 17500/42525 [26:41<36:16, 11.50it/s]

 41%|██████████████▊                     | 17504/42525 [26:41<35:31, 11.74it/s]

 41%|██████████████▊                     | 17508/42525 [26:42<35:39, 11.69it/s]

 41%|██████████████▊                     | 17512/42525 [26:42<33:21, 12.50it/s]

 41%|██████████████▊                     | 17516/42525 [26:42<34:00, 12.25it/s]

 41%|██████████████▊                     | 17520/42525 [26:43<32:56, 12.65it/s]

 41%|██████████████▊                     | 17524/42525 [26:43<36:20, 11.46it/s]

 41%|██████████████▊                     | 17528/42525 [26:43<37:31, 11.10it/s]

 41%|██████████████▊                     | 17532/42525 [26:44<37:36, 11.08it/s]

 41%|██████████████▊                     | 17536/42525 [26:44<37:28, 11.11it/s]

 41%|██████████████▊                     | 17540/42525 [26:44<36:49, 11.31it/s]

 41%|██████████████▊                     | 17544/42525 [26:45<37:39, 11.06it/s]

 41%|██████████████▊                     | 17548/42525 [26:45<37:31, 11.09it/s]

 41%|██████████████▊                     | 17552/42525 [26:46<37:37, 11.06it/s]

 41%|██████████████▊                     | 17556/42525 [26:46<37:06, 11.21it/s]

 41%|██████████████▊                     | 17560/42525 [26:46<36:10, 11.50it/s]

 41%|██████████████▊                     | 17564/42525 [26:47<35:45, 11.64it/s]

 41%|██████████████▊                     | 17568/42525 [26:47<35:34, 11.69it/s]

 41%|██████████████▉                     | 17572/42525 [26:47<35:39, 11.66it/s]

 41%|██████████████▉                     | 17576/42525 [26:48<37:49, 10.99it/s]

 41%|██████████████▉                     | 17580/42525 [26:48<36:57, 11.25it/s]

 41%|██████████████▉                     | 17584/42525 [26:48<35:44, 11.63it/s]

 41%|██████████████▉                     | 17588/42525 [26:49<35:32, 11.69it/s]

 41%|██████████████▉                     | 17592/42525 [26:49<35:29, 11.71it/s]

 41%|██████████████▉                     | 17596/42525 [26:49<36:09, 11.49it/s]

 41%|██████████████▉                     | 17600/42525 [26:50<36:53, 11.26it/s]

 41%|██████████████▉                     | 17604/42525 [26:50<36:19, 11.44it/s]

 41%|██████████████▉                     | 17608/42525 [26:50<37:02, 11.21it/s]

 41%|██████████████▉                     | 17612/42525 [26:51<36:12, 11.47it/s]

 41%|██████████████▉                     | 17616/42525 [26:51<37:01, 11.21it/s]

 41%|██████████████▉                     | 17620/42525 [26:51<36:13, 11.46it/s]

 41%|██████████████▉                     | 17624/42525 [26:52<36:04, 11.50it/s]

 41%|██████████████▉                     | 17628/42525 [26:52<38:19, 10.83it/s]

 41%|██████████████▉                     | 17632/42525 [26:53<36:50, 11.26it/s]

 41%|██████████████▉                     | 17636/42525 [26:53<37:26, 11.08it/s]

 41%|██████████████▉                     | 17638/42525 [26:53<36:52, 11.25it/s]

 41%|██████████████▉                     | 17642/42525 [26:53<38:09, 10.87it/s]

 41%|██████████████▉                     | 17646/42525 [26:54<37:23, 11.09it/s]

 42%|██████████████▉                     | 17650/42525 [26:54<37:56, 10.93it/s]

 42%|██████████████▉                     | 17654/42525 [26:55<37:02, 11.19it/s]

 42%|██████████████▉                     | 17658/42525 [26:55<36:44, 11.28it/s]

 42%|██████████████▉                     | 17662/42525 [26:55<36:26, 11.37it/s]

 42%|██████████████▉                     | 17666/42525 [26:56<37:20, 11.10it/s]

 42%|██████████████▉                     | 17670/42525 [26:56<36:17, 11.42it/s]

 42%|██████████████▉                     | 17674/42525 [26:56<36:50, 11.24it/s]

 42%|██████████████▉                     | 17676/42525 [26:56<36:16, 11.42it/s]

 42%|██████████████▉                     | 17680/42525 [26:57<37:29, 11.04it/s]

 42%|██████████████▉                     | 17684/42525 [26:57<36:24, 11.37it/s]

 42%|██████████████▉                     | 17688/42525 [26:58<37:31, 11.03it/s]

 42%|██████████████▉                     | 17692/42525 [26:58<36:25, 11.36it/s]

 42%|██████████████▉                     | 17696/42525 [26:58<35:48, 11.56it/s]

 42%|██████████████▉                     | 17700/42525 [26:59<36:36, 11.30it/s]

 42%|██████████████▉                     | 17704/42525 [26:59<36:49, 11.23it/s]

 42%|██████████████▉                     | 17708/42525 [26:59<36:01, 11.48it/s]

 42%|██████████████▉                     | 17712/42525 [27:00<35:33, 11.63it/s]

 42%|██████████████▉                     | 17716/42525 [27:00<37:58, 10.89it/s]

 42%|███████████████                     | 17720/42525 [27:00<38:28, 10.75it/s]

 42%|███████████████                     | 17724/42525 [27:01<38:14, 10.81it/s]

 42%|███████████████                     | 17728/42525 [27:01<36:52, 11.21it/s]

 42%|███████████████                     | 17732/42525 [27:01<36:53, 11.20it/s]

 42%|███████████████                     | 17736/42525 [27:02<35:49, 11.53it/s]

 42%|███████████████                     | 17740/42525 [27:02<36:49, 11.22it/s]

 42%|███████████████                     | 17744/42525 [27:03<37:04, 11.14it/s]

 42%|███████████████                     | 17748/42525 [27:03<37:20, 11.06it/s]

 42%|███████████████                     | 17752/42525 [27:03<37:00, 11.15it/s]

 42%|███████████████                     | 17756/42525 [27:04<36:29, 11.31it/s]

 42%|███████████████                     | 17760/42525 [27:04<37:56, 10.88it/s]

 42%|███████████████                     | 17764/42525 [27:04<36:51, 11.20it/s]

 42%|███████████████                     | 17768/42525 [27:05<36:49, 11.20it/s]

 42%|███████████████                     | 17772/42525 [27:05<35:54, 11.49it/s]

 42%|███████████████                     | 17776/42525 [27:05<36:43, 11.23it/s]

 42%|███████████████                     | 17780/42525 [27:06<36:32, 11.28it/s]

 42%|███████████████                     | 17784/42525 [27:06<36:40, 11.24it/s]

 42%|███████████████                     | 17788/42525 [27:07<38:09, 10.80it/s]

 42%|███████████████                     | 17792/42525 [27:07<37:43, 10.93it/s]

 42%|███████████████                     | 17796/42525 [27:07<36:34, 11.27it/s]

 42%|███████████████                     | 17800/42525 [27:08<35:44, 11.53it/s]

 42%|███████████████                     | 17804/42525 [27:08<36:16, 11.36it/s]

 42%|███████████████                     | 17808/42525 [27:08<35:25, 11.63it/s]

 42%|███████████████                     | 17812/42525 [27:09<35:05, 11.74it/s]

 42%|███████████████                     | 17816/42525 [27:09<36:39, 11.23it/s]

 42%|███████████████                     | 17820/42525 [27:09<37:14, 11.06it/s]

 42%|███████████████                     | 17824/42525 [27:10<39:17, 10.48it/s]

 42%|███████████████                     | 17828/42525 [27:10<37:15, 11.05it/s]

 42%|███████████████                     | 17832/42525 [27:10<37:07, 11.08it/s]

 42%|███████████████                     | 17836/42525 [27:11<36:54, 11.15it/s]

 42%|███████████████                     | 17840/42525 [27:11<36:09, 11.38it/s]

 42%|███████████████                     | 17844/42525 [27:12<36:37, 11.23it/s]

 42%|███████████████                     | 17848/42525 [27:12<36:33, 11.25it/s]

 42%|███████████████                     | 17852/42525 [27:12<36:21, 11.31it/s]

 42%|███████████████                     | 17856/42525 [27:13<37:30, 10.96it/s]

 42%|███████████████                     | 17860/42525 [27:13<36:25, 11.29it/s]

 42%|███████████████                     | 17864/42525 [27:13<35:47, 11.48it/s]

 42%|███████████████▏                    | 17868/42525 [27:14<36:17, 11.32it/s]

 42%|███████████████▏                    | 17872/42525 [27:14<36:00, 11.41it/s]

 42%|███████████████▏                    | 17876/42525 [27:14<35:33, 11.55it/s]

 42%|███████████████▏                    | 17880/42525 [27:15<35:08, 11.69it/s]

 42%|███████████████▏                    | 17884/42525 [27:15<34:36, 11.87it/s]

 42%|███████████████▏                    | 17888/42525 [27:15<34:49, 11.79it/s]

 42%|███████████████▏                    | 17892/42525 [27:16<35:31, 11.56it/s]

 42%|███████████████▏                    | 17896/42525 [27:16<36:11, 11.34it/s]

 42%|███████████████▏                    | 17900/42525 [27:16<37:47, 10.86it/s]

 42%|███████████████▏                    | 17904/42525 [27:17<36:29, 11.25it/s]

 42%|███████████████▏                    | 17908/42525 [27:17<36:26, 11.26it/s]

 42%|███████████████▏                    | 17912/42525 [27:18<36:17, 11.30it/s]

 42%|███████████████▏                    | 17916/42525 [27:18<36:21, 11.28it/s]

 42%|███████████████▏                    | 17920/42525 [27:18<35:31, 11.54it/s]

 42%|███████████████▏                    | 17924/42525 [27:19<35:54, 11.42it/s]

 42%|███████████████▏                    | 17928/42525 [27:19<35:18, 11.61it/s]

 42%|███████████████▏                    | 17932/42525 [27:19<37:59, 10.79it/s]

 42%|███████████████▏                    | 17936/42525 [27:20<37:53, 10.81it/s]

 42%|███████████████▏                    | 17940/42525 [27:20<36:32, 11.21it/s]

 42%|███████████████▏                    | 17944/42525 [27:20<35:44, 11.46it/s]

 42%|███████████████▏                    | 17948/42525 [27:21<35:13, 11.63it/s]

 42%|███████████████▏                    | 17952/42525 [27:21<35:54, 11.41it/s]

 42%|███████████████▏                    | 17956/42525 [27:21<35:21, 11.58it/s]

 42%|███████████████▏                    | 17960/42525 [27:22<35:49, 11.43it/s]

 42%|███████████████▏                    | 17964/42525 [27:22<35:54, 11.40it/s]

 42%|███████████████▏                    | 17968/42525 [27:22<36:26, 11.23it/s]

 42%|███████████████▏                    | 17972/42525 [27:23<36:37, 11.17it/s]

 42%|███████████████▏                    | 17976/42525 [27:23<38:42, 10.57it/s]

 42%|███████████████▏                    | 17980/42525 [27:24<36:37, 11.17it/s]

 42%|███████████████▏                    | 17984/42525 [27:24<35:27, 11.54it/s]

 42%|███████████████▏                    | 17988/42525 [27:24<35:09, 11.63it/s]

 42%|███████████████▏                    | 17992/42525 [27:25<36:20, 11.25it/s]

 42%|███████████████▏                    | 17996/42525 [27:25<37:27, 10.91it/s]

 42%|███████████████▏                    | 18000/42525 [27:25<37:55, 10.78it/s]

 42%|███████████████▏                    | 18004/42525 [27:26<36:57, 11.06it/s]

 42%|███████████████▏                    | 18006/42525 [27:26<37:50, 10.80it/s]

 42%|███████████████▏                    | 18008/42525 [27:26<38:51, 10.52it/s]

 42%|███████████████▏                    | 18012/42525 [27:26<38:49, 10.52it/s]

 42%|███████████████▎                    | 18016/42525 [27:27<36:42, 11.13it/s]

 42%|███████████████▎                    | 18020/42525 [27:27<37:13, 10.97it/s]

 42%|███████████████▎                    | 18024/42525 [27:28<35:59, 11.35it/s]

 42%|███████████████▎                    | 18028/42525 [27:28<35:09, 11.61it/s]

 42%|███████████████▎                    | 18032/42525 [27:28<36:49, 11.09it/s]

 42%|███████████████▎                    | 18034/42525 [27:28<37:22, 10.92it/s]

 42%|███████████████▎                    | 18038/42525 [27:29<37:24, 10.91it/s]

 42%|███████████████▎                    | 18042/42525 [27:29<38:33, 10.58it/s]

 42%|███████████████▎                    | 18046/42525 [27:30<36:25, 11.20it/s]

 42%|███████████████▎                    | 18050/42525 [27:30<38:14, 10.67it/s]

 42%|███████████████▎                    | 18054/42525 [27:30<38:19, 10.64it/s]

 42%|███████████████▎                    | 18058/42525 [27:31<38:22, 10.63it/s]

 42%|███████████████▎                    | 18062/42525 [27:31<38:32, 10.58it/s]

 42%|███████████████▎                    | 18066/42525 [27:31<37:05, 10.99it/s]

 42%|███████████████▎                    | 18070/42525 [27:32<35:41, 11.42it/s]

 42%|███████████████▎                    | 18072/42525 [27:32<35:29, 11.48it/s]

 43%|███████████████▎                    | 18076/42525 [27:32<37:04, 10.99it/s]

 43%|███████████████▎                    | 18080/42525 [27:33<35:58, 11.32it/s]

 43%|███████████████▎                    | 18084/42525 [27:33<36:32, 11.15it/s]

 43%|███████████████▎                    | 18088/42525 [27:33<36:58, 11.02it/s]

 43%|███████████████▎                    | 18092/42525 [27:34<37:18, 10.91it/s]

 43%|███████████████▎                    | 18096/42525 [27:34<36:30, 11.15it/s]

 43%|███████████████▎                    | 18100/42525 [27:34<37:31, 10.85it/s]

 43%|███████████████▎                    | 18104/42525 [27:35<38:03, 10.69it/s]

 43%|███████████████▎                    | 18108/42525 [27:35<37:00, 10.99it/s]

 43%|███████████████▎                    | 18112/42525 [27:36<35:46, 11.38it/s]

 43%|███████████████▎                    | 18116/42525 [27:36<35:15, 11.54it/s]

 43%|███████████████▎                    | 18120/42525 [27:36<35:21, 11.50it/s]

 43%|███████████████▎                    | 18124/42525 [27:37<35:45, 11.37it/s]

 43%|███████████████▎                    | 18128/42525 [27:37<35:08, 11.57it/s]

 43%|███████████████▎                    | 18132/42525 [27:37<35:55, 11.32it/s]

 43%|███████████████▎                    | 18136/42525 [27:38<35:57, 11.31it/s]

 43%|███████████████▎                    | 18140/42525 [27:38<35:05, 11.58it/s]

 43%|███████████████▎                    | 18144/42525 [27:38<34:45, 11.69it/s]

 43%|███████████████▎                    | 18148/42525 [27:39<34:34, 11.75it/s]

 43%|███████████████▎                    | 18152/42525 [27:39<34:31, 11.77it/s]

 43%|███████████████▎                    | 18156/42525 [27:39<35:48, 11.34it/s]

 43%|███████████████▎                    | 18160/42525 [27:40<35:04, 11.58it/s]

 43%|███████████████▍                    | 18164/42525 [27:40<34:55, 11.63it/s]

 43%|███████████████▍                    | 18168/42525 [27:40<35:31, 11.43it/s]

 43%|███████████████▍                    | 18172/42525 [27:41<37:05, 10.94it/s]

 43%|███████████████▍                    | 18174/42525 [27:41<36:26, 11.14it/s]

 43%|███████████████▍                    | 18178/42525 [27:41<38:48, 10.46it/s]

 43%|███████████████▍                    | 18182/42525 [27:42<37:18, 10.87it/s]

 43%|███████████████▍                    | 18186/42525 [27:42<36:34, 11.09it/s]

 43%|███████████████▍                    | 18190/42525 [27:42<36:36, 11.08it/s]

 43%|███████████████▍                    | 18194/42525 [27:43<37:55, 10.69it/s]

 43%|███████████████▍                    | 18198/42525 [27:43<38:55, 10.42it/s]

 43%|███████████████▍                    | 18202/42525 [27:44<38:08, 10.63it/s]

 43%|███████████████▍                    | 18206/42525 [27:44<37:37, 10.77it/s]

 43%|███████████████▍                    | 18210/42525 [27:44<38:12, 10.61it/s]

 43%|███████████████▍                    | 18214/42525 [27:45<36:50, 11.00it/s]

 43%|███████████████▍                    | 18218/42525 [27:45<36:11, 11.19it/s]

 43%|███████████████▍                    | 18222/42525 [27:45<35:25, 11.43it/s]

 43%|███████████████▍                    | 18226/42525 [27:46<34:48, 11.63it/s]

 43%|███████████████▍                    | 18230/42525 [27:46<35:19, 11.46it/s]

 43%|███████████████▍                    | 18234/42525 [27:46<35:48, 11.30it/s]

 43%|███████████████▍                    | 18238/42525 [27:47<36:10, 11.19it/s]

 43%|███████████████▍                    | 18242/42525 [27:47<37:37, 10.76it/s]

 43%|███████████████▍                    | 18246/42525 [27:48<36:11, 11.18it/s]

 43%|███████████████▍                    | 18250/42525 [27:48<36:57, 10.95it/s]

 43%|███████████████▍                    | 18254/42525 [27:48<37:29, 10.79it/s]

 43%|███████████████▍                    | 18258/42525 [27:49<36:25, 11.11it/s]

 43%|███████████████▍                    | 18262/42525 [27:49<35:48, 11.29it/s]

 43%|███████████████▍                    | 18266/42525 [27:49<34:53, 11.59it/s]

 43%|███████████████▍                    | 18270/42525 [27:50<34:45, 11.63it/s]

 43%|███████████████▍                    | 18274/42525 [27:50<34:37, 11.67it/s]

 43%|███████████████▍                    | 18278/42525 [27:50<34:34, 11.69it/s]

 43%|███████████████▍                    | 18282/42525 [27:51<35:57, 11.24it/s]

 43%|███████████████▍                    | 18286/42525 [27:51<35:06, 11.51it/s]

 43%|███████████████▍                    | 18290/42525 [27:51<34:47, 11.61it/s]

 43%|███████████████▍                    | 18294/42525 [27:52<36:26, 11.08it/s]

 43%|███████████████▍                    | 18298/42525 [27:52<36:49, 10.96it/s]

 43%|███████████████▍                    | 18300/42525 [27:52<36:09, 11.17it/s]

 43%|███████████████▍                    | 18304/42525 [27:53<36:45, 10.98it/s]

 43%|███████████████▍                    | 18308/42525 [27:53<36:16, 11.13it/s]

 43%|███████████████▌                    | 18312/42525 [27:53<35:15, 11.45it/s]

 43%|███████████████▌                    | 18316/42525 [27:54<34:46, 11.60it/s]

 43%|███████████████▌                    | 18320/42525 [27:54<36:18, 11.11it/s]

 43%|███████████████▌                    | 18324/42525 [27:54<35:32, 11.35it/s]

 43%|███████████████▌                    | 18328/42525 [27:55<36:47, 10.96it/s]

 43%|███████████████▌                    | 18332/42525 [27:55<36:00, 11.20it/s]

 43%|███████████████▌                    | 18336/42525 [27:56<36:47, 10.96it/s]

 43%|███████████████▌                    | 18340/42525 [27:56<36:02, 11.18it/s]

 43%|███████████████▌                    | 18344/42525 [27:56<35:10, 11.46it/s]

 43%|███████████████▌                    | 18348/42525 [27:57<34:44, 11.60it/s]

 43%|███████████████▌                    | 18352/42525 [27:57<34:07, 11.81it/s]

 43%|███████████████▌                    | 18356/42525 [27:57<34:52, 11.55it/s]

 43%|███████████████▌                    | 18360/42525 [27:58<34:55, 11.53it/s]

 43%|███████████████▌                    | 18364/42525 [27:58<35:04, 11.48it/s]

 43%|███████████████▌                    | 18368/42525 [27:58<34:45, 11.59it/s]

 43%|███████████████▌                    | 18372/42525 [27:59<34:55, 11.53it/s]

 43%|███████████████▌                    | 18376/42525 [27:59<34:30, 11.67it/s]

 43%|███████████████▌                    | 18380/42525 [27:59<35:18, 11.40it/s]

 43%|███████████████▌                    | 18384/42525 [28:00<34:36, 11.63it/s]

 43%|███████████████▌                    | 18388/42525 [28:00<34:33, 11.64it/s]

 43%|███████████████▌                    | 18392/42525 [28:00<34:19, 11.72it/s]

 43%|███████████████▌                    | 18396/42525 [28:01<35:18, 11.39it/s]

 43%|███████████████▌                    | 18400/42525 [28:01<34:33, 11.63it/s]

 43%|███████████████▌                    | 18404/42525 [28:01<34:23, 11.69it/s]

 43%|███████████████▌                    | 18408/42525 [28:02<35:29, 11.33it/s]

 43%|███████████████▌                    | 18412/42525 [28:02<35:42, 11.25it/s]

 43%|███████████████▌                    | 18416/42525 [28:03<35:26, 11.34it/s]

 43%|███████████████▌                    | 18420/42525 [28:03<37:13, 10.79it/s]

 43%|███████████████▌                    | 18424/42525 [28:03<35:37, 11.28it/s]

 43%|███████████████▌                    | 18428/42525 [28:04<34:43, 11.57it/s]

 43%|███████████████▌                    | 18432/42525 [28:04<34:21, 11.69it/s]

 43%|███████████████▌                    | 18436/42525 [28:04<34:43, 11.56it/s]

 43%|███████████████▌                    | 18440/42525 [28:05<34:45, 11.55it/s]

 43%|███████████████▌                    | 18444/42525 [28:05<34:18, 11.70it/s]

 43%|███████████████▌                    | 18448/42525 [28:05<34:34, 11.61it/s]

 43%|███████████████▌                    | 18452/42525 [28:06<34:34, 11.60it/s]

 43%|███████████████▌                    | 18456/42525 [28:06<35:11, 11.40it/s]

 43%|███████████████▋                    | 18460/42525 [28:06<35:33, 11.28it/s]

 43%|███████████████▋                    | 18464/42525 [28:07<35:45, 11.21it/s]

 43%|███████████████▋                    | 18468/42525 [28:07<34:45, 11.53it/s]

 43%|███████████████▋                    | 18472/42525 [28:07<35:18, 11.35it/s]

 43%|███████████████▋                    | 18476/42525 [28:08<35:18, 11.35it/s]

 43%|███████████████▋                    | 18480/42525 [28:08<34:34, 11.59it/s]

 43%|███████████████▋                    | 18484/42525 [28:08<36:03, 11.11it/s]

 43%|███████████████▋                    | 18488/42525 [28:09<35:58, 11.13it/s]

 43%|███████████████▋                    | 18492/42525 [28:09<37:01, 10.82it/s]

 43%|███████████████▋                    | 18496/42525 [28:10<36:37, 10.93it/s]

 43%|███████████████▋                    | 18498/42525 [28:10<35:55, 11.15it/s]

 44%|███████████████▋                    | 18502/42525 [28:10<36:34, 10.94it/s]

 44%|███████████████▋                    | 18506/42525 [28:11<36:55, 10.84it/s]

 44%|███████████████▋                    | 18510/42525 [28:11<35:29, 11.28it/s]

 44%|███████████████▋                    | 18514/42525 [28:11<36:16, 11.03it/s]

 44%|███████████████▋                    | 18518/42525 [28:12<36:02, 11.10it/s]

 44%|███████████████▋                    | 18522/42525 [28:12<37:12, 10.75it/s]

 44%|███████████████▋                    | 18526/42525 [28:12<35:32, 11.26it/s]

 44%|███████████████▋                    | 18530/42525 [28:13<36:12, 11.05it/s]

 44%|███████████████▋                    | 18534/42525 [28:13<35:06, 11.39it/s]

 44%|███████████████▋                    | 18538/42525 [28:13<35:39, 11.21it/s]

 44%|███████████████▋                    | 18542/42525 [28:14<35:53, 11.14it/s]

 44%|███████████████▋                    | 18546/42525 [28:14<34:49, 11.48it/s]

 44%|███████████████▋                    | 18550/42525 [28:14<35:43, 11.19it/s]

 44%|███████████████▋                    | 18554/42525 [28:15<35:46, 11.17it/s]

 44%|███████████████▋                    | 18558/42525 [28:15<35:47, 11.16it/s]

 44%|███████████████▋                    | 18560/42525 [28:15<35:19, 11.31it/s]

 44%|███████████████▋                    | 18562/42525 [28:16<37:03, 10.78it/s]

 44%|███████████████▋                    | 18564/42525 [28:16<38:14, 10.44it/s]

 44%|███████████████▋                    | 18568/42525 [28:16<38:02, 10.49it/s]

 44%|███████████████▋                    | 18572/42525 [28:17<37:47, 10.57it/s]

 44%|███████████████▋                    | 18576/42525 [28:17<36:39, 10.89it/s]

 44%|███████████████▋                    | 18580/42525 [28:17<35:14, 11.32it/s]

 44%|███████████████▋                    | 18584/42525 [28:18<36:08, 11.04it/s]

 44%|███████████████▋                    | 18588/42525 [28:18<36:01, 11.08it/s]

 44%|███████████████▋                    | 18592/42525 [28:18<35:27, 11.25it/s]

 44%|███████████████▋                    | 18596/42525 [28:19<34:58, 11.40it/s]

 44%|███████████████▋                    | 18600/42525 [28:19<34:57, 11.41it/s]

 44%|███████████████▋                    | 18604/42525 [28:19<35:47, 11.14it/s]

 44%|███████████████▊                    | 18606/42525 [28:20<35:20, 11.28it/s]

 44%|███████████████▊                    | 18610/42525 [28:20<36:05, 11.05it/s]

 44%|███████████████▊                    | 18614/42525 [28:20<35:53, 11.11it/s]

 44%|███████████████▊                    | 18618/42525 [28:21<35:41, 11.16it/s]

 44%|███████████████▊                    | 18622/42525 [28:21<35:48, 11.13it/s]

 44%|███████████████▊                    | 18626/42525 [28:21<36:28, 10.92it/s]

 44%|███████████████▊                    | 18630/42525 [28:22<35:29, 11.22it/s]

 44%|███████████████▊                    | 18632/42525 [28:22<35:40, 11.16it/s]

 44%|███████████████▊                    | 18636/42525 [28:22<36:48, 10.82it/s]

 44%|███████████████▊                    | 18640/42525 [28:23<35:58, 11.07it/s]

 44%|███████████████▊                    | 18644/42525 [28:23<34:54, 11.40it/s]

 44%|███████████████▊                    | 18648/42525 [28:23<34:24, 11.56it/s]

 44%|███████████████▊                    | 18652/42525 [28:24<35:52, 11.09it/s]

 44%|███████████████▊                    | 18656/42525 [28:24<35:51, 11.09it/s]

 44%|███████████████▊                    | 18660/42525 [28:24<34:40, 11.47it/s]

 44%|███████████████▊                    | 18664/42525 [28:25<34:41, 11.46it/s]

 44%|███████████████▊                    | 18668/42525 [28:25<36:11, 10.99it/s]

 44%|███████████████▊                    | 18672/42525 [28:25<35:24, 11.23it/s]

 44%|███████████████▊                    | 18676/42525 [28:26<35:40, 11.14it/s]

 44%|███████████████▊                    | 18680/42525 [28:26<35:35, 11.17it/s]

 44%|███████████████▊                    | 18684/42525 [28:27<36:20, 10.93it/s]

 44%|███████████████▊                    | 18688/42525 [28:27<35:38, 11.15it/s]

 44%|███████████████▊                    | 18692/42525 [28:27<33:27, 11.87it/s]

 44%|███████████████▊                    | 18696/42525 [28:28<35:56, 11.05it/s]

 44%|███████████████▊                    | 18700/42525 [28:28<35:17, 11.25it/s]

 44%|███████████████▊                    | 18704/42525 [28:28<35:13, 11.27it/s]

 44%|███████████████▊                    | 18706/42525 [28:28<34:56, 11.36it/s]

 44%|███████████████▊                    | 18710/42525 [28:29<36:16, 10.94it/s]

 44%|███████████████▊                    | 18714/42525 [28:29<35:13, 11.27it/s]

 44%|███████████████▊                    | 18718/42525 [28:30<34:33, 11.48it/s]

 44%|███████████████▊                    | 18722/42525 [28:30<34:20, 11.55it/s]

 44%|███████████████▊                    | 18726/42525 [28:30<35:48, 11.08it/s]

 44%|███████████████▊                    | 18730/42525 [28:31<35:15, 11.25it/s]

 44%|███████████████▊                    | 18734/42525 [28:31<37:04, 10.69it/s]

 44%|███████████████▊                    | 18738/42525 [28:31<37:29, 10.57it/s]

 44%|███████████████▊                    | 18742/42525 [28:32<35:34, 11.14it/s]

 44%|███████████████▊                    | 18746/42525 [28:32<34:43, 11.41it/s]

 44%|███████████████▊                    | 18750/42525 [28:32<34:10, 11.60it/s]

 44%|███████████████▉                    | 18754/42525 [28:33<35:13, 11.24it/s]

 44%|███████████████▉                    | 18758/42525 [28:33<34:32, 11.47it/s]

 44%|███████████████▉                    | 18762/42525 [28:34<34:53, 11.35it/s]

 44%|███████████████▉                    | 18766/42525 [28:34<34:18, 11.54it/s]

 44%|███████████████▉                    | 18770/42525 [28:34<34:35, 11.45it/s]

 44%|███████████████▉                    | 18774/42525 [28:35<34:17, 11.54it/s]

 44%|███████████████▉                    | 18778/42525 [28:35<34:58, 11.32it/s]

 44%|███████████████▉                    | 18782/42525 [28:35<34:24, 11.50it/s]

 44%|███████████████▉                    | 18786/42525 [28:36<34:49, 11.36it/s]

 44%|███████████████▉                    | 18790/42525 [28:36<34:14, 11.55it/s]

 44%|███████████████▉                    | 18794/42525 [28:36<35:23, 11.18it/s]

 44%|███████████████▉                    | 18798/42525 [28:37<35:13, 11.23it/s]

 44%|███████████████▉                    | 18802/42525 [28:37<35:11, 11.24it/s]

 44%|███████████████▉                    | 18806/42525 [28:37<34:40, 11.40it/s]

 44%|███████████████▉                    | 18810/42525 [28:38<34:25, 11.48it/s]

 44%|███████████████▉                    | 18814/42525 [28:38<34:29, 11.46it/s]

 44%|███████████████▉                    | 18816/42525 [28:38<35:30, 11.13it/s]

 44%|███████████████▉                    | 18820/42525 [28:39<37:47, 10.46it/s]

 44%|███████████████▉                    | 18824/42525 [28:39<36:24, 10.85it/s]

 44%|███████████████▉                    | 18828/42525 [28:39<35:03, 11.27it/s]

 44%|███████████████▉                    | 18832/42525 [28:40<35:44, 11.05it/s]

 44%|███████████████▉                    | 18836/42525 [28:40<35:06, 11.25it/s]

 44%|███████████████▉                    | 18838/42525 [28:40<35:40, 11.07it/s]

 44%|███████████████▉                    | 18842/42525 [28:41<36:14, 10.89it/s]

 44%|███████████████▉                    | 18846/42525 [28:41<37:22, 10.56it/s]

 44%|███████████████▉                    | 18850/42525 [28:41<37:47, 10.44it/s]

 44%|███████████████▉                    | 18854/42525 [28:42<38:04, 10.36it/s]

 44%|███████████████▉                    | 18858/42525 [28:42<37:20, 10.56it/s]

 44%|███████████████▉                    | 18862/42525 [28:43<37:40, 10.47it/s]

 44%|███████████████▉                    | 18866/42525 [28:43<37:06, 10.63it/s]

 44%|███████████████▉                    | 18870/42525 [28:43<36:15, 10.87it/s]

 44%|███████████████▉                    | 18874/42525 [28:44<35:40, 11.05it/s]

 44%|███████████████▉                    | 18876/42525 [28:44<35:07, 11.22it/s]

 44%|███████████████▉                    | 18880/42525 [28:44<37:01, 10.65it/s]

 44%|███████████████▉                    | 18884/42525 [28:45<36:06, 10.91it/s]

 44%|███████████████▉                    | 18888/42525 [28:45<36:20, 10.84it/s]

 44%|███████████████▉                    | 18892/42525 [28:45<35:18, 11.16it/s]

 44%|███████████████▉                    | 18896/42525 [28:46<35:18, 11.15it/s]

 44%|████████████████                    | 18900/42525 [28:46<35:39, 11.04it/s]

 44%|████████████████                    | 18904/42525 [28:46<33:39, 11.70it/s]

 44%|████████████████                    | 18908/42525 [28:47<31:31, 12.48it/s]

 44%|████████████████                    | 18912/42525 [28:47<32:40, 12.04it/s]

 44%|████████████████                    | 18916/42525 [28:47<34:49, 11.30it/s]

 44%|████████████████                    | 18920/42525 [28:48<34:26, 11.42it/s]

 45%|████████████████                    | 18924/42525 [28:48<34:03, 11.55it/s]

 45%|████████████████                    | 18928/42525 [28:48<35:25, 11.10it/s]

 45%|████████████████                    | 18932/42525 [28:49<35:45, 11.00it/s]

 45%|████████████████                    | 18936/42525 [28:49<36:57, 10.64it/s]

 45%|████████████████                    | 18940/42525 [28:50<35:28, 11.08it/s]

 45%|████████████████                    | 18944/42525 [28:50<36:50, 10.67it/s]

 45%|████████████████                    | 18948/42525 [28:50<35:15, 11.14it/s]

 45%|████████████████                    | 18952/42525 [28:51<34:47, 11.29it/s]

 45%|████████████████                    | 18956/42525 [28:51<35:09, 11.17it/s]

 45%|████████████████                    | 18960/42525 [28:51<35:04, 11.20it/s]

 45%|████████████████                    | 18964/42525 [28:52<33:58, 11.56it/s]

 45%|████████████████                    | 18968/42525 [28:52<36:24, 10.78it/s]

 45%|████████████████                    | 18972/42525 [28:52<34:53, 11.25it/s]

 45%|████████████████                    | 18976/42525 [28:53<34:07, 11.50it/s]

 45%|████████████████                    | 18980/42525 [28:53<36:10, 10.85it/s]

 45%|████████████████                    | 18984/42525 [28:54<35:59, 10.90it/s]

 45%|████████████████                    | 18988/42525 [28:54<35:10, 11.15it/s]

 45%|████████████████                    | 18992/42525 [28:54<33:27, 11.72it/s]

 45%|████████████████                    | 18996/42525 [28:55<34:06, 11.50it/s]

 45%|████████████████                    | 19000/42525 [28:55<31:39, 12.38it/s]

 45%|████████████████                    | 19004/42525 [28:55<30:49, 12.72it/s]

 45%|████████████████                    | 19008/42525 [28:55<30:15, 12.95it/s]

 45%|████████████████                    | 19012/42525 [28:56<30:53, 12.69it/s]

 45%|████████████████                    | 19016/42525 [28:56<33:16, 11.78it/s]

 45%|████████████████                    | 19020/42525 [28:56<32:59, 11.88it/s]

 45%|████████████████                    | 19024/42525 [28:57<31:26, 12.46it/s]

 45%|████████████████                    | 19028/42525 [28:57<34:38, 11.30it/s]

 45%|████████████████                    | 19032/42525 [28:58<33:41, 11.62it/s]

 45%|████████████████                    | 19034/42525 [28:58<32:52, 11.91it/s]

 45%|████████████████                    | 19038/42525 [28:58<34:41, 11.28it/s]

 45%|████████████████                    | 19042/42525 [28:58<33:18, 11.75it/s]

 45%|████████████████                    | 19046/42525 [28:59<32:46, 11.94it/s]

 45%|████████████████▏                   | 19050/42525 [28:59<33:23, 11.72it/s]

 45%|████████████████▏                   | 19054/42525 [28:59<32:39, 11.98it/s]

 45%|████████████████▏                   | 19058/42525 [29:00<34:45, 11.25it/s]

 45%|████████████████▏                   | 19062/42525 [29:00<32:54, 11.88it/s]

 45%|████████████████▏                   | 19066/42525 [29:00<33:16, 11.75it/s]

 45%|████████████████▏                   | 19070/42525 [29:01<34:05, 11.47it/s]

 45%|████████████████▏                   | 19074/42525 [29:01<35:43, 10.94it/s]

 45%|████████████████▏                   | 19078/42525 [29:02<36:45, 10.63it/s]

 45%|████████████████▏                   | 19082/42525 [29:02<35:00, 11.16it/s]

 45%|████████████████▏                   | 19086/42525 [29:02<34:42, 11.25it/s]

 45%|████████████████▏                   | 19090/42525 [29:03<36:13, 10.78it/s]

 45%|████████████████▏                   | 19094/42525 [29:03<35:11, 11.10it/s]

 45%|████████████████▏                   | 19098/42525 [29:03<34:11, 11.42it/s]

 45%|████████████████▏                   | 19102/42525 [29:04<34:31, 11.31it/s]

 45%|████████████████▏                   | 19106/42525 [29:04<34:58, 11.16it/s]

 45%|████████████████▏                   | 19110/42525 [29:04<35:17, 11.06it/s]

 45%|████████████████▏                   | 19114/42525 [29:05<34:23, 11.34it/s]

 45%|████████████████▏                   | 19118/42525 [29:05<34:46, 11.22it/s]

 45%|████████████████▏                   | 19122/42525 [29:05<33:01, 11.81it/s]

 45%|████████████████▏                   | 19126/42525 [29:06<34:34, 11.28it/s]

 45%|████████████████▏                   | 19130/42525 [29:06<32:08, 12.13it/s]

 45%|████████████████▏                   | 19134/42525 [29:06<33:24, 11.67it/s]

 45%|████████████████▏                   | 19138/42525 [29:07<33:29, 11.64it/s]

 45%|████████████████▏                   | 19142/42525 [29:07<33:20, 11.69it/s]

 45%|████████████████▏                   | 19146/42525 [29:07<33:49, 11.52it/s]

 45%|████████████████▏                   | 19150/42525 [29:08<33:17, 11.70it/s]

 45%|████████████████▏                   | 19154/42525 [29:08<33:01, 11.80it/s]

 45%|████████████████▏                   | 19158/42525 [29:09<34:18, 11.35it/s]

 45%|████████████████▏                   | 19162/42525 [29:09<34:27, 11.30it/s]

 45%|████████████████▏                   | 19164/42525 [29:09<34:09, 11.40it/s]

 45%|████████████████▏                   | 19168/42525 [29:09<36:57, 10.53it/s]

 45%|████████████████▏                   | 19172/42525 [29:10<36:48, 10.57it/s]

 45%|████████████████▏                   | 19176/42525 [29:10<35:00, 11.11it/s]

 45%|████████████████▏                   | 19180/42525 [29:11<34:36, 11.24it/s]

 45%|████████████████▏                   | 19184/42525 [29:11<36:05, 10.78it/s]

 45%|████████████████▏                   | 19188/42525 [29:11<35:48, 10.86it/s]

 45%|████████████████▏                   | 19192/42525 [29:12<35:21, 11.00it/s]

 45%|████████████████▎                   | 19196/42525 [29:12<36:23, 10.68it/s]

 45%|████████████████▎                   | 19200/42525 [29:12<35:04, 11.08it/s]

 45%|████████████████▎                   | 19204/42525 [29:13<34:53, 11.14it/s]

 45%|████████████████▎                   | 19208/42525 [29:13<37:06, 10.47it/s]

 45%|████████████████▎                   | 19212/42525 [29:14<36:16, 10.71it/s]

 45%|████████████████▎                   | 19216/42525 [29:14<34:44, 11.18it/s]

 45%|████████████████▎                   | 19220/42525 [29:14<34:49, 11.15it/s]

 45%|████████████████▎                   | 19224/42525 [29:15<35:13, 11.02it/s]

 45%|████████████████▎                   | 19228/42525 [29:15<34:05, 11.39it/s]

 45%|████████████████▎                   | 19232/42525 [29:15<33:33, 11.57it/s]

 45%|████████████████▎                   | 19236/42525 [29:16<34:24, 11.28it/s]

 45%|████████████████▎                   | 19240/42525 [29:16<33:44, 11.50it/s]

 45%|████████████████▎                   | 19244/42525 [29:16<33:13, 11.68it/s]

 45%|████████████████▎                   | 19248/42525 [29:17<34:33, 11.23it/s]

 45%|████████████████▎                   | 19252/42525 [29:17<33:57, 11.42it/s]

 45%|████████████████▎                   | 19256/42525 [29:17<34:03, 11.39it/s]

 45%|████████████████▎                   | 19260/42525 [29:18<36:24, 10.65it/s]

 45%|████████████████▎                   | 19264/42525 [29:18<34:47, 11.14it/s]

 45%|████████████████▎                   | 19268/42525 [29:18<33:49, 11.46it/s]

 45%|████████████████▎                   | 19272/42525 [29:19<33:33, 11.55it/s]

 45%|████████████████▎                   | 19276/42525 [29:19<35:04, 11.05it/s]

 45%|████████████████▎                   | 19280/42525 [29:20<35:16, 10.98it/s]

 45%|████████████████▎                   | 19284/42525 [29:20<34:23, 11.26it/s]

 45%|████████████████▎                   | 19288/42525 [29:20<34:33, 11.21it/s]

 45%|████████████████▎                   | 19292/42525 [29:21<34:32, 11.21it/s]

 45%|████████████████▎                   | 19296/42525 [29:21<34:28, 11.23it/s]

 45%|████████████████▎                   | 19298/42525 [29:21<34:58, 11.07it/s]

 45%|████████████████▎                   | 19302/42525 [29:22<36:23, 10.64it/s]

 45%|████████████████▎                   | 19306/42525 [29:22<37:09, 10.42it/s]

 45%|████████████████▎                   | 19308/42525 [29:22<36:03, 10.73it/s]

 45%|████████████████▎                   | 19312/42525 [29:23<37:27, 10.33it/s]

 45%|████████████████▎                   | 19316/42525 [29:23<35:21, 10.94it/s]

 45%|████████████████▎                   | 19320/42525 [29:23<34:00, 11.37it/s]

 45%|████████████████▎                   | 19324/42525 [29:24<34:35, 11.18it/s]

 45%|████████████████▎                   | 19328/42525 [29:24<36:20, 10.64it/s]

 45%|████████████████▎                   | 19332/42525 [29:24<36:08, 10.70it/s]

 45%|████████████████▎                   | 19336/42525 [29:25<34:29, 11.21it/s]

 45%|████████████████▎                   | 19340/42525 [29:25<35:04, 11.02it/s]

 45%|████████████████▍                   | 19344/42525 [29:25<34:20, 11.25it/s]

 45%|████████████████▍                   | 19348/42525 [29:26<33:40, 11.47it/s]

 46%|████████████████▍                   | 19352/42525 [29:26<33:49, 11.42it/s]

 46%|████████████████▍                   | 19356/42525 [29:26<33:56, 11.38it/s]

 46%|████████████████▍                   | 19360/42525 [29:27<34:11, 11.29it/s]

 46%|████████████████▍                   | 19364/42525 [29:27<33:28, 11.53it/s]

 46%|████████████████▍                   | 19368/42525 [29:27<33:03, 11.68it/s]

 46%|████████████████▍                   | 19372/42525 [29:28<34:42, 11.12it/s]

 46%|████████████████▍                   | 19376/42525 [29:28<34:54, 11.05it/s]

 46%|████████████████▍                   | 19380/42525 [29:29<35:37, 10.83it/s]

 46%|████████████████▍                   | 19384/42525 [29:29<34:13, 11.27it/s]

 46%|████████████████▍                   | 19388/42525 [29:29<33:28, 11.52it/s]

 46%|████████████████▍                   | 19392/42525 [29:30<33:06, 11.65it/s]

 46%|████████████████▍                   | 19396/42525 [29:30<32:59, 11.68it/s]

 46%|████████████████▍                   | 19400/42525 [29:30<33:12, 11.61it/s]

 46%|████████████████▍                   | 19404/42525 [29:31<32:59, 11.68it/s]

 46%|████████████████▍                   | 19408/42525 [29:31<33:06, 11.64it/s]

 46%|████████████████▍                   | 19412/42525 [29:31<34:36, 11.13it/s]

 46%|████████████████▍                   | 19416/42525 [29:32<34:30, 11.16it/s]

 46%|████████████████▍                   | 19420/42525 [29:32<35:39, 10.80it/s]

 46%|████████████████▍                   | 19424/42525 [29:32<36:06, 10.66it/s]

 46%|████████████████▍                   | 19428/42525 [29:33<34:23, 11.19it/s]

 46%|████████████████▍                   | 19432/42525 [29:33<34:00, 11.32it/s]

 46%|████████████████▍                   | 19436/42525 [29:34<34:52, 11.03it/s]

 46%|████████████████▍                   | 19440/42525 [29:34<34:20, 11.20it/s]

 46%|████████████████▍                   | 19444/42525 [29:34<33:43, 11.41it/s]

 46%|████████████████▍                   | 19448/42525 [29:35<33:17, 11.55it/s]

 46%|████████████████▍                   | 19452/42525 [29:35<33:38, 11.43it/s]

 46%|████████████████▍                   | 19456/42525 [29:35<33:11, 11.59it/s]

 46%|████████████████▍                   | 19460/42525 [29:36<35:00, 10.98it/s]

 46%|████████████████▍                   | 19464/42525 [29:36<34:18, 11.20it/s]

 46%|████████████████▍                   | 19468/42525 [29:36<33:28, 11.48it/s]

 46%|████████████████▍                   | 19472/42525 [29:37<33:48, 11.36it/s]

 46%|████████████████▍                   | 19476/42525 [29:37<33:16, 11.54it/s]

 46%|████████████████▍                   | 19480/42525 [29:37<34:20, 11.19it/s]

 46%|████████████████▍                   | 19482/42525 [29:38<33:56, 11.32it/s]

 46%|████████████████▍                   | 19486/42525 [29:38<34:55, 11.00it/s]

 46%|████████████████▍                   | 19490/42525 [29:38<35:03, 10.95it/s]

 46%|████████████████▌                   | 19494/42525 [29:39<33:50, 11.34it/s]

 46%|████████████████▌                   | 19498/42525 [29:39<33:17, 11.53it/s]

 46%|████████████████▌                   | 19502/42525 [29:39<33:54, 11.32it/s]

 46%|████████████████▌                   | 19506/42525 [29:40<34:47, 11.03it/s]

 46%|████████████████▌                   | 19510/42525 [29:40<35:39, 10.76it/s]

 46%|████████████████▌                   | 19514/42525 [29:40<35:43, 10.74it/s]

 46%|████████████████▌                   | 19518/42525 [29:41<35:25, 10.82it/s]

 46%|████████████████▌                   | 19522/42525 [29:41<34:16, 11.18it/s]

 46%|████████████████▌                   | 19526/42525 [29:42<34:55, 10.98it/s]

 46%|████████████████▌                   | 19530/42525 [29:42<35:08, 10.91it/s]

 46%|████████████████▌                   | 19534/42525 [29:42<33:54, 11.30it/s]

 46%|████████████████▌                   | 19538/42525 [29:43<33:57, 11.28it/s]

 46%|████████████████▌                   | 19542/42525 [29:43<34:27, 11.12it/s]

 46%|████████████████▌                   | 19546/42525 [29:43<34:06, 11.23it/s]

 46%|████████████████▌                   | 19550/42525 [29:44<35:27, 10.80it/s]

 46%|████████████████▌                   | 19554/42525 [29:44<33:58, 11.27it/s]

 46%|████████████████▌                   | 19558/42525 [29:44<33:17, 11.50it/s]

 46%|████████████████▌                   | 19562/42525 [29:45<33:16, 11.50it/s]

 46%|████████████████▌                   | 19566/42525 [29:45<32:45, 11.68it/s]

 46%|████████████████▌                   | 19570/42525 [29:45<33:29, 11.43it/s]

 46%|████████████████▌                   | 19574/42525 [29:46<32:50, 11.65it/s]

 46%|████████████████▌                   | 19578/42525 [29:46<32:40, 11.70it/s]

 46%|████████████████▌                   | 19582/42525 [29:47<33:12, 11.52it/s]

 46%|████████████████▌                   | 19586/42525 [29:47<34:08, 11.20it/s]

 46%|████████████████▌                   | 19590/42525 [29:47<33:52, 11.28it/s]

 46%|████████████████▌                   | 19594/42525 [29:48<35:33, 10.75it/s]

 46%|████████████████▌                   | 19598/42525 [29:48<34:45, 10.99it/s]

 46%|████████████████▌                   | 19602/42525 [29:48<35:08, 10.87it/s]

 46%|████████████████▌                   | 19606/42525 [29:49<35:13, 10.84it/s]

 46%|████████████████▌                   | 19610/42525 [29:49<34:49, 10.97it/s]

 46%|████████████████▌                   | 19614/42525 [29:49<34:54, 10.94it/s]

 46%|████████████████▌                   | 19618/42525 [29:50<35:04, 10.89it/s]

 46%|████████████████▌                   | 19622/42525 [29:50<33:51, 11.27it/s]

 46%|████████████████▌                   | 19626/42525 [29:51<34:16, 11.14it/s]

 46%|████████████████▌                   | 19630/42525 [29:51<35:34, 10.73it/s]

 46%|████████████████▌                   | 19634/42525 [29:51<34:04, 11.20it/s]

 46%|████████████████▌                   | 19638/42525 [29:52<33:26, 11.41it/s]

 46%|████████████████▋                   | 19642/42525 [29:52<34:32, 11.04it/s]

 46%|████████████████▋                   | 19646/42525 [29:52<34:05, 11.19it/s]

 46%|████████████████▋                   | 19650/42525 [29:53<34:22, 11.09it/s]

 46%|████████████████▋                   | 19654/42525 [29:53<33:29, 11.38it/s]

 46%|████████████████▋                   | 19658/42525 [29:53<33:37, 11.33it/s]

 46%|████████████████▋                   | 19662/42525 [29:54<33:08, 11.50it/s]

 46%|████████████████▋                   | 19666/42525 [29:54<33:15, 11.45it/s]

 46%|████████████████▋                   | 19670/42525 [29:54<32:53, 11.58it/s]

 46%|████████████████▋                   | 19674/42525 [29:55<32:54, 11.57it/s]

 46%|████████████████▋                   | 19678/42525 [29:55<34:09, 11.15it/s]

 46%|████████████████▋                   | 19682/42525 [29:55<33:45, 11.28it/s]

 46%|████████████████▋                   | 19686/42525 [29:56<34:12, 11.13it/s]

 46%|████████████████▋                   | 19690/42525 [29:56<34:02, 11.18it/s]

 46%|████████████████▋                   | 19694/42525 [29:57<33:18, 11.42it/s]

 46%|████████████████▋                   | 19698/42525 [29:57<34:18, 11.09it/s]

 46%|████████████████▋                   | 19702/42525 [29:57<33:37, 11.31it/s]

 46%|████████████████▋                   | 19706/42525 [29:58<33:02, 11.51it/s]

 46%|████████████████▋                   | 19710/42525 [29:58<33:14, 11.44it/s]

 46%|████████████████▋                   | 19714/42525 [29:58<34:55, 10.89it/s]

 46%|████████████████▋                   | 19718/42525 [29:59<34:19, 11.07it/s]

 46%|████████████████▋                   | 19722/42525 [29:59<34:34, 10.99it/s]

 46%|████████████████▋                   | 19726/42525 [29:59<35:33, 10.68it/s]

 46%|████████████████▋                   | 19728/42525 [30:00<34:43, 10.94it/s]

 46%|████████████████▋                   | 19732/42525 [30:00<35:16, 10.77it/s]

 46%|████████████████▋                   | 19736/42525 [30:00<33:58, 11.18it/s]

 46%|████████████████▋                   | 19740/42525 [30:01<33:45, 11.25it/s]

 46%|████████████████▋                   | 19744/42525 [30:01<33:54, 11.20it/s]

 46%|████████████████▋                   | 19748/42525 [30:01<33:18, 11.40it/s]

 46%|████████████████▋                   | 19752/42525 [30:02<33:04, 11.47it/s]

 46%|████████████████▋                   | 19756/42525 [30:02<33:44, 11.25it/s]

 46%|████████████████▋                   | 19758/42525 [30:02<33:25, 11.35it/s]

 46%|████████████████▋                   | 19762/42525 [30:03<34:04, 11.13it/s]

 46%|████████████████▋                   | 19764/42525 [30:03<34:07, 11.12it/s]

 46%|████████████████▋                   | 19768/42525 [30:03<35:51, 10.58it/s]

 46%|████████████████▋                   | 19772/42525 [30:04<34:23, 11.03it/s]

 47%|████████████████▋                   | 19776/42525 [30:04<36:11, 10.48it/s]

 47%|████████████████▋                   | 19780/42525 [30:04<34:11, 11.09it/s]

 47%|████████████████▋                   | 19784/42525 [30:05<33:40, 11.26it/s]

 47%|████████████████▊                   | 19788/42525 [30:05<34:49, 10.88it/s]

 47%|████████████████▊                   | 19792/42525 [30:05<35:53, 10.55it/s]

 47%|████████████████▊                   | 19796/42525 [30:06<34:02, 11.13it/s]

 47%|████████████████▊                   | 19798/42525 [30:06<33:41, 11.24it/s]

 47%|████████████████▊                   | 19802/42525 [30:06<35:32, 10.66it/s]

 47%|████████████████▊                   | 19806/42525 [30:07<33:48, 11.20it/s]

 47%|████████████████▊                   | 19810/42525 [30:07<33:06, 11.44it/s]

 47%|████████████████▊                   | 19814/42525 [30:07<32:41, 11.58it/s]

 47%|████████████████▊                   | 19818/42525 [30:08<32:09, 11.77it/s]

 47%|████████████████▊                   | 19822/42525 [30:08<33:29, 11.30it/s]

 47%|████████████████▊                   | 19826/42525 [30:08<33:48, 11.19it/s]

 47%|████████████████▊                   | 19830/42525 [30:09<32:52, 11.51it/s]

 47%|████████████████▊                   | 19834/42525 [30:09<33:59, 11.13it/s]

 47%|████████████████▊                   | 19838/42525 [30:09<33:58, 11.13it/s]

 47%|████████████████▊                   | 19842/42525 [30:10<33:07, 11.41it/s]

 47%|████████████████▊                   | 19846/42525 [30:10<34:00, 11.11it/s]

 47%|████████████████▊                   | 19850/42525 [30:11<33:20, 11.34it/s]

 47%|████████████████▊                   | 19854/42525 [30:11<33:28, 11.29it/s]

 47%|████████████████▊                   | 19858/42525 [30:11<34:10, 11.06it/s]

 47%|████████████████▊                   | 19862/42525 [30:12<34:00, 11.11it/s]

 47%|████████████████▊                   | 19866/42525 [30:12<34:01, 11.10it/s]

 47%|████████████████▊                   | 19870/42525 [30:12<34:25, 10.97it/s]

 47%|████████████████▊                   | 19874/42525 [30:13<33:12, 11.37it/s]

 47%|████████████████▊                   | 19878/42525 [30:13<32:52, 11.48it/s]

 47%|████████████████▊                   | 19882/42525 [30:13<33:48, 11.16it/s]

 47%|████████████████▊                   | 19886/42525 [30:14<34:46, 10.85it/s]

 47%|████████████████▊                   | 19890/42525 [30:14<33:30, 11.26it/s]

 47%|████████████████▊                   | 19894/42525 [30:14<33:17, 11.33it/s]

 47%|████████████████▊                   | 19898/42525 [30:15<34:00, 11.09it/s]

 47%|████████████████▊                   | 19902/42525 [30:15<33:16, 11.33it/s]

 47%|████████████████▊                   | 19906/42525 [30:16<33:19, 11.31it/s]

 47%|████████████████▊                   | 19910/42525 [30:16<34:35, 10.89it/s]

 47%|████████████████▊                   | 19914/42525 [30:16<35:06, 10.73it/s]

 47%|████████████████▊                   | 19918/42525 [30:17<34:06, 11.05it/s]

 47%|████████████████▊                   | 19922/42525 [30:17<33:17, 11.32it/s]

 47%|████████████████▊                   | 19926/42525 [30:17<34:08, 11.03it/s]

 47%|████████████████▊                   | 19930/42525 [30:18<34:33, 10.90it/s]

 47%|████████████████▉                   | 19934/42525 [30:18<34:09, 11.03it/s]

 47%|████████████████▉                   | 19938/42525 [30:18<33:59, 11.07it/s]

 47%|████████████████▉                   | 19942/42525 [30:19<35:13, 10.68it/s]

 47%|████████████████▉                   | 19946/42525 [30:19<34:05, 11.04it/s]

 47%|████████████████▉                   | 19950/42525 [30:20<31:49, 11.82it/s]

 47%|████████████████▉                   | 19954/42525 [30:20<31:52, 11.80it/s]

 47%|████████████████▉                   | 19958/42525 [30:20<32:37, 11.53it/s]

 47%|████████████████▉                   | 19962/42525 [30:21<32:07, 11.71it/s]

 47%|████████████████▉                   | 19966/42525 [30:21<29:45, 12.64it/s]

 47%|████████████████▉                   | 19970/42525 [30:21<29:41, 12.66it/s]

 47%|████████████████▉                   | 19974/42525 [30:22<33:02, 11.38it/s]

 47%|████████████████▉                   | 19978/42525 [30:22<33:24, 11.25it/s]

 47%|████████████████▉                   | 19982/42525 [30:22<32:32, 11.54it/s]

 47%|████████████████▉                   | 19986/42525 [30:23<31:40, 11.86it/s]

 47%|████████████████▉                   | 19988/42525 [30:23<31:22, 11.97it/s]

 47%|████████████████▉                   | 19992/42525 [30:23<33:21, 11.26it/s]

 47%|████████████████▉                   | 19996/42525 [30:23<31:06, 12.07it/s]

 47%|████████████████▉                   | 20000/42525 [30:24<30:08, 12.45it/s]

 47%|████████████████▉                   | 20004/42525 [30:24<31:57, 11.75it/s]

 47%|████████████████▉                   | 20008/42525 [30:24<30:58, 12.12it/s]

 47%|████████████████▉                   | 20012/42525 [30:25<30:57, 12.12it/s]

 47%|████████████████▉                   | 20016/42525 [30:25<32:00, 11.72it/s]

 47%|████████████████▉                   | 20020/42525 [30:25<30:44, 12.20it/s]

 47%|████████████████▉                   | 20024/42525 [30:26<32:18, 11.60it/s]

 47%|████████████████▉                   | 20028/42525 [30:26<32:21, 11.58it/s]

 47%|████████████████▉                   | 20032/42525 [30:26<31:46, 11.80it/s]

 47%|████████████████▉                   | 20036/42525 [30:27<31:44, 11.81it/s]

 47%|████████████████▉                   | 20040/42525 [30:27<31:54, 11.74it/s]

 47%|████████████████▉                   | 20044/42525 [30:27<32:50, 11.41it/s]

 47%|████████████████▉                   | 20048/42525 [30:28<33:55, 11.04it/s]

 47%|████████████████▉                   | 20052/42525 [30:28<32:55, 11.38it/s]

 47%|████████████████▉                   | 20056/42525 [30:29<33:06, 11.31it/s]

 47%|████████████████▉                   | 20060/42525 [30:29<32:59, 11.35it/s]

 47%|████████████████▉                   | 20062/42525 [30:29<32:47, 11.42it/s]

 47%|████████████████▉                   | 20066/42525 [30:29<33:49, 11.06it/s]

 47%|████████████████▉                   | 20070/42525 [30:30<32:47, 11.41it/s]

 47%|████████████████▉                   | 20074/42525 [30:30<34:12, 10.94it/s]

 47%|████████████████▉                   | 20078/42525 [30:31<34:09, 10.95it/s]

 47%|█████████████████                   | 20082/42525 [30:31<33:25, 11.19it/s]

 47%|█████████████████                   | 20086/42525 [30:31<33:22, 11.21it/s]

 47%|█████████████████                   | 20090/42525 [30:32<33:29, 11.16it/s]

 47%|█████████████████                   | 20094/42525 [30:32<33:00, 11.32it/s]

 47%|█████████████████                   | 20098/42525 [30:32<33:17, 11.23it/s]

 47%|█████████████████                   | 20102/42525 [30:33<34:11, 10.93it/s]

 47%|█████████████████                   | 20106/42525 [30:33<32:56, 11.34it/s]

 47%|█████████████████                   | 20110/42525 [30:33<32:50, 11.38it/s]

 47%|█████████████████                   | 20114/42525 [30:34<32:44, 11.41it/s]

 47%|█████████████████                   | 20118/42525 [30:34<33:37, 11.10it/s]

 47%|█████████████████                   | 20122/42525 [30:35<34:53, 10.70it/s]

 47%|█████████████████                   | 20126/42525 [30:35<33:34, 11.12it/s]

 47%|█████████████████                   | 20130/42525 [30:35<33:03, 11.29it/s]

 47%|█████████████████                   | 20134/42525 [30:36<34:34, 10.80it/s]

 47%|█████████████████                   | 20138/42525 [30:36<32:49, 11.36it/s]

 47%|█████████████████                   | 20142/42525 [30:36<33:15, 11.21it/s]

 47%|█████████████████                   | 20144/42525 [30:36<32:47, 11.37it/s]

 47%|█████████████████                   | 20148/42525 [30:37<34:04, 10.95it/s]

 47%|█████████████████                   | 20152/42525 [30:37<32:54, 11.33it/s]

 47%|█████████████████                   | 20156/42525 [30:38<33:13, 11.22it/s]

 47%|█████████████████                   | 20160/42525 [30:38<33:22, 11.17it/s]

 47%|█████████████████                   | 20164/42525 [30:38<32:31, 11.46it/s]

 47%|█████████████████                   | 20168/42525 [30:39<32:48, 11.36it/s]

 47%|█████████████████                   | 20172/42525 [30:39<32:02, 11.63it/s]

 47%|█████████████████                   | 20176/42525 [30:39<31:34, 11.80it/s]

 47%|█████████████████                   | 20180/42525 [30:40<32:46, 11.37it/s]

 47%|█████████████████                   | 20184/42525 [30:40<32:48, 11.35it/s]

 47%|█████████████████                   | 20188/42525 [30:40<34:05, 10.92it/s]

 47%|█████████████████                   | 20192/42525 [30:41<34:08, 10.90it/s]

 47%|█████████████████                   | 20196/42525 [30:41<32:41, 11.38it/s]

 47%|█████████████████                   | 20198/42525 [30:41<32:22, 11.50it/s]

 48%|█████████████████                   | 20202/42525 [30:42<33:15, 11.19it/s]

 48%|█████████████████                   | 20206/42525 [30:42<33:36, 11.07it/s]

 48%|█████████████████                   | 20210/42525 [30:42<34:15, 10.86it/s]

 48%|█████████████████                   | 20214/42525 [30:43<34:38, 10.73it/s]

 48%|█████████████████                   | 20218/42525 [30:43<33:49, 10.99it/s]

 48%|█████████████████                   | 20222/42525 [30:43<32:37, 11.39it/s]

 48%|█████████████████                   | 20224/42525 [30:44<32:21, 11.49it/s]

 48%|█████████████████                   | 20228/42525 [30:44<34:41, 10.71it/s]

 48%|█████████████████▏                  | 20232/42525 [30:44<33:55, 10.95it/s]

 48%|█████████████████▏                  | 20236/42525 [30:45<32:45, 11.34it/s]

 48%|█████████████████▏                  | 20240/42525 [30:45<32:47, 11.33it/s]

 48%|█████████████████▏                  | 20244/42525 [30:45<33:51, 10.97it/s]

 48%|█████████████████▏                  | 20248/42525 [30:46<32:49, 11.31it/s]

 48%|█████████████████▏                  | 20252/42525 [30:46<33:00, 11.24it/s]

 48%|█████████████████▏                  | 20256/42525 [30:47<32:10, 11.54it/s]

 48%|█████████████████▏                  | 20260/42525 [30:47<33:05, 11.21it/s]

 48%|█████████████████▏                  | 20264/42525 [30:47<32:45, 11.32it/s]

 48%|█████████████████▏                  | 20268/42525 [30:48<33:58, 10.92it/s]

 48%|█████████████████▏                  | 20272/42525 [30:48<33:24, 11.10it/s]

 48%|█████████████████▏                  | 20276/42525 [30:48<32:19, 11.47it/s]

 48%|█████████████████▏                  | 20280/42525 [30:49<32:36, 11.37it/s]

 48%|█████████████████▏                  | 20284/42525 [30:49<32:12, 11.51it/s]

 48%|█████████████████▏                  | 20288/42525 [30:49<32:56, 11.25it/s]

 48%|█████████████████▏                  | 20292/42525 [30:50<32:45, 11.31it/s]

 48%|█████████████████▏                  | 20296/42525 [30:50<32:58, 11.24it/s]

 48%|█████████████████▏                  | 20300/42525 [30:50<33:00, 11.22it/s]

 48%|█████████████████▏                  | 20304/42525 [30:51<32:06, 11.53it/s]

 48%|█████████████████▏                  | 20308/42525 [30:51<32:21, 11.44it/s]

 48%|█████████████████▏                  | 20312/42525 [30:51<32:46, 11.30it/s]

 48%|█████████████████▏                  | 20316/42525 [30:52<32:31, 11.38it/s]

 48%|█████████████████▏                  | 20320/42525 [30:52<33:05, 11.18it/s]

 48%|█████████████████▏                  | 20324/42525 [30:53<33:55, 10.91it/s]

 48%|█████████████████▏                  | 20328/42525 [30:53<33:37, 11.00it/s]

 48%|█████████████████▏                  | 20332/42525 [30:53<33:00, 11.20it/s]

 48%|█████████████████▏                  | 20336/42525 [30:54<33:19, 11.10it/s]

 48%|█████████████████▏                  | 20340/42525 [30:54<32:11, 11.49it/s]

 48%|█████████████████▏                  | 20344/42525 [30:54<33:01, 11.19it/s]

 48%|█████████████████▏                  | 20348/42525 [30:55<33:16, 11.11it/s]

 48%|█████████████████▏                  | 20352/42525 [30:55<33:11, 11.14it/s]

 48%|█████████████████▏                  | 20356/42525 [30:55<33:08, 11.15it/s]

 48%|█████████████████▏                  | 20360/42525 [30:56<32:27, 11.38it/s]

 48%|█████████████████▏                  | 20364/42525 [30:56<32:27, 11.38it/s]

 48%|█████████████████▏                  | 20368/42525 [30:56<33:18, 11.09it/s]

 48%|█████████████████▏                  | 20370/42525 [30:57<32:54, 11.22it/s]

 48%|█████████████████▏                  | 20374/42525 [30:57<33:15, 11.10it/s]

 48%|█████████████████▎                  | 20378/42525 [30:57<34:17, 10.76it/s]

 48%|█████████████████▎                  | 20382/42525 [30:58<33:12, 11.11it/s]

 48%|█████████████████▎                  | 20386/42525 [30:58<32:14, 11.45it/s]

 48%|█████████████████▎                  | 20390/42525 [30:58<32:40, 11.29it/s]

 48%|█████████████████▎                  | 20394/42525 [30:59<33:32, 11.00it/s]

 48%|█████████████████▎                  | 20396/42525 [30:59<33:34, 10.98it/s]

 48%|█████████████████▎                  | 20400/42525 [30:59<33:39, 10.96it/s]

 48%|█████████████████▎                  | 20404/42525 [31:00<34:30, 10.68it/s]

 48%|█████████████████▎                  | 20408/42525 [31:00<33:25, 11.03it/s]

 48%|█████████████████▎                  | 20412/42525 [31:00<33:12, 11.10it/s]

 48%|█████████████████▎                  | 20416/42525 [31:01<33:29, 11.00it/s]

 48%|█████████████████▎                  | 20420/42525 [31:01<32:21, 11.39it/s]

 48%|█████████████████▎                  | 20424/42525 [31:02<31:51, 11.56it/s]

 48%|█████████████████▎                  | 20428/42525 [31:02<32:52, 11.20it/s]

 48%|█████████████████▎                  | 20432/42525 [31:02<31:59, 11.51it/s]

 48%|█████████████████▎                  | 20436/42525 [31:03<32:50, 11.21it/s]

 48%|█████████████████▎                  | 20440/42525 [31:03<32:05, 11.47it/s]

 48%|█████████████████▎                  | 20444/42525 [31:03<33:38, 10.94it/s]

 48%|█████████████████▎                  | 20448/42525 [31:04<34:35, 10.63it/s]

 48%|█████████████████▎                  | 20452/42525 [31:04<34:17, 10.73it/s]

 48%|█████████████████▎                  | 20456/42525 [31:04<33:02, 11.13it/s]

 48%|█████████████████▎                  | 20460/42525 [31:05<32:17, 11.39it/s]

 48%|█████████████████▎                  | 20464/42525 [31:05<31:34, 11.65it/s]

 48%|█████████████████▎                  | 20468/42525 [31:05<31:46, 11.57it/s]

 48%|█████████████████▎                  | 20472/42525 [31:06<32:54, 11.17it/s]

 48%|█████████████████▎                  | 20476/42525 [31:06<32:30, 11.30it/s]

 48%|█████████████████▎                  | 20480/42525 [31:07<31:46, 11.57it/s]

 48%|█████████████████▎                  | 20484/42525 [31:07<31:23, 11.70it/s]

 48%|█████████████████▎                  | 20488/42525 [31:07<32:38, 11.25it/s]

 48%|█████████████████▎                  | 20492/42525 [31:08<31:43, 11.57it/s]

 48%|█████████████████▎                  | 20496/42525 [31:08<31:22, 11.70it/s]

 48%|█████████████████▎                  | 20500/42525 [31:08<32:06, 11.44it/s]

 48%|█████████████████▎                  | 20504/42525 [31:09<31:25, 11.68it/s]

 48%|█████████████████▎                  | 20508/42525 [31:09<31:15, 11.74it/s]

 48%|█████████████████▎                  | 20512/42525 [31:09<32:33, 11.27it/s]

 48%|█████████████████▎                  | 20516/42525 [31:10<33:14, 11.03it/s]

 48%|█████████████████▎                  | 20520/42525 [31:10<33:34, 10.92it/s]

 48%|█████████████████▎                  | 20524/42525 [31:10<34:03, 10.77it/s]

 48%|█████████████████▍                  | 20528/42525 [31:11<33:52, 10.82it/s]

 48%|█████████████████▍                  | 20532/42525 [31:11<33:57, 10.79it/s]

 48%|█████████████████▍                  | 20536/42525 [31:12<33:31, 10.93it/s]

 48%|█████████████████▍                  | 20540/42525 [31:12<33:22, 10.98it/s]

 48%|█████████████████▍                  | 20544/42525 [31:12<33:43, 10.86it/s]

 48%|█████████████████▍                  | 20548/42525 [31:13<33:13, 11.02it/s]

 48%|█████████████████▍                  | 20552/42525 [31:13<32:50, 11.15it/s]

 48%|█████████████████▍                  | 20556/42525 [31:13<32:08, 11.39it/s]

 48%|█████████████████▍                  | 20560/42525 [31:14<32:45, 11.17it/s]

 48%|█████████████████▍                  | 20564/42525 [31:14<33:03, 11.07it/s]

 48%|█████████████████▍                  | 20568/42525 [31:14<33:11, 11.02it/s]

 48%|█████████████████▍                  | 20572/42525 [31:15<34:19, 10.66it/s]

 48%|█████████████████▍                  | 20576/42525 [31:15<34:07, 10.72it/s]

 48%|█████████████████▍                  | 20580/42525 [31:16<34:26, 10.62it/s]

 48%|█████████████████▍                  | 20584/42525 [31:16<33:16, 10.99it/s]

 48%|█████████████████▍                  | 20588/42525 [31:16<33:40, 10.86it/s]

 48%|█████████████████▍                  | 20592/42525 [31:17<33:14, 11.00it/s]

 48%|█████████████████▍                  | 20596/42525 [31:17<32:39, 11.19it/s]

 48%|█████████████████▍                  | 20600/42525 [31:17<31:51, 11.47it/s]

 48%|█████████████████▍                  | 20604/42525 [31:18<32:34, 11.21it/s]

 48%|█████████████████▍                  | 20608/42525 [31:18<33:02, 11.06it/s]

 48%|█████████████████▍                  | 20612/42525 [31:18<32:40, 11.18it/s]

 48%|█████████████████▍                  | 20616/42525 [31:19<31:44, 11.50it/s]

 48%|█████████████████▍                  | 20620/42525 [31:19<32:07, 11.37it/s]

 48%|█████████████████▍                  | 20624/42525 [31:19<31:24, 11.62it/s]

 49%|█████████████████▍                  | 20628/42525 [31:20<31:24, 11.62it/s]

 49%|█████████████████▍                  | 20632/42525 [31:20<32:37, 11.18it/s]

 49%|█████████████████▍                  | 20636/42525 [31:21<32:45, 11.13it/s]

 49%|█████████████████▍                  | 20640/42525 [31:21<31:59, 11.40it/s]

 49%|█████████████████▍                  | 20644/42525 [31:21<32:46, 11.13it/s]

 49%|█████████████████▍                  | 20648/42525 [31:22<31:38, 11.53it/s]

 49%|█████████████████▍                  | 20652/42525 [31:22<31:28, 11.58it/s]

 49%|█████████████████▍                  | 20656/42525 [31:22<32:57, 11.06it/s]

 49%|█████████████████▍                  | 20660/42525 [31:23<31:54, 11.42it/s]

 49%|█████████████████▍                  | 20664/42525 [31:23<31:54, 11.42it/s]

 49%|█████████████████▍                  | 20668/42525 [31:23<33:18, 10.94it/s]

 49%|█████████████████▌                  | 20672/42525 [31:24<33:14, 10.96it/s]

 49%|█████████████████▌                  | 20676/42525 [31:24<32:41, 11.14it/s]

 49%|█████████████████▌                  | 20680/42525 [31:24<32:27, 11.22it/s]

 49%|█████████████████▌                  | 20684/42525 [31:25<32:33, 11.18it/s]

 49%|█████████████████▌                  | 20688/42525 [31:25<32:23, 11.24it/s]

 49%|█████████████████▌                  | 20692/42525 [31:26<32:42, 11.12it/s]

 49%|█████████████████▌                  | 20696/42525 [31:26<31:58, 11.38it/s]

 49%|█████████████████▌                  | 20700/42525 [31:26<31:40, 11.48it/s]

 49%|█████████████████▌                  | 20704/42525 [31:27<31:28, 11.55it/s]

 49%|█████████████████▌                  | 20708/42525 [31:27<31:04, 11.70it/s]

 49%|█████████████████▌                  | 20712/42525 [31:27<32:03, 11.34it/s]

 49%|█████████████████▌                  | 20716/42525 [31:28<31:48, 11.43it/s]

 49%|█████████████████▌                  | 20720/42525 [31:28<31:27, 11.55it/s]

 49%|█████████████████▌                  | 20724/42525 [31:28<31:30, 11.53it/s]

 49%|█████████████████▌                  | 20728/42525 [31:29<31:09, 11.66it/s]

 49%|█████████████████▌                  | 20732/42525 [31:29<31:45, 11.43it/s]

 49%|█████████████████▌                  | 20736/42525 [31:29<32:12, 11.28it/s]

 49%|█████████████████▌                  | 20740/42525 [31:30<31:26, 11.55it/s]

 49%|█████████████████▌                  | 20744/42525 [31:30<31:22, 11.57it/s]

 49%|█████████████████▌                  | 20748/42525 [31:30<32:21, 11.22it/s]

 49%|█████████████████▌                  | 20752/42525 [31:31<32:32, 11.15it/s]

 49%|█████████████████▌                  | 20756/42525 [31:31<31:38, 11.47it/s]

 49%|█████████████████▌                  | 20760/42525 [31:31<32:00, 11.33it/s]

 49%|█████████████████▌                  | 20764/42525 [31:32<31:59, 11.34it/s]

 49%|█████████████████▌                  | 20768/42525 [31:32<31:21, 11.56it/s]

 49%|█████████████████▌                  | 20772/42525 [31:33<32:27, 11.17it/s]

 49%|█████████████████▌                  | 20776/42525 [31:33<31:54, 11.36it/s]

 49%|█████████████████▌                  | 20780/42525 [31:33<31:48, 11.39it/s]

 49%|█████████████████▌                  | 20784/42525 [31:34<32:47, 11.05it/s]

 49%|█████████████████▌                  | 20788/42525 [31:34<32:24, 11.18it/s]

 49%|█████████████████▌                  | 20792/42525 [31:34<32:03, 11.30it/s]

 49%|█████████████████▌                  | 20796/42525 [31:35<31:56, 11.34it/s]

 49%|█████████████████▌                  | 20800/42525 [31:35<32:04, 11.29it/s]

 49%|█████████████████▌                  | 20804/42525 [31:35<31:43, 11.41it/s]

 49%|█████████████████▌                  | 20808/42525 [31:36<31:08, 11.62it/s]

 49%|█████████████████▌                  | 20812/42525 [31:36<30:50, 11.73it/s]

 49%|█████████████████▌                  | 20816/42525 [31:36<30:43, 11.78it/s]

 49%|█████████████████▋                  | 20820/42525 [31:37<32:39, 11.07it/s]

 49%|█████████████████▋                  | 20824/42525 [31:37<32:52, 11.00it/s]

 49%|█████████████████▋                  | 20828/42525 [31:37<32:46, 11.03it/s]

 49%|█████████████████▋                  | 20832/42525 [31:38<32:24, 11.16it/s]

 49%|█████████████████▋                  | 20834/42525 [31:38<32:06, 11.26it/s]

 49%|█████████████████▋                  | 20838/42525 [31:38<34:24, 10.51it/s]

 49%|█████████████████▋                  | 20842/42525 [31:39<33:49, 10.68it/s]

 49%|█████████████████▋                  | 20846/42525 [31:39<33:19, 10.84it/s]

 49%|█████████████████▋                  | 20850/42525 [31:40<31:47, 11.36it/s]

 49%|█████████████████▋                  | 20852/42525 [31:40<31:29, 11.47it/s]

 49%|█████████████████▋                  | 20856/42525 [31:40<32:18, 11.18it/s]

 49%|█████████████████▋                  | 20860/42525 [31:40<31:42, 11.39it/s]

 49%|█████████████████▋                  | 20864/42525 [31:41<31:36, 11.42it/s]

 49%|█████████████████▋                  | 20868/42525 [31:41<32:18, 11.17it/s]

 49%|█████████████████▋                  | 20872/42525 [31:41<31:17, 11.53it/s]

 49%|█████████████████▋                  | 20876/42525 [31:42<30:55, 11.67it/s]

 49%|█████████████████▋                  | 20880/42525 [31:42<31:59, 11.27it/s]

 49%|█████████████████▋                  | 20884/42525 [31:43<32:23, 11.13it/s]

 49%|█████████████████▋                  | 20888/42525 [31:43<32:49, 10.99it/s]

 49%|█████████████████▋                  | 20892/42525 [31:43<31:42, 11.37it/s]

 49%|█████████████████▋                  | 20896/42525 [31:44<31:01, 11.62it/s]

 49%|█████████████████▋                  | 20900/42525 [31:44<32:05, 11.23it/s]

 49%|█████████████████▋                  | 20904/42525 [31:44<32:12, 11.19it/s]

 49%|█████████████████▋                  | 20908/42525 [31:45<31:59, 11.26it/s]

 49%|█████████████████▋                  | 20912/42525 [31:45<31:04, 11.59it/s]

 49%|█████████████████▋                  | 20916/42525 [31:45<30:55, 11.65it/s]

 49%|█████████████████▋                  | 20920/42525 [31:46<30:55, 11.65it/s]

 49%|█████████████████▋                  | 20924/42525 [31:46<31:06, 11.58it/s]

 49%|█████████████████▋                  | 20928/42525 [31:46<31:40, 11.36it/s]

 49%|█████████████████▋                  | 20932/42525 [31:47<31:06, 11.57it/s]

 49%|█████████████████▋                  | 20936/42525 [31:47<31:41, 11.35it/s]

 49%|█████████████████▋                  | 20940/42525 [31:47<31:52, 11.29it/s]

 49%|█████████████████▋                  | 20944/42525 [31:48<32:59, 10.90it/s]

 49%|█████████████████▋                  | 20948/42525 [31:48<31:43, 11.33it/s]

 49%|█████████████████▋                  | 20952/42525 [31:48<31:53, 11.27it/s]

 49%|█████████████████▋                  | 20956/42525 [31:49<31:05, 11.56it/s]

 49%|█████████████████▋                  | 20960/42525 [31:49<30:35, 11.75it/s]

 49%|█████████████████▋                  | 20964/42525 [31:50<31:15, 11.50it/s]

 49%|█████████████████▊                  | 20968/42525 [31:50<31:39, 11.35it/s]

 49%|█████████████████▊                  | 20972/42525 [31:50<31:18, 11.47it/s]

 49%|█████████████████▊                  | 20976/42525 [31:51<31:12, 11.51it/s]

 49%|█████████████████▊                  | 20980/42525 [31:51<31:29, 11.40it/s]

 49%|█████████████████▊                  | 20984/42525 [31:51<32:07, 11.18it/s]

 49%|█████████████████▊                  | 20988/42525 [31:52<31:07, 11.53it/s]

 49%|█████████████████▊                  | 20992/42525 [31:52<30:57, 11.59it/s]

 49%|█████████████████▊                  | 20996/42525 [31:52<30:53, 11.61it/s]

 49%|█████████████████▊                  | 21000/42525 [31:53<31:51, 11.26it/s]

 49%|█████████████████▊                  | 21004/42525 [31:53<31:05, 11.54it/s]

 49%|█████████████████▊                  | 21008/42525 [31:53<31:20, 11.44it/s]

 49%|█████████████████▊                  | 21012/42525 [31:54<31:43, 11.30it/s]

 49%|█████████████████▊                  | 21016/42525 [31:54<30:59, 11.57it/s]

 49%|█████████████████▊                  | 21020/42525 [31:54<30:35, 11.72it/s]

 49%|█████████████████▊                  | 21024/42525 [31:55<32:22, 11.07it/s]

 49%|█████████████████▊                  | 21028/42525 [31:55<32:54, 10.89it/s]

 49%|█████████████████▊                  | 21032/42525 [31:56<32:20, 11.08it/s]

 49%|█████████████████▊                  | 21036/42525 [31:56<32:01, 11.18it/s]

 49%|█████████████████▊                  | 21040/42525 [31:56<31:38, 11.31it/s]

 49%|█████████████████▊                  | 21044/42525 [31:57<32:02, 11.17it/s]

 49%|█████████████████▊                  | 21048/42525 [31:57<31:33, 11.34it/s]

 50%|█████████████████▊                  | 21052/42525 [31:57<30:50, 11.61it/s]

 50%|█████████████████▊                  | 21056/42525 [31:58<31:36, 11.32it/s]

 50%|█████████████████▊                  | 21060/42525 [31:58<31:58, 11.19it/s]

 50%|█████████████████▊                  | 21064/42525 [31:58<30:58, 11.54it/s]

 50%|█████████████████▊                  | 21068/42525 [31:59<31:19, 11.42it/s]

 50%|█████████████████▊                  | 21072/42525 [31:59<32:24, 11.03it/s]

 50%|█████████████████▊                  | 21076/42525 [31:59<31:30, 11.34it/s]

 50%|█████████████████▊                  | 21080/42525 [32:00<31:57, 11.18it/s]

 50%|█████████████████▊                  | 21084/42525 [32:00<30:54, 11.56it/s]

 50%|█████████████████▊                  | 21086/42525 [32:00<30:46, 11.61it/s]

 50%|█████████████████▊                  | 21090/42525 [32:01<33:17, 10.73it/s]

 50%|█████████████████▊                  | 21094/42525 [32:01<32:14, 11.08it/s]

 50%|█████████████████▊                  | 21098/42525 [32:01<32:18, 11.06it/s]

 50%|█████████████████▊                  | 21102/42525 [32:02<32:17, 11.06it/s]

 50%|█████████████████▊                  | 21106/42525 [32:02<32:06, 11.12it/s]

 50%|█████████████████▊                  | 21110/42525 [32:02<32:13, 11.07it/s]

 50%|█████████████████▊                  | 21114/42525 [32:03<31:06, 11.47it/s]

 50%|█████████████████▉                  | 21118/42525 [32:03<30:43, 11.61it/s]

 50%|█████████████████▉                  | 21122/42525 [32:03<30:14, 11.80it/s]

 50%|█████████████████▉                  | 21126/42525 [32:04<30:07, 11.84it/s]

 50%|█████████████████▉                  | 21130/42525 [32:04<30:08, 11.83it/s]

 50%|█████████████████▉                  | 21134/42525 [32:05<31:44, 11.23it/s]

 50%|█████████████████▉                  | 21138/42525 [32:05<31:24, 11.35it/s]

 50%|█████████████████▉                  | 21142/42525 [32:05<30:35, 11.65it/s]

 50%|█████████████████▉                  | 21146/42525 [32:06<31:07, 11.45it/s]

 50%|█████████████████▉                  | 21150/42525 [32:06<31:14, 11.40it/s]

 50%|█████████████████▉                  | 21152/42525 [32:06<32:09, 11.07it/s]

 50%|█████████████████▉                  | 21156/42525 [32:06<32:39, 10.91it/s]

 50%|█████████████████▉                  | 21160/42525 [32:07<33:38, 10.59it/s]

 50%|█████████████████▉                  | 21162/42525 [32:07<33:15, 10.71it/s]

 50%|█████████████████▉                  | 21166/42525 [32:07<33:09, 10.73it/s]

 50%|█████████████████▉                  | 21170/42525 [32:08<32:46, 10.86it/s]

 50%|█████████████████▉                  | 21174/42525 [32:08<31:24, 11.33it/s]

 50%|█████████████████▉                  | 21178/42525 [32:08<31:00, 11.47it/s]

 50%|█████████████████▉                  | 21182/42525 [32:09<30:52, 11.52it/s]

 50%|█████████████████▉                  | 21186/42525 [32:09<30:45, 11.56it/s]

 50%|█████████████████▉                  | 21190/42525 [32:10<31:24, 11.32it/s]

 50%|█████████████████▉                  | 21194/42525 [32:10<30:39, 11.60it/s]

 50%|█████████████████▉                  | 21198/42525 [32:10<30:57, 11.48it/s]

 50%|█████████████████▉                  | 21200/42525 [32:10<30:45, 11.55it/s]

 50%|█████████████████▉                  | 21204/42525 [32:11<33:28, 10.61it/s]

 50%|█████████████████▉                  | 21208/42525 [32:11<31:53, 11.14it/s]

 50%|█████████████████▉                  | 21212/42525 [32:11<30:53, 11.50it/s]

 50%|█████████████████▉                  | 21214/42525 [32:12<30:45, 11.55it/s]

 50%|█████████████████▉                  | 21218/42525 [32:12<32:50, 10.81it/s]

 50%|█████████████████▉                  | 21222/42525 [32:12<31:56, 11.11it/s]

 50%|█████████████████▉                  | 21226/42525 [32:13<31:01, 11.44it/s]

 50%|█████████████████▉                  | 21230/42525 [32:13<31:22, 11.31it/s]

 50%|█████████████████▉                  | 21234/42525 [32:13<30:33, 11.61it/s]

 50%|█████████████████▉                  | 21238/42525 [32:14<31:30, 11.26it/s]

 50%|█████████████████▉                  | 21242/42525 [32:14<31:39, 11.21it/s]

 50%|█████████████████▉                  | 21246/42525 [32:15<31:51, 11.13it/s]

 50%|█████████████████▉                  | 21250/42525 [32:15<30:57, 11.45it/s]

 50%|█████████████████▉                  | 21254/42525 [32:15<30:14, 11.72it/s]

 50%|█████████████████▉                  | 21258/42525 [32:16<30:19, 11.69it/s]

 50%|█████████████████▉                  | 21262/42525 [32:16<31:48, 11.14it/s]

 50%|██████████████████                  | 21266/42525 [32:16<31:18, 11.32it/s]

 50%|██████████████████                  | 21270/42525 [32:17<32:20, 10.95it/s]

 50%|██████████████████                  | 21274/42525 [32:17<32:20, 10.95it/s]

 50%|██████████████████                  | 21278/42525 [32:17<33:36, 10.54it/s]

 50%|██████████████████                  | 21282/42525 [32:18<32:15, 10.97it/s]

 50%|██████████████████                  | 21286/42525 [32:18<31:52, 11.11it/s]

 50%|██████████████████                  | 21290/42525 [32:18<30:51, 11.47it/s]

 50%|██████████████████                  | 21294/42525 [32:19<31:26, 11.26it/s]

 50%|██████████████████                  | 21296/42525 [32:19<32:04, 11.03it/s]

 50%|██████████████████                  | 21300/42525 [32:19<33:43, 10.49it/s]

 50%|██████████████████                  | 21304/42525 [32:20<33:08, 10.67it/s]

 50%|██████████████████                  | 21308/42525 [32:20<31:18, 11.30it/s]

 50%|██████████████████                  | 21312/42525 [32:20<31:36, 11.19it/s]

 50%|██████████████████                  | 21316/42525 [32:21<30:48, 11.48it/s]

 50%|██████████████████                  | 21320/42525 [32:21<32:37, 10.83it/s]

 50%|██████████████████                  | 21324/42525 [32:22<32:52, 10.75it/s]

 50%|██████████████████                  | 21328/42525 [32:22<32:26, 10.89it/s]

 50%|██████████████████                  | 21332/42525 [32:22<30:51, 11.45it/s]

 50%|██████████████████                  | 21336/42525 [32:23<30:20, 11.64it/s]

 50%|██████████████████                  | 21340/42525 [32:23<29:59, 11.77it/s]

 50%|██████████████████                  | 21344/42525 [32:23<30:45, 11.48it/s]

 50%|██████████████████                  | 21348/42525 [32:24<30:06, 11.73it/s]

 50%|██████████████████                  | 21352/42525 [32:24<31:05, 11.35it/s]

 50%|██████████████████                  | 21356/42525 [32:24<30:42, 11.49it/s]

 50%|██████████████████                  | 21360/42525 [32:25<31:04, 11.35it/s]

 50%|██████████████████                  | 21364/42525 [32:25<30:14, 11.66it/s]

 50%|██████████████████                  | 21368/42525 [32:25<29:55, 11.79it/s]

 50%|██████████████████                  | 21372/42525 [32:26<30:20, 11.62it/s]

 50%|██████████████████                  | 21376/42525 [32:26<30:26, 11.58it/s]

 50%|██████████████████                  | 21380/42525 [32:26<30:45, 11.46it/s]

 50%|██████████████████                  | 21384/42525 [32:27<31:49, 11.07it/s]

 50%|██████████████████                  | 21388/42525 [32:27<31:11, 11.30it/s]

 50%|██████████████████                  | 21392/42525 [32:27<31:02, 11.35it/s]

 50%|██████████████████                  | 21396/42525 [32:28<31:02, 11.34it/s]

 50%|██████████████████                  | 21400/42525 [32:28<30:53, 11.40it/s]

 50%|██████████████████                  | 21404/42525 [32:29<31:18, 11.24it/s]

 50%|██████████████████                  | 21408/42525 [32:29<31:40, 11.11it/s]

 50%|██████████████████▏                 | 21412/42525 [32:29<31:16, 11.25it/s]

 50%|██████████████████▏                 | 21416/42525 [32:30<31:13, 11.27it/s]

 50%|██████████████████▏                 | 21420/42525 [32:30<31:06, 11.31it/s]

 50%|██████████████████▏                 | 21424/42525 [32:30<31:10, 11.28it/s]

 50%|██████████████████▏                 | 21428/42525 [32:31<31:11, 11.27it/s]

 50%|██████████████████▏                 | 21432/42525 [32:31<30:20, 11.58it/s]

 50%|██████████████████▏                 | 21436/42525 [32:31<30:56, 11.36it/s]

 50%|██████████████████▏                 | 21440/42525 [32:32<30:24, 11.56it/s]

 50%|██████████████████▏                 | 21444/42525 [32:32<30:34, 11.49it/s]

 50%|██████████████████▏                 | 21448/42525 [32:32<31:32, 11.13it/s]

 50%|██████████████████▏                 | 21452/42525 [32:33<30:30, 11.51it/s]

 50%|██████████████████▏                 | 21456/42525 [32:33<30:58, 11.34it/s]

 50%|██████████████████▏                 | 21460/42525 [32:33<30:18, 11.58it/s]

 50%|██████████████████▏                 | 21464/42525 [32:34<30:47, 11.40it/s]

 50%|██████████████████▏                 | 21468/42525 [32:34<30:22, 11.56it/s]

 50%|██████████████████▏                 | 21472/42525 [32:35<29:47, 11.78it/s]

 51%|██████████████████▏                 | 21476/42525 [32:35<28:58, 12.11it/s]

 51%|██████████████████▏                 | 21480/42525 [32:35<29:37, 11.84it/s]

 51%|██████████████████▏                 | 21484/42525 [32:36<31:22, 11.18it/s]

 51%|██████████████████▏                 | 21488/42525 [32:36<30:54, 11.35it/s]

 51%|██████████████████▏                 | 21492/42525 [32:36<30:05, 11.65it/s]

 51%|██████████████████▏                 | 21496/42525 [32:37<30:18, 11.56it/s]

 51%|██████████████████▏                 | 21500/42525 [32:37<30:19, 11.56it/s]

 51%|██████████████████▏                 | 21502/42525 [32:37<30:08, 11.62it/s]

 51%|██████████████████▏                 | 21506/42525 [32:37<32:27, 10.79it/s]

 51%|██████████████████▏                 | 21510/42525 [32:38<31:41, 11.05it/s]

 51%|██████████████████▏                 | 21514/42525 [32:38<31:21, 11.17it/s]

 51%|██████████████████▏                 | 21518/42525 [32:39<30:27, 11.49it/s]

 51%|██████████████████▏                 | 21522/42525 [32:39<30:48, 11.36it/s]

 51%|██████████████████▏                 | 21526/42525 [32:39<30:59, 11.29it/s]

 51%|██████████████████▏                 | 21530/42525 [32:40<31:13, 11.20it/s]

 51%|██████████████████▏                 | 21534/42525 [32:40<31:23, 11.14it/s]

 51%|██████████████████▏                 | 21538/42525 [32:40<30:48, 11.36it/s]

 51%|██████████████████▏                 | 21542/42525 [32:41<31:28, 11.11it/s]

 51%|██████████████████▏                 | 21546/42525 [32:41<30:14, 11.56it/s]

 51%|██████████████████▏                 | 21550/42525 [32:41<30:49, 11.34it/s]

 51%|██████████████████▏                 | 21554/42525 [32:42<29:58, 11.66it/s]

 51%|██████████████████▎                 | 21558/42525 [32:42<29:31, 11.83it/s]

 51%|██████████████████▎                 | 21562/42525 [32:42<30:34, 11.43it/s]

 51%|██████████████████▎                 | 21566/42525 [32:43<31:57, 10.93it/s]

 51%|██████████████████▎                 | 21570/42525 [32:43<31:35, 11.05it/s]

 51%|██████████████████▎                 | 21574/42525 [32:43<30:23, 11.49it/s]

 51%|██████████████████▎                 | 21578/42525 [32:44<31:01, 11.25it/s]

 51%|██████████████████▎                 | 21582/42525 [32:44<30:42, 11.36it/s]

 51%|██████████████████▎                 | 21586/42525 [32:45<30:00, 11.63it/s]

 51%|██████████████████▎                 | 21590/42525 [32:45<32:26, 10.76it/s]

 51%|██████████████████▎                 | 21594/42525 [32:45<31:45, 10.99it/s]

 51%|██████████████████▎                 | 21598/42525 [32:46<31:16, 11.15it/s]

 51%|██████████████████▎                 | 21600/42525 [32:46<30:44, 11.34it/s]

 51%|██████████████████▎                 | 21604/42525 [32:46<32:09, 10.84it/s]

 51%|██████████████████▎                 | 21608/42525 [32:47<30:39, 11.37it/s]

 51%|██████████████████▎                 | 21612/42525 [32:47<29:52, 11.67it/s]

 51%|██████████████████▎                 | 21616/42525 [32:47<29:38, 11.76it/s]

 51%|██████████████████▎                 | 21620/42525 [32:48<30:12, 11.54it/s]

 51%|██████████████████▎                 | 21624/42525 [32:48<30:28, 11.43it/s]

 51%|██████████████████▎                 | 21628/42525 [32:48<30:31, 11.41it/s]

 51%|██████████████████▎                 | 21630/42525 [32:48<30:11, 11.53it/s]

 51%|██████████████████▎                 | 21634/42525 [32:49<31:13, 11.15it/s]

 51%|██████████████████▎                 | 21638/42525 [32:49<30:01, 11.60it/s]

 51%|██████████████████▎                 | 21642/42525 [32:49<29:35, 11.76it/s]

 51%|██████████████████▎                 | 21646/42525 [32:50<29:18, 11.87it/s]

 51%|██████████████████▎                 | 21650/42525 [32:50<29:11, 11.92it/s]

 51%|██████████████████▎                 | 21654/42525 [32:51<29:50, 11.66it/s]

 51%|██████████████████▎                 | 21658/42525 [32:51<30:29, 11.41it/s]

 51%|██████████████████▎                 | 21662/42525 [32:51<30:15, 11.49it/s]

 51%|██████████████████▎                 | 21666/42525 [32:52<31:01, 11.20it/s]

 51%|██████████████████▎                 | 21670/42525 [32:52<30:04, 11.56it/s]

 51%|██████████████████▎                 | 21674/42525 [32:52<29:51, 11.64it/s]

 51%|██████████████████▎                 | 21678/42525 [32:53<30:56, 11.23it/s]

 51%|██████████████████▎                 | 21682/42525 [32:53<30:13, 11.50it/s]

 51%|██████████████████▎                 | 21686/42525 [32:53<30:05, 11.54it/s]

 51%|██████████████████▎                 | 21690/42525 [32:54<30:54, 11.23it/s]

 51%|██████████████████▎                 | 21694/42525 [32:54<30:47, 11.27it/s]

 51%|██████████████████▎                 | 21698/42525 [32:54<30:08, 11.52it/s]

 51%|██████████████████▎                 | 21702/42525 [32:55<30:21, 11.43it/s]

 51%|██████████████████▍                 | 21706/42525 [32:55<30:23, 11.42it/s]

 51%|██████████████████▍                 | 21710/42525 [32:55<31:05, 11.16it/s]

 51%|██████████████████▍                 | 21714/42525 [32:56<30:58, 11.20it/s]

 51%|██████████████████▍                 | 21718/42525 [32:56<29:49, 11.63it/s]

 51%|██████████████████▍                 | 21722/42525 [32:56<29:37, 11.70it/s]

 51%|██████████████████▍                 | 21726/42525 [32:57<29:11, 11.87it/s]

 51%|██████████████████▍                 | 21730/42525 [32:57<29:12, 11.87it/s]

 51%|██████████████████▍                 | 21734/42525 [32:57<30:13, 11.46it/s]

 51%|██████████████████▍                 | 21738/42525 [32:58<29:55, 11.58it/s]

 51%|██████████████████▍                 | 21742/42525 [32:58<29:45, 11.64it/s]

 51%|██████████████████▍                 | 21746/42525 [32:59<29:46, 11.63it/s]

 51%|██████████████████▍                 | 21750/42525 [32:59<32:11, 10.75it/s]

 51%|██████████████████▍                 | 21754/42525 [32:59<30:20, 11.41it/s]

 51%|██████████████████▍                 | 21758/42525 [33:00<30:28, 11.36it/s]

 51%|██████████████████▍                 | 21762/42525 [33:00<29:39, 11.67it/s]

 51%|██████████████████▍                 | 21766/42525 [33:00<29:54, 11.57it/s]

 51%|██████████████████▍                 | 21770/42525 [33:01<30:18, 11.42it/s]

 51%|██████████████████▍                 | 21774/42525 [33:01<30:59, 11.16it/s]

 51%|██████████████████▍                 | 21778/42525 [33:01<31:41, 10.91it/s]

 51%|██████████████████▍                 | 21782/42525 [33:02<31:19, 11.03it/s]

 51%|██████████████████▍                 | 21784/42525 [33:02<30:42, 11.26it/s]

 51%|██████████████████▍                 | 21788/42525 [33:02<31:12, 11.07it/s]

 51%|██████████████████▍                 | 21792/42525 [33:03<31:00, 11.14it/s]

 51%|██████████████████▍                 | 21796/42525 [33:03<30:08, 11.46it/s]

 51%|██████████████████▍                 | 21800/42525 [33:03<29:44, 11.61it/s]

 51%|██████████████████▍                 | 21804/42525 [33:04<29:41, 11.63it/s]

 51%|██████████████████▍                 | 21808/42525 [33:04<29:59, 11.52it/s]

 51%|██████████████████▍                 | 21812/42525 [33:04<29:41, 11.63it/s]

 51%|██████████████████▍                 | 21816/42525 [33:05<29:54, 11.54it/s]

 51%|██████████████████▍                 | 21820/42525 [33:05<29:28, 11.71it/s]

 51%|██████████████████▍                 | 21824/42525 [33:05<29:27, 11.71it/s]

 51%|██████████████████▍                 | 21828/42525 [33:06<29:56, 11.52it/s]

 51%|██████████████████▍                 | 21832/42525 [33:06<30:12, 11.42it/s]

 51%|██████████████████▍                 | 21836/42525 [33:06<30:55, 11.15it/s]

 51%|██████████████████▍                 | 21840/42525 [33:07<30:45, 11.21it/s]

 51%|██████████████████▍                 | 21844/42525 [33:07<31:25, 10.97it/s]

 51%|██████████████████▍                 | 21848/42525 [33:08<30:22, 11.34it/s]

 51%|██████████████████▍                 | 21852/42525 [33:08<30:01, 11.48it/s]

 51%|██████████████████▌                 | 21856/42525 [33:08<31:02, 11.10it/s]

 51%|██████████████████▌                 | 21860/42525 [33:09<30:16, 11.38it/s]

 51%|██████████████████▌                 | 21864/42525 [33:09<30:56, 11.13it/s]

 51%|██████████████████▌                 | 21868/42525 [33:09<31:20, 10.99it/s]

 51%|██████████████████▌                 | 21872/42525 [33:10<31:48, 10.82it/s]

 51%|██████████████████▌                 | 21876/42525 [33:10<31:47, 10.83it/s]

 51%|██████████████████▌                 | 21880/42525 [33:10<31:19, 10.98it/s]

 51%|██████████████████▌                 | 21884/42525 [33:11<31:35, 10.89it/s]

 51%|██████████████████▌                 | 21888/42525 [33:11<30:12, 11.38it/s]

 51%|██████████████████▌                 | 21892/42525 [33:12<29:58, 11.47it/s]

 51%|██████████████████▌                 | 21896/42525 [33:12<29:37, 11.61it/s]

 51%|██████████████████▌                 | 21900/42525 [33:12<29:46, 11.55it/s]

 52%|██████████████████▌                 | 21904/42525 [33:13<29:28, 11.66it/s]

 52%|██████████████████▌                 | 21908/42525 [33:13<29:05, 11.81it/s]

 52%|██████████████████▌                 | 21912/42525 [33:13<29:00, 11.84it/s]

 52%|██████████████████▌                 | 21916/42525 [33:14<29:41, 11.57it/s]

 52%|██████████████████▌                 | 21918/42525 [33:14<29:43, 11.56it/s]

 52%|██████████████████▌                 | 21922/42525 [33:14<31:00, 11.07it/s]

 52%|██████████████████▌                 | 21926/42525 [33:14<31:54, 10.76it/s]

 52%|██████████████████▌                 | 21930/42525 [33:15<31:30, 10.89it/s]

 52%|██████████████████▌                 | 21934/42525 [33:15<30:44, 11.16it/s]

 52%|██████████████████▌                 | 21936/42525 [33:15<31:10, 11.01it/s]

 52%|██████████████████▌                 | 21940/42525 [33:16<32:17, 10.63it/s]

 52%|██████████████████▌                 | 21944/42525 [33:16<31:35, 10.86it/s]

 52%|██████████████████▌                 | 21948/42525 [33:16<30:37, 11.20it/s]

 52%|██████████████████▌                 | 21952/42525 [33:17<30:41, 11.17it/s]

 52%|██████████████████▌                 | 21956/42525 [33:17<30:39, 11.18it/s]

 52%|██████████████████▌                 | 21960/42525 [33:18<29:53, 11.47it/s]

 52%|██████████████████▌                 | 21964/42525 [33:18<29:21, 11.67it/s]

 52%|██████████████████▌                 | 21968/42525 [33:18<31:16, 10.96it/s]

 52%|██████████████████▌                 | 21972/42525 [33:19<31:50, 10.76it/s]

 52%|██████████████████▌                 | 21974/42525 [33:19<31:04, 11.02it/s]

 52%|██████████████████▌                 | 21978/42525 [33:19<31:56, 10.72it/s]

 52%|██████████████████▌                 | 21982/42525 [33:20<30:26, 11.25it/s]

 52%|██████████████████▌                 | 21986/42525 [33:20<29:39, 11.54it/s]

 52%|██████████████████▌                 | 21990/42525 [33:20<29:19, 11.67it/s]

 52%|██████████████████▌                 | 21994/42525 [33:21<29:35, 11.56it/s]

 52%|██████████████████▌                 | 21998/42525 [33:21<29:51, 11.45it/s]

 52%|██████████████████▋                 | 22002/42525 [33:21<30:58, 11.04it/s]

 52%|██████████████████▋                 | 22006/42525 [33:22<30:32, 11.20it/s]

 52%|██████████████████▋                 | 22008/42525 [33:22<30:07, 11.35it/s]

 52%|██████████████████▋                 | 22012/42525 [33:22<31:13, 10.95it/s]

 52%|██████████████████▋                 | 22016/42525 [33:23<31:22, 10.90it/s]

 52%|██████████████████▋                 | 22020/42525 [33:23<31:28, 10.86it/s]

 52%|██████████████████▋                 | 22024/42525 [33:23<31:10, 10.96it/s]

 52%|██████████████████▋                 | 22028/42525 [33:24<30:47, 11.09it/s]

 52%|██████████████████▋                 | 22032/42525 [33:24<31:11, 10.95it/s]

 52%|██████████████████▋                 | 22036/42525 [33:24<32:05, 10.64it/s]

 52%|██████████████████▋                 | 22040/42525 [33:25<30:50, 11.07it/s]

 52%|██████████████████▋                 | 22044/42525 [33:25<31:12, 10.94it/s]

 52%|██████████████████▋                 | 22048/42525 [33:26<31:41, 10.77it/s]

 52%|██████████████████▋                 | 22052/42525 [33:26<31:09, 10.95it/s]

 52%|██████████████████▋                 | 22056/42525 [33:26<31:03, 10.98it/s]

 52%|██████████████████▋                 | 22060/42525 [33:27<30:00, 11.37it/s]

 52%|██████████████████▋                 | 22064/42525 [33:27<29:31, 11.55it/s]

 52%|██████████████████▋                 | 22068/42525 [33:27<30:23, 11.22it/s]

 52%|██████████████████▋                 | 22072/42525 [33:28<29:55, 11.39it/s]

 52%|██████████████████▋                 | 22076/42525 [33:28<30:58, 11.00it/s]

 52%|██████████████████▋                 | 22080/42525 [33:28<29:51, 11.41it/s]

 52%|██████████████████▋                 | 22084/42525 [33:29<29:19, 11.62it/s]

 52%|██████████████████▋                 | 22088/42525 [33:29<30:56, 11.01it/s]

 52%|██████████████████▋                 | 22092/42525 [33:29<31:49, 10.70it/s]

 52%|██████████████████▋                 | 22094/42525 [33:30<31:03, 10.97it/s]

 52%|██████████████████▋                 | 22098/42525 [33:30<31:34, 10.78it/s]

 52%|██████████████████▋                 | 22102/42525 [33:30<30:56, 11.00it/s]

 52%|██████████████████▋                 | 22106/42525 [33:31<29:56, 11.36it/s]

 52%|██████████████████▋                 | 22110/42525 [33:31<29:11, 11.65it/s]

 52%|██████████████████▋                 | 22114/42525 [33:31<28:59, 11.73it/s]

 52%|██████████████████▋                 | 22118/42525 [33:32<28:55, 11.76it/s]

 52%|██████████████████▋                 | 22122/42525 [33:32<29:11, 11.65it/s]

 52%|██████████████████▋                 | 22126/42525 [33:32<29:51, 11.39it/s]

 52%|██████████████████▋                 | 22130/42525 [33:33<30:18, 11.22it/s]

 52%|██████████████████▋                 | 22134/42525 [33:33<30:33, 11.12it/s]

 52%|██████████████████▋                 | 22138/42525 [33:34<30:33, 11.12it/s]

 52%|██████████████████▋                 | 22142/42525 [33:34<29:42, 11.43it/s]

 52%|██████████████████▋                 | 22146/42525 [33:34<30:44, 11.05it/s]

 52%|██████████████████▋                 | 22148/42525 [33:34<30:12, 11.24it/s]

 52%|██████████████████▊                 | 22152/42525 [33:35<30:49, 11.02it/s]

 52%|██████████████████▊                 | 22156/42525 [33:35<29:43, 11.42it/s]

 52%|██████████████████▊                 | 22160/42525 [33:35<30:02, 11.30it/s]

 52%|██████████████████▊                 | 22164/42525 [33:36<29:14, 11.60it/s]

 52%|██████████████████▊                 | 22166/42525 [33:36<29:09, 11.64it/s]

 52%|██████████████████▊                 | 22170/42525 [33:36<31:48, 10.67it/s]

 52%|██████████████████▊                 | 22174/42525 [33:37<30:28, 11.13it/s]

 52%|██████████████████▊                 | 22178/42525 [33:37<31:11, 10.87it/s]

 52%|██████████████████▊                 | 22182/42525 [33:37<30:37, 11.07it/s]

 52%|██████████████████▊                 | 22186/42525 [33:38<29:39, 11.43it/s]

 52%|██████████████████▊                 | 22190/42525 [33:38<30:31, 11.10it/s]

 52%|██████████████████▊                 | 22194/42525 [33:39<30:08, 11.24it/s]

 52%|██████████████████▊                 | 22198/42525 [33:39<30:09, 11.23it/s]

 52%|██████████████████▊                 | 22202/42525 [33:39<30:39, 11.05it/s]

 52%|██████████████████▊                 | 22206/42525 [33:40<30:32, 11.09it/s]

 52%|██████████████████▊                 | 22208/42525 [33:40<31:12, 10.85it/s]

 52%|██████████████████▊                 | 22212/42525 [33:40<32:16, 10.49it/s]

 52%|██████████████████▊                 | 22216/42525 [33:41<30:41, 11.03it/s]

 52%|██████████████████▊                 | 22220/42525 [33:41<29:38, 11.41it/s]

 52%|██████████████████▊                 | 22224/42525 [33:41<29:54, 11.31it/s]

 52%|██████████████████▊                 | 22228/42525 [33:42<30:17, 11.17it/s]

 52%|██████████████████▊                 | 22232/42525 [33:42<30:34, 11.06it/s]

 52%|██████████████████▊                 | 22236/42525 [33:42<29:45, 11.36it/s]

 52%|██████████████████▊                 | 22240/42525 [33:43<30:00, 11.26it/s]

 52%|██████████████████▊                 | 22244/42525 [33:43<29:52, 11.32it/s]

 52%|██████████████████▊                 | 22248/42525 [33:43<30:14, 11.17it/s]

 52%|██████████████████▊                 | 22252/42525 [33:44<30:18, 11.15it/s]

 52%|██████████████████▊                 | 22256/42525 [33:44<31:02, 10.88it/s]

 52%|██████████████████▊                 | 22260/42525 [33:44<29:58, 11.27it/s]

 52%|██████████████████▊                 | 22264/42525 [33:45<30:20, 11.13it/s]

 52%|██████████████████▊                 | 22268/42525 [33:45<30:35, 11.03it/s]

 52%|██████████████████▊                 | 22272/42525 [33:46<29:31, 11.43it/s]

 52%|██████████████████▊                 | 22276/42525 [33:46<29:54, 11.29it/s]

 52%|██████████████████▊                 | 22280/42525 [33:46<30:34, 11.03it/s]

 52%|██████████████████▊                 | 22284/42525 [33:47<29:41, 11.36it/s]

 52%|██████████████████▊                 | 22288/42525 [33:47<30:15, 11.14it/s]

 52%|██████████████████▊                 | 22292/42525 [33:47<30:01, 11.23it/s]

 52%|██████████████████▊                 | 22296/42525 [33:48<31:16, 10.78it/s]

 52%|██████████████████▉                 | 22300/42525 [33:48<30:19, 11.12it/s]

 52%|██████████████████▉                 | 22304/42525 [33:48<29:43, 11.34it/s]

 52%|██████████████████▉                 | 22308/42525 [33:49<30:21, 11.10it/s]

 52%|██████████████████▉                 | 22312/42525 [33:49<30:58, 10.88it/s]

 52%|██████████████████▉                 | 22316/42525 [33:50<30:48, 10.93it/s]

 52%|██████████████████▉                 | 22320/42525 [33:50<29:48, 11.30it/s]

 52%|██████████████████▉                 | 22324/42525 [33:50<30:01, 11.21it/s]

 53%|██████████████████▉                 | 22328/42525 [33:51<29:58, 11.23it/s]

 53%|██████████████████▉                 | 22332/42525 [33:51<29:25, 11.44it/s]

 53%|██████████████████▉                 | 22336/42525 [33:51<29:15, 11.50it/s]

 53%|██████████████████▉                 | 22340/42525 [33:52<29:15, 11.50it/s]

 53%|██████████████████▉                 | 22344/42525 [33:52<30:26, 11.05it/s]

 53%|██████████████████▉                 | 22348/42525 [33:52<30:12, 11.14it/s]

 53%|██████████████████▉                 | 22352/42525 [33:53<31:06, 10.81it/s]

 53%|██████████████████▉                 | 22356/42525 [33:53<29:44, 11.30it/s]

 53%|██████████████████▉                 | 22360/42525 [33:53<30:14, 11.11it/s]

 53%|██████████████████▉                 | 22364/42525 [33:54<29:16, 11.48it/s]

 53%|██████████████████▉                 | 22368/42525 [33:54<29:03, 11.56it/s]

 53%|██████████████████▉                 | 22372/42525 [33:54<29:34, 11.35it/s]

 53%|██████████████████▉                 | 22376/42525 [33:55<31:18, 10.73it/s]

 53%|██████████████████▉                 | 22380/42525 [33:55<30:12, 11.12it/s]

 53%|██████████████████▉                 | 22384/42525 [33:56<30:34, 10.98it/s]

 53%|██████████████████▉                 | 22386/42525 [33:56<30:02, 11.17it/s]

 53%|██████████████████▉                 | 22390/42525 [33:56<32:05, 10.46it/s]

 53%|██████████████████▉                 | 22394/42525 [33:57<30:42, 10.93it/s]

 53%|██████████████████▉                 | 22398/42525 [33:57<30:30, 11.00it/s]

 53%|██████████████████▉                 | 22402/42525 [33:57<30:17, 11.07it/s]

 53%|██████████████████▉                 | 22406/42525 [33:58<30:01, 11.17it/s]

 53%|██████████████████▉                 | 22410/42525 [33:58<29:21, 11.42it/s]

 53%|██████████████████▉                 | 22414/42525 [33:58<30:09, 11.11it/s]

 53%|██████████████████▉                 | 22418/42525 [33:59<30:29, 10.99it/s]

 53%|██████████████████▉                 | 22422/42525 [33:59<29:25, 11.39it/s]

 53%|██████████████████▉                 | 22426/42525 [33:59<29:45, 11.26it/s]

 53%|██████████████████▉                 | 22430/42525 [34:00<29:57, 11.18it/s]

 53%|██████████████████▉                 | 22434/42525 [34:00<28:53, 11.59it/s]

 53%|██████████████████▉                 | 22438/42525 [34:00<29:43, 11.26it/s]

 53%|██████████████████▉                 | 22442/42525 [34:01<30:11, 11.09it/s]

 53%|███████████████████                 | 22446/42525 [34:01<30:58, 10.81it/s]

 53%|███████████████████                 | 22450/42525 [34:02<30:44, 10.88it/s]

 53%|███████████████████                 | 22454/42525 [34:02<30:02, 11.14it/s]

 53%|███████████████████                 | 22458/42525 [34:02<31:25, 10.64it/s]

 53%|███████████████████                 | 22462/42525 [34:03<30:54, 10.82it/s]

 53%|███████████████████                 | 22464/42525 [34:03<30:21, 11.01it/s]

 53%|███████████████████                 | 22468/42525 [34:03<31:00, 10.78it/s]

 53%|███████████████████                 | 22472/42525 [34:04<29:37, 11.28it/s]

 53%|███████████████████                 | 22476/42525 [34:04<30:19, 11.02it/s]

 53%|███████████████████                 | 22480/42525 [34:04<30:25, 10.98it/s]

 53%|███████████████████                 | 22484/42525 [34:05<30:44, 10.87it/s]

 53%|███████████████████                 | 22488/42525 [34:05<29:33, 11.30it/s]

 53%|███████████████████                 | 22492/42525 [34:05<30:22, 10.99it/s]

 53%|███████████████████                 | 22496/42525 [34:06<29:45, 11.22it/s]

 53%|███████████████████                 | 22500/42525 [34:06<29:12, 11.42it/s]

 53%|███████████████████                 | 22504/42525 [34:06<28:36, 11.66it/s]

 53%|███████████████████                 | 22508/42525 [34:07<29:03, 11.48it/s]

 53%|███████████████████                 | 22512/42525 [34:07<28:36, 11.66it/s]

 53%|███████████████████                 | 22516/42525 [34:07<29:34, 11.28it/s]

 53%|███████████████████                 | 22520/42525 [34:08<29:16, 11.39it/s]

 53%|███████████████████                 | 22524/42525 [34:08<29:01, 11.49it/s]

 53%|███████████████████                 | 22528/42525 [34:09<29:31, 11.29it/s]

 53%|███████████████████                 | 22532/42525 [34:09<29:29, 11.30it/s]

 53%|███████████████████                 | 22536/42525 [34:09<29:43, 11.21it/s]

 53%|███████████████████                 | 22538/42525 [34:09<29:09, 11.42it/s]

 53%|███████████████████                 | 22542/42525 [34:10<29:46, 11.19it/s]

 53%|███████████████████                 | 22546/42525 [34:10<28:55, 11.51it/s]

 53%|███████████████████                 | 22550/42525 [34:10<28:43, 11.59it/s]

 53%|███████████████████                 | 22554/42525 [34:11<28:49, 11.55it/s]

 53%|███████████████████                 | 22558/42525 [34:11<29:33, 11.26it/s]

 53%|███████████████████                 | 22562/42525 [34:12<30:14, 11.00it/s]

 53%|███████████████████                 | 22566/42525 [34:12<30:20, 10.97it/s]

 53%|███████████████████                 | 22570/42525 [34:12<30:04, 11.06it/s]

 53%|███████████████████                 | 22574/42525 [34:13<28:55, 11.49it/s]

 53%|███████████████████                 | 22578/42525 [34:13<28:41, 11.58it/s]

 53%|███████████████████                 | 22582/42525 [34:13<29:33, 11.24it/s]

 53%|███████████████████                 | 22586/42525 [34:14<30:45, 10.80it/s]

 53%|███████████████████                 | 22590/42525 [34:14<29:59, 11.08it/s]

 53%|███████████████████▏                | 22592/42525 [34:14<29:23, 11.30it/s]

 53%|███████████████████▏                | 22596/42525 [34:15<31:25, 10.57it/s]

 53%|███████████████████▏                | 22600/42525 [34:15<29:42, 11.18it/s]

 53%|███████████████████▏                | 22604/42525 [34:15<29:08, 11.39it/s]

 53%|███████████████████▏                | 22608/42525 [34:16<28:43, 11.56it/s]

 53%|███████████████████▏                | 22612/42525 [34:16<29:15, 11.35it/s]

 53%|███████████████████▏                | 22616/42525 [34:16<29:43, 11.17it/s]

 53%|███████████████████▏                | 22620/42525 [34:17<28:58, 11.45it/s]

 53%|███████████████████▏                | 22624/42525 [34:17<29:09, 11.37it/s]

 53%|███████████████████▏                | 22628/42525 [34:17<28:26, 11.66it/s]

 53%|███████████████████▏                | 22632/42525 [34:18<28:40, 11.56it/s]

 53%|███████████████████▏                | 22636/42525 [34:18<28:31, 11.62it/s]

 53%|███████████████████▏                | 22640/42525 [34:18<28:45, 11.53it/s]

 53%|███████████████████▏                | 22644/42525 [34:19<28:56, 11.45it/s]

 53%|███████████████████▏                | 22648/42525 [34:19<28:37, 11.57it/s]

 53%|███████████████████▏                | 22652/42525 [34:19<28:20, 11.69it/s]

 53%|███████████████████▏                | 22656/42525 [34:20<28:07, 11.78it/s]

 53%|███████████████████▏                | 22660/42525 [34:20<28:44, 11.52it/s]

 53%|███████████████████▏                | 22664/42525 [34:21<28:19, 11.68it/s]

 53%|███████████████████▏                | 22668/42525 [34:21<28:14, 11.72it/s]

 53%|███████████████████▏                | 22672/42525 [34:21<27:57, 11.84it/s]

 53%|███████████████████▏                | 22676/42525 [34:22<28:37, 11.56it/s]

 53%|███████████████████▏                | 22680/42525 [34:22<30:15, 10.93it/s]

 53%|███████████████████▏                | 22684/42525 [34:22<29:06, 11.36it/s]

 53%|███████████████████▏                | 22688/42525 [34:23<29:37, 11.16it/s]

 53%|███████████████████▏                | 22692/42525 [34:23<28:51, 11.46it/s]

 53%|███████████████████▏                | 22696/42525 [34:23<29:33, 11.18it/s]

 53%|███████████████████▏                | 22700/42525 [34:24<30:06, 10.97it/s]

 53%|███████████████████▏                | 22704/42525 [34:24<30:14, 10.92it/s]

 53%|███████████████████▏                | 22708/42525 [34:24<29:50, 11.07it/s]

 53%|███████████████████▏                | 22712/42525 [34:25<29:25, 11.22it/s]

 53%|███████████████████▏                | 22716/42525 [34:25<29:28, 11.20it/s]

 53%|███████████████████▏                | 22720/42525 [34:26<30:40, 10.76it/s]

 53%|███████████████████▏                | 22724/42525 [34:26<30:31, 10.81it/s]

 53%|███████████████████▏                | 22728/42525 [34:26<29:47, 11.07it/s]

 53%|███████████████████▏                | 22732/42525 [34:27<29:21, 11.24it/s]

 53%|███████████████████▏                | 22736/42525 [34:27<30:33, 10.80it/s]

 53%|███████████████████▎                | 22740/42525 [34:27<29:36, 11.14it/s]

 53%|███████████████████▎                | 22744/42525 [34:28<29:02, 11.35it/s]

 53%|███████████████████▎                | 22748/42525 [34:28<29:11, 11.29it/s]

 54%|███████████████████▎                | 22752/42525 [34:28<28:27, 11.58it/s]

 54%|███████████████████▎                | 22756/42525 [34:29<29:23, 11.21it/s]

 54%|███████████████████▎                | 22760/42525 [34:29<30:11, 10.91it/s]

 54%|███████████████████▎                | 22764/42525 [34:30<31:50, 10.34it/s]

 54%|███████████████████▎                | 22768/42525 [34:30<30:01, 10.97it/s]

 54%|███████████████████▎                | 22772/42525 [34:30<30:10, 10.91it/s]

 54%|███████████████████▎                | 22776/42525 [34:31<30:01, 10.96it/s]

 54%|███████████████████▎                | 22780/42525 [34:31<29:36, 11.12it/s]

 54%|███████████████████▎                | 22784/42525 [34:31<29:02, 11.33it/s]

 54%|███████████████████▎                | 22788/42525 [34:32<30:32, 10.77it/s]

 54%|███████████████████▎                | 22792/42525 [34:32<29:05, 11.30it/s]

 54%|███████████████████▎                | 22796/42525 [34:32<30:25, 10.81it/s]

 54%|███████████████████▎                | 22800/42525 [34:33<29:37, 11.09it/s]

 54%|███████████████████▎                | 22804/42525 [34:33<28:50, 11.40it/s]

 54%|███████████████████▎                | 22808/42525 [34:33<28:58, 11.34it/s]

 54%|███████████████████▎                | 22812/42525 [34:34<29:21, 11.19it/s]

 54%|███████████████████▎                | 22816/42525 [34:34<30:09, 10.89it/s]

 54%|███████████████████▎                | 22820/42525 [34:35<29:14, 11.23it/s]

 54%|███████████████████▎                | 22824/42525 [34:35<28:39, 11.46it/s]

 54%|███████████████████▎                | 22828/42525 [34:35<28:10, 11.65it/s]

 54%|███████████████████▎                | 22832/42525 [34:36<28:56, 11.34it/s]

 54%|███████████████████▎                | 22836/42525 [34:36<28:55, 11.34it/s]

 54%|███████████████████▎                | 22840/42525 [34:36<28:48, 11.39it/s]

 54%|███████████████████▎                | 22844/42525 [34:37<28:14, 11.62it/s]

 54%|███████████████████▎                | 22848/42525 [34:37<27:48, 11.79it/s]

 54%|███████████████████▎                | 22852/42525 [34:37<28:17, 11.59it/s]

 54%|███████████████████▎                | 22856/42525 [34:38<28:22, 11.55it/s]

 54%|███████████████████▎                | 22860/42525 [34:38<29:16, 11.20it/s]

 54%|███████████████████▎                | 22864/42525 [34:38<29:59, 10.92it/s]

 54%|███████████████████▎                | 22868/42525 [34:39<30:50, 10.62it/s]

 54%|███████████████████▎                | 22872/42525 [34:39<31:25, 10.42it/s]

 54%|███████████████████▎                | 22876/42525 [34:40<31:04, 10.54it/s]

 54%|███████████████████▎                | 22880/42525 [34:40<31:25, 10.42it/s]

 54%|███████████████████▎                | 22884/42525 [34:40<30:04, 10.88it/s]

 54%|███████████████████▍                | 22888/42525 [34:41<30:19, 10.80it/s]

 54%|███████████████████▍                | 22892/42525 [34:41<29:14, 11.19it/s]

 54%|███████████████████▍                | 22896/42525 [34:41<29:05, 11.24it/s]

 54%|███████████████████▍                | 22900/42525 [34:42<29:25, 11.12it/s]

 54%|███████████████████▍                | 22904/42525 [34:42<28:48, 11.35it/s]

 54%|███████████████████▍                | 22908/42525 [34:42<29:25, 11.11it/s]

 54%|███████████████████▍                | 22912/42525 [34:43<28:36, 11.43it/s]

 54%|███████████████████▍                | 22916/42525 [34:43<29:32, 11.06it/s]

 54%|███████████████████▍                | 22920/42525 [34:44<30:00, 10.89it/s]

 54%|███████████████████▍                | 22922/42525 [34:44<29:31, 11.06it/s]

 54%|███████████████████▍                | 22926/42525 [34:44<29:41, 11.00it/s]

 54%|███████████████████▍                | 22930/42525 [34:44<29:33, 11.05it/s]

 54%|███████████████████▍                | 22934/42525 [34:45<29:46, 10.96it/s]

 54%|███████████████████▍                | 22938/42525 [34:45<29:59, 10.88it/s]

 54%|███████████████████▍                | 22942/42525 [34:45<29:01, 11.24it/s]

 54%|███████████████████▍                | 22946/42525 [34:46<29:57, 10.89it/s]

 54%|███████████████████▍                | 22948/42525 [34:46<30:37, 10.65it/s]

 54%|███████████████████▍                | 22952/42525 [34:46<30:50, 10.58it/s]

 54%|███████████████████▍                | 22956/42525 [34:47<29:22, 11.10it/s]

 54%|███████████████████▍                | 22960/42525 [34:47<29:49, 10.93it/s]

 54%|███████████████████▍                | 22964/42525 [34:48<29:30, 11.05it/s]

 54%|███████████████████▍                | 22968/42525 [34:48<29:25, 11.08it/s]

 54%|███████████████████▍                | 22972/42525 [34:48<29:24, 11.08it/s]

 54%|███████████████████▍                | 22974/42525 [34:48<29:20, 11.11it/s]

 54%|███████████████████▍                | 22978/42525 [34:49<31:27, 10.36it/s]

 54%|███████████████████▍                | 22982/42525 [34:49<29:30, 11.04it/s]

 54%|███████████████████▍                | 22986/42525 [34:50<29:58, 10.86it/s]

 54%|███████████████████▍                | 22990/42525 [34:50<30:37, 10.63it/s]

 54%|███████████████████▍                | 22994/42525 [34:50<30:19, 10.73it/s]

 54%|███████████████████▍                | 22998/42525 [34:51<29:54, 10.88it/s]

 54%|███████████████████▍                | 23002/42525 [34:51<29:15, 11.12it/s]

 54%|███████████████████▍                | 23006/42525 [34:51<28:47, 11.30it/s]

 54%|███████████████████▍                | 23010/42525 [34:52<27:14, 11.94it/s]

 54%|███████████████████▍                | 23014/42525 [34:52<27:47, 11.70it/s]

 54%|███████████████████▍                | 23018/42525 [34:52<28:48, 11.28it/s]

 54%|███████████████████▍                | 23022/42525 [34:53<28:18, 11.48it/s]

 54%|███████████████████▍                | 23026/42525 [34:53<29:47, 10.91it/s]

 54%|███████████████████▍                | 23030/42525 [34:54<29:12, 11.12it/s]

 54%|███████████████████▍                | 23034/42525 [34:54<28:46, 11.29it/s]

 54%|███████████████████▌                | 23038/42525 [34:54<28:59, 11.21it/s]

 54%|███████████████████▌                | 23042/42525 [34:55<28:15, 11.49it/s]

 54%|███████████████████▌                | 23046/42525 [34:55<27:54, 11.63it/s]

 54%|███████████████████▌                | 23050/42525 [34:55<27:58, 11.61it/s]

 54%|███████████████████▌                | 23054/42525 [34:56<29:35, 10.97it/s]

 54%|███████████████████▌                | 23058/42525 [34:56<29:46, 10.89it/s]

 54%|███████████████████▌                | 23062/42525 [34:56<29:56, 10.83it/s]

 54%|███████████████████▌                | 23066/42525 [34:57<28:59, 11.19it/s]

 54%|███████████████████▌                | 23070/42525 [34:57<28:20, 11.44it/s]

 54%|███████████████████▌                | 23074/42525 [34:57<29:11, 11.10it/s]

 54%|███████████████████▌                | 23078/42525 [34:58<29:36, 10.94it/s]

 54%|███████████████████▌                | 23082/42525 [34:58<29:13, 11.09it/s]

 54%|███████████████████▌                | 23086/42525 [34:59<29:59, 10.80it/s]

 54%|███████████████████▌                | 23090/42525 [34:59<30:12, 10.72it/s]

 54%|███████████████████▌                | 23094/42525 [34:59<30:12, 10.72it/s]

 54%|███████████████████▌                | 23098/42525 [35:00<29:23, 11.02it/s]

 54%|███████████████████▌                | 23102/42525 [35:00<28:34, 11.33it/s]

 54%|███████████████████▌                | 23106/42525 [35:00<28:25, 11.39it/s]

 54%|███████████████████▌                | 23110/42525 [35:01<28:26, 11.38it/s]

 54%|███████████████████▌                | 23114/42525 [35:01<29:07, 11.11it/s]

 54%|███████████████████▌                | 23118/42525 [35:01<28:38, 11.30it/s]

 54%|███████████████████▌                | 23122/42525 [35:02<27:51, 11.61it/s]

 54%|███████████████████▌                | 23126/42525 [35:02<28:13, 11.45it/s]

 54%|███████████████████▌                | 23130/42525 [35:02<29:14, 11.05it/s]

 54%|███████████████████▌                | 23134/42525 [35:03<28:37, 11.29it/s]

 54%|███████████████████▌                | 23138/42525 [35:03<28:19, 11.41it/s]

 54%|███████████████████▌                | 23142/42525 [35:04<29:50, 10.82it/s]

 54%|███████████████████▌                | 23146/42525 [35:04<29:27, 10.97it/s]

 54%|███████████████████▌                | 23150/42525 [35:04<28:23, 11.37it/s]

 54%|███████████████████▌                | 23154/42525 [35:05<28:58, 11.14it/s]

 54%|███████████████████▌                | 23158/42525 [35:05<28:56, 11.15it/s]

 54%|███████████████████▌                | 23162/42525 [35:05<28:33, 11.30it/s]

 54%|███████████████████▌                | 23166/42525 [35:06<29:54, 10.79it/s]

 54%|███████████████████▌                | 23170/42525 [35:06<28:53, 11.16it/s]

 54%|███████████████████▌                | 23174/42525 [35:06<27:02, 11.92it/s]

 55%|███████████████████▌                | 23178/42525 [35:07<26:20, 12.24it/s]

 55%|███████████████████▌                | 23182/42525 [35:07<26:53, 11.99it/s]

 55%|███████████████████▋                | 23186/42525 [35:07<27:27, 11.74it/s]

 55%|███████████████████▋                | 23190/42525 [35:08<28:15, 11.41it/s]

 55%|███████████████████▋                | 23194/42525 [35:08<28:12, 11.42it/s]

 55%|███████████████████▋                | 23198/42525 [35:08<27:41, 11.63it/s]

 55%|███████████████████▋                | 23202/42525 [35:09<27:42, 11.62it/s]

 55%|███████████████████▋                | 23206/42525 [35:09<27:36, 11.66it/s]

 55%|███████████████████▋                | 23210/42525 [35:09<27:42, 11.62it/s]

 55%|███████████████████▋                | 23214/42525 [35:10<28:34, 11.26it/s]

 55%|███████████████████▋                | 23218/42525 [35:10<29:03, 11.08it/s]

 55%|███████████████████▋                | 23222/42525 [35:11<28:45, 11.19it/s]

 55%|███████████████████▋                | 23226/42525 [35:11<28:13, 11.39it/s]

 55%|███████████████████▋                | 23230/42525 [35:11<28:21, 11.34it/s]

 55%|███████████████████▋                | 23234/42525 [35:12<27:54, 11.52it/s]

 55%|███████████████████▋                | 23238/42525 [35:12<28:24, 11.32it/s]

 55%|███████████████████▋                | 23242/42525 [35:12<29:38, 10.84it/s]

 55%|███████████████████▋                | 23244/42525 [35:12<28:56, 11.10it/s]

 55%|███████████████████▋                | 23248/42525 [35:13<29:50, 10.77it/s]

 55%|███████████████████▋                | 23252/42525 [35:13<29:26, 10.91it/s]

 55%|███████████████████▋                | 23256/42525 [35:14<29:04, 11.05it/s]

 55%|███████████████████▋                | 23260/42525 [35:14<28:01, 11.46it/s]

 55%|███████████████████▋                | 23264/42525 [35:14<29:57, 10.72it/s]

 55%|███████████████████▋                | 23268/42525 [35:15<28:47, 11.15it/s]

 55%|███████████████████▋                | 23272/42525 [35:15<28:18, 11.33it/s]

 55%|███████████████████▋                | 23276/42525 [35:15<28:31, 11.25it/s]

 55%|███████████████████▋                | 23280/42525 [35:16<29:02, 11.04it/s]

 55%|███████████████████▋                | 23284/42525 [35:16<30:07, 10.64it/s]

 55%|███████████████████▋                | 23288/42525 [35:17<28:40, 11.18it/s]

 55%|███████████████████▋                | 23290/42525 [35:17<28:50, 11.12it/s]

 55%|███████████████████▋                | 23294/42525 [35:17<29:42, 10.79it/s]

 55%|███████████████████▋                | 23298/42525 [35:17<29:36, 10.82it/s]

 55%|███████████████████▋                | 23302/42525 [35:18<30:08, 10.63it/s]

 55%|███████████████████▋                | 23306/42525 [35:18<28:59, 11.05it/s]

 55%|███████████████████▋                | 23308/42525 [35:18<28:24, 11.27it/s]

 55%|███████████████████▋                | 23312/42525 [35:19<29:08, 10.99it/s]

 55%|███████████████████▋                | 23316/42525 [35:19<28:12, 11.35it/s]

 55%|███████████████████▋                | 23320/42525 [35:19<29:05, 11.00it/s]

 55%|███████████████████▋                | 23324/42525 [35:20<28:42, 11.15it/s]

 55%|███████████████████▋                | 23328/42525 [35:20<27:50, 11.49it/s]

 55%|███████████████████▊                | 23332/42525 [35:20<28:26, 11.24it/s]

 55%|███████████████████▊                | 23336/42525 [35:21<28:11, 11.35it/s]

 55%|███████████████████▊                | 23340/42525 [35:21<28:06, 11.38it/s]

 55%|███████████████████▊                | 23344/42525 [35:22<28:47, 11.10it/s]

 55%|███████████████████▊                | 23348/42525 [35:22<29:06, 10.98it/s]

 55%|███████████████████▊                | 23352/42525 [35:22<29:04, 10.99it/s]

 55%|███████████████████▊                | 23354/42525 [35:22<29:02, 11.00it/s]

 55%|███████████████████▊                | 23358/42525 [35:23<28:57, 11.03it/s]

 55%|███████████████████▊                | 23362/42525 [35:23<27:49, 11.48it/s]

 55%|███████████████████▊                | 23366/42525 [35:24<27:21, 11.67it/s]

 55%|███████████████████▊                | 23370/42525 [35:24<28:25, 11.23it/s]

 55%|███████████████████▊                | 23374/42525 [35:24<28:12, 11.32it/s]

 55%|███████████████████▊                | 23376/42525 [35:24<28:30, 11.19it/s]

 55%|███████████████████▊                | 23380/42525 [35:25<28:46, 11.09it/s]

 55%|███████████████████▊                | 23384/42525 [35:25<28:10, 11.32it/s]

 55%|███████████████████▊                | 23388/42525 [35:25<28:29, 11.20it/s]

 55%|███████████████████▊                | 23392/42525 [35:26<27:23, 11.64it/s]

 55%|███████████████████▊                | 23396/42525 [35:26<27:45, 11.49it/s]

 55%|███████████████████▊                | 23400/42525 [35:27<28:40, 11.11it/s]

 55%|███████████████████▊                | 23404/42525 [35:27<27:36, 11.54it/s]

 55%|███████████████████▊                | 23408/42525 [35:27<28:19, 11.25it/s]

 55%|███████████████████▊                | 23412/42525 [35:28<29:03, 10.96it/s]

 55%|███████████████████▊                | 23416/42525 [35:28<28:57, 11.00it/s]

 55%|███████████████████▊                | 23420/42525 [35:28<29:20, 10.85it/s]

 55%|███████████████████▊                | 23424/42525 [35:29<28:05, 11.33it/s]

 55%|███████████████████▊                | 23428/42525 [35:29<28:23, 11.21it/s]

 55%|███████████████████▊                | 23432/42525 [35:29<28:25, 11.19it/s]

 55%|███████████████████▊                | 23436/42525 [35:30<27:44, 11.47it/s]

 55%|███████████████████▊                | 23440/42525 [35:30<28:26, 11.18it/s]

 55%|███████████████████▊                | 23444/42525 [35:30<28:15, 11.25it/s]

 55%|███████████████████▊                | 23448/42525 [35:31<28:50, 11.03it/s]

 55%|███████████████████▊                | 23452/42525 [35:31<27:45, 11.45it/s]

 55%|███████████████████▊                | 23456/42525 [35:32<29:06, 10.92it/s]

 55%|███████████████████▊                | 23460/42525 [35:32<29:47, 10.66it/s]

 55%|███████████████████▊                | 23464/42525 [35:32<28:27, 11.16it/s]

 55%|███████████████████▊                | 23468/42525 [35:33<28:54, 10.98it/s]

 55%|███████████████████▊                | 23472/42525 [35:33<27:54, 11.38it/s]

 55%|███████████████████▊                | 23476/42525 [35:33<27:13, 11.66it/s]

 55%|███████████████████▉                | 23480/42525 [35:34<27:24, 11.58it/s]

 55%|███████████████████▉                | 23484/42525 [35:34<27:01, 11.75it/s]

 55%|███████████████████▉                | 23488/42525 [35:34<26:54, 11.79it/s]

 55%|███████████████████▉                | 23492/42525 [35:35<27:31, 11.53it/s]

 55%|███████████████████▉                | 23496/42525 [35:35<28:22, 11.18it/s]

 55%|███████████████████▉                | 23500/42525 [35:35<27:49, 11.40it/s]

 55%|███████████████████▉                | 23504/42525 [35:36<27:13, 11.64it/s]

 55%|███████████████████▉                | 23508/42525 [35:36<26:57, 11.76it/s]

 55%|███████████████████▉                | 23512/42525 [35:36<27:42, 11.44it/s]

 55%|███████████████████▉                | 23516/42525 [35:37<27:50, 11.38it/s]

 55%|███████████████████▉                | 23520/42525 [35:37<28:08, 11.25it/s]

 55%|███████████████████▉                | 23524/42525 [35:37<27:46, 11.40it/s]

 55%|███████████████████▉                | 23528/42525 [35:38<28:44, 11.01it/s]

 55%|███████████████████▉                | 23532/42525 [35:38<28:45, 11.01it/s]

 55%|███████████████████▉                | 23536/42525 [35:39<27:59, 11.31it/s]

 55%|███████████████████▉                | 23540/42525 [35:39<28:17, 11.19it/s]

 55%|███████████████████▉                | 23544/42525 [35:39<28:40, 11.03it/s]

 55%|███████████████████▉                | 23548/42525 [35:40<28:48, 10.98it/s]

 55%|███████████████████▉                | 23552/42525 [35:40<27:37, 11.44it/s]

 55%|███████████████████▉                | 23556/42525 [35:40<28:00, 11.29it/s]

 55%|███████████████████▉                | 23560/42525 [35:41<27:26, 11.52it/s]

 55%|███████████████████▉                | 23564/42525 [35:41<27:33, 11.47it/s]

 55%|███████████████████▉                | 23568/42525 [35:41<28:06, 11.24it/s]

 55%|███████████████████▉                | 23572/42525 [35:42<26:13, 12.05it/s]

 55%|███████████████████▉                | 23576/42525 [35:42<25:48, 12.23it/s]

 55%|███████████████████▉                | 23580/42525 [35:42<25:11, 12.53it/s]

 55%|███████████████████▉                | 23584/42525 [35:43<25:45, 12.25it/s]

 55%|███████████████████▉                | 23588/42525 [35:43<25:00, 12.62it/s]

 55%|███████████████████▉                | 23592/42525 [35:43<24:44, 12.76it/s]

 55%|███████████████████▉                | 23596/42525 [35:44<25:01, 12.61it/s]

 55%|███████████████████▉                | 23600/42525 [35:44<25:39, 12.29it/s]

 56%|███████████████████▉                | 23604/42525 [35:44<25:59, 12.13it/s]

 56%|███████████████████▉                | 23608/42525 [35:45<24:45, 12.73it/s]

 56%|███████████████████▉                | 23612/42525 [35:45<26:18, 11.99it/s]

 56%|███████████████████▉                | 23616/42525 [35:45<25:42, 12.26it/s]

 56%|███████████████████▉                | 23620/42525 [35:46<26:26, 11.92it/s]

 56%|███████████████████▉                | 23624/42525 [35:46<25:29, 12.36it/s]

 56%|████████████████████                | 23628/42525 [35:46<24:21, 12.93it/s]

 56%|████████████████████                | 23632/42525 [35:47<24:05, 13.07it/s]

 56%|████████████████████                | 23636/42525 [35:47<24:25, 12.89it/s]

 56%|████████████████████                | 23640/42525 [35:47<24:11, 13.01it/s]

 56%|████████████████████                | 23644/42525 [35:47<23:55, 13.15it/s]

 56%|████████████████████                | 23648/42525 [35:48<26:07, 12.04it/s]

 56%|████████████████████                | 23652/42525 [35:48<25:18, 12.43it/s]

 56%|████████████████████                | 23656/42525 [35:48<24:47, 12.68it/s]

 56%|████████████████████                | 23660/42525 [35:49<25:22, 12.39it/s]

 56%|████████████████████                | 23664/42525 [35:49<24:34, 12.79it/s]

 56%|████████████████████                | 23668/42525 [35:49<25:59, 12.09it/s]

 56%|████████████████████                | 23672/42525 [35:50<24:05, 13.04it/s]

 56%|████████████████████                | 23676/42525 [35:50<23:42, 13.26it/s]

 56%|████████████████████                | 23680/42525 [35:50<24:07, 13.01it/s]

 56%|████████████████████                | 23684/42525 [35:51<25:46, 12.18it/s]

 56%|████████████████████                | 23688/42525 [35:51<27:29, 11.42it/s]

 56%|████████████████████                | 23692/42525 [35:51<27:07, 11.57it/s]

 56%|████████████████████                | 23696/42525 [35:52<26:15, 11.95it/s]

 56%|████████████████████                | 23700/42525 [35:52<26:10, 11.99it/s]

 56%|████████████████████                | 23704/42525 [35:52<25:03, 12.52it/s]

 56%|████████████████████                | 23708/42525 [35:53<23:58, 13.08it/s]

 56%|████████████████████                | 23712/42525 [35:53<25:34, 12.26it/s]

 56%|████████████████████                | 23716/42525 [35:53<25:25, 12.33it/s]

 56%|████████████████████                | 23720/42525 [35:54<26:35, 11.79it/s]

 56%|████████████████████                | 23722/42525 [35:54<26:41, 11.74it/s]

 56%|████████████████████                | 23726/42525 [35:54<27:51, 11.24it/s]

 56%|████████████████████                | 23730/42525 [35:55<27:58, 11.20it/s]

 56%|████████████████████                | 23734/42525 [35:55<28:43, 10.91it/s]

 56%|████████████████████                | 23738/42525 [35:55<27:43, 11.29it/s]

 56%|████████████████████                | 23742/42525 [35:56<28:20, 11.05it/s]

 56%|████████████████████                | 23746/42525 [35:56<28:43, 10.90it/s]

 56%|████████████████████                | 23750/42525 [35:56<27:13, 11.49it/s]

 56%|████████████████████                | 23754/42525 [35:57<28:21, 11.03it/s]

 56%|████████████████████                | 23758/42525 [35:57<26:42, 11.71it/s]

 56%|████████████████████                | 23762/42525 [35:57<26:13, 11.92it/s]

 56%|████████████████████                | 23766/42525 [35:58<26:06, 11.98it/s]

 56%|████████████████████                | 23770/42525 [35:58<26:54, 11.62it/s]

 56%|████████████████████▏               | 23774/42525 [35:58<28:58, 10.79it/s]

 56%|████████████████████▏               | 23778/42525 [35:59<28:50, 10.83it/s]

 56%|████████████████████▏               | 23782/42525 [35:59<27:57, 11.17it/s]

 56%|████████████████████▏               | 23786/42525 [36:00<29:00, 10.76it/s]

 56%|████████████████████▏               | 23790/42525 [36:00<28:21, 11.01it/s]

 56%|████████████████████▏               | 23794/42525 [36:00<28:52, 10.81it/s]

 56%|████████████████████▏               | 23798/42525 [36:01<27:39, 11.28it/s]

 56%|████████████████████▏               | 23802/42525 [36:01<27:08, 11.50it/s]

 56%|████████████████████▏               | 23806/42525 [36:01<28:30, 10.95it/s]

 56%|████████████████████▏               | 23810/42525 [36:02<28:05, 11.11it/s]

 56%|████████████████████▏               | 23814/42525 [36:02<27:54, 11.17it/s]

 56%|████████████████████▏               | 23818/42525 [36:02<26:21, 11.82it/s]

 56%|████████████████████▏               | 23822/42525 [36:03<28:03, 11.11it/s]

 56%|████████████████████▏               | 23826/42525 [36:03<29:11, 10.68it/s]

 56%|████████████████████▏               | 23830/42525 [36:03<28:04, 11.10it/s]

 56%|████████████████████▏               | 23834/42525 [36:04<28:28, 10.94it/s]

 56%|████████████████████▏               | 23838/42525 [36:04<28:11, 11.05it/s]

 56%|████████████████████▏               | 23842/42525 [36:05<27:58, 11.13it/s]

 56%|████████████████████▏               | 23846/42525 [36:05<27:22, 11.37it/s]

 56%|████████████████████▏               | 23850/42525 [36:05<27:44, 11.22it/s]

 56%|████████████████████▏               | 23854/42525 [36:06<27:18, 11.39it/s]

 56%|████████████████████▏               | 23858/42525 [36:06<27:36, 11.27it/s]

 56%|████████████████████▏               | 23862/42525 [36:06<28:15, 11.01it/s]

 56%|████████████████████▏               | 23866/42525 [36:07<27:43, 11.21it/s]

 56%|████████████████████▏               | 23870/42525 [36:07<27:44, 11.21it/s]

 56%|████████████████████▏               | 23874/42525 [36:07<28:23, 10.95it/s]

 56%|████████████████████▏               | 23878/42525 [36:08<29:23, 10.57it/s]

 56%|████████████████████▏               | 23882/42525 [36:08<29:54, 10.39it/s]

 56%|████████████████████▏               | 23886/42525 [36:09<28:22, 10.95it/s]

 56%|████████████████████▏               | 23890/42525 [36:09<27:25, 11.33it/s]

 56%|████████████████████▏               | 23894/42525 [36:09<27:12, 11.41it/s]

 56%|████████████████████▏               | 23898/42525 [36:10<26:51, 11.56it/s]

 56%|████████████████████▏               | 23902/42525 [36:10<26:40, 11.64it/s]

 56%|████████████████████▏               | 23906/42525 [36:10<26:54, 11.53it/s]

 56%|████████████████████▏               | 23910/42525 [36:11<28:20, 10.95it/s]

 56%|████████████████████▏               | 23914/42525 [36:11<27:16, 11.37it/s]

 56%|████████████████████▏               | 23918/42525 [36:11<28:16, 10.97it/s]

 56%|████████████████████▎               | 23922/42525 [36:12<27:31, 11.26it/s]

 56%|████████████████████▎               | 23926/42525 [36:12<28:59, 10.69it/s]

 56%|████████████████████▎               | 23930/42525 [36:13<28:31, 10.86it/s]

 56%|████████████████████▎               | 23934/42525 [36:13<27:16, 11.36it/s]

 56%|████████████████████▎               | 23938/42525 [36:13<26:50, 11.54it/s]

 56%|████████████████████▎               | 23942/42525 [36:14<26:41, 11.60it/s]

 56%|████████████████████▎               | 23946/42525 [36:14<27:27, 11.28it/s]

 56%|████████████████████▎               | 23950/42525 [36:14<26:56, 11.49it/s]

 56%|████████████████████▎               | 23954/42525 [36:15<27:29, 11.26it/s]

 56%|████████████████████▎               | 23958/42525 [36:15<27:19, 11.33it/s]

 56%|████████████████████▎               | 23962/42525 [36:15<26:55, 11.49it/s]

 56%|████████████████████▎               | 23966/42525 [36:16<27:43, 11.15it/s]

 56%|████████████████████▎               | 23970/42525 [36:16<27:22, 11.30it/s]

 56%|████████████████████▎               | 23974/42525 [36:16<26:47, 11.54it/s]

 56%|████████████████████▎               | 23978/42525 [36:17<26:40, 11.59it/s]

 56%|████████████████████▎               | 23982/42525 [36:17<26:31, 11.65it/s]

 56%|████████████████████▎               | 23986/42525 [36:17<27:42, 11.15it/s]

 56%|████████████████████▎               | 23990/42525 [36:18<27:04, 11.41it/s]

 56%|████████████████████▎               | 23994/42525 [36:18<27:37, 11.18it/s]

 56%|████████████████████▎               | 23998/42525 [36:18<27:03, 11.41it/s]

 56%|████████████████████▎               | 24002/42525 [36:19<27:33, 11.20it/s]

 56%|████████████████████▎               | 24006/42525 [36:19<26:54, 11.47it/s]

 56%|████████████████████▎               | 24010/42525 [36:20<27:04, 11.40it/s]

 56%|████████████████████▎               | 24014/42525 [36:20<25:47, 11.96it/s]

 56%|████████████████████▎               | 24018/42525 [36:20<26:31, 11.63it/s]

 56%|████████████████████▎               | 24022/42525 [36:21<25:38, 12.03it/s]

 56%|████████████████████▎               | 24026/42525 [36:21<24:09, 12.76it/s]

 57%|████████████████████▎               | 24030/42525 [36:21<26:33, 11.61it/s]

 57%|████████████████████▎               | 24034/42525 [36:22<26:12, 11.76it/s]

 57%|████████████████████▎               | 24038/42525 [36:22<25:59, 11.86it/s]

 57%|████████████████████▎               | 24042/42525 [36:22<25:21, 12.15it/s]

 57%|████████████████████▎               | 24046/42525 [36:22<24:18, 12.67it/s]

 57%|████████████████████▎               | 24050/42525 [36:23<23:28, 13.12it/s]

 57%|████████████████████▎               | 24054/42525 [36:23<25:57, 11.86it/s]

 57%|████████████████████▎               | 24058/42525 [36:23<25:20, 12.15it/s]

 57%|████████████████████▎               | 24062/42525 [36:24<25:32, 12.05it/s]

 57%|████████████████████▎               | 24066/42525 [36:24<26:13, 11.73it/s]

 57%|████████████████████▍               | 24070/42525 [36:24<25:35, 12.02it/s]

 57%|████████████████████▍               | 24074/42525 [36:25<24:22, 12.61it/s]

 57%|████████████████████▍               | 24078/42525 [36:25<23:58, 12.83it/s]

 57%|████████████████████▍               | 24082/42525 [36:25<23:55, 12.84it/s]

 57%|████████████████████▍               | 24084/42525 [36:26<24:47, 12.40it/s]

 57%|████████████████████▍               | 24088/42525 [36:26<26:55, 11.41it/s]

 57%|████████████████████▍               | 24092/42525 [36:26<27:24, 11.21it/s]

 57%|████████████████████▍               | 24096/42525 [36:27<26:30, 11.59it/s]

 57%|████████████████████▍               | 24100/42525 [36:27<24:56, 12.31it/s]

 57%|████████████████████▍               | 24104/42525 [36:27<24:25, 12.57it/s]

 57%|████████████████████▍               | 24108/42525 [36:28<24:24, 12.58it/s]

 57%|████████████████████▍               | 24112/42525 [36:28<25:34, 12.00it/s]

 57%|████████████████████▍               | 24116/42525 [36:28<25:08, 12.21it/s]

 57%|████████████████████▍               | 24120/42525 [36:29<26:16, 11.68it/s]

 57%|████████████████████▍               | 24124/42525 [36:29<25:51, 11.86it/s]

 57%|████████████████████▍               | 24128/42525 [36:29<26:47, 11.45it/s]

 57%|████████████████████▍               | 24132/42525 [36:30<26:15, 11.67it/s]

 57%|████████████████████▍               | 24136/42525 [36:30<27:14, 11.25it/s]

 57%|████████████████████▍               | 24140/42525 [36:30<26:15, 11.67it/s]

 57%|████████████████████▍               | 24144/42525 [36:31<25:22, 12.08it/s]

 57%|████████████████████▍               | 24148/42525 [36:31<26:37, 11.50it/s]

 57%|████████████████████▍               | 24152/42525 [36:31<26:03, 11.75it/s]

 57%|████████████████████▍               | 24156/42525 [36:32<27:36, 11.09it/s]

 57%|████████████████████▍               | 24160/42525 [36:32<27:06, 11.29it/s]

 57%|████████████████████▍               | 24164/42525 [36:32<24:33, 12.46it/s]

 57%|████████████████████▍               | 24168/42525 [36:33<24:49, 12.33it/s]

 57%|████████████████████▍               | 24172/42525 [36:33<25:43, 11.89it/s]

 57%|████████████████████▍               | 24176/42525 [36:33<25:32, 11.97it/s]

 57%|████████████████████▍               | 24180/42525 [36:34<24:01, 12.72it/s]

 57%|████████████████████▍               | 24184/42525 [36:34<23:32, 12.99it/s]

 57%|████████████████████▍               | 24188/42525 [36:34<24:18, 12.57it/s]

 57%|████████████████████▍               | 24192/42525 [36:35<25:58, 11.76it/s]

 57%|████████████████████▍               | 24196/42525 [36:35<24:41, 12.37it/s]

 57%|████████████████████▍               | 24200/42525 [36:35<25:11, 12.12it/s]

 57%|████████████████████▍               | 24204/42525 [36:36<25:24, 12.02it/s]

 57%|████████████████████▍               | 24208/42525 [36:36<24:41, 12.36it/s]

 57%|████████████████████▍               | 24212/42525 [36:36<24:17, 12.56it/s]

 57%|████████████████████▌               | 24216/42525 [36:37<24:49, 12.29it/s]

 57%|████████████████████▌               | 24220/42525 [36:37<25:52, 11.79it/s]

 57%|████████████████████▌               | 24224/42525 [36:37<25:44, 11.85it/s]

 57%|████████████████████▌               | 24228/42525 [36:38<25:47, 11.82it/s]

 57%|████████████████████▌               | 24232/42525 [36:38<26:06, 11.68it/s]

 57%|████████████████████▌               | 24236/42525 [36:38<26:22, 11.56it/s]

 57%|████████████████████▌               | 24240/42525 [36:39<26:05, 11.68it/s]

 57%|████████████████████▌               | 24244/42525 [36:39<26:41, 11.41it/s]

 57%|████████████████████▌               | 24248/42525 [36:39<24:50, 12.26it/s]

 57%|████████████████████▌               | 24252/42525 [36:40<23:46, 12.81it/s]

 57%|████████████████████▌               | 24256/42525 [36:40<25:25, 11.98it/s]

 57%|████████████████████▌               | 24260/42525 [36:40<24:58, 12.19it/s]

 57%|████████████████████▌               | 24264/42525 [36:41<24:24, 12.47it/s]

 57%|████████████████████▌               | 24268/42525 [36:41<24:30, 12.42it/s]

 57%|████████████████████▌               | 24272/42525 [36:41<24:30, 12.41it/s]

 57%|████████████████████▌               | 24276/42525 [36:42<25:23, 11.98it/s]

 57%|████████████████████▌               | 24280/42525 [36:42<24:16, 12.53it/s]

 57%|████████████████████▌               | 24284/42525 [36:42<24:31, 12.40it/s]

 57%|████████████████████▌               | 24288/42525 [36:43<25:47, 11.79it/s]

 57%|████████████████████▌               | 24292/42525 [36:43<25:17, 12.01it/s]

 57%|████████████████████▌               | 24296/42525 [36:43<24:36, 12.35it/s]

 57%|████████████████████▌               | 24300/42525 [36:44<23:10, 13.10it/s]

 57%|████████████████████▌               | 24304/42525 [36:44<24:11, 12.55it/s]

 57%|████████████████████▌               | 24308/42525 [36:44<25:22, 11.96it/s]

 57%|████████████████████▌               | 24312/42525 [36:45<24:37, 12.32it/s]

 57%|████████████████████▌               | 24316/42525 [36:45<27:11, 11.16it/s]

 57%|████████████████████▌               | 24320/42525 [36:45<25:16, 12.01it/s]

 57%|████████████████████▌               | 24324/42525 [36:46<24:49, 12.22it/s]

 57%|████████████████████▌               | 24328/42525 [36:46<25:02, 12.11it/s]

 57%|████████████████████▌               | 24332/42525 [36:46<25:20, 11.97it/s]

 57%|████████████████████▌               | 24336/42525 [36:47<24:10, 12.54it/s]

 57%|████████████████████▌               | 24340/42525 [36:47<25:13, 12.01it/s]

 57%|████████████████████▌               | 24344/42525 [36:47<25:03, 12.09it/s]

 57%|████████████████████▌               | 24348/42525 [36:48<24:56, 12.15it/s]

 57%|████████████████████▌               | 24350/42525 [36:48<26:09, 11.58it/s]

 57%|████████████████████▌               | 24354/42525 [36:48<26:21, 11.49it/s]

 57%|████████████████████▌               | 24358/42525 [36:48<26:19, 11.51it/s]

 57%|████████████████████▌               | 24362/42525 [36:49<25:10, 12.02it/s]

 57%|████████████████████▋               | 24366/42525 [36:49<25:07, 12.05it/s]

 57%|████████████████████▋               | 24370/42525 [36:49<26:32, 11.40it/s]

 57%|████████████████████▋               | 24374/42525 [36:50<24:38, 12.28it/s]

 57%|████████████████████▋               | 24378/42525 [36:50<23:54, 12.65it/s]

 57%|████████████████████▋               | 24382/42525 [36:50<23:19, 12.97it/s]

 57%|████████████████████▋               | 24386/42525 [36:51<22:53, 13.20it/s]

 57%|████████████████████▋               | 24390/42525 [36:51<23:07, 13.07it/s]

 57%|████████████████████▋               | 24394/42525 [36:51<24:18, 12.43it/s]

 57%|████████████████████▋               | 24398/42525 [36:52<23:58, 12.60it/s]

 57%|████████████████████▋               | 24402/42525 [36:52<25:18, 11.93it/s]

 57%|████████████████████▋               | 24406/42525 [36:52<25:06, 12.03it/s]

 57%|████████████████████▋               | 24410/42525 [36:53<23:56, 12.61it/s]

 57%|████████████████████▋               | 24414/42525 [36:53<23:28, 12.85it/s]

 57%|████████████████████▋               | 24418/42525 [36:53<24:32, 12.30it/s]

 57%|████████████████████▋               | 24422/42525 [36:54<23:51, 12.64it/s]

 57%|████████████████████▋               | 24426/42525 [36:54<23:58, 12.58it/s]

 57%|████████████████████▋               | 24430/42525 [36:54<25:26, 11.85it/s]

 57%|████████████████████▋               | 24434/42525 [36:55<26:19, 11.45it/s]

 57%|████████████████████▋               | 24438/42525 [36:55<25:37, 11.77it/s]

 57%|████████████████████▋               | 24442/42525 [36:55<25:05, 12.01it/s]

 57%|████████████████████▋               | 24446/42525 [36:56<26:25, 11.40it/s]

 57%|████████████████████▋               | 24450/42525 [36:56<26:35, 11.33it/s]

 58%|████████████████████▋               | 24454/42525 [36:56<25:49, 11.66it/s]

 58%|████████████████████▋               | 24458/42525 [36:57<26:14, 11.48it/s]

 58%|████████████████████▋               | 24462/42525 [36:57<23:48, 12.65it/s]

 58%|████████████████████▋               | 24466/42525 [36:57<24:32, 12.27it/s]

 58%|████████████████████▋               | 24470/42525 [36:58<23:25, 12.84it/s]

 58%|████████████████████▋               | 24474/42525 [36:58<25:00, 12.03it/s]

 58%|████████████████████▋               | 24478/42525 [36:58<25:04, 11.99it/s]

 58%|████████████████████▋               | 24482/42525 [36:59<24:35, 12.23it/s]

 58%|████████████████████▋               | 24486/42525 [36:59<24:45, 12.14it/s]

 58%|████████████████████▋               | 24490/42525 [36:59<24:03, 12.50it/s]

 58%|████████████████████▋               | 24494/42525 [37:00<26:42, 11.25it/s]

 58%|████████████████████▋               | 24498/42525 [37:00<24:48, 12.11it/s]

 58%|████████████████████▋               | 24502/42525 [37:00<25:19, 11.86it/s]

 58%|████████████████████▋               | 24506/42525 [37:01<25:07, 11.95it/s]

 58%|████████████████████▋               | 24510/42525 [37:01<23:35, 12.72it/s]

 58%|████████████████████▊               | 24514/42525 [37:01<24:30, 12.25it/s]

 58%|████████████████████▊               | 24518/42525 [37:02<24:40, 12.16it/s]

 58%|████████████████████▊               | 24522/42525 [37:02<26:17, 11.41it/s]

 58%|████████████████████▊               | 24526/42525 [37:02<26:36, 11.27it/s]

 58%|████████████████████▊               | 24530/42525 [37:03<26:38, 11.26it/s]

 58%|████████████████████▊               | 24534/42525 [37:03<26:01, 11.52it/s]

 58%|████████████████████▊               | 24538/42525 [37:03<26:10, 11.46it/s]

 58%|████████████████████▊               | 24542/42525 [37:04<26:05, 11.49it/s]

 58%|████████████████████▊               | 24546/42525 [37:04<25:47, 11.62it/s]

 58%|████████████████████▊               | 24550/42525 [37:04<25:47, 11.62it/s]

 58%|████████████████████▊               | 24554/42525 [37:05<27:10, 11.02it/s]

 58%|████████████████████▊               | 24558/42525 [37:05<26:18, 11.38it/s]

 58%|████████████████████▊               | 24562/42525 [37:05<25:45, 11.62it/s]

 58%|████████████████████▊               | 24566/42525 [37:06<26:11, 11.42it/s]

 58%|████████████████████▊               | 24570/42525 [37:06<26:36, 11.25it/s]

 58%|████████████████████▊               | 24574/42525 [37:07<26:48, 11.16it/s]

 58%|████████████████████▊               | 24578/42525 [37:07<26:57, 11.09it/s]

 58%|████████████████████▊               | 24582/42525 [37:07<26:28, 11.30it/s]

 58%|████████████████████▊               | 24586/42525 [37:08<26:01, 11.49it/s]

 58%|████████████████████▊               | 24590/42525 [37:08<27:05, 11.04it/s]

 58%|████████████████████▊               | 24594/42525 [37:08<27:19, 10.94it/s]

 58%|████████████████████▊               | 24598/42525 [37:09<26:24, 11.32it/s]

 58%|████████████████████▊               | 24602/42525 [37:09<26:03, 11.46it/s]

 58%|████████████████████▊               | 24606/42525 [37:09<27:20, 10.92it/s]

 58%|████████████████████▊               | 24610/42525 [37:10<27:26, 10.88it/s]

 58%|████████████████████▊               | 24614/42525 [37:10<27:32, 10.84it/s]

 58%|████████████████████▊               | 24618/42525 [37:11<28:24, 10.51it/s]

 58%|████████████████████▊               | 24622/42525 [37:11<27:14, 10.96it/s]

 58%|████████████████████▊               | 24626/42525 [37:11<27:21, 10.91it/s]

 58%|████████████████████▊               | 24630/42525 [37:12<26:12, 11.38it/s]

 58%|████████████████████▊               | 24634/42525 [37:12<25:41, 11.60it/s]

 58%|████████████████████▊               | 24638/42525 [37:12<26:28, 11.26it/s]

 58%|████████████████████▊               | 24642/42525 [37:13<26:02, 11.45it/s]

 58%|████████████████████▊               | 24646/42525 [37:13<27:08, 10.98it/s]

 58%|████████████████████▊               | 24650/42525 [37:13<27:34, 10.81it/s]

 58%|████████████████████▊               | 24654/42525 [37:14<26:40, 11.16it/s]

 58%|████████████████████▊               | 24658/42525 [37:14<27:26, 10.85it/s]

 58%|████████████████████▉               | 24662/42525 [37:14<26:12, 11.36it/s]

 58%|████████████████████▉               | 24666/42525 [37:15<26:38, 11.17it/s]

 58%|████████████████████▉               | 24670/42525 [37:15<26:50, 11.09it/s]

 58%|████████████████████▉               | 24674/42525 [37:16<26:00, 11.44it/s]

 58%|████████████████████▉               | 24678/42525 [37:16<26:07, 11.39it/s]

 58%|████████████████████▉               | 24682/42525 [37:16<26:34, 11.19it/s]

 58%|████████████████████▉               | 24686/42525 [37:17<26:38, 11.16it/s]

 58%|████████████████████▉               | 24690/42525 [37:17<25:53, 11.48it/s]

 58%|████████████████████▉               | 24694/42525 [37:17<26:14, 11.32it/s]

 58%|████████████████████▉               | 24698/42525 [37:18<26:07, 11.37it/s]

 58%|████████████████████▉               | 24702/42525 [37:18<26:42, 11.12it/s]

 58%|████████████████████▉               | 24706/42525 [37:18<25:57, 11.44it/s]

 58%|████████████████████▉               | 24710/42525 [37:19<26:00, 11.42it/s]

 58%|████████████████████▉               | 24714/42525 [37:19<27:37, 10.75it/s]

 58%|████████████████████▉               | 24718/42525 [37:20<28:25, 10.44it/s]

 58%|████████████████████▉               | 24722/42525 [37:20<27:38, 10.74it/s]

 58%|████████████████████▉               | 24726/42525 [37:20<26:26, 11.22it/s]

 58%|████████████████████▉               | 24730/42525 [37:21<26:32, 11.17it/s]

 58%|████████████████████▉               | 24734/42525 [37:21<25:45, 11.51it/s]

 58%|████████████████████▉               | 24738/42525 [37:21<25:34, 11.59it/s]

 58%|████████████████████▉               | 24742/42525 [37:22<25:49, 11.48it/s]

 58%|████████████████████▉               | 24746/42525 [37:22<26:12, 11.31it/s]

 58%|████████████████████▉               | 24750/42525 [37:22<25:35, 11.58it/s]

 58%|████████████████████▉               | 24754/42525 [37:23<25:20, 11.69it/s]

 58%|████████████████████▉               | 24758/42525 [37:23<25:53, 11.43it/s]

 58%|████████████████████▉               | 24762/42525 [37:23<25:21, 11.68it/s]

 58%|████████████████████▉               | 24766/42525 [37:24<25:03, 11.81it/s]

 58%|████████████████████▉               | 24770/42525 [37:24<25:03, 11.81it/s]

 58%|████████████████████▉               | 24774/42525 [37:24<25:03, 11.81it/s]

 58%|████████████████████▉               | 24778/42525 [37:25<25:31, 11.59it/s]

 58%|████████████████████▉               | 24782/42525 [37:25<26:07, 11.32it/s]

 58%|████████████████████▉               | 24786/42525 [37:25<26:00, 11.37it/s]

 58%|████████████████████▉               | 24790/42525 [37:26<25:29, 11.60it/s]

 58%|████████████████████▉               | 24794/42525 [37:26<26:57, 10.96it/s]

 58%|████████████████████▉               | 24798/42525 [37:27<27:31, 10.73it/s]

 58%|████████████████████▉               | 24802/42525 [37:27<27:33, 10.72it/s]

 58%|████████████████████▉               | 24806/42525 [37:27<26:35, 11.11it/s]

 58%|█████████████████████               | 24810/42525 [37:28<26:24, 11.18it/s]

 58%|█████████████████████               | 24814/42525 [37:28<26:47, 11.02it/s]

 58%|█████████████████████               | 24818/42525 [37:28<25:55, 11.39it/s]

 58%|█████████████████████               | 24820/42525 [37:28<25:44, 11.46it/s]

 58%|█████████████████████               | 24824/42525 [37:29<27:29, 10.73it/s]

 58%|█████████████████████               | 24828/42525 [37:29<27:16, 10.81it/s]

 58%|█████████████████████               | 24832/42525 [37:30<26:09, 11.27it/s]

 58%|█████████████████████               | 24834/42525 [37:30<25:16, 11.66it/s]

 58%|█████████████████████               | 24838/42525 [37:30<26:28, 11.13it/s]

 58%|█████████████████████               | 24842/42525 [37:30<24:47, 11.89it/s]

 58%|█████████████████████               | 24846/42525 [37:31<23:40, 12.44it/s]

 58%|█████████████████████               | 24850/42525 [37:31<24:06, 12.22it/s]

 58%|█████████████████████               | 24854/42525 [37:31<24:38, 11.95it/s]

 58%|█████████████████████               | 24858/42525 [37:32<24:11, 12.17it/s]

 58%|█████████████████████               | 24862/42525 [37:32<23:32, 12.50it/s]

 58%|█████████████████████               | 24866/42525 [37:32<23:50, 12.34it/s]

 58%|█████████████████████               | 24870/42525 [37:33<22:56, 12.82it/s]

 58%|█████████████████████               | 24874/42525 [37:33<24:13, 12.14it/s]

 59%|█████████████████████               | 24878/42525 [37:33<24:18, 12.10it/s]

 59%|█████████████████████               | 24882/42525 [37:34<24:04, 12.22it/s]

 59%|█████████████████████               | 24886/42525 [37:34<24:19, 12.08it/s]

 59%|█████████████████████               | 24890/42525 [37:34<25:36, 11.48it/s]

 59%|█████████████████████               | 24894/42525 [37:35<26:27, 11.11it/s]

 59%|█████████████████████               | 24898/42525 [37:35<25:43, 11.42it/s]

 59%|█████████████████████               | 24902/42525 [37:35<25:20, 11.59it/s]

 59%|█████████████████████               | 24906/42525 [37:36<25:54, 11.33it/s]

 59%|█████████████████████               | 24910/42525 [37:36<26:07, 11.24it/s]

 59%|█████████████████████               | 24912/42525 [37:36<25:59, 11.30it/s]

 59%|█████████████████████               | 24916/42525 [37:37<27:31, 10.66it/s]

 59%|█████████████████████               | 24920/42525 [37:37<27:03, 10.85it/s]

 59%|█████████████████████               | 24924/42525 [37:37<27:05, 10.83it/s]

 59%|█████████████████████               | 24928/42525 [37:38<26:00, 11.28it/s]

 59%|█████████████████████               | 24932/42525 [37:38<26:31, 11.05it/s]

 59%|█████████████████████               | 24936/42525 [37:39<25:59, 11.28it/s]

 59%|█████████████████████               | 24940/42525 [37:39<25:28, 11.50it/s]

 59%|█████████████████████               | 24944/42525 [37:39<25:50, 11.34it/s]

 59%|█████████████████████               | 24948/42525 [37:40<25:45, 11.37it/s]

 59%|█████████████████████               | 24952/42525 [37:40<25:13, 11.61it/s]

 59%|█████████████████████▏              | 24956/42525 [37:40<25:22, 11.54it/s]

 59%|█████████████████████▏              | 24960/42525 [37:41<25:02, 11.69it/s]

 59%|█████████████████████▏              | 24964/42525 [37:41<25:52, 11.31it/s]

 59%|█████████████████████▏              | 24968/42525 [37:41<26:06, 11.21it/s]

 59%|█████████████████████▏              | 24972/42525 [37:42<26:51, 10.89it/s]

 59%|█████████████████████▏              | 24976/42525 [37:42<26:11, 11.17it/s]

 59%|█████████████████████▏              | 24980/42525 [37:42<26:09, 11.18it/s]

 59%|█████████████████████▏              | 24984/42525 [37:43<26:29, 11.04it/s]

 59%|█████████████████████▏              | 24988/42525 [37:43<26:36, 10.98it/s]

 59%|█████████████████████▏              | 24992/42525 [37:44<26:41, 10.95it/s]

 59%|█████████████████████▏              | 24996/42525 [37:44<26:41, 10.95it/s]

 59%|█████████████████████▏              | 25000/42525 [37:44<26:23, 11.07it/s]

 59%|█████████████████████▏              | 25004/42525 [37:45<26:17, 11.10it/s]

 59%|█████████████████████▏              | 25008/42525 [37:45<26:01, 11.22it/s]

 59%|█████████████████████▏              | 25012/42525 [37:45<26:47, 10.90it/s]

 59%|█████████████████████▏              | 25016/42525 [37:46<25:43, 11.34it/s]

 59%|█████████████████████▏              | 25020/42525 [37:46<25:21, 11.50it/s]

 59%|█████████████████████▏              | 25024/42525 [37:46<25:50, 11.29it/s]

 59%|█████████████████████▏              | 25028/42525 [37:47<25:48, 11.30it/s]

 59%|█████████████████████▏              | 25032/42525 [37:47<25:24, 11.48it/s]

 59%|█████████████████████▏              | 25036/42525 [37:47<26:14, 11.11it/s]

 59%|█████████████████████▏              | 25040/42525 [37:48<25:23, 11.48it/s]

 59%|█████████████████████▏              | 25044/42525 [37:48<25:09, 11.58it/s]

 59%|█████████████████████▏              | 25048/42525 [37:48<24:58, 11.66it/s]

 59%|█████████████████████▏              | 25050/42525 [37:49<24:54, 11.69it/s]

 59%|█████████████████████▏              | 25054/42525 [37:49<26:15, 11.09it/s]

 59%|█████████████████████▏              | 25058/42525 [37:49<27:13, 10.69it/s]

 59%|█████████████████████▏              | 25062/42525 [37:50<26:17, 11.07it/s]

 59%|█████████████████████▏              | 25066/42525 [37:50<25:58, 11.20it/s]

 59%|█████████████████████▏              | 25070/42525 [37:50<25:17, 11.50it/s]

 59%|█████████████████████▏              | 25074/42525 [37:51<25:04, 11.60it/s]

 59%|█████████████████████▏              | 25078/42525 [37:51<24:58, 11.65it/s]

 59%|█████████████████████▏              | 25082/42525 [37:51<24:51, 11.70it/s]

 59%|█████████████████████▏              | 25086/42525 [37:52<24:08, 12.04it/s]

 59%|█████████████████████▏              | 25090/42525 [37:52<24:20, 11.94it/s]

 59%|█████████████████████▏              | 25094/42525 [37:52<24:26, 11.89it/s]

 59%|█████████████████████▏              | 25098/42525 [37:53<24:54, 11.66it/s]

 59%|█████████████████████▎              | 25102/42525 [37:53<25:52, 11.22it/s]

 59%|█████████████████████▎              | 25106/42525 [37:54<25:23, 11.44it/s]

 59%|█████████████████████▎              | 25110/42525 [37:54<25:08, 11.55it/s]

 59%|█████████████████████▎              | 25114/42525 [37:54<25:50, 11.23it/s]

 59%|█████████████████████▎              | 25118/42525 [37:55<25:15, 11.48it/s]

 59%|█████████████████████▎              | 25122/42525 [37:55<25:16, 11.48it/s]

 59%|█████████████████████▎              | 25126/42525 [37:55<25:00, 11.59it/s]

 59%|█████████████████████▎              | 25130/42525 [37:56<25:29, 11.37it/s]

 59%|█████████████████████▎              | 25134/42525 [37:56<25:37, 11.31it/s]

 59%|█████████████████████▎              | 25138/42525 [37:56<26:13, 11.05it/s]

 59%|█████████████████████▎              | 25142/42525 [37:57<26:05, 11.10it/s]

 59%|█████████████████████▎              | 25146/42525 [37:57<27:05, 10.69it/s]

 59%|█████████████████████▎              | 25150/42525 [37:57<25:56, 11.16it/s]

 59%|█████████████████████▎              | 25154/42525 [37:58<25:51, 11.20it/s]

 59%|█████████████████████▎              | 25158/42525 [37:58<25:05, 11.54it/s]

 59%|█████████████████████▎              | 25162/42525 [37:58<24:53, 11.63it/s]

 59%|█████████████████████▎              | 25166/42525 [37:59<24:30, 11.80it/s]

 59%|█████████████████████▎              | 25170/42525 [37:59<24:40, 11.72it/s]

 59%|█████████████████████▎              | 25174/42525 [38:00<25:31, 11.33it/s]

 59%|█████████████████████▎              | 25178/42525 [38:00<25:54, 11.16it/s]

 59%|█████████████████████▎              | 25182/42525 [38:00<25:58, 11.13it/s]

 59%|█████████████████████▎              | 25186/42525 [38:01<25:56, 11.14it/s]

 59%|█████████████████████▎              | 25190/42525 [38:01<26:40, 10.83it/s]

 59%|█████████████████████▎              | 25194/42525 [38:01<25:45, 11.21it/s]

 59%|█████████████████████▎              | 25198/42525 [38:02<25:35, 11.29it/s]

 59%|█████████████████████▎              | 25202/42525 [38:02<26:03, 11.08it/s]

 59%|█████████████████████▎              | 25206/42525 [38:02<25:19, 11.40it/s]

 59%|█████████████████████▎              | 25210/42525 [38:03<25:51, 11.16it/s]

 59%|█████████████████████▎              | 25214/42525 [38:03<25:04, 11.50it/s]

 59%|█████████████████████▎              | 25218/42525 [38:03<24:50, 11.61it/s]

 59%|█████████████████████▎              | 25222/42525 [38:04<26:31, 10.87it/s]

 59%|█████████████████████▎              | 25226/42525 [38:04<26:36, 10.84it/s]

 59%|█████████████████████▎              | 25230/42525 [38:05<25:23, 11.35it/s]

 59%|█████████████████████▎              | 25234/42525 [38:05<24:58, 11.54it/s]

 59%|█████████████████████▎              | 25236/42525 [38:05<24:52, 11.59it/s]

 59%|█████████████████████▎              | 25240/42525 [38:05<25:42, 11.20it/s]

 59%|█████████████████████▎              | 25244/42525 [38:06<25:00, 11.51it/s]

 59%|█████████████████████▎              | 25248/42525 [38:06<24:58, 11.53it/s]

 59%|█████████████████████▍              | 25252/42525 [38:06<25:07, 11.46it/s]

 59%|█████████████████████▍              | 25256/42525 [38:07<25:25, 11.32it/s]

 59%|█████████████████████▍              | 25260/42525 [38:07<25:00, 11.51it/s]

 59%|█████████████████████▍              | 25264/42525 [38:08<26:26, 10.88it/s]

 59%|█████████████████████▍              | 25268/42525 [38:08<26:01, 11.05it/s]

 59%|█████████████████████▍              | 25272/42525 [38:08<26:20, 10.91it/s]

 59%|█████████████████████▍              | 25276/42525 [38:09<25:29, 11.28it/s]

 59%|█████████████████████▍              | 25280/42525 [38:09<26:49, 10.72it/s]

 59%|█████████████████████▍              | 25284/42525 [38:09<26:13, 10.96it/s]

 59%|█████████████████████▍              | 25288/42525 [38:10<25:50, 11.12it/s]

 59%|█████████████████████▍              | 25292/42525 [38:10<25:27, 11.28it/s]

 59%|█████████████████████▍              | 25296/42525 [38:10<25:09, 11.42it/s]

 59%|█████████████████████▍              | 25300/42525 [38:11<26:05, 11.00it/s]

 60%|█████████████████████▍              | 25304/42525 [38:11<26:30, 10.82it/s]

 60%|█████████████████████▍              | 25308/42525 [38:12<25:48, 11.12it/s]

 60%|█████████████████████▍              | 25312/42525 [38:12<25:24, 11.29it/s]

 60%|█████████████████████▍              | 25316/42525 [38:12<25:29, 11.25it/s]

 60%|█████████████████████▍              | 25320/42525 [38:13<26:20, 10.88it/s]

 60%|█████████████████████▍              | 25324/42525 [38:13<26:55, 10.65it/s]

 60%|█████████████████████▍              | 25328/42525 [38:13<26:33, 10.79it/s]

 60%|█████████████████████▍              | 25332/42525 [38:14<26:29, 10.81it/s]

 60%|█████████████████████▍              | 25336/42525 [38:14<27:10, 10.54it/s]

 60%|█████████████████████▍              | 25340/42525 [38:14<26:46, 10.70it/s]

 60%|█████████████████████▍              | 25344/42525 [38:15<26:09, 10.94it/s]

 60%|█████████████████████▍              | 25348/42525 [38:15<25:14, 11.34it/s]

 60%|█████████████████████▍              | 25352/42525 [38:16<25:42, 11.13it/s]

 60%|█████████████████████▍              | 25356/42525 [38:16<25:57, 11.02it/s]

 60%|█████████████████████▍              | 25360/42525 [38:16<26:08, 10.95it/s]

 60%|█████████████████████▍              | 25364/42525 [38:17<25:44, 11.11it/s]

 60%|█████████████████████▍              | 25368/42525 [38:17<24:57, 11.45it/s]

 60%|█████████████████████▍              | 25372/42525 [38:17<25:26, 11.24it/s]

 60%|█████████████████████▍              | 25376/42525 [38:18<24:50, 11.51it/s]

 60%|█████████████████████▍              | 25380/42525 [38:18<24:47, 11.53it/s]

 60%|█████████████████████▍              | 25384/42525 [38:18<24:41, 11.57it/s]

 60%|█████████████████████▍              | 25388/42525 [38:19<24:22, 11.72it/s]

 60%|█████████████████████▍              | 25390/42525 [38:19<24:29, 11.66it/s]

 60%|█████████████████████▍              | 25394/42525 [38:19<26:42, 10.69it/s]

 60%|█████████████████████▌              | 25398/42525 [38:20<26:17, 10.86it/s]

 60%|█████████████████████▌              | 25402/42525 [38:20<25:50, 11.04it/s]

 60%|█████████████████████▌              | 25406/42525 [38:20<26:23, 10.81it/s]

 60%|█████████████████████▌              | 25410/42525 [38:21<25:23, 11.23it/s]

 60%|█████████████████████▌              | 25414/42525 [38:21<25:56, 10.99it/s]

 60%|█████████████████████▌              | 25418/42525 [38:21<25:26, 11.21it/s]

 60%|█████████████████████▌              | 25422/42525 [38:22<25:54, 11.00it/s]

 60%|█████████████████████▌              | 25426/42525 [38:22<26:04, 10.93it/s]

 60%|█████████████████████▌              | 25428/42525 [38:22<25:38, 11.11it/s]

 60%|█████████████████████▌              | 25432/42525 [38:23<26:19, 10.82it/s]

 60%|█████████████████████▌              | 25436/42525 [38:23<25:14, 11.28it/s]

 60%|█████████████████████▌              | 25440/42525 [38:23<25:07, 11.34it/s]

 60%|█████████████████████▌              | 25444/42525 [38:24<24:34, 11.58it/s]

 60%|█████████████████████▌              | 25448/42525 [38:24<25:42, 11.07it/s]

 60%|█████████████████████▌              | 25452/42525 [38:24<24:58, 11.40it/s]

 60%|█████████████████████▌              | 25456/42525 [38:25<26:49, 10.61it/s]

 60%|█████████████████████▌              | 25460/42525 [38:25<25:49, 11.02it/s]

 60%|█████████████████████▌              | 25462/42525 [38:25<25:27, 11.17it/s]

 60%|█████████████████████▌              | 25466/42525 [38:26<27:04, 10.50it/s]

 60%|█████████████████████▌              | 25470/42525 [38:26<26:36, 10.68it/s]

 60%|█████████████████████▌              | 25474/42525 [38:27<26:01, 10.92it/s]

 60%|█████████████████████▌              | 25478/42525 [38:27<27:30, 10.33it/s]

 60%|█████████████████████▌              | 25482/42525 [38:27<26:41, 10.64it/s]

 60%|█████████████████████▌              | 25486/42525 [38:28<26:33, 10.70it/s]

 60%|█████████████████████▌              | 25490/42525 [38:28<25:50, 10.99it/s]

 60%|█████████████████████▌              | 25494/42525 [38:28<25:55, 10.95it/s]

 60%|█████████████████████▌              | 25498/42525 [38:29<26:46, 10.60it/s]

 60%|█████████████████████▌              | 25502/42525 [38:29<25:42, 11.03it/s]

 60%|█████████████████████▌              | 25506/42525 [38:30<25:36, 11.08it/s]

 60%|█████████████████████▌              | 25510/42525 [38:30<25:23, 11.17it/s]

 60%|█████████████████████▌              | 25514/42525 [38:30<24:45, 11.46it/s]

 60%|█████████████████████▌              | 25518/42525 [38:31<24:43, 11.46it/s]

 60%|█████████████████████▌              | 25522/42525 [38:31<25:52, 10.95it/s]

 60%|█████████████████████▌              | 25526/42525 [38:31<25:26, 11.14it/s]

 60%|█████████████████████▌              | 25530/42525 [38:32<25:28, 11.12it/s]

 60%|█████████████████████▌              | 25534/42525 [38:32<25:26, 11.13it/s]

 60%|█████████████████████▌              | 25538/42525 [38:32<25:20, 11.17it/s]

 60%|█████████████████████▌              | 25542/42525 [38:33<24:36, 11.50it/s]

 60%|█████████████████████▋              | 25546/42525 [38:33<26:07, 10.83it/s]

 60%|█████████████████████▋              | 25550/42525 [38:33<25:22, 11.15it/s]

 60%|█████████████████████▋              | 25554/42525 [38:34<24:51, 11.38it/s]

 60%|█████████████████████▋              | 25558/42525 [38:34<24:21, 11.61it/s]

 60%|█████████████████████▋              | 25562/42525 [38:34<24:29, 11.54it/s]

 60%|█████████████████████▋              | 25566/42525 [38:35<25:11, 11.22it/s]

 60%|█████████████████████▋              | 25570/42525 [38:35<24:35, 11.49it/s]

 60%|█████████████████████▋              | 25574/42525 [38:36<24:16, 11.64it/s]

 60%|█████████████████████▋              | 25578/42525 [38:36<25:07, 11.24it/s]

 60%|█████████████████████▋              | 25582/42525 [38:36<25:02, 11.28it/s]

 60%|█████████████████████▋              | 25586/42525 [38:37<24:25, 11.56it/s]

 60%|█████████████████████▋              | 25590/42525 [38:37<24:05, 11.72it/s]

 60%|█████████████████████▋              | 25594/42525 [38:37<26:02, 10.84it/s]

 60%|█████████████████████▋              | 25598/42525 [38:38<26:31, 10.63it/s]

 60%|█████████████████████▋              | 25602/42525 [38:38<25:56, 10.87it/s]

 60%|█████████████████████▋              | 25606/42525 [38:38<25:11, 11.19it/s]

 60%|█████████████████████▋              | 25610/42525 [38:39<25:09, 11.20it/s]

 60%|█████████████████████▋              | 25614/42525 [38:39<24:41, 11.42it/s]

 60%|█████████████████████▋              | 25618/42525 [38:39<25:54, 10.87it/s]

 60%|█████████████████████▋              | 25622/42525 [38:40<25:44, 10.94it/s]

 60%|█████████████████████▋              | 25626/42525 [38:40<25:55, 10.86it/s]

 60%|█████████████████████▋              | 25630/42525 [38:41<25:38, 10.98it/s]

 60%|█████████████████████▋              | 25634/42525 [38:41<26:42, 10.54it/s]

 60%|█████████████████████▋              | 25638/42525 [38:41<25:15, 11.14it/s]

 60%|█████████████████████▋              | 25642/42525 [38:42<25:10, 11.17it/s]

 60%|█████████████████████▋              | 25646/42525 [38:42<25:54, 10.86it/s]

 60%|█████████████████████▋              | 25650/42525 [38:42<25:56, 10.84it/s]

 60%|█████████████████████▋              | 25654/42525 [38:43<25:32, 11.01it/s]

 60%|█████████████████████▋              | 25658/42525 [38:43<24:43, 11.37it/s]

 60%|█████████████████████▋              | 25662/42525 [38:43<25:24, 11.06it/s]

 60%|█████████████████████▋              | 25666/42525 [38:44<24:57, 11.26it/s]

 60%|█████████████████████▋              | 25670/42525 [38:44<25:34, 10.98it/s]

 60%|█████████████████████▋              | 25674/42525 [38:45<25:19, 11.09it/s]

 60%|█████████████████████▋              | 25678/42525 [38:45<24:44, 11.35it/s]

 60%|█████████████████████▋              | 25682/42525 [38:45<25:11, 11.14it/s]

 60%|█████████████████████▋              | 25686/42525 [38:46<24:42, 11.36it/s]

 60%|█████████████████████▋              | 25690/42525 [38:46<25:16, 11.10it/s]

 60%|█████████████████████▊              | 25694/42525 [38:46<26:29, 10.59it/s]

 60%|█████████████████████▊              | 25698/42525 [38:47<25:06, 11.17it/s]

 60%|█████████████████████▊              | 25702/42525 [38:47<25:04, 11.18it/s]

 60%|█████████████████████▊              | 25706/42525 [38:47<24:43, 11.34it/s]

 60%|█████████████████████▊              | 25710/42525 [38:48<25:56, 10.80it/s]

 60%|█████████████████████▊              | 25714/42525 [38:48<25:00, 11.20it/s]

 60%|█████████████████████▊              | 25718/42525 [38:49<25:37, 10.93it/s]

 60%|█████████████████████▊              | 25722/42525 [38:49<25:56, 10.80it/s]

 60%|█████████████████████▊              | 25726/42525 [38:49<25:06, 11.15it/s]

 61%|█████████████████████▊              | 25730/42525 [38:50<24:22, 11.48it/s]

 61%|█████████████████████▊              | 25734/42525 [38:50<24:46, 11.30it/s]

 61%|█████████████████████▊              | 25738/42525 [38:50<24:11, 11.56it/s]

 61%|█████████████████████▊              | 25742/42525 [38:51<23:57, 11.68it/s]

 61%|█████████████████████▊              | 25746/42525 [38:51<23:57, 11.67it/s]

 61%|█████████████████████▊              | 25750/42525 [38:51<25:00, 11.18it/s]

 61%|█████████████████████▊              | 25754/42525 [38:52<24:30, 11.40it/s]

 61%|█████████████████████▊              | 25758/42525 [38:52<25:06, 11.13it/s]

 61%|█████████████████████▊              | 25762/42525 [38:52<25:31, 10.94it/s]

 61%|█████████████████████▊              | 25766/42525 [38:53<25:55, 10.77it/s]

 61%|█████████████████████▊              | 25768/42525 [38:53<26:13, 10.65it/s]

 61%|█████████████████████▊              | 25772/42525 [38:53<26:13, 10.65it/s]

 61%|█████████████████████▊              | 25776/42525 [38:54<25:56, 10.76it/s]

 61%|█████████████████████▊              | 25780/42525 [38:54<25:24, 10.98it/s]

 61%|█████████████████████▊              | 25784/42525 [38:54<24:30, 11.38it/s]

 61%|█████████████████████▊              | 25788/42525 [38:55<24:44, 11.28it/s]

 61%|█████████████████████▊              | 25792/42525 [38:55<24:21, 11.45it/s]

 61%|█████████████████████▊              | 25796/42525 [38:56<24:41, 11.29it/s]

 61%|█████████████████████▊              | 25800/42525 [38:56<24:13, 11.51it/s]

 61%|█████████████████████▊              | 25804/42525 [38:56<23:53, 11.66it/s]

 61%|█████████████████████▊              | 25808/42525 [38:57<24:47, 11.24it/s]

 61%|█████████████████████▊              | 25812/42525 [38:57<24:49, 11.22it/s]

 61%|█████████████████████▊              | 25816/42525 [38:57<24:35, 11.32it/s]

 61%|█████████████████████▊              | 25820/42525 [38:58<25:36, 10.87it/s]

 61%|█████████████████████▊              | 25824/42525 [38:58<25:15, 11.02it/s]

 61%|█████████████████████▊              | 25828/42525 [38:58<25:03, 11.10it/s]

 61%|█████████████████████▊              | 25832/42525 [38:59<24:51, 11.19it/s]

 61%|█████████████████████▊              | 25836/42525 [38:59<25:12, 11.03it/s]

 61%|█████████████████████▉              | 25840/42525 [38:59<24:27, 11.37it/s]

 61%|█████████████████████▉              | 25844/42525 [39:00<25:15, 11.01it/s]

 61%|█████████████████████▉              | 25846/42525 [39:00<25:55, 10.72it/s]

 61%|█████████████████████▉              | 25850/42525 [39:00<26:07, 10.64it/s]

 61%|█████████████████████▉              | 25854/42525 [39:01<24:38, 11.27it/s]

 61%|█████████████████████▉              | 25858/42525 [39:01<24:01, 11.56it/s]

 61%|█████████████████████▉              | 25862/42525 [39:01<23:44, 11.70it/s]

 61%|█████████████████████▉              | 25866/42525 [39:02<23:36, 11.76it/s]

 61%|█████████████████████▉              | 25870/42525 [39:02<23:33, 11.78it/s]

 61%|█████████████████████▉              | 25874/42525 [39:02<24:08, 11.50it/s]

 61%|█████████████████████▉              | 25878/42525 [39:03<24:48, 11.18it/s]

 61%|█████████████████████▉              | 25882/42525 [39:03<24:17, 11.42it/s]

 61%|█████████████████████▉              | 25886/42525 [39:04<24:56, 11.12it/s]

 61%|█████████████████████▉              | 25890/42525 [39:04<25:14, 10.98it/s]

 61%|█████████████████████▉              | 25892/42525 [39:04<24:53, 11.14it/s]

 61%|█████████████████████▉              | 25896/42525 [39:04<25:41, 10.79it/s]

 61%|█████████████████████▉              | 25900/42525 [39:05<25:27, 10.88it/s]

 61%|█████████████████████▉              | 25904/42525 [39:05<25:31, 10.85it/s]

 61%|█████████████████████▉              | 25908/42525 [39:06<25:33, 10.84it/s]

 61%|█████████████████████▉              | 25912/42525 [39:06<25:15, 10.96it/s]

 61%|█████████████████████▉              | 25916/42525 [39:06<24:56, 11.10it/s]

 61%|█████████████████████▉              | 25920/42525 [39:07<24:59, 11.07it/s]

 61%|█████████████████████▉              | 25924/42525 [39:07<24:50, 11.14it/s]

 61%|█████████████████████▉              | 25928/42525 [39:07<24:57, 11.08it/s]

 61%|█████████████████████▉              | 25932/42525 [39:08<24:20, 11.36it/s]

 61%|█████████████████████▉              | 25936/42525 [39:08<24:27, 11.31it/s]

 61%|█████████████████████▉              | 25940/42525 [39:08<24:01, 11.51it/s]

 61%|█████████████████████▉              | 25944/42525 [39:09<24:53, 11.10it/s]

 61%|█████████████████████▉              | 25948/42525 [39:09<25:34, 10.80it/s]

 61%|█████████████████████▉              | 25952/42525 [39:10<25:28, 10.84it/s]

 61%|█████████████████████▉              | 25956/42525 [39:10<24:31, 11.26it/s]

 61%|█████████████████████▉              | 25960/42525 [39:10<24:08, 11.44it/s]

 61%|█████████████████████▉              | 25964/42525 [39:11<24:28, 11.28it/s]

 61%|█████████████████████▉              | 25968/42525 [39:11<24:44, 11.15it/s]

 61%|█████████████████████▉              | 25972/42525 [39:11<24:05, 11.45it/s]

 61%|█████████████████████▉              | 25976/42525 [39:12<23:40, 11.65it/s]

 61%|█████████████████████▉              | 25980/42525 [39:12<24:57, 11.05it/s]

 61%|█████████████████████▉              | 25984/42525 [39:12<25:01, 11.02it/s]

 61%|██████████████████████              | 25988/42525 [39:13<25:35, 10.77it/s]

 61%|██████████████████████              | 25992/42525 [39:13<24:38, 11.18it/s]

 61%|██████████████████████              | 25996/42525 [39:13<24:45, 11.13it/s]

 61%|██████████████████████              | 26000/42525 [39:14<24:03, 11.45it/s]

 61%|██████████████████████              | 26004/42525 [39:14<23:52, 11.54it/s]

 61%|██████████████████████              | 26008/42525 [39:15<25:00, 11.01it/s]

 61%|██████████████████████              | 26012/42525 [39:15<24:26, 11.26it/s]

 61%|██████████████████████              | 26016/42525 [39:15<24:53, 11.05it/s]

 61%|██████████████████████              | 26020/42525 [39:16<24:29, 11.23it/s]

 61%|██████████████████████              | 26024/42525 [39:16<25:03, 10.98it/s]

 61%|██████████████████████              | 26028/42525 [39:16<25:28, 10.79it/s]

 61%|██████████████████████              | 26032/42525 [39:17<25:03, 10.97it/s]

 61%|██████████████████████              | 26036/42525 [39:17<24:40, 11.14it/s]

 61%|██████████████████████              | 26040/42525 [39:17<23:59, 11.46it/s]

 61%|██████████████████████              | 26044/42525 [39:18<23:40, 11.60it/s]

 61%|██████████████████████              | 26048/42525 [39:18<23:36, 11.63it/s]

 61%|██████████████████████              | 26052/42525 [39:18<23:47, 11.54it/s]

 61%|██████████████████████              | 26056/42525 [39:19<23:39, 11.60it/s]

 61%|██████████████████████              | 26060/42525 [39:19<24:03, 11.41it/s]

 61%|██████████████████████              | 26062/42525 [39:19<24:28, 11.21it/s]

 61%|██████████████████████              | 26066/42525 [39:20<25:54, 10.59it/s]

 61%|██████████████████████              | 26070/42525 [39:20<25:48, 10.63it/s]

 61%|██████████████████████              | 26074/42525 [39:20<25:06, 10.92it/s]

 61%|██████████████████████              | 26078/42525 [39:21<24:06, 11.37it/s]

 61%|██████████████████████              | 26082/42525 [39:21<23:41, 11.57it/s]

 61%|██████████████████████              | 26086/42525 [39:21<24:19, 11.27it/s]

 61%|██████████████████████              | 26090/42525 [39:22<25:05, 10.92it/s]

 61%|██████████████████████              | 26094/42525 [39:22<25:07, 10.90it/s]

 61%|██████████████████████              | 26098/42525 [39:23<24:47, 11.05it/s]

 61%|██████████████████████              | 26102/42525 [39:23<25:28, 10.74it/s]

 61%|██████████████████████              | 26106/42525 [39:23<24:32, 11.15it/s]

 61%|██████████████████████              | 26110/42525 [39:24<24:32, 11.15it/s]

 61%|██████████████████████              | 26114/42525 [39:24<24:10, 11.32it/s]

 61%|██████████████████████              | 26118/42525 [39:24<23:44, 11.52it/s]

 61%|██████████████████████              | 26122/42525 [39:25<23:23, 11.69it/s]

 61%|██████████████████████              | 26126/42525 [39:25<24:08, 11.32it/s]

 61%|██████████████████████              | 26130/42525 [39:25<24:36, 11.11it/s]

 61%|██████████████████████              | 26134/42525 [39:26<23:51, 11.45it/s]

 61%|██████████████████████▏             | 26138/42525 [39:26<23:29, 11.63it/s]

 61%|██████████████████████▏             | 26142/42525 [39:26<24:21, 11.21it/s]

 61%|██████████████████████▏             | 26144/42525 [39:27<23:23, 11.67it/s]

 61%|██████████████████████▏             | 26148/42525 [39:27<24:44, 11.03it/s]

 61%|██████████████████████▏             | 26152/42525 [39:27<24:24, 11.18it/s]

 62%|██████████████████████▏             | 26156/42525 [39:28<25:20, 10.77it/s]

 62%|██████████████████████▏             | 26160/42525 [39:28<25:08, 10.85it/s]

 62%|██████████████████████▏             | 26164/42525 [39:28<23:50, 11.44it/s]

 62%|██████████████████████▏             | 26168/42525 [39:29<24:41, 11.04it/s]

 62%|██████████████████████▏             | 26172/42525 [39:29<24:05, 11.31it/s]

 62%|██████████████████████▏             | 26176/42525 [39:30<23:22, 11.66it/s]

 62%|██████████████████████▏             | 26178/42525 [39:30<24:15, 11.23it/s]

 62%|██████████████████████▏             | 26182/42525 [39:30<25:30, 10.68it/s]

 62%|██████████████████████▏             | 26186/42525 [39:30<24:14, 11.23it/s]

 62%|██████████████████████▏             | 26190/42525 [39:31<23:45, 11.46it/s]

 62%|██████████████████████▏             | 26194/42525 [39:31<24:13, 11.23it/s]

 62%|██████████████████████▏             | 26198/42525 [39:32<24:18, 11.19it/s]

 62%|██████████████████████▏             | 26202/42525 [39:32<24:41, 11.02it/s]

 62%|██████████████████████▏             | 26206/42525 [39:32<23:55, 11.37it/s]

 62%|██████████████████████▏             | 26210/42525 [39:33<23:43, 11.46it/s]

 62%|██████████████████████▏             | 26214/42525 [39:33<24:26, 11.12it/s]

 62%|██████████████████████▏             | 26218/42525 [39:33<25:12, 10.78it/s]

 62%|██████████████████████▏             | 26220/42525 [39:34<25:21, 10.72it/s]

 62%|██████████████████████▏             | 26224/42525 [39:34<25:15, 10.75it/s]

 62%|██████████████████████▏             | 26228/42525 [39:34<24:34, 11.05it/s]

 62%|██████████████████████▏             | 26232/42525 [39:35<23:47, 11.41it/s]

 62%|██████████████████████▏             | 26236/42525 [39:35<24:00, 11.31it/s]

 62%|██████████████████████▏             | 26240/42525 [39:35<24:46, 10.96it/s]

 62%|██████████████████████▏             | 26244/42525 [39:36<23:57, 11.33it/s]

 62%|██████████████████████▏             | 26248/42525 [39:36<23:27, 11.57it/s]

 62%|██████████████████████▏             | 26252/42525 [39:36<24:07, 11.24it/s]

 62%|██████████████████████▏             | 26256/42525 [39:37<24:37, 11.01it/s]

 62%|██████████████████████▏             | 26260/42525 [39:37<23:46, 11.40it/s]

 62%|██████████████████████▏             | 26264/42525 [39:37<24:01, 11.28it/s]

 62%|██████████████████████▏             | 26268/42525 [39:38<23:39, 11.46it/s]

 62%|██████████████████████▏             | 26272/42525 [39:38<23:33, 11.50it/s]

 62%|██████████████████████▏             | 26276/42525 [39:38<24:14, 11.17it/s]

 62%|██████████████████████▏             | 26280/42525 [39:39<24:15, 11.16it/s]

 62%|██████████████████████▎             | 26284/42525 [39:39<24:15, 11.16it/s]

 62%|██████████████████████▎             | 26288/42525 [39:40<23:36, 11.46it/s]

 62%|██████████████████████▎             | 26292/42525 [39:40<23:15, 11.63it/s]

 62%|██████████████████████▎             | 26296/42525 [39:40<23:26, 11.54it/s]

 62%|██████████████████████▎             | 26300/42525 [39:41<24:04, 11.24it/s]

 62%|██████████████████████▎             | 26304/42525 [39:41<24:29, 11.04it/s]

 62%|██████████████████████▎             | 26308/42525 [39:41<24:27, 11.05it/s]

 62%|██████████████████████▎             | 26312/42525 [39:42<25:01, 10.80it/s]

 62%|██████████████████████▎             | 26316/42525 [39:42<23:57, 11.27it/s]

 62%|██████████████████████▎             | 26320/42525 [39:42<23:35, 11.45it/s]

 62%|██████████████████████▎             | 26324/42525 [39:43<23:28, 11.50it/s]

 62%|██████████████████████▎             | 26328/42525 [39:43<24:27, 11.04it/s]

 62%|██████████████████████▎             | 26332/42525 [39:43<24:33, 10.99it/s]

 62%|██████████████████████▎             | 26336/42525 [39:44<25:02, 10.78it/s]

 62%|██████████████████████▎             | 26340/42525 [39:44<24:43, 10.91it/s]

 62%|██████████████████████▎             | 26344/42525 [39:45<24:15, 11.12it/s]

 62%|██████████████████████▎             | 26348/42525 [39:45<23:36, 11.42it/s]

 62%|██████████████████████▎             | 26352/42525 [39:45<24:10, 11.15it/s]

 62%|██████████████████████▎             | 26356/42525 [39:46<23:47, 11.33it/s]

 62%|██████████████████████▎             | 26360/42525 [39:46<23:16, 11.58it/s]

 62%|██████████████████████▎             | 26364/42525 [39:46<23:05, 11.67it/s]

 62%|██████████████████████▎             | 26368/42525 [39:47<23:01, 11.70it/s]

 62%|██████████████████████▎             | 26372/42525 [39:47<23:54, 11.26it/s]

 62%|██████████████████████▎             | 26376/42525 [39:47<23:30, 11.45it/s]

 62%|██████████████████████▎             | 26380/42525 [39:48<24:05, 11.17it/s]

 62%|██████████████████████▎             | 26384/42525 [39:48<24:28, 10.99it/s]

 62%|██████████████████████▎             | 26388/42525 [39:48<24:19, 11.06it/s]

 62%|██████████████████████▎             | 26392/42525 [39:49<24:35, 10.94it/s]

 62%|██████████████████████▎             | 26396/42525 [39:49<23:44, 11.32it/s]

 62%|██████████████████████▎             | 26400/42525 [39:50<24:21, 11.04it/s]

 62%|██████████████████████▎             | 26404/42525 [39:50<25:47, 10.42it/s]

 62%|██████████████████████▎             | 26408/42525 [39:50<25:18, 10.61it/s]

 62%|██████████████████████▎             | 26412/42525 [39:51<24:52, 10.80it/s]

 62%|██████████████████████▎             | 26414/42525 [39:51<24:18, 11.04it/s]

 62%|██████████████████████▎             | 26418/42525 [39:51<24:35, 10.92it/s]

 62%|██████████████████████▎             | 26422/42525 [39:52<24:11, 11.09it/s]

 62%|██████████████████████▎             | 26424/42525 [39:52<24:27, 10.97it/s]

 62%|██████████████████████▎             | 26428/42525 [39:52<25:22, 10.57it/s]

 62%|██████████████████████▍             | 26432/42525 [39:53<24:07, 11.12it/s]

 62%|██████████████████████▍             | 26436/42525 [39:53<23:33, 11.39it/s]

 62%|██████████████████████▍             | 26440/42525 [39:53<23:46, 11.27it/s]

 62%|██████████████████████▍             | 26444/42525 [39:54<24:26, 10.97it/s]

 62%|██████████████████████▍             | 26448/42525 [39:54<24:36, 10.89it/s]

 62%|██████████████████████▍             | 26452/42525 [39:54<24:09, 11.09it/s]

 62%|██████████████████████▍             | 26454/42525 [39:54<24:11, 11.07it/s]

 62%|██████████████████████▍             | 26458/42525 [39:55<24:49, 10.78it/s]

 62%|██████████████████████▍             | 26462/42525 [39:55<23:48, 11.25it/s]

 62%|██████████████████████▍             | 26466/42525 [39:56<23:59, 11.16it/s]

 62%|██████████████████████▍             | 26470/42525 [39:56<24:29, 10.92it/s]

 62%|██████████████████████▍             | 26474/42525 [39:56<24:16, 11.02it/s]

 62%|██████████████████████▍             | 26478/42525 [39:57<24:46, 10.80it/s]

 62%|██████████████████████▍             | 26482/42525 [39:57<24:44, 10.81it/s]

 62%|██████████████████████▍             | 26486/42525 [39:57<24:14, 11.02it/s]

 62%|██████████████████████▍             | 26490/42525 [39:58<23:57, 11.16it/s]

 62%|██████████████████████▍             | 26494/42525 [39:58<23:59, 11.14it/s]

 62%|██████████████████████▍             | 26498/42525 [39:58<23:20, 11.44it/s]

 62%|██████████████████████▍             | 26502/42525 [39:59<23:23, 11.42it/s]

 62%|██████████████████████▍             | 26506/42525 [39:59<22:59, 11.61it/s]

 62%|██████████████████████▍             | 26510/42525 [40:00<23:19, 11.44it/s]

 62%|██████████████████████▍             | 26514/42525 [40:00<23:39, 11.28it/s]

 62%|██████████████████████▍             | 26518/42525 [40:00<24:43, 10.79it/s]

 62%|██████████████████████▍             | 26522/42525 [40:01<25:20, 10.53it/s]

 62%|██████████████████████▍             | 26526/42525 [40:01<25:00, 10.66it/s]

 62%|██████████████████████▍             | 26530/42525 [40:01<24:34, 10.85it/s]

 62%|██████████████████████▍             | 26534/42525 [40:02<24:14, 11.00it/s]

 62%|██████████████████████▍             | 26538/42525 [40:02<23:23, 11.39it/s]

 62%|██████████████████████▍             | 26542/42525 [40:02<23:08, 11.51it/s]

 62%|██████████████████████▍             | 26546/42525 [40:03<22:54, 11.63it/s]

 62%|██████████████████████▍             | 26550/42525 [40:03<23:07, 11.52it/s]

 62%|██████████████████████▍             | 26554/42525 [40:04<23:49, 11.17it/s]

 62%|██████████████████████▍             | 26558/42525 [40:04<24:17, 10.95it/s]

 62%|██████████████████████▍             | 26562/42525 [40:04<23:54, 11.13it/s]

 62%|██████████████████████▍             | 26566/42525 [40:05<23:13, 11.45it/s]

 62%|██████████████████████▍             | 26570/42525 [40:05<23:32, 11.30it/s]

 62%|██████████████████████▍             | 26574/42525 [40:05<23:36, 11.26it/s]

 62%|██████████████████████▍             | 26578/42525 [40:06<23:07, 11.49it/s]

 63%|██████████████████████▌             | 26582/42525 [40:06<22:55, 11.59it/s]

 63%|██████████████████████▌             | 26586/42525 [40:06<23:55, 11.10it/s]

 63%|██████████████████████▌             | 26590/42525 [40:07<23:40, 11.22it/s]

 63%|██████████████████████▌             | 26594/42525 [40:07<23:31, 11.29it/s]

 63%|██████████████████████▌             | 26598/42525 [40:07<23:15, 11.42it/s]

 63%|██████████████████████▌             | 26602/42525 [40:08<23:20, 11.37it/s]

 63%|██████████████████████▌             | 26606/42525 [40:08<22:59, 11.54it/s]

 63%|██████████████████████▌             | 26610/42525 [40:08<22:58, 11.55it/s]

 63%|██████████████████████▌             | 26614/42525 [40:09<23:22, 11.34it/s]

 63%|██████████████████████▌             | 26618/42525 [40:09<23:57, 11.06it/s]

 63%|██████████████████████▌             | 26622/42525 [40:09<23:14, 11.40it/s]

 63%|██████████████████████▌             | 26626/42525 [40:10<23:50, 11.11it/s]

 63%|██████████████████████▌             | 26630/42525 [40:10<23:06, 11.46it/s]

 63%|██████████████████████▌             | 26634/42525 [40:11<23:08, 11.44it/s]

 63%|██████████████████████▌             | 26638/42525 [40:11<24:26, 10.83it/s]

 63%|██████████████████████▌             | 26642/42525 [40:11<23:26, 11.29it/s]

 63%|██████████████████████▌             | 26646/42525 [40:12<23:23, 11.31it/s]

 63%|██████████████████████▌             | 26650/42525 [40:12<22:50, 11.58it/s]

 63%|██████████████████████▌             | 26654/42525 [40:12<23:25, 11.29it/s]

 63%|██████████████████████▌             | 26658/42525 [40:13<23:14, 11.38it/s]

 63%|██████████████████████▌             | 26662/42525 [40:13<22:49, 11.59it/s]

 63%|██████████████████████▌             | 26666/42525 [40:13<23:03, 11.47it/s]

 63%|██████████████████████▌             | 26670/42525 [40:14<22:45, 11.61it/s]

 63%|██████████████████████▌             | 26674/42525 [40:14<22:34, 11.70it/s]

 63%|██████████████████████▌             | 26678/42525 [40:14<22:33, 11.71it/s]

 63%|██████████████████████▌             | 26682/42525 [40:15<23:26, 11.27it/s]

 63%|██████████████████████▌             | 26686/42525 [40:15<24:06, 10.95it/s]

 63%|██████████████████████▌             | 26690/42525 [40:15<23:44, 11.11it/s]

 63%|██████████████████████▌             | 26694/42525 [40:16<22:54, 11.52it/s]

 63%|██████████████████████▌             | 26698/42525 [40:16<23:03, 11.44it/s]

 63%|██████████████████████▌             | 26702/42525 [40:17<23:51, 11.05it/s]

 63%|██████████████████████▌             | 26706/42525 [40:17<23:36, 11.17it/s]

 63%|██████████████████████▌             | 26710/42525 [40:17<22:56, 11.49it/s]

 63%|██████████████████████▌             | 26714/42525 [40:18<23:03, 11.43it/s]

 63%|██████████████████████▌             | 26718/42525 [40:18<23:18, 11.30it/s]

 63%|██████████████████████▌             | 26720/42525 [40:18<23:02, 11.43it/s]

 63%|██████████████████████▌             | 26724/42525 [40:19<23:31, 11.19it/s]

 63%|██████████████████████▋             | 26728/42525 [40:19<23:48, 11.06it/s]

 63%|██████████████████████▋             | 26732/42525 [40:19<23:18, 11.30it/s]

 63%|██████████████████████▋             | 26734/42525 [40:19<24:51, 10.59it/s]

 63%|██████████████████████▋             | 26738/42525 [40:20<25:27, 10.33it/s]

 63%|██████████████████████▋             | 26742/42525 [40:20<24:23, 10.78it/s]

 63%|██████████████████████▋             | 26746/42525 [40:21<23:22, 11.25it/s]

 63%|██████████████████████▋             | 26748/42525 [40:21<24:05, 10.91it/s]

 63%|██████████████████████▋             | 26752/42525 [40:21<25:10, 10.44it/s]

 63%|██████████████████████▋             | 26756/42525 [40:21<24:33, 10.70it/s]

 63%|██████████████████████▋             | 26758/42525 [40:22<23:53, 11.00it/s]

 63%|██████████████████████▋             | 26762/42525 [40:22<23:55, 10.98it/s]

 63%|██████████████████████▋             | 26766/42525 [40:22<24:13, 10.84it/s]

 63%|██████████████████████▋             | 26770/42525 [40:23<23:11, 11.32it/s]

 63%|██████████████████████▋             | 26774/42525 [40:23<23:04, 11.38it/s]

 63%|██████████████████████▋             | 26778/42525 [40:23<22:37, 11.60it/s]

 63%|██████████████████████▋             | 26782/42525 [40:24<22:22, 11.72it/s]

 63%|██████████████████████▋             | 26786/42525 [40:24<22:10, 11.83it/s]

 63%|██████████████████████▋             | 26790/42525 [40:24<23:22, 11.22it/s]

 63%|██████████████████████▋             | 26794/42525 [40:25<23:16, 11.27it/s]

 63%|██████████████████████▋             | 26798/42525 [40:25<24:00, 10.92it/s]

 63%|██████████████████████▋             | 26802/42525 [40:26<23:59, 10.92it/s]

 63%|██████████████████████▋             | 26806/42525 [40:26<23:40, 11.06it/s]

 63%|██████████████████████▋             | 26810/42525 [40:26<24:10, 10.83it/s]

 63%|██████████████████████▋             | 26814/42525 [40:27<23:16, 11.25it/s]

 63%|██████████████████████▋             | 26818/42525 [40:27<22:51, 11.46it/s]

 63%|██████████████████████▋             | 26822/42525 [40:27<22:33, 11.60it/s]

 63%|██████████████████████▋             | 26826/42525 [40:28<23:50, 10.98it/s]

 63%|██████████████████████▋             | 26830/42525 [40:28<25:12, 10.37it/s]

 63%|██████████████████████▋             | 26834/42525 [40:28<23:46, 11.00it/s]

 63%|██████████████████████▋             | 26838/42525 [40:29<23:56, 10.92it/s]

 63%|██████████████████████▋             | 26842/42525 [40:29<23:54, 10.93it/s]

 63%|██████████████████████▋             | 26846/42525 [40:30<24:03, 10.86it/s]

 63%|██████████████████████▋             | 26850/42525 [40:30<23:54, 10.93it/s]

 63%|██████████████████████▋             | 26854/42525 [40:30<23:09, 11.28it/s]

 63%|██████████████████████▋             | 26858/42525 [40:31<23:43, 11.01it/s]

 63%|██████████████████████▋             | 26862/42525 [40:31<23:57, 10.90it/s]

 63%|██████████████████████▋             | 26866/42525 [40:31<23:15, 11.22it/s]

 63%|██████████████████████▋             | 26870/42525 [40:32<23:16, 11.21it/s]

 63%|██████████████████████▊             | 26874/42525 [40:32<22:45, 11.46it/s]

 63%|██████████████████████▊             | 26878/42525 [40:32<22:33, 11.56it/s]

 63%|██████████████████████▊             | 26882/42525 [40:33<22:51, 11.41it/s]

 63%|██████████████████████▊             | 26886/42525 [40:33<22:51, 11.40it/s]

 63%|██████████████████████▊             | 26890/42525 [40:33<22:49, 11.41it/s]

 63%|██████████████████████▊             | 26894/42525 [40:34<23:54, 10.90it/s]

 63%|██████████████████████▊             | 26898/42525 [40:34<24:35, 10.59it/s]

 63%|██████████████████████▊             | 26902/42525 [40:35<23:25, 11.12it/s]

 63%|██████████████████████▊             | 26906/42525 [40:35<22:41, 11.47it/s]

 63%|██████████████████████▊             | 26910/42525 [40:35<22:30, 11.56it/s]

 63%|██████████████████████▊             | 26914/42525 [40:36<22:20, 11.64it/s]

 63%|██████████████████████▊             | 26918/42525 [40:36<23:14, 11.20it/s]

 63%|██████████████████████▊             | 26922/42525 [40:36<23:33, 11.04it/s]

 63%|██████████████████████▊             | 26926/42525 [40:37<23:35, 11.02it/s]

 63%|██████████████████████▊             | 26930/42525 [40:37<24:06, 10.78it/s]

 63%|██████████████████████▊             | 26934/42525 [40:37<23:23, 11.11it/s]

 63%|██████████████████████▊             | 26938/42525 [40:38<23:17, 11.15it/s]

 63%|██████████████████████▊             | 26942/42525 [40:38<22:31, 11.53it/s]

 63%|██████████████████████▊             | 26946/42525 [40:38<22:16, 11.66it/s]

 63%|██████████████████████▊             | 26950/42525 [40:39<22:34, 11.50it/s]

 63%|██████████████████████▊             | 26954/42525 [40:39<22:25, 11.57it/s]

 63%|██████████████████████▊             | 26958/42525 [40:40<23:46, 10.91it/s]

 63%|██████████████████████▊             | 26962/42525 [40:40<23:40, 10.95it/s]

 63%|██████████████████████▊             | 26966/42525 [40:40<23:16, 11.14it/s]

 63%|██████████████████████▊             | 26970/42525 [40:41<23:08, 11.20it/s]

 63%|██████████████████████▊             | 26972/42525 [40:41<22:53, 11.32it/s]

 63%|██████████████████████▊             | 26976/42525 [40:41<23:36, 10.98it/s]

 63%|██████████████████████▊             | 26980/42525 [40:42<24:00, 10.79it/s]

 63%|██████████████████████▊             | 26982/42525 [40:42<23:33, 11.00it/s]

 63%|██████████████████████▊             | 26986/42525 [40:42<23:47, 10.88it/s]

 63%|██████████████████████▊             | 26990/42525 [40:43<24:21, 10.63it/s]

 63%|██████████████████████▊             | 26992/42525 [40:43<23:43, 10.91it/s]

 63%|██████████████████████▊             | 26996/42525 [40:43<24:32, 10.54it/s]

 63%|██████████████████████▊             | 27000/42525 [40:43<24:48, 10.43it/s]

 64%|██████████████████████▊             | 27004/42525 [40:44<24:08, 10.72it/s]

 64%|██████████████████████▊             | 27006/42525 [40:44<23:35, 10.97it/s]

 64%|██████████████████████▊             | 27010/42525 [40:44<24:18, 10.64it/s]

 64%|██████████████████████▊             | 27014/42525 [40:45<24:13, 10.67it/s]

 64%|██████████████████████▊             | 27018/42525 [40:45<23:03, 11.21it/s]

 64%|██████████████████████▉             | 27022/42525 [40:45<22:55, 11.27it/s]

 64%|██████████████████████▉             | 27026/42525 [40:46<23:43, 10.89it/s]

 64%|██████████████████████▉             | 27030/42525 [40:46<22:45, 11.35it/s]

 64%|██████████████████████▉             | 27034/42525 [40:47<23:55, 10.79it/s]

 64%|██████████████████████▉             | 27038/42525 [40:47<23:57, 10.77it/s]

 64%|██████████████████████▉             | 27040/42525 [40:47<23:20, 11.05it/s]

 64%|██████████████████████▉             | 27044/42525 [40:48<23:44, 10.87it/s]

 64%|██████████████████████▉             | 27048/42525 [40:48<23:28, 10.99it/s]

 64%|██████████████████████▉             | 27052/42525 [40:48<22:58, 11.23it/s]

 64%|██████████████████████▉             | 27056/42525 [40:49<23:09, 11.13it/s]

 64%|██████████████████████▉             | 27060/42525 [40:49<23:41, 10.88it/s]

 64%|██████████████████████▉             | 27064/42525 [40:49<24:03, 10.71it/s]

 64%|██████████████████████▉             | 27068/42525 [40:50<22:52, 11.26it/s]

 64%|██████████████████████▉             | 27072/42525 [40:50<22:29, 11.45it/s]

 64%|██████████████████████▉             | 27076/42525 [40:50<21:58, 11.72it/s]

 64%|██████████████████████▉             | 27080/42525 [40:51<22:24, 11.49it/s]

 64%|██████████████████████▉             | 27084/42525 [40:51<23:29, 10.95it/s]

 64%|██████████████████████▉             | 27088/42525 [40:51<23:37, 10.89it/s]

 64%|██████████████████████▉             | 27092/42525 [40:52<23:17, 11.04it/s]

 64%|██████████████████████▉             | 27096/42525 [40:52<22:38, 11.36it/s]

 64%|██████████████████████▉             | 27100/42525 [40:53<22:27, 11.45it/s]

 64%|██████████████████████▉             | 27104/42525 [40:53<22:27, 11.44it/s]

 64%|██████████████████████▉             | 27108/42525 [40:53<22:28, 11.43it/s]

 64%|██████████████████████▉             | 27112/42525 [40:54<23:11, 11.07it/s]

 64%|██████████████████████▉             | 27116/42525 [40:54<22:31, 11.40it/s]

 64%|██████████████████████▉             | 27120/42525 [40:54<23:03, 11.14it/s]

 64%|██████████████████████▉             | 27124/42525 [40:55<22:42, 11.30it/s]

 64%|██████████████████████▉             | 27128/42525 [40:55<22:28, 11.42it/s]

 64%|██████████████████████▉             | 27132/42525 [40:55<23:21, 10.98it/s]

 64%|██████████████████████▉             | 27136/42525 [40:56<23:56, 10.71it/s]

 64%|██████████████████████▉             | 27140/42525 [40:56<23:24, 10.95it/s]

 64%|██████████████████████▉             | 27144/42525 [40:56<23:47, 10.78it/s]

 64%|██████████████████████▉             | 27148/42525 [40:57<22:46, 11.25it/s]

 64%|██████████████████████▉             | 27152/42525 [40:57<22:57, 11.16it/s]

 64%|██████████████████████▉             | 27156/42525 [40:58<22:21, 11.46it/s]

 64%|██████████████████████▉             | 27160/42525 [40:58<21:57, 11.66it/s]

 64%|██████████████████████▉             | 27164/42525 [40:58<22:38, 11.31it/s]

 64%|██████████████████████▉             | 27168/42525 [40:59<23:00, 11.12it/s]

 64%|███████████████████████             | 27172/42525 [40:59<23:09, 11.05it/s]

 64%|███████████████████████             | 27176/42525 [40:59<23:28, 10.90it/s]

 64%|███████████████████████             | 27178/42525 [40:59<22:56, 11.15it/s]

 64%|███████████████████████             | 27182/42525 [41:00<23:49, 10.74it/s]

 64%|███████████████████████             | 27186/42525 [41:00<22:44, 11.24it/s]

 64%|███████████████████████             | 27190/42525 [41:01<23:20, 10.95it/s]

 64%|███████████████████████             | 27194/42525 [41:01<22:54, 11.15it/s]

 64%|███████████████████████             | 27198/42525 [41:01<22:12, 11.51it/s]

 64%|███████████████████████             | 27202/42525 [41:02<21:54, 11.65it/s]

 64%|███████████████████████             | 27206/42525 [41:02<23:13, 10.99it/s]

 64%|███████████████████████             | 27210/42525 [41:02<22:34, 11.30it/s]

 64%|███████████████████████             | 27214/42525 [41:03<22:09, 11.52it/s]

 64%|███████████████████████             | 27216/42525 [41:03<22:55, 11.13it/s]

 64%|███████████████████████             | 27220/42525 [41:03<23:13, 10.98it/s]

 64%|███████████████████████             | 27224/42525 [41:04<22:57, 11.11it/s]

 64%|███████████████████████             | 27228/42525 [41:04<23:27, 10.87it/s]

 64%|███████████████████████             | 27232/42525 [41:04<23:04, 11.04it/s]

 64%|███████████████████████             | 27236/42525 [41:05<22:08, 11.51it/s]

 64%|███████████████████████             | 27240/42525 [41:05<21:50, 11.66it/s]

 64%|███████████████████████             | 27244/42525 [41:05<22:07, 11.51it/s]

 64%|███████████████████████             | 27248/42525 [41:06<23:18, 10.92it/s]

 64%|███████████████████████             | 27252/42525 [41:06<22:42, 11.21it/s]

 64%|███████████████████████             | 27256/42525 [41:06<22:11, 11.47it/s]

 64%|███████████████████████             | 27260/42525 [41:07<22:14, 11.44it/s]

 64%|███████████████████████             | 27264/42525 [41:07<21:29, 11.84it/s]

 64%|███████████████████████             | 27268/42525 [41:07<20:42, 12.28it/s]

 64%|███████████████████████             | 27272/42525 [41:08<21:54, 11.61it/s]

 64%|███████████████████████             | 27276/42525 [41:08<21:01, 12.09it/s]

 64%|███████████████████████             | 27280/42525 [41:08<20:38, 12.31it/s]

 64%|███████████████████████             | 27284/42525 [41:09<19:47, 12.83it/s]

 64%|███████████████████████             | 27288/42525 [41:09<20:00, 12.69it/s]

 64%|███████████████████████             | 27292/42525 [41:09<22:22, 11.34it/s]

 64%|███████████████████████             | 27294/42525 [41:10<22:32, 11.26it/s]

 64%|███████████████████████             | 27298/42525 [41:10<22:21, 11.35it/s]

 64%|███████████████████████             | 27302/42525 [41:10<22:31, 11.26it/s]

 64%|███████████████████████             | 27306/42525 [41:11<21:11, 11.97it/s]

 64%|███████████████████████             | 27310/42525 [41:11<21:39, 11.71it/s]

 64%|███████████████████████             | 27314/42525 [41:11<20:38, 12.29it/s]

 64%|███████████████████████▏            | 27318/42525 [41:12<21:04, 12.03it/s]

 64%|███████████████████████▏            | 27322/42525 [41:12<19:41, 12.87it/s]

 64%|███████████████████████▏            | 27326/42525 [41:12<19:35, 12.93it/s]

 64%|███████████████████████▏            | 27330/42525 [41:13<20:24, 12.41it/s]

 64%|███████████████████████▏            | 27334/42525 [41:13<20:59, 12.06it/s]

 64%|███████████████████████▏            | 27338/42525 [41:13<20:29, 12.35it/s]

 64%|███████████████████████▏            | 27342/42525 [41:14<21:00, 12.05it/s]

 64%|███████████████████████▏            | 27346/42525 [41:14<21:18, 11.87it/s]

 64%|███████████████████████▏            | 27350/42525 [41:14<20:38, 12.25it/s]

 64%|███████████████████████▏            | 27352/42525 [41:14<20:21, 12.42it/s]

 64%|███████████████████████▏            | 27356/42525 [41:15<21:20, 11.85it/s]

 64%|███████████████████████▏            | 27360/42525 [41:15<22:13, 11.37it/s]

 64%|███████████████████████▏            | 27364/42525 [41:15<20:28, 12.34it/s]

 64%|███████████████████████▏            | 27368/42525 [41:16<21:15, 11.89it/s]

 64%|███████████████████████▏            | 27372/42525 [41:16<21:15, 11.88it/s]

 64%|███████████████████████▏            | 27376/42525 [41:17<22:21, 11.29it/s]

 64%|███████████████████████▏            | 27380/42525 [41:17<21:38, 11.67it/s]

 64%|███████████████████████▏            | 27384/42525 [41:17<21:11, 11.91it/s]

 64%|███████████████████████▏            | 27388/42525 [41:18<20:55, 12.06it/s]

 64%|███████████████████████▏            | 27392/42525 [41:18<22:03, 11.43it/s]

 64%|███████████████████████▏            | 27396/42525 [41:18<21:11, 11.90it/s]

 64%|███████████████████████▏            | 27400/42525 [41:19<20:58, 12.02it/s]

 64%|███████████████████████▏            | 27404/42525 [41:19<19:44, 12.76it/s]

 64%|███████████████████████▏            | 27408/42525 [41:19<20:40, 12.19it/s]

 64%|███████████████████████▏            | 27412/42525 [41:20<21:37, 11.65it/s]

 64%|███████████████████████▏            | 27416/42525 [41:20<21:15, 11.85it/s]

 64%|███████████████████████▏            | 27420/42525 [41:20<21:39, 11.63it/s]

 64%|███████████████████████▏            | 27424/42525 [41:21<21:34, 11.66it/s]

 64%|███████████████████████▏            | 27428/42525 [41:21<22:04, 11.39it/s]

 65%|███████████████████████▏            | 27430/42525 [41:21<22:05, 11.39it/s]

 65%|███████████████████████▏            | 27434/42525 [41:22<23:45, 10.58it/s]

 65%|███████████████████████▏            | 27438/42525 [41:22<23:18, 10.79it/s]

 65%|███████████████████████▏            | 27442/42525 [41:22<22:35, 11.13it/s]

 65%|███████████████████████▏            | 27446/42525 [41:23<22:40, 11.09it/s]

 65%|███████████████████████▏            | 27450/42525 [41:23<22:01, 11.41it/s]

 65%|███████████████████████▏            | 27454/42525 [41:23<22:37, 11.10it/s]

 65%|███████████████████████▏            | 27458/42525 [41:24<22:53, 10.97it/s]

 65%|███████████████████████▏            | 27462/42525 [41:24<22:33, 11.13it/s]

 65%|███████████████████████▎            | 27466/42525 [41:24<21:54, 11.46it/s]

 65%|███████████████████████▎            | 27470/42525 [41:25<21:56, 11.44it/s]

 65%|███████████████████████▎            | 27474/42525 [41:25<22:33, 11.12it/s]

 65%|███████████████████████▎            | 27478/42525 [41:25<22:05, 11.35it/s]

 65%|███████████████████████▎            | 27482/42525 [41:26<22:41, 11.05it/s]

 65%|███████████████████████▎            | 27486/42525 [41:26<21:44, 11.53it/s]

 65%|███████████████████████▎            | 27490/42525 [41:26<21:48, 11.49it/s]

 65%|███████████████████████▎            | 27494/42525 [41:27<21:39, 11.57it/s]

 65%|███████████████████████▎            | 27498/42525 [41:27<21:52, 11.45it/s]

 65%|███████████████████████▎            | 27502/42525 [41:28<22:08, 11.31it/s]

 65%|███████████████████████▎            | 27506/42525 [41:28<22:18, 11.22it/s]

 65%|███████████████████████▎            | 27510/42525 [41:28<22:06, 11.32it/s]

 65%|███████████████████████▎            | 27514/42525 [41:29<21:56, 11.40it/s]

 65%|███████████████████████▎            | 27518/42525 [41:29<22:19, 11.20it/s]

 65%|███████████████████████▎            | 27522/42525 [41:29<21:53, 11.43it/s]

 65%|███████████████████████▎            | 27526/42525 [41:30<21:39, 11.54it/s]

 65%|███████████████████████▎            | 27530/42525 [41:30<21:28, 11.64it/s]

 65%|███████████████████████▎            | 27534/42525 [41:30<21:25, 11.66it/s]

 65%|███████████████████████▎            | 27538/42525 [41:31<22:22, 11.16it/s]

 65%|███████████████████████▎            | 27542/42525 [41:31<22:23, 11.15it/s]

 65%|███████████████████████▎            | 27546/42525 [41:31<22:13, 11.24it/s]

 65%|███████████████████████▎            | 27550/42525 [41:32<21:35, 11.56it/s]

 65%|███████████████████████▎            | 27554/42525 [41:32<21:00, 11.88it/s]

 65%|███████████████████████▎            | 27558/42525 [41:32<20:09, 12.38it/s]

 65%|███████████████████████▎            | 27562/42525 [41:33<19:52, 12.54it/s]

 65%|███████████████████████▎            | 27566/42525 [41:33<21:17, 11.71it/s]

 65%|███████████████████████▎            | 27570/42525 [41:33<20:47, 11.99it/s]

 65%|███████████████████████▎            | 27574/42525 [41:34<21:12, 11.75it/s]

 65%|███████████████████████▎            | 27578/42525 [41:34<22:29, 11.08it/s]

 65%|███████████████████████▎            | 27582/42525 [41:34<20:58, 11.87it/s]

 65%|███████████████████████▎            | 27586/42525 [41:35<20:01, 12.44it/s]

 65%|███████████████████████▎            | 27590/42525 [41:35<19:29, 12.77it/s]

 65%|███████████████████████▎            | 27594/42525 [41:35<19:44, 12.60it/s]

 65%|███████████████████████▎            | 27598/42525 [41:36<19:41, 12.63it/s]

 65%|███████████████████████▎            | 27602/42525 [41:36<20:28, 12.15it/s]

 65%|███████████████████████▎            | 27606/42525 [41:36<19:53, 12.50it/s]

 65%|███████████████████████▎            | 27610/42525 [41:37<19:12, 12.94it/s]

 65%|███████████████████████▍            | 27614/42525 [41:37<19:28, 12.76it/s]

 65%|███████████████████████▍            | 27618/42525 [41:37<21:41, 11.46it/s]

 65%|███████████████████████▍            | 27622/42525 [41:38<19:49, 12.53it/s]

 65%|███████████████████████▍            | 27626/42525 [41:38<18:35, 13.36it/s]

 65%|███████████████████████▍            | 27630/42525 [41:38<20:12, 12.29it/s]

 65%|███████████████████████▍            | 27634/42525 [41:39<20:45, 11.95it/s]

 65%|███████████████████████▍            | 27638/42525 [41:39<19:52, 12.48it/s]

 65%|███████████████████████▍            | 27642/42525 [41:39<21:28, 11.55it/s]

 65%|███████████████████████▍            | 27646/42525 [41:40<19:29, 12.72it/s]

 65%|███████████████████████▍            | 27650/42525 [41:40<19:18, 12.83it/s]

 65%|███████████████████████▍            | 27654/42525 [41:40<19:46, 12.53it/s]

 65%|███████████████████████▍            | 27658/42525 [41:41<19:49, 12.50it/s]

 65%|███████████████████████▍            | 27662/42525 [41:41<19:18, 12.83it/s]

 65%|███████████████████████▍            | 27666/42525 [41:41<19:27, 12.73it/s]

 65%|███████████████████████▍            | 27670/42525 [41:41<19:38, 12.61it/s]

 65%|███████████████████████▍            | 27674/42525 [41:42<20:40, 11.97it/s]

 65%|███████████████████████▍            | 27678/42525 [41:42<19:57, 12.39it/s]

 65%|███████████████████████▍            | 27682/42525 [41:42<20:09, 12.27it/s]

 65%|███████████████████████▍            | 27686/42525 [41:43<20:06, 12.30it/s]

 65%|███████████████████████▍            | 27690/42525 [41:43<20:59, 11.78it/s]

 65%|███████████████████████▍            | 27694/42525 [41:43<21:48, 11.34it/s]

 65%|███████████████████████▍            | 27698/42525 [41:44<20:59, 11.77it/s]

 65%|███████████████████████▍            | 27702/42525 [41:44<20:26, 12.09it/s]

 65%|███████████████████████▍            | 27706/42525 [41:44<19:27, 12.70it/s]

 65%|███████████████████████▍            | 27710/42525 [41:45<21:51, 11.30it/s]

 65%|███████████████████████▍            | 27714/42525 [41:45<20:05, 12.29it/s]

 65%|███████████████████████▍            | 27718/42525 [41:45<21:36, 11.42it/s]

 65%|███████████████████████▍            | 27722/42525 [41:46<21:59, 11.22it/s]

 65%|███████████████████████▍            | 27726/42525 [41:46<19:38, 12.56it/s]

 65%|███████████████████████▍            | 27730/42525 [41:46<19:28, 12.66it/s]

 65%|███████████████████████▍            | 27734/42525 [41:47<19:42, 12.51it/s]

 65%|███████████████████████▍            | 27738/42525 [41:47<18:42, 13.18it/s]

 65%|███████████████████████▍            | 27742/42525 [41:47<19:55, 12.36it/s]

 65%|███████████████████████▍            | 27746/42525 [41:48<19:24, 12.69it/s]

 65%|███████████████████████▍            | 27750/42525 [41:48<19:58, 12.33it/s]

 65%|███████████████████████▍            | 27752/42525 [41:48<19:08, 12.86it/s]

 65%|███████████████████████▍            | 27756/42525 [41:49<20:59, 11.72it/s]

 65%|███████████████████████▌            | 27760/42525 [41:49<21:28, 11.45it/s]

 65%|███████████████████████▌            | 27764/42525 [41:49<21:49, 11.27it/s]

 65%|███████████████████████▌            | 27768/42525 [41:50<21:20, 11.53it/s]

 65%|███████████████████████▌            | 27772/42525 [41:50<20:47, 11.82it/s]

 65%|███████████████████████▌            | 27776/42525 [41:50<21:36, 11.38it/s]

 65%|███████████████████████▌            | 27780/42525 [41:51<21:34, 11.39it/s]

 65%|███████████████████████▌            | 27784/42525 [41:51<21:31, 11.41it/s]

 65%|███████████████████████▌            | 27788/42525 [41:51<19:42, 12.46it/s]

 65%|███████████████████████▌            | 27792/42525 [41:52<18:38, 13.17it/s]

 65%|███████████████████████▌            | 27796/42525 [41:52<19:31, 12.58it/s]

 65%|███████████████████████▌            | 27800/42525 [41:52<20:44, 11.83it/s]

 65%|███████████████████████▌            | 27804/42525 [41:53<20:22, 12.04it/s]

 65%|███████████████████████▌            | 27808/42525 [41:53<20:28, 11.98it/s]

 65%|███████████████████████▌            | 27810/42525 [41:53<20:06, 12.20it/s]

 65%|███████████████████████▌            | 27814/42525 [41:53<22:14, 11.02it/s]

 65%|███████████████████████▌            | 27818/42525 [41:54<21:09, 11.59it/s]

 65%|███████████████████████▌            | 27822/42525 [41:54<20:46, 11.79it/s]

 65%|███████████████████████▌            | 27826/42525 [41:54<20:40, 11.85it/s]

 65%|███████████████████████▌            | 27830/42525 [41:55<21:02, 11.64it/s]

 65%|███████████████████████▌            | 27834/42525 [41:55<20:55, 11.70it/s]

 65%|███████████████████████▌            | 27838/42525 [41:56<21:18, 11.49it/s]

 65%|███████████████████████▌            | 27842/42525 [41:56<21:08, 11.58it/s]

 65%|███████████████████████▌            | 27846/42525 [41:56<19:55, 12.28it/s]

 65%|███████████████████████▌            | 27850/42525 [41:56<18:49, 12.99it/s]

 66%|███████████████████████▌            | 27854/42525 [41:57<21:07, 11.57it/s]

 66%|███████████████████████▌            | 27858/42525 [41:57<20:19, 12.02it/s]

 66%|███████████████████████▌            | 27862/42525 [41:57<20:31, 11.90it/s]

 66%|███████████████████████▌            | 27866/42525 [41:58<20:37, 11.84it/s]

 66%|███████████████████████▌            | 27870/42525 [41:58<19:46, 12.35it/s]

 66%|███████████████████████▌            | 27874/42525 [41:58<19:40, 12.41it/s]

 66%|███████████████████████▌            | 27878/42525 [41:59<20:37, 11.84it/s]

 66%|███████████████████████▌            | 27882/42525 [41:59<19:51, 12.29it/s]

 66%|███████████████████████▌            | 27886/42525 [41:59<20:09, 12.11it/s]

 66%|███████████████████████▌            | 27890/42525 [42:00<21:34, 11.31it/s]

 66%|███████████████████████▌            | 27894/42525 [42:00<20:26, 11.93it/s]

 66%|███████████████████████▌            | 27898/42525 [42:00<20:26, 11.92it/s]

 66%|███████████████████████▌            | 27902/42525 [42:01<19:10, 12.71it/s]

 66%|███████████████████████▌            | 27906/42525 [42:01<19:01, 12.80it/s]

 66%|███████████████████████▋            | 27910/42525 [42:01<18:57, 12.85it/s]

 66%|███████████████████████▋            | 27914/42525 [42:02<18:45, 12.98it/s]

 66%|███████████████████████▋            | 27918/42525 [42:02<17:58, 13.55it/s]

 66%|███████████████████████▋            | 27922/42525 [42:02<18:59, 12.81it/s]

 66%|███████████████████████▋            | 27926/42525 [42:03<19:47, 12.30it/s]

 66%|███████████████████████▋            | 27930/42525 [42:03<20:12, 12.03it/s]

 66%|███████████████████████▋            | 27934/42525 [42:03<19:20, 12.57it/s]

 66%|███████████████████████▋            | 27938/42525 [42:04<20:04, 12.11it/s]

 66%|███████████████████████▋            | 27942/42525 [42:04<20:16, 11.98it/s]

 66%|███████████████████████▋            | 27946/42525 [42:04<19:42, 12.33it/s]

 66%|███████████████████████▋            | 27950/42525 [42:05<19:19, 12.57it/s]

 66%|███████████████████████▋            | 27952/42525 [42:05<19:36, 12.38it/s]

 66%|███████████████████████▋            | 27956/42525 [42:05<21:20, 11.38it/s]

 66%|███████████████████████▋            | 27960/42525 [42:05<19:17, 12.58it/s]

 66%|███████████████████████▋            | 27964/42525 [42:06<19:27, 12.48it/s]

 66%|███████████████████████▋            | 27968/42525 [42:06<19:48, 12.25it/s]

 66%|███████████████████████▋            | 27972/42525 [42:06<19:27, 12.47it/s]

 66%|███████████████████████▋            | 27976/42525 [42:07<19:13, 12.61it/s]

 66%|███████████████████████▋            | 27980/42525 [42:07<19:09, 12.65it/s]

 66%|███████████████████████▋            | 27984/42525 [42:07<20:05, 12.06it/s]

 66%|███████████████████████▋            | 27988/42525 [42:08<19:08, 12.65it/s]

 66%|███████████████████████▋            | 27992/42525 [42:08<19:06, 12.68it/s]

 66%|███████████████████████▋            | 27996/42525 [42:08<19:56, 12.15it/s]

 66%|███████████████████████▋            | 28000/42525 [42:09<20:39, 11.71it/s]

 66%|███████████████████████▋            | 28004/42525 [42:09<19:42, 12.28it/s]

 66%|███████████████████████▋            | 28008/42525 [42:09<19:16, 12.56it/s]

 66%|███████████████████████▋            | 28012/42525 [42:10<19:46, 12.23it/s]

 66%|███████████████████████▋            | 28016/42525 [42:10<20:15, 11.93it/s]

 66%|███████████████████████▋            | 28020/42525 [42:10<21:11, 11.40it/s]

 66%|███████████████████████▋            | 28024/42525 [42:11<19:14, 12.56it/s]

 66%|███████████████████████▋            | 28028/42525 [42:11<19:02, 12.69it/s]

 66%|███████████████████████▋            | 28032/42525 [42:11<19:19, 12.50it/s]

 66%|███████████████████████▋            | 28036/42525 [42:12<20:59, 11.50it/s]

 66%|███████████████████████▋            | 28040/42525 [42:12<20:06, 12.00it/s]

 66%|███████████████████████▋            | 28044/42525 [42:12<18:53, 12.78it/s]

 66%|███████████████████████▋            | 28048/42525 [42:13<19:41, 12.25it/s]

 66%|███████████████████████▋            | 28052/42525 [42:13<20:06, 11.99it/s]

 66%|███████████████████████▊            | 28056/42525 [42:13<18:55, 12.74it/s]

 66%|███████████████████████▊            | 28060/42525 [42:14<20:46, 11.61it/s]

 66%|███████████████████████▊            | 28064/42525 [42:14<20:52, 11.54it/s]

 66%|███████████████████████▊            | 28068/42525 [42:14<19:31, 12.34it/s]

 66%|███████████████████████▊            | 28072/42525 [42:15<20:49, 11.56it/s]

 66%|███████████████████████▊            | 28076/42525 [42:15<21:06, 11.41it/s]

 66%|███████████████████████▊            | 28080/42525 [42:15<20:19, 11.85it/s]

 66%|███████████████████████▊            | 28084/42525 [42:16<20:16, 11.87it/s]

 66%|███████████████████████▊            | 28088/42525 [42:16<19:01, 12.65it/s]

 66%|███████████████████████▊            | 28090/42525 [42:16<18:24, 13.07it/s]

 66%|███████████████████████▊            | 28094/42525 [42:16<19:48, 12.14it/s]

 66%|███████████████████████▊            | 28098/42525 [42:17<20:47, 11.57it/s]

 66%|███████████████████████▊            | 28102/42525 [42:17<21:21, 11.26it/s]

 66%|███████████████████████▊            | 28106/42525 [42:18<20:21, 11.80it/s]

 66%|███████████████████████▊            | 28110/42525 [42:18<19:03, 12.61it/s]

 66%|███████████████████████▊            | 28114/42525 [42:18<20:13, 11.88it/s]

 66%|███████████████████████▊            | 28118/42525 [42:19<20:36, 11.65it/s]

 66%|███████████████████████▊            | 28122/42525 [42:19<19:36, 12.24it/s]

 66%|███████████████████████▊            | 28126/42525 [42:19<20:49, 11.52it/s]

 66%|███████████████████████▊            | 28130/42525 [42:19<19:25, 12.35it/s]

 66%|███████████████████████▊            | 28134/42525 [42:20<19:55, 12.04it/s]

 66%|███████████████████████▊            | 28138/42525 [42:20<18:39, 12.85it/s]

 66%|███████████████████████▊            | 28142/42525 [42:20<19:09, 12.51it/s]

 66%|███████████████████████▊            | 28146/42525 [42:21<19:34, 12.25it/s]

 66%|███████████████████████▊            | 28150/42525 [42:21<21:11, 11.31it/s]

 66%|███████████████████████▊            | 28154/42525 [42:22<22:07, 10.82it/s]

 66%|███████████████████████▊            | 28158/42525 [42:22<21:42, 11.03it/s]

 66%|███████████████████████▊            | 28162/42525 [42:22<21:27, 11.16it/s]

 66%|███████████████████████▊            | 28166/42525 [42:23<21:26, 11.16it/s]

 66%|███████████████████████▊            | 28170/42525 [42:23<22:45, 10.51it/s]

 66%|███████████████████████▊            | 28174/42525 [42:23<21:31, 11.11it/s]

 66%|███████████████████████▊            | 28178/42525 [42:24<21:14, 11.26it/s]

 66%|███████████████████████▊            | 28182/42525 [42:24<21:20, 11.20it/s]

 66%|███████████████████████▊            | 28186/42525 [42:24<20:43, 11.53it/s]

 66%|███████████████████████▊            | 28190/42525 [42:25<20:26, 11.69it/s]

 66%|███████████████████████▊            | 28194/42525 [42:25<21:29, 11.11it/s]

 66%|███████████████████████▊            | 28198/42525 [42:26<21:31, 11.09it/s]

 66%|███████████████████████▊            | 28202/42525 [42:26<20:46, 11.49it/s]

 66%|███████████████████████▉            | 28206/42525 [42:26<21:31, 11.09it/s]

 66%|███████████████████████▉            | 28210/42525 [42:27<22:16, 10.71it/s]

 66%|███████████████████████▉            | 28214/42525 [42:27<23:04, 10.34it/s]

 66%|███████████████████████▉            | 28218/42525 [42:27<22:03, 10.81it/s]

 66%|███████████████████████▉            | 28222/42525 [42:28<22:09, 10.76it/s]

 66%|███████████████████████▉            | 28226/42525 [42:28<21:48, 10.92it/s]

 66%|███████████████████████▉            | 28230/42525 [42:28<21:19, 11.17it/s]

 66%|███████████████████████▉            | 28234/42525 [42:29<21:35, 11.03it/s]

 66%|███████████████████████▉            | 28238/42525 [42:29<20:51, 11.42it/s]

 66%|███████████████████████▉            | 28242/42525 [42:29<20:24, 11.67it/s]

 66%|███████████████████████▉            | 28246/42525 [42:30<21:13, 11.22it/s]

 66%|███████████████████████▉            | 28250/42525 [42:30<20:52, 11.40it/s]

 66%|███████████████████████▉            | 28252/42525 [42:30<20:36, 11.54it/s]

 66%|███████████████████████▉            | 28256/42525 [42:31<21:31, 11.05it/s]

 66%|███████████████████████▉            | 28260/42525 [42:31<20:39, 11.50it/s]

 66%|███████████████████████▉            | 28264/42525 [42:31<20:45, 11.45it/s]

 66%|███████████████████████▉            | 28268/42525 [42:32<20:30, 11.59it/s]

 66%|███████████████████████▉            | 28272/42525 [42:32<20:08, 11.79it/s]

 66%|███████████████████████▉            | 28276/42525 [42:32<20:33, 11.55it/s]

 66%|███████████████████████▉            | 28278/42525 [42:33<20:28, 11.60it/s]

 67%|███████████████████████▉            | 28282/42525 [42:33<21:22, 11.11it/s]

 67%|███████████████████████▉            | 28286/42525 [42:33<20:42, 11.46it/s]

 67%|███████████████████████▉            | 28290/42525 [42:34<20:42, 11.45it/s]

 67%|███████████████████████▉            | 28294/42525 [42:34<20:12, 11.74it/s]

 67%|███████████████████████▉            | 28298/42525 [42:34<19:58, 11.87it/s]

 67%|███████████████████████▉            | 28302/42525 [42:35<19:58, 11.87it/s]

 67%|███████████████████████▉            | 28306/42525 [42:35<21:19, 11.12it/s]

 67%|███████████████████████▉            | 28310/42525 [42:35<20:44, 11.43it/s]

 67%|███████████████████████▉            | 28314/42525 [42:36<21:07, 11.21it/s]

 67%|███████████████████████▉            | 28318/42525 [42:36<20:57, 11.29it/s]

 67%|███████████████████████▉            | 28322/42525 [42:37<20:57, 11.30it/s]

 67%|███████████████████████▉            | 28326/42525 [42:37<20:49, 11.36it/s]

 67%|███████████████████████▉            | 28330/42525 [42:37<21:27, 11.03it/s]

 67%|███████████████████████▉            | 28334/42525 [42:38<21:18, 11.10it/s]

 67%|███████████████████████▉            | 28338/42525 [42:38<22:22, 10.57it/s]

 67%|███████████████████████▉            | 28342/42525 [42:38<22:13, 10.63it/s]

 67%|███████████████████████▉            | 28346/42525 [42:39<21:01, 11.24it/s]

 67%|███████████████████████▉            | 28348/42525 [42:39<21:33, 10.96it/s]

 67%|████████████████████████            | 28350/42525 [42:39<25:59,  9.09it/s]
  0%|                                                  | 0/788 [00:00<?, ?it/s]
  0%|▏                                         | 3/788 [00:00<00:30, 25.96it/s]

{'loss': '0.7725', 'grad_norm': '5.375', 'learning_rate': '7.093e-06', 'epoch': '2'}

  1%|▎                                         | 6/788 [00:00<00:36, 21.71it/s]
  1%|▍                                         | 9/788 [00:00<00:34, 22.63it/s]

  2%|▌                                        | 12/788 [00:00<00:31, 24.75it/s]
  2%|▊                                        | 15/788 [00:00<00:33, 23.37it/s]

  2%|▉                                        | 18/788 [00:00<00:35, 21.74it/s]
  3%|█                                        | 21/788 [00:00<00:36, 20.99it/s]

  3%|█▏                                       | 24/788 [00:01<00:35, 21.62it/s]
  3%|█▍                                       | 27/788 [00:01<00:36, 21.05it/s]

  4%|█▌                                       | 30/788 [00:01<00:35, 21.56it/s]
  4%|█▋                                       | 33/788 [00:01<00:35, 21.26it/s]

  5%|█▊                                       | 36/788 [00:01<00:37, 20.04it/s]
  5%|██                                       | 39/788 [00:01<00:35, 21.24it/s]

  5%|██▏                                      | 42/788 [00:01<00:33, 22.28it/s]
  6%|██▎                                      | 45/788 [00:02<00:31, 23.75it/s]

  6%|██▍                                      | 48/788 [00:02<00:32, 22.71it/s]
  6%|██▋                                      | 51/788 [00:02<00:31, 23.68it/s]

  7%|██▊                                      | 54/788 [00:02<00:30, 24.22it/s]
  7%|██▉                                      | 57/788 [00:02<00:31, 23.54it/s]

  8%|███                                      | 60/788 [00:02<00:29, 24.59it/s]
  8%|███▎                                     | 63/788 [00:02<00:31, 22.68it/s]

  8%|███▍                                     | 66/788 [00:02<00:31, 23.14it/s]
  9%|███▌                                     | 69/788 [00:03<00:32, 21.90it/s]

  9%|███▋                                     | 72/788 [00:03<00:32, 21.72it/s]
 10%|███▉                                     | 75/788 [00:03<00:33, 21.13it/s]

 10%|████                                     | 78/788 [00:03<00:33, 21.27it/s]
 10%|████▏                                    | 81/788 [00:03<00:34, 20.75it/s]

 11%|████▎                                    | 84/788 [00:03<00:34, 20.56it/s]
 11%|████▌                                    | 87/788 [00:03<00:33, 20.86it/s]

 11%|████▋                                    | 90/788 [00:04<00:33, 21.13it/s]
 12%|████▊                                    | 93/788 [00:04<00:34, 19.92it/s]

 12%|████▉                                    | 96/788 [00:04<00:33, 20.41it/s]
 13%|█████▏                                   | 99/788 [00:04<00:33, 20.62it/s]

 13%|█████▏                                  | 102/788 [00:04<00:32, 20.81it/s]
 13%|█████▎                                  | 105/788 [00:04<00:34, 20.05it/s]

 14%|█████▍                                  | 108/788 [00:04<00:32, 20.96it/s]
 14%|█████▋                                  | 111/788 [00:05<00:30, 22.50it/s]

 14%|█████▊                                  | 114/788 [00:05<00:30, 22.42it/s]
 15%|█████▉                                  | 117/788 [00:05<00:31, 21.35it/s]

 15%|██████                                  | 120/788 [00:05<00:31, 21.10it/s]
 16%|██████▏                                 | 123/788 [00:05<00:32, 20.69it/s]

 16%|██████▍                                 | 126/788 [00:05<00:29, 22.81it/s]
 16%|██████▌                                 | 129/788 [00:05<00:27, 23.77it/s]

 17%|██████▋                                 | 132/788 [00:06<00:29, 22.09it/s]
 17%|██████▊                                 | 135/788 [00:06<00:28, 22.96it/s]

 18%|███████                                 | 138/788 [00:06<00:27, 23.39it/s]
 18%|███████▏                                | 141/788 [00:06<00:29, 22.05it/s]

 18%|███████▎                                | 144/788 [00:06<00:30, 21.23it/s]
 19%|███████▌                                | 148/788 [00:06<00:26, 24.56it/s]

 19%|███████▋                                | 151/788 [00:06<00:24, 25.71it/s]
 20%|███████▊                                | 154/788 [00:06<00:25, 24.54it/s]

 20%|███████▉                                | 157/788 [00:07<00:26, 24.18it/s]
 20%|████████                                | 160/788 [00:07<00:26, 23.80it/s]

 21%|████████▎                               | 163/788 [00:07<00:29, 21.21it/s]
 21%|████████▍                               | 166/788 [00:07<00:29, 21.15it/s]

 21%|████████▌                               | 169/788 [00:07<00:29, 21.17it/s]
 22%|████████▋                               | 172/788 [00:07<00:27, 22.63it/s]

 22%|████████▉                               | 175/788 [00:07<00:27, 22.36it/s]
 23%|█████████                               | 178/788 [00:08<00:28, 21.14it/s]

 23%|█████████▏                              | 181/788 [00:08<00:29, 20.47it/s]
 23%|█████████▎                              | 184/788 [00:08<00:28, 21.10it/s]

 24%|█████████▍                              | 187/788 [00:08<00:28, 20.75it/s]
 24%|█████████▋                              | 190/788 [00:08<00:28, 20.69it/s]

 24%|█████████▊                              | 193/788 [00:08<00:29, 20.29it/s]
 25%|█████████▉                              | 196/788 [00:08<00:26, 22.35it/s]

 25%|██████████                              | 199/788 [00:09<00:27, 21.44it/s]
 26%|██████████▎                             | 202/788 [00:09<00:26, 22.05it/s]

 26%|██████████▍                             | 205/788 [00:09<00:25, 22.44it/s]
 26%|██████████▌                             | 208/788 [00:09<00:25, 23.06it/s]

 27%|██████████▋                             | 211/788 [00:09<00:26, 21.98it/s]
 27%|██████████▊                             | 214/788 [00:09<00:25, 22.69it/s]

 28%|███████████                             | 217/788 [00:09<00:26, 21.76it/s]
 28%|███████████▏                            | 220/788 [00:10<00:25, 22.04it/s]

 28%|███████████▎                            | 223/788 [00:10<00:25, 22.60it/s]
 29%|███████████▍                            | 226/788 [00:10<00:24, 23.36it/s]

 29%|███████████▌                            | 229/788 [00:10<00:22, 24.81it/s]
 29%|███████████▊                            | 232/788 [00:10<00:23, 23.99it/s]

 30%|███████████▉                            | 235/788 [00:10<00:23, 23.41it/s]
 30%|████████████                            | 238/788 [00:10<00:24, 22.89it/s]

 31%|████████████▏                           | 241/788 [00:10<00:23, 23.29it/s]
 31%|████████████▍                           | 244/788 [00:11<00:24, 22.34it/s]

 31%|████████████▌                           | 247/788 [00:11<00:25, 21.26it/s]
 32%|████████████▋                           | 250/788 [00:11<00:25, 20.90it/s]

 32%|████████████▊                           | 253/788 [00:11<00:25, 21.09it/s]
 32%|████████████▉                           | 256/788 [00:11<00:23, 22.21it/s]

 33%|█████████████▏                          | 259/788 [00:11<00:25, 20.97it/s]
 33%|█████████████▎                          | 262/788 [00:11<00:24, 21.33it/s]

 34%|█████████████▍                          | 265/788 [00:12<00:25, 20.86it/s]
 34%|█████████████▌                          | 268/788 [00:12<00:24, 21.13it/s]

 34%|█████████████▊                          | 271/788 [00:12<00:25, 20.51it/s]
 35%|█████████████▉                          | 274/788 [00:12<00:25, 19.87it/s]

 35%|██████████████                          | 277/788 [00:12<00:26, 18.96it/s]
 35%|██████████████▏                         | 279/788 [00:12<00:26, 18.90it/s]

 36%|██████████████▎                         | 282/788 [00:12<00:25, 20.01it/s]
 36%|██████████████▍                         | 285/788 [00:13<00:25, 20.00it/s]

 37%|██████████████▌                         | 288/788 [00:13<00:23, 21.01it/s]
 37%|██████████████▊                         | 292/788 [00:13<00:20, 23.73it/s]

 37%|██████████████▉                         | 295/788 [00:13<00:21, 23.13it/s]
 38%|███████████████▏                        | 298/788 [00:13<00:21, 22.66it/s]

 38%|███████████████▎                        | 301/788 [00:13<00:20, 23.28it/s]
 39%|███████████████▍                        | 304/788 [00:13<00:20, 23.15it/s]

 39%|███████████████▌                        | 307/788 [00:13<00:21, 22.67it/s]
 39%|███████████████▋                        | 310/788 [00:14<00:20, 23.01it/s]

 40%|███████████████▉                        | 313/788 [00:14<00:21, 22.26it/s]
 40%|████████████████                        | 316/788 [00:14<00:20, 22.58it/s]

 40%|████████████████▏                       | 319/788 [00:14<00:20, 22.35it/s]
 41%|████████████████▎                       | 322/788 [00:14<00:20, 22.46it/s]

 41%|████████████████▍                       | 325/788 [00:14<00:21, 21.43it/s]
 42%|████████████████▋                       | 328/788 [00:14<00:21, 21.73it/s]

 42%|████████████████▊                       | 331/788 [00:15<00:20, 22.12it/s]
 42%|████████████████▉                       | 334/788 [00:15<00:19, 23.49it/s]

 43%|█████████████████                       | 337/788 [00:15<00:19, 23.60it/s]
 43%|█████████████████▎                      | 340/788 [00:15<00:19, 22.57it/s]

 44%|█████████████████▍                      | 343/788 [00:15<00:21, 21.04it/s]
 44%|█████████████████▌                      | 346/788 [00:15<00:22, 19.52it/s]

 44%|█████████████████▋                      | 349/788 [00:15<00:21, 20.19it/s]
 45%|█████████████████▊                      | 352/788 [00:16<00:20, 21.69it/s]

 45%|██████████████████                      | 355/788 [00:16<00:20, 21.64it/s]
 45%|██████████████████▏                     | 358/788 [00:16<00:20, 21.05it/s]

 46%|██████████████████▎                     | 361/788 [00:16<00:19, 22.26it/s]
 46%|██████████████████▍                     | 364/788 [00:16<00:17, 23.87it/s]

 47%|██████████████████▋                     | 367/788 [00:16<00:18, 23.27it/s]
 47%|██████████████████▊                     | 370/788 [00:16<00:17, 23.78it/s]

 47%|██████████████████▉                     | 373/788 [00:16<00:17, 24.35it/s]
 48%|███████████████████                     | 376/788 [00:17<00:16, 24.65it/s]

 48%|███████████████████▎                    | 380/788 [00:17<00:15, 26.26it/s]
 49%|███████████████████▍                    | 383/788 [00:17<00:16, 25.19it/s]

 49%|███████████████████▌                    | 386/788 [00:17<00:16, 24.05it/s]
 49%|███████████████████▋                    | 389/788 [00:17<00:17, 23.07it/s]

 50%|███████████████████▉                    | 392/788 [00:17<00:18, 21.62it/s]
 50%|████████████████████                    | 395/788 [00:17<00:17, 22.66it/s]

 51%|████████████████████▏                   | 398/788 [00:18<00:17, 22.25it/s]
 51%|████████████████████▎                   | 401/788 [00:18<00:16, 22.77it/s]

 51%|████████████████████▌                   | 404/788 [00:18<00:16, 23.58it/s]
 52%|████████████████████▋                   | 407/788 [00:18<00:15, 23.86it/s]

 52%|████████████████████▊                   | 410/788 [00:18<00:15, 24.45it/s]
 52%|████████████████████▉                   | 413/788 [00:18<00:15, 23.93it/s]

 53%|█████████████████████                   | 416/788 [00:18<00:15, 23.70it/s]
 53%|█████████████████████▎                  | 419/788 [00:18<00:17, 21.27it/s]

 54%|█████████████████████▍                  | 422/788 [00:19<00:17, 21.00it/s]
 54%|█████████████████████▌                  | 425/788 [00:19<00:17, 21.32it/s]

 54%|█████████████████████▋                  | 428/788 [00:19<00:16, 22.09it/s]
 55%|█████████████████████▉                  | 431/788 [00:19<00:15, 23.27it/s]

 55%|██████████████████████                  | 434/788 [00:19<00:15, 22.82it/s]
 55%|██████████████████████▏                 | 437/788 [00:19<00:15, 22.19it/s]

 56%|██████████████████████▎                 | 440/788 [00:19<00:15, 22.10it/s]
 56%|██████████████████████▍                 | 443/788 [00:20<00:15, 21.67it/s]

 57%|██████████████████████▋                 | 446/788 [00:20<00:15, 21.54it/s]
 57%|██████████████████████▊                 | 449/788 [00:20<00:14, 22.62it/s]

 57%|██████████████████████▉                 | 452/788 [00:20<00:15, 22.13it/s]
 58%|███████████████████████                 | 455/788 [00:20<00:14, 22.38it/s]

 58%|███████████████████████▏                | 458/788 [00:20<00:13, 23.97it/s]
 59%|███████████████████████▍                | 461/788 [00:20<00:14, 22.76it/s]

 59%|███████████████████████▌                | 464/788 [00:20<00:14, 22.36it/s]
 59%|███████████████████████▋                | 467/788 [00:21<00:14, 22.35it/s]

 60%|███████████████████████▊                | 470/788 [00:21<00:15, 20.74it/s]
 60%|████████████████████████                | 473/788 [00:21<00:15, 20.47it/s]

 60%|████████████████████████▏               | 476/788 [00:21<00:14, 20.85it/s]
 61%|████████████████████████▎               | 479/788 [00:21<00:14, 21.34it/s]

 61%|████████████████████████▍               | 482/788 [00:21<00:14, 21.80it/s]
 62%|████████████████████████▌               | 485/788 [00:21<00:14, 21.58it/s]

 62%|████████████████████████▊               | 488/788 [00:22<00:14, 21.27it/s]
 62%|████████████████████████▉               | 491/788 [00:22<00:14, 20.20it/s]

 63%|█████████████████████████               | 494/788 [00:22<00:14, 20.71it/s]
 63%|█████████████████████████▏              | 497/788 [00:22<00:12, 22.73it/s]

 63%|█████████████████████████▍              | 500/788 [00:22<00:12, 23.40it/s]
 64%|█████████████████████████▌              | 503/788 [00:22<00:12, 22.81it/s]

 64%|█████████████████████████▋              | 506/788 [00:22<00:11, 24.28it/s]
 65%|█████████████████████████▊              | 509/788 [00:22<00:11, 23.78it/s]

 65%|█████████████████████████▉              | 512/788 [00:23<00:11, 24.45it/s]
 65%|██████████████████████████▏             | 515/788 [00:23<00:10, 25.21it/s]

 66%|██████████████████████████▎             | 518/788 [00:23<00:11, 23.57it/s]
 66%|██████████████████████████▍             | 521/788 [00:23<00:10, 24.73it/s]

 66%|██████████████████████████▌             | 524/788 [00:23<00:10, 24.23it/s]
 67%|██████████████████████████▊             | 527/788 [00:23<00:11, 22.47it/s]

 67%|██████████████████████████▉             | 530/788 [00:23<00:11, 22.16it/s]
 68%|███████████████████████████             | 533/788 [00:24<00:11, 21.98it/s]

 68%|███████████████████████████▏            | 536/788 [00:24<00:11, 22.22it/s]
 68%|███████████████████████████▎            | 539/788 [00:24<00:11, 20.98it/s]

 69%|███████████████████████████▌            | 542/788 [00:24<00:12, 20.42it/s]
 69%|███████████████████████████▋            | 545/788 [00:24<00:12, 19.69it/s]

 69%|███████████████████████████▊            | 547/788 [00:24<00:12, 19.42it/s]
 70%|███████████████████████████▉            | 550/788 [00:24<00:11, 20.05it/s]

 70%|████████████████████████████            | 553/788 [00:25<00:11, 21.18it/s]
 71%|████████████████████████████▏           | 556/788 [00:25<00:10, 21.48it/s]

 71%|████████████████████████████▍           | 559/788 [00:25<00:10, 22.56it/s]
 71%|████████████████████████████▌           | 563/788 [00:25<00:09, 24.90it/s]

 72%|████████████████████████████▋           | 566/788 [00:25<00:09, 23.71it/s]
 72%|████████████████████████████▉           | 569/788 [00:25<00:09, 23.83it/s]

 73%|█████████████████████████████           | 572/788 [00:25<00:09, 22.42it/s]
 73%|█████████████████████████████▏          | 575/788 [00:25<00:09, 21.84it/s]

 73%|█████████████████████████████▎          | 578/788 [00:26<00:09, 21.18it/s]
 74%|█████████████████████████████▍          | 581/788 [00:26<00:09, 22.18it/s]

 74%|█████████████████████████████▋          | 584/788 [00:26<00:09, 21.08it/s]
 74%|█████████████████████████████▊          | 587/788 [00:26<00:09, 21.67it/s]

 75%|█████████████████████████████▉          | 590/788 [00:26<00:09, 21.17it/s]
 75%|██████████████████████████████          | 593/788 [00:26<00:08, 21.89it/s]

 76%|██████████████████████████████▎         | 596/788 [00:26<00:08, 22.38it/s]
 76%|██████████████████████████████▍         | 599/788 [00:27<00:08, 22.55it/s]

 76%|██████████████████████████████▌         | 602/788 [00:27<00:08, 22.56it/s]
 77%|██████████████████████████████▋         | 605/788 [00:27<00:07, 23.47it/s]

 77%|██████████████████████████████▊         | 608/788 [00:27<00:07, 23.89it/s]
 78%|███████████████████████████████         | 611/788 [00:27<00:07, 23.24it/s]

 78%|███████████████████████████████▏        | 614/788 [00:27<00:07, 24.01it/s]
 78%|███████████████████████████████▎        | 617/788 [00:27<00:07, 22.67it/s]

 79%|███████████████████████████████▍        | 620/788 [00:27<00:07, 22.72it/s]
 79%|███████████████████████████████▋        | 624/788 [00:28<00:06, 24.28it/s]

 80%|███████████████████████████████▊        | 627/788 [00:28<00:07, 22.71it/s]
 80%|███████████████████████████████▉        | 630/788 [00:28<00:07, 20.91it/s]

 80%|████████████████████████████████▏       | 633/788 [00:28<00:07, 20.96it/s]
 81%|████████████████████████████████▎       | 636/788 [00:28<00:06, 22.75it/s]

 81%|████████████████████████████████▍       | 639/788 [00:28<00:07, 21.11it/s]
 82%|████████████████████████████████▋       | 643/788 [00:28<00:06, 23.87it/s]

 82%|████████████████████████████████▊       | 646/788 [00:29<00:05, 23.68it/s]
 82%|████████████████████████████████▉       | 649/788 [00:29<00:05, 24.87it/s]

 83%|█████████████████████████████████       | 652/788 [00:29<00:05, 25.31it/s]
 83%|█████████████████████████████████▏      | 655/788 [00:29<00:05, 24.42it/s]

 84%|█████████████████████████████████▍      | 658/788 [00:29<00:05, 23.85it/s]
 84%|█████████████████████████████████▌      | 661/788 [00:29<00:05, 23.00it/s]

 84%|█████████████████████████████████▋      | 664/788 [00:29<00:05, 23.43it/s]
 85%|█████████████████████████████████▊      | 667/788 [00:30<00:05, 22.28it/s]

 85%|██████████████████████████████████      | 670/788 [00:30<00:05, 22.71it/s]
 85%|██████████████████████████████████▏     | 673/788 [00:30<00:05, 22.11it/s]

 86%|██████████████████████████████████▎     | 676/788 [00:30<00:04, 22.50it/s]
 86%|██████████████████████████████████▍     | 679/788 [00:30<00:04, 21.90it/s]

 87%|██████████████████████████████████▌     | 682/788 [00:30<00:04, 22.61it/s]
 87%|██████████████████████████████████▊     | 685/788 [00:30<00:04, 22.96it/s]

 87%|██████████████████████████████████▉     | 688/788 [00:30<00:04, 22.63it/s]
 88%|███████████████████████████████████     | 691/788 [00:31<00:04, 20.91it/s]

 88%|███████████████████████████████████▏    | 694/788 [00:31<00:04, 22.68it/s]
 88%|███████████████████████████████████▍    | 697/788 [00:31<00:03, 22.90it/s]

 89%|███████████████████████████████████▌    | 700/788 [00:31<00:03, 22.61it/s]
 89%|███████████████████████████████████▋    | 703/788 [00:31<00:03, 21.34it/s]

 90%|███████████████████████████████████▊    | 706/788 [00:31<00:04, 20.37it/s]
 90%|███████████████████████████████████▉    | 709/788 [00:31<00:03, 21.02it/s]

 90%|████████████████████████████████████▏   | 712/788 [00:32<00:03, 21.00it/s]
 91%|████████████████████████████████████▎   | 715/788 [00:32<00:03, 22.80it/s]

 91%|████████████████████████████████████▍   | 719/788 [00:32<00:02, 24.02it/s]
 92%|████████████████████████████████████▋   | 722/788 [00:32<00:02, 23.41it/s]

 92%|████████████████████████████████████▊   | 725/788 [00:32<00:02, 22.32it/s]
 92%|████████████████████████████████████▉   | 728/788 [00:32<00:02, 21.95it/s]

 93%|█████████████████████████████████████   | 731/788 [00:32<00:02, 21.06it/s]
 93%|█████████████████████████████████████▎  | 734/788 [00:33<00:02, 21.24it/s]

 94%|█████████████████████████████████████▍  | 737/788 [00:33<00:02, 21.08it/s]
 94%|█████████████████████████████████████▌  | 740/788 [00:33<00:02, 21.14it/s]

 94%|█████████████████████████████████████▋  | 743/788 [00:33<00:01, 22.94it/s]
 95%|█████████████████████████████████████▊  | 746/788 [00:33<00:01, 22.25it/s]

 95%|██████████████████████████████████████  | 749/788 [00:33<00:01, 22.62it/s]
 95%|██████████████████████████████████████▏ | 752/788 [00:33<00:01, 21.50it/s]

 96%|██████████████████████████████████████▎ | 755/788 [00:34<00:01, 21.47it/s]
 96%|██████████████████████████████████████▍ | 758/788 [00:34<00:01, 22.26it/s]

 97%|██████████████████████████████████████▋ | 761/788 [00:34<00:01, 21.92it/s]
 97%|██████████████████████████████████████▊ | 765/788 [00:34<00:00, 24.60it/s]

 97%|██████████████████████████████████████▉ | 768/788 [00:34<00:00, 22.89it/s]
 98%|███████████████████████████████████████▏| 771/788 [00:34<00:00, 23.12it/s]

 98%|███████████████████████████████████████▎| 774/788 [00:34<00:00, 24.33it/s]
 99%|███████████████████████████████████████▍| 777/788 [00:34<00:00, 22.87it/s]

 99%|███████████████████████████████████████▌| 780/788 [00:35<00:00, 24.54it/s]
 99%|███████████████████████████████████████▋| 783/788 [00:35<00:00, 24.72it/s]

 67%|████████████████████████            | 28350/42525 [43:15<25:59,  9.09it/s]
100%|████████████████████████████████████████| 788/788 [00:35<00:00, 23.89it/s]

Writing model shards:   0%|                              | 0/1 [00:00<?, ?it/s]

{'eval_loss': '0.8137', 'eval_accuracy': '0.6467', 'eval_macro_f1': '0.6446', 'eval_mae': '0.4034', 'eval_cil_score': '0.8992', 'eval_quadratic_weighted_kappa': '0.8717', 'eval_runtime': '35.41', 'eval_samples_per_second': '711.6', 'eval_steps_per_second': '22.25', 'epoch': '2'}

Writing model shards: 100%|██████████████████████| 1/1 [00:01<00:00,  1.32s/it]

 67%|██████████████████████           | 28353/42525 [43:18<18:20:57,  4.66s/it]

 67%|██████████████████████▋           | 28357/42525 [43:19<8:39:34,  2.20s/it]

 67%|██████████████████████▋           | 28361/42525 [43:19<4:17:58,  1.09s/it]

 67%|██████████████████████▋           | 28365/42525 [43:19<2:15:05,  1.75it/s]

 67%|██████████████████████▋           | 28367/42525 [43:20<1:39:43,  2.37it/s]

 67%|████████████████████████            | 28371/42525 [43:20<59:27,  3.97it/s]

 67%|████████████████████████            | 28373/42525 [43:20<48:10,  4.90it/s]

 67%|████████████████████████            | 28377/42525 [43:20<35:59,  6.55it/s]

 67%|████████████████████████            | 28381/42525 [43:21<28:25,  8.29it/s]

 67%|████████████████████████            | 28385/42525 [43:21<24:15,  9.71it/s]

 67%|████████████████████████            | 28389/42525 [43:22<22:39, 10.40it/s]

 67%|████████████████████████            | 28393/42525 [43:22<22:09, 10.63it/s]

 67%|████████████████████████            | 28397/42525 [43:22<21:29, 10.95it/s]

 67%|████████████████████████            | 28401/42525 [43:23<21:41, 10.85it/s]

 67%|████████████████████████            | 28405/42525 [43:23<20:55, 11.25it/s]

 67%|████████████████████████            | 28409/42525 [43:23<21:13, 11.08it/s]

 67%|████████████████████████            | 28413/42525 [43:24<21:14, 11.08it/s]

 67%|████████████████████████            | 28417/42525 [43:24<21:28, 10.95it/s]

 67%|████████████████████████            | 28421/42525 [43:24<20:48, 11.30it/s]

 67%|████████████████████████            | 28425/42525 [43:25<21:15, 11.05it/s]

 67%|████████████████████████            | 28429/42525 [43:25<20:42, 11.34it/s]

 67%|████████████████████████            | 28433/42525 [43:25<20:27, 11.48it/s]

 67%|████████████████████████            | 28437/42525 [43:26<21:43, 10.81it/s]

 67%|████████████████████████            | 28441/42525 [43:26<20:55, 11.22it/s]

 67%|████████████████████████            | 28445/42525 [43:27<20:25, 11.49it/s]

 67%|████████████████████████            | 28449/42525 [43:27<20:46, 11.29it/s]

 67%|████████████████████████            | 28453/42525 [43:27<19:43, 11.89it/s]

 67%|████████████████████████            | 28457/42525 [43:28<19:46, 11.85it/s]

 67%|████████████████████████            | 28461/42525 [43:28<19:15, 12.17it/s]

 67%|████████████████████████            | 28465/42525 [43:28<19:55, 11.76it/s]

 67%|████████████████████████            | 28469/42525 [43:29<19:05, 12.27it/s]

 67%|████████████████████████            | 28473/42525 [43:29<20:36, 11.36it/s]

 67%|████████████████████████            | 28477/42525 [43:29<21:18, 10.98it/s]

 67%|████████████████████████            | 28481/42525 [43:30<21:01, 11.13it/s]

 67%|████████████████████████            | 28485/42525 [43:30<19:40, 11.90it/s]

 67%|████████████████████████            | 28489/42525 [43:30<19:27, 12.02it/s]

 67%|████████████████████████            | 28493/42525 [43:31<20:01, 11.68it/s]

 67%|████████████████████████            | 28497/42525 [43:31<19:15, 12.14it/s]

 67%|████████████████████████▏           | 28501/42525 [43:31<18:36, 12.56it/s]

 67%|████████████████████████▏           | 28505/42525 [43:32<17:37, 13.26it/s]

 67%|████████████████████████▏           | 28509/42525 [43:32<17:54, 13.05it/s]

 67%|████████████████████████▏           | 28513/42525 [43:32<18:19, 12.74it/s]

 67%|████████████████████████▏           | 28517/42525 [43:33<19:03, 12.25it/s]

 67%|████████████████████████▏           | 28521/42525 [43:33<18:36, 12.55it/s]

 67%|████████████████████████▏           | 28525/42525 [43:33<18:59, 12.28it/s]

 67%|████████████████████████▏           | 28529/42525 [43:34<18:00, 12.95it/s]

 67%|████████████████████████▏           | 28533/42525 [43:34<18:45, 12.43it/s]

 67%|████████████████████████▏           | 28537/42525 [43:34<19:02, 12.25it/s]

 67%|████████████████████████▏           | 28541/42525 [43:35<19:13, 12.12it/s]

 67%|████████████████████████▏           | 28545/42525 [43:35<19:32, 11.92it/s]

 67%|████████████████████████▏           | 28549/42525 [43:35<19:28, 11.96it/s]

 67%|████████████████████████▏           | 28553/42525 [43:36<20:09, 11.55it/s]

 67%|████████████████████████▏           | 28557/42525 [43:36<20:43, 11.24it/s]

 67%|████████████████████████▏           | 28561/42525 [43:36<20:21, 11.43it/s]

 67%|████████████████████████▏           | 28565/42525 [43:37<20:08, 11.55it/s]

 67%|████████████████████████▏           | 28569/42525 [43:37<19:24, 11.98it/s]

 67%|████████████████████████▏           | 28573/42525 [43:37<19:16, 12.07it/s]

 67%|████████████████████████▏           | 28577/42525 [43:38<19:27, 11.95it/s]

 67%|████████████████████████▏           | 28581/42525 [43:38<20:37, 11.27it/s]

 67%|████████████████████████▏           | 28585/42525 [43:38<20:49, 11.15it/s]

 67%|████████████████████████▏           | 28589/42525 [43:39<19:23, 11.98it/s]

 67%|████████████████████████▏           | 28593/42525 [43:39<19:42, 11.78it/s]

 67%|████████████████████████▏           | 28595/42525 [43:39<20:02, 11.58it/s]

 67%|████████████████████████▏           | 28599/42525 [43:40<21:26, 10.82it/s]

 67%|████████████████████████▏           | 28603/42525 [43:40<21:22, 10.85it/s]

 67%|████████████████████████▏           | 28607/42525 [43:40<20:05, 11.54it/s]

 67%|████████████████████████▏           | 28611/42525 [43:41<19:50, 11.69it/s]

 67%|████████████████████████▏           | 28615/42525 [43:41<20:03, 11.56it/s]

 67%|████████████████████████▏           | 28619/42525 [43:41<19:50, 11.68it/s]

 67%|████████████████████████▏           | 28623/42525 [43:42<20:28, 11.31it/s]

 67%|████████████████████████▏           | 28627/42525 [43:42<20:53, 11.09it/s]

 67%|████████████████████████▏           | 28631/42525 [43:42<21:53, 10.58it/s]

 67%|████████████████████████▏           | 28635/42525 [43:43<21:06, 10.97it/s]

 67%|████████████████████████▏           | 28639/42525 [43:43<20:41, 11.18it/s]

 67%|████████████████████████▏           | 28641/42525 [43:43<20:24, 11.33it/s]

 67%|████████████████████████▏           | 28645/42525 [43:44<21:02, 11.00it/s]

 67%|████████████████████████▎           | 28649/42525 [43:44<20:18, 11.39it/s]

 67%|████████████████████████▎           | 28653/42525 [43:44<20:22, 11.35it/s]

 67%|████████████████████████▎           | 28657/42525 [43:45<20:20, 11.36it/s]

 67%|████████████████████████▎           | 28661/42525 [43:45<19:33, 11.81it/s]

 67%|████████████████████████▎           | 28665/42525 [43:45<18:22, 12.57it/s]

 67%|████████████████████████▎           | 28669/42525 [43:46<19:05, 12.10it/s]

 67%|████████████████████████▎           | 28673/42525 [43:46<18:23, 12.55it/s]

 67%|████████████████████████▎           | 28677/42525 [43:46<17:51, 12.93it/s]

 67%|████████████████████████▎           | 28681/42525 [43:47<18:25, 12.52it/s]

 67%|████████████████████████▎           | 28685/42525 [43:47<17:59, 12.82it/s]

 67%|████████████████████████▎           | 28689/42525 [43:47<18:01, 12.80it/s]

 67%|████████████████████████▎           | 28693/42525 [43:48<17:56, 12.84it/s]

 67%|████████████████████████▎           | 28697/42525 [43:48<19:13, 11.99it/s]

 67%|████████████████████████▎           | 28701/42525 [43:48<18:22, 12.54it/s]

 67%|████████████████████████▎           | 28703/42525 [43:48<18:07, 12.71it/s]

 68%|████████████████████████▎           | 28707/42525 [43:49<19:20, 11.90it/s]

 68%|████████████████████████▎           | 28711/42525 [43:49<19:13, 11.98it/s]

 68%|████████████████████████▎           | 28715/42525 [43:49<18:12, 12.65it/s]

 68%|████████████████████████▎           | 28719/42525 [43:50<18:23, 12.51it/s]

 68%|████████████████████████▎           | 28723/42525 [43:50<18:46, 12.25it/s]

 68%|████████████████████████▎           | 28727/42525 [43:50<17:38, 13.03it/s]

 68%|████████████████████████▎           | 28731/42525 [43:51<19:27, 11.81it/s]

 68%|████████████████████████▎           | 28735/42525 [43:51<19:50, 11.58it/s]

 68%|████████████████████████▎           | 28739/42525 [43:51<18:56, 12.13it/s]

 68%|████████████████████████▎           | 28743/42525 [43:52<17:56, 12.80it/s]

 68%|████████████████████████▎           | 28747/42525 [43:52<18:35, 12.35it/s]

 68%|████████████████████████▎           | 28751/42525 [43:52<18:13, 12.60it/s]

 68%|████████████████████████▎           | 28755/42525 [43:53<17:55, 12.81it/s]

 68%|████████████████████████▎           | 28759/42525 [43:53<18:52, 12.16it/s]

 68%|████████████████████████▎           | 28763/42525 [43:53<18:36, 12.32it/s]

 68%|████████████████████████▎           | 28767/42525 [43:54<17:58, 12.76it/s]

 68%|████████████████████████▎           | 28769/42525 [43:54<19:02, 12.04it/s]

 68%|████████████████████████▎           | 28773/42525 [43:54<21:04, 10.88it/s]

 68%|████████████████████████▎           | 28777/42525 [43:54<19:27, 11.77it/s]

 68%|████████████████████████▎           | 28781/42525 [43:55<19:28, 11.76it/s]

 68%|████████████████████████▎           | 28785/42525 [43:55<19:10, 11.95it/s]

 68%|████████████████████████▎           | 28789/42525 [43:55<18:50, 12.15it/s]

 68%|████████████████████████▍           | 28793/42525 [43:56<17:39, 12.96it/s]

 68%|████████████████████████▍           | 28797/42525 [43:56<17:51, 12.82it/s]

 68%|████████████████████████▍           | 28801/42525 [43:56<18:51, 12.13it/s]

 68%|████████████████████████▍           | 28803/42525 [43:57<19:35, 11.67it/s]

 68%|████████████████████████▍           | 28807/42525 [43:57<20:24, 11.20it/s]

 68%|████████████████████████▍           | 28811/42525 [43:57<20:44, 11.02it/s]

 68%|████████████████████████▍           | 28815/42525 [43:58<21:09, 10.80it/s]

 68%|████████████████████████▍           | 28819/42525 [43:58<20:37, 11.08it/s]

 68%|████████████████████████▍           | 28823/42525 [43:58<21:13, 10.76it/s]

 68%|████████████████████████▍           | 28827/42525 [43:59<21:35, 10.57it/s]

 68%|████████████████████████▍           | 28831/42525 [43:59<21:22, 10.68it/s]

 68%|████████████████████████▍           | 28835/42525 [44:00<21:36, 10.56it/s]

 68%|████████████████████████▍           | 28839/42525 [44:00<21:01, 10.85it/s]

 68%|████████████████████████▍           | 28843/42525 [44:00<20:18, 11.23it/s]

 68%|████████████████████████▍           | 28847/42525 [44:01<19:53, 11.46it/s]

 68%|████████████████████████▍           | 28849/42525 [44:01<20:03, 11.36it/s]

 68%|████████████████████████▍           | 28853/42525 [44:01<21:01, 10.84it/s]

 68%|████████████████████████▍           | 28857/42525 [44:02<20:49, 10.94it/s]

 68%|████████████████████████▍           | 28861/42525 [44:02<20:42, 11.00it/s]

 68%|████████████████████████▍           | 28865/42525 [44:02<20:33, 11.08it/s]

 68%|████████████████████████▍           | 28869/42525 [44:03<19:54, 11.44it/s]

 68%|████████████████████████▍           | 28873/42525 [44:03<19:40, 11.56it/s]

 68%|████████████████████████▍           | 28877/42525 [44:03<20:53, 10.89it/s]

 68%|████████████████████████▍           | 28881/42525 [44:04<20:41, 10.99it/s]

 68%|████████████████████████▍           | 28885/42525 [44:04<20:37, 11.02it/s]

 68%|████████████████████████▍           | 28889/42525 [44:04<19:00, 11.95it/s]

 68%|████████████████████████▍           | 28893/42525 [44:05<18:04, 12.56it/s]

 68%|████████████████████████▍           | 28897/42525 [44:05<18:20, 12.39it/s]

 68%|████████████████████████▍           | 28901/42525 [44:05<18:22, 12.36it/s]

 68%|████████████████████████▍           | 28905/42525 [44:06<17:56, 12.65it/s]

 68%|████████████████████████▍           | 28909/42525 [44:06<18:58, 11.96it/s]

 68%|████████████████████████▍           | 28913/42525 [44:06<19:01, 11.92it/s]

 68%|████████████████████████▍           | 28917/42525 [44:07<18:32, 12.23it/s]

 68%|████████████████████████▍           | 28921/42525 [44:07<19:03, 11.90it/s]

 68%|████████████████████████▍           | 28925/42525 [44:07<17:54, 12.65it/s]

 68%|████████████████████████▍           | 28929/42525 [44:08<18:45, 12.08it/s]

 68%|████████████████████████▍           | 28933/42525 [44:08<18:26, 12.28it/s]

 68%|████████████████████████▍           | 28937/42525 [44:08<19:01, 11.90it/s]

 68%|████████████████████████▌           | 28941/42525 [44:09<19:57, 11.34it/s]

 68%|████████████████████████▌           | 28945/42525 [44:09<20:38, 10.97it/s]

 68%|████████████████████████▌           | 28949/42525 [44:09<21:15, 10.64it/s]

 68%|████████████████████████▌           | 28953/42525 [44:10<21:04, 10.73it/s]

 68%|████████████████████████▌           | 28957/42525 [44:10<20:44, 10.90it/s]

 68%|████████████████████████▌           | 28961/42525 [44:11<20:19, 11.12it/s]

 68%|████████████████████████▌           | 28965/42525 [44:11<20:02, 11.28it/s]

 68%|████████████████████████▌           | 28969/42525 [44:11<20:11, 11.19it/s]

 68%|████████████████████████▌           | 28973/42525 [44:12<19:07, 11.81it/s]

 68%|████████████████████████▌           | 28977/42525 [44:12<19:52, 11.36it/s]

 68%|████████████████████████▌           | 28981/42525 [44:12<19:04, 11.83it/s]

 68%|████████████████████████▌           | 28985/42525 [44:13<18:51, 11.97it/s]

 68%|████████████████████████▌           | 28989/42525 [44:13<18:48, 11.99it/s]

 68%|████████████████████████▌           | 28993/42525 [44:13<19:36, 11.51it/s]

 68%|████████████████████████▌           | 28997/42525 [44:14<20:01, 11.25it/s]

 68%|████████████████████████▌           | 29001/42525 [44:14<20:06, 11.21it/s]

 68%|████████████████████████▌           | 29005/42525 [44:14<19:46, 11.40it/s]

 68%|████████████████████████▌           | 29009/42525 [44:15<20:57, 10.75it/s]

 68%|████████████████████████▌           | 29013/42525 [44:15<20:30, 10.98it/s]

 68%|████████████████████████▌           | 29015/42525 [44:15<20:19, 11.08it/s]

 68%|████████████████████████▌           | 29019/42525 [44:16<20:33, 10.95it/s]

 68%|████████████████████████▌           | 29023/42525 [44:16<19:53, 11.31it/s]

 68%|████████████████████████▌           | 29027/42525 [44:16<20:23, 11.03it/s]

 68%|████████████████████████▌           | 29031/42525 [44:17<19:42, 11.41it/s]

 68%|████████████████████████▌           | 29035/42525 [44:17<19:30, 11.53it/s]

 68%|████████████████████████▌           | 29039/42525 [44:17<20:13, 11.11it/s]

 68%|████████████████████████▌           | 29043/42525 [44:18<19:38, 11.44it/s]

 68%|████████████████████████▌           | 29047/42525 [44:18<19:46, 11.36it/s]

 68%|████████████████████████▌           | 29051/42525 [44:18<20:10, 11.13it/s]

 68%|████████████████████████▌           | 29055/42525 [44:19<20:14, 11.09it/s]

 68%|████████████████████████▌           | 29059/42525 [44:19<20:30, 10.94it/s]

 68%|████████████████████████▌           | 29063/42525 [44:20<19:25, 11.55it/s]

 68%|████████████████████████▌           | 29067/42525 [44:20<19:49, 11.31it/s]

 68%|████████████████████████▌           | 29071/42525 [44:20<19:40, 11.39it/s]

 68%|████████████████████████▌           | 29075/42525 [44:21<20:22, 11.00it/s]

 68%|████████████████████████▌           | 29079/42525 [44:21<20:02, 11.18it/s]

 68%|████████████████████████▌           | 29083/42525 [44:21<19:49, 11.30it/s]

 68%|████████████████████████▌           | 29087/42525 [44:22<19:56, 11.23it/s]

 68%|████████████████████████▋           | 29091/42525 [44:22<19:43, 11.36it/s]

 68%|████████████████████████▋           | 29095/42525 [44:22<19:22, 11.56it/s]

 68%|████████████████████████▋           | 29099/42525 [44:23<18:07, 12.34it/s]

 68%|████████████████████████▋           | 29103/42525 [44:23<19:20, 11.56it/s]

 68%|████████████████████████▋           | 29107/42525 [44:23<19:46, 11.31it/s]

 68%|████████████████████████▋           | 29111/42525 [44:24<18:19, 12.20it/s]

 68%|████████████████████████▋           | 29115/42525 [44:24<17:58, 12.43it/s]

 68%|████████████████████████▋           | 29119/42525 [44:24<17:17, 12.93it/s]

 68%|████████████████████████▋           | 29123/42525 [44:25<18:14, 12.24it/s]

 68%|████████████████████████▋           | 29127/42525 [44:25<19:10, 11.65it/s]

 69%|████████████████████████▋           | 29131/42525 [44:25<18:30, 12.06it/s]

 69%|████████████████████████▋           | 29135/42525 [44:26<17:43, 12.59it/s]

 69%|████████████████████████▋           | 29139/42525 [44:26<17:33, 12.70it/s]

 69%|████████████████████████▋           | 29143/42525 [44:26<18:00, 12.38it/s]

 69%|████████████████████████▋           | 29147/42525 [44:27<17:59, 12.39it/s]

 69%|████████████████████████▋           | 29151/42525 [44:27<19:23, 11.50it/s]

 69%|████████████████████████▋           | 29155/42525 [44:27<19:44, 11.29it/s]

 69%|████████████████████████▋           | 29159/42525 [44:28<20:19, 10.96it/s]

 69%|████████████████████████▋           | 29163/42525 [44:28<19:47, 11.25it/s]

 69%|████████████████████████▋           | 29167/42525 [44:28<19:44, 11.28it/s]

 69%|████████████████████████▋           | 29171/42525 [44:29<18:56, 11.75it/s]

 69%|████████████████████████▋           | 29175/42525 [44:29<18:18, 12.16it/s]

 69%|████████████████████████▋           | 29179/42525 [44:29<18:33, 11.99it/s]

 69%|████████████████████████▋           | 29183/42525 [44:30<17:24, 12.78it/s]

 69%|████████████████████████▋           | 29187/42525 [44:30<17:14, 12.89it/s]

 69%|████████████████████████▋           | 29191/42525 [44:30<19:04, 11.65it/s]

 69%|████████████████████████▋           | 29195/42525 [44:31<18:53, 11.76it/s]

 69%|████████████████████████▋           | 29199/42525 [44:31<18:46, 11.83it/s]

 69%|████████████████████████▋           | 29203/42525 [44:31<18:37, 11.92it/s]

 69%|████████████████████████▋           | 29207/42525 [44:32<17:43, 12.52it/s]

 69%|████████████████████████▋           | 29211/42525 [44:32<18:02, 12.29it/s]

 69%|████████████████████████▋           | 29215/42525 [44:32<17:28, 12.69it/s]

 69%|████████████████████████▋           | 29219/42525 [44:33<18:07, 12.24it/s]

 69%|████████████████████████▋           | 29223/42525 [44:33<17:57, 12.35it/s]

 69%|████████████████████████▋           | 29227/42525 [44:33<17:11, 12.89it/s]

 69%|████████████████████████▋           | 29231/42525 [44:34<17:46, 12.46it/s]

 69%|████████████████████████▋           | 29235/42525 [44:34<16:56, 13.08it/s]

 69%|████████████████████████▊           | 29239/42525 [44:34<17:16, 12.82it/s]

 69%|████████████████████████▊           | 29243/42525 [44:35<16:49, 13.16it/s]

 69%|████████████████████████▊           | 29247/42525 [44:35<17:54, 12.36it/s]

 69%|████████████████████████▊           | 29251/42525 [44:35<17:42, 12.49it/s]

 69%|████████████████████████▊           | 29255/42525 [44:36<16:54, 13.08it/s]

 69%|████████████████████████▊           | 29259/42525 [44:36<17:51, 12.38it/s]

 69%|████████████████████████▊           | 29263/42525 [44:36<18:13, 12.13it/s]

 69%|████████████████████████▊           | 29267/42525 [44:37<19:43, 11.21it/s]

 69%|████████████████████████▊           | 29269/42525 [44:37<19:25, 11.37it/s]

 69%|████████████████████████▊           | 29273/42525 [44:37<19:47, 11.16it/s]

 69%|████████████████████████▊           | 29277/42525 [44:37<19:44, 11.19it/s]

 69%|████████████████████████▊           | 29281/42525 [44:38<19:55, 11.08it/s]

 69%|████████████████████████▊           | 29285/42525 [44:38<20:03, 11.00it/s]

 69%|████████████████████████▊           | 29289/42525 [44:39<18:39, 11.82it/s]

 69%|████████████████████████▊           | 29293/42525 [44:39<18:31, 11.91it/s]

 69%|████████████████████████▊           | 29297/42525 [44:39<18:50, 11.70it/s]

 69%|████████████████████████▊           | 29301/42525 [44:39<17:50, 12.36it/s]

 69%|████████████████████████▊           | 29305/42525 [44:40<19:30, 11.29it/s]

 69%|████████████████████████▊           | 29309/42525 [44:40<19:41, 11.18it/s]

 69%|████████████████████████▊           | 29313/42525 [44:41<18:45, 11.74it/s]

 69%|████████████████████████▊           | 29317/42525 [44:41<19:19, 11.39it/s]

 69%|████████████████████████▊           | 29321/42525 [44:41<19:18, 11.39it/s]

 69%|████████████████████████▊           | 29325/42525 [44:42<19:02, 11.56it/s]

 69%|████████████████████████▊           | 29329/42525 [44:42<20:12, 10.88it/s]

 69%|████████████████████████▊           | 29333/42525 [44:42<20:26, 10.75it/s]

 69%|████████████████████████▊           | 29337/42525 [44:43<19:31, 11.25it/s]

 69%|████████████████████████▊           | 29341/42525 [44:43<19:24, 11.32it/s]

 69%|████████████████████████▊           | 29345/42525 [44:43<19:38, 11.18it/s]

 69%|████████████████████████▊           | 29349/42525 [44:44<19:12, 11.43it/s]

 69%|████████████████████████▊           | 29353/42525 [44:44<20:14, 10.84it/s]

 69%|████████████████████████▊           | 29357/42525 [44:45<19:20, 11.35it/s]

 69%|████████████████████████▊           | 29361/42525 [44:45<19:00, 11.54it/s]

 69%|████████████████████████▊           | 29365/42525 [44:45<17:36, 12.45it/s]

 69%|████████████████████████▊           | 29369/42525 [44:45<17:56, 12.22it/s]

 69%|████████████████████████▊           | 29373/42525 [44:46<17:40, 12.40it/s]

 69%|████████████████████████▊           | 29377/42525 [44:46<17:32, 12.49it/s]

 69%|████████████████████████▊           | 29381/42525 [44:46<18:22, 11.93it/s]

 69%|████████████████████████▉           | 29385/42525 [44:47<18:17, 11.98it/s]

 69%|████████████████████████▉           | 29389/42525 [44:47<18:43, 11.69it/s]

 69%|████████████████████████▉           | 29393/42525 [44:47<18:41, 11.71it/s]

 69%|████████████████████████▉           | 29397/42525 [44:48<18:42, 11.70it/s]

 69%|████████████████████████▉           | 29401/42525 [44:48<18:54, 11.56it/s]

 69%|████████████████████████▉           | 29405/42525 [44:48<18:40, 11.70it/s]

 69%|████████████████████████▉           | 29407/42525 [44:49<18:38, 11.73it/s]

 69%|████████████████████████▉           | 29411/42525 [44:49<19:12, 11.38it/s]

 69%|████████████████████████▉           | 29415/42525 [44:49<19:57, 10.95it/s]

 69%|████████████████████████▉           | 29419/42525 [44:50<20:18, 10.75it/s]

 69%|████████████████████████▉           | 29423/42525 [44:50<18:47, 11.62it/s]

 69%|████████████████████████▉           | 29427/42525 [44:50<19:26, 11.23it/s]

 69%|████████████████████████▉           | 29431/42525 [44:51<17:49, 12.24it/s]

 69%|████████████████████████▉           | 29435/42525 [44:51<17:14, 12.65it/s]

 69%|████████████████████████▉           | 29439/42525 [44:51<18:30, 11.79it/s]

 69%|████████████████████████▉           | 29443/42525 [44:52<17:25, 12.51it/s]

 69%|████████████████████████▉           | 29445/42525 [44:52<17:42, 12.31it/s]

 69%|████████████████████████▉           | 29449/42525 [44:52<19:44, 11.04it/s]

 69%|████████████████████████▉           | 29453/42525 [44:53<19:51, 10.97it/s]

 69%|████████████████████████▉           | 29457/42525 [44:53<19:58, 10.90it/s]

 69%|████████████████████████▉           | 29461/42525 [44:53<19:53, 10.94it/s]

 69%|████████████████████████▉           | 29465/42525 [44:54<19:28, 11.17it/s]

 69%|████████████████████████▉           | 29469/42525 [44:54<19:10, 11.35it/s]

 69%|████████████████████████▉           | 29473/42525 [44:54<19:25, 11.20it/s]

 69%|████████████████████████▉           | 29477/42525 [44:55<19:52, 10.94it/s]

 69%|████████████████████████▉           | 29481/42525 [44:55<20:00, 10.86it/s]

 69%|████████████████████████▉           | 29485/42525 [44:56<19:17, 11.26it/s]

 69%|████████████████████████▉           | 29487/42525 [44:56<19:27, 11.16it/s]

 69%|████████████████████████▉           | 29491/42525 [44:56<20:34, 10.56it/s]

 69%|████████████████████████▉           | 29495/42525 [44:57<19:30, 11.14it/s]

 69%|████████████████████████▉           | 29499/42525 [44:57<19:06, 11.36it/s]

 69%|████████████████████████▉           | 29503/42525 [44:57<18:50, 11.52it/s]

 69%|████████████████████████▉           | 29507/42525 [44:58<18:41, 11.61it/s]

 69%|████████████████████████▉           | 29511/42525 [44:58<18:28, 11.74it/s]

 69%|████████████████████████▉           | 29515/42525 [44:58<19:02, 11.38it/s]

 69%|████████████████████████▉           | 29519/42525 [44:59<19:00, 11.41it/s]

 69%|████████████████████████▉           | 29523/42525 [44:59<18:35, 11.66it/s]

 69%|████████████████████████▉           | 29527/42525 [44:59<18:31, 11.70it/s]

 69%|████████████████████████▉           | 29531/42525 [45:00<18:20, 11.80it/s]

 69%|█████████████████████████           | 29535/42525 [45:00<18:54, 11.45it/s]

 69%|█████████████████████████           | 29539/42525 [45:00<19:47, 10.94it/s]

 69%|█████████████████████████           | 29543/42525 [45:01<19:45, 10.95it/s]

 69%|█████████████████████████           | 29547/42525 [45:01<19:17, 11.22it/s]

 69%|█████████████████████████           | 29551/42525 [45:01<19:40, 10.99it/s]

 70%|█████████████████████████           | 29555/42525 [45:02<18:08, 11.91it/s]

 70%|█████████████████████████           | 29559/42525 [45:02<18:59, 11.38it/s]

 70%|█████████████████████████           | 29563/42525 [45:02<19:01, 11.36it/s]

 70%|█████████████████████████           | 29567/42525 [45:03<19:06, 11.30it/s]

 70%|█████████████████████████           | 29571/42525 [45:03<19:21, 11.15it/s]

 70%|█████████████████████████           | 29575/42525 [45:04<19:12, 11.23it/s]

 70%|█████████████████████████           | 29579/42525 [45:04<18:39, 11.56it/s]

 70%|█████████████████████████           | 29583/42525 [45:04<19:13, 11.22it/s]

 70%|█████████████████████████           | 29587/42525 [45:05<19:02, 11.33it/s]

 70%|█████████████████████████           | 29591/42525 [45:05<18:30, 11.65it/s]

 70%|█████████████████████████           | 29595/42525 [45:05<18:18, 11.77it/s]

 70%|█████████████████████████           | 29599/42525 [45:06<18:19, 11.75it/s]

 70%|█████████████████████████           | 29603/42525 [45:06<19:17, 11.16it/s]

 70%|█████████████████████████           | 29607/42525 [45:06<19:34, 11.00it/s]

 70%|█████████████████████████           | 29611/42525 [45:07<19:32, 11.01it/s]

 70%|█████████████████████████           | 29615/42525 [45:07<19:23, 11.10it/s]

 70%|█████████████████████████           | 29619/42525 [45:07<19:10, 11.22it/s]

 70%|█████████████████████████           | 29623/42525 [45:08<19:38, 10.95it/s]

 70%|█████████████████████████           | 29627/42525 [45:08<19:03, 11.28it/s]

 70%|█████████████████████████           | 29631/42525 [45:09<19:30, 11.02it/s]

 70%|█████████████████████████           | 29635/42525 [45:09<19:39, 10.93it/s]

 70%|█████████████████████████           | 29639/42525 [45:09<19:08, 11.22it/s]

 70%|█████████████████████████           | 29643/42525 [45:10<18:56, 11.33it/s]

 70%|█████████████████████████           | 29647/42525 [45:10<18:39, 11.51it/s]

 70%|█████████████████████████           | 29651/42525 [45:10<19:38, 10.92it/s]

 70%|█████████████████████████           | 29655/42525 [45:11<19:03, 11.26it/s]

 70%|█████████████████████████           | 29659/42525 [45:11<19:32, 10.98it/s]

 70%|█████████████████████████           | 29663/42525 [45:11<18:46, 11.41it/s]

 70%|█████████████████████████           | 29667/42525 [45:12<18:18, 11.70it/s]

 70%|█████████████████████████           | 29671/42525 [45:12<18:22, 11.66it/s]

 70%|█████████████████████████           | 29675/42525 [45:12<17:44, 12.08it/s]

 70%|█████████████████████████▏          | 29679/42525 [45:13<16:59, 12.60it/s]

 70%|█████████████████████████▏          | 29683/42525 [45:13<18:09, 11.79it/s]

 70%|█████████████████████████▏          | 29687/42525 [45:13<17:06, 12.51it/s]

 70%|█████████████████████████▏          | 29691/42525 [45:14<18:28, 11.58it/s]

 70%|█████████████████████████▏          | 29695/42525 [45:14<18:34, 11.51it/s]

 70%|█████████████████████████▏          | 29699/42525 [45:14<18:39, 11.46it/s]

 70%|█████████████████████████▏          | 29703/42525 [45:15<18:12, 11.74it/s]

 70%|█████████████████████████▏          | 29707/42525 [45:15<17:35, 12.15it/s]

 70%|█████████████████████████▏          | 29711/42525 [45:15<18:39, 11.45it/s]

 70%|█████████████████████████▏          | 29715/42525 [45:16<17:48, 11.99it/s]

 70%|█████████████████████████▏          | 29719/42525 [45:16<17:47, 11.99it/s]

 70%|█████████████████████████▏          | 29723/42525 [45:16<17:47, 12.00it/s]

 70%|█████████████████████████▏          | 29727/42525 [45:17<17:37, 12.10it/s]

 70%|█████████████████████████▏          | 29731/42525 [45:17<16:48, 12.69it/s]

 70%|█████████████████████████▏          | 29735/42525 [45:17<16:21, 13.03it/s]

 70%|█████████████████████████▏          | 29739/42525 [45:18<18:30, 11.51it/s]

 70%|█████████████████████████▏          | 29743/42525 [45:18<18:05, 11.77it/s]

 70%|█████████████████████████▏          | 29747/42525 [45:18<17:48, 11.95it/s]

 70%|█████████████████████████▏          | 29751/42525 [45:19<17:42, 12.03it/s]

 70%|█████████████████████████▏          | 29755/42525 [45:19<18:10, 11.71it/s]

 70%|█████████████████████████▏          | 29759/42525 [45:19<17:49, 11.94it/s]

 70%|█████████████████████████▏          | 29763/42525 [45:20<17:43, 12.00it/s]

 70%|█████████████████████████▏          | 29767/42525 [45:20<18:22, 11.57it/s]

 70%|█████████████████████████▏          | 29771/42525 [45:20<18:16, 11.64it/s]

 70%|█████████████████████████▏          | 29775/42525 [45:21<18:05, 11.74it/s]

 70%|█████████████████████████▏          | 29779/42525 [45:21<18:13, 11.66it/s]

 70%|█████████████████████████▏          | 29783/42525 [45:22<19:50, 10.71it/s]

 70%|█████████████████████████▏          | 29787/42525 [45:22<18:37, 11.40it/s]

 70%|█████████████████████████▏          | 29791/42525 [45:22<16:54, 12.55it/s]

 70%|█████████████████████████▏          | 29795/42525 [45:22<18:05, 11.73it/s]

 70%|█████████████████████████▏          | 29799/42525 [45:23<16:47, 12.63it/s]

 70%|█████████████████████████▏          | 29803/42525 [45:23<17:12, 12.32it/s]

 70%|█████████████████████████▏          | 29807/42525 [45:23<17:31, 12.09it/s]

 70%|█████████████████████████▏          | 29811/42525 [45:24<16:53, 12.54it/s]

 70%|█████████████████████████▏          | 29815/42525 [45:24<16:54, 12.52it/s]

 70%|█████████████████████████▏          | 29819/42525 [45:24<16:39, 12.72it/s]

 70%|█████████████████████████▏          | 29823/42525 [45:25<16:57, 12.48it/s]

 70%|█████████████████████████▎          | 29827/42525 [45:25<17:44, 11.93it/s]

 70%|█████████████████████████▎          | 29831/42525 [45:25<18:22, 11.51it/s]

 70%|█████████████████████████▎          | 29835/42525 [45:26<18:13, 11.61it/s]

 70%|█████████████████████████▎          | 29839/42525 [45:26<18:02, 11.72it/s]

 70%|█████████████████████████▎          | 29843/42525 [45:26<18:08, 11.65it/s]

 70%|█████████████████████████▎          | 29847/42525 [45:27<17:58, 11.76it/s]

 70%|█████████████████████████▎          | 29851/42525 [45:27<18:46, 11.26it/s]

 70%|█████████████████████████▎          | 29855/42525 [45:27<18:03, 11.69it/s]

 70%|█████████████████████████▎          | 29859/42525 [45:28<18:42, 11.28it/s]

 70%|█████████████████████████▎          | 29863/42525 [45:28<18:53, 11.17it/s]

 70%|█████████████████████████▎          | 29867/42525 [45:28<16:53, 12.48it/s]

 70%|█████████████████████████▎          | 29871/42525 [45:29<16:38, 12.68it/s]

 70%|█████████████████████████▎          | 29875/42525 [45:29<16:30, 12.77it/s]

 70%|█████████████████████████▎          | 29879/42525 [45:29<17:04, 12.35it/s]

 70%|█████████████████████████▎          | 29883/42525 [45:30<16:36, 12.69it/s]

 70%|█████████████████████████▎          | 29887/42525 [45:30<18:21, 11.47it/s]

 70%|█████████████████████████▎          | 29891/42525 [45:30<17:34, 11.98it/s]

 70%|█████████████████████████▎          | 29895/42525 [45:31<17:16, 12.19it/s]

 70%|█████████████████████████▎          | 29899/42525 [45:31<17:46, 11.83it/s]

 70%|█████████████████████████▎          | 29903/42525 [45:31<18:38, 11.28it/s]

 70%|█████████████████████████▎          | 29907/42525 [45:32<18:13, 11.54it/s]

 70%|█████████████████████████▎          | 29911/42525 [45:32<18:00, 11.68it/s]

 70%|█████████████████████████▎          | 29915/42525 [45:33<18:30, 11.36it/s]

 70%|█████████████████████████▎          | 29919/42525 [45:33<18:54, 11.11it/s]

 70%|█████████████████████████▎          | 29923/42525 [45:33<19:09, 10.97it/s]

 70%|█████████████████████████▎          | 29927/42525 [45:34<18:28, 11.36it/s]

 70%|█████████████████████████▎          | 29931/42525 [45:34<18:21, 11.44it/s]

 70%|█████████████████████████▎          | 29935/42525 [45:34<18:17, 11.48it/s]

 70%|█████████████████████████▎          | 29937/42525 [45:34<18:02, 11.62it/s]

 70%|█████████████████████████▎          | 29939/42525 [45:35<19:05, 10.99it/s]

 70%|█████████████████████████▎          | 29943/42525 [45:35<20:11, 10.39it/s]

 70%|█████████████████████████▎          | 29947/42525 [45:35<19:12, 10.91it/s]

 70%|█████████████████████████▎          | 29949/42525 [45:36<18:45, 11.17it/s]

 70%|█████████████████████████▎          | 29951/42525 [45:36<19:26, 10.78it/s]

 70%|█████████████████████████▎          | 29953/42525 [45:36<19:56, 10.51it/s]

 70%|█████████████████████████▎          | 29957/42525 [45:36<19:37, 10.68it/s]

 70%|█████████████████████████▎          | 29961/42525 [45:37<18:28, 11.33it/s]

 70%|█████████████████████████▎          | 29965/42525 [45:37<17:53, 11.70it/s]

 70%|█████████████████████████▎          | 29969/42525 [45:37<17:55, 11.68it/s]

 70%|█████████████████████████▎          | 29973/42525 [45:38<18:19, 11.42it/s]

 70%|█████████████████████████▍          | 29975/42525 [45:38<18:15, 11.46it/s]

 70%|█████████████████████████▍          | 29979/42525 [45:38<18:44, 11.15it/s]

 71%|█████████████████████████▍          | 29983/42525 [45:39<18:19, 11.41it/s]

 71%|█████████████████████████▍          | 29987/42525 [45:39<18:57, 11.03it/s]

 71%|█████████████████████████▍          | 29991/42525 [45:39<19:01, 10.98it/s]

 71%|█████████████████████████▍          | 29995/42525 [45:40<17:34, 11.88it/s]

 71%|█████████████████████████▍          | 29999/42525 [45:40<16:36, 12.56it/s]

 71%|█████████████████████████▍          | 30003/42525 [45:40<16:40, 12.52it/s]

 71%|█████████████████████████▍          | 30007/42525 [45:41<16:36, 12.57it/s]

 71%|█████████████████████████▍          | 30011/42525 [45:41<17:43, 11.77it/s]

 71%|█████████████████████████▍          | 30015/42525 [45:41<17:38, 11.82it/s]

 71%|█████████████████████████▍          | 30019/42525 [45:42<17:45, 11.73it/s]

 71%|█████████████████████████▍          | 30023/42525 [45:42<18:01, 11.56it/s]

 71%|█████████████████████████▍          | 30027/42525 [45:42<17:05, 12.18it/s]

 71%|█████████████████████████▍          | 30031/42525 [45:43<16:16, 12.80it/s]

 71%|█████████████████████████▍          | 30033/42525 [45:43<16:20, 12.74it/s]

 71%|█████████████████████████▍          | 30037/42525 [45:43<17:28, 11.91it/s]

 71%|█████████████████████████▍          | 30041/42525 [45:43<16:51, 12.34it/s]

 71%|█████████████████████████▍          | 30045/42525 [45:44<16:28, 12.63it/s]

 71%|█████████████████████████▍          | 30049/42525 [45:44<16:51, 12.33it/s]

 71%|█████████████████████████▍          | 30053/42525 [45:44<17:51, 11.64it/s]

 71%|█████████████████████████▍          | 30057/42525 [45:45<18:35, 11.17it/s]

 71%|█████████████████████████▍          | 30061/42525 [45:45<18:12, 11.41it/s]

 71%|█████████████████████████▍          | 30065/42525 [45:46<18:24, 11.29it/s]

 71%|█████████████████████████▍          | 30067/42525 [45:46<18:21, 11.31it/s]

 71%|█████████████████████████▍          | 30071/42525 [45:46<18:55, 10.97it/s]

 71%|█████████████████████████▍          | 30075/42525 [45:46<18:28, 11.24it/s]

 71%|█████████████████████████▍          | 30079/42525 [45:47<18:12, 11.39it/s]

 71%|█████████████████████████▍          | 30083/42525 [45:47<18:25, 11.25it/s]

 71%|█████████████████████████▍          | 30085/42525 [45:47<18:09, 11.42it/s]

 71%|█████████████████████████▍          | 30089/42525 [45:48<18:35, 11.14it/s]

 71%|█████████████████████████▍          | 30093/42525 [45:48<18:39, 11.11it/s]

 71%|█████████████████████████▍          | 30097/42525 [45:48<18:24, 11.25it/s]

 71%|█████████████████████████▍          | 30101/42525 [45:49<19:01, 10.89it/s]

 71%|█████████████████████████▍          | 30105/42525 [45:49<19:18, 10.72it/s]

 71%|█████████████████████████▍          | 30109/42525 [45:50<18:44, 11.04it/s]

 71%|█████████████████████████▍          | 30113/42525 [45:50<18:12, 11.36it/s]

 71%|█████████████████████████▍          | 30117/42525 [45:50<17:54, 11.54it/s]

 71%|█████████████████████████▍          | 30121/42525 [45:51<17:35, 11.75it/s]

 71%|█████████████████████████▌          | 30125/42525 [45:51<17:40, 11.70it/s]

 71%|█████████████████████████▌          | 30129/42525 [45:51<16:50, 12.27it/s]

 71%|█████████████████████████▌          | 30133/42525 [45:52<16:16, 12.69it/s]

 71%|█████████████████████████▌          | 30137/42525 [45:52<17:17, 11.94it/s]

 71%|█████████████████████████▌          | 30141/42525 [45:52<16:22, 12.61it/s]

 71%|█████████████████████████▌          | 30145/42525 [45:53<17:53, 11.53it/s]

 71%|█████████████████████████▌          | 30149/42525 [45:53<17:48, 11.58it/s]

 71%|█████████████████████████▌          | 30153/42525 [45:53<17:33, 11.75it/s]

 71%|█████████████████████████▌          | 30157/42525 [45:54<17:22, 11.86it/s]

 71%|█████████████████████████▌          | 30161/42525 [45:54<17:23, 11.85it/s]

 71%|█████████████████████████▌          | 30165/42525 [45:54<17:51, 11.54it/s]

 71%|█████████████████████████▌          | 30169/42525 [45:55<17:51, 11.53it/s]

 71%|█████████████████████████▌          | 30173/42525 [45:55<17:38, 11.67it/s]

 71%|█████████████████████████▌          | 30177/42525 [45:55<17:35, 11.70it/s]

 71%|█████████████████████████▌          | 30181/42525 [45:56<18:06, 11.36it/s]

 71%|█████████████████████████▌          | 30185/42525 [45:56<17:38, 11.66it/s]

 71%|█████████████████████████▌          | 30189/42525 [45:56<17:54, 11.48it/s]

 71%|█████████████████████████▌          | 30193/42525 [45:57<18:29, 11.12it/s]

 71%|█████████████████████████▌          | 30197/42525 [45:57<17:48, 11.54it/s]

 71%|█████████████████████████▌          | 30201/42525 [45:57<18:24, 11.16it/s]

 71%|█████████████████████████▌          | 30205/42525 [45:58<17:55, 11.45it/s]

 71%|█████████████████████████▌          | 30209/42525 [45:58<17:46, 11.55it/s]

 71%|█████████████████████████▌          | 30213/42525 [45:58<17:59, 11.41it/s]

 71%|█████████████████████████▌          | 30217/42525 [45:59<18:08, 11.31it/s]

 71%|█████████████████████████▌          | 30221/42525 [45:59<18:15, 11.23it/s]

 71%|█████████████████████████▌          | 30225/42525 [46:00<18:10, 11.28it/s]

 71%|█████████████████████████▌          | 30229/42525 [46:00<18:53, 10.85it/s]

 71%|█████████████████████████▌          | 30233/42525 [46:00<18:26, 11.11it/s]

 71%|█████████████████████████▌          | 30237/42525 [46:01<18:41, 10.95it/s]

 71%|█████████████████████████▌          | 30241/42525 [46:01<19:04, 10.73it/s]

 71%|█████████████████████████▌          | 30245/42525 [46:01<17:58, 11.39it/s]

 71%|█████████████████████████▌          | 30249/42525 [46:02<18:14, 11.22it/s]

 71%|█████████████████████████▌          | 30253/42525 [46:02<17:50, 11.47it/s]

 71%|█████████████████████████▌          | 30257/42525 [46:02<18:02, 11.34it/s]

 71%|█████████████████████████▌          | 30261/42525 [46:03<18:58, 10.78it/s]

 71%|█████████████████████████▌          | 30265/42525 [46:03<18:01, 11.33it/s]

 71%|█████████████████████████▌          | 30269/42525 [46:03<17:21, 11.76it/s]

 71%|█████████████████████████▋          | 30273/42525 [46:04<16:26, 12.42it/s]

 71%|█████████████████████████▋          | 30277/42525 [46:04<16:10, 12.61it/s]

 71%|█████████████████████████▋          | 30279/42525 [46:04<15:43, 12.98it/s]

 71%|█████████████████████████▋          | 30283/42525 [46:05<16:55, 12.06it/s]

 71%|█████████████████████████▋          | 30287/42525 [46:05<16:17, 12.52it/s]

 71%|█████████████████████████▋          | 30291/42525 [46:05<16:55, 12.05it/s]

 71%|█████████████████████████▋          | 30295/42525 [46:06<16:55, 12.05it/s]

 71%|█████████████████████████▋          | 30299/42525 [46:06<16:38, 12.24it/s]

 71%|█████████████████████████▋          | 30301/42525 [46:06<16:33, 12.31it/s]

 71%|█████████████████████████▋          | 30305/42525 [46:06<17:07, 11.90it/s]

 71%|█████████████████████████▋          | 30309/42525 [46:07<16:19, 12.47it/s]

 71%|█████████████████████████▋          | 30313/42525 [46:07<16:45, 12.15it/s]

 71%|█████████████████████████▋          | 30317/42525 [46:07<17:57, 11.33it/s]

 71%|█████████████████████████▋          | 30319/42525 [46:08<17:47, 11.43it/s]

 71%|█████████████████████████▋          | 30323/42525 [46:08<18:20, 11.08it/s]

 71%|█████████████████████████▋          | 30327/42525 [46:08<18:19, 11.09it/s]

 71%|█████████████████████████▋          | 30331/42525 [46:09<18:07, 11.21it/s]

 71%|█████████████████████████▋          | 30335/42525 [46:09<18:03, 11.25it/s]

 71%|█████████████████████████▋          | 30339/42525 [46:09<17:40, 11.49it/s]

 71%|█████████████████████████▋          | 30343/42525 [46:10<17:33, 11.57it/s]

 71%|█████████████████████████▋          | 30347/42525 [46:10<18:15, 11.12it/s]

 71%|█████████████████████████▋          | 30351/42525 [46:10<18:04, 11.22it/s]

 71%|█████████████████████████▋          | 30355/42525 [46:11<17:40, 11.48it/s]

 71%|█████████████████████████▋          | 30359/42525 [46:11<18:18, 11.07it/s]

 71%|█████████████████████████▋          | 30363/42525 [46:11<17:22, 11.67it/s]

 71%|█████████████████████████▋          | 30367/42525 [46:12<17:41, 11.45it/s]

 71%|█████████████████████████▋          | 30371/42525 [46:12<17:30, 11.57it/s]

 71%|█████████████████████████▋          | 30375/42525 [46:12<16:45, 12.09it/s]

 71%|█████████████████████████▋          | 30379/42525 [46:13<16:06, 12.56it/s]

 71%|█████████████████████████▋          | 30383/42525 [46:13<17:00, 11.90it/s]

 71%|█████████████████████████▋          | 30387/42525 [46:13<17:09, 11.79it/s]

 71%|█████████████████████████▋          | 30389/42525 [46:14<17:15, 11.72it/s]

 71%|█████████████████████████▋          | 30393/42525 [46:14<18:31, 10.91it/s]

 71%|█████████████████████████▋          | 30397/42525 [46:14<18:11, 11.11it/s]

 71%|█████████████████████████▋          | 30401/42525 [46:15<18:36, 10.86it/s]

 71%|█████████████████████████▋          | 30405/42525 [46:15<18:18, 11.03it/s]

 72%|█████████████████████████▋          | 30409/42525 [46:16<18:05, 11.16it/s]

 72%|█████████████████████████▋          | 30411/42525 [46:16<17:54, 11.27it/s]

 72%|█████████████████████████▋          | 30415/42525 [46:16<18:42, 10.79it/s]

 72%|█████████████████████████▊          | 30419/42525 [46:16<18:28, 10.92it/s]

 72%|█████████████████████████▊          | 30423/42525 [46:17<18:39, 10.81it/s]

 72%|█████████████████████████▊          | 30427/42525 [46:17<17:46, 11.34it/s]

 72%|█████████████████████████▊          | 30431/42525 [46:17<17:36, 11.44it/s]

 72%|█████████████████████████▊          | 30433/42525 [46:18<18:04, 11.15it/s]

 72%|█████████████████████████▊          | 30437/42525 [46:18<19:23, 10.39it/s]

 72%|█████████████████████████▊          | 30441/42525 [46:18<18:50, 10.69it/s]

 72%|█████████████████████████▊          | 30445/42525 [46:19<18:45, 10.74it/s]

 72%|█████████████████████████▊          | 30449/42525 [46:19<18:31, 10.87it/s]

 72%|█████████████████████████▊          | 30453/42525 [46:20<18:41, 10.77it/s]

 72%|█████████████████████████▊          | 30457/42525 [46:20<17:36, 11.43it/s]

 72%|█████████████████████████▊          | 30461/42525 [46:20<16:35, 12.12it/s]

 72%|█████████████████████████▊          | 30465/42525 [46:21<17:25, 11.54it/s]

 72%|█████████████████████████▊          | 30469/42525 [46:21<16:57, 11.84it/s]

 72%|█████████████████████████▊          | 30473/42525 [46:21<16:06, 12.48it/s]

 72%|█████████████████████████▊          | 30477/42525 [46:22<16:36, 12.09it/s]

 72%|█████████████████████████▊          | 30481/42525 [46:22<16:58, 11.83it/s]

 72%|█████████████████████████▊          | 30485/42525 [46:22<17:17, 11.61it/s]

 72%|█████████████████████████▊          | 30489/42525 [46:23<17:01, 11.78it/s]

 72%|█████████████████████████▊          | 30493/42525 [46:23<15:40, 12.80it/s]

 72%|█████████████████████████▊          | 30497/42525 [46:23<16:01, 12.52it/s]

 72%|█████████████████████████▊          | 30501/42525 [46:24<15:43, 12.75it/s]

 72%|█████████████████████████▊          | 30505/42525 [46:24<16:08, 12.41it/s]

 72%|█████████████████████████▊          | 30509/42525 [46:24<16:24, 12.21it/s]

 72%|█████████████████████████▊          | 30513/42525 [46:24<16:21, 12.24it/s]

 72%|█████████████████████████▊          | 30517/42525 [46:25<16:25, 12.19it/s]

 72%|█████████████████████████▊          | 30521/42525 [46:25<15:42, 12.73it/s]

 72%|█████████████████████████▊          | 30525/42525 [46:26<16:59, 11.77it/s]

 72%|█████████████████████████▊          | 30529/42525 [46:26<16:58, 11.78it/s]

 72%|█████████████████████████▊          | 30531/42525 [46:26<16:43, 11.95it/s]

 72%|█████████████████████████▊          | 30535/42525 [46:26<17:21, 11.51it/s]

 72%|█████████████████████████▊          | 30539/42525 [46:27<17:58, 11.11it/s]

 72%|█████████████████████████▊          | 30543/42525 [46:27<17:43, 11.27it/s]

 72%|█████████████████████████▊          | 30547/42525 [46:27<16:31, 12.08it/s]

 72%|█████████████████████████▊          | 30549/42525 [46:28<16:19, 12.23it/s]

 72%|█████████████████████████▊          | 30553/42525 [46:28<17:40, 11.29it/s]

 72%|█████████████████████████▊          | 30557/42525 [46:28<16:54, 11.79it/s]

 72%|█████████████████████████▊          | 30561/42525 [46:29<17:06, 11.66it/s]

 72%|█████████████████████████▉          | 30565/42525 [46:29<17:07, 11.64it/s]

 72%|█████████████████████████▉          | 30569/42525 [46:29<16:26, 12.13it/s]

 72%|█████████████████████████▉          | 30573/42525 [46:30<16:48, 11.85it/s]

 72%|█████████████████████████▉          | 30577/42525 [46:30<16:57, 11.75it/s]

 72%|█████████████████████████▉          | 30581/42525 [46:30<15:40, 12.69it/s]

 72%|█████████████████████████▉          | 30585/42525 [46:31<16:18, 12.21it/s]

 72%|█████████████████████████▉          | 30589/42525 [46:31<16:51, 11.80it/s]

 72%|█████████████████████████▉          | 30593/42525 [46:31<16:10, 12.29it/s]

 72%|█████████████████████████▉          | 30597/42525 [46:32<16:01, 12.40it/s]

 72%|█████████████████████████▉          | 30601/42525 [46:32<17:00, 11.68it/s]

 72%|█████████████████████████▉          | 30605/42525 [46:32<17:14, 11.52it/s]

 72%|█████████████████████████▉          | 30609/42525 [46:33<17:10, 11.56it/s]

 72%|█████████████████████████▉          | 30613/42525 [46:33<16:46, 11.84it/s]

 72%|█████████████████████████▉          | 30617/42525 [46:33<15:54, 12.48it/s]

 72%|█████████████████████████▉          | 30621/42525 [46:34<16:09, 12.28it/s]

 72%|█████████████████████████▉          | 30625/42525 [46:34<15:55, 12.46it/s]

 72%|█████████████████████████▉          | 30629/42525 [46:34<15:28, 12.81it/s]

 72%|█████████████████████████▉          | 30633/42525 [46:35<15:49, 12.52it/s]

 72%|█████████████████████████▉          | 30637/42525 [46:35<16:10, 12.25it/s]

 72%|█████████████████████████▉          | 30641/42525 [46:35<17:00, 11.64it/s]

 72%|█████████████████████████▉          | 30645/42525 [46:36<17:01, 11.63it/s]

 72%|█████████████████████████▉          | 30649/42525 [46:36<17:29, 11.31it/s]

 72%|█████████████████████████▉          | 30653/42525 [46:36<17:27, 11.33it/s]

 72%|█████████████████████████▉          | 30657/42525 [46:37<18:56, 10.44it/s]

 72%|█████████████████████████▉          | 30661/42525 [46:37<18:20, 10.78it/s]

 72%|█████████████████████████▉          | 30665/42525 [46:38<19:01, 10.39it/s]

 72%|█████████████████████████▉          | 30669/42525 [46:38<18:04, 10.93it/s]

 72%|█████████████████████████▉          | 30673/42525 [46:38<17:57, 11.00it/s]

 72%|█████████████████████████▉          | 30677/42525 [46:39<17:39, 11.18it/s]

 72%|█████████████████████████▉          | 30681/42525 [46:39<17:14, 11.45it/s]

 72%|█████████████████████████▉          | 30683/42525 [46:39<17:01, 11.59it/s]

 72%|█████████████████████████▉          | 30687/42525 [46:39<18:27, 10.69it/s]

 72%|█████████████████████████▉          | 30691/42525 [46:40<16:52, 11.69it/s]

 72%|█████████████████████████▉          | 30695/42525 [46:40<16:46, 11.75it/s]

 72%|█████████████████████████▉          | 30699/42525 [46:40<16:36, 11.87it/s]

 72%|█████████████████████████▉          | 30703/42525 [46:41<16:36, 11.87it/s]

 72%|█████████████████████████▉          | 30707/42525 [46:41<16:39, 11.82it/s]

 72%|█████████████████████████▉          | 30711/42525 [46:42<17:27, 11.28it/s]

 72%|██████████████████████████          | 30715/42525 [46:42<17:42, 11.11it/s]

 72%|██████████████████████████          | 30717/42525 [46:42<17:51, 11.02it/s]

 72%|██████████████████████████          | 30721/42525 [46:42<18:26, 10.67it/s]

 72%|██████████████████████████          | 30725/42525 [46:43<17:21, 11.33it/s]

 72%|██████████████████████████          | 30729/42525 [46:43<16:41, 11.78it/s]

 72%|██████████████████████████          | 30733/42525 [46:43<15:11, 12.94it/s]

 72%|██████████████████████████          | 30737/42525 [46:44<14:59, 13.11it/s]

 72%|██████████████████████████          | 30739/42525 [46:44<15:25, 12.73it/s]

 72%|██████████████████████████          | 30743/42525 [46:44<16:33, 11.86it/s]

 72%|██████████████████████████          | 30747/42525 [46:45<17:32, 11.19it/s]

 72%|██████████████████████████          | 30751/42525 [46:45<17:02, 11.52it/s]

 72%|██████████████████████████          | 30755/42525 [46:45<17:25, 11.25it/s]

 72%|██████████████████████████          | 30759/42525 [46:46<18:03, 10.86it/s]

 72%|██████████████████████████          | 30763/42525 [46:46<16:41, 11.74it/s]

 72%|██████████████████████████          | 30767/42525 [46:46<16:19, 12.01it/s]

 72%|██████████████████████████          | 30771/42525 [46:47<17:04, 11.47it/s]

 72%|██████████████████████████          | 30775/42525 [46:47<17:10, 11.40it/s]

 72%|██████████████████████████          | 30779/42525 [46:47<17:13, 11.36it/s]

 72%|██████████████████████████          | 30783/42525 [46:48<16:15, 12.04it/s]

 72%|██████████████████████████          | 30787/42525 [46:48<16:31, 11.84it/s]

 72%|██████████████████████████          | 30791/42525 [46:48<15:30, 12.61it/s]

 72%|██████████████████████████          | 30795/42525 [46:49<15:50, 12.34it/s]

 72%|██████████████████████████          | 30799/42525 [46:49<16:55, 11.54it/s]

 72%|██████████████████████████          | 30803/42525 [46:49<17:41, 11.04it/s]

 72%|██████████████████████████          | 30807/42525 [46:50<16:41, 11.70it/s]

 72%|██████████████████████████          | 30811/42525 [46:50<15:47, 12.37it/s]

 72%|██████████████████████████          | 30815/42525 [46:50<15:20, 12.72it/s]

 72%|██████████████████████████          | 30819/42525 [46:51<16:11, 12.04it/s]

 72%|██████████████████████████          | 30823/42525 [46:51<17:20, 11.24it/s]

 72%|██████████████████████████          | 30827/42525 [46:51<16:14, 12.00it/s]

 73%|██████████████████████████          | 30831/42525 [46:52<16:11, 12.04it/s]

 73%|██████████████████████████          | 30835/42525 [46:52<15:16, 12.75it/s]

 73%|██████████████████████████          | 30839/42525 [46:52<14:49, 13.13it/s]

 73%|██████████████████████████          | 30841/42525 [46:53<15:19, 12.71it/s]

 73%|██████████████████████████          | 30845/42525 [46:53<16:16, 11.96it/s]

 73%|██████████████████████████          | 30849/42525 [46:53<15:21, 12.67it/s]

 73%|██████████████████████████          | 30853/42525 [46:54<15:58, 12.18it/s]

 73%|██████████████████████████          | 30857/42525 [46:54<15:31, 12.53it/s]

 73%|██████████████████████████▏         | 30861/42525 [46:54<14:39, 13.27it/s]

 73%|██████████████████████████▏         | 30865/42525 [46:54<15:57, 12.17it/s]

 73%|██████████████████████████▏         | 30869/42525 [46:55<16:36, 11.70it/s]

 73%|██████████████████████████▏         | 30873/42525 [46:55<16:19, 11.90it/s]

 73%|██████████████████████████▏         | 30875/42525 [46:55<17:03, 11.38it/s]

 73%|██████████████████████████▏         | 30879/42525 [46:56<16:35, 11.69it/s]

 73%|██████████████████████████▏         | 30883/42525 [46:56<15:15, 12.71it/s]

 73%|██████████████████████████▏         | 30887/42525 [46:56<15:02, 12.89it/s]

 73%|██████████████████████████▏         | 30891/42525 [46:57<15:04, 12.86it/s]

 73%|██████████████████████████▏         | 30895/42525 [46:57<14:24, 13.45it/s]

 73%|██████████████████████████▏         | 30899/42525 [46:57<14:20, 13.51it/s]

 73%|██████████████████████████▏         | 30903/42525 [46:57<14:12, 13.63it/s]

 73%|██████████████████████████▏         | 30907/42525 [46:58<15:06, 12.82it/s]

 73%|██████████████████████████▏         | 30911/42525 [46:58<15:09, 12.77it/s]

 73%|██████████████████████████▏         | 30915/42525 [46:58<14:32, 13.31it/s]

 73%|██████████████████████████▏         | 30919/42525 [46:59<15:41, 12.33it/s]

 73%|██████████████████████████▏         | 30923/42525 [46:59<16:39, 11.61it/s]

 73%|██████████████████████████▏         | 30927/42525 [46:59<17:36, 10.98it/s]

 73%|██████████████████████████▏         | 30931/42525 [47:00<16:52, 11.45it/s]

 73%|██████████████████████████▏         | 30935/42525 [47:00<15:59, 12.08it/s]

 73%|██████████████████████████▏         | 30939/42525 [47:00<15:01, 12.85it/s]

 73%|██████████████████████████▏         | 30943/42525 [47:01<15:52, 12.16it/s]

 73%|██████████████████████████▏         | 30947/42525 [47:01<15:23, 12.54it/s]

 73%|██████████████████████████▏         | 30951/42525 [47:01<15:49, 12.19it/s]

 73%|██████████████████████████▏         | 30955/42525 [47:02<15:20, 12.57it/s]

 73%|██████████████████████████▏         | 30959/42525 [47:02<16:14, 11.87it/s]

 73%|██████████████████████████▏         | 30963/42525 [47:02<15:26, 12.49it/s]

 73%|██████████████████████████▏         | 30967/42525 [47:03<15:52, 12.14it/s]

 73%|██████████████████████████▏         | 30971/42525 [47:03<15:25, 12.48it/s]

 73%|██████████████████████████▏         | 30975/42525 [47:03<15:52, 12.12it/s]

 73%|██████████████████████████▏         | 30979/42525 [47:04<15:53, 12.11it/s]

 73%|██████████████████████████▏         | 30983/42525 [47:04<16:25, 11.71it/s]

 73%|██████████████████████████▏         | 30987/42525 [47:04<16:44, 11.48it/s]

 73%|██████████████████████████▏         | 30991/42525 [47:05<17:39, 10.89it/s]

 73%|██████████████████████████▏         | 30995/42525 [47:05<18:02, 10.65it/s]

 73%|██████████████████████████▏         | 30999/42525 [47:05<17:13, 11.15it/s]

 73%|██████████████████████████▏         | 31003/42525 [47:06<16:42, 11.50it/s]

 73%|██████████████████████████▏         | 31007/42525 [47:06<16:07, 11.91it/s]

 73%|██████████████████████████▎         | 31011/42525 [47:06<16:06, 11.91it/s]

 73%|██████████████████████████▎         | 31015/42525 [47:07<15:47, 12.15it/s]

 73%|██████████████████████████▎         | 31019/42525 [47:07<16:42, 11.48it/s]

 73%|██████████████████████████▎         | 31023/42525 [47:08<16:48, 11.40it/s]

 73%|██████████████████████████▎         | 31025/42525 [47:08<16:21, 11.72it/s]

 73%|██████████████████████████▎         | 31029/42525 [47:08<16:33, 11.57it/s]

 73%|██████████████████████████▎         | 31033/42525 [47:08<15:35, 12.28it/s]

 73%|██████████████████████████▎         | 31037/42525 [47:09<15:12, 12.58it/s]

 73%|██████████████████████████▎         | 31041/42525 [47:09<15:49, 12.10it/s]

 73%|██████████████████████████▎         | 31045/42525 [47:09<16:18, 11.73it/s]

 73%|██████████████████████████▎         | 31049/42525 [47:10<15:31, 12.32it/s]

 73%|██████████████████████████▎         | 31053/42525 [47:10<15:20, 12.46it/s]

 73%|██████████████████████████▎         | 31057/42525 [47:10<16:38, 11.48it/s]

 73%|██████████████████████████▎         | 31061/42525 [47:11<15:09, 12.61it/s]

 73%|██████████████████████████▎         | 31065/42525 [47:11<15:30, 12.32it/s]

 73%|██████████████████████████▎         | 31069/42525 [47:11<15:13, 12.54it/s]

 73%|██████████████████████████▎         | 31073/42525 [47:12<15:54, 12.00it/s]

 73%|██████████████████████████▎         | 31077/42525 [47:12<15:02, 12.68it/s]

 73%|██████████████████████████▎         | 31081/42525 [47:12<15:30, 12.30it/s]

 73%|██████████████████████████▎         | 31085/42525 [47:13<15:43, 12.13it/s]

 73%|██████████████████████████▎         | 31089/42525 [47:13<16:09, 11.79it/s]

 73%|██████████████████████████▎         | 31093/42525 [47:13<16:50, 11.32it/s]

 73%|██████████████████████████▎         | 31095/42525 [47:13<17:01, 11.19it/s]

 73%|██████████████████████████▎         | 31099/42525 [47:14<17:31, 10.87it/s]

 73%|██████████████████████████▎         | 31103/42525 [47:14<17:06, 11.13it/s]

 73%|██████████████████████████▎         | 31107/42525 [47:15<16:36, 11.46it/s]

 73%|██████████████████████████▎         | 31111/42525 [47:15<17:28, 10.88it/s]

 73%|██████████████████████████▎         | 31115/42525 [47:15<17:21, 10.96it/s]

 73%|██████████████████████████▎         | 31119/42525 [47:16<17:30, 10.86it/s]

 73%|██████████████████████████▎         | 31123/42525 [47:16<16:56, 11.22it/s]

 73%|██████████████████████████▎         | 31127/42525 [47:16<16:24, 11.58it/s]

 73%|██████████████████████████▎         | 31131/42525 [47:17<16:44, 11.34it/s]

 73%|██████████████████████████▎         | 31135/42525 [47:17<16:27, 11.54it/s]

 73%|██████████████████████████▎         | 31139/42525 [47:17<17:47, 10.67it/s]

 73%|██████████████████████████▎         | 31143/42525 [47:18<17:33, 10.81it/s]

 73%|██████████████████████████▎         | 31147/42525 [47:18<16:45, 11.31it/s]

 73%|██████████████████████████▎         | 31151/42525 [47:19<16:49, 11.26it/s]

 73%|██████████████████████████▎         | 31155/42525 [47:19<16:43, 11.33it/s]

 73%|██████████████████████████▍         | 31159/42525 [47:19<15:42, 12.06it/s]

 73%|██████████████████████████▍         | 31163/42525 [47:19<15:12, 12.45it/s]

 73%|██████████████████████████▍         | 31167/42525 [47:20<16:04, 11.77it/s]

 73%|██████████████████████████▍         | 31171/42525 [47:20<15:38, 12.10it/s]

 73%|██████████████████████████▍         | 31175/42525 [47:20<15:27, 12.24it/s]

 73%|██████████████████████████▍         | 31179/42525 [47:21<14:37, 12.93it/s]

 73%|██████████████████████████▍         | 31183/42525 [47:21<14:24, 13.12it/s]

 73%|██████████████████████████▍         | 31187/42525 [47:21<14:31, 13.01it/s]

 73%|██████████████████████████▍         | 31191/42525 [47:22<15:50, 11.92it/s]

 73%|██████████████████████████▍         | 31195/42525 [47:22<15:06, 12.50it/s]

 73%|██████████████████████████▍         | 31199/42525 [47:22<15:08, 12.46it/s]

 73%|██████████████████████████▍         | 31203/42525 [47:23<14:56, 12.63it/s]

 73%|██████████████████████████▍         | 31207/42525 [47:23<14:53, 12.66it/s]

 73%|██████████████████████████▍         | 31211/42525 [47:23<15:52, 11.88it/s]

 73%|██████████████████████████▍         | 31215/42525 [47:24<16:08, 11.67it/s]

 73%|██████████████████████████▍         | 31219/42525 [47:24<15:46, 11.94it/s]

 73%|██████████████████████████▍         | 31223/42525 [47:24<15:46, 11.94it/s]

 73%|██████████████████████████▍         | 31225/42525 [47:25<16:08, 11.66it/s]

 73%|██████████████████████████▍         | 31229/42525 [47:25<17:33, 10.72it/s]

 73%|██████████████████████████▍         | 31233/42525 [47:25<17:02, 11.05it/s]

 73%|██████████████████████████▍         | 31237/42525 [47:26<16:45, 11.22it/s]

 73%|██████████████████████████▍         | 31241/42525 [47:26<16:53, 11.14it/s]

 73%|██████████████████████████▍         | 31245/42525 [47:26<16:53, 11.13it/s]

 73%|██████████████████████████▍         | 31249/42525 [47:27<16:52, 11.14it/s]

 73%|██████████████████████████▍         | 31253/42525 [47:27<16:47, 11.18it/s]

 74%|██████████████████████████▍         | 31257/42525 [47:27<16:18, 11.51it/s]

 74%|██████████████████████████▍         | 31261/42525 [47:28<16:38, 11.28it/s]

 74%|██████████████████████████▍         | 31265/42525 [47:28<16:51, 11.14it/s]

 74%|██████████████████████████▍         | 31269/42525 [47:29<16:41, 11.24it/s]

 74%|██████████████████████████▍         | 31273/42525 [47:29<16:39, 11.26it/s]

 74%|██████████████████████████▍         | 31277/42525 [47:29<17:26, 10.74it/s]

 74%|██████████████████████████▍         | 31281/42525 [47:30<16:55, 11.07it/s]

 74%|██████████████████████████▍         | 31285/42525 [47:30<16:43, 11.20it/s]

 74%|██████████████████████████▍         | 31287/42525 [47:30<16:27, 11.38it/s]

 74%|██████████████████████████▍         | 31291/42525 [47:31<16:49, 11.12it/s]

 74%|██████████████████████████▍         | 31295/42525 [47:31<16:33, 11.31it/s]

 74%|██████████████████████████▍         | 31299/42525 [47:31<16:35, 11.27it/s]

 74%|██████████████████████████▍         | 31303/42525 [47:32<16:14, 11.52it/s]

 74%|██████████████████████████▌         | 31307/42525 [47:32<16:08, 11.59it/s]

 74%|██████████████████████████▌         | 31311/42525 [47:32<16:28, 11.35it/s]

 74%|██████████████████████████▌         | 31315/42525 [47:33<16:03, 11.64it/s]

 74%|██████████████████████████▌         | 31319/42525 [47:33<16:13, 11.51it/s]

 74%|██████████████████████████▌         | 31323/42525 [47:33<16:00, 11.67it/s]

 74%|██████████████████████████▌         | 31327/42525 [47:34<16:20, 11.42it/s]

 74%|██████████████████████████▌         | 31331/42525 [47:34<16:16, 11.47it/s]

 74%|██████████████████████████▌         | 31335/42525 [47:34<15:29, 12.04it/s]

 74%|██████████████████████████▌         | 31339/42525 [47:35<16:14, 11.48it/s]

 74%|██████████████████████████▌         | 31343/42525 [47:35<16:21, 11.39it/s]

 74%|██████████████████████████▌         | 31347/42525 [47:35<16:13, 11.48it/s]

 74%|██████████████████████████▌         | 31351/42525 [47:36<16:03, 11.60it/s]

 74%|██████████████████████████▌         | 31355/42525 [47:36<16:33, 11.25it/s]

 74%|██████████████████████████▌         | 31359/42525 [47:36<16:12, 11.49it/s]

 74%|██████████████████████████▌         | 31363/42525 [47:37<15:59, 11.64it/s]

 74%|██████████████████████████▌         | 31367/42525 [47:37<16:10, 11.49it/s]

 74%|██████████████████████████▌         | 31371/42525 [47:37<16:45, 11.09it/s]

 74%|██████████████████████████▌         | 31375/42525 [47:38<16:19, 11.38it/s]

 74%|██████████████████████████▌         | 31379/42525 [47:38<16:02, 11.58it/s]

 74%|██████████████████████████▌         | 31383/42525 [47:39<16:14, 11.43it/s]

 74%|██████████████████████████▌         | 31387/42525 [47:39<16:17, 11.40it/s]

 74%|██████████████████████████▌         | 31391/42525 [47:39<15:55, 11.65it/s]

 74%|██████████████████████████▌         | 31395/42525 [47:40<16:26, 11.28it/s]

 74%|██████████████████████████▌         | 31399/42525 [47:40<16:08, 11.48it/s]

 74%|██████████████████████████▌         | 31403/42525 [47:40<16:33, 11.19it/s]

 74%|██████████████████████████▌         | 31405/42525 [47:40<17:18, 10.70it/s]

 74%|██████████████████████████▌         | 31409/42525 [47:41<17:51, 10.37it/s]

 74%|██████████████████████████▌         | 31413/42525 [47:41<17:23, 10.65it/s]

 74%|██████████████████████████▌         | 31417/42525 [47:42<17:35, 10.52it/s]

 74%|██████████████████████████▌         | 31421/42525 [47:42<17:33, 10.54it/s]

 74%|██████████████████████████▌         | 31425/42525 [47:42<16:31, 11.19it/s]

 74%|██████████████████████████▌         | 31429/42525 [47:43<15:54, 11.62it/s]

 74%|██████████████████████████▌         | 31433/42525 [47:43<16:48, 11.00it/s]

 74%|██████████████████████████▌         | 31437/42525 [47:43<16:08, 11.45it/s]

 74%|██████████████████████████▌         | 31441/42525 [47:44<16:28, 11.21it/s]

 74%|██████████████████████████▌         | 31445/42525 [47:44<17:24, 10.61it/s]

 74%|██████████████████████████▌         | 31449/42525 [47:45<16:55, 10.90it/s]

 74%|██████████████████████████▋         | 31451/42525 [47:45<16:33, 11.15it/s]

 74%|██████████████████████████▋         | 31455/42525 [47:45<17:25, 10.59it/s]

 74%|██████████████████████████▋         | 31459/42525 [47:45<16:55, 10.90it/s]

 74%|██████████████████████████▋         | 31463/42525 [47:46<15:58, 11.54it/s]

 74%|██████████████████████████▋         | 31467/42525 [47:46<16:04, 11.47it/s]

 74%|██████████████████████████▋         | 31471/42525 [47:46<15:48, 11.65it/s]

 74%|██████████████████████████▋         | 31475/42525 [47:47<16:32, 11.14it/s]

 74%|██████████████████████████▋         | 31479/42525 [47:47<16:42, 11.01it/s]

 74%|██████████████████████████▋         | 31483/42525 [47:48<16:42, 11.02it/s]

 74%|██████████████████████████▋         | 31487/42525 [47:48<16:10, 11.37it/s]

 74%|██████████████████████████▋         | 31491/42525 [47:48<16:06, 11.42it/s]

 74%|██████████████████████████▋         | 31495/42525 [47:49<15:49, 11.62it/s]

 74%|██████████████████████████▋         | 31499/42525 [47:49<16:16, 11.29it/s]

 74%|██████████████████████████▋         | 31503/42525 [47:49<16:20, 11.24it/s]

 74%|██████████████████████████▋         | 31507/42525 [47:50<15:54, 11.54it/s]

 74%|██████████████████████████▋         | 31511/42525 [47:50<15:20, 11.97it/s]

 74%|██████████████████████████▋         | 31515/42525 [47:50<15:44, 11.66it/s]

 74%|██████████████████████████▋         | 31519/42525 [47:51<15:29, 11.84it/s]

 74%|██████████████████████████▋         | 31523/42525 [47:51<14:39, 12.51it/s]

 74%|██████████████████████████▋         | 31527/42525 [47:51<15:09, 12.09it/s]

 74%|██████████████████████████▋         | 31531/42525 [47:52<14:50, 12.35it/s]

 74%|██████████████████████████▋         | 31535/42525 [47:52<15:21, 11.92it/s]

 74%|██████████████████████████▋         | 31539/42525 [47:52<15:08, 12.09it/s]

 74%|██████████████████████████▋         | 31543/42525 [47:53<15:12, 12.03it/s]

 74%|██████████████████████████▋         | 31547/42525 [47:53<15:28, 11.82it/s]

 74%|██████████████████████████▋         | 31551/42525 [47:53<16:28, 11.10it/s]

 74%|██████████████████████████▋         | 31555/42525 [47:54<16:43, 10.93it/s]

 74%|██████████████████████████▋         | 31559/42525 [47:54<16:04, 11.37it/s]

 74%|██████████████████████████▋         | 31563/42525 [47:54<15:46, 11.59it/s]

 74%|██████████████████████████▋         | 31567/42525 [47:55<16:20, 11.18it/s]

 74%|██████████████████████████▋         | 31571/42525 [47:55<17:08, 10.65it/s]

 74%|██████████████████████████▋         | 31575/42525 [47:55<16:19, 11.18it/s]

 74%|██████████████████████████▋         | 31579/42525 [47:56<15:45, 11.58it/s]

 74%|██████████████████████████▋         | 31583/42525 [47:56<15:33, 11.73it/s]

 74%|██████████████████████████▋         | 31587/42525 [47:57<15:39, 11.64it/s]

 74%|██████████████████████████▋         | 31591/42525 [47:57<15:47, 11.54it/s]

 74%|██████████████████████████▋         | 31595/42525 [47:57<15:34, 11.69it/s]

 74%|██████████████████████████▊         | 31599/42525 [47:58<15:41, 11.60it/s]

 74%|██████████████████████████▊         | 31603/42525 [47:58<16:07, 11.29it/s]

 74%|██████████████████████████▊         | 31607/42525 [47:58<16:09, 11.26it/s]

 74%|██████████████████████████▊         | 31611/42525 [47:59<15:11, 11.98it/s]

 74%|██████████████████████████▊         | 31615/42525 [47:59<14:50, 12.25it/s]

 74%|██████████████████████████▊         | 31619/42525 [47:59<15:02, 12.08it/s]

 74%|██████████████████████████▊         | 31623/42525 [48:00<14:55, 12.17it/s]

 74%|██████████████████████████▊         | 31625/42525 [48:00<15:54, 11.42it/s]

 74%|██████████████████████████▊         | 31629/42525 [48:00<15:49, 11.48it/s]

 74%|██████████████████████████▊         | 31633/42525 [48:00<14:54, 12.17it/s]

 74%|██████████████████████████▊         | 31637/42525 [48:01<15:16, 11.87it/s]

 74%|██████████████████████████▊         | 31641/42525 [48:01<14:50, 12.22it/s]

 74%|██████████████████████████▊         | 31645/42525 [48:01<15:23, 11.78it/s]

 74%|██████████████████████████▊         | 31649/42525 [48:02<15:30, 11.69it/s]

 74%|██████████████████████████▊         | 31653/42525 [48:02<15:56, 11.37it/s]

 74%|██████████████████████████▊         | 31657/42525 [48:03<16:09, 11.21it/s]

 74%|██████████████████████████▊         | 31661/42525 [48:03<15:53, 11.39it/s]

 74%|██████████████████████████▊         | 31665/42525 [48:03<16:18, 11.10it/s]

 74%|██████████████████████████▊         | 31669/42525 [48:04<16:19, 11.09it/s]

 74%|██████████████████████████▊         | 31673/42525 [48:04<16:35, 10.90it/s]

 74%|██████████████████████████▊         | 31677/42525 [48:04<16:39, 10.85it/s]

 74%|██████████████████████████▊         | 31681/42525 [48:05<16:28, 10.97it/s]

 75%|██████████████████████████▊         | 31685/42525 [48:05<16:15, 11.11it/s]

 75%|██████████████████████████▊         | 31689/42525 [48:05<15:55, 11.34it/s]

 75%|██████████████████████████▊         | 31693/42525 [48:06<15:38, 11.54it/s]

 75%|██████████████████████████▊         | 31697/42525 [48:06<16:19, 11.05it/s]

 75%|██████████████████████████▊         | 31701/42525 [48:06<15:38, 11.53it/s]

 75%|██████████████████████████▊         | 31705/42525 [48:07<15:02, 11.98it/s]

 75%|██████████████████████████▊         | 31709/42525 [48:07<15:54, 11.33it/s]

 75%|██████████████████████████▊         | 31713/42525 [48:08<17:12, 10.47it/s]

 75%|██████████████████████████▊         | 31717/42525 [48:08<16:19, 11.04it/s]

 75%|██████████████████████████▊         | 31721/42525 [48:08<15:47, 11.41it/s]

 75%|██████████████████████████▊         | 31725/42525 [48:09<15:45, 11.42it/s]

 75%|██████████████████████████▊         | 31729/42525 [48:09<16:32, 10.88it/s]

 75%|██████████████████████████▊         | 31733/42525 [48:09<16:08, 11.14it/s]

 75%|██████████████████████████▊         | 31737/42525 [48:10<15:13, 11.80it/s]

 75%|██████████████████████████▊         | 31741/42525 [48:10<14:44, 12.19it/s]

 75%|██████████████████████████▊         | 31745/42525 [48:10<13:50, 12.99it/s]

 75%|██████████████████████████▉         | 31749/42525 [48:11<13:49, 12.99it/s]

 75%|██████████████████████████▉         | 31753/42525 [48:11<15:13, 11.80it/s]

 75%|██████████████████████████▉         | 31757/42525 [48:11<16:14, 11.05it/s]

 75%|██████████████████████████▉         | 31761/42525 [48:12<16:13, 11.06it/s]

 75%|██████████████████████████▉         | 31765/42525 [48:12<15:33, 11.53it/s]

 75%|██████████████████████████▉         | 31769/42525 [48:12<15:07, 11.85it/s]

 75%|██████████████████████████▉         | 31773/42525 [48:13<15:36, 11.48it/s]

 75%|██████████████████████████▉         | 31777/42525 [48:13<15:26, 11.60it/s]

 75%|██████████████████████████▉         | 31781/42525 [48:13<15:18, 11.70it/s]

 75%|██████████████████████████▉         | 31785/42525 [48:14<15:56, 11.23it/s]

 75%|██████████████████████████▉         | 31789/42525 [48:14<15:40, 11.41it/s]

 75%|██████████████████████████▉         | 31791/42525 [48:14<15:43, 11.38it/s]

 75%|██████████████████████████▉         | 31795/42525 [48:15<16:16, 10.99it/s]

 75%|██████████████████████████▉         | 31799/42525 [48:15<16:30, 10.83it/s]

 75%|██████████████████████████▉         | 31803/42525 [48:15<15:44, 11.35it/s]

 75%|██████████████████████████▉         | 31807/42525 [48:16<16:08, 11.06it/s]

 75%|██████████████████████████▉         | 31811/42525 [48:16<16:38, 10.73it/s]

 75%|██████████████████████████▉         | 31815/42525 [48:16<15:59, 11.16it/s]

 75%|██████████████████████████▉         | 31819/42525 [48:17<14:29, 12.32it/s]

 75%|██████████████████████████▉         | 31823/42525 [48:17<13:52, 12.86it/s]

 75%|██████████████████████████▉         | 31827/42525 [48:17<13:43, 12.98it/s]

 75%|██████████████████████████▉         | 31831/42525 [48:18<14:57, 11.91it/s]

 75%|██████████████████████████▉         | 31835/42525 [48:18<14:39, 12.15it/s]

 75%|██████████████████████████▉         | 31839/42525 [48:18<14:31, 12.25it/s]

 75%|██████████████████████████▉         | 31843/42525 [48:19<15:08, 11.76it/s]

 75%|██████████████████████████▉         | 31847/42525 [48:19<14:57, 11.89it/s]

 75%|██████████████████████████▉         | 31851/42525 [48:19<14:41, 12.10it/s]

 75%|██████████████████████████▉         | 31855/42525 [48:20<15:05, 11.79it/s]

 75%|██████████████████████████▉         | 31859/42525 [48:20<16:10, 10.99it/s]

 75%|██████████████████████████▉         | 31863/42525 [48:20<15:59, 11.11it/s]

 75%|██████████████████████████▉         | 31867/42525 [48:21<16:23, 10.83it/s]

 75%|██████████████████████████▉         | 31871/42525 [48:21<16:12, 10.96it/s]

 75%|██████████████████████████▉         | 31875/42525 [48:22<16:10, 10.97it/s]

 75%|██████████████████████████▉         | 31879/42525 [48:22<16:57, 10.47it/s]

 75%|██████████████████████████▉         | 31883/42525 [48:22<16:57, 10.46it/s]

 75%|██████████████████████████▉         | 31887/42525 [48:23<16:23, 10.81it/s]

 75%|██████████████████████████▉         | 31891/42525 [48:23<17:02, 10.40it/s]

 75%|███████████████████████████         | 31895/42525 [48:23<16:48, 10.54it/s]

 75%|███████████████████████████         | 31899/42525 [48:24<16:07, 10.99it/s]

 75%|███████████████████████████         | 31903/42525 [48:24<15:57, 11.10it/s]

 75%|███████████████████████████         | 31907/42525 [48:25<16:10, 10.95it/s]

 75%|███████████████████████████         | 31911/42525 [48:25<16:00, 11.06it/s]

 75%|███████████████████████████         | 31915/42525 [48:25<16:29, 10.72it/s]

 75%|███████████████████████████         | 31919/42525 [48:26<16:34, 10.66it/s]

 75%|███████████████████████████         | 31923/42525 [48:26<16:51, 10.48it/s]

 75%|███████████████████████████         | 31927/42525 [48:26<16:44, 10.55it/s]

 75%|███████████████████████████         | 31931/42525 [48:27<16:38, 10.61it/s]

 75%|███████████████████████████         | 31935/42525 [48:27<15:55, 11.08it/s]

 75%|███████████████████████████         | 31939/42525 [48:28<15:32, 11.36it/s]

 75%|███████████████████████████         | 31943/42525 [48:28<15:46, 11.19it/s]

 75%|███████████████████████████         | 31947/42525 [48:28<16:06, 10.94it/s]

 75%|███████████████████████████         | 31951/42525 [48:29<16:05, 10.95it/s]

 75%|███████████████████████████         | 31955/42525 [48:29<16:48, 10.48it/s]

 75%|███████████████████████████         | 31959/42525 [48:29<16:18, 10.80it/s]

 75%|███████████████████████████         | 31963/42525 [48:30<15:47, 11.15it/s]

 75%|███████████████████████████         | 31967/42525 [48:30<16:00, 10.99it/s]

 75%|███████████████████████████         | 31971/42525 [48:30<15:48, 11.13it/s]

 75%|███████████████████████████         | 31975/42525 [48:31<15:40, 11.22it/s]

 75%|███████████████████████████         | 31979/42525 [48:31<16:20, 10.76it/s]

 75%|███████████████████████████         | 31983/42525 [48:32<15:59, 10.99it/s]

 75%|███████████████████████████         | 31987/42525 [48:32<16:38, 10.56it/s]

 75%|███████████████████████████         | 31991/42525 [48:32<16:23, 10.71it/s]

 75%|███████████████████████████         | 31995/42525 [48:33<16:03, 10.93it/s]

 75%|███████████████████████████         | 31999/42525 [48:33<15:37, 11.23it/s]

 75%|███████████████████████████         | 32003/42525 [48:33<15:32, 11.29it/s]

 75%|███████████████████████████         | 32007/42525 [48:34<15:40, 11.18it/s]

 75%|███████████████████████████         | 32011/42525 [48:34<15:55, 11.00it/s]

 75%|███████████████████████████         | 32015/42525 [48:34<15:34, 11.24it/s]

 75%|███████████████████████████         | 32019/42525 [48:35<15:44, 11.12it/s]

 75%|███████████████████████████         | 32023/42525 [48:35<16:29, 10.62it/s]

 75%|███████████████████████████         | 32027/42525 [48:36<16:02, 10.90it/s]

 75%|███████████████████████████         | 32031/42525 [48:36<15:33, 11.24it/s]

 75%|███████████████████████████         | 32035/42525 [48:36<15:53, 11.00it/s]

 75%|███████████████████████████         | 32037/42525 [48:36<15:46, 11.08it/s]

 75%|███████████████████████████         | 32041/42525 [48:37<16:01, 10.90it/s]

 75%|███████████████████████████▏        | 32045/42525 [48:37<15:53, 10.99it/s]

 75%|███████████████████████████▏        | 32049/42525 [48:38<15:55, 10.97it/s]

 75%|███████████████████████████▏        | 32053/42525 [48:38<15:30, 11.25it/s]

 75%|███████████████████████████▏        | 32057/42525 [48:38<15:26, 11.30it/s]

 75%|███████████████████████████▏        | 32061/42525 [48:39<15:48, 11.03it/s]

 75%|███████████████████████████▏        | 32065/42525 [48:39<15:58, 10.91it/s]

 75%|███████████████████████████▏        | 32067/42525 [48:39<16:21, 10.65it/s]

 75%|███████████████████████████▏        | 32071/42525 [48:40<16:25, 10.61it/s]

 75%|███████████████████████████▏        | 32075/42525 [48:40<15:41, 11.09it/s]

 75%|███████████████████████████▏        | 32079/42525 [48:40<15:22, 11.32it/s]

 75%|███████████████████████████▏        | 32083/42525 [48:41<15:37, 11.14it/s]

 75%|███████████████████████████▏        | 32085/42525 [48:41<15:25, 11.28it/s]

 75%|███████████████████████████▏        | 32089/42525 [48:41<15:58, 10.89it/s]

 75%|███████████████████████████▏        | 32093/42525 [48:42<16:13, 10.71it/s]

 75%|███████████████████████████▏        | 32097/42525 [48:42<16:28, 10.55it/s]

 75%|███████████████████████████▏        | 32101/42525 [48:42<16:11, 10.73it/s]

 75%|███████████████████████████▏        | 32105/42525 [48:43<15:34, 11.15it/s]

 76%|███████████████████████████▏        | 32109/42525 [48:43<15:11, 11.43it/s]

 76%|███████████████████████████▏        | 32113/42525 [48:43<15:07, 11.48it/s]

 76%|███████████████████████████▏        | 32117/42525 [48:44<15:38, 11.09it/s]

 76%|███████████████████████████▏        | 32121/42525 [48:44<15:51, 10.93it/s]

 76%|███████████████████████████▏        | 32125/42525 [48:44<15:56, 10.88it/s]

 76%|███████████████████████████▏        | 32129/42525 [48:45<15:21, 11.28it/s]

 76%|███████████████████████████▏        | 32133/42525 [48:45<15:10, 11.42it/s]

 76%|███████████████████████████▏        | 32137/42525 [48:46<15:40, 11.05it/s]

 76%|███████████████████████████▏        | 32141/42525 [48:46<15:46, 10.98it/s]

 76%|███████████████████████████▏        | 32145/42525 [48:46<15:54, 10.87it/s]

 76%|███████████████████████████▏        | 32147/42525 [48:46<15:20, 11.27it/s]

 76%|███████████████████████████▏        | 32151/42525 [48:47<15:04, 11.47it/s]

 76%|███████████████████████████▏        | 32155/42525 [48:47<15:30, 11.15it/s]

 76%|███████████████████████████▏        | 32159/42525 [48:47<14:24, 11.99it/s]

 76%|███████████████████████████▏        | 32161/42525 [48:48<14:40, 11.77it/s]

 76%|███████████████████████████▏        | 32165/42525 [48:48<15:23, 11.22it/s]

 76%|███████████████████████████▏        | 32169/42525 [48:48<14:26, 11.95it/s]

 76%|███████████████████████████▏        | 32173/42525 [48:49<14:46, 11.67it/s]

 76%|███████████████████████████▏        | 32177/42525 [48:49<13:39, 12.63it/s]

 76%|███████████████████████████▏        | 32181/42525 [48:49<14:33, 11.84it/s]

 76%|███████████████████████████▏        | 32185/42525 [48:50<13:43, 12.56it/s]

 76%|███████████████████████████▏        | 32189/42525 [48:50<13:30, 12.75it/s]

 76%|███████████████████████████▎        | 32193/42525 [48:50<13:41, 12.57it/s]

 76%|███████████████████████████▎        | 32197/42525 [48:51<14:25, 11.93it/s]

 76%|███████████████████████████▎        | 32201/42525 [48:51<14:29, 11.87it/s]

 76%|███████████████████████████▎        | 32205/42525 [48:51<14:16, 12.05it/s]

 76%|███████████████████████████▎        | 32209/42525 [48:52<14:39, 11.73it/s]

 76%|███████████████████████████▎        | 32213/42525 [48:52<14:28, 11.87it/s]

 76%|███████████████████████████▎        | 32217/42525 [48:52<14:55, 11.51it/s]

 76%|███████████████████████████▎        | 32221/42525 [48:53<15:27, 11.11it/s]

 76%|███████████████████████████▎        | 32225/42525 [48:53<15:00, 11.44it/s]

 76%|███████████████████████████▎        | 32229/42525 [48:53<15:27, 11.10it/s]

 76%|███████████████████████████▎        | 32233/42525 [48:54<15:05, 11.36it/s]

 76%|███████████████████████████▎        | 32237/42525 [48:54<15:20, 11.17it/s]

 76%|███████████████████████████▎        | 32241/42525 [48:54<15:04, 11.37it/s]

 76%|███████████████████████████▎        | 32245/42525 [48:55<15:41, 10.92it/s]

 76%|███████████████████████████▎        | 32247/42525 [48:55<16:00, 10.70it/s]

 76%|███████████████████████████▎        | 32251/42525 [48:55<15:53, 10.78it/s]

 76%|███████████████████████████▎        | 32255/42525 [48:56<15:32, 11.01it/s]

 76%|███████████████████████████▎        | 32259/42525 [48:56<15:39, 10.93it/s]

 76%|███████████████████████████▎        | 32263/42525 [48:56<14:57, 11.43it/s]

 76%|███████████████████████████▎        | 32267/42525 [48:57<14:37, 11.69it/s]

 76%|███████████████████████████▎        | 32271/42525 [48:57<15:33, 10.98it/s]

 76%|███████████████████████████▎        | 32275/42525 [48:58<15:24, 11.09it/s]

 76%|███████████████████████████▎        | 32277/42525 [48:58<15:05, 11.32it/s]

 76%|███████████████████████████▎        | 32281/42525 [48:58<15:25, 11.07it/s]

 76%|███████████████████████████▎        | 32285/42525 [48:58<15:13, 11.21it/s]

 76%|███████████████████████████▎        | 32289/42525 [48:59<14:51, 11.48it/s]

 76%|███████████████████████████▎        | 32293/42525 [48:59<14:59, 11.38it/s]

 76%|███████████████████████████▎        | 32297/42525 [48:59<15:05, 11.30it/s]

 76%|███████████████████████████▎        | 32301/42525 [49:00<14:53, 11.45it/s]

 76%|███████████████████████████▎        | 32305/42525 [49:00<15:27, 11.02it/s]

 76%|███████████████████████████▎        | 32309/42525 [49:01<15:24, 11.04it/s]

 76%|███████████████████████████▎        | 32313/42525 [49:01<15:21, 11.08it/s]

 76%|███████████████████████████▎        | 32317/42525 [49:01<15:14, 11.16it/s]

 76%|███████████████████████████▎        | 32321/42525 [49:02<15:52, 10.71it/s]

 76%|███████████████████████████▎        | 32325/42525 [49:02<15:46, 10.78it/s]

 76%|███████████████████████████▎        | 32329/42525 [49:02<15:38, 10.87it/s]

 76%|███████████████████████████▎        | 32333/42525 [49:03<15:05, 11.26it/s]

 76%|███████████████████████████▍        | 32337/42525 [49:03<16:02, 10.59it/s]

 76%|███████████████████████████▍        | 32341/42525 [49:03<15:16, 11.12it/s]

 76%|███████████████████████████▍        | 32345/42525 [49:04<14:47, 11.46it/s]

 76%|███████████████████████████▍        | 32349/42525 [49:04<14:24, 11.77it/s]

 76%|███████████████████████████▍        | 32353/42525 [49:05<14:44, 11.50it/s]

 76%|███████████████████████████▍        | 32357/42525 [49:05<15:15, 11.10it/s]

 76%|███████████████████████████▍        | 32361/42525 [49:05<15:15, 11.10it/s]

 76%|███████████████████████████▍        | 32363/42525 [49:05<15:39, 10.82it/s]

 76%|███████████████████████████▍        | 32367/42525 [49:06<15:58, 10.60it/s]

 76%|███████████████████████████▍        | 32371/42525 [49:06<15:19, 11.04it/s]

 76%|███████████████████████████▍        | 32375/42525 [49:07<14:57, 11.31it/s]

 76%|███████████████████████████▍        | 32379/42525 [49:07<14:40, 11.52it/s]

 76%|███████████████████████████▍        | 32383/42525 [49:07<14:55, 11.32it/s]

 76%|███████████████████████████▍        | 32387/42525 [49:08<14:51, 11.37it/s]

 76%|███████████████████████████▍        | 32391/42525 [49:08<14:50, 11.37it/s]

 76%|███████████████████████████▍        | 32395/42525 [49:08<15:20, 11.01it/s]

 76%|███████████████████████████▍        | 32399/42525 [49:09<15:20, 11.00it/s]

 76%|███████████████████████████▍        | 32403/42525 [49:09<15:13, 11.08it/s]

 76%|███████████████████████████▍        | 32407/42525 [49:09<14:41, 11.47it/s]

 76%|███████████████████████████▍        | 32411/42525 [49:10<14:25, 11.69it/s]

 76%|███████████████████████████▍        | 32415/42525 [49:10<14:33, 11.58it/s]

 76%|███████████████████████████▍        | 32419/42525 [49:10<15:01, 11.21it/s]

 76%|███████████████████████████▍        | 32423/42525 [49:11<14:40, 11.47it/s]

 76%|███████████████████████████▍        | 32427/42525 [49:11<15:29, 10.87it/s]

 76%|███████████████████████████▍        | 32431/42525 [49:12<15:24, 10.91it/s]

 76%|███████████████████████████▍        | 32435/42525 [49:12<15:20, 10.96it/s]

 76%|███████████████████████████▍        | 32439/42525 [49:12<15:15, 11.02it/s]

 76%|███████████████████████████▍        | 32443/42525 [49:13<15:06, 11.12it/s]

 76%|███████████████████████████▍        | 32445/42525 [49:13<14:53, 11.28it/s]

 76%|███████████████████████████▍        | 32449/42525 [49:13<15:19, 10.96it/s]

 76%|███████████████████████████▍        | 32453/42525 [49:14<15:07, 11.10it/s]

 76%|███████████████████████████▍        | 32457/42525 [49:14<14:47, 11.34it/s]

 76%|███████████████████████████▍        | 32461/42525 [49:14<14:54, 11.25it/s]

 76%|███████████████████████████▍        | 32465/42525 [49:15<14:45, 11.36it/s]

 76%|███████████████████████████▍        | 32469/42525 [49:15<14:04, 11.91it/s]

 76%|███████████████████████████▍        | 32473/42525 [49:15<13:49, 12.12it/s]

 76%|███████████████████████████▍        | 32477/42525 [49:16<13:48, 12.13it/s]

 76%|███████████████████████████▍        | 32481/42525 [49:16<13:50, 12.09it/s]

 76%|███████████████████████████▌        | 32485/42525 [49:16<14:32, 11.51it/s]

 76%|███████████████████████████▌        | 32489/42525 [49:17<14:03, 11.90it/s]

 76%|███████████████████████████▌        | 32493/42525 [49:17<13:15, 12.61it/s]

 76%|███████████████████████████▌        | 32497/42525 [49:17<13:33, 12.33it/s]

 76%|███████████████████████████▌        | 32501/42525 [49:18<13:46, 12.13it/s]

 76%|███████████████████████████▌        | 32505/42525 [49:18<13:16, 12.58it/s]

 76%|███████████████████████████▌        | 32509/42525 [49:18<13:28, 12.39it/s]

 76%|███████████████████████████▌        | 32513/42525 [49:18<12:58, 12.86it/s]

 76%|███████████████████████████▌        | 32517/42525 [49:19<14:15, 11.70it/s]

 76%|███████████████████████████▌        | 32521/42525 [49:19<13:30, 12.34it/s]

 76%|███████████████████████████▌        | 32525/42525 [49:19<13:38, 12.22it/s]

 76%|███████████████████████████▌        | 32529/42525 [49:20<14:53, 11.18it/s]

 77%|███████████████████████████▌        | 32533/42525 [49:20<14:38, 11.37it/s]

 77%|███████████████████████████▌        | 32535/42525 [49:20<14:53, 11.18it/s]

 77%|███████████████████████████▌        | 32539/42525 [49:21<15:23, 10.82it/s]

 77%|███████████████████████████▌        | 32543/42525 [49:21<14:56, 11.13it/s]

 77%|███████████████████████████▌        | 32547/42525 [49:22<15:04, 11.03it/s]

 77%|███████████████████████████▌        | 32551/42525 [49:22<15:05, 11.01it/s]

 77%|███████████████████████████▌        | 32555/42525 [49:22<14:48, 11.23it/s]

 77%|███████████████████████████▌        | 32559/42525 [49:23<14:37, 11.36it/s]

 77%|███████████████████████████▌        | 32563/42525 [49:23<14:48, 11.21it/s]

 77%|███████████████████████████▌        | 32567/42525 [49:23<14:24, 11.51it/s]

 77%|███████████████████████████▌        | 32571/42525 [49:24<14:16, 11.63it/s]

 77%|███████████████████████████▌        | 32575/42525 [49:24<15:20, 10.81it/s]

 77%|███████████████████████████▌        | 32579/42525 [49:24<14:42, 11.27it/s]

 77%|███████████████████████████▌        | 32583/42525 [49:25<14:24, 11.50it/s]

 77%|███████████████████████████▌        | 32587/42525 [49:25<14:15, 11.61it/s]

 77%|███████████████████████████▌        | 32591/42525 [49:25<14:07, 11.73it/s]

 77%|███████████████████████████▌        | 32595/42525 [49:26<14:25, 11.47it/s]

 77%|███████████████████████████▌        | 32599/42525 [49:26<14:46, 11.19it/s]

 77%|███████████████████████████▌        | 32603/42525 [49:26<14:59, 11.03it/s]

 77%|███████████████████████████▌        | 32607/42525 [49:27<14:52, 11.11it/s]

 77%|███████████████████████████▌        | 32611/42525 [49:27<14:23, 11.49it/s]

 77%|███████████████████████████▌        | 32615/42525 [49:28<14:31, 11.37it/s]

 77%|███████████████████████████▌        | 32619/42525 [49:28<14:19, 11.52it/s]

 77%|███████████████████████████▌        | 32623/42525 [49:28<14:05, 11.72it/s]

 77%|███████████████████████████▌        | 32627/42525 [49:29<14:23, 11.47it/s]

 77%|███████████████████████████▌        | 32631/42525 [49:29<14:11, 11.62it/s]

 77%|███████████████████████████▋        | 32635/42525 [49:29<14:40, 11.23it/s]

 77%|███████████████████████████▋        | 32639/42525 [49:30<15:13, 10.82it/s]

 77%|███████████████████████████▋        | 32643/42525 [49:30<15:09, 10.87it/s]

 77%|███████████████████████████▋        | 32647/42525 [49:30<15:03, 10.93it/s]

 77%|███████████████████████████▋        | 32651/42525 [49:31<14:50, 11.09it/s]

 77%|███████████████████████████▋        | 32655/42525 [49:31<15:03, 10.92it/s]

 77%|███████████████████████████▋        | 32659/42525 [49:31<15:02, 10.93it/s]

 77%|███████████████████████████▋        | 32663/42525 [49:32<14:49, 11.09it/s]

 77%|███████████████████████████▋        | 32667/42525 [49:32<14:41, 11.19it/s]

 77%|███████████████████████████▋        | 32671/42525 [49:33<14:51, 11.06it/s]

 77%|███████████████████████████▋        | 32675/42525 [49:33<15:20, 10.70it/s]

 77%|███████████████████████████▋        | 32679/42525 [49:33<14:38, 11.21it/s]

 77%|███████████████████████████▋        | 32683/42525 [49:34<14:15, 11.51it/s]

 77%|███████████████████████████▋        | 32687/42525 [49:34<14:04, 11.65it/s]

 77%|███████████████████████████▋        | 32691/42525 [49:34<14:01, 11.68it/s]

 77%|███████████████████████████▋        | 32695/42525 [49:35<14:37, 11.20it/s]

 77%|███████████████████████████▋        | 32699/42525 [49:35<14:26, 11.34it/s]

 77%|███████████████████████████▋        | 32703/42525 [49:35<14:40, 11.16it/s]

 77%|███████████████████████████▋        | 32707/42525 [49:36<14:51, 11.02it/s]

 77%|███████████████████████████▋        | 32711/42525 [49:36<14:26, 11.33it/s]

 77%|███████████████████████████▋        | 32715/42525 [49:36<14:29, 11.28it/s]

 77%|███████████████████████████▋        | 32719/42525 [49:37<14:34, 11.21it/s]

 77%|███████████████████████████▋        | 32723/42525 [49:37<14:22, 11.37it/s]

 77%|███████████████████████████▋        | 32727/42525 [49:37<14:04, 11.61it/s]

 77%|███████████████████████████▋        | 32731/42525 [49:38<14:39, 11.13it/s]

 77%|███████████████████████████▋        | 32735/42525 [49:38<15:15, 10.69it/s]

 77%|███████████████████████████▋        | 32739/42525 [49:39<15:04, 10.82it/s]

 77%|███████████████████████████▋        | 32743/42525 [49:39<14:27, 11.27it/s]

 77%|███████████████████████████▋        | 32747/42525 [49:39<14:10, 11.50it/s]

 77%|███████████████████████████▋        | 32751/42525 [49:40<14:22, 11.33it/s]

 77%|███████████████████████████▋        | 32755/42525 [49:40<13:53, 11.72it/s]

 77%|███████████████████████████▋        | 32759/42525 [49:40<13:51, 11.75it/s]

 77%|███████████████████████████▋        | 32763/42525 [49:41<14:26, 11.27it/s]

 77%|███████████████████████████▋        | 32767/42525 [49:41<14:07, 11.51it/s]

 77%|███████████████████████████▋        | 32771/42525 [49:41<13:57, 11.65it/s]

 77%|███████████████████████████▋        | 32775/42525 [49:42<13:52, 11.71it/s]

 77%|███████████████████████████▋        | 32779/42525 [49:42<13:59, 11.62it/s]

 77%|███████████████████████████▊        | 32783/42525 [49:42<14:27, 11.23it/s]

 77%|███████████████████████████▊        | 32787/42525 [49:43<14:10, 11.45it/s]

 77%|███████████████████████████▊        | 32791/42525 [49:43<14:21, 11.30it/s]

 77%|███████████████████████████▊        | 32795/42525 [49:44<14:52, 10.91it/s]

 77%|███████████████████████████▊        | 32799/42525 [49:44<14:43, 11.01it/s]

 77%|███████████████████████████▊        | 32803/42525 [49:44<14:34, 11.11it/s]

 77%|███████████████████████████▊        | 32807/42525 [49:45<14:55, 10.85it/s]

 77%|███████████████████████████▊        | 32811/42525 [49:45<14:54, 10.87it/s]

 77%|███████████████████████████▊        | 32815/42525 [49:45<14:20, 11.28it/s]

 77%|███████████████████████████▊        | 32819/42525 [49:46<14:22, 11.25it/s]

 77%|███████████████████████████▊        | 32823/42525 [49:46<14:35, 11.08it/s]

 77%|███████████████████████████▊        | 32827/42525 [49:46<14:15, 11.33it/s]

 77%|███████████████████████████▊        | 32831/42525 [49:47<14:52, 10.86it/s]

 77%|███████████████████████████▊        | 32835/42525 [49:47<14:13, 11.35it/s]

 77%|███████████████████████████▊        | 32839/42525 [49:47<14:14, 11.34it/s]

 77%|███████████████████████████▊        | 32843/42525 [49:48<13:59, 11.53it/s]

 77%|███████████████████████████▊        | 32847/42525 [49:48<14:26, 11.16it/s]

 77%|███████████████████████████▊        | 32851/42525 [49:49<14:50, 10.87it/s]

 77%|███████████████████████████▊        | 32855/42525 [49:49<15:03, 10.70it/s]

 77%|███████████████████████████▊        | 32859/42525 [49:49<14:55, 10.80it/s]

 77%|███████████████████████████▊        | 32863/42525 [49:50<14:17, 11.27it/s]

 77%|███████████████████████████▊        | 32867/42525 [49:50<14:18, 11.25it/s]

 77%|███████████████████████████▊        | 32871/42525 [49:50<14:06, 11.41it/s]

 77%|███████████████████████████▊        | 32875/42525 [49:51<13:46, 11.68it/s]

 77%|███████████████████████████▊        | 32879/42525 [49:51<13:37, 11.81it/s]

 77%|███████████████████████████▊        | 32883/42525 [49:51<13:30, 11.90it/s]

 77%|███████████████████████████▊        | 32887/42525 [49:52<13:19, 12.05it/s]

 77%|███████████████████████████▊        | 32891/42525 [49:52<13:41, 11.72it/s]

 77%|███████████████████████████▊        | 32895/42525 [49:52<14:06, 11.38it/s]

 77%|███████████████████████████▊        | 32899/42525 [49:53<13:55, 11.52it/s]

 77%|███████████████████████████▊        | 32903/42525 [49:53<14:34, 11.00it/s]

 77%|███████████████████████████▊        | 32907/42525 [49:53<14:28, 11.07it/s]

 77%|███████████████████████████▊        | 32911/42525 [49:54<13:32, 11.83it/s]

 77%|███████████████████████████▊        | 32915/42525 [49:54<12:30, 12.81it/s]

 77%|███████████████████████████▊        | 32917/42525 [49:54<13:17, 12.04it/s]

 77%|███████████████████████████▊        | 32921/42525 [49:55<14:30, 11.03it/s]

 77%|███████████████████████████▊        | 32925/42525 [49:55<14:34, 10.98it/s]

 77%|███████████████████████████▉        | 32929/42525 [49:55<14:20, 11.16it/s]

 77%|███████████████████████████▉        | 32933/42525 [49:56<14:02, 11.38it/s]

 77%|███████████████████████████▉        | 32937/42525 [49:56<13:52, 11.52it/s]

 77%|███████████████████████████▉        | 32941/42525 [49:56<14:03, 11.36it/s]

 77%|███████████████████████████▉        | 32945/42525 [49:57<13:48, 11.56it/s]

 77%|███████████████████████████▉        | 32949/42525 [49:57<13:42, 11.64it/s]

 77%|███████████████████████████▉        | 32953/42525 [49:57<13:45, 11.60it/s]

 78%|███████████████████████████▉        | 32957/42525 [49:58<13:39, 11.67it/s]

 78%|███████████████████████████▉        | 32961/42525 [49:58<14:06, 11.30it/s]

 78%|███████████████████████████▉        | 32965/42525 [49:59<14:10, 11.24it/s]

 78%|███████████████████████████▉        | 32969/42525 [49:59<13:59, 11.38it/s]

 78%|███████████████████████████▉        | 32973/42525 [49:59<13:48, 11.52it/s]

 78%|███████████████████████████▉        | 32977/42525 [50:00<13:38, 11.67it/s]

 78%|███████████████████████████▉        | 32981/42525 [50:00<14:17, 11.13it/s]

 78%|███████████████████████████▉        | 32985/42525 [50:00<14:52, 10.69it/s]

 78%|███████████████████████████▉        | 32989/42525 [50:01<14:39, 10.85it/s]

 78%|███████████████████████████▉        | 32991/42525 [50:01<14:26, 11.01it/s]

 78%|███████████████████████████▉        | 32995/42525 [50:01<14:05, 11.27it/s]

 78%|███████████████████████████▉        | 32999/42525 [50:02<14:06, 11.25it/s]

 78%|███████████████████████████▉        | 33003/42525 [50:02<13:31, 11.73it/s]

 78%|███████████████████████████▉        | 33007/42525 [50:02<12:59, 12.22it/s]

 78%|███████████████████████████▉        | 33011/42525 [50:02<12:28, 12.71it/s]

 78%|███████████████████████████▉        | 33015/42525 [50:03<14:03, 11.27it/s]

 78%|███████████████████████████▉        | 33019/42525 [50:03<13:32, 11.71it/s]

 78%|███████████████████████████▉        | 33023/42525 [50:04<13:23, 11.82it/s]

 78%|███████████████████████████▉        | 33027/42525 [50:04<13:31, 11.70it/s]

 78%|███████████████████████████▉        | 33031/42525 [50:04<14:04, 11.24it/s]

 78%|███████████████████████████▉        | 33035/42525 [50:05<13:48, 11.45it/s]

 78%|███████████████████████████▉        | 33039/42525 [50:05<14:06, 11.20it/s]

 78%|███████████████████████████▉        | 33043/42525 [50:05<13:55, 11.35it/s]

 78%|███████████████████████████▉        | 33047/42525 [50:06<14:31, 10.87it/s]

 78%|███████████████████████████▉        | 33051/42525 [50:06<14:03, 11.24it/s]

 78%|███████████████████████████▉        | 33055/42525 [50:06<14:43, 10.72it/s]

 78%|███████████████████████████▉        | 33057/42525 [50:07<14:25, 10.94it/s]

 78%|███████████████████████████▉        | 33061/42525 [50:07<15:09, 10.40it/s]

 78%|███████████████████████████▉        | 33065/42525 [50:07<14:32, 10.84it/s]

 78%|███████████████████████████▉        | 33069/42525 [50:08<14:03, 11.21it/s]

 78%|███████████████████████████▉        | 33073/42525 [50:08<14:21, 10.97it/s]

 78%|████████████████████████████        | 33077/42525 [50:08<13:57, 11.29it/s]

 78%|████████████████████████████        | 33081/42525 [50:09<13:59, 11.25it/s]

 78%|████████████████████████████        | 33085/42525 [50:09<13:43, 11.46it/s]

 78%|████████████████████████████        | 33089/42525 [50:09<13:39, 11.52it/s]

 78%|████████████████████████████        | 33093/42525 [50:10<13:55, 11.29it/s]

 78%|████████████████████████████        | 33097/42525 [50:10<13:53, 11.31it/s]

 78%|████████████████████████████        | 33101/42525 [50:11<13:27, 11.67it/s]

 78%|████████████████████████████        | 33105/42525 [50:11<14:12, 11.05it/s]

 78%|████████████████████████████        | 33109/42525 [50:11<14:23, 10.91it/s]

 78%|████████████████████████████        | 33113/42525 [50:12<14:24, 10.88it/s]

 78%|████████████████████████████        | 33117/42525 [50:12<13:52, 11.30it/s]

 78%|████████████████████████████        | 33121/42525 [50:12<13:40, 11.46it/s]

 78%|████████████████████████████        | 33125/42525 [50:13<13:35, 11.53it/s]

 78%|████████████████████████████        | 33129/42525 [50:13<13:33, 11.56it/s]

 78%|████████████████████████████        | 33133/42525 [50:13<14:02, 11.14it/s]

 78%|████████████████████████████        | 33137/42525 [50:14<13:45, 11.37it/s]

 78%|████████████████████████████        | 33141/42525 [50:14<14:15, 10.97it/s]

 78%|████████████████████████████        | 33145/42525 [50:14<14:04, 11.10it/s]

 78%|████████████████████████████        | 33149/42525 [50:15<14:01, 11.14it/s]

 78%|████████████████████████████        | 33153/42525 [50:15<14:10, 11.01it/s]

 78%|████████████████████████████        | 33157/42525 [50:16<13:48, 11.31it/s]

 78%|████████████████████████████        | 33161/42525 [50:16<13:59, 11.15it/s]

 78%|████████████████████████████        | 33165/42525 [50:16<13:47, 11.31it/s]

 78%|████████████████████████████        | 33169/42525 [50:17<13:22, 11.66it/s]

 78%|████████████████████████████        | 33173/42525 [50:17<13:58, 11.16it/s]

 78%|████████████████████████████        | 33177/42525 [50:17<14:00, 11.12it/s]

 78%|████████████████████████████        | 33181/42525 [50:18<14:02, 11.09it/s]

 78%|████████████████████████████        | 33185/42525 [50:18<14:07, 11.02it/s]

 78%|████████████████████████████        | 33189/42525 [50:18<14:25, 10.79it/s]

 78%|████████████████████████████        | 33193/42525 [50:19<13:47, 11.27it/s]

 78%|████████████████████████████        | 33197/42525 [50:19<13:24, 11.59it/s]

 78%|████████████████████████████        | 33201/42525 [50:19<13:05, 11.87it/s]

 78%|████████████████████████████        | 33205/42525 [50:20<13:15, 11.72it/s]

 78%|████████████████████████████        | 33209/42525 [50:20<12:53, 12.05it/s]

 78%|████████████████████████████        | 33213/42525 [50:20<13:15, 11.71it/s]

 78%|████████████████████████████        | 33217/42525 [50:21<13:47, 11.25it/s]

 78%|████████████████████████████        | 33221/42525 [50:21<13:35, 11.40it/s]

 78%|████████████████████████████▏       | 33225/42525 [50:22<13:38, 11.36it/s]

 78%|████████████████████████████▏       | 33229/42525 [50:22<13:20, 11.61it/s]

 78%|████████████████████████████▏       | 33233/42525 [50:22<13:40, 11.32it/s]

 78%|████████████████████████████▏       | 33237/42525 [50:23<13:19, 11.61it/s]

 78%|████████████████████████████▏       | 33241/42525 [50:23<13:13, 11.70it/s]

 78%|████████████████████████████▏       | 33245/42525 [50:23<13:27, 11.49it/s]

 78%|████████████████████████████▏       | 33249/42525 [50:24<13:45, 11.24it/s]

 78%|████████████████████████████▏       | 33253/42525 [50:24<13:23, 11.54it/s]

 78%|████████████████████████████▏       | 33257/42525 [50:24<13:44, 11.24it/s]

 78%|████████████████████████████▏       | 33261/42525 [50:25<13:17, 11.61it/s]

 78%|████████████████████████████▏       | 33265/42525 [50:25<13:35, 11.35it/s]

 78%|████████████████████████████▏       | 33269/42525 [50:25<13:53, 11.11it/s]

 78%|████████████████████████████▏       | 33273/42525 [50:26<13:53, 11.10it/s]

 78%|████████████████████████████▏       | 33277/42525 [50:26<13:44, 11.21it/s]

 78%|████████████████████████████▏       | 33281/42525 [50:26<13:21, 11.53it/s]

 78%|████████████████████████████▏       | 33285/42525 [50:27<13:52, 11.10it/s]

 78%|████████████████████████████▏       | 33289/42525 [50:27<13:34, 11.34it/s]

 78%|████████████████████████████▏       | 33293/42525 [50:27<13:19, 11.55it/s]

 78%|████████████████████████████▏       | 33295/42525 [50:28<13:20, 11.54it/s]

 78%|████████████████████████████▏       | 33299/42525 [50:28<14:19, 10.73it/s]

 78%|████████████████████████████▏       | 33303/42525 [50:28<13:47, 11.14it/s]

 78%|████████████████████████████▏       | 33307/42525 [50:29<13:26, 11.43it/s]

 78%|████████████████████████████▏       | 33311/42525 [50:29<13:21, 11.50it/s]

 78%|████████████████████████████▏       | 33315/42525 [50:29<13:18, 11.53it/s]

 78%|████████████████████████████▏       | 33319/42525 [50:30<13:36, 11.27it/s]

 78%|████████████████████████████▏       | 33323/42525 [50:30<13:46, 11.13it/s]

 78%|████████████████████████████▏       | 33327/42525 [50:31<14:00, 10.94it/s]

 78%|████████████████████████████▏       | 33331/42525 [50:31<14:11, 10.80it/s]

 78%|████████████████████████████▏       | 33335/42525 [50:31<14:18, 10.71it/s]

 78%|████████████████████████████▏       | 33339/42525 [50:32<13:35, 11.26it/s]

 78%|████████████████████████████▏       | 33343/42525 [50:32<13:16, 11.53it/s]

 78%|████████████████████████████▏       | 33347/42525 [50:32<13:55, 10.98it/s]

 78%|████████████████████████████▏       | 33351/42525 [50:33<13:24, 11.41it/s]

 78%|████████████████████████████▏       | 33355/42525 [50:33<13:35, 11.24it/s]

 78%|████████████████████████████▏       | 33359/42525 [50:33<13:20, 11.45it/s]

 78%|████████████████████████████▏       | 33363/42525 [50:34<13:20, 11.44it/s]

 78%|████████████████████████████▏       | 33367/42525 [50:34<13:29, 11.31it/s]

 78%|████████████████████████████▎       | 33371/42525 [50:34<13:23, 11.39it/s]

 78%|████████████████████████████▎       | 33375/42525 [50:35<13:27, 11.33it/s]

 78%|████████████████████████████▎       | 33377/42525 [50:35<13:50, 11.02it/s]

 78%|████████████████████████████▎       | 33379/42525 [50:35<14:18, 10.65it/s]

 79%|████████████████████████████▎       | 33383/42525 [50:36<14:10, 10.75it/s]

 79%|████████████████████████████▎       | 33387/42525 [50:36<14:42, 10.36it/s]

 79%|████████████████████████████▎       | 33391/42525 [50:36<14:21, 10.61it/s]

 79%|████████████████████████████▎       | 33395/42525 [50:37<13:43, 11.09it/s]

 79%|████████████████████████████▎       | 33399/42525 [50:37<13:15, 11.47it/s]

 79%|████████████████████████████▎       | 33403/42525 [50:37<13:24, 11.34it/s]

 79%|████████████████████████████▎       | 33407/42525 [50:38<13:13, 11.49it/s]

 79%|████████████████████████████▎       | 33411/42525 [50:38<12:38, 12.01it/s]

 79%|████████████████████████████▎       | 33415/42525 [50:38<12:49, 11.84it/s]

 79%|████████████████████████████▎       | 33419/42525 [50:39<12:17, 12.35it/s]

 79%|████████████████████████████▎       | 33423/42525 [50:39<11:59, 12.65it/s]

 79%|████████████████████████████▎       | 33427/42525 [50:39<12:40, 11.96it/s]

 79%|████████████████████████████▎       | 33429/42525 [50:40<12:19, 12.31it/s]

 79%|████████████████████████████▎       | 33433/42525 [50:40<13:28, 11.25it/s]

 79%|████████████████████████████▎       | 33437/42525 [50:40<13:38, 11.11it/s]

 79%|████████████████████████████▎       | 33439/42525 [50:40<13:46, 10.99it/s]

 79%|████████████████████████████▎       | 33443/42525 [50:41<13:52, 10.91it/s]

 79%|████████████████████████████▎       | 33447/42525 [50:41<13:50, 10.93it/s]

 79%|████████████████████████████▎       | 33451/42525 [50:42<14:00, 10.80it/s]

 79%|████████████████████████████▎       | 33455/42525 [50:42<13:50, 10.92it/s]

 79%|████████████████████████████▎       | 33459/42525 [50:42<13:32, 11.16it/s]

 79%|████████████████████████████▎       | 33463/42525 [50:43<13:24, 11.26it/s]

 79%|████████████████████████████▎       | 33467/42525 [50:43<13:30, 11.18it/s]

 79%|████████████████████████████▎       | 33471/42525 [50:43<13:33, 11.12it/s]

 79%|████████████████████████████▎       | 33475/42525 [50:44<13:24, 11.25it/s]

 79%|████████████████████████████▎       | 33479/42525 [50:44<13:48, 10.91it/s]

 79%|████████████████████████████▎       | 33483/42525 [50:44<13:19, 11.31it/s]

 79%|████████████████████████████▎       | 33487/42525 [50:45<13:29, 11.17it/s]

 79%|████████████████████████████▎       | 33491/42525 [50:45<14:02, 10.72it/s]

 79%|████████████████████████████▎       | 33495/42525 [50:46<13:54, 10.82it/s]

 79%|████████████████████████████▎       | 33499/42525 [50:46<13:41, 10.98it/s]

 79%|████████████████████████████▎       | 33503/42525 [50:46<14:06, 10.66it/s]

 79%|████████████████████████████▎       | 33507/42525 [50:47<13:44, 10.94it/s]

 79%|████████████████████████████▎       | 33509/42525 [50:47<13:42, 10.96it/s]

 79%|████████████████████████████▎       | 33513/42525 [50:47<14:21, 10.46it/s]

 79%|████████████████████████████▎       | 33517/42525 [50:48<14:24, 10.41it/s]

 79%|████████████████████████████▍       | 33521/42525 [50:48<13:35, 11.04it/s]

 79%|████████████████████████████▍       | 33525/42525 [50:48<13:10, 11.39it/s]

 79%|████████████████████████████▍       | 33529/42525 [50:49<13:17, 11.27it/s]

 79%|████████████████████████████▍       | 33533/42525 [50:49<13:25, 11.16it/s]

 79%|████████████████████████████▍       | 33537/42525 [50:49<13:43, 10.91it/s]

 79%|████████████████████████████▍       | 33541/42525 [50:50<13:35, 11.01it/s]

 79%|████████████████████████████▍       | 33545/42525 [50:50<13:07, 11.41it/s]

 79%|████████████████████████████▍       | 33549/42525 [50:50<13:35, 11.01it/s]

 79%|████████████████████████████▍       | 33553/42525 [50:51<13:11, 11.33it/s]

 79%|████████████████████████████▍       | 33557/42525 [50:51<13:41, 10.92it/s]

 79%|████████████████████████████▍       | 33561/42525 [50:52<13:18, 11.22it/s]

 79%|████████████████████████████▍       | 33565/42525 [50:52<12:59, 11.49it/s]

 79%|████████████████████████████▍       | 33569/42525 [50:52<12:53, 11.57it/s]

 79%|████████████████████████████▍       | 33573/42525 [50:53<13:12, 11.29it/s]

 79%|████████████████████████████▍       | 33577/42525 [50:53<13:07, 11.37it/s]

 79%|████████████████████████████▍       | 33581/42525 [50:53<12:55, 11.53it/s]

 79%|████████████████████████████▍       | 33585/42525 [50:54<13:18, 11.20it/s]

 79%|████████████████████████████▍       | 33589/42525 [50:54<13:33, 10.98it/s]

 79%|████████████████████████████▍       | 33593/42525 [50:54<13:24, 11.11it/s]

 79%|████████████████████████████▍       | 33597/42525 [50:55<13:20, 11.15it/s]

 79%|████████████████████████████▍       | 33601/42525 [50:55<13:05, 11.36it/s]

 79%|████████████████████████████▍       | 33605/42525 [50:55<13:48, 10.76it/s]

 79%|████████████████████████████▍       | 33609/42525 [50:56<13:24, 11.09it/s]

 79%|████████████████████████████▍       | 33613/42525 [50:56<13:24, 11.07it/s]

 79%|████████████████████████████▍       | 33617/42525 [50:57<13:17, 11.17it/s]

 79%|████████████████████████████▍       | 33621/42525 [50:57<12:52, 11.53it/s]

 79%|████████████████████████████▍       | 33625/42525 [50:57<12:43, 11.66it/s]

 79%|████████████████████████████▍       | 33629/42525 [50:58<13:26, 11.04it/s]

 79%|████████████████████████████▍       | 33633/42525 [50:58<13:07, 11.29it/s]

 79%|████████████████████████████▍       | 33637/42525 [50:58<13:00, 11.39it/s]

 79%|████████████████████████████▍       | 33641/42525 [50:59<13:04, 11.32it/s]

 79%|████████████████████████████▍       | 33645/42525 [50:59<13:28, 10.98it/s]

 79%|████████████████████████████▍       | 33649/42525 [50:59<12:58, 11.40it/s]

 79%|████████████████████████████▍       | 33653/42525 [51:00<13:16, 11.14it/s]

 79%|████████████████████████████▍       | 33657/42525 [51:00<12:51, 11.49it/s]

 79%|████████████████████████████▍       | 33661/42525 [51:00<12:55, 11.44it/s]

 79%|████████████████████████████▍       | 33665/42525 [51:01<12:40, 11.64it/s]

 79%|████████████████████████████▌       | 33669/42525 [51:01<12:40, 11.64it/s]

 79%|████████████████████████████▌       | 33673/42525 [51:01<12:40, 11.64it/s]

 79%|████████████████████████████▌       | 33677/42525 [51:02<12:21, 11.93it/s]

 79%|████████████████████████████▌       | 33681/42525 [51:02<12:21, 11.92it/s]

 79%|████████████████████████████▌       | 33685/42525 [51:02<12:09, 12.13it/s]

 79%|████████████████████████████▌       | 33689/42525 [51:03<12:39, 11.64it/s]

 79%|████████████████████████████▌       | 33693/42525 [51:03<12:44, 11.55it/s]

 79%|████████████████████████████▌       | 33697/42525 [51:03<13:13, 11.12it/s]

 79%|████████████████████████████▌       | 33701/42525 [51:04<13:04, 11.25it/s]

 79%|████████████████████████████▌       | 33705/42525 [51:04<13:13, 11.11it/s]

 79%|████████████████████████████▌       | 33709/42525 [51:05<12:52, 11.42it/s]

 79%|████████████████████████████▌       | 33713/42525 [51:05<13:08, 11.17it/s]

 79%|████████████████████████████▌       | 33717/42525 [51:05<13:31, 10.85it/s]

 79%|████████████████████████████▌       | 33721/42525 [51:06<13:36, 10.78it/s]

 79%|████████████████████████████▌       | 33725/42525 [51:06<13:25, 10.92it/s]

 79%|████████████████████████████▌       | 33729/42525 [51:06<13:47, 10.63it/s]

 79%|████████████████████████████▌       | 33733/42525 [51:07<13:41, 10.70it/s]

 79%|████████████████████████████▌       | 33737/42525 [51:07<13:25, 10.91it/s]

 79%|████████████████████████████▌       | 33741/42525 [51:08<13:13, 11.07it/s]

 79%|████████████████████████████▌       | 33745/42525 [51:08<12:50, 11.40it/s]

 79%|████████████████████████████▌       | 33749/42525 [51:08<12:41, 11.53it/s]

 79%|████████████████████████████▌       | 33753/42525 [51:09<13:22, 10.93it/s]

 79%|████████████████████████████▌       | 33757/42525 [51:09<12:57, 11.27it/s]

 79%|████████████████████████████▌       | 33761/42525 [51:09<12:58, 11.26it/s]

 79%|████████████████████████████▌       | 33765/42525 [51:10<13:04, 11.17it/s]

 79%|████████████████████████████▌       | 33769/42525 [51:10<12:59, 11.23it/s]

 79%|████████████████████████████▌       | 33773/42525 [51:10<13:12, 11.04it/s]

 79%|████████████████████████████▌       | 33777/42525 [51:11<13:00, 11.20it/s]

 79%|████████████████████████████▌       | 33781/42525 [51:11<13:00, 11.20it/s]

 79%|████████████████████████████▌       | 33783/42525 [51:11<12:52, 11.32it/s]

 79%|████████████████████████████▌       | 33787/42525 [51:12<13:27, 10.83it/s]

 79%|████████████████████████████▌       | 33791/42525 [51:12<13:37, 10.68it/s]

 79%|████████████████████████████▌       | 33795/42525 [51:12<13:49, 10.53it/s]

 79%|████████████████████████████▌       | 33799/42525 [51:13<13:03, 11.13it/s]

 79%|████████████████████████████▌       | 33803/42525 [51:13<12:38, 11.50it/s]

 79%|████████████████████████████▌       | 33807/42525 [51:13<12:29, 11.63it/s]

 80%|████████████████████████████▌       | 33811/42525 [51:14<12:31, 11.60it/s]

 80%|████████████████████████████▋       | 33815/42525 [51:14<12:33, 11.56it/s]

 80%|████████████████████████████▋       | 33819/42525 [51:14<12:48, 11.33it/s]

 80%|████████████████████████████▋       | 33823/42525 [51:15<12:41, 11.43it/s]

 80%|████████████████████████████▋       | 33827/42525 [51:15<12:55, 11.21it/s]

 80%|████████████████████████████▋       | 33831/42525 [51:16<12:36, 11.49it/s]

 80%|████████████████████████████▋       | 33835/42525 [51:16<12:50, 11.28it/s]

 80%|████████████████████████████▋       | 33839/42525 [51:16<12:36, 11.49it/s]

 80%|████████████████████████████▋       | 33843/42525 [51:17<12:34, 11.50it/s]

 80%|████████████████████████████▋       | 33847/42525 [51:17<12:15, 11.80it/s]

 80%|████████████████████████████▋       | 33851/42525 [51:17<12:57, 11.16it/s]

 80%|████████████████████████████▋       | 33855/42525 [51:18<13:06, 11.02it/s]

 80%|████████████████████████████▋       | 33859/42525 [51:18<13:00, 11.10it/s]

 80%|████████████████████████████▋       | 33863/42525 [51:18<13:13, 10.91it/s]

 80%|████████████████████████████▋       | 33867/42525 [51:19<13:33, 10.65it/s]

 80%|████████████████████████████▋       | 33871/42525 [51:19<13:12, 10.92it/s]

 80%|████████████████████████████▋       | 33875/42525 [51:19<13:00, 11.09it/s]

 80%|████████████████████████████▋       | 33879/42525 [51:20<12:53, 11.17it/s]

 80%|████████████████████████████▋       | 33883/42525 [51:20<12:53, 11.17it/s]

 80%|████████████████████████████▋       | 33887/42525 [51:21<12:47, 11.25it/s]

 80%|████████████████████████████▋       | 33891/42525 [51:21<13:02, 11.03it/s]

 80%|████████████████████████████▋       | 33895/42525 [51:21<13:12, 10.89it/s]

 80%|████████████████████████████▋       | 33897/42525 [51:21<13:22, 10.75it/s]

 80%|████████████████████████████▋       | 33901/42525 [51:22<13:16, 10.83it/s]

 80%|████████████████████████████▋       | 33905/42525 [51:22<12:44, 11.27it/s]

 80%|████████████████████████████▋       | 33909/42525 [51:23<12:31, 11.46it/s]

 80%|████████████████████████████▋       | 33913/42525 [51:23<12:21, 11.61it/s]

 80%|████████████████████████████▋       | 33917/42525 [51:23<12:38, 11.35it/s]

 80%|████████████████████████████▋       | 33921/42525 [51:24<13:05, 10.95it/s]

 80%|████████████████████████████▋       | 33925/42525 [51:24<12:51, 11.15it/s]

 80%|████████████████████████████▋       | 33929/42525 [51:24<12:37, 11.34it/s]

 80%|████████████████████████████▋       | 33933/42525 [51:25<12:33, 11.41it/s]

 80%|████████████████████████████▋       | 33937/42525 [51:25<12:29, 11.45it/s]

 80%|████████████████████████████▋       | 33941/42525 [51:25<12:18, 11.63it/s]

 80%|████████████████████████████▋       | 33945/42525 [51:26<12:43, 11.24it/s]

 80%|████████████████████████████▋       | 33949/42525 [51:26<12:37, 11.32it/s]

 80%|████████████████████████████▋       | 33953/42525 [51:26<12:30, 11.42it/s]

 80%|████████████████████████████▋       | 33955/42525 [51:27<12:51, 11.10it/s]

 80%|████████████████████████████▋       | 33959/42525 [51:27<13:27, 10.61it/s]

 80%|████████████████████████████▊       | 33963/42525 [51:27<12:59, 10.98it/s]

 80%|████████████████████████████▊       | 33967/42525 [51:28<13:20, 10.69it/s]

 80%|████████████████████████████▊       | 33971/42525 [51:28<13:08, 10.84it/s]

 80%|████████████████████████████▊       | 33975/42525 [51:28<12:59, 10.97it/s]

 80%|████████████████████████████▊       | 33979/42525 [51:29<13:15, 10.74it/s]

 80%|████████████████████████████▊       | 33983/42525 [51:29<13:08, 10.83it/s]

 80%|████████████████████████████▊       | 33987/42525 [51:30<13:00, 10.95it/s]

 80%|████████████████████████████▊       | 33991/42525 [51:30<12:30, 11.36it/s]

 80%|████████████████████████████▊       | 33995/42525 [51:30<13:05, 10.87it/s]

 80%|████████████████████████████▊       | 33999/42525 [51:31<12:38, 11.23it/s]

 80%|████████████████████████████▊       | 34003/42525 [51:31<12:50, 11.05it/s]

 80%|████████████████████████████▊       | 34007/42525 [51:31<13:16, 10.69it/s]

 80%|████████████████████████████▊       | 34011/42525 [51:32<12:51, 11.03it/s]

 80%|████████████████████████████▊       | 34015/42525 [51:32<12:27, 11.38it/s]

 80%|████████████████████████████▊       | 34019/42525 [51:32<12:40, 11.19it/s]

 80%|████████████████████████████▊       | 34023/42525 [51:33<12:52, 11.01it/s]

 80%|████████████████████████████▊       | 34027/42525 [51:33<12:27, 11.37it/s]

 80%|████████████████████████████▊       | 34031/42525 [51:34<12:28, 11.35it/s]

 80%|████████████████████████████▊       | 34035/42525 [51:34<12:15, 11.55it/s]

 80%|████████████████████████████▊       | 34039/42525 [51:34<12:05, 11.70it/s]

 80%|████████████████████████████▊       | 34043/42525 [51:35<12:05, 11.69it/s]

 80%|████████████████████████████▊       | 34047/42525 [51:35<12:19, 11.46it/s]

 80%|████████████████████████████▊       | 34051/42525 [51:35<12:33, 11.24it/s]

 80%|████████████████████████████▊       | 34055/42525 [51:36<12:42, 11.12it/s]

 80%|████████████████████████████▊       | 34059/42525 [51:36<13:03, 10.80it/s]

 80%|████████████████████████████▊       | 34063/42525 [51:36<12:38, 11.16it/s]

 80%|████████████████████████████▊       | 34067/42525 [51:37<12:30, 11.28it/s]

 80%|████████████████████████████▊       | 34069/42525 [51:37<12:22, 11.38it/s]

 80%|████████████████████████████▊       | 34073/42525 [51:37<12:52, 10.94it/s]

 80%|████████████████████████████▊       | 34077/42525 [51:38<12:42, 11.08it/s]

 80%|████████████████████████████▊       | 34081/42525 [51:38<13:13, 10.64it/s]

 80%|████████████████████████████▊       | 34085/42525 [51:38<13:00, 10.81it/s]

 80%|████████████████████████████▊       | 34089/42525 [51:39<12:29, 11.25it/s]

 80%|████████████████████████████▊       | 34091/42525 [51:39<12:22, 11.36it/s]

 80%|████████████████████████████▊       | 34095/42525 [51:39<12:49, 10.96it/s]

 80%|████████████████████████████▊       | 34099/42525 [51:40<13:07, 10.70it/s]

 80%|████████████████████████████▊       | 34103/42525 [51:40<13:13, 10.61it/s]

 80%|████████████████████████████▊       | 34107/42525 [51:40<12:51, 10.91it/s]

 80%|████████████████████████████▉       | 34111/42525 [51:41<12:39, 11.08it/s]

 80%|████████████████████████████▉       | 34115/42525 [51:41<12:45, 10.98it/s]

 80%|████████████████████████████▉       | 34119/42525 [51:41<12:42, 11.03it/s]

 80%|████████████████████████████▉       | 34123/42525 [51:42<12:57, 10.81it/s]

 80%|████████████████████████████▉       | 34127/42525 [51:42<12:51, 10.88it/s]

 80%|████████████████████████████▉       | 34131/42525 [51:43<12:52, 10.86it/s]

 80%|████████████████████████████▉       | 34135/42525 [51:43<12:52, 10.86it/s]

 80%|████████████████████████████▉       | 34139/42525 [51:43<12:39, 11.04it/s]

 80%|████████████████████████████▉       | 34143/42525 [51:44<12:13, 11.43it/s]

 80%|████████████████████████████▉       | 34147/42525 [51:44<12:09, 11.48it/s]

 80%|████████████████████████████▉       | 34151/42525 [51:44<11:58, 11.65it/s]

 80%|████████████████████████████▉       | 34155/42525 [51:45<12:17, 11.35it/s]

 80%|████████████████████████████▉       | 34159/42525 [51:45<11:56, 11.68it/s]

 80%|████████████████████████████▉       | 34163/42525 [51:45<12:03, 11.56it/s]

 80%|████████████████████████████▉       | 34167/42525 [51:46<12:17, 11.33it/s]

 80%|████████████████████████████▉       | 34171/42525 [51:46<12:01, 11.59it/s]

 80%|████████████████████████████▉       | 34175/42525 [51:46<11:57, 11.64it/s]

 80%|████████████████████████████▉       | 34179/42525 [51:47<12:17, 11.31it/s]

 80%|████████████████████████████▉       | 34183/42525 [51:47<12:34, 11.05it/s]

 80%|████████████████████████████▉       | 34185/42525 [51:47<12:26, 11.17it/s]

 80%|████████████████████████████▉       | 34189/42525 [51:48<13:14, 10.49it/s]

 80%|████████████████████████████▉       | 34193/42525 [51:48<12:52, 10.78it/s]

 80%|████████████████████████████▉       | 34197/42525 [51:48<12:52, 10.78it/s]

 80%|████████████████████████████▉       | 34201/42525 [51:49<12:39, 10.95it/s]

 80%|████████████████████████████▉       | 34205/42525 [51:49<12:35, 11.01it/s]

 80%|████████████████████████████▉       | 34209/42525 [51:50<12:12, 11.35it/s]

 80%|████████████████████████████▉       | 34213/42525 [51:50<12:26, 11.13it/s]

 80%|████████████████████████████▉       | 34217/42525 [51:50<12:31, 11.05it/s]

 80%|████████████████████████████▉       | 34221/42525 [51:51<12:45, 10.84it/s]

 80%|████████████████████████████▉       | 34223/42525 [51:51<12:30, 11.06it/s]

 80%|████████████████████████████▉       | 34227/42525 [51:51<12:43, 10.87it/s]

 80%|████████████████████████████▉       | 34231/42525 [51:52<13:05, 10.56it/s]

 81%|████████████████████████████▉       | 34235/42525 [51:52<12:27, 11.09it/s]

 81%|████████████████████████████▉       | 34239/42525 [51:52<12:33, 10.99it/s]

 81%|████████████████████████████▉       | 34243/42525 [51:53<12:14, 11.27it/s]

 81%|████████████████████████████▉       | 34247/42525 [51:53<12:00, 11.49it/s]

 81%|████████████████████████████▉       | 34251/42525 [51:53<11:57, 11.54it/s]

 81%|████████████████████████████▉       | 34255/42525 [51:54<11:57, 11.53it/s]

 81%|█████████████████████████████       | 34259/42525 [51:54<11:58, 11.51it/s]

 81%|█████████████████████████████       | 34263/42525 [51:54<11:47, 11.67it/s]

 81%|█████████████████████████████       | 34267/42525 [51:55<11:45, 11.71it/s]

 81%|█████████████████████████████       | 34271/42525 [51:55<12:14, 11.24it/s]

 81%|█████████████████████████████       | 34275/42525 [51:55<12:12, 11.26it/s]

 81%|█████████████████████████████       | 34279/42525 [51:56<12:17, 11.18it/s]

 81%|█████████████████████████████       | 34283/42525 [51:56<12:31, 10.97it/s]

 81%|█████████████████████████████       | 34287/42525 [51:57<12:36, 10.90it/s]

 81%|█████████████████████████████       | 34289/42525 [51:57<12:20, 11.12it/s]

 81%|█████████████████████████████       | 34293/42525 [51:57<13:05, 10.48it/s]

 81%|█████████████████████████████       | 34295/42525 [51:57<12:41, 10.81it/s]

 81%|█████████████████████████████       | 34299/42525 [51:58<12:35, 10.89it/s]

 81%|█████████████████████████████       | 34303/42525 [51:58<12:06, 11.32it/s]

 81%|█████████████████████████████       | 34307/42525 [51:58<11:46, 11.64it/s]

 81%|█████████████████████████████       | 34311/42525 [51:59<12:01, 11.39it/s]

 81%|█████████████████████████████       | 34315/42525 [51:59<11:59, 11.41it/s]

 81%|█████████████████████████████       | 34319/42525 [51:59<11:51, 11.54it/s]

 81%|█████████████████████████████       | 34323/42525 [52:00<12:30, 10.93it/s]

 81%|█████████████████████████████       | 34327/42525 [52:00<12:43, 10.73it/s]

 81%|█████████████████████████████       | 34331/42525 [52:00<12:06, 11.28it/s]

 81%|█████████████████████████████       | 34335/42525 [52:01<12:16, 11.11it/s]

 81%|█████████████████████████████       | 34339/42525 [52:01<12:41, 10.75it/s]

 81%|█████████████████████████████       | 34343/42525 [52:02<12:34, 10.85it/s]

 81%|█████████████████████████████       | 34347/42525 [52:02<12:17, 11.09it/s]

 81%|█████████████████████████████       | 34351/42525 [52:02<11:52, 11.48it/s]

 81%|█████████████████████████████       | 34355/42525 [52:03<11:40, 11.66it/s]

 81%|█████████████████████████████       | 34359/42525 [52:03<11:42, 11.62it/s]

 81%|█████████████████████████████       | 34363/42525 [52:03<12:00, 11.33it/s]

 81%|█████████████████████████████       | 34367/42525 [52:04<11:58, 11.36it/s]

 81%|█████████████████████████████       | 34371/42525 [52:04<11:45, 11.56it/s]

 81%|█████████████████████████████       | 34375/42525 [52:04<11:37, 11.69it/s]

 81%|█████████████████████████████       | 34379/42525 [52:05<11:54, 11.40it/s]

 81%|█████████████████████████████       | 34383/42525 [52:05<11:40, 11.62it/s]

 81%|█████████████████████████████       | 34387/42525 [52:05<11:49, 11.47it/s]

 81%|█████████████████████████████       | 34391/42525 [52:06<11:59, 11.30it/s]

 81%|█████████████████████████████       | 34395/42525 [52:06<12:02, 11.25it/s]

 81%|█████████████████████████████       | 34399/42525 [52:06<11:45, 11.51it/s]

 81%|█████████████████████████████       | 34403/42525 [52:07<11:56, 11.33it/s]

 81%|█████████████████████████████▏      | 34407/42525 [52:07<12:09, 11.13it/s]

 81%|█████████████████████████████▏      | 34411/42525 [52:08<12:06, 11.18it/s]

 81%|█████████████████████████████▏      | 34415/42525 [52:08<12:27, 10.85it/s]

 81%|█████████████████████████████▏      | 34419/42525 [52:08<12:00, 11.24it/s]

 81%|█████████████████████████████▏      | 34423/42525 [52:09<12:26, 10.86it/s]

 81%|█████████████████████████████▏      | 34427/42525 [52:09<12:30, 10.79it/s]

 81%|█████████████████████████████▏      | 34431/42525 [52:09<12:31, 10.78it/s]

 81%|█████████████████████████████▏      | 34435/42525 [52:10<12:14, 11.02it/s]

 81%|█████████████████████████████▏      | 34439/42525 [52:10<12:05, 11.15it/s]

 81%|█████████████████████████████▏      | 34443/42525 [52:10<11:55, 11.30it/s]

 81%|█████████████████████████████▏      | 34447/42525 [52:11<12:10, 11.06it/s]

 81%|█████████████████████████████▏      | 34451/42525 [52:11<11:58, 11.23it/s]

 81%|█████████████████████████████▏      | 34455/42525 [52:12<12:12, 11.02it/s]

 81%|█████████████████████████████▏      | 34459/42525 [52:12<12:06, 11.11it/s]

 81%|█████████████████████████████▏      | 34463/42525 [52:12<12:22, 10.86it/s]

 81%|█████████████████████████████▏      | 34467/42525 [52:13<12:20, 10.88it/s]

 81%|█████████████████████████████▏      | 34471/42525 [52:13<11:55, 11.26it/s]

 81%|█████████████████████████████▏      | 34475/42525 [52:13<11:51, 11.32it/s]

 81%|█████████████████████████████▏      | 34479/42525 [52:14<11:55, 11.25it/s]

 81%|█████████████████████████████▏      | 34483/42525 [52:14<12:08, 11.04it/s]

 81%|█████████████████████████████▏      | 34487/42525 [52:14<11:45, 11.40it/s]

 81%|█████████████████████████████▏      | 34491/42525 [52:15<11:58, 11.19it/s]

 81%|█████████████████████████████▏      | 34495/42525 [52:15<11:36, 11.52it/s]

 81%|█████████████████████████████▏      | 34499/42525 [52:15<11:43, 11.42it/s]

 81%|█████████████████████████████▏      | 34503/42525 [52:16<11:31, 11.61it/s]

 81%|█████████████████████████████▏      | 34507/42525 [52:16<11:33, 11.56it/s]

 81%|█████████████████████████████▏      | 34511/42525 [52:16<11:35, 11.53it/s]

 81%|█████████████████████████████▏      | 34513/42525 [52:17<11:47, 11.32it/s]

 81%|█████████████████████████████▏      | 34517/42525 [52:17<12:41, 10.51it/s]

 81%|█████████████████████████████▏      | 34521/42525 [52:17<12:31, 10.65it/s]

 81%|█████████████████████████████▏      | 34525/42525 [52:18<12:20, 10.80it/s]

 81%|█████████████████████████████▏      | 34529/42525 [52:18<12:17, 10.84it/s]

 81%|█████████████████████████████▏      | 34533/42525 [52:19<12:15, 10.87it/s]

 81%|█████████████████████████████▏      | 34537/42525 [52:19<12:01, 11.07it/s]

 81%|█████████████████████████████▏      | 34541/42525 [52:19<11:41, 11.39it/s]

 81%|█████████████████████████████▏      | 34545/42525 [52:20<11:29, 11.57it/s]

 81%|█████████████████████████████▏      | 34549/42525 [52:20<11:49, 11.25it/s]

 81%|█████████████████████████████▎      | 34553/42525 [52:20<11:32, 11.50it/s]

 81%|█████████████████████████████▎      | 34557/42525 [52:21<11:23, 11.66it/s]

 81%|█████████████████████████████▎      | 34561/42525 [52:21<11:21, 11.69it/s]

 81%|█████████████████████████████▎      | 34565/42525 [52:21<11:52, 11.18it/s]

 81%|█████████████████████████████▎      | 34569/42525 [52:22<11:46, 11.26it/s]

 81%|█████████████████████████████▎      | 34573/42525 [52:22<12:11, 10.87it/s]

 81%|█████████████████████████████▎      | 34577/42525 [52:22<12:22, 10.70it/s]

 81%|█████████████████████████████▎      | 34581/42525 [52:23<12:39, 10.46it/s]

 81%|█████████████████████████████▎      | 34583/42525 [52:23<12:42, 10.42it/s]

 81%|█████████████████████████████▎      | 34587/42525 [52:23<12:43, 10.40it/s]

 81%|█████████████████████████████▎      | 34591/42525 [52:24<12:23, 10.67it/s]

 81%|█████████████████████████████▎      | 34595/42525 [52:24<12:17, 10.76it/s]

 81%|█████████████████████████████▎      | 34599/42525 [52:25<12:04, 10.94it/s]

 81%|█████████████████████████████▎      | 34603/42525 [52:25<11:58, 11.03it/s]

 81%|█████████████████████████████▎      | 34607/42525 [52:25<12:03, 10.94it/s]

 81%|█████████████████████████████▎      | 34611/42525 [52:26<11:37, 11.35it/s]

 81%|█████████████████████████████▎      | 34615/42525 [52:26<11:41, 11.28it/s]

 81%|█████████████████████████████▎      | 34619/42525 [52:26<11:28, 11.49it/s]

 81%|█████████████████████████████▎      | 34623/42525 [52:27<11:23, 11.56it/s]

 81%|█████████████████████████████▎      | 34627/42525 [52:27<11:46, 11.18it/s]

 81%|█████████████████████████████▎      | 34631/42525 [52:27<11:36, 11.33it/s]

 81%|█████████████████████████████▎      | 34635/42525 [52:28<11:25, 11.51it/s]

 81%|█████████████████████████████▎      | 34637/42525 [52:28<11:26, 11.48it/s]

 81%|█████████████████████████████▎      | 34641/42525 [52:28<11:51, 11.07it/s]

 81%|█████████████████████████████▎      | 34645/42525 [52:29<11:57, 10.98it/s]

 81%|█████████████████████████████▎      | 34649/42525 [52:29<11:51, 11.08it/s]

 81%|█████████████████████████████▎      | 34651/42525 [52:29<11:54, 11.02it/s]

 81%|█████████████████████████████▎      | 34655/42525 [52:30<12:05, 10.85it/s]

 82%|█████████████████████████████▎      | 34659/42525 [52:30<11:50, 11.07it/s]

 82%|█████████████████████████████▎      | 34663/42525 [52:30<11:30, 11.38it/s]

 82%|█████████████████████████████▎      | 34667/42525 [52:31<11:33, 11.33it/s]

 82%|█████████████████████████████▎      | 34671/42525 [52:31<12:06, 10.80it/s]

 82%|█████████████████████████████▎      | 34675/42525 [52:31<11:38, 11.23it/s]

 82%|█████████████████████████████▎      | 34679/42525 [52:32<11:31, 11.34it/s]

 82%|█████████████████████████████▎      | 34683/42525 [52:32<11:56, 10.95it/s]

 82%|█████████████████████████████▎      | 34687/42525 [52:32<11:32, 11.31it/s]

 82%|█████████████████████████████▎      | 34691/42525 [52:33<11:20, 11.51it/s]

 82%|█████████████████████████████▎      | 34695/42525 [52:33<11:32, 11.30it/s]

 82%|█████████████████████████████▎      | 34699/42525 [52:33<11:52, 10.98it/s]

 82%|█████████████████████████████▍      | 34703/42525 [52:34<11:32, 11.29it/s]

 82%|█████████████████████████████▍      | 34707/42525 [52:34<12:00, 10.86it/s]

 82%|█████████████████████████████▍      | 34711/42525 [52:35<11:34, 11.26it/s]

 82%|█████████████████████████████▍      | 34715/42525 [52:35<11:23, 11.43it/s]

 82%|█████████████████████████████▍      | 34719/42525 [52:35<11:33, 11.26it/s]

 82%|█████████████████████████████▍      | 34723/42525 [52:36<11:20, 11.46it/s]

 82%|█████████████████████████████▍      | 34727/42525 [52:36<11:20, 11.46it/s]

 82%|█████████████████████████████▍      | 34731/42525 [52:36<11:34, 11.22it/s]

 82%|█████████████████████████████▍      | 34735/42525 [52:37<11:29, 11.30it/s]

 82%|█████████████████████████████▍      | 34739/42525 [52:37<11:17, 11.49it/s]

 82%|█████████████████████████████▍      | 34743/42525 [52:37<11:10, 11.61it/s]

 82%|█████████████████████████████▍      | 34747/42525 [52:38<11:05, 11.69it/s]

 82%|█████████████████████████████▍      | 34751/42525 [52:38<11:26, 11.32it/s]

 82%|█████████████████████████████▍      | 34755/42525 [52:38<11:35, 11.17it/s]

 82%|█████████████████████████████▍      | 34759/42525 [52:39<11:18, 11.44it/s]

 82%|█████████████████████████████▍      | 34763/42525 [52:39<11:13, 11.53it/s]

 82%|█████████████████████████████▍      | 34767/42525 [52:39<11:19, 11.41it/s]

 82%|█████████████████████████████▍      | 34771/42525 [52:40<11:25, 11.31it/s]

 82%|█████████████████████████████▍      | 34775/42525 [52:40<11:20, 11.39it/s]

 82%|█████████████████████████████▍      | 34779/42525 [52:40<11:11, 11.54it/s]

 82%|█████████████████████████████▍      | 34783/42525 [52:41<11:11, 11.52it/s]

 82%|█████████████████████████████▍      | 34787/42525 [52:41<11:37, 11.10it/s]

 82%|█████████████████████████████▍      | 34791/42525 [52:42<11:34, 11.13it/s]

 82%|█████████████████████████████▍      | 34795/42525 [52:42<11:26, 11.26it/s]

 82%|█████████████████████████████▍      | 34799/42525 [52:42<11:43, 10.98it/s]

 82%|█████████████████████████████▍      | 34803/42525 [52:43<11:37, 11.07it/s]

 82%|█████████████████████████████▍      | 34807/42525 [52:43<11:39, 11.03it/s]

 82%|█████████████████████████████▍      | 34811/42525 [52:43<11:36, 11.08it/s]

 82%|█████████████████████████████▍      | 34815/42525 [52:44<11:36, 11.06it/s]

 82%|█████████████████████████████▍      | 34819/42525 [52:44<11:36, 11.07it/s]

 82%|█████████████████████████████▍      | 34823/42525 [52:44<11:37, 11.04it/s]

 82%|█████████████████████████████▍      | 34827/42525 [52:45<11:19, 11.34it/s]

 82%|█████████████████████████████▍      | 34831/42525 [52:45<11:31, 11.13it/s]

 82%|█████████████████████████████▍      | 34835/42525 [52:46<11:25, 11.22it/s]

 82%|█████████████████████████████▍      | 34839/42525 [52:46<11:15, 11.37it/s]

 82%|█████████████████████████████▍      | 34843/42525 [52:46<11:09, 11.48it/s]

 82%|█████████████████████████████▌      | 34847/42525 [52:47<11:39, 10.97it/s]

 82%|█████████████████████████████▌      | 34851/42525 [52:47<11:49, 10.82it/s]

 82%|█████████████████████████████▌      | 34855/42525 [52:47<12:04, 10.59it/s]

 82%|█████████████████████████████▌      | 34859/42525 [52:48<11:38, 10.97it/s]

 82%|█████████████████████████████▌      | 34863/42525 [52:48<11:37, 10.98it/s]

 82%|█████████████████████████████▌      | 34867/42525 [52:48<11:26, 11.15it/s]

 82%|█████████████████████████████▌      | 34871/42525 [52:49<11:24, 11.18it/s]

 82%|█████████████████████████████▌      | 34875/42525 [52:49<11:06, 11.47it/s]

 82%|█████████████████████████████▌      | 34879/42525 [52:50<11:25, 11.15it/s]

 82%|█████████████████████████████▌      | 34883/42525 [52:50<11:22, 11.19it/s]

 82%|█████████████████████████████▌      | 34887/42525 [52:50<11:23, 11.17it/s]

 82%|█████████████████████████████▌      | 34891/42525 [52:51<10:58, 11.59it/s]

 82%|█████████████████████████████▌      | 34895/42525 [52:51<11:34, 10.99it/s]

 82%|█████████████████████████████▌      | 34899/42525 [52:51<11:37, 10.93it/s]

 82%|█████████████████████████████▌      | 34903/42525 [52:52<11:00, 11.55it/s]

 82%|█████████████████████████████▌      | 34907/42525 [52:52<11:11, 11.35it/s]

 82%|█████████████████████████████▌      | 34911/42525 [52:52<11:13, 11.30it/s]

 82%|█████████████████████████████▌      | 34915/42525 [52:53<11:18, 11.22it/s]

 82%|█████████████████████████████▌      | 34919/42525 [52:53<11:09, 11.37it/s]

 82%|█████████████████████████████▌      | 34923/42525 [52:53<11:03, 11.46it/s]

 82%|█████████████████████████████▌      | 34927/42525 [52:54<10:26, 12.14it/s]

 82%|█████████████████████████████▌      | 34931/42525 [52:54<10:19, 12.26it/s]

 82%|█████████████████████████████▌      | 34935/42525 [52:54<09:35, 13.19it/s]

 82%|█████████████████████████████▌      | 34939/42525 [52:55<09:45, 12.95it/s]

 82%|█████████████████████████████▌      | 34943/42525 [52:55<10:20, 12.22it/s]

 82%|█████████████████████████████▌      | 34947/42525 [52:55<10:47, 11.71it/s]

 82%|█████████████████████████████▌      | 34951/42525 [52:56<11:12, 11.27it/s]

 82%|█████████████████████████████▌      | 34955/42525 [52:56<11:22, 11.09it/s]

 82%|█████████████████████████████▌      | 34959/42525 [52:56<11:13, 11.24it/s]

 82%|█████████████████████████████▌      | 34963/42525 [52:57<11:00, 11.45it/s]

 82%|█████████████████████████████▌      | 34967/42525 [52:57<11:18, 11.14it/s]

 82%|█████████████████████████████▌      | 34971/42525 [52:57<11:04, 11.37it/s]

 82%|█████████████████████████████▌      | 34975/42525 [52:58<11:17, 11.14it/s]

 82%|█████████████████████████████▌      | 34979/42525 [52:58<11:10, 11.25it/s]

 82%|█████████████████████████████▌      | 34983/42525 [52:59<11:09, 11.26it/s]

 82%|█████████████████████████████▌      | 34987/42525 [52:59<10:50, 11.58it/s]

 82%|█████████████████████████████▌      | 34991/42525 [52:59<10:58, 11.44it/s]

 82%|█████████████████████████████▋      | 34995/42525 [53:00<11:01, 11.39it/s]

 82%|█████████████████████████████▋      | 34999/42525 [53:00<10:56, 11.46it/s]

 82%|█████████████████████████████▋      | 35003/42525 [53:00<10:48, 11.60it/s]

 82%|█████████████████████████████▋      | 35007/42525 [53:01<10:40, 11.74it/s]

 82%|█████████████████████████████▋      | 35011/42525 [53:01<10:49, 11.56it/s]

 82%|█████████████████████████████▋      | 35015/42525 [53:01<11:00, 11.37it/s]

 82%|█████████████████████████████▋      | 35017/42525 [53:02<10:54, 11.47it/s]

 82%|█████████████████████████████▋      | 35021/42525 [53:02<11:27, 10.91it/s]

 82%|█████████████████████████████▋      | 35025/42525 [53:02<11:42, 10.67it/s]

 82%|█████████████████████████████▋      | 35029/42525 [53:03<11:09, 11.20it/s]

 82%|█████████████████████████████▋      | 35033/42525 [53:03<11:05, 11.25it/s]

 82%|█████████████████████████████▋      | 35037/42525 [53:03<11:25, 10.92it/s]

 82%|█████████████████████████████▋      | 35041/42525 [53:04<11:29, 10.85it/s]

 82%|█████████████████████████████▋      | 35045/42525 [53:04<11:26, 10.90it/s]

 82%|█████████████████████████████▋      | 35049/42525 [53:04<11:09, 11.17it/s]

 82%|█████████████████████████████▋      | 35053/42525 [53:05<10:51, 11.47it/s]

 82%|█████████████████████████████▋      | 35057/42525 [53:05<10:40, 11.66it/s]

 82%|█████████████████████████████▋      | 35061/42525 [53:05<10:59, 11.32it/s]

 82%|█████████████████████████████▋      | 35063/42525 [53:06<10:51, 11.46it/s]

 82%|█████████████████████████████▋      | 35067/42525 [53:06<11:28, 10.83it/s]

 82%|█████████████████████████████▋      | 35071/42525 [53:06<11:00, 11.29it/s]

 82%|█████████████████████████████▋      | 35075/42525 [53:07<11:04, 11.21it/s]

 82%|█████████████████████████████▋      | 35079/42525 [53:07<10:37, 11.67it/s]

 82%|█████████████████████████████▋      | 35083/42525 [53:07<11:01, 11.24it/s]

 83%|█████████████████████████████▋      | 35087/42525 [53:08<11:10, 11.09it/s]

 83%|█████████████████████████████▋      | 35091/42525 [53:08<10:56, 11.32it/s]

 83%|█████████████████████████████▋      | 35095/42525 [53:09<10:57, 11.31it/s]

 83%|█████████████████████████████▋      | 35099/42525 [53:09<10:58, 11.27it/s]

 83%|█████████████████████████████▋      | 35103/42525 [53:09<10:57, 11.29it/s]

 83%|█████████████████████████████▋      | 35107/42525 [53:10<11:00, 11.23it/s]

 83%|█████████████████████████████▋      | 35111/42525 [53:10<10:42, 11.54it/s]

 83%|█████████████████████████████▋      | 35115/42525 [53:10<10:38, 11.60it/s]

 83%|█████████████████████████████▋      | 35119/42525 [53:11<11:15, 10.96it/s]

 83%|█████████████████████████████▋      | 35123/42525 [53:11<11:36, 10.63it/s]

 83%|█████████████████████████████▋      | 35127/42525 [53:11<11:39, 10.57it/s]

 83%|█████████████████████████████▋      | 35129/42525 [53:12<11:09, 11.05it/s]

 83%|█████████████████████████████▋      | 35133/42525 [53:12<11:37, 10.60it/s]

 83%|█████████████████████████████▋      | 35137/42525 [53:12<10:57, 11.23it/s]

 83%|█████████████████████████████▋      | 35141/42525 [53:13<10:45, 11.43it/s]

 83%|█████████████████████████████▊      | 35145/42525 [53:13<11:18, 10.88it/s]

 83%|█████████████████████████████▊      | 35149/42525 [53:13<10:56, 11.24it/s]

 83%|█████████████████████████████▊      | 35153/42525 [53:14<10:56, 11.23it/s]

 83%|█████████████████████████████▊      | 35157/42525 [53:14<10:56, 11.22it/s]

 83%|█████████████████████████████▊      | 35161/42525 [53:14<10:39, 11.52it/s]

 83%|█████████████████████████████▊      | 35165/42525 [53:15<11:11, 10.96it/s]

 83%|█████████████████████████████▊      | 35169/42525 [53:15<11:04, 11.07it/s]

 83%|█████████████████████████████▊      | 35173/42525 [53:16<10:44, 11.41it/s]

 83%|█████████████████████████████▊      | 35177/42525 [53:16<10:32, 11.62it/s]

 83%|█████████████████████████████▊      | 35181/42525 [53:16<10:44, 11.40it/s]

 83%|█████████████████████████████▊      | 35185/42525 [53:17<10:38, 11.50it/s]

 83%|█████████████████████████████▊      | 35189/42525 [53:17<10:52, 11.24it/s]

 83%|█████████████████████████████▊      | 35193/42525 [53:17<11:23, 10.72it/s]

 83%|█████████████████████████████▊      | 35197/42525 [53:18<10:58, 11.13it/s]

 83%|█████████████████████████████▊      | 35201/42525 [53:18<11:02, 11.06it/s]

 83%|█████████████████████████████▊      | 35205/42525 [53:18<10:38, 11.46it/s]

 83%|█████████████████████████████▊      | 35209/42525 [53:19<11:00, 11.08it/s]

 83%|█████████████████████████████▊      | 35213/42525 [53:19<10:40, 11.41it/s]

 83%|█████████████████████████████▊      | 35217/42525 [53:19<10:07, 12.03it/s]

 83%|█████████████████████████████▊      | 35221/42525 [53:20<09:50, 12.37it/s]

 83%|█████████████████████████████▊      | 35225/42525 [53:20<10:20, 11.76it/s]

 83%|█████████████████████████████▊      | 35229/42525 [53:20<09:54, 12.28it/s]

 83%|█████████████████████████████▊      | 35233/42525 [53:21<10:21, 11.74it/s]

 83%|█████████████████████████████▊      | 35235/42525 [53:21<10:42, 11.34it/s]

 83%|█████████████████████████████▊      | 35239/42525 [53:21<10:59, 11.04it/s]

 83%|█████████████████████████████▊      | 35243/42525 [53:22<10:12, 11.88it/s]

 83%|█████████████████████████████▊      | 35247/42525 [53:22<09:47, 12.40it/s]

 83%|█████████████████████████████▊      | 35251/42525 [53:22<10:08, 11.95it/s]

 83%|█████████████████████████████▊      | 35255/42525 [53:23<10:15, 11.81it/s]

 83%|█████████████████████████████▊      | 35259/42525 [53:23<09:49, 12.33it/s]

 83%|█████████████████████████████▊      | 35263/42525 [53:23<09:36, 12.59it/s]

 83%|█████████████████████████████▊      | 35267/42525 [53:24<09:30, 12.72it/s]

 83%|█████████████████████████████▊      | 35269/42525 [53:24<10:08, 11.92it/s]

 83%|█████████████████████████████▊      | 35273/42525 [53:24<10:23, 11.63it/s]

 83%|█████████████████████████████▊      | 35277/42525 [53:24<10:44, 11.25it/s]

 83%|█████████████████████████████▊      | 35281/42525 [53:25<10:03, 12.00it/s]

 83%|█████████████████████████████▊      | 35285/42525 [53:25<11:08, 10.83it/s]

 83%|█████████████████████████████▊      | 35289/42525 [53:25<10:05, 11.95it/s]

 83%|█████████████████████████████▉      | 35293/42525 [53:26<09:41, 12.44it/s]

 83%|█████████████████████████████▉      | 35297/42525 [53:26<09:55, 12.14it/s]

 83%|█████████████████████████████▉      | 35301/42525 [53:27<10:33, 11.40it/s]

 83%|█████████████████████████████▉      | 35305/42525 [53:27<09:59, 12.05it/s]

 83%|█████████████████████████████▉      | 35309/42525 [53:27<09:56, 12.09it/s]

 83%|█████████████████████████████▉      | 35313/42525 [53:27<10:03, 11.95it/s]

 83%|█████████████████████████████▉      | 35317/42525 [53:28<10:05, 11.90it/s]

 83%|█████████████████████████████▉      | 35321/42525 [53:28<10:05, 11.90it/s]

 83%|█████████████████████████████▉      | 35325/42525 [53:28<09:36, 12.49it/s]

 83%|█████████████████████████████▉      | 35329/42525 [53:29<10:23, 11.54it/s]

 83%|█████████████████████████████▉      | 35333/42525 [53:29<09:52, 12.13it/s]

 83%|█████████████████████████████▉      | 35337/42525 [53:29<09:39, 12.40it/s]

 83%|█████████████████████████████▉      | 35341/42525 [53:30<10:08, 11.80it/s]

 83%|█████████████████████████████▉      | 35345/42525 [53:30<10:11, 11.74it/s]

 83%|█████████████████████████████▉      | 35349/42525 [53:31<10:39, 11.22it/s]

 83%|█████████████████████████████▉      | 35353/42525 [53:31<10:15, 11.65it/s]

 83%|█████████████████████████████▉      | 35357/42525 [53:31<10:36, 11.26it/s]

 83%|█████████████████████████████▉      | 35361/42525 [53:32<10:36, 11.26it/s]

 83%|█████████████████████████████▉      | 35365/42525 [53:32<10:03, 11.86it/s]

 83%|█████████████████████████████▉      | 35369/42525 [53:32<10:42, 11.13it/s]

 83%|█████████████████████████████▉      | 35373/42525 [53:33<09:45, 12.21it/s]

 83%|█████████████████████████████▉      | 35377/42525 [53:33<09:28, 12.58it/s]

 83%|█████████████████████████████▉      | 35381/42525 [53:33<09:40, 12.30it/s]

 83%|█████████████████████████████▉      | 35385/42525 [53:34<10:54, 10.90it/s]

 83%|█████████████████████████████▉      | 35389/42525 [53:34<11:09, 10.66it/s]

 83%|█████████████████████████████▉      | 35393/42525 [53:34<10:46, 11.03it/s]

 83%|█████████████████████████████▉      | 35397/42525 [53:35<10:57, 10.84it/s]

 83%|█████████████████████████████▉      | 35401/42525 [53:35<10:28, 11.34it/s]

 83%|█████████████████████████████▉      | 35405/42525 [53:35<10:00, 11.86it/s]

 83%|█████████████████████████████▉      | 35409/42525 [53:36<09:34, 12.38it/s]

 83%|█████████████████████████████▉      | 35413/42525 [53:36<09:30, 12.48it/s]

 83%|█████████████████████████████▉      | 35417/42525 [53:36<09:19, 12.71it/s]

 83%|█████████████████████████████▉      | 35421/42525 [53:37<09:16, 12.77it/s]

 83%|█████████████████████████████▉      | 35425/42525 [53:37<09:49, 12.04it/s]

 83%|█████████████████████████████▉      | 35429/42525 [53:37<09:14, 12.80it/s]

 83%|█████████████████████████████▉      | 35433/42525 [53:38<09:24, 12.56it/s]

 83%|█████████████████████████████▉      | 35437/42525 [53:38<09:24, 12.55it/s]

 83%|██████████████████████████████      | 35441/42525 [53:38<09:57, 11.86it/s]

 83%|██████████████████████████████      | 35445/42525 [53:39<09:26, 12.50it/s]

 83%|██████████████████████████████      | 35449/42525 [53:39<09:36, 12.27it/s]

 83%|██████████████████████████████      | 35453/42525 [53:39<10:17, 11.45it/s]

 83%|██████████████████████████████      | 35457/42525 [53:40<09:35, 12.28it/s]

 83%|██████████████████████████████      | 35461/42525 [53:40<09:51, 11.94it/s]

 83%|██████████████████████████████      | 35463/42525 [53:40<09:39, 12.20it/s]

 83%|██████████████████████████████      | 35467/42525 [53:41<10:21, 11.36it/s]

 83%|██████████████████████████████      | 35471/42525 [53:41<09:33, 12.29it/s]

 83%|██████████████████████████████      | 35475/42525 [53:41<09:58, 11.78it/s]

 83%|██████████████████████████████      | 35479/42525 [53:41<09:19, 12.60it/s]

 83%|██████████████████████████████      | 35483/42525 [53:42<09:50, 11.93it/s]

 83%|██████████████████████████████      | 35487/42525 [53:42<10:10, 11.54it/s]

 83%|██████████████████████████████      | 35491/42525 [53:42<09:44, 12.03it/s]

 83%|██████████████████████████████      | 35493/42525 [53:43<10:00, 11.72it/s]

 83%|██████████████████████████████      | 35497/42525 [53:43<10:02, 11.67it/s]

 83%|██████████████████████████████      | 35501/42525 [53:43<09:15, 12.65it/s]

 83%|██████████████████████████████      | 35505/42525 [53:44<09:29, 12.32it/s]

 84%|██████████████████████████████      | 35509/42525 [53:44<09:53, 11.81it/s]

 84%|██████████████████████████████      | 35513/42525 [53:44<10:03, 11.62it/s]

 84%|██████████████████████████████      | 35517/42525 [53:45<09:59, 11.69it/s]

 84%|██████████████████████████████      | 35521/42525 [53:45<10:25, 11.19it/s]

 84%|██████████████████████████████      | 35525/42525 [53:45<10:12, 11.43it/s]

 84%|██████████████████████████████      | 35529/42525 [53:46<10:03, 11.59it/s]

 84%|██████████████████████████████      | 35533/42525 [53:46<10:03, 11.58it/s]

 84%|██████████████████████████████      | 35537/42525 [53:46<10:07, 11.51it/s]

 84%|██████████████████████████████      | 35541/42525 [53:47<10:26, 11.15it/s]

 84%|██████████████████████████████      | 35545/42525 [53:47<10:16, 11.33it/s]

 84%|██████████████████████████████      | 35549/42525 [53:48<10:13, 11.37it/s]

 84%|██████████████████████████████      | 35553/42525 [53:48<10:37, 10.93it/s]

 84%|██████████████████████████████      | 35557/42525 [53:48<10:24, 11.16it/s]

 84%|██████████████████████████████      | 35561/42525 [53:49<10:37, 10.92it/s]

 84%|██████████████████████████████      | 35565/42525 [53:49<10:27, 11.09it/s]

 84%|██████████████████████████████      | 35569/42525 [53:49<10:26, 11.11it/s]

 84%|██████████████████████████████      | 35573/42525 [53:50<10:19, 11.22it/s]

 84%|██████████████████████████████      | 35577/42525 [53:50<10:12, 11.35it/s]

 84%|██████████████████████████████      | 35581/42525 [53:50<10:20, 11.19it/s]

 84%|██████████████████████████████      | 35585/42525 [53:51<10:01, 11.53it/s]

 84%|██████████████████████████████▏     | 35587/42525 [53:51<09:58, 11.59it/s]

 84%|██████████████████████████████▏     | 35591/42525 [53:51<10:39, 10.85it/s]

 84%|██████████████████████████████▏     | 35595/42525 [53:52<10:23, 11.12it/s]

 84%|██████████████████████████████▏     | 35599/42525 [53:52<10:16, 11.23it/s]

 84%|██████████████████████████████▏     | 35603/42525 [53:52<09:57, 11.59it/s]

 84%|██████████████████████████████▏     | 35607/42525 [53:53<10:08, 11.38it/s]

 84%|██████████████████████████████▏     | 35611/42525 [53:53<10:09, 11.35it/s]

 84%|██████████████████████████████▏     | 35615/42525 [53:53<09:54, 11.63it/s]

 84%|██████████████████████████████▏     | 35619/42525 [53:54<09:55, 11.60it/s]

 84%|██████████████████████████████▏     | 35623/42525 [53:54<10:02, 11.45it/s]

 84%|██████████████████████████████▏     | 35627/42525 [53:54<10:27, 11.00it/s]

 84%|██████████████████████████████▏     | 35631/42525 [53:55<10:33, 10.89it/s]

 84%|██████████████████████████████▏     | 35635/42525 [53:55<10:18, 11.13it/s]

 84%|██████████████████████████████▏     | 35639/42525 [53:56<10:01, 11.44it/s]

 84%|██████████████████████████████▏     | 35643/42525 [53:56<09:50, 11.66it/s]

 84%|██████████████████████████████▏     | 35647/42525 [53:56<10:21, 11.06it/s]

 84%|██████████████████████████████▏     | 35651/42525 [53:57<10:15, 11.16it/s]

 84%|██████████████████████████████▏     | 35655/42525 [53:57<10:23, 11.01it/s]

 84%|██████████████████████████████▏     | 35659/42525 [53:57<10:34, 10.82it/s]

 84%|██████████████████████████████▏     | 35663/42525 [53:58<10:36, 10.78it/s]

 84%|██████████████████████████████▏     | 35667/42525 [53:58<10:10, 11.24it/s]

 84%|██████████████████████████████▏     | 35671/42525 [53:58<09:55, 11.50it/s]

 84%|██████████████████████████████▏     | 35675/42525 [53:59<10:01, 11.38it/s]

 84%|██████████████████████████████▏     | 35679/42525 [53:59<09:52, 11.56it/s]

 84%|██████████████████████████████▏     | 35683/42525 [53:59<09:56, 11.47it/s]

 84%|██████████████████████████████▏     | 35687/42525 [54:00<09:51, 11.55it/s]

 84%|██████████████████████████████▏     | 35691/42525 [54:00<10:26, 10.92it/s]

 84%|██████████████████████████████▏     | 35695/42525 [54:01<10:35, 10.76it/s]

 84%|██████████████████████████████▏     | 35699/42525 [54:01<10:37, 10.71it/s]

 84%|██████████████████████████████▏     | 35703/42525 [54:01<10:10, 11.17it/s]

 84%|██████████████████████████████▏     | 35707/42525 [54:02<10:15, 11.08it/s]

 84%|██████████████████████████████▏     | 35711/42525 [54:02<10:10, 11.16it/s]

 84%|██████████████████████████████▏     | 35715/42525 [54:02<10:18, 11.01it/s]

 84%|██████████████████████████████▏     | 35719/42525 [54:03<10:10, 11.15it/s]

 84%|██████████████████████████████▏     | 35723/42525 [54:03<10:03, 11.27it/s]

 84%|██████████████████████████████▏     | 35727/42525 [54:03<09:52, 11.48it/s]

 84%|██████████████████████████████▏     | 35731/42525 [54:04<09:41, 11.67it/s]

 84%|██████████████████████████████▎     | 35735/42525 [54:04<09:57, 11.37it/s]

 84%|██████████████████████████████▎     | 35739/42525 [54:04<10:32, 10.73it/s]

 84%|██████████████████████████████▎     | 35743/42525 [54:05<10:36, 10.66it/s]

 84%|██████████████████████████████▎     | 35747/42525 [54:05<10:37, 10.63it/s]

 84%|██████████████████████████████▎     | 35751/42525 [54:06<10:09, 11.11it/s]

 84%|██████████████████████████████▎     | 35755/42525 [54:06<10:10, 11.09it/s]

 84%|██████████████████████████████▎     | 35759/42525 [54:06<09:52, 11.41it/s]

 84%|██████████████████████████████▎     | 35761/42525 [54:06<10:05, 11.17it/s]

 84%|██████████████████████████████▎     | 35765/42525 [54:07<10:18, 10.93it/s]

 84%|██████████████████████████████▎     | 35769/42525 [54:07<10:02, 11.22it/s]

 84%|██████████████████████████████▎     | 35773/42525 [54:08<09:43, 11.57it/s]

 84%|██████████████████████████████▎     | 35777/42525 [54:08<10:01, 11.23it/s]

 84%|██████████████████████████████▎     | 35781/42525 [54:08<10:08, 11.09it/s]

 84%|██████████████████████████████▎     | 35785/42525 [54:09<09:51, 11.40it/s]

 84%|██████████████████████████████▎     | 35789/42525 [54:09<09:38, 11.63it/s]

 84%|██████████████████████████████▎     | 35793/42525 [54:09<09:45, 11.49it/s]

 84%|██████████████████████████████▎     | 35797/42525 [54:10<10:09, 11.04it/s]

 84%|██████████████████████████████▎     | 35801/42525 [54:10<10:09, 11.03it/s]

 84%|██████████████████████████████▎     | 35805/42525 [54:10<10:38, 10.52it/s]

 84%|██████████████████████████████▎     | 35809/42525 [54:11<10:28, 10.69it/s]

 84%|██████████████████████████████▎     | 35813/42525 [54:11<10:12, 10.96it/s]

 84%|██████████████████████████████▎     | 35817/42525 [54:12<09:50, 11.36it/s]

 84%|██████████████████████████████▎     | 35821/42525 [54:12<10:00, 11.16it/s]

 84%|██████████████████████████████▎     | 35825/42525 [54:12<09:57, 11.22it/s]

 84%|██████████████████████████████▎     | 35829/42525 [54:13<09:48, 11.37it/s]

 84%|██████████████████████████████▎     | 35833/42525 [54:13<09:34, 11.66it/s]

 84%|██████████████████████████████▎     | 35837/42525 [54:13<09:27, 11.78it/s]

 84%|██████████████████████████████▎     | 35841/42525 [54:14<09:30, 11.72it/s]

 84%|██████████████████████████████▎     | 35845/42525 [54:14<09:42, 11.46it/s]

 84%|██████████████████████████████▎     | 35849/42525 [54:14<09:30, 11.70it/s]

 84%|██████████████████████████████▎     | 35853/42525 [54:15<09:26, 11.79it/s]

 84%|██████████████████████████████▎     | 35857/42525 [54:15<09:50, 11.28it/s]

 84%|██████████████████████████████▎     | 35861/42525 [54:15<09:37, 11.53it/s]

 84%|██████████████████████████████▎     | 35865/42525 [54:16<09:55, 11.19it/s]

 84%|██████████████████████████████▎     | 35869/42525 [54:16<10:17, 10.78it/s]

 84%|██████████████████████████████▎     | 35873/42525 [54:16<10:00, 11.07it/s]

 84%|██████████████████████████████▎     | 35877/42525 [54:17<09:44, 11.37it/s]

 84%|██████████████████████████████▍     | 35881/42525 [54:17<10:22, 10.68it/s]

 84%|██████████████████████████████▍     | 35885/42525 [54:18<10:23, 10.65it/s]

 84%|██████████████████████████████▍     | 35889/42525 [54:18<10:00, 11.05it/s]

 84%|██████████████████████████████▍     | 35893/42525 [54:18<09:57, 11.09it/s]

 84%|██████████████████████████████▍     | 35897/42525 [54:19<09:50, 11.23it/s]

 84%|██████████████████████████████▍     | 35901/42525 [54:19<09:42, 11.38it/s]

 84%|██████████████████████████████▍     | 35905/42525 [54:19<09:49, 11.23it/s]

 84%|██████████████████████████████▍     | 35909/42525 [54:20<10:14, 10.77it/s]

 84%|██████████████████████████████▍     | 35913/42525 [54:20<10:06, 10.90it/s]

 84%|██████████████████████████████▍     | 35917/42525 [54:20<09:42, 11.35it/s]

 84%|██████████████████████████████▍     | 35921/42525 [54:21<10:13, 10.77it/s]

 84%|██████████████████████████████▍     | 35925/42525 [54:21<09:45, 11.27it/s]

 84%|██████████████████████████████▍     | 35929/42525 [54:21<09:38, 11.39it/s]

 84%|██████████████████████████████▍     | 35933/42525 [54:22<09:46, 11.24it/s]

 85%|██████████████████████████████▍     | 35937/42525 [54:22<09:32, 11.51it/s]

 85%|██████████████████████████████▍     | 35941/42525 [54:23<09:25, 11.65it/s]

 85%|██████████████████████████████▍     | 35945/42525 [54:23<09:21, 11.72it/s]

 85%|██████████████████████████████▍     | 35949/42525 [54:23<09:19, 11.76it/s]

 85%|██████████████████████████████▍     | 35953/42525 [54:24<09:28, 11.56it/s]

 85%|██████████████████████████████▍     | 35957/42525 [54:24<09:22, 11.68it/s]

 85%|██████████████████████████████▍     | 35961/42525 [54:24<09:18, 11.75it/s]

 85%|██████████████████████████████▍     | 35965/42525 [54:25<09:33, 11.43it/s]

 85%|██████████████████████████████▍     | 35969/42525 [54:25<10:08, 10.77it/s]

 85%|██████████████████████████████▍     | 35973/42525 [54:25<10:19, 10.57it/s]

 85%|██████████████████████████████▍     | 35977/42525 [54:26<09:44, 11.20it/s]

 85%|██████████████████████████████▍     | 35981/42525 [54:26<09:40, 11.28it/s]

 85%|██████████████████████████████▍     | 35985/42525 [54:26<09:46, 11.16it/s]

 85%|██████████████████████████████▍     | 35989/42525 [54:27<09:40, 11.26it/s]

 85%|██████████████████████████████▍     | 35993/42525 [54:27<09:24, 11.57it/s]

 85%|██████████████████████████████▍     | 35997/42525 [54:27<09:33, 11.39it/s]

 85%|██████████████████████████████▍     | 36001/42525 [54:28<09:38, 11.28it/s]

 85%|██████████████████████████████▍     | 36005/42525 [54:28<09:35, 11.33it/s]

 85%|██████████████████████████████▍     | 36009/42525 [54:29<09:38, 11.26it/s]

 85%|██████████████████████████████▍     | 36013/42525 [54:29<09:54, 10.96it/s]

 85%|██████████████████████████████▍     | 36017/42525 [54:29<09:44, 11.13it/s]

 85%|██████████████████████████████▍     | 36021/42525 [54:30<09:29, 11.42it/s]

 85%|██████████████████████████████▍     | 36025/42525 [54:30<09:36, 11.27it/s]

 85%|██████████████████████████████▌     | 36029/42525 [54:30<09:28, 11.43it/s]

 85%|██████████████████████████████▌     | 36033/42525 [54:31<09:35, 11.27it/s]

 85%|██████████████████████████████▌     | 36037/42525 [54:31<09:47, 11.05it/s]

 85%|██████████████████████████████▌     | 36041/42525 [54:31<10:00, 10.81it/s]

 85%|██████████████████████████████▌     | 36045/42525 [54:32<09:50, 10.97it/s]

 85%|██████████████████████████████▌     | 36049/42525 [54:32<09:28, 11.40it/s]

 85%|██████████████████████████████▌     | 36053/42525 [54:32<09:45, 11.06it/s]

 85%|██████████████████████████████▌     | 36055/42525 [54:33<09:38, 11.18it/s]

 85%|██████████████████████████████▌     | 36059/42525 [54:33<10:10, 10.59it/s]

 85%|██████████████████████████████▌     | 36063/42525 [54:33<10:04, 10.69it/s]

 85%|██████████████████████████████▌     | 36067/42525 [54:34<09:41, 11.10it/s]

 85%|██████████████████████████████▌     | 36071/42525 [54:34<09:20, 11.51it/s]

 85%|██████████████████████████████▌     | 36075/42525 [54:34<09:10, 11.73it/s]

 85%|██████████████████████████████▌     | 36079/42525 [54:35<09:45, 11.00it/s]

 85%|██████████████████████████████▌     | 36083/42525 [54:35<09:35, 11.18it/s]

 85%|██████████████████████████████▌     | 36087/42525 [54:36<09:20, 11.48it/s]

 85%|██████████████████████████████▌     | 36091/42525 [54:36<09:07, 11.76it/s]

 85%|██████████████████████████████▌     | 36095/42525 [54:36<09:02, 11.85it/s]

 85%|██████████████████████████████▌     | 36099/42525 [54:37<09:06, 11.75it/s]

 85%|██████████████████████████████▌     | 36103/42525 [54:37<09:27, 11.32it/s]

 85%|██████████████████████████████▌     | 36107/42525 [54:37<09:32, 11.21it/s]

 85%|██████████████████████████████▌     | 36111/42525 [54:38<08:43, 12.26it/s]

 85%|██████████████████████████████▌     | 36115/42525 [54:38<08:56, 11.95it/s]

 85%|██████████████████████████████▌     | 36119/42525 [54:38<08:49, 12.09it/s]

 85%|██████████████████████████████▌     | 36121/42525 [54:38<08:42, 12.24it/s]

 85%|██████████████████████████████▌     | 36125/42525 [54:39<09:00, 11.83it/s]

 85%|██████████████████████████████▌     | 36129/42525 [54:39<09:07, 11.69it/s]

 85%|██████████████████████████████▌     | 36133/42525 [54:39<08:45, 12.15it/s]

 85%|██████████████████████████████▌     | 36137/42525 [54:40<08:36, 12.38it/s]

 85%|██████████████████████████████▌     | 36141/42525 [54:40<09:28, 11.24it/s]

 85%|██████████████████████████████▌     | 36145/42525 [54:40<09:42, 10.95it/s]

 85%|██████████████████████████████▌     | 36149/42525 [54:41<09:36, 11.06it/s]

 85%|██████████████████████████████▌     | 36153/42525 [54:41<09:38, 11.01it/s]

 85%|██████████████████████████████▌     | 36157/42525 [54:42<09:19, 11.38it/s]

 85%|██████████████████████████████▌     | 36161/42525 [54:42<09:23, 11.29it/s]

 85%|██████████████████████████████▌     | 36165/42525 [54:42<09:50, 10.77it/s]

 85%|██████████████████████████████▌     | 36169/42525 [54:43<09:34, 11.07it/s]

 85%|██████████████████████████████▌     | 36171/42525 [54:43<09:45, 10.86it/s]

 85%|██████████████████████████████▌     | 36175/42525 [54:43<09:54, 10.67it/s]

 85%|██████████████████████████████▋     | 36179/42525 [54:44<09:54, 10.68it/s]

 85%|██████████████████████████████▋     | 36183/42525 [54:44<09:45, 10.82it/s]

 85%|██████████████████████████████▋     | 36187/42525 [54:44<09:51, 10.71it/s]

 85%|██████████████████████████████▋     | 36189/42525 [54:45<09:38, 10.96it/s]

 85%|██████████████████████████████▋     | 36193/42525 [54:45<09:53, 10.68it/s]

 85%|██████████████████████████████▋     | 36197/42525 [54:45<09:25, 11.19it/s]

 85%|██████████████████████████████▋     | 36201/42525 [54:46<09:23, 11.23it/s]

 85%|██████████████████████████████▋     | 36205/42525 [54:46<09:36, 10.96it/s]

 85%|██████████████████████████████▋     | 36209/42525 [54:46<09:29, 11.08it/s]

 85%|██████████████████████████████▋     | 36213/42525 [54:47<09:42, 10.83it/s]

 85%|██████████████████████████████▋     | 36217/42525 [54:47<09:40, 10.86it/s]

 85%|██████████████████████████████▋     | 36221/42525 [54:47<09:31, 11.02it/s]

 85%|██████████████████████████████▋     | 36225/42525 [54:48<09:41, 10.83it/s]

 85%|██████████████████████████████▋     | 36229/42525 [54:48<09:16, 11.32it/s]

 85%|██████████████████████████████▋     | 36233/42525 [54:49<09:29, 11.05it/s]

 85%|██████████████████████████████▋     | 36237/42525 [54:49<09:15, 11.32it/s]

 85%|██████████████████████████████▋     | 36241/42525 [54:49<09:27, 11.07it/s]

 85%|██████████████████████████████▋     | 36245/42525 [54:50<09:16, 11.29it/s]

 85%|██████████████████████████████▋     | 36249/42525 [54:50<09:01, 11.58it/s]

 85%|██████████████████████████████▋     | 36253/42525 [54:50<09:06, 11.48it/s]

 85%|██████████████████████████████▋     | 36257/42525 [54:51<09:17, 11.24it/s]

 85%|██████████████████████████████▋     | 36261/42525 [54:51<09:04, 11.50it/s]

 85%|██████████████████████████████▋     | 36265/42525 [54:51<09:10, 11.38it/s]

 85%|██████████████████████████████▋     | 36269/42525 [54:52<09:00, 11.58it/s]

 85%|██████████████████████████████▋     | 36273/42525 [54:52<09:14, 11.27it/s]

 85%|██████████████████████████████▋     | 36277/42525 [54:52<09:10, 11.35it/s]

 85%|██████████████████████████████▋     | 36281/42525 [54:53<09:01, 11.53it/s]

 85%|██████████████████████████████▋     | 36285/42525 [54:53<09:04, 11.46it/s]

 85%|██████████████████████████████▋     | 36289/42525 [54:53<08:55, 11.64it/s]

 85%|██████████████████████████████▋     | 36293/42525 [54:54<09:14, 11.24it/s]

 85%|██████████████████████████████▋     | 36297/42525 [54:54<09:16, 11.19it/s]

 85%|██████████████████████████████▋     | 36299/42525 [54:54<09:08, 11.34it/s]

 85%|██████████████████████████████▋     | 36303/42525 [54:55<09:25, 11.00it/s]

 85%|██████████████████████████████▋     | 36307/42525 [54:55<09:34, 10.83it/s]

 85%|██████████████████████████████▋     | 36311/42525 [54:55<09:11, 11.26it/s]

 85%|██████████████████████████████▋     | 36315/42525 [54:56<09:03, 11.42it/s]

 85%|██████████████████████████████▋     | 36319/42525 [54:56<09:01, 11.45it/s]

 85%|██████████████████████████████▋     | 36323/42525 [54:56<08:52, 11.65it/s]

 85%|██████████████████████████████▊     | 36327/42525 [54:57<08:49, 11.71it/s]

 85%|██████████████████████████████▊     | 36331/42525 [54:57<09:08, 11.30it/s]

 85%|██████████████████████████████▊     | 36335/42525 [54:58<09:13, 11.18it/s]

 85%|██████████████████████████████▊     | 36339/42525 [54:58<09:04, 11.37it/s]

 85%|██████████████████████████████▊     | 36343/42525 [54:58<09:12, 11.19it/s]

 85%|██████████████████████████████▊     | 36347/42525 [54:59<09:18, 11.06it/s]

 85%|██████████████████████████████▊     | 36351/42525 [54:59<09:07, 11.28it/s]

 85%|██████████████████████████████▊     | 36355/42525 [54:59<09:01, 11.40it/s]

 86%|██████████████████████████████▊     | 36359/42525 [55:00<09:07, 11.26it/s]

 86%|██████████████████████████████▊     | 36363/42525 [55:00<09:06, 11.27it/s]

 86%|██████████████████████████████▊     | 36367/42525 [55:00<09:01, 11.38it/s]

 86%|██████████████████████████████▊     | 36371/42525 [55:01<09:05, 11.28it/s]

 86%|██████████████████████████████▊     | 36375/42525 [55:01<08:58, 11.43it/s]

 86%|██████████████████████████████▊     | 36379/42525 [55:01<09:11, 11.15it/s]

 86%|██████████████████████████████▊     | 36383/42525 [55:02<09:35, 10.68it/s]

 86%|██████████████████████████████▊     | 36387/42525 [55:02<09:34, 10.68it/s]

 86%|██████████████████████████████▊     | 36391/42525 [55:03<09:11, 11.11it/s]

 86%|██████████████████████████████▊     | 36395/42525 [55:03<09:13, 11.07it/s]

 86%|██████████████████████████████▊     | 36397/42525 [55:03<09:04, 11.25it/s]

 86%|██████████████████████████████▊     | 36401/42525 [55:03<09:23, 10.87it/s]

 86%|██████████████████████████████▊     | 36405/42525 [55:04<09:08, 11.15it/s]

 86%|██████████████████████████████▊     | 36409/42525 [55:04<09:08, 11.16it/s]

 86%|██████████████████████████████▊     | 36413/42525 [55:05<09:34, 10.63it/s]

 86%|██████████████████████████████▊     | 36417/42525 [55:05<09:16, 10.98it/s]

 86%|██████████████████████████████▊     | 36421/42525 [55:05<08:54, 11.42it/s]

 86%|██████████████████████████████▊     | 36425/42525 [55:06<09:13, 11.02it/s]

 86%|██████████████████████████████▊     | 36429/42525 [55:06<09:02, 11.23it/s]

 86%|██████████████████████████████▊     | 36433/42525 [55:06<09:20, 10.86it/s]

 86%|██████████████████████████████▊     | 36437/42525 [55:07<09:17, 10.92it/s]

 86%|██████████████████████████████▊     | 36441/42525 [55:07<09:26, 10.73it/s]

 86%|██████████████████████████████▊     | 36445/42525 [55:07<09:01, 11.23it/s]

 86%|██████████████████████████████▊     | 36449/42525 [55:08<09:06, 11.11it/s]

 86%|██████████████████████████████▊     | 36453/42525 [55:08<09:01, 11.21it/s]

 86%|██████████████████████████████▊     | 36457/42525 [55:09<08:54, 11.35it/s]

 86%|██████████████████████████████▊     | 36461/42525 [55:09<08:52, 11.38it/s]

 86%|██████████████████████████████▊     | 36465/42525 [55:09<09:05, 11.11it/s]

 86%|██████████████████████████████▊     | 36467/42525 [55:09<09:20, 10.82it/s]

 86%|██████████████████████████████▊     | 36471/42525 [55:10<09:20, 10.81it/s]

 86%|██████████████████████████████▉     | 36475/42525 [55:10<08:55, 11.30it/s]

 86%|██████████████████████████████▉     | 36479/42525 [55:10<08:51, 11.36it/s]

 86%|██████████████████████████████▉     | 36483/42525 [55:11<08:41, 11.58it/s]

 86%|██████████████████████████████▉     | 36487/42525 [55:11<08:49, 11.41it/s]

 86%|██████████████████████████████▉     | 36491/42525 [55:12<09:08, 11.00it/s]

 86%|██████████████████████████████▉     | 36495/42525 [55:12<09:05, 11.06it/s]

 86%|██████████████████████████████▉     | 36499/42525 [55:12<09:04, 11.06it/s]

 86%|██████████████████████████████▉     | 36503/42525 [55:13<09:09, 10.96it/s]

 86%|██████████████████████████████▉     | 36507/42525 [55:13<09:15, 10.83it/s]

 86%|██████████████████████████████▉     | 36511/42525 [55:13<09:03, 11.06it/s]

 86%|██████████████████████████████▉     | 36515/42525 [55:14<09:14, 10.83it/s]

 86%|██████████████████████████████▉     | 36519/42525 [55:14<09:22, 10.68it/s]

 86%|██████████████████████████████▉     | 36523/42525 [55:14<09:01, 11.08it/s]

 86%|██████████████████████████████▉     | 36527/42525 [55:15<09:09, 10.92it/s]

 86%|██████████████████████████████▉     | 36531/42525 [55:15<08:54, 11.22it/s]

 86%|██████████████████████████████▉     | 36535/42525 [55:16<08:59, 11.10it/s]

 86%|██████████████████████████████▉     | 36539/42525 [55:16<08:47, 11.35it/s]

 86%|██████████████████████████████▉     | 36543/42525 [55:16<09:04, 10.98it/s]

 86%|██████████████████████████████▉     | 36545/42525 [55:16<08:57, 11.13it/s]

 86%|██████████████████████████████▉     | 36549/42525 [55:17<09:10, 10.85it/s]

 86%|██████████████████████████████▉     | 36553/42525 [55:17<08:53, 11.19it/s]

 86%|██████████████████████████████▉     | 36557/42525 [55:18<08:54, 11.18it/s]

 86%|██████████████████████████████▉     | 36561/42525 [55:18<09:14, 10.76it/s]

 86%|██████████████████████████████▉     | 36565/42525 [55:18<08:49, 11.26it/s]

 86%|██████████████████████████████▉     | 36569/42525 [55:19<08:33, 11.61it/s]

 86%|██████████████████████████████▉     | 36573/42525 [55:19<08:27, 11.72it/s]

 86%|██████████████████████████████▉     | 36577/42525 [55:19<08:29, 11.68it/s]

 86%|██████████████████████████████▉     | 36581/42525 [55:20<08:48, 11.25it/s]

 86%|██████████████████████████████▉     | 36585/42525 [55:20<08:49, 11.22it/s]

 86%|██████████████████████████████▉     | 36589/42525 [55:20<08:47, 11.26it/s]

 86%|██████████████████████████████▉     | 36593/42525 [55:21<09:06, 10.85it/s]

 86%|██████████████████████████████▉     | 36597/42525 [55:21<08:47, 11.25it/s]

 86%|██████████████████████████████▉     | 36601/42525 [55:21<08:56, 11.05it/s]

 86%|██████████████████████████████▉     | 36605/42525 [55:22<09:01, 10.94it/s]

 86%|██████████████████████████████▉     | 36609/42525 [55:22<09:09, 10.77it/s]

 86%|██████████████████████████████▉     | 36613/42525 [55:23<08:45, 11.24it/s]

 86%|██████████████████████████████▉     | 36617/42525 [55:23<08:39, 11.38it/s]

 86%|███████████████████████████████     | 36621/42525 [55:23<08:42, 11.30it/s]

 86%|███████████████████████████████     | 36625/42525 [55:24<08:39, 11.36it/s]

 86%|███████████████████████████████     | 36629/42525 [55:24<08:33, 11.47it/s]

 86%|███████████████████████████████     | 36633/42525 [55:24<08:45, 11.22it/s]

 86%|███████████████████████████████     | 36637/42525 [55:25<09:11, 10.69it/s]

 86%|███████████████████████████████     | 36641/42525 [55:25<08:48, 11.13it/s]

 86%|███████████████████████████████     | 36645/42525 [55:25<08:53, 11.02it/s]

 86%|███████████████████████████████     | 36649/42525 [55:26<08:37, 11.36it/s]

 86%|███████████████████████████████     | 36653/42525 [55:26<08:48, 11.11it/s]

 86%|███████████████████████████████     | 36657/42525 [55:26<08:36, 11.37it/s]

 86%|███████████████████████████████     | 36661/42525 [55:27<08:40, 11.27it/s]

 86%|███████████████████████████████     | 36665/42525 [55:27<08:32, 11.43it/s]

 86%|███████████████████████████████     | 36669/42525 [55:28<08:26, 11.56it/s]

 86%|███████████████████████████████     | 36673/42525 [55:28<08:30, 11.46it/s]

 86%|███████████████████████████████     | 36677/42525 [55:28<08:45, 11.14it/s]

 86%|███████████████████████████████     | 36681/42525 [55:29<08:50, 11.01it/s]

 86%|███████████████████████████████     | 36685/42525 [55:29<08:59, 10.83it/s]

 86%|███████████████████████████████     | 36689/42525 [55:29<08:55, 10.90it/s]

 86%|███████████████████████████████     | 36693/42525 [55:30<09:01, 10.77it/s]

 86%|███████████████████████████████     | 36697/42525 [55:30<09:07, 10.65it/s]

 86%|███████████████████████████████     | 36701/42525 [55:30<09:06, 10.66it/s]

 86%|███████████████████████████████     | 36705/42525 [55:31<08:55, 10.86it/s]

 86%|███████████████████████████████     | 36709/42525 [55:31<08:47, 11.03it/s]

 86%|███████████████████████████████     | 36713/42525 [55:32<09:07, 10.62it/s]

 86%|███████████████████████████████     | 36717/42525 [55:32<08:38, 11.19it/s]

 86%|███████████████████████████████     | 36721/42525 [55:32<08:25, 11.47it/s]

 86%|███████████████████████████████     | 36725/42525 [55:33<08:39, 11.16it/s]

 86%|███████████████████████████████     | 36729/42525 [55:33<08:42, 11.10it/s]

 86%|███████████████████████████████     | 36733/42525 [55:33<08:25, 11.45it/s]

 86%|███████████████████████████████     | 36737/42525 [55:34<08:27, 11.40it/s]

 86%|███████████████████████████████     | 36741/42525 [55:34<08:18, 11.60it/s]

 86%|███████████████████████████████     | 36745/42525 [55:34<07:56, 12.13it/s]

 86%|███████████████████████████████     | 36749/42525 [55:35<07:55, 12.15it/s]

 86%|███████████████████████████████     | 36753/42525 [55:35<08:22, 11.49it/s]

 86%|███████████████████████████████     | 36757/42525 [55:35<08:51, 10.86it/s]

 86%|███████████████████████████████     | 36761/42525 [55:36<08:43, 11.01it/s]

 86%|███████████████████████████████     | 36765/42525 [55:36<08:50, 10.86it/s]

 86%|███████████████████████████████▏    | 36769/42525 [55:36<08:16, 11.60it/s]

 86%|███████████████████████████████▏    | 36773/42525 [55:37<08:18, 11.54it/s]

 86%|███████████████████████████████▏    | 36777/42525 [55:37<08:06, 11.81it/s]

 86%|███████████████████████████████▏    | 36781/42525 [55:37<07:30, 12.75it/s]

 87%|███████████████████████████████▏    | 36785/42525 [55:38<07:59, 11.98it/s]

 87%|███████████████████████████████▏    | 36789/42525 [55:38<07:37, 12.53it/s]

 87%|███████████████████████████████▏    | 36793/42525 [55:38<08:18, 11.51it/s]

 87%|███████████████████████████████▏    | 36797/42525 [55:39<08:11, 11.66it/s]

 87%|███████████████████████████████▏    | 36801/42525 [55:39<08:36, 11.08it/s]

 87%|███████████████████████████████▏    | 36805/42525 [55:40<08:21, 11.40it/s]

 87%|███████████████████████████████▏    | 36809/42525 [55:40<08:17, 11.49it/s]

 87%|███████████████████████████████▏    | 36813/42525 [55:40<08:15, 11.54it/s]

 87%|███████████████████████████████▏    | 36817/42525 [55:41<08:32, 11.14it/s]

 87%|███████████████████████████████▏    | 36821/42525 [55:41<08:32, 11.12it/s]

 87%|███████████████████████████████▏    | 36825/42525 [55:41<08:17, 11.45it/s]

 87%|███████████████████████████████▏    | 36829/42525 [55:42<08:23, 11.32it/s]

 87%|███████████████████████████████▏    | 36833/42525 [55:42<08:38, 10.98it/s]

 87%|███████████████████████████████▏    | 36837/42525 [55:42<08:25, 11.26it/s]

 87%|███████████████████████████████▏    | 36841/42525 [55:43<08:15, 11.46it/s]

 87%|███████████████████████████████▏    | 36845/42525 [55:43<07:42, 12.29it/s]

 87%|███████████████████████████████▏    | 36849/42525 [55:43<07:55, 11.94it/s]

 87%|███████████████████████████████▏    | 36853/42525 [55:44<07:47, 12.13it/s]

 87%|███████████████████████████████▏    | 36857/42525 [55:44<07:57, 11.87it/s]

 87%|███████████████████████████████▏    | 36861/42525 [55:44<08:18, 11.37it/s]

 87%|███████████████████████████████▏    | 36865/42525 [55:45<07:40, 12.29it/s]

 87%|███████████████████████████████▏    | 36869/42525 [55:45<08:18, 11.34it/s]

 87%|███████████████████████████████▏    | 36873/42525 [55:45<07:56, 11.85it/s]

 87%|███████████████████████████████▏    | 36877/42525 [55:46<07:52, 11.96it/s]

 87%|███████████████████████████████▏    | 36881/42525 [55:46<08:00, 11.75it/s]

 87%|███████████████████████████████▏    | 36885/42525 [55:46<08:15, 11.38it/s]

 87%|███████████████████████████████▏    | 36889/42525 [55:47<08:20, 11.26it/s]

 87%|███████████████████████████████▏    | 36893/42525 [55:47<08:23, 11.20it/s]

 87%|███████████████████████████████▏    | 36897/42525 [55:48<08:37, 10.87it/s]

 87%|███████████████████████████████▏    | 36901/42525 [55:48<08:28, 11.06it/s]

 87%|███████████████████████████████▏    | 36905/42525 [55:48<08:11, 11.44it/s]

 87%|███████████████████████████████▏    | 36909/42525 [55:49<08:17, 11.29it/s]

 87%|███████████████████████████████▏    | 36913/42525 [55:49<08:22, 11.17it/s]

 87%|███████████████████████████████▎    | 36917/42525 [55:49<08:10, 11.43it/s]

 87%|███████████████████████████████▎    | 36921/42525 [55:50<08:04, 11.58it/s]

 87%|███████████████████████████████▎    | 36925/42525 [55:50<08:26, 11.05it/s]

 87%|███████████████████████████████▎    | 36929/42525 [55:50<08:32, 10.93it/s]

 87%|███████████████████████████████▎    | 36933/42525 [55:51<08:19, 11.19it/s]

 87%|███████████████████████████████▎    | 36937/42525 [55:51<08:12, 11.34it/s]

 87%|███████████████████████████████▎    | 36941/42525 [55:51<08:24, 11.07it/s]

 87%|███████████████████████████████▎    | 36943/42525 [55:52<08:25, 11.04it/s]

 87%|███████████████████████████████▎    | 36947/42525 [55:52<08:37, 10.78it/s]

 87%|███████████████████████████████▎    | 36951/42525 [55:52<08:23, 11.08it/s]

 87%|███████████████████████████████▎    | 36955/42525 [55:53<08:09, 11.39it/s]

 87%|███████████████████████████████▎    | 36959/42525 [55:53<08:34, 10.82it/s]

 87%|███████████████████████████████▎    | 36963/42525 [55:53<08:20, 11.12it/s]

 87%|███████████████████████████████▎    | 36967/42525 [55:54<08:08, 11.38it/s]

 87%|███████████████████████████████▎    | 36971/42525 [55:54<08:02, 11.51it/s]

 87%|███████████████████████████████▎    | 36975/42525 [55:54<08:24, 11.01it/s]

 87%|███████████████████████████████▎    | 36979/42525 [55:55<08:29, 10.88it/s]

 87%|███████████████████████████████▎    | 36983/42525 [55:55<08:23, 11.02it/s]

 87%|███████████████████████████████▎    | 36987/42525 [55:56<08:22, 11.01it/s]

 87%|███████████████████████████████▎    | 36991/42525 [55:56<08:15, 11.17it/s]

 87%|███████████████████████████████▎    | 36995/42525 [55:56<08:17, 11.11it/s]

 87%|███████████████████████████████▎    | 36999/42525 [55:57<08:19, 11.05it/s]

 87%|███████████████████████████████▎    | 37003/42525 [55:57<08:21, 11.01it/s]

 87%|███████████████████████████████▎    | 37007/42525 [55:57<08:20, 11.03it/s]

 87%|███████████████████████████████▎    | 37011/42525 [55:58<08:15, 11.14it/s]

 87%|███████████████████████████████▎    | 37015/42525 [55:58<08:04, 11.37it/s]

 87%|███████████████████████████████▎    | 37019/42525 [55:58<07:58, 11.52it/s]

 87%|███████████████████████████████▎    | 37023/42525 [55:59<07:54, 11.60it/s]

 87%|███████████████████████████████▎    | 37027/42525 [55:59<08:02, 11.39it/s]

 87%|███████████████████████████████▎    | 37031/42525 [55:59<08:20, 10.98it/s]

 87%|███████████████████████████████▎    | 37035/42525 [56:00<08:17, 11.04it/s]

 87%|███████████████████████████████▎    | 37039/42525 [56:00<08:04, 11.32it/s]

 87%|███████████████████████████████▎    | 37043/42525 [56:01<07:55, 11.53it/s]

 87%|███████████████████████████████▎    | 37047/42525 [56:01<07:44, 11.81it/s]

 87%|███████████████████████████████▎    | 37051/42525 [56:01<07:25, 12.30it/s]

 87%|███████████████████████████████▎    | 37055/42525 [56:02<07:21, 12.38it/s]

 87%|███████████████████████████████▎    | 37059/42525 [56:02<07:24, 12.31it/s]

 87%|███████████████████████████████▍    | 37063/42525 [56:02<07:56, 11.46it/s]

 87%|███████████████████████████████▍    | 37067/42525 [56:03<08:06, 11.22it/s]

 87%|███████████████████████████████▍    | 37071/42525 [56:03<08:18, 10.94it/s]

 87%|███████████████████████████████▍    | 37075/42525 [56:03<08:00, 11.34it/s]

 87%|███████████████████████████████▍    | 37079/42525 [56:04<07:51, 11.56it/s]

 87%|███████████████████████████████▍    | 37083/42525 [56:04<07:45, 11.70it/s]

 87%|███████████████████████████████▍    | 37087/42525 [56:04<07:56, 11.40it/s]

 87%|███████████████████████████████▍    | 37091/42525 [56:05<08:31, 10.62it/s]

 87%|███████████████████████████████▍    | 37095/42525 [56:05<08:14, 10.98it/s]

 87%|███████████████████████████████▍    | 37099/42525 [56:05<08:05, 11.18it/s]

 87%|███████████████████████████████▍    | 37103/42525 [56:06<07:55, 11.41it/s]

 87%|███████████████████████████████▍    | 37107/42525 [56:06<07:46, 11.62it/s]

 87%|███████████████████████████████▍    | 37111/42525 [56:06<08:06, 11.12it/s]

 87%|███████████████████████████████▍    | 37115/42525 [56:07<07:51, 11.46it/s]

 87%|███████████████████████████████▍    | 37119/42525 [56:07<07:43, 11.67it/s]

 87%|███████████████████████████████▍    | 37123/42525 [56:08<07:54, 11.39it/s]

 87%|███████████████████████████████▍    | 37127/42525 [56:08<07:47, 11.55it/s]

 87%|███████████████████████████████▍    | 37131/42525 [56:08<07:46, 11.56it/s]

 87%|███████████████████████████████▍    | 37135/42525 [56:09<07:46, 11.54it/s]

 87%|███████████████████████████████▍    | 37139/42525 [56:09<08:01, 11.18it/s]

 87%|███████████████████████████████▍    | 37143/42525 [56:09<08:02, 11.14it/s]

 87%|███████████████████████████████▍    | 37147/42525 [56:10<08:08, 11.01it/s]

 87%|███████████████████████████████▍    | 37151/42525 [56:10<07:52, 11.38it/s]

 87%|███████████████████████████████▍    | 37155/42525 [56:10<07:50, 11.41it/s]

 87%|███████████████████████████████▍    | 37159/42525 [56:11<07:49, 11.43it/s]

 87%|███████████████████████████████▍    | 37163/42525 [56:11<07:43, 11.56it/s]

 87%|███████████████████████████████▍    | 37167/42525 [56:11<08:01, 11.12it/s]

 87%|███████████████████████████████▍    | 37171/42525 [56:12<08:09, 10.94it/s]

 87%|███████████████████████████████▍    | 37175/42525 [56:12<08:13, 10.84it/s]

 87%|███████████████████████████████▍    | 37179/42525 [56:13<08:08, 10.95it/s]

 87%|███████████████████████████████▍    | 37183/42525 [56:13<08:00, 11.12it/s]

 87%|███████████████████████████████▍    | 37187/42525 [56:13<07:53, 11.27it/s]

 87%|███████████████████████████████▍    | 37191/42525 [56:14<07:39, 11.60it/s]

 87%|███████████████████████████████▍    | 37195/42525 [56:14<07:30, 11.82it/s]

 87%|███████████████████████████████▍    | 37199/42525 [56:14<07:26, 11.94it/s]

 87%|███████████████████████████████▍    | 37203/42525 [56:15<07:15, 12.21it/s]

 87%|███████████████████████████████▍    | 37207/42525 [56:15<07:39, 11.59it/s]

 88%|███████████████████████████████▌    | 37211/42525 [56:15<07:19, 12.10it/s]

 88%|███████████████████████████████▌    | 37215/42525 [56:16<06:59, 12.65it/s]

 88%|███████████████████████████████▌    | 37219/42525 [56:16<07:02, 12.55it/s]

 88%|███████████████████████████████▌    | 37223/42525 [56:16<06:42, 13.16it/s]

 88%|███████████████████████████████▌    | 37225/42525 [56:16<07:14, 12.18it/s]

 88%|███████████████████████████████▌    | 37229/42525 [56:17<07:58, 11.06it/s]

 88%|███████████████████████████████▌    | 37233/42525 [56:17<07:57, 11.08it/s]

 88%|███████████████████████████████▌    | 37237/42525 [56:17<07:44, 11.38it/s]

 88%|███████████████████████████████▌    | 37241/42525 [56:18<08:01, 10.98it/s]

 88%|███████████████████████████████▌    | 37245/42525 [56:18<08:18, 10.59it/s]

 88%|███████████████████████████████▌    | 37249/42525 [56:19<08:24, 10.46it/s]

 88%|███████████████████████████████▌    | 37251/42525 [56:19<08:09, 10.78it/s]

 88%|███████████████████████████████▌    | 37255/42525 [56:19<08:26, 10.41it/s]

 88%|███████████████████████████████▌    | 37259/42525 [56:20<07:59, 10.98it/s]

 88%|███████████████████████████████▌    | 37263/42525 [56:20<07:49, 11.20it/s]

 88%|███████████████████████████████▌    | 37267/42525 [56:20<08:11, 10.70it/s]

 88%|███████████████████████████████▌    | 37271/42525 [56:21<08:16, 10.57it/s]

 88%|███████████████████████████████▌    | 37275/42525 [56:21<08:09, 10.71it/s]

 88%|███████████████████████████████▌    | 37279/42525 [56:21<08:19, 10.50it/s]

 88%|███████████████████████████████▌    | 37283/42525 [56:22<08:03, 10.84it/s]

 88%|███████████████████████████████▌    | 37287/42525 [56:22<07:44, 11.29it/s]

 88%|███████████████████████████████▌    | 37291/42525 [56:22<07:52, 11.08it/s]

 88%|███████████████████████████████▌    | 37295/42525 [56:23<07:36, 11.45it/s]

 88%|███████████████████████████████▌    | 37299/42525 [56:23<07:38, 11.40it/s]

 88%|███████████████████████████████▌    | 37303/42525 [56:24<07:40, 11.35it/s]

 88%|███████████████████████████████▌    | 37307/42525 [56:24<07:34, 11.49it/s]

 88%|███████████████████████████████▌    | 37311/42525 [56:24<07:27, 11.66it/s]

 88%|███████████████████████████████▌    | 37315/42525 [56:25<07:27, 11.64it/s]

 88%|███████████████████████████████▌    | 37319/42525 [56:25<07:42, 11.26it/s]

 88%|███████████████████████████████▌    | 37323/42525 [56:25<07:49, 11.07it/s]

 88%|███████████████████████████████▌    | 37327/42525 [56:26<08:08, 10.65it/s]

 88%|███████████████████████████████▌    | 37331/42525 [56:26<07:57, 10.89it/s]

 88%|███████████████████████████████▌    | 37335/42525 [56:26<07:44, 11.16it/s]

 88%|███████████████████████████████▌    | 37339/42525 [56:27<07:36, 11.36it/s]

 88%|███████████████████████████████▌    | 37343/42525 [56:27<07:37, 11.33it/s]

 88%|███████████████████████████████▌    | 37347/42525 [56:27<07:47, 11.08it/s]

 88%|███████████████████████████████▌    | 37351/42525 [56:28<07:38, 11.28it/s]

 88%|███████████████████████████████▌    | 37355/42525 [56:28<07:24, 11.63it/s]

 88%|███████████████████████████████▋    | 37359/42525 [56:28<07:21, 11.70it/s]

 88%|███████████████████████████████▋    | 37363/42525 [56:29<07:22, 11.66it/s]

 88%|███████████████████████████████▋    | 37367/42525 [56:29<07:32, 11.39it/s]

 88%|███████████████████████████████▋    | 37371/42525 [56:30<07:32, 11.40it/s]

 88%|███████████████████████████████▋    | 37375/42525 [56:30<07:41, 11.17it/s]

 88%|███████████████████████████████▋    | 37379/42525 [56:30<07:39, 11.19it/s]

 88%|███████████████████████████████▋    | 37383/42525 [56:31<07:43, 11.09it/s]

 88%|███████████████████████████████▋    | 37387/42525 [56:31<08:00, 10.69it/s]

 88%|███████████████████████████████▋    | 37391/42525 [56:31<07:45, 11.03it/s]

 88%|███████████████████████████████▋    | 37395/42525 [56:32<07:29, 11.41it/s]

 88%|███████████████████████████████▋    | 37399/42525 [56:32<07:37, 11.21it/s]

 88%|███████████████████████████████▋    | 37403/42525 [56:32<07:45, 11.00it/s]

 88%|███████████████████████████████▋    | 37407/42525 [56:33<07:38, 11.16it/s]

 88%|███████████████████████████████▋    | 37411/42525 [56:33<07:26, 11.44it/s]

 88%|███████████████████████████████▋    | 37415/42525 [56:33<07:21, 11.56it/s]

 88%|███████████████████████████████▋    | 37419/42525 [56:34<07:22, 11.55it/s]

 88%|███████████████████████████████▋    | 37423/42525 [56:34<07:23, 11.50it/s]

 88%|███████████████████████████████▋    | 37427/42525 [56:35<07:30, 11.32it/s]

 88%|███████████████████████████████▋    | 37431/42525 [56:35<07:25, 11.43it/s]

 88%|███████████████████████████████▋    | 37435/42525 [56:35<07:19, 11.58it/s]

 88%|███████████████████████████████▋    | 37439/42525 [56:36<07:26, 11.39it/s]

 88%|███████████████████████████████▋    | 37443/42525 [56:36<07:35, 11.15it/s]

 88%|███████████████████████████████▋    | 37447/42525 [56:36<07:04, 11.95it/s]

 88%|███████████████████████████████▋    | 37451/42525 [56:37<07:20, 11.52it/s]

 88%|███████████████████████████████▋    | 37455/42525 [56:37<07:21, 11.48it/s]

 88%|███████████████████████████████▋    | 37459/42525 [56:37<07:17, 11.57it/s]

 88%|███████████████████████████████▋    | 37463/42525 [56:38<07:30, 11.23it/s]

 88%|███████████████████████████████▋    | 37467/42525 [56:38<07:22, 11.44it/s]

 88%|███████████████████████████████▋    | 37471/42525 [56:38<07:29, 11.25it/s]

 88%|███████████████████████████████▋    | 37475/42525 [56:39<07:24, 11.36it/s]

 88%|███████████████████████████████▋    | 37479/42525 [56:39<07:52, 10.68it/s]

 88%|███████████████████████████████▋    | 37483/42525 [56:40<08:05, 10.38it/s]

 88%|███████████████████████████████▋    | 37487/42525 [56:40<07:59, 10.50it/s]

 88%|███████████████████████████████▋    | 37491/42525 [56:40<07:41, 10.91it/s]

 88%|███████████████████████████████▋    | 37495/42525 [56:41<06:56, 12.06it/s]

 88%|███████████████████████████████▋    | 37499/42525 [56:41<07:20, 11.40it/s]

 88%|███████████████████████████████▋    | 37503/42525 [56:41<07:18, 11.45it/s]

 88%|███████████████████████████████▊    | 37507/42525 [56:42<07:06, 11.77it/s]

 88%|███████████████████████████████▊    | 37511/42525 [56:42<06:43, 12.42it/s]

 88%|███████████████████████████████▊    | 37515/42525 [56:42<06:50, 12.21it/s]

 88%|███████████████████████████████▊    | 37519/42525 [56:43<07:24, 11.25it/s]

 88%|███████████████████████████████▊    | 37523/42525 [56:43<07:26, 11.20it/s]

 88%|███████████████████████████████▊    | 37527/42525 [56:43<07:23, 11.28it/s]

 88%|███████████████████████████████▊    | 37531/42525 [56:44<07:28, 11.14it/s]

 88%|███████████████████████████████▊    | 37535/42525 [56:44<07:19, 11.34it/s]

 88%|███████████████████████████████▊    | 37537/42525 [56:44<07:35, 10.96it/s]

 88%|███████████████████████████████▊    | 37541/42525 [56:45<07:58, 10.41it/s]

 88%|███████████████████████████████▊    | 37545/42525 [56:45<07:46, 10.69it/s]

 88%|███████████████████████████████▊    | 37549/42525 [56:45<07:23, 11.22it/s]

 88%|███████████████████████████████▊    | 37553/42525 [56:46<06:55, 11.96it/s]

 88%|███████████████████████████████▊    | 37555/42525 [56:46<07:33, 10.96it/s]

 88%|███████████████████████████████▊    | 37557/42525 [56:46<07:55, 10.45it/s]

 88%|███████████████████████████████▊    | 37561/42525 [56:46<07:42, 10.74it/s]

 88%|███████████████████████████████▊    | 37565/42525 [56:47<07:06, 11.64it/s]

 88%|███████████████████████████████▊    | 37569/42525 [56:47<07:01, 11.76it/s]

 88%|███████████████████████████████▊    | 37573/42525 [56:47<07:07, 11.58it/s]

 88%|███████████████████████████████▊    | 37577/42525 [56:48<07:17, 11.31it/s]

 88%|███████████████████████████████▊    | 37581/42525 [56:48<07:15, 11.35it/s]

 88%|███████████████████████████████▊    | 37585/42525 [56:49<07:08, 11.53it/s]

 88%|███████████████████████████████▊    | 37589/42525 [56:49<07:20, 11.20it/s]

 88%|███████████████████████████████▊    | 37593/42525 [56:49<07:11, 11.43it/s]

 88%|███████████████████████████████▊    | 37597/42525 [56:50<07:15, 11.32it/s]

 88%|███████████████████████████████▊    | 37601/42525 [56:50<07:19, 11.20it/s]

 88%|███████████████████████████████▊    | 37605/42525 [56:50<07:08, 11.47it/s]

 88%|███████████████████████████████▊    | 37609/42525 [56:51<07:12, 11.37it/s]

 88%|███████████████████████████████▊    | 37613/42525 [56:51<07:24, 11.06it/s]

 88%|███████████████████████████████▊    | 37617/42525 [56:51<07:10, 11.41it/s]

 88%|███████████████████████████████▊    | 37621/42525 [56:52<07:11, 11.36it/s]

 88%|███████████████████████████████▊    | 37625/42525 [56:52<07:06, 11.49it/s]

 88%|███████████████████████████████▊    | 37629/42525 [56:52<07:24, 11.02it/s]

 88%|███████████████████████████████▊    | 37633/42525 [56:53<07:31, 10.84it/s]

 89%|███████████████████████████████▊    | 37637/42525 [56:53<07:24, 10.99it/s]

 89%|███████████████████████████████▊    | 37641/42525 [56:54<07:16, 11.19it/s]

 89%|███████████████████████████████▊    | 37645/42525 [56:54<07:20, 11.08it/s]

 89%|███████████████████████████████▊    | 37649/42525 [56:54<07:15, 11.21it/s]

 89%|███████████████████████████████▉    | 37653/42525 [56:55<07:21, 11.04it/s]

 89%|███████████████████████████████▉    | 37657/42525 [56:55<07:29, 10.83it/s]

 89%|███████████████████████████████▉    | 37661/42525 [56:55<07:14, 11.20it/s]

 89%|███████████████████████████████▉    | 37665/42525 [56:56<07:18, 11.09it/s]

 89%|███████████████████████████████▉    | 37669/42525 [56:56<07:35, 10.66it/s]

 89%|███████████████████████████████▉    | 37673/42525 [56:56<07:16, 11.10it/s]

 89%|███████████████████████████████▉    | 37677/42525 [56:57<07:07, 11.35it/s]

 89%|███████████████████████████████▉    | 37681/42525 [56:57<07:18, 11.06it/s]

 89%|███████████████████████████████▉    | 37685/42525 [56:57<07:15, 11.10it/s]

 89%|███████████████████████████████▉    | 37689/42525 [56:58<07:15, 11.11it/s]

 89%|███████████████████████████████▉    | 37693/42525 [56:58<07:10, 11.22it/s]

 89%|███████████████████████████████▉    | 37697/42525 [56:59<07:00, 11.49it/s]

 89%|███████████████████████████████▉    | 37701/42525 [56:59<07:07, 11.29it/s]

 89%|███████████████████████████████▉    | 37705/42525 [56:59<07:25, 10.83it/s]

 89%|███████████████████████████████▉    | 37709/42525 [57:00<07:17, 11.01it/s]

 89%|███████████████████████████████▉    | 37713/42525 [57:00<07:15, 11.04it/s]

 89%|███████████████████████████████▉    | 37717/42525 [57:00<07:13, 11.10it/s]

 89%|███████████████████████████████▉    | 37721/42525 [57:01<07:00, 11.42it/s]

 89%|███████████████████████████████▉    | 37725/42525 [57:01<07:05, 11.27it/s]

 89%|███████████████████████████████▉    | 37729/42525 [57:01<07:10, 11.13it/s]

 89%|███████████████████████████████▉    | 37733/42525 [57:02<07:13, 11.04it/s]

 89%|███████████████████████████████▉    | 37737/42525 [57:02<06:59, 11.41it/s]

 89%|███████████████████████████████▉    | 37741/42525 [57:03<07:04, 11.28it/s]

 89%|███████████████████████████████▉    | 37745/42525 [57:03<06:58, 11.42it/s]

 89%|███████████████████████████████▉    | 37749/42525 [57:03<06:55, 11.48it/s]

 89%|███████████████████████████████▉    | 37753/42525 [57:04<07:00, 11.34it/s]

 89%|███████████████████████████████▉    | 37757/42525 [57:04<06:59, 11.35it/s]

 89%|███████████████████████████████▉    | 37761/42525 [57:04<06:53, 11.51it/s]

 89%|███████████████████████████████▉    | 37765/42525 [57:05<06:56, 11.43it/s]

 89%|███████████████████████████████▉    | 37769/42525 [57:05<06:49, 11.60it/s]

 89%|███████████████████████████████▉    | 37773/42525 [57:05<06:57, 11.39it/s]

 89%|███████████████████████████████▉    | 37777/42525 [57:06<06:47, 11.64it/s]

 89%|███████████████████████████████▉    | 37781/42525 [57:06<06:45, 11.69it/s]

 89%|███████████████████████████████▉    | 37785/42525 [57:06<06:42, 11.78it/s]

 89%|███████████████████████████████▉    | 37789/42525 [57:07<07:05, 11.13it/s]

 89%|███████████████████████████████▉    | 37793/42525 [57:07<07:08, 11.05it/s]

 89%|███████████████████████████████▉    | 37797/42525 [57:07<06:56, 11.36it/s]

 89%|████████████████████████████████    | 37801/42525 [57:08<06:48, 11.58it/s]

 89%|████████████████████████████████    | 37803/42525 [57:08<06:56, 11.34it/s]

 89%|████████████████████████████████    | 37807/42525 [57:08<07:12, 10.91it/s]

 89%|████████████████████████████████    | 37811/42525 [57:09<07:16, 10.81it/s]

 89%|████████████████████████████████    | 37815/42525 [57:09<07:01, 11.18it/s]

 89%|████████████████████████████████    | 37819/42525 [57:09<07:00, 11.20it/s]

 89%|████████████████████████████████    | 37823/42525 [57:10<06:47, 11.55it/s]

 89%|████████████████████████████████    | 37827/42525 [57:10<07:06, 11.02it/s]

 89%|████████████████████████████████    | 37829/42525 [57:10<06:58, 11.22it/s]

 89%|████████████████████████████████    | 37833/42525 [57:11<07:11, 10.88it/s]

 89%|████████████████████████████████    | 37837/42525 [57:11<06:54, 11.30it/s]

 89%|████████████████████████████████    | 37841/42525 [57:11<06:48, 11.48it/s]

 89%|████████████████████████████████    | 37845/42525 [57:12<06:51, 11.37it/s]

 89%|████████████████████████████████    | 37849/42525 [57:12<06:52, 11.34it/s]

 89%|████████████████████████████████    | 37853/42525 [57:12<07:07, 10.92it/s]

 89%|████████████████████████████████    | 37857/42525 [57:13<07:24, 10.51it/s]

 89%|████████████████████████████████    | 37861/42525 [57:13<07:10, 10.83it/s]

 89%|████████████████████████████████    | 37865/42525 [57:14<07:06, 10.92it/s]

 89%|████████████████████████████████    | 37869/42525 [57:14<06:56, 11.17it/s]

 89%|████████████████████████████████    | 37873/42525 [57:14<06:19, 12.25it/s]

 89%|████████████████████████████████    | 37877/42525 [57:15<06:37, 11.69it/s]

 89%|████████████████████████████████    | 37881/42525 [57:15<06:24, 12.08it/s]

 89%|████████████████████████████████    | 37885/42525 [57:15<06:26, 12.01it/s]

 89%|████████████████████████████████    | 37889/42525 [57:16<06:27, 11.95it/s]

 89%|████████████████████████████████    | 37893/42525 [57:16<06:29, 11.91it/s]

 89%|████████████████████████████████    | 37897/42525 [57:16<06:26, 11.97it/s]

 89%|████████████████████████████████    | 37901/42525 [57:17<06:34, 11.71it/s]

 89%|████████████████████████████████    | 37905/42525 [57:17<06:38, 11.58it/s]

 89%|████████████████████████████████    | 37909/42525 [57:17<06:36, 11.66it/s]

 89%|████████████████████████████████    | 37913/42525 [57:18<06:55, 11.11it/s]

 89%|████████████████████████████████    | 37917/42525 [57:18<06:44, 11.40it/s]

 89%|████████████████████████████████    | 37921/42525 [57:18<06:39, 11.51it/s]

 89%|████████████████████████████████    | 37925/42525 [57:19<06:52, 11.16it/s]

 89%|████████████████████████████████    | 37929/42525 [57:19<06:42, 11.43it/s]

 89%|████████████████████████████████    | 37933/42525 [57:19<06:35, 11.62it/s]

 89%|████████████████████████████████    | 37937/42525 [57:20<06:28, 11.81it/s]

 89%|████████████████████████████████    | 37941/42525 [57:20<06:34, 11.63it/s]

 89%|████████████████████████████████    | 37945/42525 [57:20<06:37, 11.53it/s]

 89%|████████████████████████████████▏   | 37949/42525 [57:21<06:36, 11.53it/s]

 89%|████████████████████████████████▏   | 37953/42525 [57:21<07:00, 10.86it/s]

 89%|████████████████████████████████▏   | 37957/42525 [57:22<07:11, 10.60it/s]

 89%|████████████████████████████████▏   | 37959/42525 [57:22<07:11, 10.57it/s]

 89%|████████████████████████████████▏   | 37963/42525 [57:22<07:12, 10.55it/s]

 89%|████████████████████████████████▏   | 37967/42525 [57:22<06:47, 11.18it/s]

 89%|████████████████████████████████▏   | 37971/42525 [57:23<06:43, 11.28it/s]

 89%|████████████████████████████████▏   | 37975/42525 [57:23<06:31, 11.61it/s]

 89%|████████████████████████████████▏   | 37979/42525 [57:24<07:00, 10.81it/s]

 89%|████████████████████████████████▏   | 37983/42525 [57:24<06:48, 11.12it/s]

 89%|████████████████████████████████▏   | 37987/42525 [57:24<06:48, 11.11it/s]

 89%|████████████████████████████████▏   | 37989/42525 [57:24<06:39, 11.36it/s]

 89%|████████████████████████████████▏   | 37993/42525 [57:25<06:46, 11.14it/s]

 89%|████████████████████████████████▏   | 37997/42525 [57:25<06:46, 11.13it/s]

 89%|████████████████████████████████▏   | 38001/42525 [57:25<06:36, 11.42it/s]

 89%|████████████████████████████████▏   | 38005/42525 [57:26<06:41, 11.25it/s]

 89%|████████████████████████████████▏   | 38009/42525 [57:26<06:56, 10.84it/s]

 89%|████████████████████████████████▏   | 38013/42525 [57:27<06:55, 10.85it/s]

 89%|████████████████████████████████▏   | 38017/42525 [57:27<07:07, 10.54it/s]

 89%|████████████████████████████████▏   | 38021/42525 [57:27<06:55, 10.84it/s]

 89%|████████████████████████████████▏   | 38025/42525 [57:28<06:41, 11.20it/s]

 89%|████████████████████████████████▏   | 38029/42525 [57:28<06:35, 11.38it/s]

 89%|████████████████████████████████▏   | 38033/42525 [57:28<06:30, 11.51it/s]

 89%|████████████████████████████████▏   | 38037/42525 [57:29<06:34, 11.38it/s]

 89%|████████████████████████████████▏   | 38041/42525 [57:29<06:31, 11.46it/s]

 89%|████████████████████████████████▏   | 38045/42525 [57:29<06:27, 11.58it/s]

 89%|████████████████████████████████▏   | 38049/42525 [57:30<06:44, 11.06it/s]

 89%|████████████████████████████████▏   | 38053/42525 [57:30<06:54, 10.80it/s]

 89%|████████████████████████████████▏   | 38057/42525 [57:31<06:40, 11.16it/s]

 90%|████████████████████████████████▏   | 38061/42525 [57:31<06:29, 11.45it/s]

 90%|████████████████████████████████▏   | 38063/42525 [57:31<06:27, 11.50it/s]

 90%|████████████████████████████████▏   | 38067/42525 [57:31<06:37, 11.22it/s]

 90%|████████████████████████████████▏   | 38071/42525 [57:32<06:26, 11.53it/s]

 90%|████████████████████████████████▏   | 38075/42525 [57:32<06:48, 10.88it/s]

 90%|████████████████████████████████▏   | 38079/42525 [57:32<06:37, 11.19it/s]

 90%|████████████████████████████████▏   | 38083/42525 [57:33<06:42, 11.04it/s]

 90%|████████████████████████████████▏   | 38087/42525 [57:33<06:28, 11.42it/s]

 90%|████████████████████████████████▏   | 38091/42525 [57:34<06:35, 11.20it/s]

 90%|████████████████████████████████▏   | 38095/42525 [57:34<06:51, 10.76it/s]

 90%|████████████████████████████████▎   | 38099/42525 [57:34<06:35, 11.20it/s]

 90%|████████████████████████████████▎   | 38103/42525 [57:35<06:44, 10.92it/s]

 90%|████████████████████████████████▎   | 38107/42525 [57:35<06:34, 11.20it/s]

 90%|████████████████████████████████▎   | 38109/42525 [57:35<06:30, 11.30it/s]

 90%|████████████████████████████████▎   | 38113/42525 [57:36<06:53, 10.66it/s]

 90%|████████████████████████████████▎   | 38117/42525 [57:36<07:01, 10.45it/s]

 90%|████████████████████████████████▎   | 38121/42525 [57:36<06:39, 11.04it/s]

 90%|████████████████████████████████▎   | 38125/42525 [57:37<06:40, 10.98it/s]

 90%|████████████████████████████████▎   | 38129/42525 [57:37<06:27, 11.33it/s]

 90%|████████████████████████████████▎   | 38133/42525 [57:37<06:21, 11.51it/s]

 90%|████████████████████████████████▎   | 38137/42525 [57:38<06:23, 11.46it/s]

 90%|████████████████████████████████▎   | 38141/42525 [57:38<06:21, 11.48it/s]

 90%|████████████████████████████████▎   | 38145/42525 [57:38<06:26, 11.32it/s]

 90%|████████████████████████████████▎   | 38149/42525 [57:39<06:40, 10.94it/s]

 90%|████████████████████████████████▎   | 38153/42525 [57:39<06:34, 11.07it/s]

 90%|████████████████████████████████▎   | 38157/42525 [57:40<06:22, 11.41it/s]

 90%|████████████████████████████████▎   | 38161/42525 [57:40<06:32, 11.11it/s]

 90%|████████████████████████████████▎   | 38165/42525 [57:40<06:42, 10.82it/s]

 90%|████████████████████████████████▎   | 38169/42525 [57:41<06:27, 11.24it/s]

 90%|████████████████████████████████▎   | 38173/42525 [57:41<06:34, 11.04it/s]

 90%|████████████████████████████████▎   | 38177/42525 [57:41<06:29, 11.17it/s]

 90%|████████████████████████████████▎   | 38181/42525 [57:42<06:40, 10.86it/s]

 90%|████████████████████████████████▎   | 38185/42525 [57:42<06:46, 10.68it/s]

 90%|████████████████████████████████▎   | 38189/42525 [57:42<06:51, 10.54it/s]

 90%|████████████████████████████████▎   | 38193/42525 [57:43<06:46, 10.66it/s]

 90%|████████████████████████████████▎   | 38197/42525 [57:43<06:37, 10.88it/s]

 90%|████████████████████████████████▎   | 38201/42525 [57:44<06:37, 10.87it/s]

 90%|████████████████████████████████▎   | 38205/42525 [57:44<06:40, 10.78it/s]

 90%|████████████████████████████████▎   | 38209/42525 [57:44<06:22, 11.27it/s]

 90%|████████████████████████████████▎   | 38213/42525 [57:45<06:25, 11.19it/s]

 90%|████████████████████████████████▎   | 38217/42525 [57:45<06:29, 11.05it/s]

 90%|████████████████████████████████▎   | 38221/42525 [57:45<06:17, 11.39it/s]

 90%|████████████████████████████████▎   | 38225/42525 [57:46<06:17, 11.39it/s]

 90%|████████████████████████████████▎   | 38229/42525 [57:46<06:18, 11.35it/s]

 90%|████████████████████████████████▎   | 38231/42525 [57:46<06:16, 11.41it/s]

 90%|████████████████████████████████▎   | 38235/42525 [57:47<06:44, 10.60it/s]

 90%|████████████████████████████████▎   | 38239/42525 [57:47<06:29, 11.00it/s]

 90%|████████████████████████████████▍   | 38243/42525 [57:47<06:14, 11.43it/s]

 90%|████████████████████████████████▍   | 38247/42525 [57:48<06:23, 11.16it/s]

 90%|████████████████████████████████▍   | 38251/42525 [57:48<06:12, 11.46it/s]

 90%|████████████████████████████████▍   | 38255/42525 [57:48<06:07, 11.62it/s]

 90%|████████████████████████████████▍   | 38259/42525 [57:49<06:09, 11.56it/s]

 90%|████████████████████████████████▍   | 38263/42525 [57:49<06:12, 11.45it/s]

 90%|████████████████████████████████▍   | 38267/42525 [57:49<06:12, 11.43it/s]

 90%|████████████████████████████████▍   | 38271/42525 [57:50<06:07, 11.57it/s]

 90%|████████████████████████████████▍   | 38275/42525 [57:50<06:05, 11.64it/s]

 90%|████████████████████████████████▍   | 38279/42525 [57:50<06:01, 11.75it/s]

 90%|████████████████████████████████▍   | 38283/42525 [57:51<06:23, 11.06it/s]

 90%|████████████████████████████████▍   | 38287/42525 [57:51<06:15, 11.27it/s]

 90%|████████████████████████████████▍   | 38291/42525 [57:52<06:22, 11.08it/s]

 90%|████████████████████████████████▍   | 38295/42525 [57:52<06:20, 11.11it/s]

 90%|████████████████████████████████▍   | 38299/42525 [57:52<06:09, 11.44it/s]

 90%|████████████████████████████████▍   | 38303/42525 [57:53<06:09, 11.44it/s]

 90%|████████████████████████████████▍   | 38307/42525 [57:53<06:02, 11.62it/s]

 90%|████████████████████████████████▍   | 38311/42525 [57:53<06:06, 11.50it/s]

 90%|████████████████████████████████▍   | 38315/42525 [57:54<06:10, 11.35it/s]

 90%|████████████████████████████████▍   | 38319/42525 [57:54<06:08, 11.40it/s]

 90%|████████████████████████████████▍   | 38323/42525 [57:54<06:21, 11.02it/s]

 90%|████████████████████████████████▍   | 38327/42525 [57:55<06:21, 11.02it/s]

 90%|████████████████████████████████▍   | 38331/42525 [57:55<06:17, 11.10it/s]

 90%|████████████████████████████████▍   | 38335/42525 [57:55<06:12, 11.26it/s]

 90%|████████████████████████████████▍   | 38339/42525 [57:56<06:17, 11.10it/s]

 90%|████████████████████████████████▍   | 38343/42525 [57:56<06:09, 11.31it/s]

 90%|████████████████████████████████▍   | 38347/42525 [57:56<06:16, 11.11it/s]

 90%|████████████████████████████████▍   | 38351/42525 [57:57<06:21, 10.95it/s]

 90%|████████████████████████████████▍   | 38355/42525 [57:57<06:18, 11.03it/s]

 90%|████████████████████████████████▍   | 38359/42525 [57:58<06:34, 10.55it/s]

 90%|████████████████████████████████▍   | 38363/42525 [57:58<06:15, 11.08it/s]

 90%|████████████████████████████████▍   | 38367/42525 [57:58<06:11, 11.18it/s]

 90%|████████████████████████████████▍   | 38371/42525 [57:59<06:25, 10.77it/s]

 90%|████████████████████████████████▍   | 38375/42525 [57:59<06:24, 10.81it/s]

 90%|████████████████████████████████▍   | 38379/42525 [57:59<06:16, 11.00it/s]

 90%|████████████████████████████████▍   | 38383/42525 [58:00<06:05, 11.33it/s]

 90%|████████████████████████████████▍   | 38385/42525 [58:00<06:03, 11.39it/s]

 90%|████████████████████████████████▍   | 38389/42525 [58:00<06:14, 11.03it/s]

 90%|████████████████████████████████▌   | 38393/42525 [58:01<06:00, 11.46it/s]

 90%|████████████████████████████████▌   | 38397/42525 [58:01<06:05, 11.28it/s]

 90%|████████████████████████████████▌   | 38401/42525 [58:01<06:05, 11.29it/s]

 90%|████████████████████████████████▌   | 38405/42525 [58:02<05:59, 11.47it/s]

 90%|████████████████████████████████▌   | 38409/42525 [58:02<06:16, 10.94it/s]

 90%|████████████████████████████████▌   | 38413/42525 [58:02<06:04, 11.28it/s]

 90%|████████████████████████████████▌   | 38417/42525 [58:03<06:11, 11.05it/s]

 90%|████████████████████████████████▌   | 38421/42525 [58:03<05:59, 11.40it/s]

 90%|████████████████████████████████▌   | 38425/42525 [58:04<06:05, 11.21it/s]

 90%|████████████████████████████████▌   | 38429/42525 [58:04<06:03, 11.27it/s]

 90%|████████████████████████████████▌   | 38433/42525 [58:04<05:54, 11.55it/s]

 90%|████████████████████████████████▌   | 38437/42525 [58:05<06:01, 11.32it/s]

 90%|████████████████████████████████▌   | 38441/42525 [58:05<06:14, 10.89it/s]

 90%|████████████████████████████████▌   | 38443/42525 [58:05<06:07, 11.11it/s]

 90%|████████████████████████████████▌   | 38447/42525 [58:06<06:17, 10.81it/s]

 90%|████████████████████████████████▌   | 38451/42525 [58:06<06:10, 11.00it/s]

 90%|████████████████████████████████▌   | 38455/42525 [58:06<05:56, 11.42it/s]

 90%|████████████████████████████████▌   | 38459/42525 [58:07<06:02, 11.23it/s]

 90%|████████████████████████████████▌   | 38463/42525 [58:07<05:53, 11.49it/s]

 90%|████████████████████████████████▌   | 38467/42525 [58:07<06:03, 11.17it/s]

 90%|████████████████████████████████▌   | 38471/42525 [58:08<06:07, 11.03it/s]

 90%|████████████████████████████████▌   | 38475/42525 [58:08<06:11, 10.90it/s]

 90%|████████████████████████████████▌   | 38479/42525 [58:08<06:03, 11.12it/s]

 90%|████████████████████████████████▌   | 38483/42525 [58:09<06:07, 11.01it/s]

 91%|████████████████████████████████▌   | 38487/42525 [58:09<06:09, 10.92it/s]

 91%|████████████████████████████████▌   | 38491/42525 [58:09<06:00, 11.20it/s]

 91%|████████████████████████████████▌   | 38495/42525 [58:10<05:56, 11.32it/s]

 91%|████████████████████████████████▌   | 38499/42525 [58:10<06:05, 11.02it/s]

 91%|████████████████████████████████▌   | 38503/42525 [58:11<06:05, 11.02it/s]

 91%|████████████████████████████████▌   | 38507/42525 [58:11<05:55, 11.29it/s]

 91%|████████████████████████████████▌   | 38511/42525 [58:11<06:08, 10.89it/s]

 91%|████████████████████████████████▌   | 38515/42525 [58:12<06:13, 10.72it/s]

 91%|████████████████████████████████▌   | 38519/42525 [58:12<06:01, 11.08it/s]

 91%|████████████████████████████████▌   | 38523/42525 [58:12<06:03, 11.00it/s]

 91%|████████████████████████████████▌   | 38527/42525 [58:13<05:51, 11.37it/s]

 91%|████████████████████████████████▌   | 38531/42525 [58:13<05:53, 11.31it/s]

 91%|████████████████████████████████▌   | 38535/42525 [58:13<06:03, 10.97it/s]

 91%|████████████████████████████████▋   | 38539/42525 [58:14<06:07, 10.84it/s]

 91%|████████████████████████████████▋   | 38543/42525 [58:14<06:06, 10.86it/s]

 91%|████████████████████████████████▋   | 38547/42525 [58:15<05:57, 11.12it/s]

 91%|████████████████████████████████▋   | 38551/42525 [58:15<05:49, 11.36it/s]

 91%|████████████████████████████████▋   | 38555/42525 [58:15<05:56, 11.15it/s]

 91%|████████████████████████████████▋   | 38559/42525 [58:16<06:08, 10.77it/s]

 91%|████████████████████████████████▋   | 38563/42525 [58:16<06:05, 10.84it/s]

 91%|████████████████████████████████▋   | 38567/42525 [58:16<05:50, 11.28it/s]

 91%|████████████████████████████████▋   | 38571/42525 [58:17<05:57, 11.07it/s]

 91%|████████████████████████████████▋   | 38575/42525 [58:17<05:42, 11.55it/s]

 91%|████████████████████████████████▋   | 38579/42525 [58:17<05:22, 12.23it/s]

 91%|████████████████████████████████▋   | 38583/42525 [58:18<05:19, 12.33it/s]

 91%|████████████████████████████████▋   | 38587/42525 [58:18<05:15, 12.48it/s]

 91%|████████████████████████████████▋   | 38591/42525 [58:18<05:09, 12.70it/s]

 91%|████████████████████████████████▋   | 38595/42525 [58:19<05:11, 12.60it/s]

 91%|████████████████████████████████▋   | 38599/42525 [58:19<05:12, 12.57it/s]

 91%|████████████████████████████████▋   | 38603/42525 [58:19<05:02, 12.96it/s]

 91%|████████████████████████████████▋   | 38607/42525 [58:20<05:21, 12.19it/s]

 91%|████████████████████████████████▋   | 38611/42525 [58:20<05:49, 11.20it/s]

 91%|████████████████████████████████▋   | 38615/42525 [58:20<05:43, 11.39it/s]

 91%|████████████████████████████████▋   | 38619/42525 [58:21<05:28, 11.90it/s]

 91%|████████████████████████████████▋   | 38623/42525 [58:21<05:15, 12.36it/s]

 91%|████████████████████████████████▋   | 38627/42525 [58:21<05:31, 11.77it/s]

 91%|████████████████████████████████▋   | 38631/42525 [58:22<05:32, 11.72it/s]

 91%|████████████████████████████████▋   | 38635/42525 [58:22<05:42, 11.35it/s]

 91%|████████████████████████████████▋   | 38639/42525 [58:22<05:37, 11.52it/s]

 91%|████████████████████████████████▋   | 38643/42525 [58:23<05:49, 11.10it/s]

 91%|████████████████████████████████▋   | 38647/42525 [58:23<05:54, 10.93it/s]

 91%|████████████████████████████████▋   | 38651/42525 [58:23<05:53, 10.96it/s]

 91%|████████████████████████████████▋   | 38655/42525 [58:24<05:49, 11.07it/s]

 91%|████████████████████████████████▋   | 38659/42525 [58:24<05:44, 11.23it/s]

 91%|████████████████████████████████▋   | 38663/42525 [58:25<05:55, 10.86it/s]

 91%|████████████████████████████████▋   | 38667/42525 [58:25<05:46, 11.13it/s]

 91%|████████████████████████████████▋   | 38671/42525 [58:25<05:43, 11.23it/s]

 91%|████████████████████████████████▋   | 38675/42525 [58:26<05:48, 11.06it/s]

 91%|████████████████████████████████▋   | 38679/42525 [58:26<05:42, 11.24it/s]

 91%|████████████████████████████████▋   | 38683/42525 [58:26<05:50, 10.96it/s]

 91%|████████████████████████████████▊   | 38687/42525 [58:27<05:52, 10.90it/s]

 91%|████████████████████████████████▊   | 38691/42525 [58:27<05:52, 10.86it/s]

 91%|████████████████████████████████▊   | 38695/42525 [58:27<05:37, 11.36it/s]

 91%|████████████████████████████████▊   | 38699/42525 [58:28<05:31, 11.54it/s]

 91%|████████████████████████████████▊   | 38703/42525 [58:28<05:38, 11.29it/s]

 91%|████████████████████████████████▊   | 38707/42525 [58:28<05:55, 10.75it/s]

 91%|████████████████████████████████▊   | 38711/42525 [58:29<05:42, 11.15it/s]

 91%|████████████████████████████████▊   | 38715/42525 [58:29<05:40, 11.18it/s]

 91%|████████████████████████████████▊   | 38719/42525 [58:30<05:32, 11.43it/s]

 91%|████████████████████████████████▊   | 38723/42525 [58:30<05:26, 11.64it/s]

 91%|████████████████████████████████▊   | 38727/42525 [58:30<05:25, 11.68it/s]

 91%|████████████████████████████████▊   | 38731/42525 [58:31<05:22, 11.78it/s]

 91%|████████████████████████████████▊   | 38735/42525 [58:31<05:36, 11.25it/s]

 91%|████████████████████████████████▊   | 38737/42525 [58:31<05:33, 11.34it/s]

 91%|████████████████████████████████▊   | 38741/42525 [58:31<05:46, 10.91it/s]

 91%|████████████████████████████████▊   | 38745/42525 [58:32<05:36, 11.24it/s]

 91%|████████████████████████████████▊   | 38747/42525 [58:32<05:31, 11.40it/s]

 91%|████████████████████████████████▊   | 38751/42525 [58:32<05:50, 10.78it/s]

 91%|████████████████████████████████▊   | 38755/42525 [58:33<05:35, 11.22it/s]

 91%|████████████████████████████████▊   | 38759/42525 [58:33<05:40, 11.05it/s]

 91%|████████████████████████████████▊   | 38763/42525 [58:33<05:43, 10.97it/s]

 91%|████████████████████████████████▊   | 38767/42525 [58:34<05:40, 11.04it/s]

 91%|████████████████████████████████▊   | 38771/42525 [58:34<05:51, 10.68it/s]

 91%|████████████████████████████████▊   | 38775/42525 [58:35<05:56, 10.53it/s]

 91%|████████████████████████████████▊   | 38779/42525 [58:35<05:38, 11.07it/s]

 91%|████████████████████████████████▊   | 38783/42525 [58:35<05:41, 10.97it/s]

 91%|████████████████████████████████▊   | 38787/42525 [58:36<05:45, 10.81it/s]

 91%|████████████████████████████████▊   | 38791/42525 [58:36<05:37, 11.06it/s]

 91%|████████████████████████████████▊   | 38795/42525 [58:36<05:28, 11.36it/s]

 91%|████████████████████████████████▊   | 38799/42525 [58:37<05:23, 11.53it/s]

 91%|████████████████████████████████▊   | 38803/42525 [58:37<05:24, 11.46it/s]

 91%|████████████████████████████████▊   | 38807/42525 [58:37<05:22, 11.53it/s]

 91%|████████████████████████████████▊   | 38811/42525 [58:38<05:34, 11.12it/s]

 91%|████████████████████████████████▊   | 38815/42525 [58:38<05:32, 11.16it/s]

 91%|████████████████████████████████▊   | 38819/42525 [58:39<05:55, 10.43it/s]

 91%|████████████████████████████████▊   | 38823/42525 [58:39<05:41, 10.83it/s]

 91%|████████████████████████████████▊   | 38827/42525 [58:39<05:37, 10.96it/s]

 91%|████████████████████████████████▊   | 38831/42525 [58:40<05:29, 11.20it/s]

 91%|████████████████████████████████▉   | 38835/42525 [58:40<05:28, 11.25it/s]

 91%|████████████████████████████████▉   | 38839/42525 [58:40<05:38, 10.89it/s]

 91%|████████████████████████████████▉   | 38843/42525 [58:41<05:25, 11.31it/s]

 91%|████████████████████████████████▉   | 38847/42525 [58:41<05:29, 11.16it/s]

 91%|████████████████████████████████▉   | 38851/42525 [58:41<05:28, 11.18it/s]

 91%|████████████████████████████████▉   | 38855/42525 [58:42<05:22, 11.38it/s]

 91%|████████████████████████████████▉   | 38859/42525 [58:42<05:16, 11.57it/s]

 91%|████████████████████████████████▉   | 38863/42525 [58:43<05:38, 10.83it/s]

 91%|████████████████████████████████▉   | 38867/42525 [58:43<05:36, 10.86it/s]

 91%|████████████████████████████████▉   | 38871/42525 [58:43<05:23, 11.28it/s]

 91%|████████████████████████████████▉   | 38875/42525 [58:44<05:29, 11.07it/s]

 91%|████████████████████████████████▉   | 38879/42525 [58:44<05:35, 10.86it/s]

 91%|████████████████████████████████▉   | 38883/42525 [58:44<05:34, 10.88it/s]

 91%|████████████████████████████████▉   | 38887/42525 [58:45<05:35, 10.86it/s]

 91%|████████████████████████████████▉   | 38891/42525 [58:45<05:36, 10.80it/s]

 91%|████████████████████████████████▉   | 38895/42525 [58:45<05:27, 11.10it/s]

 91%|████████████████████████████████▉   | 38899/42525 [58:46<05:25, 11.13it/s]

 91%|████████████████████████████████▉   | 38903/42525 [58:46<05:27, 11.06it/s]

 91%|████████████████████████████████▉   | 38907/42525 [58:46<05:24, 11.14it/s]

 92%|████████████████████████████████▉   | 38911/42525 [58:47<05:32, 10.87it/s]

 92%|████████████████████████████████▉   | 38915/42525 [58:47<05:21, 11.24it/s]

 92%|████████████████████████████████▉   | 38919/42525 [58:48<05:12, 11.55it/s]

 92%|████████████████████████████████▉   | 38923/42525 [58:48<05:12, 11.53it/s]

 92%|████████████████████████████████▉   | 38927/42525 [58:48<05:24, 11.08it/s]

 92%|████████████████████████████████▉   | 38931/42525 [58:49<05:14, 11.42it/s]

 92%|████████████████████████████████▉   | 38935/42525 [58:49<05:13, 11.47it/s]

 92%|████████████████████████████████▉   | 38939/42525 [58:49<05:20, 11.19it/s]

 92%|████████████████████████████████▉   | 38943/42525 [58:50<05:28, 10.89it/s]

 92%|████████████████████████████████▉   | 38947/42525 [58:50<05:17, 11.29it/s]

 92%|████████████████████████████████▉   | 38951/42525 [58:50<05:13, 11.41it/s]

 92%|████████████████████████████████▉   | 38955/42525 [58:51<05:23, 11.05it/s]

 92%|████████████████████████████████▉   | 38959/42525 [58:51<05:25, 10.96it/s]

 92%|████████████████████████████████▉   | 38963/42525 [58:51<05:14, 11.33it/s]

 92%|████████████████████████████████▉   | 38967/42525 [58:52<05:07, 11.56it/s]

 92%|████████████████████████████████▉   | 38971/42525 [58:52<05:16, 11.24it/s]

 92%|████████████████████████████████▉   | 38975/42525 [58:53<05:11, 11.39it/s]

 92%|████████████████████████████████▉   | 38979/42525 [58:53<05:05, 11.61it/s]

 92%|█████████████████████████████████   | 38983/42525 [58:53<05:04, 11.64it/s]

 92%|█████████████████████████████████   | 38987/42525 [58:54<05:01, 11.75it/s]

 92%|█████████████████████████████████   | 38991/42525 [58:54<05:12, 11.30it/s]

 92%|█████████████████████████████████   | 38995/42525 [58:54<05:14, 11.21it/s]

 92%|█████████████████████████████████   | 38999/42525 [58:55<05:13, 11.24it/s]

 92%|█████████████████████████████████   | 39003/42525 [58:55<05:21, 10.97it/s]

 92%|█████████████████████████████████   | 39007/42525 [58:55<05:20, 10.98it/s]

 92%|█████████████████████████████████   | 39011/42525 [58:56<05:14, 11.19it/s]

 92%|█████████████████████████████████   | 39015/42525 [58:56<05:26, 10.75it/s]

 92%|█████████████████████████████████   | 39019/42525 [58:56<05:23, 10.82it/s]

 92%|█████████████████████████████████   | 39023/42525 [58:57<05:15, 11.11it/s]

 92%|█████████████████████████████████   | 39027/42525 [58:57<05:17, 11.01it/s]

 92%|█████████████████████████████████   | 39031/42525 [58:58<05:17, 10.99it/s]

 92%|█████████████████████████████████   | 39035/42525 [58:58<05:18, 10.95it/s]

 92%|█████████████████████████████████   | 39037/42525 [58:58<05:21, 10.84it/s]

 92%|█████████████████████████████████   | 39041/42525 [58:58<05:21, 10.85it/s]

 92%|█████████████████████████████████   | 39045/42525 [58:59<05:22, 10.80it/s]

 92%|█████████████████████████████████   | 39049/42525 [58:59<05:23, 10.74it/s]

 92%|█████████████████████████████████   | 39053/42525 [59:00<05:22, 10.77it/s]

 92%|█████████████████████████████████   | 39057/42525 [59:00<05:25, 10.66it/s]

 92%|█████████████████████████████████   | 39061/42525 [59:00<05:13, 11.03it/s]

 92%|█████████████████████████████████   | 39065/42525 [59:01<05:09, 11.18it/s]

 92%|█████████████████████████████████   | 39067/42525 [59:01<05:04, 11.37it/s]

 92%|█████████████████████████████████   | 39071/42525 [59:01<05:19, 10.81it/s]

 92%|█████████████████████████████████   | 39075/42525 [59:02<05:17, 10.86it/s]

 92%|█████████████████████████████████   | 39079/42525 [59:02<05:05, 11.29it/s]

 92%|█████████████████████████████████   | 39083/42525 [59:02<05:13, 10.97it/s]

 92%|█████████████████████████████████   | 39087/42525 [59:03<05:05, 11.25it/s]

 92%|█████████████████████████████████   | 39091/42525 [59:03<04:56, 11.58it/s]

 92%|█████████████████████████████████   | 39095/42525 [59:03<05:03, 11.30it/s]

 92%|█████████████████████████████████   | 39099/42525 [59:04<05:10, 11.04it/s]

 92%|█████████████████████████████████   | 39103/42525 [59:04<05:11, 10.98it/s]

 92%|█████████████████████████████████   | 39107/42525 [59:04<05:08, 11.06it/s]

 92%|█████████████████████████████████   | 39111/42525 [59:05<05:12, 10.92it/s]

 92%|█████████████████████████████████   | 39115/42525 [59:05<05:21, 10.60it/s]

 92%|█████████████████████████████████   | 39119/42525 [59:06<05:08, 11.05it/s]

 92%|█████████████████████████████████   | 39123/42525 [59:06<05:05, 11.14it/s]

 92%|█████████████████████████████████   | 39127/42525 [59:06<04:57, 11.41it/s]

 92%|█████████████████████████████████▏  | 39131/42525 [59:07<05:04, 11.14it/s]

 92%|█████████████████████████████████▏  | 39133/42525 [59:07<04:58, 11.36it/s]

 92%|█████████████████████████████████▏  | 39137/42525 [59:07<05:10, 10.92it/s]

 92%|█████████████████████████████████▏  | 39141/42525 [59:08<05:02, 11.19it/s]

 92%|█████████████████████████████████▏  | 39145/42525 [59:08<05:09, 10.91it/s]

 92%|█████████████████████████████████▏  | 39147/42525 [59:08<05:20, 10.54it/s]

 92%|█████████████████████████████████▏  | 39151/42525 [59:08<05:25, 10.36it/s]

 92%|█████████████████████████████████▏  | 39155/42525 [59:09<05:05, 11.04it/s]

 92%|█████████████████████████████████▏  | 39159/42525 [59:09<05:16, 10.64it/s]

 92%|█████████████████████████████████▏  | 39163/42525 [59:10<04:59, 11.24it/s]

 92%|█████████████████████████████████▏  | 39167/42525 [59:10<04:57, 11.30it/s]

 92%|█████████████████████████████████▏  | 39171/42525 [59:10<05:08, 10.88it/s]

 92%|█████████████████████████████████▏  | 39175/42525 [59:11<05:05, 10.95it/s]

 92%|█████████████████████████████████▏  | 39179/42525 [59:11<05:11, 10.75it/s]

 92%|█████████████████████████████████▏  | 39183/42525 [59:11<04:59, 11.17it/s]

 92%|█████████████████████████████████▏  | 39187/42525 [59:12<04:55, 11.29it/s]

 92%|█████████████████████████████████▏  | 39191/42525 [59:12<04:52, 11.41it/s]

 92%|█████████████████████████████████▏  | 39195/42525 [59:12<05:05, 10.89it/s]

 92%|█████████████████████████████████▏  | 39199/42525 [59:13<05:09, 10.74it/s]

 92%|█████████████████████████████████▏  | 39203/42525 [59:13<05:15, 10.52it/s]

 92%|█████████████████████████████████▏  | 39207/42525 [59:14<05:03, 10.94it/s]

 92%|█████████████████████████████████▏  | 39211/42525 [59:14<04:59, 11.05it/s]

 92%|█████████████████████████████████▏  | 39215/42525 [59:14<04:50, 11.38it/s]

 92%|█████████████████████████████████▏  | 39219/42525 [59:15<04:49, 11.43it/s]

 92%|█████████████████████████████████▏  | 39223/42525 [59:15<04:44, 11.60it/s]

 92%|█████████████████████████████████▏  | 39227/42525 [59:15<04:54, 11.21it/s]

 92%|█████████████████████████████████▏  | 39231/42525 [59:16<04:45, 11.52it/s]

 92%|█████████████████████████████████▏  | 39235/42525 [59:16<04:42, 11.63it/s]

 92%|█████████████████████████████████▏  | 39239/42525 [59:16<04:41, 11.67it/s]

 92%|█████████████████████████████████▏  | 39243/42525 [59:17<04:41, 11.66it/s]

 92%|█████████████████████████████████▏  | 39247/42525 [59:17<04:47, 11.41it/s]

 92%|█████████████████████████████████▏  | 39251/42525 [59:17<04:57, 11.02it/s]

 92%|█████████████████████████████████▏  | 39255/42525 [59:18<04:56, 11.02it/s]

 92%|█████████████████████████████████▏  | 39259/42525 [59:18<04:57, 10.98it/s]

 92%|█████████████████████████████████▏  | 39263/42525 [59:19<04:56, 10.98it/s]

 92%|█████████████████████████████████▏  | 39267/42525 [59:19<05:01, 10.81it/s]

 92%|█████████████████████████████████▏  | 39271/42525 [59:19<04:51, 11.16it/s]

 92%|█████████████████████████████████▏  | 39275/42525 [59:20<04:55, 11.00it/s]

 92%|█████████████████████████████████▎  | 39279/42525 [59:20<04:52, 11.11it/s]

 92%|█████████████████████████████████▎  | 39283/42525 [59:20<04:51, 11.11it/s]

 92%|█████████████████████████████████▎  | 39287/42525 [59:21<04:49, 11.19it/s]

 92%|█████████████████████████████████▎  | 39291/42525 [59:21<04:49, 11.17it/s]

 92%|█████████████████████████████████▎  | 39293/42525 [59:21<04:53, 11.02it/s]

 92%|█████████████████████████████████▎  | 39297/42525 [59:22<05:00, 10.74it/s]

 92%|█████████████████████████████████▎  | 39301/42525 [59:22<04:54, 10.96it/s]

 92%|█████████████████████████████████▎  | 39305/42525 [59:22<04:45, 11.27it/s]

 92%|█████████████████████████████████▎  | 39309/42525 [59:23<04:40, 11.48it/s]

 92%|█████████████████████████████████▎  | 39313/42525 [59:23<04:36, 11.61it/s]

 92%|█████████████████████████████████▎  | 39317/42525 [59:23<04:42, 11.35it/s]

 92%|█████████████████████████████████▎  | 39321/42525 [59:24<04:35, 11.64it/s]

 92%|█████████████████████████████████▎  | 39325/42525 [59:24<04:45, 11.21it/s]

 92%|█████████████████████████████████▎  | 39329/42525 [59:24<04:56, 10.79it/s]

 92%|█████████████████████████████████▎  | 39333/42525 [59:25<04:50, 10.98it/s]

 93%|█████████████████████████████████▎  | 39337/42525 [59:25<04:41, 11.32it/s]

 93%|█████████████████████████████████▎  | 39341/42525 [59:26<04:52, 10.88it/s]

 93%|█████████████████████████████████▎  | 39345/42525 [59:26<04:42, 11.26it/s]

 93%|█████████████████████████████████▎  | 39349/42525 [59:26<04:51, 10.89it/s]

 93%|█████████████████████████████████▎  | 39353/42525 [59:27<04:50, 10.93it/s]

 93%|█████████████████████████████████▎  | 39357/42525 [59:27<04:47, 11.01it/s]

 93%|█████████████████████████████████▎  | 39361/42525 [59:27<04:41, 11.23it/s]

 93%|█████████████████████████████████▎  | 39365/42525 [59:28<04:42, 11.17it/s]

 93%|█████████████████████████████████▎  | 39369/42525 [59:28<04:42, 11.17it/s]

 93%|█████████████████████████████████▎  | 39373/42525 [59:28<04:35, 11.42it/s]

 93%|█████████████████████████████████▎  | 39377/42525 [59:29<04:38, 11.31it/s]

 93%|█████████████████████████████████▎  | 39381/42525 [59:29<04:33, 11.48it/s]

 93%|█████████████████████████████████▎  | 39385/42525 [59:29<04:28, 11.67it/s]

 93%|█████████████████████████████████▎  | 39387/42525 [59:30<04:28, 11.68it/s]

 93%|█████████████████████████████████▎  | 39391/42525 [59:30<04:53, 10.68it/s]

 93%|█████████████████████████████████▎  | 39395/42525 [59:30<04:55, 10.61it/s]

 93%|█████████████████████████████████▎  | 39399/42525 [59:31<04:39, 11.18it/s]

 93%|█████████████████████████████████▎  | 39403/42525 [59:31<04:33, 11.43it/s]

 93%|█████████████████████████████████▎  | 39407/42525 [59:31<04:33, 11.39it/s]

 93%|█████████████████████████████████▎  | 39411/42525 [59:32<04:35, 11.31it/s]

 93%|█████████████████████████████████▎  | 39415/42525 [59:32<04:38, 11.18it/s]

 93%|█████████████████████████████████▎  | 39419/42525 [59:33<04:42, 11.00it/s]

 93%|█████████████████████████████████▎  | 39423/42525 [59:33<04:46, 10.84it/s]

 93%|█████████████████████████████████▍  | 39427/42525 [59:33<04:41, 11.00it/s]

 93%|█████████████████████████████████▍  | 39431/42525 [59:34<04:32, 11.34it/s]

 93%|█████████████████████████████████▍  | 39435/42525 [59:34<04:29, 11.49it/s]

 93%|█████████████████████████████████▍  | 39439/42525 [59:34<04:34, 11.26it/s]

 93%|█████████████████████████████████▍  | 39443/42525 [59:35<04:34, 11.21it/s]

 93%|█████████████████████████████████▍  | 39447/42525 [59:35<04:43, 10.84it/s]

 93%|█████████████████████████████████▍  | 39451/42525 [59:35<04:43, 10.83it/s]

 93%|█████████████████████████████████▍  | 39455/42525 [59:36<04:31, 11.30it/s]

 93%|█████████████████████████████████▍  | 39459/42525 [59:36<04:33, 11.22it/s]

 93%|█████████████████████████████████▍  | 39463/42525 [59:36<04:38, 11.01it/s]

 93%|█████████████████████████████████▍  | 39467/42525 [59:37<04:33, 11.18it/s]

 93%|█████████████████████████████████▍  | 39471/42525 [59:37<04:38, 10.95it/s]

 93%|█████████████████████████████████▍  | 39475/42525 [59:38<04:33, 11.15it/s]

 93%|█████████████████████████████████▍  | 39479/42525 [59:38<04:26, 11.44it/s]

 93%|█████████████████████████████████▍  | 39481/42525 [59:38<04:22, 11.58it/s]

 93%|█████████████████████████████████▍  | 39485/42525 [59:38<04:37, 10.97it/s]

 93%|█████████████████████████████████▍  | 39489/42525 [59:39<04:32, 11.16it/s]

 93%|█████████████████████████████████▍  | 39493/42525 [59:39<04:25, 11.44it/s]

 93%|█████████████████████████████████▍  | 39497/42525 [59:39<04:21, 11.60it/s]

 93%|█████████████████████████████████▍  | 39501/42525 [59:40<04:25, 11.39it/s]

 93%|█████████████████████████████████▍  | 39505/42525 [59:40<04:26, 11.31it/s]

 93%|█████████████████████████████████▍  | 39509/42525 [59:41<04:24, 11.41it/s]

 93%|█████████████████████████████████▍  | 39513/42525 [59:41<04:20, 11.57it/s]

 93%|█████████████████████████████████▍  | 39517/42525 [59:41<04:29, 11.18it/s]

 93%|█████████████████████████████████▍  | 39521/42525 [59:42<04:21, 11.47it/s]

 93%|█████████████████████████████████▍  | 39525/42525 [59:42<04:40, 10.68it/s]

 93%|█████████████████████████████████▍  | 39529/42525 [59:42<04:28, 11.15it/s]

 93%|█████████████████████████████████▍  | 39533/42525 [59:43<04:26, 11.22it/s]

 93%|█████████████████████████████████▍  | 39535/42525 [59:43<04:28, 11.14it/s]

 93%|█████████████████████████████████▍  | 39539/42525 [59:43<04:38, 10.72it/s]

 93%|█████████████████████████████████▍  | 39543/42525 [59:44<04:27, 11.14it/s]

 93%|█████████████████████████████████▍  | 39547/42525 [59:44<04:20, 11.42it/s]

 93%|█████████████████████████████████▍  | 39551/42525 [59:44<04:26, 11.16it/s]

 93%|█████████████████████████████████▍  | 39555/42525 [59:45<04:24, 11.22it/s]

 93%|█████████████████████████████████▍  | 39559/42525 [59:45<04:23, 11.28it/s]

 93%|█████████████████████████████████▍  | 39563/42525 [59:45<04:17, 11.51it/s]

 93%|█████████████████████████████████▍  | 39567/42525 [59:46<04:18, 11.44it/s]

 93%|█████████████████████████████████▍  | 39571/42525 [59:46<04:25, 11.14it/s]

 93%|█████████████████████████████████▌  | 39575/42525 [59:46<04:24, 11.16it/s]

 93%|█████████████████████████████████▌  | 39579/42525 [59:47<04:28, 10.98it/s]

 93%|█████████████████████████████████▌  | 39583/42525 [59:47<04:34, 10.73it/s]

 93%|█████████████████████████████████▌  | 39587/42525 [59:48<04:34, 10.71it/s]

 93%|█████████████████████████████████▌  | 39591/42525 [59:48<04:21, 11.22it/s]

 93%|█████████████████████████████████▌  | 39595/42525 [59:48<04:24, 11.06it/s]

 93%|█████████████████████████████████▌  | 39599/42525 [59:49<04:30, 10.81it/s]

 93%|█████████████████████████████████▌  | 39603/42525 [59:49<04:30, 10.82it/s]

 93%|█████████████████████████████████▌  | 39607/42525 [59:49<04:29, 10.81it/s]

 93%|█████████████████████████████████▌  | 39611/42525 [59:50<04:19, 11.23it/s]

 93%|█████████████████████████████████▌  | 39615/42525 [59:50<04:26, 10.90it/s]

 93%|█████████████████████████████████▌  | 39619/42525 [59:50<04:18, 11.25it/s]

 93%|█████████████████████████████████▌  | 39623/42525 [59:51<04:12, 11.51it/s]

 93%|█████████████████████████████████▌  | 39627/42525 [59:51<04:09, 11.62it/s]

 93%|█████████████████████████████████▌  | 39631/42525 [59:51<04:12, 11.47it/s]

 93%|█████████████████████████████████▌  | 39635/42525 [59:52<04:07, 11.67it/s]

 93%|█████████████████████████████████▌  | 39639/42525 [59:52<04:21, 11.05it/s]

 93%|█████████████████████████████████▌  | 39643/42525 [59:53<04:21, 11.03it/s]

 93%|█████████████████████████████████▌  | 39647/42525 [59:53<04:26, 10.82it/s]

 93%|█████████████████████████████████▌  | 39651/42525 [59:53<04:14, 11.28it/s]

 93%|█████████████████████████████████▌  | 39655/42525 [59:54<04:15, 11.22it/s]

 93%|█████████████████████████████████▌  | 39659/42525 [59:54<04:16, 11.19it/s]

 93%|█████████████████████████████████▌  | 39663/42525 [59:54<04:09, 11.46it/s]

 93%|█████████████████████████████████▌  | 39667/42525 [59:55<04:12, 11.31it/s]

 93%|█████████████████████████████████▌  | 39671/42525 [59:55<04:12, 11.32it/s]

 93%|█████████████████████████████████▌  | 39675/42525 [59:55<04:17, 11.06it/s]

 93%|█████████████████████████████████▌  | 39679/42525 [59:56<04:16, 11.09it/s]

 93%|█████████████████████████████████▌  | 39683/42525 [59:56<04:20, 10.91it/s]

 93%|█████████████████████████████████▌  | 39687/42525 [59:57<04:24, 10.73it/s]

 93%|█████████████████████████████████▌  | 39691/42525 [59:57<04:12, 11.20it/s]

 93%|█████████████████████████████████▌  | 39695/42525 [59:57<04:17, 11.00it/s]

 93%|█████████████████████████████████▌  | 39699/42525 [59:58<04:09, 11.35it/s]

 93%|█████████████████████████████████▌  | 39703/42525 [59:58<04:10, 11.27it/s]

 93%|█████████████████████████████████▌  | 39707/42525 [59:58<04:04, 11.51it/s]

 93%|█████████████████████████████████▌  | 39711/42525 [59:59<04:09, 11.27it/s]

 93%|█████████████████████████████████▌  | 39715/42525 [59:59<04:05, 11.46it/s]

 93%|█████████████████████████████████▌  | 39719/42525 [59:59<04:18, 10.86it/s]

 93%|███████████████████████████████▊  | 39723/42525 [1:00:00<04:12, 11.08it/s]

 93%|███████████████████████████████▊  | 39727/42525 [1:00:00<04:05, 11.38it/s]

 93%|███████████████████████████████▊  | 39731/42525 [1:00:00<04:11, 11.12it/s]

 93%|███████████████████████████████▊  | 39735/42525 [1:00:01<04:14, 10.96it/s]

 93%|███████████████████████████████▊  | 39739/42525 [1:00:01<04:03, 11.43it/s]

 93%|███████████████████████████████▊  | 39743/42525 [1:00:01<04:01, 11.54it/s]

 93%|███████████████████████████████▊  | 39747/42525 [1:00:02<04:09, 11.12it/s]

 93%|███████████████████████████████▊  | 39751/42525 [1:00:02<04:06, 11.24it/s]

 93%|███████████████████████████████▊  | 39755/42525 [1:00:03<04:17, 10.76it/s]

 93%|███████████████████████████████▊  | 39759/42525 [1:00:03<04:14, 10.85it/s]

 94%|███████████████████████████████▊  | 39763/42525 [1:00:03<04:11, 10.97it/s]

 94%|███████████████████████████████▊  | 39767/42525 [1:00:04<04:18, 10.65it/s]

 94%|███████████████████████████████▊  | 39771/42525 [1:00:04<04:09, 11.02it/s]

 94%|███████████████████████████████▊  | 39775/42525 [1:00:04<04:17, 10.67it/s]

 94%|███████████████████████████████▊  | 39779/42525 [1:00:05<04:09, 11.02it/s]

 94%|███████████████████████████████▊  | 39783/42525 [1:00:05<04:02, 11.29it/s]

 94%|███████████████████████████████▊  | 39787/42525 [1:00:05<04:00, 11.40it/s]

 94%|███████████████████████████████▊  | 39791/42525 [1:00:06<03:57, 11.53it/s]

 94%|███████████████████████████████▊  | 39795/42525 [1:00:06<04:00, 11.35it/s]

 94%|███████████████████████████████▊  | 39799/42525 [1:00:07<03:56, 11.55it/s]

 94%|███████████████████████████████▊  | 39803/42525 [1:00:07<03:54, 11.61it/s]

 94%|███████████████████████████████▊  | 39807/42525 [1:00:07<03:54, 11.58it/s]

 94%|███████████████████████████████▊  | 39811/42525 [1:00:08<03:51, 11.70it/s]

 94%|███████████████████████████████▊  | 39815/42525 [1:00:08<03:53, 11.60it/s]

 94%|███████████████████████████████▊  | 39819/42525 [1:00:08<03:55, 11.51it/s]

 94%|███████████████████████████████▊  | 39823/42525 [1:00:09<03:55, 11.47it/s]

 94%|███████████████████████████████▊  | 39827/42525 [1:00:09<04:00, 11.20it/s]

 94%|███████████████████████████████▊  | 39831/42525 [1:00:09<04:00, 11.18it/s]

 94%|███████████████████████████████▊  | 39835/42525 [1:00:10<03:53, 11.53it/s]

 94%|███████████████████████████████▊  | 39839/42525 [1:00:10<03:58, 11.28it/s]

 94%|███████████████████████████████▊  | 39843/42525 [1:00:10<04:06, 10.88it/s]

 94%|███████████████████████████████▊  | 39847/42525 [1:00:11<04:04, 10.93it/s]

 94%|███████████████████████████████▊  | 39851/42525 [1:00:11<03:57, 11.27it/s]

 94%|███████████████████████████████▊  | 39855/42525 [1:00:11<03:54, 11.40it/s]

 94%|███████████████████████████████▊  | 39859/42525 [1:00:12<03:58, 11.16it/s]

 94%|███████████████████████████████▊  | 39863/42525 [1:00:12<03:59, 11.12it/s]

 94%|███████████████████████████████▊  | 39867/42525 [1:00:13<04:09, 10.67it/s]

 94%|███████████████████████████████▉  | 39871/42525 [1:00:13<04:12, 10.52it/s]

 94%|███████████████████████████████▉  | 39873/42525 [1:00:13<04:05, 10.81it/s]

 94%|███████████████████████████████▉  | 39877/42525 [1:00:14<04:09, 10.61it/s]

 94%|███████████████████████████████▉  | 39881/42525 [1:00:14<04:04, 10.83it/s]

 94%|███████████████████████████████▉  | 39885/42525 [1:00:14<03:53, 11.29it/s]

 94%|███████████████████████████████▉  | 39887/42525 [1:00:14<03:52, 11.35it/s]

 94%|███████████████████████████████▉  | 39891/42525 [1:00:15<03:57, 11.08it/s]

 94%|███████████████████████████████▉  | 39895/42525 [1:00:15<03:51, 11.36it/s]

 94%|███████████████████████████████▉  | 39899/42525 [1:00:15<03:52, 11.31it/s]

 94%|███████████████████████████████▉  | 39903/42525 [1:00:16<03:51, 11.34it/s]

 94%|███████████████████████████████▉  | 39907/42525 [1:00:16<03:52, 11.26it/s]

 94%|███████████████████████████████▉  | 39911/42525 [1:00:17<03:48, 11.45it/s]

 94%|███████████████████████████████▉  | 39915/42525 [1:00:17<03:50, 11.34it/s]

 94%|███████████████████████████████▉  | 39919/42525 [1:00:17<03:50, 11.33it/s]

 94%|███████████████████████████████▉  | 39923/42525 [1:00:18<03:41, 11.77it/s]

 94%|███████████████████████████████▉  | 39927/42525 [1:00:18<03:36, 12.01it/s]

 94%|███████████████████████████████▉  | 39931/42525 [1:00:18<03:37, 11.91it/s]

 94%|███████████████████████████████▉  | 39935/42525 [1:00:19<03:39, 11.79it/s]

 94%|███████████████████████████████▉  | 39939/42525 [1:00:19<03:42, 11.61it/s]

 94%|███████████████████████████████▉  | 39943/42525 [1:00:19<03:47, 11.34it/s]

 94%|███████████████████████████████▉  | 39947/42525 [1:00:20<04:00, 10.73it/s]

 94%|███████████████████████████████▉  | 39951/42525 [1:00:20<03:53, 11.01it/s]

 94%|███████████████████████████████▉  | 39955/42525 [1:00:20<03:48, 11.27it/s]

 94%|███████████████████████████████▉  | 39959/42525 [1:00:21<03:50, 11.15it/s]

 94%|███████████████████████████████▉  | 39963/42525 [1:00:21<03:44, 11.41it/s]

 94%|███████████████████████████████▉  | 39967/42525 [1:00:21<03:43, 11.47it/s]

 94%|███████████████████████████████▉  | 39971/42525 [1:00:22<03:50, 11.09it/s]

 94%|███████████████████████████████▉  | 39973/42525 [1:00:22<03:57, 10.74it/s]

 94%|███████████████████████████████▉  | 39977/42525 [1:00:22<04:05, 10.38it/s]

 94%|███████████████████████████████▉  | 39981/42525 [1:00:23<04:00, 10.57it/s]

 94%|███████████████████████████████▉  | 39985/42525 [1:00:23<03:48, 11.13it/s]

 94%|███████████████████████████████▉  | 39989/42525 [1:00:23<03:45, 11.26it/s]

 94%|███████████████████████████████▉  | 39993/42525 [1:00:24<03:44, 11.29it/s]

 94%|███████████████████████████████▉  | 39997/42525 [1:00:24<03:44, 11.25it/s]

 94%|███████████████████████████████▉  | 40001/42525 [1:00:25<03:56, 10.69it/s]

 94%|███████████████████████████████▉  | 40005/42525 [1:00:25<03:52, 10.82it/s]

 94%|███████████████████████████████▉  | 40009/42525 [1:00:25<03:50, 10.91it/s]

 94%|███████████████████████████████▉  | 40013/42525 [1:00:26<03:49, 10.92it/s]

 94%|███████████████████████████████▉  | 40017/42525 [1:00:26<03:45, 11.11it/s]

 94%|███████████████████████████████▉  | 40021/42525 [1:00:26<03:39, 11.38it/s]

 94%|████████████████████████████████  | 40025/42525 [1:00:27<03:38, 11.43it/s]

 94%|████████████████████████████████  | 40029/42525 [1:00:27<03:45, 11.07it/s]

 94%|████████████████████████████████  | 40033/42525 [1:00:27<03:41, 11.25it/s]

 94%|████████████████████████████████  | 40037/42525 [1:00:28<03:37, 11.46it/s]

 94%|████████████████████████████████  | 40041/42525 [1:00:28<03:43, 11.09it/s]

 94%|████████████████████████████████  | 40045/42525 [1:00:29<03:51, 10.71it/s]

 94%|████████████████████████████████  | 40049/42525 [1:00:29<03:44, 11.01it/s]

 94%|████████████████████████████████  | 40053/42525 [1:00:29<03:40, 11.23it/s]

 94%|████████████████████████████████  | 40057/42525 [1:00:30<03:39, 11.24it/s]

 94%|████████████████████████████████  | 40061/42525 [1:00:30<03:40, 11.16it/s]

 94%|████████████████████████████████  | 40065/42525 [1:00:30<03:35, 11.41it/s]

 94%|████████████████████████████████  | 40067/42525 [1:00:31<03:35, 11.40it/s]

 94%|████████████████████████████████  | 40071/42525 [1:00:31<03:46, 10.82it/s]

 94%|████████████████████████████████  | 40075/42525 [1:00:31<03:46, 10.83it/s]

 94%|████████████████████████████████  | 40079/42525 [1:00:32<03:46, 10.81it/s]

 94%|████████████████████████████████  | 40083/42525 [1:00:32<03:37, 11.21it/s]

 94%|████████████████████████████████  | 40087/42525 [1:00:32<03:35, 11.33it/s]

 94%|████████████████████████████████  | 40091/42525 [1:00:33<03:35, 11.31it/s]

 94%|████████████████████████████████  | 40095/42525 [1:00:33<03:33, 11.39it/s]

 94%|████████████████████████████████  | 40099/42525 [1:00:33<03:35, 11.28it/s]

 94%|████████████████████████████████  | 40103/42525 [1:00:34<03:43, 10.81it/s]

 94%|████████████████████████████████  | 40107/42525 [1:00:34<03:36, 11.16it/s]

 94%|████████████████████████████████  | 40111/42525 [1:00:34<03:29, 11.53it/s]

 94%|████████████████████████████████  | 40115/42525 [1:00:35<03:27, 11.62it/s]

 94%|████████████████████████████████  | 40119/42525 [1:00:35<03:24, 11.77it/s]

 94%|████████████████████████████████  | 40123/42525 [1:00:36<03:27, 11.58it/s]

 94%|████████████████████████████████  | 40127/42525 [1:00:36<03:35, 11.15it/s]

 94%|████████████████████████████████  | 40131/42525 [1:00:36<03:34, 11.14it/s]

 94%|████████████████████████████████  | 40135/42525 [1:00:37<03:39, 10.87it/s]

 94%|████████████████████████████████  | 40139/42525 [1:00:37<03:37, 10.96it/s]

 94%|████████████████████████████████  | 40143/42525 [1:00:37<03:40, 10.78it/s]

 94%|████████████████████████████████  | 40147/42525 [1:00:38<03:36, 10.99it/s]

 94%|████████████████████████████████  | 40151/42525 [1:00:38<03:28, 11.40it/s]

 94%|████████████████████████████████  | 40155/42525 [1:00:38<03:23, 11.64it/s]

 94%|████████████████████████████████  | 40159/42525 [1:00:39<03:27, 11.40it/s]

 94%|████████████████████████████████  | 40163/42525 [1:00:39<03:22, 11.65it/s]

 94%|████████████████████████████████  | 40167/42525 [1:00:39<03:32, 11.12it/s]

 94%|████████████████████████████████  | 40171/42525 [1:00:40<03:24, 11.52it/s]

 94%|████████████████████████████████  | 40175/42525 [1:00:40<03:29, 11.22it/s]

 94%|████████████████████████████████  | 40179/42525 [1:00:40<03:22, 11.57it/s]

 94%|████████████████████████████████▏ | 40183/42525 [1:00:41<03:23, 11.48it/s]

 95%|████████████████████████████████▏ | 40187/42525 [1:00:41<03:22, 11.57it/s]

 95%|████████████████████████████████▏ | 40191/42525 [1:00:42<03:19, 11.68it/s]

 95%|████████████████████████████████▏ | 40195/42525 [1:00:42<03:22, 11.51it/s]

 95%|████████████████████████████████▏ | 40199/42525 [1:00:42<03:31, 10.98it/s]

 95%|████████████████████████████████▏ | 40203/42525 [1:00:43<03:25, 11.32it/s]

 95%|████████████████████████████████▏ | 40207/42525 [1:00:43<03:27, 11.19it/s]

 95%|████████████████████████████████▏ | 40211/42525 [1:00:43<03:22, 11.40it/s]

 95%|████████████████████████████████▏ | 40215/42525 [1:00:44<03:19, 11.56it/s]

 95%|████████████████████████████████▏ | 40219/42525 [1:00:44<03:19, 11.58it/s]

 95%|████████████████████████████████▏ | 40223/42525 [1:00:44<03:17, 11.64it/s]

 95%|████████████████████████████████▏ | 40227/42525 [1:00:45<03:23, 11.30it/s]

 95%|████████████████████████████████▏ | 40231/42525 [1:00:45<03:22, 11.36it/s]

 95%|████████████████████████████████▏ | 40235/42525 [1:00:45<03:22, 11.28it/s]

 95%|████████████████████████████████▏ | 40239/42525 [1:00:46<03:18, 11.51it/s]

 95%|████████████████████████████████▏ | 40243/42525 [1:00:46<03:21, 11.33it/s]

 95%|████████████████████████████████▏ | 40247/42525 [1:00:46<03:21, 11.28it/s]

 95%|████████████████████████████████▏ | 40251/42525 [1:00:47<03:25, 11.07it/s]

 95%|████████████████████████████████▏ | 40255/42525 [1:00:47<03:24, 11.08it/s]

 95%|████████████████████████████████▏ | 40259/42525 [1:00:48<03:21, 11.25it/s]

 95%|████████████████████████████████▏ | 40263/42525 [1:00:48<03:21, 11.22it/s]

 95%|████████████████████████████████▏ | 40267/42525 [1:00:48<03:17, 11.41it/s]

 95%|████████████████████████████████▏ | 40271/42525 [1:00:49<03:14, 11.58it/s]

 95%|████████████████████████████████▏ | 40275/42525 [1:00:49<03:18, 11.35it/s]

 95%|████████████████████████████████▏ | 40279/42525 [1:00:49<03:19, 11.23it/s]

 95%|████████████████████████████████▏ | 40283/42525 [1:00:50<03:15, 11.47it/s]

 95%|████████████████████████████████▏ | 40285/42525 [1:00:50<03:28, 10.72it/s]

 95%|████████████████████████████████▏ | 40289/42525 [1:00:50<03:36, 10.34it/s]

 95%|████████████████████████████████▏ | 40293/42525 [1:00:51<03:31, 10.57it/s]

 95%|████████████████████████████████▏ | 40297/42525 [1:00:51<03:20, 11.11it/s]

 95%|████████████████████████████████▏ | 40301/42525 [1:00:51<03:17, 11.28it/s]

 95%|████████████████████████████████▏ | 40305/42525 [1:00:52<03:20, 11.10it/s]

 95%|████████████████████████████████▏ | 40309/42525 [1:00:52<03:20, 11.04it/s]

 95%|████████████████████████████████▏ | 40313/42525 [1:00:52<03:19, 11.09it/s]

 95%|████████████████████████████████▏ | 40317/42525 [1:00:53<03:25, 10.76it/s]

 95%|████████████████████████████████▏ | 40321/42525 [1:00:53<03:25, 10.75it/s]

 95%|████████████████████████████████▏ | 40325/42525 [1:00:54<03:21, 10.92it/s]

 95%|████████████████████████████████▏ | 40327/42525 [1:00:54<03:17, 11.11it/s]

 95%|████████████████████████████████▏ | 40331/42525 [1:00:54<03:25, 10.66it/s]

 95%|████████████████████████████████▏ | 40335/42525 [1:00:54<03:18, 11.03it/s]

 95%|████████████████████████████████▎ | 40339/42525 [1:00:55<03:12, 11.33it/s]

 95%|████████████████████████████████▎ | 40343/42525 [1:00:55<03:18, 10.99it/s]

 95%|████████████████████████████████▎ | 40347/42525 [1:00:55<03:11, 11.39it/s]

 95%|████████████████████████████████▎ | 40351/42525 [1:00:56<03:08, 11.52it/s]

 95%|████████████████████████████████▎ | 40355/42525 [1:00:56<03:14, 11.18it/s]

 95%|████████████████████████████████▎ | 40359/42525 [1:00:57<03:11, 11.30it/s]

 95%|████████████████████████████████▎ | 40363/42525 [1:00:57<03:16, 10.98it/s]

 95%|████████████████████████████████▎ | 40367/42525 [1:00:57<03:09, 11.36it/s]

 95%|████████████████████████████████▎ | 40371/42525 [1:00:58<03:13, 11.13it/s]

 95%|████████████████████████████████▎ | 40375/42525 [1:00:58<03:08, 11.40it/s]

 95%|████████████████████████████████▎ | 40379/42525 [1:00:58<03:05, 11.58it/s]

 95%|████████████████████████████████▎ | 40381/42525 [1:00:59<03:04, 11.65it/s]

 95%|████████████████████████████████▎ | 40385/42525 [1:00:59<03:18, 10.78it/s]

 95%|████████████████████████████████▎ | 40389/42525 [1:00:59<03:08, 11.33it/s]

 95%|████████████████████████████████▎ | 40393/42525 [1:01:00<03:14, 10.96it/s]

 95%|████████████████████████████████▎ | 40397/42525 [1:01:00<03:17, 10.80it/s]

 95%|████████████████████████████████▎ | 40401/42525 [1:01:00<03:17, 10.78it/s]

 95%|████████████████████████████████▎ | 40405/42525 [1:01:01<03:15, 10.82it/s]

 95%|████████████████████████████████▎ | 40409/42525 [1:01:01<03:08, 11.22it/s]

 95%|████████████████████████████████▎ | 40413/42525 [1:01:01<03:05, 11.38it/s]

 95%|████████████████████████████████▎ | 40417/42525 [1:01:02<03:02, 11.58it/s]

 95%|████████████████████████████████▎ | 40421/42525 [1:01:02<03:09, 11.07it/s]

 95%|████████████████████████████████▎ | 40425/42525 [1:01:02<03:04, 11.40it/s]

 95%|████████████████████████████████▎ | 40429/42525 [1:01:03<03:00, 11.61it/s]

 95%|████████████████████████████████▎ | 40433/42525 [1:01:03<03:04, 11.35it/s]

 95%|████████████████████████████████▎ | 40437/42525 [1:01:04<03:10, 10.98it/s]

 95%|████████████████████████████████▎ | 40441/42525 [1:01:04<03:03, 11.35it/s]

 95%|████████████████████████████████▎ | 40445/42525 [1:01:04<03:02, 11.40it/s]

 95%|████████████████████████████████▎ | 40449/42525 [1:01:05<03:01, 11.42it/s]

 95%|████████████████████████████████▎ | 40453/42525 [1:01:05<02:57, 11.69it/s]

 95%|████████████████████████████████▎ | 40457/42525 [1:01:05<02:47, 12.38it/s]

 95%|████████████████████████████████▎ | 40461/42525 [1:01:06<02:48, 12.22it/s]

 95%|████████████████████████████████▎ | 40465/42525 [1:01:06<02:47, 12.30it/s]

 95%|████████████████████████████████▎ | 40469/42525 [1:01:06<02:57, 11.55it/s]

 95%|████████████████████████████████▎ | 40473/42525 [1:01:07<03:05, 11.06it/s]

 95%|████████████████████████████████▎ | 40477/42525 [1:01:07<02:48, 12.14it/s]

 95%|████████████████████████████████▎ | 40481/42525 [1:01:07<02:36, 13.06it/s]

 95%|████████████████████████████████▎ | 40485/42525 [1:01:08<02:41, 12.61it/s]

 95%|████████████████████████████████▎ | 40489/42525 [1:01:08<02:53, 11.73it/s]

 95%|████████████████████████████████▍ | 40493/42525 [1:01:08<02:42, 12.48it/s]

 95%|████████████████████████████████▍ | 40497/42525 [1:01:09<02:48, 12.03it/s]

 95%|████████████████████████████████▍ | 40501/42525 [1:01:09<02:50, 11.86it/s]

 95%|████████████████████████████████▍ | 40505/42525 [1:01:09<02:52, 11.71it/s]

 95%|████████████████████████████████▍ | 40509/42525 [1:01:10<02:53, 11.63it/s]

 95%|████████████████████████████████▍ | 40513/42525 [1:01:10<02:59, 11.23it/s]

 95%|████████████████████████████████▍ | 40517/42525 [1:01:10<02:50, 11.78it/s]

 95%|████████████████████████████████▍ | 40521/42525 [1:01:11<02:47, 11.99it/s]

 95%|████████████████████████████████▍ | 40525/42525 [1:01:11<02:54, 11.48it/s]

 95%|████████████████████████████████▍ | 40529/42525 [1:01:11<02:36, 12.73it/s]

 95%|████████████████████████████████▍ | 40533/42525 [1:01:12<02:32, 13.06it/s]

 95%|████████████████████████████████▍ | 40537/42525 [1:01:12<02:45, 12.00it/s]

 95%|████████████████████████████████▍ | 40541/42525 [1:01:12<02:49, 11.73it/s]

 95%|████████████████████████████████▍ | 40545/42525 [1:01:13<02:47, 11.85it/s]

 95%|████████████████████████████████▍ | 40549/42525 [1:01:13<02:42, 12.13it/s]

 95%|████████████████████████████████▍ | 40553/42525 [1:01:13<02:30, 13.08it/s]

 95%|████████████████████████████████▍ | 40557/42525 [1:01:14<02:35, 12.63it/s]

 95%|████████████████████████████████▍ | 40561/42525 [1:01:14<02:39, 12.28it/s]

 95%|████████████████████████████████▍ | 40565/42525 [1:01:14<02:43, 11.99it/s]

 95%|████████████████████████████████▍ | 40569/42525 [1:01:15<02:55, 11.13it/s]

 95%|████████████████████████████████▍ | 40573/42525 [1:01:15<03:02, 10.70it/s]

 95%|████████████████████████████████▍ | 40577/42525 [1:01:15<02:53, 11.24it/s]

 95%|████████████████████████████████▍ | 40581/42525 [1:01:16<02:42, 11.94it/s]

 95%|████████████████████████████████▍ | 40585/42525 [1:01:16<02:46, 11.63it/s]

 95%|████████████████████████████████▍ | 40587/42525 [1:01:16<02:52, 11.24it/s]

 95%|████████████████████████████████▍ | 40591/42525 [1:01:16<02:48, 11.44it/s]

 95%|████████████████████████████████▍ | 40595/42525 [1:01:17<02:58, 10.79it/s]

 95%|████████████████████████████████▍ | 40599/42525 [1:01:17<02:46, 11.59it/s]

 95%|████████████████████████████████▍ | 40603/42525 [1:01:18<02:45, 11.58it/s]

 95%|████████████████████████████████▍ | 40607/42525 [1:01:18<02:37, 12.15it/s]

 95%|████████████████████████████████▍ | 40611/42525 [1:01:18<02:29, 12.84it/s]

 96%|████████████████████████████████▍ | 40615/42525 [1:01:18<02:28, 12.85it/s]

 96%|████████████████████████████████▍ | 40619/42525 [1:01:19<02:32, 12.49it/s]

 96%|████████████████████████████████▍ | 40623/42525 [1:01:19<02:37, 12.08it/s]

 96%|████████████████████████████████▍ | 40627/42525 [1:01:19<02:35, 12.24it/s]

 96%|████████████████████████████████▍ | 40631/42525 [1:01:20<02:36, 12.12it/s]

 96%|████████████████████████████████▍ | 40635/42525 [1:01:20<02:37, 12.01it/s]

 96%|████████████████████████████████▍ | 40639/42525 [1:01:20<02:31, 12.46it/s]

 96%|████████████████████████████████▍ | 40643/42525 [1:01:21<02:36, 12.00it/s]

 96%|████████████████████████████████▍ | 40647/42525 [1:01:21<02:43, 11.50it/s]

 96%|████████████████████████████████▌ | 40651/42525 [1:01:21<02:37, 11.89it/s]

 96%|████████████████████████████████▌ | 40655/42525 [1:01:22<02:32, 12.24it/s]

 96%|████████████████████████████████▌ | 40659/42525 [1:01:22<02:37, 11.85it/s]

 96%|████████████████████████████████▌ | 40663/42525 [1:01:22<02:29, 12.44it/s]

 96%|████████████████████████████████▌ | 40665/42525 [1:01:23<02:24, 12.90it/s]

 96%|████████████████████████████████▌ | 40669/42525 [1:01:23<02:45, 11.18it/s]

 96%|████████████████████████████████▌ | 40673/42525 [1:01:23<02:47, 11.08it/s]

 96%|████████████████████████████████▌ | 40677/42525 [1:01:24<02:33, 12.07it/s]

 96%|████████████████████████████████▌ | 40681/42525 [1:01:24<02:27, 12.47it/s]

 96%|████████████████████████████████▌ | 40683/42525 [1:01:24<02:25, 12.64it/s]

 96%|████████████████████████████████▌ | 40687/42525 [1:01:25<02:40, 11.46it/s]

 96%|████████████████████████████████▌ | 40691/42525 [1:01:25<02:38, 11.60it/s]

 96%|████████████████████████████████▌ | 40695/42525 [1:01:25<02:35, 11.77it/s]

 96%|████████████████████████████████▌ | 40699/42525 [1:01:26<02:40, 11.39it/s]

 96%|████████████████████████████████▌ | 40703/42525 [1:01:26<02:28, 12.25it/s]

 96%|████████████████████████████████▌ | 40707/42525 [1:01:26<02:36, 11.59it/s]

 96%|████████████████████████████████▌ | 40711/42525 [1:01:26<02:22, 12.74it/s]

 96%|████████████████████████████████▌ | 40713/42525 [1:01:27<02:22, 12.69it/s]

 96%|████████████████████████████████▌ | 40717/42525 [1:01:27<02:31, 11.95it/s]

 96%|████████████████████████████████▌ | 40721/42525 [1:01:27<02:19, 12.92it/s]

 96%|████████████████████████████████▌ | 40725/42525 [1:01:28<02:27, 12.24it/s]

 96%|████████████████████████████████▌ | 40729/42525 [1:01:28<02:24, 12.47it/s]

 96%|████████████████████████████████▌ | 40733/42525 [1:01:28<02:33, 11.64it/s]

 96%|████████████████████████████████▌ | 40737/42525 [1:01:29<02:24, 12.38it/s]

 96%|████████████████████████████████▌ | 40741/42525 [1:01:29<02:29, 11.97it/s]

 96%|████████████████████████████████▌ | 40745/42525 [1:01:29<02:33, 11.56it/s]

 96%|████████████████████████████████▌ | 40749/42525 [1:01:30<02:24, 12.26it/s]

 96%|████████████████████████████████▌ | 40753/42525 [1:01:30<02:14, 13.18it/s]

 96%|████████████████████████████████▌ | 40757/42525 [1:01:30<02:20, 12.56it/s]

 96%|████████████████████████████████▌ | 40761/42525 [1:01:31<02:28, 11.85it/s]

 96%|████████████████████████████████▌ | 40765/42525 [1:01:31<02:29, 11.81it/s]

 96%|████████████████████████████████▌ | 40769/42525 [1:01:31<02:34, 11.34it/s]

 96%|████████████████████████████████▌ | 40773/42525 [1:01:32<02:22, 12.26it/s]

 96%|████████████████████████████████▌ | 40777/42525 [1:01:32<02:31, 11.56it/s]

 96%|████████████████████████████████▌ | 40781/42525 [1:01:32<02:21, 12.30it/s]

 96%|████████████████████████████████▌ | 40785/42525 [1:01:33<02:17, 12.63it/s]

 96%|████████████████████████████████▌ | 40789/42525 [1:01:33<02:20, 12.39it/s]

 96%|████████████████████████████████▌ | 40793/42525 [1:01:33<02:17, 12.62it/s]

 96%|████████████████████████████████▌ | 40797/42525 [1:01:34<02:15, 12.71it/s]

 96%|████████████████████████████████▌ | 40801/42525 [1:01:34<02:24, 11.97it/s]

 96%|████████████████████████████████▌ | 40805/42525 [1:01:34<02:34, 11.16it/s]

 96%|████████████████████████████████▋ | 40809/42525 [1:01:35<02:37, 10.90it/s]

 96%|████████████████████████████████▋ | 40813/42525 [1:01:35<02:30, 11.40it/s]

 96%|████████████████████████████████▋ | 40817/42525 [1:01:35<02:26, 11.70it/s]

 96%|████████████████████████████████▋ | 40821/42525 [1:01:36<02:17, 12.39it/s]

 96%|████████████████████████████████▋ | 40825/42525 [1:01:36<02:14, 12.67it/s]

 96%|████████████████████████████████▋ | 40829/42525 [1:01:36<02:28, 11.39it/s]

 96%|████████████████████████████████▋ | 40833/42525 [1:01:37<02:29, 11.30it/s]

 96%|████████████████████████████████▋ | 40837/42525 [1:01:37<02:17, 12.23it/s]

 96%|████████████████████████████████▋ | 40841/42525 [1:01:37<02:15, 12.39it/s]

 96%|████████████████████████████████▋ | 40845/42525 [1:01:38<02:13, 12.57it/s]

 96%|████████████████████████████████▋ | 40849/42525 [1:01:38<02:11, 12.77it/s]

 96%|████████████████████████████████▋ | 40853/42525 [1:01:38<02:07, 13.16it/s]

 96%|████████████████████████████████▋ | 40857/42525 [1:01:39<02:14, 12.37it/s]

 96%|████████████████████████████████▋ | 40861/42525 [1:01:39<02:11, 12.65it/s]

 96%|████████████████████████████████▋ | 40865/42525 [1:01:39<02:23, 11.58it/s]

 96%|████████████████████████████████▋ | 40869/42525 [1:01:40<02:25, 11.39it/s]

 96%|████████████████████████████████▋ | 40873/42525 [1:01:40<02:16, 12.12it/s]

 96%|████████████████████████████████▋ | 40877/42525 [1:01:40<02:13, 12.37it/s]

 96%|████████████████████████████████▋ | 40881/42525 [1:01:41<02:18, 11.87it/s]

 96%|████████████████████████████████▋ | 40885/42525 [1:01:41<02:15, 12.14it/s]

 96%|████████████████████████████████▋ | 40889/42525 [1:01:41<02:11, 12.42it/s]

 96%|████████████████████████████████▋ | 40893/42525 [1:01:42<02:19, 11.68it/s]

 96%|████████████████████████████████▋ | 40897/42525 [1:01:42<02:11, 12.39it/s]

 96%|████████████████████████████████▋ | 40901/42525 [1:01:42<02:16, 11.87it/s]

 96%|████████████████████████████████▋ | 40905/42525 [1:01:42<02:07, 12.70it/s]

 96%|████████████████████████████████▋ | 40909/42525 [1:01:43<02:15, 11.95it/s]

 96%|████████████████████████████████▋ | 40913/42525 [1:01:43<02:19, 11.52it/s]

 96%|████████████████████████████████▋ | 40917/42525 [1:01:44<02:22, 11.32it/s]

 96%|████████████████████████████████▋ | 40921/42525 [1:01:44<02:16, 11.77it/s]

 96%|████████████████████████████████▋ | 40925/42525 [1:01:44<02:11, 12.18it/s]

 96%|████████████████████████████████▋ | 40929/42525 [1:01:45<02:09, 12.33it/s]

 96%|████████████████████████████████▋ | 40931/42525 [1:01:45<02:08, 12.39it/s]

 96%|████████████████████████████████▋ | 40935/42525 [1:01:45<02:17, 11.56it/s]

 96%|████████████████████████████████▋ | 40939/42525 [1:01:45<02:11, 12.06it/s]

 96%|████████████████████████████████▋ | 40943/42525 [1:01:46<02:07, 12.36it/s]

 96%|████████████████████████████████▋ | 40947/42525 [1:01:46<01:59, 13.22it/s]

 96%|████████████████████████████████▋ | 40951/42525 [1:01:46<02:13, 11.76it/s]

 96%|████████████████████████████████▋ | 40955/42525 [1:01:47<02:04, 12.56it/s]

 96%|████████████████████████████████▋ | 40959/42525 [1:01:47<02:06, 12.41it/s]

 96%|████████████████████████████████▊ | 40963/42525 [1:01:47<02:15, 11.54it/s]

 96%|████████████████████████████████▊ | 40967/42525 [1:01:48<02:13, 11.70it/s]

 96%|████████████████████████████████▊ | 40971/42525 [1:01:48<02:16, 11.40it/s]

 96%|████████████████████████████████▊ | 40975/42525 [1:01:48<02:17, 11.27it/s]

 96%|████████████████████████████████▊ | 40979/42525 [1:01:49<02:14, 11.47it/s]

 96%|████████████████████████████████▊ | 40983/42525 [1:01:49<02:04, 12.38it/s]

 96%|████████████████████████████████▊ | 40987/42525 [1:01:49<02:07, 12.07it/s]

 96%|████████████████████████████████▊ | 40991/42525 [1:01:50<02:15, 11.30it/s]

 96%|████████████████████████████████▊ | 40995/42525 [1:01:50<02:18, 11.09it/s]

 96%|████████████████████████████████▊ | 40999/42525 [1:01:51<02:19, 10.97it/s]

 96%|████████████████████████████████▊ | 41003/42525 [1:01:51<02:10, 11.64it/s]

 96%|████████████████████████████████▊ | 41007/42525 [1:01:51<02:11, 11.52it/s]

 96%|████████████████████████████████▊ | 41011/42525 [1:01:51<02:03, 12.29it/s]

 96%|████████████████████████████████▊ | 41013/42525 [1:01:52<02:12, 11.44it/s]

 96%|████████████████████████████████▊ | 41017/42525 [1:01:52<02:10, 11.56it/s]

 96%|████████████████████████████████▊ | 41021/42525 [1:01:52<02:04, 12.09it/s]

 96%|████████████████████████████████▊ | 41025/42525 [1:01:53<01:58, 12.62it/s]

 96%|████████████████████████████████▊ | 41029/42525 [1:01:53<02:00, 12.39it/s]

 96%|████████████████████████████████▊ | 41033/42525 [1:01:53<02:02, 12.16it/s]

 97%|████████████████████████████████▊ | 41037/42525 [1:01:54<01:57, 12.61it/s]

 97%|████████████████████████████████▊ | 41041/42525 [1:01:54<02:12, 11.21it/s]

 97%|████████████████████████████████▊ | 41043/42525 [1:01:54<02:13, 11.13it/s]

 97%|████████████████████████████████▊ | 41047/42525 [1:01:55<02:17, 10.78it/s]

 97%|████████████████████████████████▊ | 41051/42525 [1:01:55<02:08, 11.44it/s]

 97%|████████████████████████████████▊ | 41055/42525 [1:01:55<02:03, 11.86it/s]

 97%|████████████████████████████████▊ | 41059/42525 [1:01:56<02:04, 11.75it/s]

 97%|████████████████████████████████▊ | 41063/42525 [1:01:56<01:56, 12.59it/s]

 97%|████████████████████████████████▊ | 41067/42525 [1:01:56<01:55, 12.57it/s]

 97%|████████████████████████████████▊ | 41071/42525 [1:01:57<02:01, 11.97it/s]

 97%|████████████████████████████████▊ | 41075/42525 [1:01:57<02:00, 12.05it/s]

 97%|████████████████████████████████▊ | 41079/42525 [1:01:57<01:59, 12.12it/s]

 97%|████████████████████████████████▊ | 41083/42525 [1:01:58<01:52, 12.80it/s]

 97%|████████████████████████████████▊ | 41087/42525 [1:01:58<01:58, 12.13it/s]

 97%|████████████████████████████████▊ | 41091/42525 [1:01:58<01:59, 11.98it/s]

 97%|████████████████████████████████▊ | 41095/42525 [1:01:59<02:00, 11.89it/s]

 97%|████████████████████████████████▊ | 41099/42525 [1:01:59<02:03, 11.56it/s]

 97%|████████████████████████████████▊ | 41103/42525 [1:01:59<02:01, 11.68it/s]

 97%|████████████████████████████████▊ | 41107/42525 [1:02:00<02:04, 11.35it/s]

 97%|████████████████████████████████▊ | 41111/42525 [1:02:00<02:02, 11.54it/s]

 97%|████████████████████████████████▊ | 41115/42525 [1:02:00<02:09, 10.92it/s]

 97%|████████████████████████████████▉ | 41119/42525 [1:02:01<02:06, 11.08it/s]

 97%|████████████████████████████████▉ | 41123/42525 [1:02:01<02:05, 11.15it/s]

 97%|████████████████████████████████▉ | 41127/42525 [1:02:01<02:06, 11.04it/s]

 97%|████████████████████████████████▉ | 41131/42525 [1:02:02<02:11, 10.58it/s]

 97%|████████████████████████████████▉ | 41133/42525 [1:02:02<02:09, 10.77it/s]

 97%|████████████████████████████████▉ | 41137/42525 [1:02:02<02:07, 10.89it/s]

 97%|████████████████████████████████▉ | 41141/42525 [1:02:03<02:02, 11.29it/s]

 97%|████████████████████████████████▉ | 41145/42525 [1:02:03<01:59, 11.51it/s]

 97%|████████████████████████████████▉ | 41149/42525 [1:02:03<02:00, 11.39it/s]

 97%|████████████████████████████████▉ | 41153/42525 [1:02:04<02:02, 11.18it/s]

 97%|████████████████████████████████▉ | 41157/42525 [1:02:04<01:58, 11.56it/s]

 97%|████████████████████████████████▉ | 41161/42525 [1:02:04<01:58, 11.48it/s]

 97%|████████████████████████████████▉ | 41165/42525 [1:02:05<02:09, 10.53it/s]

 97%|████████████████████████████████▉ | 41169/42525 [1:02:05<02:11, 10.33it/s]

 97%|████████████████████████████████▉ | 41173/42525 [1:02:06<02:06, 10.71it/s]

 97%|████████████████████████████████▉ | 41177/42525 [1:02:06<02:04, 10.84it/s]

 97%|████████████████████████████████▉ | 41181/42525 [1:02:06<02:04, 10.81it/s]

 97%|████████████████████████████████▉ | 41185/42525 [1:02:07<01:55, 11.61it/s]

 97%|████████████████████████████████▉ | 41189/42525 [1:02:07<01:55, 11.56it/s]

 97%|████████████████████████████████▉ | 41193/42525 [1:02:07<01:54, 11.62it/s]

 97%|████████████████████████████████▉ | 41197/42525 [1:02:08<01:57, 11.30it/s]

 97%|████████████████████████████████▉ | 41201/42525 [1:02:08<01:57, 11.23it/s]

 97%|████████████████████████████████▉ | 41205/42525 [1:02:08<01:53, 11.66it/s]

 97%|████████████████████████████████▉ | 41209/42525 [1:02:09<01:57, 11.17it/s]

 97%|████████████████████████████████▉ | 41213/42525 [1:02:09<01:49, 12.03it/s]

 97%|████████████████████████████████▉ | 41217/42525 [1:02:09<01:48, 12.06it/s]

 97%|████████████████████████████████▉ | 41221/42525 [1:02:10<01:47, 12.14it/s]

 97%|████████████████████████████████▉ | 41225/42525 [1:02:10<01:43, 12.54it/s]

 97%|████████████████████████████████▉ | 41229/42525 [1:02:10<01:47, 12.11it/s]

 97%|████████████████████████████████▉ | 41233/42525 [1:02:11<01:48, 11.95it/s]

 97%|████████████████████████████████▉ | 41237/42525 [1:02:11<01:56, 11.05it/s]

 97%|████████████████████████████████▉ | 41241/42525 [1:02:11<01:53, 11.30it/s]

 97%|████████████████████████████████▉ | 41245/42525 [1:02:12<01:55, 11.05it/s]

 97%|████████████████████████████████▉ | 41249/42525 [1:02:12<01:53, 11.25it/s]

 97%|████████████████████████████████▉ | 41253/42525 [1:02:13<01:49, 11.57it/s]

 97%|████████████████████████████████▉ | 41257/42525 [1:02:13<01:48, 11.67it/s]

 97%|████████████████████████████████▉ | 41259/42525 [1:02:13<01:48, 11.63it/s]

 97%|████████████████████████████████▉ | 41263/42525 [1:02:13<01:54, 11.01it/s]

 97%|████████████████████████████████▉ | 41267/42525 [1:02:14<01:53, 11.08it/s]

 97%|████████████████████████████████▉ | 41271/42525 [1:02:14<01:53, 11.02it/s]

 97%|█████████████████████████████████ | 41275/42525 [1:02:15<01:56, 10.73it/s]

 97%|█████████████████████████████████ | 41279/42525 [1:02:15<01:51, 11.20it/s]

 97%|█████████████████████████████████ | 41283/42525 [1:02:15<01:49, 11.39it/s]

 97%|█████████████████████████████████ | 41287/42525 [1:02:16<01:50, 11.21it/s]

 97%|█████████████████████████████████ | 41291/42525 [1:02:16<01:50, 11.18it/s]

 97%|█████████████████████████████████ | 41295/42525 [1:02:16<01:51, 11.02it/s]

 97%|█████████████████████████████████ | 41299/42525 [1:02:17<01:48, 11.32it/s]

 97%|█████████████████████████████████ | 41303/42525 [1:02:17<01:49, 11.18it/s]

 97%|█████████████████████████████████ | 41307/42525 [1:02:17<01:50, 11.01it/s]

 97%|█████████████████████████████████ | 41311/42525 [1:02:18<01:51, 10.88it/s]

 97%|█████████████████████████████████ | 41315/42525 [1:02:18<01:50, 10.96it/s]

 97%|█████████████████████████████████ | 41319/42525 [1:02:18<01:46, 11.29it/s]

 97%|█████████████████████████████████ | 41323/42525 [1:02:19<01:47, 11.20it/s]

 97%|█████████████████████████████████ | 41327/42525 [1:02:19<01:45, 11.41it/s]

 97%|█████████████████████████████████ | 41331/42525 [1:02:20<01:46, 11.19it/s]

 97%|█████████████████████████████████ | 41335/42525 [1:02:20<01:45, 11.32it/s]

 97%|█████████████████████████████████ | 41339/42525 [1:02:20<01:44, 11.33it/s]

 97%|█████████████████████████████████ | 41343/42525 [1:02:21<01:42, 11.57it/s]

 97%|█████████████████████████████████ | 41347/42525 [1:02:21<01:40, 11.73it/s]

 97%|█████████████████████████████████ | 41351/42525 [1:02:21<01:44, 11.21it/s]

 97%|█████████████████████████████████ | 41355/42525 [1:02:22<01:42, 11.46it/s]

 97%|█████████████████████████████████ | 41359/42525 [1:02:22<01:40, 11.62it/s]

 97%|█████████████████████████████████ | 41363/42525 [1:02:22<01:39, 11.69it/s]

 97%|█████████████████████████████████ | 41367/42525 [1:02:23<01:39, 11.66it/s]

 97%|█████████████████████████████████ | 41371/42525 [1:02:23<01:40, 11.47it/s]

 97%|█████████████████████████████████ | 41375/42525 [1:02:23<01:39, 11.61it/s]

 97%|█████████████████████████████████ | 41379/42525 [1:02:24<01:37, 11.70it/s]

 97%|█████████████████████████████████ | 41383/42525 [1:02:24<01:37, 11.75it/s]

 97%|█████████████████████████████████ | 41385/42525 [1:02:24<01:36, 11.81it/s]

 97%|█████████████████████████████████ | 41389/42525 [1:02:25<01:42, 11.03it/s]

 97%|█████████████████████████████████ | 41393/42525 [1:02:25<01:46, 10.67it/s]

 97%|█████████████████████████████████ | 41397/42525 [1:02:25<01:43, 10.92it/s]

 97%|█████████████████████████████████ | 41401/42525 [1:02:26<01:48, 10.41it/s]

 97%|█████████████████████████████████ | 41405/42525 [1:02:26<01:42, 10.88it/s]

 97%|█████████████████████████████████ | 41409/42525 [1:02:26<01:39, 11.23it/s]

 97%|█████████████████████████████████ | 41413/42525 [1:02:27<01:40, 11.03it/s]

 97%|█████████████████████████████████ | 41417/42525 [1:02:27<01:43, 10.67it/s]

 97%|█████████████████████████████████ | 41421/42525 [1:02:27<01:38, 11.22it/s]

 97%|█████████████████████████████████ | 41425/42525 [1:02:28<01:37, 11.32it/s]

 97%|█████████████████████████████████ | 41429/42525 [1:02:28<01:40, 10.87it/s]

 97%|█████████████████████████████████▏| 41433/42525 [1:02:29<01:41, 10.77it/s]

 97%|█████████████████████████████████▏| 41437/42525 [1:02:29<01:40, 10.77it/s]

 97%|█████████████████████████████████▏| 41441/42525 [1:02:29<01:36, 11.24it/s]

 97%|█████████████████████████████████▏| 41445/42525 [1:02:30<01:34, 11.39it/s]

 97%|█████████████████████████████████▏| 41449/42525 [1:02:30<01:36, 11.10it/s]

 97%|█████████████████████████████████▏| 41453/42525 [1:02:30<01:38, 10.92it/s]

 97%|█████████████████████████████████▏| 41457/42525 [1:02:31<01:37, 10.98it/s]

 97%|█████████████████████████████████▏| 41461/42525 [1:02:31<01:34, 11.29it/s]

 98%|█████████████████████████████████▏| 41465/42525 [1:02:31<01:34, 11.24it/s]

 98%|█████████████████████████████████▏| 41469/42525 [1:02:32<01:31, 11.53it/s]

 98%|█████████████████████████████████▏| 41473/42525 [1:02:32<01:32, 11.42it/s]

 98%|█████████████████████████████████▏| 41477/42525 [1:02:33<01:32, 11.32it/s]

 98%|█████████████████████████████████▏| 41481/42525 [1:02:33<01:31, 11.40it/s]

 98%|█████████████████████████████████▏| 41485/42525 [1:02:33<01:35, 10.94it/s]

 98%|█████████████████████████████████▏| 41489/42525 [1:02:34<01:31, 11.36it/s]

 98%|█████████████████████████████████▏| 41493/42525 [1:02:34<01:32, 11.17it/s]

 98%|█████████████████████████████████▏| 41497/42525 [1:02:34<01:29, 11.47it/s]

 98%|█████████████████████████████████▏| 41501/42525 [1:02:35<01:30, 11.37it/s]

 98%|█████████████████████████████████▏| 41505/42525 [1:02:35<01:33, 10.95it/s]

 98%|█████████████████████████████████▏| 41509/42525 [1:02:35<01:31, 11.16it/s]

 98%|█████████████████████████████████▏| 41513/42525 [1:02:36<01:28, 11.42it/s]

 98%|█████████████████████████████████▏| 41517/42525 [1:02:36<01:28, 11.33it/s]

 98%|█████████████████████████████████▏| 41521/42525 [1:02:36<01:29, 11.28it/s]

 98%|█████████████████████████████████▏| 41525/42525 [1:02:37<01:27, 11.46it/s]

 98%|█████████████████████████████████▏| 41529/42525 [1:02:37<01:28, 11.28it/s]

 98%|█████████████████████████████████▏| 41533/42525 [1:02:38<01:31, 10.82it/s]

 98%|█████████████████████████████████▏| 41537/42525 [1:02:38<01:28, 11.22it/s]

 98%|█████████████████████████████████▏| 41541/42525 [1:02:38<01:28, 11.07it/s]

 98%|█████████████████████████████████▏| 41545/42525 [1:02:39<01:27, 11.20it/s]

 98%|█████████████████████████████████▏| 41549/42525 [1:02:39<01:27, 11.20it/s]

 98%|█████████████████████████████████▏| 41553/42525 [1:02:39<01:23, 11.71it/s]

 98%|█████████████████████████████████▏| 41557/42525 [1:02:40<01:24, 11.49it/s]

 98%|█████████████████████████████████▏| 41561/42525 [1:02:40<01:20, 11.92it/s]

 98%|█████████████████████████████████▏| 41565/42525 [1:02:40<01:20, 11.94it/s]

 98%|█████████████████████████████████▏| 41569/42525 [1:02:41<01:26, 11.01it/s]

 98%|█████████████████████████████████▏| 41573/42525 [1:02:41<01:20, 11.88it/s]

 98%|█████████████████████████████████▏| 41577/42525 [1:02:41<01:17, 12.19it/s]

 98%|█████████████████████████████████▏| 41581/42525 [1:02:42<01:17, 12.19it/s]

 98%|█████████████████████████████████▏| 41585/42525 [1:02:42<01:14, 12.57it/s]

 98%|█████████████████████████████████▎| 41587/42525 [1:02:42<01:14, 12.64it/s]

 98%|█████████████████████████████████▎| 41591/42525 [1:02:42<01:18, 11.92it/s]

 98%|█████████████████████████████████▎| 41595/42525 [1:02:43<01:17, 11.98it/s]

 98%|█████████████████████████████████▎| 41599/42525 [1:02:43<01:15, 12.19it/s]

 98%|█████████████████████████████████▎| 41603/42525 [1:02:43<01:17, 11.88it/s]

 98%|█████████████████████████████████▎| 41607/42525 [1:02:44<01:15, 12.21it/s]

 98%|█████████████████████████████████▎| 41611/42525 [1:02:44<01:12, 12.53it/s]

 98%|█████████████████████████████████▎| 41615/42525 [1:02:44<01:14, 12.15it/s]

 98%|█████████████████████████████████▎| 41619/42525 [1:02:45<01:10, 12.89it/s]

 98%|█████████████████████████████████▎| 41623/42525 [1:02:45<01:10, 12.85it/s]

 98%|█████████████████████████████████▎| 41627/42525 [1:02:45<01:13, 12.16it/s]

 98%|█████████████████████████████████▎| 41629/42525 [1:02:46<01:13, 12.12it/s]

 98%|█████████████████████████████████▎| 41633/42525 [1:02:46<01:19, 11.28it/s]

 98%|█████████████████████████████████▎| 41635/42525 [1:02:46<01:18, 11.35it/s]

 98%|█████████████████████████████████▎| 41639/42525 [1:02:47<01:23, 10.65it/s]

 98%|█████████████████████████████████▎| 41643/42525 [1:02:47<01:19, 11.16it/s]

 98%|█████████████████████████████████▎| 41647/42525 [1:02:47<01:18, 11.23it/s]

 98%|█████████████████████████████████▎| 41651/42525 [1:02:48<01:15, 11.51it/s]

 98%|█████████████████████████████████▎| 41655/42525 [1:02:48<01:15, 11.56it/s]

 98%|█████████████████████████████████▎| 41659/42525 [1:02:48<01:13, 11.73it/s]

 98%|█████████████████████████████████▎| 41663/42525 [1:02:49<01:13, 11.72it/s]

 98%|█████████████████████████████████▎| 41667/42525 [1:02:49<01:15, 11.44it/s]

 98%|█████████████████████████████████▎| 41671/42525 [1:02:49<01:17, 10.98it/s]

 98%|█████████████████████████████████▎| 41675/42525 [1:02:50<01:17, 10.92it/s]

 98%|█████████████████████████████████▎| 41679/42525 [1:02:50<01:14, 11.32it/s]

 98%|█████████████████████████████████▎| 41683/42525 [1:02:50<01:13, 11.38it/s]

 98%|█████████████████████████████████▎| 41687/42525 [1:02:51<01:15, 11.11it/s]

 98%|█████████████████████████████████▎| 41691/42525 [1:02:51<01:16, 10.90it/s]

 98%|█████████████████████████████████▎| 41695/42525 [1:02:51<01:15, 11.03it/s]

 98%|█████████████████████████████████▎| 41699/42525 [1:02:52<01:14, 11.13it/s]

 98%|█████████████████████████████████▎| 41703/42525 [1:02:52<01:13, 11.26it/s]

 98%|█████████████████████████████████▎| 41707/42525 [1:02:53<01:12, 11.32it/s]

 98%|█████████████████████████████████▎| 41711/42525 [1:02:53<01:10, 11.56it/s]

 98%|█████████████████████████████████▎| 41715/42525 [1:02:53<01:12, 11.20it/s]

 98%|█████████████████████████████████▎| 41719/42525 [1:02:54<01:11, 11.34it/s]

 98%|█████████████████████████████████▎| 41723/42525 [1:02:54<01:12, 11.13it/s]

 98%|█████████████████████████████████▎| 41727/42525 [1:02:54<01:11, 11.14it/s]

 98%|█████████████████████████████████▎| 41731/42525 [1:02:55<01:14, 10.71it/s]

 98%|█████████████████████████████████▎| 41735/42525 [1:02:55<01:10, 11.17it/s]

 98%|█████████████████████████████████▎| 41739/42525 [1:02:55<01:06, 11.90it/s]

 98%|█████████████████████████████████▎| 41743/42525 [1:02:56<01:09, 11.22it/s]

 98%|█████████████████████████████████▍| 41747/42525 [1:02:56<01:05, 11.79it/s]

 98%|█████████████████████████████████▍| 41751/42525 [1:02:56<01:01, 12.68it/s]

 98%|█████████████████████████████████▍| 41755/42525 [1:02:57<01:02, 12.29it/s]

 98%|█████████████████████████████████▍| 41759/42525 [1:02:57<01:04, 11.86it/s]

 98%|█████████████████████████████████▍| 41761/42525 [1:02:57<01:06, 11.54it/s]

 98%|█████████████████████████████████▍| 41765/42525 [1:02:58<01:09, 10.96it/s]

 98%|█████████████████████████████████▍| 41769/42525 [1:02:58<01:06, 11.30it/s]

 98%|█████████████████████████████████▍| 41773/42525 [1:02:58<01:07, 11.14it/s]

 98%|█████████████████████████████████▍| 41777/42525 [1:02:59<01:09, 10.84it/s]

 98%|█████████████████████████████████▍| 41781/42525 [1:02:59<01:05, 11.41it/s]

 98%|█████████████████████████████████▍| 41785/42525 [1:02:59<01:02, 11.81it/s]

 98%|█████████████████████████████████▍| 41789/42525 [1:03:00<01:01, 11.95it/s]

 98%|█████████████████████████████████▍| 41793/42525 [1:03:00<01:01, 11.90it/s]

 98%|█████████████████████████████████▍| 41797/42525 [1:03:00<01:01, 11.81it/s]

 98%|█████████████████████████████████▍| 41801/42525 [1:03:01<01:01, 11.78it/s]

 98%|█████████████████████████████████▍| 41805/42525 [1:03:01<01:04, 11.13it/s]

 98%|█████████████████████████████████▍| 41809/42525 [1:03:01<00:59, 11.99it/s]

 98%|█████████████████████████████████▍| 41813/42525 [1:03:02<00:59, 12.05it/s]

 98%|█████████████████████████████████▍| 41817/42525 [1:03:02<00:57, 12.31it/s]

 98%|█████████████████████████████████▍| 41821/42525 [1:03:02<00:58, 11.95it/s]

 98%|█████████████████████████████████▍| 41825/42525 [1:03:03<00:58, 11.91it/s]

 98%|█████████████████████████████████▍| 41827/42525 [1:03:03<01:00, 11.55it/s]

 98%|█████████████████████████████████▍| 41831/42525 [1:03:03<01:00, 11.43it/s]

 98%|█████████████████████████████████▍| 41835/42525 [1:03:04<00:59, 11.52it/s]

 98%|█████████████████████████████████▍| 41839/42525 [1:03:04<00:59, 11.57it/s]

 98%|█████████████████████████████████▍| 41843/42525 [1:03:04<00:57, 11.83it/s]

 98%|█████████████████████████████████▍| 41847/42525 [1:03:05<00:56, 12.08it/s]

 98%|█████████████████████████████████▍| 41851/42525 [1:03:05<00:55, 12.09it/s]

 98%|█████████████████████████████████▍| 41855/42525 [1:03:05<00:55, 12.09it/s]

 98%|█████████████████████████████████▍| 41859/42525 [1:03:06<00:55, 11.98it/s]

 98%|█████████████████████████████████▍| 41863/42525 [1:03:06<00:56, 11.62it/s]

 98%|█████████████████████████████████▍| 41867/42525 [1:03:06<00:58, 11.16it/s]

 98%|█████████████████████████████████▍| 41871/42525 [1:03:07<01:00, 10.90it/s]

 98%|█████████████████████████████████▍| 41875/42525 [1:03:07<00:58, 11.05it/s]

 98%|█████████████████████████████████▍| 41879/42525 [1:03:07<00:57, 11.19it/s]

 98%|█████████████████████████████████▍| 41883/42525 [1:03:08<00:54, 11.83it/s]

 98%|█████████████████████████████████▍| 41887/42525 [1:03:08<00:50, 12.59it/s]

 99%|█████████████████████████████████▍| 41891/42525 [1:03:08<00:55, 11.52it/s]

 99%|█████████████████████████████████▍| 41895/42525 [1:03:09<00:53, 11.78it/s]

 99%|█████████████████████████████████▍| 41899/42525 [1:03:09<00:54, 11.50it/s]

 99%|█████████████████████████████████▌| 41903/42525 [1:03:09<00:52, 11.94it/s]

 99%|█████████████████████████████████▌| 41907/42525 [1:03:10<00:49, 12.47it/s]

 99%|█████████████████████████████████▌| 41911/42525 [1:03:10<00:49, 12.43it/s]

 99%|█████████████████████████████████▌| 41915/42525 [1:03:10<00:47, 12.77it/s]

 99%|█████████████████████████████████▌| 41919/42525 [1:03:11<00:52, 11.53it/s]

 99%|█████████████████████████████████▌| 41923/42525 [1:03:11<00:51, 11.69it/s]

 99%|█████████████████████████████████▌| 41927/42525 [1:03:11<00:50, 11.84it/s]

 99%|█████████████████████████████████▌| 41931/42525 [1:03:12<00:51, 11.65it/s]

 99%|█████████████████████████████████▌| 41935/42525 [1:03:12<00:49, 11.94it/s]

 99%|█████████████████████████████████▌| 41939/42525 [1:03:12<00:46, 12.66it/s]

 99%|█████████████████████████████████▌| 41943/42525 [1:03:13<00:47, 12.28it/s]

 99%|█████████████████████████████████▌| 41947/42525 [1:03:13<00:49, 11.71it/s]

 99%|█████████████████████████████████▌| 41951/42525 [1:03:13<00:47, 11.97it/s]

 99%|█████████████████████████████████▌| 41955/42525 [1:03:14<00:48, 11.67it/s]

 99%|█████████████████████████████████▌| 41959/42525 [1:03:14<00:45, 12.35it/s]

 99%|█████████████████████████████████▌| 41963/42525 [1:03:14<00:44, 12.52it/s]

 99%|█████████████████████████████████▌| 41967/42525 [1:03:15<00:45, 12.22it/s]

 99%|█████████████████████████████████▌| 41971/42525 [1:03:15<00:45, 12.09it/s]

 99%|█████████████████████████████████▌| 41975/42525 [1:03:15<00:47, 11.52it/s]

 99%|█████████████████████████████████▌| 41979/42525 [1:03:16<00:45, 12.10it/s]

 99%|█████████████████████████████████▌| 41983/42525 [1:03:16<00:47, 11.38it/s]

 99%|█████████████████████████████████▌| 41987/42525 [1:03:16<00:45, 11.91it/s]

 99%|█████████████████████████████████▌| 41989/42525 [1:03:17<00:45, 11.68it/s]

 99%|█████████████████████████████████▌| 41993/42525 [1:03:17<00:46, 11.34it/s]

 99%|█████████████████████████████████▌| 41997/42525 [1:03:17<00:44, 11.89it/s]

 99%|█████████████████████████████████▌| 42001/42525 [1:03:18<00:40, 12.98it/s]

 99%|█████████████████████████████████▌| 42005/42525 [1:03:18<00:39, 13.16it/s]

 99%|█████████████████████████████████▌| 42009/42525 [1:03:18<00:41, 12.35it/s]

 99%|█████████████████████████████████▌| 42013/42525 [1:03:19<00:42, 12.02it/s]

 99%|█████████████████████████████████▌| 42017/42525 [1:03:19<00:39, 12.93it/s]

 99%|█████████████████████████████████▌| 42021/42525 [1:03:19<00:41, 12.29it/s]

 99%|█████████████████████████████████▌| 42025/42525 [1:03:20<00:39, 12.79it/s]

 99%|█████████████████████████████████▌| 42029/42525 [1:03:20<00:40, 12.32it/s]

 99%|█████████████████████████████████▌| 42033/42525 [1:03:20<00:39, 12.31it/s]

 99%|█████████████████████████████████▌| 42037/42525 [1:03:21<00:38, 12.55it/s]

 99%|█████████████████████████████████▌| 42041/42525 [1:03:21<00:38, 12.66it/s]

 99%|█████████████████████████████████▌| 42045/42525 [1:03:21<00:36, 13.02it/s]

 99%|█████████████████████████████████▌| 42049/42525 [1:03:21<00:37, 12.73it/s]

 99%|█████████████████████████████████▌| 42053/42525 [1:03:22<00:39, 12.09it/s]

 99%|█████████████████████████████████▋| 42057/42525 [1:03:22<00:39, 11.89it/s]

 99%|█████████████████████████████████▋| 42061/42525 [1:03:23<00:40, 11.56it/s]

 99%|█████████████████████████████████▋| 42065/42525 [1:03:23<00:40, 11.41it/s]

 99%|█████████████████████████████████▋| 42069/42525 [1:03:23<00:37, 12.12it/s]

 99%|█████████████████████████████████▋| 42073/42525 [1:03:24<00:40, 11.09it/s]

 99%|█████████████████████████████████▋| 42077/42525 [1:03:24<00:36, 12.21it/s]

 99%|█████████████████████████████████▋| 42081/42525 [1:03:24<00:33, 13.14it/s]

 99%|█████████████████████████████████▋| 42085/42525 [1:03:24<00:34, 12.60it/s]

 99%|█████████████████████████████████▋| 42089/42525 [1:03:25<00:35, 12.43it/s]

 99%|█████████████████████████████████▋| 42091/42525 [1:03:25<00:36, 11.82it/s]

 99%|█████████████████████████████████▋| 42095/42525 [1:03:25<00:38, 11.22it/s]

 99%|█████████████████████████████████▋| 42097/42525 [1:03:26<00:39, 10.90it/s]

 99%|█████████████████████████████████▋| 42101/42525 [1:03:26<00:40, 10.43it/s]

 99%|█████████████████████████████████▋| 42105/42525 [1:03:26<00:38, 10.99it/s]

 99%|█████████████████████████████████▋| 42109/42525 [1:03:27<00:39, 10.60it/s]

 99%|█████████████████████████████████▋| 42113/42525 [1:03:27<00:38, 10.82it/s]

 99%|█████████████████████████████████▋| 42115/42525 [1:03:27<00:38, 10.65it/s]

 99%|█████████████████████████████████▋| 42119/42525 [1:03:28<00:38, 10.54it/s]

 99%|█████████████████████████████████▋| 42123/42525 [1:03:28<00:36, 11.08it/s]

 99%|█████████████████████████████████▋| 42127/42525 [1:03:28<00:34, 11.45it/s]

 99%|█████████████████████████████████▋| 42131/42525 [1:03:29<00:33, 11.59it/s]

 99%|█████████████████████████████████▋| 42135/42525 [1:03:29<00:33, 11.62it/s]

 99%|█████████████████████████████████▋| 42139/42525 [1:03:29<00:33, 11.62it/s]

 99%|█████████████████████████████████▋| 42143/42525 [1:03:30<00:32, 11.66it/s]

 99%|█████████████████████████████████▋| 42147/42525 [1:03:30<00:32, 11.57it/s]

 99%|█████████████████████████████████▋| 42151/42525 [1:03:30<00:33, 11.32it/s]

 99%|█████████████████████████████████▋| 42155/42525 [1:03:31<00:31, 11.58it/s]

 99%|█████████████████████████████████▋| 42159/42525 [1:03:31<00:31, 11.52it/s]

 99%|█████████████████████████████████▋| 42163/42525 [1:03:31<00:31, 11.66it/s]

 99%|█████████████████████████████████▋| 42167/42525 [1:03:32<00:31, 11.27it/s]

 99%|█████████████████████████████████▋| 42171/42525 [1:03:32<00:30, 11.58it/s]

 99%|█████████████████████████████████▋| 42175/42525 [1:03:32<00:30, 11.44it/s]

 99%|█████████████████████████████████▋| 42179/42525 [1:03:33<00:29, 11.70it/s]

 99%|█████████████████████████████████▋| 42183/42525 [1:03:33<00:29, 11.64it/s]

 99%|█████████████████████████████████▋| 42187/42525 [1:03:34<00:29, 11.63it/s]

 99%|█████████████████████████████████▋| 42191/42525 [1:03:34<00:28, 11.64it/s]

 99%|█████████████████████████████████▋| 42195/42525 [1:03:34<00:28, 11.62it/s]

 99%|█████████████████████████████████▋| 42199/42525 [1:03:35<00:28, 11.29it/s]

 99%|█████████████████████████████████▋| 42203/42525 [1:03:35<00:28, 11.31it/s]

 99%|█████████████████████████████████▋| 42207/42525 [1:03:35<00:27, 11.58it/s]

 99%|█████████████████████████████████▋| 42211/42525 [1:03:36<00:26, 11.73it/s]

 99%|█████████████████████████████████▊| 42215/42525 [1:03:36<00:26, 11.55it/s]

 99%|█████████████████████████████████▊| 42219/42525 [1:03:36<00:27, 11.18it/s]

 99%|█████████████████████████████████▊| 42223/42525 [1:03:37<00:26, 11.43it/s]

 99%|█████████████████████████████████▊| 42227/42525 [1:03:37<00:25, 11.90it/s]

 99%|█████████████████████████████████▊| 42231/42525 [1:03:37<00:25, 11.60it/s]

 99%|█████████████████████████████████▊| 42235/42525 [1:03:38<00:24, 11.90it/s]

 99%|█████████████████████████████████▊| 42239/42525 [1:03:38<00:24, 11.88it/s]

 99%|█████████████████████████████████▊| 42243/42525 [1:03:38<00:23, 12.25it/s]

 99%|█████████████████████████████████▊| 42247/42525 [1:03:39<00:22, 12.20it/s]

 99%|█████████████████████████████████▊| 42251/42525 [1:03:39<00:22, 12.08it/s]

 99%|█████████████████████████████████▊| 42255/42525 [1:03:39<00:23, 11.61it/s]

 99%|█████████████████████████████████▊| 42259/42525 [1:03:40<00:23, 11.31it/s]

 99%|█████████████████████████████████▊| 42263/42525 [1:03:40<00:22, 11.40it/s]

 99%|█████████████████████████████████▊| 42267/42525 [1:03:40<00:22, 11.39it/s]

 99%|█████████████████████████████████▊| 42271/42525 [1:03:41<00:21, 11.57it/s]

 99%|█████████████████████████████████▊| 42275/42525 [1:03:41<00:21, 11.86it/s]

 99%|█████████████████████████████████▊| 42279/42525 [1:03:41<00:22, 11.10it/s]

 99%|█████████████████████████████████▊| 42283/42525 [1:03:42<00:21, 11.03it/s]

 99%|█████████████████████████████████▊| 42285/42525 [1:03:42<00:21, 11.23it/s]

 99%|█████████████████████████████████▊| 42289/42525 [1:03:42<00:21, 10.77it/s]

 99%|█████████████████████████████████▊| 42293/42525 [1:03:43<00:20, 11.25it/s]

 99%|█████████████████████████████████▊| 42297/42525 [1:03:43<00:20, 11.03it/s]

 99%|█████████████████████████████████▊| 42301/42525 [1:03:43<00:19, 11.24it/s]

 99%|█████████████████████████████████▊| 42305/42525 [1:03:44<00:19, 11.48it/s]

 99%|█████████████████████████████████▊| 42309/42525 [1:03:44<00:19, 11.05it/s]

100%|█████████████████████████████████▊| 42313/42525 [1:03:45<00:18, 11.37it/s]

100%|█████████████████████████████████▊| 42317/42525 [1:03:45<00:18, 11.21it/s]

100%|█████████████████████████████████▊| 42321/42525 [1:03:45<00:17, 11.54it/s]

100%|█████████████████████████████████▊| 42323/42525 [1:03:45<00:17, 11.62it/s]

100%|█████████████████████████████████▊| 42327/42525 [1:03:46<00:17, 11.03it/s]

100%|█████████████████████████████████▊| 42331/42525 [1:03:46<00:17, 11.40it/s]

100%|█████████████████████████████████▊| 42335/42525 [1:03:46<00:16, 11.71it/s]

100%|█████████████████████████████████▊| 42339/42525 [1:03:47<00:16, 11.61it/s]

100%|█████████████████████████████████▊| 42343/42525 [1:03:47<00:15, 11.52it/s]

100%|█████████████████████████████████▊| 42347/42525 [1:03:47<00:15, 11.21it/s]

100%|█████████████████████████████████▊| 42351/42525 [1:03:48<00:15, 11.40it/s]

100%|█████████████████████████████████▊| 42355/42525 [1:03:48<00:14, 11.51it/s]

100%|█████████████████████████████████▊| 42359/42525 [1:03:49<00:14, 11.12it/s]

100%|█████████████████████████████████▊| 42361/42525 [1:03:49<00:14, 11.34it/s]

100%|█████████████████████████████████▊| 42363/42525 [1:03:49<00:14, 10.86it/s]

100%|█████████████████████████████████▊| 42367/42525 [1:03:49<00:15, 10.51it/s]

100%|█████████████████████████████████▉| 42369/42525 [1:03:49<00:14, 10.66it/s]

100%|█████████████████████████████████▉| 42373/42525 [1:03:50<00:14, 10.66it/s]

100%|█████████████████████████████████▉| 42377/42525 [1:03:50<00:13, 11.08it/s]

100%|█████████████████████████████████▉| 42381/42525 [1:03:51<00:12, 11.44it/s]

100%|█████████████████████████████████▉| 42385/42525 [1:03:51<00:12, 11.36it/s]

100%|█████████████████████████████████▉| 42389/42525 [1:03:51<00:12, 11.15it/s]

100%|█████████████████████████████████▉| 42391/42525 [1:03:51<00:11, 11.74it/s]

100%|█████████████████████████████████▉| 42395/42525 [1:03:52<00:11, 11.04it/s]

100%|█████████████████████████████████▉| 42399/42525 [1:03:52<00:10, 11.78it/s]

100%|█████████████████████████████████▉| 42403/42525 [1:03:52<00:10, 11.25it/s]

100%|█████████████████████████████████▉| 42407/42525 [1:03:53<00:10, 10.83it/s]

100%|█████████████████████████████████▉| 42411/42525 [1:03:53<00:10, 10.91it/s]

100%|█████████████████████████████████▉| 42415/42525 [1:03:54<00:09, 11.36it/s]

100%|█████████████████████████████████▉| 42419/42525 [1:03:54<00:09, 11.19it/s]

100%|█████████████████████████████████▉| 42423/42525 [1:03:54<00:09, 11.32it/s]

100%|█████████████████████████████████▉| 42427/42525 [1:03:55<00:08, 11.58it/s]

100%|█████████████████████████████████▉| 42431/42525 [1:03:55<00:08, 11.50it/s]

100%|█████████████████████████████████▉| 42435/42525 [1:03:55<00:07, 12.05it/s]

100%|█████████████████████████████████▉| 42439/42525 [1:03:56<00:06, 12.53it/s]

100%|█████████████████████████████████▉| 42443/42525 [1:03:56<00:06, 12.66it/s]

100%|█████████████████████████████████▉| 42445/42525 [1:03:56<00:06, 11.65it/s]

100%|█████████████████████████████████▉| 42449/42525 [1:03:57<00:06, 11.05it/s]

100%|█████████████████████████████████▉| 42453/42525 [1:03:57<00:06, 11.28it/s]

100%|█████████████████████████████████▉| 42457/42525 [1:03:57<00:06, 11.22it/s]

100%|█████████████████████████████████▉| 42461/42525 [1:03:58<00:05, 11.08it/s]

100%|█████████████████████████████████▉| 42465/42525 [1:03:58<00:05, 11.20it/s]

100%|█████████████████████████████████▉| 42469/42525 [1:03:58<00:05, 10.99it/s]

100%|█████████████████████████████████▉| 42473/42525 [1:03:59<00:04, 11.30it/s]

100%|█████████████████████████████████▉| 42477/42525 [1:03:59<00:04, 11.46it/s]

100%|█████████████████████████████████▉| 42481/42525 [1:03:59<00:03, 11.20it/s]

100%|█████████████████████████████████▉| 42485/42525 [1:04:00<00:03, 11.55it/s]

100%|█████████████████████████████████▉| 42489/42525 [1:04:00<00:03, 11.30it/s]

100%|█████████████████████████████████▉| 42493/42525 [1:04:00<00:02, 11.47it/s]

100%|█████████████████████████████████▉| 42497/42525 [1:04:01<00:02, 11.01it/s]

100%|█████████████████████████████████▉| 42501/42525 [1:04:01<00:02, 10.99it/s]

100%|█████████████████████████████████▉| 42505/42525 [1:04:02<00:01, 11.23it/s]

100%|█████████████████████████████████▉| 42509/42525 [1:04:02<00:01, 11.03it/s]

100%|█████████████████████████████████▉| 42513/42525 [1:04:02<00:01, 10.54it/s]

100%|█████████████████████████████████▉| 42517/42525 [1:04:03<00:00, 10.71it/s]

100%|█████████████████████████████████▉| 42521/42525 [1:04:03<00:00, 10.93it/s]

100%|█████████████████████████████████▉| 42523/42525 [1:04:03<00:00, 11.02it/s]

100%|██████████████████████████████████| 42525/42525 [1:04:03<00:00,  9.62it/s]
  0%|                                                  | 0/788 [00:00<?, ?it/s]
  0%|▏                                         | 3/788 [00:00<00:30, 26.09it/s]

{'loss': '0.6802', 'grad_norm': '8.949', 'learning_rate': '5.003e-10', 'epoch': '3'}

  1%|▎                                         | 6/788 [00:00<00:35, 21.97it/s]
  1%|▍                                         | 9/788 [00:00<00:34, 22.63it/s]

  2%|▌                                        | 12/788 [00:00<00:31, 24.45it/s]
  2%|▊                                        | 15/788 [00:00<00:33, 23.06it/s]

  2%|▉                                        | 18/788 [00:00<00:35, 21.41it/s]
  3%|█                                        | 21/788 [00:00<00:36, 20.86it/s]

  3%|█▏                                       | 24/788 [00:01<00:35, 21.49it/s]
  3%|█▍                                       | 27/788 [00:01<00:36, 20.88it/s]

  4%|█▌                                       | 30/788 [00:01<00:35, 21.36it/s]
  4%|█▋                                       | 33/788 [00:01<00:35, 21.23it/s]

  5%|█▊                                       | 36/788 [00:01<00:37, 19.90it/s]
  5%|██                                       | 39/788 [00:01<00:35, 21.00it/s]

  5%|██▏                                      | 42/788 [00:01<00:34, 21.94it/s]
  6%|██▎                                      | 45/788 [00:02<00:31, 23.44it/s]

  6%|██▍                                      | 48/788 [00:02<00:32, 22.51it/s]
  6%|██▋                                      | 51/788 [00:02<00:31, 23.55it/s]

  7%|██▊                                      | 54/788 [00:02<00:30, 23.84it/s]
  7%|██▉                                      | 57/788 [00:02<00:31, 23.14it/s]

  8%|███                                      | 60/788 [00:02<00:30, 24.12it/s]
  8%|███▎                                     | 63/788 [00:02<00:32, 22.40it/s]

  8%|███▍                                     | 66/788 [00:02<00:31, 22.93it/s]
  9%|███▌                                     | 69/788 [00:03<00:33, 21.71it/s]

  9%|███▋                                     | 72/788 [00:03<00:33, 21.50it/s]
 10%|███▉                                     | 75/788 [00:03<00:34, 20.89it/s]

 10%|████                                     | 78/788 [00:03<00:33, 21.07it/s]
 10%|████▏                                    | 81/788 [00:03<00:34, 20.54it/s]

 11%|████▎                                    | 84/788 [00:03<00:34, 20.30it/s]
 11%|████▌                                    | 87/788 [00:03<00:34, 20.51it/s]

 11%|████▋                                    | 90/788 [00:04<00:33, 20.74it/s]
 12%|████▊                                    | 93/788 [00:04<00:35, 19.66it/s]

 12%|████▉                                    | 96/788 [00:04<00:34, 20.08it/s]
 13%|█████▏                                   | 99/788 [00:04<00:33, 20.28it/s]

 13%|█████▏                                  | 102/788 [00:04<00:33, 20.52it/s]
 13%|█████▎                                  | 105/788 [00:04<00:34, 19.88it/s]

 14%|█████▍                                  | 108/788 [00:05<00:32, 20.77it/s]
 14%|█████▋                                  | 111/788 [00:05<00:30, 22.28it/s]

 14%|█████▊                                  | 114/788 [00:05<00:30, 22.00it/s]
 15%|█████▉                                  | 117/788 [00:05<00:31, 21.06it/s]

 15%|██████                                  | 120/788 [00:05<00:32, 20.85it/s]
 16%|██████▏                                 | 123/788 [00:05<00:32, 20.43it/s]

 16%|██████▍                                 | 126/788 [00:05<00:29, 22.41it/s]
 16%|██████▌                                 | 129/788 [00:05<00:28, 23.42it/s]

 17%|██████▋                                 | 132/788 [00:06<00:29, 21.97it/s]
 17%|██████▊                                 | 135/788 [00:06<00:28, 22.82it/s]

 18%|███████                                 | 138/788 [00:06<00:28, 23.14it/s]
 18%|███████▏                                | 141/788 [00:06<00:29, 21.77it/s]

 18%|███████▎                                | 144/788 [00:06<00:31, 20.77it/s]
 19%|███████▌                                | 148/788 [00:06<00:26, 24.07it/s]

 19%|███████▋                                | 151/788 [00:06<00:25, 25.28it/s]
 20%|███████▊                                | 154/788 [00:07<00:26, 24.16it/s]

 20%|███████▉                                | 157/788 [00:07<00:26, 23.73it/s]
 20%|████████                                | 160/788 [00:07<00:26, 23.35it/s]

 21%|████████▎                               | 163/788 [00:07<00:29, 20.93it/s]
 21%|████████▍                               | 166/788 [00:07<00:29, 20.95it/s]

 21%|████████▌                               | 169/788 [00:07<00:29, 20.94it/s]
 22%|████████▋                               | 172/788 [00:07<00:27, 22.47it/s]

 22%|████████▉                               | 175/788 [00:08<00:27, 22.19it/s]
 23%|█████████                               | 178/788 [00:08<00:29, 21.01it/s]

 23%|█████████▏                              | 181/788 [00:08<00:29, 20.32it/s]
 23%|█████████▎                              | 184/788 [00:08<00:28, 20.92it/s]

 24%|█████████▍                              | 187/788 [00:08<00:29, 20.56it/s]
 24%|█████████▋                              | 190/788 [00:08<00:28, 20.66it/s]

 24%|█████████▊                              | 193/788 [00:08<00:29, 20.24it/s]
 25%|█████████▉                              | 196/788 [00:09<00:26, 22.26it/s]

 25%|██████████                              | 199/788 [00:09<00:27, 21.29it/s]
 26%|██████████▎                             | 202/788 [00:09<00:26, 21.84it/s]

 26%|██████████▍                             | 205/788 [00:09<00:26, 22.35it/s]
 26%|██████████▌                             | 208/788 [00:09<00:25, 23.07it/s]

 27%|██████████▋                             | 211/788 [00:09<00:26, 21.92it/s]
 27%|██████████▊                             | 214/788 [00:09<00:25, 22.67it/s]

 28%|███████████                             | 217/788 [00:09<00:26, 21.71it/s]
 28%|███████████▏                            | 220/788 [00:10<00:25, 22.07it/s]

 28%|███████████▎                            | 223/788 [00:10<00:24, 22.66it/s]
 29%|███████████▍                            | 226/788 [00:10<00:25, 22.26it/s]

 29%|███████████▌                            | 229/788 [00:10<00:23, 23.95it/s]
 29%|███████████▊                            | 232/788 [00:10<00:23, 23.42it/s]

 30%|███████████▉                            | 235/788 [00:10<00:23, 23.13it/s]
 30%|████████████                            | 238/788 [00:10<00:24, 22.74it/s]

 31%|████████████▏                           | 241/788 [00:11<00:23, 23.23it/s]
 31%|████████████▍                           | 244/788 [00:11<00:24, 22.28it/s]

 31%|████████████▌                           | 247/788 [00:11<00:25, 21.24it/s]
 32%|████████████▋                           | 250/788 [00:11<00:25, 20.92it/s]

 32%|████████████▊                           | 253/788 [00:11<00:25, 21.06it/s]
 32%|████████████▉                           | 256/788 [00:11<00:24, 22.09it/s]

 33%|█████████████▏                          | 259/788 [00:11<00:25, 20.85it/s]
 33%|█████████████▎                          | 262/788 [00:12<00:24, 21.24it/s]

 34%|█████████████▍                          | 265/788 [00:12<00:25, 20.74it/s]
 34%|█████████████▌                          | 268/788 [00:12<00:24, 21.05it/s]

 34%|█████████████▊                          | 271/788 [00:12<00:25, 20.52it/s]
 35%|█████████████▉                          | 274/788 [00:12<00:25, 19.90it/s]

 35%|██████████████                          | 277/788 [00:12<00:26, 19.02it/s]
 35%|██████████████▏                         | 279/788 [00:12<00:26, 18.93it/s]

 36%|██████████████▎                         | 282/788 [00:13<00:25, 19.90it/s]
 36%|██████████████▍                         | 285/788 [00:13<00:25, 19.81it/s]

 37%|██████████████▌                         | 288/788 [00:13<00:23, 20.90it/s]
 37%|██████████████▊                         | 292/788 [00:13<00:20, 23.66it/s]

 37%|██████████████▉                         | 295/788 [00:13<00:21, 23.02it/s]
 38%|███████████████▏                        | 298/788 [00:13<00:21, 22.59it/s]

 38%|███████████████▎                        | 301/788 [00:13<00:21, 23.14it/s]
 39%|███████████████▍                        | 304/788 [00:13<00:20, 23.06it/s]

 39%|███████████████▌                        | 307/788 [00:14<00:21, 22.57it/s]
 39%|███████████████▋                        | 310/788 [00:14<00:20, 22.83it/s]

 40%|███████████████▉                        | 313/788 [00:14<00:21, 22.13it/s]
 40%|████████████████                        | 316/788 [00:14<00:21, 22.47it/s]

 40%|████████████████▏                       | 319/788 [00:14<00:21, 22.25it/s]
 41%|████████████████▎                       | 322/788 [00:14<00:20, 22.40it/s]

 41%|████████████████▍                       | 325/788 [00:14<00:21, 21.41it/s]
 42%|████████████████▋                       | 328/788 [00:15<00:21, 21.69it/s]

 42%|████████████████▊                       | 331/788 [00:15<00:20, 22.05it/s]
 42%|████████████████▉                       | 334/788 [00:15<00:19, 23.34it/s]

 43%|█████████████████                       | 337/788 [00:15<00:19, 23.35it/s]
 43%|█████████████████▎                      | 340/788 [00:15<00:19, 22.42it/s]

 44%|█████████████████▍                      | 343/788 [00:15<00:21, 20.93it/s]
 44%|█████████████████▌                      | 346/788 [00:15<00:22, 19.39it/s]

 44%|█████████████████▋                      | 349/788 [00:16<00:21, 20.10it/s]
 45%|█████████████████▊                      | 352/788 [00:16<00:20, 21.62it/s]

 45%|██████████████████                      | 355/788 [00:16<00:20, 21.58it/s]
 45%|██████████████████▏                     | 358/788 [00:16<00:20, 20.93it/s]

 46%|██████████████████▎                     | 361/788 [00:16<00:19, 22.14it/s]
 46%|██████████████████▍                     | 364/788 [00:16<00:17, 23.66it/s]

 47%|██████████████████▋                     | 367/788 [00:16<00:18, 23.09it/s]
 47%|██████████████████▊                     | 370/788 [00:16<00:17, 23.75it/s]

 47%|██████████████████▉                     | 373/788 [00:17<00:17, 24.14it/s]
 48%|███████████████████                     | 376/788 [00:17<00:16, 24.45it/s]

 48%|███████████████████▎                    | 380/788 [00:17<00:15, 26.08it/s]
 49%|███████████████████▍                    | 383/788 [00:17<00:16, 25.06it/s]

 49%|███████████████████▌                    | 386/788 [00:17<00:16, 24.14it/s]
 49%|███████████████████▋                    | 389/788 [00:17<00:17, 23.16it/s]

 50%|███████████████████▉                    | 392/788 [00:17<00:18, 21.67it/s]
 50%|████████████████████                    | 395/788 [00:18<00:17, 22.65it/s]

 51%|████████████████████▏                   | 398/788 [00:18<00:17, 22.29it/s]
 51%|████████████████████▎                   | 401/788 [00:18<00:16, 22.98it/s]

 51%|████████████████████▌                   | 404/788 [00:18<00:16, 23.76it/s]
 52%|████████████████████▋                   | 407/788 [00:18<00:15, 23.96it/s]

 52%|████████████████████▊                   | 410/788 [00:18<00:15, 24.44it/s]
 52%|████████████████████▉                   | 413/788 [00:18<00:15, 23.96it/s]

 53%|█████████████████████                   | 416/788 [00:18<00:15, 23.85it/s]
 53%|█████████████████████▎                  | 419/788 [00:19<00:17, 21.20it/s]

 54%|█████████████████████▍                  | 422/788 [00:19<00:17, 20.93it/s]
 54%|█████████████████████▌                  | 425/788 [00:19<00:17, 21.25it/s]

 54%|█████████████████████▋                  | 428/788 [00:19<00:16, 22.11it/s]
 55%|█████████████████████▉                  | 431/788 [00:19<00:15, 23.38it/s]

 55%|██████████████████████                  | 434/788 [00:19<00:15, 22.89it/s]
 55%|██████████████████████▏                 | 437/788 [00:19<00:15, 22.18it/s]

 56%|██████████████████████▎                 | 440/788 [00:20<00:15, 22.09it/s]
 56%|██████████████████████▍                 | 443/788 [00:20<00:15, 21.77it/s]

 57%|██████████████████████▋                 | 446/788 [00:20<00:15, 21.67it/s]
 57%|██████████████████████▊                 | 449/788 [00:20<00:14, 22.64it/s]

 57%|██████████████████████▉                 | 452/788 [00:20<00:15, 22.09it/s]
 58%|███████████████████████                 | 455/788 [00:20<00:14, 22.35it/s]

 58%|███████████████████████▏                | 458/788 [00:20<00:13, 24.02it/s]
 59%|███████████████████████▍                | 461/788 [00:20<00:14, 22.90it/s]

 59%|███████████████████████▌                | 464/788 [00:21<00:14, 22.41it/s]
 59%|███████████████████████▋                | 467/788 [00:21<00:14, 22.27it/s]

 60%|███████████████████████▊                | 470/788 [00:21<00:15, 20.67it/s]
 60%|████████████████████████                | 473/788 [00:21<00:15, 20.47it/s]

 60%|████████████████████████▏               | 476/788 [00:21<00:14, 20.86it/s]
 61%|████████████████████████▎               | 479/788 [00:21<00:14, 21.30it/s]

 61%|████████████████████████▍               | 482/788 [00:21<00:14, 21.73it/s]
 62%|████████████████████████▌               | 485/788 [00:22<00:14, 21.54it/s]

 62%|████████████████████████▊               | 488/788 [00:22<00:14, 21.36it/s]
 62%|████████████████████████▉               | 491/788 [00:22<00:14, 20.25it/s]

 63%|█████████████████████████               | 494/788 [00:22<00:14, 20.68it/s]
 63%|█████████████████████████▏              | 497/788 [00:22<00:12, 22.73it/s]

 63%|█████████████████████████▍              | 500/788 [00:22<00:12, 23.53it/s]
 64%|█████████████████████████▌              | 503/788 [00:22<00:12, 22.99it/s]

 64%|█████████████████████████▋              | 506/788 [00:22<00:11, 24.44it/s]
 65%|█████████████████████████▊              | 509/788 [00:23<00:11, 23.82it/s]

 65%|█████████████████████████▉              | 512/788 [00:23<00:11, 24.51it/s]
 65%|██████████████████████████▏             | 515/788 [00:23<00:10, 25.22it/s]

 66%|██████████████████████████▎             | 518/788 [00:23<00:11, 23.68it/s]
 66%|██████████████████████████▍             | 521/788 [00:23<00:10, 24.85it/s]

 66%|██████████████████████████▌             | 524/788 [00:23<00:10, 24.31it/s]
 67%|██████████████████████████▊             | 527/788 [00:23<00:11, 22.47it/s]

 67%|██████████████████████████▉             | 530/788 [00:24<00:11, 22.15it/s]
 68%|███████████████████████████             | 533/788 [00:24<00:11, 22.01it/s]

 68%|███████████████████████████▏            | 536/788 [00:24<00:11, 22.29it/s]
 68%|███████████████████████████▎            | 539/788 [00:24<00:11, 20.99it/s]

 69%|███████████████████████████▌            | 542/788 [00:24<00:12, 20.39it/s]
 69%|███████████████████████████▋            | 545/788 [00:24<00:12, 19.69it/s]

 69%|███████████████████████████▊            | 547/788 [00:24<00:12, 19.45it/s]
 70%|███████████████████████████▉            | 550/788 [00:25<00:11, 20.05it/s]

 70%|████████████████████████████            | 553/788 [00:25<00:11, 21.18it/s]
 71%|████████████████████████████▏           | 556/788 [00:25<00:10, 21.45it/s]

 71%|████████████████████████████▍           | 559/788 [00:25<00:10, 22.61it/s]
 71%|████████████████████████████▌           | 563/788 [00:25<00:09, 24.97it/s]

 72%|████████████████████████████▋           | 566/788 [00:25<00:09, 23.74it/s]
 72%|████████████████████████████▉           | 569/788 [00:25<00:09, 23.83it/s]

 73%|█████████████████████████████           | 572/788 [00:25<00:09, 22.41it/s]
 73%|█████████████████████████████▏          | 575/788 [00:26<00:09, 21.82it/s]

 73%|█████████████████████████████▎          | 578/788 [00:26<00:09, 21.19it/s]
 74%|█████████████████████████████▍          | 581/788 [00:26<00:09, 22.19it/s]

 74%|█████████████████████████████▋          | 584/788 [00:26<00:09, 21.05it/s]
 74%|█████████████████████████████▊          | 587/788 [00:26<00:09, 21.63it/s]

 75%|█████████████████████████████▉          | 590/788 [00:26<00:09, 21.10it/s]
 75%|██████████████████████████████          | 593/788 [00:26<00:08, 21.84it/s]

 76%|██████████████████████████████▎         | 596/788 [00:27<00:08, 22.40it/s]
 76%|██████████████████████████████▍         | 599/788 [00:27<00:08, 22.57it/s]

 76%|██████████████████████████████▌         | 602/788 [00:27<00:08, 22.52it/s]
 77%|██████████████████████████████▋         | 605/788 [00:27<00:07, 23.48it/s]

 77%|██████████████████████████████▊         | 608/788 [00:27<00:07, 23.90it/s]
 78%|███████████████████████████████         | 611/788 [00:27<00:07, 23.31it/s]

 78%|███████████████████████████████▏        | 614/788 [00:27<00:07, 24.08it/s]
 78%|███████████████████████████████▎        | 617/788 [00:27<00:07, 22.73it/s]

 79%|███████████████████████████████▍        | 620/788 [00:28<00:07, 22.80it/s]
 79%|███████████████████████████████▋        | 624/788 [00:28<00:06, 24.37it/s]

 80%|███████████████████████████████▊        | 627/788 [00:28<00:07, 22.80it/s]
 80%|███████████████████████████████▉        | 630/788 [00:28<00:07, 20.94it/s]

 80%|████████████████████████████████▏       | 633/788 [00:28<00:07, 20.96it/s]
 81%|████████████████████████████████▎       | 636/788 [00:28<00:06, 22.77it/s]

 81%|████████████████████████████████▍       | 639/788 [00:28<00:07, 21.19it/s]
 82%|████████████████████████████████▋       | 643/788 [00:29<00:06, 23.98it/s]

 82%|████████████████████████████████▊       | 646/788 [00:29<00:05, 23.76it/s]
 82%|████████████████████████████████▉       | 649/788 [00:29<00:05, 24.93it/s]

 83%|█████████████████████████████████       | 652/788 [00:29<00:05, 25.36it/s]
 83%|█████████████████████████████████▏      | 655/788 [00:29<00:05, 24.62it/s]

 84%|█████████████████████████████████▍      | 658/788 [00:29<00:05, 24.04it/s]
 84%|█████████████████████████████████▌      | 661/788 [00:29<00:05, 23.13it/s]

 84%|█████████████████████████████████▋      | 664/788 [00:29<00:05, 23.50it/s]
 85%|█████████████████████████████████▊      | 667/788 [00:30<00:05, 22.32it/s]

 85%|██████████████████████████████████      | 670/788 [00:30<00:05, 22.90it/s]
 85%|██████████████████████████████████▏     | 673/788 [00:30<00:05, 22.25it/s]

 86%|██████████████████████████████████▎     | 676/788 [00:30<00:04, 22.57it/s]
 86%|██████████████████████████████████▍     | 679/788 [00:30<00:04, 21.94it/s]

 87%|██████████████████████████████████▌     | 682/788 [00:30<00:04, 22.72it/s]
 87%|██████████████████████████████████▊     | 685/788 [00:30<00:04, 23.20it/s]

 87%|██████████████████████████████████▉     | 688/788 [00:31<00:04, 22.80it/s]
 88%|███████████████████████████████████     | 691/788 [00:31<00:04, 20.97it/s]

 88%|███████████████████████████████████▏    | 694/788 [00:31<00:04, 22.66it/s]
 88%|███████████████████████████████████▍    | 697/788 [00:31<00:03, 22.98it/s]

 89%|███████████████████████████████████▌    | 700/788 [00:31<00:03, 22.78it/s]
 89%|███████████████████████████████████▋    | 703/788 [00:31<00:03, 21.43it/s]

 90%|███████████████████████████████████▊    | 706/788 [00:31<00:04, 20.38it/s]
 90%|███████████████████████████████████▉    | 709/788 [00:32<00:03, 20.93it/s]

 90%|████████████████████████████████████▏   | 712/788 [00:32<00:03, 20.93it/s]
 91%|████████████████████████████████████▎   | 715/788 [00:32<00:03, 21.64it/s]

 91%|████████████████████████████████████▍   | 719/788 [00:32<00:03, 22.98it/s]
 92%|████████████████████████████████████▋   | 722/788 [00:32<00:02, 22.61it/s]

 92%|████████████████████████████████████▊   | 725/788 [00:32<00:02, 21.73it/s]
 92%|████████████████████████████████████▉   | 728/788 [00:32<00:02, 21.50it/s]

 93%|█████████████████████████████████████   | 731/788 [00:33<00:02, 20.79it/s]
 93%|█████████████████████████████████████▎  | 734/788 [00:33<00:02, 20.96it/s]

 94%|█████████████████████████████████████▍  | 737/788 [00:33<00:02, 20.74it/s]
 94%|█████████████████████████████████████▌  | 740/788 [00:33<00:02, 20.98it/s]

 94%|█████████████████████████████████████▋  | 743/788 [00:33<00:01, 22.90it/s]
 95%|█████████████████████████████████████▊  | 746/788 [00:33<00:01, 22.26it/s]

 95%|██████████████████████████████████████  | 749/788 [00:33<00:01, 22.62it/s]
 95%|██████████████████████████████████████▏ | 752/788 [00:34<00:01, 21.46it/s]

 96%|██████████████████████████████████████▎ | 755/788 [00:34<00:01, 21.50it/s]
 96%|██████████████████████████████████████▍ | 758/788 [00:34<00:01, 22.37it/s]

 97%|██████████████████████████████████████▋ | 761/788 [00:34<00:01, 21.95it/s]
 97%|██████████████████████████████████████▊ | 765/788 [00:34<00:00, 24.48it/s]

 97%|██████████████████████████████████████▉ | 768/788 [00:34<00:00, 22.76it/s]
 98%|███████████████████████████████████████▏| 771/788 [00:34<00:00, 23.10it/s]

 98%|███████████████████████████████████████▎| 774/788 [00:34<00:00, 24.41it/s]
 99%|███████████████████████████████████████▍| 777/788 [00:35<00:00, 22.89it/s]

 99%|███████████████████████████████████████▌| 780/788 [00:35<00:00, 24.57it/s]
 99%|███████████████████████████████████████▋| 783/788 [00:35<00:00, 24.72it/s]

100%|██████████████████████████████████| 42525/42525 [1:04:39<00:00,  9.62it/s]
100%|████████████████████████████████████████| 788/788 [00:35<00:00, 23.97it/s]

Writing model shards:   0%|                              | 0/1 [00:00<?, ?it/s]

{'eval_loss': '0.851', 'eval_accuracy': '0.6447', 'eval_macro_f1': '0.6439', 'eval_mae': '0.4033', 'eval_cil_score': '0.8992', 'eval_quadratic_weighted_kappa': '0.8715', 'eval_runtime': '35.56', 'eval_samples_per_second': '708.7', 'eval_steps_per_second': '22.16', 'epoch': '3'}

Writing model shards: 100%|██████████████████████| 1/1 [00:01<00:00,  1.34s/it]

100%|██████████████████████████████████| 42525/42525 [1:04:43<00:00,  9.62it/s]

100%|██████████████████████████████████| 42525/42525 [1:04:43<00:00, 10.95it/s]
  0%|▏                                         | 3/788 [00:00<00:30, 26.12it/s]

{'train_runtime': '3883', 'train_samples_per_second': '175.2', 'train_steps_per_second': '10.95', 'train_loss': '0.7703', 'epoch': '3'}

  1%|▍                                         | 9/788 [00:00<00:34, 22.66it/s]

  2%|▊                                        | 15/788 [00:00<00:32, 23.43it/s]

  3%|█                                        | 21/788 [00:00<00:36, 20.95it/s]

  3%|█▍                                       | 27/788 [00:01<00:36, 21.06it/s]

  4%|█▋                                       | 33/788 [00:01<00:35, 21.33it/s]

  5%|██                                       | 39/788 [00:01<00:35, 21.11it/s]

  6%|██▎                                      | 45/788 [00:02<00:31, 23.72it/s]

  6%|██▋                                      | 51/788 [00:02<00:31, 23.60it/s]

  7%|██▉                                      | 57/788 [00:02<00:31, 23.42it/s]

  8%|███▎                                     | 63/788 [00:02<00:32, 22.53it/s]

  9%|███▌                                     | 69/788 [00:03<00:32, 21.82it/s]

 10%|███▉                                     | 75/788 [00:03<00:33, 21.07it/s]

 10%|████▏                                    | 81/788 [00:03<00:34, 20.72it/s]

 11%|████▌                                    | 87/788 [00:03<00:33, 20.85it/s]

 12%|████▊                                    | 93/788 [00:04<00:34, 19.99it/s]

 13%|█████▏                                   | 99/788 [00:04<00:33, 20.63it/s]

 13%|█████▎                                  | 105/788 [00:04<00:33, 20.13it/s]

 14%|█████▋                                  | 111/788 [00:05<00:29, 22.60it/s]

 15%|█████▉                                  | 117/788 [00:05<00:31, 21.31it/s]

 16%|██████▏                                 | 123/788 [00:05<00:32, 20.69it/s]

 16%|██████▌                                 | 130/788 [00:05<00:28, 22.82it/s]

 17%|██████▉                                 | 136/788 [00:06<00:27, 23.53it/s]

 18%|███████▏                                | 142/788 [00:06<00:28, 22.62it/s]

 19%|███████▌                                | 149/788 [00:06<00:25, 25.46it/s]

 20%|███████▊                                | 155/788 [00:06<00:26, 23.84it/s]

 20%|████████▏                               | 161/788 [00:07<00:27, 22.89it/s]

 21%|████████▍                               | 167/788 [00:07<00:29, 21.31it/s]

 22%|████████▊                               | 173/788 [00:07<00:27, 22.66it/s]

 23%|█████████                               | 179/788 [00:08<00:28, 21.39it/s]

 23%|█████████▍                              | 185/788 [00:08<00:29, 20.67it/s]

 24%|█████████▋                              | 191/788 [00:08<00:29, 20.15it/s]

 25%|██████████                              | 197/788 [00:08<00:26, 22.53it/s]

 26%|██████████▎                             | 203/788 [00:09<00:26, 21.72it/s]

 27%|██████████▌                             | 209/788 [00:09<00:25, 22.52it/s]

 27%|██████████▉                             | 215/788 [00:09<00:26, 21.89it/s]

 28%|███████████▏                            | 221/788 [00:10<00:25, 22.47it/s]

 29%|███████████▌                            | 227/788 [00:10<00:23, 23.55it/s]

 30%|███████████▊                            | 233/788 [00:10<00:23, 23.79it/s]

 30%|████████████▏                           | 239/788 [00:10<00:23, 22.96it/s]

 31%|████████████▍                           | 245/788 [00:11<00:25, 21.66it/s]

 32%|████████████▋                           | 251/788 [00:11<00:25, 21.47it/s]

 33%|█████████████                           | 257/788 [00:11<00:24, 21.90it/s]

 33%|█████████████▎                          | 263/788 [00:11<00:24, 21.10it/s]

 34%|█████████████▋                          | 269/788 [00:12<00:24, 20.89it/s]

 35%|█████████████▉                          | 275/788 [00:12<00:25, 20.05it/s]

 36%|██████████████▏                         | 280/788 [00:12<00:26, 18.99it/s]

 36%|██████████████▌                         | 286/788 [00:13<00:23, 21.29it/s]

 37%|██████████████▊                         | 293/788 [00:13<00:20, 23.91it/s]

 38%|███████████████▏                        | 299/788 [00:13<00:20, 23.43it/s]

 39%|███████████████▍                        | 305/788 [00:13<00:21, 22.92it/s]

 39%|███████████████▊                        | 311/788 [00:14<00:20, 22.77it/s]

 40%|████████████████                        | 317/788 [00:14<00:19, 23.57it/s]

 41%|████████████████▍                       | 323/788 [00:14<00:20, 22.92it/s]

 42%|████████████████▋                       | 329/788 [00:14<00:22, 20.52it/s]

 43%|█████████████████                       | 335/788 [00:15<00:19, 23.01it/s]

 43%|█████████████████▎                      | 341/788 [00:15<00:20, 21.86it/s]

 44%|█████████████████▌                      | 347/788 [00:15<00:22, 19.27it/s]

 45%|█████████████████▉                      | 353/788 [00:16<00:20, 21.40it/s]

 46%|██████████████████▏                     | 359/788 [00:16<00:19, 21.79it/s]

 46%|██████████████████▌                     | 365/788 [00:16<00:17, 23.53it/s]

 47%|██████████████████▊                     | 371/788 [00:16<00:16, 24.95it/s]

 48%|███████████████████▏                    | 377/788 [00:17<00:15, 26.00it/s]

 49%|███████████████████▍                    | 383/788 [00:17<00:15, 25.47it/s]

 49%|███████████████████▋                    | 389/788 [00:17<00:17, 23.32it/s]

 50%|████████████████████                    | 395/788 [00:17<00:17, 22.87it/s]

 51%|████████████████████▎                   | 401/788 [00:18<00:16, 23.11it/s]

 52%|████████████████████▋                   | 407/788 [00:18<00:15, 24.27it/s]

 52%|████████████████████▉                   | 413/788 [00:18<00:15, 24.17it/s]

 53%|█████████████████████▎                  | 419/788 [00:18<00:17, 21.59it/s]

 54%|█████████████████████▌                  | 425/788 [00:19<00:16, 21.50it/s]

 55%|█████████████████████▉                  | 431/788 [00:19<00:15, 23.61it/s]

 55%|██████████████████████▏                 | 437/788 [00:19<00:15, 22.55it/s]

 56%|██████████████████████▍                 | 443/788 [00:19<00:15, 21.82it/s]

 57%|██████████████████████▊                 | 449/788 [00:20<00:14, 22.92it/s]

 58%|███████████████████████                 | 455/788 [00:20<00:14, 22.35it/s]

 59%|███████████████████████▍                | 461/788 [00:20<00:14, 22.82it/s]

 59%|███████████████████████▋                | 467/788 [00:21<00:14, 22.40it/s]

 60%|████████████████████████                | 473/788 [00:21<00:15, 20.49it/s]

 61%|████████████████████████▎               | 479/788 [00:21<00:14, 21.46it/s]

 62%|████████████████████████▌               | 485/788 [00:21<00:14, 21.58it/s]

 62%|████████████████████████▉               | 491/788 [00:22<00:14, 20.34it/s]

 63%|█████████████████████████▏              | 497/788 [00:22<00:12, 22.82it/s]

 64%|█████████████████████████▌              | 503/788 [00:22<00:12, 22.91it/s]

 65%|█████████████████████████▊              | 509/788 [00:22<00:11, 24.03it/s]

 65%|██████████████████████████▏             | 515/788 [00:23<00:10, 25.25it/s]

 66%|██████████████████████████▍             | 521/788 [00:23<00:10, 24.92it/s]

 67%|██████████████████████████▊             | 527/788 [00:23<00:11, 22.56it/s]

 68%|███████████████████████████             | 533/788 [00:23<00:11, 22.05it/s]

 68%|███████████████████████████▎            | 539/788 [00:24<00:11, 21.13it/s]

 69%|███████████████████████████▋            | 545/788 [00:24<00:12, 19.74it/s]

 70%|███████████████████████████▉            | 550/788 [00:24<00:11, 20.25it/s]

 71%|████████████████████████████▏           | 556/788 [00:25<00:10, 21.54it/s]

 71%|████████████████████████████▌           | 563/788 [00:25<00:08, 25.16it/s]

 72%|████████████████████████████▉           | 569/788 [00:25<00:09, 24.03it/s]

 73%|█████████████████████████████▏          | 575/788 [00:25<00:09, 21.95it/s]

 74%|█████████████████████████████▍          | 581/788 [00:26<00:09, 22.37it/s]

 74%|█████████████████████████████▊          | 587/788 [00:26<00:09, 21.73it/s]

 75%|██████████████████████████████          | 593/788 [00:26<00:08, 21.99it/s]

 76%|██████████████████████████████▍         | 599/788 [00:26<00:08, 22.59it/s]

 77%|██████████████████████████████▋         | 605/788 [00:27<00:07, 23.48it/s]

 78%|███████████████████████████████         | 611/788 [00:27<00:07, 23.34it/s]

 78%|███████████████████████████████▎        | 617/788 [00:27<00:07, 22.76it/s]

 79%|███████████████████████████████▋        | 624/788 [00:28<00:06, 24.47it/s]

 80%|███████████████████████████████▉        | 630/788 [00:28<00:07, 21.03it/s]

 81%|████████████████████████████████▎       | 636/788 [00:28<00:06, 22.89it/s]

 82%|████████████████████████████████▋       | 643/788 [00:28<00:06, 24.00it/s]

 82%|████████████████████████████████▉       | 649/788 [00:29<00:05, 24.94it/s]

 83%|█████████████████████████████████▏      | 655/788 [00:29<00:05, 24.50it/s]

 84%|█████████████████████████████████▌      | 661/788 [00:29<00:05, 23.13it/s]

 85%|█████████████████████████████████▊      | 667/788 [00:29<00:05, 22.23it/s]

 85%|██████████████████████████████████▏     | 673/788 [00:30<00:05, 22.14it/s]

 86%|██████████████████████████████████▍     | 679/788 [00:30<00:04, 21.97it/s]

 87%|██████████████████████████████████▊     | 685/788 [00:30<00:04, 22.81it/s]

 88%|███████████████████████████████████     | 691/788 [00:30<00:04, 20.86it/s]

 88%|███████████████████████████████████▍    | 697/788 [00:31<00:03, 22.83it/s]

 89%|███████████████████████████████████▋    | 703/788 [00:31<00:03, 21.40it/s]

 90%|███████████████████████████████████▉    | 709/788 [00:31<00:03, 20.98it/s]

 91%|████████████████████████████████████▎   | 715/788 [00:32<00:03, 22.75it/s]

 92%|████████████████████████████████████▋   | 722/788 [00:32<00:02, 23.38it/s]

 92%|████████████████████████████████████▉   | 728/788 [00:32<00:02, 21.75it/s]

 93%|█████████████████████████████████████▎  | 734/788 [00:32<00:02, 21.19it/s]

 94%|█████████████████████████████████████▌  | 740/788 [00:33<00:02, 21.06it/s]

 95%|█████████████████████████████████████▊  | 746/788 [00:33<00:01, 22.41it/s]

 95%|██████████████████████████████████████▏ | 752/788 [00:33<00:01, 21.60it/s]

 96%|██████████████████████████████████████▍ | 758/788 [00:34<00:01, 22.34it/s]

 97%|██████████████████████████████████████▊ | 765/788 [00:34<00:00, 24.59it/s]

 98%|███████████████████████████████████████▏| 771/788 [00:34<00:00, 22.93it/s]

 99%|███████████████████████████████████████▍| 777/788 [00:34<00:00, 22.97it/s]

 99%|███████████████████████████████████████▊| 784/788 [00:35<00:00, 24.44it/s]

100%|████████████████████████████████████████| 788/788 [00:35<00:00, 22.35it/s]
Writing model shards:   0%|                              | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|██████████████████████| 1/1 [00:01<00:00,  1.32s/it]

Wrote experiments/transformers/20260521_115409_TRANSFORMER_BASELINES/nlptown__bert-base-multilingual-uncased-sentiment__fine_tuned/transformer_results.csv
Wrote experiments/transformers/20260521_115409_TRANSFORMER_BASELINES/nlptown__bert-base-multilingual-uncased-sentiment__fine_tuned/transformer_best_by_family.csv
Wrote experiments/transformers/20260521_115409_TRANSFORMER_BASELINES/nlptown__bert-base-multilingual-uncased-sentiment__fine_tuned/transformer_epoch_history.csv
[ok] transformer__nlptown__bert-base-multilingual-uncased-sentiment__fine_tuned: best_epoch=3.0 score=0.89919 mae=0.40325 acc=0.64468 macro_f1=0.64391

/cluster/courses/cil/envs/envs/text-5060/bin/python -m baselines.train_review_model --model-name nlptown/bert-base-multilingual-uncased-sentiment --experiment-name transformer__nlptown__bert-base-multilingual-uncased-sentiment__eval_only --train-path data/train.csv --output-dir experiments/transformers/20260521_115409_TRANSFORMER_BASELINES/nlptown__bert-base-multilingual-uncased-sentiment__eval_only --validation-size 0.1 --random-state 42 --max-length 256 --epochs 3 --batch-size 16 --eval-batch-size 32 --learning-rate 2e-05 --weight-decay 0.01 --eval-only --fp16

Model: nlptown/bert-base-multilingual-uncased-sentiment
Variant: eval_only
Train examples: 226800
Validation examples: 25200
Class counts: {0: 45360, 1: 45360, 2: 45360, 3: 45360, 4: 45360}

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights: 100%|█████████████████████| 201/201 [00:00<00:00, 7568.36it/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

  0%|▏                                         | 3/788 [00:00<00:30, 25.93it/s]

  1%|▍                                         | 9/788 [00:00<00:33, 23.04it/s]

  2%|▊                                        | 16/788 [00:00<00:32, 23.43it/s]

  3%|█▏                                       | 22/788 [00:00<00:35, 21.40it/s]

  4%|█▍                                       | 28/788 [00:01<00:34, 22.26it/s]

  4%|█▊                                       | 34/788 [00:01<00:35, 21.15it/s]

  5%|██                                       | 40/788 [00:01<00:34, 21.65it/s]

  6%|██▍                                      | 46/788 [00:02<00:32, 22.71it/s]

  7%|██▊                                      | 53/788 [00:02<00:29, 24.72it/s]

  7%|███                                      | 59/788 [00:02<00:29, 24.33it/s]

  8%|███▍                                     | 65/788 [00:02<00:31, 22.81it/s]

  9%|███▋                                     | 71/788 [00:03<00:33, 21.46it/s]

 10%|████                                     | 77/788 [00:03<00:33, 21.46it/s]

 11%|████▎                                    | 83/788 [00:03<00:33, 20.84it/s]

 11%|████▋                                    | 89/788 [00:04<00:33, 21.03it/s]

 12%|████▉                                    | 95/788 [00:04<00:33, 20.63it/s]

 13%|█████▏                                  | 101/788 [00:04<00:31, 21.63it/s]

 14%|█████▍                                  | 107/788 [00:04<00:33, 20.47it/s]

 14%|█████▋                                  | 113/788 [00:05<00:28, 23.59it/s]

 15%|██████                                  | 119/788 [00:05<00:32, 20.87it/s]

 16%|██████▎                                 | 125/788 [00:05<00:30, 21.97it/s]

 17%|██████▋                                 | 131/788 [00:05<00:28, 23.00it/s]

 17%|██████▉                                 | 137/788 [00:06<00:28, 22.94it/s]

 18%|███████▎                                | 143/788 [00:06<00:29, 21.95it/s]

 19%|███████▌                                | 150/788 [00:06<00:24, 25.77it/s]

 20%|███████▉                                | 156/788 [00:07<00:26, 24.00it/s]

 21%|████████▏                               | 162/788 [00:07<00:28, 22.25it/s]

 21%|████████▌                               | 168/788 [00:07<00:28, 21.87it/s]

 22%|████████▊                               | 174/788 [00:07<00:26, 23.14it/s]

 23%|█████████▏                              | 180/788 [00:08<00:28, 21.05it/s]

 24%|█████████▍                              | 186/788 [00:08<00:29, 20.23it/s]

 24%|█████████▋                              | 192/788 [00:08<00:29, 20.10it/s]

 25%|██████████                              | 198/788 [00:08<00:26, 22.01it/s]

 26%|██████████▎                             | 204/788 [00:09<00:26, 22.40it/s]

 27%|██████████▋                             | 210/788 [00:09<00:25, 22.59it/s]

 27%|██████████▉                             | 216/788 [00:09<00:26, 21.35it/s]

 28%|███████████▎                            | 222/788 [00:10<00:25, 22.63it/s]

 29%|███████████▌                            | 228/788 [00:10<00:23, 24.02it/s]

 30%|███████████▉                            | 234/788 [00:10<00:23, 23.82it/s]

 30%|████████████▏                           | 240/788 [00:10<00:23, 23.32it/s]

 31%|████████████▍                           | 246/788 [00:11<00:25, 21.33it/s]

 32%|████████████▊                           | 252/788 [00:11<00:24, 21.75it/s]

 33%|█████████████                           | 258/788 [00:11<00:25, 20.96it/s]

 34%|█████████████▍                          | 264/788 [00:11<00:24, 21.56it/s]

 34%|█████████████▋                          | 270/788 [00:12<00:24, 21.20it/s]

 35%|██████████████                          | 276/788 [00:12<00:26, 19.48it/s]

 36%|██████████████▏                         | 280/788 [00:12<00:26, 18.89it/s]

 36%|██████████████▌                         | 286/788 [00:12<00:23, 21.42it/s]

 37%|██████████████▊                         | 293/788 [00:13<00:20, 24.02it/s]

 38%|███████████████▏                        | 299/788 [00:13<00:20, 23.41it/s]

 39%|███████████████▍                        | 305/788 [00:13<00:20, 23.11it/s]

 39%|███████████████▊                        | 311/788 [00:14<00:20, 22.83it/s]

 40%|████████████████                        | 317/788 [00:14<00:19, 23.71it/s]

 41%|████████████████▍                       | 323/788 [00:14<00:20, 23.19it/s]

 42%|████████████████▋                       | 329/788 [00:14<00:20, 22.17it/s]

 43%|█████████████████                       | 336/788 [00:15<00:18, 24.21it/s]

 43%|█████████████████▎                      | 342/788 [00:15<00:20, 22.25it/s]

 44%|█████████████████▋                      | 348/788 [00:15<00:21, 20.08it/s]

 45%|█████████████████▉                      | 354/788 [00:16<00:20, 21.36it/s]

 46%|██████████████████▎                     | 360/788 [00:16<00:19, 22.36it/s]

 46%|██████████████████▌                     | 366/788 [00:16<00:17, 23.68it/s]

 47%|██████████████████▉                     | 372/788 [00:16<00:16, 24.58it/s]

 48%|███████████████████▏                    | 378/788 [00:16<00:15, 26.37it/s]

 49%|███████████████████▍                    | 384/788 [00:17<00:15, 25.39it/s]

 49%|███████████████████▊                    | 390/788 [00:17<00:17, 22.63it/s]

 50%|████████████████████                    | 396/788 [00:17<00:16, 23.73it/s]

 51%|████████████████████▍                   | 402/788 [00:18<00:16, 23.40it/s]

 52%|████████████████████▋                   | 408/788 [00:18<00:16, 23.55it/s]

 53%|█████████████████████                   | 415/788 [00:18<00:14, 25.41it/s]

 53%|█████████████████████▎                  | 421/788 [00:18<00:17, 21.24it/s]

 54%|█████████████████████▋                  | 427/788 [00:19<00:16, 21.65it/s]

 55%|█████████████████████▉                  | 433/788 [00:19<00:14, 24.33it/s]

 56%|██████████████████████▎                 | 439/788 [00:19<00:15, 22.32it/s]

 56%|██████████████████████▌                 | 445/788 [00:19<00:15, 21.98it/s]

 57%|██████████████████████▉                 | 451/788 [00:20<00:14, 22.94it/s]

 58%|███████████████████████▏                | 457/788 [00:20<00:14, 23.46it/s]

 59%|███████████████████████▌                | 463/788 [00:20<00:14, 22.21it/s]

 60%|███████████████████████▊                | 469/788 [00:20<00:14, 21.69it/s]

 60%|████████████████████████                | 475/788 [00:21<00:14, 21.21it/s]

 61%|████████████████████████▍               | 481/788 [00:21<00:13, 22.29it/s]

 62%|████████████████████████▋               | 487/788 [00:21<00:13, 21.95it/s]

 63%|█████████████████████████               | 493/788 [00:22<00:14, 20.88it/s]

 63%|█████████████████████████▎              | 499/788 [00:22<00:12, 23.46it/s]

 64%|█████████████████████████▋              | 505/788 [00:22<00:11, 23.67it/s]

 65%|█████████████████████████▉              | 511/788 [00:22<00:11, 23.95it/s]

 66%|██████████████████████████▏             | 517/788 [00:23<00:11, 24.16it/s]

 66%|██████████████████████████▌             | 523/788 [00:23<00:10, 24.50it/s]

 67%|██████████████████████████▊             | 529/788 [00:23<00:11, 23.05it/s]

 68%|███████████████████████████▏            | 535/788 [00:23<00:11, 22.95it/s]

 69%|███████████████████████████▍            | 541/788 [00:24<00:12, 20.30it/s]

 69%|███████████████████████████▊            | 547/788 [00:24<00:12, 19.66it/s]

 70%|████████████████████████████            | 553/788 [00:24<00:11, 21.29it/s]

 71%|████████████████████████████▍           | 559/788 [00:25<00:10, 22.70it/s]

 72%|████████████████████████████▋           | 566/788 [00:25<00:09, 24.02it/s]

 73%|█████████████████████████████           | 572/788 [00:25<00:09, 22.51it/s]

 73%|█████████████████████████████▎          | 578/788 [00:25<00:09, 21.40it/s]

 74%|█████████████████████████████▋          | 584/788 [00:26<00:09, 21.22it/s]

 75%|█████████████████████████████▉          | 590/788 [00:26<00:09, 21.35it/s]

 76%|██████████████████████████████▎         | 596/788 [00:26<00:08, 22.60it/s]

 76%|██████████████████████████████▌         | 602/788 [00:26<00:08, 22.64it/s]

 77%|██████████████████████████████▊         | 608/788 [00:27<00:07, 24.12it/s]

 78%|███████████████████████████████▏        | 614/788 [00:27<00:07, 24.13it/s]

 79%|███████████████████████████████▍        | 620/788 [00:27<00:07, 22.91it/s]

 80%|███████████████████████████████▊        | 627/788 [00:27<00:06, 23.01it/s]

 80%|████████████████████████████████▏       | 633/788 [00:28<00:07, 21.09it/s]

 81%|████████████████████████████████▍       | 639/788 [00:28<00:07, 21.27it/s]

 82%|████████████████████████████████▊       | 646/788 [00:28<00:05, 23.87it/s]

 83%|█████████████████████████████████       | 652/788 [00:29<00:05, 25.60it/s]

 84%|█████████████████████████████████▍      | 658/788 [00:29<00:05, 24.06it/s]

 84%|█████████████████████████████████▋      | 664/788 [00:29<00:05, 23.59it/s]

 85%|██████████████████████████████████      | 670/788 [00:29<00:05, 22.81it/s]

 86%|██████████████████████████████████▎     | 676/788 [00:30<00:04, 22.59it/s]

 87%|██████████████████████████████████▌     | 682/788 [00:30<00:04, 22.77it/s]

 87%|██████████████████████████████████▉     | 688/788 [00:30<00:04, 22.84it/s]

 88%|███████████████████████████████████▏    | 694/788 [00:30<00:04, 22.76it/s]

 89%|███████████████████████████████████▌    | 700/788 [00:31<00:03, 22.67it/s]

 90%|███████████████████████████████████▊    | 706/788 [00:31<00:04, 20.50it/s]

 90%|████████████████████████████████████▏   | 712/788 [00:31<00:03, 21.01it/s]

 91%|████████████████████████████████████▍   | 719/788 [00:32<00:02, 24.04it/s]

 92%|████████████████████████████████████▊   | 725/788 [00:32<00:02, 22.24it/s]

 93%|█████████████████████████████████████   | 731/788 [00:32<00:02, 21.04it/s]

 94%|█████████████████████████████████████▍  | 737/788 [00:32<00:02, 20.99it/s]

 94%|█████████████████████████████████████▋  | 743/788 [00:33<00:01, 22.89it/s]

 95%|██████████████████████████████████████  | 749/788 [00:33<00:01, 21.53it/s]

 96%|██████████████████████████████████████▎ | 755/788 [00:33<00:01, 20.96it/s]

 97%|██████████████████████████████████████▋ | 761/788 [00:34<00:01, 21.78it/s]

 97%|██████████████████████████████████████▉ | 768/788 [00:34<00:00, 22.67it/s]

 98%|███████████████████████████████████████▎| 774/788 [00:34<00:00, 24.27it/s]

 99%|███████████████████████████████████████▌| 780/788 [00:34<00:00, 24.62it/s]

100%|███████████████████████████████████████▉| 786/788 [00:35<00:00, 23.84it/s]

100%|████████████████████████████████████████| 788/788 [00:35<00:00, 22.45it/s]

Wrote experiments/transformers/20260521_115409_TRANSFORMER_BASELINES/nlptown__bert-base-multilingual-uncased-sentiment__eval_only/transformer_results.csv
Wrote experiments/transformers/20260521_115409_TRANSFORMER_BASELINES/nlptown__bert-base-multilingual-uncased-sentiment__eval_only/transformer_best_by_family.csv
Wrote experiments/transformers/20260521_115409_TRANSFORMER_BASELINES/nlptown__bert-base-multilingual-uncased-sentiment__eval_only/transformer_epoch_history.csv
[ok] transformer__nlptown__bert-base-multilingual-uncased-sentiment__eval_only: best_epoch=0.0 score=0.89336 mae=0.42655 acc=0.63401 macro_f1=0.62847

[{'model_name': 'microsoft/deberta-v3-base',
  'variant': 'fine_tuned',
  'run_name': 'microsoft__deberta-v3-base__fine_tuned',
  'run_dir': PosixPath('experiments/transformers/20260521_115409_TRANSFORMER_BASELINES/microsoft__deberta-v3-base__fine_tuned')},
 {'model_name': 'nlptown/bert-base-multilingual-uncased-sentiment',
  'variant': 'fine_tuned',
  'run_name': 'nlptown__bert-base-multilingual-uncased-sentiment__fine_tuned',
  'run_dir': PosixPath('experiments/transformers/20260521_115409_TRANSFORMER_BASELINES/nlptown__bert-base-multilingual-uncased-sentiment__fine_tuned')},
 {'model_name': 'nlptown/bert-base-multilingual-uncased-sentiment',
  'variant': 'eval_only',
  'run_name': 'nlptown__bert-base-multilingual-uncased-sentiment__eval_only',
  'run_dir': PosixPath('experiments/transformers/20260521_115409_TRANSFORMER_BASELINES/nlptown__bert-base-multilingual-uncased-sentiment__eval_only')}]

## Total Analysis

In [4]:
result_frames = []
for run in completed_runs:
    result_frames.append(pd.read_csv(run["run_dir"] / "transformer_results.csv"))

results = pd.concat(result_frames, ignore_index=True)
total_results = results.sort_values(
    ["status", "cil_score"], ascending=[False, False]
).reset_index(drop=True)
total_results.to_csv(EXPERIMENT_DIR / "total_analysis.csv", index=False)
total_results

,experiment,family,model,variant,status,best_epoch,best_epoch_train_loss,best_epoch_val_loss,train_seconds,eval_seconds,accuracy,macro_f1,mae,cil_score,quadratic_weighted_kappa,notes
0,transformer__nlptown__bert-base-multilingual-u...,transformer,nlptown/bert-base-multilingual-uncased-sentiment,fine_tuned,ok,3.0,0.680230,0.850999,3884.967314,35.298712,0.644683,0.643910,0.403254,0.899187,0.871509,Final eval score=0.89919
1,transformer__nlptown__bert-base-multilingual-u...,transformer,nlptown/bert-base-multilingual-uncased-sentiment,eval_only,ok,0.0,NaN,0.836051,0.000000,35.693490,0.634008,0.628472,0.426548,0.893363,0.863253,Final eval score=0.89336
2,transformer__microsoft__deberta-v3-base__fine_...,transformer,microsoft/deberta-v3-base,fine_tuned,ok,1.0,1.614795,NaN,4930.337912,63.419465,0.200000,0.066667,2.000000,0.500000,0.000000,Final eval score=0.50000

## Report Analysis

In [5]:
ok_results = results[results["status"] == "ok"].copy()
report_results = (
    ok_results.sort_values("cil_score", ascending=False)
    .groupby(["model", "variant"], as_index=False)
    .first()
    .sort_values("cil_score", ascending=False)
    .reset_index(drop=True)
)
report_results.to_csv(EXPERIMENT_DIR / "report_analysis.csv", index=False)
report_results

,model,variant,experiment,family,status,best_epoch,best_epoch_train_loss,best_epoch_val_loss,train_seconds,eval_seconds,accuracy,macro_f1,mae,cil_score,quadratic_weighted_kappa,notes
0,nlptown/bert-base-multilingual-uncased-sentiment,fine_tuned,transformer__nlptown__bert-base-multilingual-u...,transformer,ok,3.0,0.680230,0.850999,3884.967314,35.298712,0.644683,0.643910,0.403254,0.899187,0.871509,Final eval score=0.89919
1,nlptown/bert-base-multilingual-uncased-sentiment,eval_only,transformer__nlptown__bert-base-multilingual-u...,transformer,ok,0.0,NaN,0.836051,0.000000,35.693490,0.634008,0.628472,0.426548,0.893363,0.863253,Final eval score=0.89336
2,microsoft/deberta-v3-base,fine_tuned,transformer__microsoft__deberta-v3-base__fine_...,transformer,ok,1.0,1.614795,NaN,4930.337912,63.419465,0.200000,0.066667,2.000000,0.500000,0.000000,Final eval score=0.50000

## Epoch History

In [6]:
history_frames = []
for run in completed_runs:
    history_frames.append(pd.read_csv(run["run_dir"] / "transformer_epoch_history.csv"))

epoch_history = pd.concat(history_frames, ignore_index=True)
epoch_history = epoch_history.sort_values(["experiment", "epoch"]).reset_index(drop=True)
epoch_history.to_csv(EXPERIMENT_DIR / "epoch_analysis.csv", index=False)
epoch_history

,experiment,epoch,train_loss,val_loss,accuracy,macro_f1,mae,cil_score,quadratic_weighted_kappa
0,transformer__microsoft__deberta-v3-base__fine_...,1.0,1.614795,NaN,0.200000,0.066667,2.000000,0.500000,0.000000
1,transformer__microsoft__deberta-v3-base__fine_...,2.0,0.000000,NaN,0.200000,0.066667,2.000000,0.500000,0.000000
2,transformer__microsoft__deberta-v3-base__fine_...,3.0,0.000000,NaN,0.200000,0.066667,2.000000,0.500000,0.000000
3,transformer__nlptown__bert-base-multilingual-u...,0.0,NaN,0.836051,0.634008,0.628472,0.426548,0.893363,0.863253
4,transformer__nlptown__bert-base-multilingual-u...,1.0,0.858159,0.834058,0.636905,0.639880,0.408333,0.897917,0.866883
5,transformer__nlptown__bert-base-multilingual-u...,2.0,0.772469,0.813666,0.646746,0.644559,0.403373,0.899157,0.871656
6,transformer__nlptown__bert-base-multilingual-u...,3.0,0.680230,0.850999,0.644683,0.643910,0.403254,0.899187,0.871509